// data_194_202.js - පිටු 194 සිට 202 දක්වා සියලුම වචන
const data_extra_194_202 = [
  // --- පිටුව 194 ---
  { "word": "චූර්ණ", "meaning": "හුණු, අළුහුණු", "category": "treatment" },
  { "word": "චූර්ණිඵල", "meaning": "හුනෙන් ගන්නා ජලය හෝ පිළිස්සුණු හුණුගල් රත් කලකට වතුර බෝතල දෙකක් දමා දියකොට තැන්වලට තබා පෙරා ගන්නා ජලය", "category": "treatment" },
  { "word": "චූර්ණිපාද", "meaning": "සාදිලිංගම්", "category": "treatment" },
  { "word": "චූර්නත", "meaning": "රෝග විශේෂයක්", "category": "symptom" },
  { "word": "වෙගලඹක්", "meaning": "වල් මුරුංගා, මුරුංගා", "category": "plant" },
  { "word": "වෙගලපල්ලව", "meaning": "මුරුංගා", "category": "plant" },
  { "word": "වෙතකී", "meaning": "ඉඟිනි, අරළු, දෑසමන්", "category": "plant" },
  { "word": "වෙතන", "meaning": "ඉඟිනි", "category": "plant" },
  { "word": "වෙතනකී", "meaning": "අරළු ගෙඩි, ඉඟිනි ඇට", "category": "plant" },
  { "word": "වෙතනිකා", "meaning": "අරළු", "category": "plant" },
  { "word": "වෙතනිය", "meaning": "ඉඟිනි", "category": "plant" },
  { "word": "වෙතනියා", "meaning": "ඹසබිය (ඍෂභක-අෂ්ටක වර්ගයේ බෙහෙත්)", "category": "plant" },
  { "word": "වෙනි", "meaning": "පිච්ච මල්", "category": "plant" },
  { "word": "වෙනිකා", "meaning": "දෑසමන්", "category": "plant" },
  { "word": "වෙනිපුප්", "meaning": "පිච්ච මල්", "category": "plant" },
  { "word": "වෙනිමාල", "meaning": "රක්මල්", "category": "plant" },
  { "word": "වෙනිමාල පුෂ්ප", "meaning": "රක්මල්", "category": "plant" },
  { "word": "වෙල", "meaning": "රේදි", "category": "plant" },
  { "word": "වෙලොත", "meaning": "පත්තක්කා", "category": "plant" },
  { "word": "වෛතස", "meaning": "බෝගස", "category": "plant" },
  { "word": "වෛතසක", "meaning": "බෝගස", "category": "plant" },
  { "word": "වෛතසතරු", "meaning": "බෝගස", "category": "plant" },
  { "word": "වෛතසද්‍රැම", "meaning": "බෝගස", "category": "plant" },
  { "word": "වෛතසවාක්‍ෂ", "meaning": "බෝගස, අඹ ගස, ඇසතු ගස", "category": "plant" },
  { "word": "වෛවගුල", "meaning": "කපුරු", "category": "plant" },
  { "word": "චොකා", "meaning": "රක්ගොකටු මුල්", "category": "plant" },
  { "word": "චොබ", "meaning": "රක් ගොකටු මුල්", "category": "plant" },
  { "word": "චොව", "meaning": "කුරුඳු පොතු, ඇටකෙසෙල්", "category": "plant" },
  { "word": "චොව පාත", "meaning": "ඇටකෙසෙල් පැන්", "category": "treatment" },
  { "word": "චොවසුන්මිය", "meaning": "කුරුඳු, තුන්පත් අකුරුඳු දේවගය හෝ කෙසෙල් දේවගය", "category": "plant" },
  { "word": "චොඩා", "meaning": "මහ මුඩමහණ", "category": "plant" },
  { "word": "චොතක", "meaning": "වෑහෑරිය, කුරුඳුපොතු", "category": "plant" },
  { "word": "චොදතික", "meaning": "බැබිල, සුළු බැබිල", "category": "plant" },
  { "word": "චොපව්ති", "meaning": "සීනඅල", "category": "plant" },
  { "word": "චොබවීත", "meaning": "සීනල, චීනල (චීනඅල)", "category": "plant" },
  { "word": "චොරා", "meaning": "හිඟුරුපියලි, සුලුපෝටා, සුලුබැබිල", "category": "plant" },
  { "word": "චොරක", "meaning": "හිඟුරා, හරංකහ, විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "චොරකපතු", "meaning": "කැළගස", "category": "plant" },
  { "word": "චොරතා", "meaning": "විෂ්ණුක්‍රාන්ති, හරංකහ, හිඟුරුපියලි", "category": "plant" },
  { "word": "චොරකී", "meaning": "සිහින් නාරං", "category": "plant" },
  { "word": "චොරනාලිකා", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "චොරපුෂ්ප", "meaning": "විෂ්ණුක්‍රාන්ති, වල්දෙහි, යක්බේරිය, හිඟුරුපියලි, මදටිය, මාරා, තුත්තිරි", "category": "plant" },
  { "word": "චොරභාණ්ඩිකා", "meaning": "වම්බොටු", "category": "plant" },
  { "word": "චොරල", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "චොරසුන්සි", "meaning": "ශෙවතකින්නි (එලකටරොලු)", "category": "plant" },
  { "word": "චොරෂ්ටි", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "චොරස්නායු", "meaning": "කාකනාසා, එල බුලත්", "category": "plant" },
  { "word": "චොරා", "meaning": "හබනගිරිය", "category": "plant" },
  { "word": "චොලකින්", "meaning": "කාරංගස", "category": "plant" },
  { "word": "චොලකි", "meaning": "සිහින්නාරං, කිමිල්", "category": "plant" },
  { "word": "චොහාර", "meaning": "කෘමිගස්තෘ", "category": "plant" },

  // --- පිටුව 195 ---
  {
    "word": "චෞචෞ",
    "meaning": "ලබු වගියට අයත් මෙම වැල්වල සෑදෙන ගෙඩි පැසුන විට ගෙඩිය වැලේ තිබියදීම එහි තිබෙන එකම ඇටයත් වැලක් පැලවී පිටතට ඇදී යයි. මේ ගෙඩිවල යුෂ මූත්‍ර කෘච්ඡ්‍රයට ප්‍රත්‍යක්ෂ යි.",
    "category": "plant"
  },
  { "word": "චෞර", "meaning": "රිදීහුනු", "category": "treatment" },
  { "word": "චෞරපුෂ්පොෂධී", "meaning": "ග්‍රන්ථිපර්ණී", "category": "plant" },
  { "word": "චෞර", "meaning": "වාක්‍ෂය", "category": "treatment" },
  { "word": "ච්‍යුත", "meaning": "අඹගස", "category": "plant" },
  { "word": "ඡකණී", "meaning": "ගොම", "category": "treatment" },
  { "word": "ඡගල", "meaning": "ගිරිනිල්ල (මාබණ්ඩා) ගෝනකොළ", "category": "plant" },
  { "word": "ඡගලාන්ත්‍රී", "meaning": "ගිරිනිල්ල, පුවක්ගස,", "category": "plant" },
  { "word": "ඡටාඵල", "meaning": "පුවක්ගස, පොල්ගස, හල්ගස", "category": "plant" },
  { "word": "ඡත්‍රිමිකා", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "ඡත්‍ර", "meaning": "ගැටකුඹ, කඳුරු, හොර, (සරල) රතු ඉකිරි", "category": "plant" },
  { "word": "ඡත්‍රක", "meaning": "කොත්තඹුරු, (කොත්තමල්ලි) ගැටතුඹ", "category": "plant" },
  { "word": "ඡත්‍රකී", "meaning": "අරත්ත, කලුබාවැල්", "category": "plant" },
  { "word": "ඡත්‍රදානය", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ඡත්‍රපතු", "meaning": "කරගස, රක්අත්තන", "category": "plant" },
  { "word": "ඡත්‍රපත්‍රක", "meaning": "බුත්පත්, රක්අත්තන", "category": "plant" },
  { "word": "ඡත්‍රපර්ණී", "meaning": "රක්අත්තන, පුලිල, කරගස", "category": "plant" },
  { "word": "ඡත්‍රපර්විකා", "meaning": "සිරස්ස", "category": "plant" },
  { "word": "ඡත්‍රපුෂ්ප", "meaning": "මදටිය, මාරා, රක්අත්තන", "category": "plant" },
  { "word": "ඡත්‍රපුෂ්පී", "meaning": "මහ හාතාවාරිය", "category": "plant" },
  { "word": "ඡත්‍රයෝගි", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "ඡත්‍රව්‍ය", "meaning": "දේවදාර", "category": "plant" },
  { "word": "ඡත්‍රවෘක්‍ෂ", "meaning": "මුචුකුන්ද වාක්‍ෂය", "category": "plant" },
  { "word": "ඡත්‍රා", "meaning": "කොත්තඹුරු, (කොත්තමල්ලි) ගතපුෂ්ප, කඳුරු, පත්පාඩගම්, සිරස්ස, දේවදාර", "category": "plant" },
  { "word": "ඡත්‍රාක", "meaning": "නෙල්ලි, සිනියා ගස", "category": "plant" },
  { "word": "ඡත්‍රාකී", "meaning": "අරත්ත, කළුවා අල, පැපිලිය", "category": "plant" },
  { "word": "ඡත්‍රාබඟ", "meaning": "හිරියල්", "category": "treatment" },
  { "word": "ඡත්‍රාබඟි", "meaning": "සිරස්ස, අරත්ත", "category": "plant" },
  { "word": "ඡත්‍රාධානස", "meaning": "කොත්තඹුරු", "category": "plant" },
  { "word": "ඡත්‍රාමින", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ඡත්‍රාහ්ව", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ඡත්‍රි", "meaning": "රක්අත්තන", "category": "plant" },
  { "word": "ඡත්‍රිත්", "meaning": "රක්අත්තන", "category": "plant" },
  { "word": "ඡත්‍රෝපක කාරිකා", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "ඡර්දිකා", "meaning": "වමනය", "category": "symptom" },
  { "word": "ඡර්දිමා", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "ඡර්දිමිකා", "meaning": "රසකිඳ, වැල්මදට", "category": "plant" },
  { "word": "ඡද", "meaning": "කොල්ලම්කොළ, තැල්වැල්, කල්නික", "category": "plant" },
  { "word": "ඡදන", "meaning": "කුකුරුමුවන්, කොබෝලිල, කොල්ලම්කොළ", "category": "plant" },
  { "word": "ඡදපතු", "meaning": "බුත්පත් ගස", "category": "plant" },
  { "word": "ඡන්නා", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ඡන", "meaning": "හණ", "category": "plant" },
  { "word": "ඡයා", "meaning": "කන්සා", "category": "plant" },
  { "word": "ඡර්දන", "meaning": "කොසඹ, කුකුරුමුවන්", "category": "plant" },
  { "word": "ඡර්දි", "meaning": "වමන රෝගය", "category": "symptom" },
  { "word": "ඡර්දිකා", "meaning": "විෂ්ණුක්‍රාන්ති, ලාකඩ, වමනය, කාස රෝගය", "category": "symptom" },
  { "word": "ඡර්දිකාපුරී", "meaning": "සිහින් එන්සාල්", "category": "plant" },

  // --- පිටුව 196 ---
  { "word": "ඡර්දිකාරිණී", "meaning": "වදකසා, අක්මැල්ල", "category": "plant" },
  { "word": "ඡර්දිකාරිපු", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ඡර්දිඝන", "meaning": "විලඳ, කොසඹ, හිත්වන්සාල්", "category": "treatment" },
  { "word": "ඡවිපත්‍රක", "meaning": "ඇත්සාවිය", "category": "plant" },
  { "word": "ඡාග", "meaning": "එළගිතෙල්", "category": "treatment" },
  { "word": "ඡාගක්‍ෂීර විනාශන", "meaning": "ගැටනිවුල්", "category": "plant" },
  { "word": "ඡාගකර්ණී", "meaning": "කුඹුක් (සල් විශේෂයක්)", "category": "plant" },
  { "word": "ඡාගභක්‍ෂ්‍යා", "meaning": "තියඳ", "category": "plant" },
  { "word": "ඡාගභස්මිනී", "meaning": "තියඳ", "category": "plant" },
  { "word": "ඡාගමොද", "meaning": "අසමෝද", "category": "plant" },
  { "word": "ඡාගලා", "meaning": "ගිරිනිල්ල, (මාබණ්ඩා)", "category": "plant" },
  { "word": "ඡාගලාක්‍ෂ", "meaning": "ඉද්ද ගස", "category": "plant" },
  { "word": "ඡාගගාන්ධිනී", "meaning": "මැඩහඟු", "category": "plant" },
  { "word": "ඡාගශිංගි", "meaning": "සිහින් මස්බැද්ද, සිහින් මැඩහඟු, (වෙලිප්පරිත්ති)", "category": "plant" },
  { "word": "ඡාගක්‍ෂීරවිනාශණ", "meaning": "ගැටනිවුල් ගස", "category": "plant" },
  { "word": "ඡාදන", "meaning": "තිල්කටුකරඬු", "category": "plant" },
  { "word": "ඡාඳිනීවාදර", "meaning": "කපු", "category": "plant" },
  { "word": "ඡාඳිනීවාරද", "meaning": "කපු", "category": "plant" },
  { "word": "ඡාබාරී", "meaning": "හණ ගස", "category": "plant" },
  { "word": "ඡායාරුරා", "meaning": "දෙඹ ගස", "category": "plant" },
  { "word": "ඡායාවෘක්‍ෂ", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "ඡාරදි", "meaning": "රක්අත්තන", "category": "plant" },
  { "word": "ඡාවි", "meaning": "කිණ ගස", "category": "plant" },
  { "word": "ඡිතති", "meaning": "කරඳ ගස", "category": "plant" },
  { "word": "ඡිදුරිදර", "meaning": "ඡිලොදරරෝගය", "category": "symptom" },
  { "word": "ඡිදුවෙදෙහි", "meaning": "ගප්තිප්පිලි", "category": "plant" },
  { "word": "ඡින්න", "meaning": "රසකිඳ, මහ මුඩමහණ, ඉදිසල්", "category": "plant" },
  { "word": "ඡින්නගන්ධිකා", "meaning": "මුඩමහණ", "category": "plant" },
  { "word": "ඡින්නගන්ධිනී", "meaning": "මුඩමහණ, නික", "category": "plant" },
  { "word": "ඡින්නගන්ධිනිකා", "meaning": "වෙල්මුබ (මුඛමහණ)", "category": "plant" },
  { "word": "ඡින්නග්‍රන්ථික", "meaning": "මුඩමහණ", "category": "plant" },
  { "word": "ඡින්නවේසිකා", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "ඡින්නපත්‍රී", "meaning": "දියමින්ත, ඇඹුලඇඹිලිය", "category": "plant" },
  { "word": "ඡින්නපත්‍රිකා", "meaning": "ඇම්බරැල්ලා ගස", "category": "plant" },
  { "word": "ඡින්නපුෂ්ප", "meaning": "තිලකවෘක්‍ෂය", "category": "plant" },
  { "word": "ඡින්නරුහා", "meaning": "සුළුකුර, රසකිඳ, කුකුරුමුවන්, වැටකේ", "category": "plant" },
  { "word": "ඡින්නරොහා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ඡින්නලතා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ඡින්නා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ඡින්නාස්වාස", "meaning": "ශ්වාස රෝගයක්", "category": "symptom" },
  { "word": "ඡින්නොද්භවා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ඡුල්ලි", "meaning": "සුළුකුර, මහකුර, නිල්තම්පලා", "category": "plant" },
  { "word": "ජුර", "meaning": "වඳුරු මෑ මුල්", "category": "plant" },
  { "word": "ජුරිකා", "meaning": "රක්අත්තන", "category": "plant" },
  { "word": "ඡෙක", "meaning": "ඉඟුරු", "category": "plant" },
  { "word": "ඡෙදනීය", "meaning": "ඉඟිනි ගස", "category": "plant" },
  { "word": "ඡෙදී", "meaning": "ඉඟිනි ගස", "category": "plant" },
  { "word": "ඡෙද්‍ර", "meaning": "සෝමලතා", "category": "plant" },
  { "word": "ඡෙදික", "meaning": "වේවැල්", "category": "plant" },
  { "word": "ජෝලඹ", "meaning": "ලප්නාරං", "category": "plant" },
  { "word": "ජෝහාරා", "meaning": "වියලි යොන් ඉඳි", "category": "plant" },
  { "word": "ජඛස්නේතු", "meaning": "තොවිල", "category": "plant" },
  { "word": "ජග්ල", "meaning": "උක්පැණි, කුකුරුමුවන්, සුරා, (ගෝධා)", "category": "treatment" },

  // --- පිටුව 197 ---
  { "word": "ජගල", "meaning": "උක්පැණි, කුකුරුමුවන්, ගෝධා", "category": "treatment" },
  { "word": "ජගකාමිභ", "meaning": "පනගි", "category": "plant" },
  { "word": "ජගනාවන්ඳන්", "meaning": "වැල්කසඹිලියා", "category": "plant" },
  { "word": "ජගතයාහ්ව", "meaning": "පනගි", "category": "plant" },
  { "word": "ජගතුල", "meaning": "නල්පත", "category": "plant" },
  { "word": "ජගනේඵලා", "meaning": "කොටදිඹුලා ගස", "category": "plant" },
  { "word": "ජගල", "meaning": "මුදුපෙණ, මස්වර්ග", "category": "treatment" },
  { "word": "ජඝනෝඵලා", "meaning": "කළුකැම්මේරිය, කොටදිඹුලා", "category": "plant" },
  { "word": "ජඝනාපවන්දන", "meaning": "රන්වන් සඳුන්", "category": "plant" },
  { "word": "ජංඝල", "meaning": "මස්", "category": "treatment" },
  { "word": "ජංඝලා", "meaning": "ගිරිනිල්ල (මාබණ්ඩා)", "category": "plant" },
  { "word": "ජංඝාගුල", "meaning": "කෙන්ඩා ගුලය", "category": "treatment" },
  { "word": "ජංඝුල", "meaning": "වැටකොළු ගෙඩි", "category": "plant" },
  { "word": "ජංඝස්නේතු", "meaning": "තොවිල", "category": "plant" },
  { "word": "ජට", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ජටා", "meaning": "ජටාමාංශ, සාතාවාරිය, වාගස්, දිවුල්", "category": "plant" },
  { "word": "ජටාකාලි", "meaning": "සාතාවාරිය, පිටවක්කා", "category": "plant" },
  { "word": "ජටානනා", "meaning": "ජටාමාංශ, පිටවක්කා", "category": "plant" },
  { "word": "ජටානුතා", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ජටාමල්", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ජටාමලා", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "ජටාමාංශි", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ජටාමූල", "meaning": "නවතාළිලිය, සාතාවාරිය, නීතිග", "category": "plant" },
  { "word": "ජටාය", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "ජටායපුෂ්ප", "meaning": "එඬරුමල්", "category": "plant" },
  { "word": "ජටායුෂ්", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "ජටාහි", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ජටාරාද්‍රා", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ජටාල", "meaning": "ගුගුල්, ජටාමාංශ, කපුරු, නුග", "category": "plant" },
  { "word": "ජටාවතී", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ජටි", "meaning": "නුග ගස, ජටාමාංශ, තෙලඹු ගෙඩි, පුමිල", "category": "plant" },
  { "word": "ජටිකා", "meaning": "හුනිද", "category": "plant" },
  { "word": "ජටිල", "meaning": "වදකහ, නුග, පුමිල, හිඟුරුපියලි, තිප්පිලි", "category": "plant" },
  { "word": "ජටිලා", "meaning": "අමුකපුරු, ජටාමාංශ, සුළුසාරණ", "category": "plant" },
  { "word": "ජටී", "meaning": "තෙලුඹුගෙඩි, නුග, ජටාමාංශ, පුමිල", "category": "plant" },
  { "word": "ජටින්", "meaning": "තත්පුමිල, (තෙලසවු)", "category": "plant" },
  { "word": "ජඨරනුත්", "meaning": "ඇසල", "category": "plant" },
  { "word": "ජඨරොදර", "meaning": "ජලෝදර රෝගය", "category": "symptom" },
  { "word": "ජඩ", "meaning": "වඳුරු මෑ, ඊතණ", "category": "plant" },
  { "word": "ජඩා", "meaning": "පිටවක්කා, වඳුරු මෑ", "category": "plant" },
  { "word": "ජඩි", "meaning": "සුවඳ කසා", "category": "plant" },
  { "word": "ජඩස්මක", "meaning": "මනෝසිල, ගල්සෙවෙල්", "category": "treatment" },
  { "word": "ජත", "meaning": "හොමුවහු", "category": "plant" },
  { "word": "ජතකා", "meaning": "කසා", "category": "plant" },
  { "word": "ජතු", "meaning": "ලාකඩ, ගල්මද, ගල්සෙවෙල්, ලතුදිය", "category": "treatment" },
  { "word": "ජතුක", "meaning": "පෙරුම්කායම්, (පිණ්ඩහිඟු)", "category": "treatment" },
  { "word": "ජතුකා", "meaning": "පැපිලිය, වටාස්ස, ආපසුමුදු, තම්පලා", "category": "plant" },
  { "word": "ජතුකාශ්මීර", "meaning": "කොකුම්", "category": "plant" },
  { "word": "ජතුකාහ්වා", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "ජතුකාචි", "meaning": "වටාස්ස", "category": "plant" },
  { "word": "ජතුපත්‍රිකා", "meaning": "ඇඹුල්ඇඹිලිය, කුඩාපහණබෙය", "category": "plant" },
  { "word": "ජතුමණි", "meaning": "කුෂ්ඨ රෝගයක්", "category": "symptom" },
  { "word": "ජතුමුඛ", "meaning": "තැල්වී වෙසෙසක්", "category": "plant" },
  { "word": "ජතුරස", "meaning": "ලතුදිය", "category": "treatment" },
  { "word": "ජතුශිලා", "meaning": "ගල්සෙවෙල්", "category": "treatment" },
  { "word": "ජතුන", "meaning": "වැලුක්, රඹුක්", "category": "plant" },
  { "word": "ජන්තු", "meaning": "ගෝ මුත්‍රා, අත්තික්කා", "category": "treatment" },
  { "word": "ජන්තුක", "meaning": "පිණ්ඩ හිඟු, (පෙරුම්කායම්)", "category": "treatment" },
  { "word": "ජන්තුකා", "meaning": "සාදිලිංගම්, ලාකඩ", "category": "treatment" },

  // --- පිටුව 198 ---
  { "word": "ජන්තුකුමාර", "meaning": "කොසඹ, මහකොසඹ", "category": "plant" },
  { "word": "ජන්තුඝන", "meaning": "වලඟසාල්, පිණ්ඩහිඟු, දෙහිම", "category": "treatment" },
  { "word": "ජන්තුජිත්", "meaning": "වලඟසාල්, දෙබමිගස", "category": "plant" },
  { "word": "ජන්තුනාශන", "meaning": "කෘමිඝයනා, පෙරුම්කායම්, කොරාසානි", "category": "treatment" },
  { "word": "ජන්තුපාදප", "meaning": "අඹ වෙසෙසක්", "category": "plant" },
  { "word": "ජන්තුඵල", "meaning": "දිඹුල්, අත්තික්කා", "category": "plant" },
  { "word": "ජන්තුහන්", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ජන්තුමත්ඵල", "meaning": "දිඹුල්ගස", "category": "plant" },
  { "word": "ජන්තුමාරි", "meaning": "කොසඹ, දෙහි", "category": "plant" },
  { "word": "ජනතුරස", "meaning": "ලතුදිය", "category": "treatment" },
  { "word": "ජන්තුරලා", "meaning": "ඊතණ, කුසතණ, වැලුක්", "category": "plant" },
  { "word": "ජන්තුවෘක්‍ෂ", "meaning": "ඇටඹ, දිඹුල් ගස", "category": "plant" },
  { "word": "ජන්තුශත්‍රැ", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ජන්තුහන්තු", "meaning": "හණඇට", "category": "plant" },
  { "word": "ජන්තුහන්ත්‍රී", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ජන්තුඝාතන", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ජන්තුහාහ්", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ජන්තව", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ජන්ම", "meaning": "කොකුම්", "category": "plant" },
  { "word": "ජන්වේනු", "meaning": "මහදියබෙරලිය", "category": "plant" },
  { "word": "ජන", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "ජනකාරිනී", "meaning": "ලතුදිය", "category": "treatment" },
  { "word": "ජනතිකා", "meaning": "ඇල්වී", "category": "plant" },
  { "word": "ජනනී", "meaning": "ලමඟ, සාදික්කා, ලාකඩ, ලුණුවිල, කුවරන්, ජටාමාංශ, බෝලිද්ද", "category": "plant" },
  { "word": "ජනතිරිපු", "meaning": "තියඳ", "category": "plant" },
  { "word": "ජනමුඛ", "meaning": "කොත්තමල්ලි, මුරුංගා, නාරන්", "category": "plant" },
  { "word": "ජනමුඛියා", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ජනරක්ෂක", "meaning": "වල්තම්පලා", "category": "plant" },
  { "word": "ජනවල්ලභ", "meaning": "එල එරබු", "category": "plant" },
  { "word": "ජනා", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "ජනාමිභය", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "ජනාහ්වය", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "ජතිකා", "meaning": "අබනගිරිය, අවිරිය, තෙල්බේරු", "category": "plant" },
  { "word": "ජනිකොශිකා", "meaning": "තෙල්බේරු", "category": "plant" },
  { "word": "ජනතිලිකා", "meaning": "නිල්කටරොළු", "category": "plant" },
  { "word": "ජනිවා", "meaning": "තිගිරි", "category": "plant" },
  { "word": "ජනිෂ්ඨා", "meaning": "දෑසමන්", "category": "plant" },
  { "word": "ජනි", "meaning": "වටාස්ස, කසා, සාදික්කා, ලමඟ, හිඟුරුවැල්, වටුලාපිය", "category": "plant" },
  { "word": "ජනෙනිකා", "meaning": "තියඳ, හැල්වී, සෑටදා වී", "category": "plant" },
  { "word": "ජනෙෂ්ට", "meaning": "යොහොඹු, දෑසමන්, කසා, ලාකඩ", "category": "plant" },
  { "word": "ජනේෂිඨා", "meaning": "විෂ්ණුක්‍රාන්ති, රිදී, රත්රන්", "category": "treatment" },
  { "word": "ජනොතහම", "meaning": "තේක්ක ගස", "category": "plant" },
  { "word": "ජපා", "meaning": "බඳුවද", "category": "plant" },
  { "word": "ජපාකුසුමසන්නිභ", "meaning": "හිඟුල්", "category": "treatment" },
  { "word": "ජපාපුෂ්ප", "meaning": "වදමල්", "category": "plant" },
  { "word": "ජපාප්‍රසූන", "meaning": "වදමල්", "category": "plant" },
  { "word": "ජපාරක්ත", "meaning": "බඳුවද, පොකුරු වද", "category": "plant" },
  { "word": "ජපුමෝදනී", "meaning": "හෙල බටු, මහ හෙලබටු", "category": "plant" },
  { "word": "ජබා", "meaning": "වදගස", "category": "plant" },
  { "word": "ජම්බල", "meaning": "(ජමබෝල) ජැගිරි වර්ගයේ ඉතා විශාල එල හටගන්නා ගස, දෙහිමී වලට ද නමි.", "category": "plant" },
  { "word": "ජම්බාල", "meaning": "මඩ, වැටකේ", "category": "plant" },
  { "word": "ජම්බි", "meaning": "හලා, මුං, මරාවක ගස, අක්මැල්ල", "category": "plant" },
  { "word": "ජම්බීර", "meaning": "දෙහිමී, කරව්, අඳුතලා, හෙල අඳුතලා", "category": "plant" },
  { "word": "ජම්බිල", "meaning": "දෙහිමී", "category": "plant" },
  { "word": "ජම්බීල", "meaning": "දෙහිමී", "category": "plant" },

  // --- පිටුව 199 ---
  { "word": "ජම්බු", "meaning": "මාදම්, හෙළදම්, දඹ, වැටකේ, තොවිල", "category": "plant" },
  { "word": "ජම්බුක", "meaning": "තොවිල, බැමිනිරිය, මහඋවරල, ලොත්", "category": "plant" },
  { "word": "ජම්බුකතාණ", "meaning": "සුවඳ තෘණ", "category": "plant" },
  { "word": "ජම්බුකා", "meaning": "කිඹුල්වන් මිදි", "category": "plant" },
  { "word": "ජම්බුල", "meaning": "වැටකේ, දඹගස", "category": "plant" },
  { "word": "ජම්බුවෘක්‍ෂ", "meaning": "දඹගස", "category": "plant" },
  { "word": "ජම්බෝල", "meaning": "ජැගිරි වගියේ වඩාම ලොකු ගෙඩි පල ගන්නා ගස", "category": "plant" },
  { "word": "ජම්හ", "meaning": "දෙබම්, සුදුමරාවක ගස", "category": "plant" },
  { "word": "ජම්හක", "meaning": "කසාවන් ලොත්", "category": "plant" },
  { "word": "ජම්හන", "meaning": "වරාගස, මරාවක ගස", "category": "plant" },
  { "word": "ජම්හාර", "meaning": "දෙබම් ගස", "category": "plant" },
  { "word": "ජම්හාල", "meaning": "දෙබම්", "category": "plant" },
  { "word": "ජම්හාලා", "meaning": "දෙබම්, ලප්නාරං, වරා", "category": "plant" },
  { "word": "ජම්හි", "meaning": "පැණි දෙබම්", "category": "plant" },
  { "word": "ජම්හින්", "meaning": "දෙබම් ගස", "category": "plant" },
  { "word": "ජම්හීර", "meaning": "දෙබම්, තලා, කළු තලා", "category": "plant" },
  { "word": "ජම්හිරී", "meaning": "පැණි දෙබම්, දෙබම්", "category": "plant" },
  { "word": "ජම්ම", "meaning": "ඉඟුරු", "category": "plant" },
  { "word": "ජම්නාරං", "meaning": "ලොකුම නාරං වර්ගය", "category": "plant" },
  { "word": "ජම්නිය", "meaning": "මුවකිරිය", "category": "plant" },
  { "word": "ජම්රය", "meaning": "බැබිල", "category": "plant" },
  { "word": "ජය", "meaning": "මිදි, සිහින්මිදි, මහමිදි", "category": "plant" },
  { "word": "ජයකාරිකා", "meaning": "නිදිකුම්බා, (දඹින්තෘණ) වැල්මදට", "category": "plant" },
  { "word": "ජයතාරු", "meaning": "නන්දි රුක", "category": "plant" },
  { "word": "ජයද්‍රැම", "meaning": "පිළිල", "category": "plant" },
  { "word": "ජයනති", "meaning": "කහ, මිදි, සුළු බුබාවිල, වඳුරු මෑ", "category": "plant" },
  { "word": "ජයන්තී", "meaning": "වැල්මදට, අරළු, සුදුනික", "category": "plant" },
  { "word": "ජයන්තෘකා", "meaning": "සිහින්මිදි, වනුවැල්, (බාත්වැල්)", "category": "plant" },
  {
    "word": "ජයපාල (ජයපාල ගස)",
    "meaning": "වල් කැප්පෙට්ටියා කොළ වලට මඳක් සමාන, බික් තුනකට ගැලවෙන, තද කටුවක් තුළ ඇට තුන බැගින් තිබෙන ජයපාල ගස ගුණ නොදන්නා කෙනෙක් ඇතැයි සිතිය නොහැක. මෙය දේශීය වෙදකමේ ප්‍රධාන විරේක බෙහෙතකි. ආමශුල, උදාරශුල ආදී රෝග වලට ත්, වෙනත් ජ්වර රෝග ආදියට ත් දෙන ගුලි වර්ග වලට විෂ හැරී ජයපාල ඇට ද ඖෂධයක් වශයෙන් එකතු කරති.",
    "category": "plant"
  },
  { "word": "ජයවාක්‍ෂ", "meaning": "බෝ රුක, ඇසතු බෝ", "category": "plant" },
  { "word": "ජයවෘක්‍ෂක්‍ෂීර", "meaning": "බෝ කිරි", "category": "plant" },
  { "word": "ජයසුමන", "meaning": "බඳුවද", "category": "plant" },
  { "word": "ජයා", "meaning": "විෂ්ණුක්‍රාන්ති, සිහින් මිදි, වැල්මදට, තලා, කංසා, කස්තුරි, අරළු, සෙන්කොට්ටම්", "category": "plant" },

  // --- පිටුව 200 ---
  { "word": "ජයාග්නිමන්ථ", "meaning": "මිදි, නීතිග", "category": "plant" },
  { "word": "ජයාජය", "meaning": "මහමිදි", "category": "plant" },
  { "word": "ජයාපනි", "meaning": "එන්සාල්, එල්වළු", "category": "plant" },
  { "word": "ජයාප්පති", "meaning": "එන්සාල්, එල්වළු", "category": "plant" },
  { "word": "ජයාවහා", "meaning": "නිල්රතණ, මහ දත්ත", "category": "plant" },
  { "word": "ජයාහ්වා", "meaning": "වද, බඳුවද, පොකුරුවද, මහ දත්ත", "category": "plant" },
  { "word": "ජර්ජර", "meaning": "ගල්සෙවෙල්, රතුලූණු", "category": "treatment" },
  { "word": "ජර්නිල", "meaning": "තල, වල් තල", "category": "plant" },
  { "word": "ජර", "meaning": "දුරු, සිහින් දුරු, (සුදුදුරු)", "category": "plant" },
  { "word": "ජරකා", "meaning": "සුදුදුරු, (සිහින්දුරු) පෙරුම්කායම්", "category": "plant" },
  { "word": "ජරණ", "meaning": "ඇත්තෝර, සුවසලුණු", "category": "plant" },
  { "word": "ජරණා", "meaning": "පෙරුම්කායම්, කොවිලම්, කලුදුරු", "category": "treatment" },
  { "word": "ජරණද්‍රැම", "meaning": "මූරුත ගස", "category": "plant" },
  { "word": "ජරණහිබටු", "meaning": "පිණ්ඩහිබටු, (පෙරුම්කායම්) දෙදුරු, සුවස ලුණු, කොට්ටම්", "category": "treatment" },
  { "word": "ජරසි", "meaning": "ලීබෑත්ත", "category": "plant" },
  { "word": "ජරා", "meaning": "වදකහ, කිරිපලු ගස", "category": "plant" },
  { "word": "ජරාජම්බු", "meaning": "බලුදම්, කාක දම්", "category": "plant" },
  { "word": "ජරාවරා", "meaning": "වදකහ, ලාකඩ, තලා, වද", "category": "plant" },
  { "word": "ජල", "meaning": "ඉරිවේරිය, තිප්පිලි, කුඹුරැක්, ග්‍රීවේර, සුදුරියම්, වතුර, කඩුකරෝෂණ", "category": "plant" },
  { "word": "ජලඋදර", "meaning": "එනම් රෝගය", "category": "symptom" },
  { "word": "ජලකණ්ටක", "meaning": "කොහිල, (අභිරු) කටු පෙනෙල, නිරමුල්ලිය, (ඉකිරිය)", "category": "plant" },
  { "word": "ජලකන්‍ද", "meaning": "කොහිල, කටුපෙනෙල", "category": "plant" },
  { "word": "ජලකරඹික", "meaning": "සක්, පොල්", "category": "plant" },
  { "word": "ජලකාමී", "meaning": "හොමුවහු, වරා පුෂ්ප", "category": "plant" },
  { "word": "ජලකාමා", "meaning": "වරාමල්, හොමුවහු", "category": "plant" },
  { "word": "ජලකාමුක", "meaning": "කටුම්බින් වාක්‍ෂය", "category": "plant" },
  { "word": "ජලකාමුකී", "meaning": "කටුම්බින් වාක්‍ෂය", "category": "plant" },
  { "word": "ජලකුන්තල", "meaning": "දියසෙවෙල්", "category": "plant" },
  { "word": "ජලකුම්බිකා", "meaning": "කොහිල, සෙවෙල්", "category": "plant" },
  { "word": "ජලකුමිහී", "meaning": "දියපරඬලා", "category": "plant" },
  { "word": "ජලකෙශ", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "ජලගුක", "meaning": "පාසි, (පෙද) දියසෙවෙල් තෙලුඹුදලි, නෙළුම්මල්", "category": "plant" },
  { "word": "ජලඝනද්‍රැම", "meaning": "රණවරා", "category": "plant" },
  { "word": "ජලජ", "meaning": "සක්, නිලුපුල්, ඉරිවේරිය, තල්ගස, කුරුඳුපොතු, මිදෙල්ල, හොමුවහු, කපුරු, තුත්පුමිල, පලොල්, පෙද, නෙළුම්", "category": "plant" },
  { "word": "ජලජපතුකා", "meaning": "සුබාවා", "category": "plant" },
  { "word": "ජලජමහුත", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "ජලජම්බු", "meaning": "වල්මී, ඔලිඳ", "category": "plant" },
  { "word": "ජලජා", "meaning": "වල්මී, බෝදි ගස", "category": "plant" },
  { "word": "ජලජාපා", "meaning": "හොමුවහු", "category": "plant" },
  { "word": "ජලජීවිනී", "meaning": "දියපුබාවා", "category": "plant" },
  { "word": "ජලතණඩුලිය", "meaning": "දියතිල්ල", "category": "plant" },
  { "word": "ජලතාල", "meaning": "කාම්මේරිය ගස", "category": "plant" },
  { "word": "ජලතාවිකා", "meaning": "කාම්මේරිය ගස", "category": "plant" },
  { "word": "ජලතික්තකා", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "ජලතික්තිකා", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "ජලත්‍රාණ", "meaning": "වැලුක්, රඹුක්", "category": "plant" },
  { "word": "ජලද", "meaning": "නිල්මානෙල්, වම්මුතු, කලාදුරු, කපුරු", "category": "plant" },
  { "word": "ජලදර", "meaning": "කලාදුරු", "category": "plant" },
  { "word": "ජලදා", "meaning": "සක්නාබ", "category": "treatment" },
  { "word": "ජලදාගත", "meaning": "සල් ගස, තේක්ක ගස", "category": "plant" },
  { "word": "ජලද්‍රැම", "meaning": "රණවරා", "category": "plant" },
  { "word": "ජලධර", "meaning": "කපුරු, ශක්ගෙහිය, කොල්ලු ගස", "category": "plant" },
  { "word": "ජලධාර", "meaning": "කසාවන් සුවඳහොට", "category": "plant" },
  { "word": "ජලධාරා", "meaning": "සුවඳහොට, (සැවැන්දරා) ඉකිරි, (නිරමුල්ලිය)", "category": "plant" },

  // --- පිටුව 201 ---
  { "word": "ජලධි", "meaning": "වම්මුතු, කලාදුරු", "category": "plant" },
  { "word": "ජලන", "meaning": "මිදි", "category": "plant" },
  { "word": "ජලනි", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "ජලනිලි", "meaning": "පෙද, (පාසි) දියසෙවෙල්", "category": "plant" },
  { "word": "ජලනෙතු", "meaning": "බිම් ගස", "category": "plant" },
  { "word": "ජලපතාන්ත්‍රිකා", "meaning": "දියපුබාවා", "category": "plant" },
  { "word": "ජලප්‍රප", "meaning": "පනගි", "category": "plant" },
  { "word": "ජලපිල", "meaning": "කැකිරි, පොල්", "category": "plant" },
  { "word": "ජලපිප්පලි", "meaning": "දියතිප්පිලි", "category": "plant" },
  { "word": "ජලප්‍රවෝදනී", "meaning": "එලබටු", "category": "plant" },
  { "word": "ජලපුද", "meaning": "කසාවන් ඉරිවේරිය", "category": "plant" },
  { "word": "ජලප්‍රිය", "meaning": "මුරුංගා ගස, කොතඹුරු, (කොත්තමල්ලි)", "category": "plant" },
  { "word": "ජලඵල", "meaning": "පොල් ගස, කටුපෙනෙල", "category": "plant" },
  { "word": "ජලපේණ", "meaning": "මුදුපෙණ", "category": "treatment" },
  { "word": "ජලබිජු", "meaning": "අඹ යනාදිය", "category": "plant" },
  { "word": "ජලබ්‍රාහ්මී", "meaning": "බෝදි ගස", "category": "plant" },
  { "word": "ජලනාස", "meaning": "මුදුපෙණ", "category": "treatment" },
  { "word": "ජලනිප්ඵල", "meaning": "දියමිදෙල්ල", "category": "plant" },
  { "word": "ජලහු", "meaning": "කපුරු, දියතිල්ල", "category": "plant" },
  { "word": "ජලහාත්", "meaning": "කපුරු", "category": "treatment" },
  { "word": "ජලමක්‍ෂ", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "ජලමණ්ඩපිකා", "meaning": "සෙවෙල්, දියපරඬලා", "category": "plant" },
  { "word": "ජලමඬුක", "meaning": "ඕලුගස", "category": "plant" },
  { "word": "ජලමසි", "meaning": "කපුරු", "category": "treatment" },
  { "word": "ජලමුවි", "meaning": "කපුරු, වම්මුතු", "category": "plant" },
  { "word": "ජලමුර්නිකා", "meaning": "පාණ්වැස්ස", "category": "plant" },
  { "word": "ජලමොද", "meaning": "සුවඳහොට", "category": "plant" },
  { "word": "ජලරස", "meaning": "ලුණු, සුවසලුණු", "category": "treatment" },
  { "word": "ජලරැපු", "meaning": "රණවරා", "category": "plant" },
  { "word": "ජලවන්", "meaning": "නෙළුම්", "category": "plant" },
  { "word": "ජලවල්කල", "meaning": "දියපරඬලා", "category": "plant" },
  { "word": "ජලවල්ලී", "meaning": "කටු පෙනෙල", "category": "plant" },
  { "word": "ජලවානීර", "meaning": "හොමුවහු", "category": "plant" },
  { "word": "ජලවාස", "meaning": "සුවඳහොට", "category": "plant" },
  { "word": "ජලමික්‍රම", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "ජලවිලා", "meaning": "දියපරඬලා", "category": "plant" },
  { "word": "ජලවේතස", "meaning": "ඇඹුල්වේ, හොමුවහු", "category": "plant" },
  { "word": "ජලශුක", "meaning": "පෙද, නෙළුම් අල", "category": "plant" },
  { "word": "ජලශුවි", "meaning": "කටු පෙනෙල", "category": "plant" },
  { "word": "ජලශුනු", "meaning": "සුදු ඊතණ", "category": "plant" },
  { "word": "ජලසන්ත්‍රාස", "meaning": "ජලභීතිකා රෝගය", "category": "symptom" },
  { "word": "ජලසම්භව", "meaning": "හොමුවහු", "category": "plant" },
  { "word": "ජලසමුතුක", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "ජලසර්පිනී", "meaning": "පුබාවා", "category": "plant" },
  { "word": "ජලසුවි", "meaning": "කටුපෙනෙල, දියපුබාවා", "category": "plant" },
  { "word": "ජලහාස", "meaning": "මුදුපෙණ", "category": "treatment" },
  { "word": "ජලාක්‍ෂි", "meaning": "දියනිප්පිලි", "category": "plant" },
  { "word": "ජලාබ්‍යා", "meaning": "ඕලු ගස", "category": "plant" },
  { "word": "ජලාඤ්ජවල", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "ජලාටනී", "meaning": "දියපුබාවා", "category": "plant" },
  { "word": "ජලාධාරා", "meaning": "ඉකිරිය, සුවඳහොට", "category": "plant" },
  { "word": "ජලාබුජ", "meaning": "හල් ගස", "category": "plant" },
  { "word": "ජලාම්බුකා", "meaning": "දියපුබාවා", "category": "plant" },
  { "word": "ජලාමොද", "meaning": "සැවැන්න", "category": "plant" },
  { "word": "ජලායුක", "meaning": "නෙළුම් අල", "category": "plant" },
  { "word": "ජලායුකා", "meaning": "දියපුබාවා", "category": "plant" },
  { "word": "ජලාන්වයා", "meaning": "ඉරිවේරිය, උපුල්", "category": "plant" },
  { "word": "ජලාශය", "meaning": "සැවැන්න", "category": "plant" },
  { "word": "ජලාශ්‍රය", "meaning": "සැවැන්න", "category": "plant" },
  { "word": "ජලාසුකා", "meaning": "දියපුබාවා", "category": "plant" },
  { "word": "ජලිකා", "meaning": "කුඹල්ලා", "category": "plant" },
  { "word": "ජලේරුහා", "meaning": "කටුම්බින් වෘක්‍ෂය", "category": "plant" },
  { "word": "ජලෝකාකාල", "meaning": "දියගොමුවහු", "category": "plant" },
  { "word": "ජලෝකාසමානා", "meaning": "හොමුවහු, දියගොමුවහු", "category": "plant" },
  { "word": "ජලොත්භව", "meaning": "රඹුක්, වැලුක්, ලුණුවිල (බැමිනිරිය)", "category": "plant" },
  { "word": "ජලොත්භවතෘණ", "meaning": "වැලුක්", "category": "plant" },
  { "word": "ජලොරගා", "meaning": "දියකුඹල්ලා", "category": "plant" },

  // --- පිටුව 202 ---
  { "word": "ජලොලුකා", "meaning": "පියුම් ඇට", "category": "plant" },
  { "word": "ජලෙශක", "meaning": "හොමුවහු", "category": "plant" },
  { "word": "ජලෙශකා", "meaning": "දියපුබාවා", "category": "plant" },
  { "word": "ජවනෙෂට", "meaning": "කළු ඊයම්", "category": "treatment" },
  { "word": "ජවලි", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "ජවසාන්වා", "meaning": "අසමෝදගම්", "category": "plant" },
  { "word": "ජවා", "meaning": "වදමල්, වදකසා", "category": "plant" },
  { "word": "ජවාදු", "meaning": "ජවාදුනි, කෘමිඝස්තෘ", "category": "treatment" },
  { "word": "ජවාන", "meaning": "කෘමිඝස්තෘ", "category": "treatment" },
  { "word": "ජවානි", "meaning": "කෘමිඝස්තෘ, තිත්ත වැටකොළු, අසමෝද", "category": "plant" },
  { "word": "ජවානිකා", "meaning": "කෘමිඝස්තෘ", "category": "treatment" },
  { "word": "ජවානි", "meaning": "අසමෝදගම්", "category": "plant" },
  { "word": "ජවානියා", "meaning": "කෘමිඝස්තෘ", "category": "treatment" },
  { "word": "ජවාපුෂ්ප", "meaning": "වදමල", "category": "plant" },
  { "word": "ජවාෂ්වා", "meaning": "කෘමිඝස්තෘ, කොරාසානි", "category": "treatment" },
  { "word": "ජහිස", "meaning": "අතිවිඩයන්", "category": "plant" },
  { "word": "ජසද", "meaning": "කළු ඊයම්, තුත්ථනාගම්", "category": "treatment" },
  { "word": "ජසාහා", "meaning": "කෘමිඝස්තෘ", "category": "treatment" },
  { "word": "ජහං", "meaning": "මහ මුඩමහණ", "category": "plant" },
  { "word": "ජා", "meaning": "හණ, තියඳ", "category": "plant" },
  { "word": "ජාංගලය", "meaning": "මදුළු දිය හා ගල් ඇති ප්‍රදේශය", "category": "treatment" },
  { "word": "ජාංගලවගමස්", "meaning": "ජාංගල වර්ගයේ මස්රස", "category": "treatment" },
  { "word": "ජාගත", "meaning": "තියඳ, සෝමලතා", "category": "plant" },
  { "word": "ජාගලා", "meaning": "ගිරිනිල්ල", "category": "plant" },
  { "word": "ජාගුඩ", "meaning": "කොකුම්", "category": "plant" },
  { "word": "ජාඩගල", "meaning": "එඬරු මෑ", "category": "plant" },
  { "word": "ජාඩගුඩි", "meaning": "කොකුම්", "category": "plant" },
  { "word": "ජාජ්", "meaning": "සිනිත්දුරු, (සුදුදුරු)", "category": "plant" },
  { "word": "ජාටලි", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "ජාඨර ග්‍රන්ථි", "meaning": "ගුල්ම රෝගය", "category": "symptom" },
  { "word": "ජාඩ්‍යාහරි", "meaning": "දෙබම් ගස", "category": "plant" },
  { "word": "ජාඩියා", "meaning": "සැලිය, බරණිය, පිප්පය", "category": "plant" },
  { "word": "ජාතකොෂ", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතඵල", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතරූප", "meaning": "නාමල්රේණු, රත්, නාකෙසරා", "category": "plant" },
  { "word": "ජාතරූපකා", "meaning": "සවර්ණ, (රත්රන්)", "category": "treatment" },
  { "word": "ජාතරූපප්‍රභා", "meaning": "හිරියල්", "category": "treatment" },
  { "word": "ජාතවේදස්", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "ජාතසාර", "meaning": "සිවිය, ගප්තිප්පිලිඉඟිනි, මහඉඟිනි", "category": "plant" },
  { "word": "ජාතී", "meaning": "වෙලඟ, යොහොඹු, සමන්පිච්ච, (දෑසමන්) මිදි, නෙල්ලිසාදික්කා, ලමඟ", "category": "plant" },
  { "word": "ජාතිකා", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතිකාඵල", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතිකොෂිකා", "meaning": "ලමඟ, සාදික්කා", "category": "plant" },
  { "word": "ජාතිකොෂ", "meaning": "වසාවාසි, ලමඟ, සාදික්කා, මිදි, හිඟුරුපියලි, ජයපාල, නෙරළු අල", "category": "plant" },
  { "word": "ජාතිකොෂාතක", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතිප්", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතිවෙනී", "meaning": "පිච්ච මල්", "category": "plant" },
  { "word": "ජාතිප්තනී", "meaning": "ලමඟ, සාදික්කා", "category": "plant" },
  { "word": "ජාතිදඩ්‍ර", "meaning": "දම්දෙවිසුදු (සිරිතේක්කු)", "category": "plant" },
  { "word": "ජාතිපක්", "meaning": "සාදික්කා ගෙඩි", "category": "plant" },
  { "word": "ජාතිපත්", "meaning": "වසාවාසි", "category": "plant" },
  { "word": "ජාතිපත්‍ර", "meaning": "වසාවාසි", "category": "plant" },
  { "word": "ජාතිපත්‍රක", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතිපත්‍රී", "meaning": "වසාවාසි", "category": "plant" },
  { "word": "ජාතිපර්ණී", "meaning": "වසාවාසි, සාදික්කා", "category": "plant" },
  { "word": "ජාතිඵල", "meaning": "සාදික්කා ගෙඩි", "category": "plant" },
  { "word": "ජාතිපුෂ්ප", "meaning": "යොහොඹු (ගැටපිච්ච) දෑසමන්", "category": "plant" },
  { "word": "ජාතිපුෂ්කර", "meaning": "සාදික්කා ගෙඩි", "category": "plant" },
  { "word": "ජාතිප්‍රවාල", "meaning": "දෑසමන් දළු", "category": "plant" },
  { "word": "ජාතිඵල", "meaning": "ලමඟ, සාදික්කා", "category": "plant" },
  { "word": "ජාතිඵලන්තව", "meaning": "වසාවාසි", "category": "plant" },
  { "word": "ජාතිරස", "meaning": "වච්චනාවි", "category": "plant" }
];