// data_482_492.js - පිටු 482 සිට 492 දක්වා සියලුම වචන සහ විස්තර
const data_extra_482_492 = [

    // --- පිටුව 482 ---
    { 
        "word": "සහල් දෝවුන් දිය", 
        "meaning": "හාල්පාණු = (සිංහල කැකුළු හාල් පාණු (හාල් සේදු වතුර) මේ රටේ පෙර සිට ගනිති. සහල් පලම් එකකට වතුර එක පතක් දමා සිංහල පැය 15 ක් තබා පෙරා ගත් ජලය සහල් දෝවුන් දිය (තණ්ඩුලාම්බු) වේ.", 
        "category": "liquid" 
    },
    { "word": "සහලෝකා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "සහස්", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සහස් දත්", "meaning": "මත්ස්‍යා, (බලයා)", "category": "animal" },
    { "word": "සහස් නෙත්", "meaning": "කෙළිඳ ගස්", "category": "plant" },
    { "word": "සහස් පත්", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "සහස් රැස්", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සහස් වෙද", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සහස්‍රකණ්ඩි", "meaning": "සුදු රතණ", "category": "plant" },
    { "word": "සහස්‍ර පත්‍ර", "meaning": "රත් නෙළුම්", "category": "plant" },
    { "word": "සහස්‍ර පාද", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සහස්‍ර වීර්‍ය්‍යා", "meaning": "රතණ", "category": "plant" },
    { "word": "සහස්‍ර වේධි", "meaning": "ඇඹුල්වේ, පෙරුම්කායම්, කස්තුරි", "category": "plant" },
    { "word": "සහස්‍රා", "meaning": "දියමින්ත", "category": "plant" },
    { "word": "සහසිරි", "meaning": "ඇම්බරැල්ල", "category": "plant" },
    { "word": "සහසා", "meaning": "අරත්ත", "category": "plant" },
    { "word": "සහා", "meaning": "මුංවැන්න, කෝමාරිකා, දඬු උපුල්, සුදු කටුකරඬු, අරත්ත, පික්මල්, කටුකරඬු, සුලු හෙල දිය, මහ හෙලදිය", "category": "plant" },
    { "word": "සහාවර", "meaning": "තෙල ගස, රන්වන් කටුකරඬු", "category": "plant" },
    { "word": "සහාර", "meaning": "අඹ", "category": "plant" },
    { "word": "සහිඤ්ඤු", "meaning": "දෙහි", "category": "plant" },
    { "word": "සහිරි", "meaning": "පුස්කර", "category": "plant" },
    { "word": "සා", "meaning": "සැම ගස්, අත්තන", "category": "plant" },
    { "word": "සාක", "meaning": "මහරී, අතු", "category": "plant" },
    { "word": "සාකය", "meaning": "වරණ ගස", "category": "plant" },
    { "word": "සාකාපස", "meaning": "තික, වරා, කුඹුරු, තොටිල, එරබදු යන මේ පස් වර්ගයේ ශාඛා", "category": "plant" },
    { "word": "සාකුරණ්ඩ", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "සාකොට", "meaning": "ගැට නිටුල්", "category": "plant" },
    { "word": "සාඛා", "meaning": "අතු", "category": "plant" },
    { "word": "සාඛින", "meaning": "සැමගස", "category": "plant" },
    { "word": "සාගර", "meaning": "මුහුදු ලුණු", "category": "mineral" },
    { "word": "සාගරක", "meaning": "මුහුදු ලුණු", "category": "mineral" },
    { "word": "සාගරගාමිණී", "meaning": "හීන් එන්සාල්", "category": "plant" },
    { "word": "සාගරජමල", "meaning": "මුදු පෙණ", "category": "mineral" },
    { "word": "සාගරොත්", "meaning": "මුදුලුණු", "category": "mineral" },
    { "word": "සාගරොත්පල", "meaning": "මුදු පෙණ", "category": "mineral" },
    { "word": "සාච්චාටිකා", "meaning": "සුදු සාරණ", "category": "plant" },
    { "word": "සාටක / සාටිකා", "meaning": "රෙදි", "category": "general" },
    { "word": "සාඩන විටපි", "meaning": "කිහිරි ගස", "category": "plant" },
    { "word": "සාතකුම්භ", "meaning": "අලරිය, රත්රන්", "category": "compound" },
    { "word": "සාතලා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "සාතලාවර්තිනි", "meaning": "වී", "category": "plant" },
    { "word": "සාතාවාරි", "meaning": "සාතාවාරිය (සාතාවාරිය)", "category": "plant" },
    { "word": "සාතාවාරිය", "meaning": "ජලමක්‍ෂී", "category": "plant" },
    { "word": "සාද", "meaning": "කොකුම්", "category": "plant" },
    { "word": "සාදනී", "meaning": "බෙරු", "category": "plant" },
    { "word": "සාදෘශ්‍ය", "meaning": "සම වූ දිය හා ගල් ඇති ප්‍රදේශය", "category": "general" },
    { "word": "සාදික්කායි", "meaning": "ලමඟ පුවක් (සාදික්කා ගෙඩි)", "category": "plant" },
    { "word": "සාදිලිංගම්", "meaning": "හිඟුල් (නිබහුල)", "category": "mineral" },
    { "word": "සාදුකණ්ටො", "meaning": "කටු කිහිරි", "category": "plant" },
    { "word": "සාදු පුෂ්ප", "meaning": "ගොඩ නෙළුම්", "category": "plant" },
    { "word": "සාදුපුෂ්පී", "meaning": "මයිල ගස", "category": "plant" },
    { "word": "සාදුවෘක්‍ෂ", "meaning": "ලුණුවරණ, කොළොම් ගස", "category": "plant" },

    // --- පිටුව 483 ---
    { "word": "සානු", "meaning": "ඝන වූ දෙය, සිනිඳු දෙය", "category": "general" },
    { "word": "සානුපුෂ්ප", "meaning": "බුළු ගස", "category": "plant" },
    { "word": "සාන", "meaning": "මිදටිය 15 ක බර", "category": "general" },
    { "word": "සානය", "meaning": "සය අකක්", "category": "general" },
    { "word": "සාති", "meaning": "කොරාසානි", "category": "plant" },
    { "word": "සානු", "meaning": "මහ සාරණ", "category": "plant" },
    { "word": "සානුප්", "meaning": "කොත්තමල්ලි, පොකුරු", "category": "plant" },
    { "word": "සාබරි", "meaning": "යක්බේරිය", "category": "plant" },
    { 
        "word": "සාම්බ්‍රානි", 
        "meaning": "<b>කුන්දිරුක්කන්</b><br><br>ගසේ මුලින් සහ කඳින් ද නිකුත්වෙන දුම්මල වැනි මැලියම් සාම්බ්‍රානි නමින් ගෙවල් සුගන්ධවත් කරණ, විෂබීජ නාශක ද්‍රව්‍යයක් වශයෙන් දුම් ඇල්ලීමට පාවිච්චි කරති.<br><br>දවට කොළ වලට සමාන කොළ ඇති සුදු පාට කඳකින් යුත් අඩි පණහක් පමණ උසට වැවෙන ගසකි. මේ ගසේ ඇට හොර ගසේ ඇට වලට මඳක් සමාන ය. පියාපත් බඳු ය.", 
        "category": "plant",
        "image": "img_sambrani_kundirukkan.jpg"
    },
    { "word": "සාමිනුවා", "meaning": "රත් ලොත්", "category": "plant" },
    { "word": "සාමිනාර", "meaning": "සාම්බර දේශයෙහි ලුණු", "category": "mineral" },
    { "word": "සාම", "meaning": "රුක් ගස, ඉරමුසු", "category": "plant" },
    { "word": "සාමං", "meaning": "සුවඳ, ඉරමුසු", "category": "plant" },
    { "word": "සාමදාන", "meaning": "කොළය කඩා නැවත එකතු කළ විට පෑස්සෙන සිංහ මුඛ කොළ වැනි කොළ ඇති කුඩා පැළෑටියක්", "category": "plant" },
    { "word": "සාමවල්ක / සාමවෘක්‍ෂ", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "සාමා", "meaning": "පෝටා වැල, පුවඟු, කළු තුස්තවාළු, ඉරමුසු", "category": "plant" },
    { "word": "සාමී වෘක්‍ෂ", "meaning": "කැළ ගස", "category": "plant" },
    { "word": "සාමුද්‍ර / සාමුද්‍රක / සාමුද්‍රජ / සාමුද්‍රලවණ", "meaning": "මුදු ලුණු", "category": "mineral" },
    { "word": "සාමුද්‍රික", "meaning": "මුහුදු ලුණු", "category": "mineral" },
    { "word": "සායපුංඛා", "meaning": "පිල ගස", "category": "plant" },
    { "word": "සාර්ෂා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "සාර", "meaning": "අරටුව, වෙඬරු, යකඩ, සජී ක්‍ෂාර, මිතුර, රෝම ලුණු, මී ගස", "category": "mineral" },
    { "word": "සාරක", "meaning": "ජයපාල, ඇට්ටර", "category": "plant" },
    { "word": "සාරබදිර", "meaning": "හිඹුරු ගස", "category": "plant" },
    { "word": "සාරගන්ධි", "meaning": "සඳුන්", "category": "plant" },
    { "word": "සාරස", "meaning": "මීපැණි, මී ඉටි", "category": "animal" },
    { "word": "සාරබහ", "meaning": "නෙළුම් අල, සක, සඳුන්, කපුරු, කලාඳුරු", "category": "plant" },
    { "word": "සාරප්", "meaning": "වෙඬරු", "category": "food" },

    // --- පිටුව 484 ---
    { "word": "සාරණ", "meaning": "අතිසාරය, වැල් බැබිල, ඇම්බරැල්ල", "category": "plant" },
    { "word": "සාරණී", "meaning": "සාරණ, යොහොඹු, ආපසු මුදු", "category": "plant" },
    { "word": "සාරණෙ", "meaning": "සාරණ", "category": "plant" },
    { "word": "සාරතර", "meaning": "කෙනෙල් ගස", "category": "plant" },
    { "word": "සාරතෙල", "meaning": "ගෝසාල වැල", "category": "plant" },
    { "word": "සාර්දි", "meaning": "ලියනඟලා, රුක් අත්තන, රණවරා, කටුකරෝහිණී", "category": "plant" },
    { "word": "සාරද්‍රැම", "meaning": "කිහිරි", "category": "plant" },
    { "word": "සාරපුෂ්ප", "meaning": "පියා ගස, සල් ගස", "category": "plant" },
    { "word": "සාරමහා", "meaning": "බැබිල", "category": "plant" },
    { "word": "සාරමුෂිකා", "meaning": "දේවදාලිය", "category": "plant" },
    { "word": "සාරස", "meaning": "බට", "category": "plant" },
    { "word": "සාරලජ", "meaning": "අබ", "category": "plant" },
    { "word": "සාරවතී", "meaning": "සැමගස", "category": "plant" },
    { "word": "සාරවීරතරු", "meaning": "අන්දර ගස", "category": "plant" },
    { "word": "සාරස (2)", "meaning": "සුදු නෙළුම්, සවිඳව ලුණු, නෙළුම්, මීපැණි, ලුණු රස", "category": "general" },
    { "word": "සාරශ්‍රෙෂ්ඨා", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "සාරා", "meaning": "කලු තුස්තවාළු, රතණ, මී මෑ, දෙළුම්, බෝදි ගස, ලුණුවරණ", "category": "plant" },
    { "word": "සාරාල", "meaning": "තල ගස (තිල)", "category": "plant" },
    { "word": "සාරිණී", "meaning": "කපු ගස, මඟුල් කුඹුරු වැන්න, ඇල් කහඹිලියා, රන්වන් ඇට්ටර, ආපසු මුදු, රතු සාරණ", "category": "plant" },
    { "word": "සාරිබා", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "සාරිබි", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "සාරි", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "සාරී(තා)ණ", "meaning": "ගොඩමානෙල්, කහඹිලියා, ආපසු මුදු, රතු සාරණ, කපු ගස", "category": "plant" },
    { "word": "සාල්මලි", "meaning": "ඉඹුල් ගස", "category": "plant" },
    { "word": "සාල්මලි නිර්‍ය්‍යාස", "meaning": "හිඹුල් ලාටු", "category": "plant" },
    { "word": "සාල්මාර", "meaning": "ඉඹුල් ලාටු", "category": "plant" },
    { "word": "සාල", "meaning": "සල් ගස, දුම්මල", "category": "plant" },
    { "word": "සාලන / සාලනියර්‍ය්‍යාස", "meaning": "දුම්මල", "category": "plant" },
    { "word": "සාලපර්ණී", "meaning": "මෙවන්, අස්වැන්න", "category": "plant" },
    { "word": "සාලපුෂ්ප", "meaning": "ගොඩපියුම්", "category": "plant" },
    { "word": "සාලය", "meaning": "අඹගස", "category": "plant" },
    { "word": "සාලරස / සාලවෙෂට", "meaning": "දුම්මල", "category": "plant" },
    { "word": "සාලස්මා", "meaning": "තල් ගස", "category": "plant" },
    { "word": "සාලස්සර්ජ", "meaning": "බුරුත ගස", "category": "plant" },
    { "word": "සාලස", "meaning": "සල් ගස", "category": "plant" },
    { "word": "සාලසාරක", "meaning": "මුරුත ගස", "category": "plant" },
    { 
        "word": "සාලාදි ගණය", 
        "meaning": "සල්, කොඹු (කෝන්), රන්වන් කෑල, (වෙනි වැල්), දව ගස්, සදෙල (රන්වන් සල්), කුඹුක්, පියා, මහරී, ඇට්ටර, රුක් බූරුද (සාරණ), කිහිරි හර, හෙළ - රත් හඳුන් දේවගය, හිඹුරු, රත් මුරුත, කරද (සිරිල), තිඹිරි, කලු වැල් (අගිල්) යන මේ ශාලාදි ගණය සෙම්රෝග, කැසීම, චර්ම රෝග, කුෂ්ඨ, ප්‍රමේහ යන මේ රෝග නසන්නේ ය.", 
        "category": "compound" 
    },
    { "word": "සාලි", "meaning": "හාල් = (වී වර්ගයක්)", "category": "plant" },
    { "word": "සාලුකා", "meaning": "ඕළු, සාදික්කා, මානෙල් අල", "category": "plant" },
    { "word": "සාලෙය", "meaning": "ශතපුෂ්ප, පද්මකාෂ්ඨ", "category": "plant" },
    { "word": "සාලො", "meaning": "සල්ගස", "category": "plant" },
    { "word": "සාවඟ", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "සාවර", "meaning": "ලොත්", "category": "plant" },
    { "word": "සාවරක", "meaning": "ලොත් ගස", "category": "plant" },
    { "word": "සා වසුරු", "meaning": "නැබේටි", "category": "plant" },
    { "word": "සාවාසද", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "සාවිතෘ", "meaning": "වරා", "category": "plant" },
    { "word": "සාසප", "meaning": "අබ", "category": "plant" },
    { "word": "සාසින්", "meaning": "චම්මුතු, (කලාඳුරු)", "category": "plant" },

    // --- පිටුව 485 ---
    { "word": "සැඩරැස්", "meaning": "වරා", "category": "plant" },
    { "word": "සැඩොල්", "meaning": "සාල්", "category": "plant" },
    { "word": "සෑනි", "meaning": "මල්කැත", "category": "plant" },
    { "word": "සැපිටි", "meaning": "(උරලා) සට්ටම්", "category": "general" },
    { "word": "සැබෝ", "meaning": "කරල් සැබෝ", "category": "plant" },
    { "word": "සැබෝ සල්", "meaning": "කරල් සැබෝ ඇට", "category": "plant" },
    { "word": "සෑම", "meaning": "වේලඟ", "category": "plant" },
    { "word": "සැර", "meaning": "මලාව = (පාස=පෙට්ටිය)", "category": "general" },
    { "word": "සැලඹ", "meaning": "හාළඹ, (හැලි අඹ - ලොකු අඹ) බක්මී ගස් වලට බොහෝ සෙයින් සමාන හැලඹ නමැති වෙන ගස් වර්ගයක් ද තිබේ.", "category": "plant" },
    { "word": "සැලිමුහුනු", "meaning": "සුදු මුහු අල", "category": "plant" },
    { "word": "සැවාන්දව", "meaning": "සුවඳ හොට (සැවැන්දරා)", "category": "plant" },
    { "word": "සැවාන්දන", "meaning": "සැවැන්න = (සැවැන්දරා)", "category": "plant" },
    { "word": "සැවාන්දරා", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "සැවාන්දෙව", "meaning": "සුවඳහොට", "category": "plant" },
    { "word": "සැවාන්ත මුල්", "meaning": "බබුස් තණ", "category": "plant" },
    { "word": "සැවුලු", "meaning": "කුකුළා", "category": "animal" },
    { "word": "සැහායුරු", "meaning": "අඹ", "category": "plant" },
    { "word": "සැලඹු", "meaning": "සෑලි අඹ, (ලොකු අඹ)", "category": "plant" },
    { "word": "සිංගාටෝ", "meaning": "ගොකටු", "category": "plant" },
    { "word": "සිංවත", "meaning": "ආඬාතෝඩං", "category": "plant" },
    { "word": "සිංගපා", "meaning": "ඉත්තෑව ගස, ඇට්ටර ගස", "category": "plant" },
    { "word": "සිංග", "meaning": "රන් මුරුංගා ගස, මූණමල් ගස, වංඇපල", "category": "plant" },
    { "word": "සිංහක", "meaning": "වංඇපල", "category": "plant" },
    { "word": "සිංහකෙසර", "meaning": "මූණමල් ගස", "category": "plant" },
    { "word": "සිංහතුණ්ඩ", "meaning": "දළුක්", "category": "plant" },
    { "word": "සිංහනාදිකා", "meaning": "ඇල් කහඹිලියා", "category": "plant" },
    { "word": "සිංහපර්ණී", "meaning": "වංඇපල ගස", "category": "plant" },
    { "word": "සිංහපුච්ඡී", "meaning": "මස්වැන්න, පුස්වැන්න, අස්වැන්න", "category": "plant" },
    { "word": "සිංහපුච්ඡිකා", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "සිංහපුෂ්පා", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "සිංහමුඛ", "meaning": "ආඬාතෝඩං, (මෙහි සිංහ මුඛාකාර මල් පිපෙන හෙයින් සිංහමුඛ යයි කියති)", "category": "plant" },
    { "word": "සිංහමුඛී", "meaning": "පුස්වැන්න, මස්වැන්න, වංඇපල", "category": "plant" },
    { "word": "සිංහමුත්‍ර", "meaning": "වැලි", "category": "mineral" },
    { "word": "සිංහල", "meaning": "කුරුඳු ගස", "category": "plant" },
    { "word": "සිංහලක", "meaning": "පින්තල, නික ගස", "category": "plant" },
    { "word": "සිංහලාඞ්ගුලී", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "සිංහවින්නා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "සිංහා", "meaning": "යකඩ මල", "category": "mineral" },
    { "word": "සිංහාද්‍යස්නා", "meaning": "වංඇපල", "category": "plant" },
    { "word": "සිංහාන", "meaning": "යකඩ මල", "category": "mineral" },
    { "word": "සිංහාස්‍ය", "meaning": "වංඇපල", "category": "plant" },
    { "word": "සිංහිකා", "meaning": "වංඇපල", "category": "plant" },
    { "word": "සිංහී", "meaning": "එළ බටු, කටුවැල් බටු, වම්බටු, මුංවැන්න, වංඇපල", "category": "plant" },
    { "word": "සිංහුණ්ඩී", "meaning": "මහ උක්, වැල් මුරුංගා", "category": "plant" },
    { "word": "සික්ථ", "meaning": "මී ඉටි, බෙරු", "category": "animal" },
    { "word": "සික්ථක", "meaning": "මී ඉටි", "category": "animal" },
    { "word": "සිකතා මේහ", "meaning": "ප්‍රමේහ රෝගයක්", "category": "treatment" },
    { "word": "සිකතා", "meaning": "වැලි", "category": "mineral" },
    { "word": "සිකණ්ඩි", "meaning": "කටුපිල", "category": "plant" },
    { "word": "සිකා", "meaning": "කිරි බදු වැල", "category": "plant" },
    { "word": "සිකාපතු", "meaning": "රත්එරබදු", "category": "plant" },
    { "word": "සිකි", "meaning": "පල්මාණික්කන්", "category": "mineral" },
    { "word": "සිකිඟිව", "meaning": "පල්මාණික්කන්", "category": "mineral" },
    { "word": "සිකුරුපියලි", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "සිඛණ්ඩි", "meaning": "කටුපිල", "category": "plant" },
    { "word": "සිඛණ්ඩිකා", "meaning": "කටුපිල", "category": "plant" },
    { "word": "සිඛණ්ඩී", "meaning": "ඔලිඳ, පිච්ච වැල", "category": "plant" },
    { "word": "සිඛර", "meaning": "යබොර, වසාංවාසි", "category": "mineral" },
    { "word": "සිඛරා", "meaning": "බුලත්", "category": "plant" },

    // --- පිටුව 486 ---
    { "word": "සිඛරි", "meaning": "කුන්දිරුක්කන්, ඇපල, තෙලගස", "category": "plant" },
    { "word": "සිඛා", "meaning": "රත් එරබු", "category": "plant" },
    { "word": "සිඛි", "meaning": "රත් නිටුල්", "category": "plant" },
    { "word": "සිඟු", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සිඟී", "meaning": "වංඇපල", "category": "plant" },
    { "word": "සිඟිවෙර", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "සිඞ්ගි", "meaning": "දේවදාර", "category": "plant" },
    { "word": "සිඞ්ගිලිකොසි", "meaning": "හිඟුරු වැල්", "category": "plant" },
    { "word": "සිඞ්ඝාටො", "meaning": "ගොකටු", "category": "plant" },
    { "word": "සිඞ්ඝාණ", "meaning": "යබොර", "category": "mineral" },
    { "word": "සිඤ්චිතා", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "සිටාමල්ලී", "meaning": "අස්වැන්න", "category": "plant" },
    { "word": "සිතනම්පිටි", "meaning": "බැබිල", "category": "plant" },
    { "word": "සිතනලෙ", "meaning": "හීන් එන්සාල්", "category": "plant" },
    { "word": "සිතතලෙප්පාටු", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "සිතක", "meaning": "මී ඉටි, මීපැණි", "category": "animal" },
    { "word": "සිත", "meaning": "රිදී, අලපාහි, සඳුන්, ගොඩු වනු, කපුරු, මුඛ රෝගයක්, මැණික්වැන්න, සීනි, සුදු පාටා නම්, වී", "category": "general" },
    { "word": "සිතකර", "meaning": "කපුරු", "category": "plant" },
    { "word": "සිතකර්ණී", "meaning": "වංඇපල", "category": "plant" },
    { "word": "සිතකුලක", "meaning": "බැබිල", "category": "plant" },
    { "word": "සිතග", "meaning": "එළ ඉඹුල් ගස", "category": "plant" },
    { "word": "සිතගුජා", "meaning": "සීනි, සුදුහඳුරු", "category": "food" },
    { "word": "සිතගුඤ්ජා", "meaning": "එළ ඔලිඳ", "category": "plant" },
    { "word": "සිතච්ඡත්‍ර", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "සිතච්ඡද", "meaning": "එළ රතණ", "category": "plant" },
    { "word": "සිතදර්භ", "meaning": "එළ කුසතණ", "category": "plant" },
    { "word": "සිතදිප්‍ය", "meaning": "සුදු දුරු", "category": "plant" },
    { "word": "සිතදූර්වා", "meaning": "එළ රතණ", "category": "plant" },
    { "word": "සිතද්‍රොන", "meaning": "ගැටතුඹ, යොන්තුඹ", "category": "plant" },
    { "word": "සිතධාතු", "meaning": "හටුවැල්බටු", "category": "plant" },
    { "word": "සිතපක්‍ෂී", "meaning": "වරාගස", "category": "plant" },
    { "word": "සිතපුෂ්ප", "meaning": "හෙලකටරොලු, හෙළ බටු, තුවරලා", "category": "plant" },
    { "word": "සිතපුෂ්පා", "meaning": "කොටවිලයාමුරු, තුවරලා, කුසතණ, එළ එරබදු, එළ රතණ, බෝලිද්ද", "category": "plant" },
    { "word": "සිතපුසු", "meaning": "පුස්සමින්", "category": "plant" },
    { "word": "සිතරතට", "meaning": "සුදු හඳුන්", "category": "plant" },
    { "word": "සිතමරිච", "meaning": "එළ මිරිස්", "category": "plant" },
    { "word": "සිතමාස", "meaning": "මහ මෑ", "category": "plant" },
    { "word": "සිතමු", "meaning": "කපුරු", "category": "plant" },
    { "word": "සිතලා", "meaning": "තලා", "category": "plant" },
    { "word": "සිතලෙබා", "meaning": "කබසකුරු", "category": "plant" },
    { "word": "සිතවර්ෂාභු", "meaning": "එළ සාරණ", "category": "plant" },
    { "word": "සිතසායක", "meaning": "එළ පියගස", "category": "plant" },
    { "word": "සිතසිම්බිකා", "meaning": "තිරිඟු", "category": "plant" },
    { "word": "සිතශූරණ", "meaning": "වල් කිඩාරම්", "category": "plant" },
    { "word": "සිතසර්ෂප", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "සිතහිමි", "meaning": "සුදු හඳුන්", "category": "plant" },
    { "word": "සිතා", "meaning": "සුදු හඳුන්, සීනි, වදකසා", "category": "plant" },
    { "word": "සිතාඛණ්ඩ", "meaning": "මීහකුරු", "category": "food" },
    { "word": "සිතාණ්ඩිකා", "meaning": "සුළුසාරණ, මහ සාරණ", "category": "plant" },
    { "word": "සිතාබ්ජ", "meaning": "සුදු පියුම", "category": "plant" },
    { "word": "සිතාභ / සිතාභ්‍ර / සිතාභ්‍රැ / සිතාභ්‍රැක", "meaning": "කපුරු, මෝරු", "category": "plant" },
    { "word": "සිතාම්බුජ", "meaning": "හෙළ නෙළුම්", "category": "plant" },
    { "word": "සිතාර්ජක", "meaning": "සුදුතලා", "category": "plant" },
    { "word": "සිතාර්ජුන", "meaning": "මුරුත", "category": "plant" },
    { "word": "සිතාරත්න", "meaning": "හීන්අරත්ත", "category": "plant" },
    { "word": "සිතාරුණී", "meaning": "කුෂ්ඨ රෝගයක්", "category": "treatment" },
    { "word": "සිතාලක", "meaning": "සුදු මදාරා", "category": "plant" },
    { "word": "සිතාලතා", "meaning": "සුදු රතණ", "category": "plant" },
    { "word": "සිතවාර", "meaning": "කිඹුල්වැන්න", "category": "plant" },
    { "word": "සිතු", "meaning": "පලොල් රුක", "category": "plant" },
    { "word": "සිතුබන්", "meaning": "සුන්සාල් බත්", "category": "food" },
    { "word": "සිතුලා", "meaning": "තලා", "category": "plant" },
    { "word": "සිතෙකර", "meaning": "කොල්ලු, එළ රතණ", "category": "plant" },
    { "word": "සිතොග්‍රා", "meaning": "හෙළ වදකසා", "category": "plant" },


//පිටු 487 සිට 492 දක්වා සියලුම වචන සහ විස්තර


    // --- පිටුව 487 ---
    { "word": "සිතොපල", "meaning": "පබළු, එළබටු, සීනි", "category": "plant" },
    { "word": "සිඬ", "meaning": "සවිඳව, කවඅත්තන, සීනි", "category": "plant" },
    { "word": "සිඬක", "meaning": "නිකගස, සල්ගස", "category": "plant" },
    { "word": "සිඬජල", "meaning": "කාඩි", "category": "liquid" },
    { "word": "සිඬභො", "meaning": "අබ", "category": "plant" },
    { "word": "සිඬධාතු", "meaning": "රසදිය", "category": "mineral" },
    { "word": "සිඬපුෂ්ප", "meaning": "කණේරු", "category": "plant" },
    { "word": "සිඬප්‍රයොජන", "meaning": "සුදු අබ", "category": "plant" },
    { "word": "සිඬම", "meaning": "කුෂ්ඨ රෝගයක්, (ලාදුරු)", "category": "treatment" },
    { "word": "සිඬමුලිකොළ", "meaning": "වරා කොළ", "category": "plant" },
    { "word": "සිඬරස", "meaning": "රසදිය", "category": "mineral" },
    { "word": "සිඬසාධක", "meaning": "සුදු අබ", "category": "plant" },
    { "word": "සිඬාඞ්ගී", "meaning": "නුග ගස, අබ", "category": "plant" },
    { "word": "සිද්ධි", "meaning": "සුළුදඹකලත්, පළගස, වැටකොළු, කිතුල් ගස", "category": "plant" },
    { "word": "සිද්ධිහුරු", "meaning": "වියළි ඉඟුරු", "category": "plant" },
    { "word": "සිලු", "meaning": "සෙනෙඛ ලුණු", "category": "mineral" },
    { "word": "සිලුජල", "meaning": "මූහුදු දිය හෝ මුදු ජලය", "category": "liquid" },
    { "word": "සිලුපෙන", "meaning": "මුහුදු පෙණ", "category": "mineral" },
    { "word": "සිලුබිජු", "meaning": "අබ", "category": "plant" },
    { "word": "සිලුලුණු", "meaning": "සවිඳලුණු", "category": "mineral" },
    { "word": "සිලුවර", "meaning": "නික, ලුණුවරණ", "category": "plant" },
    { "word": "සිලුවරපත්", "meaning": "නිකකොළ", "category": "plant" },
    { "word": "සිලුවරණ", "meaning": "නික", "category": "plant" },
    { "word": "සිලුහත්", "meaning": "අබ", "category": "plant" },
    { "word": "සිලුහත්සුණු", "meaning": "අබකුඩු", "category": "plant" },
    { "word": "සිලුහතු", "meaning": "අබ", "category": "plant" },
    { "word": "සිලුහතු තෙල්", "meaning": "අබ තෙල්", "category": "liquid" },
    { "word": "සිධිම", "meaning": "කුෂ්ඨ රෝගයක්, (ලාදුරු)", "category": "treatment" },
    { "word": "සිධු", "meaning": "මීපැණි", "category": "liquid" },
    { "word": "සිධුපුෂ්පී", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සිත්සාටක", "meaning": "කොකැටිය", "category": "plant" },
    { "word": "සිත්කල්", "meaning": "කිතුල්, (හින්තාල) රසකිඳ", "category": "plant" },
    { "word": "සිත්තිල්", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "සින්දු", "meaning": "සවිඳලුණු, තොවිල ගස", "category": "plant" },
    { "word": "සින්ද්‍ර(ක්‍ර)ක", "meaning": "නිකගස", "category": "plant" },
    { "word": "සින්දුකොඩි", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "සින්දූර", "meaning": "සින්දූරම්, රතු ඊයම්", "category": "mineral" },
    { "word": "සින්දූරකාරණ", "meaning": "ඊයම්", "category": "mineral" },
    { "word": "සින්දුවාර", "meaning": "නිකගස, නිකමල", "category": "plant" },
    { "word": "සින්දුවාරිකා", "meaning": "නික ගස", "category": "plant" },
    { "word": "සින්දූරමි", "meaning": "රසබෙහෙත, (රසභෂ්ම) චූර්ණය", "category": "compound" },
    { "word": "සින්දූරි", "meaning": "එරබදු ගස, මිලනගස", "category": "plant" },
    { "word": "සින්ධු", "meaning": "සවිඳව, ඇත්දළ, පලිඟු, සුදු පුස්කර", "category": "mineral" },
    { "word": "සින්ධුකඵ", "meaning": "මුහුදුපෙණ", "category": "mineral" },
    { "word": "සින්ධුකාර", "meaning": "සුදු පුස්කර", "category": "plant" },
    { "word": "සින්ධුජ", "meaning": "සවිඳව", "category": "mineral" },
    { "word": "සින්ධුත්‍ථ", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "සින්ධුති", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "සින්ධුත්‍ථභව", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "සින්ධුඵල", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "සින්ධුපුෂ්ප", "meaning": "කුසුමාඤ්ජන, සක්, මලිත", "category": "mineral" },
    { "word": "සින්ධුමන්ථජ", "meaning": "අමෘත,සවිඳවලුණු", "category": "mineral" },
    { "word": "සින්ධුලවන", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "සින්ධුවරිත", "meaning": "නිකගස", "category": "plant" },
    { "word": "සින්ධුවාර", "meaning": "නික, හෙළ නික", "category": "plant" },
    { "word": "සින්ධුවාරක", "meaning": "නික ගස", "category": "plant" },
    { "word": "සින්ධුවාරච්ඡද", "meaning": "නික, කවණික", "category": "plant" },
    { "word": "සින්ධුවාරිකා", "meaning": "නිකගස", "category": "plant" },
    { "word": "සින්ධුවෙසක", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "සින්දූර", "meaning": "සින්දූරම්", "category": "mineral" },
    { "word": "සින්තෙලම්", "meaning": "සිහින් එන්සාල්", "category": "plant" },
    { "word": "සිත්‍ය", "meaning": "වම්මුතු", "category": "plant" },
    { "word": "සින්හි", "meaning": "කටුවැල්බටු, එළබටු, වංඇපල", "category": "plant" },
    { "word": "සිනකර", "meaning": "සිනක්කාරම්", "category": "mineral" },
    { "word": "සිනිකර", "meaning": "සිනක්කාරම්", "category": "mineral" },
    { "word": "සිනිද", "meaning": "අඹ", "category": "plant" },
    { "word": "සිනිබලා", "meaning": "සියඹලා", "category": "plant" },
    { "word": "සිප්", "meaning": "නිකගස, මුල", "category": "plant" },
    { "word": "සිපා", "meaning": "නුග ඇටුවත්, මුල", "category": "plant" },
    { "word": "සිම්බකණ්ටිකා", "meaning": "කිරිඳි", "category": "plant" },
    { "word": "සිම්බලු", "meaning": "කොළ ඉඹුල්", "category": "plant" },
    { "word": "සිම්බලි", "meaning": "ඉඹුල්", "category": "plant" },
    { "word": "සිම්බා(ම්බි)", "meaning": "වඳුරු මෑ", "category": "plant" },

    // --- පිටුව 488 ---
    { "word": "සිම්බිජා", "meaning": "කොල්ලු", "category": "plant" },
    { "word": "සිම්බිල", "meaning": "හිඹුල්, අවර", "category": "plant" },
    { "word": "සිම්බී", "meaning": "මුංවැන්න", "category": "plant" },
    { "word": "සිම්බිධාන්‍ය", "meaning": "උඳු; මුං ආදිය", "category": "plant" },
    { "word": "සියන්දුඹුලු", "meaning": "වියන්දුඹුලු", "category": "general" },
    { "word": "සියපත්", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "සියම්බිදි", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "සියම්බිදිපත්", "meaning": "මුද්දරප්පලම් මිරිකා පෙරා ගත් ජලය", "category": "liquid" },
    { "word": "සියඹිර", "meaning": "ඉඟුරුපියලි", "category": "plant" },
    { "word": "සිර", "meaning": "ඉස, නිප්පිලිමුල්, පලොල්ගස", "category": "plant" },
    { "word": "සිරසනන්ත", "meaning": "සුළුකරඹ", "category": "plant" },
    { "word": "සිරසලොද", "meaning": "කරපිංචා", "category": "plant" },
    { "word": "සිරා", "meaning": "කිරිඅඟුණ", "category": "plant" },
    { "word": "සිරි", "meaning": "බෙලි, ඉළුක්", "category": "plant" },
    { "word": "සිරිකට", "meaning": "සඳුන්", "category": "plant" },
    { 
        "word": "සිරිතේක්කු", 
        "scientific": "Premna Tomentosa",
        "meaning": "<b>Premna Tomentosa-සිරිතේක්කු</b><br><br>මුල් පෑලවීමෙන් විශාල ලෙස බෝවී යන භාරඞ්ගි ආදි නම් රාශියකින් හැඳින්වෙන සිරිතේක්කු ගස ඉන්දියාවෙහි මෙන් ම ලංකාවෙහි ද මැනවින් වැවෙයි. ගස මේරූනවිට මුදුනෙහි රතු-සුදු පැහැයෙන් යුත් මල් පොකුරු පිපෙන මේ ගසේ ඖෂධ සඳහා ගන්නේ ගැට සහිත මුල් ය.<br><br>මේ මුල් උණ-කාස-ශ්වාස-ජලෝදර හා වාතාබාධ සඳහා ගන්නා ඖෂධ යෝග වලට එකතු කරති.", 
        "category": "plant",
        "image": "img_premna_tomentosa_siritekku.jpg"
    },
    { "word": "සිරිකඩ", "meaning": "හඳුන්ගස", "category": "plant" },
    { "word": "සිරිකමල", "meaning": "සඳුන්", "category": "plant" },
    { "word": "සිරිකුමිල්", "meaning": "කරබෙහිය", "category": "plant" },
    { "word": "සිරිනාගි", "meaning": "මදටිය", "category": "plant" },
    { "word": "සිරිවි", "meaning": "අඩනහිරිය", "category": "plant" },
    { "word": "සිරිපත්", "meaning": "ගල්මද", "category": "mineral" },
    { "word": "සිරිදල", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "සිරිපර්ණී", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "සිරිපල", "meaning": "බෙලි", "category": "plant" },
    { "word": "සිරිමල්", "meaning": "වසාංවාසි", "category": "plant" },
    { "word": "සිරියල", "meaning": "හිරියල=හිරිතල (අල වර්ගයක්)", "category": "plant" },
    { "word": "සිරියෙල්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "සිරිල", "meaning": "පණුකරඹ, කුණුකරඳ", "category": "plant" },
    { "word": "සිරිවටු", "meaning": "ශ්‍රීවෙෂට=වාක්‍ෂධූප= සරලද්‍රව=(සිරිවටු වශයෙන් හොරඉටි(හොරදුම්මල) ගත යුතු බැව් පෙනෙන නමුත් වැඩි දෙනා ගන්නේ හොර අරටුව ය.)", "category": "plant" },
    { "word": "සිරිවාසො", "meaning": "සරලදව", "category": "plant" },

    // --- පිටුව 489 ---
    { 
        "word": "සිරිවැඩිබැවිල", 
        "scientific": "Sida Alba",
        "meaning": "<b>Sida Alba- සිරිවැඩිබැවිල (නාගබලා)</b><br><br>දම්පාට මිශ්‍ර සුදු පාටින් යුත් මල් ගසපුරා ම පිපෙන අඩි හතරක් පහක් පමණ උසට වැවෙන බැවිල වර්ගයට අයත් ඉතාම ලක්‍ෂණ ගස නාගබලා නම් වූ සිරිවැඩි බැවිල ගස යි. නාගබලා වෙනුවට ගත යුත්තේ ගස්කැළිය නොව මේ සිරිවැඩි බැවිල ය. මෙය වා-පිත්-සෙම් සමනය හා සෞම්‍ය ධාතු වර්ධන ය කරණ වාජීකරණ ඖෂධයකි. බැවිල වර්ග ගණ විස්තරයක් 332 පිටේ ඇත.", 
        "category": "plant",
        "image": "img_sida_alba_siriwadibawila.jpg"
    },
    { "word": "සිරිසලොද", "meaning": "සබරල", "category": "plant" },
    { "word": "සිරිෂ", "meaning": "මාරාගස, මහරීගස", "category": "plant" },
    { "word": "සිරුකීරෙ", "meaning": "සුළුකූර", "category": "plant" },
    { "word": "සිරුක්ති", "meaning": "අගිල්", "category": "plant" },
    { "word": "සිරූපයරු", "meaning": "හීන්මුංඇට", "category": "plant" },
    { "word": "සිරුපිලෙලෙ", "meaning": "පොල්පලා", "category": "plant" },
    { "word": "සිරුපුන්නෙ", "meaning": "කිනදොඹ", "category": "plant" },
    { "word": "සිරුපුල්ලඩි", "meaning": "මුංවැන්න", "category": "plant" },
    { "word": "සිරුමරම්", "meaning": "කුඩා ගස්", "category": "plant" },
    { "word": "සිරුමුගස්තෙ", "meaning": "සින්දුමැඬ", "category": "plant" },
    { "word": "සිරුවලුනියෙ", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "සිරෝමූර්තු", "meaning": "ශීර්ෂ රෝගයක්", "category": "treatment" },
    { "word": "සිරෝසූල", "meaning": "ඉසරුජාව", "category": "treatment" },
    { "word": "සිලපි", "meaning": "සක්නැබ", "category": "animal" },
    { "word": "සිල්ලකි", "meaning": "කෙහෙල් ගස", "category": "plant" },
    { "word": "සිල", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "සිලන්දු", "meaning": "කුෂ්ඨ රෝගයක්", "category": "treatment" },
    { "word": "සිලා", "meaning": "ගල, වැටකොළු", "category": "plant" },
    { "word": "සිලාජතු", "meaning": "ගල්මද", "category": "mineral" },
    { "word": "සිලාජතු (2)", "meaning": "කොල්ලු", "category": "plant" },
    { "word": "සිලාභෙද", "meaning": "පොල්පළා", "category": "plant" },
    { "word": "සිලායනි", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "සිලායු", "meaning": "\"සිලායු\" නම් මුඛරෝගය", "category": "treatment" },
    { "word": "සිලායුෂ", "meaning": "පොල්පළා", "category": "plant" },
    { "word": "සිලිල්", "meaning": "ඉරිවේරිය, වතුර", "category": "plant" },
    { "word": "සිලිල්‍ද", "meaning": "චම්මුතු", "category": "plant" },
    { "word": "සිලිල්දත්", "meaning": "පියුම්", "category": "plant" },
    { "word": "සිලිල", "meaning": "සිහල ජලය, දියපාර, (සිලිලාර) එල්පත, එල්පැන්", "category": "liquid" },
    { "word": "සිලිස්සන්", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "සිලු", "meaning": "මොණරපිල්, මොණරකුඩුම්බිය", "category": "plant" },
    { "word": "සිලුපාත්", "meaning": "ඇල්වතුර", "category": "liquid" },
    { "word": "සිළුමිණි", "meaning": "ඔලිඳ", "category": "plant" },
    { "word": "සිලෙන්දි", "meaning": "මල්කූර", "category": "plant" },
    { "word": "සිවකැරිය", "meaning": "දෙළොස් කඳ, දොළොස් කිරිය", "category": "plant" },
    { "word": "සිව්කුඹුක්", "meaning": "කුඹුක් වර්ග හතර (දිය කුඹුක්, ගොඩකුඹුක්, රත්කුඹුක්, (අශ්වකර්ණ) කුඹුක්)", "category": "plant" },

    // --- පිටුව 490 ---
    { "word": "සිවිගුල්", "meaning": "ඇසළ ගස", "category": "plant" },
    { "word": "සිවිතුඹ", "meaning": "ගැටතුඹ, යොන්තුඹ, මල්තුඹ, ගෙඩි තුඹ, (තුඹකරිවිල)", "category": "plant" },
    { "word": "සිව්දල", "meaning": "ඇසළ ගස", "category": "plant" },
    { "word": "සිව්දූ", "meaning": "චතුර්ජාතක - (එන්සාල්, කරාබු, වසාංවාසි, සාදික්කා)", "category": "compound" },
    { "word": "සිව්රස", "meaning": "නීරස්ස", "category": "plant" },
    { "word": "සිව්රස්පොතු", "meaning": "නීරස්සපළු", "category": "plant" },
    { "word": "සිවිසානය", "meaning": "තුන්කලඳ", "category": "general" },
    { "word": "සිව", "meaning": "අරළු, මිණිරන්", "category": "plant" },
    { "word": "සිවග්‍රාජන", "meaning": "අරළු, රතුළූනු", "category": "plant" },
    { "word": "සිවත්ගුරු", "meaning": "සුවන්ගුරු", "category": "mineral" },
    { "word": "සිවන්තෙකෙ", "meaning": "තුස්තවාළු", "category": "plant" },
    { "word": "සිවන්දුප්පු", "meaning": "සිවසලුණු (සුවසලුණු)", "category": "mineral" },
    { "word": "සිමි", "meaning": "සම, සිවියවැල්", "category": "plant" },
    { 
        "word": "සිවිය", 
        "scientific": "Piper Chaba",
        "meaning": "<b>Piper Chaba-සිවිය / සිවියවැල් (ගජපිප්පලී)</b><br><br>සිවිය බුලත් කොළ වලට සමාන ඊට වඩා මඳක් ඝණ කොළ හා අඟල් අටක් පමණ දිග කරල් ඇති පිප්පලී ගණයට අයත් වැල් වර්ගයකි. මෙය ලංකාවෙහි මෙන් ම ඉන්දියා-ජාවා-සුමාත්‍රා යන රට වල ද මැනවින් වැවේ යි.<br><br>සිවිය-කාස, ශ්වාස, ශ්ලේෂ්ම, ජ්වර, වාත නාශක හා අග්නිදීපනය ඇති කරණ උෂ්ණකාරක ඖෂධයකි. දේශීය වෙදකමේ බොහෝ ඖෂධ යෝග වලට සිවිය මුල් ඇතුළත් කර තිබේ.", 
        "category": "plant",
        "image": "img_piper_chaba_siviya.jpg"
    },
    { "word": "සිවෙල්", "meaning": "කුඹුරු ඇට", "category": "plant" },
    { "word": "සිෂ්ටාසන", "meaning": "මැණික්වැන්න", "category": "plant" },
    { "word": "සිසක", "meaning": "ඊයම්", "category": "mineral" },
    { "word": "සිසපත්‍ර", "meaning": "ඊයම්", "category": "mineral" },
    { "word": "සිසි", "meaning": "කපුරු", "category": "plant" },
    { "word": "සිසිප්‍රිය", "meaning": "නිල්මානෙල්", "category": "plant" },
    { "word": "සිසිමෙලෙ", "meaning": "සියඹලා ගස", "category": "plant" },
    { "word": "සිසිර", "meaning": "සැවැන්න, ඉරිවේරිය", "category": "plant" },
    { "word": "සිසිරා", "meaning": "රතණ", "category": "plant" },
    { "word": "සිසිල", "meaning": "සඳුන්", "category": "plant" },
    { "word": "සිසුර", "meaning": "තලා", "category": "plant" },
    { "word": "සිහ්නකි", "meaning": "කෙහෙල් ගස", "category": "plant" },
    { "word": "සිහ්ල", "meaning": "තුරුක්තෙල්", "category": "liquid" },
    { "word": "සිහපුච්ඡී", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "සිහිකා", "meaning": "කාමරංගා", "category": "plant" },
    { "word": "සිහින්අක්මල්ල", "meaning": "හීන් අක්මල්ල", "category": "plant" },
    { "word": "සිහින්කස්", "meaning": "කුඩා දද හෝ කුෂ්ටය", "category": "treatment" },
    { "word": "සිහින්කසා", "meaning": "හීන් කසා ගස", "category": "plant" },
    { "word": "සිහින්මැඬහඟු", "meaning": "සිහින්මැස්බැද්ද", "category": "plant" },
    { "word": "සිහින්මිදි", "meaning": "හීන් මිදි ගස", "category": "plant" },
    { "word": "සිහිනැටි", "meaning": "හීනටි වී", "category": "plant" },
    { "word": "සිහිනිදි", "meaning": "හින්දුදි, සිනිද්ද", "category": "plant" },
    { "word": "සිහිල්", "meaning": "ඉරිවේරිය, සඳුන්", "category": "plant" },
    { "word": "සිහුණ්ඩ", "meaning": "දළුක්", "category": "plant" },

    // --- පිටුව 491 ---
    { "word": "සී", "meaning": "සිංහයා-වෘක්‍ෂාධිපතක (ගස් මුදුන්)", "category": "general" },
    { 
        "word": "සී අක්කා", 
        "meaning": "<b>සී අක්කා</b><br><br>සිනිද්ද හෝ සියඹලා කොළ වැනි කොළ හා අඟල් 6 x 1/2 ක් පමණ දිග-පළල ඇති කරල් පොකුරු සැදෙන අඩි පහළොහක් පමණ උසට වැවෙන දකුණු ඉන්දියාවෙන් ගෙනැවිත් මෙහි බෝකරණ ලද ගසකි.<br><br>මෙය චර්ම රෝග නාශක ඖෂධයකි. සමේ පිට සැදෙන අළුහන්-හොරි-දද-කුෂ්ඨ වලට මේ කරල්වල ඇට ඇල් දියෙන් අඹරා ඇඟේ ගා පැය බාගයකින් පමණ ඇල්වතුර නෑම කරති. මේ සේ සතියකට තුන් වරක් පමණ සති කිහිපයක් නොකඩවා නෑමෙන් සම්පූර්ණ සුවය ලබාගත හැක. ඒ කාලය තුළ සබන් ගෑම සුදුසු නැත.<br><br>එක වරක් පමණක් මේ ඇට අඹරා ගෑමෙන් පිට සමේ තිබෙන තෙල් ගතිය මඟහැරී සම හොඳින් පිරිසිදු වෙයි.", 
        "category": "plant",
        "image": "img_see_akka.jpg"
    },
    { "word": "සීකස", "meaning": "සිහින් කසා ගස", "category": "plant" },
    { "word": "සීගා", "meaning": "මුරුංගා ගස", "category": "plant" },
    { "word": "සීගාකා", "meaning": "වැල් මුරුංගා", "category": "plant" },
    { "word": "සීත", "meaning": "අගිල්, කිහිරි, සඳුන්, කටුපිල, ලෝලු, තුන් සුමුල, ගොමුවනු, පෝටා, (පුවටා)", "category": "plant" },
    { "word": "සීත උද්දල", "meaning": "ලෝලු", "category": "plant" },
    { "word": "සීතක", "meaning": "අගිල්, කර ගස, සීනි, කලු ඊයම්", "category": "plant" },
    { "word": "සීතකණ්‍යා", "meaning": "කහඹිලියා", "category": "plant" },
    { "word": "සීත කුම්භිකා", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "සීතකුලක", "meaning": "සුළු බැබිල", "category": "plant" },
    { "word": "සීතගන්ධි", "meaning": "සුදු හඳුන් ගස", "category": "plant" },
    { "word": "සීතගාත්‍රා", "meaning": "සන්නිපාත ජ්වර රෝගයක්", "category": "treatment" },
    { "word": "සීතපානි", "meaning": "කටුපිල", "category": "plant" },
    { "word": "සීතද්‍රොණි", "meaning": "යොන්තුඹ", "category": "plant" },
    { "word": "සීතපක්‍ෂ", "meaning": "කටුපිල", "category": "plant" },
    { "word": "සීතපල්ලව", "meaning": "බළුදම්", "category": "plant" },
    { "word": "සීතපාකි", "meaning": "කලීල වැල, කටුපිල", "category": "plant" },
    { "word": "සීතපුෂ්ප", "meaning": "හෙළ නික, මහ කරඹ", "category": "plant" },
    { "word": "සීතපුෂ්පී", "meaning": "ඇස් බැවිල", "category": "plant" },
    { "word": "සීතප්‍රිය", "meaning": "පැපිලිය-ඇල්කහඹිලියා", "category": "plant" },

    // --- පිටුව 492 ---
    { "word": "සීත ඵල", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "සීතබිහො", "meaning": "කපුරු", "category": "plant" },
    { "word": "සීත බහුල", "meaning": "කිහිරි", "category": "plant" },
    { "word": "සීතභීරු", "meaning": "ඉද්ද ගස", "category": "plant" },
    { "word": "සීතමාලා", "meaning": "අක්මැල්ල", "category": "plant" },
    { "word": "සීතල", "meaning": "කැකිරි, මහ කයිස්, ඇඹුල, නිලු මල්, සුලු බැබිල, බැවිල", "category": "plant" },
    { "word": "සීතලා", "meaning": "සුලු බැවිල, කැකිරි", "category": "plant" },
    { "word": "සීතලාරඤ්ජ", "meaning": "කපුරු", "category": "plant" },
    { "word": "සීතලාලය", "meaning": "එළ ජම්බු", "category": "plant" },
    { "word": "සීත වල්ලභා", "meaning": "බළුදම්", "category": "plant" },
    { "word": "සීතවර", "meaning": "ලෝලු", "category": "plant" },
    { "word": "සීතවාරක", "meaning": "කිරිඳි", "category": "plant" },
    { "word": "සීතවාරා", "meaning": "පුස්සමින්", "category": "plant" },
    { "word": "සීතවියලී", "meaning": "නිල් මහනෙල්, ඇඹුල", "category": "plant" },
    { "word": "සීතසහා", "meaning": "කෝමාරිකා", "category": "plant" },
    { "word": "සීත සිව", "meaning": "සවිඳව", "category": "mineral" },
    { "word": "සීත සෞගන්ධි", "meaning": "රත් මානෙල්", "category": "plant" },
    { "word": "සිතා", "meaning": "කෝමාරිකා", "category": "plant" },
    { "word": "සීතාර්ජක", "meaning": "අඳුතලා", "category": "plant" },
    { 
        "word": "සීතාලොලි", 
        "meaning": "මී වදලෙහි ඇලෙන පස් (නඟුලෙන් සී සාන විට පස කැපී යාම සඳහා සවිකර තිබෙන වානේ පතුරෙහි එකතු වන පස්, මේ පස් එකතු වන්නේ ඒ වානේ පතුර හා සම්බන්ධ වූ නඟුලීසේ මුල්ලෙහි ය. ඒ පස් රැගෙන ඇල් දියෙන් දිය කර පෙරා ගති කරණ (ඉතා) බෙහෙත් කැවී මෙන් විෂ ශරීර ගතවූ රෝගීන්ට පෙවීමෙන් සම්පූර්ණ සුවය ලැබේ. මෙය බුදුරජාණන් වහන්සේ විසින් (විනය පිටක - මහා වග්ග පාලි - භෙසජ්ජක්ඛන්ධක) සරදින්නා බාධය (ඉතා බෙහෙත් කැවීමෙන් ඇති වන රෝගය) ට නියම කර වදාරණ ලද බෙහෙතකි.", 
        "category": "treatment" 
    },
    { "word": "සීතිදාරකා", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "සීතිද්‍රොණි", "meaning": "යොන්තුඹ", "category": "plant" },
    { "word": "සීතිසාරක", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "සීධු", "meaning": "මී පැණි, උක් පැණියෙන් කළ සුරා", "category": "liquid" },
    { "word": "සීධුගන්ධ", "meaning": "මූණමල් ගස", "category": "plant" },
    { "word": "සීධුපුෂ්ප", "meaning": "මූණමල් ගස, මලිත, කොළොම්", "category": "plant" },
    { "word": "සීධුපුෂ්පී", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සීධුවල", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "සීධුරස", "meaning": "අඹගස", "category": "plant" },
    { "word": "සීන්", "meaning": "වංඇපල", "category": "plant" },
    { "word": "සීන් ගොඩ මේනේරිය", "meaning": "සිහින් මෙනේරි (ධාන්‍ය වර්ගයක්)", "category": "plant" },
    { "word": "සීනක්කාරම්", "meaning": "එනම් උප ධාතු (ලවණ) විශේෂය", "category": "mineral" },
    { "word": "සීන් තඹල", "meaning": "කුඩා කොළ ඇති තඹල වර්ගය (ඡායාරූප සහිත විස්තරයක් ඉදිරියෙහි ඇත)", "category": "plant" },
    { "word": "සීනවචුබම්", "meaning": "අමු කපුරු", "category": "plant" },
    { "word": "සීනමුල්", "meaning": "චීන දේශයෙන් ගෙනෙන ලද බෙහෙත් අල වර්ගයක් = (චොබචිනි=ඡායාරූප සහිත විස්තරයක් 192 පිටේ ඇත)", "category": "plant" },
    { "word": "සීනි", "meaning": "උක් ආදියෙහි පැණි උකු කර සාදා ගන්නා සිහින් කැට වර්ගයක්", "category": "food" },
    { "word": "සීනිදි", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "සීනුක්", "meaning": "පතොක් වර්ගයට අයත් පැළෑටියක්. මෙහි දඬු සිරස්ස පළු වලට වඩා මඳක් විශාල ය. හතරස් ය. නාරටිය දිගේ සිහින් කොළ තිබේ. කිරි ඇති - නැති සීනුක් දෙවර්ගයකි. මෙයින් ඖෂධ සඳහා ගන්නේ කිරි සහිත වර්ගය පමණකි.", "category": "plant" }

];

