// data_375_384.js - පිටු 375 සිට 384 දක්වා සියලුම වචන
const data_extra_375_384 = [
    // --- පිටුව 375 ---
    { "word": "මුදුස්ස", "meaning": "මුරුවාවැල", "category": "plant" },
    { "word": "මුදුසිව", "meaning": "නිල්මිදි", "category": "plant" },
    { "word": "මුදාගන්ධක", "meaning": "සුදුපාට ගෙන්දගම් වගියක්", "category": "mineral" },
    { "word": "මුදිකා", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "මුදි", "meaning": "මකුණුවැන්න", "category": "plant" },
    { "word": "මුන්කිල්", "meaning": "හුනගස", "category": "plant" },
    { "word": "මුන්තක", "meaning": "තෙලඹුගස", "category": "plant" },
    { "word": "මුන්දිරි", "meaning": "කපුගස", "category": "plant" },
    { "word": "මුන්නිකා", "meaning": "වෙල්මුඩ", "category": "plant" },
    { "word": "මුන්මුරා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "මුන්වන්", "meaning": "මුන්වැන්න", "category": "plant" },
    { "word": "මුන්වැන්න", "meaning": "හෙළබිය", "category": "plant" },
    { "word": "මුනවිතිරිකොළ", "meaning": "උඳුපියලි", "category": "plant" },
    { "word": "මුනිකා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "මුනිවිච්ච", "meaning": "රක්අත්තන", "category": "plant" },
    { "word": "මුනිතරා", "meaning": "මූණමල්ගස", "category": "plant" },
    { "word": "මුනිතිකෘ", "meaning": "බෙලි", "category": "plant" },
    { "word": "මුනිද්‍රැම", "meaning": "මුරුංගා, තොටිල, කතුරුමුරුංගා", "category": "plant" },
    { "word": "මුනිපුත්‍රක", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "මුනිපුෂ්ප", "meaning": "මුනමල්", "category": "plant" },
    { "word": "මුනිප්‍රිය", "meaning": "රසඳුන්, මාරා, රත්කෑල, මහරි", "category": "plant" },
    { "word": "මුනිභෙෂජ්", "meaning": "අරළු, මුරුංගා", "category": "plant" },
    { "word": "මුනිතාරකුන්තල්", "meaning": "ආපසුමුදු", "category": "plant" },
    { "word": "මුනිරසාස", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "මුනිශාඛ", "meaning": "කතුරුමුරුංගා", "category": "plant" },
    { "word": "මුනිසන්තක", "meaning": "දියඇඹුලැඹිලිය", "category": "plant" },
    { "word": "මුනිසිඩිකාන්", "meaning": "බුත්සරණ", "category": "plant" },
    { "word": "මුනි", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "මුවපුලා", "meaning": "කටුපිල", "category": "plant" },
    { "word": "මුබබා", "meaning": "මුරුවා", "category": "plant" },
    { "word": "මුෂීක", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "මුර්මුරි", "meaning": "වවුලැටියවැල", "category": "plant" },
    { "word": "මුෂා", "meaning": "මැඩහඟු, මෝර, මැස්ස, මුරුවා, නියඳ", "category": "plant" },
    { "word": "මුෂාදේවි", "meaning": "නියඳ", "category": "plant" },
    { "word": "මුරජඵල", "meaning": "කොස්", "category": "plant" },
    { "word": "මුරනික්තක", "meaning": "වැල්මුරුංගා", "category": "plant" },
    { "word": "මුරවින", "meaning": "කිලිමාලය", "category": "plant" },
    { "word": "මුරා", "meaning": "තලිස්පතුරු", "category": "plant" },
    { "word": "මුරක්කාරෙ", "meaning": "කුකුරුමුවන්ගස", "category": "plant" },
    { "word": "මුරක්කු", "meaning": "එරබදු", "category": "plant" },
    { "word": "මුරකු", "meaning": "මුරුවාවැල", "category": "plant" },
    { "word": "මුරගණ්ඩ", "meaning": "මිදි", "category": "plant" },
    { "word": "මුරගපානි", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "මුරගප්‍රිය", "meaning": "රසඳුන්", "category": "plant" },
    { "word": "මුරඟි", "meaning": "නාමල", "category": "plant" },
    { "word": "මුරංග", "meaning": "කටුපිල ගස", "category": "plant" },
    { "word": "මුරංගා", "meaning": "මෝර, මුරුංගා", "category": "plant" },
    { "word": "මුරංඟි", "meaning": "වැල්මුරුංගා, කටුපිල ගස", "category": "plant" },
    { "word": "මුරත", "meaning": "මුරත ගස", "category": "plant" },
    { "word": "මුරදර", "meaning": "දේවදාර", "category": "plant" },
    { "word": "මුරන්කෙකෙ", "meaning": "මුරුංගා", "category": "plant" },
    { 
        "word": "මුරුවා", 
        "scientific": "Marsdenia Tenacissima",
        "meaning": "Marsdenia Tenacissima- මුරුවා වැල්. වැල් සහ කොළ කිහිරි සුදු පාටින් යුක්ත ය. කොළ වල සිහින් බුවක් තිබේ. මඳක් උල්වගිය රවුම් කොළ ගෙරි කන් වලට හෝ ඉල්ල කොළ වලට සමාන ය. කුමනින් වලටත් වඩා තද තික්ත ගතියකින් යුත් මේ වගිය දේශීය වෙදකමේ දරුණු රෝග දෙකක් සඳහා ප්‍රත්‍යක්ෂ ගුණදායක ඖෂධයකි. හොරි-දද-කුෂ්ඨ-කඩුවෙගන් ආදි ශරීරගත ලේ විෂවීමෙන් හා කාමින්ගෙන් බෝවෙන සමේ රෝග වලට මේ දඬු කැබලි වතුරෙන් දින පතා උදේ-සවස ඒ තුවාල (බිබිලි) තැවීම බෙහෙත් වතුර වදින සේ සේදීමෙන් සම පූර්ණ සුවය ලබා ගත හැකි වීම එකකි. අනික් එක විෂමජ්වරය (මැලේරියාව) යි. මුරුවා වැල් කලං 12 ක් ගෙන පත 8 පත 1 ට සිඳ උදේ-සවස දින කීපයක් පානය කිරීමෙන් ඒ දරුණු උණ රෝගය සම්පූර්ණයෙන් ශරීරයෙන් පහ කර ගණිම යි.", 
        "category": "plant",
        "image": "img_375_muruwa.jpg"
    },

    // --- පිටුව 376 ---
    { "word": "මුරුවට්ට", "meaning": "තල, මී, කොහොඹ, ආදි ඇට වලින් තෙල් සිඳ ගත් කලු ඉතිරි වන ලබ=(රොඩු=පුන්නක්කු)", "category": "plant" },
    { "word": "මුරුවාසි", "meaning": "මුරුවා", "category": "plant" },
    { "word": "මුල්", "meaning": "රක්මුල", "category": "plant" },
    { "word": "මුල්ඉලවත්", "meaning": "කටුනිඹුල්", "category": "plant" },
    { "word": "මුල්කාවලා", "meaning": "කටුපිල", "category": "plant" },
    { "word": "මුල්බෙන්", "meaning": "විනමුල්, (මින අල=සීන අල=අලබෙන්)", "category": "plant" },
    { "word": "මුල්මුරුක්තං", "meaning": "එරබදු", "category": "plant" },
    { "word": "මුල්ලුකිරෙසි", "meaning": "කටුතම්පලා", "category": "plant" },
    { "word": "මුල්ලිපලාශු", "meaning": "කටුකෑල", "category": "plant" },
    { "word": "මුල්ලෙ", "meaning": "මෑල්ල ගස", "category": "plant" },
    { "word": "මුල", "meaning": "රාබු ගස", "category": "plant" },
    { "word": "මුලක්කණ", "meaning": "නිප්පිලි මුල්", "category": "plant" },
    { "word": "මුලඟු", "meaning": "වල්මොලඟු, ගම්මිරිස්", "category": "plant" },
    { "word": "මුලගුණ", "meaning": "අඟුණමුල්", "category": "plant" },
    { "word": "මුලප්", "meaning": "පලොල්", "category": "plant" },
    { "word": "මුලපත්‍රී", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "මුලපලා", "meaning": "රාබු ගස", "category": "plant" },
    { "word": "මුලපුල", "meaning": "කටුපිල", "category": "plant" },
    { "word": "මුලරෝගවැදි", "meaning": "අර්ශස් රෝගය", "category": "treatment" },
    { "word": "මුලස්ම", "meaning": "පල්මාණික්කම්, මයුර තුතු", "category": "mineral" },
    { "word": "මුලසාදන", "meaning": "පොණඬරු", "category": "plant" },
    { "word": "මුව", "meaning": "සමූහය", "category": "general" },
    { 
        "word": "මුවකිරිය", 
        "scientific": "Sarcostemma Brunonianum",
        "meaning": "Sarcostemma Brunonianum- දියසෙවෙල් රැඳෙන දිය සීරාව සහිත ගස්වල පැලවී පහතට එල්ලා වැටෙන නවහන්දි ගස් වැනි වැල් වගියකි. මෙය වැඩි වශයෙන් වැවෙන්නේ බේදැරු අතරින් ය. බිම පැලවී උඩට වැවෙන නඩු වැනි ගස් වගිය තවහන්දි ලෙසත්, ඒ ලක්‍ෂණයෙන් ම යුක්ත ව ගස් වල පැලවී පහතට ඇදෙන වගිය මුවකිරිය ලෙස ත් හැඳින්වෙයි. මේ වගිය දේශීය වෙදකමේ තෙල්-බෙහෙත් සඳහා පාවිච්චි කරණ ශක්තිජනක ඖෂධයකි.", 
        "category": "plant",
        "image": "img_376_muwakiriya.jpg"
    },

    // --- පිටුව 377 ---
    { "word": "මුළුඅල", "meaning": "රාබු", "category": "plant" },
    { "word": "මුෂ්ක", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "මුෂ්පලා", "meaning": "රාබු", "category": "plant" },
    { "word": "මුවන්", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "මුවනාබ", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "මුවමද", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "මුවර", "meaning": "මෝරු", "category": "liquid" },
    { "word": "මුවරද", "meaning": "රේණු, සිංහයා", "category": "plant" },
    { "word": "මුවරඹ", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "මුශරි", "meaning": "සුදු ඊයම්", "category": "mineral" },
    { "word": "මුෂ්කක", "meaning": "තෙලඹු ගස, දේවදාර, ඇපල ගස", "category": "plant" },
    { "word": "මුෂ්කකාදිගණය", "meaning": "තෙලඹු, අරළු, බුළු, නෙල්ලි, කුකුරුමාන්, කෙළිඳසාල්, රත්නිටුල්, සිනුක්, දෑව, කෑල, ඇටිවේරිය යන මේ ගණය ප්‍රමේහ හා අශ්මරි නසන්නේ ය.", "category": "compound" },
    { "word": "මුෂ්ට", "meaning": "වම්මුතු, කලාදුරු", "category": "plant" },
    { "word": "මුෂ්ටිකා", "meaning": "මුඩමහණ, රේරු", "category": "plant" },
    { "word": "මුෂ්ටී", "meaning": "රේරු, මුඩමහණ, ගැටපිච්ච", "category": "plant" },
    { "word": "මුෂ්ටිලි", "meaning": "මුසලි - බින්තල්", "category": "plant" },
    { "word": "මුෂණ", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "මුස්ත", "meaning": "තෙලඹු", "category": "plant" },
    { "word": "මුස්තක", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "මුස්තකමුල", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "මුස්තාකා", "meaning": "සුවඳැති මැලියම් වගියක්", "category": "plant" },
    { "word": "මුස්තා", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "මුස්කාදිගණය", "meaning": "වම්මුතු, පාඨා (ලුණුකැටියාවැල් හෝ දියමිත්ත), දෙකසා, කටුකරණ, හෙළ වදකසා, (හිමාලයෙහි උපදනා හෙමවතී) හින් එන්සාල්, ඉවද, කොට්ටම්, බදුල්ල, අරළු, බුළු, නෙල්ලි, හඟුලු(නල්වැල්) යන මේ ගණය සෙම් නැසීම දොස් පැසවීම හා දොස් සමනය ත්, යෝනි දොෂ පහ කිරීම ත්, තනකිරි ඇති කිරීම ත් කරයි.", "category": "compound" },
    { "word": "මුසුමුසුවිතෙසි", "meaning": "දිඹිප්පු", "category": "plant" },
    { 
        "word": "මුස්සැන්ද", 
        "scientific": "Mussaenda Frondosa",
        "meaning": "Mussaenda Frondosa- ශ්‍රීවර්ණී. ඇතැම් පළාත්වල මුස්සැන් ද නමින් ද ව්‍යවහාර වන මෙය පඳුරු වගියකි. එහෙත් ගසක ආධාරයක් ලැබුනොත්, හිඹුටුවැල් මෙන් ඒ ගස මුදුනට ම නැග සවිකිය ග්‍රහණයෙන් පත්‍ර වලින් එය සරසයි. මේ නිසා දහවල් කාලයෙහි මෙන් ම සඳ රැසින් බබලන රාත්‍රී කාලයෙහිත් බොහෝ දුර සිට වුව ද සුදු පැහැයෙන් දිලිසෙන කොළ ඇති මුස්සැන්ද අඳුනා ගත හැක. මේ සුදු පාට කොළ නික්මෙන්නේ මේ පඳුරෙහි හටගන්නා කහ රන්වන් පැහැයෙන් යුත් සත්‍රීන්ගේ කර්ණාභරණ (කරාබු) වල හැඩහුරුකම ඇති මල් අසලින් ය. මේ සුදු කොළ පොල්කිරි මිශ්‍ර ඇල් දියෙන් උකු කලු හාල් පිටි වල බහා පොල් තෙලෙන් බැඳ පප්පඩම් වැනි රසවත් ආහාරයක් පිළියෙල කර ගත හැක. මෙය කුඩා ළමයින්ගේ ධාරණ ශක්තිය වඩවන ආහාරයකි. මෙහි මුල් හා සුදු පාට කොළ උන්මාදය (පිස්සුව), කලානාදය, ධාරණ ශක්තියේ දුර්වලකම හා නොසන්සුන්කම ආදි හිසේ හටගන්නා නොයෙකුත් අසනීප වලට ප්‍රත්‍යක්‍ෂ ඖෂධයකි. මුස්සැන්ද ඇට කුඩු එළමුත්‍ර සමග මිශ්‍ර කර දීමෙන් කාමිලා (සෙංගමාල) හා පාණ්ඩු රෝග සුව වෙයි. සාමාන්‍යයෙන් මූත්‍ර වර්ධනය කරණ බලකාරක ඖෂධයක් වූ මේ පැලෑටියේ මුල්වල සාරය, කාශ - ශ්වාස - ආමජ්වර - ශීතජ්වර - විෂමජ්වර - උදාවර්ත යන රෝග වලට ත්, නිල් පාට කොළ පරණ වණවල කොළ කපා පිරිසිදු කිරීමට ත්, සිරීම් තුවාල වලට ත් ගනිති.", 
        "category": "plant",
        "image": "img_377_mussaenda.jpg"
    },

    // --- පිටුව 378 ---
    { "word": "මුසොනැඬු", "meaning": "මහ ඉරමුසු", "category": "plant" },
    { "word": "මුස්ස", "meaning": "මුරුවාවැල්", "category": "plant" },
    { "word": "මුසල්පහර", "meaning": "සාබෙටි", "category": "plant" },
    { "word": "මුසලි", "meaning": "බිම්තල්, ඌරල", "category": "plant" },
    { "word": "මුහුණමල්", "meaning": "වකුලවෘක්‍ෂය", "category": "plant" },
    { "word": "මුහුඬුව", "meaning": "මල්කර්ණිකාව", "category": "plant" },
    { "word": "මුහුණ", "meaning": "මුහුණමල්ගස", "category": "plant" },
    { "word": "මුහුදුසෙම්", "meaning": "මුදුපෙණ", "category": "nature" },
    { "word": "මුහුතකෙසුරු", "meaning": "මුහුණමල්ගස", "category": "plant" },
    { "word": "මුහුල", "meaning": "මුහුව - මූණමල්", "category": "plant" },
    { "word": "මුහුළුමල්ගස", "meaning": "මූණමල්ගස (මුහුණගස)", "category": "plant" },
    { "word": "මුහොටිකා", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "මුලාල", "meaning": "තෙලඹුදැලි (මානෙල්)", "category": "plant" },
    { "word": "මුතකා", "meaning": "ඉන්සළු ගස", "category": "plant" },
    { "word": "මුතුඵල", "meaning": "තියඹරා, කැකිරි", "category": "plant" },
    { "word": "මුතුලා", "meaning": "කැකිරි", "category": "plant" },
    { "word": "මුතුහරා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "මුදුපෙණ", "meaning": "මුහුදයාක ඇතුලට සමාන කිලිපී සුදු පාටින් යුත් කැටිගැසී සැදී තිබෙන ලුණුකැට වැනි කුඩා ද්‍රව්‍යයකි. ඇතැම් අය මුදු පෙණ වලට දැලිපොතු ද ගනිති.", "category": "nature" },
    { "word": "මුනමිකිරි කොළ", "meaning": "උඳුපියලි", "category": "plant" },

    // --- පිටුව 379 ---
    { 
        "word": "මූණමල්", 
        "scientific": "Mimusops Elengi",
        "meaning": "Mimusops Elengi- බකුල. මූහුණ ගස, මුහුණ මල් ගස, මූන මල් ගස යන නම් වලින් සිංහලයන් අතර ප්‍රසිද්ධ මේ ගස මනුෂ්‍ය ශරීරයට හිතකරය. මෙහි පොතු හා ඇට, දත් සෙලවීම, විදුරුමස් දියවීම, විදුරුමස් වලින් ලේ සාරේ යාම, තොල් පැලීම ආදි මුඛ රෝග පිළිබඳ ආබාධ වලට හා ග්‍රහණ්‍යාබාධ වලටත් ප්‍රත්‍යක්‍ෂ ඖෂධයකි. දන්ත රෝග පිළිබඳ හැම බෙහෙතකට ම පාහේ මුහුණමල් පොතු ද ඇතුළත් ව ඇත. කුඩා බුළු ගෙඩි පමණ වූ මේ ගස් වල ගෙඩි කසට-පැණි-පිටි රසයන්ගෙන් යුක්ත ය. දන්ත රෝග වලක්වා ගැනීමට හා ආහාරයක් වශයෙන් ද මුහුණ ගෙඩි කෑමට යෝග්‍ය ය.", 
        "category": "plant",
        "image": "img_379_moonamal.jpg"
    },
    { "word": "මූර්ඛව", "meaning": "ඉස", "category": "anatomy" },
    { "word": "මූර්ඛවවාරිනී", "meaning": "මෝරගස", "category": "plant" },
    { "word": "මූර්ඛවපුෂ්ප", "meaning": "මාරාගස", "category": "plant" },
    { "word": "මූල", "meaning": "ඉරිවේරිය, නිප්පිලිමුල්, මුල් වගී", "category": "plant" },
    { "word": "මූලක්කණ", "meaning": "නිප්පිලිමුල්", "category": "plant" },
    { "word": "මූලක", "meaning": "නිතිවැල්, අඳුතලා, ලීමෑ නියඹරා, නිප්පිලිමුල්", "category": "plant" },
    { "word": "මූලකතිකා", "meaning": "තියඹරා වැල", "category": "plant" },
    { "word": "මූලකපත්‍රිකා", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "මූලකපර්ණී", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "මූලප්", "meaning": "අමු ඉඟුරු, මුල් වලින් අල සෑදෙන මානෙල්, කලාදුරු, පලොල්", "category": "plant" },
    { "word": "මූලපුෂ්කර", "meaning": "නෙළුම්අල", "category": "plant" },
    { "word": "මූලපෙශකර", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "මූලඵල", "meaning": "කොස්ගෙඩිය", "category": "plant" },
    { "word": "මූලරස", "meaning": "මුරුවා", "category": "plant" },
    { "word": "මූලශාධන", "meaning": "පොණඬරු", "category": "plant" },
    { "word": "මූලා", "meaning": "හාතවාරිය අල", "category": "plant" },
    { "word": "මූලිනි", "meaning": "බැමිතිරිය, බිම්නුග", "category": "plant" },
    { "word": "මූවිට", "meaning": "මුතුමාගිය", "category": "plant" },
    { "word": "මූෂණ", "meaning": "නිප්පිලිමුල්, මිරිස්", "category": "plant" },
    { "word": "මූෂා", "meaning": "රත්රන්මකන කෝව", "category": "general" },
    { "word": "මූෂිකපර්ණී", "meaning": "මීකන්පලා", "category": "plant" },
    { "word": "මූෂිකපාෂාණ", "meaning": "මීපාෂාණම්", "category": "mineral" },
    { "word": "මූෂිකවපු", "meaning": "මීනුගගස", "category": "plant" },
    { "word": "මූෂිකවිනාශනී", "meaning": "දේවදාලි", "category": "plant" },
    { "word": "මූෂිකා", "meaning": "දේවදාලි", "category": "plant" },

    // --- පිටුව 380 ---
    { "word": "මූෂිකාගර්භි", "meaning": "දේවදාලි", "category": "plant" },
    { "word": "මූෂිකාස්‍රණී", "meaning": "නික්තවැටකොළු", "category": "plant" },
    { "word": "මූෂිකාශ්‍රවනා", "meaning": "මකුණුවැන්න", "category": "plant" },
    { "word": "මූෂිකාහ්වා", "meaning": "දත්ත", "category": "plant" },
    { "word": "මෘගගාමිනී", "meaning": "වලඟසාල්", "category": "plant" },
    { "word": "මෘගනාභි", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "මෘගනාභිනී", "meaning": "වලඟසාල්", "category": "plant" },
    { "word": "මෘගනාලිකා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "මෘගපර්ණී", "meaning": "ගොකටු", "category": "plant" },
    { "word": "මෘගපාශි", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "මෘගභක්‍ෂපා", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "මෘගමද", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "මෘගරසා", "meaning": "මුඟුල්කුඹුරු, වෑත්ත, මහබැවිල", "category": "plant" },
    { "word": "මෘගරාටිකා", "meaning": "රසකිඳ, රත්නමල, කිරිපලා", "category": "plant" },
    { "word": "මෘගරුවිකා", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "මෘගසාරා", "meaning": "වලඟසාල්", "category": "plant" },
    { "word": "මෘගා", "meaning": "මහබැවිල", "category": "plant" },
    { "word": "මෘගාක්‍ෂි", "meaning": "මඟගොත්සුතු කැකිරි", "category": "plant" },
    { "word": "මෘගාණ්ඩජ", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "මෘගාදනී", "meaning": "මඟ ගොත්සුතු කැකිරි, තුඹගෙඩි", "category": "plant" },
    { "word": "මෘගාපි", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "මෘගෙශීරූ", "meaning": "සුදුකැකිරි", "category": "plant" },
    { "word": "මෘඩවස", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "මෘඛ", "meaning": "මහගොත්කැකිරි", "category": "plant" },
    { "word": "මෘඩා", "meaning": "මහගොත්සුතුකැකිරි", "category": "plant" },
    { "word": "මෘණාල", "meaning": "නෙළුම්අල, සැවැන්න", "category": "plant" },
    { "word": "මෘණාලසුත්‍ර", "meaning": "නෙළුඹු", "category": "plant" },
    { "word": "මෘණාලිකා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "මෘත්‍යනා", "meaning": "තුබරි", "category": "plant" },
    { "word": "මෘත්සකලා", "meaning": "කටුරෝහිණී", "category": "plant" },
    { "word": "මෘතජීව", "meaning": "මාරාගස", "category": "plant" },
    { "word": "මෘතඵලී", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "මෘතසබගම", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "මෘතාඛි", "meaning": "අරළු", "category": "plant" },
    { "word": "මෘතාලක", "meaning": "තුබරි", "category": "plant" },
    { "word": "මෘතාශ්‍රී", "meaning": "දක්, මහලක්", "category": "plant" },
    { "word": "මෘතීනාසක", "meaning": "රසදිය", "category": "mineral" },
    { "word": "මෘතීපුෂ්ප", "meaning": "දළුක්ගස", "category": "plant" },
    { "word": "මෘතීඵල", "meaning": "කෙසෙල්ගස", "category": "plant" },
    { "word": "මෘතීශාගක", "meaning": "පාරද (රසදිය)", "category": "mineral" },
    { "word": "මෘතීදීක", "meaning": "බටගස", "category": "plant" },
    { "word": "මෘද්වීකා", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "මෘද්වී", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "මෘඩබගුලිනී", "meaning": "වැටකොළු", "category": "plant" },
    { "word": "මෘදු", "meaning": "කිනිහිරැද, විභානුපත්‍ර, වෘක්‍ෂ", "category": "plant" },
    { "word": "මෘදුකණ්ටක", "meaning": "රත්පත් කටුකරඬු, කටුකරඬු", "category": "plant" },
    { "word": "මෘදුකඞ්", "meaning": "බුරඳ", "category": "plant" },
    { "word": "මෘදුකඞ්බක්", "meaning": "බුරපතු", "category": "plant" },
    { "word": "මෘදුච්ඡද", "meaning": "කරගස, ගල්මෝර", "category": "plant" },
    { "word": "මෘදුවච්ඡිත්", "meaning": "කරගස, බුරපත්", "category": "plant" },
    { "word": "මෘදුත්ව", "meaning": "දුම්මල, කරගස", "category": "plant" },
    { "word": "මෘදුපත්‍ර", "meaning": "සුළුකූර, කූරතම්පලා, කිරිහන්දා", "category": "plant" },
    { "word": "මෘදුපර්ණී", "meaning": "දුරාලභා", "category": "plant" },
    { "word": "මෘදුපර්වක", "meaning": "වේවැල", "category": "plant" },
    { "word": "මෘදුපුෂ්ප", "meaning": "වෑත්, මාරාගස", "category": "plant" },
    { "word": "මෘදුඵලා", "meaning": "මුද්දරප්පලම්, උගුරැස්ස, තැඹිලිගෙඩි", "category": "plant" },
    { "word": "මෘදුලොහ", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "මෘදුලොහකම්", "meaning": "කළු තුඹ", "category": "mineral" },
    { "word": "මෘදුමිරෙචනී", "meaning": "පතුක්", "category": "plant" },
    { "word": "මෘදුසිව", "meaning": "නිල් ලෝලු", "category": "plant" },
    { "word": "මෘදුසි", "meaning": "සුදුබකලන්", "category": "plant" },
    { "word": "මෘෂා", "meaning": "මිරිස්", "category": "plant" },
    { "word": "මෘෂ්පී", "meaning": "ඌරල (බිමිතල්)", "category": "plant" },
    { "word": "මෘෂ", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "මහාපානි", "meaning": "රසකිඳ", "category": "plant" },

    // --- පිටුව 381 ---
    { "word": "මෙඅන්", "meaning": "බත්", "category": "food" },
    { "word": "මෙබලා", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "මෙගනාරායන", "meaning": "මාන්සවේරිය, අක්කාපාන", "category": "plant" },
    { "word": "මෙගලබක්", "meaning": "වැල්මුරුංගා", "category": "plant" },
    { "word": "මෙඝ", "meaning": "ඉරිවේරිය, කලාදුරු", "category": "plant" },
    { "word": "මෙඝකර්ණ", "meaning": "සුළු කුඹුක්", "category": "plant" },
    { "word": "මෙඝකුසුම", "meaning": "තෝරගස", "category": "plant" },
    { "word": "මෙඝදිප", "meaning": "ලියනගලා", "category": "plant" },
    { "word": "මෙඝනාද", "meaning": "සුළුකූර, කූරතම්පලා", "category": "plant" },
    { "word": "මෙඝනාමන්", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "මෙඝපුෂ්ප", "meaning": "වතුර", "category": "liquid" },
    { "word": "මෙඝභව", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "මෙඝරාව", "meaning": "සුළුකූර", "category": "plant" },
    { "word": "මෙඝලොචන", "meaning": "රන්වන් කිකිරිඳිය", "category": "plant" },
    { "word": "මෙඝවර්ණී", "meaning": "බටුදැම්, බෙරු", "category": "plant" },
    { "word": "මෙඝවර්ණී(2)", "meaning": "නිලී වෘක්‍ෂය (අවරිය)", "category": "plant" },
    { "word": "මෙඝවාහිනී", "meaning": "මයිල ගස", "category": "plant" },
    { "word": "මෙඝවිනාශිනී", "meaning": "දියබෙරලිය", "category": "plant" },
    { "word": "මෙඝසප්නිනෝද්භව", "meaning": "උගුරැස්ස", "category": "plant" },
    { "word": "මෙඝසම්භව", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "මෙඝසාර", "meaning": "විනකපුරු, දෙඹගස", "category": "plant" },
    { "word": "මෙඝා", "meaning": "බෙබර", "category": "plant" },
    { "word": "මෙඝාක්‍ෂ", "meaning": "තුවර ගස, කිකිරිඳිය", "category": "plant" },
    { "word": "මෙඝාණ්ඩ", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "මෙඝාහා", "meaning": "බදුදම්", "category": "plant" },
    { "word": "මෙචක", "meaning": "කළුදුණු", "category": "plant" },
    { "word": "මෙට(බ)", "meaning": "ඔල්මාදය", "category": "treatment" },
    { "word": "මෙපී", "meaning": "උළුවා", "category": "plant" },
    { "word": "මෙටුලා", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "මෙත්තා", "meaning": "සඳුන්", "category": "plant" },
    { "word": "මෙපිකා", "meaning": "වල්උළුවා", "category": "plant" },
    { "word": "මෙපි", "meaning": "උළුවා, (උළුවාහාල්)", "category": "plant" },
    { "word": "මෙද", "meaning": "ගුරත්ද ගස, මිහිඇට", "category": "plant" },
    { "word": "මෙදක", "meaning": "රසදිය, කුන්දරුක්කන්, මේද තෙල", "category": "mineral" },
    { "word": "මෙද(2)", "meaning": "ගෝරෝචන, මේවත්", "category": "plant" },
    { "word": "මෙදුශ්ව", "meaning": "මේවන්", "category": "plant" },
    { "word": "මෙදිනී", "meaning": "මහ වැල්පෙනෙල", "category": "plant" },
    { "word": "මෙදුර", "meaning": "සිකිඳුදෙය", "category": "plant" },
    { "word": "මෙදෙ", "meaning": "මේදතෙල", "category": "liquid" },
    { "word": "මෙදෙත්භවා", "meaning": "මේවන්", "category": "plant" },
    { "word": "මෙධ", "meaning": "හෙළහිඹුරු", "category": "plant" },
    { "word": "මෙධ්‍යා", "meaning": "බැමිතිරිය, හෙළවදකසා", "category": "plant" },
    { "word": "මෙධ්‍යාකාරී", "meaning": "වදකසා", "category": "plant" },
    { "word": "මෙධ්‍යාකෘෂ", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "මෙධාජනනී", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "මෙධ්‍ය", "meaning": "රන්වන් වදකහ, කිහිරි, යව, සක්මල්, ගොරද", "category": "plant" },
    { "word": "මෙධ්‍යමුඛ්‍ය", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "මෙධ්‍යා(2)", "meaning": "පිරිසිදුදෙය, ලුණුවිල", "category": "plant" },
    { "word": "මෙධ්‍යාහාර", "meaning": "දී ආදිය", "category": "food" },
    { "word": "මෙන", "meaning": "මැණික්", "category": "mineral" },
    { "word": "මෙනා", "meaning": "මුහුණ", "category": "anatomy" },
    { "word": "මෙනෙල", "meaning": "මෙහෙණල", "category": "plant" },
    { "word": "මෙන්ට ආවා", "meaning": "අමුකහ", "category": "plant" },
    { "word": "මෙරය", "meaning": "ධාන්‍යාදියෙන් කළ සුරා", "category": "liquid" },
    { "word": "මෙල්ල", "meaning": "ලප්නාරං", "category": "plant" },
    { "word": "මෙල්සිනී", "meaning": "උක්ගස", "category": "plant" },
    { "word": "මෙලවජ්ගක්", "meaning": "හෙළ ලුහුනු", "category": "plant" },
    { "word": "මෙලවජ්මුඛ", "meaning": "තඹ", "category": "mineral" },
    { "word": "මෙලසි", "meaning": "හෙළ සැබෝ", "category": "plant" },
    { "word": "මො", "meaning": "බෙරු, අඳුන්", "category": "plant" },
    { "word": "මොලොවදකරණදල", "meaning": "වරා කොළ", "category": "plant" },
    { "word": "මෙවත්", "meaning": "මේදෘ", "category": "plant" },
    { "word": "මේෂ", "meaning": "තෝරගස, එළුවා", "category": "plant" },
    { "word": "මේෂක", "meaning": "ඇත්දෝර", "category": "plant" },
    { "word": "මේෂලෝචන", "meaning": "තෝරගස", "category": "plant" },
    { "word": "මේෂලොම", "meaning": "රන්වන්කිකිරිඳිය", "category": "plant" },
    { "word": "මේෂවල්ලී", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "මේෂවිශාණී", "meaning": "වේලිප්පරිත්ති, (මැඩහඟු)", "category": "plant" },
    { "word": "මේෂගෘංගී", "meaning": "වච්චනාභි, මෑබගඟු", "category": "plant" },

    // --- පිටුව 382 ---
    { "word": "මෙෂා", "meaning": "අඳුතලා, හින් එන්සාල්", "category": "plant" },
    { "word": "මෙෂාක්‍ෂ", "meaning": "තුවර ගස, කිකිරිඳිය, තෝර", "category": "plant" },
    { "word": "මෙෂාක්‍ෂිකුසුම", "meaning": "තෝරගස", "category": "plant" },
    { "word": "මෙෂාක්‍ෂී", "meaning": "තෝරගස", "category": "plant" },
    { "word": "මෙෂාවගී", "meaning": "මාබිඟඟු, වච්චනාභි", "category": "plant" },
    { "word": "මෙෂාණ්ඩ", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "මෙහලු", "meaning": "අඳුතලා, වේලා", "category": "plant" },
    { "word": "මෙහී", "meaning": "ජටාමාංශ, කෝන්ගස", "category": "plant" },
    { "word": "මෙසෙස්", "meaning": "සවිවිෂ", "category": "treatment" },
    { "word": "මෙසග්නී", "meaning": "කහ", "category": "plant" },
    { "word": "මෙඝනාගනී", "meaning": "සුදු කටරොළු", "category": "plant" },
    { "word": "මෙහරිපු", "meaning": "රණවරා, වැල්මුරුංගා", "category": "plant" },
    { "word": "මෙහවිනාශිනී", "meaning": "දියබෙරලිය", "category": "plant" },
    { "word": "මෙහෙහල", "meaning": "ලුණුවිල, මානෙල්, කිබාරම්", "category": "plant" },
    { "word": "මෙහොදරි", "meaning": "සින් සාතාවාරිය", "category": "plant" },
    { "word": "මෙ", "meaning": "වම්මුතු", "category": "plant" },
    { "word": "මෛග", "meaning": "කලාදුරු, කූරතම්පලා", "category": "plant" },
    { "word": "මෛගඅල", "meaning": "කලාදුරු අල", "category": "plant" },
    { "word": "මෛගනාද", "meaning": "සුළුකූර", "category": "plant" },
    { "word": "මෛගමුත්තා", "meaning": "කලාදුරු අල", "category": "plant" },
    { "word": "මෛදු", "meaning": "මේවත් (අෂ්ටක වගියේ ඔසු වක්)", "category": "plant" },
    { "word": "මෛනල", "meaning": "මෙහෙහල, (මෙහෙහල-ඇතාම්) ලුණුවිල", "category": "plant" },
    { "word": "මෛනි", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "මෛල්", "meaning": "උක්", "category": "plant" },
    { "word": "මෛල්සිනී", "meaning": "උක්ගස", "category": "plant" },
    { "word": "මෛල", "meaning": "සිනි, උක්ගස", "category": "plant" },
    { "word": "මෛඝනාසනී", "meaning": "සුදු කටරොළු", "category": "plant" },
    { "word": "මෛෂකා", "meaning": "වල්මදට", "category": "plant" },
    { "word": "මෛසක", "meaning": "ඇත්දෝර", "category": "plant" },
    { "word": "මෛසිකා", "meaning": "වල්මදට", "category": "plant" },
    { "word": "මෛහ", "meaning": "ප්‍රමේහ රෝගය", "category": "treatment" },
    { "word": "මෛහරිපු", "meaning": "රණවරා", "category": "plant" },
    { "word": "මෛරෙය", "meaning": "මලිත මල්, උක්සකුරු, කොත්තමල්ලි, ඇඹුල්කාඩි, සුරා, කරල්සැබෝ", "category": "plant" },
    { "word": "මෛල(2)", "meaning": "මයිලගස්", "category": "plant" },
    { "word": "මෛලාංගා", "meaning": "ලුහුවරණ, ලොත්ගස", "category": "plant" },
    { "word": "මෛලාත්‍යා", "meaning": "මයිල", "category": "plant" },
    { "word": "මෛලේය", "meaning": "ගොකටු, එන්සාල්", "category": "plant" },
    { "word": "මොක්‍ෂ", "meaning": "වලඟසාල්, තෙලඹු, පලොල්", "category": "plant" },
    { "word": "මොක්‍ෂක", "meaning": "ඇපල, දේවදාලිය, හෙළ පලොල්", "category": "plant" },
    { "word": "මොගංව්‍ය", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මොක්‍ෂා", "meaning": "පලොල්", "category": "plant" },
    { "word": "මොච", "meaning": "පොල්ගස, කොස්ගස, මුරුංගා ගස, බෙරු, ඉඹුල්, තල්ගෙඩි, කෙසෙල්ගෙඩි", "category": "plant" },
    { "word": "මොචක", "meaning": "ගෙන්දගම්, මුරුංගා, දෑව ලුණු, වලඟසාල්, හොයදුන්, කෙසෙල්", "category": "plant" },
    { "word": "මොවකි", "meaning": "මුරුංගා, මහඉඟිනි, ඉඹුල්", "category": "plant" },
    { "word": "මොචන", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "මොචරස", "meaning": "ඉඹුල්ලාටු", "category": "plant" },
    { "word": "මොචාග්‍රවා", "meaning": "ඉඹුල්ලාටු", "category": "plant" },
    { "word": "මොචා", "meaning": "ඇටකෙහෙල්, ඉඹුල්, ඉන් සළු ගස", "category": "plant" },
    { "word": "මොචාට", "meaning": "කඬදුරා, ඇටකෙහෙල්", "category": "plant" },
    { "word": "මොචී", "meaning": "ඉඹුරා", "category": "plant" },
    { "word": "මොච්ක්‍ෂපාඝ", "meaning": "ගොන්කැකිරි", "category": "plant" },
    { "word": "මොප්", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මොප්තණ", "meaning": "මුදුප් නම් තණ වර්ගය", "category": "plant" },
    { "word": "මොට්චු", "meaning": "කකුල", "category": "plant" },
    { "word": "මොට", "meaning": "දෙහි", "category": "plant" },
    { "word": "මොටදසියා කොළ", "meaning": "පබ (උඩහලු) වැල", "category": "plant" },

    // --- පිටුව 383 ---
    { "word": "මොටපාටි", "meaning": "සුළුබූබැවිල", "category": "plant" },
    { "word": "මොටා", "meaning": "බැවිල", "category": "plant" },
    { "word": "මොඩකොත්නාන්", "meaning": "වැල්පෙනෙල", "category": "plant" },
    { "word": "මොද", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මොදක", "meaning": "අග්ගලා, කුන්දරුක්කන්", "category": "food" },
    { "word": "මොදගස්තු", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මොදමොදබ්‍යා", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මොදමෝදිනී", "meaning": "ජම්බු", "category": "plant" },
    { "word": "මොදයන්ති", "meaning": "වල්ඉද්ද", "category": "plant" },
    { "word": "මොදරකන්තිය", "meaning": "නුටුවැල්", "category": "plant" },
    { "word": "මොදු", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මොදිනී", "meaning": "සුරා, ඉද්ද, අසමෝදගම්, සමන්කස්තුරි, ඇත්දෙමට", "category": "plant" },
    { "word": "මොනරකුඩුම්බිය", "meaning": "දුටුසතුටු", "category": "plant" },
    { "word": "මොනරක්කි", "meaning": "ලප්වාකල්", "category": "plant" },
    { 
        "word": "මොනරපහුරු", 
        "meaning": "මෙය කඩුවපහර පැලයක් මෙන් දෙපසට බෙදී යන කොළ ඇති නිතර දිය සීරාව සහිත ගල් උඩ හටගන්නා පැලෑටියකි. මෙහි මල් ඕකිඩ් (උඩවැඩියා)මල් වැනි ය. ඒ මල් පරවූ විට බුත්සරණ ඇට පමණ ගෙඩි පොකුරු සෑදෙයි. මෙහි මල් සහ ඉදුන ගෙඩිත් මොණර පිල් (මයුරපිච්ඡ) පාහයෙන් යුක්ත ය. මේ පැලෑටිය සහමුලයෙන් ම ගෙඩි-වණ-තුවාල සඳහා ගන්නා බෙහෙත් වට්ටෝරුවල ඇතුලත් කර තිබේ.", 
        "category": "plant",
        "image": "img_383_monarapahuru.jpg"
    },
    { "word": "මොනරසිළු", "meaning": "හෝපළු, පවුරු තල් ගස", "category": "plant" },
    { "word": "මොරට", "meaning": "බොරළුදමුණු, මුරුවා, නියඳ, උක්මුල්, මැඩහඟු, අඟුණමල්, සත් රැයක් පිළිනු කළ කිරි", "category": "plant" },
    { "word": "මොරපී", "meaning": "මුරුවා", "category": "plant" },
    { "word": "මොරබිප්", "meaning": "පියා (මොර) ඇට", "category": "plant" },
    { "word": "මොරවා", "meaning": "මුරුවා වැල්", "category": "plant" },
    { "word": "මොලහු", "meaning": "ගම්මිරිස්", "category": "plant" },
    { "word": "මොවුනල", "meaning": "මානෙල් අල", "category": "plant" },
    { "word": "මොසා", "meaning": "අරළු", "category": "plant" },
    { "word": "මොහවන්දන", "meaning": "ගෝරෝචන", "category": "mineral" },
    { "word": "මොහත", "meaning": "ගෝරෝචන, අත්තන", "category": "plant" },
    { "word": "මොහිනී", "meaning": "හින් බෙබර, බුලත්, තුන් බෝ අත්තන", "category": "plant" },
    { "word": "මොහි", "meaning": "කන්සා", "category": "plant" },
    { "word": "මොහොපුන", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "මොහොර", "meaning": "කිරිමෝරු", "category": "liquid" },
    { "word": "මොහොර(2)", "meaning": "මෝරා", "category": "animal" },

    // --- පිටුව 384 ---
    { "word": "මෝක්‍ෂපාල", "meaning": "කටුවල අල", "category": "plant" },
    { "word": "මෝගංව්‍ය", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මෝච", "meaning": "ඇට කෙසෙල්, (රඹ) කොස් ගස, තෝර", "category": "plant" },
    { "word": "මෝචක", "meaning": "වලඟසාල්, ඉඹුල්", "category": "plant" },
    { "word": "මෝචයුග්මය", "meaning": "ඇටකෙසෙල්, මස්කෙසෙල් දෙවගය", "category": "plant" },
    { "word": "මෝච රස", "meaning": "ඉඹුල් ලාටු", "category": "plant" },
    { "word": "මෝචා", "meaning": "ඉඹුල්, ඇටකෙසෙල්", "category": "plant" },
    { "word": "මෝචී", "meaning": "මී මුරුවට", "category": "plant" },
    { "word": "මෝවික් වෘක්‍ෂබය", "meaning": "ගොන්කැකිරි", "category": "plant" },
    { "word": "මෝටාපාටි", "meaning": "සුළු බූ බැවිල", "category": "plant" },
    { "word": "මෝදක", "meaning": "අසමෝදගම්", "category": "food" },
    { "word": "මෝදගම්", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මෝදක(2)", "meaning": "තිබ්බටු", "category": "plant" },
    { "word": "මෝරට පත්", "meaning": "මුරුවා කොළ", "category": "plant" },
    { "word": "මෝරිය", "meaning": "මුඛ රෝගයක්", "category": "treatment" },
    { "word": "මෝවික්", "meaning": "ගොන් කැකිරි", "category": "plant" },
    { "word": "මෝහී", "meaning": "කංසා", "category": "plant" },
    { "word": "මෝහිනී මජ්ජර", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "මෞක්තික", "meaning": "මුතු", "category": "mineral" },
    { "word": "මෞක්තික පුනවා", "meaning": "මුතුබෙල්ලා", "category": "animal" },
    { "word": "මෞක්තික ශුක්ති", "meaning": "මුතු බෙල්ලා", "category": "animal" },
    { "word": "මෞක්‍ෂුපී", "meaning": "රතණ", "category": "plant" },
    { "word": "මෞක්‍ෂුප් පත්‍රී", "meaning": "පොතු", "category": "plant" },
    { "word": "මෞදුම්බර පල", "meaning": "අට්ටික්කා", "category": "plant" },
    { "word": "මෞර්වී", "meaning": "නියඳ, මැඩහඟු", "category": "plant" },
    { "word": "මෞලි", "meaning": "හෝපළු ගස", "category": "plant" },
    { "word": "මෞගලි", "meaning": "බින්තල්", "category": "plant" },
    { "word": "මෙලවජ්", "meaning": "මිරිස්, සාදිලිංගම්", "category": "mineral" },
    { "word": "මෙලවජ් කනු", "meaning": "ලූනු", "category": "plant" },
    { "word": "මෙලවජ්බාය", "meaning": "තඹ", "category": "mineral" },
    { "word": "මෙලවජ්ගක්", "meaning": "සුදු ලූනු", "category": "plant" },
    { "word": "මෙලවජ්ප", "meaning": "මිරිස්, සාදිලිංගම්", "category": "plant" },
    { "word": "මෙලවජ්ප්‍රිය", "meaning": "ගොඩ මිරිස්", "category": "plant" },
    { "word": "මෙලවජ්ජල", "meaning": "කෝපි", "category": "plant" },
    { "word": "මෙලවජ්මුඛ", "meaning": "තඹ", "category": "mineral" },
    { "word": "මෙලවජ්ජා", "meaning": "කෝපි", "category": "plant" },
    { "word": "යක් ඇස් පත්", "meaning": "කුඹුරු කොළ", "category": "plant" },
    { "word": "යක් ඇස් බිජු", "meaning": "කුඹුරු ඇට", "category": "plant" },
    { "word": "යක් එරබදු", "meaning": "සොබන මන්දාර, පාරිභද්‍ර (එරබදු වගියක්)", "category": "plant" },
    { "word": "යක් කොමඬු", "meaning": "ඉසු වාරුණී, =(බොංග පුහුල්=ඔඩ්ඩි පුහුල්)", "category": "plant" },
    { "word": "යක් බේරිය", "meaning": "අඬනගිරියා, වේලුනු කරල් සොලවන විට නාදයක් (ශබ්දක්) නික්මෙන පැණි තෝර කොළ වලට මඳක් සමාන අඩි තුනකට වඩා උස් නොවූ පැලෑටිය කි.", "category": "plant" },
    { "word": "යක්‍ෂ", "meaning": "කුඹුරු ඇට", "category": "plant" },
    { "word": "යක්‍ෂක", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "යක්‍ෂකර්දම", "meaning": "කොකුම් මල්, අගිල්, කස්තුරි, කපුරු, සඳුන්, මේ හැම සම භාගව මිශ්‍ර කිරීම යක්‍ෂකර්දම නම් වේ.", "category": "compound" },
    { "word": "යක්‍ෂ කරු", "meaning": "නුග ගස", "category": "plant" },
    { "word": "යක්‍ෂ ද්‍රාක්‍ෂ (යක්‍ෂ ද්‍රාග)", "meaning": "කුඹුරු වැළ", "category": "plant" },
    { "word": "යක්‍ෂධූප", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "යක්‍ෂ ඵල", "meaning": "ඉඟිනි ඇට", "category": "plant" },
    { "word": "යක්‍ෂභූෂණ", "meaning": "ඉළක්", "category": "plant" },
    { "word": "යක්‍ෂමක්‍ෂී", "meaning": "මුද්දරප්පලම් වැල", "category": "plant" },
    { "word": "යක්‍ෂමෝදංසී", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "යක්‍ෂවාක්‍ෂ", "meaning": "තුන් පුලිල", "category": "plant" },
    { "word": "යක්‍ෂශ්‍රෙෂ්ඨ", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "යක්‍ෂාක්‍ෂී", "meaning": "කුඹුරු වැල, කුඹුරු ඇට", "category": "plant" },
    { "word": "යක්‍ෂාමලක", "meaning": "පිණඬා ඉඳි ගෙඩි", "category": "plant" },
    { "word": "යක්‍ෂාවාස", "meaning": "තුඹ ගස", "category": "plant" }
];

