// data_116_124.js - පිටු 116 සිට 124 දක්වා සියලුම වචන
const data_extra_116_124 = [
  // --- පිටුව 116 ---
  { "word": "කුකුණ්ඨක", "meaning": "කිහිරි, උඳු, වැල්කසඹිලියා", "category": "plant" },
  { "word": "කුකුණික", "meaning": "ළදරුවන්ට ඇතිවන ඇස් රෝගයකි", "category": "symptom" },
  { "word": "කුකුඤ්ඤනී", "meaning": "දුදු වැල්", "category": "plant" },
  {
    "word": "කුකුරමාන (මදන)",
    "scientific": "Randia Dumetorum",
    "meaning": "මෙය මකුළු කොළ වලට සමාන කොළ ඇති, කුඩා කිහිරි ගෙඩි වල හැඩහුරුකමට සමාන ගෙඩි ඇති, අඩි 40 ක් හෝ 50 ක් පමණ උසට වැඩෙන ගසකි. කට හාරවන සුළු කටුක රසයකින් යුත් මේ ගසේ ගෙඩි ලාටු දිය වීමට හා ශ්ලේෂ්මාධික ඉදිමුම් රෝග වලට ඖෂධ වශයෙන් යොදනු ලැබේ. මේ ගෙඩි ආරක්‍ෂා සහිත යෙදූ කල විරේකයක් ද වේ. තද මත් ගතියකින් යුත් මේවා නොයෙක් සතුන් මත් කිරීමට ද යොදා ගනිති. ගර්භණීන්ට ද අගුණ කර ය.",
    "category": "plant"
  },
  { "word": "කුකුල් පක්", "meaning": "කුකුරමාන ගෙඩි", "category": "plant" },
  { "word": "කුකුල් පගර", "meaning": "කුකුල් වසුරු", "category": "treatment" },
  { "word": "කුකුල් ලැම්බියේ ඇට", "meaning": "කුකුලාගේ ඉලපුළුවල ඇට", "category": "treatment" },
  { "word": "කුකුල් වසුරු", "meaning": "කුකුල් බෙටි", "category": "treatment" },
  { "word": "කුකුල", "meaning": "දැහැවියා, ගින්දර", "category": "treatment" },
  { "word": "කුකුල්ල", "meaning": "ජාවාල වගියෙහි වූ මඳක් තිත්ත රස ඇති අල වගියක්", "category": "plant" },
  { "word": "කුකුලු", "meaning": "රළු, කකීශ", "category": "treatment" },
  { "word": "කුකුලුසුන්", "meaning": "කහිටකශාලී", "category": "plant" },
  { "word": "කුකුෂ්ඨ", "meaning": "උඳු", "category": "plant" },
  { "word": "කුකෙලෙ", "meaning": "පොකුණ", "category": "treatment" },
  { "word": "කුකොල", "meaning": "බැබර ගස", "category": "plant" },
  { "word": "කුඩස", "meaning": "වරා", "category": "plant" },
  { "word": "කුඩකුම", "meaning": "සඳුන් මල්, කොකුම්, කොට්ටම්, උපුල් කොළ", "category": "plant" },
  { "word": "කුඩකුමපප්‍ර", "meaning": "කොකුම් මල්, සඳුන් මල්", "category": "plant" },
  { "word": "කුඩකුම්ම", "meaning": "කොකුම්", "category": "plant" },
  { "word": "කුඩකුම් රේණු", "meaning": "කොකුම් පරාග (රොන්)", "category": "plant" },
  { "word": "කුඩකුඹ", "meaning": "ඉබුල් ගස", "category": "plant" },
  { "word": "කුඩකුඹාගරුක", "meaning": "රන්වන් සඳුන්", "category": "plant" },
  { "word": "කුඩකුම්", "meaning": "මිය දුදු වැල්", "category": "plant" },
  { "word": "කුඩගනී", "meaning": "මිය දුදු වැල්", "category": "plant" },
  { "word": "කුඩගිලි", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "කුඩගිලිත්තෙනයෙයි", "meaning": "දුම්මල තෙල්", "category": "treatment" },
  { "word": "කුඤ්චිකාසොඝා", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කුච්ඡ", "meaning": "හෙල පිසුම්, (හෙලපුල්)", "category": "plant" },
  { "word": "කුච්ඡුට", "meaning": "එඬරු", "category": "plant" },
  { "word": "කුච්ඡුම", "meaning": "සිතියා ගස", "category": "plant" },

  // --- පිටුව 117 ---
  { "word": "කුච", "meaning": "තනය", "category": "treatment" },
  { "word": "කුචණි", "meaning": "මූරුවා වැල්", "category": "plant" },
  { "word": "කුචණිකා", "meaning": "මූරුවා වැල්", "category": "plant" },
  { "word": "කුචන්දන", "meaning": "රත් සඳුන්, වැල්මදට, පතගි", "category": "plant" },
  { "word": "කුචන", "meaning": "හුන්සවාලු", "category": "plant" },
  { "word": "කුචඵල", "meaning": "දෙළුම්, (දඹ) දිවුල් ගස", "category": "plant" },
  { "word": "කුචරන", "meaning": "හුන්තමුවාලු", "category": "plant" },
  { "word": "කුචිමුක", "meaning": "ගල්කුර, සාපුර, කුරපලා", "category": "plant" },
  { "word": "කුචිල", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "කුචිලා", "meaning": "ගොඩකදුරු", "category": "plant" },
  { "word": "කුජ", "meaning": "ගස, අඟුරු", "category": "treatment" },
  { "word": "කුජ්ජ", "meaning": "ඇඹුල, ඇඹුල", "category": "treatment" },
  { "word": "කුපො", "meaning": "කුඩා ගස", "category": "plant" },
  { "word": "කුඤ්චඵලා", "meaning": "අළු පුහුල්", "category": "plant" },
  { "word": "කුඤ්චනන්ද", "meaning": "රත්සඳුන්", "category": "plant" },
  { "word": "කුඤ්චි", "meaning": "කළු දුරු, මදදුරු", "category": "plant" },
  { "word": "කුඤ්චිකා", "meaning": "මදදුරු, කළුදුරු, හීන් එන්සාල්", "category": "plant" },
  { "word": "කුඤ්චනා", "meaning": "තෝරා, තුවරලා මල්", "category": "plant" },
  { "word": "කුඤ්චිනා", "meaning": "මහදුරු, කළුදුරු, හීන් එන්සාල්", "category": "plant" },
  { "word": "කුඤ්ජකා", "meaning": "උවන්සාල", "category": "plant" },
  { "word": "කුඤ්ජප්‍රිය", "meaning": "වදකහ", "category": "plant" },
  { "word": "කුඤ්ජර", "meaning": "මසිල, රක්ලොත්, පුමිල, ඇසලූ", "category": "plant" },
  { "word": "කුඤ්ජරකණිකා", "meaning": "ගජ තිප්පිලි", "category": "plant" },
  { "word": "කුඤ්ජරකජාරිබුල", "meaning": "රාබු", "category": "plant" },
  { "word": "කුඤ්ජර පිප්පලි", "meaning": "ඇත් වගපුල්, (ගජ තිප්පිලි) සිවිය", "category": "plant" },
  { "word": "කුඤ්ජරා", "meaning": "මලිත ගස, පලොල් ගස", "category": "plant" },
  { "word": "කුඤ්ජරාශන", "meaning": "ඇසල, බෝ ගස", "category": "plant" },
  { "word": "කුඤ්ජරාහ්වය", "meaning": "කොවඩිබුලා ගස", "category": "plant" },
  { "word": "කුඤ්ජරී", "meaning": "මසිල ගස", "category": "plant" },
  { "word": "කුඤ්ජරිකා", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "කුඤ්ජරී", "meaning": "මසිල, මහපොහොඹරු", "category": "plant" },
  { "word": "කුඤ්ජල", "meaning": "ඇඹුල් ගස, කාඩිය, හීලූ", "category": "treatment" },
  { "word": "කුඤ්ජවාලුකා", "meaning": "සූදුරු", "category": "plant" },
  { "word": "කුඤ්ජිකා", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කුට්ට", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "කුට්ඨසනී", "meaning": "කළුකම්මේරිය, කුට්ඨිල", "category": "plant" },
  { "word": "කුට්ඨිල", "meaning": "මල් කැකුළු", "category": "plant" },
  { "word": "කුට", "meaning": "රක් ගස, මීලබඩ ගස, කට රොලු, නිවුල් ගස, කොට්ටම්", "category": "plant" },
  { "word": "කුටක", "meaning": "කෙළිඳ ගස", "category": "plant" },
  { "word": "කුටක භෙදි", "meaning": "කඩුකරෝෂණ", "category": "plant" },
  { "word": "කුටකා", "meaning": "සිහින් මැඩගු, මස්බැද්ද, (වෙලිප්පරිත්ති)", "category": "plant" },
  { "word": "කුටජ", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කුටජ ඵල", "meaning": "කෙළිඳ ඇට", "category": "plant" },
  { "word": "කුටජ බීජ", "meaning": "කෙළිඳසාල්", "category": "plant" },
  { "word": "කුටජසක් ක්‍රියා", "meaning": "කෙළිඳ පොතු", "category": "plant" },
  { "word": "කුටජ සුධා", "meaning": "කෙළිඳ සුනු", "category": "plant" },
  { "word": "කුටජී", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කුටජිකා", "meaning": "කෙළිඳ ඇට", "category": "plant" },
  { "word": "කුටජීව", "meaning": "බුන්සාරණ ගස", "category": "plant" },
  { "word": "කුටජො", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කුටතුඹී", "meaning": "තිත්තලබු", "category": "plant" },
  { "word": "කුටුඹී", "meaning": "තිත්තලබු", "category": "plant" },
  { "word": "කුටන්", "meaning": "කොවිල", "category": "plant" },
  { "word": "කුටන්තන", "meaning": "කලාඳුරු, (වම්මුතු) කොවිල, දසපුර, කොට්ටම්, බුළු", "category": "plant" },
  { "word": "කුටන්හරා", "meaning": "කොවිල, දසපුර, පාලාබත නම් පලා වෙසෙස", "category": "plant" },
  { "word": "කුටනී", "meaning": "මඟදුරු වැල", "category": "plant" },
  { "word": "කුටප", "meaning": "නෙළුම් මල", "category": "plant" },
  { "word": "කුටර", "meaning": "ගස, (වාක්‍යය)", "category": "plant" },
  { "word": "කුටරවාහිනි", "meaning": "හුන්සවාලු", "category": "plant" },
  { "word": "කුටරැණා", "meaning": "හුන්සවාලු", "category": "plant" },
  { "word": "කුටල", "meaning": "කොබෝලිල", "category": "plant" },
  { "word": "කුටඝට", "meaning": "පුවක්", "category": "plant" },
  { "word": "කුටස්ථාන", "meaning": "පිටවක්කා (නවකන්දි ලිය = බිම් නෙල්ලි)", "category": "plant" },
  { "word": "කුටසිබිලි", "meaning": "කොලනිඹුල්", "category": "plant" },
  { "word": "කුටාමොද", "meaning": "උරලෑ පීටි", "category": "treatment" },

  // --- පිටුව 118 ---
  { "word": "කුටාරු", "meaning": "ගස (රුක)", "category": "plant" },
  { "word": "කුටි", "meaning": "ගෙය, ගස, ශිරස්ස, වතුර, ඉඟුරු", "category": "treatment" },
  { "word": "කුටිකා", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "කුටිව", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "කුටිසඤ්ජර", "meaning": "වල්නමපලා", "category": "plant" },
  { "word": "කුටිමින්", "meaning": "වාෂභක (ඔසබිය) (අෂ්ටක වගියේ ඔසුවක්)", "category": "plant" },
  { "word": "කුටීර", "meaning": "තුවරලා", "category": "plant" },
  { "word": "කුටිල", "meaning": "සුදු පියලි, අරණක්කසා, තුවරලා මල්, කිණිහිරි, ගැට පිච්ච, ඉඟුරු", "category": "plant" },
  { "word": "කුටිල කණ්ටක", "meaning": "කටු කිහිිරි", "category": "plant" },
  { "word": "කුටිලසන්තක", "meaning": "සිවිය ගස", "category": "plant" },
  { "word": "කුටිලා", "meaning": "අරණක් කසා (හරන්කහ)", "category": "plant" },
  { "word": "කුටිලාලය", "meaning": "හරංකසා", "category": "plant" },
  { "word": "කුටී", "meaning": "එල කෙළිඳ ගස, ගින්පැණිස ගස", "category": "plant" },
  { "word": "කුඩ", "meaning": "දිවුල් ගස", "category": "plant" },
  { "word": "කුඩස්", "meaning": "උපුල් කොළ", "category": "plant" },
  { "word": "කුඩරිණී", "meaning": "සදුහුන්සවාලු", "category": "plant" },
  { "word": "කුඩාර", "meaning": "රේරා හෝ නිද", "category": "plant" },
  { "word": "කුඩිකා", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "කුඩිල්ලක", "meaning": "රතුසාරණ", "category": "plant" },
  { "word": "කුණ්ඩර", "meaning": "තලා ගස", "category": "plant" },
  { "word": "කුණ්ඩේරක", "meaning": "වෙලා ගස", "category": "plant" },
  { "word": "කුණ්ඩේරජ", "meaning": "සදුතලා ගස", "category": "plant" },
  { "word": "කුණ්ඩේරව", "meaning": "අඳුනලා", "category": "plant" },
  { "word": "කුඩ්මල", "meaning": "ඇඹුල", "category": "treatment" },
  { "word": "කුබ්භක", "meaning": "අඳුර", "category": "treatment" },
  { "word": "කුඩ්බ", "meaning": "නෑලියෙන් සතරෙන් කොටස", "category": "treatment" },
  { "word": "කුඩම්පිටෙයි", "meaning": "පනමපෙති (රහස් බෙහෙත් වට්ටෝරුවක ඔසුවක්)", "category": "plant" },
  { "word": "කුඬලී", "meaning": "කොබෝලිල", "category": "plant" },
  { "word": "කුඬුහුකුම්", "meaning": "හීන් කරවිල", "category": "plant" },
  { "word": "කුඩා අදිකාරි", "meaning": "ඉඟුරු (රහස් බෙහෙත් වට්ටෝරුවක ඔසුවක්)", "category": "plant" },
  { "word": "කුඩා කලුවා", "meaning": "සීතල පොළොවේ හටගන්නා පුරුක් පුරුක් ඇති කළු පාට වැලක්", "category": "plant" },
  { "word": "කුඩාගල්", "meaning": "උපුල්", "category": "plant" },
  { "word": "කුඩා පනීක්කිල", "meaning": "අරණක්කසා (රහස් බෙහෙත් වට්ටෝරුවක ඔසුවක්)", "category": "plant" },
  { "word": "කුඩාරත්න මූඩියන්සේ", "meaning": "ගම්මිරිස් (රහස් බෙහෙත් වට්ටෝරුවක ඔසුවක්)", "category": "plant" },
  { "word": "කුඩා සුදනා", "meaning": "සීතල ගුණයෙන් යුත් කහ ලබ හටගන්නා පොඩි මල් ඇති පැළෑටියක්", "category": "plant" },
  {
    "word": "කුඩා හැඬියා",
    "meaning": "සැත්ගේ පෑරණි ග්‍රීවාභරණය (මාලය) ක හැඩ හුරු කමින් යුත් එකට ගෙතී තිබෙන සිහින් කෙඳි වැනි කොළ ඇති, දියසිරාව ඇති පෙදෙස් වල දියසෙවෙල් සහිත ගස්වල පැලවී වැවෙන උඩවැඩියා වර්ඟයක්. මේවා අග වැල් මල් (බුලත් කරල්) වැනි කුඩා කරල් සෑදේ. හොඳට වැඩෙන පැළයක් පවා අඩි දෙකකට වඩා දික් නොවේ.",
    "category": "plant"
  },
  { "word": "කුණිකාරන", "meaning": "නිළුපුල්, (නිල් මානෙල්)", "category": "plant" },
  { "word": "කුඩු මුහුන්", "meaning": "කුඩු මුහුන්", "category": "treatment" },
  { "word": "කුඩු ගම් දෙමිට්ස්", "meaning": "කුඩම්මිරිස් සහ ගම්මිරිස්", "category": "plant" },
  { "word": "කුඩ්බ", "meaning": "නෑලියෙන් සතරෙන් පංගුව", "category": "treatment" },
  { "word": "කුඩ්බය", "meaning": "මනා බාගය හෝ පලම් අට", "category": "treatment" },
  { "word": "කුඩුමනි", "meaning": "ඔලිඳ වැල්", "category": "plant" },
  { "word": "කුඩුමල", "meaning": "මුකල කැකුල (මෙරූ මල් පොහොට්ටුව)", "category": "plant" },

  // --- පිටුව 119 ---
  {
    "word": "කුඩු වෙලග",
    "scientific": "Mallotus Phillippinensis",
    "meaning": "මෙම ගසේ කඳ ගුරු පාටය. කොළ හැඩ හුරුකමෙන් අවටිකිකා කොළ වලට සමාන ය. දිග අඟල් 7 ක් හා පළල අඟල් 3 ක් පමණ ඇත. කොළ වල යටි පැත්ත ගුරු පාටය. උඩ පැත්ත නිල් පාට ය. කුඩා මසන් ගෙඩි වැනි මේ ගසේ හටගන්නා ගෙඩි වල පොතු කෘමිනාශක ඖෂධයකි. දරක රෝග වලට ප්‍රත්‍යක්ෂ ය. ගෙඩි ඇඟිලි දෙකට ගෙන පොඩි කළ විට තද කහ පාටකින් යුක්තයි. කෑරූවිට රතු පාට සි.",
    "category": "plant"
  },
  { "word": "කුණ", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "කුණ්ඨක", "meaning": "රන්වන් කටු කරඬු", "category": "plant" },
  { "word": "කුණ්ඨකුරණ්ඩ", "meaning": "රන්වන් කටු කරඬු ගස", "category": "plant" },
  { "word": "කුණ්ඨි", "meaning": "අඳුනලා", "category": "plant" },
  { "word": "කුණ්ඩී", "meaning": "රත්කිහිරියල්", "category": "plant" },
  { "word": "කුණ්ඩන", "meaning": "සුන් සහල් (පොඩි වූ හාල් ඇට)", "category": "treatment" },
  { "word": "කුණ්ඩල", "meaning": "රතු පෙනන්ත ගස", "category": "plant" },
  { "word": "කුණ්ඩ ගෝලක", "meaning": "කාඩි", "category": "treatment" },
  { "word": "කුණ්ඩටල", "meaning": "අග්‍ර ගස", "category": "plant" },
  { "word": "කුණ්ඩලපල", "meaning": "අග්‍ර ගස", "category": "plant" },
  { "word": "කුණ්ඩලනා", "meaning": "රස කිඳ", "category": "plant" },
  { "word": "කුණ්ඩලපලී", "meaning": "ඉන්සල් ගස, අග්‍රගස", "category": "plant" },
  { "word": "කුණ්ඩලී", "meaning": "අමු, රසකිඳ, සිහින් එන්සාල්, රත්ගිරියල්, කොබෝලිල, ඇසල", "category": "plant" },
  { "word": "කුණ්ඩලිනී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "කුණ්ඩවල්ලි", "meaning": "අග්‍ර, ඉන්සලු", "category": "plant" },
  { "word": "කුණ්ඩමුනී", "meaning": "ඔලිඳ", "category": "plant" },
  { "word": "කුණඹ", "meaning": "නියපිරිත්තා", "category": "plant" },
  { "word": "කුණඹ", "meaning": "කොවිල", "category": "plant" },
  { "word": "කුණක්ඛ", "meaning": "වල් නමපලා", "category": "plant" },
  { "word": "කුණ්ඨි", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "කුණී", "meaning": "තුනහ කට මාසය", "category": "treatment" },
  { "word": "කුණුමැල්ල", "meaning": "මැල්ල වගියක්", "category": "treatment" },
  { "word": "කුක්කුටුමුත්‍රා", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "කුත්සලා", "meaning": "අවරිය ගස", "category": "plant" },
  { "word": "කුත්සිතාඛ්‍යා", "meaning": "බක්මී, කොලොම්, බක්මී", "category": "plant" },
  { "word": "කුත්සිත නීලමලී", "meaning": "ඉබුල්", "category": "plant" },
  { "word": "කුතක", "meaning": "රසඳුන්", "category": "treatment" },
  { "word": "කුතාප", "meaning": "කුස තණ", "category": "plant" },
  { "word": "කුතකින", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "කුතුම්බ", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "කුතුම්බක", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "කුතුම්බර", "meaning": "කෝන්, ශාණ", "category": "plant" },
  { "word": "කුතුම්බරී", "meaning": "කොත්තඹුරු, (කොත්තමල්ලි)", "category": "plant" },

  // --- පිටුව 120 ---
  { "word": "කුතුම්බුරු", "meaning": "හිඹිරි ගෙඩි", "category": "plant" },
  { "word": "කුතෝරැකා", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "කුතෝරැළ", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "කුට්", "meaning": "කුස තණ, ඊතණ", "category": "plant" },
  { "word": "කුජදල", "meaning": "කොබෝලිල ගස", "category": "plant" },
  { "word": "කුද්ර", "meaning": "කොබෝලිල, ඇසලූ", "category": "plant" },
  { "word": "කුදිරවල්ලී", "meaning": "අස්වැන්න, කිිකිරිදිය", "category": "plant" },
  { "word": "කුදුදල", "meaning": "අන්ඳර ගස", "category": "plant" },
  { "word": "කුදුම්බක", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "කුදුරැක්", "meaning": "වනුක්", "category": "plant" },
  { "word": "කුදෙහිලක", "meaning": "කෙසෙල්", "category": "plant" },
  { "word": "කුදුණි", "meaning": "කුද්දිටිය (රෝගයක්)", "category": "symptom" },
  { "word": "කුන්කුමපට්ටෙහි", "meaning": "කොකුම් පොතු", "category": "plant" },
  { "word": "කුන්වය නන්දන", "meaning": "රත්සඳුන්", "category": "plant" },
  { "word": "කුන්පරි", "meaning": "මසිල", "category": "plant" },
  { "word": "කුන්ති", "meaning": "රත්ගිරියල්, මනෝසිල", "category": "treatment" },
  { "word": "කුණ්ඩිකේරිකා", "meaning": "කෙම්වැල්", "category": "plant" },
  { "word": "කුන්තලවධිනි", "meaning": "කිිකිරිදිය", "category": "plant" },
  { "word": "කුන්තලිකා", "meaning": "ඉරිවේරිය", "category": "plant" },
  { "word": "කුන්තාල", "meaning": "ඉරිවේරිය", "category": "plant" },
  { "word": "කුන්තලෝගිර", "meaning": "කුබේර", "category": "treatment" },
  { "word": "කුන්තී", "meaning": "ගුගුල් ගස, ඉඳුසල් ගස", "category": "plant" },
  { "word": "කුන්ද", "meaning": "වැකොඳ, සමන්මල්, කොල්ලු, කුන්දිරුක්කන්, කකුළුසුනු", "category": "plant" },
  { "word": "කුන්දක", "meaning": "කුන්දිරුක්කන් ගස", "category": "plant" },
  { "word": "කුන්දරු", "meaning": "තුන්පත් කුරැඳු", "category": "plant" },
  { "word": "කුන්දරුක්", "meaning": "කුඹුරු", "category": "plant" },
  { "word": "කුන්දරිකා", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "කුන්දරු", "meaning": "අලරිය, (කණේරා) කළු ලුණු, වනුක්", "category": "treatment" },
  { "word": "කුන්දල්", "meaning": "මදුවැල්, ඔලිඳ", "category": "plant" },
  { "word": "කුන්ද සහවා", "meaning": "බෝලිද්ද", "category": "plant" },
  { "word": "කුන්ද", "meaning": "සොහොලු, පිච්ච, බෝලිද්ද", "category": "plant" },
  { "word": "කුකුදල", "meaning": "මහ ඇසල ගස", "category": "plant" },
  { "word": "කුන්දර", "meaning": "තුන්පත් කුරැඳු", "category": "plant" },
  { "word": "කුන්දුරු", "meaning": "තුන්පත් කුරැඳු, ඉඳුසල්, ගුගුල්", "category": "plant" },
  { "word": "කුන්දරිකී", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "කුන්දරිතනම", "meaning": "කුන්දිරුක්කන්", "category": "plant" },
  { "word": "කුන්දරිත්තනම", "meaning": "කුන්දිරුක්කන්", "category": "plant" },
  { "word": "කුඤ්ඤුක්කන්", "meaning": "කුන්දිරුක්කන්", "category": "plant" },
  { "word": "කුඤ්ඤ", "meaning": "දුම්මල, කුන්දිරුක්කන්, තුන්පත් කුරැඳු", "category": "plant" },
  { "word": "කුඤ්ඤග්‍රාන්ව", "meaning": "කුන්දිරුක්කන්", "category": "plant" },
  { "word": "කුඤ්ඤරු", "meaning": "කවට්ට කුමන්ජල්", "category": "plant" },
  { "word": "කුඤ්ඤරුක", "meaning": "කෙසෙල්, කුන්දිරුක්කන්", "category": "plant" },
  { "word": "කුඤ්ඤරුකි", "meaning": "කොවිල, ඉන්සලු", "category": "plant" },
  { "word": "කුඤ්ඤමණි", "meaning": "ඔලිඳ", "category": "plant" },
  { "word": "කුනබ්", "meaning": "කොවිල", "category": "plant" },
  { "word": "කුහව", "meaning": "කොබෝලිල", "category": "plant" },
  { "word": "කුහවී", "meaning": "හිරියල්, මනෝසිල", "category": "treatment" },
  { "word": "කුහවටු", "meaning": "බුලත්", "category": "plant" },
  { "word": "කුතප", "meaning": "කුස තණ, ඊතණ", "category": "plant" },
  { "word": "කුහලින්", "meaning": "කතුරුමුරුංගා", "category": "plant" },
  { "word": "කුතාශක", "meaning": "ඇල්කසඹිලියා", "category": "plant" },
  { "word": "කුනිමිබ", "meaning": "බිමිකොහොඹ", "category": "plant" },
  { "word": "කුනී", "meaning": "කිරිබෝගස, තක්නිරක", "category": "plant" },
  { "word": "කුප්ත", "meaning": "උක්ගස", "category": "plant" },
  { "word": "කුපප", "meaning": "සකපුෂ්ප", "category": "plant" },
  { "word": "කුප්පකිරෙහි", "meaning": "කුරක්කම්පලා", "category": "plant" },
  { "word": "කුප්පමේනිය", "meaning": "මාජ්ජාර මෝහිනී, මීකු බඬයට ප්‍රත්‍යක්ෂ විෂ නාශක පැළෑටියකි.", "category": "plant" },
  { "word": "කුප්පලකෝෂි", "meaning": "පුපුල වැල, වැල්පුපුල", "category": "plant" },
  { "word": "කුපපතස", "meaning": "කොස් ගස", "category": "plant" },
  { "word": "කුපාස", "meaning": "කදුරු", "category": "plant" },
  { "word": "කුප්පී", "meaning": "සිහින් කිහිරි, සුළු කිහිරි, ගොබකදුරු", "category": "plant" },
  { "word": "කුබීර්", "meaning": "මූරැක, කරල්සැබ", "category": "plant" },
  { "word": "කුබ්ජක", "meaning": "රක්ත සෙව්වන්දි (සුදු රෝස)", "category": "plant" },

  // --- පිටුව 121 ---
  { "word": "කුබ්ජකණ්ඨක", "meaning": "හෙල කිහිරි", "category": "plant" },
  { "word": "කුබ්ජපර්ණිකා", "meaning": "මැඩගු, මස්බැද්ද (වෙලිප්පරිත්ති)", "category": "plant" },
  { "word": "කුබ්ජපුෂ්ප", "meaning": "කසාවන් ගිරිනීල්ල", "category": "plant" },
  { "word": "කුබ්ජුකු", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "කුබුද", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "කුබුදන", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "කුබුලු", "meaning": "කරඳ, කුඹුක් ගස", "category": "plant" },
  { "word": "කුබේර", "meaning": "බූව ගස, කුඹුරු වැල", "category": "plant" },
  { "word": "කුබේරක", "meaning": "කුඹුරු වැල, නන්දි වාක්‍යය", "category": "plant" },
  { "word": "කුබේරනෙත්‍රා", "meaning": "පලොල් ගස, කුඹුරු වැල", "category": "plant" },
  { "word": "කුබේරබීජු", "meaning": "කුඹුරු ඇට", "category": "plant" },
  { "word": "කුබේ", "meaning": "කුඹුරු වැල, බූ ගස, පලොල්", "category": "plant" },
  { "word": "කුබේරාක්‍ෂි", "meaning": "කුඹුරු වැල", "category": "plant" },
  { "word": "කුබේරාහ්වය", "meaning": "නන්දි වාක්‍යය", "category": "treatment" },
  { "word": "කුමිකුම්ප්පු", "meaning": "සඳුන් මල්", "category": "plant" },
  { "word": "කුමින", "meaning": "දත්ත", "category": "treatment" },
  { "word": "කුම්බිකා", "meaning": "මුද්දරප්පලම් වැල - ලබු වැල", "category": "plant" },
  { "word": "කුම්බිය", "meaning": "දියපරබලා", "category": "plant" },
  { "word": "කුම්බිලයා", "meaning": "අවුල්දනී (කිඹුලා)", "category": "treatment" },
  { "word": "කුම්බස", "meaning": "ලබු", "category": "plant" },
  { "word": "කුම්භ", "meaning": "ගුගුල්, ඇත්දෙමට, ද්‍රෝණ 20 ක බර ප්‍රමාණය, ජයපාල, කරබෙයියා, පලොල්, පුස්වෙන්න", "category": "treatment" },
  { "word": "කුම්භක", "meaning": "අමුක්කරා, මිණීරන්", "category": "treatment" },
  { "word": "කුම්භකර්ණී", "meaning": "හරංකහ", "category": "plant" },
  { "word": "කුම්භකර්ණිකා", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කුම්භකරෙවනා", "meaning": "ජයපාල ගස", "category": "plant" },
  { "word": "කුම්භකාරී", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කුම්භකාරිකා", "meaning": "කොල්ලු, මනෝසිල", "category": "treatment" },
  { "word": "කුම්භප්", "meaning": "කතුරුමුරුංගා ගස", "category": "plant" },
  { "word": "කුම්භභූ", "meaning": "කසට ගස", "category": "plant" },
  { "word": "කුම්භුගුමිබි", "meaning": "දිය ලබු වැල", "category": "plant" },
  { "word": "කුම්භපුටා", "meaning": "සුදු නිරස්සවාලු", "category": "plant" },
  { "word": "කුම්භපුෂ්පී", "meaning": "රත් පලොල් ගස", "category": "plant" },
  { "word": "කුම්භඵල", "meaning": "කොමඩු, පත්තක්කා, කොවඩිබුලා", "category": "plant" },
  { "word": "කුම්භය", "meaning": "පලම් 512 (රාත්තල් 64)", "category": "treatment" },
  { "word": "කුම්භයෝති", "meaning": "ගැටතුඹ, හෙල කණේරා, සුදු අලරිය, කුකුරු මුවන්, හෙල කතුරුමුරුංගා", "category": "plant" },
  { "word": "කුම්භයෝනිකා", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "කුම්භලා", "meaning": "මුඛමගණ (වෙල්ලුඹ)", "category": "treatment" },
  { "word": "කුම්භවිකාර", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කුම්භවීජ(ක)", "meaning": "කරඳ වෙසෙසක්", "category": "plant" },
  { "word": "කුම්භවිරායී", "meaning": "කොසඹ, මහ කොසඹ", "category": "plant" },
  { "word": "කුම්භා", "meaning": "කරපිංචා, කලු නිරස්සවාලු", "category": "plant" },
  { "word": "කුම්භාඛ්‍යා", "meaning": "රත් පලොල්", "category": "plant" },
  { "word": "කුම්භාණ්ඩී", "meaning": "අළුපුහුල්", "category": "plant" },
  { "word": "කුම්භාරී", "meaning": "ඇත්දෙමට, අළුපුහුල්", "category": "plant" },
  { "word": "කුම්භාලාබු", "meaning": "මනයලබු", "category": "plant" },
  { "word": "කුම්භි", "meaning": "කරබෙයියා, ඇත්දෙමට, දඹ, දියපරබලා, සින් මද, ලෝලු, ඇල්කසඹිලියා", "category": "plant" },
  { "word": "කුම්භිකා", "meaning": "රතැඹුල ගෙඩි, රන් බිලු ගෙඩි, දියපරබල්", "category": "plant" },
  { "word": "කුම්භිකපර්ණ", "meaning": "කසට ගස", "category": "plant" },
  { "word": "කුම්භික ඵල", "meaning": "කසට ගෙඩි", "category": "plant" },
  { "word": "කුම්භිකා", "meaning": "කසට ගස, පලොල්, ඇත්දෙමට, තඹලපලා, අස්ගොදු, දියපරබලා, මුද්දරප් පලම්, ගැටතුඹ", "category": "plant" },
  { "word": "කුමිනිත්", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "කුමිනිති", "meaning": "මුංවැන්න, ජයපාල ගස", "category": "plant" },
  { "word": "කුමිනිිට් පල", "meaning": "ජයපාල ගෙඩි", "category": "plant" },
  { "word": "කුමිනිිට් විජ්", "meaning": "ජයපාල ඇට", "category": "plant" },
  { "word": "කුම්භිපාකි", "meaning": "කරපිංචා ගස", "category": "plant" },
  { "word": "කුම්භිවාක්‍ය", "meaning": "සිහින් මිදි, ඇල්කස බිලියා, දෙඹ, කරපිංචා, ඇත් දෙමට, දියපරබල්", "category": "plant" },
  { "word": "කුම්භිවෘක්ෂ", "meaning": "කසට ගස", "category": "plant" },

  // --- පිටුව 122 ---
  { "word": "කුම්බී", "meaning": "ඇඹුල් ඇඹිලිය", "category": "plant" },
  { "word": "කුම්බීර", "meaning": "කරබෙයියා", "category": "plant" },
  { "word": "කුම්බීරී", "meaning": "කරබෙයියා", "category": "plant" },
  { "word": "කුම්ලී", "meaning": "ඇඹුල", "category": "plant" },
  { "word": "කුම", "meaning": "පෘථිවි ධාතුව", "category": "treatment" },
  { "word": "කුය", "meaning": "වතුර", "category": "treatment" },
  { "word": "කුයව", "meaning": "තණ වර්ගයක් (යව වැනි)", "category": "plant" },
  { "word": "කුර", "meaning": "කටු කිහිරි, කරල්සැබෝ", "category": "plant" },
  { "word": "කුරණ්ට", "meaning": "කටුකරඬු ගස", "category": "plant" },
  { "word": "කුරණ්ටක", "meaning": "කරල්සැබෝ, කටුකරඬු", "category": "plant" },
  { "word": "කුරණ්ඩ", "meaning": "කටුකරඬු", "category": "plant" },
  { "word": "කුරත්ථ", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කුරබක", "meaning": "සෙව්වන්දි (රතු රෝස) කටුකරඬු", "category": "plant" },
  { "word": "කුරබක පුෂ්ප", "meaning": "කටුකරඬු මල්", "category": "plant" },
  { "word": "කුරබ", "meaning": "කටුකරඬු", "category": "plant" },
  { "word": "කුරබිකා", "meaning": "රතු නිදිකුම්බා", "category": "plant" },
  { "word": "කුරභ", "meaning": "ගෙලසැබෝ, කරල්සැබෝ, සූදුරු", "category": "plant" },
  { "word": "කුරම", "meaning": "කැස්බෑවා", "category": "treatment" },
  { "word": "කුරල්", "meaning": "කරල්සැබෝ", "category": "plant" },
  { "word": "කුරව", "meaning": "කටුකරඬු", "category": "plant" },
  { "word": "කුරවක", "meaning": "රතු සෙව්වන්දි, කටුකරඬු", "category": "plant" },
  { "word": "කුරවල්", "meaning": "කරල්සැබෝ", "category": "plant" },
  { "word": "කුරවි", "meaning": "සූදුරු, කිහිරි", "category": "plant" },
  { "word": "කුරවික", "meaning": "සූදුරු", "category": "plant" },
  { "word": "කුරවිල්ලක", "meaning": "කරවිල", "category": "plant" },
  { "word": "කුරවිලන", "meaning": "සින්නක්කාරම්", "category": "treatment" },
  { "word": "කුරවි", "meaning": "කරවිල", "category": "plant" },
  { "word": "කුරස", "meaning": "ගල්මද", "category": "treatment" },
  { "word": "කුරාට", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "කුරාණ", "meaning": "කලන් තුන", "category": "treatment" },
  { "word": "කුරාණා", "meaning": "අරළු", "category": "plant" },
  { "word": "කුරාණ්ත", "meaning": "කටුකරඬු", "category": "plant" },
  { "word": "කුරාමර්ථ", "meaning": "ඇටවමාරා", "category": "plant" },
  { "word": "කුරාල", "meaning": "මියුරු", "category": "treatment" },
  { "word": "කුරාලී", "meaning": "ලියනගලා", "category": "plant" },
  { "word": "කුරාස", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කුරකා", "meaning": "කොසඹ ගස", "category": "plant" },

  // --- පිටුව 123 ---
  { "word": "කුරකී", "meaning": "වෙල්ලන්ගිරිය", "category": "plant" },
  { "word": "කුරබග", "meaning": "අක්කරපට්ටා", "category": "plant" },
  { "word": "කුරභගන්ධනී", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කුරභිකා", "meaning": "මුගුණුවැන්න", "category": "plant" },
  { "word": "කුරභිනී", "meaning": "මුවන්ත, මුගුණුවැන්න", "category": "plant" },
  { "word": "කුරවු", "meaning": "කුරට, දෙමට ගස", "category": "plant" },
  { "word": "කුරණ්ඩ ගුවන් කාලෙයි කොම්බ්‍ර", "meaning": "මුදු වැල්", "category": "plant" },
  { "word": "කුරණ", "meaning": "කවුකරඹු, රන් වන් කටු කරඬු", "category": "plant" },
  { "word": "කුරණ්ටිකා", "meaning": "කෙළිඳ ගස, කිඹුල් වැන්න", "category": "plant" },
  { "word": "කුරණී", "meaning": "කුරැඳු ගස, කවුකරඹු", "category": "plant" },
  { "word": "කුරණ්ඩ", "meaning": "දමුනු, බොරළුදමුනු", "category": "plant" },
  { "word": "කුරණ්ඩක", "meaning": "රන්වන් කටුකරඬු, ගිරිනීල්ල", "category": "plant" },
  { "word": "කුරඹ", "meaning": "උග්‍රරස්ස", "category": "plant" },
  { "word": "කුරඹිකා", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "කුරබද්ධි", "meaning": "දෙව් අබ", "category": "plant" },
  { "word": "කුරව", "meaning": "රත් කටු කරඹු, රන් කරල් සැබෝ", "category": "plant" },
  { "word": "කුරවක", "meaning": "රත් ගිරිනීල්ල, කිරිඳි වැල්, කරල් සැබ, වෙල්නැල්, රත් කවුකරඹු, කෙළිඳ", "category": "plant" },
  { "word": "කුරස", "meaning": "වවවමාවි, ගොඩිච්චි (ඇත් අබි)", "category": "plant" },
  { "word": "කුරා", "meaning": "අස්බැවිල, ගරිරය", "category": "plant" },
  { "word": "කුරක්ෂක්", "meaning": "වල් කිරිඅඟුණ, සිහින් කිරිඅඟුණ", "category": "plant" },
  { "word": "කුරා", "meaning": "කටුවැල්බටු, බත්", "category": "plant" },
  { "word": "කුරකුන්තී", "meaning": "රන්කිරිගොකටු, පින් තලි", "category": "plant" },
  { "word": "කුරාවි", "meaning": "ගස", "category": "plant" },
  { "word": "කුරාට", "meaning": "කිඹුල්වැන්න", "category": "plant" },
  { "word": "කුරාටකා", "meaning": "සිහින් මැඩගු, (වෙලිප්පරිත්ති)", "category": "plant" },
  { "word": "කුරැණිට(ක)", "meaning": "රන්වන් ගිරිනීල්ල, රන්වන් කටුකරඹු, කෙළිඳ, හීඟපන් තණ", "category": "plant" },
  { "word": "කුරැණිටිකා", "meaning": "රන්වන් ගිරිනීල්ල, රන්වන් කටුකරඹු, කෙළිඳ, හීඟපන් තණ", "category": "plant" },
  { "word": "කුරැණිවී", "meaning": "සේපාලිකා, ගිරිනීල්ල", "category": "plant" },
  { "word": "කුරැණියක", "meaning": "කටුකරඹු, රන් වන් කටුකරඹු, කිරිදිවැල්", "category": "plant" },
  { "word": "කුරණ්කබක", "meaning": "මහ වැල්පෙනෙල", "category": "plant" },
  { "word": "කුරණ්ඩුක", "meaning": "කිරිදිවැල්, හීන් මැඩගු", "category": "plant" },
  { "word": "කුරණාග", "meaning": "කසාවන් ගිරිනීල්ල, කටුකරඹු", "category": "plant" },
  { "word": "කුරැඳු", "meaning": "කුරැඳු ගස (ළමය)", "category": "plant" },
  { "word": "කුරන්වි", "meaning": "කටුකරඹු", "category": "plant" },
  { "word": "කුරාන්තෙයි", "meaning": "පඹුටු ගස", "category": "plant" },
  { "word": "කුරන්තෝට්ටි", "meaning": "වැල්කසඹිලියා, රසකිඳ", "category": "plant" },
  { "word": "කුරනිකා", "meaning": "කිරිඳි", "category": "plant" },
  { "word": "කුරප්ප්‍ර", "meaning": "ඉරමුසු", "category": "plant" },
  { "word": "කුරාඹ", "meaning": "හින්නාරන් වෙසෙසක්", "category": "plant" },
  { "word": "කුරාඹා", "meaning": "ගැටතුඹ ගස", "category": "plant" },
  { "word": "කුරාම්බිකා", "meaning": "ගැටතුඹ ගස", "category": "plant" },
  { "word": "කුරැමිබි", "meaning": "කුරැඳු ගස", "category": "plant" },
  { "word": "කුරැම", "meaning": "කැස්බෑවා", "category": "treatment" },
  { "word": "කුරැවක", "meaning": "රතු කටුකරඬු, ගිරිනීල්ල", "category": "plant" },
  { "word": "කුරැවිවන්", "meaning": "හින්කබල", "category": "plant" },
  { "word": "කුරැවිවේසි", "meaning": "පිළිල (ඉටිකෙසෙල්)", "category": "plant" },
  { "word": "කුරැවින්ද", "meaning": "හිඟුල්, වම්මුතු, බැදි හාල්, කිරිඳි, සාදිලිංගම්, සාතාවාරිය", "category": "plant" },
  { "word": "කුරැවින්දක", "meaning": "වම්මුතු - වල් කොල්ලු", "category": "plant" },
  { "word": "කුරැවින්දපාෂාණ", "meaning": "පද්මරාග, (කුරැවින්දන්-කුරැඳු පහන)", "category": "treatment" },
  { "word": "කුරැවීරක", "meaning": "කුඹුක් ගස", "category": "plant" },
  { "word": "කුරාස", "meaning": "සුන්සහල් (පොඩි වූ සහල්)", "category": "treatment" },
  { "word": "කුල්", "meaning": "කලප", "category": "treatment" },
  { "word": "කුල්මාක", "meaning": "කාඩි ඇඹුල, ජටාමාංශ", "category": "treatment" },

  // --- පිටුව 124 ---
  { "word": "කුලක්ෂයා", "meaning": "වාත රෝග සඳහා දෙන ගුලියක්", "category": "treatment" },
  { "word": "කුලජ", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කුලටක", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "කුලපති", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කුලපාල", "meaning": "මුගුණුවැන්න", "category": "plant" },
  { "word": "කුලසමප්‍රතා", "meaning": "බලිද", "category": "plant" },
  { "word": "කුලීර", "meaning": "කකුළුවා, කටුවැල්බටු, දේවදාර", "category": "plant" },
  { "word": "කුලීරක", "meaning": "කුඩා කකුළුවා, කටුවැල්බටු", "category": "plant" },
  { "word": "කුලීරසති", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "කුලීර ශිර්ෂා", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "කුලීරශීර්ෂා", "meaning": "කකුළුසුනු", "category": "plant" },
  { "word": "කුලීරශිර්ෂිකා", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "කුලාල", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කුලාලසති", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කුලත්ථ", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කුලත්ථිකා", "meaning": "වල් කොල්ලු", "category": "plant" },
  { "word": "කුල්ල", "meaning": "කලප", "category": "treatment" },
  { "word": "කුලවා", "meaning": "ගොම", "category": "treatment" },
  { "word": "කුලු", "meaning": "එළුකිරි", "category": "treatment" },
  { "word": "කුලාලි", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කුවත", "meaning": "වතුර", "category": "treatment" },
  { "word": "කුවපප", "meaning": "දිය මානෙල්", "category": "plant" },
  { "word": "කුවල", "meaning": "මහ ඇසල, දිය මානෙල්, පෑණි කොමඩු", "category": "plant" },
  { "word": "කුවලක", "meaning": "ඇසල, කිරියල්", "category": "plant" },
  { "word": "කුවලයි", "meaning": "දිය මානෙල්", "category": "plant" },
  { "word": "කුවලයා", "meaning": "දිය මානෙල්", "category": "plant" },
  { "word": "කුවලයාපීඩ", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කුවර", "meaning": "කරඳ ගස, කසඹිලියා, කෙළිඳ", "category": "plant" }
];