// data_514_524.js - පිටු 514 සිට 516 දක්වා සියලුම වචන සහ විස්තර
const data_extra_514_524 = [

    // --- පිටුව 514 ---
    { "word": "හන්සපා", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "හන්සපාද", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "හන්සපේත", "meaning": "අබින්", "category": "plant" },
    { "word": "හනිල", "meaning": "වැටකෙයියා", "category": "plant" },
    { "word": "හනු", "meaning": "කහ, සක්නැබ", "category": "plant" },
    { "word": "හනුව", "meaning": "හක්ක", "category": "anatomy" },
    { "word": "හපු", "meaning": "සපු ගස", "category": "plant" },
    { "word": "හපුෂා", "meaning": "ගම්මිරිස් වැනි පෙනුමක් ඇති කළු පාටින් යුත් හපුෂා නම් වූ සුගන්ධ ද්‍රව්‍යය", "category": "plant" },
    { "word": "හපුසුරා", "meaning": "වෙල්මුඩ (මුඩමහණ)", "category": "plant" },
    { "word": "හබ", "meaning": "අබ", "category": "plant" },
    { "word": "හඹු", "meaning": "කැඳ", "category": "food" },
    { "word": "හම්පිල්ල", "meaning": "කම්පිල්ල (ක) = සම්පිලිත්ත, සම්පෙලිත්ත, (සම්පිල්ල - ඇකැම) අඬිල්ල ගණයට අයත් ලාදුරු කෘමි රෝග වලට ප්‍රත්‍යක්ෂ, මඳක් විරේක කාරක ගුණයෙන් යුත් ගසකි", "category": "plant" },
    { "word": "හම්පිලිත්ත", "meaning": "හම්පිල්ල", "category": "plant" },
    { "word": "හමුදව", "meaning": "අමු ගොම", "category": "animal" },
    { "word": "හයඃකර්ණී", "meaning": "මුරුත", "category": "plant" },
    { "word": "හයගන්ධ", "meaning": "අමුක්කරා, කාව ලුණු, අසමෝදගම්", "category": "plant" },
    { "word": "හයතාසිතී", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "හයපුච්ඡ", "meaning": "උඳුපියලි, මස්වැන්න", "category": "plant" },
    { "word": "හයපුච්ඡිකා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "හයප්‍රිය", "meaning": "අමුක්කරා, ඉඳි", "category": "plant" },
    { "word": "හයමාර / හයමාරක", "meaning": "අලරිය", "category": "plant" },
    { "word": "හයමාරණ", "meaning": "ඇසටු", "category": "plant" },
    { "word": "හයසිංහ", "meaning": "අලරිය", "category": "plant" },
    { "word": "හයා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "හයානන්ද", "meaning": "මුං", "category": "plant" },
    { "word": "හයාරි", "meaning": "කණේරු", "category": "plant" },
    { "word": "හයාසනා", "meaning": "කෙසෙල් ගස", "category": "plant" },
    { "word": "හම්", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "හරිනිෂී", "meaning": "අරළු, කංසා", "category": "plant" },
    { "word": "හරකල්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "හරතෙපස්", "meaning": "රසදිය", "category": "mineral" },
    { "word": "හරන්තහ", "meaning": "වනකසා (හරංකහ = අරණකසා)", "category": "plant" },
    { "word": "හරපුෂ්පා", "meaning": "වේලා ගස", "category": "plant" },
    { "word": "හරප්‍රිය", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "හර රත", "meaning": "රත්සඳුන්", "category": "plant" },
    { "word": "හර වල්ලභ", "meaning": "අත්තන", "category": "plant" },
    { "word": "හරවිජ", "meaning": "රසදිය", "category": "mineral" },
    { "word": "හරා", "meaning": "කන්සා", "category": "plant" },
    { "word": "හරි", "meaning": "පිනුවන් පැහැය, ගුගුල්, අගිල්, රත්රන්", "category": "plant" },
    { "word": "හරිණක්‍ෂිකා", "meaning": "කෙසර බැවිල", "category": "plant" },
    { "word": "හරිචන්දන", "meaning": "සුදුහඳුන්, ගෝසීසඳුන්, කොකුම්, කස්තුරි, රන්වන් සඳුන්", "category": "plant" },
    { "word": "හරිඩ කසා", "meaning": "අරළු", "category": "plant" },
    { "word": "හරිඩබයා", "meaning": "අරළු ගෙඩි", "category": "plant" },
    { "word": "හරිණී", "meaning": "රන්වන් බෝලිද්ද, වැල්මදට, ලියනඟලා", "category": "plant" },
    { "word": "හරිත්", "meaning": "මුං", "category": "plant" },
    { "word": "හරිත්ශාඛ", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "හරිත", "meaning": "රතණ, මිදි, මුද්දරප්පලම්, නිල් රතණ, මහ මුං, සිත් මුං, පලාවන් පාට", "category": "plant" },
    { "word": "හරිතකී", "meaning": "අරළු", "category": "plant" },
    { "word": "හරිතපුෂ්ප", "meaning": "බෙරු", "category": "plant" },
    { "word": "හරිණමඤ්ජරී", "meaning": "කේසර බැවිල", "category": "plant" },
    { "word": "හරිතශාක", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "හරිතාල / හරිතාලක", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "හරිතාලිකා", "meaning": "රතණ, හිරියල්", "category": "mineral" },
    { "word": "හරිභාග්ම", "meaning": "තුත්පත්", "category": "plant" },
    { "word": "හරිද්‍ර", "meaning": "වනුවැල්", "category": "plant" },
    { "word": "හරිද්‍රමෙහ", "meaning": "ප්‍රමේහ රෝගයක්", "category": "treatment" },

    // --- පිටුව 515 ---
    { "word": "හරිද්‍රව", "meaning": "නාමල්රේණු, හුණු", "category": "plant" },
    { "word": "හරිද්‍රා", "meaning": "කහ, වනුවැල්, දාරුහරිද්‍රා", "category": "plant" },
    { "word": "හරිද්‍රාන්‍ය", "meaning": "වනුවැල් = (බාන්වැල්, වෙනිවැල්)", "category": "plant" },
    { "word": "හරිද්‍රාදි ගණය", "meaning": "වියලි කසා, පුස්වැන්න (පෘෂ්ණිපර්ණී) දුරතිශා, වැල්මී, කෙළිඳ හාල්, යන මේ හරිද්‍රාදි ගණය ඉස් පැසවීම, ආම අතිසාර සමනය හා තනකිරි දොස් ශුද්ධ කිරීම ද කෙරේ.", "category": "compound" },
    { "word": "හරිද්‍රා (2)", "meaning": "වනුවැල්", "category": "plant" },
    { "word": "හරිත්මුද්දග", "meaning": "සරත් කල්හි පාසුන මුං ඇට", "category": "plant" },
    { "word": "හරි නාමන්", "meaning": "මුං", "category": "plant" },
    { "word": "හරිනෙත්‍ර", "meaning": "සුදු නෙළුම්", "category": "plant" },
    { "word": "හරිප්‍රිය", "meaning": "කිකිරිදිය, සඳුන්, සැවැන්න, කොළොම්, රන්වන් කිකිරිදිය, කණේරු, සක්, බටුවද, තලා", "category": "plant" },
    { "word": "හරිමඤ්ජරි", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "හරිමන්ථ", "meaning": "කින්හිරි ගස, හන", "category": "plant" },
    { "word": "හරිමන්ථක", "meaning": "කඩල", "category": "plant" },
    { "word": "හරිමන්ථජ", "meaning": "හන, කළු මුං", "category": "plant" },
    { "word": "හරිවල්ලභ", "meaning": "අත්තන", "category": "plant" },
    { "word": "හරිවාලුක", "meaning": "එන්සාල්, ගොකටු", "category": "plant" },
    { "word": "හරිවාස", "meaning": "පුලිල ගස", "category": "plant" },
    { "word": "හරිවෘක්‍ෂ", "meaning": "ඒලවාලුක", "category": "plant" },
    { "word": "හරිවාහ", "meaning": "කිකිරිදිය", "category": "plant" },
    { "word": "හරිවිජ", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "හරිශෘංගී", "meaning": "කළු නික", "category": "plant" },
    { "word": "හරිසඳන්", "meaning": "සුදු හඳුන්, ගෝසී සඳුන්", "category": "plant" },
    { "word": "හරී", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "හරීතකාදි ගණය", "meaning": "අරළු, බුලු, නෙල්ලි, යන හරීතකාදි ගණය, විෂම හුණ නසයි, දෘෂ්ටිය දෙයි. බඩගින්න, ප්‍රමේහය, කුෂ්ටය, පිත හා සෙම් රෝග ත් නසයි,", "category": "compound" },
    { "word": "හරීතකී", "meaning": "අරළු", "category": "plant" },
    { "word": "හරීතශොක", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "හාරතෙල්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "හරෙණව", "meaning": "හන", "category": "plant" },
    { "word": "හරෙණු", "meaning": "කොල්ලු, රහැනිය", "category": "plant" },
    { "word": "හරෙණුක", "meaning": "රහැනිය, වල්ගම්මිරිස්", "category": "plant" },
    { "word": "හරෙණුකා", "meaning": "වට රහැනිය", "category": "plant" },
    { "word": "හලක", "meaning": "රතු මානෙල්, (රතුහෙල්මැලි)", "category": "plant" },
    { "word": "හල", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "හලද", "meaning": "කසා", "category": "plant" },
    { "word": "හලධරප්‍රිය", "meaning": "බක්මී, කොළොම්", "category": "plant" },
    { "word": "හලා", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "හලාහල විෂ", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "හලී", "meaning": "සලල", "category": "plant" },
    { "word": "හලිද්දී", "meaning": "කහ", "category": "plant" },
    { "word": "හලිද්‍රැම", "meaning": "සල් ගස", "category": "plant" },
    { "word": "හලිනී", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "හලින", "meaning": "සල් ගස", "category": "plant" },
    { "word": "හලිප්‍රිය", "meaning": "බක්මී", "category": "plant" },
    { "word": "හල්", "meaning": "අල", "category": "plant" },
    { "word": "හල්ද", "meaning": "කහ අල", "category": "plant" },
    { "word": "හවරි පලා", "meaning": "එනම් වැල් විශේෂය = මේවායේ කොළ දිගටි ය, කුඩා ය, දලුව නිතරම ආපසු හැරී යයි. පැරණි වෙදවරු මෙය ආපසු මුදු යනුවෙන් ද හඳුන්වති.", "category": "plant" },
    { "word": "හවි", "meaning": "රත්නිටුල්, ගිතෙල්", "category": "plant" },
    { "word": "හවිමන්ත", "meaning": "කින්හිරි ගස, ගිතෙල්", "category": "plant" },
    { "word": "හවිඃස්‍රාවි", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "හසතක", "meaning": "එරබු ගස", "category": "plant" },
    { "word": "හසතපර්ණී", "meaning": "රත් එරබු", "category": "plant" },
    { "word": "හස්තපර්ණිකා", "meaning": "සක් නැබ", "category": "animal" },
    { "word": "හස්තපයෝධර", "meaning": "අත්තන", "category": "plant" },
    { "word": "හස්තාසුවල්ලභ", "meaning": "වල්ලි අල (වැල් අල)", "category": "plant" },
    { "word": "හස්තානතී", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "හස්තී", "meaning": "අත්තන", "category": "plant" },

    // --- පිටුව 516 ---
    { "word": "හස්තිකර්ණී", "meaning": "එරබු, රත් එරබු, හබරල", "category": "plant" },
    { "word": "හස්තිකර්ණී පලාස", "meaning": "ඇත්කැලිග", "category": "plant" },
    { "word": "හස්තිකර්ණී (2)", "meaning": "හබරල", "category": "plant" },
    { "word": "හස්තිකරඤ්ජ", "meaning": "මහකරඳ", "category": "plant" },
    { "word": "හස්තිකොලි", "meaning": "බෙබර", "category": "plant" },
    { "word": "හස්තිකොල", "meaning": "ගජතිප්පිලි", "category": "plant" },
    { "word": "හස්තිගන්ධ", "meaning": "වේලා ගස", "category": "plant" },
    { "word": "හස්තිදන්තා", "meaning": "නියඹරා, ඇත්දත්", "category": "plant" },
    { "word": "හස්තිදන්ත ඵලා", "meaning": "නියඹරා, කැකිරි", "category": "plant" },
    { "word": "හස්තිපර්ණී", "meaning": "සබරල (හබරල)", "category": "plant" },
    { "word": "හස්තිපර්ණිකා", "meaning": "සක්නැබ", "category": "animal" },
    { "word": "හස්තිපර්ණිකා (2)", "meaning": "මහ වැටකොළු", "category": "plant" },
    { "word": "හස්තිපර්ණී (2)", "meaning": "මුරුවා, මහ වැටකොළු", "category": "plant" },
    { "word": "හස්තිපිප්පලී", "meaning": "ගජ තිප්පිලි (ඇත් වගපුල්)", "category": "plant" },
    { "word": "හස්තිපුෂ්ප", "meaning": "නාමල් රේණු", "category": "plant" },
    { "word": "හස්තිමසුරැක", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "හස්තිමාගධ", "meaning": "ගජතිප්පිලි", "category": "plant" },
    { "word": "හස්තිරොහතක", "meaning": "මහ කරඳ", "category": "plant" },
    { "word": "හස්තිවාරුණී", "meaning": "මහ කරඳ", "category": "plant" },
    { "word": "හස්තිවිෂාණී", "meaning": "කෙසෙල් ගස", "category": "plant" },
    { "word": "හස්තිශුණ්ඩී", "meaning": "ඇත් සොඬක් මෙන් අග නැමී තිබෙන දණ්ඩක සුදුමල් හට ගන්නා කුඩා පැළෑටි වර්ගයක්. ඇත් සොඬ=(ඇත්සැටිය) 465 පිටේ ශ්‍රී හසතිනී ගණ ලියූ ඡායාරූප සහිත විස්තරය බලන්න.", "category": "plant" },
    { "word": "හස්තිශුණ්ඩා", "meaning": "ඇත්සොඬ", "category": "plant" },
    { "word": "හස්තී (2)", "meaning": "දත්ත, සිවිය, කෙසෙල්", "category": "plant" },
    { "word": "හසු", "meaning": "අස්වැන්න", "category": "plant" },
    { "word": "හාතක", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "හාතවාරා", "meaning": "සාතාවාරිය වැල", "category": "plant" },
    { "word": "හාතාවාරිය", "meaning": "සාතාවාරිය වැල", "category": "plant" },
    { "word": "හායක", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "හායතී", "meaning": "බූව ගස", "category": "plant" },
    { "word": "හායතීවාක්‍ෂ", "meaning": "රන්වන් සඳුන්", "category": "plant" },
    { "word": "හාර", "meaning": "අරටුව (හර)", "category": "plant" },
    { "word": "හාරදූරා", "meaning": "මුද්‍රික ඵල", "category": "plant" },
    { "word": "හාරිද්‍ර", "meaning": "වච්චනාභි, කොළොම් ගස, මිදිගස", "category": "plant" },
    { "word": "හාරිද්‍රක", "meaning": "කහ, වනුවැල්", "category": "plant" },
    { "word": "හාලා", "meaning": "සුරා", "category": "liquid" },
    { "word": "හාස", "meaning": "කුරුදු", "category": "plant" },
    { "word": "හාළි", "meaning": "ආහාරාදිය", "category": "general" },
    { "word": "හැඩකන්සා", "meaning": "කන්සා වර්ගයට ම අයත් ගසකි", "category": "plant" },
    { "word": "හැමරස පල", "meaning": "කෙල්ලි", "category": "plant" },
    { "word": "හැල්වීය", "meaning": "ඇල් වී", "category": "plant" },
    { "word": "හාල්සිදුහතු", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "හාලිදඹ", "meaning": "මහ දඹ", "category": "plant" },
    { "word": "හිංසා", "meaning": "කටුවෙලඟ", "category": "plant" },
    { "word": "හිංසි", "meaning": "කාමරංගා", "category": "plant" },
    { "word": "හිංඝු", "meaning": "ඔලිඳ, ජටාමාංශ, ගස්කැලිය", "category": "plant" },
    { "word": "හිංඝුකාරිකා", "meaning": "කටුවෙලඟ", "category": "plant" },
    { "word": "හිංගාදෘක්‍ෂ", "meaning": "අත්තන", "category": "plant" },
    { "word": "හිංගු", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "හිංගස", "meaning": "හික් ගස", "category": "plant" },
    { "word": "හිඟිනිය", "meaning": "එරමිණියා වැල්, ඉඟිනි", "category": "plant" },
    { "word": "හිඟු", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "හිඟුරා", "meaning": "ඉඟුරු, හිඟුරු වැල්", "category": "plant" },
    { "word": "හින්දුරුපට", "meaning": "හිඟුරු වැල් සුඹුලු (පට්ටා) මෙනි යුෂ සන්නි රෝග වලට හා සර්ප විෂට නස්‍ය කිරීමට ගනිති", "category": "plant" },



    // --- පිටුව 517 ---
    { 
        "word": "හිඟුල්", 
        "scientific": "Amoor Rohitaka",
        "meaning": "<b>Amoor Rohitaka- හිඟුල් — රෝහිතක</b><br><br>මෙය ගුරු පාට කඳක් හා බෙදී ගිය අතු පතර ඇති විශාල ගසකි. මේ ගස ලංකාවේ මාවනැල්ල - හිඟුල යන ප්‍රදේශවල ඝනව වැවී තිබේ. ඉන්දියාවේ බොහෝ පළාත් වල ද මේ ගස මනාව වැවෙයි. මෙහි කොළ ගල් මොර කොළ වැනි යි. ගෙඩි ලා රත් පැහැයෙන් යුක්ත ය. ඒවා මුදුප් පලම් වැනි අලංකාර ඵල ය. මේ ගෙඩි වල යුෂ යහපත් විරේචනීය ඖෂධයකි.<br><br>ප්ලීහා රෝග නාශක ඖෂධයක් නිසා මේ ගසට ප්ලීහ ඝඝා යන නාමය සංස්කෘත භාෂාවෙන් ව්‍යවහාර කෙරේ. ග්‍රන්ථි මහත් වීමට, අක්මාව මහත් වීමට හා බරවාරු ගතිය අඩු කිරීමට ත් හිඟුල් සාරය යොදති.<br><br>මේ ගසේ පොතු තද තිත්ත රසයෙන් යුක්ත ය. ඒවා මැලේරියා රෝගීන්ට ත් මැලේරියාව නිසා ප්ලීහාව මහත් වූ රෝගීන්ට ත් ප්‍රතිකාර සඳහා ගනිති.<br><br>විශේෂයෙන් හිඟුල් සාරය මැලේරියාවෙන් ඇලදිව මහත්වන අයට දිය හැකි ප්‍රත්‍යක්ෂ තම ඖෂධයකි.", 
        "category": "plant",
        "image": "img_amoor_rohitaka_hingul.jpg"
    },
    { "word": "හිඟුලං", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "හිඟුලලි", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "හිඟුළු", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "හිබුතු", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "හිබුතුතු", "meaning": "පෙරුම්කායම් ගසේ පතුරු වලින් ගන්නා ලාටු (පෙරන්කායම්)", "category": "plant" },
    { "word": "හිබුතුකං", "meaning": "පෙරුම්කායම් ගසේ කරටියෙන් ගන්නා ලාටු (පෙරන්කායම්)", "category": "plant" },
    { "word": "හිබුතුනිය්‍යාස", "meaning": "පෙරුම්කායම් ගසේ මැලියම් (ලාටු) (පෙරුම්කායම්)", "category": "plant" },
    { "word": "හිබුතුනිය්‍යාස මාලක", "meaning": "කොසඹ", "category": "plant" },
    { "word": "හිබඟුපත්‍රා", "meaning": "පත්‍රාහිංගු", "category": "plant" },
    { "word": "හිබඟු පත්‍රිකා", "meaning": "දිය බෙරලිය", "category": "plant" },
    { "word": "හිබඟුපත්‍රී", "meaning": "පත්‍රාහිංගු, දියබෙරලිය", "category": "plant" },
    { "word": "හිබඟුල", "meaning": "බටු ගස, සාදිලිංගම්, හිඟුල්", "category": "plant" },
    { "word": "හිබඟුලි", "meaning": "එළබටු ගස", "category": "plant" },
    { "word": "හිබඟුසිපාටිකා", "meaning": "පෙරුම්කායම් කොළ වලින් ගන්නා ලාටු (පෙරන්කායම්)", "category": "plant" },

    // --- පිටුව 518 ---
    { "word": "හිප්පල", "meaning": "දිය මිදෙල්ල", "category": "plant" },
    { "word": "හික්‍ෂීර", "meaning": "මුදුපෙණ", "category": "mineral" },
    { "word": "හිතුල්", "meaning": "කිතුල් ගස, හිඳිගස", "category": "plant" },
    { "word": "හිදමස්", "meaning": "හෘදයමාංශය", "category": "anatomy" },
    { "word": "හිද", "meaning": "හදවත", "category": "anatomy" },
    { "word": "හිදි", "meaning": "තණරුක්", "category": "plant" },
    { "word": "හින්තාල", "meaning": "කිතුල්ගස", "category": "plant" },
    { "word": "හින්සලු", "meaning": "සිංසපා, (ඇට්ටේරියා)සුදු සල් ගස", "category": "plant" },
    { "word": "හින්සා", "meaning": "සඳුන්", "category": "plant" },
    { "word": "හිප්පයා", "meaning": "දීකිරි", "category": "liquid" },
    { "word": "හිබට", "meaning": "බට ජාතියක්", "category": "plant" },
    { "word": "හිඹුරු", "meaning": "ගුරුන්ද, රුක්බූරුද, ඉඹුරු", "category": "plant" },
    { "word": "හිඹුල්", "meaning": "ඉඹුල්", "category": "plant" },
    { "word": "හිම", "meaning": "හීන්එන්සාල්, කපුරු, සඳුන්, විලඳ, ඉරිවේරිය, හරේනුක, කලාඳුරු, ඉඟුරු හෝ බෙහෙත් වර්ග කපා තලා තබා ඇල්දියෙහි රැයක් බහා පෙරා ගන්නා ජලය. (හිමකෂාය)", "category": "liquid" },
    { "word": "හිමක", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "හිමකර", "meaning": "කපුරු", "category": "plant" },
    { "word": "හිමජා", "meaning": "හිඟුරුපියලි, රත්කිරි ගොකටු, අරළු", "category": "plant" },
    { "word": "හිමතුන", "meaning": "සැවැන්න, සුදුහඳුන්, රත් හඳුන්", "category": "plant" },
    { "word": "හිමතුලසුණු", "meaning": "සුදුහඳුන් සුණු හෝ කපුරු", "category": "plant" },
    { "word": "හිමදුග්ධා", "meaning": "කිරිකවෙළු", "category": "plant" },
    { "word": "හිමද්‍රැම", "meaning": "කොසඹගස", "category": "plant" },
    { "word": "හිමපුෂ්ප", "meaning": "ඇසළ ගස", "category": "plant" },
    { "word": "හිමවාලුක", "meaning": "කපුරු", "category": "plant" },
    { "word": "හිමහාසක", "meaning": "කිතුල් ගස", "category": "plant" },
    { "word": "හිමා", "meaning": "සඳුන්, දෙඹ", "category": "plant" },
    { "word": "හිමාංශුනිභය", "meaning": "රිදී", "category": "mineral" },
    { "word": "හිමාංශු", "meaning": "කපුරු", "category": "plant" },
    { "word": "හිමාද්‍රිජ", "meaning": "රත්කිරිගොකටු", "category": "plant" },
    { "word": "හිමාබිජ", "meaning": "මහනෙල්", "category": "plant" },
    { "word": "හිමාබතී", "meaning": "පික්මලි", "category": "plant" },
    { "word": "හිමාභ්‍ර", "meaning": "කපුරු", "category": "plant" },
    { "word": "හිමාරාහි", "meaning": "වරාගස, රත්නිටුල්", "category": "plant" },
    { "word": "හිමාලය", "meaning": "එළකිහිරි, කටුකරෝහිණී, තලිස් පතුරු, පිටවක්කා", "category": "plant" },
    { "word": "හිමාවතී", "meaning": "රත්කිරිගොකටු", "category": "plant" },
    { "word": "හිමාවාලක", "meaning": "කපුරු", "category": "plant" },
    { "word": "හිමාශ්‍රයා", "meaning": "රන්වන් බුලත්", "category": "plant" },
    { "word": "හිමාසූකා", "meaning": "කෙම්පලා", "category": "plant" },
    { "word": "හිමාහ්වය", "meaning": "කපුරු", "category": "plant" },
    { "word": "හිමාහ්වා", "meaning": "රහැනිය, වල්ගම්මිරිස්", "category": "plant" },
    { "word": "හිමොත්තර", "meaning": "කිඹුල්වත් මුද්දරප්පලම්", "category": "plant" },
    { "word": "හිමෝද්භවා", "meaning": "හිඟුරුපියලි, රත්කිරි ගොකටු", "category": "plant" },
    { "word": "හිමොපල", "meaning": "කපුරු", "category": "plant" },
    { "word": "හිය", "meaning": "ඉයවැල්", "category": "plant" },
    { "word": "හිර", "meaning": "කෙම්පලා", "category": "plant" },
    { "word": "හිරඩු", "meaning": "ඉරටු", "category": "plant" },
    { "word": "හිරණ්‍ය", "meaning": "රත්රන්, අත්තන, රිදී", "category": "mineral" },
    { "word": "හිරණ්‍ය (2)", "meaning": "කවඩි", "category": "animal" },
    { "word": "හිරණ්‍යපුෂ්පී", "meaning": "බින්තල්", "category": "plant" },
    { "word": "හිරණ්‍යරෙතස්", "meaning": "රත් නිටුල්", "category": "plant" },
    { "word": "හිරවේරිය", "meaning": "හ්‍රීවේර= ලක්දිව හ්‍රීවේර වෙනුවට ගන්නේ ඉන් තල වලට සමාන කප්පර වල්ලී ගණයට අයත් පැළෑටියකි.", "category": "plant" },
    { "word": "හිරිකොළ", "meaning": "දුනුකේ සමාන කොළ ඇති එයට කුඩා ගසක්", "category": "plant" },
    { "word": "හිරිඛි", "meaning": "හිරියල්, රත්හිරියල්", "category": "mineral" },
    { "word": "හිරිඛෙරක", "meaning": "හ්‍රීවේර", "category": "plant" },
    { "word": "හිරියල්", "meaning": "සිරියල්", "category": "mineral" },
    { "word": "හිරිවේර", "meaning": "හ්‍රීවේර", "category": "plant" },
    { "word": "හිල්වළු", "meaning": "හීනවැළු", "category": "plant" },
    { "word": "හිලමොචිකා", "meaning": "නිකවැල්, මුහුණ වැන්න", "category": "plant" },

    // --- පිටුව 519 ---
    { "word": "හිළු", "meaning": "හීනවැළු", "category": "plant" },
    { "word": "හිස්බිජු", "meaning": "පුස්ඇට", "category": "plant" },
    { "word": "හිස්සා", "meaning": "වදකසා", "category": "plant" },
    { "word": "හිස්සාඃ", "meaning": "වදකහ අල", "category": "plant" },
    { "word": "හිසල්", "meaning": "හීන්සලු, හීන්එන්සාල්", "category": "plant" },
    { 
        "word": "හීන් තඹල", 
        "scientific": "Ehretia Buxifolia",
        "meaning": "<b>Ehretia Buxifolia-හීන් තඹල</b><br><br>තඹල ගණ විස්තරයක් 211 පිටේ ඇත. එයින් එක් වර්ගයක් වූ හීන් තඹල ගස අඩි අටක් පමණ උසට වැවේ. කටුපිල කොළ වලට ත් වඩා කුඩා කැටයම් (දැති) සහිත ඝණසැරේට තිබෙන මේ ගසේ කොළ හා ඉදුන විට ලා රෝස පැහැයෙන් යුත් බෝල කඩල ඇට පමණ ගෙඩි නිසා මෙය ගෙ මිදුල්වල අලංකාරය පිණිස ත්, ඖෂධ පිණිස ත් වවා ගත හැක.<br><br>මේ ගසේ කොළ වල හා මුල් වල සාරය බහු මූත්‍ර රෝගය (දියවැඩියාව) ට ප්‍රත්‍යක්‍ෂ ඖෂධයකි.", 
        "category": "plant",
        "image": "img_ehretia_buxifolia_hin_tambala.jpg"
    },
    { "word": "හීන්දරත්ත", "meaning": "කුඩා අරත්ත", "category": "plant" },
    { "word": "හීන්මඬහඟු", "meaning": "වේලිප්පරිත්ති", "category": "plant" },
    { "word": "හීති", "meaning": "සීනි", "category": "food" },
    { "word": "හීර", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "හීරක", "meaning": "විදුරු (දියමන්ති)", "category": "mineral" },
    { "word": "හීරී", "meaning": "ඇත්දෙමට, ලේ", "category": "plant" },
    { "word": "හීරැස්ස", "meaning": "සිරස්ස, (පළු) දික්තිබිය)", "category": "plant" },
    { "word": "හීවළු", "meaning": "හීනවළු ගස", "category": "plant" },
    { "word": "හීස්සා", "meaning": "වදකහ අල", "category": "plant" },
    { "word": "හුක්ගස්", "meaning": "උක්ගස", "category": "plant" },
    { "word": "හුණ", "meaning": "උණගස", "category": "plant" },
    { "word": "හුණකපුරු", "meaning": "උණකපුරු", "category": "plant" },
    { "word": "හුතාසනා / හුතාශ / හුතාශන", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "හුන්කිරි", "meaning": "මීකිරි, දෙනුන්කිරි", "category": "liquid" },
    { "word": "හුන", "meaning": "කලං තුනක්", "category": "general" },
    { "word": "හුනක්", "meaning": "කලං තුනක්", "category": "general" },
    { "word": "හුතකිමිල්බඩ", "meaning": "උණගොබඩු", "category": "plant" },
    { "word": "හුතග", "meaning": "නතරද", "category": "plant" },
    { "word": "හුතත්ග", "meaning": "නෝමයට අඬගහන දිවුල් ගස", "category": "plant" },
    { "word": "හුතමකුල්", "meaning": "වංගරෝචනා (උණකපුරු)", "category": "mineral" },
    { "word": "හුතපුපුලු", "meaning": "උණහපුළුවා", "category": "plant" },
    { "word": "හුනලු", "meaning": "හුලුකාන්, ලුණුකැඳ", "category": "food" },
    { "word": "හුනිද", "meaning": "ඔලිඳවැල්", "category": "plant" },

    // --- පිටුව 520 ---
    { "word": "හුඹස්දළු", "meaning": "හුඹස්වල මුදුන් කෑලි (බැඳගෙන එන හුඹස්)", "category": "mineral" },
    { "word": "හුරල", "meaning": "අල වර්ගයක්, බිමිතල්", "category": "plant" },
    { 
        "word": "හුලන්හික්", 
        "scientific": "Odina Wodior",
        "meaning": "<b>Odina Wodior-හුලන්හික් — ඔඩිනා</b><br><br>මෙය හැඩහුරුකමින් හික් කොළ වලට හා ප්‍රමාණයෙන් නාඉඹුල් කොළ වලට සමාන කොළ ඇති ඉතා උස් ව වැවෙන සුදු පැහැති කඳකින් යුත් විශාල ගසකි.<br><br>මේ ගසේ පොතු තැල්මට - ඉදිමුමට හා කැඩුම්-බිඳුම් වෙදකමේ ඖෂධ යෝග වලට ත් ගනිති.", 
        "category": "plant",
        "image": "img_odina_wodior_hulanhik.jpg"
    },
    { "word": "හුරිලු", "meaning": "ලේ, ලෙය", "category": "anatomy" },
    { "word": "හුරුහාල්", "meaning": "ඇල්වී වර්ගයක්", "category": "plant" },
    { "word": "හුල්", "meaning": "කඩ", "category": "general" },
    { "word": "හුළකාන්", "meaning": "ලුණුකැඳ", "category": "food" },
    { "word": "හෘද්‍ය", "meaning": "අසමෝද, දෙහි, කුරුඳුපොතු", "category": "plant" },
    { "word": "හෘද්‍යගන්ධ", "meaning": "හීන්දුරු, බෙලිගස", "category": "plant" },
    { "word": "හෘද්‍යගන්ධක", "meaning": "සුවසලුණු", "category": "mineral" },
    { "word": "හෘද්‍යගන්ධා", "meaning": "කොත්තමල්ලි, බෙලි", "category": "plant" },
    { "word": "හෘද්‍යා", "meaning": "මුලත්, සුදු දුරු", "category": "plant" },
    { "word": "හෘද්‍යගවේරීන", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "හාලුපාය", "meaning": "කටින් පණුදිය වැගීම", "category": "treatment" },
    { "word": "හෙටි", "meaning": "නටුව", "category": "plant" },
    { "word": "හෙතු", "meaning": "ඇඹුල්ඇඹිලිය", "category": "plant" },
    { "word": "හෙතදිරින්කා", "meaning": "ගස්-සඞ්ඛ්‍යාරාග (කාෂ්ණකෝලි)", "category": "plant" },
    { "word": "හෙප්පැත්", "meaning": "දිය නොබස්නා ජලාසයන්හි ජලය (හෙබදිය)", "category": "liquid" },
    { "word": "හෙමිදල", "meaning": "රණවරා ගස", "category": "plant" },
    { "word": "හෙම්බිරිය්‍ය", "meaning": "සෙම්ප්‍රතිශ්‍යාව", "category": "treatment" },
    { "word": "හෙම්වත", "meaning": "අරළු", "category": "plant" },
    { "word": "හෙම්වද / හේමවතී", "meaning": "(සුදු) වදකහ", "category": "plant" },
    { "word": "හේම", "meaning": "නාමල්රේණු, බින්කොසඹ, රත්රන්, අත්තන", "category": "plant" },
    { "word": "හේමක්‍ෂීරී", "meaning": "රත්ගොකටු, පික්මල්", "category": "plant" },
    { "word": "හේමකඳුල", "meaning": "පබලු", "category": "plant" },
    { "word": "හේමකාන්තා", "meaning": "දාරුහරිද්‍රා", "category": "plant" },
    { "word": "හේමකාන්තී", "meaning": "වෙනිවැල්, දාරුහරිද්‍රා", "category": "plant" },
    { "word": "හේමකිඤ්ජල්කා", "meaning": "නාමල්රේණු", "category": "plant" },
    { "word": "හේමකෙතකී", "meaning": "රන්වැටකේ", "category": "plant" },
    { "word": "හේමක්‍රාන්තා", "meaning": "දාරුහරිද්‍රා", "category": "plant" },
    { "word": "හේමතාර", "meaning": "තුත්පත්", "category": "plant" },
    { "word": "හේමන්තී", "meaning": "නාමල් රේණු, බින්කොසඹ", "category": "plant" },

    // --- පිටුව 521 ---
    { "word": "හේමදුග්ධ", "meaning": "දිවුල්", "category": "plant" },
    { "word": "හේමදුග්ධක", "meaning": "දිවුල්, පික්මලි", "category": "plant" },
    { "word": "හේමදුග්ධා", "meaning": "ගොකටු, පික්මලි", "category": "plant" },
    { "word": "හේමදුග්ධින්", "meaning": "දිවුල්", "category": "plant" },
    { "word": "හේමදුත්තුර", "meaning": "රන්වන් අත්තන", "category": "plant" },
    { "word": "හේමද්‍රැම", "meaning": "රණවරා", "category": "plant" },
    { "word": "හේමදිප් රණ", "meaning": "පික්මලි", "category": "plant" },
    { "word": "හේමන්", "meaning": "නාමල්රේණු", "category": "plant" },
    { "word": "හේමන්‍ය", "meaning": "රන්වන් අත්තන", "category": "plant" },
    { "word": "හේමන්තරැප්", "meaning": "ජුල්ගස (දිවුල්ගස)", "category": "plant" },
    { "word": "හේමනිධි", "meaning": "රසදිය", "category": "mineral" },
    { "word": "හේමපද්මක", "meaning": "මහපොණඩරු", "category": "plant" },
    { "word": "හේමපුෂ්ප", "meaning": "සපු, හෝපළු, නාමල් රේණු", "category": "plant" },
    { "word": "හේමපුෂ්පක", "meaning": "සපු", "category": "plant" },
    { "word": "හේමපුෂ්පිකා", "meaning": "බින්තල්, කසාවන් පියාගස", "category": "plant" },
    { "word": "හේමපුෂ්පී", "meaning": "රන්වන් බුලත්, වැල් මදට, කැකිරි, බින්තල්, කටු වැල්බටු, රන්වන් ඉද්ද", "category": "plant" },
    { "word": "හේමඵලා", "meaning": "රන්වන් කෙසෙල්", "category": "plant" },
    { "word": "හේමයුතිකා", "meaning": "රන්වන් බෝලිද්ද", "category": "plant" },
    { "word": "හේමරසා", "meaning": "පික්මලි", "category": "plant" },
    { "word": "හේමරාගිනී", "meaning": "කහ", "category": "plant" },
    { "word": "හේමලතා", "meaning": "රන්වන් බුලත්", "category": "plant" },
    { "word": "හේමවතී", "meaning": "සුදු වදකහ, අරළු", "category": "plant" },
    { "word": "හේමවා", "meaning": "රත්කිරි ගොකටු", "category": "plant" },
    { "word": "හේමසංහ", "meaning": "නාමල්රේණු", "category": "plant" },
    { "word": "හේමසංඥක", "meaning": "මහපොණඩරු", "category": "plant" },
    { "word": "හේමිකා", "meaning": "පික්මලි, රත්කිරි ගොකටු", "category": "plant" },
    { "word": "හේමහරිතකී", "meaning": "රන්වන් පැහැති අරළු, වනුවැල්", "category": "plant" },
    { "word": "හේමොන්මත්ත", "meaning": "රන්වන් අත්තන ගස", "category": "plant" },
    { "word": "හේරබදු", "meaning": "එරබදු", "category": "plant" },
    { "word": "හේරලි", "meaning": "පැසුන කොස්ගෙඩි", "category": "plant" },
    { "word": "හේලකිරි", "meaning": "එළකිරි", "category": "liquid" },
    { "word": "හේලමාලි", "meaning": "කල්හාර", "category": "plant" },
    { "word": "හේල අල", "meaning": "සුදුමුහු අල", "category": "plant" },
    { "word": "හේලඇඹුල", "meaning": "සුදුනෙළුම්", "category": "plant" },
    { "word": "හේලජීරක", "meaning": "සුදුලූහුනු අල", "category": "plant" },
    { "word": "හේලතිකා", "meaning": "සුදු පාට කඳ-කොළ හා මල් ඇති නික වර්ගය. (හෙළ නික-කළුනික-(ලා නිල්පැහැය ඇති) නික යයි නික වර්ග තුනක් තිබේ. එයින් සුලභ ලා නිල් පැහැය ඇති නික වර්ගය පමණකි).", "category": "plant" },
    { "word": "හේලසිරිවැඩිබැවිල", "meaning": "සුදු සිරිවැඩි බැවිල", "category": "plant" },
    { "word": "හේලි", "meaning": "වරාගස", "category": "plant" },
    { "word": "හේලිවජ", "meaning": "සුදු වදකහ", "category": "plant" },
    { "word": "හේසිතනු", "meaning": "සක්නැබ", "category": "animal" },
    { "word": "හේළ", "meaning": "ලෝලුගස", "category": "plant" },
    { "word": "හේළකලවැල්", "meaning": "සුදු කලවැල්", "category": "plant" },
    { "word": "හේළකිලි", "meaning": "කුෂ්ඨ රෝගයක්", "category": "treatment" },
    { "word": "හේළගිරිතිල්ල", "meaning": "සුදු ගිරිතිල්ල (සුදු මාබණ්ඩා)", "category": "plant" },
    { "word": "හේළාමුල්", "meaning": "සුදු මානෙල්", "category": "plant" },
    { "word": "හේම (2)", "meaning": "බිංකොසඹ", "category": "plant" },
    { "word": "හේමවතී (2)", "meaning": "අරළු, හෙළවද, පික්මලි, දාරුහරිද්‍රා, රත්කිරි ගොකටු", "category": "plant" },
    { "word": "හේමී", "meaning": "රත්කිරිගොකටු", "category": "plant" },
    { "word": "හේය්‍යගව්‍යඝ්‍රත", "meaning": "ඊයේ කිරි වලින් ගත් වෙඬරු", "category": "liquid" },
    { "word": "හේල මෝචිකා", "meaning": "නිතිවැළ (නිවිති වැල)", "category": "plant" },
    { "word": "හේවච", "meaning": "උගුරුස්ස", "category": "plant" },

    // --- පිටුව 522 & 523 ---
    { "word": "හේම (3)", "meaning": "රත්රත්, නාමල්රේණු", "category": "plant" },
    { "word": "හේමන්", "meaning": "උදුවප්-දුරුතු දෙමස", "category": "general" },
    { "word": "හේමද්‍රැම (2)", "meaning": "රණවරා", "category": "plant" },
    { "word": "හේමපුෂ්ප (2)", "meaning": "නාමල්රේණු", "category": "plant" },
    { 
        "word": "හොඩල", 
        "scientific": "Modecca Palmata",
        "meaning": "<b>Modecca Palmata-හොඩල</b><br><br>හොඩල වැල හුරැල්ල කොළ වැනි ඇඟිලි බෙදී තිබෙන කොළ හා පෙනෙල වැල්වල මෙන් ලක්‍ෂණ රත් ඇට ඇති විශාල වැලකි.<br><br>මේ වැලේ සැදෙන ගෙඩි ප්‍රමාණයෙන් ලොකු හිඹුටු හෝ පැෂන්ෆෘට් ගෙඩි පමණ ඇත. අමුගෙඩි නිල් පාටිනු ත් ඉදුණ ගෙඩි තද කහ පාටිනු ත් යුක්ත ය. ඉදුණවිට අධික ගොහාමත් ගතියක් දැක්වෙන නමුදු මාරාන්තික විෂ ද්‍රව්‍යයක් වූ මේ ගෙඩි හිඹුටු ගෙඩි යයි වරදවා කෑම නිසා අවුරුදු පතා බොහෝ දෙනෙකුගේ ජීවිත විනාශ වේ.<br><br>මෙය අල සහිත වැලකි. මේරු වැල්වල රාජ අල (ලොකු වැල් අල) පමණ විශාල අල බසියි.<br><br>චීන අල මේ රටට එන්නට මත්තෙන් උපදංශ (පරංගි) රෝගීන්ගේ වණ (තුවාල) වල පිට ගෑම සඳහා මේ හොඩල අල රැගෙන තිබෙන බව පැරණි බෙහෙත් වට්ටෝරුවලින් පෙනේ.", 
        "category": "plant",
        "image": "img_modecca_palmata_hodala.jpg"
    },
    { 
        "word": "හොඬපර", 
        "meaning": "<b>හොඬපර</b><br><br>හොඬපර - මහපර = (ගොඩපර-හොඩපර යයි පරවර්ග දෙකකි. එයින් ගොඩපර ගෙඩි ප්‍රමාණයෙන් කුඩා ය. තද ඇඹුලකින් හා සිසිල් ගුණයකින් යුක්ත ය. වැඩි වශයෙන් දිය නාන පොකුණු අසල ම වැවී තිබෙන ගොඩපර ගසේ ගෙඩි ඉස සිසිල් කරණ, ඉසේ කුණු හා උකුණන් පලවා කරණ පහසු ම ඉසකුඩිච්චිය යි.<br><br>නාන්නට සුදානම්වී අසල තිබෙන ගොඩපර ගහක් යටින් ඉඳී වැටී තිබෙන ගොඩපර ගෙඩි කීපයක් අවුලා රෙදි සෝදන ගල උඩ ම තබා තවත් ගලක් ගෙන තලා ඉසට දමා පැය කාලක් පමණ තිබෙන්නට හැර එයින් ඉස සෝදා නෑමිට ඉහත සඳහන් සම්පූර්ණ ගුණ ම ලබා ගත හැක.<br><br>හොඬපර කොළ කාලතුවක්කු උණ්ඩ ගසේ කොළ වලට සමාන ය. තොරස කොළවල මෙන් රළු බූවක් තිබේ මේ ගසේ තද සෙවෙල් ගතියකින් යුත් රාත්තල් අට දක්වා බර ගෙඩි සැදෙ යි. නො මේරු මේ (ලපටි=නැට) ගෙඩි ගෙන පෙති ගසා කහ-ලුණු-ගොරක දමා තම්බා දිය පෙරා හැර අනිකුත් කුළුබඩු හා පොල්කිරි දමා ඉස්ම හිඳෙන්ට උයා තෙම්පරාදු කර ගත් කල රසවත් ව්‍යංජනයකි.<br><br>මේරු ගෙඩිවල දියර අවුන්ස දෙක දක්වා වත්කල හැකි පතුරු ගැලවෙ යි. උත්සව අවස්ථාවන්හි ගොක්කොළ වලින් සෑදු පුහුල් පහන් දල්වූ කාලයෙහි ඒවා තුල මැටි පහන් වෙනුවට වැඩි වශයෙන් ම තබන්නේ පොල්තෙල් වත්කල මේ හොඬපර ලෙලි ය.<br><br>අඳුරු සහිත-ගං ඉවුරු-දිය පාර අසබඩ හා කුඹුරු අස්වනාත්වල වැවෙන මේ ගස යක් යාදිශාන්තික වෘක්‍ෂයක් ලෙස සලකන ඇතැම් යකැදුරෝ තොවිල්පොළ වල දී දුම්මල, පිදේනි, තටු ආදියෙහි පහන් දැල්වීම සඳහා හොඬපර ලෙලි ම ගනිති.", 
        "category": "plant" 
    },
    { "word": "හොබරවාලු", "meaning": "බාල වී වර්ගයක්, ඇඹුල් රසැති කෙසෙල් වර්ගයක්", "category": "plant" },
    { "word": "හොම්බාන්‍ය", "meaning": "තල", "category": "plant" },
    { "word": "හොමුගු", "meaning": "හෝපළු = (අශොක) දිය පරඬලා", "category": "plant" },
    { "word": "හොමුදමුහුණු", "meaning": "අශෝක ගස", "category": "plant" },
    { "word": "හොයදුන්", "meaning": "යාමින, නදූශ්‍රිත, ශ්‍රොතොඤ්ජන, ශෞවීර, කපොතාඤ්ජන - යන නම් වලින් හැඳින්වෙන කොබෙයි පැහැයෙන් යුත් මැටි වර්ගය (සෞවීර දේශයෙහි වූ යමුනා ගංඉවුරේ හිදී සොයාගත හැකි ද්‍රව්‍යයකි).", "category": "mineral" },
    { "word": "හොරණි", "meaning": "රත්තඹල, රත්මල්", "category": "plant" },
    { "word": "හොරණිමා(වා)ළු", "meaning": "හොබරවාලු", "category": "plant" },
    { "word": "හොරා", "meaning": "මීට නම් ජලජ පුෂ්ප විශේෂය", "category": "plant" },
    { "word": "හෝ", "meaning": "හෝපළු ගස", "category": "plant" },
    { "word": "හෝතලා", "meaning": "හෝ ගද ගසක තලා වර්ගය", "category": "plant" },
    { "word": "හෝදඹු", "meaning": "කරාබුනැටි", "category": "plant" },
    { "word": "හෝපළු", "meaning": "අශෝක ගස", "category": "plant" },
    { "word": "හෝපැන්", "meaning": "ඔය(ගංගා)වල ජලය", "category": "liquid" },
    { "word": "හෝමී", "meaning": "මිහී ගස", "category": "plant" },
    { "word": "හෝවැලතලා", "meaning": "හෝතලා", "category": "plant" },
    { "word": "හෝරණි", "meaning": "රත්මල් ගස", "category": "plant" },
    { "word": "හෞම", "meaning": "ගොරක", "category": "plant" },
    { "word": "හ්‍රස්වගවෙඩුකා", "meaning": "කොටිකන්බැවිල, සිරිවැඩිබැවිල", "category": "plant" },
    { "word": "හ්‍රස්වජම්බු", "meaning": "හීන්ජම්බු", "category": "plant" },
    { "word": "හ්‍රස්වපත්‍රකා", "meaning": "ඇසටු", "category": "plant" },
    { "word": "හ්‍රස්වපුෂ්ප", "meaning": "මීගස", "category": "plant" },
    { "word": "හ්‍රස්වඵලා", "meaning": "පිටවක්කා", "category": "plant" },

    // --- පිටුව 524 ---
    { "word": "හ්‍රස්වමූල", "meaning": "රතුඋක්ගස", "category": "plant" },
    { "word": "හ්‍රස්වවර්ණක", "meaning": "රත්එරබු", "category": "plant" },
    { "word": "හ්‍රස්වා", "meaning": "ගස්කැලිය, තිබ්බටු", "category": "plant" },
    { "word": "හ්‍රස්වාංග", "meaning": "ජීවක", "category": "plant" },
    { "word": "හ්‍රස්වාග්නි", "meaning": "වරාගස, රත්නිටුල්", "category": "plant" },
    { "word": "හ්‍රස්වාහ්ව", "meaning": "ජීවක", "category": "plant" },
    { 
        "word": "හ්‍රීබේර", 
        "meaning": "<b>හ්‍රීබේර</b><br><br>හ්‍රීවේර-හ්‍රීබේර පැළෑටිය (මෙය රතුපාට මල් සහ ගසේ සෑම තැනම සිහින් බූවක් ඇති, කස්තුරි වැනි මනා සුවඳකින් යුත් බැවිල ගණයට අයත් පැළෑටියකි.<br><br>මේ වෙනුවට පෙර සිට ලංකාවේ ගන්නේ දියසිරාව සහිත තැන්වල මැනවින් වැවෙන කප්පරවල්ලිය ගණයට අයත් ඉරිවේරිය නමැති පැළෑටිය යි.<br><br>මේ ඉරිවේරිය පැළෑටියෙහි ද ආම-අජීර්ණ-ජ්වර- ප්‍රතිශ්‍ය්‍යා ආදි රෝග නාශක ශක්තියක් තිබෙන බව ප්‍රකට කරුණකි.", 
        "category": "plant" 
    }
];

// සියලුම දත්ත කොටස් එකතු කර අවසාන master array එක සෑදීම
// (කලින් දුන් දත්ත ගොනු සියල්ල මෙහිදී එකතු වේ යැයි උපකල්පනය කෙරේ)



