// data_231_240.js - පිටු 231 සිට 240 දක්වා සියලුම වචන
const data_extra_231_240 = [
  // --- පිටුව 231 ---
  { "word": "තොයමඤ්ජරී", "meaning": "දියෙහි වැවෙන සැබෝ", "category": "plant" },
  { "word": "තොයමල", "meaning": "මුදුපෙණ", "category": "treatment" },
  { "word": "තොයමුචි", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "තොයවතී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තොයවර", "meaning": "කලාඳුරු", "category": "plant" },
  { "word": "තොයවල්ලරී", "meaning": "දියතිප්පිලි", "category": "plant" },
  { "word": "තොයවල්ලී", "meaning": "කරවිල, වැල් පෙනෙල, තොල්වැල්ල", "category": "plant" },
  { "word": "තොයවැල්", "meaning": "එනම් වැල් වගිය", "category": "plant" },
  { "word": "තොයවාසී", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "තොයශුක", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "තොයාරිවාසිනී", "meaning": "පලොල් ගස", "category": "plant" },
  { "word": "තොයාපමාගී", "meaning": "දිය සැබෝ", "category": "plant" },
  { "word": "තොයෝද්භවා", "meaning": "දිය සැබෝ", "category": "plant" },
  { "word": "තොල් පාලියාව", "meaning": "තොල් පෑලීම (රෝගයක්)", "category": "symptom" },
  {
    "word": "තොලබෝ (විෂමඬල)",
    "scientific": "Crinum Asiaticum",
    "meaning": "තොලබෝ අල ප්‍රධාන වශයෙන් ස්ථාවර-ජංගම විෂ නාශක ඖෂධයකි. මදය රත්කොට කසාය කර ගත් තොලබෝ කොළ යුෂ කන් කැක්කුමට පාවිච්චි කරන සාමාන්‍ය බෙහෙතකි. තොලබෝ අල යුෂ නිවැරදි ලෙස විරේකයක් බැව් ද සොයාගෙන තිබේ. හුරු කොළ වැනි කොළ ඇති කුඩා පුවක් ගසක් පමණ මහත රවුම් කඳකින් යුත් අඩි පහක් පමණ උසට වැවෙන ගොඩ මානෙල් පවුලට අයත් වුවකි. ගුප්ත විද්‍යාඥයෝ ඇස්වහ කටවහ පිළිබඳ ගුරුකම් කිරීමට ත් හදි හුනියම් කිරීම හා කැපීම ගැන ත් තොලබෝ අල වලින් නොයෙකුත් වගියේ කටයුතු කරති.",
    "category": "plant"
  },
  { "word": "තොල්ල", "meaning": "බුව", "category": "plant" },
  { "word": "තොල එල-බුව", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "තොල්ලුකර්ණී", "meaning": "ඉරවක්", "category": "plant" },
  { "word": "තොල්වැල්ල", "meaning": "වැල්පෙනෙල", "category": "plant" },

  // --- පිටුව 232 ---
  { "word": "තෝ", "meaning": "කෑදැත්තා", "category": "plant" },
  { "word": "තෝතැන්න", "meaning": "ජලතලාව", "category": "plant" },
  { "word": "තෝම", "meaning": "කුරුඳුපොතු", "category": "plant" },
  { "word": "තෝමාල", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "තෝර", "meaning": "පෙති තෝර, ඇත් තෝර, පැණිතෝර, උරතෝර, රට තෝර යයි තෝර වගී කීපයකි.", "category": "plant" },
  { "word": "තෝල්", "meaning": "පොතු", "category": "plant" },
  { "word": "තෝල්", "meaning": "ඔලිඳ ඇට 80 ක බර", "category": "treatment" },
  { "word": "තෝල්වැල්ල", "meaning": "වැල්පෙනෙල, කිරිල, රට බුලත්", "category": "plant" },
  { "word": "තෞතිල", "meaning": "මුතු", "category": "treatment" },
  { "word": "තෞදි", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "ත්‍රිපංචාදිගණය", "meaning": "සුදු රියම්, තඹ, යකඩ, කළු රියම්, රත්රන්, රිදී යන මේ ලෝහමල හාල් රෝග ගුල්ම, පාණ්ඩු, ප්‍රමේහ, විෂ යන මේ රෝග නසන්නේ ය.", "category": "treatment" },
  { "word": "ත්‍රිපංචාදි", "meaning": "රියම්, සුදු රියම්, තඹ, රිදී, යකඩ, රන්, ලෝහමල යන ධාතු සත", "category": "treatment" },
  { "word": "ත්‍රිපාග්‍ර", "meaning": "මිරිකුළු (මුරුංගා)", "category": "plant" },
  { "word": "ත්‍රිපු", "meaning": "කළු රියම්", "category": "treatment" },
  { "word": "ත්‍රිපුකන්‍දී", "meaning": "නියඹරා", "category": "plant" },
  { "word": "ත්‍රිපුටී", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ත්‍රපුල", "meaning": "සුදු රියම්", "category": "treatment" },
  { "word": "ත්‍රපුස්", "meaning": "සුදු රියම්, තියඹරා වැල", "category": "plant" },
  { "word": "ත්‍රපුස", "meaning": "කළු ත්‍රස්තවාල, නියඹරා, සුදු රියම්", "category": "plant" },
  { "word": "ත්‍රපුසතෙල", "meaning": "නියඹරා ඇට තෙල්", "category": "treatment" },
  { "word": "ත්‍රපුසා", "meaning": "නියඹරා, කළුත්‍රස්තවාල, මහ ගොන්කැකිරි", "category": "plant" },
  { "word": "ත්‍රපුසිනී", "meaning": "කැකිරි", "category": "plant" },
  { "word": "ත්‍රයසම", "meaning": "පොල්", "category": "plant" },
  { "word": "ත්‍රයස්ත්‍රික", "meaning": "ඉඟුරු, මිරිස්, තිප්පිලි, අරළු, බුළු, නෙල්ලි, ගොකටු", "category": "plant" },
  { "word": "ත්‍රයෝරජ", "meaning": "කාන්දම්", "category": "treatment" },
  { "word": "ත්‍රස්තාවාලු", "meaning": "සප්සඳ, නිරස්සවාල", "category": "plant" },
  { "word": "ත්‍රසාදනී", "meaning": "ගල්මද, ගල් සෙවෙල්", "category": "treatment" },
  { "word": "ත්‍රසායනී", "meaning": "ගල්මද", "category": "treatment" },
  { "word": "ත්‍රාව", "meaning": "කාම්මේරිය", "category": "plant" },
  { "word": "ත්‍රායක", "meaning": "නෙරි විෂ, වච්චනාවි", "category": "plant" },
  { "word": "ත්‍රායමාණිකා", "meaning": "ලුණුවිල", "category": "plant" },
  { "word": "ත්‍රායමාණා", "meaning": "ලුණුවිල, කවුඩු උඩැත්තා", "category": "plant" },
  { "word": "ත්‍රිති", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ත්‍රිසත්පත්‍ර", "meaning": "රත්මහනෙල්, සුදු මහනෙල්", "category": "plant" },
  { "word": "ත්‍රිසූර", "meaning": "ඉකිරි", "category": "plant" },
  { "word": "ත්‍රිසූරී", "meaning": "ගොකටු", "category": "plant" },
  { "word": "ත්‍රික", "meaning": "ඉඟුරු, ගම්මිරිස්, තිප්පිලි, යන තුන් වර්ගය හෝ අරළු, බුළු, නෙල්ලි යන තෙවග", "category": "plant" },
  { "word": "ත්‍රිකටුත්‍රික", "meaning": "එන්සාල්, කුරුඳු, කොල්ලම්කොළ, කරාබු, වසාවාසි, සාදික්කා, අරළු, බුළු, නෙල්ලි, ඉඟුරු, ගම්මිරිස්, තිප්පිලි", "category": "plant" },
  { "word": "ත්‍රිකටු", "meaning": "ගොකටු (නෙරෙවි) කටු පෙනෙල", "category": "plant" },
  { "word": "ත්‍රිකටුක", "meaning": "නිකුළු, (ඉඟුරු, මිරිස්, තිප්පිලි)", "category": "plant" },
  { "word": "ත්‍රිකණ්ට", "meaning": "ගොකටු, කටුවැල්බටු, යවාස, යන තෙවග හෝ බටු, සිහින්මිදි, වැල්කසඹිලියා යන තෙවගය හෝ කවුඩුකැකිරි, ගොකටු, දුරලභා යන තෙවගය හෝ සිද්ධිගුරු, කටුපෙනෙල, කටුවැල්බටු යන තෙවගය", "category": "plant" },
  { "word": "ත්‍රිකණ්ටක", "meaning": "ත්‍රස්තවාල, ගොකටු", "category": "plant" },
  { "word": "ත්‍රිකණ්ටාබ්‍ය", "meaning": "කටු පෙනෙල", "category": "plant" },
  { "word": "ත්‍රිකතුය", "meaning": "සම වූ තිපල්, නිකුළු, හිඟු යන නව වර්ගය", "category": "plant" },
  { "word": "ත්‍රිකතිකා", "meaning": "නිකුළු, තිපල්, නිවග", "category": "plant" },

  // --- පිටුව 233 ---
  { "word": "ත්‍රිකයුග", "meaning": "ත්‍රික ද්වය (ත්‍රිපල, තිකුළු දෙක)", "category": "treatment" },
  { "word": "ත්‍රිකාර්ෂික", "meaning": "සිද්ධිඟුරු, අතිවිඩයන්, කලාඳුරු", "category": "plant" },
  { "word": "ත්‍රිකූට", "meaning": "කකුළු සුණු", "category": "treatment" },
  { "word": "ත්‍රිකූට ලවණ", "meaning": "මුහුදු ලුණු", "category": "treatment" },
  { "word": "ත්‍රිකූටාභව", "meaning": "කළු ලුණු", "category": "treatment" },
  { "word": "ත්‍රිකෝණ", "meaning": "කටු පෙනෙල, නිරමුල්ලිය", "category": "plant" },
  { "word": "ත්‍රිකෝණඵල", "meaning": "නිරමුල්ලිය, කටුපෙනෙල", "category": "plant" },
  { "word": "ත්‍රිකෝණා", "meaning": "කටු පෙනෙල", "category": "plant" },
  { "word": "ත්‍රිග", "meaning": "නියඹරා", "category": "plant" },
  { "word": "ත්‍රිගන්ධ", "meaning": "එන්සාල්, කුරුඳු පොතු, කොල්ලම් කොළ යන තුන් වර්ගය", "category": "plant" },
  { "word": "ත්‍රියුග්මී", "meaning": "බෙලි ගස", "category": "plant" },
  { "word": "ත්‍රියුගා", "meaning": "අස්වැන්න", "category": "plant" },
  { "word": "ත්‍රිප්", "meaning": "තුන් දොසින් වූ ලෙඩ", "category": "symptom" },
  { "word": "ත්‍රිපටා", "meaning": "කේලි ගස", "category": "plant" },
  { "word": "ත්‍රිපත්ත", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ත්‍රිපතා", "meaning": "එන්සාල්, කුරුඳු, කොල්ලම් කොළ", "category": "plant" },
  { "word": "ත්‍රිපතක", "meaning": "කොල්ලම් කොළ", "category": "plant" },
  { "word": "ත්‍රිදල", "meaning": "බෙලි ගස", "category": "plant" },
  { "word": "ත්‍රිදලා", "meaning": "වලාවැන්න, වැල්මී, රතු නිදිකුම්බා", "category": "plant" },
  { "word": "ත්‍රිදලිකා", "meaning": "හිඟුරුවැල", "category": "plant" },
  { "word": "ත්‍රිදිවේන්ද්‍ර", "meaning": "දේවදාර, බෙලි ගස", "category": "plant" },
  { "word": "ත්‍රිදශේෂට", "meaning": "තලා ගස", "category": "plant" },
  { "word": "ත්‍රින සහ", "meaning": "දේවඅඹ ගස", "category": "plant" },
  { "word": "ත්‍රිනක", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ත්‍රිදීප", "meaning": "කහ, බොඹු", "category": "plant" },
  { "word": "ත්‍රිදිවා", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ත්‍රිදේවෝද්භවා", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ත්‍රිදොෂ", "meaning": "අසමෝදගම් තුන් වර්ගය", "category": "plant" },
  { "word": "ත්‍රිධාර", "meaning": "දවක් ගස", "category": "plant" },
  { "word": "ත්‍රිධාරිකා", "meaning": "නබවල්ලී, හාවිල වෙසෙසක්", "category": "plant" },
  { "word": "ත්‍රින්ත්‍රිකා", "meaning": "සියඹලා", "category": "plant" },
  { "word": "ත්‍රින්තෘණී", "meaning": "සියඹලා", "category": "plant" },
  { "word": "ත්‍රිසර්පපත්‍ර", "meaning": "රත් මහනෙල්", "category": "plant" },
  { "word": "ත්‍රින", "meaning": "හල්ගස", "category": "plant" },
  { "word": "ත්‍රිනරාජයා", "meaning": "පුවක්", "category": "plant" },
  { "word": "ත්‍රිනාද්‍ර", "meaning": "ඉඟි", "category": "plant" },
  { "word": "ත්‍රිතෙහ", "meaning": "පොල්, රසදිය, උරල", "category": "plant" },
  { "word": "ත්‍රිප්ත", "meaning": "බදුල්ල", "category": "plant" },
  { "word": "ත්‍රිපට", "meaning": "කළුලුණු, බල්පසුණු, බටලුණු යන තුන්", "category": "treatment" },
  { "word": "ත්‍රිපතු", "meaning": "බෙලි", "category": "plant" },
  { "word": "ත්‍රිපතුක", "meaning": "එරබදු, රත්කාල", "category": "plant" },
  { "word": "ත්‍රිපතා", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ත්‍රිපද", "meaning": "වලාවැන්න, රතු නිදිකුම්බා", "category": "plant" },
  { "word": "ත්‍රිපදී", "meaning": "වලාවැන්න", "category": "plant" },
  { "word": "ත්‍රිපර්ණී", "meaning": "ප්‍රශ්නිපර්ණී, ශාලිපර්ණී, කාලගස", "category": "plant" },
  { "word": "ත්‍රීපර්ණ", "meaning": "වල්කපුගස, පුස්වැන්න, වල්කංසා, ශාලිපර්ණී", "category": "plant" },
  { "word": "ත්‍රිපර්ණී", "meaning": "අස්වැන්න, ශාලිපර්ණී, ඇත්දෙමට, රත් සඳුන්, මස් බැද්ද, මස්වැන්න", "category": "plant" },
  { "word": "ත්‍රිපර්ණිකා", "meaning": "දුරලභා, වැල්කසඹිලියා", "category": "plant" },
  { "word": "ත්‍රිපාද", "meaning": "වලාවැන්න, රතු නිදිකුම්බා", "category": "plant" },
  { "word": "ත්‍රිපාදී", "meaning": "වලාවැන්න, රතු නිදිකුම්බා", "category": "plant" },
  { "word": "ත්‍රිපාලිකා", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "ත්‍රිපුට", "meaning": "තකුල්, ගොකටු, සිහින් එන්සාල්, එරබදු, ත්‍රස්තවාල, සිහින් මූ", "category": "plant" },
  { "word": "ත්‍රිපුටභා", "meaning": "සුදු ත්‍රස්තවාල", "category": "plant" },
  { "word": "ත්‍රිපුටා", "meaning": "එන්සාල්, මහ එන්සාල්, සිහින් එන්සාල්, මූ, කොල්ලු", "category": "plant" },
  { "word": "ත්‍රිපුට්ඨි", "meaning": "හෙළ එරබු", "category": "plant" },
  { "word": "ත්‍රිපුටිත්", "meaning": "එරබු ගස", "category": "plant" },
  { "word": "ත්‍රිපුටිඵල", "meaning": "එරබු ගස", "category": "plant" },
  { "word": "ත්‍රිපුලී", "meaning": "ත්‍රස්තවාලූ", "category": "plant" },
  { "word": "ත්‍රිපුරමල්ලිකා", "meaning": "ඉද්ද වෙසෙසක්", "category": "plant" },

  // --- පිටුව 234 ---
  { "word": "ත්‍රිපුස්", "meaning": "නියඹරා, මහගොන්කැකිරි, සිහින් මූ", "category": "plant" },
  { "word": "ත්‍රිපුෂ්පා", "meaning": "මහ බැබිල", "category": "plant" },
  { "word": "ත්‍රිපුස", "meaning": "නියඹරා, මහ කැකිරි", "category": "plant" },
  { "word": "ත්‍රිපුසා", "meaning": "නියඹරා, මහකැකිරි, කළු ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ත්‍රිපුසී", "meaning": "පෙනෙල ගස", "category": "plant" },
  { "word": "ත්‍රිපල", "meaning": "අරළු, බුළු, නෙල්ලි, යන ත්‍රිවර්ගය", "category": "plant" },
  { "word": "ත්‍රිපලා", "meaning": "අරළු, බුළු, නෙල්ලි යන තෙවර්ගය", "category": "plant" },
  { "word": "ත්‍රිඵලිකා", "meaning": "අරළු, බුළු, නෙල්ලි යන තෙවර්ගය", "category": "plant" },
  { "word": "ත්‍රිබධී", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ත්‍රිබලා", "meaning": "සුළුවැබිල, මහබැබිල, සිරිවැඩිබැබිල යන තෙවගය", "category": "plant" },
  { "word": "ත්‍රිබධිය", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "ත්‍රිභීර", "meaning": "එරබු, නල්ගස, වෙඬහමු", "category": "plant" },
  { "word": "ත්‍රිභඬි", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ත්‍රිභණ්ඩි", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ත්‍රෛමද", "meaning": "වම්මුතු, තිවුල්, වලඟසාල් යන තුන", "category": "plant" },
  { "word": "ත්‍රිමධු", "meaning": "සීනි, මීපැණි, ගිතෙල් යන තුන", "category": "treatment" },
  { "word": "ත්‍රියන්ති", "meaning": "බැමිනිරිය", "category": "plant" },
  { "word": "ත්‍රියව", "meaning": "හුනිද ඇටය", "category": "plant" },
  { "word": "ත්‍රියෂ්ටි", "meaning": "පැපිලිය", "category": "plant" },
  { "word": "ත්‍රියසාවක", "meaning": "බේරු, ත්‍රස්තවාල", "category": "plant" },
  { "word": "ත්‍රීරේඛා", "meaning": "ශක්ගෙඩිය", "category": "plant" },
  { "word": "ත්‍රිලවණ", "meaning": "සමීද, සුවස, බලල් යන තුන", "category": "treatment" },
  { "word": "ත්‍රිලිප", "meaning": "බෝලිද්ද", "category": "plant" },
  { "word": "ත්‍රිලොහක", "meaning": "රත්, රිදී, තඹ", "category": "treatment" },
  { "word": "ත්‍රිවග", "meaning": "අරළු, බුළු, නෙල්ලි, හෝ ඉඟුරු, ගම්මිරිස්, තිප්පිලි, නැත හොත් කරාබු, සාදික්කා, වසාවාසි", "category": "plant" },
  { "word": "ත්‍රීවගක", "meaning": "අරළු, බුළු, නෙල්ලි හෝ ඉඟුරු, ගම්මිරිස්, තිප්පිලි", "category": "plant" },
  { "word": "ත්‍රිවර්ණා", "meaning": "වල්කපු", "category": "plant" },
  { "word": "ත්‍රිවල්ලි", "meaning": "වැල්මදට, ගොන්කැකිරි", "category": "plant" },
  { "word": "ත්‍රිවල්ලිකා", "meaning": "පත්තක්කා ගෙඩිය", "category": "plant" },
  { "word": "ත්‍රිවිෂ", "meaning": "රතුඑරබු", "category": "plant" },
  { "word": "ත්‍රිවිෂප", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ත්‍රිවීශයී", "meaning": "රත්එරබු", "category": "plant" },
  { "word": "ත්‍රිවෘත", "meaning": "හෝපලු ගස", "category": "plant" },
  { "word": "ත්‍රිවිධ ශීතල පාක", "meaning": "මෘදු පාක, සම පාක, ඛර පාක", "category": "treatment" },
  { "word": "ත්‍රිවිධ ලවණ", "meaning": "ගල් ලුණු, ලේවාලුණු, සිඳු ලුණු", "category": "treatment" },
  { "word": "ත්‍රිවිජ", "meaning": "තලගස, බොධිඹු(බදුල්ල)", "category": "plant" },
  { "word": "ත්‍රිවාන්", "meaning": "කළු ත්‍රස්තවාල", "category": "plant" },
  { "word": "ත්‍රිවෘන්තිකා", "meaning": "කළු ත්‍රස්තවාල", "category": "plant" },
  { "word": "ත්‍රිවෘත්තලස්තකා", "meaning": "වැල්පෙනෙල", "category": "plant" },
  { "word": "ත්‍රිවෘතින්කා", "meaning": "කළු ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ත්‍රිවෘත්තපත්‍රා", "meaning": "ගිරිනිල්ල (මාබණ්ඩා), බටුල්ල, පණවෙදය", "category": "plant" },
  { "word": "ත්‍රිවෘත", "meaning": "කාල, එරබදු, ත්‍රස්තවාල", "category": "plant" },
  { "word": "ත්‍රිවාතා", "meaning": "අරළු, ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ත්‍රිවාන්ත්‍රා", "meaning": "කාලගස", "category": "plant" },
  { "word": "ත්‍රිවෙලා", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ත්‍රිශත පත්‍ර", "meaning": "හෙල පියුම්, කුමුදු", "category": "plant" },
  { "word": "ත්‍රිශාඛ පත්‍ර", "meaning": "බෙලිගස", "category": "plant" },
  { "word": "ත්‍රිශාල පත්‍ර", "meaning": "බෙලිගස", "category": "plant" },
  { "word": "ත්‍රිගා", "meaning": "කබලි", "category": "plant" },
  { "word": "ත්‍රිගිරස්", "meaning": "උණරෝගය", "category": "symptom" },
  { "word": "ත්‍රිගිටා", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "ත්‍රිගිණිකා", "meaning": "කිඩාරම්, රසදිය", "category": "treatment" },
  { "word": "ත්‍රිගුල", "meaning": "රසදිය", "category": "treatment" },
  { "word": "ත්‍රීසන්ධිකා", "meaning": "මල් ගස", "category": "plant" },
  { "word": "ත්‍රීසන්ධ්‍යාපුසුමි", "meaning": "නෙවිරික්කා මල් ගස", "category": "plant" },
  { "word": "ත්‍රීසන්ධ්‍යාකුසුම", "meaning": "නෙවිරික්කා මල් ගස", "category": "plant" },
  { "word": "ත්‍රීසන්ධ්‍යා", "meaning": "වද, නෙවිරික්කා මල් ගස", "category": "plant" },
  { "word": "ත්‍රිසම", "meaning": "අරළු, ඉඟුරු, උක්සකුරු", "category": "treatment" },
  { "word": "ත්‍රිසාක පත්‍ර", "meaning": "බෙලි", "category": "plant" },
  { "word": "ත්‍රිසායත", "meaning": "ගල්මද, ගල්සෙවෙල්", "category": "treatment" },
  { "word": "ත්‍රිසුගන්ධි", "meaning": "එන්සාල්, කුරුඳුපොතු, කොල්ලම්කොළ", "category": "plant" },
  { "word": "ත්‍රිසෞගන්ධ", "meaning": "ත්‍රිසුගන්ධ", "category": "plant" },
  { "word": "ත්‍රිශිම", "meaning": "වතුවැල්, සුදුහඳුන්, රත්හඳුන්", "category": "plant" },

  // --- පිටුව 235 ---
  { "word": "ත්‍රිපි", "meaning": "සිහින් එන්සාල්, කරබෙයිය ගස, (කරපිංචා ගස)", "category": "plant" },
  { "word": "ත්‍රිපිදලිය", "meaning": "සිහින් එන්සාල්, මහළු සාල් දෙක", "category": "plant" },
  { "word": "ත්‍රිපෙලි", "meaning": "තුන් සහ, (පලම් 1?)", "category": "treatment" },
  { "word": "ත්‍රිපෙෂ", "meaning": "කම් තුන", "category": "treatment" },
  { "word": "ත්‍රිසසාමි", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "ත්‍රිමිබකත්ව", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "ත්‍රීසුපුළු", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "ත්‍රිද්‍ර", "meaning": "සුදු හුස්නවාල, ඉද්ද වෙසෙසක්", "category": "plant" },
  { "word": "ත්‍රිපූෂණ", "meaning": "ඉඟුරු, ගම්මිරිස්, නිප්පිලි යන තුන", "category": "treatment" },
  { "word": "ත්‍රෛසකසුද", "meaning": "අඳුන් වෙසෙසක්", "category": "treatment" },
  { "word": "ත්‍රෛකටුක", "meaning": "තියුල්", "category": "plant" },
  { "word": "ත්‍රෛපල", "meaning": "තිපල්", "category": "plant" },
  { "word": "ත්‍රෛඵල", "meaning": "සාසවා", "category": "symptom" },
  { "word": "තින්", "meaning": "කුරුඳුපොතු", "category": "plant" },
  { "word": "තින්කබ", "meaning": "වල්කිඹාරම්", "category": "plant" },
  { "word": "තින්ගණ", "meaning": "දෙබම්, නාරම්", "category": "plant" },
  { "word": "තින්දෙශ", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "තින්දෙශපානා", "meaning": "බෝදිඇට", "category": "plant" },
  { "word": "තින්පස ද්‍රව්‍ය", "meaning": "නුග, අට්ටික්කා, බෝ, ඇසතු, පුලිල යන පොතු පස", "category": "plant" },
  { "word": "තින්පප්‍ර", "meaning": "පහණිඟු, කුරුඳුපොතු, පෙරුම්කායම් ගස", "category": "plant" },
  { "word": "තින්පත්‍රී", "meaning": "පෙරුම්කායම්, කලුදුරු, කොල්ලම්, නිඟුපත් තණ", "category": "plant" },
  { "word": "තින්සශීර", "meaning": "හුණමකුළු, (හුණකපුරු=තුක්පිචු)", "category": "plant" },
  { "word": "තින්සාදිවි", "meaning": "කුරුඳුපොතු", "category": "plant" },
  { "word": "තින්සාර", "meaning": "පුනගස, කුරුඳුගස, උණකපුරු", "category": "plant" },
  { "word": "තින්සුගන්ධ", "meaning": "නාරංගස, එල්වළු, (එල්වළුක=අඩඇට)", "category": "plant" },
  { "word": "තින්සුගන්ධිකා", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "තින්දෙශ", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "තින්දෙශපානා", "meaning": "බෝදිඇට", "category": "plant" },
  { "word": "තින්ගාගීර", "meaning": "උණකපුරු, (තුඹුඟා සකිරි)", "category": "plant" },
  { "word": "තොව", "meaning": "කුරුඳු, තලිස් ආදි පොතු වර්ග", "category": "plant" },
  { "word": "තොවස්නිර", "meaning": "උණගස", "category": "plant" },
  { "word": "තොව", "meaning": "කුරුඳු, තලකෙල, රක් පදුර", "category": "plant" },
  { "word": "තොවපල", "meaning": "රණවරා", "category": "plant" },
  { "word": "තොවාඬා", "meaning": "නාරංගස", "category": "plant" },
  { "word": "තොවාපත", "meaning": "පෙරුම්කායම්, කුරුඳු පොතු", "category": "plant" },
  { "word": "තොවිල්ජුනා", "meaning": "ගතපුෂ්ප", "category": "plant" },
  { "word": "තොමිසා", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "තොවිසාර", "meaning": "පුනගස", "category": "plant" },
  { "word": "තින්වුණේම්", "meaning": "ගන්දසූරිය", "category": "plant" },
  { "word": "තොවිසුගන්ධිකා", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "තොගාබකා", "meaning": "කුරුඳු පොතු", "category": "plant" },
  { "word": "තොව", "meaning": "කුරුඳුතෙල්", "category": "treatment" },
  { "word": "තින්ති", "meaning": "හොම්බුකොළ", "category": "plant" },
  { "word": "තොව්‍යාම පනී / තොව්‍යාමග", "meaning": "වරාගස", "category": "plant" },
  { "word": "තෛපස්", "meaning": "පාංශුලුණු", "category": "treatment" },
  { "word": "තජස", "meaning": "හිරි", "category": "plant" },
  { "word": "තවක", "meaning": "මල් කණ්", "category": "plant" },
  { "word": "තස", "meaning": "දහවියා, කාඩි", "category": "treatment" },
  { "word": "තසෝදක", "meaning": "කාඩි", "category": "treatment" },
  { "word": "තවෙකෙයක", "meaning": "ග්‍රන්ථිපර්ණී වාක්‍ෂය", "category": "plant" },

  // --- පිටුව 236 ---
  { "word": "දංශමූල", "meaning": "මුරුංගා ගස", "category": "plant" },
  { "word": "දංෂ්ට්‍රා", "meaning": "සප්දංෂ්ට්‍රා, තෙරෙංචි (ගොකටු)", "category": "plant" },
  { "word": "දක්කාටියා", "meaning": "(දන්තකාටියා) සර්පගන්ධි", "category": "plant" },
  { "word": "දක්පල", "meaning": "දක්පල, (දික්පල) ඇසල කරල් හෝ ගස", "category": "plant" },
  { "word": "දක්‍ෂ", "meaning": "ශිව වාසය", "category": "treatment" },
  { "word": "දක්‍ෂිණ දේශජා", "meaning": "ලතාකස්තුරි", "category": "plant" },
  { "word": "දක්‍ෂිණා වාහන", "meaning": "වතුසුද්ද, මස්බැද්ද, මෙබනගු", "category": "plant" },
  { "word": "දක", "meaning": "(උදක) වතුර", "category": "treatment" },
  { "word": "දකජ", "meaning": "යවකාර ලුණු, (යවක්‍ෂාර) යවගර ලුණු=යවකර ලුණු", "category": "treatment" },
  { "word": "දකසිතලිකා", "meaning": "හෙළඹල", "category": "plant" },
  { "word": "දකුණුපූට", "meaning": "දකුණු නාසාපුටය (දකුණු නැහැ සිදුරු)", "category": "treatment" },
  { "word": "දකොදර", "meaning": "උදර රෝගයක්", "category": "symptom" },
  { "word": "දග්ධරුහ", "meaning": "නලතණ", "category": "plant" },
  { "word": "දණ්ඩිිකා", "meaning": "බන්දමකුළු, ඇත්සාවිය", "category": "plant" },
  { "word": "දග්ධ පාදන", "meaning": "දඹකුළු, (දඹුමන්) ආහාර පිසූ භාජනයේ පතුලෙහි පිළිස්සුණ ආහාර කොටස්", "category": "treatment" },
  { "word": "දග", "meaning": "සාදිලිංගම්", "category": "treatment" },
  { "word": "දගාදය", "meaning": "ගුලවංග, කුරාඳු", "category": "treatment" },
  { "word": "දබුදින්නරා", "meaning": "වැල්මිදට හෝ නිදිකුම්බා", "category": "plant" },
  { "word": "දබුඹුල්", "meaning": "ඉඹුල් වර්‍ගයක්", "category": "plant" },
  { "word": "දබකලන්", "meaning": "මස්වැන්න, හෙළඹිය, (කොල්ලු)", "category": "plant" },
  { "word": "දබකෙහෙල්", "meaning": "වල්කෙහෙල් වර්ගයක්", "category": "plant" },
  { "word": "දබරත්", "meaning": "කෝට්ටන්, කොළොම් ගස", "category": "plant" },
  { "word": "දබවල්", "meaning": "දබුවැල් පණි", "category": "treatment" },
  { "word": "දබිතර", "meaning": "වැල්මදට, හින් නිදිකුම්බා", "category": "plant" },
  { "word": "දණ්ඩකේශීර", "meaning": "මහනුග, නුග", "category": "plant" },
  { "word": "දණ්ඩගිරි", "meaning": "නුග", "category": "plant" },
  { "word": "දණ්ඩපුෂ්ප", "meaning": "කොමාරිකා", "category": "plant" },
  { "word": "දණ්ඩපුෂ්පී", "meaning": "කොමාරිකා", "category": "plant" },
  { "word": "දණ්ඩේල", "meaning": "දැත්ත ගස", "category": "plant" },
  { "word": "දණ්ඩමානභ", "meaning": "පීත චිතගර නම් තුවරලා වගිය", "category": "plant" },
  { "word": "දණ්ඩරෑන්", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "දණ්ඩවල්ලී", "meaning": "කෙමෙබෙයි කොළ, (මොනරකුඩුම්බිය)", "category": "plant" },
  { "word": "දණ්ඩවාලී", "meaning": "කුමුරු මැන්න, වුව සබැරැ", "category": "plant" },
  { "word": "දණ්ඩවාස", "meaning": "දළක්ගස", "category": "plant" },
  {
    "word": "දන්තකැටියා",
    "scientific": "Ophiorrhiza Mangos",
    "meaning": "සර්පගන්ධි. මෙය අඩි දෙකක් පමණ උසට වැවෙන ඒකාවේරිය ගසකට අයත් පැලෑටියකි. කඳෙහි අග සෑදෙන හැම මල් පොකුරක් ම පෙති පහ බැගින් ඇති කුඩා මල් හට ගනිති. මේ මල් හැම අතින් ම ඒකාවේරිය මල් වලට සමාන නමුත් ප්‍රමාණයෙන් ඊට වඩා කුඩා ය. මල් වැටුනායින් පසු ඉතිරි වන හැම මල් පොකුරක ම දත් වල හැඩ හුරුකම ඇති ඇට කොපු පේළි පහ බැගින් ඇත. මේ මල් කොපු පොකුරු දත් සැට්ට (පොකුරු) වලට සමාන නිසා මේ වගිය දන්තකැටියා යන නාමයෙන් වෙදකමට හඳුන්වා දී ඇත. සර්පයන් සපා කෑම නිසා හෝ පොළොන් විෂ ඇතුළු වූ හැම විෂකටම මෙය ප්‍රත්‍යක්ෂ ඖෂධයකි.",
    "category": "plant"
  },

  // --- පිටුව 237 ---
  { "word": "දත්මි ශාඛා", "meaning": "සිරිතේක්කු", "category": "plant" },
  { "word": "දත්තීගස්තී", "meaning": "තුවරලාමල, පණබි නගර", "category": "plant" },
  { "word": "දත්තා", "meaning": "ලියනඟලා, වෙල්ලන්ගිරිය, ගස්කැලිය, කර්‍වෙල්ලන්ගිරිය", "category": "plant" },
  { "word": "දන්තඝාත", "meaning": "කිරිමිදෙල්ල", "category": "plant" },
  { "word": "දන්තීකා", "meaning": "තොවිල ගස", "category": "plant" },
  { "word": "දන්තින්", "meaning": "කුකුරුමුවන් ගෙඩි, දමනක වාක්‍ෂය", "category": "plant" },
  { "word": "දත්තෙබාලා", "meaning": "ගොඩමානෙල්, තුන්බෝ අත්තන, දැත්ත", "category": "plant" },
  { "word": "දත්තෙරමුල්", "meaning": "(කෂාය බෙහෙත්)", "category": "treatment" },
  { "word": "දත්තීර", "meaning": "තුන්බෝ අත්තන", "category": "plant" },
  { "word": "දද", "meaning": "කෝල්, පසින්", "category": "plant" },
  { "word": "දදකිරිය", "meaning": "රතුපාට උඳු පියලි වැනි කොළ ඇති හිරි සහිත පොළව මත ඇලී සැදෙන පැලෑටියක්", "category": "plant" },
  { "word": "දදකොළ", "meaning": "ළිඳුවිල, (බැමිනිරිය)", "category": "plant" },
  { "word": "දදගස්", "meaning": "දත්ත", "category": "plant" },
  { "word": "දදඵල", "meaning": "තිවුල්", "category": "plant" },
  { "word": "දදරද", "meaning": "සඳුන් ගස", "category": "plant" },
  { "word": "දදනස්", "meaning": "ලුණුවිල", "category": "plant" },
  { "word": "දදපල", "meaning": "තිවුල් ගෙඩි", "category": "plant" },
  { "word": "දදිලවණ", "meaning": "මුදු ලුණු", "category": "treatment" },
  { "word": "දදිසාර", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "දදී", "meaning": "දිකිරි", "category": "treatment" },
  { "word": "දදෝ", "meaning": "ලබු, අංකුරය", "category": "plant" },
  { "word": "දද්‍රැ", "meaning": "දද රෝගය", "category": "symptom" },
  { "word": "දද්‍රැවේරී", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "දද්‍රැහන", "meaning": "බෝදි ඇට, කෝර, තෝර ඇට, ඇත්තෝර, පෙනිතෝර", "category": "plant" },
  { "word": "දද්‍රැත්ති", "meaning": "බෝදි ඇට", "category": "plant" },
  { "word": "දද්‍රැතාසන", "meaning": "තෝර", "category": "plant" },
  { "word": "දද්‍රැහර්", "meaning": "තෝර ගස", "category": "plant" },
  { "word": "දධ්‍යග්ධ", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "දධ්‍යක්‍ෂ", "meaning": "හොරමැලියම්", "category": "treatment" },
  { "word": "දධ්‍යනී", "meaning": "කුරුක්ති", "category": "plant" },
  { "word": "දධ්‍යාහ්ව", "meaning": "තිවුළු ගස", "category": "plant" },
  { "word": "දධ්‍යාන්වය", "meaning": "හොරමැලියම්", "category": "treatment" },
  { "word": "දධිපුෂ්කර", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "දධිසාදන", "meaning": "දිමන්", "category": "treatment" },
  { "word": "දධිනසාර", "meaning": "දීපෙරලි දිය", "category": "treatment" },

  // --- පිටුව 238 ---
  { "word": "දධි", "meaning": "දිකිරි, තිවුළු ගස", "category": "treatment" },
  { "word": "දධිසීර", "meaning": "ගුගුල්, දීකිරි", "category": "treatment" },
  { "word": "දධිකා", "meaning": "කොත්තඹුරු, සිරිවට්ටු ගස, දිකිරි මුසු බත", "category": "plant" },
  { "word": "දධිකූර්ච්චිකා", "meaning": "දී හා කිරි එකට මිශ්‍ර දධි කූර්ච්චිකා නමි", "category": "treatment" },
  { "word": "දධිජ", "meaning": "දිවුල්", "category": "plant" },
  { "word": "දධිඵලාබා", "meaning": "තිවුළු මැලියම්", "category": "treatment" },
  { "word": "දධිපුෂ්ප", "meaning": "නොපිපුණු කිරි", "category": "treatment" },
  { "word": "දධිනාමක", "meaning": "තිවුළු ගෙඩිය", "category": "plant" },
  { "word": "දධිපුෂ්ප", "meaning": "වම්මුතු (කෛවර්ති වම්මුතු)", "category": "plant" },
  { "word": "දධිපුෂ්පක", "meaning": "අබනගිරිය", "category": "plant" },
  { "word": "දධිපුෂ්පා", "meaning": "වැල් පෙනෙල", "category": "plant" },
  { "word": "දධිපුෂ්පී", "meaning": "දේවදාලිය, වැල් පෙනෙල", "category": "plant" },
  { "word": "දධිපුෂ්පිකා", "meaning": "අබනගිරිය, එල කටරොළු, වඳුරු මෑ", "category": "plant" },
  { "word": "දධිඵල", "meaning": "දිවුල්, වට්ටක්කා", "category": "plant" },
  { "word": "දධිභව", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "දධිමණ්ඩ", "meaning": "දී පෙරලි දිය, මෝරු", "category": "treatment" },
  { "word": "දධිමණ්ඩෝත්භව", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "දධිවාරි", "meaning": "දී පෙරලි දිය", "category": "treatment" },
  { "word": "දධිවාස්තුකා", "meaning": "සිරියල් වෙසෙසක්", "category": "treatment" },
  { "word": "දධිශල්‍යතී", "meaning": "කරල් සැබ, හෙළ කරල් සැබ", "category": "plant" },
  { "word": "දධිසායස", "meaning": "ගිතෙල්", "category": "treatment" },
  { "word": "දධිසේතන", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "දධිසේවද", "meaning": "මෝරු", "category": "treatment" },
  { "word": "දධිසාර", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "දන්", "meaning": "මාදම්", "category": "plant" },
  { "word": "දතන", "meaning": "හිඟුරු පියලි, දන් කැටියා, හිඟිරි, ඇත්දෙත, (ඇත්දළ)", "category": "plant" },
  { "word": "දතතන", "meaning": "වා ඇසල", "category": "plant" },
  { "word": "දතනකර්", "meaning": "දෙබිම", "category": "plant" },
  { "word": "දතනකම්", "meaning": "දෙබිම, දෙහි", "category": "plant" },
  { "word": "දතනශාඛ", "meaning": "උගුරැස්ස, කුඹුක් ගස, කරඳ", "category": "plant" },
  { "word": "දතන ඡේතු", "meaning": "හින් තොහොඹු ගස", "category": "plant" },
  { "word": "දතසාර", "meaning": "දෙහි ගස", "category": "plant" },
  { "word": "දතනවිජ්ජපති", "meaning": "කාතිරි, කෙම් වැල්, කුන්දුරුක්කන්", "category": "plant" },
  { "word": "දතනධාවන", "meaning": "තිඟිරි, කවකිසිපි, මුහුණ මල්", "category": "plant" },
  { "word": "දතන පතුක", "meaning": "කොඳ මල්", "category": "plant" },
  { "word": "දතනපතිකා", "meaning": "කොඳ", "category": "plant" },
  { "word": "දතනපුෂ්ප", "meaning": "ඉඟිනි ගස, කොඳ මල්", "category": "plant" },
  { "word": "දතතෛල", "meaning": "කිවුළු, ඉඟිනි, වගපුල්", "category": "plant" },
  { "word": "දතනමුලිකා", "meaning": "දන් කැටිය, දන්ත කැටිය", "category": "plant" },
  { "word": "දන්තාරක්ෂත", "meaning": "කසීස්", "category": "treatment" },
  { "word": "දන්තවිජක", "meaning": "දෙළුම් ඇට, දෙළුම් ගස", "category": "plant" },
  { "word": "දතභමින්", "meaning": "දෙළුම් ගස, ලබු", "category": "plant" },
  { "word": "දතතශඨ", "meaning": "දිවුල්, දෙහි, කාමරංගා, ලප්නාරම්, දෙබම්, ඇඹරැල්ලා", "category": "plant" },
  { "word": "දන්තශඨා", "meaning": "ඇඹුලඇඹිලිය, මනබෑවිල", "category": "plant" },
  { "word": "දන්ත ශරිීර", "meaning": "දත් ලෙයින්", "category": "treatment" },
  { "word": "දන්තගාඛ", "meaning": "කොසඹ", "category": "plant" },
  { "word": "දන්තසද්", "meaning": "දෙහි", "category": "plant" },
  { "word": "දත්තා", "meaning": "වඳුරුපල", "category": "plant" },
  { "word": "දන්තායාන", "meaning": "කොසඹ, දෙහි", "category": "plant" },
  { "word": "දන්තාව්වා", "meaning": "හිඟුරා, පියලි", "category": "plant" },
  { "word": "දනි", "meaning": "දත්ත", "category": "plant" },
  { "word": "දන්යිකර්ණී", "meaning": "හබරල", "category": "plant" },
  { "word": "දන්තිකා", "meaning": "දත්ත", "category": "plant" },
  { "word": "දන්තිනී", "meaning": "දත්ත ගස", "category": "plant" },
  { "word": "දන්තීඵල", "meaning": "නිප්පිලි, ජයපාල ඇට", "category": "plant" },
  { "word": "දන්තිමුලිනා", "meaning": "දන්තගස", "category": "plant" },
  { "word": "දතිරධන්‍ද", "meaning": "දෙබම්, ලප්නාරම් ගස", "category": "plant" },
  { "word": "දන්විප්", "meaning": "ජයපාල ඇට", "category": "plant" },
  { "word": "දනුරණ්ඩ", "meaning": "ලප්නාරම් ගස", "category": "plant" },
  { "word": "දපනා", "meaning": "වේලා, සුදු දෑසමන් ගස", "category": "plant" },
  { "word": "දපලති", "meaning": "කුමුරු වැල්, හිඟුරා වැල්", "category": "plant" },
  { "word": "දඹික", "meaning": "දඹ වන්", "category": "plant" },
  { "word": "දන්ඩෙව", "meaning": "සිරිතේක්කු, (දම දෙව සඳු)", "category": "plant" },

  // --- පිටුව 239 ---
  { "word": "දන්තක", "meaning": "වැල් කසඹිලියා", "category": "plant" },
  { "word": "දන / දනා", "meaning": "කොත්තමල්ලි, කුරා ගින, (කටුකරෝෂණ)", "category": "plant" },
  { "word": "දන්පල", "meaning": "කිරිපළු", "category": "plant" },
  { "word": "දනා", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "දනිකී", "meaning": "මීග පෝටා වැල", "category": "plant" },
  { "word": "දනී", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "දනු", "meaning": "බදුල්ල", "category": "plant" },
  { "word": "දම දෙව සුදු", "meaning": "සිරිතේක්කු, ජාති දඹ", "category": "plant" },
  { "word": "දමසෙනෙව", "meaning": "ඉරිවේ", "category": "plant" },
  { "word": "දමබටුල", "meaning": "සෙවට්ටුල ව්‍යංජනය", "category": "treatment" },
  { "word": "දමළුං ගරණ", "meaning": "ගප්සඳ", "category": "plant" },
  { "word": "දමි", "meaning": "බෝදි ගස, බටු ගස, බට ගස", "category": "plant" },
  { "word": "දමිහෘ", "meaning": "මී හුඟ", "category": "plant" },
  { "word": "දමන", "meaning": "බට", "category": "plant" },
  { "word": "දමනක", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "දමනී", "meaning": "නිලතිඬා වැල්", "category": "plant" },
  { "word": "දමයත්තී", "meaning": "ඉද්ද වෙසෙසක්, කසීරි", "category": "plant" },
  { "word": "දමිකා", "meaning": "මිරිස්", "category": "plant" },
  { "word": "දමුණු", "meaning": "උගුරැස්ස, (බොරළු දමුණු) දමුණු මල්", "category": "plant" },
  { "word": "දයි", "meaning": "සාදන්, ජමුළු", "category": "plant" },
  { "word": "දද්දරක්ද", "meaning": "මහත් පලා, ගොඩුකොළ", "category": "plant" },
  { "word": "දද්දුර", "meaning": "පිට සුදු සාරණ", "category": "plant" },
  { "word": "දද්දුරච්ඡද", "meaning": "බැමිනිරිය, (ලුණුවිල)", "category": "plant" },
  { "word": "දද්දුරදලා", "meaning": "ගොඩුකොළ", "category": "plant" },
  { "word": "දද්දුර පර්ණී", "meaning": "බැමිනිරිය", "category": "plant" },
  { "word": "දර්ද්‍රැ", "meaning": "මදල් ගස", "category": "plant" },
  { "word": "දර්ද්‍රැස්න", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "දද්ද්‍රැ වෛරින්", "meaning": "කිඹුල් ගස", "category": "plant" },
  { "word": "දර්ණ", "meaning": "ඉලක්, ද්වක්, පිකණී", "category": "plant" },
  { "word": "දර්ප", "meaning": "කස්තුරි, සාරණ", "category": "treatment" },
  { "word": "දර්පා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "දර්භ", "meaning": "ඉලක්, ද්වක්, ඊතණ", "category": "plant" },
  { "word": "දර්භ පත්‍ර", "meaning": "වැළුක්", "category": "plant" },
  { "word": "දර්වි", "meaning": "නෑවැඳ, හින් කරඹ", "category": "plant" },
  { "word": "දර්විපත්‍රිකා", "meaning": "ගොඩු කොළ", "category": "plant" },
  { "word": "දර්වනීය", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දර්වාතොත්තලා", "meaning": "සුදු දෑසමන් ගස", "category": "plant" },
  { "word": "දර්ශ", "meaning": "හාතාවාරිය, සංඛ්බෙල්ලා", "category": "plant" },
  { "word": "දර්සණකෝකා", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "දලද", "meaning": "හිඟුල්, සාදිලිංගම්, වච්චනාවි", "category": "treatment" },
  { "word": "දර්සූර", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දලනාර", "meaning": "මසන්", "category": "plant" },
  { "word": "දල", "meaning": "කොල්ලම් කොළ, දන, කොළ (පත්‍ර)", "category": "plant" },
  { "word": "දලකිරිනී", "meaning": "පහනක් ගස", "category": "plant" },
  { "word": "දලකඩ", "meaning": "ගල්ගුණ රෝගය", "category": "symptom" },
  { "word": "දලකූරා", "meaning": "දව කොළ", "category": "plant" },
  { "word": "දලකොෂ", "meaning": "කොඳ මල්, ඉද්ද", "category": "plant" },
  { "word": "දලදර", "meaning": "කලාඳුරු, (වම්මුතු)", "category": "plant" },
  { "word": "දල නිමොකා", "meaning": "කරගස්, බූත්පන්නැස්", "category": "plant" },
  { "word": "දලපුෂ්පා", "meaning": "වැටකේ", "category": "plant" },
  { "word": "දලමේ", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "දලස්නුති", "meaning": "සබුක්", "category": "plant" },
  { "word": "දලසාලාසී", "meaning": "සුදු තලා ගස", "category": "plant" },
  { "word": "දලසාරිනී", "meaning": "ගඟුවා ගස", "category": "plant" },
  { "word": "දලසුනා", "meaning": "මීගිරි ගස", "category": "plant" },
  { "word": "දලා", "meaning": "අසමෝදගම්, බුලත්", "category": "plant" },
  { "word": "දලාසක", "meaning": "නාමල් රේණු, මාර, මදටිය, තල ගස", "category": "plant" },
  { "word": "දලාසකි", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "දලාසහස", "meaning": "කොල්ලම් කොළ", "category": "plant" },
  { "word": "දලාමිල", "meaning": "කුකුරුමුවන්, දමනක රුක", "category": "plant" },

  // --- පිටුව 240 ---
  { "word": "දලාන්ම", "meaning": "කොල්ලම් කොළ", "category": "plant" },
  { "word": "දක්", "meaning": "එනම් ගස", "category": "plant" },
  { "word": "දක්වමුල්", "meaning": "රක්දි, නිප්පිලි මුල්", "category": "plant" },
  { "word": "දද්වා", "meaning": "නිප්පිලි", "category": "plant" },
  { "word": "දලෙගහී", "meaning": "රක් අත්තන", "category": "plant" },
  { "word": "දවම", "meaning": "දහස", "category": "treatment" },
  { "word": "දවන්තී", "meaning": "මී හුඟ", "category": "plant" },
  { "word": "දවලදුරා", "meaning": "සුදු දුරු", "category": "plant" },
  { "word": "දවල සඳුන්", "meaning": "සුදු සඳුන්", "category": "plant" },
  { "word": "දවල්නර්", "meaning": "අන්කෙන්ද", "category": "plant" },
  { "word": "දවස්ගිගී", "meaning": "වරාගස", "category": "plant" },
  { "word": "දවා", "meaning": "හුඟල", "category": "plant" },
  { "word": "දවාලී", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "දගහ", "meaning": "නාල්", "category": "plant" },
  { "word": "දගකුල", "meaning": "බෝගස", "category": "plant" },
  { "word": "දගමුල වාක්‍ෂ", "meaning": "ලෝලු, කරඳ, බෙලි, ඇසතු, කොලොම්, කොනොම්, නුග, දිවුල්, ඇඹුල, සිසයිලා යන ගස් දහය", "category": "plant" },
  { "word": "දගපවා", "meaning": "දශමූල", "category": "plant" },
  { "word": "දගනවිප්", "meaning": "දෙළුම් ගස", "category": "plant" },
  { "word": "දගනාග්‍ය", "meaning": "ඇඹුලඇඹිලිය", "category": "plant" },
  { "word": "දගපුෂ්ප", "meaning": "කලාඳුරු", "category": "plant" },
  { "word": "දගමුළු", "meaning": "කලාඳුරු", "category": "plant" },
  { "word": "දගමුල", "meaning": "දසමුල් - බෙලි, තොවිල, ඇටදෙමට, පලොල්, සිහින් මිදි, අස්වැන්න, ප්‍රශ්නිපර්ණී, එලබටු, කටුවැල්බටු, ගොකටු, (නෙරෙවි) යන මුල් දස වගිය", "category": "plant" },
  { "word": "දග ලවණ", "meaning": "සෛන්ධව, සුවස, බලල්, යවක්‍ෂාර, වැලිගර (මැටිකර ලුණු=සාරණී සංග්‍රහවෙහි) මුණ්ඩ, උද්භිද, කෘළු, රෝම, පාංශු යන ලුණු දස වගය.", "category": "treatment" },
  { "word": "දගසංඛාධ්‍යී", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "දගසහකාලුත්බ", "meaning": "වරාකිරි", "category": "plant" },
  { "word": "දශාධි", "meaning": "දශමුල", "category": "plant" },
  { "word": "දශානිකා", "meaning": "දත්ත ගස", "category": "plant" },
  { "word": "දශාශීර්", "meaning": "මුව, තොටුල, ගව, එළු, බැටු, තිරෙල, මහිෂ, ඇත්, යන මේ සතුන්ගේ කිරි සහ තන කිරි (සතුන්ගේ කිරි)", "category": "treatment" },
  { "word": "දසකුල", "meaning": "බෝගස", "category": "plant" },
  { "word": "දසන", "meaning": "දත්ත", "category": "plant" },
  { "word": "දසමුඛ", "meaning": "හස්ති, මහිෂ, ගස්ති, අශ්ව, මුව, පසෙළුව, තිරෙළු, බැටු, කොටළු, නර යන මේ දස දෙනාගේ මූත්‍ර", "category": "treatment" },
  { "word": "දසමුල්ගණය", "meaning": "දශමුල බලන්න", "category": "plant" },
  { "word": "දසවග මාංස", "meaning": "ගෝන, ගව, එළු, බැටළු, මුව, මුන්ටි, ඉත්තෑ, ඌරු, කුකුළු, මොනර යන මොවුන්ගේ මාංස දස වගියයි.", "category": "treatment" },
  { "word": "දසවෙසිකා", "meaning": "දන්තකා (වී පොතු)", "category": "plant" },
  { "word": "දසාවිශුල", "meaning": "පත්තක්කා, පැණි කොමඩු", "category": "plant" },
  { "word": "දසාරණා", "meaning": "ලියනඟලා, කෙකටිය", "category": "plant" },
  { "word": "දසි", "meaning": "කොලොම් ගස", "category": "plant" },
  { "word": "දහ", "meaning": "තුවරලා වැල්, සාදිලිංගම්", "category": "plant" },
  { "word": "දහදස", "meaning": "කුරාඳු", "category": "treatment" },
  { "word": "දහන", "meaning": "බදුල්ල, මිදි, රත් නිවුල්, වරා, කුඩුමිරිස්,", "category": "plant" },
  { "word": "දහනම්බු", "meaning": "බදුල්ල", "category": "plant" },
  { "word": "දහනමිප්‍ර", "meaning": "ලියනහලා", "category": "plant" },
  { "word": "දහනා", "meaning": "හිඟුල්-කාෂි", "category": "treatment" },
  { "word": "දහනි", "meaning": "මුරුවා", "category": "plant" },
  { "word": "දහනෝපල", "meaning": "පලිඟු", "category": "treatment" },
  { "word": "දළු", "meaning": "පෙතන්, අඹකුරය", "category": "plant" },
  { "word": "දළු සර", "meaning": "(ජලචර) මත්ස්‍යයෝ", "category": "treatment" }
];