// data_405_417.js - පිටු 405 සිට 417 දක්වා සියලුම වචන සහ විස්තර
const data_extra_405_417 = [
    // --- පිටුව 405 ---
    { 
        "word": "රුක් ගොකටු හා රන්කිරි ගොකටු", 
        "meaning": "වල් ගොකටු (නෙරෙවි = ගොක්‍ෂුරක) වගියක් ද මේ රටේ තිබෙන නිසා රුක් ගොකටු නමිනුත්, ඒ ගසෙන් රත් පාට කිරි නික්මෙන නිසා රත් කිරි ගොකටු නමිනුත්, ගොරක ගසට සමාන නමුදු කොළ හා කඳන් තද කාෂණ වර්ණයෙන් යුක්ත නිසා කණ (කාෂ්ණ) ගොරක නමිනුත්, ගොරක මල් වලට සමාන මල් පොකුරු සෑදෙන නමුදු ගොරක ගෙඩි පමණ විශාල නොවන රට තිබ්බටු ගෙඩි වැනි ප්‍රකට ව නොපෙනෙන කුඩා ගෙඩි සෑදෙන නිසා මල ගොරක - මල්ගොරක යන නම් වලින් හැඳින්වෙන මේ රුක් ගොකටු ගස පමණකි ලංකාවේ තිබුණේ.\n\nඋතුරු අමෙරිකාවේ මැක්සිකෝ ප්‍රදේශය ජන්ම භූමිකොට ඇති (Argemone Mexicana) නැමැති පැලෑටිය මෙහි බෝවී මෙන් පසු තවත් රන්කිරි ගොකටු වර්ගයක් එයට එකතු විය.\n\nකටු සහිත රන්වන් පාට කිරි නික්මෙන ඒ පැලෑටි ආයුර්වේදයට හා දේශීය වෙදකමට ඇතුල් කර ගැනීමේ දී කණකත පත්‍රී, ස්වර්ණක්‍ෂීරී, රන් කිරි ගොකටු යන නම් වලින් හැඳින්වීම යි එයට හේතුව වූනේ. එක ම නමින් පවත්නා මේ දෙවර්ගය රස-ගුණ-වීර්‍ය, වශයෙන් හා හැඩහුරු කමින් ද වෙනස් ය.\n\nරුක් ගොකටු (රන්කිරි ගොකටු) ගස ගොරක ගසක් වැනි විශාල වෘක්‍ෂයකි. කණකත පත්‍රී (රන්කිරිගොකටු)ගස කටුවැල්බටු වැනි කුඩා පැලෑටියකි. පිට රටින් අළුතෙන් ආ පැළෑටියකට රත්කිරි ගොකටු යන නම තබා අපේ පැරණි රන්කිරි ගොකටු ගසේ නම මකා දමන්ට ඇතැම් අය ගන්නා උත්සාහය ගැන අනුකම්පා කළයුතුය. (රන්කිරි ගොකටු පැලය ගැන ලියා ඇති විස්තරය බලන්න)", 
        "category": "plant" 
    },
    { "word": "රුක්පෙනෙල", "meaning": "ගස්පෙනෙල = (163 පිටේ ගස් පෙනෙල ගැන ලියූ විස්තරය බලන්න)", "category": "plant" },
    { "word": "රුක්බුරද", "meaning": "හිඹුරු", "category": "plant" },
    { "word": "රුක්බෝ", "meaning": "රුක්අත්තන ගස", "category": "plant" },
    { "word": "රුක්ම", "meaning": "නාකේසර", "category": "plant" },
    { "word": "රුක්මිණී", "meaning": "ස්වර්ණක්‍ෂීරී (රන්කිරි ගොකටු)", "category": "plant" },
    { "word": "රුක්රකුන්", "meaning": "රුක්ගස්", "category": "plant" },
    { "word": "රුක්සිදුරු", "meaning": "ගස්බෙන (වෘක්‍ෂකුහර)", "category": "general" },
    // --- පිටුව 406 ---
    { "word": "රුක", "meaning": "රුකඟුණ ගස, (අංකොලගස)", "category": "plant" },

    { 
        "word": "රුකඟුණ", 
        "scientific": "Alangium Lamarckii",
        "meaning": "Alangium Lamarckii- රුකඟුණ - ගස් අඟුණ. (අංකොල - ගන්ධපුෂ්ප)\n\nමෙහි කොළ දිග-පළලින් මකුළු කොළවලට සමානය. එහෙත් මකුළුකොළ මෙන් සම්පූර්ණයෙන් දිග හැරී නැත. මදක් ගොටු ගැසී ඇත. මෝරපු කොළ පවා ලපටි පෙනුමෙන් යුක්ත ය. මස සහිත ය. ප්‍රාණවත් ය. මල් දෙඹ මල්වලට මදක් සමාන නමුත් පිපුණ විට රේණු ඊට වඩා දික්ව සිටී යි. ඒ මල් තද සුවඳකින් යුක්ත ය. ගසේ කඳ සුදු පාට ය. අඩි 30 ක් පමණ උසට වැවේ යි.\n\nතෝෂාන්විත වෘක්‍ෂයක්:\nමෙය පුදුම එලවන ඖෂධ ගුණයකින් යුත් තෝෂාන්විත දුර්ලභ වෘක්‍ෂයකි. මේ ගස් තිබෙන ඉඩම් වලට සර්පයෝ නො පැමිණෙති. තිඹිරි ගෙඩියෙහි මෙන් ඉදිරියට නෙරා තිබෙන තොම්බක් ඇති ඇඹුල් පේර වැනි මේ ගසේ ගෙඩි වල ඇතුළත ඇත්තේ එක ම ඇටයක් පමණකි.\n\nඅහසින් යාමට:\nඅදෘශ්‍යමාන ව (නොපෙනී) සිටීමට හා අහසින් යාමට විද්‍යාධරයන් විසින් සකස් කරණ අඳුන් වලට මේ තෙල් අවශ්‍ය බවත්, නියම පිළිවෙලට ඇට ලබා ගත හැක්කේ හිමාල වන ප්‍රදේශයෙහි වැවෙන මේ වගියේ ගස් වලින් පමණක් බවත් බෙහෙත් වට්ටෝරු පොත් වල කියා තිබේ. ලංකාවේ තිබෙන රුකඟුණ ගස් කීපය පරික්‍ෂා කර බැලීමි. ඒවායේ සෑදෙන ගෙඩි වල ඇතුළලා රන් පැහැයෙන් යුක්ත ව හිස් ව තිබේ. ඇතුළෙහි ඇටයක් හෝ වෙන කිසිවක් නැත. අපේ රටේ තිබෙන යම්කිසි ගසක ඇට සෑදෙනොත් එය හිමාලය අඩවියට සමාන පෘථිවි රසයෙන් යුත් උසස් භූමියක පිහිටීම නිසා සිදු වන ප්‍රාතිහාර්‍ය්‍යයක් විය හැකි යි.", 
        "category": "plant",
        "image": "img_406_rukanguna.jpg"
    },
    // --- පිටුව 407 ---

    { "word": "රුකුදු", "meaning": "රුක්මල්", "category": "plant" },
    { "word": "රුක්‍ෂ", "meaning": "රත්රන්, අත්තන, ලෝකඩ, නාමල් රේණු", "category": "plant" },
    { "word": "රුච", "meaning": "දුමැඬ", "category": "plant" },
    { "word": "රුචක", "meaning": "සර්ජීක්‍ෂාර, (සුවසලුනු), වලඟසාල්, දෙළුම්, ලූණු, ගෝරෝචන, එරඬු, ලප්නාරං, බදුල්ල, බලල් ලුණු, කළඳ", "category": "plant" },
    { "word": "රුචරූකඛ", "meaning": "බූරද ගස", "category": "plant" },
    { "word": "රුචි", "meaning": "ගෝරෝචන", "category": "mineral" },
    { "word": "රුචිකන්තක", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "රුචිර", "meaning": "මිරිස්, නියඹරා, කොකුම්, කුරුඳු, ගෝරෝචන, කරාබු නැටි, රිදී", "category": "plant" },
    { "word": "රුචිරබන්ධු", "meaning": "සාසහක, උණමකුළු, කළු කිරිබදු", "category": "plant" },
    { "word": "රුචිරාංක්‍ෂන", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "රුචිෂ්‍යා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "රුචු", "meaning": "එරබු, හෙළ එරබු", "category": "plant" },
    { "word": "රුච්‍ය", "meaning": "සුවසලුණු, ඉඟිනි ගස, ඇල් වී", "category": "plant" },
    { "word": "රුච්‍යක", "meaning": "සුවස ලුණු", "category": "mineral" },
    { "word": "රුච්‍යකඤ්", "meaning": "කිබාරම්", "category": "plant" },
    { "word": "රුජා", "meaning": "ලෙඩ, කොට්ටම්", "category": "treatment" },
    { "word": "රුජාකර", "meaning": "කාමරංගා ගෙඩි", "category": "plant" },
    { "word": "රුජාසන", "meaning": "වැලුඟුන්", "category": "plant" },
    { "word": "රුතිදෙනගොමුය", "meaning": "රුචි දෙනකගේ ගොම හා මූත්‍ර", "category": "animal" },
    { "word": "රුතිකා", "meaning": "උළුවා", "category": "plant" },
    { "word": "රුදිර", "meaning": "රුධිරය (ලේ)", "category": "anatomy" },
    { "word": "රුදිරය", "meaning": "ලේ", "category": "anatomy" },
    { "word": "රුදිරහර", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "රුද්‍රා", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "රුද්‍රරුක්‍ෂිප්", "meaning": "ජයපාල ඇට", "category": "plant" },
    { "word": "රුද්‍ර", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "රුද්‍රප්", "meaning": "රසදිය", "category": "mineral" },
    { "word": "රුද්‍රජටා", "meaning": "ඊශ්වරයාගේ ජටාව බඳු පෙනුමන් පාට ඇති වැල්ජාතියක්, (ජටාමකුට)", "category": "plant" },
    { "word": "රුද්‍රපත්නී", "meaning": "එළ රතණ, ඇගැස්ස", "category": "plant" },
    { "word": "රුද්‍රපුෂ්ප", "meaning": "බදුවද, වද", "category": "plant" },
    { "word": "රුද්‍රප්‍රියා", "meaning": "අරළු, ගුගුල්", "category": "plant" },
    { "word": "රුද්‍රමල්ලී", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "රුද්‍රා", "meaning": "හෙළ තම්පලා", "category": "plant" },
    { "word": "රුධිර", "meaning": "ලේ, තඹ, කොකුම්", "category": "mineral" },
    { "word": "රුධිරනාමක", "meaning": "කොකුම්", "category": "plant" },
    { "word": "රුධිරපායි", "meaning": "කූඩැල්ලා", "category": "animal" },
    { "word": "රුපුතෙල්", "meaning": "එරඬු තෙල්", "category": "liquid" },
    { "word": "රුඹු, රූඹුක, රූඹ්‍රක", "meaning": "එරබු", "category": "plant" },
    { "word": "රුලන්", "meaning": "රට තිරිඟු පිටි", "category": "food" },
    { "word": "රුමන්", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "රුමු", "meaning": "එරඬු, රක් එරබු", "category": "plant" },
    { "word": "රුක්‍ෂක", "meaning": "කුෂ්ට රෝගය", "category": "treatment" },
    { "word": "රුක්‍ෂජිහ්ව", "meaning": "මහා කුෂ්ට රෝගය", "category": "treatment" },
    { "word": "රුක්‍ෂකරා", "meaning": "මකුල්ගස", "category": "plant" },
    { "word": "රුහ", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "රුහර", "meaning": "සමුනය", "category": "plant" },
    { "word": "රූ", "meaning": "ශුක්‍ර ධාතුව", "category": "anatomy" },
    { "word": "රූක්‍ෂ", "meaning": "දත්ත ගස, කොට්ටම්, වියලි දේ", "category": "plant" },
    { "word": "රූක්‍ෂගන්ධ", "meaning": "ගුගුල්, පෙරුම්කායම්", "category": "plant" },
    { "word": "රූක්‍ෂපත්‍ර", "meaning": "ගැටනිටුල්", "category": "plant" },
    { "word": "රූක්‍ෂප්‍රිය", "meaning": "සාමහක", "category": "plant" },
    { "word": "රූක්‍ෂා", "meaning": "දුදු", "category": "plant" },
    { "word": "රූකාවා", "meaning": "ලප්නාරම්", "category": "plant" },
    { "word": "රූකණ්ඨා", "meaning": "ලප්නාරම්", "category": "plant" },
    { "word": "රූප", "meaning": "කුප්පමේනිය", "category": "plant" },

    // --- පිටුව 408 ---
    { "word": "රූපලාභිනී", "meaning": "දුදු", "category": "plant" },
    { "word": "රූපවාන්", "meaning": "හෝපලු ගස", "category": "plant" },
    { "word": "රූපාරී", "meaning": "කොසඹ", "category": "plant" },
    { "word": "රූපිකා", "meaning": "එළවරා", "category": "plant" },
    { "word": "රූපිමාක්‍ෂික", "meaning": "දියරිදී", "category": "mineral" },
    { "word": "රූප්‍ය", "meaning": "රිදී", "category": "mineral" },
    { "word": "රූප්‍ය(ක)", "meaning": "රිදී", "category": "mineral" },
    { "word": "රූප්‍යතාර", "meaning": "රිදී", "category": "mineral" },
    { "word": "රූෂක", "meaning": "වංඇපල, කුෂ්ඨ රෝග විශේෂයක්", "category": "treatment" },
    { "word": "රූස්කරා", "meaning": "මකුල්, මකුල් ගස", "category": "plant" },
    { "word": "රූහා", "meaning": "මහාපෝටා වැල", "category": "plant" },
    { "word": "රෙචක", "meaning": "පික්මල්, යවකර, ජයපාල, මාරා ගස, ඇසළ", "category": "plant" },
    { "word": "රෙචන", "meaning": "ගොඩ ඊරිස්, ඇසළ, මගරි = මදටිය, ජයපාල, යවක්‍ෂාර ලුණු", "category": "plant" },
    { "word": "රෙචනක", "meaning": "වෙලඟ ගස", "category": "plant" },
    { "word": "රෙවනී", "meaning": "ත්‍රස්තාවළු, මිරිස්, කටු වෙලඟ", "category": "plant" },
    { "word": "රෙවී", "meaning": "අගුණ, වෙලඟ, රඹුටන්", "category": "plant" },
    { "word": "රෙණු", "meaning": "පැපිලිය, මල්රේණු, දූලි, පස්", "category": "plant" },
    { "word": "රෙණුකා", "meaning": "රහාණිය (වටරහාණ)", "category": "plant" },
    { "word": "රෙණුනාමක", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "රෙණුසාර", "meaning": "කපුරු, මල්රේණු", "category": "plant" },
    { "word": "රෙණුකො", "meaning": "හරේණුකා", "category": "plant" },
    { "word": "රෙවක", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "රෙවත", "meaning": "මිගස", "category": "plant" },
    { "word": "රෙවෙර", "meaning": "මානෙල් අල, නෙළුඹල", "category": "plant" },
    { "word": "රෙහෙර", "meaning": "නෙළුම් අල, සුළු ඕලු අල", "category": "plant" },
    { "word": "රෙහෙනිසුරු", "meaning": "කපුරු", "category": "plant" },
    { "word": "රෙමී", "meaning": "නිල් උණ ගස", "category": "plant" },
    { "word": "රේණු", "meaning": "රොත්, පැපිලිය", "category": "plant" },
    { "word": "රේණුක", "meaning": "රහාණිය (වල්ගා මිරිස්)", "category": "plant" },
    { "word": "රේණුනාමක", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "රේතස්", "meaning": "ශුක්‍රධාතුව", "category": "anatomy" },
    { "word": "රේමස්", "meaning": "රේරු", "category": "plant" },
    { "word": "රේරු", "meaning": "රේරු ගස් (කෙෂමුෂ්ටි)", "category": "plant" },
    { "word": "රේවඟි", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "රොකම්", "meaning": "රෝගි", "category": "treatment" },
    { "word": "රෝග", "meaning": "කොට්ටම්, ධාතු විෂමවීමට ගන්නා ලෙඩ", "category": "treatment" },
    { "word": "රෝගරාජ", "meaning": "ක්‍ෂය රෝගය", "category": "treatment" },
    { "word": "රෝගශිලා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "රෝගහාරීන්", "meaning": "වෛද්‍යවරයා", "category": "person" },
    { "word": "රෝගාර්පි", "meaning": "ලෙඩඇත්තා", "category": "person" },
    { "word": "රෝගිනරු", "meaning": "නෝපළු ගස", "category": "plant" },
    { "word": "රෝචක", "meaning": "රෝමලුණු, උද්භිදලුණු, ගොරද", "category": "mineral" },
    { "word": "රෝචන", "meaning": "ගෝරෝචන, කටු ඉඹුල්, එළමුරුංගා, සුදුලූනු, කරඳ, රඹුටන්, ඇසළ, දෙළුම්, රතු හෙල්මැලි", "category": "plant" },
    { "word": "රෝචනක", "meaning": "දෙබොම්", "category": "plant" },
    { "word": "රෝචනකඵල", "meaning": "දෙබොම්, දෙබොම් ප්‍රභේද, බෙබර ගස", "category": "plant" },
    { "word": "රෝචනා", "meaning": "මනෝසිල, ගෝරෝචන, නෙල්ලි, එළත්‍රස්තාවළු", "category": "plant" },
    { "word": "රෝචනි", "meaning": "ත්‍රස්තාවළු, මිරිස්, කුටු වෙලඟ", "category": "plant" },
    { "word": "රෝවචනො", "meaning": "කොළ හිඹුල්", "category": "plant" },
    { "word": "රෝචී", "meaning": "නිතිවැල්", "category": "plant" },
    { "word": "රෝදන(නී)", "meaning": "ඇල්කසඹිලියා", "category": "plant" },
    { "word": "රෝදනිකා", "meaning": "යවාස", "category": "plant" },
    { "word": "රෝදනී", "meaning": "දුරාලභා", "category": "plant" },
    { "word": "රෝත්", "meaning": "රේණු", "category": "plant" },
    { "word": "රොම", "meaning": "ලොම, කොල්ලන් කොළ, රෝමලුණු, කැකිරිවැල, මසිලමල", "category": "plant" },

   
    // --- පිටුව 409 ---
    { "word": "රොමක", "meaning": "පාංශුලුණු, සමහාරී නම් ලුණු, රෝම ලුණු", "category": "mineral" },
    { "word": "රොමන්ත", "meaning": "මලබටු", "category": "plant" },
    { "word": "රොමලවණ", "meaning": "රෝමලුණු", "category": "mineral" },
    { "word": "රොමලුණු", "meaning": "යවනලුණු", "category": "mineral" },
    { "word": "රොම වල්ලි සමන්විත", "meaning": "රසතැල්ල", "category": "plant" },
    { "word": "රොමශ", "meaning": "කොල්ලන්කොළ", "category": "plant" },
    { "word": "රොමශක", "meaning": "රෝමලුණු", "category": "mineral" },
    { "word": "රොමශා", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "රොමසි", "meaning": "ගස්කැළිය", "category": "plant" },
    { "word": "රොමසපා", "meaning": "කැකිරි", "category": "plant" },
    { "word": "රොමහමී", "meaning": "සාදිලිංගම්, හිඟුල්", "category": "mineral" },
    { "word": "රොමිහෂිණ", "meaning": "බුළුගස", "category": "plant" },
    { "word": "රොමාලපිච්පිත්", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "රොල", "meaning": "පිය යුතු නෙල්ලි", "category": "plant" },
    { "word": "රොල්", "meaning": "කටරොළු, (හෙළ(සුදු) කටරොළු, නිල් කටරොළු ය යි වගී දෙකකි.)", "category": "plant" },
    { "word": "රොසන", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "රොගනද්‍රැම", "meaning": "සුදුහඳුන්", "category": "plant" },
    { "word": "රොහි", "meaning": "වල්එරබදු", "category": "plant" },
    { "word": "රොහිණී", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "රොහිත්", "meaning": "නික්තලබු", "category": "plant" },
    { "word": "රොහිත", "meaning": "වල්එරබදු, ත්‍රස්තාවළු", "category": "plant" },
    { "word": "රොහිතක", "meaning": "වල්එරබදු", "category": "plant" },
    { "word": "රොහිතෙය", "meaning": "වල්එරබදු", "category": "plant" },
    { "word": "රොහිනි", "meaning": "දිඹුල්, මුවකිරිය, එරබදු, අරළු, කටුකරෝහිණී, මිදටගස්, ඇත්දෙමට", "category": "plant" },
    { "word": "රොහිෂ", "meaning": "සුවඳ තණ, වල්එරබදු, අසුගස", "category": "plant" },
    { 
        "word": "රෝහිතක", 
        "meaning": "කෑල වෙනුවට ඉන්දියාවේ ගන්නේ මේ ගසේ සාරය යි. මෙහි කොළ දිග පළලින් අඟල් 7 x 2 ක් පමණ ඇත. මෙහි කොළ හා කඳත් අපේ රටේ තිබෙන ගල් මොරගසක කොළවලට හා කඳට සමාන ය. මේ වගියට ලංකාවේ ඇතැම් පළාත්වල වල් එරබදු යන නම ද ව්‍යවහාර කරති. (ඉදිරියෙහි හිඟුල් ගුණ ලියා ඇති විස්තරය බලන්න)", 
        "category": "plant",
        "image": "img_409_rohitaka.jpg"
    },
    { "word": "රෝවනි", "meaning": "මිරිස්, මංජි(මඤ්ජි)", "category": "plant" },
    { "word": "රෝම", "meaning": "කැකිරිවැල, මසිලමල", "category": "plant" },
    { "word": "රෝස", "meaning": "මල්ගස් ජාතියක්", "category": "plant" },
    { "word": "රෝසන", "meaning": "කටුකරෝහිණී", "category": "plant" },

    // --- පිටුව 410 ---
    { "word": "රෝහිණ", "meaning": "එරබදු", "category": "plant" },
    { "word": "රෝහිණී", "meaning": "මදටිය, මුවකිරිය, කටුකරෝහිණී", "category": "plant" },
    { "word": "රෝහිණීද්‍රැම", "meaning": "සපුගස", "category": "plant" },
    { "word": "රෝහිස", "meaning": "අසුගස්", "category": "plant" },
    { "word": "රෞද්‍ර", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "රෞප්‍ය", "meaning": "රිදී", "category": "mineral" },
    { "word": "රෞම", "meaning": "ගාම්භාරී (ගම්හාරි) ලුණු, (රෝමලුණු)", "category": "mineral" },
    { "word": "රෞමක", "meaning": "රෝමලුණු", "category": "mineral" },
    { "word": "රෞහණ", "meaning": "සඳුන් රුක", "category": "plant" },
    { "word": "රෞහිණ", "meaning": "සඳුන්", "category": "plant" },
    { "word": "රෞහිණී", "meaning": "සුදු සඳුන්", "category": "plant" },
    { "word": "රෞහිෂ", "meaning": "රතණ", "category": "plant" },
    { "word": "රඃ", "meaning": "රත් හිරියල්", "category": "mineral" },
    { "word": "ල", "meaning": "හදවත", "category": "anatomy" },
    { "word": "ලක්තක", "meaning": "ලතුදිය (ලාක්‍ෂාරස)", "category": "mineral" },
    { "word": "ලක්තකමින්", "meaning": "රත්ලොත්", "category": "plant" },
    { "word": "ලක්තා", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "ලක්‍ෂක", "meaning": "උණකපුරු", "category": "plant" },
    { "word": "ලක්‍ෂණ", "meaning": "ඇපල ගස", "category": "plant" },
    { "word": "ලක්‍ෂමණා", "meaning": "රසතැල්ල, කටුවැල්බටු", "category": "plant" },
    { "word": "ලක්‍ෂමී", "meaning": "සැම, සුළුදඹකලත්, මැණික්වැන්න, සාදිවි නම් ඖෂධය, එක් පෙති පියුම", "category": "plant" },
    { "word": "ලක්‍ෂ්මීඵල", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "ලක්‍ෂ්මීවන්", "meaning": "කොස්ගස", "category": "plant" },
    { "word": "ලකච", "meaning": "දෙහිගස", "category": "plant" },
    { "word": "ලකචලිය", "meaning": "බුත්සරණ", "category": "plant" },
    { "word": "ලකුව", "meaning": "දෙල්ගස, කොස්ගොන්න ගස", "category": "plant" },
    { "word": "ලග්නී", "meaning": "උණකපුරු", "category": "plant" },
    { "word": "ලගතාඃ", "meaning": "සිනිමිදි", "category": "plant" },
    { "word": "ලගුඬ", "meaning": "රත්කණේරු", "category": "plant" },
    { "word": "ලඝ්වි", "meaning": "බෙබරගස", "category": "plant" },
    { "word": "ලඝු", "meaning": "බෙරු, වී, පික්මල්, උණකපුරු, විලඳ, රත්එරබු", "category": "plant" },
    { "word": "ලඝුකාම්‍යයි", "meaning": "ඇත්දෙමට හෙදයක්", "category": "plant" },
    { "word": "ලඝුකායීෂ", "meaning": "මල්කසිස්", "category": "mineral" },
    { "word": "ලඝුවන්දන", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "ලඝුච්ඡිටා", "meaning": "බෙබර ප්‍රභේද, කැකිරි", "category": "plant" },
    { "word": "ලඝුදන්තී", "meaning": "හින්දන්ත", "category": "plant" },
    { "word": "ලඝුනාමන්", "meaning": "අගිල්, සඳුන්", "category": "plant" },
    { "word": "ලඝුපර්ණී", "meaning": "මුරුවා", "category": "plant" },
    { "word": "ලඝුපුට", "meaning": "ගෝමවරටි අටකින් දෙන පුටය. එහෙත් රිදී ආදී ලෝහ ධාතුවල දී ගොම වරටි 30 කින් දෙන පුටය ලසුපුට නමි.", "category": "treatment" },
    { "word": "ලඝුපුෂ්ප", "meaning": "රත්ලොත්, මුඩමහණ, පුවක්ගස්, බින්කොළොම්", "category": "plant" },
    { "word": "ලඝුපුෂ්පා", "meaning": "රන්වන් වැටකොළු", "category": "plant" },
    { "word": "ලඝුබදර", "meaning": "හින්බෙබර", "category": "plant" },
    { "word": "ලඝුබ්‍රාහ්මී", "meaning": "හින් ලුණුවිල", "category": "plant" },
    { "word": "ලඝුමන්ජරී", "meaning": "සිනිමිදි", "category": "plant" },
    { "word": "ලඝුලය", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "ලඝුවල්කල", "meaning": "මුරුවා වැල", "category": "plant" },
    { "word": "ලඝුචිරේවනි", "meaning": "දන්ත", "category": "plant" },
    { "word": "ලඝුඇඳැලා", "meaning": "හින් දිඹුල්", "category": "plant" },
    { "word": "ලඝුහේමදුග්ධා", "meaning": "හින්දිඹුල්", "category": "plant" },
    { "word": "ලඞකායි(පි)කා", "meaning": "පික්මැලි", "category": "plant" },
    { "word": "ලඞකාස්නායි", "meaning": "නවහන්දි", "category": "plant" },
    { "word": "ලඞකරි", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "ලඞකෙපිකා", "meaning": "පික්මැලි", "category": "plant" },
    { "word": "ලජ්ජය", "meaning": "රහස්පියස", "category": "anatomy" },
    { "word": "ලජ්ජාලු", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ලජ්ජරි", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ලජ කා", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ලජ කාරිකා", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ලජ්ජකාරිකාරිකා", "meaning": "නිදිකුම්බා", "category": "plant" },

    // --- පිටුව 411 ---
    { "word": "ලට්ට", "meaning": "මිගස", "category": "plant" },
    { "word": "ලට්වා", "meaning": "වනුක්", "category": "plant" },
    { "word": "ලටු", "meaning": "වැල්මී, වැල්මදට", "category": "plant" },
    { "word": "ලඨිවන", "meaning": "වැල්මී වන", "category": "plant" },
    { "word": "ලතඹ", "meaning": "ලා දළුව", "category": "plant" },
    { "word": "ලතා", "meaning": "වැල, පුවඟු, රතණ, දුදු, යොහොඹු", "category": "plant" },
    { "word": "ලතාකස්තුරිකා", "meaning": "කපුකිනිය", "category": "plant" },
    { "word": "ලතාග්‍ර", "meaning": "පබළු", "category": "mineral" },
    { "word": "ලතාතරු", "meaning": "නාරම්, තල්, සල්", "category": "plant" },
    { "word": "ලතාන්ත", "meaning": "මල්", "category": "plant" },
    { "word": "ලතාඵල", "meaning": "පතෝල, දුම්මැල්ල", "category": "plant" },
    { "word": "ලතාමණී", "meaning": "පබළු, ලාකඩ", "category": "mineral" },
    { "word": "ලතාමරුන්", "meaning": "පික්මල්", "category": "plant" },
    { "word": "ලතායෂ්ටි", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "ලතායාවක", "meaning": "පබළු", "category": "mineral" },
    { "word": "ලතායාසු", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "ලතාකි", "meaning": "රන්වන් ලූනු, නිල්ලූනු, පබළු", "category": "plant" },
    { "word": "ලතාවගී", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "ලතාවෘක්‍ෂ", "meaning": "සල්ගස", "category": "plant" },
    { "word": "ලතාහ්වා", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "ලතු", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "ලද", "meaning": "කුකුරුමුවන් ගස", "category": "plant" },
    { "word": "ලදපස්මල්", "meaning": "රතණ, සමන්පිච්ච, සුන්සහල්, සුදු අබ, විලඳ", "category": "plant" },
    { "word": "ලත්තු", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "ලත්තුකාද්වික", "meaning": "හල්ගස", "category": "plant" },
    { "word": "ලප්", "meaning": "විලඳ", "category": "food" },
    { "word": "ලප්තැල්ල", "meaning": "තැල්වැල් වගියක්", "category": "plant" },
    { "word": "ලප්තාරං", "meaning": "නස්නාරන්", "category": "plant" },
    { "word": "ලප්නාරඟ", "meaning": "නත්නාරන් (නස්නාරන්)", "category": "plant" },
    { "word": "ලප්වටු", "meaning": "වටු (වටීටක) පක්‍ෂි වගියක්", "category": "animal" },
    { "word": "ලපක්", "meaning": "මැලැස්ස (ලා ගෙඩි)", "category": "plant" },
    { "word": "ලපන", "meaning": "මුඛය", "category": "anatomy" },
    { "word": "ලපළු", "meaning": "ලා දළුව", "category": "plant" },
    { "word": "ලපුස්", "meaning": "දෙල්", "category": "plant" },
    { "word": "ලබදු", "meaning": "දෙල්", "category": "plant" },
    { "word": "ලබු", "meaning": "දෙල්ගස", "category": "plant" },
    { "word": "ලබුසා", "meaning": "ලබු", "category": "plant" },
    { "word": "ලබෝර", "meaning": "කප්පරවල්ලිය", "category": "plant" },
    { "word": "ලඹු", "meaning": "ගැටපිච්ච", "category": "plant" },
    { "word": "ලම්පත", "meaning": "තුරුක්තෙල්", "category": "liquid" },
    { "word": "ලම්බකර්ණ", "meaning": "රාක්‍ෂඇඹුන් ගස", "category": "plant" },
    { "word": "ලම්බදත්තා", "meaning": "ලඹකා නිප්පිලි", "category": "plant" },
    { "word": "ලම්බන්වීජා", "meaning": "වන නිප්පිලි", "category": "plant" },
    { "word": "ලම්බඵල", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "ලම්බඵලා", "meaning": "ගබනහිරියා", "category": "plant" },
    { "word": "ලම්බබීජා", "meaning": "ලංකා නිප්පිලි", "category": "plant" },
    { "word": "ලම්බෝස්මා", "meaning": "නික්ත ලබු", "category": "plant" },
    { "word": "ලම්වා", "meaning": "නික්තලබු", "category": "plant" },
    { "word": "ලමග", "meaning": "කුරුඳු, කරාබු", "category": "plant" },
    { "word": "ලමගගස්", "meaning": "කුරුඳු හෝ කරාබු ගස්", "category": "plant" },
    { "word": "ලමගමෙදල", "meaning": "කුරුඳු, එන්සාල්, කොල්ලන් කොළ", "category": "plant" },
    { "word": "ලමහසුඹුළු", "meaning": "කුරුඳු පොතු", "category": "plant" },
    { "word": "ලමට", "meaning": "මිගස", "category": "plant" },
    { "word": "ලමසි", "meaning": "කොල්ලු, (බිළිඳුන්)", "category": "plant" },
    { "word": "ලමා", "meaning": "කොල්ලම්කොළ ගස", "category": "plant" },
    { "word": "ලවාඬි", "meaning": "හදවත", "category": "anatomy" },
    { "word": "ලමෝර", "meaning": "කප්පරවල්ලිය", "category": "plant" },
    { "word": "ලසිනෝරු", "meaning": "සායම් දිය කිරීමට ගන්නා තෙල් ජාතියක්", "category": "liquid" },
    { "word": "ලකී", "meaning": "වරා", "category": "plant" },
    { "word": "ලර්කි", "meaning": "කැකිරිවැල", "category": "plant" },
    { "word": "ලලන", "meaning": "සල්ගස, තල්ගස, පියල්ගස, දුම්මල", "category": "plant" },
    { "word": "ලලනාප්‍රිය", "meaning": "කොළොම්, ඉරිවේරිය, අරුද", "category": "plant" },
    { "word": "ලලිතා", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "ලව", "meaning": "ලැහැබ, කරාබුනැටි", "category": "plant" },


    // --- පිටුව 412 ---
    { "word": "ලවංඟ", "meaning": "කරාබුනැටි, කුරුඳුගස්, කරාබු ගස", "category": "plant" },
    { "word": "ලවංඟකලිකා", "meaning": "කරාබු", "category": "plant" },
    { "word": "ලවංඟපුෂ්ප", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "ලවංඟසුඹුලු", "meaning": "කුරුඳුපොතු", "category": "plant" },
    { "word": "ලවණ", "meaning": "ලුණු, බලල් ලුණු, මහදුදු", "category": "mineral" },
    { "word": "ලවණකිංගුකා", "meaning": "මහදුදු", "category": "plant" },
    { "word": "ලවණවච්ඡද", "meaning": "ලේනියපලා", "category": "plant" },
    { "word": "ලවණපාටුචිහව", "meaning": "උද්භිද ලුණු", "category": "mineral" },
    { "word": "ලවණමූල", "meaning": "ලුණුමඩ", "category": "mineral" },
    { "word": "ලවණා", "meaning": "දුදු", "category": "plant" },
    { "word": "ලවණාධිප", "meaning": "මුහුදුලුණු", "category": "mineral" },
    { "word": "ලවණාෂ්ටක", "meaning": "සවිඳවලුණු, සුවස ලුණු, කළුලුණු, මුහුදුලුණු, පාංශු ලුණු, බලල්ලුණු, උද්භිද ලුණු, රෝමලුණු", "category": "mineral" },
    { "word": "ලවණිකා", "meaning": "ලේනියපලා", "category": "plant" },
    { "word": "ලවණෝත්තම", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "ලවණෝබ්ධිසම්භව", "meaning": "මුහුදුලුණු", "category": "mineral" },
    { "word": "ලවන්", "meaning": "ලපල = (ලවන = අළුතෙන් වැවෙන කාල ය)", "category": "general" },
    { "word": "ලවන", "meaning": "ලපල", "category": "plant" },
    { "word": "ලවලිකා", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "ලවලි", "meaning": "අනෝනා, කටු අනෝනා", "category": "plant" },
    { "word": "ලගස", "meaning": "සලුල", "category": "plant" },
    { "word": "ලසවල්ලිය", "meaning": "දියෙහි වැවෙන වැල්", "category": "plant" },
    { "word": "ලසා", "meaning": "කහ අල", "category": "plant" },
    { "word": "ලසිකා", "meaning": "උක්පැණි, සදම්දුළු", "category": "food" },
    { "word": "ලසුහ / ලසුනු", "meaning": "සුදුලූනු", "category": "plant" },
    { "word": "ලහවු", "meaning": "දුම්මල, ලාබු", "category": "plant" },
    { "word": "ලාක්‍ෂා", "meaning": "ලාකඩ, හෙළ ලොත්", "category": "mineral" },
    { "word": "ලාක්‍ෂාප්‍රසාදන", "meaning": "ලොත්", "category": "plant" },
    { "word": "ලාක්‍ෂාඵල", "meaning": "ලා ගෙඩි (මැලැසි)", "category": "plant" },
    { 
        "word": "ලාක්‍ෂාරස", 
        "meaning": "ලතුදිය, සිනිදුව අඹරා ලාකඩ එක් ගුණයකට පිරිසිදු වතුර හය ගුණයක් සිටින සේ ගෙණ ලාකඩ සුණු ජලයේ ගෑවෙන පමණට භාජනයක තබා රත්කිරීමෙන් වර්ණවත් වන ජලය නැවත නැවතත් පෑදෙන්නට තබා පෙරා ගෑණීමෙන් පසු ලතු දිය සෑදේ.", 
        "category": "liquid" 
    },
    { "word": "ලාක්‍ෂී", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "ලාක්‍ෂිකා", "meaning": "හරංකසා", "category": "plant" },
    { "word": "ලාක", "meaning": "රත්ලොත් ගස", "category": "plant" },
    { "word": "ලාබා", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "ලාබාප්‍රසාදන", "meaning": "රත්ලොත්", "category": "plant" },
    { "word": "ලාඝව", "meaning": "නීරෝගී", "category": "treatment" },
    { "word": "ලාඞගලි", "meaning": "නියඟලා", "category": "plant" },
    { "word": "ලාඞගලිකා", "meaning": "පුස්වැන්න, ලියනඟලා", "category": "plant" },
    { "word": "ලාඞගලින්", "meaning": "පොල් ගස", "category": "plant" },
    { 
        "word": "ලාඞගලී", 
        "meaning": "ලියනඟලා, නියඟලා = දන්කැක්කුම සෑදුන විට මේ අල අඹරා තොලදෙන (දත් රුදාව නැති) අංශයේ පය මාපට ඇඟිල්ලේ බැඳීමෙන් සමහර දත් කැක්කුම් සුව වන බව පෙනේ. (275 පිටේ නියඟලා ගැණ ලියා ඇති විස්තරය බලන්න.)", 
        "category": "plant" 
    },
    { "word": "ලාංගුල", "meaning": "තල් ගස", "category": "plant" },
    { "word": "ලාංගුලිකා", "meaning": "අස්වැන්න, පුස්වැන්න", "category": "plant" },
    { "word": "ලාංගුලි", "meaning": "අස්වැන්න, වඳුරු මෑ", "category": "plant" },
    { "word": "ලාජ", "meaning": "සැවැන්න, බැඳිහාල්, විලඳ", "category": "plant" },
    { "word": "ලාජ පුෂ්පි", "meaning": "මඟුල් කරඳ ගස", "category": "plant" },



  
    // --- පිටුව 413 ---
    { "word": "ලාජා", "meaning": "විලඳ", "category": "food" },
    { "word": "ලාජාදි", "meaning": "විලඳ ආදි කොට ඇති", "category": "food" },
    { "word": "ලාජාපානිත", "meaning": "මල්තැලි දිය, මල්සර (මල් පැණි)", "category": "liquid" },
    { "word": "ලාජා පුෂ්පී", "meaning": "මඟුල් කරඳ ගස", "category": "plant" },
    { "word": "ලාටපර්ණ්‍ය", "meaning": "කුරුඳු පොතු", "category": "plant" },
    { "word": "ලාටුරූ", "meaning": "දරුණු පාප රෝගයක්", "category": "treatment" },
    { "word": "ලාපිනී", "meaning": "යොන්තුඹ", "category": "plant" },
    { "word": "ලාබු (ජ)", "meaning": "ලබු", "category": "plant" },
    { "word": "ලාබුලතා", "meaning": "ලබු වැල", "category": "plant" },
    { "word": "ලාබුසුඹුබි", "meaning": "ලබු", "category": "plant" },
    { "word": "ලාම්ප්ප (ක)", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "ලාමිජ්ජව", "meaning": "සැවැන්දරා", "category": "plant" },
    { "word": "ලාලන", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "ලාලා", "meaning": "කෙළ", "category": "anatomy" },
    { 
        "word": "ලාලු", 
        "meaning": "පොල් කිරි සමග මිශ්‍ර කර උකු කළ පිටි කැන්ද කොළ වල ගා අව්වෙන් වියලා ගලවා ගත් පප්පඩම් වැනි සිනිදු රොටී පොල් තෙලෙන් බැද පැණි ඉස පිළියෙල කරගන්නේ ලාලු නමි.", 
        "category": "food" 
    },
    { "word": "ලාස් හතර", "meaning": "ද්‍රෝණය, (පලම් 256)", "category": "measurement" },
    { "word": "ලාස්-නාලි හතර", "meaning": "(කුරුණිය, පත 16, සීරු නැඹුමක්)", "category": "measurement" },
    { "word": "ලැම", "meaning": "හිරියල්", "category": "mineral" },
    { 
        "word": "ලිංගම්", 
        "meaning": "හිඟුල් (සාදිලිඞගම්) රසදිය පෙරාගන්නේ මේ සාදිලිඞගම් වලින් ය. එයිනුත් රසදිය වැඩිපුර තිබෙන්නේ උලාදිලිඞගම් වල ය.", 
        "category": "mineral" 
    },
    { "word": "ලිකුච", "meaning": "දෙහි ගස, දෙල් ගෙඩි", "category": "plant" },
    { "word": "ලිකුචයුස", "meaning": "දෙහි ඇඹුල්", "category": "plant" },
    { "word": "ලිකුවො", "meaning": "දෙහි", "category": "plant" },
    { "word": "ලිකොචක", "meaning": "රුක් අඟුණ ගස", "category": "plant" },
    { "word": "ලිංග", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "ලිංගක", "meaning": "ජූල් ගස (දිවුල් ගස)", "category": "plant" },
    { "word": "ලිංග වධනි", "meaning": "සැබෝ", "category": "plant" },
    { "word": "ලිප කදලි", "meaning": "ඇට කෙසෙල්", "category": "plant" },
    { "word": "ලියකස්තුරු", "meaning": "තකුල් (කපු කිනිස්ස = ලතා කස්තුරිකා)", "category": "plant" },
    { "word": "ලියන් තන රස", "meaning": "තන කිරි", "category": "liquid" },
    { "word": "ලියනහලා", "meaning": "ලාඞගලී, නියඟලා", "category": "plant" },
    { "word": "ලිහිල කොළ", "meaning": "ඉල්ල කොළ", "category": "plant" },
    { "word": "ලිනියන්", "meaning": "තද ඇඹුලකින් යුත් ගෙඩි හටගන්නා අඹිල ගණයට අයත් ගසක්", "category": "plant" },
    { "word": "ලුංග", "meaning": "ලප්නාරම්, ඇඹුල්දෙබම් ගස", "category": "plant" },
    { "word": "ලුක්ෂුර", "meaning": "එන්සාල්", "category": "plant" },
    { "word": "ලුණඹු", "meaning": "ලුණුදිය", "category": "plant" },
  
    // --- පිටුව 414 ---
    { 
        "word": "ලුණුකැටියාවැල්", 
        "scientific": "Cocculus Villosus",
        "meaning": "Cocculus Villosus- මෙය යාපනය ත්‍රිකුණාමලය ආදි වැලි සහිත මුහුදුබඩ ප්‍රදේශ වල වැවෙන දියමිත්ත පවුලට අයත් වැලකි. මේ වගියේ කොළ කුඩා රූකඩ කොළ වැනි අළු පාටින් යුක්ත ය. දියමිත්ත වලට වඩා මස සහිත ය.\n\nදියමිත්ත - ලුණුකැටියා වැල් දෙවගයම එක තැන තියා බැලුව හොත් පෙනෙන්නේ සිංහල පුවක් සහ රට පුවක් දෙවගය අතර ඇති වෙනස වැනිකි. ලුණුකැටියා - දිය මිත්ත පවුලේ ප්‍රමාණයෙන් විශාල වගිය වන බව කිව හැකි යි. \"පාඨා වෙනුවට දිය මිත්ත ගෑණීම වරද ය. ඒ වෙනුවට ගත යුත්තේ ලුණුකැටියා වැල් ය\" යන කියමනෙහි ඇති සත්‍යයක් නැත. මේ දෙවගයම ගුණයෙන් සමාන බැව් විශේෂඥ මතය හෙයිනි. එම නිසා පාඨා වෙනුවට මේ දෙවගයෙන් ලැබෙන දෙයක් ගෑණීම සුදුසු බැව් කියමි.\n\nපාඨා අපේ දේශීය වෙදකමේ නොයෙක් ඖෂධ යෝග සමග යෙදී ඇත. විශේෂයෙන් පිළිස්සුම්, සර්ප විෂ, උපදංශ, (පරංගි) සමාජ රෝග හා ලිංගික රෝග පිළිබඳ ඇතිවන වේදනා සන්සිඳවීම සඳහා ආලේප කිරීමට ද පාඨා කොළ ප්‍රයෝජන වත් ය.", 
        "category": "plant",
        "image": "img_413_lunukatiyawel.jpg"
    },
    { "word": "ලුණු පස", "meaning": "සවිඳ, සුවස, බලල්, කාච, මුදු යනු ලුණු පස යි.", "category": "mineral" },
    { "word": "ලුණු මාල්", "meaning": "ලුණු මස්", "category": "food" },
    { 
        "word": "ලුණුවරණ ගස", 
        "scientific": "Crataeva Religiosa",
        "meaning": "Crataeva Religiosa- ලුණුවරණ - වරුණ (අශ්මරිඝන). මෙහි කොළ කොබ්බෑ කොළ වලට සමානය. එක නැටියේ කොළ තුන බැගින් පිහිටා තිබේ. ගසේ කොළ සියල්ලම අවුරුදු පතා වැටී ගස ඉපලක් මෙන් වෙයි. ඉන් පසු අතු අග සුදු පාට මල් පොකුරු හට ගනියි. මේ ගසේ අතු ලුණු පුපුරා මෙන් වහා බිඳෙයි.\n\nමෙහි සාරය දේශීය වෙදකමේ නොයෙක් ඖෂධ යෝග වලට ඇතුළත් ව තිබේ. එයින් අශ්මරී හා මුත්‍රාශය පිළිබඳ රෝග ප්‍රධාන ය. මෙය ශරීරයේ ලේ භේදනයෙහි ලා මහත් ක්‍රියාකාරී බලයක් ඇති ඖෂධයකි.", 
        "category": "plant",
        "image": "img_414_lunuwarana.jpg"
    },



    // --- පිටුව 415 ---
    { "word": "ලුනඹ", "meaning": "මුහුදු වතුර, (කරදිය)", "category": "liquid" },
    { "word": "ලුප් ඉදිරු", "meaning": "උඳුගොව්වා", "category": "plant" },
    { "word": "ලුපුල්", "meaning": "පොල්", "category": "plant" },
    { "word": "ලුලහ", "meaning": "හත් අවුරුදු ලුණු", "category": "mineral" },
    { "word": "ලුහුනු-ලූනු", "meaning": "(රතු ලූනු, සුදු ලූනු, රට (ලොකු) ලූනු යයි ලූනු වගී කීපයකි)", "category": "plant" },
    { "word": "ලුහුල්-ලුල්ලු", "meaning": "(මුහුල් මත්ස්‍යයෝ, වයස් ගත වූ ලුලාට කළු මඟ යයි කියති)", "category": "animal" },
    { "word": "ලූතා", "meaning": "මකුළුවා, යොන්තුඹ", "category": "plant" },
    { "word": "ලූතා විෂ", "meaning": "දිවි මකුළු විෂ", "category": "treatment" },
    { "word": "ලූතිකා", "meaning": "මකුළුවා", "category": "animal" },
    { "word": "ලූනල", "meaning": "කරවැල් විෂට ගන්නා කුඩා ලූනු අල වැනි අල ඇති පලා වගියක්", "category": "plant" },
    { "word": "ලූනල අල", "meaning": "වල් ලූනු", "category": "plant" },
    { "word": "ලූල", "meaning": "ජවනාර්න්", "category": "plant" },
    { "word": "ලෙඛ්‍යච්ඡද", "meaning": "තල් ගස", "category": "plant" },
    { "word": "ලෙඛ්‍යදල", "meaning": "තල් ගස", "category": "plant" },
    { "word": "ලෙඛ්‍ය පත්‍රක", "meaning": "කර ගස (තල් ගස)", "category": "plant" },
    { "word": "ලෙඛ", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ලෙබණ", "meaning": "ගම්මිරිස්", "category": "plant" },
    { "word": "ලෙඛන", "meaning": "තුප්පතු, මිරිස්", "category": "plant" },
    { "word": "ලෙඛන පත්‍ර", "meaning": "තල්ගස, තුප්පතු", "category": "plant" },
    { "word": "ලෙබු", "meaning": "දෙහි ගස", "category": "plant" },
    { "word": "ලෙතිකා", "meaning": "ලේනිය පලා", "category": "plant" },
    { "word": "ලෙයි", "meaning": "ලේල්ල", "category": "plant" },
    { "word": "ලෙල", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ලෙවන්", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "ලෙහ", "meaning": "ලප්නාරම්", "category": "plant" },
    { "word": "ලෙහා", "meaning": "තලප, (ලේහ)", "category": "food" },
    { "word": "ලෙහ්‍යා", "meaning": "තලප (ලේහ)", "category": "food" },
    { "word": "ලේ", "meaning": "ලේය (රුධිර)", "category": "anatomy" },
    { "word": "ලේඅතීසාර", "meaning": "රක්තාතිසාර රෝගය", "category": "treatment" },
    { "word": "ලේගියම්", "meaning": "මත් බව ඇති කරණ ලේහ ද්‍රව්‍යයක්", "category": "treatment" },
    { "word": "ලේ පාවන", "meaning": "ලේ අතීසාරය", "category": "treatment" },
    { "word": "ලේමාලේ", "meaning": "ස්ත්‍රීන්ට වැළඳෙන මාලේ(ප්‍රදර=කිලිමාලේ)රෝගය", "category": "treatment" },
    { "word": "ලේවැන්න", "meaning": "කැපුන් කිරිය", "category": "plant" },
    { 
        "word": "ලේවැරැල්ල", 
        "scientific": "Eupatorium Ayapana",
        "meaning": "Eupatorium Ayapana-අයියා පාන (බෙංගාලි). රට බිලිං හෝ වැරණියා කොළ වලට මඳක් සමාන මුළු නිවාන්න මෙන් බිම දිගේ මුල් අල්ලා දුවන පඳුරු වගියකි. මෙහි රත් පාට කොළ - නැටි සහ දඬු ඇති වගිය ලේවෑරැල්ල නමින් හැඳින් වේ. මේ වගියට ම අයත් එළ පාට දඬු - කොළ හා නැටි ඇති තවත් වගියක් ද තිබේ.\n\nමෙය ප්‍රංශය ජන්ම භූමිය කොට ඇති පැලෑටියකි. අයාපාන-අයියාපාන යනු විදේශීය නාමයෝ යි. මේ පැලෑටියේ ලක්‍ෂණ හා වැවෙන ස්වභාවයත් සලකා මෙයට ලේවෑරැල්ල යන සිංහල නාමය තබා තිබේ මෙය දහඩිය උපදවන රක්තාතිසාර නාශක ඖෂධයකි. අපරදිගින් පෙර දිගට මේ පැලෑටිය බෝවී වැඩි කල් ගතවී නැත. එහෙත් දැනට ලංකාව ඇතුළු ඉන්දියා - ජාවා යන රට වල මෙය විශාල ලෙස පැතිර ගොස් තිබේ.", 
        "category": "plant",
        "image": "img_415_lewaralla.jpg"
    },

    // --- පිටුව 416 ---
    { "word": "ලොකප්‍රිය", "meaning": "මඟ දඹ කලත්", "category": "plant" },
    { "word": "ලොකෙශ", "meaning": "රසදිය", "category": "mineral" },
    { "word": "ලොවක", "meaning": "කෙසෙල් ගස, මුරුවා වැල", "category": "plant" },
    { "word": "ලොචන", "meaning": "ඇස", "category": "anatomy" },
    { "word": "ලොච මස්තක", "meaning": "මොණර කුඩුම්බිය", "category": "plant" },
    { "word": "ලොප්සුඹුළු / ලොප්සුඹුලු", "meaning": "ලොත්සුඹුලු", "category": "plant" },
    { "word": "ලොඹි", "meaning": "ගොරක ගෙඩියේ මදය", "category": "plant" },
    { "word": "ලොස්‍යා", "meaning": "කෙල ගස", "category": "plant" },
    { "word": "ලොණ", "meaning": "ලුණු", "category": "mineral" },
    { 
        "word": "ලොණසෝවීර රසය", 
        "meaning": "ලුණු කාඩි = (මෙය උදර වාතාබාධයට බුදුරජානන් වහන්සේ විසින් නියම කරණ ලද ඖෂධයෝගයකි. ශුද්ධ කළ යව සහල් සවිඳ ලුණු සමග ඇල් දියෙහි බහා මැටි බඳුනක ලා අඹය ගසා දෙසතියක් පොළොවෙහි වළලා තබා පෙරා ගත්තා (කාඩි) ජලය.", 
        "category": "liquid" 
    },
    { "word": "ලොණා", "meaning": "හින් ඇඹුලැඹිලිය", "category": "plant" },
    { "word": "ලොණී", "meaning": "ගෙද, ගෙදපලා", "category": "plant" },
    { 
        "word": "ලොත් සුඹුළු", 
        "scientific": "Melaleuca Lucabendron",
        "meaning": "Melaleuca Lucabendron- ලොත් සුඹුළු - ලොබු යයි වගී දෙකකි. මේ ඡායා රූපයෙන් දැක්වෙන්නේ ලොත් සුඹුළු ගසකි. මෙය ගම්මිරිස් කොළ වැනි සිහින් දිග කොළ ඇති සුඹුළු වැනි පොතු ගැලවී යන ගුරු පාට කඳකින් යුත් විශාල ගසකි. ලොත් සුඹුළු නමින් ලංකාවේ විකිණීමට තිබෙන්නේ මේ ගසේ සුඹුළු යි. ඉන්දියාවේ ඇතැම් ප්‍රදේශ වල මෙය ලොබු වෙනුවට ගන්නා අතර වෙනත් ප්‍රදේශ වල විදුරු බබු - පිහත්-කෝප්ප ආදිය පටවා (පැක් කර) යැවීමේ දී ආරක්‍ෂාව පිණිස දමන පිදුරු වෙනුවට පාවිච්චි කරති.\n\nලොබු වෙනුවට මේ සුඹුළු ගෑණීම හරි නැත. ලොබු සුඹුළු සහිත ගසක් නොව කපු පොතු වැනි ඝණ පොතු වලින් යුත් (Symplocos Racemosa) යන ලැටින් නාමයෙන් හැඳින්වෙන ගස් වගියයි. දැනට මේ වගියේ පොතු ලංකාවේ බෙහෙත් බඩු කඩවල තිබේ. ලොත්සුඹුළු කියා ඉල්ලූ විට ඉහත සඳහන් සුඹුළු ත්, ලොබු කියා ඉල්ලූ විට මේ පොතු වගිය ත් ලබාගත හැක.\n\nලංකාවේ තිබෙන බෝඹු ගස ද ලොබු ගණය ට අයත් ගසකි. ලොබු පොතු ලබා ගන්ට බැරි වූ විට ඒ වෙනුවට ප්‍රතිනිධි වශයෙන් බෝඹු පොතු ගෑණීම සුදුසු බැව් කියමි. අපේ රටේ පැරණි දේශීය වෛද්‍යවරු ලොබු වෙනුවට බෝඹු පොතු මෙන් ම ලුණුවරණ පොතු ද රැගෙන තිබෙන බව පැරණි වට්ටෝරු වලින් පෙනේ.\n\nලොබු පොතු, අතිසාර, ජ්වර, ලාදුරු යන රෝග වලට ත් සෙම් නැසීමට හා දත් මුල් ශක්තිමත් කිරීමට ත් ගන්නා ඖෂධ යෝග වලට ඇතුලත් කර තිබේ.\n\nඉන්දියානුවෝ මේ ගසෙන් ලබාගන්නා සායමක් නලලෙහි තිලක තැබීම සඳහා පාවිච්චි කරති. ඒ නිසා ලොබු වලට තිලක යන අපර නාමයක් ද ලැබී තිබේ.", 
        "category": "plant",
        "image": "img_416_loth_sumbulu.jpg"
    },

    // --- පිටුව 417 ---
    { "word": "ලොද්දආදි ගණය", "meaning": "ලොධ්‍රාදි ගණය", "category": "compound" },
    { "word": "ලොද්දො", "meaning": "ලොත්", "category": "plant" },
    { "word": "ලොද", "meaning": "ලොත් ගස", "category": "plant" },
    { "word": "ලොදරද", "meaning": "ලොත්මල් රේණු, ලොත් සුඹුළු සුණු", "category": "plant" },
    { "word": "ලොද", "meaning": "තල්ආදියෙහි බූරැල්ලුමදය, කෝමාරිකා කොළයෙහි මදය", "category": "plant" },
    { "word": "ලොද්‍රම්", "meaning": "රත් ලොත්", "category": "plant" },
    { "word": "ලොධ්‍ර", "meaning": "ලොත් ගස", "category": "plant" },
    { "word": "ලොධ්‍රද්වය", "meaning": "සුදු හා රතු මල් ඇති ලොත් ගස් දෙවගිය", "category": "plant" },
    { "word": "ලොධ්‍රාදි ගණය", "meaning": "ලොබුද්‍ර (හෙළ, රත් ලොත් දෙවග) ය, කලාදුරු, හෝපලු, කෙසෙල්, සල්, එලවාලුක (එල්වළු = අළු ඇට) කොළොම්, වැල්මදට, ඇත්දෙමට, ඉන්සළු (බෝ) යන මේ ගණය, සෙම් හා මේදස් වියලීම, යෝනි දොෂ දුරු කිරීම, වණ හා සියලු විෂ ත් පහ කරන්නේය.", "category": "compound" },
    { "word": "ලොධ්‍රපිලක", "meaning": "වෙනි වු මොර", "category": "plant" },
    { "word": "ලොධ්‍ර වෘක්‍ෂ", "meaning": "ලුණුවරණ = ලොබු වෙනුවට මෙරට වෙද වරු ලුණු වරණ පොතු ද පාවිච්චි කළ බව පැරණි වට්ටෝරු වලින් පෙනේ.", "category": "plant" },
    { "word": "ලොධ්‍ර ශාලව", "meaning": "හෙළ ලොත්", "category": "plant" },
    { "word": "ලොනත පත්‍රිකා", "meaning": "ලේනිය පලා", "category": "plant" },
    { "word": "ලොන පිණ්ඩ", "meaning": "ලුණුමඩ", "category": "mineral" },
    { "word": "ලොප් සුඹුළු", "meaning": "ලොබු", "category": "plant" },
    { "word": "ලොප්ප්‍ය", "meaning": "දීකිරි, (මිදුණු කිරි)", "category": "food" },
    { "word": "ලොහනියා", "meaning": "මහ මුඩ මහණ", "category": "plant" },
    { "word": "ලොම කර්කට", "meaning": "අසමෝදගම්", "category": "plant" }
];

