// data_79_88.js - පිටු 79 සිට 88 දක්වා සියලුම වචන
const data_extra_79_88 = [
  // --- පිටුව 79 (image_ad4626.png) ---
  {
    "word": "කප්පරවල්ලිය",
    "meaning": "ඉරිවේරිය පැළෑටියට හැම අතින් ම සමාන එයට වඩා තද සුවඳකින් යුත් දිය සිරාව තිබෙන තැන්වල වැවෙන මේ පැළෑටිය ගවයින්ගේ අජීර්ණ රෝගයට නිතර අවශ්‍ය වන නිසා ගම්වැසි හැම දෙනා අතර ම ප්‍රසිද්ධ ඖෂධයකි. ඒ හැර මේ වගිය පීනස, කක්කල් කැස්ස, අපස්මාර, (මිම ස්මෝර්) හා වලිප්පුව ඇතුළු රෝග වලට ප්‍රත්‍යක්ෂ ඖෂධයකි.",
    "category": "plant"
  },
  { "word": "කප්පාසි", "meaning": "කපු", "category": "plant" },
  { "word": "කප්පාසිකා", "meaning": "කැප්පිටියා", "category": "plant" },
  { "word": "කප්පි", "meaning": "නැල් කැබලි", "category": "treatment" },
  { "word": "කප්පිල්", "meaning": "මොණර පිහාටු", "category": "treatment" },
  { "word": "කප්පූර", "meaning": "කපුරු", "category": "plant" },
  { "word": "කපවෙහෙරි", "meaning": "එල කටුවැල්බටු", "category": "plant" },
  { "word": "කපහු", "meaning": "පහුක්", "category": "plant" },
  { "word": "කපර්දිකා", "meaning": "කවඩි, කවඩිබෙල්ලා, ප්‍රස්කර", "category": "treatment" },
  { "word": "කපාටසන්ධිකා", "meaning": "කර්ණරෝග විශේෂයක්", "category": "symptom" },
  { "word": "කපාල", "meaning": "හිස්කබල, කුෂ්ඨය", "category": "symptom" },
  { "word": "කපාලශූල", "meaning": "හිසරුදාව, කුෂ්ඨ රෝගයක්", "category": "symptom" },
  { "word": "කපාලිකා", "meaning": "දන්ත රෝගයක්", "category": "symptom" },
  { "word": "කපාලී", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කපි", "meaning": "ඇඹුල් කපු, ඇඹුල්, රන් සඳුන්, තූරක්නෙල්, කසඹිලියා", "category": "plant" },
  { "word": "කපිකච්ඡු", "meaning": "වඳුරු මෑ, කසඹිලියා", "category": "plant" },
  { "word": "කපිකර්ණිකා", "meaning": "අඳුරිය, ඇඹුල් කපු", "category": "plant" },
  { "word": "කපිකා", "meaning": "නික, නිල්වන් මල් ඇති නික", "category": "plant" },
  { "word": "කපිකේතන", "meaning": "කුඹුක්, (අර්ජුන)", "category": "plant" },
  { "word": "කපිගන්ධිකා", "meaning": "ගජතිප්පිලි", "category": "plant" },
  { "word": "කපිචකුඩල", "meaning": "තූරක්නෙල්", "category": "plant" },
  { "word": "කපිමුඛා", "meaning": "ඇම්බරෙල්ලා ගස", "category": "plant" },
  { "word": "කපිමුඛී", "meaning": "ඇම්බරෙල්ලා ගස", "category": "plant" },
  { "word": "කපිජ", "meaning": "තූරක්නෙල්", "category": "plant" },
  { "word": "කපිජ්‍ය", "meaning": "කිරිපලු, කිරිපලු ගස", "category": "plant" },
  { "word": "කපිජ්වලක්කා", "meaning": "එලවාලුක, (අඹ ඇට)", "category": "plant" },
  { "word": "කපිඤ්ජල", "meaning": "ගිවුල් පත්, උඳුකා, ඇලකිරිය", "category": "plant" },
  { "word": "කපිඤ්ජලා", "meaning": "අඳුනලා, ගිවුල්, (ගිවුලු)", "category": "plant" },
  { "word": "කපිත්ත", "meaning": "එලවාලුක, වන්සාල්", "category": "plant" },
  { "word": "කපිත්තපත්‍රී", "meaning": "ගිවුලු පල", "category": "plant" },
  { "word": "කපිත්‍ථ", "meaning": "දිවුල්, (ගිවුලු)", "category": "plant" },
  { "word": "කපිත්‍ථඵල", "meaning": "දිවුල්, (ගිවුලු)", "category": "plant" },
  { "word": "කපිත්‍ථපත්‍රී", "meaning": "අඹ වගයක්", "category": "plant" },
  { "word": "කපිත්‍ථපර්ණී", "meaning": "කරල් සැබෝ, අඳුනලා, සුදු අක්මැල්ල", "category": "plant" },
  { "word": "කපිනා", "meaning": "ගිවුලු", "category": "plant" },
  { "word": "කපිනාමු", "meaning": "අඹ වගයක්", "category": "plant" },
  { "word": "කපිනායික", "meaning": "කරල් සැබෝ, අඳුනලා, සුදු අක්මැල්ල", "category": "plant" },
  { "word": "කපිනෙටා", "meaning": "ගිවුලු", "category": "plant" },
  { "word": "කපිනෙත්‍රා", "meaning": "වඳුරු මෑ, සැබෝ", "category": "plant" },
  { "word": "කපිපට්ටි", "meaning": "රන් ගොකටු, රතු සැබෝ", "category": "plant" },
  { "word": "කපිප්‍රිය", "meaning": "දිවුලු, (ගිවුල්) ඇම්බරෙල්ලා, අඹ", "category": "plant" },
  { "word": "කපිමුඛ", "meaning": "ඇම්බරෙල්ලා", "category": "plant" },
  { "word": "කපිරස", "meaning": "තූරක්නෙල්", "category": "plant" },
  { "word": "කපිරසායස", "meaning": "ඇම්බරෙල්ලා ගස", "category": "plant" },
  { "word": "කපිරෝමන්", "meaning": "වඳුරු මෑ, ගම්මිරිස්, රුතැණිය, (වල්මොලඟු)", "category": "plant" },
  { "word": "කපිරෝමඵල", "meaning": "දිවුල්, ගිවුලු", "category": "plant" },
  { "word": "කපිල", "meaning": "රුතැණිය, එන්සාල්, කවඩු දන්ත", "category": "plant" },
  { "word": "කපිලී", "meaning": "ඇත් පගපුල්", "category": "plant" },
  { "word": "කපිල", "meaning": "වඳුරු මෑ, ඇවට්ඨිය, තූරක්නෙල්, රුතැණිය, (වල්ගා මිරිස්)", "category": "plant" },
  { "word": "කපිලකේතු", "meaning": "කොමඩු, පුහුල්", "category": "plant" },
  { "word": "කපිලවක්තු", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "කපිලවක්තුකා", "meaning": "ඇඹුල් කපු", "category": "plant" },

  // --- පිටුව 80 (image_ad4362.png) ---
  { "word": "කපිලවක්ත්‍රී", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "කපිලවල්ලී", "meaning": "ගජතිප්පිලි", "category": "plant" },
  { "word": "කපිලශාසපා", "meaning": "රන්වන් ඇවට්ඨිය", "category": "plant" },
  { "word": "කපිලා", "meaning": "ඇවට්ඨිය, පිත්තල, තූරක්නෙල්, කොමඩු", "category": "plant" },
  { "word": "කපිලාක්‍ෂි", "meaning": "රන්වන් ඇවට්ඨිය", "category": "plant" },
  { "word": "කපිලා ඵල", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "කපිලාරේචක", "meaning": "කිඹුල්වන් කලා", "category": "plant" },
  { "word": "කපිලෝත්පල", "meaning": "නැල්කසඹිලියා", "category": "plant" },
  { "word": "කපිලෝමන්", "meaning": "රුතැණිය, (මල් ගා මිරිස්)", "category": "plant" },
  { "word": "කපිලෝමඵල", "meaning": "ඇලකසඹිලියා, වඳුරු මෑ", "category": "plant" },
  { "word": "කපිලෝල", "meaning": "රුතැණිය", "category": "plant" },
  { "word": "කපිලෝහ", "meaning": "පිත්තල", "category": "treatment" },
  { "word": "කපිවක්ත්‍රා", "meaning": "කඹ", "category": "plant" },
  { "word": "කපිවදනා", "meaning": "ඇම්බරෙල්ලා", "category": "plant" },
  { "word": "කපිවල්ලි", "meaning": "ගජතිප්පිලි, (ඇත් වගපුල්)", "category": "plant" },
  { "word": "කපිවාසි", "meaning": "තුත්තුලිය", "category": "plant" },
  { "word": "කපිෂ්ඨ", "meaning": "කිරිපලු, ගිවුලු, (දිවුල්)", "category": "plant" },
  { "word": "කපිහ", "meaning": "යොනොමු වැල්, තූරක්නෙල්", "category": "plant" },
  { "word": "කපි ශීර්ෂිකා", "meaning": "හිඟුල්, සාදිලිංගම්", "category": "treatment" },
  { "word": "කපිර්‍ෂ", "meaning": "කිරිපලු රුක", "category": "plant" },
  { "word": "කපිතනක", "meaning": "දැරු හරිද්‍රා, හෙලසබු, මහරි", "category": "plant" },
  { "word": "කපිතන", "meaning": "කොකුම්, ගෑබුබ, කිවුලු, මහරි, මදපිය, බෝගස, කිරිපලු, හෙලසබු, ඇම්බරෙල්ලා", "category": "plant" },
  { "word": "කපිතන", "meaning": "බුනුග, නුත්පුලිල, කොකුම්", "category": "plant" },
  { "word": "කපිතඵල", "meaning": "ගිවුලු ගස", "category": "plant" },
  { "word": "කපිෂ්ට", "meaning": "කිරිපලු, ගිවුලු", "category": "plant" },
  { "word": "කපු", "meaning": "ඇඹුල් කපු, මහ කපු", "category": "plant" },
  {
    "word": "කපුකිනිස්ස (කකුළ්)",
    "scientific": "Hibiscus Abelmoschus",
    "meaning": "මෙහි කොළ-මල්-ගෙඩි හා ඇට යෑම අතින් ම නාපිරින්ත්ත වැලේ කොළ-මල්-ගෙඩි හා ඇට වලට සමාන ය. එහෙත් නාපිරින්ත්ත වැල මෙන් මේ වර්ගය සිහින් ව දිගට ඇදී යන ගතියක් නැත. තිබුටු වැනි වඩා දිගට නො දුවන පඳුරු විශේෂයකි. මනා සුවඳකින් යුත් මේ වර්ගයේ ඇට දේශීය වෙදකමේ උසස් ඖෂධයකි. පස්පලවතින් යුත් බුලත් විටට ගන්නා සුගන්ධ ද්‍රව්‍යවලින් ද එකකි.",
    "category": "plant"
  },

  // --- පිටුව 81 (image_ad433f.png) ---
  { "word": "කපුගෙඩි", "meaning": "කපුගෙරි, (කපුගෙඩියේ මැල කටුව=නෙරිය)", "category": "plant" },
  {
    "word": "කපුරු (කර්පූර)",
    "scientific": "Cinnamomum Camphora",
    "meaning": "අපේ පොත්වල පෙන්වා දී තිබෙන පරිදි කපුරු - අමු කපුරු යයි කපුරු වර්ග දෙකකි. මේවා ගස් වර්ග දෙකකින් ලබා ගන්නා දෙවර්ගයකි. එයින් කපුරු (Cinnamomum Camphora) සිනමෝමුම් කාම්පෝරා නම් ගසේ කඳෙන් ලබාගන්නා වර්ගයකි. අමුකපුරු (Dryobalanops Aromatica) ඩ්‍රියෝ බලානප්ස් ඇරෝමැටිකා නැමති බෝර්නියෝ සහ සුමාත්‍රා යන රටවල වැවෙන ගස් වර්ගයෙන් ස්වාභාවිකව ලැබෙන ද්‍රව්‍යයකි. කපුරු දේශීය වෙදකමේ තෙල්-බේත්-කල්ක-ගුලි-මෝදක ආදිය සඳහා බෙහෙවින් ම අවශ්‍ය ඖෂධයකි. මෙය කාමෝද්දීපනය කරන රසායන ද්‍රව්‍යයකි. පස්පලවතින් යුත් බුලත් විටට ද මෙය ඇතුළත් කර තිබෙන්නේ කාමෝද්දීපනය-විෂනාශනය-දත් පණුවන් නොකෑම-මුඛ සුගන්ධය ආදී බොහෝ කරුණු සලකා ගෙනය. මෙය ඇලෙන ගතියෙන් යුත්, කටුක තිත්ත රසැති, තියුණු සුවඳක් ඇති, ඇසට හිතකර, පිපාසය නැති කරන, වාතය හා වේදනා නාශක ගුණයෙන් යුක්තය.",
    "category": "plant"
  },
  { "word": "කපෝත", "meaning": "අස්වාන්ත, සුවසලුළු", "category": "treatment" },
  { "word": "කපෝතක", "meaning": "අඳුන්, සෞවීරාඤ්ජන", "category": "treatment" },
  { "word": "කපෝතවක්ත්‍රා", "meaning": "කාවැට්ටු මාසය", "category": "plant" },
  { "word": "කපෝතවල්ලී", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "කපෝතචුච්ඡු", "meaning": "අස්වාන්ත", "category": "treatment" },
  { "word": "කපෝතවප්‍රා", "meaning": "කළුකම්මේරිය", "category": "plant" },

  // --- පිටුව 82 (image_ad4308.png) ---
  { "word": "කපෝත පර්ණිකා", "meaning": "කෝවක්කා, කැසිරි, පුත්තුවිල", "category": "plant" },
  { "word": "කපෝත මණි", "meaning": "සිනින් එන්සාල්", "category": "plant" },
  { "word": "කපෝත මේධා", "meaning": "බුත්තුවිල", "category": "plant" },
  { "word": "කපෝත විකෘතී", "meaning": "බැමිනිරිය, බුනු විල", "category": "plant" },
  { "word": "කපෝත වේගා", "meaning": "බැමිනිරිය", "category": "plant" },
  { "word": "කපෝතාභී", "meaning": "පඹුටුවැල්-බුනු විල", "category": "plant" },
  { "word": "කපෝතාඤ්ජන", "meaning": "අඳුන්", "category": "treatment" },
  { "word": "කපෝතිකා", "meaning": "සිටිවට, කරේට, ඇලකෝමා", "category": "plant" },
  { "word": "කපාල", "meaning": "කළු ගොල, කකමුල", "category": "symptom" },
  { "word": "කඵ", "meaning": "සෙම, රසකාල්ල, ගිවුලු, අතිසාරය", "category": "symptom" },
  { "word": "කඵ ගණ්ඨ", "meaning": "ගෙල සෙම පිරීම", "category": "symptom" },
  { "word": "කඵදම", "meaning": "ලොච්චු ගස (පහරුප්)", "category": "plant" },
  { "word": "කඵ නාලී", "meaning": "දත් මුල්කි උපදනා රෝගයක්", "category": "symptom" },
  { "word": "කඵර්පණ", "meaning": "කලාදුරු", "category": "plant" },
  { "word": "කඵ වර්ධක", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "කඵ වාතාන්විත", "meaning": "මුගුණුවැන්න", "category": "plant" },
  { "word": "කඵ විරෝධි", "meaning": "ගම්මිරිස්, කපුරු", "category": "plant" },
  { "word": "කඵ විරෝධීන්", "meaning": "ගම්මිරිස්, කපුරු", "category": "plant" },
  { "word": "කඵා", "meaning": "රසකාල්ල, ලපකාල්ල", "category": "plant" },
  { "word": "කඵාන්තක", "meaning": "සිතියා ගස", "category": "plant" },
  { "word": "කඵාශන", "meaning": "මිරිස්, ගම්මිරිස්, දුරු", "category": "plant" },
  { "word": "කඵාරි", "meaning": "ඉඟුරු, සිද්ධිගුරු", "category": "plant" },
  { "word": "කඵාත්සලෝභා", "meaning": "සෙම ශීන්තාරය", "category": "symptom" },
  { "word": "කඵෝදර", "meaning": "සෙමෙන් උපදනා උදර රෝගයක්", "category": "symptom" },
  { "word": "කබලිකා", "meaning": "බැලිද වැල, ගජ බැලිද වැල", "category": "plant" },
  { "word": "කබන්‍ධ", "meaning": "ගිවුල්", "category": "plant" },
  { "word": "කබන්‍ධ", "meaning": "ගොම", "category": "treatment" },
  { "word": "කබපිල", "meaning": "මොණරවිල්", "category": "plant" },
  { "word": "කබර", "meaning": "පැපිලිය, පත් පාඩගම්, පේලා", "category": "plant" },
  { "word": "කබරමනි", "meaning": "ඇසිරිගල්", "category": "treatment" },
  { "word": "කබරස", "meaning": "කබරොස්සා වැල්", "category": "plant" },
  { "word": "කබරි", "meaning": "කබෙලු, වේලා, පැපිලිය", "category": "plant" },
  { "word": "කබරෝ", "meaning": "පැපිලිය, (පත්පාඩගම්)", "category": "plant" },
  {
    "word": "කබරෝස",
    "meaning": "විස රහ කළු පිනට ප්‍රත්‍යක්ෂ තද ගතියකින් යුත් අලයක් ඇති කටු සහිත වැලකි. මෙය විෂ වෙන රෝග වලට ද ප්‍රත්‍යක්ෂ බෙහෙතකි.",
    "category": "plant"
  },
  { "word": "කබල", "meaning": "කලන් තුන", "category": "treatment" },
  { "word": "කබලග්‍රහ", "meaning": "කලන් තුන", "category": "treatment" },
  { "word": "කබලිකා",
    "meaning": "වත බැඳි පටියට තත්, බෙහෙතත් අතර තබන (අත් නිකාරා ආදී) කොලු වැස්ම",
    "category": "treatment"
  },
  { "word": "කබලු", "meaning": "රොටී, ආප්ප", "category": "treatment" },
  { "word": "කබලුදාස්නා", "meaning": "වැල්-කබරොස්සා වැල්", "category": "plant" },
  { "word": "කබිත්", "meaning": "ගිවුලු ගස", "category": "plant" },
  { "word": "කබුප්පෘ", "meaning": "ඇත් කිරිඳ", "category": "plant" },
  { "word": "කබුදන", "meaning": "කුඹුක් ගස", "category": "plant" },
  { "word": "කම්", "meaning": "වතුර", "category": "treatment" },
  { "word": "කම්දද", "meaning": "මෝරු", "category": "treatment" },
  { "word": "කම්ප", "meaning": "වතුර", "category": "treatment" },
  { "word": "කම්පවායු", "meaning": "වාත රෝග විශේෂයක්", "category": "symptom" },
  { "word": "කම්පිල්ල", "meaning": "උග්‍රරස්ස, කම්බේලඟ, කරඳ, හම්බිල, (කම්බිල්ල) සුදු පුස්කරාමු", "category": "plant" },
  { "word": "කම්පිල්ලක", "meaning": "හම්බිල්ල, දේවදාලිය", "category": "plant" },
  { "word": "කම්පිල්ලමාලක", "meaning": "බූනාල් වේ සෙක්", "category": "plant" },
  { "word": "කම්පිල්ල", "meaning": "ගජතිප්පිලි", "category": "plant" },
  { "word": "කම්බලා", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "කම්බෙල", "meaning": "ගෙරිඅඟ, වතුර", "category": "treatment" },
  { "word": "කම්බු", "meaning": "සක්බෙල්ලා", "category": "treatment" },
  { "word": "කම්බුක", "meaning": "කුඩා සක්බෙල්ලා", "category": "treatment" },
  { "word": "කම්බුකා (පොටා)", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "කම්බුකිනි", "meaning": "ශීර්ෂ වාක්‍යස (මහරි ගස)", "category": "plant" },

  // --- පිටුව 83 (image_ad42e4.png) ---
  { "word": "කම්බු පුෂ්ප", "meaning": "අධනගිරිය", "category": "plant" },
  { "word": "කම්බු මාලිනී", "meaning": "අබාර, (අධනගිරිය)", "category": "plant" },
  { "word": "කම්බු ධර", "meaning": "සක්, (සක්ගෙඩි)", "category": "treatment" },
  { "word": "කම්බු", "meaning": "සැවැන්න", "category": "plant" },
  { "word": "කම්හාරි", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කම්මලකෝති", "meaning": "වැක්කිරි වැල්", "category": "plant" },
  { "word": "කම්හෝල්", "meaning": "මීවෙලත්ත", "category": "plant" },
  { "word": "කම්මී", "meaning": "හැන්ද", "category": "treatment" },
  { "word": "කම්සස", "meaning": "මූරුවා", "category": "plant" },
  { "word": "කම්බල්", "meaning": "නුත්පුලිල, මුගුණුවැන්න", "category": "plant" },
  { "word": "කම්බලකර්ණ", "meaning": "පුමිල රුක", "category": "plant" },
  { "word": "කම්නි", "meaning": "නොපොලු ගස, කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "කමනි", "meaning": "නුප්පමේනිය", "category": "plant" },
  { "word": "කමල", "meaning": "රත්-සුදු නෙලුම් දෙවර්ගය", "category": "plant" },
  { "word": "කමලකා", "meaning": "සෝබාරු, කොල්ලොත් කොළ", "category": "plant" },
  { "word": "කමලකේසර", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "කමලච්ඡන්ද", "meaning": "පියුම් කෙසර", "category": "plant" },
  { "word": "කමල දල", "meaning": "කොල්ලොත් කොළ", "category": "plant" },
  { "word": "කමල නාල", "meaning": "කොල්ලොත් කොළ", "category": "plant" },
  { "word": "කමල පත්‍ර", "meaning": "නෙලුම් දඬු", "category": "plant" },
  { "word": "කමල වීර්‍ය", "meaning": "නැමල් රේණු, කුරළු පොතු, කොල්ලොත්කොළ", "category": "plant" },
  { "word": "කමලා", "meaning": "නෙලුම් ඇට", "category": "plant" },
  { "word": "කමලෝත්තරා", "meaning": "කම්පිල්ල, කටු වෙලඟ", "category": "plant" },
  { "word": "කමිල්", "meaning": "සෙන්දිරික්කා, වතුර", "category": "plant" },
  { "word": "කමිල් පත්", "meaning": "කොල්ලොත්කොළ, නෙලුම්, මානෙල්, සින්සගල්", "category": "plant" },
  { "word": "කමිල් වන්", "meaning": "කොල්ලොත්කොළ", "category": "plant" },
  { "word": "කමිකා", "meaning": "නෙලුම් රේණු, නෙලුම් කෙමිය, නෙලුම් පත්‍ර", "category": "plant" },
  { "word": "කමිට්ටා", "meaning": "පුවක්", "category": "plant" },
  { "word": "කමිය", "meaning": "දිවුල්", "category": "plant" },
  { "word": "කමුගන්ට්වල්ලායි", "meaning": "පුවක් මල්", "category": "plant" },
  { "word": "කමුකමර්ම", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "කමුසේට්", "meaning": "පුවක්, දෙළුම්", "category": "plant" },
  { "word": "කමුලා", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "කමුස්ස", "meaning": "මූරුවා", "category": "plant" },
  { "word": "කඹ", "meaning": "කිණිහිරි", "category": "plant" },
  { "word": "කඹු", "meaning": "දඹු, රත්රන්", "category": "treatment" },
  { "word": "කඹුලු", "meaning": "කඹු කටුපුවා-වැටකේලු වැල් (රහස් වට්ටෝරුවක සඳහන් බෙහෙතක්)", "category": "plant" },
  { "word": "කයතුල", "meaning": "ගංකසා අල", "category": "plant" },
  { "word": "කයසැට", "meaning": "කහවැලි, අරලු, හීන් එන්සාල්", "category": "plant" },
  { "word": "කයියර්ප්පු", "meaning": "සැවැන්දන, (සැවැන්දරා)", "category": "plant" },
  { "word": "කයියප්පු", "meaning": "ගොල පුවක්, (පොහි පුවක්) වලින් සහ රන් කිණිරිය වලින් නිපදවන කයිපපු දෙවර්ගයකි.", "category": "plant" },
  { "word": "කයියන්තකරෙයි", "meaning": "රන්වන් කිණිරි දිය, කිණිරි", "category": "plant" },
  { "word": "කයිල", "meaning": "කයිලවැල්", "category": "plant" },
  { "word": "කයිරි", "meaning": "මිරිස්, බෙලිගස, කුඩමිරිස් වැල්, හීන් නෙල්ලි", "category": "plant" },
  { "word": "කයිට", "meaning": "කොල අරලු, ගිවුල්, බෙලි, කාඤ්චිවල, අඟිල්", "category": "plant" },
  { "word": "කයිටක", "meaning": "එක්දඹු, කසඹිලියා, කාඤ්චි", "category": "plant" },
  { "word": "කයිටප්‍රියා", "meaning": "නිවිතිවැල්", "category": "plant" },
  { "word": "කයිටක ශාලී", "meaning": "කකුලුසුනු, (කොල අරලු)", "category": "plant" },
  { "word": "කයිටකී", "meaning": "කකුලුසුනු, (කොල අරලු)", "category": "plant" },
  { "word": "කයිටිකා නන්මිනික", "meaning": "බුළු දඹු", "category": "plant" },
  { "word": "කයිටවල්ලී", "meaning": "ඇත් වගපුල්, වතුර මෑ", "category": "plant" },
  { "word": "කයිටාවාස", "meaning": "කකුලුසුනු, දූවගස, කාඤ්චි", "category": "plant" },
  { "word": "කයිටන්වා", "meaning": "කකුලුසුනු (කකුලුසුං)", "category": "plant" },

  // --- පිටුව 84 (image_ad42c4.png) ---
  { "word": "කයිටාවාහ", "meaning": "කකුලුසුනු", "category": "plant" },
  { "word": "කයිටාවන්‍ධ", "meaning": "බෙලි රුක", "category": "plant" },
  { "word": "කයිටිකා", "meaning": "බෙලි, කැකිරි", "category": "plant" },
  { "word": "කයිටිකා ඵල", "meaning": "මෑන් (බැබර) සිනින්මෑන්", "category": "plant" },
  { "word": "කයිටිනී", "meaning": "දුරහරිද්‍රා", "category": "plant" },
  { "word": "කයීට්", "meaning": "ඉඟුල්, කැසිරි, බැබර, නිවි නීනවැල, කොලඅරළු", "category": "plant" },
  { "word": "කර්කට් පල", "meaning": "මෑන් ගෙඩි (බැබර පල)", "category": "plant" },
  { "word": "කර්කකච්ඡු", "meaning": "බෙලි", "category": "plant" },
  { "word": "කර්කකච්ඡු", "meaning": "මෑන් (බැබර)", "category": "plant" },
  { "word": "කර්කඵල", "meaning": "හීන් නෙල්ලි", "category": "plant" },
  { "word": "කර්කභී", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "කර්කරිල", "meaning": "දේවදුරු", "category": "plant" },
  { "word": "කර්කරා", "meaning": "පුසුල්", "category": "plant" },
  { "word": "කර්කවල්ලි", "meaning": "සැබෝ, ඇත් වගපුල්", "category": "plant" },
  { "word": "කර්කය", "meaning": "කරඳ, ලක්, වං ඇපල, මින්බැද්ද, (වෙලිප්පිරිත්ති) කුඹු වෙළඟ, කුරළු පොතු", "category": "plant" },
  { "word": "කර්කයවජ්ජ", "meaning": "එක් ගස", "category": "plant" },
  { "word": "කර්කගදල", "meaning": "ගාටිනිවුල්, දුම්වැල්ල කොච්චිමුල ගස", "category": "plant" },
  { "word": "කර්කගපත්‍රිකා", "meaning": "දුම්වැල්ල", "category": "plant" },
  { "word": "කර්කශා", "meaning": "දියබෙරලිය", "category": "plant" },
  { "word": "කර්කශිකා", "meaning": "ගින්නී, බගනු, වල්බැබර", "category": "plant" },
  { "word": "කර්කාරු", "meaning": "වල්බැබර", "category": "plant" },
  { "word": "කර්කිණී", "meaning": "කොමඩු", "category": "plant" },
  { "word": "කර්කෙටී", "meaning": "වලගසල්, කර ගස", "category": "plant" },
  { "word": "කර්කෝටක", "meaning": "වැල්තුඹ, රේරා, පුහුල්, දේවදාලිය", "category": "plant" },
  { "word": "කර්කෝටකා", "meaning": "කැකිරි, වැල්තුඹ, රේරා, බෙලි ගස, ලක් ගස", "category": "plant" },
  { "word": "කර්කෝටකී", "meaning": "වැටකොළු, කැකිරි", "category": "plant" },
  { "word": "කර්කෝටකී ඵල", "meaning": "දේවදාලි ගෙඩිය, වැටපුහුල්, හීන්ත වැටකොළු", "category": "plant" },
  { "word": "කර්කෝටජ", "meaning": "පුහුල් වැල", "category": "plant" },
  { "word": "කර්කෝටි", "meaning": "වැල්තුඹ, කැකිරි, සිනින් බැබර, රේරා", "category": "plant" },
  { "word": "කර්කෝටිකා", "meaning": "වැල්තුඹ", "category": "plant" },
  { "word": "කර්කෝරි", "meaning": "රේරා", "category": "plant" },
  { "word": "කර්කෝලාස", "meaning": "කකුළු, (කපුකිනිස්ස)", "category": "plant" },
  { "word": "කර්බුර", "meaning": "අරණක්කසා, (ගරංකහ)", "category": "plant" },
  { "word": "කර්වුරකා", "meaning": "හඟුරු මියැලි, සුවඳ කසා, කහ ගස", "category": "plant" },
  { "word": "කර්පුර", "meaning": "බුදි පල", "category": "plant" },
  { "word": "කර්ණ", "meaning": "ඇසල (එරඬු)", "category": "plant" },
  { "word": "කර්ණක", "meaning": "සිනින් මිරි", "category": "plant" },
  { "word": "කර්ණිකා", "meaning": "ඇසල, සිනින් මිරි, මඟ වන්සාල්, කිණිහිරි", "category": "plant" },
  { "word": "කර්ණිකාපී", "meaning": "ඇසල, කිණිහිරිය", "category": "plant" },
  { "word": "කර්ණිකී", "meaning": "කටුකිණිහිරි", "category": "plant" },
  { "word": "කර්ණ කුමි", "meaning": "කන් රෝගයක්", "category": "symptom" },
  { "word": "කර්ණ ගුප්", "meaning": "කාරදු", "category": "treatment" },
  { "word": "කර්ණ ජීරක", "meaning": "හින්දුරු", "category": "plant" },
  { "word": "කර්ණ බු", "meaning": "බෙලි ගස", "category": "plant" },
  { "word": "කර්ණ පුෂ්ප", "meaning": "මූරුවා, නිල්ගිරිනීල්ල", "category": "plant" },
  { "word": "කර්ණ පුර", "meaning": "ඇඹුල්, නිල් මානෙල්, අශෝකා, නන්දි රුක", "category": "plant" },
  { "word": "කර්ණ පුරකා", "meaning": "කොලොම් ගස, මඟුරි, හෝපලු", "category": "plant" },
  { "word": "කර්ණ මෝටා", "meaning": "වෙලා ගස", "category": "plant" },
  { "word": "කර්ණ රාව", "meaning": "දුඟුදු", "category": "symptom" },
  { "word": "කර්ණ ශේඛර", "meaning": "සල් ගස", "category": "plant" },
  { "word": "කර්ණසස්‍රාට", "meaning": "කර්ණ රෝගයක් (කන් පැසවීම)", "category": "symptom" },
  { "word": "කර්ණාඛ්‍ය", "meaning": "සුදු ගිරිනීල්ල", "category": "plant" },
  { "word": "කර්ණාටි", "meaning": "වලා වැන්න", "category": "plant" },
  { "word": "කර්ණා භරණිකා", "meaning": "ඇසල (එරඬු)", "category": "plant" },
  { "word": "කර්ණාරි", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "කර්ණිකා", "meaning": "සිනින් මිරි, ඇසල (එරඬු)", "category": "plant" },
  { "word": "කර්ණිකාර", "meaning": "කිණිහිරි, ඇසල", "category": "plant" },
  { "word": "කර්ණී දයක", "meaning": "කලුවැල්", "category": "plant" },
  { "word": "කර්ණී", "meaning": "කඩුවැල්බටු", "category": "plant" },

  // --- පිටුව 85 (image_ad42a2.png) ---
  { "word": "කර්ණී මත්", "meaning": "ඇසල ගස", "category": "plant" },
  { "word": "කර්ණෝර", "meaning": "දුඟුදු", "category": "plant" },
  { "word": "කර්තිම", "meaning": "පාංශු ලුණු, බලල් ලුණු, රෝම ලුණු, තූරක්නෙල්, ලෝකඩ", "category": "treatment" },
  { "word": "කර්තී බුබ්", "meaning": "බලල් ලුණු", "category": "treatment" },
  { "word": "කර්ද", "meaning": "මඩ", "category": "treatment" },
  { "word": "කර්දම", "meaning": "මඩ", "category": "treatment" },
  { "word": "කර්දමශිකා", "meaning": "සිරිලන්තේක්කු", "category": "plant" },
  { "word": "කර්ද මර්ධ", "meaning": "සිරිලන්තේක්කු", "category": "plant" },
  { "word": "කර්ද මුගු", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "කර්දප්පව", "meaning": "මෝරු", "category": "treatment" },
  { "word": "කර්දු", "meaning": "හිබරම් අල", "category": "plant" },
  { "word": "කර්ප", "meaning": "ගල්පිසැල්", "category": "plant" },
  { "word": "කර්පි", "meaning": "සකුරා", "category": "plant" },
  { "word": "කර්පිකා", "meaning": "කවඩි, වල්කපු", "category": "plant" },
  { "word": "කර්පිර", "meaning": "හුන්තම්, රිදීහුන්තම්, වනු වැල් (මාළු වැල්) දිවුල් ගස, උක් පැණි", "category": "plant" },
  { "word": "කර්පිරා", "meaning": "ගල්පිසැල් ගස", "category": "plant" },
  { "word": "කර්පී රුහ", "meaning": "මුසුප්පතු (ජන්මානික්කම්)", "category": "plant" },
  { "word": "කර්පී සා", "meaning": "හුන්තම්", "category": "plant" },
  { "word": "කර්පී", "meaning": "නොයෙකුත්, රසඳුන්, ඉඟිනි ගස", "category": "plant" },
  { "word": "කර්පිට", "meaning": "රසඳුන්", "category": "treatment" },
  { "word": "කර්පූර", "meaning": "හුන්තම්", "category": "plant" },
  { "word": "කර්පූරක", "meaning": "ඉඟිනි", "category": "plant" },
  { "word": "කර්පූර ගන්‍ධි", "meaning": "සපු, කපු ඇට", "category": "plant" },
  { "word": "කර්පූර තුලසී", "meaning": "කපු, කපු ගස", "category": "plant" },
  { "word": "කර්පූර තෛල", "meaning": "රිදී", "category": "treatment" },
  { "word": "කර්පූර රස", "meaning": "කපුරු, විනකපුරු", "category": "plant" },
  { "word": "කර්පූර වල්ලි", "meaning": "සුවඳකසා, හිඟුරු මියැලි, කපුරු", "category": "plant" },
  { "word": "කර්පූර හරිද්‍රා", "meaning": "මල කොල", "category": "plant" },
  { "word": "කර්පූරා", "meaning": "කපුරු සුවඳැති කහ වෙසෙසක්", "category": "plant" },
  { "word": "කර්පුරිකා", "meaning": "කපුරුනෙල්, ඉරිවේරිය", "category": "plant" },
  { "word": "කර්බර", "meaning": "මල කොල", "category": "plant" },
  { "word": "කර්බිනී", "meaning": "කප්පුවල්ලිය", "category": "plant" },
  { "word": "කර්බුද්ර", "meaning": "හරන්කහ", "category": "plant" },
  { "word": "කර්බුර", "meaning": "ආමගන්ධිහරිද්‍රා (කපුරු කහ)", "category": "plant" },
  { "word": "කර්බුර ඵල", "meaning": "හුන්තම්", "category": "plant" },
  { "word": "කර්බුරා", "meaning": "අත්තන, උක් වෙසෙසක්", "category": "plant" },
  { "word": "කර්බුරු", "meaning": "සවණිකිරි, (රන්කිරි ගොකටු)", "category": "treatment" },
  { "word": "කර්ම", "meaning": "නිල් ගිරිනීල්ල, හෙලපෙතන්, ලෝලු", "category": "plant" },
  { "word": "කර්මකර", "meaning": "හිඟුරපියලි, රත් සිරියල්, කහ ගස", "category": "treatment" },
  { "word": "කර්ම කරී", "meaning": "සාකුරාණ්ඩ වාසය", "category": "plant" },
  { "word": "කර්ම කාරී", "meaning": "රත් පලොල්, වෙලා", "category": "plant" },
  { "word": "කර්මි", "meaning": "රත්රන්, රත් පලොල්", "category": "treatment" },
  { "word": "කර්මි ඵල", "meaning": "කාර් ගස, බුප්පතු", "category": "plant" },
  { "word": "කර්මුල", "meaning": "හුණගස", "category": "plant" },
  { "word": "කර්ම රඝ", "meaning": "බූජන", "category": "treatment" },
  { "word": "කර්මර්", "meaning": "බූජන වැල්", "category": "plant" },
  { "word": "කර්මිකා", "meaning": "හුඟ ගස", "category": "plant" },
  { "word": "කර්මි ශාසී", "meaning": "කාමරංගා ගෙඩි", "category": "plant" },
  { "word": "කර්මුල", "meaning": "කුසතණ, ඊතණ, බට", "category": "plant" },
  { "word": "කර්මාර", "meaning": "කාමරංගා", "category": "plant" },
  { "word": "කර්මාරිකා", "meaning": "උග්රකපුරු", "category": "treatment" },
  { "word": "කර්වර", "meaning": "ගැටනිවුල්", "category": "plant" },

  // --- පිටුව 86 (image_ad426a.png) ---
  { "word": "කර්වරිකා", "meaning": "වරාගස", "category": "plant" },
  { "word": "කර්වදුර", "meaning": "අරණක්කසා (හරංකහ)", "category": "plant" },
  { "word": "කර්වුදරකා", "meaning": "උණුගස, කාමරංගා", "category": "plant" },
  { "word": "කර්ශී", "meaning": "කාමරංගා ගස", "category": "plant" },
  { "word": "කළු", "meaning": "ලෝලු, ලාවුලු, ගිඟුපන්", "category": "plant" },
  { "word": "කළුකා", "meaning": "ගිගුපන් තණ", "category": "plant" },
  { "word": "කළුන්", "meaning": "කොහොබොල්ල", "category": "plant" },
  { "word": "කළුන්", "meaning": "ලෝලු", "category": "plant" },
  { "word": "කළ්‍යාණ", "meaning": "හිඟුරුමියැලි", "category": "plant" },
  { "word": "කළුළු", "meaning": "තුන් කලඳ", "category": "treatment" },
  { "word": "කළවක", "meaning": "තෝර, වටකෝර", "category": "plant" },
  { "word": "කළුිකා", "meaning": "අනසි වාක්‍යය, ගනගස", "category": "plant" },
  { "word": "කර්", "meaning": "කිරි වාක්‍යය, හෙලවද", "category": "treatment" },
  {
    "word": "කර්-කර් ගස",
    "meaning": "මෙය මැලියම් සහිත මුත්‍රකාරක ගසකි. මෙහි කොළ මැල්ලුම කෑමට ගනු ලැබේ. පෝෂණ ගුණය මෙවායේ බෙහෙවින් ඇත. ආහාර දුර්ලභ කාල වලදී මේවා කෑමෙන් ජීවත් වූ මිනිසුන් ගැන පොත පතෙහි සඳහන්ව තිබේ.",
    "category": "plant"
  },
  { "word": "කර්කා", "meaning": "වලඟසල්, දුම්වැල්ල ගස", "category": "plant" },
  { "word": "කර්කද", "meaning": "දෙවවම, කොහොබොල්ල වකුල (මුහුණමල්) කිරිදිවැල් පොල්මල් ඇට", "category": "plant" },
  { "word": "කර්කානාවල්ලි", "meaning": "ගිඳි", "category": "plant" },
  { "word": "කර්කශාල", "meaning": "සිවිය, ඇන්වගපුල්", "category": "plant" },
  { "word": "කර්කාමා", "meaning": "ලක් ගස", "category": "plant" },
  { "word": "කර්කාම", "meaning": "කරවිල, පාණවැස්ස", "category": "plant" },
  { "word": "කර්ච්විරකම", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "කරවජ්ජ", "meaning": "පොල් කැඩිය, උක් වෙසෙසක්", "category": "plant" },
  { "word": "කරවමසින්", "meaning": "කලුදුරු", "category": "plant" },
  { "word": "කරච්ඡ", "meaning": "ගැටනිවුල්, නික", "category": "plant" },
  { "word": "කරජ", "meaning": "නාරන්", "category": "plant" },
  { "word": "කරජා", "meaning": "තේක්ක ගස", "category": "plant" },
  { "word": "කරපොති", "meaning": "සන්නාම, දිවිපසුරු, මල් කරඳ-කරඳ", "category": "plant" },
  { "word": "කරපප්පසි", "meaning": "කරඳ ගස", "category": "plant" },
  { "word": "කරඤ්ජ", "meaning": "මකෙස්සුවක්කා", "category": "plant" },
  { "word": "කරඤ්ජක", "meaning": "මකෙස්සුවක්කා", "category": "plant" },
  { "word": "කරඤ්ජ තෛල", "meaning": "කරඳ, සක්කාව, කුණු කරඳ", "category": "plant" },
  { "word": "කරඤ්ජනය", "meaning": "කරඳ, මගුල්කරඳ", "category": "plant" },
  { "word": "කරඤ්ජ ඵල", "meaning": "තෙකල-කරඳ ඇට තෙල්", "category": "plant" },
  { "word": "කරඤ්ජ පත්‍ර", "meaning": "කුණුකරඳ, සිහිට", "category": "plant" },
  { "word": "කරඤ්ජිකා", "meaning": "දිවුල් ගෙඩි", "category": "plant" },
  { "word": "කරඤ්ජී", "meaning": "ගිවුලු, (දිවුල්)", "category": "plant" },
  { "word": "කරට්", "meaning": "කවුඩකරඳ, මගුල්කරඳ", "category": "plant" },
  { "word": "කරටක", "meaning": "මග කරඳ ගස, කුඹුරු වැල්", "category": "plant" },
  { "word": "කරට", "meaning": "කුකුරුමුවන්, වනුක්, සෙන් දිරික්කා, කරඹ", "category": "plant" },
  { "word": "කරඩිබෙනෙයි", "meaning": "වනුක්", "category": "plant" },
  { "word": "කරණී නානයෙයි", "meaning": "කරඳ", "category": "plant" },
  { "word": "කරණ්ඩ", "meaning": "වලස්තෙල්", "category": "treatment" },
  { "word": "කරණ්ඩ ඵල", "meaning": "සකුරා මැට්ට", "category": "treatment" },
  { "word": "කරත්", "meaning": "සකුර කරඬු, කුකුරුමුවන් කරඬු ගස", "category": "plant" },
  { "word": "කරණී", "meaning": "ගිවුලු ගස", "category": "plant" },
  { "word": "කරතල", "meaning": "තලාගස, ශරීරය", "category": "treatment" },
  { "word": "කරන්ත", "meaning": "මානෙල්, හිබරම්", "category": "plant" },
  { "word": "කරනා උපපු", "meaning": "නෙළුම් අල", "category": "plant" },
  { "word": "කරනාග කොල්ලු", "meaning": "වල්මෑ", "category": "plant" },
  { "word": "කරනග", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කරනිකා", "meaning": "සළුහුණු", "category": "treatment" },
  { "word": "කරබුබාගක", "meaning": "කල්කොල්ලු", "category": "plant" },

  // --- පිටුව 87 (image_ad3fbe.png) ---
  { "word": "කරමාණී", "meaning": "පබ්බාලිය, (පන්පාඩගම්)", "category": "plant" },
  { "word": "කරද", "meaning": "සක්නබ", "category": "treatment" },
  { "word": "කරද ඛණ්ඩිකා", "meaning": "සුදුවැටකේ", "category": "plant" },
  { "word": "කරදු", "meaning": "නිදි, කරඳ", "category": "plant" },
  { "word": "කරදම", "meaning": "ගස්කැලිය", "category": "plant" },
  { "word": "කරනෙයි", "meaning": "කිබරම්", "category": "plant" },
  { "word": "කරනෙත", "meaning": "කඳුරුගස", "category": "plant" },
  { "word": "කරපන්", "meaning": "කිබරම්", "category": "plant" },
  { "word": "කරපට", "meaning": "මානෙල්, කිබරම්", "category": "plant" },
  { "word": "කරපත්‍ර", "meaning": "සෙම් කිරීම නිසා ශරීරයේ සැමතැනම හෝ තැන් තැන්වල හටගන්නා රක්තපැහැ පළු", "category": "symptom" },
  { "word": "කරපත්‍රක", "meaning": "අක්කුපපට්ටා", "category": "symptom" },
  { "word": "කරපත්‍රිකා", "meaning": "කෑකලා", "category": "plant" },
  { "word": "කරපර්ණී", "meaning": "තල", "category": "plant" },
  { "word": "කරපාකයක", "meaning": "පහගි, අත්තානි", "category": "plant" },
  { "word": "කරපිංච", "meaning": "රක්තරුබු, කුකුරු මුවන්, බණ්ඩක්කා", "category": "plant" },
  { "word": "කරමි", "meaning": "කල්කයක වැලි සේ කැකුළුව වැවෙන පදම්", "category": "treatment" },
  { "word": "කරමිල්ලක", "meaning": "කරබෙබිය", "category": "plant" },
  { "word": "කරපුව", "meaning": "මොණර පිහාටු", "category": "treatment" },
  { "word": "කරාබි", "meaning": "කරවිල", "category": "plant" },
  { "word": "කරඹුසා", "meaning": "දෙන්නොක", "category": "plant" },
  { "word": "කරඹු", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කරඹෙයියා", "meaning": "කොමඩු, (පත්තක්කා)", "category": "plant" },
  { "word": "කරබෙල", "meaning": "දික්දුරු", "category": "plant" },
  { "word": "කරභ", "meaning": "කරපිංචාවස, (කරබෙයියා ගස)", "category": "plant" },
  { "word": "කරභඤ්ජිකා", "meaning": "කරබ, වල කටුරොලු", "category": "plant" },
  { "word": "කරභ ප්‍රියා", "meaning": "ගජතිප්පිලි, සුකසා කාපාලි", "category": "plant" },
  { "word": "කරභ වල්ලභ", "meaning": "මහකරද, කුඹුරු වැල", "category": "plant" },
  { "word": "කරහාදනී", "meaning": "වැල්කසඹිලියා, හීන් මෝරගස", "category": "plant" },
  { "word": "කරභාස", "meaning": "දිවුල්, පීයාගස, මෝරගස", "category": "plant" },
  { "word": "කරභී", "meaning": "වැල්කසඹිලියා", "category": "plant" },
  { "word": "කරභාටි", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "කරමා", "meaning": "හුඹ, වැල්හුඹ, ගින්මබ ගස, එලපට රෝ", "category": "plant" },
  { "word": "කරමාක", "meaning": "කවුරුකඩු, කුකුරුමුවන්", "category": "plant" },
  { "word": "කරමාර", "meaning": "පුගුන් ගස", "category": "plant" },
  { "word": "කරමදරි", "meaning": "එලසබෝ", "category": "plant" },
  { "word": "කරමට්ටි", "meaning": "කොටිකන් බැමිල", "category": "plant" },
  { "word": "කරමර්ද", "meaning": "හෙලකරල්සැබ, (සුදු කරල්සැබ)", "category": "plant" },
  { "word": "කරමර්දන", "meaning": "පුවක්ගස", "category": "plant" },
  { "word": "කරමෘතක්තෘ", "meaning": "කරඹ", "category": "plant" },
  { "word": "කරමුදි", "meaning": "පුවක්පල", "category": "plant" },
  { "word": "කරමුදිකා", "meaning": "කළු අත්තන", "category": "plant" },
  { "word": "කරමර්දන්", "meaning": "කරබ, මහකරබ, සෙල සැඛෝ", "category": "plant" },
  { "word": "කරමල", "meaning": "කරඹ, මහකරබ, දුම මැල්ල", "category": "plant" },
  { "word": "කරමෛකලලු", "meaning": "කරබ", "category": "plant" },
  { "word": "කරමල", "meaning": "ලෝලු, ගිඟුස වැල", "category": "plant" },
  { "word": "කරමුව", "meaning": "සිවංගුරු", "category": "plant" },
  { "word": "කරයාන්පු", "meaning": "සිරස්ස", "category": "symptom" },
  { "word": "කරරි", "meaning": "පුවක්ගස", "category": "plant" },
  { "word": "කරරාහ", "meaning": "රත්මල්, (රංගිලමල්)", "category": "plant" },
  { "word": "කරල්ලැබ", "meaning": "අසමෝදගම්", "category": "plant" },
  { "word": "කරල", "meaning": "සක්නබ, රක්කාගුණ, පුවගු, මිහසෙවන්, (අෂ්ටක වර්ගයේ ඔසුවක්)", "category": "treatment" },
  { "word": "කරවනලා", "meaning": "කරල්සැබෝ ගස", "category": "plant" },
  { "word": "කරවාල", "meaning": "කහ, ගිවුලුගස", "category": "plant" },
  { "word": "කරවැල", "meaning": "කලාවගියක්", "category": "plant" },

  // --- පිටුව 88 (image_ad3f9e.png) ---
  { "word": "කරවි", "meaning": "හෙල අබ, අසමෝදගම්", "category": "plant" },
  { "word": "කරවීර", "meaning": "කණේරා, අලරිය, රංගි පියල්, මනෝසිල", "category": "plant" },
  { "word": "කරවීරක", "meaning": "කුඹුක්, රත් කණේරා, රතු අලරිය", "category": "plant" },
  { "word": "කරවීරගුඡ්ජා", "meaning": "රටනේර", "category": "plant" },
  { "word": "කරවීරගා", "meaning": "රත් සිරියල්", "category": "treatment" },
  { "word": "කරවීරානුජා", "meaning": "රටනේර", "category": "plant" },
  { "word": "කරවීරිකා", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "කරවිල්ලක", "meaning": "කරවිල", "category": "plant" },
  { "word": "කරවිලන", "meaning": "සිනක්කාරම්", "category": "treatment" },
  { "word": "කරව්‍යා", "meaning": "ඒවාමාංශ", "category": "treatment" },
  { "word": "කරසපල", "meaning": "බුළු", "category": "plant" },
  { "word": "කරසම්භව", "meaning": "රෝමලුණු", "category": "treatment" },
  { "word": "කරාට", "meaning": "අල, නෙළුම් අල, කුකුරු මුවන්", "category": "plant" },
  { "word": "කරාටක", "meaning": "කුකුරුමුවන්, නෙළුම් මල්", "category": "plant" },
  { "word": "කරාමපු", "meaning": "කරාබුනැටි", "category": "plant" },
  { "word": "කරාමුත්‍රිකා", "meaning": "දියබෙරලිය ගස", "category": "plant" },
  { "word": "කරාවිලා", "meaning": "කරඹ ගස", "category": "plant" },
  { "word": "කරාමර්ථ", "meaning": "ඇටවමාරා", "category": "plant" },
  { "word": "කරායන", "meaning": "මඟ දියබෙරලිය", "category": "plant" },
  { "word": "කරාල", "meaning": "කලුතල, අක්මැල්ල", "category": "plant" },
  { "word": "කරාලකලිකා", "meaning": "කොද ගස", "category": "plant" },
  { "word": "කරාලා", "meaning": "ඉඟුරු, වලගසල්", "category": "plant" },
  { "word": "කරාලාබ", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කරාලි", "meaning": "ලියනගලා", "category": "plant" },
  { "word": "කරාලෝහා", "meaning": "පිත්තල", "category": "treatment" },
  { "word": "කරී", "meaning": "අභූෂ්, හෙලකීිරිය", "category": "plant" },
  { "word": "කරීංගල", "meaning": "කරීබගල-(තදින් කසන විෂ සහිත හබරල වගියක්) ගරු බිල්ලා වැල්, (යක් පුහුල්-බිම් පුහුල්)", "category": "plant" },
  { "word": "කරී උප්පු", "meaning": "කලුලුණු (වස කැපී නසන්නට ගන්නා ලුණු)", "category": "treatment" },
  { "word": "කරිකා", "meaning": "ඇපල ගස, ඉඟුරු, ගුරුළු", "category": "plant" },
  { "word": "කරිකනා", "meaning": "ඇත් වගපුල්", "category": "plant" },
  { "word": "කරිකනාවල්ලි", "meaning": "සිටිය වැල", "category": "plant" },
  { "word": "කරිකුසුම", "meaning": "නා (මල්) ගස", "category": "plant" },
  { "word": "කරිකාභො", "meaning": "ඇත් වගපුල්, (ගජතිප්පිලි)", "category": "plant" },
  { "word": "කරිකේත ර", "meaning": "නාකේසර", "category": "plant" },
  { "word": "කරිකේවාරා", "meaning": "දම්බත් (දංකුඹ=බත් දංකුඹ)", "category": "treatment" },
  { "word": "කරීවජ්ජ", "meaning": "නැල්පතුරු", "category": "treatment" },
  { "word": "කරීබක", "meaning": "නොපිල", "category": "plant" },
  { "word": "කරීදමන", "meaning": "වල්කොල්ලු", "category": "plant" },
  { "word": "කරීන්", "meaning": "නාකේසර", "category": "plant" },
  { "word": "කරීපත්‍ර", "meaning": "නැල්පතුරු", "category": "treatment" },
  { "word": "කරීපප්පලි", "meaning": "ඇත් ව ග පු ල් (ගජතිප්පිලි) සිතිය, රන් ගොකටු", "category": "plant" },
  { "word": "කරීභ", "meaning": "බෝ ගස", "category": "plant" },
  { "word": "කරීමාලක", "meaning": "කුකුළු කරඳ, සිරිත", "category": "plant" },
  { "word": "කරීල", "meaning": "හීන් කරවිල, තුඹකරවිල", "category": "plant" },
  { "word": "කරීලක", "meaning": "බඩුකරවිල, තුඹකරවිල", "category": "plant" },
  { "word": "කරීලකා", "meaning": "ගජතිප්පිලි", "category": "plant" },
  { "word": "කරීවල්ලී", "meaning": "කරවිල වැල", "category": "plant" },
  { "word": "කරීවිල", "meaning": "ගඟල, දෙමස් ගඟල, (කබරල විශේෂයක්)", "category": "plant" },
  { "word": "කරීවෙක්කු", "meaning": "කෙලකීිරිය", "category": "plant" },
  { "word": "කරු", "meaning": "දළක්, හුණකීිරිය, හෙල කණේරා, (සුදු අලරිය) කටුකීිරිය මඟ උක්", "category": "plant" },
  { "word": "කරූර", "meaning": "කඹිල", "category": "plant" },
  { "word": "කරූරිය", "meaning": "ගොමවැරැට්ටි, අස්වට", "category": "treatment" },
  { "word": "කරුෂ", "meaning": "කලන් තුන", "category": "treatment" },
  { "word": "කරීසකස", "meaning": "කිණිරිය", "category": "plant" },
  { "word": "කරීසලාන්කන්නි", "meaning": "කලුඅත්තන", "category": "plant" },
  { "word": "කරුල් නන්මිනිකයි", "meaning": "වල් බෝඹු", "category": "plant" },
  { "word": "කරෙකණු වාච්චි", "meaning": "ජේයාව", "category": "treatment" },
  { "word": "කරේකල්", "meaning": "නිල් කඹුරුකුඹු", "category": "plant" },
  { "word": "කරෙකුරැණිච්", "meaning": "කලු කොල්ලු", "category": "plant" },
  { "word": "කරෙකොල්ලු", "meaning": "ඉදිරි ගස", "category": "plant" },
  { "word": "කරේන්", "meaning": "වියළි පුවක් (කරංකා)", "category": "plant" },
  { "word": "කරොකා", "meaning": "කරඳ, කස්, වං ඇපල, මින්බැද්ද", "category": "plant" }
];