// data_144_152.js - පිටු 144 සිට 152 දක්වා සියලුම වචන
const data_extra_144_152 = [
  // --- පිටුව 144 (image_91e832.jpg) ---
  { "word": "ක්‍රකව", "meaning": "කටුකිරිය, උග්‍රරස්ස, විකඩ්කත නම් වාක්‍යය", "category": "plant" },
  { "word": "ක්‍රකවජ්ජ", "meaning": "වටකේ", "category": "plant" },
  { "word": "ක්‍රකවපත්‍ර", "meaning": "තේක්ක ගස, වටකේ ගස", "category": "plant" },
  { "word": "ක්‍රකවා", "meaning": "වැටකේ ගස, නානි විශේෂයක්", "category": "plant" },
  { "word": "ක්‍රකර්", "meaning": "කටුකිරිය (කිරීර වාක්‍යය) හුණ කිළිල", "category": "plant" },
  { "word": "ක්‍රිකිකා", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "ක්‍රකුර", "meaning": "රක්කුජ්ජද (සාරණ)", "category": "plant" },
  { "word": "ක්‍රතඥනිය", "meaning": "රතු, කළු මල් සහිත කඩුකරෝෂණී වගී දෙක", "category": "plant" },
  { "word": "ක්‍රතනි", "meaning": "මිණිමස්", "category": "treatment" },
  { "word": "ක්‍රතක", "meaning": "බලල්ලුණු, රෝමලුණු", "category": "treatment" },
  { "word": "ක්‍රතමාලක", "meaning": "එරහඳි (ඇසල)", "category": "plant" },
  { "word": "ක්‍රතය", "meaning": "මෝරු", "category": "treatment" },
  { "word": "ක්‍රිකිකා", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "ක්‍රවනක", "meaning": "සුදු අගිල්", "category": "plant" },
  { "word": "ක්‍රක්ෂද්‍ර", "meaning": "රක්කුජ්ජද", "category": "plant" },
  { "word": "ක්‍රදිනී", "meaning": "දියබෙරලිය", "category": "plant" },
  { "word": "ක්‍රමුපුරක", "meaning": "කතුරුමුරුංගා ගස", "category": "plant" },
  { "word": "ක්‍රමිකණ්ටක", "meaning": "වලඟසාල්, රත් නිවුල්", "category": "plant" },
  { "word": "ක්‍රමසන", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ක්‍රමිජ්", "meaning": "අගිල්, සඳුන්, ලාකඩ", "category": "treatment" },
  { "word": "ක්‍රමිගස්ත්‍රැ", "meaning": "වලඟසාල්, දිවුල්ගස", "category": "plant" },
  { "word": "ක්‍රමිලක", "meaning": "වල්ලුමු", "category": "treatment" },
  { "word": "ක්‍රමුක", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "ක්‍රමුක", "meaning": "පුවක්, ඇත්කලාඳුරු, රත් ලොත්, බුන්මදුරා, දේවදාර ගස, කපු ඇට", "category": "plant" },
  { "word": "ක්‍රමුග", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "ක්‍රවුනනි", "meaning": "රැතැණිය, වල්මුලඟු (වල් මොලඟු)", "category": "plant" },
  { "word": "ක්‍රව්‍යාද", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "ක්‍රගණාමිල", "meaning": "සියඹලා", "category": "plant" },
  { "word": "ක්‍රගර", "meaning": "තලකිරි බත්", "category": "treatment" },
  { "word": "ක්‍රගාර්", "meaning": "බත්", "category": "treatment" },
  { "word": "ක්‍රස්න", "meaning": "නිල් මානෙල්", "category": "plant" },
  { "word": "ක්‍රස්නා", "meaning": "කුඹුරු", "category": "plant" },
  { "word": "ක්‍රස්ඵල", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "ක්‍රසකාමිල", "meaning": "සින්බිලා (සියඹලා)", "category": "plant" },
  { "word": "ක්‍රාධි", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "ක්‍රාන්තා", "meaning": "බබු, එන්සාල්", "category": "treatment" },
  { "word": "ක්‍රාන්ති", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "ක්‍රාමික", "meaning": "පුවක් මුල", "category": "plant" },
  { "word": "ක්‍රාමණ", "meaning": "පුස්කර", "category": "treatment" },
  { "word": "ක්‍රාර", "meaning": "බදුල්ල, සුලුබැවිල, රතු කණේරු", "category": "plant" },
  { "word": "ක්‍රාරක", "meaning": "රතු සාරණ", "category": "plant" },
  { "word": "ක්‍රාරකමණී", "meaning": "තිත්ත ලබු", "category": "plant" },
  { "word": "ක්‍රාරගඬ", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ක්‍රාරදර්ශිණී", "meaning": "එල කැම්මේරිය", "category": "plant" },
  { "word": "ක්‍රාරධුනී", "meaning": "කලු අත්තන", "category": "plant" },
  { "word": "ක්‍රාරා", "meaning": "සුලුබැවිල, රතු සාරණ", "category": "plant" },
  { "word": "ක්‍රමුඛ", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "ක්‍රිතක", "meaning": "බලල් ලුණු", "category": "treatment" },
  { "word": "ක්‍රිමි", "meaning": "ලෝබු, යකඩ", "category": "treatment" },
  { "word": "ක්‍රිමිකණ්ටක", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ක්‍රිමිසන", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ක්‍රිම්ප", "meaning": "සඳුන්, අගිල්, ලාකඩ, ක්‍රිමි ගස්ත්‍රැ", "category": "treatment" },
  { "word": "ක්‍රිම්ජිත්", "meaning": "වලඟසාල්, ගම්මිරිස්", "category": "plant" },
  { "word": "ක්‍රිමිදන්න", "meaning": "දන්ත රෝගයක්", "category": "symptom" },
  { "word": "ක්‍රිමිමුල", "meaning": "පුවක්", "category": "plant" },
  { "word": "ක්‍රිමිරිපු", "meaning": "වලඟසාල්, එරබදු", "category": "plant" },
  { "word": "ක්‍රිමිරාප්‍ර", "meaning": "ක්‍රිමිගස්ත්‍රැ", "category": "treatment" },
  { "word": "ක්‍රිමිගස්ත්‍රැ", "meaning": "එනම් වගිය, වලඟසාල්, පබළු", "category": "treatment" },
  { "word": "ක්‍රිමිශාස්ත්‍රව", "meaning": "ඉඟුරා, ගුරන්ද", "category": "plant" },

  // --- පිටුව 145 (image_924267.jpg) ---
  { "word": "ක්‍රිමිහර", "meaning": "ගම්මිරිස්, වලඟසාල්, කලු දුරු", "category": "plant" },
  { "word": "ක්‍රිම්භා", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "ක්‍රිෂ්ණ", "meaning": "දුරා, වැව්රණ, කවුදුරු, තිප්පිලි, කලු ලුණු, වැටකේ", "category": "treatment" },
  { "word": "ක්‍රිෂ්ණගබ්", "meaning": "මිල්ල ගස", "category": "plant" },
  { "word": "ක්‍රිෂ්ණී", "meaning": "බුව", "category": "plant" },
  { "word": "ක්‍රිෂ්ණේප්ප්‍ර", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "ක්‍රිෂ්ණා", "meaning": "මහකරඹ, තිප්පිලි, කලුදුරු", "category": "plant" },
  { "word": "ක්‍රොඩ", "meaning": "බින්තල් අල", "category": "plant" },
  { "word": "ක්‍රොඩකණ්ට", "meaning": "උවරල", "category": "plant" },
  { "word": "ක්‍රොඩකන්‍තයා", "meaning": "උවරල", "category": "plant" },
  { "word": "ක්‍රොඩකේශර (කා)", "meaning": "මිහවම්මුතු", "category": "plant" },
  { "word": "ක්‍රොඩචූඩා", "meaning": "මිහමුඩමහණ", "category": "plant" },
  { "word": "ක්‍රොඩපර්ණි", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "ක්‍රොඩපුෂ්පී", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ක්‍රොඩි", "meaning": "උවරල", "category": "plant" },
  { "word": "ක්‍රොඩේෂ්ටා", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "ක්‍රොමමුක", "meaning": "පුවක්කා", "category": "plant" },
  { "word": "ක්‍රොෂ්ඨි", "meaning": "කිරිබදු, කෝවක්කා, තල", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රක මෙබලා", "meaning": "පෘශ්ණි පර්ණී", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රික මූලිකා", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රකා", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රසංවිටිකා", "meaning": "නව්නන්දි ගස", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රඵල", "meaning": "අගුණකරගස", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රවිනා", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රවිනා", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ක්‍රොෂ්ඨී", "meaning": "ඇත්සාවිය", "category": "treatment" },
  { "word": "ක්‍රොෂටේක්ෂු", "meaning": "සුදු උක්", "category": "plant" },
  { "word": "ක්‍රොෂ්ට්‍රි", "meaning": "කිරිබදු, තල", "category": "plant" },
  { "word": "ක්‍රොෂ්ඨල", "meaning": "මසන් (බැබර)", "category": "plant" },
  { "word": "ක්‍රොසකන්ධන", "meaning": "නෙළුමුළු, තිප්පිලි, තෙවම් ඇට, (ධාන්‍ය විශේෂයක්)", "category": "plant" },
  { "word": "ක්‍රොන්‍ධ", "meaning": "යකඩ", "category": "treatment" },
  { "word": "ක්‍රොනති", "meaning": "වටරැගැණි, (වල්ගා මිරිස්)", "category": "plant" },
  { "word": "ක්ලෙදපනායත", "meaning": "නෙළුම් ඇට", "category": "plant" },
  { "word": "ක්ලෙදලෝහිත", "meaning": "හිඟුල්", "category": "treatment" },
  { "word": "ක්ලම", "meaning": "ගිලන්බව", "category": "treatment" },
  { "word": "ක්ලමීට්", "meaning": "ආයාසය, වැඩි කෙබෙත් තුව", "category": "treatment" },
  { "word": "ක්ලිතක", "meaning": "වැල්මී, රසබලින්ද, කරඳ ඇට", "category": "plant" },
  { "word": "ක්ලිතකභාෂා", "meaning": "රත් හඳුන්", "category": "plant" },
  { "word": "ක්ලිතකිකා", "meaning": "නිල් අවිරිය, අවිරිය", "category": "plant" },
  { "word": "ක්ලිනිකා", "meaning": "පොල්පලා, අස්වැන්න, අවිරිය", "category": "plant" },
  { "word": "ක්ලිතන", "meaning": "වැල්මී වෙසෙසක්, අවිරිය, පුස්වැන්න", "category": "plant" },
  { "word": "ක්ලිතනිකා", "meaning": "බෙරා", "category": "plant" },
  { "word": "ක්ලිතනී", "meaning": "පුස්වැන්න, අවිරිය", "category": "plant" },
  { "word": "ක්ලිතනීය", "meaning": "වැල්මී වෙසෙසක්, අවිරිය, පුස්වැන්න", "category": "plant" },
  { "word": "ක්ලින්නා", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "ක්වථ", "meaning": "තම්බනලද", "category": "treatment" },
  { "word": "ක්වථිත", "meaning": "පිසන ලද, කකාරන ලද", "category": "treatment" },
  { "word": "ක්වථිත ද්‍රව්‍ය", "meaning": "කකාරණ ලද ද්‍රව්‍ය (අරිෂ්ට)", "category": "treatment" },
  { "word": "ක්වල", "meaning": "ලොකු බැබර ගෙඩිය", "category": "plant" },
  { "word": "ක්වාථ", "meaning": "සිඳපු කෂාය", "category": "treatment" },
  { "word": "ක්වාථොත්භව", "meaning": "මයුර තුඹ", "category": "plant" },

  // --- පිටුව 146 (image_92426d.jpg) ---
  { "word": "ක්ෂණක", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "ක්ෂණතු තුවාලය", "meaning": "තුවාලය", "category": "treatment" },
  { "word": "ක්ෂත", "meaning": "සාල්", "category": "treatment" },
  { "word": "ක්ෂතක්ෂම", "meaning": "රත් කිහිරි ගස", "category": "plant" },
  { "word": "ක්ෂතශිරීත්", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ක්ෂතක", "meaning": "අබ", "category": "plant" },
  { "word": "ක්ෂතකාන්", "meaning": "බදුල්ල ගස", "category": "plant" },
  { "word": "ක්ෂතඝණ", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "ක්ෂතජ", "meaning": "බැදි සාල්, කොකුම් මල්, ලේ", "category": "treatment" },
  { "word": "ක්ෂතහර", "meaning": "අගිල්, ලාකඩ", "category": "treatment" },
  { "word": "ක්ෂත්‍ර", "meaning": "තුවරලා", "category": "plant" },
  { "word": "ක්ෂත්‍රපාදප", "meaning": "කිරිපලු ගස", "category": "plant" },
  { "word": "ක්ෂත්‍රා", "meaning": "කිරිපලු ගස", "category": "plant" },
  { "word": "ක්ෂත්‍රානී", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "ක්ෂත්‍රීනී", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "ක්ෂත්‍රිය", "meaning": "කිරිපලු ගස", "category": "plant" },
  { "word": "ක්ෂත්‍රියබර", "meaning": "තිත්තවැල", "category": "plant" },
  { "word": "ක්ෂත්‍රියබරා", "meaning": "තිත්තවැල, තිත්ත කැල්ල", "category": "plant" },
  { "word": "ක්ෂත්‍රියවරා", "meaning": "ලබු වෙසෙසක්", "category": "plant" },
  { "word": "ක්ෂපදා", "meaning": "මුරංගා, (මිරිකුළු)", "category": "plant" },
  { "word": "ක්ෂපා", "meaning": "වරාගස", "category": "plant" },
  { "word": "ක්ෂපාකසීරී", "meaning": "වරාගස", "category": "plant" },
  { "word": "ක්ෂපාකර", "meaning": "කපුරු", "category": "plant" },
  { "word": "ක්ෂමා", "meaning": "කිරිසබ ගස", "category": "plant" },
  { "word": "ක්ෂමාංශ", "meaning": "මුරංගා ගස", "category": "plant" },
  { "word": "ක්ෂමාධිෂාඨිනී", "meaning": "වාෂභක (අෂ්ටක වගියේ ඔසුවක්)", "category": "treatment" },
  { "word": "ක්ෂමාරොහ", "meaning": "සොත්බුදි (රටබුදි)", "category": "treatment" },
  { "word": "ක්ෂමොදග", "meaning": "මිරිකුළු, (මුරංගා)", "category": "plant" },
  { "word": "ක්ෂය", "meaning": "කාෂ රෝගය", "category": "symptom" },
  { "word": "ක්ෂයනරු", "meaning": "නන්දි රාක", "category": "plant" },
  { "word": "ක්ෂයනාමිකා", "meaning": "රේරා ගස", "category": "plant" },
  { "word": "ක්ෂයනාශිනී", "meaning": "අරලු, නිතිහ, (කෝවක්කා)", "category": "plant" },
  { "word": "ක්ෂයසප්", "meaning": "වම්ඇපල (අගල්ආධාර)", "category": "plant" },
  { "word": "ක්ෂයහරි", "meaning": "කිරිබදු", "category": "plant" },
  { "word": "ක්ෂයාවහා", "meaning": "රේරා, (රේරාගහ)", "category": "plant" },
  { "word": "ක්ෂයාවන්‍ධ", "meaning": "රේරා, (රේරාගහ)", "category": "plant" },
  { "word": "ක්ෂයාවභා", "meaning": "රේරා, (රේරාගහ)", "category": "plant" },
  { "word": "ක්ෂරීප", "meaning": "කොකුම් මල්, (කුංකුම) බැදි හාල්", "category": "treatment" },
  { "word": "ක්ෂරිකා", "meaning": "ගැටනිවුල්, කලු අබ, තෙලඹු ගස", "category": "plant" },
  { "word": "ක්ෂරපත්‍රා", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ක්ෂරවක කණ්ඨිකා", "meaning": "නෙරෙවි (ගොකටු)", "category": "plant" },
  { "word": "ක්ෂව", "meaning": "අක්මැල්ල, හෙල අබ", "category": "plant" },
  { "word": "ක්ෂවක්ෂව", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "ක්ෂවක", "meaning": "හෙල අබ, සැබෝ, මුගුණුවැන්න, කලු අබ", "category": "plant" },
  { "word": "ක්ෂවිකා", "meaning": "බිම්මුල්, අබ, අක්මැල්ල, කරල්සැබෝ, තලා", "category": "plant" },
  { "word": "ක්ෂවතන්‍ද්‍රා", "meaning": "නන්දි රැක", "category": "plant" },
  { "word": "ක්ෂවතු", "meaning": "ඇත්බටු, (වම්බටු)", "category": "plant" },
  { "word": "ක්ෂවතුනාමිකා", "meaning": "රේරා", "category": "plant" },
  { "word": "ක්ෂවපත්‍රා", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ක්ෂවප්‍රවාහිනී", "meaning": "නිබිබොටු", "category": "plant" },
  { "word": "ක්ෂවමුෂ්ටි", "meaning": "රේරා ගස", "category": "plant" },
  { "word": "ක්ෂවා", "meaning": "අබගස", "category": "plant" },
  { "word": "ක්ෂවාරොහන", "meaning": "රටබුදි ගස", "category": "plant" },
  { "word": "ක්ෂාමදංග", "meaning": "මුරංගා", "category": "plant" },
  { "word": "ක්ෂාර", "meaning": "ලුණු, ලුණුවගී, සකුර, මදටිය, කොසඹ, අළු, අළුපුස්කර", "category": "treatment" },
  { "word": "ක්ෂාරක", "meaning": "තෙලඹු", "category": "plant" },
  { "word": "ක්ෂාර කාරක", "meaning": "බදුල්ල", "category": "plant" },
  { "word": "ක්ෂාරත්‍රය", "meaning": "පුස්කර, යවකාර, සූයන ලුණු වගී තුන", "category": "treatment" },
  { "word": "ක්ෂාරද්වය", "meaning": "පුස්කර, යවකාර", "category": "treatment" },
  { "word": "ක්ෂාරදල", "meaning": "වරාගස, හින්තම්පල", "category": "plant" },
  { "word": "ක්ෂාරදලා", "meaning": "වරා ගස හින්තමිබල", "category": "plant" },

  // --- පිටුව 147 (image_924287.jpg) ---
  { "word": "ක්ෂාරදශක", "meaning": "මුරංගා, රාබු, කැළ, සියඹලා, කිතුල්, ඉඟුරු, කොසඹ, උක්, සැබෝ, කෙසෙල් යන ගස් දශය", "category": "plant" },
  { "word": "ක්ෂාරද්‍රැ", "meaning": "තෙලඹු ගස", "category": "plant" },
  { "word": "ක්ෂාරපංච", "meaning": "පිදුරු, තෙලඹු, තල දඬු, දවාගත් අළු සහ යවකාර, සුවස ලුණු", "category": "treatment" },
  { "word": "ක්ෂාර පත්‍ර", "meaning": "තඹපලා", "category": "plant" },
  { "word": "ක්ෂාරබිධ්යා", "meaning": "සැබෝ", "category": "plant" },
  { "word": "ක්ෂාර රාජ්", "meaning": "පුස්කර", "category": "treatment" },
  { "word": "ක්ෂාරවගී", "meaning": "සුවස ලුණු, පුස්කර, යවකාර ලුණු", "category": "treatment" },
  { "word": "ක්ෂාරවල්ලී", "meaning": "කිරිබදු", "category": "plant" },
  { "word": "ක්ෂාරවෘක්ෂ", "meaning": "තෙලඹු ගස", "category": "plant" },
  { "word": "ක්ෂාරශ්‍රේෂ්ඨ", "meaning": "නව සාරන්, කාල, රත්කාල, එරබදු, තෙලඹු ගස", "category": "plant" },
  { "word": "ක්ෂාරසප්‍රිය", "meaning": "කිරිබදු", "category": "plant" },
  { "word": "ක්ෂාරෂ්ඨක", "meaning": "තල දඬු, ලියනඟලා, කරල්සැබ, සිරිල, කෙම්වැල්, තෙලඹු යන මේවා දවාගත් අළු", "category": "treatment" },
  { "word": "ක්ෂාරසුකාල", "meaning": "කිරිබදු අල", "category": "plant" },
  { "word": "ක්ෂාරාර්ම", "meaning": "මුහුදු ලුණු", "category": "treatment" },
  { "word": "ක්ෂාරාමුන", "meaning": "කාරම් දිය", "category": "treatment" },
  { "word": "ක්ෂාරාෂ්ටක", "meaning": "කෑල, දළක්, සැබෝ, සියඹලා, වරා, තෙලඹු", "category": "plant" },
  { "word": "ක්ෂාරොත්තභව", "meaning": "තෙලඹු ගස", "category": "plant" },
  { "word": "ක්ෂාරෝදක", "meaning": "කාරම් දිය", "category": "treatment" },
  { "word": "ක්ෂාවක", "meaning": "අබ", "category": "plant" },
  { "word": "ක්ෂිති", "meaning": "ගෝරෝචන, කිහිරි ගස", "category": "treatment" },
  { "word": "ක්ෂිතිකසම", "meaning": "කලු කිහිරි", "category": "plant" },
  { "word": "ක්ෂිතිපන්නු", "meaning": "රියම්", "category": "treatment" },
  { "word": "ක්ෂිතිබදු", "meaning": "කුඩා බැබර වෙසෙසක්", "category": "plant" },
  { "word": "ක්ෂිතිමෝහන", "meaning": "මුරංගා (මිරිකුළු)", "category": "plant" },
  { "word": "ක්ෂීර", "meaning": "මහ කොසඹ, කිරි, ලියනඟලා, කිරිනු, වසතැල්ල, හෝර මැලියම්", "category": "treatment" },
  { "word": "ක්ෂීරක", "meaning": "එල මුරංගා", "category": "plant" },
  { "word": "ක්ෂීරකන්‍ධුකී", "meaning": "ශීර්ෂ (මහරි) වාක්‍යය", "category": "plant" },
  { "word": "ක්ෂීරකඨකා", "meaning": "කෙළිඳ ඇට", "category": "plant" },
  { "word": "ක්ෂීරකන්‍ධ", "meaning": "කිරිබදු වැල්", "category": "plant" },
  { "word": "ක්ෂීරකාකෝලිකා", "meaning": "කිරිකවෙළු (අෂ්ටක වගියේ ඔසුවක්)", "category": "plant" },
  { "word": "ක්ෂීරකාණ්ඩක", "meaning": "වරා, දළක්", "category": "plant" },
  { "word": "ක්ෂීරකාෂඨා", "meaning": "නුග වෙසෙසක්", "category": "plant" },
  { "word": "ක්ෂීරකුටපකා", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "ක්ෂීරබක්යා", "meaning": "කිරිබදු", "category": "plant" },
  { "word": "ක්ෂීරබර්ජුර", "meaning": "රටබුදි ගස", "category": "plant" },
  { "word": "ක්ෂීරජ", "meaning": "දියකිරි", "category": "treatment" },
  { "word": "ක්ෂීරත්‍රය", "meaning": "දළක්, වරා, නුග", "category": "plant" },
  { "word": "ක්ෂීරතුම්බී", "meaning": "ලබු වෙසෙසක්", "category": "plant" },
  { "word": "ක්ෂීරදල", "meaning": "තඹපලා, සිහින්තඹපලා, වරා ගස, කිරිහැන්ද", "category": "plant" },
  { "word": "ක්ෂීරදම", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "ක්ෂීරනාස", "meaning": "ගැටනිවුල්", "category": "plant" },
  { "word": "ක්ෂීරපන", "meaning": "මුරංගා, මහනුග, වරා", "category": "plant" },
  { "word": "ක්ෂීරපත්‍රිකා", "meaning": "වරා", "category": "plant" },
  { "word": "ක්ෂීරපත්‍රී", "meaning": "වරා, මහනුග", "category": "plant" },
  { "word": "ක්ෂීරපර්ණ", "meaning": "වරාගස", "category": "plant" },
  { "word": "ක්ෂීරපර්ණී", "meaning": "වරාගස", "category": "plant" },
  { "word": "ක්ෂීරපර්ණිකී", "meaning": "වරාගස", "category": "plant" },
  { "word": "ක්ෂී රපලා", "meaning": "කඩල-හෙල ලුහුණු", "category": "plant" },
  { "word": "ක්ෂීරපා", "meaning": "බෝගස, කිරිබෝ ගස", "category": "plant" },
  { "word": "ක්ෂීරපීලූ", "meaning": "මහ කරඹ", "category": "plant" },
  { "word": "ක්ෂීරපුෂ්ප", "meaning": "මුරුවා වැල්", "category": "plant" },
  { "word": "ක්ෂීරපුෂ්පී", "meaning": "කිරිකවෙළු (අෂ්ටක වගියේ ඔසුවක්)", "category": "plant" },
  { "word": "ක්ෂීරබිදාරිකා", "meaning": "කව් කිරිබදු, කිරි බදු", "category": "plant" },

  // --- පිටුව 148 (image_92428d.jpg) ---
  { "word": "ක්ෂීරිබොධි", "meaning": "කිරි බෝ, ඇසතුබෝ", "category": "plant" },
  { "word": "ක්ෂීරනාසකතා", "meaning": "කෝවක්කා, කැකිරි", "category": "plant" },
  { "word": "ක්ෂීරමොරට", "meaning": "එල මුරුවා වැල්", "category": "plant" },
  { "word": "ක්ෂීරලතා", "meaning": "කිරිබදු අල", "category": "plant" },
  { "word": "ක්ෂීරවල්ලී", "meaning": "කිරිබදු වැල්", "category": "plant" },
  { "word": "ක්ෂීරවිදාරිකා", "meaning": "කිරිබදු වැල්", "category": "plant" },
  { "word": "ක්ෂීරවිෂ", "meaning": "මැලියම් විෂ", "category": "treatment" },
  { "word": "ක්ෂීරවිසාලිකා", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ක්ෂීරවාක්ෂ", "meaning": "ඇසතුබෝ, කිරිපලු, දිවුල්", "category": "plant" },
  { "word": "ක්ෂීරශාක", "meaning": "කෝවක්කා, කිරිකවෙළු, කිරිපලු රුක", "category": "plant" },
  { "word": "ක්ෂීරශිඛී", "meaning": "සිරවවු (හෝරඅරවු)", "category": "treatment" },
  { "word": "ක්ෂීරශුක්තා", "meaning": "කිරිකවෙළු, කිරිබදු", "category": "plant" },
  { "word": "ක්ෂීරශුක්ල", "meaning": "කිරිකවෙළු, කිරිබදු, කිරිපළු", "category": "plant" },
  { "word": "ක්ෂීරශුක්ලිකා", "meaning": "කවෙළු", "category": "plant" },
  { "word": "ක්ෂීරශුක්නා", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ක්ෂීරශාඛී", "meaning": "කොලු අරලු, කක්ෂිකා ලිංගී", "category": "plant" },
  { "word": "ක්ෂීරශ්‍රීවේෂ්ටා", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "ක්ෂීරශ්‍රේෂ්ඨා", "meaning": "මදටිය, මාරා, එරබදු, කෑල", "category": "plant" },
  { "word": "ක්ෂීරස", "meaning": "මීදෙන කිරි", "category": "treatment" },
  { "word": "ක්ෂීරසන්තානිකා", "meaning": "මීදෙන කිරි", "category": "treatment" },
  { "word": "ක්ෂීරසාර", "meaning": "වෙඩරෑ, පැණියෝගපේණ, සක්කුරුපේණ", "category": "treatment" },
  { "word": "ක්ෂීරකා", "meaning": "කිරිපලු, ලප්නෑල්ල, ඇසතු", "category": "plant" },
  { "word": "ක්ෂීරාරා", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ක්ෂීරාරාබිකා", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ක්ෂීරාරාවී", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ක්ෂීරාරාන්වා", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ක්ෂීරාරාන්මිකා", "meaning": "කුඩා කිරිපලු", "category": "plant" },
  { "word": "ක්ෂීරාවිකා", "meaning": "කිරිඟුළු (කිරි අඟුණ)", "category": "plant" },
  { "word": "ක්ෂීරාව්හ", "meaning": "හෝර ගස", "category": "plant" },
  { "word": "ක්ෂීරිකාගන්ධ", "meaning": "කිරිබදු", "category": "plant" },
  { "word": "ක්ෂීරිකා", "meaning": "කිරිපලු, රටබුදි", "category": "plant" },
  { "word": "ක්ෂීරිකුටජිකා", "meaning": "කෙම්නීද", "category": "plant" },
  { "word": "ක්ෂීරිනී", "meaning": "කිරිකවෙළු, කිරිබදු, මස්බැද්ද, මැඩගු, පහුක්, කිරිදි, ඇත්දෙමට, යක්බේරිය, රත්කිරිගොකටු, පික්මැලි (පික්මල්)", "category": "plant" },
  { "word": "ක්ෂීරින්", "meaning": "නුග, පුමිල, අට්ටක්කා", "category": "plant" },
  { "word": "ක්ෂීරිනකතා", "meaning": "කොබෝවක්කා", "category": "plant" },
  { "word": "ක්ෂීරි", "meaning": "බෝ, නුග, පුමිල, අට්ටක්කා", "category": "plant" },
  { "word": "ක්ෂීරීවාක්ෂ", "meaning": "නුග, පුමිල, ඇසතු, බෝ, දිවුල්", "category": "plant" },
  { "word": "ක්ෂීරශාඛා", "meaning": "නුග ආදී කිරි ඇති රුක්හි දළුවට පිටින් පිහිටි කොපුව", "category": "plant" },
  { "word": "ක්ෂීරි", "meaning": "කිරිපලු, දිවුල්, තෙලඹු, මුවකිරිය, ලියනඟලා, රන්කිරිගොකටු, නුග, පුමිල, වතුසුද්ද, මාඹුග, උක්කපුරු, කෙළිඳ, වරා", "category": "plant" },
  { "word": "ක්ෂීරාක්", "meaning": "ගිතෙල්", "category": "treatment" },
  { "word": "ක්ෂීරොරොදන", "meaning": "කිරිබත්", "category": "treatment" },
  { "word": "ක්ෂිව", "meaning": "සිවිය, ඇත්වගපුල්", "category": "plant" },
  { "word": "ක්ෂඤ්ජබෝධනී", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "ක්ෂඤ්ජබෝධන", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "ක්ෂුප්නිකා", "meaning": "හෙල අබ", "category": "plant" },
  { "word": "ක්ෂුණ", "meaning": "රැක්පෙනෙල", "category": "plant" },
  { "word": "ක්ෂුත", "meaning": "කිවිසුම, ප්‍රතිශ්යා රෝගය", "category": "symptom" },
  { "word": "ක්ෂුතක", "meaning": "අබ, හෙල අබ", "category": "plant" },
  { "word": "ක්ෂුද", "meaning": "සහල් සුණු", "category": "treatment" },
  { "word": "ක්ෂුද්‍ර", "meaning": "කටුවැල්බටු, කලාඳුරු, මීනුග, මුගුණුවැන්න, සිහින් දුම්බු, සුවක්කා, කරබෙයියා, රතු සාරණ, දෙල්, තිබිබොටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රඝන්ටිකා", "meaning": "සිහින් නෙරෙංචි", "category": "plant" },
  { "word": "ක්ෂුද්‍රකණ්ටිකා", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රකණ්ටිකා", "meaning": "කටුවැල්බටු", "category": "plant" },

  // --- පිටුව 149 (image_92464e.jpg) ---
  { "word": "ක්ෂුද්‍රක", "meaning": "දියෙහි හටගන්නා කටු පෙනෙල", "category": "plant" },
  { "word": "ක්ෂුද්‍රකම්බු", "meaning": "සක්බෙල්ලා, හින් කිරිවිල, කෑණි වගියට අයත් ධාන්‍ය වගියක්", "category": "treatment" },
  { "word": "ක්ෂුද්‍රබදිර", "meaning": "ගුරැන්ද", "category": "plant" },
  { "word": "ක්ෂුද්‍රබර්ජුරී", "meaning": "හින්ඳි", "category": "plant" },
  { "word": "ක්ෂුද්‍රගොක්ෂුර", "meaning": "හින්නෙරෙංචි", "category": "plant" },
  { "word": "ක්ෂුද්‍රගොදුම්", "meaning": "හින් තිරිඟු", "category": "plant" },
  { "word": "ක්ෂුද්‍රසණ්ඩිකා", "meaning": "අබනගිරිය", "category": "plant" },
  { "word": "ක්ෂුද්‍රවහදන", "meaning": "රත් සඳුන්", "category": "plant" },
  { "word": "ක්ෂුද්‍රවිතූ", "meaning": "ගල්කුරපලා", "category": "plant" },
  { "word": "ක්ෂුද්‍රද්‍රේ", "meaning": "හෙලදඹ (සුදු දම්බු) ලප්නාරං (නස්නාරං)", "category": "plant" },
  { "word": "ක්ෂුද්‍රජාලිනී", "meaning": "සිහින් වැටකොළු (හියන් වැටකොළු)", "category": "plant" },
  { "word": "ක්ෂුද්‍රජීරක", "meaning": "කළුදුරු, හින්දුරු, සූදුරු", "category": "plant" },
  { "word": "ක්ෂුද්‍රද්‍රව", "meaning": "නිතිහ ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රනන්ඩූල", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ක්ෂුද්‍රතුලසී", "meaning": "තලාගස් වගියක්", "category": "plant" },
  { "word": "ක්ෂුද්‍රද්‍රක්කා", "meaning": "අබනගිරිය", "category": "plant" },
  { "word": "ක්ෂුද්‍රදදා", "meaning": "සමන්, පුස්සමන්", "category": "plant" },
  { "word": "ක්ෂුද්‍රද්‍රභී", "meaning": "හින් කුසතණ", "category": "plant" },
  { "word": "ක්ෂුද්‍රද්‍රැ", "meaning": "මිරිස් ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රධානී", "meaning": "බෙලි", "category": "plant" },
  { "word": "ක්ෂුද්‍රධාන්‍ය", "meaning": "කුරහන්, අමු, ආදී කුඩා ධාන්‍ය වගී", "category": "plant" },
  { "word": "ක්ෂුද්‍රපත්‍ර", "meaning": "සුදු සාරණ, සුදු කුසතණ", "category": "plant" },
  { "word": "ක්ෂුද්‍රපත්‍රා", "meaning": "වදකහ, ඇඹුල්ඇඹිලිය", "category": "plant" },
  { "word": "ක්ෂුද්‍රපතී", "meaning": "වදකහ", "category": "plant" },
  { "word": "ක්ෂුද්‍ර පනස", "meaning": "දෙල් ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රපර්ණී", "meaning": "අටුගස්", "category": "plant" },
  { "word": "ක්ෂුද්‍රපර්ණී", "meaning": "පොල්පලා, පුස්වැන්න, කුඹුරු වැල්, තලා, මුංවැන්න, ඇගස්වැන්න", "category": "plant" },
  { "word": "ක්ෂුද්‍රපයලා", "meaning": "දේවදාලිය, නෙළුමු ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රපාෂාණභෙද", "meaning": "කුඩා පාෂාණභේදය (හින් පොල්පලා)", "category": "plant" },
  { "word": "ක්ෂුද්‍රපිප්පලී", "meaning": "වල් තිප්පිලි", "category": "plant" },
  { "word": "ක්ෂුද්‍රඵලා", "meaning": "කැකිරි, කෝවක්කා, බෑවිල, නෙලකටුරොලු, කවුපල් බටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රබලා", "meaning": "සුලුබැවිල", "category": "plant" },
  { "word": "ක්ෂුද්‍රභජ්", "meaning": "සිහින්දුම්බ, (සිහින්මධභහ) මස්බැද්ද", "category": "plant" },
  { "word": "ක්ෂුද්‍රගහන්ටාකී", "meaning": "නිබිබටුගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රමාතා", "meaning": "එලකබුවැල්බටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රමාරිෂ", "meaning": "සුලුකුර ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රමාශ", "meaning": "මස්වන්න", "category": "plant" },
  { "word": "ක්ෂුද්‍රමුස්තා", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "ක්ෂුද්‍රමොරට", "meaning": "සිහින් මුරුවා වැල්", "category": "plant" },
  { "word": "ක්ෂුද්‍රය", "meaning": "කලං එකහමාර", "category": "treatment" },
  { "word": "ක්ෂුද්‍රවංශ", "meaning": "නිදිකුම්බ", "category": "plant" },
  { "word": "ක්ෂුද්‍රවශාභූ", "meaning": "සුලුසාරණ", "category": "plant" },
  { "word": "ක්ෂුද්‍රවල්ලී", "meaning": "සුදු කරිවිල", "category": "plant" },
  { "word": "ක්ෂුද්‍රවසුභ", "meaning": "අටුකලා", "category": "plant" },
  { "word": "ක්ෂුද්‍රවාර්ථිකිනි", "meaning": "නිබිබොටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රවාර්ථකි", "meaning": "නිබිබොටු, රැක්බටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රශ්ලේෂ්මාන්තක", "meaning": "කුඩා ලෝලු ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රවේතසා", "meaning": "රතු සැබෝ, කුඩා කිණිහිරියා ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රගහපුෂ්පිකා", "meaning": "කුඩාභාණී ගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රශිකී", "meaning": "මොණරකුඩුම්බිය", "category": "plant" },
  { "word": "ක්ෂුද්‍රසහා", "meaning": "මූවැන්න", "category": "plant" },
  { "word": "ක්ෂුද්‍රසෙවන්තී", "meaning": "සින්කලගස", "category": "plant" },
  { "word": "ක්ෂුද්‍රහිංගුලිකා", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රා", "meaning": "කටුවැල්බටු, නිබිබොටු", "category": "plant" },
  { "word": "ක්ෂුද්‍රාන්තිමත්ට", "meaning": "සිහින් මිදි", "category": "plant" },
  { "word": "ක්ෂුද්‍රාපාමාර්ග", "meaning": "රතු සැබෝ", "category": "plant" },
  { "word": "ක්ෂුද්‍රාභිජනන", "meaning": "අබ, කළුඅබ, අක්මැල්ල", "category": "plant" },

  // --- පිටුව 150 (image_924725.jpg) ---
  { "word": "ක්ෂුද්‍රාම්ලා", "meaning": "ඇඹුල් ඇඹිලිය", "category": "plant" },
  { "word": "ක්ෂුද්‍රාමිලක සංඥා", "meaning": "කණ්ඩ වාක්‍යය", "category": "treatment" },
  { "word": "ක්ෂුද්‍රෙලා", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ක්ෂුද්‍රොදුම්බරිකා", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "ක්ෂුධාකුගල", "meaning": "අන්ඳර ගස", "category": "plant" },
  { "word": "ක්ෂුප", "meaning": "දඹු", "category": "treatment" },
  { "word": "ක්ෂුමා", "meaning": "අවරිය ගස", "category": "plant" },
  { "word": "ක්ෂුමිගෝධක", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "ක්ෂුර", "meaning": "ඉකිරි, රඹුක්, වැලුක්, කලු අගිල්", "category": "plant" },
  { "word": "ක්ෂුරක", "meaning": "මදටිය, මාරා, පොල්, ගොකටු", "category": "plant" },
  { "word": "ක්ෂුරාදිකා", "meaning": "නෙරෙංචි, සිහින් ගොකටු", "category": "plant" },
  { "word": "ක්ෂුරාග්‍ර", "meaning": "ගොකටු", "category": "plant" },
  { "word": "ක්ෂුරිකාපත්‍ර", "meaning": "බට", "category": "plant" },
  { "word": "ක්ෂුල්ලපත්‍ර", "meaning": "ඉළුක් තණ", "category": "plant" },
  { "word": "ක්ෂුව", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "ක්ෂේක", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ක්ෂේමකන්‍ධ", "meaning": "කණේරු ගස", "category": "plant" },
  { "word": "ක්ෂේතප්‍රා", "meaning": "කටුවැල්බටු, සුදු කටුවැල්බටු", "category": "plant" },
  { "word": "ක්ෂේතබුද්ධී", "meaning": "එල කටුවැල්බටු", "category": "plant" },
  { "word": "ක්ෂේත්‍ර මානිකා", "meaning": "වල් අසමෝදගම්", "category": "plant" },
  { "word": "ක්ෂේත්‍රමාලිකා", "meaning": "වදකහ", "category": "plant" },
  { "word": "ක්ෂේත්‍රරාගා", "meaning": "කැකිරි, සිහින් කැකිරි", "category": "plant" },
  { "word": "ක්ෂේත්‍රසම්භව", "meaning": "බණ්ඩක්කා", "category": "plant" },
  { "word": "ක්ෂේත්‍රාමලකී", "meaning": "පිටවක්කා, බිම්තල්", "category": "plant" },
  { "word": "ක්ෂේත්‍රැ", "meaning": "තිරිඟු", "category": "plant" },
  { "word": "ක්ෂේම", "meaning": "අරණක්කසා", "category": "plant" },
  { "word": "ක්ෂේමික", "meaning": "හිඟුරුපියලි, අරණක්කසා", "category": "plant" },
  { "word": "ක්ෂේමමුල", "meaning": "දිවුල් ගස", "category": "plant" },
  { "word": "ක්ෂේමිකා", "meaning": "කහ", "category": "plant" },
  { "word": "ක්ෂෛව", "meaning": "කෙසෙල්, විල", "category": "plant" },
  { "word": "ක්ෂෞමබලගලා", "meaning": "තුවර ගස", "category": "plant" },
  { "word": "ක්ෂෞමබ", "meaning": "තිත්ත වැටකොළු, ජවක නම් ඔසු වෙසෙස, රතු වරා ගෙඩිය", "category": "plant" },
  { "word": "ක්ෂෞවපල්ල", "meaning": "අත්තික්කා", "category": "plant" },
  { "word": "ක්ෂෞවම්බගලා", "meaning": "තෝර", "category": "plant" },
  { "word": "ක්ෂෞතෘසති", "meaning": "කිරිදි වැල්", "category": "plant" },
  { "word": "ක්ෂේත්‍රතුක", "meaning": "කිරිදි වැල්", "category": "plant" },
  { "word": "ක්ෂෝරෙයි", "meaning": "හුළුකැන් (ලුණු කැඳ)", "category": "treatment" },
  { "word": "ක්ෂෝමිකා", "meaning": "චොරක නම් ගන්ධ ද්‍රව්‍යය", "category": "treatment" },
  { "word": "ක්ෂෞලි", "meaning": "කවෙළු (අෂ්ටක වගියේ ඔසුවක්)", "category": "treatment" },
  { "word": "ක්ෂෞද්‍ර", "meaning": "මීපැණි, සපුගස", "category": "treatment" },
  { "word": "ක්ෂෞද්‍රප්‍ර", "meaning": "මිගුටි", "category": "treatment" },
  { "word": "ක්ෂෞද්‍රපා", "meaning": "මඩු, ගකිරා (මීපැණි උක් සකුරු)", "category": "treatment" },
  { "word": "ක්ෂෞද්‍රධාතු", "meaning": "මීපැණි", "category": "treatment" },
  { "word": "ක්ෂෞද්‍රබොධය", "meaning": "මිගුටි", "category": "treatment" },
  { "word": "ක්ෂෞද්‍රප්‍රිය", "meaning": "ගම්මිරිස්, හෙල මීගස", "category": "plant" },
  { "word": "ක්ෂෞද්‍රමේභ", "meaning": "මධුමේහය", "category": "symptom" },
  { "word": "ක්ෂෞද්‍රගකිරා", "meaning": "මඩු ශකිරා", "category": "treatment" },
  { "word": "ක්ෂෞත්‍රෙය", "meaning": "මිගුටි", "category": "treatment" },
  { "word": "ක්ෂෞමී", "meaning": "හණගස", "category": "plant" },
  { "word": "ඛ", "meaning": "මිණීරන්", "category": "treatment" },
  { "word": "ඛබ්බර", "meaning": "ලොත්, රත්ලොත්, පුවක්", "category": "plant" },
  { "word": "ඛඟන", "meaning": "ඉකිරි ගස", "category": "plant" },
  { "word": "ඛග්‍ර", "meaning": "මිණීරන්, (ලුහුක)", "category": "treatment" },
  { "word": "ඛග", "meaning": "රන්මස්සිදු, (සවණිමක්ෂිකා)", "category": "treatment" },
  { "word": "ඛගවනු", "meaning": "දෙල් ගස", "category": "plant" },
  { "word": "ඛගන්ත්‍ර", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ඛඩගට", "meaning": "මහවාළුක්", "category": "plant" },

  // --- පිටුව 151 (image_924a64.jpg) ---
  { "word": "ඛජ්ජූරී", "meaning": "හිඳි", "category": "plant" },
  { "word": "ඛජ්ජූර", "meaning": "රත්ලොත්, පුවක්", "category": "plant" },
  { "word": "ඛට්ව", "meaning": "පෙනෙල වැල", "category": "plant" },
  { "word": "ඛට්වි", "meaning": "නියඟරා, මග ගොත්සුතු කැකිරි", "category": "plant" },
  { "word": "ඛටාල", "meaning": "සුලුකුර", "category": "treatment" },
  { "word": "ඛඩක", "meaning": "දේවතාඩ වාක්‍යය", "category": "treatment" },
  { "word": "ඛඩපුෂප", "meaning": "ගිවූලු, ඇඹුල් ඇඹිලිය, මිරිස්, කළුදුරු, නිවුල් යන මෙයින් පිසු මෝරු වෙසෙසක්", "category": "treatment" },
  { "word": "ඛනින", "meaning": "ගම්මිරිස්", "category": "plant" },
  { "word": "ඛණ්ඩ", "meaning": "උක්සකුරු, ගස්කැලිය, බුලල් ලුණු", "category": "treatment" },
  { "word": "ඛණ්ඩක", "meaning": "මුංපලා", "category": "plant" },
  { "word": "ඛණ්ඩකා", "meaning": "සවාස්, සකීරා", "category": "treatment" },
  { "word": "ඛණ්ඩගුළු", "meaning": "කබසකුරු", "category": "treatment" },
  { "word": "ඛණ්ඩජ", "meaning": "උක්සකුරු, සවාස්, සකීරා", "category": "treatment" },
  { "word": "ඛණ්ඩොද්භව", "meaning": "සවාස්, සකීරා", "category": "treatment" },
  { "word": "ඛණ්ඩන", "meaning": "සුන් සහල් (කඩසාල් = කැඩුන හාල්)", "category": "treatment" },
  { "word": "ඛණ්ඩරාජ", "meaning": "බෝදි ඇට", "category": "plant" },
  { "word": "ඛණ්ඩරාල්", "meaning": "සූකිරි", "category": "treatment" },
  { "word": "ඛණ්ඩලවන", "meaning": "බලල්ලුණු", "category": "treatment" },
  { "word": "ඛණ්ඩවිජාර", "meaning": "සකුරු", "category": "treatment" },
  { "word": "ඛණ්ඩශාලුක", "meaning": "උක්සකුරු", "category": "treatment" },
  { "word": "ඛණ්ඩසකීරා", "meaning": "උක්සකුරු, සූකිරි, සීනි", "category": "treatment" },
  { "word": "ඛණ්ඩසිතා", "meaning": "කබසකුරු, සීනි, සකුරු", "category": "treatment" },
  { "word": "ඛණ්වධාර", "meaning": "මෝරු", "category": "treatment" },
  { "word": "ඛණ්වහාරා", "meaning": "මෝරු", "category": "treatment" },
  { "word": "ඛණ්ඩී", "meaning": "ගස්කැලිය, බලල්ලුණු, සූකිරි", "category": "treatment" },
  { "word": "ඛණ්ඩමාලක", "meaning": "නෙල්ලියුණු, නෙල්ලි ගෙඩිය", "category": "plant" },
  { "word": "ඛණ්ඩිකා", "meaning": "මුං පලා", "category": "plant" },
  { "word": "ඛණ්ඩිත", "meaning": "මිරිස්, කලත් මෑ (කොල්ලු)", "category": "plant" },
  { "word": "ඛණ්ඩනකණ්ඩ", "meaning": "බතල", "category": "plant" },
  { "word": "ඛණ්ඩින්", "meaning": "වල්මුං", "category": "plant" },
  { "word": "ඛණ්ඩ විකාර", "meaning": "රසකිඳ, කබසකුරු", "category": "treatment" },
  { "word": "ඛණ්ඩ", "meaning": "වල්මුං", "category": "plant" },
  { "word": "ඛණ්ඩීර", "meaning": "රන්වන්මුං", "category": "plant" },
  { "word": "ඛණ්ඩොත්භව", "meaning": "කබසකුරු, රසකිඳ", "category": "treatment" },
  { "word": "ඛදර", "meaning": "රත් කිහිරි, නිදිකුම්බා", "category": "plant" },
  { "word": "ඛදිකා", "meaning": "විලඳ", "category": "treatment" },
  { "word": "ඛදර", "meaning": "කිණිහිරිය, කිහිරි, හිඹුරා, රක් බුජ්ජද (සාරණ)", "category": "plant" },
  { "word": "ඛදිර කණ්ඩක", "meaning": "රත්කිහිරිය", "category": "plant" },
  { "word": "ඛදර පත්‍රක", "meaning": "රත්කිහිරිය, සල්ගස", "category": "plant" },
  { "word": "ඛදර පත්‍රිකා", "meaning": "නිදිකුම්බා, දකින් තරු (වැල්මදට) හිඟුරා", "category": "plant" },
  { "word": "ඛදරවල්ලී", "meaning": "කිණිහිරි ගස", "category": "plant" },
  { "word": "ඛදරපීට්", "meaning": "හෝපලු ඇට", "category": "plant" },
  { "word": "ඛදරශිකී", "meaning": "කයිප්පු", "category": "treatment" },
  { "word": "ඛදරසාර", "meaning": "කයිප්පු, කිහිරි මැලියම්", "category": "treatment" },
  { "word": "ඛදිරා", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "ඛදිරාමුගහ", "meaning": "කිහිරි ගස, හිඹුරා", "category": "plant" },
  { "word": "ඛදිරාහ්ව", "meaning": "කිහිරි ගස, හිඹුරා", "category": "plant" },
  { "word": "ඛදිරී", "meaning": "නිදිකුම්බා වැල්, ලාකඩ", "category": "plant" },
  { "word": "ඛදිරිකා", "meaning": "ලාකඩ, නිදිකුම්බා", "category": "plant" },
  { "word": "ඛදිරොද්භුහ", "meaning": "කයිප්පු, කිහිරි මැලියම්", "category": "treatment" },
  { "word": "ඛදිරොපම", "meaning": "තෙලකිණිරි, සිතියා ගස", "category": "plant" },
  { "word": "ඛද්‍ය පත්‍රී", "meaning": "කිහිරි ගස", "category": "plant" },
  { "word": "ඛබ්", "meaning": "අල", "category": "plant" },
  { "word": "ඛබ් බක්", "meaning": "නෙරෙංචි", "category": "plant" },
  { "word": "ඛබ් පුෂ්ප", "meaning": "අශෝක (හෝපලු)", "category": "plant" },
  { "word": "ඛබ් පලා", "meaning": "කිරිබදු", "category": "plant" },
  { "word": "ඛබ්ලොද්භව", "meaning": "ඇඹුල", "category": "plant" },
  { "word": "ඛන්ධවල්ලී", "meaning": "කිරිබදු", "category": "plant" },

  // --- පිටුව 152 (image_924d8f.jpg) ---
  { "word": "ඛපුට", "meaning": "වක්නිය", "category": "treatment" },
  { "word": "ඛපුර", "meaning": "වම්මුතු, දිවිපසුරු, කළු ලුණු, කුන්දිරුක්කන්, පුවක් ගස", "category": "treatment" },
  { "word": "ඛපුරාපුර", "meaning": "කුන්දිරුක්කන් ධූපය", "category": "treatment" },
  { "word": "ඛපුෂ්ප", "meaning": "කොස් ගස", "category": "plant" },
  { "word": "ඛමුලි", "meaning": "දියපරබලා", "category": "plant" },
  { "word": "ඛප්", "meaning": "කැසීම", "category": "symptom" },
  { "word": "ඛජීකා", "meaning": "උපදංග රෝගය", "category": "symptom" },
  { "word": "ඛජ්ජ", "meaning": "රටබුදි (යොන්බුදි)", "category": "treatment" },
  { "word": "ඛජ්ජසක", "meaning": "වරා, බෝදි ඇට, අත්තික්කා", "category": "plant" },
  { "word": "ඛර්ජුර", "meaning": "රටබුදි, ගල්කසඹිලිය, පුවක් ගස, බිම්තල්, මුද්දරප් පලම්", "category": "plant" },
  { "word": "ඛර්ජුර පත්‍රිකා", "meaning": "කිහිරි, රත්කිහිරි, යොන්බුදි", "category": "plant" },
  { "word": "ඛර්ජුර මස්සනක", "meaning": "හින්ඳබ (ඉඳිබබ)", "category": "plant" },
  { "word": "ඛර්ජුරී", "meaning": "මොරගස, හිඳි ගස, (යොන් ඉඳි) උවරල", "category": "plant" },
  { "word": "ඛර්ජුරිකා වාක්‍යය", "meaning": "හිඳි ගස", "category": "plant" },
  { "word": "ඛර්ජුරී", "meaning": "රටබුදි, වනයෙහි වූ මොර, උවරල", "category": "plant" },
  { "word": "ඛර්ජරිකා", "meaning": "රිදීහුන්තම්", "category": "treatment" },
  { "word": "ඛර්බ", "meaning": "සෙව්වන්දි", "category": "plant" },
  { "word": "ඛර්බුජ", "meaning": "කැකිරි", "category": "plant" },
  { "word": "ඛර්යරිකා", "meaning": "රිදීහුන්තම්", "category": "treatment" },
  { "word": "ඛර්වා", "meaning": "සිරිවැඩි බැබිල", "category": "plant" },
  { "word": "ඛර්වෘෂ", "meaning": "වට්ටක්කා", "category": "plant" },
  { "word": "ඛර", "meaning": "යක්බේරිය, තල්, එල නික, දේවදාලිය, තිඹිරි, දිවිපසුරු, නික", "category": "plant" },
  { "word": "ඛරක", "meaning": "පැපිලිය", "category": "plant" },
  { "word": "ඛරකෝම", "meaning": "සිහින් මිදි", "category": "plant" },
  { "word": "ඛරකාෂ්ටිකා", "meaning": "සුළු බැවිල, බැවිල", "category": "plant" },
  { "word": "ඛරගන්ධ", "meaning": "ගස්කැලිය, සිරිවැඩි බැබිල", "category": "plant" },
  { "word": "ඛරගන්තිකා", "meaning": "සිරිවැඩි බැබිල, වල් තලා ගස", "category": "plant" },
  { "word": "ඛරගකනි", "meaning": "සිරිවැඩි බැබිල", "category": "plant" },
  { "word": "ඛරසයන", "meaning": "නාමල් රේණු", "category": "plant" },
  { "word": "ඛරවර්ධ", "meaning": "දුම්මල, ගැටතිඹුල්, සල්, තේක්ක", "category": "treatment" },
  { "word": "ඛරන්ව", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "ඛරතුන්වක", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "ඛරද", "meaning": "ගස්කැලිය, කිරිබදු", "category": "plant" },
  { "word": "ඛරදංශූ", "meaning": "ගොකටු", "category": "plant" },
  { "word": "ඛරදණ්ඩී", "meaning": "නෙළුම් මල්", "category": "plant" },
  { "word": "ඛරදණ්ඩිකා", "meaning": "ගස්කැලිය", "category": "plant" },
  { "word": "ඛරදලා", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "ඛරපණ", "meaning": "අත්තන ගස", "category": "plant" },
  { "word": "ඛරබන්තිකා", "meaning": "සිරිවැඩි බැබිල", "category": "plant" },
  { "word": "ඛරාදිනී", "meaning": "රුතැණිය", "category": "plant" },
  { "word": "ඛරපත්‍ර", "meaning": "ලුණුවරණ, නිඹුල්, ගැට නිඹුල්, තියඳ, කිහිරි, තලා, සකුරු, ඉල්ලගස, එල කිහිරි ගස", "category": "plant" },
  { "word": "ඛරපත්‍රස", "meaning": "කරවිකලා, බෝලිද්ද තිලක වාක්‍යය (තල ගස)", "category": "plant" },
  { "word": "ඛරපර්ණී", "meaning": "ගැටනිඹුල්, කොට දිඹුලා", "category": "plant" },
  { "word": "ඛරපර්ණිකා", "meaning": "කරල්සැබෝ", "category": "plant" },
  { "word": "ඛරපල්ලව", "meaning": "ගැටනිඹුල් ගස", "category": "plant" },
  { "word": "ඛරපාෂ්ය", "meaning": "ගිවූලු ගස", "category": "plant" },
  { "word": "ඛරපෂ්ප", "meaning": "ගිවූලු ගස", "category": "plant" },
  { "word": "ඛරපුෂ්ප", "meaning": "වේලා, රම්මානිස්ස, තියඳ, කෝවක්කා, මල් සුදු වේලා, කවුඩු කැකිරි, රත් කරල් සැබෝ", "category": "plant" },
  { "word": "ඛරමඤ්ජරී", "meaning": "කරල්සැබෝ", "category": "plant" },
  { "word": "ඛරමදී", "meaning": "හෙලසැබෝ", "category": "plant" },
  { "word": "ඛරමුබ", "meaning": "වේලාගස", "category": "plant" },
  { "word": "ඛරයදවිකා", "meaning": "සුලුබැවිල (හීන් බැබිල)", "category": "plant" }
];