// data_279_287.js - පිටු 279 සිට 287 දක්වා ඉල්ලුම් කළ සියලුම වචන සහ විස්තර
const data_extra_279_287 = [
    // --- පිටුව 279 ---
    { 
        "word": "නිල් ඇවරිය", 
        "meaning": "කොළ (යුෂ) තද නිල් පැහැයකින් යුක්ත නිසා මේ වර්ගයට සංස්කෘත භාෂාවෙන් නීලි - නීලිකා යන නම් ව්‍යවහාර වේ. ලංකාවේ මුල සිට පැවත එන වර්ගය සහ ඉන්දියාවෙන් ගෙනැවිත් බෝ කරණ ලද වර්ගය වශයෙන් දෙකකි. විශේෂ ප්‍රතිකර්මයක්: නිල් ඇවරිය මුල් කලන් දෙකහමාරක් ගෙන පත අට පත එකට කපාය කර (සිඳ) වරකට එළඟිතෙල් මේස හැඳි දෙකක් බැගින් දමා උදේ-සවස කෑමට පැයකට කලින්, මේසේ කෂාය හතරක් පානය කිරීමෙන් ශරීරගතවූ කවර වර්ගයේ පිස්සු බළු විෂක් වුවද සුව වෙයි.", 
        "category": "plant" 
    },

    // --- පිටුව 280 ---
    { "word": "නිෂ්කණ්ටක", "meaning": "ලුනුවරණ", "category": "plant" },
    { "word": "නිෂ්කුටි", "meaning": "සිහින් එන්සාල්, මහ එන්සාල්", "category": "plant" },
    { "word": "නිෂ්ටකා", "meaning": "ත්‍රස්තාවාලු", "category": "plant" },
    { "word": "නිෂ්පත්‍රිකා", "meaning": "කංසා, දත්දක්", "category": "plant" },
    { "word": "නිපට", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "නිසි", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "නිසිපුෂ්පා", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "නිස්කාසක්‍ෂීර", "meaning": "තිරිඟු", "category": "plant" },
    { "word": "නිස්චය", "meaning": "යක්නැඹ", "category": "plant" },
    { "word": "නිස්තුසපත්‍ර", "meaning": "රඹුක්, වෘලුක්, මහ උක්", "category": "plant" },
    { "word": "නිස්ත්‍රින්‍ශපත්‍රක", "meaning": "දර්භ, මහ උක්", "category": "plant" },
    { "word": "නිස්ස්නෙහ ඵල", "meaning": "කටුවැල් බටු, හෙළ කටුවැල්බටු", "category": "plant" },
    { "word": "නිස්පාව", "meaning": "අවරවැල් (මහ මෑ)", "category": "plant" },
    { "word": "නිස්සාර", "meaning": "බිම්කොහොඹ, තොටිල, එරබු", "category": "plant" },
    { "word": "නිස්සාරකා", "meaning": "හෙළ එරබු, නවහන්දි එරබු", "category": "plant" },
    { "word": "නිස්සාරගන්ධා", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "නිස්සාවො", "meaning": "බනිත් පෙරැ කෘද", "category": "plant" },
    { "word": "නිසුහ", "meaning": "කෘද", "category": "plant" },
    { "word": "නිසුනී", "meaning": "යොන්ඉඳි", "category": "plant" },
    { "word": "නිසද පොතකය", "meaning": "බෙහෙත් අඹරන ලබ (දරු)ගල", "category": "equipment" },
    { "word": "නිසදය", "meaning": "බෙහෙත් අඹරණ (යට) ගල", "category": "equipment" },
    { "word": "නිසා", "meaning": "කහ", "category": "plant" },
    { "word": "නිසින්ධු", "meaning": "නික", "category": "plant" },
    { "word": "නිසුල්", "meaning": "මිදෙල්ල", "category": "plant" },
    { "word": "නිසෘතා", "meaning": "ත්‍රස්තාවාලු", "category": "plant" },
    { "word": "නිහාර", "meaning": "පිත්ත", "category": "treatment" },
    { "word": "නිහිර", "meaning": "තඹ", "category": "mineral" },
    { "word": "නිලබපණෙයි", "meaning": "බිම්තල්, ඌරල", "category": "plant" },

    // --- පිටුව 281 ---
    { "word": "නිළපත්‍ර", "meaning": "රත් මහනෙල්, දෙළුම්, සාරණ, පොල්පලා, නියඳ, තිරිඟු", "category": "plant" },
    { "word": "නිලපත්‍රී", "meaning": "නියඳ", "category": "plant" },
    { "word": "නිලපර්ණී", "meaning": "රත්හඳුන්, ගිඩි", "category": "plant" },
    { "word": "නිලපුරණ්ඩි", "meaning": "උඳුපියලි", "category": "plant" },
    { "word": "නිලපුරී", "meaning": "උඳුපියලි", "category": "plant" },
    { "word": "නිලපුෂ්ප", "meaning": "විෂ්ණුක්‍රාන්ති, නිල්වන් කිකිරිඳිය, ගිරිනිල්ල, නිල්කටුකරඬු, බේරු, නිල් කටරොළු", "category": "plant" },
    { "word": "නිලපුෂ්පා", "meaning": "විෂ්ණුක්‍රාන්ති, නිල් කටරොළු", "category": "plant" },
    { "word": "නිලපුෂ්පී", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "නිල ප්‍රියක", "meaning": "නිල්පියල් රූක", "category": "plant" },
    { "word": "නිලඵලා", "meaning": "දඹ, ජම්බු ගස", "category": "plant" },
    { "word": "නිලභූමි මලක්‍ෂාර", "meaning": "රිදීතුත්ථ", "category": "mineral" },
    { "word": "නිලභෙද", "meaning": "කටුකරෝහණ", "category": "plant" },
    { "word": "නිලමඤ්ජරිකා", "meaning": "කලු නික, කරබෙරිය", "category": "plant" },
    { "word": "නිලමල්ලිකා", "meaning": "බෙලි", "category": "plant" },
    { "word": "නිලමාලිකා", "meaning": "බෙලි", "category": "plant" },
    { "word": "නිලය", "meaning": "රුක් අඟුණ, කලු ලුණු", "category": "plant" },
    { "word": "නිලයෂ්ටිකා", "meaning": "බේරු", "category": "plant" },
    { "word": "නිලයින්", "meaning": "ලුහුලා", "category": "plant" },
    { "word": "නිලරත්ත", "meaning": "ඉඟිනිල", "category": "plant" },
    { "word": "නිලරූප්", "meaning": "තිඹිරි, කොටදිඹුලා", "category": "plant" },
    { "word": "නිලලතා", "meaning": "නිල්වැල්", "category": "plant" },
    { "word": "නිලව", "meaning": "ලියනගලා", "category": "plant" },
    { "word": "නිලවෘක්‍ෂ", "meaning": "නිල් පියල් ගස", "category": "plant" },
    { "word": "නිලවෘක්‍ෂා", "meaning": "නිල් මුරුවා වැල", "category": "plant" },
    { "word": "නිල වලි ශූර", "meaning": "කටරොළු වැල", "category": "plant" },
    { "word": "නිල වල්ලී", "meaning": "සිහින් දුම්බ, පිප්පිලි", "category": "plant" },
    { "word": "නිලවාකසි", "meaning": "සන්නියට දුම්කට ගන්නා ද්‍රව්‍යයක්", "category": "treatment" },
    { "word": "නිලවෙම්බු", "meaning": "බිම් කොහොඹ", "category": "plant" },
    { "word": "නිලශෙඛරිකා", "meaning": "ගිරිනිල්ල, නිල් කටුකරඬු", "category": "plant" },
    { "word": "නිලසාර", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "නිලසින්ධුක", "meaning": "කළුනික, කරබෙරිය", "category": "plant" },
    { "word": "නිලසෙපාලිකා", "meaning": "කළුතලා", "category": "plant" },
    { 
        "word": "නුග", 
        "meaning": "නයග්‍රොධ (වනස්පතිවෘක්‍ෂය). කිරිපලු නුග, (අප්පාල) කිරි නුග (කලහ), ඇසතු නුග, බෙහෙත් නුග, බිත් නුග යයි නුග වර්ග කීපයකි. කිරි නුග (කලහ) ගැන විස්තරයක් ඇත. බෙහෙත් නුග අරළු (ආරුවත්=අතු වලින් සහ කඳේ ඉහළින් පහතට ඇදෙන මුල්) යුෂ බහු මූත්‍ර (දිය වැඩියා) රෝගයට ප්‍රත්‍යක්ෂ ඖෂධයකි.", 
        "category": "plant" 
    },

    // --- පිටුව 282 ---
    { "word": "නුග අරළු", "meaning": "නුග මුල්, (නුග ආරුවත්)", "category": "plant" },
    { "word": "නුග දළු", "meaning": "වටසිංග (ඇතාම්)", "category": "plant" },
    { "word": "නුදුඹර", "meaning": "දික්ත", "category": "plant" },
    { "word": "නුපුන්", "meaning": "නොපිපෙන (මල් පල හට නොගන්න)", "category": "plant" },
    { "word": "නුබමිනී", "meaning": "වරාගස", "category": "plant" },
    { "word": "නුවරඑලිය", "meaning": "කපු ගස", "category": "plant" },
    { "word": "නුසෝසායි", "meaning": "අරළු", "category": "plant" },
    { "word": "නුහි", "meaning": "දක්", "category": "plant" },
    { "word": "නුහුසු", "meaning": "ගෝනුස්සන්", "category": "animal" },
    { "word": "නූතන", "meaning": "නික", "category": "plant" },
    { "word": "නූද", "meaning": "බූහමදුරු", "category": "plant" },
    { "word": "නූනාමරම්", "meaning": "අහු ගස්", "category": "plant" },
    { "word": "නූසොයාසි", "meaning": "අරළු", "category": "plant" },
    { "word": "නෘත්‍යකි", "meaning": "කළුනික", "category": "plant" },
    { "word": "නෘප", "meaning": "කුවෙරල", "category": "plant" },
    { "word": "නෘපකණ්", "meaning": "මීග ලුහුටු", "category": "plant" },
    { "word": "නෘපති", "meaning": "මය ගොත් සුතු කැකිරි", "category": "plant" },
    { "word": "නෘපද්‍රැම", "meaning": "එරහැදි, (ඇසළ)", "category": "plant" },
    { "word": "නෘපප්‍රිය", "meaning": "වටකේ, හිඳි, මඟුලුහුටු, අඹ, මහ ඉඳි", "category": "plant" },
    { "word": "නෘපප්‍රිය ඵල", "meaning": "වැටකොළු", "category": "plant" },
    { "word": "නෘපාංශුහු", "meaning": "මරිසුව, (මුරුංගා)වැල් මුරුංගා", "category": "plant" },
    { "word": "නෙක්කන්ති", "meaning": "දේවදාර", "category": "plant" },
    { "word": "නෙට්ටි", "meaning": "නැටි", "category": "plant" },
    { "word": "නෙබුල්", "meaning": "තිබුල් නම් ඔසු වර්ගය", "category": "plant" },
    { "word": "නෙබුමිනාලි", "meaning": "වසතැල්ල", "category": "plant" },
    { "word": "නෙත් සිලිල්", "meaning": "කඳුලු", "category": "treatment" },
    { "word": "නෙත්‍රා", "meaning": "කොහොඹ, බුලත්", "category": "plant" },
    { "word": "නේත්‍රෞෂධ", "meaning": "කටුකරඬු, වරා, පිත කරෝහිණී", "category": "plant" },

    // --- පිටුව 283 ---
    { "word": "නේත්‍රෞෂධී", "meaning": "මාබගඟු", "category": "plant" },
    { "word": "නේපා", "meaning": "නුග", "category": "plant" },
    { "word": "නේපාල", "meaning": "ජයපාල", "category": "plant" },
    { "word": "නේමින්", "meaning": "කොඹු, කෝන්", "category": "plant" },
    { "word": "නේමිවෘක්‍ෂ", "meaning": "මුරුත, හෙළකිහිරිය", "category": "plant" },
    { "word": "නේමිසාර", "meaning": "හිඹුටු, කළු කිහිරිය", "category": "plant" },
    { "word": "නේර්වාලම්", "meaning": "ජයපාල", "category": "plant" },
    { "word": "නේරී", "meaning": "කැප්පෙටියා (කැප්පෙට්ටියා), ගස්කැප්පෙට්ටියා, වැල්කැප්පෙට්ටියා යයි වර්ග දෙකකි. මේ දෙවර්ගයම ඖෂධවශයෙන් ගනිති. එයිනුත් කැඩුම්-බිඳුම්-ගෙඩි වන-පිළිකා වලට ත් තෙල් වර්ග හැඳීමට ත් වැඩි වශයෙන් අවශ්‍ය වන්නේ වැල් කැප්පෙට්ටියාය. ගස්කැප්පෙට්ටියා ඖෂධ පිණිස හා බුලත්-අමු මිරිස්-ඉඟුරු පාත්ති පොහොර කිරීමට ත් ගනිති.", "category": "plant" },
    { 
        "word": "නොනන්කෙන්ද", 
        "meaning": "මෙය අංකෙන්ද වර්ගයට අයත් වූ අංකෙන්ද ගසට බෙහෙවින් සමාන ගසකි. මේ ගසත් අංකෙන්ද ගසත් අතර ඇති එකම වෙනස නම්: අංකෙන්ද ගසේ කුඩා රිකිලි වල දෙපැත්තට බෙදී යන කොළ දෙක වෙනුවට මේ ගසේ දෙපැත්තට බෙදී යන කොළ පස බැගින් ඇති නටු දෙක බැගින් පිහිටීම පමණකි. මේ ගසේ පොතු තැල්මට හා ඉදිමුමට කහ ලුණු ලා කොටා මලවා බඳිති. කැඩුම් - බිඳුම් වෙදකමේ ඖෂධ යෝග වලට ද මේ පොතු මිශ්‍ර කරති.", 
        "category": "plant" 
    },
    { "word": "නොච්චි", "meaning": "හෙළ නික, (සිලුවර)", "category": "plant" },
    { "word": "නොතිත", "meaning": "වෙඬරු", "category": "treatment" },
    { "word": "නොමල්", "opacity": "දිවුල්", "category": "plant" },
    { "word": "නොරපලම්", "meaning": "මොර", "category": "plant" },
    { "word": "නොද්දල", "meaning": "ගෙඳ පලා", "category": "plant" },
    { "word": "නෝනේමි", "meaning": "කෝන්ගස, කොබුගස", "category": "plant" },
    { "word": "නෝස්", "meaning": "සාදික්කා ගෙඩිය", "category": "plant" },
    { "word": "නෛග්‍රොධා", "meaning": "නුග, නුග පලා", "category": "plant" },
    { "word": "නෛපාල", "meaning": "ත්‍රස්තාවාලු, කොහොඹ, ජයපාල", "category": "plant" },
    { "word": "නෛපාලි", "meaning": "රත් හිරිගල්, යොන් තඹ, මනෝසිල", "category": "plant" },
    { "word": "නෛපාලිකා", "meaning": "රත්හිරිගල්", "category": "plant" },
    { "word": "නෛමාලී", "meaning": "මනෝසිල, රත්හිරිගල්", "category": "plant" },
    { "word": "නෛමාලිකා", "meaning": "මනෝසිල", "category": "plant" },
    { "word": "නෛමිල්‍ය", "meaning": "පුද්ගල මල්", "category": "plant" },
    { "word": "නෛලකාන්ත", "meaning": "අබ", "category": "plant" },

    // --- පිටුව 284 ---
    { "word": "න්‍යග්‍රොධ", "meaning": "නුග, මහ නුග", "category": "plant" },
    { 
        "word": "න්‍යග්‍රොධාදිගණය", 
        "meaning": "නුග, දිවුල්, ඇසතු, පුලිල, මී ගස්, නිඹිරි, මොර, මහබෙබර, කදුරු, මාරා, අඹ, හෝපලු, (නොමුවහු) කෑල, බදුල්ල, මුවකිරිය, ලොඹු, මහ දඹ, දියදඹ, ගල්දඹ යන මේ ගණය පිත්, ලේ, මේහ ජය ගන්නේය. ව්‍රණ, දාහ, යෝනි රෝග නසන්නේ ය.", 
        "category": "compound" 
    },
    { "word": "න්‍යග්‍රොධාශ්ව", "meaning": "මිනුග, මීකන්පලා", "category": "plant" },
    { "word": "න්‍යග්‍රොධි", "meaning": "මීකන්පලා, මිනුග", "category": "plant" },
    { "word": "න්‍යබගුනුරූහ", "meaning": "තොටිල", "category": "plant" },
    { "word": "න්‍යමූප්ප", "meaning": "කාමරංගා ගෙඩි", "category": "plant" },
    { 
        "word": "පංගන් වැල්", 
        "meaning": "පාලග වැල් = පාංගා වැල් (වෙනි වැල් කොළ වලට සමාන වෙනි වැල් මෙන් විශාලව වැවෙන වර්ගයක්. මේ වර්ගය තුවාල වෙදකමට ත්, නොයෙක් දේ බැඳීමට(වෙලීමට)ත් ගනිති)", 
        "category": "plant" 
    },
    { "word": "පාංචරස", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "පක්", "meaning": "ගෙඩිය, ඉදුණු පල", "category": "plant" },
    { "word": "පකතිනි", "meaning": "කාසුන්", "category": "plant" },
    { "word": "පකකුර", "meaning": "පතඟි", "category": "plant" },
    { "word": "පක්තොට්ටික්කායි", "meaning": "රේරු ගස", "category": "plant" },
    { "word": "පකතිඤ්ජා", "meaning": "රක්තාතිසාරය", "category": "treatment" },
    { "word": "පක්තුරු", "meaning": "බුලු ගස", "category": "plant" },
    { "word": "පක්‍ෂකෘත්", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "පක්‍ෂඵල", "meaning": "කටුපිල, පැසුණු ගෙඩිය", "category": "plant" },
    { "word": "පක්වාශය", "meaning": "උදරයෙහි ආහාර පැසෙන කොටස", "category": "anatomy" },
    { "word": "පක්‍ෂබීර", "meaning": "නෙළුම් ඇට", "category": "plant" },
    { "word": "පක්‍ෂම", "meaning": "නෙළුම් රේණු", "category": "plant" },
    { "word": "පක්‍ෂි", "meaning": "රන්මැක්සිදු (ස්වර්ණමාක්‍ෂික)", "category": "mineral" },
    { "word": "පක්‍ෂිවාස", "meaning": "ගස", "category": "plant" },
    { "word": "පකාගක", "meaning": "ලෝකඩ", "category": "mineral" },
    { "word": "පකිරිය", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "පකිසරණ", "meaning": "කටුපිල ගස", "category": "plant" },
    { "word": "පගහව", "meaning": "කුණු කරඳ", "category": "plant" },
    { "word": "පගර", "meaning": "පහුරු", "category": "plant" },
    { "word": "පගලි", "meaning": "රීදුත්ත", "category": "plant" },
    { "word": "පංක", "meaning": "මඩ", "category": "nature" },
    { "word": "පංකජුරත්", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "පංකජප්", "meaning": "නෙළුම්මල", "category": "plant" },
    { "word": "පංකාතිප්ප්", "meaning": "නෙළුම් ඇට, රම්මා නිස්ස", "category": "plant" },
    { "word": "පංකාරුහ", "meaning": "නෙළුම් මල්", "category": "plant" },
    { "word": "පංකජාභරණා", "meaning": "නෙළුම්මල", "category": "plant" },
    { "word": "පංකිල", "meaning": "මඩ", "category": "nature" },
    { "word": "පංකාර", "meaning": "පෙද", "category": "plant" },
    { "word": "පංකෙරුහ", "meaning": "නෙළුම්මල්", "category": "plant" },
    { "word": "පච්චඉංචි", "meaning": "අමු ඉඟුරු", "category": "plant" },
    { "word": "පච්චකොළානු", "meaning": "අඳුනලාගස්", "category": "plant" },
    { "word": "පච්චපත්නි", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "පච්චසෙම්මුල්ලි", "meaning": "නිල් කටුකරඬු", "category": "plant" },
    { "word": "පච්චිපත්නි", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "පච්චිලෙල", "meaning": "කොලොන් ගස, කොල්ලම්කොළ", "category": "plant" },
    { "word": "පඤ්ජපුෂ්ප", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "පඤ්ජපුෂ්පි", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "පච්චදාරු", "meaning": "වෙනිවැල්ගැට", "category": "plant" },
    { "word": "පචති", "meaning": "වල් දෙළුම්", "category": "plant" },
    { "word": "පචම්පච", "meaning": "වනුවැල් (බානුවැල්=කහ වැල්)", "category": "plant" },
    { "word": "පචිනවන", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පචිබලා", "meaning": "සිරස්ස, (දික්තිබිය)", "category": "plant" },
    { "word": "පචි", "meaning": "(පක්‍ෂි)-කපු පුළුන්", "category": "plant" },

    // --- පිටුව 285 ---
    { "word": "පවෙරාජනිකා", "meaning": "අබනගිරියා", "category": "plant" },
    { "word": "පවේලි", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පඤ්චඋන්මාදය", "meaning": "නපුරු ආහාරය, නපුරු පානය, භය, ශෝකය, අමනුෂ්‍යභය යන මෙයින් පැමිණෙන පිස්සුව", "category": "treatment" },
    { "word": "පඤ්චකණ්ටකිනි", "meaning": "හෙළබටු", "category": "plant" },
    { "word": "පඤ්චකර්මය", "meaning": "වමන, විරේචන, නිරූහණ, (වස්තිය), නශ්‍ය, අනුවාසන, (බඩට තෙල් විදීම) යන කර්ම පස", "category": "treatment" },
    { "word": "පඤ්චකෂාය", "meaning": "දඹ, හිඹුල්, බෑපිල, මුහුණමල්, මසන් යන කසට පස", "category": "compound" },
    { "word": "පඤ්චකාන්ත", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "පඤ්චකෝලගණය", "meaning": "තිප්පිලි, තිප්පිලිමුල්, සිවිය, රත්නිටුල්, සිද්ධිඟුරු යන මේ පස් කෝල් නමි.", "category": "compound" },
    { "word": "පඤ්චගව්‍ය", "meaning": "දී, කිරි, ගිතෙල්, ගෝ මූත්‍ර, ගොම යන පස යි.", "category": "compound" },
    { "word": "පඤ්චගෝරස", "meaning": "පස්ගෝරස=(නොමිදුන කිරි, මිදුන (දී)කිරි, ගිතෙල්, තක්‍රා (මෝරු=දී පෙරළිදිය) නොතිත (වෙඬරු=බටර්) යන පස්ගව් රස)", "category": "compound" },
    { "word": "පඤ්චපත්‍ර", "meaning": "නෙළුම් අල = (නෙළුඹු දැලි = නෙළුඹල)", "category": "plant" },
    { "word": "පඤ්චපල්ලව", "meaning": "අඹ, ඇසතු, නුග, පලොල්, කෑල යන මේ ගස්වල කොලවර්ග පස", "category": "compound" },
    { "word": "පඤ්චභෙෂජ්‍ය", "meaning": "සහඳ, නවතිත, තෙල, මධු, ඵාණිත හෝ ගිතෙල් මී පැණි, වෙඬරු, තෙල්, සකුරු යන පස", "category": "compound" },
    { "word": "පඤ්චමධුරමාංශ", "meaning": "හද මස්, ලැමඩි මස්, අක්මාවේ මස්, පපු මස්, අඟුණ මස්", "category": "anatomy" },
    { "word": "පඤ්චමුඛි", "meaning": "වංඇපල", "category": "plant" },
    { "word": "පඤ්චමූල", "meaning": "බෙලි, තොටිල, ඇත්දෙමට, මිදි, පලොල් යන මේ මුල් පස", "category": "compound" },
    { "word": "පඤ්චාමෘත", "meaning": "කිරි, දී, හෝ උක්සකුරු, ගිතෙල්, දී, මී පැණි යන පස", "category": "compound" },
    { "word": "පඤ්චරත්ත", "meaning": "නිල් මැණික්, දියමන්ත, පද්මරාග, මුතු, පබලු", "category": "mineral" },
    { "word": "පඤ්චරස", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "පඤ්චරසා", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "පඤ්චරාජප්‍රිය", "meaning": "බුලත්", "category": "plant" },
    { "word": "පඤ්චරාජඵල", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "පඤ්චලවණ", "meaning": "සුවස, බළල්, යවකර, සයින්දව, රෝම යන ලුණු පස", "category": "compound" },
    { "word": "පඤ්චලොහ", "meaning": "රත්, රිදී, තඹ, සුදුඊයම්, කලු ඊයම් යන ලෝහ වර්ග පස", "category": "compound" },
    { "word": "පඤ්චලොහක", "meaning": "පස් ලෝ = පඤ්ච ලෝහ", "category": "compound" },
    { "word": "පඤ්චවපි", "meaning": "ඇසල, බෙලි, නුග, නෙල්ලි, අශෝකා යන පස", "category": "compound" },
    { "word": "පඤ්ච වල්කල", "meaning": "නුග, දිවුල්, ඇසතු, පුලිල, බෝ යන මේ ගස්වල පොතු", "category": "compound" },
    { "word": "පඤ්චවිධ අජීර්ණ", "meaning": "ආමාජීර්ණය, විදග්ධාජීර්ණය, විෂ්ටබ්ධාජීර්ණය, අමීලාජීර්ණය, රසශෙෂාජීර්ණය", "category": "treatment" },
    { "word": "පඤ්චවිධ පද්ම", "meaning": "රක්තෝත්පල, නිලෝත්පල, ශ්වේතෝත්පල, රක්ත පද්ම, ශ්වේත පද්ම", "category": "compound" },
    { "word": "පඤ්චවිධ මුත්‍ර", "meaning": "මහාමුත්‍ර, උෂ්ට්‍රමුත්‍ර, මීනාමුත්‍ර, නමුකමුත්‍ර, සූකරමුත්‍ර", "category": "compound" },
    { "word": "පඤ්චවිධ සුරා", "meaning": "පිට්ටසුරා, පුප්පසුරා, ඕදනීය සුරා, බීජප්‍රකෘතිගතක සුරා, සම්භාර සංයුක්ත සුරා, යන සුරා වර්ග පස", "category": "compound" },

    // --- පිටුව 286 ---
    { "word": "පඤ්ච ශස්‍ය", "meaning": "කොතඹුරු, තල, මෑ, යව, හෙළ දඹකලන් යන ශස්‍ය පස", "category": "compound" },
    { "word": "පඤ්චසාර", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "පඤ්ච සුගන්ධික", "meaning": "කපුරු, තකුල්, කුරුඳුමුල්, පුවක්, සාදික්කා යන පස", "category": "compound" },
    { "word": "පඤ්චාංග", "meaning": "මුල්, කොළ, ගෙඩි, මල්, පොතු යන පස", "category": "compound" },
    { "word": "පඤ්චාංගුල", "meaning": "එරබු, (හෙළ, රත් එරබු දෙවර්ගය)", "category": "plant" },
    { "word": "පඤ්චාම්ල", "meaning": "ඇසටු, කොහොඹ, සපු, නා, පොල් යන පස", "category": "compound" },
    { "word": "පඤ්චාමෘත", "meaning": "කිරි, දී, ගිතෙල්, මී පැණි යන පස යි.", "category": "compound" },
    { "word": "පඤ්චාලි", "meaning": "ඇත්අඩි, ඇත්සැටිය", "category": "plant" },
    { "word": "පඤ්චරාප්‍රිය", "meaning": "බුලත්", "category": "plant" },
    { "word": "පඤ්චිපර්ණී", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "පට", "meaning": "අඹරණ ගල", "category": "equipment" },
    { "word": "පටන", "meaning": "එලබටු", "category": "plant" },
    { "word": "පටරංග", "meaning": "පතඟි", "category": "plant" },
    { "word": "පටරක්‍ෂක", "meaning": "පතඟි", "category": "plant" },
    { "word": "පටල", "meaning": "එළ ලොත් ගස", "category": "plant" },
    { "word": "පටටි", "meaning": "ලොත්, හෙළ ලොත්", "category": "plant" },
    { "word": "පටටිකා", "meaning": "ලොත්, හෙළ ලොත්", "category": "plant" },
    { "word": "පටටිකාඛ්‍යා", "meaning": "රත්ලොත්", "category": "plant" },
    { "word": "පටටිකා", "meaning": "ලොඬු (ලොත්) විශේෂයක්", "category": "plant" },
    { "word": "පටටින්", "meaning": "රත්ලොත්", "category": "plant" },
    { "word": "පටින", "meaning": "එලබටු", "category": "plant" },
    { "word": "පට්විල", "meaning": "ලොත්, හෙළලොත්, සිරිල, කුණුකරඳ", "category": "plant" },
    { "word": "පට", "meaning": "රෙදි, කිරිපලු", "category": "plant" },
    { "word": "පටපත්‍ර", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "පටබඳිආරච්චිල", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "පටම්පටා", "meaning": "මහකපු, බෙහෙත් කපු", "category": "plant" },
    { "word": "පටම්පටී", "meaning": "මහකපු", "category": "plant" },
    { "word": "පටරක්ත", "meaning": "පතඟි", "category": "plant" },
    { "word": "පටරාග", "meaning": "පතඟි", "category": "plant" },
    { "word": "පටල", "meaning": "මිණිරන්, දුම්මැල්ල", "category": "plant" },
    { "word": "පටවාසක", "meaning": "කොකුම්සුණු", "category": "plant" },
    { "word": "පටසුල", "meaning": "කපු", "category": "plant" },
    { "word": "පටී", "meaning": "සපොල්, හෙළ පලොල්", "category": "plant" },
    { "word": "පටිමලය", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පටීර", "meaning": "සඳුන්, කිහිරි", "category": "plant" },
    { 
        "word": "පටිධාතු", 
        "scientific": "Ophioglossum Pendulum",
        "meaning": "මේ වර්ගය වැඩි වශයෙන් පැළවී වන්නේ නිතර දියසීරාව සහිත පිණි ඉසෙන සුර්ය රශ්මියෙන් නොතැවෙන (මහ හිමයේ) බේදුරු අතරිනු යි. අඟල් එකේ සිට දෙක දක්වා පළලට වැවෙන මේ වර්ගය අඩි හය දක්වා දිගට එල්ලා වැටෙයි. හොඳට වැවුන කොළ වල අග පතු බළලු දෙකක් හෝ තුනක් බැගින් බෙදී සිටි යි. පෙනුමෙන් පටියකට සමාන නිසා පටි ධාතු නමින් හැඳින්වෙන මෙය උඩවැඩියා වර්ගයට අයත් පැළෑටියකි. දේශීය වෙදකමේ ඇතැම් ගන්දි තෙල් වලට මේ වර්ගය නියම කර තිබේ. වැඩිවශයෙන් බේදුරු ආශ්‍රයෙන් ම වැවෙන මේ වර්ගය දිය සීරාව සහිත ගස් දෙබල්වල හා ගල්වලත් වැවෙයි.", 
        "category": "plant",
        "image": "img_286_patidhatu.jpg"
    },

    // --- පිටුව 287 ---
    { "word": "පටු", "meaning": "(ලවණ) පාංශුලුණු-සවිඳලුණු, දුම්මැල්ල, අරත්ත, වැල්මඳට", "category": "mineral" },
    { "word": "පටුක්තම", "meaning": "සයින්දව ලුණු", "category": "mineral" },
    { "word": "පටුකර", "meaning": "සවින්දව", "category": "mineral" },
    { "word": "පටුගන", "meaning": "ඔලිඳ", "category": "plant" },
    { "word": "පටුපර්ණ", "meaning": "ගොකටු", "category": "plant" },
    { "word": "පටුපර්ණී", "meaning": "වික්මැලී, සෘණීක්‍ෂීරී", "category": "plant" },
    { "word": "පටුමාන්මක", "meaning": "ලුණුමුඩ", "category": "treatment" },
    { "word": "පටුර", "meaning": "රත්හඳුන්", "category": "plant" },
    { 
        "word": "පටෝල", 
        "meaning": "පතෝල, දුම්මැල්ල, (අඩියකට වඩා දිග නැති ගෙඩි පතෝල නැතහොත් වන පතෝල නමින් හැඳින් වෙන (කෑමට ගන්නා) පතෝල වර්ගය පටෝල බැව් ඇතැම් අය කියති. පටෝල වෙනුවට තිත්ත වැටකොළු ගන්නා අය ද සිටිති. එහෙත් මේ රටේ වැඩි දෙනා ගන්නේ දුම්මැල්ල ම ය.", 
        "category": "plant" 
    },
    { 
        "word": "පටෝලාදිගණය", 
        "meaning": "පටෝල (දුම්මැල්ල), සුදු හඳුන්, මුරුවා මුල්, කුබුරුඇට, පාඨා (ලුණු කැටියා වැල්) (පාඨා වලට වැඩිදෙනා ගන්නේ දියමිත්තයි) රසකිඳ යන මේ ගණය පිත්, සෙම්, අරුවි, වමන, ජ්වර, කැසුම් විෂ නසන්නේය.", 
        "category": "compound" 
    },
    { "word": "පටෝලා", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "පටෝලසාපක", "meaning": "තිත්ත වැටකොළු", "category": "plant" },
    { "word": "පටෝලි", "meaning": "තිත්ත වැටකොළු, දුම්මැල්ල", "category": "plant" },
    { "word": "පටෝලිකා", "meaning": "පතෝල, වැටකොළු", "category": "plant" },
    { "word": "පඨ", "meaning": "උඩනල වැල්, (පඩවැල්)", "category": "plant" },
    { "word": "පඩු", "meaning": "රණහුණ", "category": "plant" },
    { "word": "පඩර", "meaning": "හෙළ තෙම්ම", "category": "plant" },
    { "word": "පඩාවොක්කු", "meaning": "වැල්දෙහි", "category": "plant" },
    { "word": "පඬුකෝවෙ", "meaning": "පසඟිල්ල", "category": "plant" },
    { "word": "පඬුරා", "meaning": "හෙළ තෙම්ම", "category": "plant" },
    { "word": "පඩෙර", "meaning": "හෙළ තෙම්ම", "category": "plant" },
    { "word": "පණ්කර", "meaning": "ජලජ පුෂ්ප (නෙළුම්, මහනෙල් යනාදිය)", "category": "plant" },
    { "word": "පණ්කත්පලෙ", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පණ්චවාවල්", "meaning": "කපු", "category": "plant" },
    { "word": "පණ්චි", "meaning": "පුළුන්", "category": "plant" },
    { "word": "පණ්ඩක", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "පණ්ඩර", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "පණ්ඩරා", "meaning": "අබනගිරියා", "category": "plant" },
    { "word": "පණ්ඩුක", "meaning": "යොහොඹු, පිච්ච වැල", "category": "plant" },
    { "word": "පණණ", "meaning": "දුටුවැල්, කොළ", "category": "plant" },
    { "word": "පණණම්බිලයාගු", "meaning": "ඇඹුල් කැඳ", "category": "treatment" },
    { "word": "පණණ්‍යා", "meaning": "දුටුවැල්", "category": "plant" },
    { "word": "පණිතාකි", "meaning": "ගල්කූර", "category": "plant" },
    { "word": "පණ්දීරන්", "meaning": "දල්කිකිරි", "category": "plant" },
    { "word": "පණ්නෙයි", "meaning": "කිතුල්පානය", "category": "treatment" },
    { "word": "පණ", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "පණපක්‍ෂිකා", "meaning": "හීනුඳුපියලි", "category": "plant" },
    { "word": "පණමරම්", "meaning": "තල් ගස", "category": "plant" },
    { "word": "පණසඵල", "meaning": "කොස් (වැල-වරකා) ගෙඩි", "category": "plant" },
    { "word": "පණා", "meaning": "කොස්", "category": "plant" },
    { "word": "පණාදි", "meaning": "බුව", "category": "plant" },
    { "word": "පණාපත්ති", "meaning": "අරළු", "category": "plant" }
];

