// data_99_108.js - පිටු 99 සිට 108 දක්වා සියලුම වචන
const data_extra_99_108 = [
  // --- පිටුව 99 (image_9eb385.png) ---
  { "word": "කාකස්සී", "meaning": "ගබ්බිලිද", "category": "plant" },
  { "word": "කාසභා", "meaning": "වදකසා", "category": "plant" },
  { "word": "කාටම්", "meaning": "කළුකම්මේරිය", "category": "plant" },
  { "word": "කාටපාලී", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාටපාලි", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාසමහා", "meaning": "කාවළුණු", "category": "plant" },
  { "word": "කාක", "meaning": "පලොල්, කාවළුණු, මී ඉටි", "category": "treatment" },
  { "word": "කාමප්‍රභූ", "meaning": "මුගුණුවැන්න", "category": "plant" },
  { "word": "කාචර", "meaning": "සපු, (සපුගස)", "category": "plant" },
  { "word": "කාවලවන්ත", "meaning": "කාවළුණු, කළුදුරු", "category": "plant" },
  { "word": "කාවසෙස්වොලා", "meaning": "කාව් මැටිවලින් ගත්ලුණු", "category": "treatment" },
  { "word": "කාව්වේලි", "meaning": "වැල්කසඹිලියා", "category": "plant" },
  { "word": "කාප්තත්", "meaning": "ඇඹුල", "category": "plant" },
  { "word": "කාර්පුනස", "meaning": "කපු", "category": "plant" },
  { "word": "කාඤ්චන", "meaning": "රත්රන්, සපු, නාගස, දිවුල්, (අවරින්කා) කහ, හෙල කොබෝලිල, රන්කිරියල්, නා මල් රේණු, සිවංගුරු, අත්තන", "category": "plant" },
  { "word": "කාඤ්චනක", "meaning": "කොබෝලිල, කිරියල්", "category": "plant" },
  { "word": "කාඤ්චනකාරිනී", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "කාඤ්චනකේෂම", "meaning": "මී අඹ", "category": "plant" },
  { "word": "කාඤ්චනගෞරිකා", "meaning": "සිවංගුරු", "category": "plant" },
  { "word": "කාඤ්චනපුෂ්ප", "meaning": "කිණිහිරි, සිහින් මිරි", "category": "plant" },
  { "word": "කාඤ්චනපුෂ්පිකා", "meaning": "රන්වන් සමන්ලව", "category": "plant" },
  { "word": "කාඤ්චනක්ෂීපණ", "meaning": "සිවංගුරු", "category": "plant" },
  { "word": "කාඤ්චනා", "meaning": "කහ", "category": "plant" },
  { "word": "කාඤ්චනාර", "meaning": "රත් කොබෝලිල", "category": "plant" },
  { "word": "කාඤ්චනාල", "meaning": "කොබෝලිල, ඇසල", "category": "plant" },
  { "word": "කාඤ්චනාක්‍ෂය", "meaning": "නාමල් රේණු, නාගස, සපුකැකුළු", "category": "plant" },
  { "word": "කාඤ්චනී", "meaning": "කැල්වැල්, කහ, රන් කිරිගොකටු, (සවණිකිරි)", "category": "plant" },
  { "word": "කාඤ්චි", "meaning": "කෙළිඳ (හුනිද)", "category": "plant" },
  { "word": "කාඤ්චික", "meaning": "නල ගස, කාඩිය", "category": "treatment" },
  { "word": "කාඤ්චිකාම්බු", "meaning": "කාඩිය", "category": "treatment" },
  { "word": "කාඤ්චි ශක්ති", "meaning": "කාඩිය", "category": "treatment" },
  { "word": "කාඤ්චිකා", "meaning": "කාඩිය, විනාකිරි ආදී අම්ල වර්ග", "category": "treatment" },
  { "word": "කාඤ්ජි කවාශ", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "කාඤ්ජි කා", "meaning": "කාඩි", "category": "treatment" },
  { "word": "කාඤ්ජිකාසදෘ", "meaning": "කාඩිය", "category": "treatment" },
  { "word": "කාඤ්ජි පත්‍රිකා", "meaning": "කළුවන් දන්ත", "category": "plant" },
  { "word": "කාඤ්ජි", "meaning": "සිරිත්කෝකූ, ගැටතුඹ", "category": "plant" },
  { "word": "කාට්ටුකාතිපු", "meaning": "ලොක්ක මල් (මලිකමල්)", "category": "plant" },
  { "word": "කාට්ටාමිනක්කු", "meaning": "වල් එඬරු", "category": "plant" },
  { "word": "කාට්ටුකරණෙයි", "meaning": "වල්කිබරම්", "category": "plant" },
  { "word": "කාට්ටුපයරා", "meaning": "වල් මෑ", "category": "plant" },
  { "word": "කාටල", "meaning": "කොට්ටම්බා", "category": "plant" },
  { "word": "කාටු ඉංචි", "meaning": "වල්ඉඟුරු", "category": "plant" },
  { "word": "කාටුපුල", "meaning": "මහේමා - යක්නාරං", "category": "plant" },
  { "word": "කාටුජීරක", "meaning": "දේවදුරු", "category": "plant" },
  { "word": "කාටුතෙනෙගාති", "meaning": "හෙලලුඹු", "category": "plant" },
  { "word": "කාටුතුලසි", "meaning": "මීදුරු(තලා)", "category": "plant" },
  { "word": "කාටුපයාරා", "meaning": "වල් මුං, වල් මෑ", "category": "plant" },
  { "word": "කාටුම්", "meaning": "ඇවුළු", "category": "plant" },
  { "word": "කාඨින", "meaning": "ඉඳි ගස", "category": "plant" },
  { "word": "කාඨිනස ඵල", "meaning": "දිවුලු ගස", "category": "plant" },
  { "word": "කාණ්ඩෝදුම්බර", "meaning": "කොවඩිබුලා ගස", "category": "plant" },
  { "word": "කාණ්ඩරි", "meaning": "කාඩි", "category": "treatment" },
  { "word": "කාඩි", "meaning": "ඇඹුල් දිය, කාඩි දිය (රාබු අල සහ වී සමයේ ගෙන කොටා සුදුසු භාජනයක දමා දිය වත් කර සතියක් පමණ පැසෙන්ට හැර පෙරා ගත් ජලය කාඩි වේ. නෑහැනොත් බිලද, නෙල්ලි, තිප්පිලි, ලුණු, කුරුඳු පොතු, අසමෝදගම්, මේ කී දේ සමව ගෙන කොටා බඳුනක ලා දිය වත් කර තෙ දිනක් පමණ තබා පෙරා ගත් ජලයද කාඩි නමි. ආරනාල ද කාඩි විශේෂයකි. එය සාදා ගන්නා ක්‍රමය මේ පොතේ 40 පිටුවේ ඇත.)", "category": "treatment" },

  // --- පිටුව 100 (image_9eb001.png) ---
  { "word": "කාඩිනීර්", "meaning": "කාඩි දිය", "category": "treatment" },
  { "word": "කාණ්ඩ", "meaning": "කුඩම්මිරිස්, ගල්පිසැල්", "category": "plant" },
  { "word": "කාණ්ඩකටුක", "meaning": "karavila", "category": "plant" },
  { "word": "කාණ්ඩකණ්ටක", "meaning": "සැබෝ", "category": "plant" },
  { "word": "කාණ්ඩධාර", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "කාණ්ඩකීලක", "meaning": "ලොත් ගස", "category": "plant" },
  { "word": "කාණ්ඩගුණ්ඩ", "meaning": "කෙකපිය", "category": "plant" },
  { "word": "කාණ්ඩතික්ත", "meaning": "බිමකොහොඹ (කිරාත) ගණ, යක්බේරිය", "category": "plant" },
  { "word": "කාණ්ඩන් මිරුග කොම්ප්‍ර", "meaning": "කහ වේන අඟ", "category": "treatment" },
  { "word": "කාණ්ඩනී", "meaning": "බුලත්වැල, (කාණ්ඩනි තලා)", "category": "plant" },
  { "word": "කාණ්ඩනීල", "meaning": "ලොත් ගස", "category": "plant" },
  { "word": "කාණ්ඩප්‍රභා", "meaning": "කවුවිල", "category": "plant" },
  { "word": "කාණ්ඩපුෂ්ප", "meaning": "ගැටතුඹ ගස", "category": "plant" },
  { "word": "කාණ්ඩභරණ", "meaning": "කුලූරැණ", "category": "treatment" },
  { "word": "කාණ්ඩභාඛා", "meaning": "මුවකිරිය වැල, සොමිලතා", "category": "plant" },
  { "word": "කාණ්ඩභීනා", "meaning": "ලොත් ගස", "category": "plant" },
  { "word": "කාණ්ඩහීන", "meaning": "ලොත්, වම්මුතු", "category": "plant" },
  { "word": "කාණ්ඩතිකතා", "meaning": "බිමකොහොඹ, යක්බේරිය", "category": "plant" },
  { "word": "කාණ්ඩ මිරුගකොම්බ්‍ර", "meaning": "ගවර් අං", "category": "treatment" },
  { "word": "කාණ්ඩාරොහා", "meaning": "කඩුකරෝසණ", "category": "plant" },
  { "word": "කාණ්ඩිකෝශී", "meaning": "වැල්කසඹිලියා", "category": "plant" },
  { "word": "කාණ්ඩීතික්තාක", "meaning": "බිමකොහොඹ (කිරාත)", "category": "plant" },
  { "word": "කාණ්ඩීල්වේන්නෙයි", "meaning": "වොවිරැ", "category": "treatment" },
  { "word": "කාණ්ඩීර්", "meaning": "වැල්මදට, කරල්සැබ, කරවිල, මොර", "category": "plant" },
  { "word": "කාණ්ඩීරා", "meaning": "වැල්මදට, කරවිල", "category": "plant" },
  { "word": "කාණ්ඩීවෛක්ෂ", "meaning": "ලංගස්, වැලුක්, ඉඟිරි", "category": "plant" },
  { "word": "කාණ්ඩීවෛක්ෂු", "meaning": "උක්, වැලුක්, ගොකලු", "category": "plant" },
  { "word": "කාණ්ඩේවත්", "meaning": "රඹුක්, වැලුක්, ඉඟිරි, (නිරඹුල්ලිය,) උක්", "category": "plant" },
  { "word": "කාණ්ඩේසි", "meaning": "කුඩම්මිරිස්", "category": "plant" },
  { "word": "කාණ්ඩබේර්", "meaning": "සුලුකුර", "category": "plant" },
  { "word": "කාණ්ඩබේරැහා", "meaning": "කඩුකරෝෂණ", "category": "plant" },
  { "word": "කානොතොට්ටි", "meaning": "වෙල්ලන්ගිරිය", "category": "plant" },
  { "word": "කාද", "meaning": "කොල්ලම් කොළ", "category": "plant" },
  { "word": "කාදම්බ", "meaning": "කොලොම් ගස (උක්ගස)", "category": "plant" },
  { "word": "කාදම්බකර", "meaning": "කොලොම් ගස", "category": "plant" },
  { "word": "කාදම්බයි", "meaning": "කොලොම්, බක්මී", "category": "plant" },
  { "word": "කාදම්බරී", "meaning": "සුරා", "category": "treatment" },
  { "word": "කාදම්බරීවිර", "meaning": "රාමජ්ජි (රාබිජ්ජූ)", "category": "plant" },
  { "word": "කාදම්බා", "meaning": "මුඛමගණ", "category": "treatment" },
  { "word": "කාදම්බී", "meaning": "වැලිනීතින (වැලිනිවිනි)", "category": "plant" },
  { "word": "කාදු", "meaning": "කඩුකරොබු", "category": "plant" },
  { "word": "කාන්චි", "meaning": "හුනිද (ඔලිඳ)", "category": "plant" },
  { "word": "කාන්චිවුරෙහි", "meaning": "ගොබකදුරු", "category": "plant" },
  { "word": "කාන්ටවෝරි", "meaning": "කසඹිලියා", "category": "plant" },
  { "word": "කාන්තා", "meaning": "කාන්තම්, රක්කගුණ, පුළුගු, කොකුම්, සඳුන්, දිය මිදෙල්ල", "category": "treatment" },
  { "word": "කාන්තාශ්‍රාමික", "meaning": "මගවම්මුතු (මහ කලාඳුරු)", "category": "plant" },
  { "word": "කාන්තගල්", "meaning": "කාන්තම් ගල්", "category": "treatment" },
  { "word": "කාන්තාධාතු", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "කාන්තපාෂාණ", "meaning": "කාන්තම්", "category": "treatment" },
  { "word": "කාන්තපුෂ්ප", "meaning": "කොබෝලිල", "category": "plant" },
  { "word": "කාන්තම", "meaning": "කාන්තම්", "category": "treatment" },
  { "word": "කාන්තාලක", "meaning": "නන්දිරුක (වතු සුද්ද)", "category": "plant" },

  // --- පිටුව 101 (image_9eaf03.png) ---
  { "word": "කාභු", "meaning": "නලගස", "category": "plant" },
  { "word": "කාම්භූ", "meaning": "නලගස", "category": "plant" },
  { "word": "කාම්බුකා", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "කාමෝෂී", "meaning": "මීවෙලන්ත, දෙඹ, උඳුපියලි, හෙලකිණිරි, මුංවැන්න", "category": "plant" },
  { "word": "කාමෝත්පකා", "meaning": "එල හුනිද", "category": "plant" },
  { "word": "කාම්පිල්ලක", "meaning": "කවුවෙලඟ, උග්‍රරස්ස", "category": "plant" },
  { "word": "කාම", "meaning": "පියා ගස", "category": "plant" },
  { "word": "කාම", "meaning": "සිනි, තෝර, තුවරලා", "category": "plant" },
  { "word": "කාමබීජදලා", "meaning": "රන් වන් වැටකේ", "category": "plant" },
  { "word": "කාෂසති", "meaning": "කඩුවැල්බටු", "category": "plant" },
  { "word": "කාමචාරිනී", "meaning": "අරත්ත", "category": "plant" },
  { "word": "කාමචාරියා", "meaning": "අරත්ත, කලුවා", "category": "plant" },
  { "word": "කාමවී", "meaning": "කළුකම්මේරිය", "category": "plant" },
  { "word": "කාමජනනී", "meaning": "බුලත්", "category": "plant" },
  { "word": "කාමහර", "meaning": "සිහින් දුම්බලා", "category": "plant" },
  { "word": "කාමද", "meaning": "කලිසපතුරා, කිබරද, බුලත්, අරලු", "category": "plant" },
  { "word": "කාමදුතා", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "කාමදුනී", "meaning": "හෙල පලොල්, රත් පලොල්", "category": "plant" },
  { "word": "කාමදිර ජන්ම", "meaning": "කොකුම්", "category": "plant" },
  { "word": "කාමනිධි", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කාම ප්‍රියකාරි", "meaning": "අශ්වගොඳු", "category": "plant" },
  { "word": "කාම ඵල", "meaning": "මී අඹ ගස", "category": "plant" },
  { "word": "කාමප්ඵලා", "meaning": "කොසොල් ගස", "category": "plant" },
  { "word": "කාමමෝද", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කාමරඬ්කායි", "meaning": "කාමරංගා", "category": "plant" },
  { "word": "කාමරංගා", "meaning": "කාමරංගා ගස, (පැණි කාමරංගා, ඇඹුල් කාමරංගා යයි දෙවගයකි. පැණි කාමරංගා කෑමටත්, ඇඹුල් කාමරංගා ලෝහ වගී ශුද්ධ කිරීමටත් ගණිති)", "category": "plant" },
  { "word": "කාමරෑපෝදයම", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කාමල", "meaning": "සෙන්ගමාල රෝගය", "category": "symptom" },

  // --- පිටුව 102 (image_9eab87.png) ---
  { "word": "කාමලකී", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "කාමලෝච", "meaning": "කළු අගිල්, කළුවැල්", "category": "plant" },
  { "word": "කාමවිනි", "meaning": "දුරහරිද්‍රා (ලංකාවේ මේ වෙනුවට වෙනිවැල් ගණිති)", "category": "plant" },
  { "word": "කාමවල්ලභ", "meaning": "අඹ, කුරළු පොතු, බුලදම්", "category": "plant" },
  { "word": "කාමවන්ත", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාමශර", "meaning": "අඹ", "category": "plant" },
  { "word": "කාමා", "meaning": "වැල්මදට, කැප්පිටියා", "category": "plant" },
  { "word": "කාමාංගී", "meaning": "සාදා", "category": "treatment" },
  { "word": "කාමාචි", "meaning": "හින්කැම්මේරිය", "category": "plant" },
  { "word": "කාමානා", "meaning": "කලුවාකම්මේරිය", "category": "plant" },
  { "word": "කාමාක්‍ෂා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කාමායුධ", "meaning": "අඹගස", "category": "plant" },
  { "word": "කාමාලු", "meaning": "රතු මල් ඇති පෙනන්තගස", "category": "plant" },
  { "word": "කාමිනී", "meaning": "දුරහරිද්‍රා", "category": "plant" },
  { "word": "කාමිනිග", "meaning": "මුරංගා ගස", "category": "plant" },
  { "word": "කාමිල", "meaning": "දෙඹ ගස", "category": "plant" },
  { "word": "කාමුක්", "meaning": "සාදික්කා, වනසාදික්කා", "category": "plant" },
  { "word": "කාමුකා", "meaning": "විෂ්ණුක්‍රාන්ති, නෝපලු, සමන්පිච්ච, කෝන්ගහ, අක්මැල්ල, කලුවැල්ල, පුවක්", "category": "plant" },
  { "word": "කාමුරා", "meaning": "කරාබු", "category": "plant" },
  { "word": "කාමෙෂට", "meaning": "මී අඹ ගස", "category": "plant" },
  { "word": "කාමෛ", "meaning": "සිරිල", "category": "plant" },
  { "word": "කායඵල", "meaning": "කරබෙයියා (කරපිංචා)", "category": "plant" },
  { "word": "කායම", "meaning": "පෙරුම්කායම්, බෙහෙත් නොදේද", "category": "treatment" },
  { "word": "කායවල්ලී", "meaning": "එබල", "category": "plant" },
  { "word": "කායස්ථා", "meaning": "අරත්ත, කවෙළු, අරළු, එන්සාල්", "category": "plant" },
  { "word": "කායස්ථාපාලි", "meaning": "රත්පලොල්", "category": "plant" },
  { "word": "කායස්ථා", "meaning": "කලුවැල්, කොල්ල", "category": "plant" },
  { "word": "කායිතදුලෙයි", "meaning": "මියලි කොළ", "category": "plant" },
  { "word": "කායිපකායි", "meaning": "මියලි ගෙඩි, (මියලු ගෙඩි)", "category": "plant" },
  { "word": "කායිසදපටෙයි", "meaning": "මියලි පොතු", "category": "plant" },
  { "word": "කායිනෙයිසිට්ටි", "meaning": "ගස්පෙනෙලගෙඩි, පෙනෙල ඇට", "category": "plant" },
  { "word": "කායිපොන්නමකොට්ට", "meaning": "ගස් පෙනෙල ගෙඩි, පෙනෙල ඇට", "category": "plant" },
  { "word": "කාර්ජඅගිල්", "meaning": "අගිල්, කළුවැල්", "category": "plant" },
  { "word": "කාර්ජයම්", "meaning": "කලවර්යම", "category": "treatment" },
  { "word": "කාර්කලක", "meaning": "සිහින් කිහිිරි", "category": "plant" },
  { "word": "කාර්කවල්ලී", "meaning": "බලිද", "category": "plant" },
  { "word": "කාර්කසමර", "meaning": "රත්රන්, අත්තන, කපු", "category": "plant" },
  { "word": "කාර්කෝටක", "meaning": "වැල්තුඹ", "category": "plant" },
  { "word": "කාර්කෝරි", "meaning": "රේරා", "category": "plant" },
  { "word": "කාර්තනස්සිරි", "meaning": "රන්ගොකටු", "category": "treatment" },
  { "word": "කාර්ගෝල් අරිසි", "meaning": "බෝදි ඇට, කළුබෝ ඇට", "category": "plant" },
  { "word": "කාර්නික", "meaning": "කිරියගුළු", "category": "plant" },
  { "word": "කාෂ්ට", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "කාෂ්ටවිකා", "meaning": "කවඩි", "category": "treatment" },
  { "word": "කාෂ්ටිකාපාචි", "meaning": "වැල් කපු", "category": "plant" },
  { "word": "කාර්පාස", "meaning": "මහකපු, ගිඟුරුපියලි", "category": "plant" },
  { "word": "කාර්පාසිකස", "meaning": "කපු ඇට", "category": "plant" },
  { "word": "කාර්පාස්තුලක", "meaning": "කපු පුළුන්", "category": "treatment" },
  { "word": "කාර්පුරිකාවරසි", "meaning": "බෝදි ඇට", "category": "plant" },
  { "word": "කාර්මක", "meaning": "කොවිල, දියමිදෙල්ල, හෙල කිහිිරි", "category": "plant" },
  { "word": "කාර්මරි", "meaning": "උක්මකුළු", "category": "treatment" },
  { "word": "කාර්මුක", "meaning": "කිහිිරි, කොවිල, දිය මිදෙල්ල, හෙල කිහිිරි", "category": "plant" },
  { "word": "කායා", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "කාර්යමිරි", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කාර්යමියති", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කාර්ය", "meaning": "සල් රුක, ඇත්දෙමට, දෙල්", "category": "plant" },
  { "word": "කාර්ෂික", "meaning": "කිරිපලා", "category": "plant" },

  // --- පිටුව 103 (image_9ea85d.png) ---
  { "word": "කාර්ෂීණී", "meaning": "නානාචාරිය", "category": "treatment" },
  { "word": "කාර", "meaning": "යවකාර ලුණු", "category": "treatment" },
  { "word": "කාරමසස", "meaning": "යවකාර, පුස්කර, සච්චකාර, ඕංකාර, සර්ප් හෝ අක්පත යන ක්ෂාර පස", "category": "treatment" },
  { "word": "කාරක", "meaning": "බුදුසල් ගස", "category": "plant" },
  { "word": "කාරකවිකා", "meaning": "අරළු", "category": "plant" },
  { "word": "කාරගිල්", "meaning": "කළුවැල්, කළු අගිල්", "category": "plant" },
  { "word": "කාරද", "meaning": "කන්නකලාඳුරු (කණිඟුළු)", "category": "plant" },
  { "word": "කාරබුයි", "meaning": "(කරබුයි) ඇට කළු පැණි පුහුල් (පත්තක්කා)", "category": "plant" },
  { "word": "කාරභී", "meaning": "වැල්තුඹ, සකපුෂ්ප, කලුවැල්, හීන් එන්සාල්", "category": "plant" },
  { "word": "කාරමි", "meaning": "පුස්කර, ලුනුරසැති සාර ද්‍රව්‍ය (යවකාර, පුස්කර, සච්චකාරම්, ඕංකාරම්, අක්පතක්ෂාර)", "category": "treatment" },
  { "word": "කාරමස", "meaning": "ප්‍රවෘ, රක්කගුණ. (ගත්අගුණ,) මහ අසමෝදගම්", "category": "treatment" },
  { "word": "කාරමිකා", "meaning": "කපුරු", "category": "plant" },
  { "word": "කාරලවණ", "meaning": "කාරමීලුණු", "category": "treatment" },
  { "word": "කාරවග", "meaning": "කාරම් (කටුක) වගී", "category": "treatment" },
  { "word": "කාරවල්ය", "meaning": "කරවිල", "category": "plant" },
  { "word": "කාරවල්ල", "meaning": "සිහින් කරවිල (තුඹ කරවිල)", "category": "plant" },
  { "word": "කාරවල්ලී", "meaning": "අසමෝදගම්, මහ කරවිල", "category": "plant" },
  { "word": "කාරවල්ලිකා", "meaning": "කරවිල, මඟකරවිල", "category": "plant" },
  { "word": "කාරවල්ලක", "meaning": "කරවිල, මහකරවිල", "category": "plant" },
  { "word": "කාරවි", "meaning": "සකපුෂ්ප, කරවිල, කුරදු කොළ, රන්මානිස්ස, දුලපකුළු, මොණරකුඩුම්බිය, කොබෙයි කොළ", "category": "plant" },
  { "word": "කාරමවල්ලී", "meaning": "අසමෝද", "category": "plant" },
  { "word": "කාරවෙල්ල", "meaning": "කරවිල", "category": "plant" },
  { "word": "කාරවෙල්ලී", "meaning": "කරවිල", "category": "plant" },
  { "word": "කාරස්කර", "meaning": "කඩුරු ගස", "category": "plant" },
  { "word": "කාරසන්", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "කාරසවද", "meaning": "ඇසල", "category": "plant" },
  { "word": "කාරව", "meaning": "මහ අසමෝද", "category": "treatment" },
  { "word": "කාරිකා", "meaning": "මනෝසිල, කවෙළු", "category": "treatment" },
  { "word": "කාරී", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "කාරක", "meaning": "කාමරංගා ගස", "category": "plant" },
  { "word": "කාරිකා", "meaning": "මීගොක්කිල", "category": "plant" },
  { "word": "කාරජ", "meaning": "නාමල්රේණු, සිවංගුරු", "category": "plant" },
  { "word": "කාරපු", "meaning": "උක්ගසක්", "category": "plant" },
  { "word": "කාරෝදක", "meaning": "මුණුරසැති අළු සහිත දිය", "category": "treatment" },
  { "word": "කාරොස", "meaning": "කාරම් බෙහෙත", "category": "treatment" },
  { "word": "කාල්පක", "meaning": "හීන්ගුරාපියලි, සුවඳකසා", "category": "plant" },
  { "word": "කාල්ලී", "meaning": "පතෝක්", "category": "plant" },
  { "word": "කාල", "meaning": "බෑවිල, රත්නිවුල්, කළුදුරු, මනෝසිල, වැල්මදට, කළුතූත්තාවාළු, සුලුවැවිල, ලෝකඩ, කොත්තමල්ලි", "category": "treatment" },
  { "word": "කාලඅඟුරු", "meaning": "කලුවැල්", "category": "plant" },
  { "word": "කාලකණ්ඩ", "meaning": "කිහිිරි", "category": "plant" },
  { "word": "කාලක", "meaning": "කරබෙයියා (කරපිංචා) පිල, හිඟුරුපියලි, සුවඳකසා, මීඅඹ, තොවිල, (කපුකිනිස්ස) කිරියල්, කලාඳුරු", "category": "plant" },
  { "word": "කාලකණ්ඩ", "meaning": "පියාගස", "category": "plant" },
  { "word": "කාලකණ්ඩී", "meaning": "නිල්කැට", "category": "treatment" },
  { "word": "කාලකණ්ඩිකා", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "කාල කවන්තා", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "කාල වෘක්ෂ", "meaning": "කලු මිල් ඇති කෙහෙලමු ගස", "category": "plant" },
  { "word": "කාලකස්තුරි", "meaning": "කස්තුරි වෙසෙසක්", "category": "treatment" },
  { "word": "කාලකායිකා", "meaning": "හෝපලු ගස", "category": "plant" },
  { "word": "කාලකාලි", "meaning": "ලියනගලා", "category": "plant" },
  { "word": "කාලසූව", "meaning": "වවවමාවි (වන්සකෘත) විෂ ඉඟුරු", "category": "plant" },
  { "word": "කාලසූටාක", "meaning": "වවවමාවි, කදුරුගස", "category": "plant" },
  { "word": "කාලකණිතා", "meaning": "කෙහෙලමු ගස", "category": "plant" },
  { "word": "කාලකණ්ඩිකා", "meaning": "කෙහෙලමු ගස", "category": "plant" },
  { "word": "කාලධකෘත", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "කාලධිකාභා", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "කාලපීරක", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කාලකල්ලි", "meaning": "බිමමගණ (වෙල්ලුඹ)", "category": "plant" },
  { "word": "කාලතාල", "meaning": "කෙහෙල ගස", "category": "plant" },

  // --- පිටුව 104 (image_9ea0de.png) ---
  { "word": "කාලතින්දුක", "meaning": "කටුරු ගස", "category": "plant" },
  { "word": "කාලප්‍රිප", "meaning": "කලු තුඹ", "category": "plant" },
  { "word": "කාලදෙලා", "meaning": "ඇවට්ඨිය", "category": "plant" },
  { "word": "කාලදේවන්", "meaning": "රිදී", "category": "treatment" },
  { "word": "කාලන්", "meaning": "එරමිණියා", "category": "plant" },
  { "word": "කාලභින්තිකා", "meaning": "ගුඟුල්", "category": "plant" },
  { "word": "කාලපත්‍රී", "meaning": "හලින්කස්තුරි", "category": "treatment" },
  { "word": "කාලපර්ණී", "meaning": "තුවරලා", "category": "plant" },
  { "word": "කාලපර්ණී", "meaning": "කළු හුන්සවාලු", "category": "plant" },
  { "word": "කාලපාශී", "meaning": "ඉරමුසු", "category": "plant" },
  { "word": "කාලබිලුක", "meaning": "කටුරු ගස", "category": "plant" },
  { "word": "කාලපුෂ්ප", "meaning": "ගල්සෙවල, කඹිලගස", "category": "plant" },
  { "word": "කාලපෙස", "meaning": "කිරිමෝරා", "category": "treatment" },
  { "word": "කාලපෙසිකා", "meaning": "වැල්මදට, ශිරස්ස, කළුදුරු", "category": "plant" },
  { "word": "කාලපෙගී", "meaning": "කළු ශිරස්සු", "category": "treatment" },
  {
    "word": "කාලමේඝ",
    "scientific": "Antrographis Paniculata",
    "meaning": "මෙය අඩි දෙකක් පමණ උසට වැඩෙන හේන් මිරිස් කොළ වැනි කොළ හා නයි (හීන්) මිරිස් කරල් පමණ හීන් කරල් පොකුරු ඇති පැළෑටියකි. ඉතා තද තිත්ත ගතියකින් යුත් මේ සම්පූර්ණ පැළෑටිය ජ්වරය, රාජපිතායනය, ආදී රෝග සමුහයකට ම ප්‍රත්‍යක්ෂ ගුණදායක ඖෂධයකි.",
    "category": "plant"
  },
  { "word": "කාලබුරිකා", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "කාලනභබි", "meaning": "එල හුනිද, වැල්මදට", "category": "plant" },
  { "word": "කාලඹේ", "meaning": "වැලිනීවිනී", "category": "plant" },
  { "word": "කාලමිකපාරි", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "කාලමිහ", "meaning": "කලුතලා, කළුදුරු, අක්මැල්ල", "category": "plant" },
  { "word": "කාලවිසාල", "meaning": "ගල්සෙවල, කළු අගිල්, අක්මැල්ල", "category": "plant" },
  { "word": "කාලොකසභනක", "meaning": "නෙළුමුළු", "category": "plant" },
  { "word": "කාලබුල", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "කාලමේභී", "meaning": "කළු හුන්සවාලු, වැල්මදට, බෝදිගස්, කහ, කළුදුරු", "category": "plant" },
  { "word": "කාලශේඛිකා", "meaning": "වැල්පෙනෙල, බෝදි ඇට, වැල්මදට", "category": "plant" },
  { "word": "කාලය", "meaning": "සකබ", "category": "treatment" },
  { "word": "කාලයා", "meaning": "මී, ලියි, උඳු", "category": "treatment" },
  { "word": "කාල ලවණ", "meaning": "කලු ලුණු, උද්භිද ලුණු", "category": "treatment" },
  { "word": "කාලලොකී", "meaning": "කළු ලුණු", "category": "treatment" },
  { "word": "කාලලොහක", "meaning": "යකඩ, කළු යකඩ", "category": "treatment" },
  { "word": "කාලවම්", "meaning": "පුවක්", "category": "plant" },
  { "word": "කාලවර්ණිකා", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාලවිකාසිකා", "meaning": "කවෙළු, කිහිිරි කවෙළු", "category": "plant" },
  { "word": "කාලවිජයකා", "meaning": "නොවැල, කමිබුහින්දු", "category": "plant" },
  { "word": "කාලවෘන්තා", "meaning": "කොල්ලු, රත්පලොල්", "category": "plant" },

  // --- පිටුව 105 (image_9ea09f.png) ---
  { "word": "කාලවෘන්තී", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාල ශාක", "meaning": "සීල, කරපිංචා, (කරබෙයියා)", "category": "plant" },
  { "word": "කාලශාකෘත", "meaning": "කලු ගඟල", "category": "plant" },
  { "word": "කාලශාල", "meaning": "සලසාල", "category": "plant" },
  { "word": "කාලශේප", "meaning": "කල්වැල්", "category": "plant" },
  { "word": "කාලස්කන්ධ", "meaning": "දුරා, වල්කිරිද, අවිචින්කා, කොල්ලන් කොළ, ජීවක වෘක්ෂය", "category": "plant" },
  { "word": "කාලසකර", "meaning": "නිගිිරි ගස, කමිලගස", "category": "plant" },
  { "word": "කාලසාරි", "meaning": "පලොල් ගස", "category": "plant" },
  { "word": "කාලසාර", "meaning": "කිහිිරි, රත් වන් සඳුන්, කළුවැල්, කිරියල්,", "category": "plant" },
  { "word": "කාලහ", "meaning": "පලොල් (කලීල) පන්සති පර්ණී", "category": "plant" },
  { "word": "කාලසෙස", "meaning": "මෝරා", "category": "treatment" },
  { "word": "කාලහීන", "meaning": "ලොත් රුක", "category": "plant" },
  { "word": "කාලා", "meaning": "වැල්මදට, කළුදුරු, ඇඹුල් සරා, කටු පුසක මාල, බෙරා, ඇවට්ඨිය, යකබ", "category": "plant" },
  { "word": "කාලාගරු", "meaning": "කළු අඟිල්, කළුවැල්", "category": "plant" },
  { "word": "කාලාජාජී", "meaning": "කළුදුරු, හීඟදුරු", "category": "plant" },
  { "word": "කාලාක්‍ෂි", "meaning": "හලකහඹු, අවරිය", "category": "plant" },
  { "word": "කාලාන්", "meaning": "යකබ", "category": "treatment" },
  { "word": "කාලානුසාරිනී", "meaning": "කළු ඉරමුසු", "category": "plant" },
  { "word": "කාලානුසාරී", "meaning": "ගල්කහළු, ගලින් උපන් සුවඳ ද්‍රව්‍ය, ඇවට්ඨිය, තුඹ රොලු, කස්තරවල්ලිය", "category": "treatment" },
  { "word": "කාලානුසාරිකා", "meaning": "ගල්මද, ගල්සෙවෙල්", "category": "treatment" },
  { "word": "කාලානුසාරී", "meaning": "කළුවැල්, කළු අගිල්, ඉරමුසු", "category": "plant" },
  { "word": "කාලානුසාරිකා", "meaning": "තුවරලා", "category": "plant" },
  { "word": "කාලානුසාරිකා", "meaning": "තුවරලා, රන් වන් සඳුන්", "category": "plant" },
  { "word": "කාලාය", "meaning": "උඳුඇට (උඳු)", "category": "plant" },
  { "word": "කාලායස", "meaning": "යකඩ", "category": "treatment" },
  { "word": "කාලාන්ත", "meaning": "සුවඳ හිබිරි", "category": "plant" },
  { "word": "කාලී", "meaning": "ලියනගලා, ශිරස්සවාල, ඇත්තෝර ගස, සුලුවැවිල, රන්වන් කාල, වැල්පෙනෙල, අගිල්, බෙරා, කළුදුරු, කෙළිඳ, නිල් බුල", "category": "plant" },
  { "word": "කාලිකා", "meaning": "ඇත්තෝර, කළු අඟිල්, කළුවැල්, සින්සදුන්, මහ කැකිරි", "category": "plant" },
  { "word": "කාලිකගි", "meaning": "අවරිය", "category": "plant" },
  { "word": "කාලිකා", "meaning": "අරළු, කළුදුරු, ශාකා මාර්ක, ජවමාර්ක", "category": "plant" },
  { "word": "කාලිති", "meaning": "රතු අඹ, කළුදුරු, කවෙළු", "category": "plant" },
  { "word": "කාලිකා", "meaning": "කෙළිඳ ගස, බෝ", "category": "plant" },
  { "word": "කාලිභා", "meaning": "කොකකුමු, පෑණිකොමඩු, මහ කැකිරි", "category": "plant" },
  { "word": "කාලිගෙන", "meaning": "බුළුගස", "category": "plant" },
  { "word": "කාලිංගක", "meaning": "හුළු අරළු", "category": "plant" },
  { "word": "කාලිංගක", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "කාලිම්බි", "meaning": "හින් එන්සාල්", "category": "plant" },
  { "word": "කාලිසිකා", "meaning": "හෙළිඳ, (කෙළිඳකාල්)", "category": "plant" },
  { "word": "කාලිසිකා", "meaning": "තිරස්වතාළු, නිල් කැකිරි", "category": "plant" },
  { "word": "කාලිශා", "meaning": "අවරිය", "category": "plant" },
  { "word": "කාලින්", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කාලිය", "meaning": "මාන්තවාල (මතුවාල=කසවැල්)", "category": "plant" },
  { "word": "කාලියක", "meaning": "කළුවැල්", "category": "plant" },
  { "word": "කාලියස", "meaning": "නිඳුතුම්බා, කලුඅගිල්, දුරාභීද්‍රා", "category": "plant" },
  { "word": "කාලි", "meaning": "වැල්පෙනෙල, කළුදුරු, බෙරා", "category": "plant" },
  { "word": "කාලෙයක", "meaning": "යහ, නෙළුම් ඇට, කටු සඳුන්, වැල්මදට, මතුවාල, කොකුම්", "category": "plant" },

  // --- පිටුව 106 (image_9ea001.png) ---
  { "word": "කාලොදර", "meaning": "උග්‍රරස්ස, කටුවෙලඟ", "category": "plant" },
  { "word": "කාලොපල", "meaning": "කාන්තම්", "category": "treatment" },
  { "word": "කාලොගිත", "meaning": "එරමිණියා", "category": "plant" },
  { "word": "කාවසතිකතක", "meaning": "හඟි ගස", "category": "plant" },
  { "word": "කාවරි", "meaning": "තිඹිකොළ, වැල්තුඹ ගෙඩි", "category": "plant" },
  { "word": "කාවලා", "meaning": "පීල, සෙලපිල", "category": "treatment" },
  { "word": "කාවල්ලු", "meaning": "රත්කැල්", "category": "plant" },
  { "word": "කාවාකා", "meaning": "කැකිරි", "category": "plant" },
  { "word": "කාවේරකණ්යක", "meaning": "කාවේරි රුක", "category": "plant" },
  { "word": "කාවේරි", "meaning": "කසා", "category": "plant" },
  { "word": "කාවෙලු", "meaning": "අරලු, මහකැකිරි", "category": "plant" },
  { "word": "කාවාස", "meaning": "පිළිල (ගස්වල බැඳෙන පිළිල)", "category": "plant" },
  { "word": "කාශ්මිරී", "meaning": "ඇත්දෙමට, කපුරු", "category": "plant" },
  { "word": "කාශ්මිරී", "meaning": "ඇත්දෙමට, කපුරු", "category": "plant" },
  { "word": "කාශ්මීසති", "meaning": "ඇත්දෙමට, පොකුරු මුල්", "category": "plant" },
  { "word": "කාශ්මීර", "meaning": "කොකුම්, ඇත්දෙමට", "category": "plant" },
  { "word": "කාශ්මීරප", "meaning": "කොකුම්, පොකුරු මුල්, කොට්ටම", "category": "plant" },
  { "word": "කාශ්මීරජා", "meaning": "ඉවඳ", "category": "treatment" },
  { "word": "කාශ්මීරජීරක", "meaning": "සුදු දුරු", "category": "plant" },
  { "word": "කාශ්මිරා", "meaning": "ඉවඳ", "category": "treatment" },
  { "word": "කාශවරි", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කාශය", "meaning": " mI p#Ni", "category": "treatment" },
  { "word": "කාශයා", "meaning": "රටතෝර", "category": "plant" },
  { "word": "කාශ", "meaning": "උක්, වැලුක්, ඉඟිනි, කාශ රෝගය", "category": "plant" },
  { "word": "කාශක", "meaning": "වැලුක්", "category": "plant" },
  { "word": "කාශනාශන", "meaning": "කකුළුසුනු (කහිටක ශාලි)", "category": "plant" },
  { "word": "කාශවාහිනි", "meaning": "නිකගස", "category": "plant" },
  { "word": "කාශමදි", "meaning": "ඇත්තෝර, ඇත්තෝර", "category": "plant" },
  { "word": "කාශාලමලි", "meaning": "කටුඉබිබුල් ගස", "category": "plant" },
  { "word": "කාශීස", "meaning": "කසීස්", "category": "treatment" },
  { "word": "කාශීසමුභූත", "meaning": "රන් දිය", "category": "treatment" },
  { "word": "කාශුකාර", "meaning": "පුවක්ගස", "category": "plant" },
  { "word": "කාශේෂක්ෂු", "meaning": "වැලුක්", "category": "plant" },
  { "word": "කාශව", "meaning": "දේවදාර, තොරගස", "category": "plant" },
  { "word": "කාශවකදලි", "meaning": "ඇටකෙසෙල්", "category": "plant" },
  { "word": "කාශවකුඹෙරා", "meaning": "හෙලපලොල්", "category": "plant" },
  { "word": "කාශටබ", "meaning": "වැව්රණ - දේවදාර", "category": "plant" },
  { "word": "කාශව දර", "meaning": "වනුමල්, (බාන්වැල්)", "category": "plant" },
  { "word": "කාශවය", "meaning": "නිමේෂකාල (නිමේෂකාල= ඇසිපිය හෙලන ප්‍රමාණ කාලය)", "category": "treatment" },
  { "word": "කාෂ්ටයත", "meaning": "නාග ගස", "category": "plant" },
  { "word": "කාෂ්ටධියුල", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "කාෂ්ටපාටලා", "meaning": "හෙලපලොල්", "category": "plant" },
  { "word": "කාෂ්ටපාටලිකා", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාෂ්ටපාටලි", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාෂ්ටඵලා", "meaning": "පලොල්", "category": "plant" },
  { "word": "කාෂ්ටඵලෙරොහා", "meaning": "හෙලපලොල්", "category": "plant" },
  { "word": "කාෂ්ටපුෂ්ප", "meaning": "වැටකේ", "category": "plant" },
  { "word": "කාෂ්ටමධුකා", "meaning": "වැල්මී", "category": "plant" },
  { "word": "කාෂ්ටයති", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කාෂ්ටරජනී", "meaning": "දුරහරිද්‍රා", "category": "plant" },
  { "word": "කාෂ්ටවල්ලිකා", "meaning": "කඩුකරෝසණ", "category": "plant" },
  { "word": "කාෂ්ටවාරිනී", "meaning": "අරත්ත (රක්ත) කලුවාගස්", "category": "plant" },
  { "word": "කාෂ්ටවාසතුකා", "meaning": "තඹපලා වෙසෙසක්", "category": "plant" },
  { "word": "කාෂ්ටශාරිවා", "meaning": "ඉරමුසු", "category": "plant" },
  { "word": "කාෂ්ටශාලී", "meaning": "රත් කැල්", "category": "plant" },
  { "word": "කාෂඨා", "meaning": "වනුමල්", "category": "plant" },
  { "word": "කාෂ්ඨාගරු", "meaning": "රන්වන් අගිල්", "category": "plant" },
  { "word": "කාෂීසරාසා", "meaning": "කෙසෙල්ගස", "category": "plant" },
  { "word": "කාෂ්ටීල", "meaning": "හෙලවරණස", "category": "plant" },
  { "word": "කාෂ්ටීලා", "meaning": "ඇටකෙසෙල්, හෙලවරා", "category": "plant" },

  // --- පිටුව 107 (image_9e9cdb.png) ---
  { "word": "කාෂෙඨක්ෂු", "meaning": "උක්වෙසෙසක්", "category": "plant" },
  { "word": "කාෂෙඨෝදුම්බරිකා", "meaning": "කොවඩිබුලා ගස", "category": "plant" },
  { "word": "කාෂ්මීර්", "meaning": "රටතෝර", "category": "plant" },
  { "word": "කාෂ්වතද", "meaning": "දේවදාර ගස", "category": "plant" },
  { "word": "කාෂ්ටය", "meaning": "කලා එනසෝර", "category": "plant" },
  { "word": "කාසසසයන", "meaning": "නොරාගස", "category": "plant" },
  { "word": "කාෂ්මිර", "meaning": "නෙල්ලි අල, කොකුම්, කොට්ටම", "category": "plant" },
  { "word": "කාස්මීරජන්මන්", "meaning": "කොකුම්", "category": "plant" },
  { "word": "කාසස", "meaning": "සන්නය, දෙල්ගස", "category": "plant" },
  { "word": "කාස", "meaning": "ඉඟිනි, උක්, වැලුක්, රඹුක්, මූරංගා ගස", "category": "plant" },
  { "word": "කාසං", "meaning": "වැලුක්", "category": "plant" },
  { "word": "කාසඥ", "meaning": "තෝර, බුළු", "category": "plant" },
  { "word": "කාසසනි", "meaning": "කළුවැල්, කළු අගිල්, බුළු, කිරිසඟුළු, සිරිත්තේක්කු, කටුවැල්බටු", "category": "plant" },
  { "word": "කාසනාසිනී", "meaning": "කකුළුසුනු", "category": "plant" },
  { "word": "කාසහඤ්ජන", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "කාසමදි", "meaning": "තෝර, රටතෝර", "category": "plant" },
  { "word": "කාසමර්දිකා", "meaning": "තෝර, රටතෝර", "category": "plant" },
  { "word": "කාසමර්දන", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "කාසරි", "meaning": "තෝර", "category": "plant" },
  { "word": "කාසාරි", "meaning": "රටතෝර", "category": "plant" },
  { "word": "කාසිකා", "meaning": "සෙම, වහඹු", "category": "symptom" },
  { "word": "කාසීර", "meaning": "එලබඩු", "category": "plant" },
  { "word": "කාසීස", "meaning": "කසීස්", "category": "treatment" },
  { "word": "කාසුදෘ", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "කාහලපුෂ්ප", "meaning": "අන්සනමල්, අත්තන", "category": "plant" },
  { "word": "කාහී", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කාළු", "meaning": "ලෝකඩ", "category": "treatment" },
  { "word": "කාළලවණ", "meaning": "බල්ලලුණු, කවළුණු", "category": "treatment" },
  { "word": "කාළසාක", "meaning": "කරවිල ගස", "category": "plant" },
  { "word": "කාළා", "meaning": "ඉඟුක්කාව, වැල්මදට, අමුක්කරා, පලොල්, කළුදුරු, අමිරිය.", "category": "plant" },
  {
    "word": "කැකිරි",
    "meaning": "ස්කන්ධාරි, (හේන් කැකිරි, සීනි කැකිරි, තිත්ත කැකිරි, ගොන් කැකිරි යයි කැකිරි වගී 4 කි. මෙයින් ඇඹුල් රසයෙන් යුත් කුඩා ම කැකිරි වගිය හේන් කැකිරි අශ්මරී රෝගයට ප්‍රත්‍යක්ෂ ඖෂධයකි)",
    "category": "plant"
  },
  {
    "word": "කැකිල්ල",
    "meaning": "වැඩි ප්‍රයෝජනයක් නැති කදින් බෝවී යන ඉඩම් නිසරු වන පැළෑටියකි. මෙයින් ගන්නා ප්‍රයෝජනය නම්: වල වලු ගොඩාලූ, පනල් ආදිය ආවරණය කිරීමයි. තුවාල වෙදකම ට ද ගනිති.",
    "category": "plant"
  },
  { "word": "කැකුණමිල", "meaning": "කැකුණ ලාටු", "category": "plant" },
  { "word": "කැකුලු", "meaning": "කහින, රළු", "category": "treatment" },
  { "word": "කැවිකිරි", "meaning": "මඳුරාගස", "category": "plant" },
  { "word": "කැටිලුණු", "meaning": "කෑමට ගන්නා ලුණු", "category": "treatment" },
  { "word": "කැණිබු", "meaning": "බුලත්වැල, බුලත් කිතිති", "category": "plant" },
  { "word": "කෑද", "meaning": "කාඩි", "category": "treatment" },
  { "word": "කෑදුත්ත", "meaning": "ඔසු වෙසෙසක්", "category": "treatment" },
  { "word": "කෑදරවාල", "meaning": "උඳුපියලි", "category": "plant" },
  { "word": "කෑන්", "meaning": "සබුනාහ, මෝරා", "category": "treatment" },
  {
    "word": "කෑන්ද",
    "meaning": "කාන්දගස - (රක්තාකෑන්ද, බ්‍රකෑන්ද, මුදුකෑන්ද, යයි කෑන්ද වගී තුනකි. මෙයින් රත් කෑන්ද කොළ හා කිරි (ලාවු) ප්‍රයෝජනවත් ය.)",
    "category": "plant"
  },
  {
    "word": "කැම්මේරිය",
    "meaning": "කැම්මේරිය, මොපාලාවිය රත්, කළු, කැම්මේරිය වශයෙන් වගී දෙකකි. එයින් කළු කැම්මේරිය වඩා ප්‍රයෝජනවත් ය. විස්තර 92 පිටුවේ කළු කැම්මේරිය බලන්න.",
    "category": "plant"
  },

  // --- පිටුව 108 (image_9e9955.png) ---
  {
    "word": "කැනහිල් අල",
    "meaning": "සුබමුලි,= ලාමජ්ජි, (නරි අල,) මෙය බින්තල් ගණයට අයත් වාජීකරණ බෙහෙතකි. අරළු වගියෙන් ද එකකි.",
    "category": "plant"
  },
  { "word": "කැනහිල්ල", "meaning": "කවුසෙවෙල් (සිහිනිද)", "category": "plant" },
  { "word": "කැනහිවි", "meaning": "කැනහිල්ල", "category": "plant" },
  {
    "word": "කැපුන්කීරිය",
    "meaning": "තුවාල සුගන්ධන බෙහෙතක්. දළක් වගියට අයත් වූ මේ පැළෑටිය අඩි 8 ක් පමණ උසට වැවෙයි. මෙහි කඳ ඇලවේ වැලක් පමණ ඇත. කොළ අඟල් 1 1/2 x 1 පමණ දිග - පළල ය. ඕවාල හැඩයෙන් යුක්ත ය. මේ කොළ එක තැන දෙක බැගින් දෙපසට බෙදී තිබේ. දළක් ගසේ මෙන් ම මේ පැළෑටියේ ද සෑම තැන ම සුදුපාට කිරි පිරී ඇත. මෙහි කරටි තලා (පොඩිකර) කැපුම් තුවාල වලට ලේ පිටින් බැඳීමෙන් එහි තුවාල පැසවන්නේ නැතුව ඉතා ඉක්මනින් සුව වෙයි.",
    "category": "plant"
  },
  { "word": "කැබිලිත්තෙ නටන්නා", "meaning": "වී පොරී (රහස් බේත් වට්ටෝරුවක එන වචනයක්)", "category": "treatment" },
  {
    "word": "කැබෙල්ල",
    "meaning": "කැබෙල්ල ගස - (තේ ගසට සමාන මේ ගසේ දළු මාළු වට හා තේ කොළ වෙනුවට පිළියෙල කර ගත හැක)",
    "category": "plant"
  },
  { "word": "කැම්මිර", "meaning": "කැම්මේරිය", "category": "plant" },
  { "word": "කැම්මේරිය", "meaning": "කළුකැම්මේරිය (කාකජංඝා) නිදිගන්වන පැළෑටියකි.", "category": "plant" },
  { "word": "කැම්පීචා", "meaning": "(කැම්පුවා) - කැම්පීචා කස.", "category": "treatment" },
  { "word": "කැරවි", "meaning": "ගාජ්ජාර - (ඇදුමට ප්‍රත්‍යක්ෂ බෙහෙතකි)", "category": "treatment" },
  { "word": "කාල", "meaning": "සබුනාහ, බෑවිල, කණේරා, කිණිහිරි", "category": "treatment" },
  {
    "word": "කාලනිය",
    "meaning": "වල්ඟා (අරත්ත, ඉඟුරු, වල් ඉඟුරු, කළුවා අල වගියට අයත් ගසකි.) තද සුවඳකින් යුත් මේ වගියේ මල් සහ බඩ බුලත් විට රසවත් කිරීමට ගනිති.",
    "category": "plant"
  },
  { "word": "කැලුම්", "meaning": "මීහනෙල් අල", "category": "plant" },
  { "word": "කැලෙන්සාපු පොන්ත", "meaning": "කටුකැල්ල (රහස් බේත් වට්ටෝරුවක එන වචනයක්)", "category": "treatment" },
  { "word": "කැවිඩි", "meaning": "කැප්පෙටියා", "category": "plant" }
];