// data_288_296.js - පිටු 288 සිට 296 දක්වා සියලුම වචන
const data_extra_288_296 = [
    // --- පිටුව 288 ---
    { "word": "පණාපුෂ්පි", "meaning": "පොලොස්", "category": "plant" },
    { "word": "පණි", "meaning": "අඹ", "category": "plant" },
    { "word": "පුණ්ජික", "meaning": "කරව්, කරවිල", "category": "plant" },
    { "word": "පණිලතා", "meaning": "බුලත් වැල", "category": "plant" },
    { "word": "පණිවා", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "පණීව", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "පණ්වේ", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "පණ්ඩිව", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "පණ්ඩිතා", "meaning": "බුලත්", "category": "plant" },
    { "word": "පත්", "meaning": "පෙන්ත", "category": "plant" },
    { 
        "word": "පත්කෑල", 
        "scientific": "Butea Frondosa",
        "meaning": "රත්කෑල ගස්. පත්කෑල (රත් කෑල), කැට කෑල (ගැට කෑල) යයි කෑල වර්ග දෙකකි. එයින් ගැට සහිත සුදු කඳක් ඇති වඩා නිල් පාට නොවූ කොස් කොළ ප්‍රමාණ හැඩහුරුකමින් යුත් කොළ ඇති අඩි පණහක් පමණ උසට වැවෙන වර්ගය කැටකෑල නමි. මේ වර්ගයේ පොතු තැල්ම - උළුක්කුව - ඉදිමුම ඇතුළු කැඩුම්-බිඳුම් වෙද කමට ත් ගව වෙද කමට ත් ගනිති. පත් කෑල (රත් කෑල) රත් පාටට හුරු කඳක් ඇති අඩි හැත්තෑ පහක් පමණ උසට වැවෙන විශාල ගසකි. මේ ගසේ කොළ කැටකෑල කොළ වලට වඩා විශාල ය. තද නිල් පැහැයකින් යුක්ත ය. එකවරම ගස පිරී යන සේ අතු අග පිපී යන රන් පාට මල් සමූහය දින දෙකක් තුනක් තුළ පර වී වැටී ගොස් ගස් යට රතු පලස් ඇතිරුවාක් වැනි ශෝභාවක් දරයි. “දුරට පෙනෙන මේ මල් ගිනි කඳලි යයි සිතා රවටී සිවල්ලු දුව එති” යි යනු ජන ප්‍රවාදයකි.\n\nඅවුරුදු තුන් සියයක් ජීවත් විය හැකි බෙහෙතක්:\nමහනුවර සමයේ විසූ ශ්‍රී රත්නශෙඛර නමැති රාජ වෛද්‍යවරයකු විසින් ලියන ලද අත් වෙද පොතක මිනිසෙකු ට අවුරුදු තුන් සියයක් ජීවත් විය හැකි පුදුම බෙහෙතක් ගැන සඳහන් වෙයි. “විශාල ලෙස වැඩුණ පත්කෑල ගසක මුල සිට බඹය (අඩි හය) ක් උසින් උඩ කොටස කපා හර ඉතිරි වන ඒ මුල් කොටස මුදුනෙහි ලොකු වන්ගෙඩියක ඇතුල් කුහරය පමණ විශාල සිදුරක් පහතට සාරා ඒ සිදුර ඇතුළට ඇට අස් කළ අමු නෙල්ලි පලම් හැට හතරක් බහා ඒ වර්ගයේ ලී කෑල්ලකින්ම ඇබයක් ගසා බිම සිට ඒ ලී කොටස වැසී යන පරිදි අඩි හයක් උසට ගොම වරටි (වියලුනු ගොම) ගොඩ ගසා ඒ ගොම වරටි වලට ගිනි තබා, ගොම වරටි සම්පූර්ණයෙන් දැවී ගියාට පසු උතුරා නැගගෙන ඇවිත් එකට මුසු වී තිබෙන ඒ පලාශ සාරය සහිත නෙල්ලි කල්කය ගෙන ගිතෙලින් අඹරා, නොපිරිහුනු ශරීර ශක්තිය ඇති (පණස් විය නොඉක්මවූ) ස්ත්‍රියක් හෝ පුරුෂයෙක් ගෙන ඉස් සෝදා නහවා පිරිසිදු කොට පිරුවට අන්දවා මැසි, මදුරුවන් ගෙන් උපද්‍රවා නොවන පරිදි ආරක්‍ෂා සහිත ව විශේෂ ඇතුල් කාමරයක තබා මේ නෙල්ලි කල්කය ත් උණු කළ එළකිරි ත් පමණක් දිනකට තුන් වර බැගින් දිනපතා මසක් ආහාර වශයෙන් දිය යුතුයි. මෙසේ මේ රසායනය එළකිරි සමග දින පසළොසක් අනුභව කරන විට ඔහු ගේ හෝ ඇය ගේ ඉස කෙස් නිය පොතු දත් හා සම ත් ගැලවී යයි. අනිත් දින පසළොස අනුභව කරන විට ඒ සියල්ල ම යොදින් වැඩී තරුණ භාවයට පත් වෙයි. මෙසේ තිරිහන් වූ පසු අවුරුදු තුන් සියයක් ජීවත් විය හැකියි” ඉන් පසු වෙන විශේෂ පාවිච්චියක් හෝ ප්‍රතිකාරයක් නැත. (පත්කෑල ප්‍රධාන වර්ගයේ වාජීකරණ ඖෂධයකි. අගින් කපා දැමූ ගසේ මුල කොටස ගොම රොඩු ගින්නෙන් රත් වන විට මුල් සහිත සම්පූර්ණ මුල කොටසේ ම ඇති සාරය උතුරා මුදුනෙහි වූ සිදුරෙහි තිබෙන නෙල්ලි පලම් හැට හතර සමග එකට මිශ්‍ර වෙයි. නෙල්ලි ද සෞම්‍ය ධාතු වර්ධනය වන ඖෂධයකි. මෙසේ ඇතිවන මිශ්‍රනයෙහි ජීවන බලය වැඩි දියුණු කිරීමේ යම් කිසි ශක්තියක් ඇතුවාට කිසි ම සැකයක් නැත. අප ඇසූ-දුටු කාලයක පරීක්‍ෂණයකට භාජන කර නැති මේ වාජීකරණ ක්‍රමය අත්හදා බැලීම නවීන විද්‍යාවේ හා මානව සමාජයේ දියුණුවට හිතැති අයට භාර වූවකි.", 
        "category": "plant",
        "image": "img_288_patkaela.jpg"
    },

    // --- පිටුව 289 ---
    { "word": "පත්තක්කා", "meaning": "කොමඩු වර්ගයක්", "category": "plant" },
    { "word": "පත්තබඟ", "meaning": "රත්හඳුන්, පතඟි", "category": "plant" },
    { "word": "පත්තිමසාර", "meaning": "අරළු", "category": "plant" },
    { "word": "පත්නිය", "meaning": "අරළු", "category": "plant" },
    { "word": "පත්තුර", "meaning": "මුගුණුවැන්න", "category": "plant" },
    { "word": "පත්තෘයාගී", "meaning": "මුගුණුවැන්න", "category": "plant" },
    { "word": "පත්‍ර", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "පත්‍රපන්ති", "meaning": "ගඩා දෙහි, (කුඩුලු දෙහි)", "category": "plant" },
    { "word": "පත්‍රය", "meaning": "මාරා, මදටිය, අරළු, වැටකොළු, කිරි පලා, රසකිඳ, මල් වැටකොළු, සෑම ගස්", "category": "plant" },
    { "word": "පත්‍රශාකා", "meaning": "සූකිරි, තම්පලා", "category": "plant" },
    { "word": "පත්‍රයා", "meaning": "අරළු", "category": "plant" },
    { "word": "පත්දලු", "meaning": "කොල්ලම් කොළ", "category": "plant" },
    { "word": "පත්පට", "meaning": "පත්පාඩගම් (පැපිලිය)", "category": "plant" },
    { "word": "පත්තරාකම්", "meaning": "පද්මරාග", "category": "mineral" },
    { "word": "පත්මෘත්‍ය", "meaning": "තුවර = ප්‍රතිනිධි වශයෙන් සුවඳ කොට්ටම් ගනිති.", "category": "plant" },
    { "word": "පත්රිය", "meaning": "ලිහිණියා", "category": "plant" },
    { "word": "පත", "meaning": "කලන් (48) හතලිස් අට", "category": "measurement" },

    // --- පිටුව 290 ---
    { "word": "පතක", "meaning": "සුවැන්න", "category": "plant" },
    { "word": "පතඟි", "meaning": "කොළ සහ ලියන් රත් කිහිරිය වලට සමාන කටු සහිත මේ වර්ගය ආදිම යුගයෙහි සිට ලංකාවේ ඖෂධ වශයෙන් හා සායම් වශයෙනුත් භාවිත කර ගෙන එන්නකි. රත් කිහිරිය මෙන් ම මේ වර්ගයේ හර (අරටු) ද පද්මරාග වර්ණයෙන් යුක්ත ය. තනිකර පතඟි අරටු කෂාය, අතීසාරයට හා රක්තාතීසාරයට ප්‍රත්‍යක්‍ෂ යි.", "category": "plant" },
    { "word": "පතඟබඟ", "meaning": "පතඟි, වැල්මදට", "category": "plant" },
    { "word": "පතපලඟු ගිනිසු", "meaning": "උනු අළු පල්ලේ ලා පුලුස්සා ගත් ප්‍රප (කැවිලි) වර්ග", "category": "food" },
    { "word": "පතර", "meaning": "සමූහය, පෙනි", "category": "general" },
    { "word": "පතරාජ", "meaning": "ලොලු ගස්. ශ්ලෙෂ්මාතක. ලොකු- කුඩා වශයෙන් ලොලු වර්ග දෙකකි. විශාල ලෙස වැඩෙන මේවායේ ගෙඩි කෑමට ප්‍රිය යි. වැඩි පුර කෑවොත් විරේක වෙයි. මේ ගසේ සෑදෙන කටු වල මල් වැනි මල් පොකුරු රසවත් ව්‍යඤ්ජනය කි. ලොලු පොතු බහු මූත්‍ර දෝෂ සමනය පිළිබඳව ත්, සෙම් රෝග පිළිබඳව ත්, ධාතු ශක්තිය වර්ධනය කිරීම පිළිබඳවත් ඖෂධයක් වශයෙන් ප්‍රසිද්ධ ය.", "category": "plant" },
    { "word": "පන්", "meaning": "කුඹුක්, සුදු කුඹුක්, නියඳ", "category": "plant" },
    { "word": "පතිද්‍රැම", "meaning": "කිහිරි, වෙළඟ ගස", "category": "plant" },
    { "word": "පති බිම්බිකා", "meaning": "කලාදුරු, කලුදුරු", "category": "plant" },
    { "word": "පතිමාලි", "meaning": "හෙළ දඹ", "category": "plant" },
    { "word": "පතිමි", "meaning": "සිරිල", "category": "plant" },
    { "word": "පතිවෘත", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "පතු", "meaning": "කකුල", "category": "anatomy" },
    { "word": "පතුක්", "meaning": "පතොක් = බඩ දිව, (දළුක් පවුලට අයත් මේ ගස් කටු සහිත ය. දත් කැක්කුමට හා වෙනත් තෙල් බෙහෙත් වලට අවශ්‍ය ඖෂධයකි.", "category": "plant" },
    { "word": "පතුල් විදුර", "meaning": "පතුල් පැලීම", "category": "treatment" },
    { "word": "පත්‍යා", "meaning": "හෙළ වදකසා", "category": "plant" },
    { "word": "පත්‍යාලතා", "meaning": "කිරිපලා, බුදු, රසකිඳ", "category": "plant" },
    { "word": "පත්‍ර", "meaning": "කොල්ලම්කොළ, කිහිරි, තලිස් පත්‍ර, කුරුඳු පොතු, රත් අබරු", "category": "plant" },
    { "word": "පත්‍රක", "meaning": "ඇඹුලැඹිලිය, කොල්ලම් කොළ, උක් ගස", "category": "plant" },
    { "word": "පත්‍රකා", "meaning": "රසකිඳ, වසාවාසි, කවුඩු උඩැත්ත", "category": "plant" },
    { "word": "පත්‍රස්න", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "පත්‍රන්‍යය", "meaning": "ගබාදෙහි", "category": "plant" },
    { "word": "පත්‍රපක්‍ෂි", "meaning": "කර ගස, පොණකර, කහ පොණකර", "category": "plant" },

    // --- පිටුව 291 ---
    { "word": "පත්‍ර පර්ණිකා", "meaning": "හිඟුරු පියලි", "category": "plant" },
    { "word": "පත්‍රපුෂ්ප", "meaning": "රතුතලා", "category": "plant" },
    { "word": "පත්‍රභ", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "පත්‍රභූෂණ", "meaning": "අශෝක", "category": "plant" },
    { "word": "පත්‍රභූසිත", "meaning": "හෙළ එරබු", "category": "plant" },
    { "word": "පත්‍රමිකා", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "පත්‍ර මල්ලිකා", "meaning": "කොමාරිකා", "category": "plant" },
    { "word": "පත්‍ර මාලිකා", "meaning": "කොමාරිකා", "category": "plant" },
    { "word": "පත්‍ර මණ්ඩිත", "meaning": "නවගිලි එරබු", "category": "plant" },
    { "word": "පත්‍රමානත", "meaning": "හොමුවානු", "category": "plant" },
    { "word": "පත්‍රය", "meaning": "කොළය", "category": "anatomy" },
    { "word": "පත්‍රලා", "meaning": "තෙලකිරිය, ඉන්සලු, සුදු කූර", "category": "plant" },
    { "word": "පත්‍රවොච", "meaning": "කුරුඳු පොතු", "category": "plant" },
    { "word": "පත්‍රශ්‍රෙෂ්ඨ", "meaning": "බෙලි", "category": "plant" },
    { "word": "පත්‍රස්නූහා", "meaning": "පතුක්", "category": "plant" },
    { "word": "පත්‍රසංඥ", "meaning": "කොල්ලම් කොළ", "category": "plant" },
    { "word": "පත්‍රසේනා", "meaning": "මස්බැද්ද", "category": "plant" },
    { "word": "පත්‍රහීන", "meaning": "දෙබ කිණ", "category": "plant" },
    { "word": "පත්‍රා", "meaning": "වැල්පෙනෙල", "category": "plant" },
    { "word": "පත්‍රාඛ්‍ය", "meaning": "කොල්ලම් කොළ, තලිස් පත්‍ර", "category": "plant" },
    { "word": "පත්‍රාසන", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "පත්‍රාංග", "meaning": "පතඟි, රත්හඳුන්, වැල් මදට, වසාවාසි, කර ගස", "category": "plant" },
    { "word": "පත්‍රාංගි", "meaning": "නියඳ", "category": "plant" },
    { "word": "පත්‍රාචලි", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "පත්‍රී", "meaning": "දක්", "category": "plant" },
    { "word": "පත්‍රිකා", "meaning": "උඩැත්ත, කවුඩුඋඩැත්ත, මහ දඹ", "category": "plant" },
    { "word": "පත්‍රිත්", "meaning": "තල්", "category": "plant" },
    { "word": "පත්‍රෙලා", "meaning": "වටමිරිස් =(වාල්මොලගු = රුහැණිය)", "category": "plant" },
    { "word": "පත්‍රෝණී", "meaning": "තොටිල", "category": "plant" },
    { "word": "පථ්‍යා", "meaning": "අරළු, සාමගස, මුදුප්පලවි", "category": "plant" },
    { "word": "පද්ම", "meaning": "සුදු නෙළුම්, රත් නෙළුම්, වැල්මදට, පොණකර, හෙළබටු, මැණික්වැන්න, නෙළුම් අල", "category": "plant" },
    { "word": "පද්මකා", "meaning": "නිදිකුම්බ, නෙළුම් ඇට, රත් නෙළුම්, සඳුන්, මහ පොණකර, වැල්මදට, සුවඳ කොට්ටම්", "category": "plant" },
    { "word": "පද්මක", "meaning": "නෙළුම් පෙති බඳු, ලා රත් පැහැති, ද්‍රව විශේෂයකි. කාශ්මීරයෙහි වැවෙන මේ ගසේ හරය පද්මකාෂ්ඨ නමි. පද්මකාෂ්ඨ වෙනුවට ලංකාවේ ගන්නේ පද්මනාල = (නෙළුඹුදැලි = නෙළුම් දඬු) ය. පෙනෙරීක (පොඬරු වලට ද මේ පද්මකාෂ්ඨ යන නම ව්‍යවහාර වේ)", "category": "plant" },
    { "word": "පද්මකඤ්ජරී", "meaning": "නිදිකුම්බ, බිම් තල්, ඌරල", "category": "plant" },
    { "word": "පද්මකණ්ටනිකා", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "පද්මකන්‍ද", "meaning": "ශාලුක, නෙළුඹු දැලි", "category": "plant" },
    { "word": "පද්මකීටී", "meaning": "බටු, නෙළුම්", "category": "plant" },
    { "word": "පද්මකර්ණී", "meaning": "පොණකර", "category": "plant" },
    { "word": "පද්මකා", "meaning": "වැල්මදට, පිළිකා විශේෂයක්", "category": "plant" },
    { "word": "පද්මකාෂ්ඨ", "meaning": "පද්මක නම් සුගන්ධවත් වෘක්ෂයෙහි අරටුව පද්මකාෂ්ඨ නමි.", "category": "plant" },
    { "word": "පද්මකුඤ්ජරිය", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "පද්මකෙශර", "meaning": "නෙළුම් රේණු, දෙඹ ගස්", "category": "plant" },
    { "word": "පද්මකෝචි", "meaning": "මැණික් වැන්න, පුස් වැන්න, පොල්පලා", "category": "plant" },
    { "word": "පද්මගන්ධ", "meaning": "පොණකර", "category": "plant" },
    { "word": "පද්මගන්‍ධි", "meaning": "පද්මකාෂ්ඨ", "category": "plant" },
    { "word": "පද්මචරිනි", "meaning": "ලුණුවිල, පුස්වැන්න, පොල්පලා", "category": "plant" },
    { "word": "පද්මනාල", "meaning": "නෙළුම් දඬු", "category": "plant" },
    { "word": "පද්ම පඤ්චමි", "meaning": "හිඟුරු වැල්, ගුරුන්ද", "category": "plant" },
    { "word": "පද්ම පත්‍ර", "meaning": "නෙළුම් කොළ, පොකුරු මුල්", "category": "plant" },

    // --- පිටුව 292 ---
    { "word": "පද්මපුෂ්පී", "meaning": "කිණිහිරියා", "category": "plant" },
    { "word": "පද්මභෙද", "meaning": "නෙළුම් මල් රේණු", "category": "plant" },
    { "word": "පද්මය", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "පද්මරවිඥ", "meaning": "එක්පෙති පියුම්", "category": "plant" },
    { "word": "පද්මරාග", "meaning": "පියුම් රාමිණී (රක්ත) හෝ රත් නෙළුම්", "category": "mineral" },
    { "word": "පද්මරාගමණි", "meaning": "පියුම්රාමිණී (රක්ත)", "category": "mineral" },
    { "word": "පද්මවති", "meaning": "පුස්වැන්න, පොල්පලා, මැණික්වැන්න", "category": "plant" },
    { "word": "පද්ම බීජ", "meaning": "නෙළුම් ඇට", "category": "plant" },
    { "word": "පද්මශුභා", "meaning": "මැණික්වැන්න", "category": "plant" },
    { "word": "පද්මසාරනි", "meaning": "එක් පෙති පියුම්", "category": "plant" },
    { "word": "පද්මා", "meaning": "පුස්වැන්න, පොල්පලා, මැණික්වැන්න, කුරුඳු, නිදිකුම්බා, සෙන්දිරින්කා, සිරිතේක්කු", "category": "plant" },
    { "word": "පද්මාක්‍ෂ", "meaning": "නෙළුම් ඇට, තෝර", "category": "plant" },
    { "word": "පද්මාකර", "meaning": "පුස්වැන්න, පොල්පලා, මැණික්වැන්න", "category": "plant" },
    { "word": "පද්මාවර", "meaning": "පොල්පලා, පුස්වැන්න", "category": "plant" },
    { "word": "පද්මාට", "meaning": "තෝර", "category": "plant" },
    { "word": "පද්මාණ්ඩ", "meaning": "නිදිකුම්බා = (කටු නිදිකුම්බා මුල් තම්බා සූකිරි කුඩු දමා බීම කක්කල් කැස්සට ප්‍රත්‍යක්ෂ ඖෂධයකි) එසේම අණ්ඩ කෝෂ ශෝථ, ග්‍රන්ථි ශෝථ වලට ප්‍රලේප සඳහා ද යොදනු ලැබේ.", "category": "plant" },
    { "word": "පද්මාදි මූල", "meaning": "නෙළුම් අල", "category": "plant" },
    { "word": "පද්මාති", "meaning": "මැණික්වැන්න, පොල්පලා", "category": "plant" },
    { "word": "පද්මාවති", "meaning": "පොල්පලා, ලුණුවිල, මැණික්වැන්න", "category": "plant" },
    { "word": "පද්මාහ්වය", "meaning": "පද්මකාෂ්ඨ", "category": "plant" },
    { "word": "පද්මිනී", "meaning": "නෙළුම් රේණු, කෙරව", "category": "plant" },
    { "word": "පද්මෝත්තර", "meaning": "සෙන්දිරික්කා, වතුක්", "category": "plant" },
    { "word": "පදතීර්", "meaning": "තෙලිදිය", "category": "liquid" },
    { "word": "පදර", "meaning": "රසදිය", "category": "mineral" },
    { "word": "පදාරෝහිණී", "meaning": "මුරුවා මුල්, නුග", "category": "plant" },
    { "word": "පදග්නිවි", "meaning": "නිවිති = (නිහිය)", "category": "plant" },
    { "word": "පදුම", "meaning": "වම්මුතු", "category": "plant" },
    { "word": "පදුරොහි", "meaning": "නුග", "category": "plant" },
    { "word": "පදුම", "meaning": "උපුල්", "category": "plant" },
    { "word": "පදුමරාග", "meaning": "පියුම්රාමිණී", "category": "mineral" },
    { "word": "පද්‍රය", "meaning": "පලව් (64) හැට හතර", "category": "measurement" },
    { "word": "පන්ගම්පාලෙයි", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පන්ගිරිපුල්", "meaning": "පෑගිරි", "category": "plant" },
    { "word": "පන්න", "meaning": "දූදු වැල්, = (දුදු=දුහුදු)", "category": "plant" },
    { "word": "පන්නගුහ", "meaning": "වෙල්මුඩ", "category": "plant" },
    { "word": "පන්නාකි", "meaning": "ගල්කූර ගස", "category": "plant" },
    { "word": "පන්නීර්", "meaning": "පිනිදිය", "category": "liquid" },
    { "word": "පන්මල්", "meaning": "තුන්හිරියා පන්", "category": "plant" },
    { "word": "පන්වා", "meaning": "නයා", "category": "animal" },
    { "word": "පන", "meaning": "වී ඇටයක බර, පල්මාණික්කම්", "category": "measurement" },
    { "word": "පනදාරිය", "meaning": "ප්‍රාණජීව පැලෑටිය (නිතර චලනය වන නිල් අවරිය කොළ වැනි කොළ ඇති අඩි එක හමාරක් පමණ උසට වැවෙන පැලෑටියකි)", "category": "plant" },
    { "word": "පනමගල්කණ්ඩු", "meaning": "තල්සූකිරි, (තල් ගල්කණ්ඩු)", "category": "food" },
    { "word": "පනමිපෙනි", "meaning": "කාසි පෙනි = (කිඹුල්වැන්න)", "category": "plant" },
    { "word": "පනලිය", "meaning": "වැල් පෙනෙල", "category": "plant" },
    { "word": "පනස", "meaning": "කොස් ගස", "category": "plant" },
    { "word": "පනසා", "meaning": "මූණමල්", "category": "plant" },
    { "word": "පනාදි", "meaning": "බුව", "category": "plant" },
    { "word": "පනස ඵල", "meaning": "කොස් = (වැල=වරකා) ගෙඩිය", "category": "plant" },
    { "word": "පනාමරම්", "meaning": "තල් ගස", "category": "plant" },
    { "word": "පනාමල්", "meaning": "පොලොස් ගැට (කොස් මල්)", "category": "plant" },
    { "word": "පනික්කි අධිකාරි", "meaning": "කුඩුමිරිස්", "category": "plant" },

    // --- පිටුව 293 ---
    { "word": "පනිච්චෙයි", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "පනිව", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "පනිදිවු", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "පනුසතුරාට", "meaning": "වලඟසාල්", "category": "plant" },
    { "word": "පප්පාබගම්", "meaning": "පත්පාඩගම්, (පැපිලිය)", "category": "plant" },
    { "word": "පප්පාන", "meaning": "පාවට්ටා", "category": "plant" },
    { "word": "පපට", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පපුන්නාග", "meaning": "තුවර, දෙඹ", "category": "plant" },
    { "word": "පබකි", "meaning": "වල්දෙළුම්", "category": "plant" },
    { "word": "පබලය", "meaning": "දළුව", "category": "plant" },
    { "word": "පබලපළු", "meaning": "දළු", "category": "plant" },
    { "word": "පබලු", "meaning": "ප්‍රවාල, (පබුළු)", "category": "mineral" },
    { "word": "පබාතිකා", "meaning": "ප්‍රවාහිකා නම් අතීසාරය", "category": "treatment" },
    { 
        "word": "පඹුරු", 
        "scientific": "Atalantia missionis",
        "meaning": "තද පෑගිරි සුවඳැති ගස් වර්ගයක්. ලෙමන් කොළ වලට සමාන තද නිල් පාට කොළ හා දෙහි මල් වැනි මල් ඇති රට තිබ්බටු පමණ ගෙඩි සෑදෙන අඩි පණහක් පමණ උසට වැවෙන ගසකි. මේ ගසේ මුල් සහ කොළ තද පෑගිරි ගතියකින් යුක්ත ය. ඉතා ශක්තිමත් වූද, බර වූද, සුදු පාට වූද මේ ගසේ ලී කෘත්‍රිම ඇත් දත් (හස්ති දන්ත) සෑදීමට ගනිති. මේ ගසේ කොළ-මුල් හා පොතු දේශීය වෙදකමේ නොයෙක් ඖෂධ යෝග සමග නියම කර තිබේ. ඇතැම් පළාත් වල පඹුරු වෙනුවට ඇඹුල්දෙබොක් වර්ගයට ම අයත් එපමණ ඇඹුල් ගතියක් නැති, සෙවෙල් සහිත ඇඹුල් ගතියක් ඇති, හැඩහුරුකමින් පැණිදෙබොක් වලට සමාන, ප්‍රමාණයෙන් ඊට වඩා විශාල ගෙඩි සෑදෙන ගස් වර්ගයක කොළ පොතු මුල් ආදිය ගනිති. නියම පඹුරු ලෙස ඖෂධ වශයෙන් ගත යුත්තේ මේ ඡායා රූපයෙහි දැක්වෙන තද පෑගිරි ගතියකින් යුත් ඉහත සඳහන් වර්ගය යි. එ වැනි තද සුවඳක් නැති ඇඹුල් දෙබොක් වැනි වර්ගය නො වේ.", 
        "category": "plant",
        "image": "img_293_pamburu.jpg"
    },
    { "word": "පම්පටි", "meaning": "වරාගස", "category": "plant" },
    { "word": "පම්පනක", "meaning": "ඇපල", "category": "plant" },
    { "word": "පමුතුමිනතු", "meaning": "රන්වන් අත්තන", "category": "plant" },
    { "word": "පඹ", "meaning": "සැරසිලි කිරීම සඳහා ගන්නා වැල් වර්ගයක්. මේ වර්ගයේ කොළ ඇදුම (රෝගය)ට ප්‍රත්‍යක්‍ෂ යි.", "category": "plant" },

    // --- පිටුව 294 ---
    { "word": "පයඃ", "meaning": "එළ කිරිබදු අල, කවෙලු, කිරි, වතුර", "category": "compound" },
    { "word": "පයතන්කායි", "meaning": "ලීමැ, මෑ", "category": "plant" },
    { "word": "පයරු", "meaning": "මුංඇට", "category": "plant" },
    { "word": "පයස්", "meaning": "කිරි, කිරිකවෙලු, කිරිපත්", "category": "food" },
    { "word": "පයස්විනී", "meaning": "එළ කිරිබදු, කිරිකවෙලු", "category": "plant" },
    { "word": "පයස්‍ය", "meaning": "කිරි, කිරිකවෙලු, කිරිගහලු, උප්තැල්ල", "category": "plant" },
    { "word": "පයස", "meaning": "කිරි", "category": "food" },
    { "word": "පයසා", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "පයිකාම්මේරිය", "meaning": "ශාතාවාරිය", "category": "plant" },
    { "word": "පයිනාවල්", "meaning": "බද්ධමී", "category": "plant" },
    { "word": "පයෝ", "meaning": "කිරි", "category": "food" },
    { "word": "පයෝධර", "meaning": "තන, අත්තන", "category": "plant" },
    { "word": "පයෝධරක්ෂීර", "meaning": "තනකිරි", "category": "anatomy" },
    { "word": "පයෝධර රස", "meaning": "තනකිරි", "category": "anatomy" },
    { "word": "පයෝධිජ", "meaning": "මුහුදු පෙණ", "category": "nature" },
    { "word": "පයෝබර", "meaning": "පොල්, කිහිරි", "category": "plant" },
    { "word": "පයෝබිධි", "meaning": "මුහුදු පෙණ", "category": "nature" },
    { "word": "පයෝර", "meaning": "කිහිරි", "category": "plant" },
    { "word": "පයෝලතා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "පර්කිරී", "meaning": "පලොල්, පුලිල", "category": "plant" },
    { "word": "පර්පටක", "meaning": "දුරුතැරියා", "category": "plant" },
    { "word": "පර්පති", "meaning": "දුරුතැරියා", "category": "plant" },
    { "word": "පර්පවන්", "meaning": "දුරුතැරියා", "category": "plant" },
    { "word": "පර්ටකම්", "meaning": "පත්පාඩගම්", "category": "plant" },
    { "word": "පර්ණ", "meaning": "බුලත්, අඳුතලා, කෑල, එරබදු, මහපොණකර, මිනුග, කොල්ලම් කොළ", "category": "plant" },
    { "word": "පර්ණචොරක", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "පර්ණභෙදිනී", "meaning": "රුක්අඟුණ", "category": "plant" },
    { "word": "පර්ණලතා", "meaning": "බුලත් වැල", "category": "plant" },
    { "word": "පර්ණවා", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "පර්ණශෙවාල", "meaning": "දියපරඬලා", "category": "plant" },
    { "word": "පර්ණසස", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "පර්ණහිත", "meaning": "බිම් කොහොඹ", "category": "plant" },
    { "word": "පර්ණී", "meaning": "අඳුතලා, දියපරඬල්, ගොටු කොළ, කෑල, ශතපුෂ්ප, මකුණු වැන්න, කොල්ලම් කොළ", "category": "plant" },
    { "word": "පර්ණිකා", "meaning": "පුස්වැන්න, පොල්පලා, නියඳ", "category": "plant" },
    { "word": "පපිට", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පපිටක", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පපිටකි", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පපිටි", "meaning": "කසා, පැපිලිය", "category": "plant" },
    { "word": "පපිටිය", "meaning": "කවඩිබෙල්ලා", "category": "animal" },
    { "word": "පරපනා", "meaning": "වංඇපල", "category": "plant" },
    { "word": "පයසි", "meaning": "කයිලවැල", "category": "plant" },
    { "word": "පර්ම", "meaning": "නික", "category": "plant" },
    { "word": "පර්මිත", "meaning": "මහ ඉඟිනි, සිවිය, අඳුතලා, ඇටිකෙසෙල්", "category": "plant" },
    { "word": "පර්මිතසින්දූර", "meaning": "ගල්සෙවෙල්, ගල්මද", "category": "mineral" },
    { "word": "පර්මිනී", "meaning": "ඉන්සළු, ඇටිකෙසෙල්", "category": "plant" },
    { "word": "පර්මනෙසි", "meaning": "මයිල", "category": "plant" },
    { "word": "පර්මපුෂ්පිකා", "meaning": "දුත්ත", "category": "plant" },
    { "word": "පර්මවල්ලි", "meaning": "ජනන, මල් ජනන, කුස තණ", "category": "plant" },
    { "word": "පර්වි", "meaning": "දෙළුම් පල, පූරැක", "category": "plant" },
    { "word": "පරිවාක", "meaning": "මයිල, මිදිගස", "category": "plant" },
    { "word": "පර", "meaning": "රසදිය", "category": "mineral" },
    { "word": "පරං", "meaning": "ලුහුනු", "category": "plant" },
    { "word": "පරකිර්නිය", "meaning": "අහුගස", "category": "plant" },
    { "word": "පරකුක්‍ෂවය", "meaning": "සුදු දුරු", "category": "plant" },
    { "word": "පරබනිකිලඹු", "meaning": "සිතල, පරබනිපිටෙයි (සිතඅල=චීනඅල)", "category": "plant" },
    { "word": "පරබලා", "meaning": "දියපරඬලා", "category": "plant" },
    { "word": "පරණලා", "meaning": "වේලීවිච්ච කොළ = වියලි ගිය කොළ (පරණ දල = පරණලා = පරඬලා = පරඬල = පරඬලා = පරඬැල්)", "category": "plant" },
    { "word": "පරපුටු", "meaning": "කොවුලන්", "category": "animal" },
    { "word": "පරබොප්", "meaning": "අරන්කහ", "category": "plant" },
    { "word": "පරමපඤ්චක", "meaning": "පොණකර, මිනුග", "category": "plant" },
    { "word": "පරමර්ද", "meaning": "තුවර, තෝර, රටතෝර", "category": "plant" },
    { "word": "පරමායු", "meaning": "පියාගස", "category": "plant" },
    { "word": "පරමුද්ග", "meaning": "තිරිඟු", "category": "plant" },

    // --- පිටුව 295 ---
    { "word": "පරමෙෂ්ටිනි", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "පරලව", "meaning": "ගැටතුඹ", "category": "plant" },
    { "word": "පරලි", "meaning": "දෙඹ", "category": "plant" },
    { "word": "පරව", "meaning": "නිරිහුකුඹු, වියලි කොළ", "category": "plant" },
    { "word": "පරවිෂ්ණු", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "පරවිත", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "පරසතු", "meaning": "හෙළ කොබෝලීල, නා මල්, අබ", "category": "plant" },
    { "word": "පරා", "meaning": "රසදිය, තල, කලාදුරු, සිහින් එන්සාල්", "category": "compound" },
    { "word": "පරාක්පුෂ්පි", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "පරාග", "meaning": "සඳුන්, මල් රේණු, ද්‍රව්‍ය සුණු", "category": "plant" },
    { "word": "පරාජිතා", "meaning": "කංසා", "category": "plant" },
    { "word": "පරාපන", "meaning": "උඳු", "category": "plant" },
    { "word": "පරාවරා", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "පරිකාර", "meaning": "සුළු සාරණ", "category": "plant" },
    { "word": "පරිගුප්ප", "meaning": "වෙල්මුඩ", "category": "plant" },
    { "word": "පරිත්තී", "meaning": "කපු", "category": "plant" },
    { "word": "පරිතකි", "meaning": "අරළු", "category": "plant" },
    { "word": "පරිතාපය", "meaning": "දාහය", "category": "treatment" },
    { "word": "පරිපාකිනි", "meaning": "ත්‍රස්තාවළු", "category": "plant" },
    { "word": "පරිපිෂටක", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "පරිපෙලක", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "පරිපෙලව", "meaning": "කලාදුරු, කොඩවියා මුරු, බ්‍යාමක, තුරුක් තෙල්", "category": "plant" },
    { "word": "පරිබ්‍යාස", "meaning": "හාල්", "category": "food" },
    { "word": "පරිභව්ව", "meaning": "කොට්ටන්", "category": "plant" },
    { "word": "පරිබ්‍රාජ්", "meaning": "වෙල්මුඩ", "category": "plant" },
    { "word": "පරිමණ්ඩලමධ්‍ය", "meaning": "සිහින් මිදි", "category": "plant" },
    { "word": "පරිමර්දි", "meaning": "තෝර", "category": "plant" },
    { "word": "පරිව්‍යය", "meaning": "නාල්සුඩු", "category": "plant" },
    { "word": "පරිව්‍යාධ", "meaning": "කිණිහිරියා ගස්", "category": "plant" },
    { "word": "පරිව්‍යාහ", "meaning": "කිණිහිරියා ගස්", "category": "plant" },
    { "word": "පරිවාද", "meaning": "ඇඹුල්වේ, කිණිහිරියාගස", "category": "plant" },
    { "word": "පරිසෝන්‍ය", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "පරුණ්ජ්‍යාය", "meaning": "මෑකරල්", "category": "plant" },
    { "word": "පරුහෝ", "meaning": "පරක්කන්", "category": "plant" },
    { "word": "පරූෂිකා", "meaning": "යොන්හිඳි, බොරළුදමුණු", "category": "plant" },
    { "word": "පරූෂ", "meaning": "නිල්කටුකරඬු", "category": "plant" },
    { "word": "පරූෂක", "meaning": "බොරළුදමුණු", "category": "plant" },
    { "word": "පරූෂකා", "meaning": "යොන්හිඳි, බොරළුදමුණු", "category": "plant" },
    { "word": "පරුස්", "meaning": "උගුරැස්ස, (බොරළුදමුණු)", "category": "plant" },
    { "word": "පරූසකාදිගණය", "meaning": "බොරළුදමුණු (උගුරැස්ස) ඇත්දෙමට, දෙළුම්, ලමහඵල, බෝ ජාති ඵල, කිරිපළු, ඉඟිනිඇට, මිදි යන මේ ගණය, වා, නසයි. හෘදයට හිතයි- රුචි උපදවයි. පිපාසා, මූත්‍ර දෝෂ ද නසන්නේය.", "category": "compound" },
    { "word": "පරෙවි", "meaning": "පරවියන්", "category": "animal" },
    { "word": "පරේරු", "meaning": "තල පරෙරිය", "category": "plant" },
    { "word": "පරොල්‍ය", "meaning": "ගල්පියල්", "category": "plant" },
    { "word": "පල්", "meaning": "පලම", "category": "measurement" },
    { "word": "පල්පුර", "meaning": "ලප්නාරම්, දෙළුම්ගෙඩිය", "category": "plant" },
    { "word": "පල්මපාසි", "meaning": "කේගර බැවිල", "category": "plant" },
    { "word": "පල්මාණික්කම්", "meaning": "මයුර තුතු", "category": "mineral" },
    { "word": "පල්ලද්‍රැම", "meaning": "අශෝක, (නෝපළු)", "category": "plant" },
    { "word": "පල්ලදු", "meaning": "පල්ලවද්‍රැ = නෝපළු - (අසෝක)", "category": "plant" },
    { "word": "පල්ලවො", "meaning": "ලා පත්‍රය", "category": "plant" },
    { "word": "පල", "meaning": "ලප්නාරන්ගෙඩිය, කුකුරු මන්, තිප්පිලි", "category": "plant" },
    { "word": "පලංකොද", "meaning": "මිරිස්වැල", "category": "plant" },
    { "word": "පලංකෂ", "meaning": "ගුගුල් = (ගුගුල් වර්ග පසකි.)", "category": "plant" },
    { "word": "පලඅටය", "meaning": "ඉලඇටය", "category": "anatomy" },
    { "word": "පලක්‍ෂාර", "meaning": "ලේ", "category": "anatomy" },
    { "word": "පලකයි", "meaning": "වැල්බැවිල", "category": "plant" },
    { "word": "පලකා", "meaning": "එන්සාල්", "category": "plant" },
    { "word": "පලග", "meaning": "පලහටි", "category": "plant" },
    { "word": "පලඞකසා", "meaning": "අරත්ත, ලාකඩ, ඉකිරි, ගොකටු, මඟදඔකලත්, කෑල, මැසිදු, ගුගුල්", "category": "plant" },

    // --- පිටුව 296 ---
    { "word": "පලණ්ඩුක", "meaning": "සුදුළූනු", "category": "plant" },
    { "word": "පලපුර", "meaning": "ලප්නාරං, දෙළුම් ගෙඩි", "category": "plant" },
    { "word": "පලපුරක", "meaning": "දෙළුම්ගෙඩි", "category": "plant" },
    { "word": "පලම්පාසි", "meaning": "බූබැවිල", "category": "plant" },
    { "word": "පලමල්නැටි", "meaning": "කරාබුනැටි, වසාවාසි, සාදික්කා", "category": "plant" },
    { "word": "පලය", "meaning": "කලං 12 (පලම)", "category": "measurement" },
    { "word": "පලවුද්දි", "meaning": "අණ්ඩවාතය (පලවාතය)", "category": "treatment" },
    { "word": "පලශය", "meaning": "රණහුන", "category": "plant" },
    { "word": "පලස්", "meaning": "කෑල", "category": "plant" },
    { "word": "පලසු", "meaning": "කෑල", "category": "plant" },
    { "word": "පලසුප්", "meaning": "කෑලරූක", "category": "plant" },
    { "word": "පලා", "meaning": "පොල්, කෙම්පලා", "category": "plant" },
    { "word": "පලාණ්ඩව", "meaning": "ලූනු, රතුළූනු", "category": "plant" },
    { "word": "පලාණ්ඩු", "meaning": "ලූනු, රතුළූනු", "category": "plant" },
    { "word": "පලාරුප්", "meaning": "පුලිල", "category": "plant" },
    { "word": "පලාල", "meaning": "අඹ, පිදුරු", "category": "plant" },
    { "word": "පලාස්", "meaning": "කෑල, කිරිපළු, කොල්ලම් කොළ, ගස් කෑලිය, එරබදු", "category": "plant" },
    { "word": "පලාසපර්ණ", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "පලාසපර්ණී", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "පලාසිකා", "meaning": "කිරිබදු, හෙළකිහිරි, රත්කිහිරි", "category": "plant" },
    { "word": "පලාසු", "meaning": "කෑල, ගස් කෑලිය", "category": "plant" },
    { "word": "පලිකායි", "meaning": "අක්මැල්ල", "category": "plant" },
    { "word": "පලිත", "meaning": "ගල්නහර, ගල්මද", "category": "mineral" },
    { "word": "පලිපාක", "meaning": "රත්තිඹුල්", "category": "plant" },
    { "word": "පලිරක්කොඩි", "meaning": "එළ කිරිබදු, අලජාති", "category": "plant" },
    { "word": "පලිය", "meaning": "කිරිපලු, පලොල්", "category": "plant" },
    { "word": "පළු", "meaning": "පළුගස, (රාජාදනී) මීලුගස, කිරිපලුගස, තුවර, ඇසමුරුක", "category": "plant" },
    { "word": "පවත්නකායි", "meaning": "විලිකුන්පල", "category": "plant" },
    { "word": "පවපාකල්", "meaning": "වැල්තුඹ", "category": "plant" },
    { "word": "පලොල්", "meaning": "පුලිල", "category": "plant" },
    { "word": "පවඟ", "meaning": "වඳුරා", "category": "animal" },
    { "word": "පවනු", "meaning": "රුක්ගස, පුවඟු", "category": "plant" },
    { "word": "පවන්පාට", "meaning": "කපු", "category": "plant" },
    { "word": "පවනලා", "meaning": "යවකරලුණු", "category": "mineral" },
    { "word": "පවනා", "meaning": "කට්ටකුමන්ජල්", "category": "plant" },
    { "word": "පවනාන්වය", "meaning": "බුව", "category": "plant" },
    { "word": "පවනිමිනීත", "meaning": "මහපටෝල, දුම්මැල්ල", "category": "plant" },
    { "word": "පවල", "meaning": "පබලු", "category": "mineral" },
    { "word": "පවලම්", "meaning": "පබලු", "category": "mineral" },
    { "word": "පවලමල්ලීක්කෙයි", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "පවස", "meaning": "මල්", "category": "plant" },
    { "word": "පවාරු", "meaning": "කරවිල", "category": "plant" },
    { "word": "පවින", "meaning": "මිරිස්", "category": "plant" },
    { "word": "පවිත්‍ර", "meaning": "මීපැණි, බුත්සරණ, තල, තලා, ගිතෙල්, ඉවක්, රත්කතුරා, කසා", "category": "plant" },
    { "word": "පවිත්‍රක", "meaning": "දිවුල්, (අට්ටික්කා) ඇසතු, (බෝගස) කුසතණ, ඊතණ, අලරිය, කුරුඳුමුවත්, ඉරක්", "category": "plant" },
    { "word": "පවුමුත්තුත්තා", "meaning": "රන්වන් අත්තන", "category": "plant" },
    { "word": "පවුරුහල්", "meaning": "හෝපලු ගස", "category": "plant" },
    { "word": "පශු", "meaning": "වැටකේ", "category": "plant" },
    { "word": "පශුගන්ධා", "meaning": "වේලා, රම්මානිස්ස", "category": "plant" },
    { "word": "පශුවත", "meaning": "වලාවැන්න", "category": "plant" },
    { "word": "පස්ඇට", "meaning": "උඳු, මුං, තල, තිරිඟු, වී", "category": "plant" },
    { "word": "පස්ඇඹුල්", "meaning": "දෙහි, දෙබර, නාරං, අගඩා, (නස්නාරං), ගොරක", "category": "plant" },
    { "word": "පස්කටු", "meaning": "ගොකටු (නෙරෙන්චි) කටුවැල්බටු, බටු, කටුකරඬු, කරඹ", "category": "plant" },
    { "word": "පස්කුල්", "meaning": "ඉඟුරු, ගම්මිරිස්, තිප්පිලි, අබ, වදකහ", "category": "plant" },
    { "word": "පස්කුල් බඩු", "meaning": "සුදු දුරු, කළු දුරු, කොත්තමල්ලි, අබ, උළුහාල්", "category": "plant" },
    { "word": "පස්කොල්", "meaning": "පඤ්චකෝල, 285 පිට බලන්න.", "category": "compound" },
    { "word": "පස් කොළ", "meaning": "නික, එරබු, තොටිල, බෙලි, කුඹුරු යන මේ ගස්වල කොළ", "category": "compound" }
];

