// data_260_269.js - පිටු 260 සිට 269 දක්වා සියලුම වචන
const data_extra_260_269 = [
  // --- පිටුව 260 ---
  { "word": "ද්‍රැම", "meaning": "ගස, දවගස, තල්ගස, එරබදු, කෙළිඳ, දෙල්ම් ගස, ඇසල", "category": "plant" },
  { "word": "ද්‍රැමකණ්ටකා", "meaning": "ඉඹුල්ගස", "category": "plant" },
  { "word": "ද්‍රැමකිල", "meaning": "දේවදාරු වෘක්‍ෂය", "category": "plant" },
  { "word": "ද්‍රැමන්චි", "meaning": "කෙළිඳපොතු", "category": "plant" },
  { "word": "ද්‍රැමබවජ", "meaning": "තල්ගස", "category": "plant" },
  { "word": "ද්‍රැමතබ", "meaning": "එරබදු ගස", "category": "plant" },
  { "word": "ද්‍රැමශිර්ෂ", "meaning": "දෙල්ම්ගස", "category": "plant" },
  { "word": "ද්‍රැමශ්‍රේෂ්ඨ", "meaning": "ප්‍රධාන වෘක්‍ෂය, තල්ගස", "category": "plant" },
  { "word": "ද්‍රැමව්‍යාධි", "meaning": "ලාකඩ, වෘක්‍ෂරෝගය", "category": "symptom" },
  { "word": "ද්‍රාමයා", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "ද්‍රාමාරුහා", "meaning": "වම්මුතු වෙසෙසක්", "category": "plant" },
  { "word": "ද්‍රාමේශ්වර", "meaning": "තල්ගස, ශ්‍රේෂ්ඨවෘක්‍ෂය", "category": "plant" },
  { "word": "ද්‍රාමෝත්පල", "meaning": "කිනිහිරි", "category": "plant" },
  { "word": "ද්‍රාවෘක්ෂ", "meaning": "කොළොම්", "category": "plant" },
  { "word": "ද්‍රාෂ්ටිකාන්ත", "meaning": "පොණ්ඩරු (පොඩරු)", "category": "plant" },
  { "word": "ද්‍රාෂ්ටිභේද", "meaning": "පොල්පලා", "category": "plant" },
  { "word": "ද්‍රාෂ්ටිවියාධි", "meaning": "තලිස් පතුරු", "category": "plant" },
  { "word": "ද්‍රාසද", "meaning": "මරදන මාණික්", "category": "treatment" },
  { "word": "ද්‍රාසල්ලක", "meaning": "පියාගස", "category": "plant" },
  { "word": "ද්‍රැ", "meaning": "අමුරන්", "category": "plant" },
  { "word": "ද්‍රේක (කා)", "meaning": "කොසඹ වෙසෙසක්", "category": "plant" },
  { "word": "ද්වාදශ පත්‍රිකා", "meaning": "සතකුප්ප (ශත පුෂ්ප)", "category": "plant" },
  { "word": "ද්වාදශාත්මන්", "meaning": "වරාගස", "category": "plant" },
  { "word": "ද්වාදශිකාය", "meaning": "කළු දෙලුම්, (පලව්)", "category": "plant" },
  { "word": "ද්වාරකා", "meaning": "කපු", "category": "plant" },
  { "word": "ද්වාරදාරු", "meaning": "තේක්ක ගස", "category": "plant" },
  { "word": "ද්වික්‍ෂාර", "meaning": "යවක්‍ෂාර, සජ්ජික්‍ෂාර, යන කාරම් දෙවගය.", "category": "treatment" },
  { "word": "ද්වික්‍ෂීර", "meaning": "එළ කිරි, එළු කිරි යන දෙවගය", "category": "treatment" },
  { "word": "ද්විකා", "meaning": "අගිල් දර", "category": "plant" },
  { "word": "ද්විකටුක", "meaning": "තිප්පිලි, ගම්මිරිස් යන දෙවගය", "category": "plant" },
  { "word": "ද්විකාවාක්ෂ", "meaning": "හොරගස", "category": "plant" },
  { "word": "ද්විකාකොලි", "meaning": "කවෙලු, කිරි කවෙලු යන දෙවගය", "category": "plant" },
  { "word": "ද්විග්නයුෂණ", "meaning": "මහකරඹ", "category": "plant" },
  { "word": "ද්විජ", "meaning": "කොත්තමල්ලි, රණතිය, මුදු පෙණ, සිරිතේක්කු, තුඹුරු වෘක්‍ෂය", "category": "plant" },
  { "word": "ද්විජකුත්සිත", "meaning": "ලෝලු", "category": "plant" },
  { "word": "ද්විජකේතු", "meaning": "දෙබම් වෙසෙසක්", "category": "plant" },
  { "word": "ද්විජවන්දනීය", "meaning": "කිකිරිදිය", "category": "plant" },
  { "word": "ද්විජප්‍රියා", "meaning": "මුවකිරිය, සෝමලතාව", "category": "plant" },
  { "word": "ද්විජයෂ්ටි", "meaning": "දම් දෙව් සුදු (සිරිතේක්කු)", "category": "plant" },
  { "word": "ද්විජවාක්‍ෂ", "meaning": "එරබදු, කාල", "category": "plant" },
  { "word": "ද්විජසේනහ", "meaning": "කාල ගස", "category": "plant" },
  { "word": "ද්විජසපනා", "meaning": "මහ මෑ", "category": "plant" },
  { "word": "ද්විජාධිකා", "meaning": "කුලුරණ", "category": "plant" },
  { "word": "ද්විජේන්ද්‍රක", "meaning": "දෙහි ගස", "category": "plant" },
  { "word": "ද්විතීයශරීර", "meaning": "කවෙලු, කිරි කවෙලු", "category": "plant" },
  { "word": "ද්විතීයශරීරාකොලි", "meaning": "කිරි කවෙලු", "category": "plant" },
  { "word": "ද්විතීය කස්තුරි", "meaning": "පතුක්", "category": "plant" },
  { "word": "ද්විතීයචෝරකා", "meaning": "අරණකසා (හරන්කහ)", "category": "plant" },
  { "word": "ද්විතීයත්‍රිඵලා", "meaning": "මිදි, ඉඳි, ඇටදෙමට යන තෙවගය", "category": "plant" },
  { "word": "ද්විතීය යව", "meaning": "කලු තලා", "category": "plant" },
  { "word": "ද්විතීයානා", "meaning": "වෙනිවැල්", "category": "plant" },
  { "word": "ද්විතීයෝකි", "meaning": "වරා, හෙළ වරා", "category": "plant" },
  { "word": "ද්වීතුතාම", "meaning": "රිදී තුත්තම්, මයුර තුත්තම් (පල් මානික්කම්)", "category": "treatment" },
  { "word": "ද්වීතුතානා", "meaning": "කිඹුල් වැන්න, (සවසති කා=පනව් පෙති)", "category": "plant" },
  { "word": "ද්විදල", "meaning": "අග්මන්තක වෘක්ෂය, ඇටිවේරිය", "category": "plant" },

  // --- පිටුව 261 ---
  { "word": "ද්විධාන්මිකා", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ද්විධාතු", "meaning": "මිනිරන්, (අනුක)", "category": "treatment" },
  { "word": "ද්විබාලේඛ්‍ය", "meaning": "කිතුල් ගස", "category": "plant" },
  { "word": "ද්විතිගා", "meaning": "හරිදා, දාරු හරිදා යන දෙවගය", "category": "plant" },
  { "word": "ද්විතීයුසකන", "meaning": "මහ කරඹ", "category": "plant" },
  { "word": "ද්විපත්‍රක", "meaning": "වණ්ඩාකා කඳ නම් අල වෙසෙස", "category": "plant" },
  { "word": "ද්විපද", "meaning": "හුණගස", "category": "plant" },
  { "word": "ද්විපර්ණී", "meaning": "අස්වැන්න, පුස්වැන්න", "category": "plant" },
  { "word": "ද්විපායා", "meaning": "දියමින්ත දෙවගය", "category": "plant" },
  { "word": "ද්විපාදිකා", "meaning": "නාගස", "category": "plant" },
  { "word": "ද්විපිට", "meaning": "පුලුත්", "category": "plant" },
  { "word": "ද්විපුට", "meaning": "කොත්තමල්ලි, ඉද්ද ගස", "category": "plant" },
  { "word": "ද්විපුනහ්වා", "meaning": "සුදු-රතු සාරණ දෙවගය", "category": "plant" },
  { "word": "ද්විබ්‍රාහ්මී", "meaning": "බැමිනිරිය දෙවගය", "category": "plant" },
  { "word": "ද්විමාෂ", "meaning": "මුගුණුවැන්න, මස්වැන්න", "category": "plant" },
  { "word": "ද්වීර", "meaning": "වේලා ගස", "category": "plant" },
  { "word": "ද්වීරද", "meaning": "නාගස", "category": "plant" },
  { "word": "ද්වීරද පිසපලි", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "ද්වීරේඛ", "meaning": "වේලා ගස", "category": "plant" },
  { "word": "ද්වංවහතා", "meaning": "මරිතොණ්ඩි ගස", "category": "plant" },
  { "word": "ද්වංවනහි", "meaning": "එළ බටු, කටුවැල් බටු", "category": "plant" },
  { "word": "ද්වාඟාවිකා", "meaning": "මැඩහඟු, සිහින් මැඩහඟු", "category": "plant" },
  { "word": "ද්වාෂටකා", "meaning": "සැවැන්දරා", "category": "plant" },
  { "word": "ද්විෂා", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ද්විෂ්‍ය", "meaning": "තකුල්", "category": "plant" },
  { "word": "ද්විප", "meaning": "රත් නෙලුම්, නාගස, තකුල්", "category": "plant" },
  { "word": "ද්විපකා", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "ද්විප සම්භවා", "meaning": "හිඳි, තකුල්", "category": "plant" },
  { "word": "ද්විප සපි", "meaning": "නාගස", "category": "plant" },
  { "word": "ද්විපබලා", "meaning": "සිරිවැඩි බැබිල", "category": "plant" },
  { "word": "ද්විපාබ්‍ය", "meaning": "නාගස", "category": "plant" },
  { "word": "ද්විපාන්තර වචා", "meaning": "සින අල", "category": "plant" },
  { "word": "ද්විපිගසතා", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "ද්විපි / ද්විපිකා", "meaning": "රත්නෙබුල්, හාතාවාරිය", "category": "plant" },
  { "word": "ද්විපිගසත්‍රා", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "ද්වීරදෘගන", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "ද්විපස", "meaning": "අසමෝදගම්", "category": "plant" },
  { "word": "ධකඤ්ජබිල", "meaning": "කාඩි", "category": "treatment" },
  { "word": "ධටාග්‍රයා", "meaning": "මුරුවා වැල්", "category": "plant" },
  { "word": "ධනද", "meaning": "අත්තන, තුන්බෝඅත්තන", "category": "plant" },
  { "word": "ධනතිකා", "meaning": "කොතඹුරු", "category": "plant" },
  { "word": "ධනතුර", "meaning": "අත්තන", "category": "plant" },
  { "word": "ධන්වක", "meaning": "ධන්වන වෘක්‍ෂය", "category": "plant" },
  { "word": "ධන්වඞග", "meaning": "ගෝනු වෘක්‍ෂය, ධන්වන වෘක්‍ෂය", "category": "plant" },
  { "word": "ධන්වනරා", "meaning": "සෝමලතා", "category": "plant" },
  { "word": "ධන්වනහරිග්‍රහණ", "meaning": "කුලුරණ", "category": "plant" },
  { "word": "ධන්වප", "meaning": "මුවන් ආදී සතුන්ගේමස්", "category": "treatment" },
  { "word": "ධන්වනච්ඡද", "meaning": "මිදි ගස", "category": "plant" },
  { "word": "ධන්වන පත්‍රක", "meaning": "මිදි", "category": "plant" },
  { "word": "ධන්ව පට", "meaning": "පියල් ගස", "category": "plant" },
  { "word": "ධන්ව යවාස", "meaning": "250 පිටේ දුරාලභා බලන්න.", "category": "plant" },
  { "word": "ධන්වං", "meaning": "කිරි අඟුණ", "category": "plant" },
  { "word": "ධන්මින්", "meaning": "කුඹුක්, මුහුණමල් ගස", "category": "plant" },
  { "word": "ධන්වී", "meaning": "මුහුණමල්, කුඹුක් ගල්කහඹිලියා", "category": "plant" },
  { "word": "ධන්වීනා", "meaning": "කිරි අඟුණ", "category": "plant" },
  { "word": "ධනය / ධනයක / ධනයා", "meaning": "මුරත, නෙල්ලි, වම්මුතු, කොත්තමල්ලි", "category": "plant" },
  { "word": "ධනයාවෘක්ෂ", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "ධන", "meaning": "කොත්තමල්ලි, කවඩි, සැවැන්දරා", "category": "plant" },
  { "word": "ධනක", "meaning": "අගිල්, (අගරු) කොත්තමල්ලි", "category": "plant" },

  // --- පිටුව 262 ---
  { "word": "ධනඤ්ජය", "meaning": "කුඹුක්, කවසි, රත්නිවුල්", "category": "plant" },
  { "word": "ධනද", "meaning": "නිටොල් ගස, මිදෙල්ල ගස", "category": "plant" },
  { "word": "ධනද්‍රක්‍ෂි", "meaning": "පලොල් ගස", "category": "plant" },
  { "word": "ධනප්‍රියා", "meaning": "බුලුදම් ගස", "category": "plant" },
  { "word": "ධනහර", "meaning": "ග්‍රන්ථිපර්ණී වෘක්‍ෂය", "category": "plant" },
  { "word": "ධනහරි", "meaning": "හරංකහ, හිඟුරු පියලි", "category": "plant" },
  { "word": "ධනා", "meaning": "කොත්තමල්ලි, අමුකොත්තමල්ලි", "category": "plant" },
  { "word": "ධනිකා", "meaning": "කොත්තමල්ලි, රැකහුණ, පුවඟු", "category": "plant" },
  { "word": "ධනි", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධනිය / ධනියක", "meaning": "කොත්තමල්ලි (අමු කොතඹුරු)", "category": "plant" },
  { "word": "ධනු", "meaning": "හුණ ගස, ඇසතු, බදුල්ල, නාගස, නෙල්ලි, වැල් අඟුණ, (කිරි අඟුණ වැල්) මුරත", "category": "plant" },
  { "word": "ධනුඃප(ප්ප)ට", "meaning": "පියල් ගස", "category": "plant" },
  { "word": "ධනුඃශාඛා", "meaning": "මුරුවා වැල, පියල් ගස", "category": "plant" },
  { "word": "ධනුදෘක්‍ෂි", "meaning": "කුඹුරු වැල", "category": "plant" },
  { "word": "ධනුර්ද්‍රැම", "meaning": "උණ ගස", "category": "plant" },
  { "word": "ධනුර්මාලා", "meaning": "මුරුවා වැල", "category": "plant" },
  { "word": "ධනුර්ලතා", "meaning": "සෝමලතා", "category": "plant" },
  { "word": "ධනුර්වාත", "meaning": "වාත රෝගයක් (ධනුස්තම්භ)", "category": "symptom" },
  { "word": "ධනුර්විප", "meaning": "බදුල්ල ගස", "category": "plant" },
  { "word": "ධනුවෘක්‍ෂ", "meaning": "බදුල්ල, හුණ ගස, ඇසතු, නාගස, මුරත, නෙල්ලි", "category": "plant" },
  { "word": "ධනුශ්‍රේණි", "meaning": "නියඳ, මුරුවා, කටරොලු", "category": "plant" },
  { "word": "ධනුෂ්ප", "meaning": "උණ ගස", "category": "plant" },
  { "word": "ධනුස්", "meaning": "පියල්, බදුල්ල ගස", "category": "plant" },
  { "word": "ධනුස්තම්භ", "meaning": "වාත රෝගයක්", "category": "symptom" },
  { "word": "ධනුෂ්පට", "meaning": "කිරිපලුගස, පියල් ගස,", "category": "plant" },
  { "word": "ධනෙයක", "meaning": "කොත්තමල්ලි (කොතඹුරු)", "category": "plant" },
  { "word": "ධමන", "meaning": "බටදඬු, කුලල් බට", "category": "plant" },
  { "word": "ධමනී", "meaning": "නහර, බෙල්ල, කහ, පබලු වැල, පුස්වැන්න", "category": "plant" },
  { "word": "ධමනය", "meaning": "ධමන වෘක්‍ෂය, කහ", "category": "plant" },
  { "word": "ධම්ගකා", "meaning": "අලරිය (කණේරු)", "category": "plant" },
  { "word": "ධමිණී", "meaning": "ධන්වන වෘක්‍ෂය", "category": "plant" },
  { "word": "ධමින", "meaning": "කිරි අඟුණ", "category": "plant" },
  { "word": "ධම්බෝෂින්", "meaning": "බුලු ගස", "category": "plant" },
  { "word": "ධම්පතන", "meaning": "මිරිස්", "category": "plant" },
  { "word": "ධම්පත්‍ර", "meaning": "දිඹුල් ගස", "category": "plant" },
  { "word": "ධම්පට්ටිපා", "meaning": "මිරිස්", "category": "plant" },
  { "word": "ධම්පාතාන", "meaning": "මිරිස්", "category": "plant" },
  { "word": "ධම් වාක්‍ෂ", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "ධම්හන්තා", "meaning": "බුලු ගස", "category": "plant" },
  { "word": "ධරණ", "meaning": "වරා ගස, පුතිද ඇට විසිහතරක බර", "category": "plant" },
  { "word": "ධරණී", "meaning": "ගෞරිපාෂානම්, (කසාවන් පාෂානම්)", "category": "treatment" },
  { "word": "ධරා", "meaning": "එල්ගු-වම්බටු", "category": "plant" },
  { "word": "ධරාවුල", "meaning": "කාමරංගා ගස", "category": "plant" },
  { "word": "ධලණඩක", "meaning": "දාවගස", "category": "plant" },
  { "word": "ධව", "meaning": "දාවගස", "category": "plant" },
  { "word": "ධවනී", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ධවල", "meaning": "හෙළකටරොලු, සැවැන්දරා, දාව, කුඹුක් ගස, සුදු මිරිස්, සක් (සංඛ)", "category": "plant" },
  { "word": "ධවල පට්ටිපා / ධවල පාටලි", "meaning": "හෙළ පලොල් වෙසෙසක්", "category": "plant" },
  { "word": "ධවල ප්‍රකාශ්වා", "meaning": "පිට සුදු සාරණ", "category": "plant" },
  { "word": "ධවල ශාරිවා", "meaning": "සුදු හිරමුසු, වදකහ", "category": "plant" },
  { "word": "ධවලා", "meaning": "සුදු හිරමුසු, වදකහ, එළකටරොලු", "category": "plant" },
  { "word": "ධවලේක්‍ෂු", "meaning": "සුදු උක්", "category": "plant" },
  { "word": "ධවලෝත්පල", "meaning": "හෙළපුල්, (එළමානෙල්)", "category": "plant" },

  // --- පිටුව 263 ---
  { "word": "ධානක", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධාතු", "meaning": "රත් හිරියල්, ගල් සෙවෙල්, මාක්‍ෂික, සිවංගුරු, සාදිලිංගම්, පුෂ්කර", "category": "treatment" },
  { "word": "ධාතුකප්", "meaning": "ගල්සෙවෙල්", "category": "treatment" },
  { "word": "ධාතුකාසිග", "meaning": "කසීස් නම් උප ධාතු වෙසෙස", "category": "treatment" },
  { "word": "ධාතුකේසර", "meaning": "කසීස්", "category": "treatment" },
  { "word": "ධාතුඝ්‍රාහී", "meaning": "රිදී තුතු", "category": "treatment" },
  { "word": "ධාතුඝ්න", "meaning": "කාඩි", "category": "treatment" },
  { "word": "ධාතුවෙතනකර", "meaning": "අග්මන්තක වෘක්‍ෂය, කිරි, නෙල්ලි", "category": "plant" },
  { "word": "ධාතුප්", "meaning": "ගල්මද, ගල්සෙවෙල්", "category": "treatment" },
  { "word": "ධාතුදාපී", "meaning": "පුෂ්කර", "category": "plant" },
  { "word": "ධාතුපත්‍රී", "meaning": "තලිස්පතුරු", "category": "plant" },
  { "word": "ධාතුඵල", "meaning": "රතුහුණු", "category": "treatment" },
  { "word": "ධාතු පුෂ්පිකා", "meaning": "මලිත, (මලිතමල්)", "category": "plant" },
  { "word": "ධාතුමලකා", "meaning": "කලි රඟම්", "category": "plant" },
  { "word": "ධාතුමාක්‍ෂික", "meaning": "මාසිදු", "category": "plant" },
  { "word": "ධාතුමාරිණී", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ධාතුමීෂ්", "meaning": "රියම්", "category": "treatment" },
  { "word": "ධාතුවිෂ", "meaning": "හිරියල් ආදිය", "category": "treatment" },
  { "word": "ධාතුවෙරින්", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ධාතුශෙඛර", "meaning": "කසීස්", "category": "treatment" },
  { "word": "ධාතුශොධනකරී", "meaning": "අරළු", "category": "plant" },
  { "word": "ධාතුසාමහනකර", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ධාතුසම්භව", "meaning": "රියම්", "category": "treatment" },
  { "word": "ධාතුහන්", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ධාතෘපුෂ්පිකා", "meaning": "මසිල ගස", "category": "plant" },
  { "word": "ධාත්‍රිකා", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "ධාත්‍රිපත්‍ර", "meaning": "තලිස් පතුරු, නෙල්ලි", "category": "plant" },
  { "word": "ධාත්‍රිපත්‍රී", "meaning": "තලිස් පතුරු, නෙල්ලි කොළ", "category": "plant" },
  { "word": "ධාත්‍රීඵල", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "ධාත්‍රී", "meaning": "මලිත, නෙල්ලි", "category": "plant" },
  { "word": "ධාත්‍රිශ්වරී", "meaning": "මසිල ගස", "category": "plant" },
  { "word": "ධාන්‍ය", "meaning": "එන්සාල්, කොත්තමල්ලි, තල, පිටවක්කා, ධාන්‍යවගී", "category": "plant" },
  { "word": "ධාන්‍යක", "meaning": "කොත්තමල්ලි, සිහින් මුං", "category": "plant" },
  { "word": "ධාන්‍යක තණ්ඩුල", "meaning": "කොත්තමල්ලි සහල්", "category": "plant" },
  { "word": "ධාන්‍යගණ්ඩා", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධාන්‍යචමස", "meaning": "හබල පෙති", "category": "plant" },
  { "word": "ධාන්‍යත්වච්", "meaning": "දහයියා", "category": "plant" },
  { "word": "ධාන්‍යාදිපඤ්චක", "meaning": "කොත්තමල්ලි, සිද්ධිඟුරු, වම්මුතු, ඉරිවේරිය, බෙලිමුල් යන පස් වගයෙන් කළ කෂාය", "category": "treatment" },
  { "word": "ධාන්‍යබීජ", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධාන්‍යමාස", "meaning": "මෑ, උඳු, කඩල", "category": "plant" },
  { "word": "ධාන්‍යමුල", "meaning": "කාඩි", "category": "treatment" },
  { "word": "ධාන්‍ය යෝනි", "meaning": "කාඩි", "category": "treatment" },
  { "word": "ධාන්‍යරාජ", "meaning": "යව", "category": "plant" },
  { "word": "ධාන්‍යවීජ", "meaning": "කොතඹුරු", "category": "plant" },
  { "word": "ධාන්‍යවීර", "meaning": "මෑ", "category": "plant" },
  { "word": "ධාන්‍යශාක", "meaning": "කොතඹුරු", "category": "plant" },
  { "word": "ධාන්‍යහ්වා / ධාන්‍ය / ධාන්‍යකා", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධාන්‍යාමිල", "meaning": "කාඩි, නෙල්ලි", "category": "treatment" },
  { "word": "ධාන්‍යාසක", "meaning": "හාල්වී", "category": "plant" },
  { "word": "ධානයෙගත", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධානයෝත්තම", "meaning": "ඇල්වී", "category": "plant" },
  { "word": "ධානාක", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධානාචා", "meaning": "අස්වැන්න", "category": "plant" },
  { "word": "ධානා", "meaning": "කොතඹුරු, බදිහාල්, හබලපෙති", "category": "plant" },
  { "word": "ධානාකා", "meaning": "කොතඹුරු", "category": "plant" },
  { "word": "ධානාචූර්ණ", "meaning": "අත්සුණු, බැදිහාල් පිටි", "category": "treatment" },

  // --- පිටුව 264 ---
  { "word": "ධානී", "meaning": "පියාගස", "category": "plant" },
  { "word": "ධාතින්", "meaning": "මෝරගස", "category": "plant" },
  { "word": "ධානුෂ්කා", "meaning": "කරල්සැබෝ", "category": "plant" },
  { "word": "ධානුෂ්ප", "meaning": "උණගස", "category": "plant" },
  { "word": "ධානෙය", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "ධාමනිඩි", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ධාමාර්ගව", "meaning": "හෙළ කරල්සැබ, වැටකොළු", "category": "plant" },
  { "word": "ධාරාෂ්ට්‍රපදී", "meaning": "වලාවැන්න, රතු නිදිකුම්බා", "category": "plant" },
  { "word": "ධාරකා", "meaning": "සිහින් මසන්", "category": "plant" },
  { "word": "ධාරණී", "meaning": "කටුවැල්බටු, රසකිඳ, හිඟුල්", "category": "plant" },
  { "word": "ධාරා", "meaning": "රසකිඳ, බක්මී, කහ, නෙල්ලි, කවෙලු", "category": "plant" },
  { "word": "ධාරා කදම්බ", "meaning": "කොළොම්", "category": "plant" },
  { "word": "ධාරාවුල", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "ධාරින්", "meaning": "මෝර ගස, බුබුර ගස", "category": "plant" },
  { "word": "ධාරොෂණ කිරි", "meaning": "දෙවූ හැටියේ (උණුසුම යන්ට පෙර) කිරි", "category": "treatment" },
  { "word": "ධාවනතී", "meaning": "අස්වැන්න, මෑ, සිහින් වැන්න, පොල්පලා, පුස්වැන්න", "category": "plant" },
  { "word": "ධාවනය", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ධාවන", "meaning": "සාදික්කා, කුරුඳු", "category": "plant" },
  { "word": "ධාවතිකා", "meaning": "කොත්තමල්ලි, කටුවැල්බටු", "category": "plant" },
  { "word": "ධාවනී", "meaning": "කටුවැල් බටු, යක්බේරිය, අස්වැන්න, කොතඹුරු", "category": "plant" },
  { "word": "ධිෂමූල", "meaning": "කටුපිල", "category": "plant" },
  { "word": "ධිර", "meaning": "වෘෂභක, කොකුම්, කවෙලු, මුරුවා, අස්වැන්න", "category": "plant" },
  { "word": "ධිරා", "meaning": "කවෙලු, කිරි කවෙලු, රසකිඳ, සුවඳකහ, ඇටිවේරිය, මේද, මහදුරු", "category": "plant" },
  { "word": "ධිරාහී", "meaning": "ඇටිවේරිය ගස", "category": "plant" },
  { "word": "ධිවරී", "meaning": "වලඟසාල්, හාතාවාරිය", "category": "plant" },
  { "word": "ධිගාරා", "meaning": "කුන්දරුක්කන්", "category": "plant" },
  { "word": "ධුක", "meaning": "වලාවැන්න, බේබර වෙසෙසක්", "category": "plant" },
  { "word": "ධුත්තර", "meaning": "අත්තන", "category": "plant" },
  { "word": "ධුත්තරක", "meaning": "අත්තන", "category": "plant" },
  { "word": "ධුනක", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "ධුම", "meaning": "මියන්දඬුමූල, තුරක් තෙල්, තිරිඟු", "category": "plant" },
  { "word": "ධුමකා", "meaning": "ඇන්අඬි", "category": "plant" },
  { "word": "ධුමකාහ්වය", "meaning": "පොණ්ඩරු", "category": "plant" },
  { "word": "ධුමවූර්ණ", "meaning": "හිරිඟුපිටි", "category": "treatment" },
  { "word": "ධුමවරණ", "meaning": "තුරක් තෙල්", "category": "treatment" },
  { "word": "ධුර්ජරී / ධුර්ජුලි", "meaning": "අත්තන", "category": "plant" },
  { "word": "ධුර්දපුෂ්පිකා", "meaning": "ඇන්අඬි", "category": "plant" },
  { "word": "ධුර්ධර", "meaning": "වෘෂභක", "category": "plant" },
  { "word": "ධුරන්‍ධර", "meaning": "වාහනක නම් ඔසු වෙසෙස, දාවගස", "category": "plant" },
  { "word": "ධුරන්‍ධීඵල", "meaning": "මුංගස", "category": "plant" },
  { "word": "ධුක මුහුණමල් ගස", "meaning": "කැකිරි, කෝවක්කා, කටුඬු, උඩැත්ත", "category": "plant" },
  { "word": "ධුතක", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "ධුප", "meaning": "තුරක්තෙල්", "category": "treatment" },
  { "word": "ධුපදම", "meaning": "රත්කිහිරි", "category": "plant" },
  { "word": "ධුපන", "meaning": "දුම්මැල්ල, දුම්මල", "category": "treatment" },
  { "word": "ධුපවෘක්‍ෂ", "meaning": "හොර, රත්කිහිරි", "category": "plant" },
  { "word": "ධුපසක්වාරි", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "ධුපසරල", "meaning": "හොරගස", "category": "plant" },
  { "word": "ධුපාගාර", "meaning": "අගිල් වෙසෙසක්", "category": "plant" },
  { "word": "ධුපාඞග", "meaning": "හොරඅරටු, (සිරිවටු)", "category": "plant" },
  { "word": "ධුම", "meaning": "තුඹුරු වෘක්‍ෂය, තුරක්තෙල්", "category": "plant" },
  { "word": "ධුමපත්‍ර", "meaning": "දුම්ගස", "category": "plant" },
  { "word": "ධුමා", "meaning": "ඇන්අඬි", "category": "plant" },
  { "word": "ධුමාහ්වා", "meaning": "දුම්ගස", "category": "plant" },

  // --- පිටුව 265 ---
  { "word": "ධූම", "meaning": "මියන්දඬුමුල, තුරක්තෙල්, ගල් සෙවෙල්", "category": "treatment" },
  { "word": "ධූමකා", "meaning": "ඇත්සාටිය", "category": "plant" },
  { "word": "ධූමකාහ්වය", "meaning": "පොණ්ඩරු", "category": "plant" },
  { "word": "ධූමචූර්ණ", "meaning": "තිරිඟු", "category": "plant" },
  { "word": "ධූමප්", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "ධූමනේත්‍ර", "meaning": "දුම්නෙත්‍ර, දුම් බොන කෝව - (පයිප්පය)", "category": "treatment" },
  { "word": "ධූමයෝනි", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "ධූමවෘක්‍ෂ", "meaning": "හොරගස", "category": "plant" },
  { "word": "ධූමිස", "meaning": "තේක්ක ගස", "category": "plant" },
  { "word": "ධූමාඛ්‍යා", "meaning": "ඇටිවේරිය", "category": "plant" },
  { "word": "ධූමිකා", "meaning": "ඇටිවේරිය", "category": "plant" },
  { "word": "ධූතී", "meaning": "ගුගුල්, බළල් ලුණු, අත්තන, හිඟුරුපියලි", "category": "plant" },
  { "word": "ධූනිකාන්", "meaning": "අත්තන", "category": "plant" },
  { "word": "ධූනිමාතුල", "meaning": "අත්තන", "category": "plant" },
  { "word": "ධූතිමාතුභා", "meaning": "රත්ත (රාමභා)", "category": "plant" },
  { "word": "ධූහීර", "meaning": "රසදිය", "category": "treatment" },
  { "word": "ධූතී", "meaning": "බළල් ලුණු, කටුවැල්බටු", "category": "plant" },
  { "word": "ධූමින", "meaning": "දාවගස", "category": "plant" },
  { "word": "ධූලිකදම්බක", "meaning": "කුඹුක්, බක්මී, ලුණුවරණ, කොළොම්, කොබු", "category": "plant" },
  { "word": "ධූලිපුෂ්ප / ධූලිපුෂ්පී", "meaning": "වැටකේ", "category": "plant" },
  { "word": "ධූසර", "meaning": "මුං", "category": "plant" },
  { "word": "ධූසරපත්‍රිකා", "meaning": "ඇත්සාටිය", "category": "plant" },
  { "word": "ධෘව", "meaning": "නුග", "category": "plant" },
  { "word": "ධෘවා", "meaning": "අස්වැන්න", "category": "plant" },
  { "word": "ධෘෂණප්", "meaning": "උණ කොළ", "category": "plant" },
  { "word": "ධෘතරාෂ්ට්‍රපදී", "meaning": "වලාවැන්න", "category": "plant" },
  { "word": "ධෘතිපුද", "meaning": "මහසාරණ", "category": "plant" },
  { "word": "ධේනුකා / ධේන", "meaning": "කොතඹුරු", "category": "plant" },
  { "word": "ධේනුකාරී", "meaning": "නාගස", "category": "plant" },
  { "word": "ධේනුර්ජිවා", "meaning": "ගොඩිවී", "category": "plant" },
  { "word": "ධේනුදුග්ධ", "meaning": "කැකිරි", "category": "plant" },
  { "word": "ධෛයසි", "meaning": "සාදික්කා, ජීවක", "category": "plant" },
  { "word": "ධෝත", "meaning": "නිල්කසීස්", "category": "treatment" },
  { "word": "ධෝතකණ්ඩි", "meaning": "සූකිරි", "category": "treatment" },
  { "word": "ධෝතය", "meaning": "සිලුහුණු", "category": "treatment" },
  { "word": "ධෝතේය", "meaning": "යවිනේධව ලුණු", "category": "treatment" },
  { "word": "ධෝෂර", "meaning": "දාවගස", "category": "plant" },
  { "word": "ධ්‍යාම", "meaning": "කුකුරුමාන්, තුඹ", "category": "plant" },
  { "word": "ධ්‍යාමිකා", "meaning": "එනම් සුවඳ තෘණ වගිය", "category": "plant" },
  { "word": "ධ්වංසිත්", "meaning": "ගල්මෝර", "category": "treatment" },
  { "word": "ධ්වජ", "meaning": "තල්ගස, ලිහුව", "category": "plant" },
  { "word": "ධ්වජද්‍රැම", "meaning": "තල්ගස", "category": "plant" },
  { "word": "ධ්වාංක්‍ෂපක්සා", "meaning": "කලු කැම්මේරිය", "category": "plant" },
  { "word": "ධ්වාංක්‍ෂපටලු", "meaning": "බුලුදම්", "category": "plant" },
  { "word": "ධ්වාංක්‍ෂතුණ්ඩඵලා", "meaning": "බුරල්ලගස", "category": "plant" },
  { "word": "ධ්වාංක්‍ෂනාමා", "meaning": "කොටදිඹුලා", "category": "plant" },
  { "word": "ධ්වාංක්‍ෂනාලා", "meaning": "කාකනාසා", "category": "plant" },
  { "word": "ධ්වාබකොලි / ධ්වාඛෙකෝලි", "meaning": "කිරිකවෙලු", "category": "plant" },
  { "word": "ධ්වාන්තඝාතුක / ධ්වාන්තාරාති / ධ්වාන්තාරි", "meaning": "නෝටිල ගස, වරාගස", "category": "plant" },
  { "word": "ධ්වාඝ", "meaning": "දිඹුල් (අත්තික්කා)", "category": "plant" },
  { "word": "ධ්වාසම්වි", "meaning": "කලුකැම්මේරිය", "category": "plant" },
  { "word": "ධ්වාහාරී", "meaning": "ජටාමාංශ, වරා, කොසඹ, කොකුම්, හිඟුල්, යක්බේරිය", "category": "plant" },

  // --- පිටුව 266 & 267 ---
  { "word": "නක්කන්තිනා", "meaning": "අනෝජා ගස", "category": "plant" },
  { "word": "නක්තවිප්", "meaning": "මාරා ගස", "category": "plant" },
  { "word": "නක්තමාල", "meaning": "මඟුල්කරඳ", "category": "plant" },
  { "word": "නක්තාවර", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "නක්තාහ්ව", "meaning": "මඟුල්කරඳ", "category": "plant" },
  { "word": "නක්‍ෂමාරොහ / නක්‍ෂමාරොහා", "meaning": "හිඳි", "category": "plant" },
  { "word": "නකතද්‍රිය", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "නකාබිගි", "meaning": "කොලු අරළු", "category": "plant" },
  { "word": "නකුල", "meaning": "ජටාමාංශ, අරත්ත, කොසඹ, ඉඹුල්, කොකුම්", "category": "plant" },
  { "word": "නකුලා", "meaning": "කටුකරෝෂණ. (කුවරණ) මෙය ඉන්දියාවේ සිට ලංකාවට ගෙන්වන කුඩා පැලෑටියක වියලන ලද අල (මුල්) ය. මේ වගිය උණ රෝගය හා විරේකාදිය පිණිස ගන්නා නොයෙක් ඖෂධ යෝග සමග යොදනු ලැබේ. ඖෂධ පිණිස ගන්නා විට කටුකරෝෂණ ශුද්ධ කොට ගත යුතුයි.", "category": "plant" },
  { "word": "නකුලී", "meaning": "අරණකසා, සිවිය, යක්බේරිය, හණ", "category": "plant" },
  { "word": "නකුලේෂඨ / නකුලේෂඨා", "meaning": "අරත්ත, කළුවා අල, දන්තකැටියා, ඒකාවේරිය", "category": "plant" },
  { "word": "නඛ / නඛර", "meaning": "දිවිපහුරු, වක්නිය, සක්නැබ", "category": "plant" },
  { "word": "නඛා", "meaning": "ඇන්අඬි", "category": "plant" },
  { "word": "නඛී", "meaning": "සක්නැබ = (නඛි) දෙවර්ගයකි. මේවා සුගන්ධ ද්‍රව්‍ය වලට අයත් ය.", "category": "plant" },
  { "word": "නග්නජිත්", "meaning": "කපු", "category": "plant" },
  { "word": "නග්නිකා", "meaning": "මහකපු", "category": "plant" },
  { "word": "නග්නෙලා", "meaning": "වටමිරිස් (වල්ගාමිරිස් = වාල්මොලගු = රණහංසියා)", "category": "plant" },
  { "word": "නග", "meaning": "ගස, පර්වතය", "category": "plant" },
  { "word": "නගත්‍රිප්", "meaning": "කපුගස", "category": "plant" },
  { "word": "නගරෝෂධී", "meaning": "කෙසෙල් ගස", "category": "plant" },
  { "word": "නගනාවසුරක්", "meaning": "දිඹුල් ගස", "category": "plant" },
  { "word": "නගරි", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { 
    "word": "නගා මැරූ අල (නන්ගලා අල)", 
    "meaning": "මෙය පොතුකොළ පන් වලට සමාන කොළ ඇති අඩි එකහමාරක් පමණ උසට වැවෙන වදකහ ගස් වැනි පැලෑටි වගියකි. මේවා පිදුරුතලාගල-හමුණුකුල- නුවරඑළිය යන ශීතාධික ප්‍රදේශයන්හි බහුල ලෙස වැවේ ය. මේවායේ හැම පැලෑටියක ම අල දෙකක් බැගින් තිබේ. එයින් ලොකු අලය වටප්‍රමාණයෙන් අඟල් 2 1/2 කට සහ කුඩා අලය අඟල් 1 1/2 කට වඩා විශාල ව නො වැඩේ. මිනිසුන් අතර කට කථා වශයෙන් පවතින මේ ඖෂධයෙහි ඇතැයි කියන කාමෝද්දීපනය පිළිබඳ විශ්වාසය සත්‍යයක් දැයි මේ අල යුෂ දිව ගා බැලීමෙන් වටහා ගත හැක. 'මේ අල වාජීකරණ ඖෂධයකි' යන්න ගැන නම් කිසිම සැකයක් නැත.\n\n**රාජවදුල - නන්ගලා**\n\n“රාහුණේ කිරිඳි ගඟ අසබඩ නන්ගලා නමැති වැල් වගියක් තිබේ. ඒවායේ කොළ ඉඟුරු කොළ වැනි ය. වැල් නියහලා වැල් වැනි ය. ඒ වැල් මුල එකකට එකක් ලොකු වූ එකට බැඳී තිබෙන අල දෙකක් බැගින් ඇත. මේ අල සේදී ගඟ දියට මුසු වූ අවස්ථාවල ඒ වතුර නාන අයට පවා කාම ශක්තිය ලැබේ.” මේ වාක්‍යය රාජවදුල නමැති රහස් ඖෂධ පිළිබඳ විස්තර සඳහන් ඖෂධ වදුලක ලියා තිබේ. මේ බෙහෙත් වදුලු පොත මා අතට පත්වූයේ මේ දේශීය වෛද්‍ය ශබ්ද කෝෂය මුද්‍රණය කරවන අවස්ථාවෙහි හදිසියෙන් ම නිසා මේ වැල් සොයා යාමට මට අවකාශයක් නො ලැබීම ගැන කණගාටු වෙමි. එහෙයින් දේශීය වෛද්‍ය ඖෂධ ගුණ ඇල්මක් දක්වන මේ පොත කියවන (පාඨක) භවතුන් මේ ඖෂධ වැල් වගිය සොයා ගැනීම ගැන උනන්දුවක් දක්වනවා ඇතැයි බලාපොරොත්තු වන්නෙමි.\n\n**1 - සිය සොහොයුරිය...**\n\nසිය සොහොයුරිය ද කැටි ව කඩුවල අල ඉදිරීම සඳහා ගිය සහෝදරයෙක්, කඩුවල අල සාරා ගෙන ගෙදර එන්ට සූදානම් වී බුලත් විටක් කෑමට හුණු ගත් උල් පිහිය අසල තිබුන මේ වගියේ අල පඳුරක ගසා තැබුවේලු. ඉන් පසු ඒ පිහි තුඩින් හුණු රැගෙන බුලත්විටක් කෑ සිය සොහොයුරියට මේ අල යුෂ ශරීරගතවීම නිසා කාමුක අදහස් ඇතිවී සිය සොහොයුරා ලවා බිලි බිය සිදුවා ගන්නට උත්සාහ කිරීම ගැන ලැජ්ජාවට හා කෝපයට පත් වූ හෙතෙම නගා (සිය සොහොයුරී) මරා දමා ගෙදර ආවේලු. ඒ නගා මැරීමට හේතු වූයේ මේ අල වගිය නිසා මෙයට නගා මැරූ අල යයි ව්‍යවහාර වූ බව ජන කථාවෙහි එ යි.", 
    "category": "plant" 
  },

  // --- පිටුව 268 ---
  { "word": "නච්චු", "meaning": "කදුරු", "category": "plant" },
  { "word": "නච්චුර", "meaning": "වතුවැල්", "category": "plant" },
  { "word": "නට්ඨමාල", "meaning": "කිරිබෝ ගස, කිරිපළු ගස", "category": "plant" },
  { "word": "නත්කවිජ", "meaning": "හෝපලු, තොවිල, හිරියල්", "category": "plant" },
  { "word": "නත්නසූරිය", "meaning": "කසඹිලියා", "category": "plant" },
  { "word": "නත්නාරම්", "meaning": "නස්නාරම්, (බෙහෙතට ගන්නා නාරන් වගිය) මේවායේ ගස් හා ගෙඩි හින් නාරම් වලට හැඩහුරුවෙන් ම සමාන යි. ඉදුන ගෙඩි වල ඇඹුල් ඉතා ප්‍රියකරු රසයකින් යුක්ත යි. එහෙත් හින් නාරම් වලට වඩා ඇඹුල් සැරයි. ඇතැම් පළාත් වල නස් නාරම් වෙනුවට ඔයිබි දෙහි ගනිති. ඒවායේ ගෙඩි ඉදුන විට යන්තම් කහපාට වෙයි. ගෙඩිය මතුපිට තැතින් තැන ලප වැටී තිබේ. ඇඹුල් අමුතු කර යි. කාරම් ගතියෙන් යුක්ත යි.", "category": "plant" },
  { "word": "නත්වන්", "meaning": "කොබෝලීල ගස", "category": "plant" },
  { "word": "නත", "meaning": "හුවරලා", "category": "plant" },
  { "word": "නතමාල", "meaning": "කරඳ", "category": "plant" },
  { "word": "නතාබණ්ඩි", "meaning": "කකිටකග්‍රිංගි", "category": "plant" },
  { "word": "නද", "meaning": "තෙල", "category": "plant" },
  { "word": "නදන", "meaning": "සුදුහඳුන්", "category": "plant" },
  { "word": "නදනා", "meaning": "මහනෙල් මල", "category": "plant" },
  { "word": "නදි", "meaning": "බෝනුග ගස, කුඹුක්", "category": "plant" },
  { "word": "නදිකාන්තා", "meaning": "අක්මැල්ල, දඹ, කටුවෙළඟ, කොටදිඹුලා ගස", "category": "plant" },
  { "word": "නදිකදම්බක", "meaning": "කටුවෙළඟ", "category": "plant" },
  { "word": "නදිකාමුක", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "නදී කුලප්‍රිය / නදී ජාප්‍රිය", "meaning": "දිය හොමුවඟ", "category": "plant" },
  { "word": "නදීජ / නදීජා", "meaning": "කුඹුක්, කටුවෙළඟ", "category": "plant" },
  { "word": "නදිහල්ලතකි", "meaning": "කඩුකරෝපණ, ගංබටුල්ල", "category": "plant" },
  { "word": "නදීමකුටු", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "නදීවාක්‍ෂ", "meaning": "බුලු", "category": "plant" },
  { "word": "නදීසර්ජ", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "නද්‍ය / නද්‍යාග්‍රිත", "meaning": "හොයදුන්", "category": "plant" },
  { "word": "නද්‍යසිත", "meaning": "හොයලුන්", "category": "plant" },
  { "word": "නද්‍යාවෘත / නන්දාවෘත", "meaning": "වතුසුද්ද", "category": "plant" },
  { "word": "නන්දතිලගා", "meaning": "රැකහුණ (ගස් අඟුණ)", "category": "plant" },
  { "word": "නන්දවෘක්ෂ", "meaning": "බූව ගස", "category": "plant" },
  { "word": "නන්දසුගන්ධි", "meaning": "අරත්ත, කළුවා ගස", "category": "plant" },
  { "word": "නන්දිකාන්තා", "meaning": "නික, ජම්බු, කලුකැම්මේරිය, දියමිදෙල්ල", "category": "plant" },
  { "word": "නන්දිතරා", "meaning": "දාව ගස", "category": "plant" },
  { "word": "නන්දිනි", "meaning": "වටමිරිස්, (වාල්මොලගු), අරළු, හොර", "category": "plant" },
  { "word": "නන්දියාවට්ටම් / නන්දියාවට්ටෙයි", "meaning": "වතුසුද්ද", "category": "plant" },
  { "word": "නන්දිවෘක්ෂ", "meaning": "වතුසුද්ද, මදටිය, මාරා, අටිවිකා", "category": "plant" },
  { "word": "නන්ද්යාවර්තක", "meaning": "ඇසතු භෙදයක්, මැඬහඟු වලට ද පර්යාය නාමයකි.", "category": "plant" },
  { "word": "නන්ද්යාවර්තන", "meaning": "වතුසුද්ද මල", "category": "plant" },
  { "word": "නන්ද්යාවෘත", "meaning": "වතුසුද්ද, තුවරලා", "category": "plant" },

  // --- පිටුව 269 ---
  { "word": "නන්නාරී", "meaning": "නත්නාරිය, ඉරමුසු", "category": "plant" },
  { "word": "නනයාවර්චිචි", "meaning": "දියපරබල්", "category": "plant" },
  { "word": "නනුතෘණ", "meaning": "සක්නැබ", "category": "plant" },
  { "word": "නපද්මක", "meaning": "සුදු ලබු", "category": "plant" },
  { "word": "නප්‍රිය", "meaning": "කලු අගිල්", "category": "plant" },
  { "word": "නභ", "meaning": "තුවරලා", "category": "plant" },
  { "word": "නභුස", "meaning": "රණවරා, ගප්තිප්පිලි, සිවිය, තුවරලා", "category": "plant" },
  { "word": "නමිකොට්ට", "meaning": "පෙනෙල ඇට, ගස් පෙනෙල", "category": "plant" },
  { "word": "නමු", "meaning": "මිදෙල්ල", "category": "plant" },
  { "word": "නමස්කර / නමස්කාරි", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "නමසාල", "meaning": "කෙසෙල්", "category": "plant" },
  { "word": "නමාලිකා", "meaning": "බිමිතල්, ඌරල, නිදිකුම්බා", "category": "plant" },
  { "word": "නමුඛු / නමුසි", "meaning": "ලුණුවරණ ගස", "category": "plant" },
  { "word": "නමුබු", "meaning": "නික ගස", "category": "plant" },
  { "word": "නමේරු", "meaning": "හොර, (සරල)", "category": "plant" },
  { "word": "නයන", "meaning": "ඇස්", "category": "plant" },
  { "word": "නයනභූෂණ / නයනානඤ්ජනිකා", "meaning": "හොයදුන්", "category": "plant" },
  { "word": "නයි ඇස්", "meaning": "බලිද", "category": "plant" },
  { "word": "නයිදිවි", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "නයිපෙණ", "meaning": "අබින්", "category": "plant" },
  { "word": "නයිමිරිස්", "meaning": "හින්මිරිස් (ඉතා ම සැර මිරිස් වර්ගය)", "category": "plant" },
  { "word": "නය්‍යාත්", "meaning": "ලුණුවරණ", "category": "plant" },
  { "word": "නරඵල / නරමු", "meaning": "නරමුත්‍ර", "category": "treatment" },
  { "word": "නරනි", "meaning": "ගිහෙල්", "category": "plant" },
  { "word": "නරදමි", "meaning": "සපිහාවය", "category": "plant" },
  { "word": "නරදුපහතලා", "meaning": "තලා වගියක්", "category": "plant" },
  { "word": "නරබිජු", "meaning": "රණවරා ඇට", "category": "plant" },
  { "word": "නරවලි", "meaning": "ගිරස්ස", "category": "plant" },
  { "word": "නරසෙන්කල්", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "නරිඅල", "meaning": "නිවල්අල = ශාලාමිශ්‍රී = ශුඩාමුලී", "category": "plant" },
  { "word": "නරිඋල්ලිය", "meaning": "ඉකිරිය", "category": "plant" },
  { "word": "නරිප්ප", "meaning": "නරමුත්‍ර, නරදිය, (සර්ප විෂට ඉතාප්‍රත්‍යක්‍ෂ ඖෂධයකි)", "category": "treatment" },
  { "word": "නරිතාවල්", "meaning": "බලුදම්, කාකජම්බු", "category": "plant" },
  { "word": "නරිපයරු", "meaning": "මුංවැන්න", "category": "plant" },
  { "word": "නරිවිලි", "meaning": "ලෝලු", "category": "plant" },
  { "word": "නරන්තාලි", "meaning": "වසතැල්ල", "category": "plant" },
  { "word": "නරේහු හොග්‍ය", "meaning": "සඳුන්", "category": "plant" },
  { "word": "නරේන්ද්‍රාහ්ව", "meaning": "අගිල්", "category": "plant" },
  { "word": "නල්කලත්", "meaning": "කොල්ලු වගියක්", "category": "plant" },
  { "word": "නල්ලවෙන්තේ", "meaning": "නලනෙල්", "category": "plant" },
  { "word": "නල", "meaning": "උණ ගස, බට, රණ උණ, කකුවා", "category": "plant" },
  { "word": "නලක්‍ෂ", "meaning": "රඹුක්, වැළුක්", "category": "plant" },
  { "word": "නලකණ්ට", "meaning": "හෙළ බටු", "category": "plant" },
  { "word": "නල ගොදුරු", "meaning": "වලසා", "category": "plant" },
  { "word": "නලප්", "meaning": "හුණමකුල්, හුණ කපුරු, නෙළුම්", "category": "plant" },
  { "word": "නලද / නලදම", "meaning": "සැවැන්න, කටුකරෝෂණ, ජටාමාංශ", "category": "plant" },
  { "word": "නලමින්", "meaning": "නලමන්සු", "category": "plant" },
  { "word": "නලාරංජි", "meaning": "ලියනහලා", "category": "plant" },
  { "word": "නලි / නලී", "meaning": "බටු", "category": "plant" },
  { "word": "නලිකා", "meaning": "රඹුක්, වැළුක්", "category": "plant" },
  { "word": "නලින", "meaning": "නෙළුම්, ඇඹුල, බුලත්", "category": "plant" },
  { "word": "නලිනීගුහ", "meaning": "නෙළුම් අල", "category": "plant" },
  { "word": "නලිනී", "meaning": "නෙළුම්", "category": "plant" },
  { "word": "නලිනා තුබුසානු", "meaning": "බුලත් වැල", "category": "plant" },
  { "word": "නව", "meaning": "රතු සාරණ", "category": "plant" },
  { "word": "නව අඟිලිය", "meaning": "එරබු", "category": "plant" },
  { "word": "නවවාරම්", "meaning": "නවසාරම්, යවකාර ලුණු", "category": "treatment" }
];