// data_395_404.js - පිටු 395 සිට 404 දක්වා සියලුම වචන සහ විස්තර
const data_extra_395_404 = [
    // --- පිටුව 395 සහ 396 ---
    { 
        "word": "රත් හඳුන්", 
        "scientific": "Pterocarpus Santalinus",
        "meaning": "Pterocarpus Santalinus- රත් හඳුන් නමින් හැඳින්වෙන මේ ගස සුදු හඳුන් ගසට හෝ එළ කිහිරිය ගසට හෝ රත් කිහිරිය ගසට කිසිම විදියකින් සමානකමක් නැත. එය බොහෝ දුරට සමාන වන්නේ මදුරා ගසට යි. රත් හඳුන් ගසේ පිට පොත්ත ද මදුරා ගසේ පිට පොත්ත මෙන් ම සවි ය. සුදු පාහයෙන් යුක්ත ය. දෙ වර්ගයේ ම කඳ මහත් වන්නේ පොත්ත පිපිරී යාමෙනි. දෙවගියේ ම කොළ ද හැඩහුරුකමින් එකාකාර යි. එහෙත් රත් හඳුන් කොළය මදුරා කොළයට වඩා ඝණ යි. කර කොළ මෙන් මස සහිත යි. දෙ වර්ගයේ ම අරටු පද්මරාග වර්ණයෙන් යුක්ත යි. අරටුවල සුවඳ ද එක සමාන යි. දඹදිව ඇතැම් ශීතාධික ප්‍රදේශයන්හි වැවෙන මේ වගිය පෙර රජුන් විසින් ලංකාවේ නොයෙක් පළාත්වල වගා කරණ ලද බව පෙනේ. දිගාමඩුලු පෙදෙසට අයත් ගල්ඔය මිටියාවතෙහි නාමින් වනගත ව තිබෙන්නේ ඒ ගස් වලින් බෝවී යන ගස් විය හැක. රත් හඳුන් අඳුනාගැනීමට මේ වනය පරික්‍ෂා කිරීමෙන් නියම රත් හඳුන් සොයා ගත හැක.\n\nරත් හඳුන් - රත් කිහිරිය:\nරත් හඳුන් මදුරා පවුලට අයත් ගසකි. රත් කිහිරිය පතඟි පවුලට අයත් ගසකි. රත් හඳුන් වෙනුවට ප්‍රතිනිධි වශයෙන් ගන්ට ඉන්දියානු රැසිවරු නියම කර තිබෙන්නේ අළුත් සැවැන්දරා මුල් ය. එහෙත් ලංකා රැසිවරු ඒ වෙනුවට රැගෙන තිබෙන්නේ ත් මේ දක්වා ගන්නේ ත් රත් කිහිරිය ය. සුවඳෙහොට (සැවැන්දරා) මුල් නොවේ. රත් හඳුන්-කිහිරිය දෙවර්ගයෙහි සුළු සමානත්වයක් ඇත්තේ අරටුවල වර්ණයෙහි පමණකි. ශීත ගුණයෙන් යුත් බලකාරක දුර්ලභ ඖෂධයක් වූ රත් හඳුන් වෙනුවට සැවැන්දරා මුල් වලට වඩා පෙනුමෙන් වත් සමානත්වයක් ඇති රත් කිහිරිය රැගෙන සැනසෙන්නේ රත් හඳුන් වල මිල අධිකකම හා දුර්ලභතවය නිසා විය හැක. නේපාලයේ රාජකීය උද්‍යානය ඇතුළු මේ ගස් වල ඇට පහසුවෙන් සපයා ගත හැකි ස්ථාන වලින් ඇට ලබා ගෙන අපේ රටේ ද විශාල ලෙස රත් හඳුන් වැවීමෙන් ජාතික ආදායමේ හා දේශීය වෙදකමේ දියුණුව ත් සිදුකල හැකි බැව් මගේ හැඟීම යි. මෙය ආණ්ඩුවෙන් ඉටු විය යුතු යුතුකමකි.", 
        "category": "plant",
        "image": "img_395_rath_handun.jpg"
    },
    { "word": "රන්මුක්තකා", "meaning": "කොබෝ ගස", "category": "plant" },
    { "word": "රතුසුග", "meaning": "රතුපාට නුග ගස්", "category": "plant" },
    { "word": "රතුහරන්", "meaning": "රත් හඳුන් හර", "category": "plant" },
    { "word": "රථ", "meaning": "වේගස්, වෙරලු, කෝන් ගස, කොබු", "category": "plant" },
    { "word": "රථාංගනා", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "රථාංගනී", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "රථද්‍රෘ", "meaning": "කෝන්ගස, කොබු ගස", "category": "plant" },
    { "word": "රථවර්ණා", "meaning": "මැණික්වැන්න", "category": "plant" },
    { "word": "රථාංගපුෂ්ප", "meaning": "හොමුවානු", "category": "plant" },
    { "word": "රථාග්‍රපුෂ්ප", "meaning": "වේවැල", "category": "plant" },
    { "word": "රද", "meaning": "දත්, ලූනුව, ලේ", "category": "anatomy" },
    { "word": "රදච්ඡද", "meaning": "තොල", "category": "anatomy" },
    { "word": "රදන", "meaning": "දත්", "category": "anatomy" },
    { "word": "රදලියා", "meaning": "ඉල්ල, (ඉවිල්ල=ඉහිල්ල) කොළ වැනි කොළ ඇති ගස් වගියක්", "category": "plant" },
    { "word": "රන්", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "රන් ඉඳිවැල්", "meaning": "රනින් කළ කුඩා කෙන්දි", "category": "mineral" },
    { "word": "රන්කේසර", "meaning": "දෙඹ ගස", "category": "plant" },
    { "word": "රන්කෙසෙල්", "meaning": "රන්වන් කදලි (වාක්‍ෂය)", "category": "plant" },
    { "word": "රන්ව", "meaning": "රත්කෑල", "category": "plant" },
    { "word": "රන්තොලිවි", "meaning": "පිලගස", "category": "plant" },
    { "word": "රන්සී", "meaning": "බටු ගස, මිදි", "category": "plant" },
    { "word": "රන්බු", "meaning": "සිදුර", "category": "general" },
    { 
        "word": "රන්කිරි ගොකටු", 
        "scientific": "Argemone Mexicana",
        "meaning": "Argemone Mexicana- මැක්සිකෝව ජන්මභූමිකොට ඇති මෙය හිම වැනි පාහයෙන් යුත් ඉතා ලක්‍ෂණ පැලෑටියකි. එහෙත් කඳෙහි ත්, කොළ වල ත්, නැටි වල ත්, ගෙඩි වල ත්, හැම තැනකම ත්, අඟල් බාගයක් පමණ දික් වූ තියුණු කටුවලින් වැසී තිබෙන නිසා කිට්ටුවෙන්ට බැරි ය. මෙය ද අපර දිගින් පෙර දිගට ඇවිත් අපේ ආයුර්වේදයට එකතුවී අවුරුදු පන්සියයකට වඩා පැරණි නැති බැව් භාවප්‍රකාශයෙන් එහා වෙද පොත් වල සඳහන් ව නො තිබීමෙන් පෙනේ.\n\nප්‍රමාණයෙන් සිහින් බෝටියා මල් පමණ වූ මේ පැලෑටියේ මල් වර්ණයෙන් හා හැඩහුරුකමින් නාමල් වැනි ය. ගෙඩි රට බිලින් ගෙඩි වලට සමාන ය. ඇට සරංගි තෝරඇට පමණ ඇත. එමෙන් ම කළු පාට ය. කිරි තද රන්වන් පාහයෙන් යුක්ත ය. අඩි එකහමාරක් පමණ උසට වැවෙන මේ පැලෑටිය වැවී එල දැරීමෙන් පසු කටුවැල්බටු පැලෑටිය මෙන් සම පූර්ණයෙන් ම වියලි යයි. මෙහි කිරි සහ සම්පූර්ණ පැලෑටිය ම ත් ඖෂධ සඳහා ගණිති. මෙය මුත්‍රා කෘච්ඡ්‍රා, අශ්මරි, ශොථ, දහජ්වර, කාසිම, කාමිරෝග හා සෙම්-පිත් ප්‍රධාන ව ඇති වන හැම රෝගයකට ම ගුණ දෙන ඖෂධයකි. (ඉදිරියෙහි රූක් ගොකටු ගණ ලියා ඇති විස්තරය බලන්න.)", 
        "category": "plant",
        "image": "img_396_rankiri_gokatu.jpg"
    },

    // --- පිටුව 397 ---
    { "word": "රන්බෙලි", "meaning": "සිප්පිබෙල්ලා", "category": "animal" },
    { "word": "රන්මොට", "meaning": "රත්මොට, (දදවලට ගාන බෙහෙතක්)", "category": "plant" },
    { "word": "රන්වන්කිහිරිය", "meaning": "මෙපලෝම, (රතු පාට කිහිරිය)", "category": "plant" },
    { "word": "රන්වන් සඳුන්", "meaning": "හරිචන්දන", "category": "plant" },
    { "word": "රන්වන්වේලා", "meaning": "රම්මානිස්ස", "category": "plant" },
    { 
        "word": "රන්මානිස්ස", 
        "scientific": "Cleome Viscosa",
        "meaning": "Cleome Viscosa- රන්වන් පාට මල් පොකුරු හා එල්බ ගිය කරල් ඇති අඩි දෙකක් පමණ උසට වැවෙන මෙය ප්‍රධාන පඬියන්ගේ වාතහර ඖෂධයකි. ප්‍රාණජීවය වැනි දේශීය වෙදකමේ තෙල් වගී සහ වෙනත් වාතහර ඖෂධ වගී පිළියෙල කිරීමේදී මේ පැලෑටිය ද අවශ්‍ය වේ. ඇතැම් පළාත්වල රන්වන් වේලා නමින් හැඳින්වෙන මෙය ඖෂධ සඳහා සහමුලයෙන් ම ගන්නා පැලෑටියකි.", 
        "category": "plant",
        "image": "img_397_ranmanissa.jpg"
    },
    { "word": "රත්ප", "meaning": "සවිඳවලුණු, මනෝසිල", "category": "mineral" },
    { "word": "රත්සිරියෙල්", "meaning": "හිරියල් නම් ධාතු විශේෂය", "category": "mineral" },
    { "word": "රණබිජු", "meaning": "රණවරා ඇට", "category": "plant" },

    // --- පිටුව 398 ---
    { "word": "රනිල", "meaning": "නිසර පෙරලිය", "category": "plant" },
    { "word": "රඹ", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "රඹුක", "meaning": "එරඬු", "category": "plant" },
    { "word": "රඹුක්", "meaning": "රඹුක් වැල් (උක් වගියට අයත් ඊට වඩා කුඩා දිගට වැල් යන පඳුරු වගියක්)", "category": "plant" },
    { "word": "රඹගා", "meaning": "කෙහෙල්", "category": "plant" },
    { "word": "රම්මානිස්ස", "meaning": "රන් මානිස්ස, රන් වන් වේලා", "category": "plant" },
    { "word": "රම්‍ය", "meaning": "සපු ගස, දුම්මල්ල මුල්, නුග ගස", "category": "plant" },
    { "word": "රම්‍යපුෂ්ප", "meaning": "ඉඹුල් ගස", "category": "plant" },
    { "word": "රම්‍යා", "meaning": "ගොඩ පියුම්, (මිතඹර)", "category": "plant" },
    { "word": "රම්‍යභවනි", "meaning": "පෙරැම්කායම්", "category": "plant" },
    { "word": "රමණ", "meaning": "දුම්මල්ල මුල්, පොල් ගස", "category": "plant" },
    { "word": "රමණීප්‍රිය", "meaning": "සැවැන්න, (සැවැත් දරා)", "category": "plant" },
    { "word": "රමා", "meaning": "රම්මානිස්ස", "category": "plant" },
    { "word": "රමාප්‍රිය", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "රමාන්වය", "meaning": "රම්මානිස්ස", "category": "plant" },
    { "word": "රර රාජ්", "meaning": "රසඳුන්", "category": "plant" },
    { "word": "රව", "meaning": "තොටිල", "category": "plant" },
    { "word": "රවං", "meaning": "හිරස්ස", "category": "plant" },
    { "word": "රවකා", "meaning": "දිවි පහුරු (වක් නිය)", "category": "plant" },
    { "word": "රවකං", "meaning": "දිවි පහුරු", "category": "plant" },
    { "word": "රවි", "meaning": "තඹ, වරා ගස", "category": "plant" },
    { "word": "රවිගුහා", "meaning": "දුරාලහා, (ධන්වයවාස)", "category": "plant" },
    { "word": "රවිනාථ", "meaning": "නෙළුම් මිල, බදුවද", "category": "plant" },
    { "word": "රවිනාමක", "meaning": "තඹ", "category": "mineral" },
    { "word": "රවිපත්", "meaning": "වරා කොළ", "category": "plant" },
    { "word": "රවිප්‍රිය", "meaning": "රත් නෙළුම්, කණේරු, වේලා, කොසඹ", "category": "plant" },
    { "word": "රවිප්‍රිතා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "රවි මදී", "meaning": "තෝර", "category": "plant" },
    { "word": "රවිරත්න", "meaning": "මැණික, තඹ", "category": "mineral" },
    { "word": "රවිලෝහ", "meaning": "තඹ", "category": "mineral" },
    { "word": "රවු", "meaning": "රහු ගෙඩිය", "category": "plant" },
    { "word": "රහනා", "meaning": "දිව", "category": "anatomy" },
    { "word": "රහාණ", "meaning": "ගිතෙල්", "category": "liquid" },
    { "word": "රඟාල", "meaning": "අඹගස්, උක්ගස්", "category": "plant" },
    { "word": "රස්", "meaning": "රහු ගෙඩිය", "category": "plant" },
    { "word": "රසකා", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "රසනා වතුකා", "meaning": "රත්මල්, ගොරක", "category": "plant" },
    { "word": "රස", "meaning": "රස දිය, වච්චනාභි, අතිරසය, ගෙන්දගම්, තෙත් ගතිය, කන ලද ආහාරයාගේ මනාව පැස වීම, ඉරිවේරිය", "category": "compound" },
    { "word": "රසබලිද", "meaning": "පැණිබලිඳ", "category": "plant" },
    { "word": "රසකර්පුර", "meaning": "රිදී තුත්තන්", "category": "mineral" },
    { "word": "රසකිඳ", "meaning": "අමෘත=(දික් කිඳ, අළුකිඳ, බුකිඳ, ගැට කිඳ, සෙවෙල් කිඳ, තික්ත කිඳ, මිටි කිඳ, රස කිඳ යයි කිඳි වගී අටකි.)", "category": "plant" },
    { "word": "රසකිඳ අරළු", "meaning": "රසකිඳ වැලෙක් බිමට ඇදෙන මුල් (කෙඳි)", "category": "plant" },
    { "word": "රසකේසර", "meaning": "කපුරු", "category": "plant" },
    { "word": "රසකුම්භ", "meaning": "කිතුල් ගස", "category": "plant" },
    { "word": "රසගඟා", "meaning": "රස කහර", "category": "mineral" },
    { "word": "රසගබ්", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "රසගබ්බා", "meaning": "තුත්තම්", "category": "mineral" },
    { "word": "රසගහි", "meaning": "රසඳුන්, සාදිලිංගම්", "category": "mineral" },
    { "word": "රසගහිකා", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසගහී", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසඥා", "meaning": "පුස්කර", "category": "plant" },
    { "word": "රසප්", "meaning": "සාදිලිංගම්, ලක් සකුරු, ලේ", "category": "mineral" },
    { "word": "රසපාත", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසඳු", "meaning": "දිව", "category": "anatomy" },
    { "word": "රසතාවතුක", "meaning": "රත්මල්", "category": "plant" },
    { "word": "රසකලාලක්‍ෂමණ", "meaning": "ලේ ලක්‍ෂමණ", "category": "treatment" },
    { "word": "රසභෙද්‍ය", "meaning": "ලේ", "category": "anatomy" },
    { "word": "රසදාක", "meaning": "රසදිය", "category": "mineral" },

    // --- පිටුව 399 ---
    { "word": "රසදුන්", "meaning": "අක්‍ෂාන කාච, රස අඳුන් =(දාරුහරිද්‍රා පලමක් ගෙන වතුර පත 8 කට තලා දමා පත 1 ට සිඳුවා ගත් කෂායට එළ කිරි පතක් ලා ඝණ වන තෙක් සිඳුවා ගත් අඳුන ද රසදුන් නමි වේ)", "category": "treatment" },
    { "word": "රසද්‍රාවි", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "රසධාතු", "meaning": "රසදිය", "category": "mineral" },
    { "word": "රසනා", "meaning": "කාඩි, අරත්ත, දිව", "category": "anatomy" },
    { "word": "රසනාගහි", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසනායක", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "රසනාසක", "meaning": "හිඟුල්, (ඉඟුල්)", "category": "mineral" },
    { "word": "රසනෙත්‍රකා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "රසපාකල්", "meaning": "උක් සකුරු", "category": "food" },
    { "word": "රසඵල", "meaning": "පොල් ගස", "category": "plant" },
    { "word": "රසමාණික්‍ය", "meaning": "රසදිය", "category": "mineral" },
    { "word": "රසරාජ්", "meaning": "රසදිය", "category": "mineral" },
    { "word": "රසල", "meaning": "උක්ගස", "category": "plant" },
    { "word": "රසලය", "meaning": "උක් ගස", "category": "plant" },
    { "word": "රසලොහ", "meaning": "රසදිය", "category": "mineral" },
    { "word": "රසවර්ජිත", "meaning": "මෝරු", "category": "liquid" },
    { "word": "රසගොධන", "meaning": "පුස්කර", "category": "plant" },
    { "word": "රසසපාන", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "රස සය", "meaning": "මධුර, ඇඹුල්, ලුණු, කටුක, තික්ත, කසට යන රස වගී සය.", "category": "treatment" },
    { "word": "රස සය (වෘක්‍ෂයක)", "meaning": "මුලරස, බක රස, තවරස, පත්‍රරස, ඵලරස, පුෂ්ප රස යන රස සය.", "category": "treatment" },
    { "word": "රස හරණ්‍ය", "meaning": "මාංශය", "category": "anatomy" },
    { "word": "රසා", "meaning": "දියමිත්ත, රසඳුන්, මුද්‍රිකා එල", "category": "plant" },
    { "word": "රසාගු", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසාගුප්", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසාගුහා", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසාඤ්ජන", "meaning": "අග්මසාර, අංජන කැට, හා පිත්තල බොර වලින් සාදන අඳුන් වගියක්", "category": "mineral" },
    { "word": "රසාය්‍ය", "meaning": "ඇම්බරැල්ල", "category": "plant" },
    { "word": "රසාදනී", "meaning": "වං ඇපල", "category": "plant" },
    { "word": "රසායික", "meaning": "පුස්කර, කොට දිඹුලා", "category": "plant" },
    { "word": "රසාන", "meaning": "ගිතෙල්, ගෝමුත්‍රා", "category": "liquid" },
    { "word": "රසාම්ල", "meaning": "සියඹලා, ඇඹුල්වේ", "category": "plant" },
    { "word": "රසායන", "meaning": "රස බෙහෙත් වගී, විෂ ප්‍රභෙද, මෝරා, වලඟසාල්", "category": "treatment" },
    { "word": "රසායක ඵලා", "meaning": "අරළු", "category": "plant" },
    { "word": "රසායන ශ්‍රෙෂ්ඨ", "meaning": "රසදිය", "category": "mineral" },
    { "word": "රසායනි", "meaning": "රසකිඳ, කෝමාරිකා, කළු කාම්මේරිය, මඟකරඳ", "category": "plant" },
    { "word": "රසාල්", "meaning": "ඊතණ, කිරිබදු, මුද්දරප්පලම්, කොස්, පොණඬරු, දඹ, තිරිඟු, උක් දඬු, උණ ගස", "category": "plant" },
    { "word": "රසාලිකා", "meaning": "වී, උක් ප්‍රභේදයක්", "category": "plant" },
    { "word": "රසාල්", "meaning": "පුස්කර", "category": "plant" },
    { "word": "රසුන", "meaning": "ලූනු", "category": "plant" },
    { "word": "රසුවන්", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "රසේනු", "meaning": "සාදිලිංගම්, රසදිය", "category": "mineral" },
    { "word": "රසෝ", "meaning": "ගෙත්දගම්, රන්දිස", "category": "mineral" },
    { "word": "රසෝනමාලි", "meaning": "මුං", "category": "plant" },
    { "word": "රසෝත්ගව", "meaning": "මුං, සාදිලිංගම්", "category": "plant" },
    { "word": "රසෝත්හවා", "meaning": "රසඳුන්, පුස්වැන්න", "category": "plant" },
    { "word": "රසෝත්හුන", "meaning": "රසඳුන්", "category": "mineral" },
    { "word": "රසෝන (ක)", "meaning": "සුදු ලූනු", "category": "plant" },
    { "word": "රසොපල", "meaning": "මුතු", "category": "mineral" },
    { "word": "රසොබල", "meaning": "ගෙත්දගම්", "category": "mineral" },
    { "word": "රසස්", "meaning": "ලේ, දියමිත්ත, අරත්ත", "category": "anatomy" },
    { "word": "රහස් පියස", "meaning": "සත්‍රීන්ගේ යෝනි මාර්ගය (රහස්‍ය ප්‍රදේශය)", "category": "anatomy" },
    { "word": "රහස්‍ය", "meaning": "දියමිත්ත, අරත්ත", "category": "plant" },

    // --- පිටුව 400 ---
    { "word": "රා", "meaning": "සුරාව", "category": "liquid" },
    { "word": "රාක්‍ෂස", "meaning": "ගොකටු-හොර ඉටි", "category": "plant" },
    { "word": "රාක්‍ෂා", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "රාක්‍ෂි", "meaning": "කුඹුරු ඇට", "category": "plant" },
    { "word": "රාග", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "රාග කාරිණී", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "රාගවෘන්තී", "meaning": "කිහිං, ලතුදිය, (ලාකඩ=ලාක්‍ෂාරස)", "category": "plant" },
    { "word": "රාගඳලි", "meaning": "සැබෝ ගස", "category": "plant" },
    { "word": "රාගනිල", "meaning": "ගිරිකිල්ල", "category": "plant" },
    { "word": "රාගපුෂ්ප", "meaning": "බදුවද", "category": "plant" },
    { "word": "රාග පුෂ්පී", "meaning": "බදුවද මල්", "category": "plant" },
    { "word": "රාග ප්‍රසව", "meaning": "බදුවද, රතු සියඹලා, රතු වදකහ, රතු ඕලු", "category": "plant" },
    { "word": "රාගමලත්", "meaning": "පිච්ච මල", "category": "plant" },
    { "word": "රාගාංඛිනී", "meaning": "වැල් මදට", "category": "plant" },
    { "word": "රාගිණී", "meaning": "බුලත්", "category": "plant" },
    { "word": "රාගී", "meaning": "කුරක්කන්", "category": "plant" },
    { "word": "රාගොයි", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "රාසාට", "meaning": "එළ සැබෝ", "category": "plant" },
    { "word": "රාජ්", "meaning": "ඇසල ගස", "category": "plant" },
    { "word": "රාජක්‍ෂවක", "meaning": "අක්මැල්ල, අබ", "category": "plant" },
    { "word": "රාජක", "meaning": "කරඹ ගස්, කලාදුරු", "category": "plant" },
    { "word": "රාජකදම්බක", "meaning": "බක්මී", "category": "plant" },
    { "word": "රාජකලින්දි", "meaning": "කොමඩු", "category": "plant" },
    { "word": "රාජකෙශර", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "රාජකුල මුදලියා", "meaning": "කැකුණ ගස", "category": "plant" },
    { "word": "රාජ කුෂ්මාණ්ඩ", "meaning": "එළබඩු, කලාදුරු", "category": "plant" },
    { "word": "රාජ කෙතකි", "meaning": "(දුටුකේ ගස)", "category": "plant" },
    { "word": "රාජ කොශාතකි", "meaning": "වැටකොළු, නියන් වැටකොළු", "category": "plant" },
    { "word": "රාජ ඛර්ජූරී", "meaning": "යොන් ඉඳි", "category": "plant" },
    { "word": "රාජ ජම්බු", "meaning": "මාදම්", "category": "plant" },
    { "word": "රාජතරු", "meaning": "කිහිං, ඇසළ", "category": "plant" },
    { "word": "රාජතාල", "meaning": "පුවක් ගස", "category": "plant" },
    { "word": "රාජ තික්තක", "meaning": "බිම් කොසඹ", "category": "plant" },
    { "word": "රාජදන්ත ඵල", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "රාජද්‍රැම", "meaning": "ඇසළ ගස", "category": "plant" },
    { "word": "රාජ ධත්තූර", "meaning": "තුන්බෝ අත්තන", "category": "plant" },
    { "word": "රාජධුස්තූරක", "meaning": "මහ අත්තන", "category": "plant" },
    { "word": "රාජ ධූතී", "meaning": "තුන්බෝ අත්තන", "category": "plant" },
    { "word": "රාජතියංස", "meaning": "හල් දුම්මල", "category": "mineral" },
    { "word": "රාජනී", "meaning": "බෙරු ගස, නිලී (නීලිකා)", "category": "plant" },
    { "word": "රාජ පටෝල", "meaning": "මිහිරි දුම්මැල්ල", "category": "plant" },
    { "word": "රාජ පලාණ්ඩ", "meaning": "රතු ලූනු", "category": "plant" },
    { "word": "රාජපන", "meaning": "වණ රාජ, ගුරුළු රාජ, සඳ රාජ, ඉර රාජ, ගරුඬ රාජ", "category": "plant" },
    { "word": "රාජපිල්ල", "meaning": "මහ බෙබර", "category": "plant" },
    { "word": "රාජපුත්‍ර", "meaning": "නික්ත ලබු", "category": "plant" },
    { "word": "රාජ පුත්‍රී", "meaning": "රණහිරියා, දසමන්, නික්ත ලබු", "category": "plant" },
    { "word": "රාජපුෂ්ප", "meaning": "කොකුම්, නා ගස, ලුනු වරණ", "category": "plant" },
    { "word": "රාජ පුගා", "meaning": "නික්ත ලබු", "category": "plant" },
    { "word": "රාජඵණීජ්ජක", "meaning": "නාරම් ගස", "category": "plant" },
    { "word": "රාජඵල", "meaning": "දුම්මැල්ල, ජම්බු", "category": "plant" },
    { "word": "රාජ ඵලාණ්ඩ", "meaning": "රතුලූනු", "category": "plant" },
    { "word": "රාජ බදර", "meaning": "රතු නෙල්ලි, මහබෙබර", "category": "plant" },
    { "word": "රාජ බලා", "meaning": "වල් බැවිල, ආපසු මුදු, ඇසලු, මහ බැවිල", "category": "plant" },
    { "word": "රාජ භද්‍රක", "meaning": "කොසඹ, එරබදු", "category": "plant" },
    { "word": "රාජභෝග", "meaning": "සඳුන්", "category": "plant" },
    { "word": "රාජ භෝග්‍ය", "meaning": "සාදික්කා, කිරිපළු", "category": "plant" },
    { "word": "රාජ මාරල", "meaning": "අගිල්", "category": "plant" },
    { "word": "රාජ මාංෂ", "meaning": "ලී මෑ, මෑ කරල්", "category": "plant" },
    { "word": "රාජ මාෂ", "meaning": "ලීඳු, මැකරල්", "category": "plant" },
    { "word": "රාජ යක්‍ෂම", "meaning": "ක්‍ෂය රෝගය", "category": "treatment" },
    { "word": "රාජ යෝග්‍ය", "meaning": "සුදු හඳුන්", "category": "plant" },
    { "word": "රාජ රඛග", "meaning": "රිදී", "category": "mineral" },
    { "word": "රාජ රැකෙබා", "meaning": "ඇපල", "category": "plant" },
    { "word": "රාජ රුවන්", "meaning": "අගිල්", "category": "plant" },

    // --- පිටුව 401 ---
    { "word": "රාජ වල්ලභ", "meaning": "මහ බෙබර ගස", "category": "plant" },
    { "word": "රාජ වෘක්‍ෂ", "meaning": "ඇසල, ලී මෑ, තෝර", "category": "plant" },
    { "word": "රාජ ශාක", "meaning": "සුළු කූර", "category": "plant" },
    { "word": "රාජසර්ෂප", "meaning": "මහ අරත්ත, තුන්බෝ අත්තන", "category": "plant" },
    { "word": "රාජ සමීප", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "රාජ හර්ණා", "meaning": "තුවරලා", "category": "plant" },
    { "word": "රාජහර්ණී විනාසනී", "meaning": "ගොඩමානේරිය", "category": "plant" },
    { "word": "රාජා", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "රාජාදන", "meaning": "පියල් ගස, කිරිපළු, කෑල", "category": "plant" },
    { "word": "රාජාදන ඵල", "meaning": "කිරිපළු ගස", "category": "plant" },
    { "word": "රාජාමිල", "meaning": "ඇඹුල් වේ", "category": "plant" },
    { "word": "රාජායතන", "meaning": "පියල් ගස, කිරිපළු, කෑල, ගිරිනිල්ල", "category": "plant" },
    { "word": "රාජාකී", "meaning": "එළ වරා", "category": "plant" },
    { "word": "රාජානී", "meaning": "අගරු, අගිල්", "category": "plant" },
    { "word": "රාජාර්හව", "meaning": "අගිල්, සඳුන්, කළු අගිල්, සුදු රියම්, ජම්බු", "category": "plant" },
    { "word": "රාජාෂ්ට සෙය්‍යාක", "meaning": "නිල් කටු කරඬු", "category": "plant" },
    { "word": "රාජි", "meaning": "අබ", "category": "plant" },
    { "word": "රාජීක", "meaning": "අබ", "category": "plant" },
    { "word": "රාජීකා", "meaning": "අබ", "category": "plant" },
    { "word": "රාජීව", "meaning": "එළ හෙළ අබ", "category": "plant" },
    { "word": "රාජීව", "meaning": "නෙළුම්, නිල් මහනෙල්", "category": "plant" },
    { "word": "රාධී", "meaning": "මහ අබ, වන රේබා", "category": "plant" },
    { "word": "රාසි", "meaning": "එළ දුම්මැල්ල", "category": "plant" },
    { "word": "රාත්‍රිකර", "meaning": "කපුරු", "category": "mineral" },
    { "word": "රාත්‍රිපුෂ්ප", "meaning": "මහනෙල්", "category": "plant" },
    { "word": "රාත්‍රිශ්වර", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "රාත්‍රී", "meaning": "කහ", "category": "plant" },
    { "word": "රාත්‍රීහාෂ", "meaning": "සුදු මහනෙල්", "category": "plant" },
    { "word": "රාදාර", "meaning": "ගිතෙල්", "category": "liquid" },
    { "word": "රාබු", "meaning": "මූල පලා", "category": "plant" },
    { "word": "රාමන", "meaning": "තොටිල, නිඹිරි", "category": "plant" },
    { "word": "රාම", "meaning": "කොට්ටම්, කුරතම්පලා, කොල්ලම් කොළ, පෙරුන්කායම්, හින් කොසඹ, හෙළපෝටා", "category": "plant" },
    { "word": "රාමකර්පූරක", "meaning": "මුතු", "category": "mineral" },
    { "word": "රාමර්දනක", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "රාමඨ", "meaning": "පෙරුම්කායම්, මසුර තුතු", "category": "mineral" },
    { "word": "රාමඨී", "meaning": "පෙරුම්කායම්, මසුර තුතු", "category": "mineral" },
    { "word": "රාමතෙල්", "meaning": "බඩේ සිට මුඛයෙන් පිට වන ආහාර ගඳින් යුත් වාතය.", "category": "treatment" },
    { "word": "රාම දූතී", "meaning": "කලා ප්‍රභේද", "category": "plant" },
    { "word": "රාමන", "meaning": "තොටිල", "category": "plant" },
    { "word": "රාම රූප", "meaning": "වංඇපල", "category": "plant" },
    { "word": "රාම වල්ලභ", "meaning": "කර ගස, කුරුඳු පොතු", "category": "plant" },
    { "word": "රාම්සුත", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "රාම්සෙන (ක)", "meaning": "බිම් කොසඹ", "category": "plant" },
    { "word": "රාමා", "meaning": "පෙරුම්කායම්, සාදිලිංගම්, සුදු කටුවැල් බටු, හෝපළු, ගෝරෝචන, ගුරු බැවිල, රම්මානිස්ස", "category": "plant" },
    { "word": "රාමාර්ධනක", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "රාමාෂ්ටා", "meaning": "රම්මානිස්ස", "category": "plant" },
    { "word": "රාමේෂ්ට", "meaning": "කුරුඳු පොතු", "category": "plant" },
    { "word": "රාල", "meaning": "දුම්මල, සල් ගහේ ලාටු", "category": "plant" },
    { "word": "රාලකායයි", "meaning": "සල් ගස", "category": "plant" },
    { "word": "රාලුක", "meaning": "අල, රාබු අල", "category": "plant" },
    { "word": "රාශ්ව", "meaning": "එළබටු", "category": "plant" },
    { "word": "රාශ්වකා", "meaning": "නිබ්බටු", "category": "plant" },
    { "word": "රාෂ්ට්‍රි(කා)", "meaning": "කටුවැල් බටු", "category": "plant" },
    { "word": "රාෂ්ට්‍රී", "meaning": "දල්ව මුල්", "category": "plant" },
    { "word": "රාෂ්ට්‍රිකි", "meaning": "එළබටු", "category": "plant" },
    { "word": "රාෂණා", "meaning": "රැත්ත (රැත්ත ගුණ 402 පිටෙනි ලියා ඇති විස්තරය බලන්න) ගස් වල හට ගන්නා පිළිල වගියට පත්‍ර රාෂ්ණා යයි කියති.", "category": "plant" },

    // --- පිටුව 402 ---
    { "word": "රාෂණාඵලා", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "රාෂනවෘන්තී", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "රාසාල", "meaning": "උක් ගස", "category": "plant" },
    { "word": "රාහුවර්ධන", "meaning": "අමු ඉඟුරු", "category": "plant" },
    { "word": "රාහුවර්ෂප", "meaning": "ලූනු", "category": "plant" },
    { "word": "රාහුත්සාහ", "meaning": "ලූනු", "category": "plant" },
    { "word": "රාහු රත්න", "meaning": "ගෝමේද (මැණික් වගියක්)", "category": "mineral" },
    { 
        "word": "රැත්ත - රාෂ්ණා (පත්‍ර රාෂ්ණා)", 
        "scientific": "Vanda Roxburghii",
        "meaning": "Vanda Roxburghii- රැත්ත (රාෂ්ණා) වෙනුවට අනාදිමත් කාලයක සිට අපේ රටේ පාවිච්චි කරන්නේ නියඟ පඬුලට අයත් අරත්ත (Cophiarrhiza Mungos) නමැති ඖෂධයකි. එය හින් අරත්ත, මහ අරත්ත යයි දෙ වගයකි. ඒ දෙවගිය ම ඖෂධ සඳහා අවශ්‍ය වෙයි. ඒවායේ අල (මුල්) නිය අල හෝ වල් ඉඟුරු අල වැනි තද සුවඳකින් හා කට හාරවන (කාවදින) ගතියකින් යුක්ත ය. සුළු තික්ත රසයක් ද ඇත. \"මෙයට ව්‍යවහාර වන නාකුලී - නකුලෙෂ්ටා යන නම් මෙහි සර්ප විෂ නාශක බලයක් මිස රාෂ්ණා වල ඇති වාත - ජ්වර රෝගෝපශමන ශක්තියක් නැත\" යනු එක් මතයකි.\n\nපත්‍රරාෂ්ණා - එක් සිය දහය (110) ක් පමණ වූ උඩවැඩියා වගී අතුරෙන් පත්‍රරාෂ්ණා ද එකකි. මේ වගිය වවුල් පහුර හා දියසෙවෙල් එකතු වන ගස් දෙබල වල ත්, ගස් බිල වල ත් සරු සාරව වැවෙයි. ඉන්දියානු ද්‍රව්‍ය ගුණ නිඝණ්ඩුවල කියා තිබෙන පරිදි මඳ සුවඳකින් හා තික්ත රසයකින් යුත් මේ වගිය වාත - ජ්වර ආබාධයන්හි පසස්නා ලද නිසා ඉන්දියානු වෛද්‍යවරයන් රාෂ්ණා ඖෂධ වශයෙන් මේය ගන්නා බව ඇසීමු.\n\nඅපේ රටේ ඇතැම් අය \"රාෂ්ණා වෙනුවට මේ වගිය ගත යුතු ය\"යි කියන නමුත් ගත්තේ පැරණි පුරුදු අරත්ත ම ය. අරත්ත නුදුටු - නොදන්නා පාඨකයන් ඇතැයි සිතීම දුෂ්කර නිසා ඉන්දියාවෙන් ආ අළුත් මතයට භාජන වී තිබෙන පත්‍ර රාෂ්ණා පැලයක ඡායාරූපයක් පමණකි මෙහි දැක්වෙන්නේ.", 
        "category": "plant",
        "image": "img_402_rathna.jpg"
    },

    // --- පිටුව 403 ---
    { "word": "රැස්කන්සා", "meaning": "හාඬකන්සා", "category": "plant" },
    { "word": "රැගැන්සිය", "meaning": "වල්ගම්මිරිස්, (වල් මොලඟු)", "category": "plant" },
    { "word": "රෑ", "meaning": "අමුකහ, කහ", "category": "plant" },
    { "word": "රෑකු", "meaning": "රැක් ගස", "category": "plant" },
    { "word": "රෑට හැසිරීම", "meaning": "හිඟුරුපියලි අල", "category": "plant" },
    { "word": "රෑණ", "meaning": "කුඹුරුණ, (කටුකරෝෂණ)", "category": "plant" },
    { "word": "රික්", "meaning": "නාමගස්", "category": "plant" },
    { "word": "රිඟිකොල", "meaning": "වච්චනාවි (වස) කොළ", "category": "plant" },
    { "word": "රිඟිනි", "meaning": "නිබ්බොටු", "category": "plant" },
    { "word": "රිඟිනීතුල්‍යා", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "රිටු", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "රිටුක", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "රිටුකා", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "රිටුතු", "meaning": "කපුටන්, කොහොඹ ගස", "category": "animal" },
    { "word": "රිටු තෙල්", "meaning": "කොහොඹ තෙල්", "category": "liquid" },
    { "word": "රිටු පුඹු", "meaning": "කොහොඹ පොතු", "category": "plant" },
    { "word": "රිපු", "meaning": "ගෙද", "category": "plant" },
    { "word": "රිතුක", "meaning": "හුණමකුල්", "category": "plant" },
    { "word": "රිතුකා", "meaning": "තුක්පිවි, (ලුණමකුව)", "category": "plant" },
    { "word": "රිතුකා-හුණමකුල්", "meaning": "හුණකපුරු", "category": "plant" },
    { "word": "රිදිතුහු", "meaning": "රිදීතුත්තම්", "category": "mineral" },
    { "word": "රිපු", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "රිවි", "meaning": "වරා ගස, ඉරමුසු, රිටි නම් ගස් වගිය", "category": "plant" },
    { "word": "රිවිගුරමුසු", "meaning": "සස්සඳ", "category": "plant" },
    { "word": "රිගයගඟා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "රිහිරි", "meaning": "රුධිරය", "category": "anatomy" },
    { "word": "රිතී", "meaning": "යකඩමල, පිත්තල", "category": "mineral" },
    { "word": "රිතීකා", "meaning": "අඳුන්, පිත්තල, මල්", "category": "mineral" },
    { "word": "රිතීප්", "meaning": "මල් අඳුන්, (පුෂ්ප අඳුන්)", "category": "mineral" },
    { "word": "රිතීපුෂ්ප", "meaning": "පුෂ්ප අඳුන්", "category": "mineral" },
    { "word": "රිතීසමන", "meaning": "සුදුකුඹුක්", "category": "plant" },
    { "word": "රිරි", "meaning": "පිත්තල", "category": "mineral" },
    { "word": "රිරිඹුන්නාවල්", "meaning": "(රිරිඹුන්කාවල්) උඩහළුවැල්=(පබවැල්)", "category": "plant" },
    { "word": "රුක්", "meaning": "කොට්ටම්, නාමගස්, රැක් ගස", "category": "plant" },
    { "word": "රුක්‍ය", "meaning": "නාමල් රේණු අත්තන, රත්රන්", "category": "plant" },
    { "word": "රුක්අගුණ", "meaning": "රූකඟුණ, =(අංකොළ)", "category": "plant" },
    { "word": "රුක්අත්තන", "meaning": "සප්ත පර්ණී වෘක්‍ෂය", "category": "plant" },
    { "word": "රුක්බක", "meaning": "කෙළින්ද ගස", "category": "plant" },
    { "word": "රුක්ඛාදනී", "meaning": "පිපිල", "category": "plant" },
    { "word": "රුක් ගස", "meaning": "ඊරිය, මලබඩ, රුක් යන ගස් තුන් වර්ගය ම පෙනුමෙන් සමාන ය. ඒවා හඳුනාගත හැක්කේ මල් හා ඵල හටගැනීමෙන් පසුව ය. රැක් ගස් වල ලපටි අවධියේ කොළ පැහැයෙන් හා මෝරූ (පැසුණු) පසු කහ පාටින් යුත් ගැට සහිත බුබුළු වැනි අති සුගන්ධවත් මල් පොකුරු සෑදෙ යි. මෙහි ඵල හටගන්නේ ඒ මල් පොකුරු වලින් නොවේ. කුඩා අතු දිගට වෙන් වෙන් වශයෙන් ය. ඊරිය ගසේ ද රැක් ගසෙනි මෙන් ම කුඩා අතු දිගට ඵල හට ගනී. එහෙත් රුක් මල් වැනි ලක්‍ෂණ මල් හටගැනීමක් එහි නැත. මල බඩ ගසෙහි කොළ හා ගෙඩි ඊරිය, රුක් දෙවගයට වඩා මඳක් දිගටි හැඩයෙන් යුක්ත ය. මේ තුන් වගෙ ම ගෙඩි වල ලෙල්ලට ත්, ඇටයට ත් අතර රතු පාටින් යුත් (සාදික්කා ගෙඩිවල මෙන්) වසාවාසි තිබේ. ඊරිය, රැක් දෙවගය ම ඖෂධ වශයෙන් ගනිති. මලබඩ දේශීය වෙදකමෙහි ඖෂධ වශයෙන් යෙදුන තැනක් ගැන දකින්නට නැත. කල්ගිය වන වල සෑදෙන කෝෂ - ඊරිය කිරි රෙදි කෑල්ලක ගා එක වරක් පමණක් ඒ වණය පිට එලීමෙන් සම්පූර්ණයෙන් ඒ කෝෂය කැපී වණය ශුද්ධ වී රතුමස් පෑදේ. රුක් මල් දේශීය වෙදකමේ ප්‍රියඟු වෙනුවට යොදති.", "category": "plant" },

    // --- පිටුව 404 ---
    
    { 
        "word": "රුක්ගොකටු", 
        "scientific": "Argemone Mexicana",
        "meaning": "Argemone Mexicana- මේ ගස රන්කිරිගොකටු - රුක්ගොකටු - කටුගොකටු - මලගොකටු - මල්ගොකටු යන නම් වලින් හැඳින් වෙයි. රන් වන්පාට කිරි වගියක් පිට කරණ නිසා මේ ගසට සංස්කෘතයෙන් කණක ක්‍ෂීරී යයි කියති. පැරණි සිංහල දේශීය වෙදකමේ මේ ගස හඳුන් වන්නේ රත්කිරි ගොකටු - රුක් ගොකටු යන නම වලිනි ය.\n\nමේ ගසින් ලබාගන්නා දඬු රත්පාහාය ඇති කිරි රසායන ද්‍රව්‍යයක් වශයෙන් හා ශ්‍රේෂ්ඨ තම ඖෂධයක් වශයෙන් ද ප්‍රයෝජනවත් ය. මේ කිරිවල තිබෙන රසායනික පුදුම ගුණය නම්: අව්-වැසි-සුළං වලට එහි වර්ණය වෙනස් නොවි ඔරොත්තු දීමේ ශක්තිය යි.\n\nමේ තාක් නො නැසී පවත්නා කරබගල - සීගිරිය - දිඹුලාගල - හිඳගල ආදි ගල් ගුහාවල ඇඳ තිබෙන සිතියම් වල කහ වර්ණය දක්වා තිබෙන්නේ මේ කිරි වලිනි ය. එයින් කරබගල සිතියම් අවුරුදු 2100 කට වඩා පැරණි බැව් වංගකථා හා රූප ලක්‍ෂණ අනුව තීරණය කළ හැක.", 
        "category": "plant",
        "image": "img_404_ruk_gokatu.jpg"
    },
    { 
        "word": "රුක්ගොකටු - මල - මුත්‍ර විරේකය (රුක්ගොකටු කිරි මගින්)", 
        "meaning": "මේ කිරි කලඳකට සියඹලා බොර කලං තුනක් මිශ්‍රකර සීනි දමා අඹරා කෙසෙල් කොළයක ඔතා වණ්ඩුවේ තම්බා උණු දිය පතකට ඒ කලං හතරම දිය කර හත් වරක් පෙරා එක වරම පොවන්න. කවර තරමේ මල-මුත්‍ර බද්ධයක් වුව ද එකෙනෙහි මගහැරී යයි. මල - මුත්‍ර අස්සීය එක වර සුව කළ හැකි වෙන එකම වස්තියක් හෝ එකම බෙහෙතක් මේ තාක් සොයාගෙන නැති නිසා මහත් ක්‍රියාකාරී බලයක් ඇති මනුෂ්‍ය ශරීරයට හිතකර ඖෂධයක් වශයෙන් ද මේ (රුක්ගොකටු) කිරි වලට ලැබේ නුයේ උසස් තැනක් ය.", 
        "category": "treatment" 
    },

];

