// data_418_427.js - පිටු 418 සිට 427 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 143
const data_extra_418_427 = [
    // --- පිටුව 418 ---
    { "word": "ලොමශ", "meaning": "කොට දිඹුලා, ජටාමාංශ, වඳුරු මෑ, වදකහ, මහමේවන්, කොල්ලම් කොළ, බැබිල", "category": "plant" },
    { "word": "ලොමශකාණ්ඩා", "meaning": "ඉඹුල්", "category": "plant" },
    { "word": "ලොමශපර්ණිකා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "ලොමශපුෂ්පක", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ලොමශා", "meaning": "ජටාමාංශ, එළ වදකසා, වඳුරු මෑ", "category": "plant" },
    { "word": "ලොමශාණික", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "ලොමහාන්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "ලොමිකා", "meaning": "ඊතණ", "category": "plant" },
    { "word": "ලොමුදහ රස්", "meaning": "ස්ත්‍රීන්ගේ යෝනි මාර්ගය", "category": "anatomy" },
    { "word": "ලොලාන්තක", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ලොලිකා", "meaning": "ඇඹුලැඹිලිය", "category": "plant" },
    { "word": "ලොලී", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ලොහ", "meaning": "අගිල්, ලෝකඩ", "category": "mineral" },
    { "word": "ලොහක", "meaning": "අගිල්", "category": "plant" },
    { "word": "ලොහ කණක", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "ලොහකන්‍යා", "meaning": "යකඩ කාන්දම්", "category": "mineral" },
    { "word": "ලොහකමිඞ", "meaning": "කාන්දම්", "category": "mineral" },
    { "word": "ලොහකිච්ච", "meaning": "යබොර", "category": "mineral" },
    { "word": "ලොහජ", "meaning": "යකඩ මල", "category": "mineral" },
    { "word": "ලොහජ රජ", "meaning": "යබොර", "category": "mineral" },
    { "word": "ලොහද්‍රාවිත්", "meaning": "පුස්කර", "category": "plant" },
    { "word": "ලොහවර", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "ලොහ විශුද්ධිද", "meaning": "පුස්කර", "category": "plant" },
    { "word": "ලොහ ශ්ලේෂ්ම", "meaning": "පුස්කර", "category": "plant" },
    { "word": "ලොහිත", "meaning": "රත් හඳුන්, කටු වෙලඟ, ලේ, රත් මුරුංගා, රම්මානිස්ස", "category": "plant" },
    { "word": "ලොහිතංකො", "meaning": "පියුම්රාමිණි", "category": "plant" },
    { "word": "ලොහිත චන්දන", "meaning": "රන්වන් සඳුන්, කොකුම්", "category": "plant" },
    { "word": "ලොහිත පුෂ්පක", "meaning": "දෙබොම්", "category": "plant" },
    { "word": "ලොහිත බිජු", "meaning": "නුග හෝ මදට", "category": "plant" },
    { "word": "ලොහිත මෘත්තිකා", "meaning": "සිවංගුරු", "category": "mineral" },
    { "word": "ලොහිත යෂ්ටිකා", "meaning": "වැල් මදට", "category": "plant" },
    { "word": "ලොහිත වල්ලි", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "ලොහිතා", "meaning": "නිදිකුම්බා, රතු සාරණ", "category": "plant" },
    { "word": "ලොහිතාබාහක", "meaning": "රත්නිටුල්, කටු වෙලඟ", "category": "plant" },
    { "word": "ලොහිතායස්", "meaning": "තඹ", "category": "mineral" },
    { "word": "ලොහෝ", "meaning": "යකඩ", "category": "mineral" },
    { "word": "ලොහෝටි", "meaning": "රසදිය", "category": "mineral" },
    { "word": "ලොගොත්තම", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "ලේ", "meaning": "බලල් ලුණු", "category": "mineral" },
    { "word": "ලෝමිකා", "meaning": "හිතණ", "category": "plant" },
    { "word": "ලෝලු", "meaning": "ලෝලු ගස්", "category": "plant" },
    { "word": "ලෝලේ", "meaning": "බොරළු දමුණු", "category": "plant" },
    { "word": "ලෝහිත", "meaning": "ලේ", "category": "anatomy" },
    { 
        "word": "වංඇපල", 
        "meaning": "අගල් ආධාර,-(වැටහිර=ආඩතෝඩා=වෛද්‍යමාතා=සිංහමුඛී) සංස්කෘත නම් තිස් හතරකින් හැඳින්වෙන වංඇපල ත් නියතින් එළ නමින් හැඳින්වෙන පාවට්ටා ත් දෙවර්ගයකි. වං ඇපල හෘදය රෝග, හා බහුමුත්‍ර (දියවැඩියා) රෝගය ගැන ප්‍රත්‍යක්ෂ ඖෂධයකි. (300 පිටේ පාවට්ටා ගැණ ලියූ කත්හි මේ දෙවර්ගය ගැණ ම පැහැදිලි විස්තරයක් ඇත)", 
        "category": "plant" 
    },
    { "word": "වංජුලමාලි", "meaning": "හෝපළු", "category": "plant" },
    { "word": "වංජුලො", "meaning": "හෝපළු, හොමුවහනු", "category": "plant" },
    { "word": "වංමුතු", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වංශ", "meaning": "උණකපුරු, උක් ගස, සල් ගස, හුණමකුළු", "category": "plant" },
    { "word": "වංශ කර්පුර රෝචනා", "meaning": "උණකපුරු, හුණ මකුළු", "category": "plant" },
    { "word": "වංශකි", "meaning": "උණකපුරු, හුණ මකුළු", "category": "plant" },

    // --- පිටුව 419 ---
    { "word": "වංශ තණ්ඩුල", "meaning": "උණ ගසෙන් සෑදෙන හාල්", "category": "plant" },
    { "word": "වංශනේත්‍ර", "meaning": "උක් මුල", "category": "plant" },
    { "word": "වංශපත්‍ර", "meaning": "උණ කොළ, නල නම් තණකොළ", "category": "plant" },
    { "word": "වංශ පත්‍රකා", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "වංශපිත", "meaning": "රත් ගුගුල්", "category": "plant" },
    { "word": "වංශ පුෂ්පා", "meaning": "මඟුල් කුඹුරුවැන්න", "category": "plant" },
    { "word": "වංශපුරක", "meaning": "උක් මුල", "category": "plant" },
    { "word": "වංශ භවා", "meaning": "උණකපුරු", "category": "plant" },
    { "word": "වංශ රෝචනා", "meaning": "උණ කපුරු", "category": "plant" },
    { "word": "වංශ වණ්ණො", "meaning": "වෙරලු මිණි", "category": "plant" },
    { "word": "වංශ ශකීරා", "meaning": "උණකපුරු", "category": "plant" },
    { "word": "වංශාහු", "meaning": "උණ ගොබේ", "category": "plant" },
    { "word": "වංශික", "meaning": "අගිල්, සඳුන්", "category": "plant" },
    { "word": "වංශික (කා)", "meaning": "අගිල්", "category": "plant" },
    { "word": "වංශිබ්‍යා", "meaning": "උණ කපුරු, හුණ මකුළු", "category": "plant" },
    { "word": "වංශී", "meaning": "උණ කපුරු, හුණ මකුළු", "category": "plant" },
    { "word": "වක්තු", "meaning": "තුවරලා ගස", "category": "plant" },
    { "word": "වක්තුග්‍රහණ", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "වක්තු වාස", "meaning": "නාරම් ගස", "category": "plant" },
    { "word": "වක්තු සොධින්", "meaning": "නාරම් ගස", "category": "plant" },
    { "word": "වක්ත්‍රාහ්ව", "meaning": "තුවරලා", "category": "plant" },
    { "word": "වක්නිය", "meaning": "දිවි පහුරු, ව්‍යාඝ්‍රනඛ, පසුවරුතලා, නියඳ", "category": "plant" },
    { "word": "වක්‍ෂ", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වක්‍ෂමී", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "වක්‍ර", "meaning": "තුවරලා", "category": "plant" },
    { "word": "වක්‍ර කණ්ඨ", "meaning": "බෙබර ගස, මසන්, කිහිරි ගස", "category": "plant" },
    { "word": "වක්‍ර පුෂ්ප", "meaning": "කෑල ගස", "category": "plant" },
    { "word": "වක්‍රා", "meaning": "කකීටකශෘංගි", "category": "plant" },
    { "word": "වක්‍ර (2)", "meaning": "කතුරුමුරුංගා", "category": "plant" },
    { "word": "වක්‍ර කණ්ඨ (2)", "meaning": "බෙබර ගස", "category": "plant" },
    { "word": "වක්‍රාංග", "meaning": "සිරිවඩු", "category": "plant" },
    { "word": "වක්‍රාප", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "වක්‍රයි", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "වක්‍රාණසි", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "වකුල", "meaning": "මූණමල් ගස, කවේළු, කුළු රණ", "category": "plant" },
    { "word": "වග", "meaning": "ව්‍යාඝ්‍රයා, වනය", "category": "general" },
    { "word": "වගතුත්", "meaning": "නිකුළු, (ද්‍රව්‍ය) කරාබු, වසාවාසි, සාදික්කා යන තුන් ජාතිය", "category": "plant" },
    { "word": "වග තුන", "meaning": "කරාබු, වසාවාසි, සාදික්කා", "category": "plant" },
    { "word": "වගපුල්", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "වග වැල්", "meaning": "වක් නිය, (දිවිපහුරු)", "category": "plant" },
    { "word": "වර්ග", "meaning": "නිවගි", "category": "plant" },
    { "word": "වඟු", "meaning": "සිහින් ධාන්‍ය වගියක්", "category": "plant" },
    { "word": "වඞග", "meaning": "යකඩ, ඊයම්, මුරුංගා, සුදු ඊයම්", "category": "mineral" },
    { "word": "වඞගසෙන", "meaning": "මූණමල් ගස", "category": "plant" },
    { "word": "වඞගාරි", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "වච්චනාරේ", "meaning": "පොණ්ඩුරු හෙවත් වච්චනාභි", "category": "plant" },
    { "word": "වච්චනාති", "meaning": "ගුථය", "category": "plant" },
  

    // --- පිටුව 420 ---
    { 
        "word": "වච්චනාවි (රිංගි - කාල කූට)", 
        "scientific": "Aconitum Ferox",
        "meaning": "Aconitum Ferox- වච්චනාවි - වත්සනාභ (විෂ) Aconitum Ferox- හිමාලය කඳු වැටිය ඇතුළු උතුරු ඉන්දියාවෙහි වැවෙන මෙය ප්‍රධාන විෂ වගී අටෙන් එකකි. වච්චනාභි නමින් හැඳින්වෙන්නේ මේ පැලෑටි වගියේ වියලන ලද අල (මුල්) සමූහය ය. මේ අල දින තුනක් එල ගෝ මූත්‍ර වල දමා විෂ මැරීමෙන් පසු වේලා ගෙණ ඖෂධ සඳහා යොදා ගත හැක.\n\nදේශීය වෙද කමෙහි ස්ථාවර - ජංගම විෂ නාසක ඖෂධ වගී හා සින්දූරම් (රස බෙහෙත්) වගී පිළියෙල කිරීමේ දී වච්චනාභි ද බොහෝ වට්ටෝරු වල ඇතුලත් කර තිබේ.\n\nනහර ගත ආබාධ, සර්ප විෂ, කැස්ස හා තවත් බොහෝ ආබාධ වලට වච්චනාභි මිශ්‍ර ඖෂධ යෝග යොදති.", 
        "category": "plant",
        "image": "img_419_vachchanabi.jpg"
    },
    { "word": "වචවාචි", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "වචා", "meaning": "වදකසා", "category": "plant" },
    { 
        "word": "වචාදි ගණය", 
        "meaning": "වදකහ, කලාදුරු, අරළු, දේවදාර, වියලි ඉඟුරු, අතිවිඩයම් (ඉවද) යන මේ වචාදි ගණය, දොස් පැසවීම, ආම අතිසාර සින්දුවීම හා තන කිරි දොස් ශුද්ධ කිරීම ද කෙරේ.", 
        "category": "compound" 
    },
    { "word": "වච්‍ය", "meaning": "දඹින්තරු", "category": "plant" },
    { "word": "වජ්‍ර", "meaning": "වල් කිබාරම්", "category": "plant" },
    { "word": "වජ්‍ර පියඃ", "meaning": "මුංකිරිය වැල්", "category": "plant" },
    { "word": "වජ්", "meaning": "වජ්‍රදාරු", "category": "plant" },
    { "word": "වජ්‍රපිරිබුලු", "meaning": "හෙළ වදකහ", "category": "plant" },
    { "word": "වජ්‍රරල", "meaning": "කිබාරම්", "category": "plant" },
    { "word": "වජ්‍රි", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වජ්‍රීර", "meaning": "ජීවක, මිදුරු = (දියමිත්තී)", "category": "plant" },
    { "word": "වජ්‍රීරෝ", "meaning": "දියමිත්තී", "category": "plant" },
    { "word": "වජ්‍ර (2)", "meaning": "කිබාරම්, දළුක්, ඉරිවේරිය, නෙල්ලි, තල මල්, ත්‍රිවේර, ඉකි රිය, මිදුරු", "category": "plant" },
    { "word": "වජ්‍රකණ්ටක", "meaning": "දළුක් ගස", "category": "plant" },
    { "word": "වජ්‍රබක", "meaning": "කිබාරම් අල", "category": "plant" },
    { "word": "වජ්‍රතුණ්ඩ", "meaning": "දළුක් ගස", "category": "plant" },
    { "word": "වජ්‍රද්‍ර", "meaning": "සිනුක්", "category": "plant" },
    { "word": "වජ්‍රද්‍රැම", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "වජ්‍රපුට", "meaning": "බෙහෙත් පිසින (උයන) පුටා ප්‍රභේදයක්", "category": "treatment" },
    { "word": "වජ්‍රපුෂ්ප", "meaning": "තල මල්, වාගස", "category": "plant" },
    { "word": "වජ්‍රපුෂ්පා", "meaning": "සතපුෂ්ප", "category": "plant" },
    { "word": "වජ්‍රබාබඩී", "meaning": "දුම්කොළ", "category": "plant" },
    { "word": "වජ්‍රමණී", "meaning": "දියමන්ති (වජ්‍ර)", "category": "mineral" },
    { "word": "වජ්‍රමත්තාහ්ව", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වජ්‍රමාණික්‍ය", "meaning": "දියමන්ති මැණික", "category": "mineral" },
    { "word": "වජ්‍රමූලී", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "වජ්‍රවල්ලරී", "meaning": "හිරස්ස", "category": "plant" },
    { "word": "වජ්‍රවල්ලි", "meaning": "හිරස්ස", "category": "plant" },
    { "word": "වජ්‍රවෘක්‍ෂ", "meaning": "වැල් කරඳ", "category": "plant" },
    { "word": "වජ්‍රවෘක්‍ෂ (2)", "meaning": "උගුරැස්ස, පියා ගස, දළුක්", "category": "plant" },
    { "word": "වජ්‍රවෘක්‍ෂී", "meaning": "දළුක්", "category": "plant" },
    { "word": "වජ්‍රා", "meaning": "රසකිඳ, දළුක්, ඉකිරිය, මිදුරු", "category": "plant" },
    { "word": "වජ්‍රාඛ්‍යා", "meaning": "ගස්කැලිය, පතොක්", "category": "plant" },
    { "word": "වජ්‍රාංගී", "meaning": "හිරස්ස", "category": "plant" },
    { "word": "වජ්‍රාස්ති ශෘංගලා", "meaning": "ඉකිරිය", "category": "plant" },
    { "word": "වඤ්ජල", "meaning": "කෝන් ගස, හෝපළු, ගොඩමානෙල්, ඇඹුල්වේ", "category": "plant" },
    { "word": "වඤ්ජුලද්‍රැම", "meaning": "හෝපළු ගස", "category": "plant" },
    { "word": "වඤ්ජුලප්‍රිය", "meaning": "මේඝල", "category": "plant" },
    { "word": "වඤ්ජුලා", "meaning": "හෝපළු, හොමුවානු", "category": "plant" },
    { "word": "වට්ටක්කා", "meaning": "රට (දේස) පුහුල්", "category": "plant" },
    { "word": "වට්ටකිලිකිලිප්පෙයි", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "වට්ටතණී", "meaning": "අනෝදා, මහ බැබිල", "category": "plant" },
    { "word": "වට්ටතිප්පිරිප්පු", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වට්ටා", "meaning": "අනවප් ගස, මහ බැබිල", "category": "plant" },
    { "word": "වටටානත්‍රි", "meaning": "අනවප් (අනෝදා) ගස", "category": "plant" },

//  පිටු 421 සිට 423 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 106

    // --- පිටුව 421 ---
    { "word": "වටටාමරෙයි", "meaning": "වට රහාණ (වල් ගම්මිරිස්)", "category": "plant" },
    { "word": "වට්ටි වේරා", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වට්ට්‍යා", "meaning": "මඟුල්කුඹුරුවැන්න", "category": "plant" },
    { "word": "වට", "meaning": "නුග ගස, කබ", "category": "plant" },
    { "word": "වටංසක", "meaning": "වදමල", "category": "plant" },
    { "word": "වටක", "meaning": "කලං එකහමාර ගුලිය", "category": "treatment" },
    { "word": "වටන්", "meaning": "මූන", "category": "anatomy" },
    { "word": "වටන්දිය", "meaning": "මුහුප්ජලය", "category": "liquid" },
    { "word": "වටපත්‍ර", "meaning": "එලවරා, පොල්පලා, අඳුතලා", "category": "plant" },
    { "word": "වටරහාණ", "meaning": "වල්මොලඟු", "category": "plant" },
    { "word": "වටවත්වේලා", "meaning": "වේලා වගියක්", "category": "plant" },
    { "word": "වටවාස", "meaning": "නුග ගස", "category": "plant" },
    { "word": "වටසිංහ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "වටාස්ස", "meaning": "පන්මුසු පොළොවේ හට ගන්නා පෙනි සේ කොළ හා පිණි සමාන මුදුනේ මල් ඇති පැලෑටියක්", "category": "plant" },
    { "word": "වටු", "meaning": "කොටිල", "category": "plant" },
    { "word": "වටුක", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වටොර", "meaning": "කලවය", "category": "anatomy" },
    { "word": "වඩිරන්", "meaning": "වදකහ", "category": "plant" },
    { "word": "වඬු", "meaning": "බටුගස", "category": "plant" },
    { "word": "වණ්‍ය", "meaning": "සබරල, රත්ඔලු", "category": "plant" },
    { "word": "වණ", "meaning": "වස්තියා", "category": "treatment" },
    { "word": "වණ්ඩුල", "meaning": "මඟකුර", "category": "plant" },
    { "word": "වණ්ඩුලොපෙකො", "meaning": "මඟකුර", "category": "plant" },
    { "word": "වන්සක", "meaning": "කෙළින්ද ගස, මල් කසිස්", "category": "plant" },
    { "word": "වන්සකා", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "වන්සකවිජ", "meaning": "කෙළින්ද ඇට", "category": "plant" },
    { "word": "වන්සනා", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "වන්සනාභ", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "වන්සාක්‍ෂි", "meaning": "මහගොන්සුදු කැකිරි", "category": "plant" },
    { "word": "වන්සාදන", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "වන්සාදනී", "meaning": "කිරිපළු, රසකිඳ, සිත් දුමාව", "category": "plant" },
    { "word": "වනිහා", "meaning": "කැඳ", "category": "food" },
    { "word": "වනී", "meaning": "කය", "category": "anatomy" },
    { "word": "වනුරු", "meaning": "වස්ත්‍ර", "category": "general" },
    { "word": "වද", "meaning": "වදකහ, වදමල් ගස", "category": "plant" },
    { "word": "වදකර", "meaning": "වදකහ අල", "category": "plant" },
    { "word": "වදකහ", "meaning": "මීගලතා", "category": "plant" },
    { "word": "වදනොත්තමා", "meaning": "කකීටකශෘංගි", "category": "plant" },
    { "word": "වදසයන", "meaning": "ලබුනැටි", "category": "plant" },
    { "word": "වදරා", "meaning": "කපු, බින්තල්", "category": "plant" },
    { "word": "වදසන්", "meaning": "ස්ත්‍රීන්ගේ යෝනි මාර්ගය", "category": "anatomy" },
    { "word": "වදසෝ", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "වදගැනීගෙ කැවුතු", "meaning": "වදකහ අල", "category": "plant" },
    { "word": "වදු", "meaning": "වදකහ", "category": "plant" },
    { 
        "word": "වඳුරු මෑ", 
        "scientific": "Mucuna Pruriens",
        "meaning": "Mucuna Pruriens- වාජීකරණ ඖෂධයක්\n\nමෙය ලංකාවේ හා ඉන්දියාවේ වැවෙන බෙහෙත් වැලකි. මෙහි කොළ - වැල හා කරල් බොහෝ දුරට දඹල කොළ - වැල හා කරල් වලට ත් සමාන යි. පොකුරු වශයෙන් සෑදෙන මේ වගියේ කරල් ලපටි අවධියෙහි නිල් පාහයෙන් ත්, වියලන විට කළු පාහයෙනු ත් යුක්ත යි. පැසුන කරල් මතුපිට මිල්ලෑඩ වැනි පැහැයකින් දිලිසෙයි. ඇට කළු පාට යි. මේ ඇටවල සුදුපාටින් යුත් මදය මත් වන සුළු ගතියකින් යුත් වාජීකරණ ඖෂධයකි.\n\nබුද්ධදාස රජතුමා ලියූ සාරාර්ථ සංග්‍රහයෙහි තුන් දොස් වගියකින් යුත් සප්ත ධාතු වර්ධනයෙහි ලා ඉතාම ප්‍රත්‍යක්‍ෂ වාජීකරණ රසායනයක් තිබේ. වඳුරුමෑ ඇට ද එයින් එකකි.", 
        "category": "plant",
        "image": "img_421_vandurumae.jpg"
    },

    // --- පිටුව 422 ---
    { "word": "වඳුරා", "meaning": "මසුරිකා බිබිලි, දියමිත්තී, සිරස්ස වැල", "category": "plant" },
    { "word": "වඳුරුවැල්", "meaning": "සිරස්ස", "category": "plant" },
    { "word": "වඳුරුම්", "meaning": "වඳුරු ආමාසය", "category": "anatomy" },
    { "word": "වඳුරුවසුරු", "meaning": "වඳුරු බෙටි", "category": "animal" },
    { "word": "වබු", "meaning": "කබල", "category": "mineral" },
    { "word": "වන්ඇපල", "meaning": "ආඩතෝඩා=(වෛද්‍යමාතෘ)", "category": "plant" },
    { "word": "වන්දුලප්ප", "meaning": "වරා ගස", "category": "plant" },
    { "word": "වන්තසා", "meaning": "ඇත්තෝර ගස, පිළිල", "category": "plant" },
    { "word": "වන්තකා", "meaning": "ඇත්තෝර", "category": "plant" },
    { "word": "වන්තිකා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "වන්ටය", "meaning": "කැටි", "category": "general" },
    { "word": "වන්ටා", "meaning": "බැවිල", "category": "plant" },
    { "word": "වන්ද", "meaning": "මඟකරඬ", "category": "plant" },
    { "word": "වන්දවිග්‍ර", "meaning": "අමුකපුරු", "category": "plant" },
    { "word": "වන්දනීය", "meaning": "ගෝරෝචන, රන්වන් කිකිරිදිය", "category": "plant" },
    { "word": "වන්ද", "meaning": "පිළිල, මහපෝටාවැල", "category": "plant" },
    { "word": "වන්දකා", "meaning": "පිළිල", "category": "plant" },
    { "word": "වන්දම්", "meaning": "මීපැණි", "category": "liquid" },
    { "word": "වන්‍ද්‍යා", "meaning": "ගෝරෝචන", "category": "mineral" },
    { "word": "වන්‍ධ්‍යා", "meaning": "මැණික්වැන්න, බැමිතිරිය", "category": "plant" },
    { "word": "වන්‍ධ්‍යාකකෝට / වන්‍ධ්‍යාකර්කෝට", "meaning": "වල්තුඹ", "category": "plant" },
    { "word": "වන්‍ධුකපුෂ්ප", "meaning": "පියඟුගස", "category": "plant" },
    { "word": "වන්තක", "meaning": "විලේපන", "category": "treatment" },
    { "word": "වන්‍ය", "meaning": "වල්කිබාරම්, බින්තල්, සබරල, කලාදුරු, රත් මහනෙල්, වතුර", "category": "plant" },
    { "word": "වන", "meaning": "වතුර, ආරණ්‍යය", "category": "general" },
    { "word": "වනක", "meaning": "නිකගස", "category": "plant" },
    { "word": "වනකදලි", "meaning": "වල්කෙසෙල්", "category": "plant" },
    { "word": "වනකන්‍ද", "meaning": "වල්කිබාරම්", "category": "plant" },
    { "word": "වනකර්ණිකා", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "වනකර්පාසි", "meaning": "වල්කපු", "category": "plant" },
    { "word": "වනකර", "meaning": "බදුල්ල, රත්නිටුල්", "category": "plant" },
    { "word": "වනකාකෝලි", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "වනකෝමාරිකා", "meaning": "කන්‍යා", "category": "plant" },
    { "word": "වනචන්‍ද්‍රන", "meaning": "අගිල්, සඳුන්", "category": "plant" },
    { "word": "වනචන්‍ද්‍රිකා", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "වනජ", "meaning": "අමුක්කරා, වල්කිබාරම්, සිත්මිදි, වල්කපු", "category": "plant" },
    { "word": "වනජා", "meaning": "බුලු, මුංවැන්න", "category": "plant" },
    { "word": "වනජාක", "meaning": "තල", "category": "plant" },
    { "word": "වනතික්ත", "meaning": "අරළු, දියමිත්ත", "category": "plant" },
    { "word": "වනතික්තිකා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වනද්‍රන", "meaning": "සඳුන්", "category": "plant" },
    { "word": "වනද්‍රනී", "meaning": "දුරාලහා", "category": "plant" },
    { "word": "වනද්‍රයන", "meaning": "වහුවල්", "category": "plant" },
    { "word": "වනදීප", "meaning": "වල්සපු", "category": "plant" },
    { "word": "වනපල්ලව", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "වනපුෂ්පා", "meaning": "සතපුෂ්ප", "category": "plant" },

    // --- පිටුව 423 ---
    { "word": "වනසුරක", "meaning": "වල් දෙබොම්", "category": "plant" },
    { "word": "වනප්‍රසජ", "meaning": "කෑල", "category": "plant" },
    { "word": "වනප්‍රිය", "meaning": "කුරුඳු පොතු", "category": "plant" },
    { "word": "වනමල්ලි", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "වනමල්ලිකා", "meaning": "යොන්තුඹ, ගිරිකිල්ල", "category": "plant" },
    { "word": "වනමලී", "meaning": "වලිද්ද", "category": "plant" },
    { "word": "වනමාලිකා", "meaning": "යොන්තුඹ, ඌරල, මරිතොන්ඩි", "category": "plant" },
    { "word": "වනමාලි", "meaning": "වැටකේ, යොන්තුඹ, බෝලිද්ද", "category": "plant" },
    { "word": "වනමුද්ඝ", "meaning": "මුංවැන්න", "category": "plant" },
    { "word": "වනමුර්වජා", "meaning": "කකීටකශෘංගි", "category": "plant" },
    { "word": "වනමෙපිකා", "meaning": "වල්උළුවා", "category": "plant" },
    { "word": "වනමොචා", "meaning": "ඇටකෙසෙල්", "category": "plant" },
    { "word": "වනය", "meaning": "සංතකුප්පි (සඛපුෂ්පි)", "category": "plant" },
    { 
        "word": "වනරාජ", 
        "scientific": "Anoecto Chilus",
        "meaning": "Anoecto Chilus - රාජ පනහට අයත් එක් ඖෂධ වර්ගයක්\n\nමේ වර්ගයේ කොළ දිග-පළලින් අඟල් 4x1 1/2 ක් පමණ ඇත. කොළ වල උඩ පැත්ත ලා රත් පාහයෙන් යුත් විල්මුද රෙදි කඩක් මෙන් දිලිසෙයි. ඒ මතුයෙහි වැටී තිබෙන රන්වන් රේඛා වලින් කොළ ගොහාමත් ව තිබේ. පැලෑටියේ කඳ වදකහ පැලයක කඳ හෝ හාල්දණ්ඩකගේ කර මෙන් වයිරන් සහිත යි.\n\nලංකා වනරාජ කොළ හැඩහුරුකමින් ඉරරාජ කොළ වලට සමාන වන අතර ඉන්දියා වනරාජ එයට වඩා උල් දිගටි හැඩයෙන් යුක්ත වෙයි.\n\nවනරාජ දේශීය වෙදකමේ ඇතැම් ගුප්ත තෙල් - බෙහෙත් සඳහා නියම කර තිබේ.", 
        "category": "plant",
        "image": "img_423_vanaraja.jpg"
    },

// පිටු 424 සිට 426 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 163

    // --- පිටුව 424 ---
    { "word": "වනලක්‍ෂ්මී", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "වනවජ්‍ර", "meaning": "කළුතලා", "category": "plant" },
    { "word": "වනවාසින්", "meaning": "කෙළඹු, දේවදාලි, බින්තල්, සාමහක", "category": "plant" },
    { "word": "වනවිලාසිනී", "meaning": "අබනගිරිය", "category": "plant" },
    { "word": "වනවීජ", "meaning": "වල්දෙබොම්=වනවීජපුර", "category": "plant" },
    { "word": "වනවීජපුර", "meaning": "ලප්නාරන් වගියක්", "category": "plant" },
    { "word": "වනවෘන්තාකී", "meaning": "බටු, වල්බටු", "category": "plant" },
    { "word": "වනවුහි", "meaning": "බොබහමු", "category": "plant" },
    { "word": "වනවෙස්මක", "meaning": "කවනික", "category": "plant" },
    { "word": "වනශුකරී", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "වනශෘංගාට", "meaning": "ගොකටු, ඉකිරිය, වල්කොහිල", "category": "plant" },
    { "word": "වනශොධන", "meaning": "කරබෙබිය", "category": "plant" },
    { "word": "වනශොභන", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "වනස්නකී", "meaning": "මහනුග", "category": "plant" },
    { "word": "වනස්පති", "meaning": "නුග (ඇසතු වගී)", "category": "plant" },
    { "word": "වනසංකට", "meaning": "මසුර, වනකපු", "category": "plant" },
    { "word": "වනසරෝජිනී", "meaning": "වල්කපු", "category": "plant" },
    { "word": "වනසු", "meaning": "යකවනස්ස, මාරාගස, මදට ගස", "category": "plant" },
    { "word": "වනහරින්ද්‍රා", "meaning": "වල්කසා", "category": "plant" },
    { "word": "වනාහස", "meaning": "කුසතණ", "category": "plant" },
    { "word": "වනාකක", "meaning": "මුං", "category": "plant" },
    { "word": "වනාමල", "meaning": "කරඹ", "category": "plant" },
    { "word": "වනාමු", "meaning": "කොහු අඹ", "category": "plant" },
    { "word": "වනාර්හට", "meaning": "වල්කසා (හරන්කහඅල)", "category": "plant" },
    { "word": "වනාලිකා", "meaning": "ඇත්සැටිය (ඇස්සොබ)", "category": "plant" },
    { "word": "වනිකා", "meaning": "පුවඟු, මෝරු", "category": "plant" },
    { "word": "වනිතාප්‍රිය", "meaning": "පුස්කර, අබනගප්‍රිය", "category": "plant" },
    { "word": "වනෙක්‍ෂුද්‍රා", "meaning": "කරඳ", "category": "plant" },
    { "word": "වනෙසර්ජ", "meaning": "පියාගස", "category": "plant" },
    { "word": "වනෝද්භවා", "meaning": "වල්කපු", "category": "plant" },
    { "word": "වනුජ", "meaning": "සෙන්දිරික්කා ගස, (කුසුම්බ) වන්නිශිබ", "category": "plant" },
    { "word": "වනුරු", "meaning": "කිරිපළු ගස", "category": "plant" },
    { "word": "වනුරුප්‍රිය", "meaning": "කිරිපළු ගස", "category": "plant" },
    { "word": "වනුලුරක්", "meaning": "පියාගස", "category": "plant" },
    { 
        "word": "වනුවැල්", 
        "meaning": "වෙනිවැල්=(බාන්වැල්, කහවැල්) යන මේ නම් වලින් හැඳින්වෙන වැල් වර්ගය අපේ රටේ දාරුහරිද්‍රා වෙනුවට ගණිති. මෙය පීටගැස්මට හා ග්‍රන්ථි රෝගයට ප්‍රත්‍යක්ෂ ඖෂධයකි. (දාරුහරිද්‍රා ගැන ලියූ විස්තරය බලන්න.)", 
        "category": "plant" 
    },
    { "word": "වපු", "meaning": "ශරීරය, දඩකලත්", "category": "anatomy" },
    { "word": "වපුල", "meaning": "හෝපලු", "category": "plant" },
    { "word": "වප්‍ර", "meaning": "ඊයම්, වැල්මදට", "category": "mineral" },
    { "word": "වප්‍රතී", "meaning": "කැල්වැල", "category": "plant" },
    { "word": "වමමුතු", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වමථු", "meaning": "වමනය කිරීම", "category": "treatment" },
    { "word": "වමනතක", "meaning": "තොටිල", "category": "plant" },
    { "word": "වමන", "meaning": "දියපුබාවා, කුකුරුමාන්, කුරුදු, මහකපු", "category": "plant" },
    { "word": "වමනඵල", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "වමනිමුල", "meaning": "තුවරලා, බින්නුග", "category": "plant" },
    { "word": "වයඃපා", "meaning": "මුකුණුවැන්න, අරළු, රසකිඳ, නෙල්ලි, කිරිකවෙළු", "category": "plant" },
    { "word": "වයස්න", "meaning": "මුගුණුවැන්න", "category": "plant" },
    { "word": "වයස්පතා", "meaning": "නෙල්ලි, රසකිඳ", "category": "plant" },
    { "word": "වයස්‍යා", "meaning": "මඟුල්කරඳ", "category": "plant" },
    { "word": "වයසෙක්‍ෂු", "meaning": "වැලක්", "category": "plant" },
    { "word": "වර්ග", "meaning": "කරාබුනැටි, වසාවාසි, සාදික්කා", "category": "plant" },
    { "word": "වර්චර", "meaning": "ශකක, සාදිලිංගම්, වේලා, රත්හඳුන්, තලා", "category": "mineral" },
    { "word": "වර්චල", "meaning": "සූර්යකාන්ත ගස", "category": "plant" },
    { "word": "වර්චස්", "meaning": "ශුක්ල, මල", "category": "anatomy" },
    { "word": "වර්චස්ක", "meaning": "මල", "category": "anatomy" },
    { "word": "වර්ජක", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "වර්ණ", "meaning": "කොකුම්, වතුර, කහ, මහ හිඟුරුපියලි, හිරියල්", "category": "plant" },
    { "word": "වර්ණකා", "meaning": "හිරියල්, සඳුන්, ආදි ද්‍රව්‍ය, සාදිලිංගම්", "category": "mineral" },

    // --- පිටුව 425 ---
    { "word": "වර්ණතුල්‍ය", "meaning": "කොව්වැල", "category": "plant" },
    { "word": "වර්ණද", "meaning": "කළු අගිල්", "category": "plant" },
    { "word": "වර්ණදත්‍රී", "meaning": "කහ", "category": "plant" },
    { "word": "වර්ණපත්‍ර", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "වර්ණපිෂ්ඩීතක", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "වර්ණප්‍රසාදන", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "වර්ණලොහ", "meaning": "පිත්තල", "category": "mineral" },
    { "word": "වර්ණවතී", "meaning": "කහ", "category": "plant" },
    { "word": "වර්ණස්", "meaning": "මොරගස", "category": "plant" },
    { "word": "වර්ණස්‍ය", "meaning": "රන්වන් කටුකරඬු", "category": "plant" },
    { "word": "වර්ණා", "meaning": "කලා", "category": "plant" },
    { "word": "වර්ණාර්ග", "meaning": "මුං", "category": "plant" },
    { "word": "වර්ණානිනී", "meaning": "කහ", "category": "plant" },
    { "word": "වර්තුල", "meaning": "ගප්පිප්පිලි, වතුසුද්ද, ලූනු, මුරුංගා", "category": "plant" },
    { "word": "වර්ධක", "meaning": "මදටිය", "category": "plant" },
    { "word": "වර්ධමාන", "meaning": "එරඬු, එළ එරඬු", "category": "plant" },
    { "word": "වර්ධමානක", "meaning": "එරඬු", "category": "plant" },
    { "word": "වර්ධමකණ්ටක", "meaning": "තලා", "category": "plant" },
    { "word": "වර්ධමකපා", "meaning": "දසමන්", "category": "plant" },
    { "word": "වර්වර", "meaning": "රන්වන් සඳුන්, ගෙන්දගම්, රම්මානිස්ස, කළුතලා, අඳුතලා, සාදිලිංගම්", "category": "plant" },
    { "word": "වර්වරා", "meaning": "වේලාගස", "category": "plant" },
    { "word": "වර්ෂක", "meaning": "බැමිතිරිය (ලුණුවිල)", "category": "plant" },
    { "word": "වර්ෂකේතු", "meaning": "මහසාරණ, රතුසාරණ", "category": "plant" },
    { "word": "වර්ෂපාකින්", "meaning": "ඇම්බරැල්ල", "category": "plant" },
    { "word": "වර්ෂපුෂ්ප", "meaning": "කුඹුරුවැල්, මහ බැබිල", "category": "plant" },
    { "word": "වර්ෂපුෂ්පා", "meaning": "මඟුල්කුඹුරුවැන්න, මහබැබිල", "category": "plant" },
    { "word": "වර්ෂපුෂ්පී", "meaning": "අස්බැබිල, වල්කුඹුරු වැන්න", "category": "plant" },
    { "word": "වර්ෂා", "meaning": "කළුදුරු", "category": "plant" },
    { "word": "වර්ෂාභූ", "meaning": "සාරණ", "category": "plant" },
    { "word": "වර්ෂායාතු", "meaning": "නිකිනි, බිනර දෙමස", "category": "general" },
    { "word": "වර්ෂාහු", "meaning": "සුළුසාරණ, මහසාරණ", "category": "plant" },
    { "word": "වර්ෂායුස්‍යා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වර්ෂාල", "meaning": "කඩල", "category": "plant" },
    { "word": "වර්ෂෝපල", "meaning": "දෙබොම්", "category": "plant" },
    { "word": "වර්හ", "meaning": "විෂ්ණුක්‍රාන්ති, මොණරපිල්, මලිත ගස, රත්නිටුල්", "category": "plant" },
    { "word": "වර්හකුසුම", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "වර්හින", "meaning": "තුවරලා", "category": "plant" },
    { "word": "වර්හිපුෂ්ප", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "වර්හිගුෂ්මන්", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වර්හිෂ්ට", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වර්හිස්", "meaning": "රත්නිටුල්, විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "වර", "meaning": "කොකුම්, ගුගුල්, ලාකඩ, කටුකරඬු, කෙළින්ද, කුරුඳු, නිපල්, අමුඉඟුරු", "category": "plant" },
    { "word": "වරක", "meaning": "වරක නම් වූ මෙතේරි පඳුරු වැනි ගොයම් වගියක්, (වරා) වල්මුං, පැපිලිය, දෙබොම්, කසිස්", "category": "plant" },
    { "word": "වරකණ්ඨා", "meaning": "සින් මැඩහඟු", "category": "plant" },
    { "word": "වරකණ්ඨක", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "වරකා", "meaning": "ඉදුනවිට බෙරි නොවන ගෙඩි සෑදෙන කොස් වගිය", "category": "plant" },
    { "word": "වරකු", "meaning": "අමු", "category": "plant" },
    { "word": "වරගාත්‍රී", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වරචන්ද්‍රන", "meaning": "දේවදාර, වනුක්ඇට, කළුඅගිල්", "category": "plant" },
    { "word": "වරටිටාමරේ", "meaning": "වල්මොලඟු", "category": "plant" },
    { "word": "වරණ", "meaning": "මුඛ රෝග ප්‍රභේදයක්", "category": "treatment" },
    { "word": "වරණඩාලු", "meaning": "එරබු ගස", "category": "plant" },
    { "word": "වරණ", "meaning": "ලුණුවරණ", "category": "plant" },
    { 
        "word": "වරණාදිගණය", 
        "meaning": "ලුණුවරණ, කටුවෙලඟ, සාතාවාරිය, බෙලි,සින්-මහ මැඩහඟු දේවදාරගස, වැල් මුරුංගා, ඉමක්, සිරිල, පිත-රක්ත කටුකරඬු දෙවගිය, එළ බටු, කටුවැල්බටු, බොරළුදමුණු, (උගුරුස්ස) නිතින් (කෙමි=කෝ වක්කා), සිහින්මිදි, සිවිය, රත් නිටුල්, කරඳ යන මේ වරණාදි ගණය අන්ත්‍ර විද්‍රධි හා සෙම් මේදස්, ගුල්ම රෝග පහ කරන්නේ ය.", 
        "category": "compound" 
    },

    // --- පිටුව 426 ---
    { "word": "වරතච", "meaning": "කොසඹ", "category": "plant" },
    { "word": "වරතික්තා", "meaning": "පැපිලිය, දුම්මැල්ල, කෙළින්ද", "category": "plant" },
    { "word": "වරතික්තක", "meaning": "අලරිය", "category": "plant" },
    { "word": "වරද", "meaning": "කෝමාරිකා, අමුක්කරා, කෝවක්කා, ඊතණ", "category": "plant" },
    { "word": "වරදා", "meaning": "අමුක්කරා, කෝවක්කා, නික", "category": "plant" },
    { "word": "වරද්‍රැම", "meaning": "අගිල්", "category": "plant" },
    { "word": "වරපිතක", "meaning": "මීහිරන්", "category": "plant" },
    { "word": "වරප්‍රිය", "meaning": "කුරුඳු", "category": "plant" },
    { "word": "වරප්‍රියබග", "meaning": "ත්‍රිබේර", "category": "plant" },
    { "word": "වරඵල", "meaning": "එලජම්බු, පොල්ගස, දෙහිගස", "category": "plant" },
    { "word": "වරම්බරා", "meaning": "වනුපර්ණී (සක්වැන්න)", "category": "plant" },
    { "word": "වරමුඛී", "meaning": "රේණුක නම් සුවඳ", "category": "plant" },
    { "word": "වරලබ්ධ", "meaning": "සපුගස", "category": "plant" },
    { "word": "වරලිපතු", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "වරවාහ්ලිකා", "meaning": "කොකුම්", "category": "plant" },
    { "word": "වරා", "meaning": "අරළු, බුළු, නෙල්ලි, රේණුක නම් සුවඳ ද්‍රව්‍යය, රසකිඳ, මේවන්, වළඟසාල්, දියමිත්ත, කහ, බෝදි ඇට, සුදු පාසානම්, යක්බේරිය", "category": "plant" },
    { "word": "වරාගස", "meaning": "කුරුඳු", "category": "plant" },
    { "word": "වරාංග", "meaning": "කහ, වෙනිවැල්", "category": "plant" },
    { "word": "වරාංගක", "meaning": "කුරුඳු", "category": "plant" },
    { "word": "වරාංගින්", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "වරාජ", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "වරාට", "meaning": "කවඩි", "category": "animal" },
    { "word": "වරාටක", "meaning": "නෙළුම් බඩිටා, (නෙළුම්කෙමිය)", "category": "plant" },
    { "word": "වරාටකරජස්", "meaning": "නාමල්රේණු", "category": "plant" },
    { "word": "වරාටිකා", "meaning": "කවඩි", "category": "animal" },
    { "word": "වරාදන", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "වරාබායක", "meaning": "කුරුඳු", "category": "plant" },
    { "word": "වරාපක්ක්‍ෂව", "meaning": "වරා කොළ", "category": "plant" },
    { "word": "වරාභිෂක්", "meaning": "අනුගස", "category": "plant" },
    { "word": "වරාමු", "meaning": "කරඹ", "category": "plant" },
    { "word": "වරාරබ්ධක", "meaning": "විදුරු", "category": "plant" },
    { "word": "වරාරොහ", "meaning": "රත් නෙළුම්", "category": "plant" },
    { "word": "වරාල", "meaning": "කරාබුනැටි", "category": "plant" },
    { "word": "වරාලක", "meaning": "කුරුඳුපොතු, කරාබු", "category": "plant" },
    { "word": "වරාලඹ", "meaning": "නික්තලබු", "category": "plant" },
    { "word": "වරාලි", "meaning": "වැරුල්ල, ලේවෑරැල්ල", "category": "plant" },
    { "word": "වරා වගී හතර", "meaning": "රතුවරා, එළවරා, අළු වරා, පැණිවරා", "category": "plant" },
    { "word": "වරාසන", "meaning": "වදමල (බදුවද)", "category": "plant" },
    { 
        "word": "වරාසාල්", 
        "meaning": "වරක නැමති මහදුරු ඇට පමණ වී ඇට සෑදෙන මෙතේරි පඳුරු වැනි වී වගියක් ඇත. මේ වගීයේ සහල් දුර්භික්‍ෂ කාල වල රජවරුන්ට පවා අනුභෝජන වන බැව් පැරණි සිංහල සාහිත්‍ය පොත්වල කියා තිබේ.", 
        "category": "plant" 
    },
    { "word": "වරාහ", "meaning": "බින්තල්, කලාදුරු, අමුක්කරා", "category": "plant" },
    { "word": "වරාහකර්ණී", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වරාහකාන්තා", "meaning": "බින්තල්", "category": "plant" },
    { "word": "වරාහක්‍රාන්තා", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "වරාහිකා", "meaning": "වඳුරුමෑ", "category": "plant" },
    { "word": "වරාහිගන්‍ධා", "meaning": "බින්තල්", "category": "plant" },
    { "word": "වරාහී", "meaning": "කලාදුරු, ඇත්දෙමට", "category": "plant" },
    { "word": "වරාහිප්‍රිය", "meaning": "සූරල, ඇත්දෙමට", "category": "plant" },
    { "word": "වරි", "meaning": "වදකහ, සාතාවාරිය, කෝවක්කා", "category": "plant" },
    { "word": "වරිකා", "meaning": "රණවරා ගස", "category": "plant" },
    { "word": "වරිත", "meaning": "රණවරා", "category": "plant" },
    { "word": "වරිෂ්ට", "meaning": "මිරිස්, තඹ, ඉරිවේරිය, කෝවක්කා", "category": "plant" },

//පිටුව 427 හි සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 45
    // --- පිටුව 427 ---
    { "word": "වරිෂ්ටා", "meaning": "කටුරෝහිණී", "category": "plant" },
    { "word": "වරි", "meaning": "සාතාවාරිය, කෝවක්කා, තල, වැලුක්", "category": "plant" },
    { "word": "වරියස්", "meaning": "සුරා", "category": "liquid" },
    { "word": "වරුක්කු", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "වරුණ", "meaning": "ලුණුවරණ, සුරා", "category": "plant" },
    { "word": "වරුණා", "meaning": "වදකහ", "category": "plant" },
    { "word": "වරුණු", "meaning": "කිරිපලු", "category": "plant" },
    { "word": "වරොට", "meaning": "කුකුරුමාන් මල", "category": "plant" },
    { "word": "වරොත්පල", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "වරෙෂඪ", "meaning": "අරළු, මුකුණුවැන්න, ගොටුකොළ", "category": "plant" },
    { "word": "වරෙෂඪි", "meaning": "මුකුණුවැන්න, ගොටුකොළ, අරළු", "category": "plant" },
    { "word": "වල්", "meaning": "කෙසෙල් ගස, අඹ ගස", "category": "plant" },
    { 
        "word": "වල් ඉඟුරු", 
        "meaning": "කච්චා අල-චර්ම රෝග සඳහා ආලේපයට ගන්නා තද සුවඳකින් යුත් පැලෑටියක්. (92 පිටේ ඡායාරූපය සහිත විස්තරය බලන්න)", 
        "category": "plant" 
    },
    { "word": "වල්කතරු", "meaning": "පුවක් ගස, පටිටිකා වැල", "category": "plant" },
    { "word": "වල්කපුකිනිස්ස", "meaning": "වනකර්පාස (වල් බන්ඩක්කා)", "category": "plant" },
    { "word": "වල්කල", "meaning": "පොතු, හෙළ ලොත්, දිය මිදෙල්ල, සබරලොත්", "category": "plant" },
    { "word": "වල්කලන්", "meaning": "වල්කොල්ලු", "category": "plant" },
    { "word": "වල්කලොස්න", "meaning": "පටිටිකා, ලොත්", "category": "plant" },
    { "word": "වල්කහ", "meaning": "වනහරිද්‍රා", "category": "plant" },
    { "word": "වල්කොසොඹ", "meaning": "ලුණුමිදෙල්ල", "category": "plant" },
    { "word": "වල්ගු", "meaning": "සඳුන්", "category": "plant" },
    { "word": "වල්ගුජ", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "වල්ගුපත්‍ර", "meaning": "වල්මුං", "category": "plant" },
    { "word": "වල්තිය", "meaning": "කාලතියා", "category": "plant" },
    { "word": "වල්තියදල", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "වල්නිති", "meaning": "වල් නිවිණිය වැල්", "category": "plant" },
    { "word": "වල්මධුකර", "meaning": "වැල්මී", "category": "plant" },
    { "word": "වල්මලගුන්ත", "meaning": "කාලමැදින", "category": "plant" },
    { "word": "වල්මිකවප්ප", "meaning": "ශිරාරෝගයක් (ක්‍රිමිජ විද්‍රාව)", "category": "treatment" },
    { "word": "වල්ල", "meaning": "ඔලිඳ ඇට තුනක ප්‍රමාණ බර, ඇඹුල්වේ.", "category": "plant" },
    { "word": "වල්ලක", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "වල්ලකී", "meaning": "සල්ගස", "category": "plant" },
    { "word": "වල්ලභා", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "වල්ලර", "meaning": "කළු අගිල්, මුකුණුවැන්න, ගොටුකොළ", "category": "plant" },
    { "word": "වල්ලරි", "meaning": "මඟුල්කරඳ, වල්උළුවා, මල් පොකුර, එළනිටුල්", "category": "plant" },
    { "word": "වල්ලරෙරෙ", "meaning": "මුකුණුවැන්න", "category": "plant" },
    { "word": "වල්ලසා", "meaning": "අමුක්කරා", "category": "plant" },
    { 
        "word": "වල්ලා ගස්", 
        "meaning": "බර අඩු සුදු පාට ලී ඇති මේ ගස් වල කොළ දත් ගලවන (ප්‍රත්‍යක්‍ෂ) බේතකි. (පුරාණ ලංකාවේ) මෙකලමෙන් දත් රෝග බහුල නැත. එකල වයස් ගත වූ ඇතැම් අයගේ විදුරුමස් දියවී දත් සෙලවෙන්ට පටන් ගනී යි. එසේ වූ විට මේ වල්ලා ගසේ කොළ අඹරා ඒ සෙලවෙන දත් තිබෙන විදුරුමසට තබා මිනිතතු පහළොහක් පමණ සිටිය විට දින කීපයකින් කිසියම් වේදනාවක් නැති ව ඒ දත් ගැලවී වැටේ යි.", 
        "category": "plant" 
    },
    { "word": "වල්ලි", "meaning": "අසමෝද, කයිවර්තමුස්තා, කෙකටිය, සිවිය, හෙළ නිටුල්, මිරිස්", "category": "plant" },
    { "word": "වල්ලිකිලංගු", "meaning": "වැල්ලෙ අල", "category": "plant" },
    { "word": "වල්ලිකා", "meaning": "කොමඩු පුහුල්, හිරස්ස, පුස්සුල්", "category": "plant" },
    { "word": "වල්ලිජ", "meaning": "මිරිස්", "category": "plant" },
    { "word": "වල්ලිජ (2)", "meaning": "ගම්මිරිස්", "category": "plant" },
    { "word": "වල්ලිබා", "meaning": "කොමඩු, පත්කක්කා", "category": "plant" },
    { "word": "වල්ලී", "meaning": "වැල්, මිරිස්වැල, ගිරිතිල්ල", "category": "plant" }
];



