// data_251_259.js - පිටු 250 සිට 259 දක්වා සියලුම වචන
const data_extra_251_259 = [
  // --- පිටුව 251  (දුරාලභා සහ ගස්කහඹිලියා සම්පූර්ණ විස්තරය) ---
  {
    "word": "දුරාලභා (ධන්වයවාස)",
    "meaning": "යවාස, වැල් කසඹිලියා, (වාග්විකාලී) ගස් කසඹිලියා, (වල්කසඹිලියා) යි වෙන් වෙන් වූ වගී හතරකි. ධන් (අරාබි) දේශයෙහි වැවෙන යවාස (ධන්වයවාස) නම් පැළෑටි වගිය දුරාලභා බව ත්, දුරාලභා හා යවාස යන දෙවගිය ම සමාන ගුණ ඇති ඖෂධ බව ත්, දුරාලභා වෙනුවට යවාස ගැන්ම සුදුසු බව ත්, ඉන්දියානු ද්‍රව්‍ය ගුණ නිඝණ්ඩුවල කියා තිබේ. එහෙත් දුරාලභා (ධන්වයවාස) යවාස දෙවගිය වෙනුවට වැල් කසඹිලියා හෝ ගස් කසඹිලියා ගැනීමට ඉන්දියානු පොත් වල නියම කර ඇති තැනක් දැනගන්නට නැත. \n\nධන්වයවාස (දුරාලභා): මෙය ධන් (අරාබි) දේශය ප්‍රභව කොට ඇති අඩියක් පමණ උසට වැවෙන පැළෑටියකි. මෙහි කොළ දිග-පළල අඟල් 1/2 x 1/8 ක් පමණ ඇත. මල් රතු පාට ය. අතුවල සහ කඳේ කටු තිබේ. දුරාලභා (ධන්වයවාස) වලට ව්‍යවහාර කරන්නේ උෂ්ට්‍රභක්ෂ්‍යා (ඔටුවන් විසින් කනු ලබන පැළෑටි) යන සංස්කෘත නාමයෙන් ත් මේ පැළෑටිය ඔටුවන් කන ප්‍රදේශයෙහි (අරාබි දේශයෙහි) උපදින වගියක් බැව් පෙනේ. මෙයින් අපට දුරාලභා - ධන්වයවාස නම් දෙකකින් කියවෙන්නේ එක ම වර්ගයක් බැව් නිශ්චය කළ හැක. \n\nයවාස: අඩියක් පමණ උසට වැවෙන දිග - පළල අඟල් 1 x 1/2 පමණ ඇති රත්පාට දුරාලභා මල්වලට වඩා කුඩා මල් හටගන්නා කටු සහිත කඳක් හා අතු ඇති පැළෑටියකි යවාස. ධන්වයවාස (දුරාලභා) වලට පෙනුමෙන් හා රස - ගුණ - වීර්ය වශයෙන් මඳක් සමාන නිසා දුරාලභා වෙනුවට ප්‍රතිනිධි වශයෙන් ගැණීමට නියමකර තිබෙන යවාස, නමින් මේ පැළෑටිය දුරාලභා නොවන බැව් පැහැදිලි වේ.",
    "category": "plant"
  },
  {
    "word": "වැල්කහඹිලියා (වාග්විකාලී)",
    "meaning": "එහෙත් ලංකාවේ මේ පැළෑටි දෙවර්ගය වෙනුවට ගන්නේ විෂ සහිත සිහින් බුවක් ඇති වැල් කසඹිලියා වැල් ය. එය වෘෂ්විකාලී යන සංස්කෘත නාමයකින් හැඳින්වෙන වෙන ම වර්ගයකි. අරාබියේ වැවෙන දුරාලභා (ධන්වයවාස) වෙනුවට ප්‍රතිනිධි වශයෙන් යවාස ඉන්දියානු වෛද්‍යවරයන් නියම කළාක් මෙන් ම, අතීතයෙහි අරාබිය - ඉන්දියාව හා ලංකාව ත් අතර ගමනාගමනය පිළිබඳ පැවති දුෂ්කරතාවය නිසා ද්‍රව්‍ය ලබා ගැනීමේ අපහසුව ගැන සැලකු ලද්දිද (වාග්විකාලී) විද්‍යාව සම්බන්ධ පුළුල් අවබෝධයක් ඇති ව විසූ අපේ පැරණි වෛද්‍යවරයෝ දුරාලභා වෙනුවට වැල් කසඹිලියා සම්මත කර ගත් බවට කිසි ම සැකයක් නැත. අෂ්ටක වර්ගය ඇතුළු පද්මකාෂ්ඨ - දාරුහරිදා - පුෂ්කරමූල - හලාහක - කූෂ්ඨ - ප්‍රියංගු ආදී අරාබි - ඉන්දියා රටවල වැවෙන ඖෂධ වෙනුවට ප්‍රතිනිධි වශයෙන් මේ රටේ උපදනා ඖෂධ ගන්නේ ද අතීතයෙහි පැවති මේ දුෂ්කරත්වය නිසා විය හැක.",
    "category": "plant"
  },
  {
    "word": "ගස් කහඹිලියා",
    "meaning": "දුරාලභා - යවාස පැළෑටි ගස් වර්ග දෙකක් නිසා ඒ වෙනුවට ලංකාවේ වැවෙන කහඹිලියා ගස් (ගස් කහඹිලියා) ඇතැම් වෛද්‍යවරයෝ ගනිති. ගෙඩි මොළොක් කිරීමේ ගුණය හැර ඒ වගියේ වෙන යම් කිසි ගුණයක් නැති නිසා එය ගැණීම සුදුසු නැත. යවාස-දුරාලභා (ධන්වයවාස) නැතහොත් ගතයුත්තේ පුරුදු වැල්කසඹිලියා ම ය.",
    "category": "plant"
  },

  // --- පිටුව 252 ---
  { "word": "දුවන", "meaning": "රත්රන්", "category": "treatment" },
  { "word": "දුවකුම", "meaning": "ගොකටු", "category": "plant" },
  { "word": "දුෂ්බදිර", "meaning": "ගුරන්ද ගස", "category": "plant" },
  { "word": "දුෂ්ටබුමක", "meaning": "වතුවැල්, හෙළ රතණ, ඇත්සාටිය", "category": "plant" },
  { "word": "දුෂ්ප්‍රවේගා", "meaning": "කණ්ඨාරී වෘක්ෂය", "category": "plant" },
  { "word": "දුෂ්ටවියසී", "meaning": "මස්බැද්ද, තලිස්පතුරු, දියමින්ත", "category": "plant" },
  { "word": "දුෂ්පත්‍ර", "meaning": "අරණකාසා, (හරන්කහ) හිඟුරුපියලි", "category": "plant" },
  { "word": "දුෂ්පගී", "meaning": "රටඉඳි, කටුවැල්බටු, වැල් කසඹිලියා", "category": "plant" },
  { "word": "දුෂ්පරිග්‍රහ", "meaning": "රටඉඳි, කටුවැල්බටු", "category": "plant" },
  { "word": "දුෂ්ප්‍රසම්භි", "meaning": "දුරාලභා, කටුවැල්බටු", "category": "plant" },
  { "word": "දුෂ්ප්‍රදර්ශිනී", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "දුස්සා", "meaning": "අත්තන", "category": "plant" },
  { "word": "දුස්පගිනී", "meaning": "හිඳි", "category": "plant" },
  { "word": "දුස්පර්ශා", "meaning": "හිඳිගස්, කටුවැල්බටු, දුරාලභා", "category": "plant" },
  { "word": "දුස්පුෂ්ප", "meaning": "මීගස", "category": "plant" },
  { "word": "දුස්ප්‍රදර්ශී", "meaning": "කටුවෙලඟ, හෙළ බටු, දුරාලභා", "category": "plant" },
  { "word": "දුස්ප්‍රදර්ශිකා", "meaning": "අබ", "category": "plant" },
  { "word": "දුස්ප්‍රදර්ශිනී", "meaning": "වැටකොළු, හෙළබටු, කටුවැල්බටු", "category": "plant" },
  { "word": "දුෂ්ප්‍රදර්ශා", "meaning": "දුරාලභා, ඉඳි", "category": "plant" },
  { "word": "දුස්ඵලි", "meaning": "හිඳි", "category": "plant" },
  { "word": "දුස්ඵාලිනී", "meaning": "යොන්හිඳි", "category": "plant" },
  { "word": "දුහිකී", "meaning": "වරා", "category": "plant" },
  { "word": "දුහුදු තෙල්", "meaning": "දුහුදු ඇට මිරිකා ගන්නා තෙල්", "category": "treatment" },
  { "word": "දුහුනුමඬලා", "meaning": "දුනුමඩලා- (විස්තර 249 පිටේ ඇත.) (මෙය ප්‍රසුතයට ගන්නා බෙහෙතකි.)", "category": "plant" },
  {
    "word": "දුහුදු (දුඳි)",
    "scientific": "Celastrus Paniculata",
    "meaning": "දුහුදු වැල්. මෙය ලොවි කොළ වලට සමාන කොළ ඇති, තිබ්බටු වැල් මෙන් වැඩී යන පඳුරු (වැල්) වර්ගයකි. ලංකාවේ මෙන් ම ඉන්දියාවේ ද බොහෝ දෙනාගේ සැළකිල්ලට භාජන වූ ඖෂධයකි. දුහුදු දුහුදු ඇටවලින් ලබාගන්නා තෙල් ආයුර්වේදයේ ධාරණ ශක්තිය දියුණුවීම සඳහා ඉහළින් ම පිළිගැනේ. බින්දු පහකට වැඩි නොවන ගණනක් දිනපතා උදේ සවස බොන්ට දෙති. කිරීමටත් දිනපතා උදේ සවස පාවිච්චි කරණ ලංකාවේ පැරණි දේශීය සරස්වතී තෛලයට ගන්නා ප්‍රධාන ද්‍රව්‍ය වලින් දුහුදු තෙල් ද එක වගයකි. අතීසාර - වාතරක්ත - අංශභාග - ලාදුරු, කුඩා ළමයින්ගේ පණු ගාය ඇතුළු ශාරීරික ආබාධ වලට ගන්නා ඖෂධයෝග වලට ද දුහුදු ඇතුළත් කර තිබේ. දුහුදු කොළ යුෂ පානය කිරීමෙන් අබින් දුම් පානය නිසා විෂ ශරීර ගත වූවන්ගේ විෂ ද නැසේ යයි.",
    "category": "plant"
  },

  // --- පිටුව 253 ---
  {
    "word": "අබින් සොයා ගැනිමක් - කරබාරු ගනියම",
    "meaning": "මෙයින් බිංදු පහ බැගින් උදේ සවස තුන් මාසයක් පාවිච්චි කිරීමෙන් ස්ත්‍රී-පුරුෂයන්ගේ තෙල් හා සෙම මිශ්‍ර කරබාරු ගතිය (බොරු ඇඟ) සම්පූර්ණයෙන් මඟ හැරී ප්‍රමාණවත් ශරීර ඇති වෙයි.",
    "category": "treatment"
  },
  {
    "word": "දියවැඩියාවට",
    "meaning": "එසේ ම වරකට බිංදු පහ බැගින් දිනපතා උදේ සවස තුන් මාසයක් මේ තෙල් පාවිච්චි කිරීමෙන් බහු මූත්‍ර දෝෂය (දියවැඩියාව) නියම ප්‍රමාණය දක්වා අඩුවෙයි.",
    "category": "treatment"
  },
  { "word": "දූතසනී", "meaning": "මුඩමහණ", "category": "plant" },
  { "word": "දූතය", "meaning": "පැණිරස", "category": "treatment" },
  { "word": "දූනි", "meaning": "රතු පලොල්", "category": "plant" },
  { "word": "දූනිකා", "meaning": "එළ කටුවැල්බටු", "category": "plant" },
  { "word": "දූදරා", "meaning": "අත්තන", "category": "plant" },
  { "word": "දූද්‍රි", "meaning": "දුහුදු ගස්, කිරි, දුහුදු තෙල්", "category": "plant" },
  { "word": "දූපය", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "දූයතී", "meaning": "හිඟුරු පියලි", "category": "plant" },
  { "word": "දූෂා", "meaning": "ඒතන්, දූෂා වනාහි නීල දූෂා, ශ්වේත දූෂා, ගණ්ඩ දූෂා යයි වගී තුනකි", "category": "plant" },
  { "word": "දූර්මූල", "meaning": "මුදකණි, දුරාලභා", "category": "plant" },
  { "word": "දූර්මූලා", "meaning": "නියඳ, යවාස", "category": "plant" },
  { "word": "දූරවේදක", "meaning": "යකඩ, කාන්දම්", "category": "treatment" },
  { "word": "දූරානුගත මූලා", "meaning": "ඉරමුසු, මහ ඉරමුසු", "category": "plant" },
  { "word": "දූලිකා", "meaning": "අවිරිය", "category": "plant" },
  { "word": "දෘක්ප්‍රසාද", "meaning": "කුලත්ථකෘත, කොල්ලු", "category": "plant" },
  { "word": "දෘකිලිම", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දෘග්වියාධිගත", "meaning": "රත්හඳුන්", "category": "plant" },
  { "word": "දෘඪබීජක", "meaning": "අන්දර, අස්වැන්න", "category": "plant" },
  { "word": "දෘඪ", "meaning": "ඉඹුල් ගස, ද්‍රවගස", "category": "plant" },
  { "word": "දෘඪකැටා", "meaning": "බබුස් තණ", "category": "plant" },
  { "word": "දෘඪකණ්ටක", "meaning": "රුකුගුණ", "category": "plant" },
  { "word": "දෘඪකාණ්ඩ", "meaning": "රණ ගස, මදු වැල", "category": "plant" },
  { "word": "දෘඪගන්ධ", "meaning": "පෙරුම්කායම්", "category": "treatment" },
  { "word": "දෘඪ ග්‍රන්ථි", "meaning": "රණගස", "category": "plant" },
  { "word": "දෘඪච්ඡද", "meaning": "තල්ගස", "category": "plant" },
  { "word": "දෘඪතරු", "meaning": "පොල් ගස, ද්‍රවගස", "category": "plant" },
  { "word": "දෘඪතාණ", "meaning": "මුදු තණ, බබුස් තණ", "category": "plant" },
  { "word": "දෘඪදාරු", "meaning": "තල්ගස", "category": "plant" },
  { "word": "දෘඪනීල", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "දෘඪපත්‍ර", "meaning": "රණගස, මුදු තණ", "category": "plant" },
  { "word": "දෘඪපත්‍ර වාරුණී", "meaning": "හෙළපිල = දන්ත රෝගයට විශේෂ ගුණ දෙන ඖෂධයකි.", "category": "plant" },
  { "word": "දෘඪපාද", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "දෘඪපාද", "meaning": "අත්බේරිය", "category": "plant" },
  { "word": "දෘඪ ප්‍රයෝග", "meaning": "පලොල්", "category": "plant" },

  // --- පිටුව 254 ---
  { "word": "දෘඪප්‍රරෝහ", "meaning": "නුග ගස, පුලිල", "category": "plant" },
  { "word": "දෘඪඵල", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "දෘඪබන්ධ", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "දෘඪබන්ධනී", "meaning": "ඉරමුසු, රණා", "category": "plant" },
  { "word": "දෘඪබාලුක", "meaning": "එල්වළු", "category": "plant" },
  { "word": "දෘඪපුර", "meaning": "ගොකටු", "category": "plant" },
  { "word": "දෘඪමාලා", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "දෘඪමූල", "meaning": "පොල් ගස, අන්දර ගස, මුරුක් නම් තෘණ විශේෂය", "category": "plant" },
  { "word": "දෘඪලතා", "meaning": "මදුවැල", "category": "plant" },
  { "word": "දෘඪ වල්කල", "meaning": "පුවක්, දිය මිත්ත, දෙල්", "category": "plant" },
  { "word": "දෘඪවාල", "meaning": "එල්වළු", "category": "plant" },
  { "word": "දෘඪශිප්", "meaning": "රම්මානිස්ස, රන්වන් වේලා, තෝර, මසන්, සිනියා, පොල් ගස", "category": "plant" },
  { "word": "දෘඪවිප්ක", "meaning": "පොල්", "category": "plant" },
  { "word": "දෘඪවෘත්තා", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "දෘඪස්කන්ධ", "meaning": "කිරිපළු", "category": "plant" },
  { "word": "දෘඪස්පිනී", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "දෘඪසූත්‍රිකා", "meaning": "මුරුවා", "category": "plant" },
  { "word": "දෘඪා", "meaning": "පිටවක්කා, බිමිතල්", "category": "plant" },
  { "word": "දෘතා", "meaning": "දුරු", "category": "plant" },
  { "word": "දෘනාම", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "දෘම", "meaning": "පොල්, මහ නුග", "category": "plant" },
  { "word": "දෘමං", "meaning": "සුළු කුඹුක්", "category": "plant" },
  { "word": "දෘමව්‍යාධි", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "දෘමෝ", "meaning": "මෝර ගස", "category": "plant" },
  { "word": "දෘමොත්ඵල", "meaning": "කින්හිගිරි, ඇසල", "category": "plant" },
  { "word": "දෘවාක්ෂ", "meaning": "කොළොම්", "category": "plant" },
  { "word": "දෘශාඝ", "meaning": "වදුරු මෑ", "category": "plant" },
  { "word": "දෘශෝපම", "meaning": "හෙළ පියුම්", "category": "plant" },
  { "word": "දෘෂ්ටිකාන්ත", "meaning": "පොණ්ඩරු, ගොඩ මානෙල්", "category": "plant" },
  { "word": "දෘෂ්ටිවිශෝධි", "meaning": "තලිස්පතුරු", "category": "plant" },
  { "word": "දෘෂ්ටිවීර", "meaning": "මීපැණි", "category": "treatment" },
  { "word": "දෘසම්භේද", "meaning": "පුස්වැන්න, පොල්", "category": "plant" },
  { "word": "දෘසල්පොස", "meaning": "පියාගස්", "category": "plant" },
  { "word": "දෘහා", "meaning": "(දෙදුරු) කළුදුරු, සුදුදුරු", "category": "plant" },
  { "word": "දෙඅරිසි", "meaning": "පොඩි අරිසි, මහ අරිසි, වැලි පොළොවේ හටගන්නා, ලා නිල් සහ කිලිටි සුදුපාට සුළු තයි වැනි පැළෑටියක් (සාරාර්ථ සංග්‍රහව) පොඩි අරිසි ගැන විස්තරයක් ඉදිරියෙහි ඇත.", "category": "plant" },
  { "word": "දෙඉද්ද", "meaning": "සිනිද්ද, බෝලිද්ද", "category": "plant" },
  { "word": "දෙකටරොළු", "meaning": "(දෙ කටරොළු) එළ කටරොළු, නිල් කටරොළු (වැල්)", "category": "plant" },
  { "word": "දෙකටුකරඬු", "meaning": "රත් කටුකරඬු, කහ කටුකරඬු", "category": "plant" },
  { "word": "දෙකරඹ", "meaning": "හින් කරඹ, මහ කරඹ (බැමියත්)", "category": "plant" },
  { "word": "දෙකසා", "meaning": "කසා, වදකසා", "category": "plant" },
  { "word": "දෙකිහිරි", "meaning": "හෙළ කිහිරි, රත් කිහිරි", "category": "plant" },
  { "word": "දෙකාල", "meaning": "කාල, (කළු කාල) රත් කාල (පත් කාල)", "category": "plant" },
  { "word": "දෙකූඩුල්ල", "meaning": "පත, (කාල)", "category": "plant" },
  { "word": "දෙකුයුම්", "meaning": "කරාබු, වසාවාසි", "category": "plant" },
  { "word": "දෙකුර", "meaning": "සුළු කූර, මහ කූර", "category": "plant" },
  { "word": "දෙගල්", "meaning": "ගල් මද, ගල් නහර දෙක", "category": "treatment" },
  { "word": "දෙතඹල", "meaning": "හින් තඹල, මහ තඹල", "category": "plant" },
  { "word": "දෙදිය", "meaning": "සිරි දිය, කර දිය", "category": "treatment" },
  { "word": "දෙදිවි", "meaning": "නාවා", "category": "plant" },
  { "word": "දෙදුම්බ", "meaning": "රසතල්ල, නිත්තතල්ල (වැල්)", "category": "plant" },
  { "word": "දෙදුරසමෝද", "meaning": "දෙදුරු, (සුදු දුරු - කළුදුරු) අසමෝදගම්", "category": "plant" },
  { "word": "දෙදුරු", "meaning": "සුදුදුරු, කළුදුරු", "category": "plant" },
  { "word": "දෙන්දාති", "meaning": "නික", "category": "plant" },
  { "word": "දෙනයි", "meaning": "සුළු නයි, මහ නයි", "category": "plant" },
  { "word": "දෙනිඹ", "meaning": "කොසඹ, බිම්කොසඹ හෝ කොසඹ මහකොසඹ (ලුණුමිදෙල්ල)", "category": "plant" },

  // --- පිටුව 255 ---
  { "word": "දෙපනස්", "meaning": "සියඹලා", "category": "plant" },
  { "word": "දෙබටු", "meaning": "එළබටු, කටුවැල්බටු", "category": "plant" },
  { "word": "දෙබුරැද", "meaning": "සිහින් සාරණ, මහ (පිට සුදු) සාරණ", "category": "plant" },
  { "word": "දෙමදු", "meaning": "වැල්මී, මීමල්", "category": "plant" },
  { "word": "දෙමිතතා", "meaning": "කහ", "category": "plant" },
  { "word": "දෙමිදි", "meaning": "හින් මිදි, මහ මිදි", "category": "plant" },
  { "word": "දෙමිරිකුළු", "meaning": "සිහින් මුරුංගා, මහ මුරුංගා", "category": "plant" },
  { "word": "දෙමිරිස්", "meaning": "(ගම්) මිරිස්, වල්ගම්මිරිස් (වල්මොලගු)", "category": "plant" },
  { "word": "දෙමැබිය", "meaning": "රුනමැබිය, මැබිය", "category": "plant" },
  { "word": "දෙමෝද", "meaning": "අසමෝදගම්, කොරාසානි", "category": "plant" },
  { "word": "දෙසි", "meaning": "මහ මිදි", "category": "plant" },
  { "word": "දෙරමිනියා", "meaning": "සුළු එරමිනියා, මහ එරමිනියා", "category": "plant" },
  { "word": "දෙල්", "meaning": "ලබුප් එල වෘක්ෂය", "category": "plant" },
  { "word": "දෙලත්", "meaning": "එන්සාල්, මහ එන්සාල්", "category": "plant" },
  { "word": "දෙලොබු", "meaning": "(දෙලොත්) = හෙළලොත් රත්ලොත්", "category": "plant" },
  { "word": "දෙව් පියවුරු", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "දෙවගපුල්", "meaning": "වගපුල්, ඇත්වගපුල් (තිප්පිලි, ගප් තිප්පිලි)", "category": "plant" },
  { "word": "දෙවිබුරැව", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "දෙවිකුසුම්", "meaning": "කරාබුනැටි", "category": "plant" },
  { "word": "දෙවුකොසි", "meaning": "මුරුවා වැල්", "category": "plant" },
  { "word": "දෙවුදුරු", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දෙසඳුන්", "meaning": "රත්හඳුන්, සුදු හඳුන්", "category": "plant" },
  { "word": "දෙසැබිල්ල", "meaning": "සැබිල්ල දෙවර්ගය, (වාදමුස වැටීමට දෙන ඖෂධයකි)", "category": "plant" },
  { "word": "දෙහඬ", "meaning": "රත් හඳුන්, සුදු හඳුන්", "category": "plant" },
  { "word": "දෙහි මාලසි", "meaning": "දෙහි ගැට", "category": "plant" },
  { "word": "දෙහිරමුසු", "meaning": "හින් ඉරමුසු, මහ ඉරමුසු", "category": "plant" },
  { "word": "දෙහුනහ", "meaning": "කලං හය, (හුන දෙක)", "category": "treatment" },
  { "word": "දේව", "meaning": "දේවදාර, ගොඩ මානෙල්, රසකිඳ", "category": "plant" },
  { "word": "දේවකදම්බ", "meaning": "සඳුන්, කපුරු, අගිල්, කොකුම්, හිරිකඩ සඳුන් යන පස් සුවඳ කල්කය", "category": "treatment" },
  { "word": "දේවකාෂ්ඨ", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දේව කෙඳිරි", "meaning": "මුරුංගා", "category": "plant" },
  { "word": "දේව කුතකුටක", "meaning": "කිඹුල්වැන්න", "category": "plant" },
  { "word": "දේව කුසුම්බිකා", "meaning": "යොන්තුඹ, මහ තුඹ", "category": "plant" },
  { "word": "දේවකුරුම්බා", "meaning": "මහ ගැට තුඹ", "category": "plant" },
  { "word": "දේවකුසුම", "meaning": "කරාබු", "category": "plant" },
  { "word": "දේවගණා", "meaning": "මහා මේදා", "category": "plant" },
  { "word": "දේව ගන්ධිකා", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "දේවගුරු", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "දේවගුරු මුදියන්සේ", "meaning": "ගන්සූරිය ගස (රහස් බෙත් වට්ටෝරුවක ප්‍රහේලිකා වචනයක්)", "category": "plant" },
  { "word": "දේව ඡන්දක", "meaning": "ද්‍යාමක නම් සුවඳ තෘණ, කලාඳුරු", "category": "plant" },
  { "word": "දේවතරුණී", "meaning": "මහා රෝස ගස", "category": "plant" },
  { "word": "දේවතරු", "meaning": "රත්හඳුන්, මුදුරා, ඇසතු, කටුකිහිරි (මඟුරාදි වෘක්ෂ පස)", "category": "plant" },
  { "word": "දේවතා", "meaning": "අත්තන, තුන්බෝ අත්තන", "category": "plant" },
  { "word": "දේවතා කුසුම", "meaning": "කරාබු නැටි", "category": "plant" },
  { "word": "දේවතාණ්ඩී", "meaning": "දේවදාලිය වැල්, උඩ හල්ලා වැල්, (උඩහව = පබ වැල්)", "category": "plant" },
  { "word": "දේවතාමණී", "meaning": "මහාමේදා (අෂ්ටක වගියේ බෙහෙත්)", "category": "plant" },
  { "word": "දේවතාග්‍රහගඤ්ජිනී", "meaning": "බුලත්", "category": "plant" },
  { "word": "දේවතාස", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "දේවදණ්ඩ", "meaning": "එරබදු වෙසෙසක්", "category": "plant" },
  { "word": "දේව දණ්ඩා", "meaning": "සිරිවැඩි බැවිල", "category": "plant" },
  { "word": "දේවදණ්ඩෝත්ඵල", "meaning": "සිරිවැඩි බැවිල, ගස් කැලිය", "category": "plant" },

  // --- පිටුව 256 ---
  { "word": "දේව දන්තා", "meaning": "කොසඹ", "category": "plant" },
  { "word": "දේව දන්තී", "meaning": "කොසඹ", "category": "plant" },
  { "word": "දේවදානී", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "දේවදාසි", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දේවදාරු", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දේවදාලී", "meaning": "දේවදාලිය වැල් = ගිනි කදම්බ = ගිනි රැස්", "category": "plant" },
  { "word": "දේවදූතිකා", "meaning": "වැල් රඹුටන්", "category": "plant" },
  { "word": "දේවදූතදන්තී", "meaning": "පිටවක්කා, කටුනලා, රන්තලා, දුටු සතුටු, (කෝබේසි කොළ - මොණර කුඩුම්බිය)", "category": "plant" },
  { "word": "දේව ද්‍රැම", "meaning": "කට්ටකුමංජල්, කුන්දරුක්කම්", "category": "plant" },
  { "word": "දේවදාම", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දේවධූප", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "දේවධූම", "meaning": "ගුගුල්, කුන්දරුක්කම්, දුම්මල", "category": "treatment" },
  { "word": "දේවනා", "meaning": "අත්තන, තුන්බෝ අත්තන", "category": "plant" },
  { "word": "දේවනාළ", "meaning": "මසබට", "category": "plant" },
  { "word": "දේවනාළ", "meaning": "මඟබට", "category": "plant" },
  { "word": "දේවනිර්මිත", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "දේවනිර්මිතා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "දේවනි", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "දේවපත්‍රිකා", "meaning": "පික් මල්", "category": "plant" },
  { "word": "දේවපාරා", "meaning": "ලියනහලා", "category": "plant" },
  { "word": "දේවපුත්‍ර", "meaning": "හුණකපුරු", "category": "plant" },
  { "word": "දේවපුෂ්ප", "meaning": "කරාබු", "category": "plant" },
  { "word": "දේවපුෂ්ප", "meaning": "අලරිය (කණේරු)", "category": "plant" },
  { "word": "දේවපුෂ්පක", "meaning": "දෙඹ", "category": "plant" },
  { "word": "දේවපුෂ්පාර", "meaning": "හෙළ කණේරු", "category": "plant" },
  { "word": "දේවප්‍රිය", "meaning": "කිකිරිදිය, රන්වන් කිකිරිදිය, කසාවන් කටුකරඬු, කටු රඹුරංගා, සුවඳ හොට, බුලත්", "category": "plant" },
  { "word": "දේවපාෂාණ", "meaning": "කිරිපලා", "category": "plant" },
  { "word": "දේවබලා", "meaning": "මහ බැබිල, වලාවැන්න, (හංසපාදි) දුටු සතුටු", "category": "plant" },
  { "word": "දේවභවනා", "meaning": "ඇසතු", "category": "plant" },
  { "word": "දේවමණි", "meaning": "මස්බැද්ද, මහමෙවන් (මහා ශ්‍රාවණ)", "category": "plant" },
  { "word": "දේවමණීර්", "meaning": "හුණගස", "category": "plant" },
  { "word": "දේවමතනි", "meaning": "මහාමේදා (අෂ්ටක වගියේ ඔසුවක්)", "category": "plant" },
  { "word": "දේවමිත්‍ර", "meaning": "කුඹුක් ගස", "category": "plant" },
  { "word": "දේවයෝනි", "meaning": "ගල් සෙවෙල්, ගල් මද", "category": "treatment" },
  { "word": "දේවරාජ", "meaning": "මුරුවා", "category": "plant" },
  { "word": "දේවල්කා", "meaning": "සිනිද්ද, ගැටපිච්ච", "category": "plant" },
  { "word": "දේවලාබුලිකා", "meaning": "ඇත්සාටිය, හිත් මැඩහඟු", "category": "plant" },
  { "word": "දේව වල්ලභ", "meaning": "දෙඹ, කිණ දෙඹ", "category": "plant" },
  { "word": "දේව වල්ලභා", "meaning": "කිණ දෙඹ", "category": "plant" },
  { "word": "දේවවලා", "meaning": "ගොඩමානෙල්", "category": "plant" },
  { "word": "දේවවෘක්ෂ", "meaning": "රක්අත්තන, ගුගුල්, එරබදු", "category": "plant" },
  { "word": "දේවශතගන්ධිකා", "meaning": "මොණරකුඩුම්බිය, දුටුසතුටු, (කෝබේසි පලා)", "category": "plant" },
  { "word": "දේවශ්‍රේණි", "meaning": "මුරුවා", "category": "plant" },
  { "word": "දේවශාලී", "meaning": "හැල් වෙසෙසක්.", "category": "plant" },
  { "word": "දේවශේඛර", "meaning": "දමනක රුක", "category": "plant" },
  { "word": "දේවසහා", "meaning": "ගොඩමානෙල්, දුටුසතුටු, මොණර කුඩුම්බිය = කෝබේසි පලා) කූඹුරුවැල්, මඟුල්කරුඹුර වැන්න", "category": "plant" },
  { "word": "දේවසර්ෂප", "meaning": "දෙවි අබ", "category": "plant" },
  { "word": "දේවා", "meaning": "ගොඩ මානෙල්, අසන පර්ණී රුක", "category": "plant" },
  { "word": "දේවාංගිකා", "meaning": "ගස්කැලිය", "category": "plant" },
  { "word": "දේවාග්‍රා", "meaning": "ගස්කැලිය", "category": "plant" },
  { "word": "දේවාත්මන්", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "දේවාද්වය", "meaning": "මහබැබිල, සිරිවැඩි බැබිල", "category": "plant" },
  { "word": "දේවානු", "meaning": "බුලත්", "category": "plant" },
  { "word": "දේවානෘ", "meaning": "බුලත්", "category": "plant" },
  { "word": "දේවානාං අග්‍රප්‍රිය", "meaning": "බුලත්", "category": "plant" },
  { "word": "දේවාව්වා", "meaning": "මහබැබිල, මඟුල් කුඹුරු වැන්න", "category": "plant" },
  { "word": "දේවාලය", "meaning": "ගොඩමානෙල්", "category": "plant" },

  // --- පිටුව 257 ---
  { "word": "දේවවාස", "meaning": "ඇසතු, රක්අත්තන, දේවදාර", "category": "plant" },
  { "word": "දේවාහ්වය", "meaning": "දේවදාර, සිද්ධිගුරු", "category": "plant" },
  { "word": "දේවාන්වගන්ධිකා", "meaning": "දුටුසතුටු", "category": "plant" },
  { "word": "දේවාන්ව", "meaning": "දුටුසතුටු, මොණර කුඩුම්බිය, (කෝබේසිපලා) දේවදාර", "category": "plant" },
  { "word": "දේවිකා", "meaning": "අත්තන", "category": "plant" },
  { "word": "දේවිලතා", "meaning": "පික්මැලි, (පික්මල්)", "category": "plant" },
  { "word": "දේවී", "meaning": "මුරුවා, පික්මැලි, වැල්තුඹ, වැටකොළු, අරළු, බැබිල, දිය මිත්ත, අස්වැන්න", "category": "plant" },
  { "word": "දේවිවිප්", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "දේවේෂ්ට", "meaning": "ගුගුල්, ලප්නාරම්, මහ මේදා", "category": "plant" },
  { "word": "දේව්‍යසා", "meaning": "මුරාමාංශි, බැමිනිරිය", "category": "plant" },
  { "word": "දේශ්‍යාමබැබිල", "meaning": "කෙළිඳ ඇට", "category": "plant" },
  { "word": "දේශා", "meaning": "මුරත ගස", "category": "plant" },
  { "word": "දේශි", "meaning": "වැල්මී", "category": "plant" },
  { "word": "දේශිකා", "meaning": "දෙසි", "category": "plant" },
  { "word": "දේහලා", "meaning": "මින්පාන්", "category": "plant" },
  { "word": "දේහලි", "meaning": "හෝපලු", "category": "plant" },
  { "word": "දේහවල්කල", "meaning": "මුරුඤ්ජතෙල්", "category": "treatment" },
  { "word": "දේහදියා", "meaning": "නරමුත්‍ර", "category": "treatment" },
  { "word": "දෛත්‍යාස", "meaning": "ලාකඩ, සුරා", "category": "treatment" },
  { "word": "දෛත්‍යාකූසුමා", "meaning": "සුගන්ධ ද්‍රව්‍යයක්", "category": "plant" },
  { "word": "දෛත්‍යාමේදජ", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "දෛත්‍යරක්තක", "meaning": "හිඟුල්", "category": "treatment" },
  { "word": "දෛත්‍යා", "meaning": "තලිස්පතුරු, මුරාමාංශි, අසමෝදගම්", "category": "plant" },
  { "word": "දෛතේය්‍ය", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "දෛතේය්‍යරක්ත", "meaning": "හිඟුල්", "category": "treatment" },
  { "word": "දෛවකාමිනී", "meaning": "මහමෙවන්", "category": "plant" },
  {
    "word": "දොඩම්පනා",
    "scientific": "Glycosmis Pentaphylla",
    "meaning": "පැඟිරි ගස් වගියක්. මේ ගස වියලි කලාපයේ වැවෙන තද පැඟිරි ගතියකින් යුත් ගස් වගියකි. පඳුරු වශයෙන් වැවෙන මේ ගස් වල කොළ හැඩහුරු කමින් කොස් කොළ වලට සමාන ය. එයට වඩා මඳක් බොකුටු ගතියෙන් යුක්ත ය. කර කොළ ප්‍රමාණ ඝනකමින් හා තද කොළ පාටින් යුත් මේ ගසේ කොළ යුෂ හා මුල් ද ප්‍රාණ ජීවය වැනි උසස් තෙල් වගී වලට හා සන්ධි රෝග සඳහා හිඳින තෙල් වගී වලට ත් ගනිති. මේ ගසේ මුල් ශ්ලේෂ්ම නාශක ඖෂධයකි. ඒ සඳහා අවශ්‍ය කෂාය - අරිෂ්ට - ආසව ආදිය පිණිස දොඩම්පනා මුල් භාවිත කරති.",
    "category": "plant"
  },

  // --- පිටුව 258 ---
  { "word": "දොණ්ඩිකා (නඩි)", "meaning": "කරඳ වෘක්ෂය", "category": "plant" },
  { "word": "ද්‍රෝමි", "meaning": "දෙඹ", "category": "plant" },
  { "word": "ද්‍රෝමිපා", "meaning": "දෙඹ ගස", "category": "plant" },
  { "word": "ද්‍රෝමි", "meaning": "කේසර", "category": "plant" },
  { "word": "ද්‍රෝරණී", "meaning": "සායම් වගී දියකිරීමට හා චිත්‍ර වර්ණවත් කිරීමට අවශ්‍ය තෙල් ලබා ගන්නා ගස් වගිය, මේ තෙල් තුවාල වල බබු කැළැල් මට සාදා ගන්නා පැලැස්තර පිණිස ද ගනිති.", "category": "plant" },
  { "word": "ද්‍රෝරණතෙල්", "meaning": "ද්‍රෝරණ ගසින් ගන්නා තෙල්", "category": "treatment" },
  { "word": "දෝතල කිතුල්", "meaning": "කිතුල් ගස", "category": "plant" },
  { "word": "දෝතලු", "meaning": "පුවක් වර්ගයට අයත් රතු මල් හා කොළපු වලින් යුත් ලේනතැරි පමනට වඩා දිගැති නැබි කුඩා ගෙඩි වලු සෑදෙන වනගත ව වැවෙන (තාල වර්ගයේ) ගසකි.", "category": "plant" },
  { "word": "ද්‍රෝතින්කා", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ද්‍රෝති", "meaning": "අවිරිය", "category": "plant" },
  { "word": "දෝලා", "meaning": "අවිරිය, බේරු, තෙල්බේරු", "category": "plant" },
  { "word": "දෝලායන්ත්‍රය", "meaning": "දෝලා යනු එල්ලෙන යන අර්ථ යි. භාජනයක කැබලි දෙකක් වැනි ආධාරයක් තබා වතුර නොගෑවෙන සේ ඖෂධ පොට්ටනියක් එහි එල්වා ඒ බේහෙත හුමාලයෙන් තැම්බීම සඳහා පිළියෙළ කර ගන්නා ක්‍රමය දෝලා යන්ත්‍රය යි. පුරාණයේ සිට දේශීය වෙදකමේ පැවත එන කඩපිම්මෙන් තැම්බීම දෝලා යන්ත්‍ර ක්‍රමය යි.", "category": "treatment" },
  { "word": "දෝෂකාර", "meaning": "දෙල් ගස", "category": "plant" },
  { "word": "දෝෂනේත්‍ර", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "දෝෂපාකින්", "meaning": "ඇම්බරැල්ලා", "category": "plant" },
  { "word": "දෝෂපාවන", "meaning": "නිවුලු ගස", "category": "plant" },
  { "word": "දෝෂහාරී", "meaning": "හෝපලු", "category": "plant" },
  { "word": "දෝෂකෙලශී", "meaning": "වල් වේලා ගස", "category": "plant" },
  { "word": "දෝෂ", "meaning": "කිනිහිරිය", "category": "plant" },
  { "word": "දෝසා", "meaning": "අමු කහ අල", "category": "plant" },
  { "word": "දෝගත", "meaning": "මසිල ගස", "category": "plant" },
  { "word": "දෝහල", "meaning": "හෝපලු ගස", "category": "plant" },
  { "word": "දෝහාපනය", "meaning": "කිරි", "category": "treatment" },
  { "word": "ද්‍රේවණිකා", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "ද්‍රෞෂීල්‍යකා", "meaning": "කරිවිල, මහ කරිවිල", "category": "plant" },
  { "word": "ද්‍රෞසලේය", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ද්‍යුන", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ද්‍යුපනී", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ද්‍යුමණී", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ද්‍රඩ", "meaning": "ද්‍රව ගස", "category": "plant" },
  { "word": "ද්‍රමා", "meaning": "කිහිරි", "category": "plant" },
  { "word": "ද්‍රව්‍ය", "meaning": "අස්වැන්න, ගල්මද, ගල් සෙවෙල්, පික්තල, බෙහෙත, සුරා", "category": "treatment" },
  { "word": "ද්‍රව", "meaning": "ද්‍රවගස, මෝරු", "category": "treatment" },
  { "word": "ද්‍රවාය", "meaning": "රන්සකුරු", "category": "treatment" },
  { "word": "ද්‍රවදුරා", "meaning": "පික්තල, ලාකඩ", "category": "treatment" },
  { "word": "ද්‍රවද්‍රව්‍ය", "meaning": "කිරි, දී, ගිතෙල්, ආදී වැගිරෙන ද්‍රව්‍ය", "category": "treatment" },
  { "word": "ද්‍රවන්ති", "meaning": "සාතාවාරිය, මිකත්පලා, මිනුග, ගොඩුකොළ", "category": "plant" },

  // --- පිටුව 259 ---
  { "word": "ද්‍රවන", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ද්‍රවවිනාශනී", "meaning": "වැළුක්, රඹුක්", "category": "plant" },
  { "word": "ද්‍රවා", "meaning": "අස්වැන්න", "category": "plant" },
  { "word": "ද්‍රවාක්ෂී", "meaning": "කලාඳුරු (වම්මුතු)", "category": "plant" },
  { "word": "ද්‍රවිඩ", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ද්‍රවින", "meaning": "රත්රන්", "category": "treatment" },
  { "word": "ද්‍රවිනාශන", "meaning": "මුරුංගා", "category": "plant" },
  { "word": "ද්‍රවිනතාශක", "meaning": "මිරිකුළු (මුරුංගා ගස)", "category": "plant" },
  { "word": "ද්‍රාක්ෂා", "meaning": "මිදිපල (මුද්‍රික ඵල) වාහනක, පියාගස්, යොන්ඉඳි", "category": "plant" },
  { "word": "ද්‍රාක්ෂාඵල", "meaning": "පියල්ගස්, මිදිඵල", "category": "plant" },
  { "word": "ද්‍රාක්ෂායනී", "meaning": "දන්ත ගස", "category": "plant" },
  { "word": "ද්‍රාම", "meaning": "රණහුණ", "category": "plant" },
  { "word": "ද්‍රාමිලි", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ද්‍රාවක කාණ්ඩ", "meaning": "තෙලෙකඳ (අල වෙසෙසක්)", "category": "plant" },
  { "word": "ද්‍රාවන", "meaning": "ඉඟිනි ඇටය", "category": "plant" },
  { "word": "ද්‍රාවනී", "meaning": "කවන්නික, තලාගස්, කරබෙයිය", "category": "plant" },
  { "word": "ද්‍රාවා", "meaning": "මුරුවාවැල්", "category": "plant" },
  { "word": "ද්‍රාවිඩ", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ද්‍රාවිඩක", "meaning": "හිඟුරුපියලි, බළල්ළූණු", "category": "plant" },
  { "word": "ද්‍රාවිඩහුනිකා", "meaning": "බළල්ළූණු, ආමගරිදා", "category": "plant" },
  { "word": "ද්‍රාවිඩි", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ද්‍රාම්බෝද්භව", "meaning": "සුවඳතෘණ, පුවඟු, එන්සාල්", "category": "plant" },
  { "word": "ද්‍රාවිණ", "meaning": "බූරැල්ල, කැම්මේරිය", "category": "plant" },
  { "word": "ද්‍රාවින්", "meaning": "ඇඹුල්වේ", "category": "plant" },
  { "word": "ද්‍රාවී", "meaning": "පුෂ්කර, කඩල", "category": "plant" },
  { "word": "ද්‍රීර්ගහානර", "meaning": "පුවක්", "category": "plant" },
  { "word": "ද්‍රෝණී", "meaning": "ගැටතුඹ, රන්වන් සඳුන්, කුරිඤ්ජි ගතර, මුහුදු ලුණු", "category": "treatment" },
  { "word": "ද්‍රෝණගන්ධිකා", "meaning": "අරත්ත, කළුවාගස්", "category": "plant" },
  { "word": "ද්‍රෝණපර්ණී", "meaning": "ගැටතුඹ, බිම් කෙසෙල්", "category": "plant" },
  { "word": "ද්‍රෝණපුෂ්පී", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ද්‍රෝණිය", "meaning": "ලාස් 4, = (පත 64, පලම් 256. තිබ)", "category": "treatment" },
  { "word": "ද්‍රෝණවෛකුණ්ඨකා", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ද්‍රෝණා", "meaning": "ගැටතුඹ, මහගොන් කැකිරි", "category": "plant" },
  { "word": "ද්‍රෝණී", "meaning": "බේරු, තෙල්බේරු, අවිරිය", "category": "plant" },
  { "word": "ද්‍රෝණිකා", "meaning": "ගැටතුඹ, අවිරිය ගස", "category": "plant" },
  { "word": "ද්‍රෝණිද්‍ර", "meaning": "වැටකේ", "category": "plant" },
  { "word": "ද්‍රෝණිය", "meaning": "ලාස් 16", "category": "treatment" },
  { "word": "ද්‍රෝණී", "meaning": "වැටකේ ගස", "category": "plant" },
  { "word": "ද්‍රෝණීජ", "meaning": "මුහුදු ලුණු", "category": "treatment" },
  { "word": "ද්‍රෞහිමාතාකා", "meaning": "තියඳ", "category": "plant" },
  { "word": "ද්‍රෞහණි", "meaning": "මුහුදු ලුණු", "category": "treatment" },
  { "word": "ද්‍රෞහණිජ", "meaning": "මුහුදු ලුණු", "category": "treatment" },
  { "word": "ද්‍රෑකිලිම", "meaning": "දේවදාර", "category": "plant" },
  { "word": "ද්‍රෑසින්", "meaning": "ශුමිවම්පක වෘක්ෂය", "category": "plant" },
  { "word": "ද්‍රෑසගන්ධ", "meaning": "පෙරුම්කායම්", "category": "treatment" },
  { "word": "ද්‍රෑසතරු", "meaning": "ද්‍රව ගස", "category": "plant" },
  { "word": "ද්‍රෑසදාරු", "meaning": "තල්ගස", "category": "plant" },
  { "word": "ද්‍රෑසපත්‍රවාරිණී", "meaning": "හෙළපිල", "category": "plant" },
  { "word": "ද්‍රෑසඵල", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "ද්‍රෑසබන්ධු", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ද්‍රෑසමාපුර", "meaning": "ගොකටු", "category": "plant" },
  { "word": "ද්‍රෑසමූල", "meaning": "අන්දර", "category": "plant" },
  { "word": "ද්‍රෑසවාරා", "meaning": "එල්වළු", "category": "plant" },
  { "word": "ද්‍රෑසවිෂ්ටක", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "ද්‍රෑඨාඞඝ්‍රීක", "meaning": "අන්දර, අස්වැන්න", "category": "plant" }
];