// data_221_230.js - පිටු 221 සිට 230 දක්වා සියලුම වචන
const data_extra_221_230 = [
  // --- පිටුව 221 ---
  { "word": "තිනිම", "meaning": "රත් හඳුන්, සුදු හඳුන්, වගාපුල් යන තුන් වගය", "category": "plant" },
  { "word": "තිහිර", "meaning": "හබි", "category": "plant" },
  { "word": "තීක්‍ෂණ", "meaning": "රිදීතුත්ථ, නියඳ, නිප්පිලි, වදකසා, කළු අබ, හෝතලා, මුරුංගා, මිරිස්, යකඩ, වානේ, කුඹකණ, රත්ගස්, ලොත්, යව, කරලුණු, විෂ, කටුකරඬු, මෝර, උළුහාල්, මුහුදුමිණි, මී ගස්, කටුකරෝෂණ, කරාබුනැටි", "category": "plant" },
  { "word": "තීක්‍ෂණක", "meaning": "ඇපල, හෙළ අබ, තෙලඹු", "category": "plant" },
  { "word": "තීක්‍ෂණකණ්ටක", "meaning": "අත්තන ගස, සිනියා ගස, ඉඹුල් වෘක්‍ෂය, කරීර වෘක්‍ෂය, ලුණ ගස, දළක් ගස, කටුකරඬු, යවාස", "category": "plant" },
  { "word": "තීක්‍ෂණකණ්ටකා", "meaning": "කණ්ඨාරී වෘක්‍ෂය", "category": "plant" },
  { "word": "තීක්‍ෂණකන්ද", "meaning": "රතුලුලූණු", "category": "plant" },
  { "word": "තීක්‍ෂණකන්දක", "meaning": "සබරල", "category": "plant" },
  { "word": "තීක්‍ෂණකරණවල්ලි", "meaning": "සිවිය", "category": "plant" },
  { "word": "තීක්‍ෂණකල්ක", "meaning": "කොතඹුරු ගස", "category": "plant" },
  { "word": "තීක්‍ෂණකිලක", "meaning": "අන්තරපවිටා, එළ කුකුරුමුවන්", "category": "plant" },
  { "word": "තීක්‍ෂණගන්ධ", "meaning": "අක්මැල්ල, මුරුංගා, අසමෝදගම්, කුන්දුරුක්කන්, තුන් පත් කුරුඳු", "category": "plant" },
  { "word": "තීක්‍ෂණගන්ධකා", "meaning": "මුරුංගා", "category": "plant" },
  { "word": "තීක්‍ෂණගන්ධිනී", "meaning": "කුන්දුරුක්කන්", "category": "plant" },
  { "word": "තීක්‍ෂණගන්ධුලා", "meaning": "පියල් ගස", "category": "plant" },
  { "word": "තීක්‍ෂණගන්ධා", "meaning": "එළසාල්, තම්පලා, අබ, වදකසා, පියාගස්, අදුතලා, සුදුදුරු", "category": "plant" },
  { "word": "තීක්‍ෂණගන්‍ධිනී", "meaning": "වදකසා", "category": "plant" },
  { "word": "තීක්‍ෂණගනකොෂා", "meaning": "සුළුවදකසා", "category": "plant" },
  { "word": "තීක්‍ෂණඡදව", "meaning": "තුඹුරු වාක්‍ෂය", "category": "plant" },
  { "word": "තීක්‍ෂණතණ්ඩූල", "meaning": "නිප්පිලි", "category": "plant" },
  { "word": "තීක්‍ෂණතරැ", "meaning": "මාර ගස", "category": "plant" },
  { "word": "තීක්‍ෂණතෛල", "meaning": "හෙළ අබ, දත් කිරි, දුම්මැල්ල", "category": "treatment" },
  { "word": "තීක්‍ෂණදණ්ඩ", "meaning": "යාවනාල වෘක්‍ෂය", "category": "plant" },
  { "word": "තීක්‍ෂණදුම", "meaning": "ඇටවෙරිය, මෝරගස", "category": "plant" },
  { "word": "තීක්‍ෂණධූම", "meaning": "ඇටවෙරිය", "category": "plant" },
  { "word": "තීක්‍ෂණපතු", "meaning": "පියා ගස, රතු උක් ගස", "category": "plant" },
  { "word": "තීක්‍ෂණපර්ණී", "meaning": "කාමරංගා ගස", "category": "plant" },
  { "word": "තීක්‍ෂණපුෂ්ප", "meaning": "වැටකේ, කුරුඳු පොතු, කරාබු", "category": "plant" },
  { "word": "තීක්‍ෂණප්‍රිය", "meaning": "යව", "category": "plant" },
  { "word": "තීක්‍ෂණඵල", "meaning": "පියා ගස්, තෙප්පල් පල වෘක්‍ෂය", "category": "plant" },
  { "word": "තීක්‍ෂණඵලා", "meaning": "මහ අබ", "category": "plant" },
  { "word": "තීක්‍ෂණමඤ්ජරී", "meaning": "බුලත් වැල", "category": "plant" },
  { "word": "තීක්‍ෂණමුල", "meaning": "මුරුංගා, (මිරිකුළු)", "category": "plant" },
  { "word": "තීක්‍ෂණරස", "meaning": "යවකාරලුණු", "category": "treatment" },
  { "word": "තීක්‍ෂණලෝහ / තීක්‍ෂණලෝහන", "meaning": "වානේ", "category": "treatment" },
  { "word": "තීක්‍ෂණවල්ක", "meaning": "තුඹුරු ගස", "category": "plant" },
  { "word": "තීක්‍ෂණවාක්‍ෂ", "meaning": "පියා ගස", "category": "plant" },
  { "word": "තීක්‍ෂණවෘතා", "meaning": "මෝර ගස", "category": "plant" },
  { "word": "තීක්‍ෂණශුක", "meaning": "යවබුව", "category": "plant" },
  { "word": "තීක්‍ෂණසාර", "meaning": "මී ගස", "category": "plant" },
  { "word": "තීක්‍ෂණසාරා", "meaning": "ඇටවෙරිය", "category": "plant" },
  { "word": "තීක්‍ෂණා", "meaning": "කටුකරෝෂණ, වදකසා, අබ, මුරුංගා, දිය", "category": "plant" },
  { "word": "තීක්‍ෂණාංග", "meaning": "මුරුංගා, (මිරිකුළු)", "category": "plant" },
  { "word": "තීක්‍ෂණාය", "meaning": "වානේ", "category": "treatment" },
  { "word": "තීක්‍ෂරී", "meaning": "ඉකිරි", "category": "plant" },
  { "word": "තීඹරා නෑඹුක්", "meaning": "තියඹරා නෑඹු පත්", "category": "plant" },
  { "word": "තීණ්ඩිපදි", "meaning": "බිමිතල්", "category": "plant" },
  { "word": "තීර", "meaning": "රියම්, වානේ", "category": "treatment" },

  // --- පිටුව 222 ---
  { "word": "තීරක", "meaning": "රියම්", "category": "treatment" },
  { "word": "තීරණ", "meaning": "කටුකරඳ ගස", "category": "plant" },
  { "word": "තීරසම්භව", "meaning": "පුෂ්කර", "category": "plant" },
  { "word": "තිරි (තිහිරි)", "meaning": "රුරංගා, (දෙමට වගී යක්)", "category": "plant" },
  { "word": "තීව්‍ර", "meaning": "කටුකරෝෂණ, අබ, මහ දුරු", "category": "plant" },
  { "word": "තීව්‍රකන්‍ද", "meaning": "කිඩාරම්", "category": "plant" },
  { "word": "තීව්‍රගන්ධා / තීව්‍රගන්ධාන්ඩිකා", "meaning": "යව, අසමෝදගම්", "category": "plant" },
  { "word": "තීව්‍රජ්වාලා", "meaning": "මලිත", "category": "plant" },
  { "word": "තීව්‍රරස", "meaning": "කොළඅරළු, කහිටකලින්ඟි", "category": "plant" },
  { "word": "තීව්‍රශක්ති", "meaning": "රටමිරිස්", "category": "plant" },
  { "word": "තීර්ණිකා", "meaning": "පැපිලිය", "category": "plant" },
  { "word": "තීෂ්‍යා", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "තුංගීසරී", "meaning": "කපු ගස", "category": "plant" },
  { "word": "තුක්පිපිරි / තුක්බුක් / තුකා / තුගා", "meaning": "උණකපුරු, උණමකුළු", "category": "treatment" },
  { "word": "තුකාක්‍ෂීරී", "meaning": "උණමකුළු, උණකපුරු", "category": "treatment" },
  { "word": "තුගී", "meaning": "වේලාගස", "category": "plant" },
  { "word": "තුගුල", "meaning": "බිලු අල", "category": "plant" },
  { "word": "තුංග", "meaning": "පොල්, දෙඹ, නෙළුම් රේණු", "category": "plant" },
  { "word": "තුංගක / තුංගකේශර", "meaning": "දෙඹ ගස", "category": "plant" },
  { "word": "තුංගද්‍රැම / තුංගවෘක්‍ෂ / තුංගසංකුල", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "තුංගසාර", "meaning": "නෙළුම් රේණු", "category": "plant" },
  { "word": "තුංගා", "meaning": "උණමකුළු, උණ කපුරු, සාම ගස", "category": "plant" },
  { "word": "තුංගාක්‍ෂීරී", "meaning": "උණ කපුරු", "category": "treatment" },
  { "word": "තුංගාබ්‍ය", "meaning": "දෙඹ, මහ දෙඹ, සාම රුක", "category": "plant" },
  { "word": "තුගාරි", "meaning": "සුදු කණේරු ගස", "category": "plant" },
  { "word": "තුඞ්ගි", "meaning": "වේලා, රම්මානිස්ස", "category": "plant" },
  { "word": "තුඞ්ගිනී", "meaning": "එල්වලු, එන්සාල්, සිහින් එන්සාල්, සාතාවාරිය", "category": "plant" },
  { "word": "තුච්ඡ / තුච්ඡා", "meaning": "අවිරිය ගස, එන්සාල්", "category": "plant" },
  { "word": "තුච්ඡක", "meaning": "කෙළිඳසාල්", "category": "plant" },
  { "word": "තුච්ඡද්‍රැම", "meaning": "එරබු, නවගිලි එරබු", "category": "plant" },
  { "word": "තුච්ඡපතු", "meaning": "තෝවැලල", "category": "plant" },
  { "word": "තුට්ටරි", "meaning": "අනෝදා ගස", "category": "plant" },
  { "word": "තුටුපානු", "meaning": "බුලත් වැල", "category": "plant" },
  { "word": "තුඩරණ", "meaning": "තම්බොටු (වේ) වැල්", "category": "plant" },
  { "word": "තුඩවැඩියා", "meaning": "(උඩවැඩියා) ගස්වල වැවෙන පිළිල වර්ගයක්", "category": "plant" },
  { "word": "තුඩු", "meaning": "රියම්", "category": "treatment" },
  { "word": "තුණ්ඩ", "meaning": "කපු, කෝවක්කා, කැකිරි", "category": "plant" },
  { "word": "තුණ්ඩකී", "meaning": "කුඹුරු වැල", "category": "plant" },
  { "word": "තුණ්ඩකෙරිකා / තුණ්ඩකෙරි", "meaning": "කපු ගස, කෙම්වැල", "category": "plant" },
  { "word": "තුණ්ඩකෙරී", "meaning": "කෝවක්කා, කැකිරි, උඩැත්ත", "category": "plant" },
  { "word": "තුණ්ඩී", "meaning": "කෝවක්කා, කැකිරි, උඩැත්ත, කපු, රඹුක්, වැළුක්, කිරිහඟුව", "category": "plant" },
  { "word": "තුණ්ඩිකා", "meaning": "කෝවක්කා, උඩැත්ත, ලබුහල්, කපු ගස, බූරැල්ල", "category": "plant" },
  { "word": "තුණ්ඩිකේරි / තුණ්ඩිකේරිකා", "meaning": "කපු, කෝවක්කා", "category": "plant" },
  { "word": "තුණ්ඩිකේරී", "meaning": "කෙම්වැල, කපු ගස", "category": "plant" },
  { "word": "තුණ්ඩිකෝරි", "meaning": "කෝවක්කා, කපු", "category": "plant" },
  { "word": "තුණ්ඩිර", "meaning": "මාරා, මදටිය", "category": "plant" },
  { "word": "තුණ්ඩිරකා", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "තුණ්ඩිල", "meaning": "ගෙදපලා", "category": "plant" },
  { "word": "තුණින්න", "meaning": "පොන්නරු", "category": "plant" },

  // --- පිටුව 223 ---
  { "word": "තුණුක (තුණික) / තුනක", "meaning": "නන්දිවාක්‍ෂය", "category": "plant" },
  { "word": "තුණීර", "meaning": "තණකොළ", "category": "plant" },
  { "word": "තුත්තම", "meaning": "රිදී තුත්තම, පල්මානික්කම්", "category": "treatment" },
  { "word": "තුත්ති ඉනම", "meaning": "කොටිකන් බැවිල", "category": "plant" },
  { "word": "තුත්තුමී", "meaning": "ලක්‍ෂපණී", "category": "plant" },
  { "word": "තුත්‍ථ / තුත්‍ථක", "meaning": "රිදීතුත්‍ථ, මයුරතුත්‍ථ, බේරු, තෙල්බේරු, සිහින් එන්සාල්", "category": "treatment" },
  { "word": "තුත්‍ථා", "meaning": "බේරු, තෙල් බේරු, සිහින් එන්සාල්, අවිරිය", "category": "plant" },
  { "word": "තුත්‍ථාඤ්ජන", "meaning": "මයුරතුත්‍ථ, (පල්මානික්කම්)", "category": "treatment" },
  { "word": "තුන්ථි", "meaning": "බේරු, තෙල්බේරු", "category": "plant" },
  { "word": "තුතුවලසි / තුදුවලෙයි", "meaning": "වැල් තිබ්බටු, කටුවැල් බටු", "category": "plant" },
  { "word": "තුන්කුළු", "meaning": "තිකුළු (ඉඟුරු, ගම්මිරිස්, තිප්පිලි)", "category": "plant" },
  { "word": "තුන්ගඳ", "meaning": "කුරුඳු පොතු, එන්සාල්, කොල්ලම්කොළ යන සුගන්ධ ද්‍රව්‍ය තුණ", "category": "plant" },
  { "word": "තුන්තකාරිකා", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "තුත්තුහ", "meaning": "අබ ගස", "category": "plant" },
  { "word": "තුන්ථ", "meaning": "බේරු, තෙල්බේරු", "category": "plant" },
  { "word": "තුන්දි", "meaning": "මහදඹ, හැලිදඹ, දියදඹ", "category": "plant" },
  { "word": "තුන්දල", "meaning": "මිදෙල්ල", "category": "plant" },
  { "word": "තුන්දිලපලා", "meaning": "තියඹරා, මහකැකිරි, මහගොන්සුතු කැකිරි", "category": "plant" },
  { "word": "තුන්දි", "meaning": "තුන්බෝ අත්තන", "category": "plant" },
  { "word": "තුන්දු ගඳ", "meaning": "එන්සාල්, කුරුඳුපොතු, කොල්ලම්කොළ", "category": "plant" },
  { "word": "තුන්න", "meaning": "කිරිබෝ ගස, නන්දි රුක", "category": "plant" },
  { "word": "තුන්නක", "meaning": "පොන්නරු, නන්දිවාක්‍ෂය", "category": "plant" },
  { "word": "තුන් නිවුල්", "meaning": "රත්නිවුල්, එළනිවුල්, නිල්නිවුල්", "category": "plant" },
  { "word": "තුන්පත්කුරුඳු", "meaning": "පත්‍ර (ඇඟිලි) තුනක් එක පත්‍රයේ තිබෙන කුරුඳු විශේෂය", "category": "plant" },
  {
    "word": "තුම්පත් කුරුඳු",
    "scientific": "Limonia Alata",
    "meaning": "ත්‍රිපර්ණ වරාංගක. මේ වර්ගයේ කොළ වල නැට්ට අඟල් දෙකක් පමණ දිග ය. ඒ නැට්ටේ කෙළවරින් වෙන් වෙන් වශයෙන් බෙදී ගිය කොළ තුන බැගින් ඇත. මෙයින් මැද කොළය විශාල ය. දෙපැත්තේ කොළ දෙක ඊට මඳක් කුඩා ය. ලොකුම කොළ දිග-පළල අඟල් 2 1/2 x 1 ක් පමණ ඇත. මේ වර්ගය හැඩහුරුකමින් පමනාරම් පඳුරකට සමාන ය. අඩි විස්සක් පමණ උසට වැවේ.",
    "category": "plant"
  },

  // --- පිටුව 224 ---
  { "word": "තුන්පල", "meaning": "මේවා වැඩි වශයෙන් වැවී තිබෙන්නේ සිතුල්පව්ව, කරඹගල, අනුරාධපුර වැනි උෂ්ණ කලාපයට අයත් පැරණි රාජධානිවල ය. තුම්පත් කුරුඳු යයි කුරුඳු ගණයෙහි ලා ව්‍යවහාර කළත් හැඩ හුරු කමින් හා සුවඳින් පැඟිරි වර්ගයෙහි ලා ගැනේ. මේ වර්ගයේ ඇට, මුල් සහ පොතු දිව්‍යාංගනාදිය වැනි පැරණි තෙල් වලට ගනිති. ශ්ලේෂම නාශක ඖෂධයක් වශයෙන් ද පාවිච්චි කරති.", "category": "plant" },
  { "word": "තුන්පල", "meaning": "තිපල්", "category": "plant" },
  { "word": "තුම්පාල මරම්", "meaning": "දුම්ගස්", "category": "plant" },
  { "word": "තුන්පුව", "meaning": "ත්‍රස්තාවාලු", "category": "plant" },
  { "word": "තුන්පුමිල", "meaning": "තෙලසවු", "category": "plant" },
  { "word": "තුන්රස්", "meaning": "ත්‍රස්තාවාලු, තුන්රස් මුල්", "category": "plant" },
  { "word": "තුන්ලෝ - ජයගත් කොළ", "meaning": "කංසා", "category": "plant" },
  { "word": "තුන්වග", "meaning": "කරාබු, වසාවාසි, සාදික්කා", "category": "plant" },
  { "word": "තුන්වන්මිවු", "meaning": "තුඹකරවිල", "category": "plant" },
  { "word": "තුන්විඳ සුවඳ", "meaning": "කස්තුරි, අගිල්, කළුවැල්", "category": "plant" },
  { "word": "තුනවු", "meaning": "බුලත්", "category": "plant" },
  { "word": "තුනි", "meaning": "බේරු, අවිරිය", "category": "plant" },
  { "word": "තුනීර", "meaning": "තණකොළ", "category": "plant" },
  { "word": "තුතුකෙසරා", "meaning": "වසාරොද", "category": "plant" },
  { "word": "තුනුඟඹ", "meaning": "ඇටිකුකුළන්", "category": "plant" },
  { "word": "තුම්පෙ", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "තුම්බ / තුම්බා", "meaning": "නෙල්ලි, දියලබු, සුදුලබු, තිත්තලබු", "category": "plant" },
  { "word": "තුම්බක", "meaning": "ලබු", "category": "plant" },
  { "word": "තුම්බන්තකාසි", "meaning": "තුඹ, වැල්තුඹ ගෙඩි", "category": "plant" },
  { "word": "තුම්බරා / තුම්බුරු", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "තුම්බලිකා", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "තුම්බි", "meaning": "දියලබු, තිත්ත ලබු, ලබු", "category": "plant" },
  { "word": "තුම්බිකුක්‍ෂි", "meaning": "තිත්ත ලබු වැල", "category": "plant" },
  { "word": "තුම්බිත්", "meaning": "හොරගස, කුලික වාක්‍ෂය", "category": "plant" },
  { "word": "තුම්බු", "meaning": "දියලබු", "category": "plant" },
  { "word": "තුම්බුක / තුම්බුරී", "meaning": "සැම ගස, කොත්තමල්ලි", "category": "plant" },
  { "word": "තුම්බ්‍යප්", "meaning": "දියලබු", "category": "plant" },
  { "word": "තුම්හ", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "තුමුල", "meaning": "ඉරිවේරිය, බුත් ගස", "category": "plant" },
  { "word": "තුඹ", "meaning": "වැල්තුඹ, ගංතුඹ, ගොන්තුඹ, රියම්. මෙයින් වැල්තුඹ තිත්ත නැති කුඩා ගෙඩි සෑදෙන අල ඇති වර්ගයයි. මෙය අගනා ඖෂධයකි.", "category": "plant" },

  // --- පිටුව 225 (තුඹකරිවිල සම්පූර්ණ විස්තරය) ---
  {
    "word": "තුඹකරිවිල",
    "scientific": "Momordica Cochinchinensis",
    "meaning": "වනගතව වැවෙන කරිවිල වර්ගයන්. තිත්ත කරිවිල, බටු කරිවිල, මල් තුඹ, තුඹ කරිවිල යයි කරිවිල වගී කීපයකි. එයින් තිත්ත කරිවිල තිත්ත සුදු දෙපාටින් යුත් ලොකු කුඩා දෙවර්ගයකි. බටු කරිවිල එළබටු ගෙඩි ප්‍රමාණයෙන් යුත් ඕවිටි භාගය සහිත සිහින් කෙන්දි වැනි නටු වලින් එල්බෙන කුඩා ගෙඩි සෑදෙන වනගත ව වැවෙන වැල් වර්ගයකි. මේ වර්ගයේ ගෙඩි තිත්ත රසයෙන් අඩු ය. මල්තුඹ - තුඹ (කරිවිල) වර්ග දෙක එක ම වර්ගයට අයත් ය. මල් පමණක් හටගන්නා වර්ගයට මල්තුඹ යයි ද, මල් සහ ගෙඩි දෙවගය ම හටගන්නා වර්ගයට තුඹ (කරිවිල) යයි ද වෙන් වශයෙන් ව්‍යවහාර කරණ නමුත් මේ මල් තුඹ - තුඹ කරිවිල දෙවර්ගයේ ම අල-මල්-කොළ හා වැලු ත් එක සමාන ය. වෙනසකට ඇත්තේ එක වර්ගයක මල් පමණක් සෑදීම ත්, අනිත් වර්ගයේ මල් සහ ගෙඩි යන දෙවර්ගය ම සෑදීම ත් පමණකි. මේවායේ ලොකු කිරිබදු අල පමණ විශාල අල තිබේ. නියං කාලයට තණ කැළෑ වල් කොටා ගිනි තැබීමට අනිත් එළබටු, බිංකොහොඹ ආදී පැල වර්ග සමග ම පැලවෙන මේ වැල් ද ඒ හේන් ලැපල් වන විට එල දරා මැරී යයි. මේ වැල් වර්ගය වැඩි වශයෙන් වැවෙන්නේ රත්නපුර දිස්ත්‍රික්කයේ කොළඹගේආර, ඇඹිලිපිටිය, ගල්පාය ආදී වියලි ප්‍රදේශ වල ය. හැඩ හුරුකමින් ගස් තක්කාලි ගෙඩි වලට සමාන ප්‍රමාණයෙන් ඊට මඳක් කුඩා වූ තුඹකරිවිල ගෙඩි තිත්ත මිශ්‍ර කිරි රසයෙන් යුක්ත යි. අනුභව කරණවිට මොලය පිනවන ගතියක් දැනෙයි. අමු ගෙඩි නිල් පාටයි. ඉදුනවිට කහ පාටයි. තුඹ කරිවිල තුන්දොස් සමනය වන විෂ නාශක ඖෂධ යකි. ප්‍රාණජීවය වැනි අගනා තෙල් වර්ග වලට ත්, සාතා-අරිෂ්ට ආදී වෙනත් ඖෂධ යෝග වලට ත් තුඹ කරිවිල අල සහ කොළ යුෂ ත් ඇතුළත් ව තිබේ. සාමාන්‍යයෙන් හැම කරිවිල වර්ගයක ම ස්ථාවර-ජංගම විෂ නාශක බලයක් තිබේ. ඇතැම් පාසානම් වර්ග ඇතුළු වෙන ත් විෂ වගී ශුද්ධකිරීම (විෂ මැරීම) කරිවිල යුෂ වලින් කළ හැක්කේ ද ඒ නිසා ය. තුඹකරිවිල ඉස්ම වරකට පත බාගය බැගින් උදය තුනක් හිස්බඩ පානය කිරීමෙන් අශ්මරී ගල් වැටෙයි.",
    "category": "plant"
  },

  // --- පිටුව 226 ---
  { "word": "තුඹස්මි", "meaning": "තුඹස්වල බඳින මී හෝ තුඹස්වල තිබෙන මී වද වැනි වෙසන්ගේ ගෙවල්", "category": "treatment" },
  { "word": "තුරඟසිපා", "meaning": "අස්ගොදු මුල්", "category": "plant" },
  { "word": "තුරගා / තුරගි", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "තුරගාහ්වා", "meaning": "අමුක්කරා, (අස්ගොදු) ඇපල", "category": "plant" },
  { "word": "තුරඞ්ගක", "meaning": "මහ වැටකොළු", "category": "plant" },
  { "word": "තුරඞ්ගා / තුරඞ්ගගන්ධා", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "තුරඞ්ගම", "meaning": "තිත්ත වැටකොළු", "category": "plant" },
  { "word": "තුරඩගාරිපු", "meaning": "කණේරු ගස", "category": "plant" },
  { "word": "තුරඩගාරි", "meaning": "කණේරු, අලරිය", "category": "plant" },
  { "word": "තුරඩගාහ්ව", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "තුරඬගි / තුරඬබි", "meaning": "අමුක්කරා, මහ බෙබර", "category": "plant" },
  { "word": "තුරීයත", "meaning": "අලරිය, කණේරු", "category": "plant" },
  { "word": "තුරියි", "meaning": "පල්මානික්කම්", "category": "treatment" },
  { "word": "තුරා", "meaning": "ගස්, පක්‍ෂීන්", "category": "plant" },
  { "word": "තුරාවි", "meaning": "ගස", "category": "plant" },
  { "word": "තුරා පතුරු", "meaning": "රඹ (කෙසෙල්) පතුරු", "category": "plant" },
  { "word": "තුරාපා", "meaning": "ගස්වල මුල", "category": "plant" },
  { "word": "තුරාසක", "meaning": "තුරැක්තෙල්", "category": "treatment" },
  { "word": "තුරාසු", "meaning": "පල්මානික්කම් (මයුරතුත්‍ථ)", "category": "treatment" },
  { "word": "තුල්", "meaning": "කිතුල්, කබ", "category": "plant" },
  { "word": "තුල්‍ය", "meaning": "තිබ්බටු", "category": "plant" },
  { "word": "තුල්‍යා / තුල්‍යාවචක", "meaning": "පිච්චමල්", "category": "plant" },
  { "word": "තුල", "meaning": "සුදුරියම්, බ්‍රහ්මදරු, ඉරිවේරිය", "category": "plant" },
  { "word": "තුලදපා", "meaning": "ඉඹුල් ගස", "category": "plant" },
  { "word": "තුලපුංවනම්", "meaning": "දැවිරිය", "category": "plant" },
  { "word": "තුල්‍යසුගන්ධිකා", "meaning": "තික්තතල්ලෙ", "category": "plant" },
  { "word": "තුලසී", "meaning": "තලා", "category": "plant" },
  { "word": "තුලසිදෝෂා", "meaning": "වේලාගස", "category": "plant" },
  { "word": "තුලසිපර්ණි / තුලාසි", "meaning": "තලාකොළ, තලා", "category": "plant" },
  { "word": "තුලා", "meaning": "සියක් පලම", "category": "treatment" },
  { "word": "තුලාක්‍ෂ", "meaning": "රතුමුණු", "category": "plant" },
  { "word": "තුලාවිප්", "meaning": "ඔලිඳඇට", "category": "plant" },
  { "word": "තුලිකා", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "තුලිනි / තුලිප්ලා", "meaning": "ඉඹුල්ගස, වෙලිප්පරිත්ති", "category": "plant" },
  { "word": "තුවංමිටිටි", "meaning": "තුඹකරිවිල, වැල්තුඹ ගෙඩි", "category": "plant" },
  { "word": "තුවටු", "meaning": "නාවි, නමු", "category": "plant" },
  { "word": "තුවර / තුවරිකා", "meaning": "තුවරලා, තෝර, කයිප්, නාපිරිත්ත, රටතෝර", "category": "plant" },
  { "word": "තුවරල", "meaning": "හිඟුරු පියලි, හිත් ඊපා, තණ, කට්ටකුමංජල්", "category": "plant" },
  { "word": "තුවරි (තුවරී)", "meaning": "තිරිඟු, තල, රටතෝර, හෙළ අබ", "category": "plant" },
  { "word": "තුවරිසිඹ", "meaning": "රත්තෝර", "category": "plant" },
  { "word": "තුෂ්‍ය", "meaning": "වැල්පෙනෙල", "category": "plant" },
  { "word": "තුෂ්ටි", "meaning": "සුව දඬු කලත්", "category": "plant" },
  { "word": "තුෂ / තුස", "meaning": "බුව, දහවියා, වී කුඩු", "category": "plant" },
  { "word": "තුෂාරගෙහ / තුසාර / තුසාරකර", "meaning": "කපුරු, තුප්පතු, පිණි(හිම) සීතල", "category": "treatment" },
  { "word": "තුෂාරාම්බු", "meaning": "පිණිවතුර", "category": "treatment" },
  { "word": "තුසවාරි / තුසාම්බු / තුසෝදක", "meaning": "කාඩි වතුර, කාඩි දිය", "category": "treatment" },
  { "word": "තුසි", "meaning": "පලාවගී, වේලා", "category": "plant" },
  { "word": "තුහරි", "meaning": "කිරිඅඟුණ වැල", "category": "plant" },
  { "word": "තුහින / තුහිනාංශු / තුහිනි", "meaning": "කපුරු, සඳුන්", "category": "treatment" },
  { "word": "තුහිනාංශු තෛල", "meaning": "කපුරු තෙල්", "category": "treatment" },

  // --- පිටුව 227 ---
  { "word": "තූණ / තූණික", "meaning": "නන්දි වාක්‍ෂය", "category": "plant" },
  { "word": "තූණී", "meaning": "අවිරිය රුක", "category": "plant" },
  { "word": "තූත(ද) / තූතක", "meaning": "පුවත් ගස, පුලිල ගස", "category": "plant" },
  { "word": "තූද", "meaning": "ඇසතු ගස් වැනි වෙසෙසක්", "category": "plant" },
  { "word": "තූන", "meaning": "හණ ගස, පුවත් ගස, පුලිල ගස", "category": "plant" },
  { "word": "තූබර", "meaning": "රටතෝර", "category": "plant" },
  { "word": "තූය්‍ය", "meaning": "කරඹ ගස", "category": "plant" },
  { "word": "තූරී", "meaning": "එළ අත්තන, සඳුන්", "category": "plant" },
  { "word": "තූල", "meaning": "සුදු රියම්, වලාවැන්න, පුවත්, කපු", "category": "plant" },
  { "word": "තූලක / තූල පිච්චු / තූල ඵලා / තූලවෘක්‍ෂ", "meaning": "හිඹුල් ගස, ඉඹුල් ගස", "category": "plant" },
  { "word": "තූල පුෂ්ප", "meaning": "වලාවැන්න, හිඹුල්", "category": "plant" },
  { "word": "තූලඵල", "meaning": "හිඹුල් ගස, වරා ගස", "category": "plant" },
  { "word": "තූල ශකීර", "meaning": "කපු ඇට", "category": "plant" },
  { "word": "තූලිනී", "meaning": "හිඹුල්", "category": "plant" },
  { "word": "තූලී", "meaning": "රතුකපු, ඇවිරිය, සැවැන්දරා", "category": "plant" },
  { "word": "තූෂණ", "meaning": "හණගස", "category": "plant" },
  { "word": "තෘචවෘක්‍ෂ", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "තෘචූෂණ", "meaning": "ඉඟුරු, ගම්මිරිස්, නිප්පිලි", "category": "treatment" },
  { "word": "තෘප්ත", "meaning": "බදුල්ල, බදුල්ල ගස", "category": "plant" },
  { "word": "තෘට්ඨා / තෘටි", "meaning": "එන්සාල්, සිත් එන්සාල්", "category": "plant" },
  { "word": "තෘණ", "meaning": "තණ, හණගස, රඹුක්, වැළුක්", "category": "plant" },
  { "word": "තෘණක", "meaning": "තණහාල්, හුණගස්", "category": "plant" },
  { "word": "තෘණකණ්ටක", "meaning": "නිරමුල්ලිය", "category": "plant" },
  { "word": "තෘණකුමී", "meaning": "සුදුලබු", "category": "plant" },
  { "word": "තෘණ කේගර / තෘණගෙහර", "meaning": "තෘණකුඩකුම", "category": "plant" },
  { "word": "තෘණකේතකි", "meaning": "උණමකුව, =(තුක්පිචු=හුණමකුළු)", "category": "plant" },
  { "word": "තෘණකේතු / තෘණ ධ්වජ", "meaning": "උණගස, තල්ගස", "category": "plant" },
  { "word": "තෘණ ග්‍රන්ථී", "meaning": "කසාවන් මල් ඇති නීතිග", "category": "plant" },
  { "word": "තෘණගොඩ", "meaning": "කරබෙයිය (කරපිංචා)", "category": "plant" },
  { "word": "තෘණ චර / තෘණවර", "meaning": "ගෝමේද", "category": "treatment" },
  { "word": "තෘණ වාහ / තෘණරූප / තෘණවාහ", "meaning": "කේ, තේකොළ", "category": "plant" },
  { "word": "තෘණ ජලායුකා / තෘණ ජලෞකා", "meaning": "ගොඩකුඹල්ලා", "category": "plant" },
  { "word": "තෘණජීව", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "තෘණද්‍රැම", "meaning": "හිඳිගස්, (යොන් ඉඳි) පොල්, පුවක්, තල, වැටකේ", "category": "plant" },
  { "word": "තෘණධාන්‍ය / තෘණාන්‍ය", "meaning": "උඳු, හාල්, අමු, මෙනේරි", "category": "plant" },
  { "word": "තෘණනිම්බ", "meaning": "බිංකොහොඹ", "category": "plant" },
  { "word": "තෘණපඤ්චමූල", "meaning": "කුශ, වැළුක්, ඊතණ, බට, උක් යන තණ පස් වගේ මුල්", "category": "plant" },
  { "word": "තෘණපුෂ්ප", "meaning": "කොකුම්", "category": "plant" },
  { "word": "තෘණපුෂ්පී", "meaning": "සිඳුරුපුෂ්පී වාක්‍ෂය", "category": "plant" },
  { "word": "තෘණඵල", "meaning": "පොල්", "category": "plant" },
  { "word": "තෘණබිප්", "meaning": "අමුහාල්", "category": "plant" },
  { "word": "තෘණමුසතික", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "තෘණමේරු", "meaning": "රුක්‍ෂාක්‍ෂ වාක්‍ෂය", "category": "plant" },
  { "word": "තෘණරුප්", "meaning": "පොල්, තල්, හුණ, උක්", "category": "plant" },
  { "word": "තෘණරූපහවය / තෘණේහ්පු", "meaning": "තල්ගස", "category": "plant" },
  { "word": "තෘණශීත", "meaning": "දේවතාඩ වාක්‍ෂය", "category": "plant" },
  { "word": "තෘණගීතා", "meaning": "දිය නිප්පිලි", "category": "plant" },

  // --- පිටුව 228 ---
  { "word": "තෘණශොණබිකා", "meaning": "හිත් වැටකේ", "category": "plant" },
  { "word": "තෘණසම්භව", "meaning": "කොකුම්", "category": "plant" },
  { "word": "තෘණසාර", "meaning": "කෙසෙල් ගස", "category": "plant" },
  { "word": "තෘණසුන්‍ය", "meaning": "ඉඳිද, සිනිද්ද, වැටකේ", "category": "plant" },
  { "word": "තෘණසුලා", "meaning": "සිනිද්ද, වතුවැල්, (බාත්වැල්)", "category": "plant" },
  { "word": "තෘණාහ්ව", "meaning": "පොල්", "category": "plant" },
  { "word": "තෘණී", "meaning": "බේරු, තෙල්බේරු", "category": "plant" },
  { "word": "තෘණේක්‍ෂු", "meaning": "බබුස් තණ", "category": "plant" },
  { "word": "තෘතෝදභවා / තෘනොඅබඩ", "meaning": "එන්සාල්, හිත් එන්සාල්", "category": "plant" },
  { "word": "තෘපනා", "meaning": "මිහමෙවන්", "category": "plant" },
  { "word": "තෘපා", "meaning": "බදුල්ලගස", "category": "plant" },
  { "word": "තෘප්තිඝන", "meaning": "සිද්ධිඟුරු, තිපුල්, සිවිය, වලඟසාල්, මුරුවා", "category": "plant" },
  { "word": "තෘඵලා", "meaning": "තිපල්", "category": "plant" },
  { "word": "තෘමාණාස්න", "meaning": "පැපිලිය (පත්පාඩගම්)", "category": "plant" },
  { "word": "තෘෂාවහා", "meaning": "මුවැන්න", "category": "plant" },
  { "word": "තෘෂාඝ / තෘෂායා", "meaning": "සතකුප්ප, (ශතපුෂ්ප)", "category": "plant" },
  { "word": "තෘපිනොතපාර", "meaning": "අගන පර්ණී", "category": "plant" },
  { "word": "තෙකාරැප්", "meaning": "කිකිරිදිය", "category": "plant" },
  { "word": "තෙකුලත්කොඹි", "meaning": "එලවැල්, කයිලවැල්", "category": "plant" },
  { "word": "තෙපෑඋල", "meaning": "තෙප්පල වෘක්‍ෂය", "category": "plant" },
  { "word": "තෙපක", "meaning": "කොකුම්, කටුකරෝෂණ, දේවදාර", "category": "plant" },
  { "word": "තෙප්න", "meaning": "උණගස, මුරුවා, දුදුවැල, මුදුතන, බිහි බට, හුණගස", "category": "plant" },
  { "word": "තෙප්නි", "meaning": "මුරුවා, එළමුරුවා, වදකසා", "category": "plant" },
  { "word": "තෙප්වතී", "meaning": "දිය තිප්පිලි", "category": "plant" },
  { "word": "තෙපස් / තෛපස්", "meaning": "ගිතෙල්", "category": "treatment" },
  { "word": "තෙපාත / තෙපාතක", "meaning": "කුරුඳු, එත්සාල්, කොල්ලම් කොළ යන තුන් වගිය", "category": "plant" },
  { "word": "තෙපාස්වා", "meaning": "තෙප් එල වාක්‍ෂය", "category": "plant" },
  { "word": "තෙප් පතු", "meaning": "කොල්ලම් කොළ", "category": "plant" },
  { "word": "තෙපොවාක්‍ෂ", "meaning": "සිහින්මිදි", "category": "plant" },
  { "word": "තෙතනත්කොටත්", "meaning": "ඉඟිනි ඇට", "category": "plant" },
  { "word": "තෙත්කා", "meaning": "පොල්", "category": "plant" },
  { "word": "තෙත්පානි", "meaning": "මීපැණි", "category": "treatment" },
  { "word": "තෙන්මුලගු", "meaning": "මී ඉටි", "category": "treatment" },
  { "word": "තෙප්පත් පිල්ලු", "meaning": "ඉප්ප්", "category": "plant" },
  { "word": "තෙබු", "meaning": "කෙමුක - (නියඟණයට අයත් විෂ නාසක පැලෑටියකි)", "category": "plant" },
  { "word": "තෙබුස", "meaning": "නෙබුඅල, කිරිහඟුව", "category": "plant" },
  { "word": "තෙම්නල", "meaning": "නෙළුම් අල, ලුණුවිල", "category": "plant" },
  { "word": "තෙම්රිවායු", "meaning": "වාත රෝගයක්", "category": "symptom" },
  { "word": "තෙල්", "meaning": "පස්ගෝරස, ගිතෙල්", "category": "treatment" },
  { "word": "තෙලකානා", "meaning": "අඹගස", "category": "plant" },
  { "word": "තෙලකිරිය", "meaning": "ගොකටු", "category": "plant" },
  { "word": "තෙලපණ්ණිකා", "meaning": "රත්වන් සඳුන්", "category": "plant" },
  { "word": "තෙලඹු", "meaning": "සිඹලි = (ඉඹුල් ගණයට අයත් ගසකි) හෙලඹු, රත්තෙලඹු යයි තෙලඹු දෙවර්ගයකි", "category": "plant" },
  { "word": "තෙලිප්ප්", "meaning": "තෙලිදිය, = තෙල් දිය, (තල්-පොල් කිතුල් මල් වලින් කපාගන්නා පැණිරසැති ජලය)", "category": "treatment" },
  { "word": "තෙලිසප්", "meaning": "නාගයා", "category": "plant" },
  { "word": "තෙලුම්බටු", "meaning": "එලබටු (තැළුම්බටු)", "category": "plant" },
  { "word": "තෙවග = ත්‍රිවගී", "meaning": "කරාබු, වසාවාසි, සාදික්කා යන තුන් වගිය", "category": "plant" },
  { "word": "තෙවිකුම්", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "තෙසුමද", "meaning": "එන්සාල්, කුරුඳු පොතු, කොල්ලම් කොළ", "category": "plant" },

  // --- පිටුව 229 ---
  { "word": "තේංගාපු කිරෙයි", "meaning": "පොල්පලා, පුස්වැන්න", "category": "plant" },
  { "word": "තේංගිත් ඝාරයම්", "meaning": "පොල් අරක්කු", "category": "treatment" },
  { "word": "තේකරැප්", "meaning": "කිකිරිදිය", "category": "plant" },
  { "word": "තේකාකොට්ට", "meaning": "ඉඟිනි ඇට", "category": "plant" },
  {
    "word": "තේජපත්‍ර",
    "meaning": "තමාල පත්‍ර (කොල්ලම් කොළ) වෙනුවට ඉන්දියාවේ ගන්නේ මේ තේජපත්‍ර ය. මේ වගියේ කොළ එක නැට්ටේ දෙක බැගින් පිහිටා ඇත. දිග - පළල අඟල් 3 x 2 ක් ඇති මේ කොළ හැඩහුරු කමින් අවර කොළ වලට සමාන ය.",
    "category": "plant"
  },
  { "word": "තේප්", "meaning": "රම්මානිස්ස, කොකුම්", "category": "plant" },
  { "word": "තේප්ක", "meaning": "දේවදාර, කටුකරෝෂණ, කොකුම්", "category": "plant" },
  { "word": "තේප්න", "meaning": "ඔලිඳ, දුහුදු, බට, මුරුවා, කසා, කිකිරිදිය, මුරුංගා, හුණ ගස්", "category": "plant" },
  { "word": "තේප්නි / තේප්නී", "meaning": "මුරුවා", "category": "plant" },
  { "word": "තේප්ස්", "meaning": "වෙඬුරෙන් උපන් ගිතෙල් ආදිය", "category": "treatment" },
  { "word": "තේප්ස්වතී / තේප්ස්විනී", "meaning": "මුරුවා, ගප්තිප්පිලි, සිවිය, දුඳි", "category": "plant" },
  { "word": "තේපස්විත්", "meaning": "තලගස", "category": "plant" },
  { "word": "තේප්සි", "meaning": "සිවිය", "category": "plant" },
  { "word": "තේජෝමන්", "meaning": "මිදි, සිහින් මිදි", "category": "plant" },
  { "word": "තේජෝවතී", "meaning": "රම්මානිස්ස, දුහුදු, කලගස", "category": "plant" },
  { "word": "තේජෝවාක්‍ෂ", "meaning": "කුඩා සිහින් මිදිගස", "category": "plant" },
  { "word": "තේජෝශ්වා", "meaning": "දුදුවැල, වදකසා", "category": "plant" },
  { "word": "තේන්", "meaning": "මීපැණි, මී", "category": "treatment" },
  { "word": "තේන්තුන්ගි", "meaning": "වැලිකහ ගස", "category": "plant" },
  { "word": "තේන් පානි", "meaning": "මී පැණි", "category": "treatment" },
  { "word": "තේන් මොලුකු", "meaning": "මී ඉටි", "category": "treatment" },
  { "word": "තේනිය", "meaning": "වක්නිය", "category": "plant" },
  { "word": "තේරි", "meaning": "වල් කැප්පෙටියා ගස", "category": "plant" },
  { "word": "තෛකස්", "meaning": "කුප්පමේනිය", "category": "plant" },
  { "word": "තෛප් වල්ලි", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "තෛපසි", "meaning": "ඇත්ගඟුල්", "category": "plant" },
  { "word": "තෛමින", "meaning": "පොන්නරු", "category": "plant" },
  { "word": "තෛමිර", "meaning": "එනම් නෙතු රෝගය", "category": "symptom" },
  { "word": "තෛතරි පේෂ්‍යතිර", "meaning": "දීපෙරලිදිය", "category": "treatment" },
  { "word": "තෛතරිවාල / තෛතරි වේලං", "meaning": "වේලා", "category": "plant" },

  // --- පිටුව 230 ---
  { "word": "තෛල", "meaning": "තෙල්, තල, මනෝසිල, තලතෙල්", "category": "treatment" },
  { "word": "තෛලං", "meaning": "මකුල් ගස", "category": "plant" },
  { "word": "තෛලක", "meaning": "රත්තෙළුම්, රත්බිලු, (රතුමුළු)", "category": "plant" },
  { "word": "තෛලකන්‍ද", "meaning": "තෙල අල", "category": "plant" },
  { "word": "තෛල කාණ්ඩ", "meaning": "නිරමුල්ලිය, ඉකිරි", "category": "plant" },
  { "word": "තෛල නිය්‍යාස", "meaning": "ජවාදි කස්තුරි", "category": "treatment" },
  { "word": "තෛල පණී", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "තෛලපර්ණික / තෛලපර්ණිකා", "meaning": "සඳුන්, සුදු හඳුන්, සිරිවඩු (හොර අරටු) දේවදාර", "category": "plant" },
  { "word": "තෛලපිප්ප්", "meaning": "වල්තලා ගස", "category": "plant" },
  { "word": "තෛල පිණ්ඩිතක", "meaning": "කටුකරඬු", "category": "plant" },
  { "word": "තෛලපීත", "meaning": "පොන්නරු", "category": "plant" },
  { "word": "තෛල ප්‍රභව", "meaning": "තලමල්", "category": "plant" },
  { "word": "තෛල ඵල / තෛලඵලා", "meaning": "තල, බිලු, අඟුණ කර ගස, වැලහුණ, කිරි අඟුණ", "category": "plant" },
  { "word": "තෛලභාවිතී", "meaning": "දෑසමන්", "category": "plant" },
  { "word": "තෛලමක්‍ෂප්", "meaning": "තලතෙල්", "category": "treatment" },
  { "word": "තෛලමාලපා / තෛලවල්ලී", "meaning": "සාතාවාරිය, සිහින් සාතාවාරිය", "category": "plant" },
  { "word": "තෛල වතප්‍රග", "meaning": "පුවක් වෙසෙසක්", "category": "plant" },
  { "word": "තෛලවිප්", "meaning": "බදුල්ල ගස", "category": "plant" },
  { "word": "තෛලසස්‍ය", "meaning": "කිරිබදු, කවෙළු, එල කටරොලු", "category": "plant" },
  { "word": "තෛලසාධන", "meaning": "හකුල්", "category": "plant" },
  { "word": "තෛලාගරා", "meaning": "අගිල් වෙසෙසක්", "category": "plant" },
  { "word": "තෛලාභ", "meaning": "මුහුණමල්", "category": "plant" },
  { "word": "තෛලි", "meaning": "තල", "category": "plant" },
  { "word": "තෛලීක", "meaning": "ලොත් ගස", "category": "plant" },
  { "word": "තොක", "meaning": "පොතු", "category": "plant" },
  { "word": "තොටාසුරිබගි", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "තොට්ටිය", "meaning": "සුදු වෙල්ලන් ගිරිය", "category": "plant" },
  { "word": "තොටමියල්කඩ", "meaning": "තොට පියලි, රද, තොට සෝදන දිය (පැරණි රෙදි වලින් කැපී ඉතිරිවන රෙදි කෑලි (කඩමාළු)", "category": "treatment" },
  { "word": "තොටුලු / තොවිල", "meaning": "තොවිල, සෝන", "category": "plant" },
  { "word": "තොදන / තොදය / තොදු", "meaning": "කටුවෙළඟ, කඩුවෙළඟ", "category": "plant" },
  { "word": "තොම", "meaning": "කුරුඳු පොතු", "category": "plant" },
  { "word": "තොය", "meaning": "ඉරිවේරිය, වතුර", "category": "plant" },
  { "word": "තොයකාම", "meaning": "හොමුවහු", "category": "plant" },
  { "word": "තොයකුම්භ", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "තොයගහී", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "තොයජ", "meaning": "සුවඳහොට", "category": "plant" },
  { "word": "තොයද", "meaning": "ගිතෙල්, කලාදුරු, කඩුවෙළඟ", "category": "treatment" },
  { "word": "තොයදුම", "meaning": "ඉඟිනි ගස", "category": "plant" },
  { "word": "තොයධර / තොයධාර", "meaning": "වම්මුතු, කිඹුල්වැන්න", "category": "plant" },
  { "word": "තොයසි ප්‍රිය", "meaning": "කරාබුනැටි", "category": "plant" },
  { "word": "තොයපර්ණී", "meaning": "කරවිල වැල", "category": "plant" },
  { "word": "තොයපාෂාණ", "meaning": "රිදී තුත්ථ", "category": "treatment" },
  { "word": "තොයපාෂාණප්ඵල", "meaning": "රිදී තුත්තම", "category": "treatment" },
  { "word": "තොය පිපලි", "meaning": "ලියනහලා, කූර රණ, දියතිප්පිලි", "category": "plant" },
  { "word": "තොයපුෂ්ප / තොයපුෂ්පී / තොය පුෂ්පා", "meaning": "පලොල්, පලොල් ගස", "category": "plant" },
  { "word": "තොයප්‍රසාදනී", "meaning": "ඉඟිනි ඇට, ඉඟිනි ගස", "category": "plant" },
  { "word": "තොයඵල / තොය ඵලා", "meaning": "බිලු, නියඹරා, කැකිරි, මහකැකිරි", "category": "plant" }
];