// data_203_210.js - පිටු 203 සිට 210 දක්වා සියලුම වචන
const data_extra_203_210 = [
  // --- පිටුව 203 ---
  { "word": "ජාතිලංග", "meaning": "හිඟු, (හිඟුල්), සාදිලිංගම්", "category": "treatment" },
  { "word": "ජාතිශෂ්‍ය", "meaning": "ලමඟ, සාදික්කා, ජයපාල, නෙරළු අල", "category": "plant" },
  { "word": "ජාතිශුක", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතිසාරා", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතිසුමන", "meaning": "සමන්පිච්ච, (දෑසමන්) යොහොඹු", "category": "plant" },
  { "word": "ජාතිසෝද", "meaning": "ජයපාල", "category": "plant" },
  { "word": "ජාතිහිඹුලු", "meaning": "හිඟුල්", "category": "treatment" },
  { "word": "ජාතී", "meaning": "දෑසමන්, යොහොඹු, සාදික්කා", "category": "plant" },
  { "word": "ජාතීකොෂඵල", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතීපාත", "meaning": "වසාවාසි", "category": "plant" },
  { "word": "ජාතීඵල", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "ජාතීඵලා", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "ජාධුක", "meaning": "පෙරුම්කායම්", "category": "treatment" },
  { "word": "ජාතුඵල", "meaning": "අට්ටික්කා (දිඹුල්)", "category": "plant" },
  { "word": "ජාතුහා", "meaning": "කටුකාල (කටුකාලිය)", "category": "plant" },
  { "word": "ජාපනී", "meaning": "ලබත්ත", "category": "plant" },
  { "word": "ජාපාල", "meaning": "ජයපාල", "category": "plant" },
  { "word": "ජාම්බුනද", "meaning": "දුඹුරත්රන්, අත්තන, නාකෙසුරා", "category": "plant" },
  { "word": "ජාම්භව", "meaning": "දම් (ඔ=ජම්බු)", "category": "plant" },
  { "word": "ජාම්හීර", "meaning": "දෙබම්", "category": "plant" },
  { "word": "ජාමාතෘ", "meaning": "ගප්තිප්පිලි, දුවරැක, සුය්‍යකාන්ත", "category": "plant" },
  { "word": "ජායක", "meaning": "අගිල්, කළුවැල්", "category": "plant" },
  { "word": "ජාරක", "meaning": "කුඹුරුවැල්", "category": "plant" },
  { "word": "ජාරණවිප්", "meaning": "රසදිය දිය කරණ අල වර්ගයක්", "category": "plant" },
  { "word": "ජාරණී", "meaning": "මහදුරු", "category": "plant" },
  { "word": "ජාරණ", "meaning": "මහදුරු", "category": "plant" },
  { "word": "ජාරබා", "meaning": "ඇසල", "category": "plant" },
  { "word": "ජාරබාය පළු", "meaning": "ඇසල කරල්", "category": "plant" },
  { "word": "ජාරි", "meaning": "මෙනේරි නම් ධාන්‍ය වගිය", "category": "plant" },
  { "word": "ජාරිනී", "meaning": "වැටකොළු, දේවදාලිය", "category": "plant" },
  { "word": "ජාලව", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "ජාල", "meaning": "කොළොම් ගස, පළුගස, මල්කාකුල", "category": "plant" },
  { "word": "ජාලක", "meaning": "කුටුම්බිනී වෘක්‍ෂය", "category": "plant" },
  { "word": "ජාලය", "meaning": "පළුගස", "category": "plant" },
  { "word": "ජාලවර්වුරකා", "meaning": "සිනිය ගස් වෙසෙසක්", "category": "plant" },
  { "word": "ජාලි", "meaning": "පතෝල, (දුම්මැල්ල) වැටකොළු, පලොල්, හෙළ පලොල්", "category": "plant" },
  { "word": "ජාලික", "meaning": "මල් කැකුළ, කුඩිමල (මල් පොහොට්ටුව)", "category": "plant" },
  { "word": "ජාලිකා", "meaning": "දියකුඹල්ලා", "category": "plant" },
  { "word": "ජාලිකා වෘක්‍ෂය", "meaning": "කොටදිඹුලාගස", "category": "plant" },
  { "word": "ජාලිකිනී", "meaning": "දිය කුඹල්ලා (දිය පුබාවා)", "category": "plant" },
  { "word": "ජාලිනී", "meaning": "දේවදාලිය, වැටකොළු, නෙල්ලි, මුරුවා, ඇඹුල්පලු, මස්බැද්ද, (වෙලිප්පරිත්ති)", "category": "plant" },
  { "word": "ජාලිම", "meaning": "කොට්ටම්, සුවඳ කොට්ටම්", "category": "plant" },
  { "word": "ජාලිවෘක්‍ෂ", "meaning": "කොටදිඹුලා ගස, උගුරැස්ස ගස", "category": "plant" },
  { "word": "ජාලී", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "ජාවක", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "ජාවසිනී", "meaning": "අවිරිය ගස", "category": "plant" },
  { "word": "ජාෂක", "meaning": "කළුවැල්", "category": "plant" },
  { "word": "ජාහකදුර්‍වනි", "meaning": "දිය කුඹල්ලා", "category": "plant" },
  { "word": "ජිංඟි", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "ජිංඟිනී", "meaning": "වැල්මදට, ඉඟිනි, මහ ඉඟිනි, ගොඩකදුරු", "category": "plant" },
  { "word": "ජිජුකාව", "meaning": "ඔලිඳ, (හුනිද)", "category": "plant" },
  { "word": "ජිඤ්ජුකා", "meaning": "ඔලිඳ, (හුනිද)", "category": "plant" },
  { "word": "ජිතේන්ද්‍රියාහ්ව", "meaning": "කාමවෘද්ධි වෘක්‍ෂය", "category": "plant" },
  { "word": "ජින්තුබිය", "meaning": "හඳුන් ගස", "category": "plant" },
  { "word": "ජිනවර්ණ්‍ය", "meaning": "නිල්පුල් (නිල්මහනෙල්)", "category": "plant" },
  { "word": "ජිම්භී", "meaning": "මුවැන්න", "category": "plant" },
  { "word": "ජිම්භ", "meaning": "තුවරලා", "category": "plant" },

  // --- පිටුව 204 ---
  { "word": "ජිමුත", "meaning": "දේවදාලිය, වම්මුතු, (කලාඳුරු) වැටකොළු", "category": "plant" },
  { "word": "ජිමූතක", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "ජියා", "meaning": "කිරිපලා", "category": "plant" },
  { "word": "ජීරවාමල", "meaning": "කොරාසානි", "category": "plant" },
  { "word": "ජීව", "meaning": "ජීවක, කිරිබදුඅල, රසකිඳ, අමුකහ", "category": "plant" },
  { "word": "ජීවගමබහල", "meaning": "තුවරලා", "category": "plant" },
  { "word": "ජීවුළු", "meaning": "ජූල්, (දිවුල්)", "category": "plant" },
  { "word": "ජීෂ්ණු", "meaning": "කුඹුක්, කෙළිඳ ගස", "category": "plant" },
  { "word": "ජීහ්ම", "meaning": "තුවරලාගස", "category": "plant" },
  { "word": "ජීහ්මග", "meaning": "කුකුරුමුවන්, තුවරලා, සුදුරියම්", "category": "plant" },
  { "word": "ජීහමගලය", "meaning": "කිහිරි ගස", "category": "plant" },
  { "word": "ජීහ්වග", "meaning": "කොතඹුරු (කොත්තමල්ලි)", "category": "plant" },
  { "word": "ජීහ්වාල", "meaning": "අබනගිරිය", "category": "plant" },
  { "word": "ජීහ්වාස්තම්භ", "meaning": "එනම් වාත රෝගයක්", "category": "symptom" },
  { "word": "ජීමූත", "meaning": "දේවදාලිය, වම්මුතු", "category": "plant" },
  { "word": "ජීමූතකා", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "ජීමූතමූල", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ජීර්ණ", "meaning": "දුරු, මහදුරු, කලාඳුරු, ගල්මද, ගල් සෙවෙල්", "category": "plant" },
  { "word": "ජීර්ණදුරු", "meaning": "වෘද්ධදාරලතා, මේ වෙනුවට ලංකාවේ ගිරිකිල්ල (මාබණ්ඩා) වැල් ගනිති", "category": "plant" },
  { "word": "ජීර්ණපත්‍රිකා", "meaning": "වංගපත්‍රී නාම", "category": "plant" },
  { "word": "ජීර්ණපර්ණ", "meaning": "බකිනි, බක්මී, කොළොම් ගස", "category": "plant" },
  { "word": "ජීර්ණබාලුක", "meaning": "කලු වෘද්ධදාරක ලතා, මහදුරු", "category": "plant" },
  { "word": "ජීර්ණම්බුද", "meaning": "ඇත්කලාඳුරු, (මහ වම්මුතු)", "category": "plant" },
  { "word": "ජීර්ණවල්කල", "meaning": "ගිරිනිල්ල, (මාබණ්ඩා)", "category": "plant" },
  { "word": "ජීර්ණෝත්භව", "meaning": "අලකිරිය", "category": "plant" },
  { "word": "ජීය්‍යී", "meaning": "දුරු, සුදු දුරු, (සීන්දුරු)", "category": "plant" },
  { "word": "ජීරලගු", "meaning": "මිරිස්වැල්", "category": "plant" },
  { "word": "ජීර", "meaning": "දුරු, දෙදුරු (සුදු දුරු, කලු දුරු)", "category": "plant" },
  { "word": "ජීරක", "meaning": "දෙදුරු (සුදු දුරු, කලුදුරු)", "category": "plant" },
  { "word": "ජීරණ", "meaning": "සුනු (පෙරුම්කායම්) සුදු දුරු, (සීන්දුරු)", "category": "plant" },
  { "word": "ජීලු", "meaning": "කොරාසානි", "category": "plant" },
  { "word": "ජීව", "meaning": "බත්, ආහාරය, බුක්සරණ, නීතිග, ලුණුමිදෙල්ල", "category": "plant" },
  { "word": "ජීවක", "meaning": "අමුකහ", "category": "plant" },
  { "word": "ජීවකොලිකා", "meaning": "කිරිකවෙළු, (අෂ්ටක වගියේ ඔසුවක්)", "category": "plant" },
  { "word": "ජීවණී", "meaning": "කිරිකවෙළු, පියාගස, දිය, තනකිරි, දඩකලන්, එළකිරි", "category": "plant" },
  { "word": "ජීවත", "meaning": "ගෙද", "category": "plant" },
  { "word": "ජීමතග්‍රවන", "meaning": "ගෙදපලා", "category": "plant" },
  { "word": "ජීවන්ති", "meaning": "රසකිඳ, කිරිබදු, බත්", "category": "plant" },
  { "word": "ජීවද", "meaning": "නීතිග ගස", "category": "plant" },
  { "word": "ජීවදන්තී", "meaning": "සිරස්ස", "category": "plant" },
  { "word": "ජීවදායක", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ජීවදෘෂ්ටි", "meaning": "නීතිග ගස", "category": "plant" },
  { "word": "ජීවනත්‍ය", "meaning": "රත්තම්පලා, තම්පලා", "category": "plant" },
  { "word": "ජීවනත්‍යකා", "meaning": "අරළු, රත්තම්පලා රසකිඳ, පිළිල (ඉටිකෙහෙල්)", "category": "plant" },
  { "word": "ජීවනත්‍යමසක", "meaning": "රත්තම්පලා", "category": "plant" },
  { "word": "ජීවනතිකා", "meaning": "ඒතන්, අරළු, ප්‍රජාවා නීතිග, රසකිඳ, මෑබහඟු, මේ වන්, බෙදුරු", "category": "plant" },
  { "word": "ජීවනතීය", "meaning": "සිරස්ස", "category": "plant" },
  { "word": "ජීවන්තී", "meaning": "වැල්මී, බුලත්, අරළු දුහුදු (දුඳි) රසකිඳ, දිවිපහුරු හිඟුරුපියලි, නීතිග, මේද්‍ර (මේවන් - අෂ්ටක වගියේ බෙහෙතක්) රන්වන් ඉද්ද", "category": "plant" },

  // --- පිටුව 205 ---
  { "word": "ජීවන", "meaning": "ජලය, අමෘතය, තනකිරි", "category": "plant" },
  { "word": "ජීවනා", "meaning": "සුළු දඩකලන්, කුරුඳු", "category": "plant" },
  { "word": "ජීවනාසාත", "meaning": "වච්චනාභි", "category": "plant" },
  { "word": "ජීවනාමා", "meaning": "කිරිපලා, ගැටකොළු", "category": "plant" },
  { "word": "ජීවනාලිනී", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ජීවනී", "meaning": "දිවිපහුරු, ජීවක (අෂ්ටක වගියේ ඔසුවක්)", "category": "plant" },
  { "word": "ජීවනීකා", "meaning": "අරළු, කවෙළු", "category": "plant" },
  { "word": "ජීවනී", "meaning": "බුලත්, කිරිපළු, කිඳි, කිරි පලා, අරළු, මේවන්, අමුකහ, ජීවක", "category": "plant" },
  { "word": "ජීවනීයගණ", "meaning": "අෂ්ට වගිය සහ නීතිග, මුංවැන්න, මස්වැන්න, වැල්මී යන ද්‍රව්‍ය", "category": "plant" },
  { "word": "ජීවනීයා", "meaning": "කිරිකවෙළු, අරළු, කිරි පලා, මුරුවා, ගැටකොළු", "category": "plant" },
  { "word": "ජීවපත්‍රී", "meaning": "දිවිපහුරු", "category": "plant" },
  { "word": "ජීවපුත්‍රක", "meaning": "අගුන (කර) ගස", "category": "plant" },
  { "word": "ජීවපුෂ්පා", "meaning": "මහ නීතිග", "category": "plant" },
  { "word": "ජීවප්‍රියා", "meaning": "අරළු, පිළිල (ඉටිකෙහෙල්)", "category": "plant" },
  { "word": "ජීවපෘෂ්ඨා", "meaning": "නීතිග", "category": "plant" },
  { "word": "ජීවභද්‍රා", "meaning": "කිරිපලා, බුලත්, ගැට කොළු පලා", "category": "plant" },
  { "word": "ජීවලා", "meaning": "නිප්පිලි වෙසෙසක්", "category": "plant" },
  { "word": "ජීවවර්ධනී", "meaning": "කිරිපලා, ගැටකොළු පලා, අරළු", "category": "plant" },
  { "word": "ජීවවල්ලී", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ජීවවෘෂා", "meaning": "දිවිපහුරු, නීතිග", "category": "plant" },
  { "word": "ජීවශුක්ලා", "meaning": "කිරිකවෙළු", "category": "plant" },
  { "word": "ජීවසුමන", "meaning": "වද", "category": "plant" },
  { "word": "ජීවා", "meaning": "වදකසා, කිරිපලා, අරළු", "category": "plant" },
  { "word": "ජීවාලා", "meaning": "සිංහල නිප්පිලි", "category": "plant" },
  { "word": "ජීවිකා", "meaning": "දිවිපහුරු, නීතිග", "category": "plant" },
  { "word": "ජීවිත", "meaning": "නෙරෙවි, (ගොකටු), බත්", "category": "plant" },
  { "word": "ජීවිතා", "meaning": "දියනිප්පිලි", "category": "plant" },
  { "word": "ජීවිනී", "meaning": "කවෙළු", "category": "plant" },
  { "word": "ජීව්‍ය", "meaning": "ජීවක නම් ඔසුව", "category": "plant" },
  { "word": "ජීව්‍යා", "meaning": "අරළු, ගොකටු, තම්පලා පික්මැලි (පික්මල්)", "category": "plant" },
  { "word": "ජුගුප්සිත", "meaning": "සුදු ළූනු", "category": "plant" },
  { "word": "ජුගුග", "meaning": "ගෝනකොළ", "category": "plant" },
  { "word": "ජුගුගාපවෙශි", "meaning": "ගිරිනිල්ල", "category": "plant" },
  { "word": "ජුගුගා", "meaning": "ගිරිනිල්ල", "category": "plant" },
  { "word": "ජුෂ්ටකක", "meaning": "යූෂ", "category": "plant" },
  { "word": "ජූටි", "meaning": "කපුරු වෙසෙසක්", "category": "plant" },
  { "word": "ජූනඃඛ්‍ය", "meaning": "උලූකතෘණ", "category": "plant" },
  { "word": "ජූර්ති", "meaning": "උණරෝගය", "category": "symptom" },
  { "word": "ජූෂ", "meaning": "මුං ආදී කෂාය", "category": "treatment" },
  { "word": "ජූෂණ", "meaning": "මලිත ගස", "category": "plant" },
  { "word": "ජෘමිහිනී", "meaning": "එන්සාල් කොළ", "category": "plant" },
  { "word": "ජෙපාල", "meaning": "ජයපාල", "category": "plant" },
  { "word": "ජෙපාලක", "meaning": "ඉරිවේරිය", "category": "plant" },
  { "word": "ජෙපොමාලක", "meaning": "කොසඹ, මහ කොසඹ", "category": "plant" },
  { "word": "ජෙෂී", "meaning": "වැල්මී", "category": "plant" },
  { "word": "ජෛත්‍ර", "meaning": "පාරද (රසදිය), ඖෂධය", "category": "treatment" },
  { "word": "ජෛත්‍රී", "meaning": "මිදි, මිදි ගස, නීතිග, සාදික්කා", "category": "plant" },
  { "word": "ජෛපාල", "meaning": "ජයපාල ගස", "category": "plant" },
  { "word": "ජෛවාතෘකා", "meaning": "කපුරු", "category": "plant" },
  { "word": "ජෙෂ්‍යස් තොයාමල", "meaning": "කාඩි", "category": "treatment" },
  { "word": "ජෙෂ්‍යස්බලා", "meaning": "මහබැබිල", "category": "plant" },
  { "word": "ජෙෂ්‍යෂ්ඨා", "meaning": "කෙසෙල් ගස", "category": "plant" },
  { "word": "ජ්‍යෙෂ්ඨිමධු", "meaning": "වැල්මී", "category": "plant" },

  // --- පිටුව 206 ---
  { "word": "ජ්‍යොත්ස්‍නා", "meaning": "පතෝල, (දුම්මැල්ල)", "category": "plant" },
  { "word": "ජ්‍යොත්ස්‍නී", "meaning": "තියත්ත වැටකොළු", "category": "plant" },
  { "word": "ජ්‍යොතසනාවෘක්‍ෂ", "meaning": "ජරඟ (පහන් ගස)", "category": "plant" },
  { "word": "ජ්‍යොතස්නී", "meaning": "පතෝල, (දුම්මැල්ල)", "category": "plant" },
  { "word": "ජ්‍යොතස්තිකා", "meaning": "දුම්මැල්ල, රණා ලිය", "category": "plant" },
  { "word": "ජ්‍යොතස්නී", "meaning": "දුම්මැල්ල, (පතෝල)", "category": "plant" },
  { "word": "ජ්‍යොතිඃසෝම", "meaning": "රත්හඳුන්", "category": "plant" },
  { "word": "ජ්‍යොතිලතා", "meaning": "දුදුදුවැල", "category": "plant" },
  { "word": "ජ්‍යොතිෂ්ක", "meaning": "මිදි, තිඹුල් ගස, උළුවා හාල්", "category": "plant" },
  { "word": "ජ්‍යොතිෂ්මතී", "meaning": "වැල්පෙනෙල, කිඳි", "category": "plant" },
  { "word": "ජ්‍යොතිස්", "meaning": "උළුවා ගස, නිටෝල්, රත්හඳුන්", "category": "plant" },
  { "word": "ජ්‍යොතී", "meaning": "රත්හඳුන්", "category": "plant" },
  { "word": "ජ්‍යොගක", "meaning": "අගිල්, කළු අගිල්, පෙරුම්කායම්", "category": "plant" },
  { "word": "ජ්‍යොගල", "meaning": "පෙරුම්කායම්", "category": "treatment" },
  { "word": "ජ්‍යොධිනී", "meaning": "කසාවන් දේවදාලිය", "category": "plant" },
  { "word": "ජ්‍යොතනපත්‍රිකා", "meaning": "උගුරස්ස, කලු වෙලඟ", "category": "plant" },
  { "word": "ජ්‍යොතනපර්ණිකා", "meaning": "උගුරස්ස", "category": "plant" },
  { "word": "ජ්‍යොති", "meaning": "රත්නිඹුල්", "category": "plant" },
  { "word": "ජ්‍යොතිපති", "meaning": "ළිඳ", "category": "plant" },
  { "word": "ජ්‍යොතිරූපා", "meaning": "දුදුදුවැල්=දුහුදු, =දුඳි", "category": "plant" },
  { "word": "ජ්‍යොතිෂණ", "meaning": "මහමිදි", "category": "plant" },
  { "word": "ජ්‍යොතිෂ්මත්", "meaning": "රත්නිඹුල්", "category": "plant" },
  { "word": "ජ්‍යොතිෂ", "meaning": "උළුවා, උළුවාවැල්", "category": "plant" },
  { "word": "ජ්‍යොතිෂ්‍යා", "meaning": "මහමිදි", "category": "plant" },
  { "word": "ජ්‍යොතිස්ක", "meaning": "ළිඳ, රත්නිඹුල්", "category": "plant" },
  { "word": "ජ්‍යොතිස්මතී", "meaning": "මුරුවා, දුඳි", "category": "plant" },
  { "word": "ජ්‍යොතිස්මතිලතා", "meaning": "දුඳි, දුදුදුවැල්", "category": "plant" },
  { "word": "ජ්‍යොදති", "meaning": "නිබිඛටු, නිල්බටු", "category": "plant" },
  { "word": "ජ්‍යොසමගලය", "meaning": "කළුකිහිරි, කිහිරි", "category": "plant" },
  { "word": "ජ්වරඝන", "meaning": "වැල්මදට, පැපිලිය, රසකිඳ, තම්පලා, නිල්තම්පලා", "category": "plant" },
  { "word": "ජ්වරඝනී", "meaning": "සේපාලිකා, තලාගස, පැපිලිය, රසකිඳ, වැල්මදට", "category": "plant" },
  { "word": "ජ්වරජිත්", "meaning": "පත්පාඩගම් (පැපිලිය)", "category": "plant" },
  { "word": "ජ්වරනාශනී", "meaning": "පත්පාඩගම්, රසකිඳ, වැල්මදට", "category": "plant" },
  { "word": "ජ්වරවිනාශනී", "meaning": "කිඳි, රසකිඳ", "category": "plant" },
  { "word": "ජ්වරහනත්‍රී", "meaning": "රසකිඳ, වැල්මදට", "category": "plant" },
  { "word": "ජ්වරහර", "meaning": "කටුවැල්බටු, කිඳි, මොනර කුඩුම්බිය, (දුටුසතුටු)", "category": "plant" },
  { "word": "ජ්වරාහරා", "meaning": "කටුවැල්බටු, දුටුසතුටු, (මොනරකුඩුම්බිය) ගොඩ මානෙල්, රසකිඳ", "category": "plant" },
  { "word": "ජ්වරාංඝා", "meaning": "මහදත්ත", "category": "plant" },
  { "word": "ජ්වරාංඝී", "meaning": "මහදත්ත", "category": "plant" },
  { "word": "ජ්වරාන්තක", "meaning": "උණරෝගය", "category": "symptom" },
  { "word": "ජ්වරාන්තිසාර", "meaning": "උණෙන් යුතු අතිසාරය", "category": "symptom" },
  { "word": "ජ්වරාපහ", "meaning": "ඇසල, දුම්මැල්ල (පතෝල), වැල්මදට, කිරාත, (බිංකොසඹ)", "category": "plant" },
  { "word": "ජ්වරාපහා", "meaning": "ඉඟුරු, බෙලි", "category": "plant" },
  { "word": "ජ්වරාරි", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ජ්වල", "meaning": "සිහින්දුරු, (සුදුදුරු) සුදු රියම්", "category": "plant" },
  { "word": "ජ්වලත්ප්‍රභා", "meaning": "කළුඅබ", "category": "plant" },
  { "word": "ජ්වලන", "meaning": "රත්නිඹුල්, සිහින් මිදි, මහමිදි", "category": "plant" },
  { "word": "ජ්වලනී", "meaning": "මුරුවාවැල", "category": "plant" },
  { "word": "ජ්වාලා", "meaning": "මසිලගස, නිවුල්ගස", "category": "plant" },
  { "word": "ජ්වාලාජිහ්ව", "meaning": "මසිලගස, නිවුල්ගස, ගින්න", "category": "plant" },
  { "word": "ජ්වාලාමුඛී", "meaning": "සූර්යකාන්ත ගස", "category": "plant" },
  { "word": "ජ්වාලි", "meaning": "රත්නිඹුල්", "category": "plant" },
  { "word": "ජ්‍රාවතී", "meaning": "අක්මැල්ල", "category": "plant" },

  // --- පිටුව 207 ---
  { "word": "ඣජ්ජ්‍ය", "meaning": "මාබණ්ඩා (ගිරිනිල්ල)", "category": "plant" },
  { "word": "ඣජ්ජරී", "meaning": "ඉනිල කොළ", "category": "plant" },
  { "word": "ඣංකාරක", "meaning": "ගිරිනිල්ල", "category": "plant" },
  { "word": "ඣටා", "meaning": "පිටවක්කා = (බිම්නෙල්ලි=නවතාළිලිය)", "category": "plant" },
  { "word": "ඣටානාභී", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "ඣටාමලා", "meaning": "පිටවක්කා, (බිම්නෙල්ලි=නවතාළිලිය)", "category": "plant" },
  { "word": "ඣරගී", "meaning": "අලකිරිය, කවුඩු උඩැත්ත, උඩැත්ත", "category": "plant" },
  { "word": "ඣලෂ", "meaning": "සකුරු, සීනි", "category": "plant" },
  { "word": "ඣලි", "meaning": "පුවක්", "category": "plant" },
  { "word": "ඣවක", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "ඣෂ", "meaning": "ගස්කැලිය, සිරිවැඩි බැබිල", "category": "plant" },
  { "word": "ඣෂකෙතු", "meaning": "බිම්නෙල්ලි, (පිටවක්කා) බෝලිද්ද", "category": "plant" },
  { "word": "ඣෂා", "meaning": "සිරිවැඩි බැබිල, මල් සුදු බැබිල, හෙළ බටු, ගස් කැලිය", "category": "plant" },
  { "word": "ඣාෂිකාත", "meaning": "කාරම් වෙසෙසක්", "category": "treatment" },
  { "word": "ඣාට", "meaning": "තෙලඹු ගස", "category": "plant" },
  { "word": "ඣාටල", "meaning": "තෙලඹු ගස, පලොල් ගස", "category": "plant" },
  { "word": "ඣාටාමලා", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "ඣාටිකා", "meaning": "දෑසමන්, පිටවක්කා", "category": "plant" },
  { "word": "ඣාටි", "meaning": "දෑසමන්, පිටවක්කා", "category": "plant" },
  { "word": "ඣාමල", "meaning": "පලොල්, තෙලඹු, ගොකටු", "category": "plant" },
  { "word": "ඣාවු", "meaning": "නාවා ගස", "category": "plant" },
  { "word": "ඣාවුක", "meaning": "පීවුල නොහොත් මිදෙල්ල නාවා ගස", "category": "plant" },
  { "word": "ඣාවුකා", "meaning": "නාවා ගස", "category": "plant" },
  { "word": "ඣිංඝා", "meaning": "දුම්මැල්ල, (පතෝල)", "category": "plant" },
  { "word": "ඣිංඝිනී", "meaning": "දියමින්ත, වැල්මදට", "category": "plant" },
  { "word": "ඣික්ජිණි", "meaning": "යාපුර, තෙඹු, ඉඟිනි", "category": "plant" },
  { "word": "ඣිණ්ඩිඛා", "meaning": "රන්වන් කටුකරඬු, ගිරිනිල්ල, (මාබණ්ඩා), බේරු, හෙල්බේරු, නැටවි, ගැබිනැටවි, මෙනේරි", "category": "plant" },
  { "word": "ඣින්තුහිය", "meaning": "හඳුන්", "category": "plant" },
  { "word": "ඣිම්බා", "meaning": "නවැඟිලිය (එරබු)", "category": "plant" },
  { "word": "ඣිල්ලි", "meaning": "කුර, මහ කුරපලා", "category": "plant" },
  { "word": "ඣුලි", "meaning": "පුවක් වෙසෙසක්", "category": "plant" },
  { "word": "ඣොබ", "meaning": "පුවක් වෙසෙසක්", "category": "plant" },
  { "word": "ටකකදෙහිය", "meaning": "තම්පලා වෙසෙසක්", "category": "plant" },
  { "word": "ටගර", "meaning": "පුෂ්කර", "category": "plant" },
  { "word": "ටංකා", "meaning": "මහ දඹ, පුෂ්කර", "category": "plant" },
  { "word": "ටංකානල", "meaning": "අඹගස", "category": "plant" },
  { "word": "ටංකානක", "meaning": "බූනමදුරු වෘක්‍ෂය", "category": "plant" },
  { "word": "ටංඟන", "meaning": "පුෂ්කර", "category": "plant" },
  { "word": "ටංඟිනී", "meaning": "දියමින්තවැළ", "category": "plant" },
  { "word": "ටණ්ඩුකා", "meaning": "කසාවන් ලොත්", "category": "plant" },
  { "word": "ටන්කණ", "meaning": "පුෂ්කර", "category": "plant" },
  { "word": "ටන්කණක්‍ෂාර", "meaning": "සුස්කර, (පුෂ්කර)", "category": "treatment" },
  { "word": "ටපි", "meaning": "පලොල් ගස", "category": "plant" },
  { "word": "ටම්පාටලි", "meaning": "පලොල්", "category": "plant" },
  { "word": "ටහඬ", "meaning": "කබ", "category": "plant" },
  { "word": "ටාංකා", "meaning": "නිල්වන් ගිවුළු", "category": "plant" },
  { "word": "ටාංකාමාඨවිකා", "meaning": "නිල්වන් ගිවුළු වලින් කළ මද්‍ය වෙසෙසක්", "category": "treatment" },
  { "word": "ටිඟහොල්ගර", "meaning": "තුංගවන්තක නම් ගස", "category": "plant" },
  { "word": "ටිඟොල්", "meaning": "නිබොල් (කටු සහිත ගස් වගියක්)", "category": "plant" },
  { "word": "ටිංහිතක", "meaning": "තොවිල ගස, කසාවන් ලොත්", "category": "plant" },
  { "word": "ටිංතිනිකා", "meaning": "සියඹලා, (සිනිඹලා), දියමහරි", "category": "plant" },
  { "word": "ටිඹි", "meaning": "ගොම්පිඹ", "category": "plant" },

  // --- පිටුව 208 ---
  { "word": "ටුන්ටුක", "meaning": "තොවිල", "category": "plant" },
  { "word": "ටුන්ටුකා", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "ටුන්ඩුක", "meaning": "තොවිල, බහු (දෙල්)", "category": "plant" },
  { "word": "ටුනාකා", "meaning": "බිමිතල්", "category": "plant" },
  { "word": "ටෙනුක", "meaning": "තොවිල ගස", "category": "plant" },
  { "word": "ටොටාපල", "meaning": "මීගස", "category": "plant" },
  { "word": "ඩය", "meaning": "(දඟදිය) ඩගදිය", "category": "plant" },
  { "word": "ඩහඬු", "meaning": "ගස් වගියක් (දෙල්ගස)", "category": "plant" },
  { "word": "ඩහු", "meaning": "කොස්ගොන්න, දෙල්", "category": "plant" },
  { "word": "ඩාලිම", "meaning": "දෙළුම් ගස", "category": "plant" },
  { "word": "ඩිණ්ඩි (ක)", "meaning": "රන් එරබු", "category": "plant" },
  { "word": "ඩිණ්ඩිම", "meaning": "කරඳ, කරඹ, කිරලගස", "category": "plant" },
  { "word": "ඩිණ්ඩීර", "meaning": "මුහුදුපෙණ", "category": "treatment" },
  { "word": "ඩිම්බ", "meaning": "එරබුගස, බීජය", "category": "plant" },
  { "word": "ඩිම්බිකා", "meaning": "තොවිල ගස", "category": "plant" },
  { "word": "ඩුම්බර", "meaning": "කොටදිඹුලා", "category": "plant" },
  { "word": "ඩුම්බරපර්ණී", "meaning": "දෑත්ත ගස", "category": "plant" },
  { "word": "ඩෙබර", "meaning": "මසන්", "category": "plant" },
  { "word": "ඩේලා", "meaning": "බේරු, තෙල්බේරු, නැටවි, ගැබිනැටවි", "category": "plant" },
  { "word": "ඩොඩි", "meaning": "නීතිග", "category": "plant" },
  { "word": "ඩොරිබි", "meaning": "වම්බොටු", "category": "plant" },
  { "word": "ඩොනෝ", "meaning": "දෙකා", "category": "plant" },
  { "word": "ඩෝලා", "meaning": "බේරු", "category": "plant" },
  { "word": "ඩෝලාඵල", "meaning": "මීගස්වල ගෙඩි", "category": "plant" },
  { "word": "ඩෝලායන්ත්‍ර", "meaning": "ඩෝලායන්ත්‍රය, කඩපිම්ම", "category": "treatment" },
  { "word": "ඪංකාණ", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "ඪිණ්ඩිණිකා", "meaning": "දියමිදෙල්ල", "category": "plant" },
  { "word": "තකත්‍රා", "meaning": "මෝරු", "category": "treatment" },
  { "word": "තකකටපිනා", "meaning": "සමදරා, මසන්", "category": "plant" },
  { "word": "තකකාලි", "meaning": "කළු කැම්මේරිය", "category": "plant" },
  { "word": "තකකාරි", "meaning": "නීතිග", "category": "plant" },
  { "word": "තකකාලෙ", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "තකෙකාල", "meaning": "තකුල් (කපුකිනිස්ස)", "category": "plant" },
  { "word": "තක්‍ර", "meaning": "මෝරු, පැපිලිය", "category": "treatment" },
  { "word": "තක්‍රප්", "meaning": "ගෝශී සඳුන්", "category": "plant" },
  { "word": "තක්‍රප්තමන්", "meaning": "දිකිරි", "category": "treatment" },
  { "word": "තක්‍රහින්", "meaning": "දිවුළු ගස", "category": "plant" },
  { "word": "තක්‍රුවාමන", "meaning": "නාරංගස", "category": "plant" },
  { "word": "තක්‍රාහ්ව", "meaning": "කාන්දම්", "category": "treatment" },
  { "word": "තක්‍ෂ", "meaning": "ගන්ධක, ගෙන්දගම්", "category": "treatment" },
  { "word": "තක්‍ෂං", "meaning": "කරටියෙන් නික්මෙන ලාකඩ", "category": "treatment" },
  { "word": "තක්‍ෂපර්ණී", "meaning": "කොළ බිඳ ගන්නා ලාකඩ", "category": "treatment" },
  { "word": "තක්‍ෂපතතිං", "meaning": "කොළ වලින් නික්මෙන ලාකඩ", "category": "treatment" },
  { "word": "තක්‍ෂරෙසි", "meaning": "තෝර", "category": "plant" },
  { "word": "තකුල්", "meaning": "කපුකිනිස්ස, (තකුල්) ලිය කස්තුරි, කළුවැල්", "category": "plant" },
  { "word": "තකුළු", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "තගපත්‍රී", "meaning": "කෙසෙල්", "category": "plant" },
  { "word": "තගර", "meaning": "තුවරලා, කුරුඳු, කුකුරු මුවන්, තෝර, ගුගුල්", "category": "plant" },
  { "word": "තගරබගක", "meaning": "කුරුඳු, වසාවාසි", "category": "plant" },
  { "word": "තගරපත්‍රී", "meaning": "කෙසෙල්", "category": "plant" },
  { "word": "තගරපාදික", "meaning": "වතුසුද්ද", "category": "plant" },
  { "word": "තගරිපාදි", "meaning": "තුවරලා ගස", "category": "plant" },
  { "word": "තගරා", "meaning": "තුවරලා", "category": "plant" },
  { "word": "තචසාර", "meaning": "හුණ", "category": "plant" },
  { "word": "තජ්වී", "meaning": "හිඟුපත් තණ", "category": "plant" },

  // --- පිටුව 209 ---
  { "word": "තට", "meaning": "හිරියල්, සප්සඳ, ඔලිඳවැළ", "category": "plant" },
  { "word": "තටං", "meaning": "සප්සඳ", "category": "plant" },
  { "word": "තටාකන්", "meaning": "දියසෙවෙල්", "category": "plant" },
  { "word": "තටාකන්‍ව", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "තටාග", "meaning": "සෙවෙල්", "category": "plant" },
  { "word": "තඩාග", "meaning": "සෙවෙල්, දියපරඬලා", "category": "plant" },
  { "word": "තඬිතන්", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "තඬුලය", "meaning": "හාල්", "category": "plant" },
  { "word": "තණ්ඩබ්‍ය", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "තණ්ඩී", "meaning": "ජූල්", "category": "plant" },
  { "word": "තණ්ඩුරින", "meaning": "හාල්පානු දිය", "category": "treatment" },
  { "word": "තණ්ඩුල", "meaning": "රත්තම්පලා, සුන්සාල්, වලඟසාල්, අඩඇට දසයක බර", "category": "plant" },
  { "word": "තණ්ඩුලක්‍ෂාලින", "meaning": "සහල් දෙවුත් දිය", "category": "treatment" },
  { "word": "තණ්ඩුලබණඩක", "meaning": "හාල්කුඩු, සුන්සාල්", "category": "plant" },
  { "word": "තණ්ඩුලභාවන", "meaning": "හාල්පානු දිය", "category": "treatment" },
  { "word": "තණ්ඩුලනාමන්", "meaning": "සුළුකුර", "category": "plant" },
  { "word": "තණ්ඩුලපුෂ්ඨ", "meaning": "බැදිසාල්", "category": "plant" },
  { "word": "තණ්ඩුලවාරි", "meaning": "සහල්පානු දිය", "category": "treatment" },
  { "word": "තණ්ඩුලා", "meaning": "මහ නිදිකුම්බා, වලඟසාල්, සුළුකුර", "category": "plant" },
  { "word": "තණ්ඩුලාම්බු", "meaning": "හාල්පානු දිය", "category": "treatment" },
  { "word": "තණ්ඩුලිවිප්", "meaning": "වලඟසාල්, සුළුකුර", "category": "plant" },
  { "word": "තණ්ඩුලිය", "meaning": "වලඟසාල්, සුළුකුර, වල්තම්පලා, කූරතම්පලා", "category": "plant" },
  { "word": "තණ්ඩුලියක", "meaning": "වලඟසාල්, සුළුකුර පලා", "category": "plant" },
  { "word": "තණ්ඩුලියදල", "meaning": "සුළුකුර", "category": "plant" },
  { "word": "තණ්ඩුලු", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "තණ්ඩුලෙය්‍යා", "meaning": "සුළුකුර", "category": "plant" },
  { "word": "තණ්ඩුලෙර", "meaning": "සුළුකුර", "category": "plant" },
  { "word": "තණ්ඩුලෝද", "meaning": "සහල්පානු දිය", "category": "treatment" },
  { "word": "තතපස්මුල් ගණය", "meaning": "ඉරවක්, වැටකේ, රතණ, රණහුණ, උක් යන මේ ගණය පිත් මුත්‍ර කෘච්ඡ්‍රය නසා මූත්‍ර වස්තිය සුද්ධ කරන්නේය.", "category": "treatment" },
  { "word": "තණරුද", "meaning": "තල්", "category": "plant" },
  { "word": "තණසාර", "meaning": "හණ", "category": "plant" },
  { "word": "තත්කාරි", "meaning": "ගොඩමෙනේරිය", "category": "plant" },
  { "word": "තත්පත්ත්‍රී", "meaning": "කෙසෙල් ගස, හිඟුපත් තණ", "category": "plant" },
  { "word": "තත්පද", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "තත්ඵල", "meaning": "බෙබර, නිප්පිලි, බිලු, මුරුංගා, හිඟුරුපියලි, තොරඬුටි, කොට්ටම්", "category": "plant" },
  { "word": "තත්කානි", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තත්කසිකොල්ලි", "meaning": "ගනාමූරු අල", "category": "plant" },
  { "word": "තත්නී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තත්තිකා", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "තත්තිර් විට්ටංකිලාග්‍ර", "meaning": "සාතාවාරිය අල", "category": "plant" },
  { "word": "තත්තිරි විප්පා", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "තත්තුකී", "meaning": "එල අබ", "category": "plant" },
  { "word": "තත්තුතී", "meaning": "අමුනු (බෙය්‍ය අමුනු=උගුරැස්ස)", "category": "plant" },
  { "word": "තත්තුතර්‍යාඝ", "meaning": "හල්ගස", "category": "plant" },
  { "word": "තත්තුහ", "meaning": "අබ", "category": "plant" },
  { "word": "තත්තුරා", "meaning": "තෙළුම් අල", "category": "plant" },
  { "word": "තත්තුල", "meaning": "සහල්, වලඟසාල්", "category": "plant" },
  { "word": "තත්තු විග්‍රහ", "meaning": "කෙසෙල්", "category": "plant" },
  { "word": "තත්තුසාර", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "තත්ත්‍රී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තත්ත්‍රිකා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තත්ත්‍රෝදනවා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තත්ට්ල", "meaning": "හිඟුරුපියලි, තිප්පිලි", "category": "plant" },
  { "word": "තත්ද්‍රි", "meaning": "පතහඬුව", "category": "plant" },
  { "word": "තත්වබගි", "meaning": "ඇම්බරැල්ල", "category": "plant" },
  { "word": "තත්වි", "meaning": "ශාලිපර්ණී, ප්‍රශ්නිපර්ණී", "category": "plant" },
  { "word": "තත්වි", "meaning": "පුස්වැන්න, හිඟු", "category": "plant" },
  { "word": "තත්වෙසි", "meaning": "පත් තණ, (පත්‍ර‍ා හිඩුව)", "category": "plant" },
  { "word": "තනදදු", "meaning": "ලබු ගෙඩිය", "category": "plant" },
  { "word": "තනපා", "meaning": "කිරි", "category": "treatment" },

  // --- පිටුව 210 ---
  { "word": "තනය", "meaning": "දෙම්මපල, ලුබුවැල, ධාන්‍ය වගියක් (තණ)", "category": "plant" },
  { "word": "තනයා", "meaning": "කළුතලා, පුස්වැන්න, කෝමාරිකා", "category": "plant" },
  { "word": "තතරද", "meaning": "තල්ගස", "category": "plant" },
  { "word": "තතිවාල්ලේ පෙරුමාල්", "meaning": "වැල්පෙනෙල", "category": "plant" },
  { "word": "තනුක්‍ෂීර", "meaning": "ඇම්බරැල්ල ගස", "category": "plant" },
  { "word": "තනුක", "meaning": "කුරුඳුපොතු, බුළු ගස, මසිල මල්", "category": "plant" },
  { "word": "තනුවෘක්‍ෂ", "meaning": "සිනිය ගස", "category": "plant" },
  { "word": "තනුත්‍යක්", "meaning": "මිදි", "category": "plant" },
  { "word": "තනුත්‍වචා", "meaning": "සිහින්මිදි", "category": "plant" },
  { "word": "තනුච්‍රා", "meaning": "සිහින්මිදි, මිදි", "category": "plant" },
  { "word": "තනුපත්‍ර", "meaning": "වැලහුණ", "category": "plant" },
  { "word": "තනුප්‍රභ", "meaning": "ගිතෙල්", "category": "treatment" },
  { "word": "තනුපාහ් (දි)", "meaning": "නිඹුල් ගස, ගිතෙල්", "category": "plant" },
  { "word": "තනුරස", "meaning": "බඟදිය", "category": "treatment" },
  { "word": "තනුවිසෝධන්", "meaning": "බේරු, තෙල් බේරු, නැටවි", "category": "plant" },
  { "word": "තප්තකාඤ්චන", "meaning": "රත්රන්", "category": "treatment" },
  { "word": "තප්තලෝමය", "meaning": "කසීස්", "category": "treatment" },
  { "word": "තප්ත වල්ලීර", "meaning": "වැල්ලීරා මස්", "category": "treatment" },
  { "word": "තපන", "meaning": "මිදි, බදුල්ල, වරාගස", "category": "plant" },
  { "word": "තපනක", "meaning": "හල් වෙසෙසක්", "category": "plant" },
  { "word": "තපනච්ඡද", "meaning": "දමනක රුක", "category": "plant" },
  { "word": "තපන තනයා", "meaning": "සෑගස, ලෝලුගස", "category": "plant" },
  { "word": "තපනා", "meaning": "සිහින් මිදි", "category": "plant" },
  { "word": "තපනී", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "තපනීය", "meaning": "රත්රන්, රිදී, අත්තන ගස", "category": "plant" },
  { "word": "තපස්වී", "meaning": "මුරුවා, මුඛමහණ, දමනක වෘක්‍ෂය", "category": "plant" },
  { "word": "තපස්විනී", "meaning": "කටුකරෝෂණ, ජටාමාංශ, වෙල්මුබ (මුඛමහණ)", "category": "plant" },
  { "word": "තපස්විපත්‍ර", "meaning": "දමනක වෘක්‍ෂය", "category": "plant" },
  { "word": "තපස්වී මුල්", "meaning": "දමනක වෘක්‍ෂයේ මුල්", "category": "plant" },
  { "word": "තපසියා", "meaning": "වෙල්මුබ (මුඛමහණ)", "category": "plant" },
  { "word": "තපිනී", "meaning": "ලුණුවිල", "category": "plant" },
  { "word": "තපෝධන", "meaning": "මුඛමහණ", "category": "plant" },
  { "word": "තබුව", "meaning": "වරාකිරි", "category": "plant" },
  { "word": "තම්", "meaning": "තබ", "category": "plant" },
  { "word": "තම්බටුවැල්", "meaning": "තුඩරණ, (මෑ වේවැල් වලට වඩා කුඩා ඇලවේවැල් වලට ලොකු වේවැල් වගිය)", "category": "plant" },
  { "word": "තම්බුර", "meaning": "තුම්බුරු නම් රුක", "category": "plant" },
  { "word": "තම්බුලි", "meaning": "බුලත්", "category": "plant" },
  { "word": "තම්මැන්තබිජු", "meaning": "තම්මැන්නා ඇට", "category": "plant" },
  { "word": "තම", "meaning": "කොල්ලම්කොළ", "category": "plant" },
  { "word": "තමක", "meaning": "ශ්වාස රෝගය", "category": "symptom" },
  { "word": "තමකා", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "තමරාප", "meaning": "සකුරු වෙසෙසක්", "category": "plant" },
  { "word": "තමරූප", "meaning": "වරාගස", "category": "plant" },
  { "word": "තමල්", "meaning": "කොල්ලම්කොළ", "category": "plant" },
  { "word": "තමළු", "meaning": "පිටවක්කා, කොල්ලම් කොළ", "category": "plant" },
  { "word": "තමස්විනී", "meaning": "කහ", "category": "plant" },
  { "word": "තමා", "meaning": "පිටවක්කා, තඹල ගස", "category": "plant" },
  { "word": "තමාබු", "meaning": "දුම්කොළ", "category": "plant" },
  { "word": "තමාල", "meaning": "මදටිය, මාරා, කොල්ලම් කොළ, බුලත්, ලුණුපරණ, බිම් නෙල්ලි, (පිටවක්කා)", "category": "plant" },
  { "word": "තමාලක", "meaning": "බිම්නෙල්ලි, කිඹුල්වැන්න", "category": "plant" },
  { "word": "තමාලච්ඡද", "meaning": "කොල්ලම්කොළ", "category": "plant" },
  { "word": "තමාලපත්‍ර", "meaning": "කොල්ලම්කොළ", "category": "plant" },
  { "word": "තමාලී", "meaning": "කොල්ලම්කොළ", "category": "plant" },
  { "word": "තමාලික", "meaning": "වැල්මදට, පිටවක්කා", "category": "plant" },
  { "word": "තමාලින්", "meaning": "ලුණුවරණ", "category": "plant" },
  { "word": "තමාලිනී", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "තමි", "meaning": "කසා", "category": "plant" }
];