const data_extra_186_193 = [
{"word":"චතුරුෂණ","meaning":"තිප්පිලි, ඉඟුරු, මිරිස්, තිප්පිලිමුල්","category":"treatment"},
{"word":"චතුගවද","meaning":"ඇඹුලඇඹිලිය, කිඹුල්වැන්න","category":"plant"},
{"word":"චතුෂ්පත්‍ර","meaning":"කිඹුල්වැන්න","category":"plant"},
{"word":"චතුෂ්පුටොද්භව","meaning":"කසාවන් මල් ඇති කණේරු","category":"plant"},
{"word":"චතුෂ්පර්ණී","meaning":"කුඩා ඇඹුලඇඹිලිය, කිඹුල්වැන්න","category":"plant"},
{"word":"චතුෂ්ඵලා","meaning":"ගස්කැලිය, කොටිකන්බැවිල, සිරිවැඩිබැවිල","category":"plant"},
{"word":"චතුෂ්ප්‍රභේද","meaning":"බන්ධුක්කා","category":"plant"},
{"word":"චතුස්නෙහ","meaning":"ගිතෙල්, තලතෙල්, පොල්තෙල්, එඬරුතෙල්","category":"treatment"},
{"word":"චතුස්නෙහ","meaning":"සකීරා, ගිතෙල්, වෙඬරු, කිරි","category":"treatment"},
{"word":"චතුස්සම","meaning":"අගිල්, කස්තුරි, කුංකුමප්පු-ගෝරද","category":"treatment"},
{"word":"චතු","meaning":"කපුරු, සඳුන්, රත්රන්, හිඟුරුපියලි, තුත්තුනාගම්, උගුරස්ස","category":"treatment"},
{"word":"චන්දන","meaning":"සඳුන්, කෝන්, සිහින් ඉරමුසු, රක්මල්, චන්දනකාෂ්ඨ-සඳුන්","category":"plant"},
{"word":"චන්දනගොප","meaning":"සිහින් ඉරමුසු, ඉරමුසු","category":"plant"},
{"word":"චන්දනද්වය","meaning":"සඳුන් දෙවර්ගය","category":"plant"},
{"word":"චන්දනද්‍රැම","meaning":"සඳුන් ගස, සල්ගස","category":"plant"},
{"word":"චන්දනපුෂ්ප","meaning":"කරාබුනැටි, කුරුඳු","category":"plant"},
{"word":"චන්දනමුලිකා","meaning":"කළු ඉරමුසු","category":"plant"},
{"word":"චන්දනසාරිවා","meaning":"හින් ඉරමුසු","category":"plant"},
{"word":"චන්දනා","meaning":"හින් ඉරමුසු","category":"plant"},
{"word":"චන්දනී","meaning":"රකුගුණ","category":"plant"},
{"word":"චන්දනීයා","meaning":"ගෝරෝචන","category":"treatment"},
{"word":"චන්ද්‍ර","meaning":"කපුරු-වගී දෙකකි (පක, අපක වශයෙන්. විස්තර 81පිටුවේ ඇත.)","category":"treatment"},
{"word":"චන්ද්‍රලේඛා","meaning":"වඳුරු මෑ","category":"plant"},
{"word":"චන්ද්‍ර","meaning":"කටුවෙලඟ, මහකරඹ, කුඩුමිරිස්, කපුරු, හිඟුරුපියලි, රත්රන්, සඳුන්","category":"plant"},
{"word":"චන්ද්‍රක","meaning":"මුරංගා ඇට, කපුරු, මිරිස්","category":"plant"},
{"word":"චන්ද්‍රකාන්තා","meaning":"සුදු හඳුන්, නික, හෙලබටු, කටුවැල්බටු, දියකදිර, පියුගල්","category":"plant"},
{"word":"චන්ද්‍රකාන්තාපද්ම","meaning":"හෙල බටු, හෙල කොඳ","category":"plant"},
{"word":"චන්ද්‍රකාන්තී","meaning":"රිදී","category":"treatment"},
{"word":"චන්ද්‍රකාර","meaning":"සුදු හඳුන්","category":"plant"},
{"word":"චන්ද්‍රකාලී","meaning":"සුදුපෝටා","category":"plant"},
{"word":"චන්ද්‍රකී","meaning":"දන්තීනාග රෝගය","category":"symptom"},
{"word":"චන්ද්‍රගන්ධ","meaning":"හිඟුරුපියලි","category":"plant"},
{"word":"චන්ද්‍රතර","meaning":"මහසෝමවල්ලී ලතාව","category":"plant"},
{"word":"චන්ද්‍රනාමන්","meaning":"කපුරු","category":"plant"},
{"word":"චන්ද්‍රපර්ණී","meaning":"ආපසුමුදු","category":"plant"},
{"word":"චන්ද්‍රපාණී","meaning":"සුදු අත්තන","category":"plant"},
{"word":"චන්ද්‍රපුෂ්පී","meaning":"හෙලබටු, කටුවැල්බටු, බෝදි ඇට","category":"plant"},
{"word":"චන්ද්‍රප්‍රභා","meaning":"බෝදි ගස","category":"plant"},
{"word":"චන්ද්‍රඵල","meaning":"පලිඟු","category":"treatment"},
{"word":"චන්ද්‍රබාලා","meaning":"එන්සාල්","category":"plant"},
{"word":"චන්ද්‍රබාලි","meaning":"එන්සාල්, මහ එන්සාල්","category":"plant"},
{"word":"චන්ද්‍රභස්මන්","meaning":"කපුරු","category":"treatment"},
{"word":"චන්ද්‍රභා","meaning":"කටුවැල්බටු","category":"plant"},
{"word":"චන්ද්‍රභාෂ","meaning":"රසකිඳ","category":"plant"},
{"word":"චන්ද්‍රභාෂා","meaning":"රසකිඳ, කටුවැල්බටු","category":"plant"},
{"word":"චන්ද්‍රභිඬා","meaning":"බෝදිගස","category":"plant"},
{"word":"චන්ද්‍රමල්ලිකා","meaning":"හිඟුරුපියලි, ඉද්ද","category":"plant"},
{"word":"චන්ද්‍රමල්ලී","meaning":"ඉද්ද වෙසෙසක්","category":"plant"},
{"word":"චන්ද්‍රමාතා","meaning":"එන්සාල්, සිහින් එන්සාල්","category":"plant"},
{"word":"චන්ද්‍රරැප්කා","meaning":"බෝදිඇට","category":"plant"},
{"word":"චන්ද්‍රරෙඛා","meaning":"බෝදි ගස","category":"plant"},
{"word":"චන්ද්‍රලතා","meaning":"එන්සාල්","category":"plant"},
{"word":"චන්ද්‍රලෙඛා","meaning":"දුහුදු ඇට, බෝදි ඇට","category":"plant"},
{"word":"චන්ද්‍රවල්ලභා","meaning":"සෝමලතා, බැමිනිරිය","category":"plant"},
{"word":"චන්ද්‍රවල්ලරී","meaning":"බෝදිඇට, ආපසුමුදු","category":"plant"},
{"word":"චන්ද්‍රවල්ලී","meaning":"යොහොඹු, පිච්ච, ආපසුමුදු, බැමිනිරිය","category":"plant"},
{"word":"චන්ද්‍රශකලා","meaning":"බෝදි ඇට","category":"plant"},
{"word":"චන්ද්‍රසංඥ","meaning":"කපුරු","category":"plant"},
{"word":"චන්ද්‍රසම්භව","meaning":"එන්සාල්, මහ එන්සාල්","category":"plant"},
{"word":"චන්ද්‍රසුර","meaning":"වල් උවවානාල්","category":"plant"},
{"word":"චන්ද්‍රහාසා","meaning":"කටුවැල්බටු, රසකිඳ, ආපසුමුදු","category":"plant"},
{"word":"චන්ද්‍රා","meaning":"වැල්මදට, එන්සාල්, රසකිඳ, කටුවැල්බටු","category":"plant"},
{"word":"චන්ද්‍රාභිඬා","meaning":"බෝදි ගස","category":"plant"},
{"word":"චන්ද්‍රාභීක","meaning":"කපුරු","category":"plant"},
{"word":"චන්ද්‍රාලෝක","meaning":"බෝදි ඇට","category":"plant"},
{"word":"චන්ද්‍රාස්පද","meaning":"කකුළුසුනු","category":"treatment"},
{"word":"චන්ද්‍රාහ්ව","meaning":"කපුරු","category":"plant"},
{"word":"චන්ද්‍රිකා","meaning":"එන්සාල්, මහ එන්සාල්, ඉද්ද","category":"plant"},
{"word":"චන්ද්‍රිකාමුඛ","meaning":"හෙවපුල්","category":"plant"},
{"word":"චපල","meaning":"කම්පලා","category":"plant"},
{"word":"චපලී","meaning":"බෝදිගස","category":"plant"},
{"word":"චපෙභාෂ්ටා","meaning":"මහනෙල්","category":"plant"},
{"word":"චමක","meaning":"කබල, කොණ්ඩ කබල","category":"plant"},
{"word":"චමපතු","meaning":"ගොකටු","category":"plant"},
{"word":"චමල්වීතෙ","meaning":"හණඇට","category":"plant"},
{"word":"චමසිඳු","meaning":"අබ","category":"plant"},
{"word":"චම්ප","meaning":"කිනිහිරිය","category":"plant"},
{"word":"චම්පල","meaning":"රිදී, රසදිය, ලිමා, වැටකේ","category":"plant"},
{"word":"චම්පලපුෂ්ප","meaning":"වැටකේ","category":"plant"},
{"word":"චම්පලා","meaning":"රසදිය, අරළු, කංසා, වගපුල්, වටකේ","category":"plant"},
{"word":"චම්පලමුල","meaning":"තිප්පිලි මුල්","category":"plant"},
{"word":"චම්ප","meaning":"කොබෝලිල","category":"plant"},
{"word":"චම්පක","meaning":"සපු","category":"plant"},
{"word":"චම්පක කුඩිමල","meaning":"සපුකැකුළ","category":"plant"},
{"word":"චම්පකදලි","meaning":"කෙසෙල් වෙසෙසක් (සපු ආනමාලු)","category":"plant"},
{"word":"චම්පක පුෂ්පී","meaning":"සපු මල්","category":"plant"},
{"word":"චම්පකාල","meaning":"කොස් ගස","category":"plant"},
{"word":"චම්පකොෂ","meaning":"කොස්","category":"plant"},
{"word":"චම්පාල","meaning":"කොස් ගස","category":"plant"},
{"word":"චමෙපයා","meaning":"සපු","category":"plant"},
{"word":"චමෙලි","meaning":"දෑසමන්","category":"plant"},
{"word":"චමට","meaning":"මහ තිරිඟු","category":"plant"},
{"word":"චමය","meaning":"දන්ත, දූමිතරිය","category":"plant"},
{"word":"චමර","meaning":"සෙමරමුවා","category":"treatment"},
{"word":"චමරපුෂ්පී","meaning":"රඹුක්, වැලුක්","category":"plant"},
{"word":"චමරිකා","meaning":"කොබෝලිල, රතුපෙතන්","category":"plant"},
{"word":"චමි","meaning":"සපු","category":"plant"},
{"word":"චයියගුලන්","meaning":"කපුරුනොල්කස්කුරු","category":"plant"},
{"word":"චරෝට","meaning":"දිය මිදෙල්ල","category":"plant"},
{"word":"චර්චරිකා","meaning":"තේක්ක ගස","category":"plant"},
{"word":"චර්චභා","meaning":"වාෂභක (අෂ්ටක වර්ගයේ ඔසුවක්)","category":"plant"},
{"word":"චර්භට","meaning":"කැකිරි","category":"plant"},
{"word":"චමි","meaning":"පැපිලිය, රත් එරබු","category":"plant"},
{"word":"චමිකා","meaning":"දේවදාලිය, වැටකොළු","category":"plant"},
{"word":"චමිකර","meaning":"තුවර, තෝර","category":"plant"},
{"word":"චමිකරී","meaning":"මාංශරෝහිණීනම ලතාව","category":"plant"},
{"word":"චමිකපා","meaning":"ලුණුවිල, මස්වැන්න","category":"plant"},
{"word":"චමිකා","meaning":"දේවදාලිය, (දෙවිදර) වැටකොළු","category":"plant"},
{"word":"චමිකායා","meaning":"ලුණුවිල","category":"plant"},
{"word":"චමිකාරතරු","meaning":"එල කුකුරුමුවන්","category":"plant"},
{"word":"චමිකාරලු","meaning":"උවරල","category":"plant"},
{"word":"චමිකාරිකා","meaning":"හිඟුරු වැල්","category":"plant"},
{"word":"චමිගයෝෂ්ටක","meaning":"කපුකිනිස්ස","category":"plant"},
{"word":"චමිවිතුක","meaning":"සෙම්තකුෂ්ට රෝගය","category":"symptom"},
{"word":"චමිඛක්","meaning":"මිනි මස්","category":"treatment"},
{"word":"චමිද්‍රැම","meaning":"බූප්පතු ගස","category":"plant"},
{"word":"චර්මන්වතී","meaning":"කෙසෙල් ගස","category":"plant"},
{"word":"චර්මනාශක","meaning":"වල් උවවානාල්","category":"plant"},
{"word":"චර්මිපිකා","meaning":"මසුරිකා රෝග භේදයක්","category":"symptom"},
{"word":"චර්මබද්ධන","meaning":"ගම්මිරිස්","category":"plant"},
{"word":"චර්මිලක","meaning":"ලුණුවරණ","category":"plant"},
{"word":"චර්මවෘක්ෂ","meaning":"මුරත, කුඹුක්, තෙලකඹුක්, බූප්පතු ගස","category":"plant"},
{"word":"චර්මසංඥ","meaning":"හිඟුරුවැල්","category":"plant"},
{"word":"චර්මසා","meaning":"මී","category":"treatment"},
{"word":"චර්මසම්භවා","meaning":"මහඑන්සාල්","category":"plant"},
{"word":"චර්මිසාන්වා","meaning":"ලුණුවිල","category":"plant"},
{"word":"චර්මහන්ත්‍රී","meaning":"කිබාරත්","category":"plant"},
{"word":"චර්මාභයෝෂ්ටක","meaning":"තකුල්","category":"plant"},
{"word":"චර්මාංශුරාපත","meaning":"හිඟුල්","category":"treatment"},
{"word":"චමාරක","meaning":"සුදු හිඟුල්","category":"treatment"},
{"word":"චර්මාන්වය","meaning":"පැපිලිය","category":"plant"},
{"word":"චර්මාන්වා","meaning":"හිඟුරුවැල්, බැමිනිරිය","category":"plant"},
{"word":"චර්මි","meaning":"බූප්පතු","category":"plant"},
{"word":"චර්මික්","meaning":"බූප්පතු, කෙසෙල්","category":"plant"},
{"word":"චර්මී","meaning":"බූරද","category":"plant"},
{"word":"චරකා","meaning":"පත්පාඩගම්","category":"plant"},
{"word":"චරතිපත්‍රිකා","meaning":"අරත්ත","category":"plant"},
{"word":"චරද","meaning":"නිකගස","category":"plant"},
{"word":"චරප්‍රිය","meaning":"මිරිස්","category":"plant"},
{"word":"චරස්කණ","meaning":"නිදිගස","category":"plant"},
{"word":"චරාවර","meaning":"කමසිබෙල්ලෝ, මුද්දරප්පලම්","category":"plant"},
{"word":"චරාක","meaning":"රන්වන් වේලා","category":"plant"},
{"word":"චරිත්‍රා","meaning":"සියඹලා ගස","category":"plant"},
{"word":"චරිපර්ණී","meaning":"ආපසුමුදු","category":"plant"},
{"word":"චල්ව","meaning":"මහ මෑ","category":"plant"},
{"word":"චල","meaning":"රසදිය, තුරුක්තෙල්, ගෙන්දගම්, රන්වන් සඳුන්","category":"treatment"},
{"word":"චලක","meaning":"ගුගුල්","category":"plant"},
{"word":"චලත්","meaning":"පික්මල්","category":"plant"},
{"word":"චලච්ඡද","meaning":"හලගස, ඇසල ගස, එරබදු ගස","category":"plant"},
{"word":"චලදල","meaning":"බෝගස, ඇසතු, පුමිල","category":"plant"},
{"word":"චලද්‍රැම","meaning":"ගොකටු","category":"plant"},
{"word":"චලන","meaning":"සිහින් මිදි","category":"plant"},
{"word":"චලපතු","meaning":"ඇසතු, බෝගස","category":"plant"},
{"word":"චලපුත්‍ර","meaning":"තුරුක්තෙල්","category":"treatment"},
{"word":"චලා","meaning":"තුස්තවාලු, මී ඉටි","category":"treatment"},
{"word":"චලාවල","meaning":"තල්ගස","category":"plant"},
{"word":"චලාතකඛග","meaning":"වාතරෝගයක්,","category":"symptom"},
{"word":"චලාතබගකම්ප","meaning":"(වෙව්ලිම)","category":"symptom"},
{"word":"චලාපභ","meaning":"රතු කොල්ලු, ලුණුමරණ","category":"plant"},
{"word":"චවබක","meaning":"සිවිය, ගප්තිප්පිලි","category":"plant"},
{"word":"චවන / චවි","meaning":"සිවිය, ගප්තිප්පිලි","category":"plant"},
{"word":"චවිකා","meaning":"විෂ්ණුක්‍රාන්ති, ඇත්වගපුල් (ගප්තිප්පිලි) සිවිය, ගොකොළු","category":"plant"},
{"word":"චවිකාංශ්‍රික","meaning":"නිප්පිලිමුල්","category":"plant"},
{"word":"චවිකා ශරස්","meaning":"නිප්පිලි මුල්","category":"plant"},
{"word":"චවී","meaning":"සිවිය, ඇත්වගපුල්","category":"plant"},
{"word":"චව්‍ය","meaning":"කපුරු, සිවිය, ගප්තිප්පිලිදෙකසා","category":"plant"},
{"word":"චව්‍යක්‍ෂර","meaning":"අරළු, සිවිය,ගප්තිප්පිලි","category":"plant"},
{"word":"චව්‍යඵල","meaning":"ගප්තිප්පිලි","category":"plant"},
{"word":"චව්‍යා","meaning":"සිවිය, ගප්තිප්පිලි, කපු, දී","category":"plant"},
{"word":"චව්‍යාපා","meaning":"සිවිය, ගප්තිප්පිලි","category":"plant"},
{"word":"චාක්ෂුක","meaning":"කෝමීගස","category":"plant"},
{"word":"චාකුලියා","meaning":"පුස්වැන්න","category":"plant"},
{"word":"චාබෙගරි","meaning":"ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චාඛෙගරිසදගපතු","meaning":"කිඹුල්වැන්න","category":"plant"},
{"word":"චාතුර්ජාතක","meaning":"කුරුඳුපොතු, එන්සාල්, කොල්ලම් කොළ, නාකෙසුරා (නාමල්රේණු)","category":"plant"},
{"word":"චාතුර්භද්‍රක","meaning":"සිද්ධිගුරු, අතිවිඩයන්, කලාඳුරු, රසකිඳ","category":"plant"},
{"word":"චාදික්කායි","meaning":"සාදික්කා","category":"plant"},
{"word":"චාඥානාගරී","meaning":"අමුඉඟුරු","category":"plant"},
{"word":"චාඥා","meaning":"කටුවැල්බටු, හෙල කටුවැල්බටු","category":"plant"},
{"word":"චාඥාක","meaning":"අමු ඉඟුරු","category":"plant"},
{"word":"චාඥුක","meaning":"සිද්ධිගුරු","category":"plant"},
{"word":"චාන්දනාගර","meaning":"අමුඉඟුරු","category":"plant"},
{"word":"චාඥාද","meaning":"ඉවද","category":"plant"},
{"word":"චාඥාබ්‍ය","meaning":"අමුඉඟුරු","category":"plant"},
{"word":"චානක","meaning":"ගොම වැරටි","category":"treatment"},
{"word":"චානකම","meaning":"ගොම","category":"treatment"},
{"word":"චානල","meaning":"මිදි, හින්මිදි ගස","category":"plant"},
{"word":"චාසපට","meaning":"පියල් ගස","category":"plant"},
{"word":"චාම්පෙය","meaning":"නාගස්, සපු, දෑසමන්, නාමල්රේණු, ආපසුමුදු, අත්තන ගස","category":"plant"},
{"word":"චාම්පෙයක","meaning":"නාමල්රේණු, සපුමල්","category":"plant"},
{"word":"චාම්පෙයකුඩිමල","meaning":"සපුකැකුළ","category":"plant"},
{"word":"චාමර","meaning":"වැලුක්, ග්‍රන්ථිපර්ණී වාක්‍යය","category":"plant"},
{"word":"චාමරපුෂ්ප","meaning":"උක්, පුවක්, වැටකේ, අඹ","category":"plant"},
{"word":"චාමරපුෂ්පිකා","meaning":"ගතපුෂ්ප","category":"plant"},
{"word":"චාමල","meaning":"දෙල්ම්ගෙඩි","category":"plant"},
{"word":"චාමලගත","meaning":"දෙල්ම්ගෙඩි","category":"plant"},
{"word":"චාමිකර","meaning":"අත්තන, රත්රන්","category":"plant"},
{"word":"චාමුර්තී","meaning":"අඹගෙඩිය","category":"plant"},
{"word":"චාමො","meaning":"බතින් පෙරා කැඳ","category":"treatment"},
{"word":"චාරක","meaning":"පියල් ගස","category":"plant"},
{"word":"චාරටී","meaning":"පිටවක්කා, පුස්වැන්න, මෑණික්වැන්න, පොල්පලා","category":"plant"},
{"word":"චාරණී","meaning":"කණේරු, ගොඩ මානෙල්","category":"plant"},
{"word":"චාරි","meaning":"නිදිකුම්බා","category":"plant"},
{"word":"චාරිත්‍රා","meaning":"සියඹලා ගස","category":"plant"},
{"word":"චාරිවාච්","meaning":"මෑබහඟු","category":"plant"},
{"word":"චාරු","meaning":"කොකුම්, රතුන්, සල්ගස, පද්මකාෂ්ඨ","category":"plant"},
{"word":"චාරුක","meaning":"රත් සඳුන්","category":"plant"},
{"word":"චාරුකෙශර","meaning":"කලාඳුරු, ඉඟුරු, සෙව්වන්දි","category":"plant"},
{"word":"චාරුකෙශා","meaning":"වල්ඉද්ද","category":"plant"},
{"word":"චාරුදගිණ","meaning":"පුමිල, තුත්පුමිල, තෙලසවු","category":"plant"},
{"word":"චාරුද්‍රා","meaning":"තෙලසවු, කපුරුකහ","category":"plant"},
{"word":"චාරුද්‍රක්","meaning":"කිරිපළුගස, නුග ගස","category":"plant"},
{"word":"චාරුධාම","meaning":"ආමුහරිද්‍රා","category":"plant"},
{"word":"චාරුත","meaning":"මනෝසිල","category":"treatment"},
{"word":"චාරුනාලක","meaning":"රත් පියුම්, (රත් නෙළුම්)","category":"plant"},
{"word":"චාරුපර්ණී","meaning":"ආපසුමුදු, කොකුම්","category":"plant"},
{"word":"චාරුපත්‍රිකා","meaning":"පත්‍රැඟිඩිනු, ආපසුමුදු","category":"plant"},
{"word":"චාරුපුෂ්පී","meaning":"රත් පලොල්","category":"plant"},
{"word":"චාරුඵලා","meaning":"කැකිරි, කෝවක්කා, මුද්දරප්පලම්","category":"plant"},
{"word":"චාරුබාලිකා","meaning":"කොකුම්","category":"plant"},
{"word":"චාරුමක්ෂිකා","meaning":"මුද්දරප්පලම්","category":"plant"},
{"word":"චාල්මුග්‍රා (වෙරළුමුග්‍රා)","meaning":"තුවරකා (Bixinae Odorata). මෙය ඉන්දියාව ජන්මභූමිය කොට ඇති මෑතක සිට ලංකාවේ ද බෝවී යන ගස් වගියකි. මේ ගස පෙනුමෙන් ලංකාවේ කළු තිඹිරි ගසකට සමාන ය. අඩි යක් පමණ දිග හා අඟල් හතරක් පමණ පළල ඇති මේ ගසේ කොළ නටු වල එක තැනින් දෙක බැගින් දෙ පැත්තට බෙදී ඇත. මේ ගසේ ඇට වලින් ලබා ගන්නා තෙල් ලාදුරු රෝගයටත්, හොරි, දද, කුෂ්ට, කඩුවෙගන් ආදී සමේ රෝග වලටත් ප්‍රත්‍යක්ෂ ඖෂධයකි. අතීසාර, සමාජ රෝග, පෙනහල්ලේ ආබාධ යන මේ රෝග වලට චාල්මුග්‍රා සාරය මිශ්‍ර ඖෂධ යෝග යොදති. ලංකාවේ මකුළු (මකුල්ල) ගසෙහි ද මීට සමාන ගුණ ඇතැයි වෛද්‍යවරයෝ අදහස් කරති.","category":"plant"},
{"word":"චාරමොද","meaning":"කහවන් සිනිද්ද","category":"plant"},
{"word":"චාරුයුතී","meaning":"සුදුවන් සිනිද්ද","category":"plant"},
{"word":"චාරුරත්න","meaning":"රත්රන්","category":"treatment"},
{"word":"චාරුවර්ණිනී","meaning":"ලාකඩ","category":"treatment"},
{"word":"චාරුවෘක්ෂ","meaning":"තුත් පුමිල, (තෙලසවු)","category":"plant"},
{"word":"චාරුශෘංගි","meaning":"බාත්වැල්, (මනුවැල්=වෙනිවැල්)","category":"plant"},
{"word":"චාස","meaning":"උක් වෙසෙසක්","category":"plant"},
{"word":"චිංගුලක","meaning":"තල්කොළ","category":"plant"},
{"word":"චිකාණ","meaning":"පුවක්ගස","category":"plant"},
{"word":"චිකකා","meaning":"පුවක් ගස","category":"plant"},
{"word":"චිකකිණි","meaning":"පුවක් ගස","category":"plant"},
{"word":"චිකිත්සක","meaning":"රෝගයට ප්‍රතිකෘර, උපාය කිරීම","category":"treatment"},
{"word":"චිකිත්සය","meaning":"වෙදකම්කරන්නා, සුව කරන්ට පුළුවන් ලෙඩ","category":"treatment"},
{"word":"චිකුල","meaning":"දත්ත ගස","category":"plant"},
{"word":"චිවි","meaning":"නිටෝල් ගස","category":"plant"},
{"word":"චිඤ්චා","meaning":"සියඹලා, හුනිද","category":"plant"},
{"word":"චිඤ්චාමල","meaning":"ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චිඤ්චාසාර","meaning":"ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චිඤ්චිකා","meaning":"සියඹලා, හුනිද","category":"plant"},
{"word":"චිඤ්චිනිකා","meaning":"සියඹලා ගස","category":"plant"},
{"word":"චිත්ත","meaning":"රත්නිවුල්","category":"plant"},
{"word":"චිත්තක","meaning":"රත්නිවුල්","category":"plant"},
{"word":"චිත්තනාරීත්","meaning":"මුරංගා ගස","category":"plant"},
{"word":"චිත්තරා","meaning":"රසකිඳ","category":"plant"},
{"word":"චිත්‍ර","meaning":"හෙලනිවුල්, අසෝක, මිනුග, එරබු","category":"plant"},
{"word":"චිත්‍රක","meaning":"එරබු, සිද්ධිගුරු, කොත්තමල්ලි, ගස් කැලිය, රත්නිවුල්, හෙල නිවුල්","category":"plant"},
{"word":"චිත්‍රකණ්ඨක","meaning":"ගොකටු","category":"plant"},
{"word":"චිත්‍රකණ්ඩාලි","meaning":"ගෝනසවැල්","category":"plant"},
{"word":"චිත්‍රකමින්","meaning":"කෝමී ගස","category":"plant"},
{"word":"චිත්‍රකා","meaning":"රත්නිවුල්","category":"plant"},
{"word":"චිත්‍රකාරක","meaning":"කුඹුක්","category":"plant"},
{"word":"චිත්‍රකුලා","meaning":"හින්දැත්ත ගස","category":"plant"},
{"word":"චිත්‍රකෘත්","meaning":"කෝන්, කෝබු","category":"plant"},
{"word":"චිත්‍රගණ","meaning":"හිරියල්","category":"treatment"},
{"word":"චිත්‍රගුගා","meaning":"තොවිල","category":"plant"},
{"word":"චිත්‍රගුකිනි","meaning":"වෙල්මුබ, (මුඛමහණ)","category":"plant"},
{"word":"චිත්‍රඝන","meaning":"රක්අත්තන","category":"plant"},
{"word":"චිත්‍රචඤ්චු","meaning":"නවාගිලි, (එඬරු)","category":"plant"},
{"word":"චිත්‍රට","meaning":"රියම්","category":"treatment"},
{"word":"චිත්‍රඬවි","meaning":"බූප්පතු","category":"plant"},
{"word":"චිත්‍රතණ්ඩූල","meaning":"වලඟසාල්","category":"plant"},
{"word":"චිත්‍රතණ්ඩූලා","meaning":"වලඟසාල්","category":"plant"},
{"word":"චිත්‍රදණ්ඩක","meaning":"කිඩාරම්, කපු ගස","category":"plant"},
{"word":"චිත්‍රදේවී","meaning":"කැකිරි, කෝවක්කා","category":"plant"},
{"word":"චිත්‍රපත්‍ර","meaning":"බූප්පතු","category":"plant"},
{"word":"චිත්‍රපත්‍රී","meaning":"දියනිප්පිලි, පුස්වැන්න","category":"plant"},
{"word":"චිත්‍රපත්‍රිකා","meaning":"කවුඩු කැකිරි, ගැටතුඹ, දිවුල්කොළ, අලකිරිය","category":"plant"},
{"word":"චිත්‍රපද","meaning":"වලාවැන්න","category":"plant"},
{"word":"චිත්‍රපර්ණී","meaning":"පොල්පලා, පුස්වැන්න","category":"plant"},
{"word":"චිත්‍රපාශී (ලී)","meaning":"නිටෝල් ගස","category":"plant"},
{"word":"චිත්‍රපාලා","meaning":"මහ ගොන්කැකිරි","category":"plant"},
{"word":"චිත්‍රපුෂ්පී","meaning":"දියමින්ත","category":"plant"},
{"word":"චිත්‍රපුෂ්පින්","meaning":"ඇම්බරැල්ලා","category":"plant"},
{"word":"චිත්‍රප්‍රිය","meaning":"හිරියල්","category":"treatment"},
{"word":"චිත්‍රඵල","meaning":"දුම්මැල්ල, කැකිරි, මහගොන්කැකිරි","category":"plant"},
{"word":"චිත්‍රඵලා","meaning":"කටුවැල්බටු, තියඹරා, මහකැකිරි, කෝවක්කා","category":"plant"},
{"word":"චිත්‍රබීජා","meaning":"වලඟසාල්","category":"plant"},
{"word":"චිත්‍රභානු","meaning":"නිටෝල්, වරා, බදුල්ල","category":"plant"},
{"word":"චිත්‍රභෙෂජ","meaning":"කොටදිඹුලා","category":"plant"},
{"word":"චිත්‍රමූල","meaning":"එඬරු","category":"plant"},
{"word":"චිත්‍රයොගි","meaning":"කුඹුක්","category":"plant"},
{"word":"චිත්‍රරාග","meaning":"කර","category":"treatment"},
{"word":"චිත්‍රරොගක","meaning":"සිහින්මිදි","category":"plant"},
{"word":"චිත්‍රලතා","meaning":"වැල්මදට","category":"plant"},
{"word":"චිත්‍රලා","meaning":"හෙල අබ, ගොරක්ෂවෘක්‍ෂය","category":"plant"},
{"word":"චිත්‍රලොහ","meaning":"වානේ","category":"treatment"},
{"word":"චිත්‍රවර්තීනී","meaning":"රහෑණිය ඇට","category":"plant"},
{"word":"චිත්‍රවල්ලි","meaning":"වැල්මදට, ගොන්කැකිරි","category":"plant"},
{"word":"චිත්‍රවල්ලිකා","meaning":"පත්තක්කා ගෙඩිය","category":"plant"},
{"word":"චිත්‍රවිෂ","meaning":"රතුඑරබු","category":"plant"},
{"word":"චිත්‍රවිප්ප","meaning":"වලඟසාල්","category":"plant"},
{"word":"චිත්‍රවීශයී","meaning":"රත්එරබු","category":"plant"},
{"word":"චිත්‍රගොක","meaning":"හෝපලු ගස","category":"plant"},
{"word":"චිත්‍රසානු","meaning":"හිරියල්","category":"treatment"},
{"word":"චිත්‍රා","meaning":"මිනුග, ගොඩුකොළ, දන්ත, කැකිරි, වැල්මදට, කරගස, වලඟසාල්","category":"plant"},
{"word":"චිත්‍රාංග","meaning":"ගුගුල්","category":"plant"},
{"word":"චිත්‍රාඬඟ","meaning":"රක්නිවුල්, හිරියල්, ගුගුල්","category":"plant"},
{"word":"චිත්‍රාබහා","meaning":"වැල්මදට, කලුදුරු","category":"plant"},
{"word":"චිත්‍රාබගි","meaning":"වැල්මදට, රත්නිවුල්","category":"plant"},
{"word":"චිදි","meaning":"සුවකැරබ","category":"plant"},
{"word":"චින්තිනි","meaning":"සියඹලා ගස","category":"plant"},
{"word":"චිපිටක","meaning":"හබලපෙති","category":"treatment"},
{"word":"චිපිටා","meaning":"වල්කොල්ලු","category":"plant"},
{"word":"චිමභාටකි","meaning":"දියමින්ත","category":"plant"},
{"word":"චිකීර්ෂා","meaning":"පුවක්ගෙඩිය","category":"plant"},
{"word":"චිහීට","meaning":"මහදුරු","category":"plant"},
{"word":"චීර්ගතිකා","meaning":"කැකිරි","category":"plant"},
{"word":"චීර්නිට","meaning":"කැකිරි වෙසෙසක්","category":"plant"},
{"word":"චිලසුලවල්ලි","meaning":"මිරිස්වැල","category":"plant"},
{"word":"චිහි","meaning":"මසන්","category":"plant"},
{"word":"චිර","meaning":"බෙලි","category":"plant"},
{"word":"චිරජීවක","meaning":"නිඹුල්, පියාගස","category":"plant"},
{"word":"චිරජීවනී","meaning":"ඉඹුල්ගස","category":"plant"},
{"word":"චිරඤ්ජීවී","meaning":"ඇඹුල, තොවිල","category":"plant"},
{"word":"චිරතිකතා","meaning":"බිමිකොසඹ, තිත්තකැකිරි","category":"plant"},
{"word":"චිරනාථ","meaning":"පොකුරු මුල්","category":"plant"},
{"word":"චිරපතුක","meaning":"කුඩාසල් ගස","category":"plant"},
{"word":"චිරපත්‍රා","meaning":"ජම්බු වෘක්ෂ වෙසෙසක්","category":"plant"},
{"word":"චිරපර්ණී","meaning":"සල් ගස","category":"plant"},
{"word":"චිරපාකී","meaning":"තල්, පොල්, දිඹුල්, ගිවුලු","category":"plant"},
{"word":"චිරපාකින්","meaning":"දිවුල්","category":"plant"},
{"word":"චිරපුෂ්පී","meaning":"මුහුණමල්","category":"plant"},
{"word":"චිරබිල්ලක","meaning":"කරඳ","category":"plant"},
{"word":"චිරබිල්ව","meaning":"බෙලි, සිරිල","category":"plant"},
{"word":"චිරරෝපක","meaning":"සිහින්මිදි","category":"plant"},
{"word":"චිරවි","meaning":"බෙලි","category":"plant"},
{"word":"චිරවිල්ව","meaning":"මඟුල් කරඳ","category":"plant"},
{"word":"චිරවිල්වක","meaning":"සිරිල","category":"plant"},
{"word":"චිරවියශී","meaning":"රත් එරබු","category":"plant"},
{"word":"චිරවෘක්ෂ","meaning":"බදුල්ල","category":"plant"},
{"word":"චිරා","meaning":"දියමින්ත","category":"plant"},
{"word":"චිරාටිකා","meaning":"පිටසුදු සාරණ (පිටසුදුපලා)","category":"plant"},
{"word":"චිරාතච්ඡද","meaning":"කෙසෙල් ගස","category":"plant"},
{"word":"චිරාතික්ත","meaning":"බිංකොසඹ","category":"plant"},
{"word":"චිරායු","meaning":"නිඹුල්","category":"plant"},
{"word":"චිරායුෂ්","meaning":"තල් ගස","category":"plant"},
{"word":"චිරායුෂප","meaning":"සාතාවාරිය, සිහින් සාතාවාරිය","category":"plant"},
{"word":"චිරාස්මිකා / චිරාස්විකා","meaning":"බිමිකොසඹ","category":"plant"},
{"word":"චිරිකච්ඡද","meaning":"පාලඟවැල් (පාලවැල්)","category":"plant"},
{"word":"චිරිපතු","meaning":"හින්කරිවිල","category":"plant"},
{"word":"චිරිමිල්ව","meaning":"කරඳ ගස","category":"plant"},
{"word":"චිලලක","meaning":"ලොත්, සඳුන් ගස","category":"plant"},
{"word":"චිල්ලී","meaning":"කුරතම්පලා, අලරිය, ලොත්, කණේරු","category":"plant"},
{"word":"චිලී","meaning":"සල්ල, සරල ගස (නොරගස)","category":"plant"},
{"word":"චිලිඹා","meaning":"පුලිල ගස","category":"plant"},
{"word":"චිලිනලි","meaning":"සල් ගස","category":"plant"},
{"word":"චිවු (ක)","meaning":"මුචුකුන්දරුක","category":"plant"},
{"word":"චිහ්නධාරිණී","meaning":"ඉරමුසු","category":"plant"},
{"word":"චිඛා","meaning":"දේවදාරු රුක","category":"plant"},
{"word":"චීන අල","scientific":"Gynura Pseudo China","meaning":"චීන අල - සීන අල, චොබවිනී (උපදංශ රෝගයට ප්‍රත්‍යක්ෂ පිටරටින් ගෙනෙන අල වර්ගයකි). චීන අල-සීන අල, අලබෙත්, මුල් බෙත් යන නම් කීපයකින් ම ලාංකික වෛද්‍යවරයන් අතර හැඳින්වෙන මේ වර්ගය අපේ දේශීය වෙදකමට එකතුවී අවුරුදු පන්සියයකට වඩා පරණී නැත. භාව ප්‍රකාශයට වඩා පැරණී ඉන්දියානු සංස්කෘත පොත් වල චීන අල ගැන සඳහන් ව නැති නිසා ඉන්දියාවට ද මෙය ඖෂධයක් වශයෙන් භාවිතයට පටන් ගෙන අවුරුදු පන්සියයකට වැඩි කාලයක් ගතවී නැති බව පෙනේ. (193 පිටුව) සාමාන්‍ය පෙනුමට මෙය රාබු පැළයකට සමාන යි. එහෙත් අලවල පිහිටීම හා කොළවල හැඩහුරුකම ත් රාබු පැළයකට වඩා මඳක් වෙනස් බව ඡායාරූපය දෙස බැලීමෙන් වටහා ගත හැක. චීන අල යන නමින් ම පෙනෙන්නේ මේ වර්ගය චීන-ලංකා සම්බන්ධය පැවති ඈත අතීතයෙහි අපේ රටට ගෙනැවිත් බෝකරණ ලද්දක් බව ය. චීන අල ඉතා ප්‍රත්‍යක්ෂ ගුණදායක වටිනා ඖෂධයකි. සමාජ රෝග, උපදංශ, (පරංගි) ලාදුරු, ග්‍රන්ථිශූල ආදී අසාධ්‍ය රෝග කීපයකට ම යොදන බෙහෙත් වට්ටෝරුවලට චීන අල ඇතුළත් ව තිබේ.","category":"plant"},
{"word":"චීනක","meaning":"චීන කපුරු","category":"treatment"},
{"word":"චීනකපිඨිකා","meaning":"පතෝල","category":"plant"},
{"word":"චීනකර්පූර","meaning":"කපුරු වෙසෙසක්","category":"treatment"},
{"word":"චීනපිටස්","meaning":"සින්දුරම්","category":"treatment"},
{"word":"චීනපිණ්ඩා","meaning":"තුවරලා","category":"plant"},
{"word":"චීනපිෂ්ට / චීනපිෂ්ටා","meaning":"සින්දුරම්","category":"treatment"},
{"word":"චීනාල","meaning":"සීනල, අලබෙත්, (සිනඅල)","category":"plant"},
{"word":"චීනවබා","meaning":"රියම්","category":"treatment"},
{"word":"චීනා","meaning":"හල්දුම්මල","category":"treatment"},
{"word":"චීනාක","meaning":"කපුරු","category":"treatment"},
{"word":"චීනිවෙපා","meaning":"සීන අල","category":"plant"},
{"word":"චීනිච්ඡද / චීනිපත්‍රී","meaning":"ඉඳි ගස, කොසඹගස","category":"plant"},
{"word":"චීර","meaning":"කිරිමුගුරුද","category":"plant"},
{"word":"චීරපර්ණී","meaning":"සල් ගස","category":"plant"},
{"word":"චීරා","meaning":"දියමින්ත","category":"plant"},
{"word":"චීරිකච්ඡද","meaning":"පාලඟපලා","category":"plant"},
{"word":"චුක්‍ර","meaning":"සියඹලා බොර, ඇඹුල්වේ","category":"plant"},
{"word":"චුක්‍රකා","meaning":"සියඹලා, ඇඹුල්වේ","category":"plant"},
{"word":"චුක්‍රකෙපා","meaning":"ඇඹුල්වේ","category":"plant"},
{"word":"චුක්‍රචණ්ඩිකා","meaning":"සියඹලා ගස","category":"plant"},
{"word":"චුක්‍රඵල","meaning":"ගොරක","category":"plant"},
{"word":"චුක්‍රවායතුකා","meaning":"ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චුක්‍රවේතස","meaning":"ගොරක","category":"plant"},
{"word":"චුක්‍රගාක","meaning":"ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චුක්‍රාටලා","meaning":"ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චුක්‍රාමිලා","meaning":"සියඹලා, ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චුක්‍රිකා","meaning":"ඇඹුල්ඇඹිලිය","category":"plant"},
{"word":"චුක්‍රී","meaning":"සියඹලා","category":"plant"},
{"word":"චුච්චු","meaning":"නිදිකුම්බා, කොලොම්, රාබු, කිඹුල්වැන්න","category":"plant"},
{"word":"චුචු","meaning":"කිඹුල්වැන්න","category":"plant"},
{"word":"චුඤ්චු","meaning":"රතු එඬරු, නිවිනිවැල","category":"plant"},
{"word":"චුණ්ණවාලිනී","meaning":"බෙහෙත් කුඩු හලන පෙත්තෙරය","category":"treatment"},
{"word":"චුත","meaning":"අඹගස","category":"plant"},
{"word":"චුතු","meaning":"ඇඹුල්වේ","category":"plant"},
{"word":"චුන්තය","meaning":"ඒකාවේරිය මුල්","category":"plant"},
{"word":"චුම්බක","meaning":"කාන්දම්","category":"treatment"},
{"word":"චුම්බලා","meaning":"මුඩමහණ","category":"plant"},
{"word":"චුද්‍රික","meaning":"කුකුරුමුවන්","category":"plant"},
{"word":"චුල්ලිකා","meaning":"ලවණ-ලුණු වෙසෙසක්","category":"treatment"},
{"word":"චුස්ත","meaning":"මොණර කුඩුම්බිය","category":"plant"},
{"word":"චූබා","meaning":"දුටුසතුරු, (මොණරකුඩුම්බිය) කෝබේසිපලා, හෙල ඔලිඳ","category":"plant"},
{"word":"චූඩාමිලා","meaning":"සියඹලා","category":"plant"},
{"word":"චූඩාමණී","meaning":"ඔලිඳ, රත් ඔලිඳ","category":"plant"},
{"word":"චූබාලා","meaning":"වම්මුතු, මහවම්මුතු, (කලාඳුරු)","category":"plant"},
{"word":"චූත","meaning":"අඹ","category":"plant"},
{"word":"චූතකා","meaning":"අඹගස, ගොරක ගස","category":"plant"},
{"word":"චූතසාර","meaning":"අඹ මැලියම්","category":"plant"}
];