// data_297_305.js - පිටු 297 සිට 305 දක්වා සියලුම වචන
const data_extra_297_305 = [
    // --- පිටුව 297 ---
    { "word": "පස්ච", "meaning": "පියාගස්", "category": "plant" },
    { "word": "පස්චපුෂ්පී", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "පස්චෝරුපලා", "meaning": "පියාගස්", "category": "plant" },
    { "word": "පස්තණ මුල්", "meaning": "වෑක්, උක්, ඉළුක්, ඊතණ, රණහුණ", "category": "compound" },
    { "word": "පස්තෙල්", "meaning": "තල, මී, කොහොඹ, එරඬු, ගිතෙල්", "category": "compound" },
    { "word": "පස්දලු", "meaning": "එරබු ගස", "category": "plant" },
    { "word": "පස්දුරු", "meaning": "සුදු දුරු, කළු දුරු, අසමෝදගම්, මහ දුරු, ශතපුෂ්ප", "category": "compound" },
    { "word": "පස්පලවත", "meaning": "කපුරු, පුවක්, බුලත්, තකුල්, මුඛවාසගණ", "category": "compound" },
    { "word": "පස්පියුම්", "meaning": "ඇඹුල්, උපුල්, නෙළුම්, රත් පියුම්, හෙළ පියුම්", "category": "compound" },
    { "word": "පස්පැඟිරි", "meaning": "නස්නාරන්, යකිනාරං, දෙහි, දොඩම්, පඹුරු", "category": "compound" },
    { "word": "පස්පැණි", "meaning": "මී, බඹර, කණවියා, දඬුවැල් බෑ, කුඩා මී", "category": "compound" },
    { "word": "පස්බඩ", "meaning": "පොල්, තල්, කිතුල්, ඉඳි, වැටකේ හෝ පුවක් යන මේ ගස්වල බඩ", "category": "compound" },
    { "word": "පස් මුල්", "meaning": "සුළු පස් මුල් හෝ මහපස් මුල්", "category": "compound" },
    { "word": "පස්රස", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "පස්ලුණු", "meaning": "මුහුදු ලුණු, සුවස ලුණු, සවිඳ ලුණු, බළල් ලුණු, උද්භිද ලුණු", "category": "compound" },
    { "word": "පස්වදෑරුම් කෂාය", "meaning": "ස්වරස, කල්ක, ඵාන්ට, හිම, ක්වාථ යන පඤ්ච කෂාය", "category": "treatment" },
    { "word": "පස්වැල්", "meaning": "කහඹිලියා, පුවටා, (පෝටා), කිරිබදු, මුරුවා, ඉරමුසු", "category": "compound" },
    { "word": "පස්සය", "meaning": "කහඹිලියා", "category": "plant" },
    { "word": "පසකුරු", "meaning": "නුග, ඇසතු, බෝ, පුලිල, අට්ටික්කා යන පස් වගය.", "category": "compound" },
    { "word": "පසකුරුදළු", "meaning": "නුග, ඇසතු, බෝ, පුලිල, අට්ටික්කා යන පසෙහි දළු", "category": "compound" },
    { "word": "පසරූප", "meaning": "පංචෝපචාර", "category": "treatment" },
    { "word": "පසල්", "meaning": "ගෙඳ", "category": "plant" },
    { "word": "පසඟ", "meaning": "පඤ්චාංගය (මුල්, පොතු, කොළ, මල්, නැටි)", "category": "compound" },
    { "word": "පසඟිලි", "meaning": "එඬරු ගස", "category": "plant" },
    { "word": "පසඟුල්", "meaning": "එරබු", "category": "plant" },
    { "word": "පසඟිල්ල", "meaning": "එරබු ගස", "category": "plant" },
    { "word": "පසලෛ", "meaning": "නිති (නිවිති)", "category": "plant" },
    { "word": "පසවො", "meaning": "මැල, දළුව", "category": "plant" },
    { "word": "පසාදන", "meaning": "රත්ලොත්", "category": "plant" },
    { "word": "පසාතය", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "පසි", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "පසෝලි", "meaning": "කවෙලු, කිරිකවෙලු", "category": "plant" },
    { "word": "පහකාරි", "meaning": "සිහින් මිදි", "category": "plant" },
    { "word": "පහත", "meaning": "බුත්සරණ, බෝගස්, පොල්පලා, අරළු", "category": "plant" },
    { "word": "පහතබෙය", "meaning": "පොල්පලා", "category": "plant" },
    { "word": "පළුලු", "meaning": "පලොල් ගස", "category": "plant" },
    { "word": "පා", "meaning": "කිරි, සාමගස්, මුල, රුක් මල, පාදය", "category": "general" },
    { "word": "පාංගවී", "meaning": "පාංශු ලුණු", "category": "mineral" },
    { "word": "පාංශු", "meaning": "පැපිලිය, පස්, වැලිකරලුණු, ගල්සෙවෙල්", "category": "mineral" },
    { "word": "පාංශුකාශිෂ", "meaning": "කසිස්", "category": "mineral" },
    { "word": "පාංශුප්", "meaning": "පාංශුලුණු, රෝමලුණු", "category": "mineral" },
    { "word": "පාංශුප්ජ", "meaning": "පාංශු ලුණු", "category": "mineral" },
    { "word": "පාංශුත", "meaning": "පාංශුලුණු", "category": "mineral" },
    { "word": "පාංශුපත්‍ර", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "පාංශුපත්‍රී", "meaning": "නිල්තම්පලා", "category": "plant" },
    { "word": "පාංශුභව", "meaning": "පාංශු ලුණු", "category": "mineral" },
    { "word": "පාංශුලවණ", "meaning": "පාංශුලුණු", "category": "mineral" },
    { "word": "පාංශුලොඝ", "meaning": "රෝමලුණු", "category": "mineral" },
    { "word": "පාක්කොට්ටි", "meaning": "වියලි පුවක්", "category": "plant" },
    { "word": "පාක", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "පාකකෘෂණ", "meaning": "කරඹ", "category": "plant" },
    { "word": "පාකකෘෂඵල", "meaning": "කරඹගෙඩි", "category": "plant" },
    { "word": "පාකඵල", "meaning": "කරඹ, මඟකරල්", "category": "plant" },
    { "word": "පාකඵල්‍යාඝණි", "meaning": "කරඹ", "category": "plant" },
    { "word": "පාකම්පාලෙයි", "meaning": "දියමිත්ත වැල", "category": "plant" },
    { "word": "පාකර", "meaning": "කොල්ලම් කොළ", "category": "plant" },

    // --- පිටුව 298 ---
    { "word": "පාකරඤ්ජන", "meaning": "කොල්ලම් කොළ, කැකිරි", "category": "plant" },
    { "word": "පාකල", "meaning": "කොට්ටම්, තුඹගෙඩි", "category": "plant" },
    { "word": "පාකලවණ", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "පාකාලි", "meaning": "කොබෝලීල", "category": "plant" },
    { "word": "පාකි", "meaning": "කටුපිල", "category": "plant" },
    { "word": "පාකිසරණ", "meaning": "කටුපිල ගස", "category": "plant" },
    { "word": "පාක්‍ය", "meaning": "සුවසලුණු, බළල්ලුණු, යවකර ලුණු", "category": "mineral" },
    { "word": "පාවක", "meaning": "තුරුක්තෙල්", "category": "liquid" },
    { "word": "පාවකි", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "පාවන", "meaning": "අරළු, රත් එරබු", "category": "plant" },
    { "word": "පාවනී", "meaning": "දියමිත්ත, අරළු, සූරියකාන්ත", "category": "plant" },
    { "word": "පාවිනවන", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පාට", "meaning": "වැල්කපු", "category": "plant" },
    { "word": "පාටතී", "meaning": "සූරියකාන්ත", "category": "plant" },
    { "word": "පාටල", "meaning": "පලොල්", "category": "plant" },
    { "word": "පාටලා", "meaning": "රත් පලොල්, පලොල්", "category": "plant" },
    { "word": "පාටලාලි", "meaning": "රත්පලොල්", "category": "plant" },
    { "word": "පාටලාපුෂ්ප වර්ණක", "meaning": "පද්මකාෂ්ඨ", "category": "plant" },
    { "word": "පටලාසන්නිභ", "meaning": "පද්මකාෂ්ඨ", "category": "plant" },
    { "word": "පාටලි", "meaning": "රත් පලොල්, පලොල්", "category": "plant" },
    { "word": "පාටලපුෂ්ප", "meaning": "පලොල්මල්", "category": "plant" },
    { "word": "පාටවච්චා", "meaning": "කපු", "category": "plant" },
    { "word": "පාටිකා", "meaning": "පළිඟු ගල", "category": "mineral" },
    { "word": "පාටිවල", "meaning": "අක්මැල්ල, කටුවෙලුහ", "category": "plant" },
    { "word": "පාපී", "meaning": "වැල්කපු", "category": "plant" },
    { "word": "පාඨීන්", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "පාඨීම", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "පාඨා", "meaning": "ලුණුකැටියා වැල් හෝ දියමිත්ත වැල් (පාඨා වෙනුවට පෙර සිට ලක්දිව ගන්නේ දියමිත්ත වැල් ය)", "category": "plant" },
    { "word": "පාඨාදිගණය", "meaning": "පාඨා, දුම්දැවිසුදු, සිහින් මැහඟු, සිඳිඟුරු, දෙවිදුරු යන මේ ගණය, කැසි, මුස, හා උඩුකුරු වාත ගුල්ම රුජා නසන්නේ ය.", "category": "compound" },
    { "word": "පාඨිකා", "meaning": "රත්තිටුල්, දියමිත්ත", "category": "plant" },
    { "word": "පඨිව්‍යාල", "meaning": "තිටුල්", "category": "plant" },
    { "word": "පාඨි", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "පාඨින", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "පාඬුරොසි", "meaning": "බද්ධමී", "category": "plant" },
    { "word": "පාණ්ඩර", "meaning": "හිරියල්, උඩැත්ත, කෝවක්කා", "category": "mineral" },
    { "word": "පාණ්ඩරභව", "meaning": "දළුව ගස", "category": "plant" },
    { "word": "පාණ්ඩරභූරුහ", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "පාණ්ඩරා", "meaning": "මහසෙවන්, හෙළදඹ, දළුවගස, හබනගිරියා", "category": "plant" },
    { "word": "පාණ්ඩව", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "පාණ්ඩුක", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "පාණ්ඩුකණ්ටක", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "පාණ්ඩුනාරු", "meaning": "දළුව ගස, දුරු", "category": "plant" },
    { "word": "පාණ්ඩුනාග", "meaning": "දෙඹ", "category": "plant" },
    { "word": "පාණ්ඩුපත්‍ර", "meaning": "සිවිය, ගජතිප්පිලි", "category": "plant" },
    { "word": "පාණ්ඩුපත්‍රී", "meaning": "සිවිය, වටමිරිස්, (වාල්මොලගු)", "category": "plant" },
    { "word": "පාණ්ඩුඵල", "meaning": "බෙබර, දුම්මැල්ල", "category": "plant" },
    { "word": "පාණ්ඩුද්‍රැම", "meaning": "හෙළදඹ, වංඇපල, මස්වැන්න, කෙළිඳ ගස", "category": "plant" },
    { "word": "පාණ්ඩුරා", "meaning": "අගල්ආදාර", "category": "plant" },
    { "word": "පාණ්ඩුරාකාර", "meaning": "පාංශුලුණු", "category": "mineral" },
    { "word": "පාණ්ඩුරාග", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "පාණ්ඩුරී", "meaning": "නෙළුම්අල", "category": "plant" },
    { "word": "පාණ්ඩුල", "meaning": "හෙළ ජම්බු, මස්වැන්න", "category": "plant" },
    { "word": "පාණ්ඩුලොමපර්ණී", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "පාණ්ඩුලොමසා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "පාණක", "meaning": "තුරුක්තෙල්", "category": "liquid" },

    // --- පිටුව 299 ---
    { "word": "පාතන", "meaning": "ගව කිරි", "category": "food" },
    { "word": "පාතාලමධු", "meaning": "බිමගුහසේ බැඳි මීයේ පැණි", "category": "food" },
    { "word": "පාතාලමූල", "meaning": "බිම්මුල්, නියඳ", "category": "plant" },
    { "word": "පාතාලමූලී", "meaning": "බිම්තල්, ඌරල", "category": "plant" },
    { "word": "පාතාලමූලිකා", "meaning": "නියඳ", "category": "plant" },
    { "word": "පාතාලවායිනී", "meaning": "බුලත්", "category": "plant" },
    { "word": "පාතිරී", "meaning": "රත්පලොල්", "category": "plant" },
    { "word": "පාත්‍රය", "meaning": "පලම් හැට හතර (64)", "category": "measurement" },
    { "word": "පාත්‍රාඛ්‍යා", "meaning": "තලිස්පත්‍ර", "category": "plant" },
    { "word": "පාත්‍රී", "meaning": "පලොල්", "category": "plant" },
    { "word": "පාදිපා", "meaning": "හෙල්මැලි", "category": "plant" },
    { "word": "පාද", "meaning": "මුල්", "category": "plant" },
    { "word": "පාදප", "meaning": "වෘක්‍ෂය", "category": "plant" },
    { "word": "පාදකාග", "meaning": "නුග, මහනුග", "category": "plant" },
    { "word": "පාදගණ්ඩි", "meaning": "ගොප් ඇටය", "category": "anatomy" },
    { "word": "පාදපාරෝහිණී", "meaning": "දුමැඩ, සිහින් දුමැඩ", "category": "plant" },
    { "word": "පාදපාහ", "meaning": "නුග, මහ නුග", "category": "plant" },
    { "word": "පාදරෝහ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "පාදවෘක්‍ෂ", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "පාදවෘක්‍ෂ (2)", "meaning": "තොටිල", "category": "plant" },
    { "word": "පාදකෙමන්කා", "meaning": "කවුඩුලී", "category": "plant" },
    { "word": "පාදොදක", "meaning": "මෝරු", "category": "liquid" },
    { "word": "පාන්ට", "meaning": "බෙහෙත් වර්ග උණු දියෙහි බහා තේ, කෝපි මෙන් පිළියෙල කර ගන්නා ජලය.", "category": "treatment" },
    { "word": "පාන්ශුපර්‍ය්‍යාය", "meaning": "පැපිලිය, (පත්පාඩගම්)", "category": "plant" },
    { "word": "පානිගතල", "meaning": "තුන් කලඳ, අත්ල", "category": "measurement" },
    { "word": "පානිමර්ද", "meaning": "කරඹ", "category": "plant" },
    { "word": "පානිමානික", "meaning": "තුන් කලඳ", "category": "measurement" },
    { "word": "පානිය", "meaning": "දිය", "category": "liquid" },
    { "word": "පානීය මූලකා", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "පානුදි", "meaning": "බුව", "category": "plant" },
    { "word": "පාප්පඬපුල්ලු", "meaning": "පත්පාඩගම්", "category": "plant" },
    { "word": "පාපවෙලා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පාපනාශන", "meaning": "ගස් රුක්අත්තන, කරල්සැබෝ", "category": "plant" },
    { "word": "පාපමරං", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පාමස්න", "meaning": "බේරු, අත්තන, ගෙන්දගම්", "category": "plant" },
    { "word": "පාමරෝඝරා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "පාමාරි", "meaning": "ගඞක, (ගෙන්දගම්)", "category": "plant" },
    { "word": "පායස", "meaning": "සිරිවඩු, (හොරඅරටු)", "category": "plant" },
    { "word": "පායසක", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "පායුධර", "meaning": "කරල්සැබ දෙක", "category": "plant" },
    { "word": "පාඨී", "meaning": "කණේරු", "category": "plant" },
    { "word": "පාඨිකී", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "පාඨීව", "meaning": "උද්භිද ලුණු", "category": "mineral" },
    { "word": "පාරඟව", "meaning": "උද්භිද ලුණු", "category": "mineral" },
    { "word": "පාරීත", "meaning": "ගල්මද, ගල්සෙවෙල්, තුරුක් තෙල්", "category": "mineral" },
    { "word": "පාර්තී", "meaning": "මලිත, ඇටිකෙසෙල්", "category": "plant" },
    { "word": "පාමීර", "meaning": "ගොකටු (නෙරෙන්චි)", "category": "plant" },
    { "word": "පාර", "meaning": "කොබෝලීල", "category": "plant" },
    { "word": "පාරද", "meaning": "රසදිය", "category": "mineral" },
    { "word": "පාරභව", "meaning": "ලෝහ, යකඩ", "category": "mineral" },
    { "word": "පාරසය", "meaning": "කිරිබත්", "category": "food" },
    { "word": "පාරාං", "meaning": "රසලිය", "category": "plant" },
    { "word": "පාරාපත", "meaning": "උඳු, පරෙවියන්", "category": "animal" },
    { "word": "පාරාපකාඩ්ඩි", "meaning": "දුටුවැල්", "category": "plant" },
    { "word": "පාරාහෙදි", "meaning": "බටු", "category": "plant" },
    { "word": "පාරාවත", "meaning": "දුටු, යකඩ", "category": "mineral" },
    { "word": "පාරාවතපද", "meaning": "වලාවැන්න, අක්මැල්ල", "category": "plant" },
    { "word": "පාරාවතපදී", "meaning": "වලාවැන්න, දුටු", "category": "plant" },
    { "word": "පාරාවතපුරීෂ", "meaning": "පරෙවි වසුරු", "category": "animal" },
    { "word": "පාරාවාර", "meaning": "උඳු", "category": "plant" },
    { "word": "පාරිජාත", "meaning": "එරබදු, මුරුවා, මදුරා, සේපාලිකා", "category": "plant" },
    { "word": "පාරිපාදප", "meaning": "තොටිල", "category": "plant" },
    { "word": "පාරිභද්‍ර", "meaning": "බප්පල ගස් (යක්එරබදු = කටුකෑල) දේවදාර", "category": "plant" },

    // --- පිටුව 300 ---
    { "word": "පාරිභද්‍රක", "meaning": "කොහොඹ, දේවදාර, කොට්ටම්", "category": "plant" },
    { "word": "පාරිභව", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "පාරිභාය්‍ය", "meaning": "කොට්ටම්, ගොටු කොළ", "category": "plant" },
    { "word": "පාරල", "meaning": "පලොල්", "category": "plant" },
    { "word": "පාරූෂක", "meaning": "බොරළුදමුණු", "category": "plant" },
    { "word": "පාරේය", "meaning": "කොබෝලීල", "category": "plant" },
    { "word": "පාරෝහ", "meaning": "නුග මුල් (නුග අරළු)", "category": "plant" },
    { "word": "පාල්", "meaning": "කිරි", "category": "liquid" },
    { "word": "පාල්කොඩි", "meaning": "කිරිවැල්", "category": "plant" },
    { "word": "පාල්මුඩඟි", "meaning": "දත් ගස", "category": "plant" },
    { "word": "පාලක", "meaning": "මහගෙඳ, කුන්දිරුක්කන්", "category": "plant" },
    { "word": "පාලක (2)", "meaning": "තිටුල්", "category": "plant" },
    { "word": "පාලග", "meaning": "වැල් වර්ගයක් (පාලංගා)", "category": "plant" },
    { "word": "පාලන", "meaning": "ත්‍රස්තාවාලු", "category": "plant" },
    { "word": "පාලනී", "meaning": "ලුණුවිල (බැමිතිරිය)", "category": "plant" },
    { "word": "පාලමරම්", "meaning": "කිරිපලු ගස", "category": "plant" },
    { "word": "පාලවේලිකා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "පාලාවැල්", "meaning": "පාලඟ වැල්(පාල වැල් = මනමාල වැල්) බුලත්පාලා, බිම දුවන බුලත් වැලට ත් මනමාල වැල් නමැති ඇඹිල්ල කොළ වලට සමාන වැලට ත් පාලාවැල් ය යි කියති.", "category": "plant" },
    { "word": "පාලාස", "meaning": "කොල්ලම් කොළ", "category": "plant" },
    { "word": "පාලාසෝමී", "meaning": "එරබදු ගස", "category": "plant" },
    { "word": "පාලි", "meaning": "ඇපල, ගැටතිටුල්, රණහුණ, තල", "category": "plant" },
    { "word": "පාලික", "meaning": "ගැටතිටුල්, කොට්ටම්, තල", "category": "plant" },
    { "word": "පාලිකා", "meaning": "තල ඇට, රත් ගැට තිටුල්", "category": "plant" },
    { "word": "පාලිතුලෙ", "meaning": "කිරිකවෙලු", "category": "plant" },
    { "word": "පාලිඤ්ජ", "meaning": "ත්‍රස්තාවාලු, කුන්දිරුක්කන්", "category": "plant" },
    { "word": "පාලින්‍දි", "meaning": "ගැටතුඹ, කළු ත්‍රස්තාවාලු, වැල්පෙනෙල, මහ ඇඹුල්වේ.", "category": "plant" },
    { "word": "පාලින්‍ධ්‍යා", "meaning": "කළු ත්‍රස්තාවාලු", "category": "plant" },
    { "word": "පාලීත", "meaning": "ගස්පෙනෙල", "category": "plant" },
    { "word": "පාලිප්පල", "meaning": "රණහුණ", "category": "plant" },
    { "word": "පාලිභද්ද", "meaning": "එරබදු ගස", "category": "plant" },
    { "word": "පාලි (2)", "meaning": "ඇපල, රණහුණ, තල", "category": "plant" },
    { "word": "පාලෛ", "meaning": "කිරිපලු", "category": "plant" },
    { "word": "පාවකකාසි", "meaning": "කරවිල", "category": "plant" },
    { "word": "පාවක", "meaning": "රත් තිටුල්, වෙල්මුඩ, මහරි, වැල්තුඹ, වලඟසාල්", "category": "plant" },
    { "word": "පාවකාසංඥක", "meaning": "රත් තිටුල්", "category": "plant" },
    { "word": "පාවකාරනී", "meaning": "මහ මිදි", "category": "plant" },
    { "word": "පාවට්ටා", "meaning": "මේ වම් ඇපල, අගල් ආධාර, වැඩහිර, ආඩාතෝඩා (ආඩුතෝඩෙයි) යන නම් වලින් කියන ලද පැලෑටිය නොව, සුදු පාට විහිදීගිය සිහින් මල් පොකුරු ඇති වංඇපල කොළ වලට මඳක් දිගින් හා පළලින් කුඩා වූ වෙන වර්ගයකි. වංඇපල කොළ එළු කණට සමාන ය. දෙමළෙන් ආඩුතෝඩෙයි (ආඩාතෝඩා) කියන්නේ ඒ නිසා ය. පොකුරු වශයෙන් සෑදෙන එහි මල් ද සිංහමුඛාකාර ය, ඒ වර්ගයට ම සංස්කෘතයෙන් සිංහමුඛී යන නාමය ව්‍යවහාර වන්නේ ද ඒ නිසාය. පාවට්ටා කාමිලා (සෙංගමාල) පාණ්ඩු රෝග හා ආන්ත්‍රික රෝග (බඩවැලේ ආබාධ) වලට ප්‍රත්‍යක්‍ෂ තද තිත්ත රසයෙන් යුක්ත වර්ගයකි.", "category": "plant" },
    { "word": "පාවන", "meaning": "කලා, අරළු", "category": "plant" },
    { "word": "පාවම්‍ය", "meaning": "තරුණ ගස", "category": "plant" },
    { "word": "පාෂලවණ", "meaning": "පාංශුලුණු", "category": "mineral" },
    { "word": "පාෂාණි", "meaning": "එනම් උපධාතු වර්ගය", "category": "mineral" },
    { "word": "පාෂාණි (2)", "meaning": "පොල්පලා", "category": "plant" },
    { "word": "පාෂාණකුසුම", "meaning": "ගල්සෙවෙල්, ගල්මද", "category": "mineral" },
    { "word": "පාෂාණජීජ්", "meaning": "කොල්ලු", "category": "plant" },
    { "word": "පාෂාණභෙද", "meaning": "පොල්පලා, අක්කාපාන (විස්තර 2 පිටේ බලන්න)", "category": "plant" },
    { "word": "පාෂාණභෙදක", "meaning": "පොල්කුඩුපලා", "category": "plant" },

    // --- පිටුව 301 ---
    { "word": "පාෂාණභෙදි", "meaning": "පහතබෙය (පොල්පලා) කපුවල්ලිය, අක්කාපාන", "category": "plant" },
    { "word": "පාෂාණාන්තක", "meaning": "පොල්පලා, කොබෝලීල", "category": "plant" },
    { "word": "පාසි", "meaning": "දියසෙවෙල්", "category": "plant" },
    { "word": "පාසුකාසිස", "meaning": "කසිස්", "category": "mineral" },
    { "word": "පාසුපත", "meaning": "වකපුෂ්ප", "category": "plant" },
    { "word": "පාසුදරි", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "පැඟිරි", "meaning": "දෙබොක්වර්ග, (දෙහි දෙබොක් ආදී පැඟිරි ගස්වල යුෂ)", "category": "plant" },
    { 
        "word": "පැණිබැවිල", 
        "meaning": "අශ්මභෙදක පැලෑටියක්. හිත්බැවිල, මහ බැවිල, සුළු බූබැවිල, මහබූබැවිල, කොටිකන් බැවිල, සිරිවාඩි බැවිල, කේගර බැවිල, වැල් බැවිල යයි ඉන්දියානු වෙද පොත්වල බැවිල වර්ග අටක් දක්වා තිබේ. අපේ පැරණි වට්ටෝරු වෙද පොත් වල පැණි බැවිල නමින් තවත් බැවිල වර්ගයක් ගැන විස්තර ලියා තිබේ. මෙය වැඩිපුර වැවෙන්නේ සබරගමු පළාතේ ඕවිටි වල ය. මේ වර්ගයේ කොළ සුළුබූබැවිල කොළ වලට සමානය. ඊට වඩා මඳක් උල්ව ගිය දෑති සහිත මේ කොළ හැම බැවිල වර්ගයක කොළ වලට වඩා සිත් ගන්නා ස්වභාවයකින් යුක්ත යි. අඩි එකහමාරකට වඩා උස් ව නොවැවෙන මේ ගසේ කොත්තමල්ලි ඇට වැනි ඇට තිබේ. ඒ ඇට වල හැඩහුරුකම නිසා ගම්වාසීහු මෙයට වල් කොත්තමල්ලි කියා කියති. මේ ගසේ මුල් අශ්මරිගල් (ශකීරාශ්මරී) දිය කිරීමෙහි ලා ප්‍රත්‍යක්‍ෂ ඖෂධයකි.", 
        "category": "plant",
        "image": "img_301_panibavila.jpg"
    },
    { "word": "පැදුමි", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "පැන්", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "පැන්පුවක්", "meaning": "පෑන්වුරු, පෑන්වුරු, (ලපටි පුවක් = ගොලු පුවක්)", "category": "plant" },
    { "word": "පැත්මල්", "meaning": "කුසතණ", "category": "plant" },
    { "word": "පැපසරා", "meaning": "මුඛමඟන (වෙල්මුඩ)", "category": "plant" },
    { "word": "පැපිලිය", "meaning": "පත්පාඩගම්", "category": "plant" },
    { "word": "පැය", "meaning": "කලන් දහය (10)", "category": "measurement" },
    { "word": "පැරුත්ති", "meaning": "කපු ගස", "category": "plant" },
    { "word": "පැගස්", "meaning": "ඔලිඳ", "category": "plant" },
    { "word": "පැණි රස ඇති ලිය", "meaning": "වැල්මී වැල", "category": "plant" },
    { "word": "පැණිමදුලු", "meaning": "තරමක් ඉදුනු වරකා මදුළු උණු දියෙහි දමා වේලා ගන්නා අටුකොස් වර්ගය", "category": "food" },

    // --- පිටුව 302 ---
    { 
        "word": "පැණිවරා", 
        "meaning": "වරා වර්ගයක්. වරා, එළවරා, අළුවරා, පැණිවරා යයි වරා වර්ග හතරකි. මෙයින් වරා සාමාන්‍ය ඖෂධයක් වශයෙනුත්, එළවරා සර්පවිෂටත්, අළුවරා ගව වෙදකමටත්, පැණිවරා ගන්දි තෙල් වලට හා කැඩුම්-බිඳුම් වෙද කමටත් ගනිති. මුලින් කී තුන් වර්ගයේ ම කොළ, මල්, ගෙඩි හැඩහුරුකමින් සමාන ය. එහෙත් පැණිවරා වල ගම්මිරිස් කොළ වැනි උල් වූ සිහින් කොළ ඇති නිසා කොළ වලින් පමණක් අනිත් තුන් වර්ගයට වෙනස් ය. මේ සතර වර්ගය ම කිරි සහිත ය. වරා කිරි දේශීය වෙදකමේ ඇතැම් ගුප්ත චිකිත්සා ක්‍රම ගැන ප්‍රත්‍යක්‍ෂ ඖෂධයක් ලෙස ද පාවිච්චි කරති.", 
        "category": "plant",
        "image": "img_302_paniwara.jpg"
    },
    { "word": "පිංගල", "meaning": "ඉරිවේරිය, ගෝරෝචන, සුදු ඊයම්", "category": "plant" },
    { "word": "පිංජර", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "පිංජ්‍යා", "meaning": "කංසා", "category": "plant" },
    { "word": "පික්ක මාතා", "meaning": "මහමිදි", "category": "plant" },
    { "word": "පික්කාරි", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පික්මල්", "meaning": "දෙව්ලිය, (රෝසමල් යයි ඇතැම් පොතක තිබේ)", "category": "plant" },
    { "word": "පිකප්‍රියා", "meaning": "හෙළදඹ, මහ දඹ", "category": "plant" },
    { "word": "පිකබන්ධු", "meaning": "අඹ", "category": "plant" },
    { "word": "පිඟි", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "පිච්ච", "meaning": "පෙරුම්කායම්, උණකපුරු, ලොලු, ඉරිවේරිය, ගොරඳ, වැල්මදට, කහ, හිරියල්, මුද්දරප්පලම්, කුසතණ, ඊතණ, දුදු", "category": "plant" },
    { "word": "පිච්චලලෙහ", "meaning": "පිත්තල", "category": "mineral" },
    { "word": "පිච්චලා", "meaning": "ගෝරෝචන, සුදු ඊයම්, ඉරිවේරිය", "category": "plant" },
    { "word": "පිච්චා", "meaning": "මුද්‍රික ඵල, වැල්මිදි", "category": "plant" },
    { "word": "පිච්චාබඟ", "meaning": "වැල් මිදි", "category": "plant" },
    { "word": "පිච්චාබඟ හබඟිනී", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "පිච්ච", "meaning": "ගැට පිච්ච (යොහොඹු), සමන් පිච්ච (සුදු මල් ඇති වර්ගය), දසමන් (කැකුලු ලා රත් පැහැති සමන් පිච්ච වර්ගය) යයි පිච්ච වර්ග තුනකි.", "category": "plant" },
    { "word": "පිච්චට", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "පිච්චමාව", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "පිච්චිල", "meaning": "ඉඹුල්, කට්ටකුමන්ජල්", "category": "plant" },

    // --- පිටුව 303 ---
    { "word": "පිච්ච්‍ය", "meaning": "කපු", "category": "plant" },
    { "word": "පිච්ඡ", "meaning": "පුවක්, කෙසෙල්, හිඹුල්ලාටු, ඉන්සලු", "category": "plant" },
    { "word": "පිච්ඡල", "meaning": "ඇටිවේරිය, හිඹුල් ලාටු, ලේනිය පලා", "category": "plant" },
    { "word": "පිච්ඡලදල", "meaning": "මසන්", "category": "plant" },
    { "word": "පිච්ඡා", "meaning": "ඉඹුල් ලාටු, මොනර පිල්, බනිත් පෙරැ කෘද", "category": "plant" },
    { "word": "පිච්ඡිල", "meaning": "ඉඹුල් ලාටු, ඇට්ටර, (ඇටිවේරිය) ලේනිය පලා", "category": "plant" },
    { "word": "පිච්ඡිලච්ඡද", "meaning": "බෙබර, බැවිල", "category": "plant" },
    { "word": "පිච්ඡලනවී", "meaning": "බැවිල, නාරං", "category": "plant" },
    { "word": "පිච්ඡලනව", "meaning": "බැවිල", "category": "plant" },
    { "word": "පිච්ඡලනිය්‍යාස", "meaning": "හිඹුල් ලාටු", "category": "plant" },
    { "word": "පිච්ඡල පත්‍ර", "meaning": "සිහින්මසන්, පලොල්", "category": "plant" },
    { "word": "පිච්ඡල පත්‍රිකා", "meaning": "පලොල්", "category": "plant" },
    { "word": "පිච්ඡලපවනා", "meaning": "කට්ටකුමන්ජල්", "category": "plant" },
    { "word": "පිච්ඡිලස්‍රාව", "meaning": "කොමාරිකා", "category": "plant" },
    { "word": "පිච්ඡලසාර", "meaning": "හිඹුල් මැලියම්", "category": "plant" },
    { "word": "පිච්ඡලා", "meaning": "ලේනිය පලා, හිඹුල් ගස", "category": "plant" },
    { "word": "පිච්ඡිලාගුරු", "meaning": "ඇටිවේරිය", "category": "plant" },
    { "word": "පිචු", "meaning": "කපු පුළුන්, තුන් කලඳ, කපු නූල්", "category": "plant" },
    { "word": "පිචුක", "meaning": "කුකුරුමුවන්, වරා, තුන් කලඳ", "category": "plant" },
    { "word": "පිචුකස", "meaning": "තුන් කලඳ", "category": "measurement" },
    { "word": "පිචුපර්ණී", "meaning": "මුරුවා", "category": "plant" },
    { "word": "පිචුමන්‍ද", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "පිචු මර්ද", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "පිචුල", "meaning": "මිදෙල්ල", "category": "plant" },
    { "word": "පිචුණි", "meaning": "පුලුන්", "category": "plant" },
    { "word": "පිඤ්ජ", "meaning": "මොනර පිල්, කහ", "category": "plant" },
    { "word": "පිඤ්ජ්‍යා", "meaning": "කංසා", "category": "plant" },
    { "word": "පිඤ්ජර", "meaning": "නාමල් රේණු, හිරියල්, රත්රන්", "category": "plant" },
    { "word": "පිඤ්ජරා", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "පිඤ්ජුල", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "පිට", "meaning": "බට ගස", "category": "plant" },
    { "word": "පිටක", "meaning": "සුළු සාරණ", "category": "plant" },
    { "word": "පිටවක්කා", "meaning": "භූධාත්‍රි, (බිම් නෙල්ලි)", "category": "plant" },
    { 
        "word": "පිට සුදු පලා", 
        "scientific": "Boerhaavia Diffusa",
        "meaning": "සාරණ වර්ග දෙකකි. හීන් සාරණ, මහ සාරණ වශයෙනි. එයින් හීන් සාරණ හැඩහුරුකමින් ගෙඳ පලා වලට සමාන ය. මහ සාරණ ද දෙ වර්ගයකි. කොළයේ යටි පැත්ත සුදු සහ රතු වශයෙනි. පිට සුදු පලා කියන්නේ එයින් කොළයේ පිට පැත්ත සුදු වර්ගයට යි. ඖෂධ වශයෙන් ගන්නේ ද ගුණයෙන් වැඩි මේ වර්ගය යි. මෙය මූත්‍ර වර්ධනය, ආමාශ ශක්තිය හා අග්නි දීපනය කරයි. පාණ්ඩු රෝග, ජලෝදර, සෙංගමාල, මූත්‍ර කෘච්ඡ්‍රව හා ශෝථ (ඉදිමුම) යන රෝග වලට ප්‍රත්‍යක්‍ෂ ඖෂධයකි. මේ සාරණ තුන් වර්ගය ම ලාංකිකයෝ බෙහෙතක් වශයෙන් පමණක් නොව දෛනික ආහාරයක් වශයෙන් ද ප්‍රයෝජන ගනිති. රෝග නාශක ශක්තියක් ඇති මෙවැනි ඖෂධ දින පතා ආහාර වශයෙන් ගැනීම මනුෂ්‍ය ශරීරයට හිතකර ය. පිට සුදු කොළ නමින් තවත් වර්ගයක් තිබේ. එය පිට සුදු පලා (සාරණ) නොවේ.", 
        "category": "plant",
        "image": "img_303_pitasudupala.jpg"
    },

    // --- පිටුව 304 ---
    { "word": "පිටුකර", "meaning": "පිටිකර, ගලවළුව", "category": "anatomy" },
    { "word": "පිටොස්", "meaning": "කොස් ගෙඩියේ මදුලු හා ඇට කටු අතර ඇති සුදු පාට මස", "category": "plant" },
    { "word": "පිටවේ", "meaning": "පිල", "category": "plant" },
    { "word": "පිඩුකස", "meaning": "කලං තුන", "category": "measurement" },
    { "word": "පිඩුපල", "meaning": "අබ", "category": "plant" },
    { "word": "පිඬක", "meaning": "තුරුක් තෙල්", "category": "liquid" },
    { "word": "පිඬු", "meaning": "සමූහය", "category": "general" },
    { "word": "පිණ්ඩ", "meaning": "ලුණුමුඩ, යකඩ, ඝන, වච්චනාභි, රසකිඳ, නෙරිවිෂ, ඉන්සළු, හිඟුල්", "category": "compound" },
    { "word": "පිණ්ඩක", "meaning": "තලමුරු, පික්මැලි, තුරුක් තෙල්, රත්කිරි ගොකටු", "category": "plant" },
    { "word": "පිණ්ඩඛර්ජුරිකා", "meaning": "යොන් ඉඳි", "category": "plant" },
    { "word": "පිණ්ඩඛර්ජුරී", "meaning": "යොන් ඉඳි", "category": "plant" },
    { "word": "පිණ්ඩතගර", "meaning": "තුරුක් තෙල්", "category": "liquid" },
    { "word": "පිණ්ඩ පණි", "meaning": "කහ", "category": "plant" },
    { "word": "පිණ්ඩ පුෂ්ප", "meaning": "අශෝකා", "category": "plant" },
    { "word": "පිණ්ඩ පුෂ්පක", "meaning": "කුරනම්පලා", "category": "plant" },
    { "word": "පිණ්ඩ ඵල", "meaning": "යොන් ඉඳි", "category": "plant" },
    { "word": "පිණ්ඩඵලා", "meaning": "තිත්ත ලබු", "category": "plant" },
    { "word": "පිණ්ඩමුස්තා", "meaning": "කලාදුරු, ඉඟුරු", "category": "plant" },
    { "word": "පිණ්ඩ වර්ණි", "meaning": "කහ", "category": "plant" },
    { "word": "පිණ්ඩ විජ්ජක", "meaning": "කිණිහිරි", "category": "plant" },
    { "word": "පිණ්ඩා", "meaning": "කහ, දිය බෙරලිය", "category": "plant" },
    { "word": "පිණ්ඩාතක ඵල", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "පිණ්ඩාමෘතා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "පිණ්ඩාශිගු", "meaning": "පෙරුම්කායම් (පිණ්ඩ හිඟු)", "category": "plant" },
    { "word": "පිණ්ඩිත", "meaning": "මකුල් ගස", "category": "plant" },
    { "word": "පිණ්ඩී ඵලා", "meaning": "තිත්ත ලබු", "category": "plant" },
    { "word": "පිණ්ඩී පුෂ්ප", "meaning": "හෝපලු", "category": "plant" },
    { "word": "පිණ්ඩීඵල", "meaning": "තිත්ත ලබු, අඹගස", "category": "plant" },
    { "word": "පිණ්ඩී", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "පිණ්ඩීත", "meaning": "හෝපලු, තුරුක් තෙල්, ඉකිරි", "category": "plant" },
    { "word": "පිණ්ඩීතක", "meaning": "තුරුක්තෙල්, තුවරලා, කටුකරඬු, කුකුරුමාන්", "category": "plant" },
    { "word": "පිණ්ඩීතක ඵල", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "පිණ්ඩීතගර", "meaning": "තුවරලා", "category": "plant" },
    { "word": "පිණ්ඩීනා", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "පිණ්ඩීපුෂ්ප", "meaning": "හෝපලු ගස", "category": "plant" },
    { "word": "පිණ්ඩී ඵල", "meaning": "අඹගස, තිත්ත ලබු", "category": "plant" },
    { "word": "පිණ්ඩීවෘක්‍ෂ", "meaning": "හෝපලු ගස", "category": "plant" },
    { "word": "පිණ්‍යා", "meaning": "දුටු", "category": "plant" },
    { "word": "පිණ්‍යාක", "meaning": "පෙරුම්කායම්, තික, තුරුක් තෙල්", "category": "plant" },
    { "word": "පිතභ", "meaning": "පිත", "category": "anatomy" },
    { "word": "පිතතස්ති", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "පිතතසාති", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පිතතද්‍රාවිත්", "meaning": "දෙබොක්", "category": "plant" },
    { "word": "පිතතද්‍රැ", "meaning": "බාන්වැල්", "category": "plant" },
    { "word": "පිතතතාය", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පිතතප්‍රකාශ", "meaning": "කටුකරෝහණ", "category": "plant" },
    { "word": "පිතත ප්‍රනාශනි", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පිතතල", "meaning": "ලියනගලා", "category": "plant" },
    { "word": "පිතතලා", "meaning": "ඇසළ", "category": "plant" },
    { "word": "පිතතහා", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "පිතතාරි", "meaning": "පැපිලිය, රත්මානිස්ස, ලාකඩ", "category": "plant" },
    { "word": "පිත්තාප්‍රිය", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "පිතුඅට", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "පිතෘ", "meaning": "මීපැණි", "category": "food" },
    { "word": "පිත්", "meaning": "පද්මකේසර, (නෙළුම්රේණු)", "category": "plant" },

    // --- පිටුව 305 ---
    { "word": "පින්න", "meaning": "තද තිත්ත ගතියෙන් යුත් කාම රෝග නාශක පැලෑටියකි. මේ වර්ගයේ මල් පිපෙන විට කිතුල් හකුරු සුවඳක් නික්මෙයි. පින්න කොළයක කරබටු (ඉදුන එල බටු) ගෙඩියක්, දත් පව කෑල්ලක් හා තිත්ත අබින් කෑල්ලක් ඔතා උණු අළු පල්ලේ ලා තම්බා අඹරා දත මුල තැබීමෙන් දරුණු දත් පණුවන් කෑමක් වුව ද මිනිත්තු කීපයක් තුළ දී සුව වෙයි. අත්දුටුවකි.", "category": "plant" },
    { "word": "පින්නපාකු", "meaning": "පෙරුම්කායම්, නික, තලමුරුවට", "category": "plant" },
    { "word": "පින්මල්ලි", "meaning": "සෙව්වන්දි", "category": "plant" },
    { "word": "පිනක", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "පිනාශිලිය", "meaning": "වනයෙපඩ වර්ගයක් (කලුලැස්ස)", "category": "plant" },
    { "word": "පිප්ඵල", "meaning": "පලොල්, ඇසතු, තිප්පිලි, බෝ, රත්ගොකටු", "category": "plant" },
    { "word": "පිප්ඵලා", "meaning": "එලබටු, රත් ගොකටු", "category": "plant" },
    { "word": "පිප්ඵලාබහුලි", "meaning": "තුන් පුලිල", "category": "plant" },
    { "word": "පිප්ඵලී", "meaning": "වගපුල්, ඇසතු, පුලිලගස, සිවිය, සාතාවාරිය, කිරිපලු, නියඟලා", "category": "plant" },
    { "word": "පිප්ඵලී පත්‍රක", "meaning": "තුන් පුලිල", "category": "plant" },
    { "word": "පිප්ඵලී ඵලක", "meaning": "තුන් පුලිල", "category": "plant" },
    { "word": "පිප්ඵලී මූල", "meaning": "තිප්පිලි මුල්", "category": "plant" },
    { "word": "පිප්ඵලී ශිපා", "meaning": "පුලිල", "category": "plant" },
    { "word": "පිප්ඵල්‍යාදි ගණය", "meaning": "තිප්පිලි, රත් තිටුල්, වදකහ, කෙළිඳ හාල්, ගජතිප්පිලි, තිප්පිලි මුල්, කලාදුරු, සිඳිඟුරු, එන්සාල්, අතිවිඩයම්, රුහැණිය, සිවිය, මිරිස්, යදුල්, අබ, දම් දෙඹ සුදු, මුරුවා මුල්, තොටිල, කුකුරුමාන්, කළුදුරු, පෙරුම්කායම්, කුවරණ, වලඟසාල් යන මේ ගණය වා, සෙම් නසන්නේ ය.", "category": "compound" },
    { "word": "පිපිඤ්ඤා", "meaning": "කුඩා තියඹරා (තුප්‍රෂා)", "category": "plant" },
    { "word": "පිමි", "meaning": "සමුද්‍රරෝගයක්", "category": "treatment" },
    { "word": "පිය", "meaning": "කොළොම්, තුවරලා වැල, මොර ගස, පියාල ගස", "category": "plant" },
    { "word": "පියක", "meaning": "කොළොම්", "category": "plant" },
    { "word": "පියඟු", "meaning": "පුවඟු, තණහාල්", "category": "plant" },
    { "word": "පියපළු", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "පියම", "meaning": "රතිකෙළිය, ප්‍රියාව", "category": "general" },
    { "word": "පියයුරු යුෂ", "meaning": "තනකිරි", "category": "anatomy" },
    { "word": "පියයුරු රස", "meaning": "තනකිරි", "category": "anatomy" },
    { "word": "පියල්", "meaning": "මොරගස", "category": "plant" },
    { "word": "පියලි", "meaning": "වෑරහැලි", "category": "plant" },
    { "word": "පියවුරු", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "පියා", "meaning": "බක්මී, මොරගස", "category": "plant" },
    { "word": "පියාල", "meaning": "පියල් හෙවත් මොර", "category": "plant" },
    { "word": "පියුම්", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "පියුම් ගොබු", "meaning": "නෙළුම් ගොබුව, (පද්ම කර්ණිකාව) මල් කැකුල", "category": "plant" },
    { "word": "පියුමාටර", "meaning": "පියුම් ඵල", "category": "plant" },
    { "word": "පිරත්තු", "meaning": "වැටකොළු", "category": "plant" },
    { "word": "පිරන්ඩෙකොඩි", "meaning": "සිරස්ස", "category": "plant" },
    { "word": "පිරප්පත් කිලංගු", "meaning": "වේමුල්", "category": "plant" },
    { "word": "පිරප්පත් කොඩොල්", "meaning": "වේබඩ", "category": "plant" },
    { "word": "පිරම්", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "පිරමි", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "පිරායදම්", "meaning": "කිරි නෙටුල්", "category": "plant" },
    { "word": "පිරාසි", "meaning": "ගැටනෙටුල්", "category": "plant" },
    { "word": "පිරිමි පනා", "meaning": "වරකා ගස", "category": "plant" },
    { "word": "පිරිවට", "meaning": "රෙදි, පිළි", "category": "general" },
    { "word": "පිල්ල", "meaning": "කුඩුමිරිස්", "category": "plant" },
    { "word": "පිල්ලු", "meaning": "තණකොළ", "category": "plant" }
];