// data_493_506.js - පිටු 493 සිට 506 දක්වා සියලුම වචන සහ විස්තර
const data_extra_493_506 = [

    // --- පිටුව 493 ---
    { "word": "සීපද", "meaning": "ශ්ලීපද (බරපා=බරවා) රෝගය", "category": "treatment" },
    { "word": "සීමන්තනී", "meaning": "ඇසතු බෝ ගස", "category": "plant" },
    { "word": "සීමී", "meaning": "ඉස, මහරී රුක", "category": "plant" },
    { "word": "සීර", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සීරස්", "meaning": "ශිරස්ස වැල (පළු)", "category": "plant" },
    { "word": "සීරස්ස", "meaning": "වීදුරු වැල් (සිරස්ස පළු)", "category": "plant" },
    { "word": "සීරී", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "සීල", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "සීවාල", "meaning": "නඟුලේ වානේ පතුර හෝ නඟුලෙන් සාන සී විට", "category": "general" },
    { "word": "සීස", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "සීසං", "meaning": "බලුල් ලුණු, කළු තුඹ", "category": "mineral" },
    { "word": "සීසක", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "සීසපත්‍ර", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "සීසුර", "meaning": "තලා", "category": "plant" },
    { "word": "සිහනාගා", "meaning": "සිහින් කැනැස්ස", "category": "plant" },
    { "word": "සීහපුච්ඡී", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "සීහල", "meaning": "සිද්ධිගුරු, කුරුඳු", "category": "plant" },
    { "word": "සීහලප්‍රිය", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සීහිකා", "meaning": "කාමරංගා", "category": "plant" },
    { "word": "සීහුණ්ඩා", "meaning": "දළුක් ගස", "category": "plant" },
    { "word": "සුං", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සුක්‍ර", "meaning": "වරා ගස, ශුක්‍ර ධාතුව", "category": "plant" },
    { "word": "සුක්‍රද", "meaning": "වැටකේ ගස", "category": "plant" },
    { "word": "සුක්‍රමෙහ", "meaning": "ප්‍රමේහ රෝගයක්", "category": "treatment" },
    { "word": "සුක්‍රා", "meaning": "ගෝසාල වැල", "category": "plant" },
    { "word": "සුක්කං", "meaning": "සුක්ලය", "category": "general" },
    { "word": "සුකතං", "meaning": "වියළි කහ", "category": "plant" },
    { "word": "සුකතා", "meaning": "වියළි කහ", "category": "plant" },
    { "word": "සුකති", "meaning": "සක්නැබ, කලං හය (6)", "category": "animal" },
    { "word": "සුක්රා", "meaning": "ශුක්‍ර ධාතුව", "category": "anatomy" },
    { "word": "සුක්ල", "meaning": "කිරි අඟුණ", "category": "plant" },
    { "word": "සුක්ලකන්ද", "meaning": "සුදුළූනු", "category": "plant" },
    { "word": "සුක්ලක", "meaning": "මුදු පෙණ", "category": "mineral" },
    { "word": "සුක්ලතා", "meaning": "හරංකසා", "category": "plant" },
    { "word": "සුක්ලපිණ්ඩිතක", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "සුක්ලප්‍රසමනී", "meaning": "කිරි අඟුණ", "category": "plant" },
    { "word": "සුක්ල පුෂ්පා", "meaning": "අඬනහිරියා", "category": "plant" },
    { "word": "සුක්ලා", "meaning": "තුස්තවාලු, කවෙළු", "category": "plant" },
    { "word": "සුක්ලාරි මේදක", "meaning": "හෙළ ඉඟුරු", "category": "plant" },
    { "word": "සුක", "meaning": "පොණඩරු", "category": "plant" },
    { "word": "සුකණ්ටක", "meaning": "ඉඳි", "category": "plant" },
    { "word": "සුකණි", "meaning": "රතු මුතු", "category": "mineral" },
    { "word": "සුකන්‍දක", "meaning": "හබරල", "category": "plant" },
    { "word": "සුකන්දික", "meaning": "ලූහුනු", "category": "plant" },
    { "word": "සුකස්සින්", "meaning": "බිමිතල්, ලවණ, ඌරල", "category": "mineral" },
    { "word": "සුකහිටි", "meaning": "ඉඳි", "category": "plant" },
    { "word": "සුකර්ණිකා", "meaning": "මකුණුවැන්න, මිකන්පලා", "category": "plant" },
    { "word": "සුකර්ණී", "meaning": "නියඹරා", "category": "plant" },
    { "word": "සුකස්ථාන", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සුකාණ්ඩ", "meaning": "උක් ගස, කරිවිල වැල", "category": "plant" },
    { "word": "සුකාමා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "සුකාෂ්ට", "meaning": "දේවදාර", "category": "plant" },
    { "word": "සුකුන්දක", "meaning": "මුතු", "category": "mineral" },
    { "word": "සුකුන්දන", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "සුකුමාරක", "meaning": "කොල්ලන් කොළ", "category": "plant" },
    { "word": "සුකුමාරා", "meaning": "සාදික්කා, සිනිද්ද, කෙසෙල්", "category": "plant" },
    { "word": "සුකුරු", "meaning": "ශුක්‍රධාතුව", "category": "anatomy" },
    { "word": "සුකෙසර", "meaning": "දෙළුම්, චතුක්", "category": "plant" },
    { "word": "සුකොමලා", "meaning": "එරබදු", "category": "plant" },
    { "word": "සුකොලි", "meaning": "කිරිකවෙළු", "category": "plant" },
    { "word": "සුඛ", "meaning": "වී, මාදුරු, සුළු දඹ කලත්, රත් නෙළුම්", "category": "plant" },
    { "word": "සුඛ ගන්ධක", "meaning": "රතු තලා, කෑල", "category": "plant" },
    { "word": "සුඛමෝද", "meaning": "කෙනෙල් ගස", "category": "plant" },
    { "word": "සුඛවහිකා / සුඛවචිස්", "meaning": "සර්ජිකක්‍ෂාර (සුවස ලුණු)", "category": "mineral" },
    { "word": "සුඛවහික", "meaning": "සුවස ලුණු", "category": "mineral" },
    { "word": "සුඛවාස", "meaning": "කුකුරුමාන්", "category": "plant" },

    // --- පිටුව 494 ---
    { "word": "සුබස්සබ්ද", "meaning": "ශතූ", "category": "general" },
    { "word": "සුබාන්වය", "meaning": "කලාඳුරු", "category": "plant" },
    { "word": "සුබුමාරක", "meaning": "උක් ගස්, කොල්ලම් කොළ", "category": "plant" },
    { "word": "සුබොධික", "meaning": "සර්ජිකක්‍ෂාර", "category": "mineral" },
    { "word": "සුබොධභවා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "සුබොධය", "meaning": "තලිස් පතුරු", "category": "plant" },
    { "word": "සුගන්ධ", "meaning": "අතිවිඩයම්, කළුදුරු", "category": "plant" },
    { "word": "සුගන්ධි", "meaning": "අඹ", "category": "plant" },
    { "word": "සුගන්ධ (2)", "meaning": "තුරුක් තෙල්, හීන් දුරු, නිල් මහනෙල්, සඳුන්, කින්හිරි, රත් මුරුංගා, හණ, සුවස ලුණු, ගෙන්දගම්, කිනදොඹ, වී, රතු මුතු, කොල්ලම් කොළ, ගැටතුඹ", "category": "compound" },
    { "word": "සුගන්ධ (3)", "meaning": "දුරු, නිලුපුල්, සඳුන්, ග්‍රන්ථිපර්ණී, රතු මුරුංගා, ගෙන්දගම්, තඹිල, සේර", "category": "compound" },
    { "word": "සුගන්ධක", "meaning": "රතු තලා, ගෙන්දගම්, තාරම්", "category": "plant" },
    { "word": "සුගන්ධ කුසුමා", "meaning": "දාසමන්", "category": "plant" },
    { "word": "සුගන්ධ ප්‍රියඟු", "meaning": "සුවඳ පුවඟු", "category": "plant" },
    { "word": "සුගන්ධ මුද්ග", "meaning": "උළුහාල්", "category": "plant" },
    { "word": "සුගන්ධමූලා", "meaning": "අරත්ත, හිඟුරු පියලි, ඉරමුසු, ගොඩ පියුම්, (මී කබර)", "category": "plant" },
    { "word": "සුගන්‍ධා", "meaning": "ගොකටු, කඩල, හිඟුරු පියලි, අරත්ත, මල් තුඹ, අතිවිඩයම්, ශතපුෂ්ප, මහ ඉරමුසු, කරපිංචා, රතණ, සිනිද්ද, නස්නාරං, තලා, මහඑන්සාල්, රත් බෝලිද්ද, කලුදුරු", "category": "plant" },
    { "word": "සුගන්ධාව්‍ය", "meaning": "සුවස ලුණු", "category": "mineral" },
    { "word": "සුගන්‍ධා ගුරු", "meaning": "සුවඳ අගිල්", "category": "plant" },
    { "word": "සුගන්ධාමලක", "meaning": "සමීපොඩි ගණය හා සංයෝග කොට ගත් නෙල්ලි", "category": "plant" },
    { "word": "සුගන්ධී", "meaning": "කලාඳුරු, එන්සාල්, කොකවිය, සුවඳ තණ, එළ නෙළුම්, කොත්තමල්ලි, සුවස ලුණු", "category": "plant" },
    { "word": "සුගන්ධිකා", "meaning": "සුවස ලුණු, කොත්තමල්ලි, කලුදුරු, නිල් මහනෙල්, නෙළුම් අල, ජුල් (දිවුල්)", "category": "plant" },
    { "word": "සුගන්ධිකා (2)", "meaning": "වැටකේ ගස, කටුනික, ගිවුල්", "category": "plant" },
    { "word": "සුගන්ධි කුසුම", "meaning": "රත් කනේරු", "category": "plant" },
    { "word": "සුගන්ධි කුසුමා", "meaning": "දාසමන්", "category": "plant" },
    { "word": "සුගන්ධිවෘක්ෂිකා", "meaning": "සිහින් එන්සාල්", "category": "plant" },
    { "word": "සුගන්ධිත්‍රෑලා", "meaning": "සාදික්කා ගෙඩි, පූගඵල (පුවක් ගෙඩි), කරාබු ගෙඩි", "category": "plant" },
    { "word": "සුගන්ධිනී", "meaning": "රන්වන් වැටකේ, රන්වන් කනේරු", "category": "plant" },
    { "word": "සුගන්ධිමූලා", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "සුගන්ධී (2)", "meaning": "සුවස ලුණු, එන්සාල්, කින්හිරි, කුණු කරඳ, එළ නෙළුම්, තිප්පිලිමුල්, කෙකටිය, සුවඳ තණ", "category": "compound" },
    { "word": "සුගිණ", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සුගුන්ථි", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "සුග්‍ර", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සුච", "meaning": "යවකාර ලුණු", "category": "mineral" },
    { "word": "සුචක්‍ෂුස්", "meaning": "අත්තික්කා", "category": "plant" },
    { "word": "සුච්ඡත්‍රිකා", "meaning": "මහ තුඹු පලා = (මහා චඤ්චුශාක)", "category": "plant" },
    { "word": "සුජාන්වල", "meaning": "රසදිය", "category": "mineral" },
    { "word": "සුජවචික", "meaning": "සුවස ලුණු", "category": "mineral" },
    { "word": "සුජවමින්", "meaning": "කර ගස", "category": "plant" },
    { "word": "සුජවි", "meaning": "කකීටකශෘංගි", "category": "plant" },
    { "word": "සුජිත්‍ර වීජා", "meaning": "වළඟසාල්", "category": "plant" },
    { "word": "සුජිත්‍රා", "meaning": "නියඹරා", "category": "plant" },
    { "word": "සුජිත්‍රනු", "meaning": "ඉලුක්", "category": "plant" },
    { "word": "සුජිපත්‍රා", "meaning": "මහ සාරණ, නිදිකුම්බා", "category": "plant" },
    { "word": "සුජිපුෂ්ප", "meaning": "කෑල ගස", "category": "plant" },
    { "word": "සුජ්ජල", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "සුඤ්ජි", "meaning": "සිද්ධිගුරු", "category": "plant" },
    { "word": "සුත්", "meaning": "අල", "category": "plant" },
    { "word": "සුත්කට", "meaning": "වසාංවාසි", "category": "plant" },

    // --- පිටුව 495 & 496 ---
    { "word": "සුත", "meaning": "ඇල්කහඹිලියා, බුත්සරණ", "category": "plant" },
    { "word": "සුතක", "meaning": "රසදිය", "category": "mineral" },
    { "word": "සුතප්පව", "meaning": "බුත්සරණ", "category": "plant" },
    { "word": "සුතප්පක / සුතඤ්ජීව", "meaning": "බුත්සරණ", "category": "plant" },
    { "word": "සුතපාදික", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "සුතක්‍ෂාරී", "meaning": "දේවදාලිය", "category": "plant" },
    { "word": "සුතශ්‍රේනි", "meaning": "මකුණුවැන්න, නුග, මීනුග", "category": "plant" },
    { "word": "සුතිකාග", "meaning": "එරබදු ගස, බිම්කොසඹ, කොසඹ", "category": "plant" },
    { "word": "සුතික්‍ෂණ", "meaning": "මුරුංගා, වැල් මුරුංගා", "category": "plant" },
    { "word": "සුතුංග", "meaning": "පොල් ගස", "category": "plant" },
    { "word": "සුතුරා", "meaning": "නූල", "category": "general" },
    { "word": "සුතුපුෂ්පික", "meaning": "කපු ගස්", "category": "plant" },
    { "word": "සුතෙලා", "meaning": "මහ දුදු", "category": "plant" },
    { "word": "සුදත්‍රා", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "සුදණ්ඩ", "meaning": "වේවැල්", "category": "plant" },
    { "word": "සුදණ්ඩිකා", "meaning": "තාරම් ගස", "category": "plant" },
    { "word": "සුදන්තීකා", "meaning": "රත් පලොල්", "category": "plant" },
    { "word": "සුදබින්දිම", "meaning": "ප්‍රමේහ රෝග භේදයක් (ධාතු උණුකරවා යාම)", "category": "treatment" },
    { "word": "සුදර්ශිතා", "meaning": "කංසා, බූ කිඳ", "category": "plant" },
    { "word": "සුදල", "meaning": "අස්වැන්න", "category": "plant" },
    { "word": "සුදු අබ", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "සුදු උක්", "meaning": "සුදු පැහැති උක්", "category": "plant" },
    { "word": "සුදු කඳ", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "සුදු තුඹ", "meaning": "සුදු ඊයම්", "category": "mineral" },
    { "word": "සුදු දුරු", "meaning": "ශ්වේත ජීරක (සුදුරු)", "category": "plant" },
    { "word": "සුදු මහනෙල්", "meaning": "එළ මානෙල්", "category": "plant" },
    { "word": "සුදු වැටකොළු", "meaning": "සුදු වැටකොලු", "category": "plant" },
    { "word": "සුදු වෙල්ලන්ගිරිය", "meaning": "බෙහෙතට ගන්නා වෙල්ලන් ගිරිය වර්ගය. සුදු - කළු භේදයෙන් වෙල්ලන්ගිරිය දෙවර්ගයකි. මේ වැල් ගැන විස්තරයක් 448 පිටේ ඇත.", "category": "plant" },
    { "word": "සුදුසුරමෙත්තා", "meaning": "සුදු හඳුන්", "category": "plant" },
    { 
        "word": "සුදු හඳුන්", 
        "scientific": "Santalum Album",
        "meaning": "<b>Santalum Album-සුදු හඳුන් (ශ්වේත චන්දන / සොගන්ධී)</b><br><br>කටරොළු වැල් කොළ වැනි විශාල හැඩයෙන් යුත් කුඩා කොළ-වාර්ණියා මල් පොකුරු වැනි සිහින් මල් පොකුරු හා බෝල කසල ඇට පමණ කුඩා ගෙඩි (ඇට) පොකුරු ඇති සුදු හඳුන් ගස පෙර-අපර දෙ දිගට ම අයත් ඕස්ට්‍රේලියා - පර්සියා - ජාවා - සුමාත්‍රා - ඉන්දියා - ලංකා යන රට වල මැනවින් වැවෙයි.<br><br>මේ ගසේ සුගන්ධවත් වූ මල් හා හර (අරටු) පෙර-අපර දෙදිග ම ඖෂධ සඳහා ගනිති. එයිනුත් අනාදිමත් කාලයක සිට පෙර දිග රට වල මේ වර්ගය ඖෂධයක් වශයෙන් යොදති.<br><br>ඒ ඒ රට වල දේශගුණය අනුව මේ වර්ගයේ සුවඳ - රස ගුණ - ඕජා හා වර්ණය ත් වෙනස් වන බව පෙනේ. ඕස්ට්‍රේලියාවේ හා උතුරු ඉන්දියාවේ වැවෙන සුදු හඳුන් හර දුඹුරු සුදු වර්ණයෙන් යුක්ත යි. සුගන්ධය ද අධික යි.<br><br>මයිසූර් රාජ්‍යයේ ප්‍රසිද්ධ පාර වල සෙවන සඳහා දෙපේලියට අතරින් අතර සිටුවා තිබෙන්නේ සුදු හඳුන් සහ හොද අඹ වර්ග ය. අඹ ගස් වලින් මඟ යන එන්නන්ට තාවකාලික ප්‍රයෝජනයකුත්, සුදු හඳුන් ගස් වලින් සහ අඹ ලී වලින් රජයට විශාල ජාතික ආදායමකුත් නො දැනුවත්ව ම වාගේ ලැබේ. එහෙත් අපේ රටේ පාර දෙපස හෙවනට සිටුවා තිබෙන්නේ රට මාරා ගස් ය.<br><br>සුදු හඳුන් ප්‍රමේහ රෝග නාශක ඖෂධයකි. මෙහි ඇති සිසිල් ගුණය මනුෂ්‍ය ශරීරයට හිතකර ය. මේ පිළිබඳ කෂාය, අරිෂ්ට, ආසව, ගුලි, කල්ක, ගිත කෂාය ආදි හැම එකකට ම සුදු හඳුන් අවශ්‍ය වේ. හඳුන් තෙල් ඖපසර්ගික මේහය (සුදු බින්දුම) ට දෙන ප්‍රධාන ඖෂධයකි. සුදු හඳුන් - ජාතික සුවඳ ද්‍රව්‍යයකි. ආගමික ශුද්ධ වස්තුවකි.", 
        "category": "plant",
        "image": "img_santalum_album_sudu_handun.jpg"
    },
    { "word": "සුදු මුතු", "meaning": "එළ මුතු", "category": "mineral" },
    { "word": "සුධශිර", "meaning": "කපෝතාඤ්ජන (කොබෙයියන් මැටි=ගොයදුන්) ඉදිරියෙහි ඇති ගොයදුන් විස්තරය බලන්න.", "category": "mineral" },
    { "word": "සුධගිලා", "meaning": "පලිඟු", "category": "mineral" },
    { "word": "සුධා", "meaning": "හුනු, වතුර, නෙල්ලි, මුරුවා, දළුක්, මහ උක්, අරළු, මීපැණි, අස්වැන්න", "category": "plant" },
    { "word": "සුධාංශු", "meaning": "කපුරු", "category": "plant" },
    { "word": "සුධාංශුතෙල", "meaning": "කපුරු තෙල්", "category": "liquid" },
    { "word": "සුධාංශුරත්න", "meaning": "මුතු", "category": "mineral" },
    { "word": "සුධාබග", "meaning": "කපුරු", "category": "plant" },
    { "word": "සුධාජ්චින්", "meaning": "ලුණු", "category": "mineral" },
    { "word": "සුධාධාර / සුධානිධි", "meaning": "කපුරු", "category": "plant" },
    { "word": "සුධාපයස්", "meaning": "දළුක් ගස", "category": "plant" },
    { "word": "සුධාපාසානක", "meaning": "හුණු ගල්", "category": "mineral" },
    { "word": "සුධාභඃ(සූ)ති", "meaning": "කපුරු", "category": "plant" },
    { "word": "සුධාමුලි", "meaning": "නරී අල, (ශාලාමිශ්‍රී-මෙය රසායන බෙහෙතකි)", "category": "plant" },
    { "word": "සුධාමොදක / සුධාසීත / සුධාවාස", "meaning": "කපුරු, ඉඹුල්", "category": "plant" },
    { "word": "සුධාශ්‍රවා", "meaning": "දත්ත", "category": "plant" },
    { "word": "සුධෝත්භවා", "meaning": "අරළු", "category": "plant" },
    { "word": "සුන්", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සුන්සි", "meaning": "සිද්ධිගුරු", "category": "plant" },
    { "word": "සුන්දර", "meaning": "ගෝමේද, නිල් මානෙල්", "category": "mineral" },
    { "word": "සුන්මුරුන්කෙ", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සුනංකාරී", "meaning": "ඉරමුසු වැල", "category": "plant" },
    { "word": "සුනක", "meaning": "රසදිය", "category": "mineral" },
    { "word": "සුනකට", "meaning": "කුරුඳු පොතු", "category": "plant" },
    { "word": "සුනන්ද", "meaning": "ගෝරෝචන", "category": "plant" },
    { "word": "සුනන්‍දා", "meaning": "සප්සඳ, අක්පත්‍රී වෘක්‍ෂ", "category": "plant" },
    { "word": "සුනන්නාරී", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "සුනඛ", "meaning": "දිවුල්", "category": "plant" },
    { "word": "සුනා", "meaning": "වේලා ගස", "category": "plant" },
    { "word": "සුනාලක", "meaning": "මූණමල් ගස", "category": "plant" },
    { "word": "සුනිසාස", "meaning": "බටුවද", "category": "plant" },
    { "word": "සුනිර්ගුණ්ඩි", "meaning": "කළුතලා, නික", "category": "plant" },
    { "word": "සුනිර්‍ය්‍යාස", "meaning": "අලරිය, කණේරු", "category": "plant" },
    { "word": "සුනිල", "meaning": "දෙළුම් ගස, කටරොළු වැල", "category": "plant" },

    // --- පිටුව 497 ---
    { "word": "සුනිස", "meaning": "කිඹුල්වැන්න", "category": "plant" },
    { "word": "සුනිසන්", "meaning": "කිඹුල්වැන්න", "category": "plant" },
    { "word": "සුනිසන්න", "meaning": "කිඹුල්වැන්න", "category": "plant" },
    { "word": "සුනිසන්නක", "meaning": "කිඹුල්වැන්න,(පලා පෙති)ඇඹුල්ඇඹිලිය", "category": "plant" },
    { "word": "සුනිසන්නපත්‍රක", "meaning": "ඇඹුල් ඇඹිලිය මෙය හොඳ ශාක විශේෂයකි. ග්‍රහණී අතිසාරාදි රෝග වලදී ආහාර සමග දෙනු ලබති.", "category": "plant" },
    { "word": "සුනිහන්ව", "meaning": "කුණුකරඳ", "category": "plant" },
    { "word": "සුනීල", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "සුනීලක", "meaning": "නිල්කිකිරිදිය", "category": "plant" },
    { "word": "සුනුසන්", "meaning": "කිඹුල්වැන්න", "category": "plant" },
    { "word": "සුප්", "meaning": "මල්", "category": "plant" },
    { "word": "සුප්ත", "meaning": "පලම් දහසය", "category": "general" },
    { "word": "සුප්තියා", "meaning": "කලං හය", "category": "general" },
    { "word": "සුප්‍රපර්ණී", "meaning": "මුවැන්න", "category": "plant" },
    { "word": "සුපත්කාර", "meaning": "හෙළ නෙළුම්", "category": "plant" },
    { "word": "සුපත්‍ර", "meaning": "හෙළ නෙළුම්, සාතාවාරිය, පාලංගා", "category": "plant" },
    { "word": "සුපත්‍රක", "meaning": "මුරුංගා, ආපසුමුදු", "category": "plant" },
    { "word": "සුපත්‍රාධ", "meaning": "හෙළ හිඹුරු", "category": "plant" },
    { "word": "සුපර්ණී", "meaning": "නාමල්රේණු, ඇසළ, රුක් අත්තන, හරේනුක, කෑල, රන්වන් කිරිපලා", "category": "plant" },
    { "word": "සුපර්වා", "meaning": "සුදු රතණ", "category": "plant" },
    { "word": "සුපරි", "meaning": "පුවක්", "category": "plant" },
    { "word": "සුපල", "meaning": "මුදිකප්පල (මිදිවැල)", "category": "plant" },
    { "word": "සුපවිත්‍ර", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "සුපාක්‍ය", "meaning": "බලුල් ලුණු", "category": "mineral" },
    { "word": "සුපාක", "meaning": "වැල්තුඹ", "category": "plant" },
    { "word": "සුපාර්ශ්ව", "meaning": "තෙලඹු, පුවිල, තුන් පුවිල", "category": "plant" },
    { "word": "සුපාරශ්වක", "meaning": "කරබෙහිය", "category": "plant" },
    { "word": "සුපිඞ්ගලා", "meaning": "දිවුල්, බුලත්", "category": "plant" },
    { "word": "සුපුෂ්පිකා", "meaning": "ආපසුමුදු", "category": "plant" },
    { "word": "සුපුෂ්කරා", "meaning": "ගොඩනෙළුම්,(මිතඹර)", "category": "plant" },
    { "word": "සුපුෂ්කලා", "meaning": "මැණික්වැන්න", "category": "plant" },
    { "word": "සුපුෂ්ප", "meaning": "පලොල්", "category": "plant" },
    { "word": "සුපුෂ්පක", "meaning": "හෝපළු, පොණඩරු", "category": "plant" },
    { "word": "සුපුෂ්පී", "meaning": "සුදු කටරොළු, ශතපුෂ්ප, උළුවා, ගැටතුඹ", "category": "plant" },
    { "word": "සුපුර", "meaning": "දෙළුම්, උප්නාරන්", "category": "plant" },
    { "word": "සුපුරක", "meaning": "මූණමල් ගස", "category": "plant" },
    { "word": "සුපුත්තර", "meaning": "මාදම්, දිවුල්", "category": "plant" },
    { "word": "සුප්‍රසර්ණී", "meaning": "මුවැන්න", "category": "plant" },
    { "word": "සුප්‍රභ", "meaning": "පද්මකාෂ්ඨ", "category": "plant" },
    { "word": "සුප්‍රසරා", "meaning": "ආපසුමුදු", "category": "plant" },
    { "word": "සුප්‍රසස්‍ය", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "සුප්‍රියා", "meaning": "ගොටුකොළ", "category": "plant" },
    { "word": "සුඵල", "meaning": "දෙළුම්, වෙඬරු, මුං, කින්හිරි, ජුල්, නියඹරා, කොමඩු පුහුල්, කෙසෙල්", "category": "plant" },
    { "word": "සුඵලා", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "සුබඞ්", "meaning": "තලගස", "category": "plant" },
    { "word": "සුභ", "meaning": "කයිප්, පළුගස", "category": "plant" },
    { "word": "සුභග", "meaning": "හෝපළු, සපුගස, රතු උඳු පියලි, පුෂ්කර, කොටවිලයාමුරු, අස්වැන්න, කහ, නිල්රතණ, පුවඟු, තලා, කස්තුරි, රත් කෙසෙල්, සිනිද්ද", "category": "plant" },
    { "word": "සුභගා", "meaning": "පොල්ගස", "category": "plant" },
    { "word": "සුභවභා", "meaning": "පුවඟු", "category": "plant" },
    { "word": "සුභද්‍ර", "meaning": "තුස්තවාලු, බෙලි, බැමිතිරිය, දේවදාර", "category": "plant" },
    { "word": "සුභද්‍රා", "meaning": "කොසඹ, කළුඉරමුසු, ඇත්දෙමට", "category": "plant" },
    { "word": "සුභා", "meaning": "හරංකහ, උණකපුරු, සාතාවාරිය", "category": "plant" },
    { "word": "සුභි", "meaning": "කදඹ, බක්මී", "category": "plant" },
    { "word": "සුභික්‍ෂා", "meaning": "මයිල ගස", "category": "plant" },
    { "word": "සුභීරක", "meaning": "කෑලගස", "category": "plant" },
    { "word": "සුභූති", "meaning": "බෙලි ගස", "category": "plant" },

    // --- පිටුව 498 ---
    { "word": "සුඹුළු", "meaning": "පොතු", "category": "general" },
    { "word": "සුම", "meaning": "කපුරු, මල්", "category": "plant" },
    { "word": "සුමං", "meaning": "සපු, පිච්ච", "category": "plant" },
    { "word": "සුමඞ්ගලා", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "සුමති", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "සුමදන", "meaning": "අඹගස", "category": "plant" },
    { "word": "සුමන", "meaning": "තිරිඟු, අත්තන, සමන්, සාදික්කා, බටුවද, නුග, වසාංවාසි, මාදම්, කරඳ, සිරිල, කොල්ලු", "category": "plant" },
    { "word": "සුමනං", "meaning": "පිච්ච", "category": "plant" },
    { "word": "සුමනඃපත්‍රිකා", "meaning": "වසාංවාසි", "category": "plant" },
    { "word": "සුමනඃඵල", "meaning": "ජුල්ගස, (දිවුල්ගස) සාදික්කා, උප්නාරම්", "category": "plant" },
    { "word": "සුමනඃපලම්", "meaning": "උප්නාරම්", "category": "plant" },
    { "word": "සුමනයත්", "meaning": "වසාංවාසි, දාසමන්", "category": "plant" },
    { "word": "සුමනඵල", "meaning": "උප්නාරම්", "category": "plant" },
    { "word": "සුමනස්", "meaning": "දාසමන් මල්", "category": "plant" },
    { "word": "සුමනස", "meaning": "කරබෙහිය", "category": "plant" },
    { "word": "සුමනා", "meaning": "දාසමන්, තිරිඟු", "category": "plant" },
    { "word": "සුමනාවල", "meaning": "උප්නාරන්", "category": "plant" },
    { "word": "සුමලි", "meaning": "බින්තල්", "category": "plant" },
    { "word": "සුමලේරූප", "meaning": "බටුවද", "category": "plant" },
    { "word": "සුමුඛ", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "සුමූල", "meaning": "අස්වැන්න, පුස්වැන්න", "category": "plant" },
    { "word": "සුමෙධස්", "meaning": "දූදු", "category": "plant" },
    { "word": "සුර්ප", "meaning": "ද්‍රෝණ 2 ක්, (පත 128, ලාස් 2)", "category": "general" },
    { "word": "සුර්පපර්ණී", "meaning": "මුවැන්න", "category": "plant" },
    { "word": "සුයතී", "meaning": "වෑක්", "category": "plant" },
    { "word": "සුහක්තා", "meaning": "කොබෝවක්කා", "category": "plant" },
    { "word": "සුරක්ත", "meaning": "ඇසටු", "category": "plant" },
    { "word": "සුරක්තක", "meaning": "කොහු අඹ, සිවංගුරු", "category": "plant" },
    { "word": "සුරක්‍ෂඃ", "meaning": "කොසඹ, මදටිය", "category": "plant" },
    { "word": "සුරක්‍ෂාඞ්ගු කොඩි", "meaning": "ගස් සැහඬිලියා", "category": "plant" },
    { "word": "සුරඛග", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "සුරඞ්ගක", "meaning": "පතඟි, වැල්මදට", "category": "plant" },
    { "word": "සුරඞ්ගධාතු", "meaning": "සිවංගුරු", "category": "mineral" },
    { "word": "සුරඞ්ගා", "meaning": "කොටඩිඹුලා", "category": "plant" },
    { "word": "සුරඞ්ගිකා", "meaning": "මුරුවාවැල්", "category": "plant" },
    { "word": "සුරඞ්ගී", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "සුරක්‍ෂපා", "meaning": "පුවක්", "category": "plant" },
    { "word": "සුරණ", "meaning": "කිඩාරන්", "category": "plant" },
    { "word": "සුරත්හර", "meaning": "රත්හඳුන්, දේවදාර", "category": "plant" },
    { "word": "සුරතංව්‍ය", "meaning": "රසදිය", "category": "mineral" },
    { "word": "සුරතබහපු", "meaning": "මදනකාමපු (349 පිටේ මදනකාමපු ගැන ලියා ඇති විස්තරය බලන්න)", "category": "plant" },
    { "word": "සුරතාරුත්", "meaning": "දේවදාර", "category": "plant" },
    { "word": "සුරති", "meaning": "කරබෙහිය, මාදම්, ගිරමුසු", "category": "plant" },
    { "word": "සුරදාර / සුරදාරු", "meaning": "දේවදාර", "category": "plant" },
    { "word": "සුරදුන්දුහී", "meaning": "තලා", "category": "plant" },
    { "word": "සුරද්‍රැම", "meaning": "දේවදාර", "category": "plant" },
    { "word": "සුරධූප", "meaning": "දුම්මල", "category": "plant" },
    { "word": "සුරපර්ණික", "meaning": "දෙඹ", "category": "plant" },
    { "word": "සුරපර්ණී", "meaning": "කෑල", "category": "plant" },
    { "word": "සුරපුණ්ණාග", "meaning": "දෙඹ ගස, කිනදෙඹ, කින", "category": "plant" },
    { "word": "සුරප්‍රිය", "meaning": "කතුරු, සාදික්කා, කෙනෙල්", "category": "plant" },
    { "word": "සුරබි", "meaning": "මාදම්ගස, ඉරමුසු වැල, කරපිංචා", "category": "plant" },
    { "word": "සුරභි", "meaning": "සාදික්කා, සැමගස, කෙහෙල්, තලා, මූණමල්, දුම්මල, සිනිද්ද", "category": "plant" },
    { "word": "සුරභිඃ", "meaning": "කටුකුමන්ජල්", "category": "plant" },
    { "word": "සුරභිගන්ධිකා", "meaning": "ගිවුල්", "category": "plant" },
    { "word": "සුරභිච්ඡද", "meaning": "කරබෙහිය, ජුල්", "category": "plant" },
    { "word": "සුරභිභව", "meaning": "මහ එන්සාල්", "category": "plant" },
    { "word": "සුරභිදාරු", "meaning": "හොරගස", "category": "plant" },
    { "word": "සුරභිපත්‍රා", "meaning": "ජම්බු, මහ ජම්බු", "category": "plant" },
    { "word": "සුරභිපත්‍රිකා", "meaning": "මාදම්", "category": "plant" },
    { "word": "සුරභිපුණ්ණාග", "meaning": "කිනදොඹ", "category": "plant" },

// --- පිටුව 499 ---
    { "word": "සුරභිභූෂණ", "meaning": "ගොකටු", "category": "plant" },
    { "word": "සුරභිමුද්ගකා", "meaning": "උළුවා", "category": "plant" },
    { "word": "සුරභිවල්කල", "meaning": "කුරුඳුපොතු", "category": "plant" },
    { "word": "සුරභිශල", "meaning": "සපුගස", "category": "plant" },
    { "word": "සුරභිශ්‍රවා", "meaning": "කෙහෙල්", "category": "plant" },
    { "word": "සුරහී", "meaning": "කළුතලා", "category": "plant" },
    { "word": "සුරහිරසා", "meaning": "ඉන්සළු", "category": "plant" },
    { "word": "සුරමානා", "meaning": "කඩල", "category": "plant" },
    { "word": "සුරමෘත්තිකා", "meaning": "සුදු පාසානම්, නගර, වණිවක් මැටි", "category": "mineral" },
    { "word": "සුරමේද සමුද්භව", "meaning": "මේවන්", "category": "plant" },
    { "word": "සුරමේදු", "meaning": "මහමේවන්", "category": "plant" },
    { "word": "සුරරාජක", "meaning": "පියාගස", "category": "plant" },
    { "word": "සුරලතා", "meaning": "මහදුදු", "category": "plant" },
    { "word": "සුරලාරාම්", "meaning": "මීවැල", "category": "plant" },
    { "word": "සුරවපා", "meaning": "නාගිරිය (නෙරිවිස)", "category": "plant" },
    { "word": "සුරවර්ණිකා", "meaning": "දෙඹ", "category": "plant" },
    { "word": "සුරවෘක්‍ෂ / සුරවෘත්ත", "meaning": "කෑලගස", "category": "plant" },
    { "word": "සුරවල්ලභා", "meaning": "සුදු රතණ", "category": "plant" },
    { "word": "සුරවල්ලී", "meaning": "තලා", "category": "plant" },
    { "word": "සුරශ්‍රේෂ්ඨ", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "සුරස", "meaning": "පොත්ත, හෙළ නික, වසාංවාසි, නික, සුවඳතණ, ඉඹුල් ලාටු, තලා, අරත්ත, උළුවා, බැමිතිරිය, මහ සාතාවාරිය, බැවිල", "category": "plant" },
    { "word": "සුරසා", "meaning": "තලා, අරත්ත", "category": "plant" },
    { "word": "සුරසාදිගණය", "meaning": "තලා, හෙළ තලා දෙක, තුවර, අඳුතලා, රතු අක්මැල්ල, බැළතණ, (කරවකල=වෙණුතණ) නික, උඩැත්ත, (රියකොළ) දුමැඩ කොළොම්, සුවඳ තලා, (හිරමුසු) අබ, කළුඅක්මැල්ල, රේරු, සිහින් අක්මැල්ල, වළඟසාල්, කළු කැම්මේරිය, මුරුවා, කොතුරබැද්ද, (මිකන්පලා) ඇත්දෙමට යන මේ සුරසාදි ගණය. පණුරෝග, සෙම් රෝග, කාසය, අරුචි, ප්‍රතිශ්‍යා, ශ්වාස හා වණ රෝග නසන්නේ ය.", "category": "compound" },
    { "word": "සුරසාං", "meaning": "කළුතලා", "category": "plant" },
    { "word": "සුරසොද්භව", "meaning": "මයිල ගස", "category": "plant" },
    { "word": "සුරා", "meaning": "රා, ආපසුමුදු, අරක්කු", "category": "liquid" },
    { "word": "සුරාග", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "සුරාජක", "meaning": "කිකිරිදිය", "category": "plant" },
    { "word": "සුරාහසී", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "සුරාල", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "සුරාශ්‍රය", "meaning": "යොහොඹු", "category": "plant" },
    { "word": "සුරාෂ්ට්‍රජ", "meaning": "කලුමුං, තුවර", "category": "plant" },
    { "word": "සුරාෂ්ට්‍රජා", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "සුරාහ්ව", "meaning": "දේවදාර, කුකුරුමාන්, හීන් තලා, කහ", "category": "plant" },
    { "word": "සුරාබහ", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සුරාස", "meaning": "අස්වැන්න, සිරිතේක්කු", "category": "plant" },
    { "word": "සුරාහක", "meaning": "තෙලසබු", "category": "plant" },
    { "word": "සුරේ", "meaning": "එරමිණියා", "category": "plant" },
    { "word": "සුරොජක", "meaning": "දේවදාර", "category": "plant" },
    { "word": "සුරොත්තර", "meaning": "සඳුන්", "category": "plant" },
    { "word": "සුලන්සිල්", "meaning": "හුලන්හික්ගස්", "category": "plant" },
    { "word": "සුලහ", "meaning": "අඹ, මුංවැන්න, දුම්කොළ", "category": "plant" },
    { "word": "සුලශ්වල", "meaning": "තල්ගස", "category": "plant" },
    { "word": "සුළුඅංකෙන්ද", "meaning": "හීන් අන්කෙන්ද ගස", "category": "plant" },
    { "word": "සුළුකරඹ", "meaning": "හීන්කරඹ", "category": "plant" },
    { "word": "සුළුකුඹුක්", "meaning": "හීන් කුඹුක්ගස", "category": "plant" },
    { "word": "සුළුකූර", "meaning": "හීන්කූරතම්පලා", "category": "plant" },
    { "word": "සුළුගත", "meaning": "අස්වැන්න, පුස්වැන්න", "category": "plant" },
    { "word": "සුළුගෙලඩිය", "meaning": "මුංවැන්න, (කුඩා කොල්ලු)", "category": "plant" },

    // --- පිටුව 500 ---
    { 
        "word": "සුළුනයි", 
        "meaning": "<b>සුළුනයි—කුඩා පැළෑටියක්</b><br><br>නයි පෙනෙයක හැඩහුරු කමින් යුත් තණකොළ සමග වැවෙන මුඟුණුවැන්න වැනි පැළෑටියකි. අඳුන් කිකිරිදිය වල මෙන් පුරුක් මුල දෙපසට විහිදී ගිය කොළ ඇත. මුදුනෙහි උඳු පියලි කොළයකට ත් වඩා කුඩා රත් ඉරි වලින් යුත් මල් හට ගණ් යි.<br><br>මේ පැළෑටිය කුඩා ය. හැම තැනම තිබෙන නිසා සුලභ ය. එහෙත් මෙය ඇස පිළිබඳ කරුණු වලදී පුදුම දේවල් කළ හැකි පැළෑටියකි. මේ කොළ විකා හකුදෙකේ තබා ගෙන කෑමෙන් පමණක් වැලි දෙ ඇස් වල පුරවා ගත හැකි යි. ඇස් වලට කිසිම තුවාලයක් හෝ වේදනාවක් නැතිව ඒ වැලි පිටවී යයි. එසේ ම ඇසේ ගල්-වැලි ආදියක් තිබියදී මේ කොළ ඉස්ම ස්වල්පයක් ඇසට වත්කළොත් ඒ වැලි ඇස කපා ගෙන ඇතුලට කාවදියි. ඒවා අස්කළ හැක්කේ ශල්‍යකර්මයකින් පසුව ය.<br><br>එසේ ම තුවාලයකින් ඇස ඇතුලේ ලේ පිටවී යේ නම් අමු කහ ස්වල්පයක් සමග මේ කොළ කොටා ගත් ඉස්ම ඇසට මිරිකීමෙන් දින තුනකින් සම්පූර්ණ සුවය ලැබේ.", 
        "category": "plant",
        "image": "img_sulunayi.jpg"
    },
    { "word": "සුළුනික", "meaning": "හින්නික ගස", "category": "plant" },
    { "word": "සුළුපස්මුල්ගණය", "meaning": "(සුළුපහ) එළබටු, කටුවැල්බටු, අස්වැන්න, පොල්පලා, ගොකටු, (නෙරෙංචි) (අප රටේ පෘෂ්ණිපර්ණී (පුස්වැන්න) වෙනුවට පොල්පලා ද, ශාලිපර්ණී (සල්වැන්න) වෙනුවට අස්වැන්න ද සුළු පස් මුලට පෙර සිට ම යොදන බව පෙනේ.) මේ ගණයෙන් වා, පිත්, නසන්නේ ය.", "category": "compound" },
    { "word": "සුළුපෝටා", "meaning": "හීන් පුවටා වැල", "category": "plant" },
    { "word": "සුළුබූරුද", "meaning": "සාරණ", "category": "plant" },
    { "word": "සුළුමී", "meaning": "කණවෙයියා පැණි", "category": "liquid" },
    { "word": "සුළු මෑ", "meaning": "හීන්මෑවැල", "category": "plant" },
    { "word": "සුළුමුරුත", "meaning": "හීන්මුරුත ගස", "category": "plant" },
    { "word": "සුළුමෙවන්", "meaning": "කුඩාශාලාමිශ්‍රී (මේදා)", "category": "plant" },
    { "word": "සුළුරත්ත", "meaning": "හීන්අරත්ත", "category": "plant" },
    { "word": "සුලොමශා", "meaning": "කොටඩිඹුලා, අක්මැල්ල, මුරුවා", "category": "plant" },
    { "word": "සුලොමා", "meaning": "වැල්මදට", "category": "plant" },

    // --- පිටුව 501 ---
    { "word": "සුලොහිතා", "meaning": "ලියනඟලා හෙවත් ගින්දිවි වැල", "category": "plant" },
    { "word": "සුව", "meaning": "යොහොඹු", "category": "plant" },
    { "word": "සුවඟුර", "meaning": "සිවංගුරු", "category": "mineral" },
    { "word": "සුවණ්ණං", "meaning": "රත්‍රං", "category": "mineral" },
    { "word": "සුවතුරා", "meaning": "මහරී, මාරා, මිදටගස", "category": "plant" },
    { "word": "සුවඳ", "meaning": "හීන්හෙද", "category": "plant" },
    { 
        "word": "සුවඳ අගිල්", 
        "scientific": "Aquilaria Agallocha",
        "meaning": "<b>Aquilaria Agallocha-සුවඳ අගිල්—අගරු</b><br><br>අගිල් දිග - පළල අඟල් 3 1/2 x 3/4 ක් පමණ ඇති නා කොළ වලට නැතහොත් කොරකහ කොළ වලට සමාන කොළ ඇති ගසකි.<br><br>මේ ගසෙන් කෘෂ්ණාගරු, කාෂ්ඨාගරු, දාහාගරු, මීබඟලයාගරු, අගරු යයි මැලියම් වර්ග පහක් ලැබෙන බව ඉන්දියානු නිඝණ්ඩු වල විස්තර කර තිබේ.<br><br>මේ මැලියම් ආසියාතික රටවල පෙර සිටම භාවිත වන ශුද්ධ වූ සුවඳ ද්‍රව්‍යයකි. අගිල් හර (අරටු) රත්කිහිරි හර මෙන් තද ය. ශේෂ වර්ණයෙන් (ගුරු පාටින්) යුක්ත ය. මේ හර ඖෂධ සඳහා ගනිති.", 
        "category": "plant",
        "image": "img_aquilaria_agallocha_suwanda_agil.jpg"
    },
    { "word": "සුවඳතලා", "meaning": "හිරමුසු", "category": "plant" },
    { "word": "සුවඳපස", "meaning": "කපුරු, සඳුන්, කස්තුරි, කොකුම්, පිනිදිය", "category": "compound" },
    { "word": "සුවඳහොට", "meaning": "සැවැන්දරා", "category": "plant" },
    { "word": "සුවදැල්", "meaning": "සුවඳහාල්, (ධාන්‍ය) සුවදැල් (කෙසෙල්)", "category": "plant" },
    { "word": "සුවන්ගුරු", "meaning": "සවර්ණගෛරික නම් උපධාතු විශේෂය", "category": "mineral" },
    { "word": "සුවර්චක", "meaning": "ආපසුමුදු, සුවසලුණු", "category": "plant" },
    { "word": "සුවර්චල", "meaning": "කොබෝවක්කා", "category": "plant" },
    { "word": "සුවර්චිකා", "meaning": "යවකාරලුණු, සුවසලුණු", "category": "mineral" },
    { "word": "සුවර්චිත්", "meaning": "සර්ජිකක්‍ෂාර", "category": "mineral" },
    { "word": "සුවර්චිලා", "meaning": "කෝවක්කා, සුවසලුණු", "category": "plant" },
    { "word": "සුවර්ණ", "meaning": "රත්හඳුන්, සිවංගුරු, නාමල්රේණු, අත්තන, යොහොඹු, රත්‍රන්, රත්ගුගුල්, සෙන්කොට්ටම්, කෑල", "category": "mineral" },
    { "word": "සුවර්ණක", "meaning": "පින්තල, ඇසළ, රුක්අත්තන", "category": "plant" },
    { "word": "සුවර්ණකය", "meaning": "තුන් කලඳ", "category": "general" },
    { "word": "සුවර්ණගෛරික", "meaning": "සුවංගුරු", "category": "mineral" },
    { "word": "සුවර්ණනාකුලී", "meaning": "මහදුදු", "category": "plant" },
    { "word": "සුවර්ණපුෂ්පී", "meaning": "ඇසළගස", "category": "plant" },
    { "word": "සුවර්ණප්‍රසව", "meaning": "එන්සාල්", "category": "plant" },
    { "word": "සුවර්ණවර්ණ", "meaning": "කහ", "category": "plant" },
    { "word": "සුවර්ණා", "meaning": "කළු අගිල්, බැවිල, කහ, මුඟුණුවැන්න", "category": "plant" },
    { "word": "සුවර්ණාඛ්‍ය", "meaning": "නාමල්රේණු", "category": "plant" },
    { "word": "සුවරා", "meaning": "අරත්ත", "category": "plant" },
    { "word": "සුවල්ලී", "meaning": "(සෝමවල්ලී) බෝදිඇට", "category": "plant" },

    // --- පිටුව 502 ---
    { "word": "සුවශ්චිල", "meaning": "රන්ගොකටු", "category": "plant" },
    { "word": "සුවස", "meaning": "සුවසලුණු", "category": "mineral" },
    { "word": "සුවහා", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "සුවාහා", "meaning": "ඉන්සලු, ජලාවතී (එල්වළු) හීන්අරත්ත, සේපාලිකා, තුස්තවාළු, වළාවැන්න, බින්තල්, මහ අරත්ත", "category": "plant" },
    { "word": "සුවියසි", "meaning": "වල්කපු, බෙබරගෙඩි", "category": "plant" },
    { "word": "සුවීරක", "meaning": "සෞවීර අඳුන්", "category": "mineral" },
    { "word": "සුවිරාමල", "meaning": "කාඩි", "category": "liquid" },
    { "word": "සුවෘත්තා", "meaning": "කිඩාරම්, නෙළුම්, ඇත්සැටිය, මුද්දරප්පලම්", "category": "plant" },
    { "word": "සුවෘත්තී", "meaning": "හිඟුරු පියලි", "category": "plant" },
    { "word": "සුශවි", "meaning": "කරිවිල, හීන් කරිවිල, කළුදුරු, කෝවැල, සිරිල, දුම්මල්ල", "category": "plant" },
    { "word": "සුශාක", "meaning": "කූරතම්පලා", "category": "plant" },
    { "word": "සුශිඛ", "meaning": "රත්නිටුල් ගස", "category": "plant" },
    { "word": "සුශිකා", "meaning": "කෙසෙල් ගස", "category": "plant" },
    { "word": "සුෂ්ට්‍රි", "meaning": "කරවිල වැල්", "category": "plant" },
    { "word": "සුෂ්ට්‍රකාෂ්ඨ", "meaning": "බෙරු", "category": "plant" },
    { "word": "සුසක", "meaning": "වියළි දේ, ලාකඩ", "category": "general" },
    { "word": "සුසකමාංස", "meaning": "වියළි මස්", "category": "animal" },
    { "word": "සුසකර", "meaning": "පුස්කර", "category": "plant" },
    { "word": "සුසමාපු", "meaning": "ආස්මී", "category": "general" },
    { "word": "සුසාව", "meaning": "කෙසෙල් ගස", "category": "plant" },
    { "word": "සුසාර", "meaning": "සඳුන්, රත් කිහිරි", "category": "plant" },
    { "word": "සුසාරක", "meaning": "හෙළ හිඹුරු", "category": "plant" },
    { "word": "සුසිඛ", "meaning": "කළුකිහිරි, රත් නිටුල්, මොණරකුඩුම්බිය", "category": "plant" },
    { "word": "සුසිර", "meaning": "කොට්ටම්, කරාබුනැටි", "category": "plant" },
    { "word": "සුසිල", "meaning": "කකීටකශෘංගි", "category": "plant" },
    { "word": "සුසේන", "meaning": "කරඹ", "category": "plant" },
    { "word": "සුසේනිකා", "meaning": "වැල් පෙනෙල, කළු තුස්තවාළු", "category": "plant" },
    { "word": "සුසේත", "meaning": "කරඹ", "category": "plant" },
    { "word": "සූක්‍ෂම", "meaning": "හීන් එන්සාල්, ශරීරයේ සියුම් කූප වල පවා පැතිර යන වත්සනාභ වැනි විෂ වර්ග", "category": "plant" },
    { "word": "සූක්‍ෂම තණ්ඩුල", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "සූක්‍ෂමදලා", "meaning": "දුරාලභා", "category": "plant" },
    { "word": "සූක්‍ෂම පත්‍ර", "meaning": "පැපිලිය, කොත්තමල්ලි, වල්දුරු, හීන් බෙබර, වල් අඳුතලා, රත් උක්, ශතපුෂ්ප, සාතාවාරිය, හීන් බැමිතිරිය, ඇල් කහඹිලියා, උණ ගස", "category": "plant" },
    { "word": "සූක්‍ෂම පත්‍රා", "meaning": "රසකිඳ, ඇල්කහඹිලියා, කංසා, සාතාවාරිය", "category": "plant" },
    { "word": "සූක්‍ෂම පත්‍රිකා", "meaning": "රසකිඳ, සාතාවාරිය, පැපිලිය", "category": "plant" },
    { "word": "සූක්‍ෂමපත්‍රී", "meaning": "සාතාවාරිය, පැපිලිය", "category": "plant" },
    { "word": "සූක්‍ෂම පිප්පලී", "meaning": "වල් නිප්පිලි", "category": "plant" },
    { "word": "සූක්‍ෂමපුෂ්පා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "සූක්‍ෂම ඵලා", "meaning": "පිටවක්කා, හීන් මෑබහනු", "category": "plant" },
    { "word": "සූක්‍ෂම මූලා", "meaning": "මිදි", "category": "plant" },
    { "word": "සූක්‍ෂමවල්ලී", "meaning": "වැල්මදට, පැපිලිය", "category": "plant" },
    { "word": "සූක්‍ෂම වීජා", "meaning": "කසකසා ගස", "category": "plant" },
    { "word": "සූක්‍ෂමා", "meaning": "හීන් එන්සාල්, බෝලිද්ද", "category": "plant" },
    { "word": "සූක්‍ෂමෙලා", "meaning": "හීන් එන්සාල්", "category": "plant" },
    { "word": "සූක", "meaning": "යවාදියෙහි බූව, මහනෙල්", "category": "plant" },
    { "word": "සූකතුණ්ඩ", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "සූකපාකය", "meaning": "යවකාර", "category": "mineral" },
    { "word": "සූකර", "meaning": "හෙළ වරා, බිමිතල්, ඌරල", "category": "plant" },
    { "word": "සූකවල්ලභ", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "සූකාලු", "meaning": "කිඩාරම්", "category": "plant" },
    { "word": "සූකාාවාකා", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "සූතිරී", "meaning": "ගල්කණ්ඩු = (වැලි හකුරු වැනි ද්‍රව්‍යයක්) සුදු පැහැති හකුරු වෙසෙසක්", "category": "mineral" },
    { "word": "සූකෙෂ්ට", "meaning": "දෙළුම්", "category": "plant" },

    // --- පිටුව 503 ---
    { "word": "සූචිකර්ණී / සූචිකර්ණිකා", "meaning": "එළ නෙළුම්", "category": "plant" },
    { "word": "සූචිකා පුෂ්ප / සූචිකා පුෂ්පී", "meaning": "වැටකේ", "category": "plant" },
    { "word": "සූචිකාමුඛ", "meaning": "සක්", "category": "animal" },
    { "word": "සූචිනු", "meaning": "වළඟසාල්", "category": "plant" },
    { "word": "සූචිපුෂ්ප", "meaning": "වැටකේ", "category": "plant" },
    { "word": "සූචිවක්තු", "meaning": "දියමන්ති", "category": "mineral" },
    { "word": "සූචිවක්තුක", "meaning": "සුදු අඳුතලා", "category": "plant" },
    { "word": "සූචිශාලී", "meaning": "අමු ආදි හීන් ධාන්‍ය", "category": "plant" },
    { "word": "සූච්‍යාග්‍ර", "meaning": "ඉළුක්", "category": "plant" },
    { "word": "සූත්කතා", "meaning": "කුරුඳු පොතු", "category": "plant" },
    { "word": "සූතපාදිකා", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "සූතිකා", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "සූතිකාතක", "meaning": "බිම් කොසඹ", "category": "plant" },
    { "word": "සූතික්‍ෂණ", "meaning": "හෙළ මුරුංගා", "category": "plant" },
    { "word": "සූත්‍ර", "meaning": "නූල", "category": "general" },
    { "word": "සූත්‍ර පුෂ්ප / සූත්‍ර පුෂ්පිකා", "meaning": "කපු ගස", "category": "plant" },
    { "word": "සූදා", "meaning": "අරළු", "category": "plant" },
    { "word": "සූදෝධභවා", "meaning": "අරළු", "category": "plant" },
    { "word": "සූනකය / සූනකාපී", "meaning": "යොන් තුඹ", "category": "plant" },
    { "word": "සූනක", "meaning": "පතුක්", "category": "plant" },
    { "word": "සූනු", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සූපඝ්න", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සූප පර්ණී", "meaning": "මුං වැන්න", "category": "plant" },
    { "word": "සූපභූෂණ", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සූපශ්‍රෙෂ්ඨ", "meaning": "මුං", "category": "plant" },
    { "word": "සූපාබාග", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සූප්‍රියා", "meaning": "මකුණුවැන්න", "category": "plant" },
    { "word": "සූඵලා", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "සූයසී", "meaning": "වරා ගස, හෙළනික, වෑක්, ඉරමුසු", "category": "plant" },
    { "word": "සූයසීකාන්තා", "meaning": "පලිඟු, සූර්‍ය්‍යකාන්ත මල් ගස", "category": "plant" },
    { "word": "සූයසිකාන්තා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "සූයසීදස", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සූයසීපර්ණී", "meaning": "මුංවැන්න", "category": "plant" },
    { "word": "සූයසීප්‍රිය", "meaning": "තඹ", "category": "mineral" },
    { "word": "සූයසීපුත්‍රා", "meaning": "ලෝලු ගස, සැම ගස", "category": "plant" },
    { "word": "සූයසීබන්ධු", "meaning": "ඇඹුල, නෙළුම්, නිල් මානෙල්, (නිලුපුල්)", "category": "plant" },
    { "word": "සූයසීභක්ත", "meaning": "බටු වද", "category": "plant" },
    { "word": "සූයසීභගතා / සූයසීලතා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "සූයසීවර්තා", "meaning": "වේලා ගස", "category": "plant" },
    { "word": "සූයසීවල්ලභ", "meaning": "කිකිරිදිය", "category": "plant" },
    { "word": "සූයසීවල්ලභා", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "සූයසීවල්ලී", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සූයසීසන්ම", "meaning": "වැල්තිබ්බටු", "category": "plant" },
    { "word": "සූයසීා", "meaning": "ලෝලු", "category": "plant" },
    { "word": "සූයසීාක්‍ෂ", "meaning": "සූර්‍ය්‍යකාන්තී මැණික්.", "category": "mineral" },
    { "word": "සූයසීාවර්තීය", "meaning": "සූරුවාරදය (සුර වරා දය = සූරාවාරදව)", "category": "plant" },
    { "word": "සූයසීාවර්තී", "meaning": "වේලා, කෝවක්කා", "category": "plant" },
    { "word": "සූයසීාහ්ව / සූයසීාහ්වය", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සූර", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සූරණ", "meaning": "කිඩාරම්", "category": "plant" },
    { "word": "සූරිකාන්ත", "meaning": "සූර්‍ය්‍යකාන්ත ගස", "category": "plant" },
    { "word": "සූරිභක්තා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "සූරී", "meaning": "වරා ගස, මහ අබ", "category": "plant" },
    { "word": "සූලකාන්", "meaning": "හුල් මස්", "category": "animal" },
    { "word": "සූලවිදාරිණී", "meaning": "මුංවැන්න", "category": "plant" },
    { "word": "සූසු මධ්‍යා", "meaning": "තුස්තවාලු", "category": "plant" },
    { "word": "සෙංකොට්ටම්", "meaning": "සෙංකල නිරිකොට්ටම්", "category": "plant" },
    { "word": "සෙංගමාල", "meaning": "කාමිලා රෝගය", "category": "treatment" },
    { "word": "සෙකර", "meaning": "කරල් සැබෝ", "category": "plant" },
    { "word": "සෙබරිකො", "meaning": "සැබෝ", "category": "plant" },
    { "word": "සෙවක", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "සෙතඹ", "meaning": "ඇටඹ", "category": "plant" },

    // --- පිටුව 504 ---
    { "word": "සෙතාවහා", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "සෙතු", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "සෙතුභෙදින්", "meaning": "දත්ත", "category": "plant" },
    { "word": "සෙතුවෘක්‍ෂ", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "සෙන්තරුන්කාලි", "meaning": "රත් කිහිරි", "category": "plant" },
    { "word": "සෙන්කල නිරි කොට්ටම්", "meaning": "සෙන්කොට්ටම් (නදී භල්ලාතක)", "category": "plant" },
    { "word": "සෙන්කිරෝ", "meaning": "රත් තම්පලා", "category": "plant" },
    { 
        "word": "සෙන්කොට්ටම්", 
        "scientific": "Semicarpus Anacardium",
        "meaning": "<b>Semicarpus Anacardium-සෙන්කොට්ටම්—නදී භල්ලාතක</b><br><br>සෙන්කල නිරි කොට්ටම් කමින් පැරණි සිංහල වට්ටෝරු වෙද පොත් වල සඳහන් වන මේ ගසේ දිග - පළල අඟල් 8 1/2 x 3 1/4 පමණ ඇති උඩු පැත්ත කොළ පාට සහ යටි පැත්ත මඳක් සුදු පාටින් යුත් තිඹිරි කොළ වැනි කොළ තිබේ. මේ කොළ නුග කොළ පමණ විශාල ය. මේ ගසේ කතිරකැටිනි වැනි පැතලි ගෙඩි (ඇට) සැදෙයි. මේ ගෙඩි තුළ අබින් පමණ තද කළු පැහැයෙන් යුත් සායමක් තිබේ. රජකයෝ මේ සායම අල්පෙනෙත්ති තුඩින් ගෙන රෙදි ලකුණු දැමීමට පාවිච්චි කරති. මේ සායම තද කළු පාටින් යුක්ත ය. රෙදි වල දමන ලකුණු කිසි දිනක මැකිය නො හැක. මේ ගසේ කොළ ද මේ බඳු කසට ගතියකින් යුක්ත ය.<br><br>මේ ගෙඩි අග්නි මාන්ද්‍යය, ආමවාතය, ලාදුරු, කෘමි රෝග හා නහර ගත ආබාධ වලට ත් දෙන ඖෂධ යෝග වලට ඇතුළත් කර තිබේ.<br><br>(නදී) භල්ලාතක වෙනුවට ඖෂධ සඳහා ගත යුත්තේ බදුල්ල නොව සෙන්කොට්ටම් ය. බදුල්ල කොළ ද හැඩහුරු කමින් සෙන්කොට්ටම් වලට මඳක් සමාන නමුත් එය වෙන වර්ගය කි. එහි ඇට ද සෙන්කොට්ටම් ඇට වලට වඩා වෙනස් ය.", 
        "category": "plant",
        "image": "img_semicarpus_anacardium_senkottam.jpg"
    },
    { "word": "සෙන්කොඩිවෙල්", "meaning": "රත් නිටුල්", "category": "plant" },
    { "word": "සෙන්චන්දනම්", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "සෙන්තාමරම්", "meaning": "රත් නෙළුම්", "category": "plant" },
    { "word": "සෙන්දිරින්කා", "meaning": "සඞ්ඛ්‍යාරාග", "category": "plant" },
    { "word": "සෙන්නසුරුවි", "meaning": "රන් කරල් සැබ", "category": "plant" },
    { "word": "සෙන", "meaning": "වෙලන් ගස, (වෙලඟ)", "category": "plant" },
    { "word": "සෙනරත්", "meaning": "මොණරකුඩුම්බිය", "category": "plant" },


    // --- පිටුව 505 ---
    { "word": "සෙනා", "meaning": "අබ", "category": "plant" },
    { "word": "සෙනාහ්ව", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සෙනෙන්", "meaning": "තරණ ගස", "category": "plant" },
    { "word": "සෙනේහ", "meaning": "ගිතෙල්", "category": "liquid" },
    { "word": "සෙප්පුටියා", "meaning": "කැප්පිටිය (කැප්පෙට්ටියා ගස)", "category": "plant" },
    { "word": "සෙපත්ති", "meaning": "ඇත්දෙමට ගස", "category": "plant" },
    { "word": "සෙපාලිකා", "meaning": "කළුතලා, සේපාලිකා", "category": "plant" },
    { "word": "සෙබිබ", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "සෙඹු", "meaning": "තඹ, ලොකු", "category": "mineral" },
    { "word": "සෙම්පරිත්තේ", "meaning": "වද ගස්", "category": "plant" },
    { "word": "සෙම්පරිත්තම්පු", "meaning": "වද මල්", "category": "plant" },
    { "word": "සෙම්පුනෙරෙච්චි", "meaning": "මහ නෙරෙංචි", "category": "plant" },
    { "word": "සෙම්බකාමරම්", "meaning": "සපු ගස", "category": "plant" },
    { "word": "සෙම්බකාමුට්ටු", "meaning": "සපු කැකුළු", "category": "plant" },
    { "word": "සෙම්බුනෙරෙංචි", "meaning": "මහ ගොකටු (මහ නෙරෙංචි)", "category": "plant" },
    { "word": "සෙමද", "meaning": "ඉඟුරුපියලි", "category": "plant" },
    { "word": "සේරපාදට", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "සෙරාප්පාඩි", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "සෙරෙයසකො", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "සෙලු", "meaning": "ලෝලු ගස", "category": "plant" },
    { "word": "සෙල්කැන්", "meaning": "වැල්මදට (දඹ ඉදින් තරු)", "category": "plant" },
    { "word": "සේලෙය්‍යා", "meaning": "ගල්මද", "category": "mineral" },
    { "word": "සෙලෝ", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "සෙලෝදරා", "meaning": "බොරාදම් ගස", "category": "plant" },
    { "word": "සෙව්‍ය", "meaning": "ඉරිවේරිය, සැවැන්න, ඇසටු, දියමිදෙල්ල, සුදු හඳුන්", "category": "plant" },
    { "word": "සෙව්චගන්ති", "meaning": "රත් කතුරු", "category": "plant" },
    { "word": "සෙව්චන්දි", "meaning": "පික් මල්ලි (පික් මල්)", "category": "plant" },
    { "word": "සෙව්වරලි", "meaning": "රත් කණේරු", "category": "plant" },
    { "word": "සෙව්වාමනක්කු", "meaning": "රත් එඬරු", "category": "plant" },
    { "word": "සෙව්වෙල්ලී", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "සෙවාලො", "meaning": "සෙවෙල", "category": "plant" },
    { "word": "සෙවි", "meaning": "ජීවක", "category": "plant" },
    { "word": "සෙවුන්දරං", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "සෙවුපිල්ල", "meaning": "එළ වරා", "category": "plant" },
    { "word": "සෙවුවල්ලි", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "සෙවෙදි", "meaning": "තුස්තවාලු", "category": "plant" },
    { "word": "සෙවෙල්", "meaning": "පෙද (දිය සෙවෙල්)", "category": "plant" },
    { "word": "සෙලඹ", "meaning": "හැළඹ = හැලි අඹ (මහ අඹ හෝ සුදු අඹ)", "category": "plant" },
    { "word": "සේතනි", "meaning": "ඉඟිනි ඇට", "category": "plant" },
    { "word": "සේතු", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "සේනාය", "meaning": "කරඹ", "category": "plant" },
    { "word": "සේපාල මරම්", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "සේම", "meaning": "මිරිස් වැල, ගම්මිරිස්", "category": "plant" },
    { "word": "සේයසි", "meaning": "දියමින්ත", "category": "plant" },
    { "word": "සේව්‍ය", "meaning": "සිවිය", "category": "plant" },
    { "word": "සේරල", "meaning": "සේර මුල්, දියෙහි හටගන්නා අල වර්ගයක්", "category": "plant" },
    { 
        "word": "සේරු", 
        "scientific": "සේරු ගස්",
        "meaning": "<b>සේරු - රේරු ගස්</b><br><br>සේරු (රේරු) කොළ තරමක කටු අත්තන කොළ පමණ ඇත. බෝ කොළයේ මෙන් මේ කොළයේ අග ද මඳක් උල් ව තිබේ. මේ ගසේ කොළ බෙහෙවින් ම ඉන්දියානු ගොඩ කඳුරු කොළ වලට සමාන ය.<br><br>අවුරුදු පතා මේ ගසේ පිට සිවිය (පිට පොත්ත) ගැලවී අළුත් වෙයි. එම නිසා සේරු ගසේ කඳ නිතර ම සුදු පැහැයෙන් දිලිසෙන පිරිසිදු ගතියෙන් යුක්ත වෙයි. මෙය මද්‍ය කාරක ඖෂධයකි. මේ ගසේ කොළ හා පොතු වල යුෂ ප්‍රධාන කොට ඇති ඉතා ප්‍රත්‍යක්ෂ තුවාල තෙලක් තිබේ.<br><br>හැඩහුරු කමින් හා ගුණයෙන් මේ රේරු ගස ත් ඉන්දියානු ගොඩ කඳුරු ගස ත් එකක් ම බැව් සිතිය හැක. මේ දෙවර්ගය ම විෂමුෂ්ටි නාමයෙන් හැඳින්වීම ද මෙහි ලා සැලකිය යුතු තවත් කරුණකි.", 
        "category": "plant",
        "image": "img_seru_reru.jpg"
    },

    // --- පිටුව 506 ---
    { "word": "සේවන්දි", "meaning": "සෙව්වන්දි", "category": "plant" },
    { "word": "සේවාල", "meaning": "සෙවෙල්", "category": "plant" },
    { "word": "සෛංහල", "meaning": "කුරුඳු", "category": "plant" },
    { "word": "සෛක", "meaning": "මදටිය, ඔලිඳ", "category": "plant" },
    { "word": "සෛකනොහව", "meaning": "අමු ඉඟුරු", "category": "plant" },
    { "word": "සෛකත", "meaning": "වැලි, සාදිලිංගම්", "category": "mineral" },
    { "word": "සෛකතෙෂට", "meaning": "අමු ඉඟුරු අල", "category": "plant" },
    { "word": "සෛකබාලි", "meaning": "ඔලිඳ වැල", "category": "plant" },
    { "word": "සෛකරි", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "සෛබරිකා", "meaning": "හෙළ කරල් සැබෝ", "category": "plant" },
    { "word": "සෛන්ධව", "meaning": "සිඳු ලුණු", "category": "mineral" },
    { "word": "සෛයසී", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "සෛරීය", "meaning": "රන්වන් කටුකරඬු", "category": "plant" },
    { "word": "සෛරීයන", "meaning": "ගිරිතිල්ල, කටුකරඬු", "category": "plant" },
    { "word": "සෛරෙය", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "සෛල", "meaning": "ගල්මද, හින් එන්සාල්", "category": "mineral" },
    { "word": "සෛලප්", "meaning": "ගල්මද, සඳුන්", "category": "mineral" },
    { "word": "සෛලොත්භව", "meaning": "හෙළ සඳුන්, ගල්නහර", "category": "plant" },
    { "word": "සෛව", "meaning": "වැලිද්ද", "category": "plant" },
    { "word": "සෛවල", "meaning": "දියසෙවෙල්, මහ පොණඩරු", "category": "plant" },
    { "word": "සෛවාල", "meaning": "පෙද, (සෙවෙල්)", "category": "plant" },
    { "word": "සොකනාසක", "meaning": "හෝපළු", "category": "plant" },
    { "word": "සොකරොහිණී", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "සොග්ගරුහතී", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "සොගන්ධික", "meaning": "හෙල්මැලි", "category": "plant" },
    { "word": "සොච්චා", "meaning": "එළ බටු", "category": "plant" },
    { "word": "සොණ්ඩි", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "සොණණං", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "සොණිතං", "meaning": "ලේ", "category": "anatomy" },
    { "word": "සොතඝාතී", "meaning": "සුළු බූරුද, මහසාරණ", "category": "plant" },
    { "word": "සොදතොට", "meaning": "සුවඳ හොට (සැවැන්දරා)", "category": "plant" },
    { "word": "සොදක", "meaning": "තෙරිවිෂ", "category": "plant" },
    { "word": "සොධ්‍යා", "meaning": "ලුණුවිල, ශාලිපර්ණී", "category": "plant" },
    { "word": "සොධන", "meaning": "කයිප්", "category": "plant" },
    { "word": "සොනකො", "meaning": "තොවිල", "category": "plant" },
    { "word": "සොනය", "meaning": "ලුණු", "category": "mineral" },
    { "word": "සොනා", "meaning": "එරබදු", "category": "plant" },
    { "word": "සොනික්කං", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "සොඵ", "meaning": "ඉදිමුම", "category": "treatment" },
    { "word": "සොඵක / සොඵකෘද්‍රැම", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "සොඵග්නී", "meaning": "මහසාරණ, සුළුසාරණ", "category": "plant" }

];