// data_109_115.js - පිටු 109 සිට 115 දක්වා සියලුම වචන
const data_extra_109_115 = [
  // --- පිටුව 109 (image_861748.png) ---
  {
    "word": "කැසිපිස්සන්වැල්",
    "meaning": "රත් පිතට කැසීමට හා ඉසකුඩිච්චියට ප්‍රත්‍යක්ෂ අධික සීත ගුණයෙන් යුත් වැල් වගියකි. මේවායේ කොළ කොටා ඇල් දියෙන් මිරිකා පෙරා සීනි දමා රැයක් මිදෙන්ට තබාගත් කල ජෙලි වැනි අධික සීත ගුණයෙන් යුත් රසවත් කෑමක් පිළියෙල කර ගත හැක.",
    "category": "plant"
  },
  { "word": "කැසිමුස්", "meaning": "කැස්ස හා ඇදුම", "category": "symptom" },
  { "word": "කෑහැල", "meaning": "කාල ගස", "category": "plant" },
  {
    "word": "කැර-කැර ගස",
    "meaning": "(බරු වගියට අයත්) අවුරුදු සිය ගණන් ගිය විට ඇතුළේ සාරය (බස්නම) තැනීමට සුදුසු අරටුවක් සාදන උඩවැඩියා වැවීමට පොතු ගන්නා ගසකි.",
    "category": "plant"
  },
  {
    "word": "කැල-කැල ගස",
    "meaning": "(කැවිකාල, පව (රත්) කැල යයි කැල වගී දෙකකි. කැට කැල කැඩුම් බිඳුම් වෙදකමටත් පව (රත්) කැල වාජීකරණ ඖෂධවලටත් ප්‍රත්‍යක්ෂයකි.",
    "category": "plant"
  },
  { "word": "කැලිය", "meaning": "නාග බලා නම් ගස", "category": "plant" },
  { "word": "කිංකිණි", "meaning": "රිදී හුන්තම්", "category": "treatment" },
  { "word": "කිංකිණි", "meaning": "කිහිරි, උග්‍රරස්ස, කවුකිරිය, මුවන්ත", "category": "plant" },
  { "word": "කිංගෙදිරිදං", "meaning": "ඉද්ද", "category": "plant" },
  { "word": "කිංචුලකයෝ", "meaning": "භිමිකා, (ගැඬවිලා)", "category": "treatment" },
  { "word": "කිංචය", "meaning": "අගිල්", "category": "plant" },
  { "word": "කිංඡල්ක", "meaning": "පියුම් කේසරා, නාමල් රේණු", "category": "plant" },
  { "word": "කිංපල", "meaning": "කොවට්ටන්", "category": "plant" },
  { "word": "කිංව", "meaning": "නෙළුම් මල් රේණු", "category": "plant" },
  { "word": "කිංගුක", "meaning": "කාල, එරබදු, අත්තන, තල ගස", "category": "plant" },
  { "word": "කිංසුක", "meaning": "අරත්ත, එරබදු, අත්තන", "category": "plant" },
  { "word": "කිංපකෙබො", "meaning": "පියුම් කෙසර", "category": "plant" },
  { "word": "කික්කාරි", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "කිණි", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "කිතුරැ", "meaning": "මුල්ල", "category": "plant" },
  { "word": "කිඩිකාර", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "කිඩිකිරට", "meaning": "සිතියා ගස", "category": "plant" },
  { "word": "කිඩිකිරණ", "meaning": "හෝපලු ගස", "category": "plant" },
  { "word": "කිඩිකිරනක", "meaning": "කවුකරඹු ගස", "category": "plant" },
  { "word": "කිඩිකිරල", "meaning": "මූණමල්, සිතියා ගස", "category": "plant" },
  { "word": "කිඩිකිරිච්", "meaning": "කවුකිණිරි", "category": "plant" },
  { "word": "කිඩිකිලොස", "meaning": "හෝපලු ගස", "category": "plant" },
  { "word": "කිච්චා", "meaning": "මුහුකාපුජා", "category": "treatment" },
  { "word": "කිච්චාඩ්", "meaning": "මුං ඇට හා සහල් ද මිශ්‍ර කර පිළියෙල කරන ආහාරයක්", "category": "treatment" },
  { "word": "කිච්චලක", "meaning": "ගැබ්වුලා", "category": "treatment" },
  { "word": "කිඤ්ච", "meaning": "නෙළුම් මල් රේණු", "category": "plant" },
  { "word": "කිඤ්චුලක", "meaning": "කොවට්ටන්, නාමල් රේණු, නෙළුම් මල් රේණු", "category": "plant" },
  { "word": "කිඤ්චුලකා", "meaning": "කොවට්ටන්, නාමල් රේණු, නෙළුම් මල් රේණු", "category": "plant" },
  { "word": "කිවට", "meaning": "සබෝරා", "category": "plant" },
  { "word": "කිවිටො", "meaning": "බුළු", "category": "plant" },
  { "word": "කිවිට්", "meaning": "සබෝර", "category": "plant" },
  { "word": "කිවිට", "meaning": "රිදීහුන්තම්, උක්පැණි", "category": "treatment" },
  { "word": "කිවිමුලක", "meaning": "උවරල", "category": "plant" },
  { "word": "කිවු", "meaning": "සමූහය", "category": "treatment" },
  { "word": "කිඩාරම්", "meaning": "කිඩාරම් ගස", "category": "plant" },
  { "word": "කිඩිබ", "meaning": "කිහිරි, හුන්තම්, රිදී හුන්තම්, කුෂ්ඨ රෝගයක්", "category": "symptom" },
  { "word": "කිණ්වමුලක", "meaning": "මුණමල් ගස", "category": "plant" },
  { "word": "කිණි", "meaning": "සැඛෝ ගස", "category": "plant" },

  // --- පිටුව 110 (image_8617a8.png) ---
  { "word": "කිණිගු", "meaning": "මුලාස්ස, ලාගෙඩි", "category": "plant" },
  { "word": "කිණිරී", "meaning": "කිණිහිරි ගස", "category": "plant" },
  { "word": "කිණිඟි", "meaning": "කරල්සැබෝ, එල කටු රොලු", "category": "plant" },
  { "word": "කිණිඟිතුලසී", "meaning": "කවුතුලසී", "category": "plant" },
  {
    "word": "කිණිහිරී",
    "meaning": "කර්ණිකාර, ශාඛභූරා, කමින් නාමල් වලට සමාන කහපාට මල් හටගන්නා කපු කොළ වැනි කොළ ඇති, හීන් ගස් වැනි කඳ ඇති ගස් වර්ඟයකි.",
    "category": "plant"
  },
  { "word": "කිණූ", "meaning": "ගම්මිරිස් වැල", "category": "plant" },
  { "word": "කිණූමිස්", "meaning": "දුල් මිස්", "category": "treatment" },
  { "word": "කිණව", "meaning": "අත්තන, හිඟුරුපියලි, සුවඳ කසා", "category": "plant" },
  { "word": "කිණවරුප්", "meaning": "අත්තන ගස", "category": "plant" },
  { "word": "කිණල්", "meaning": "එනම් ගස, ඉඳි ගස", "category": "plant" },
  { "word": "කිණල", "meaning": "ඇට කෙසෙල් හැඩය ඇති අට නැති මාළු කෙසෙල් වර්ගයක්", "category": "plant" },
  { "word": "කිණූල්", "meaning": "කිතුල් ගස, (හිතාල)", "category": "plant" },
  { "word": "කිදල", "meaning": "කුඩා වැල", "category": "plant" },
  { "word": "කිදි", "meaning": "රසකිඳ, හිමපලා", "category": "plant" },
  { "word": "කිඹිලිය", "meaning": "කිඹිලිය", "category": "plant" },
  { "word": "කිදි (වැල්)", "meaning": "කිඳි වර්ග අටකි. රස කිඳ, තිත්ත කිඳ, බූ කිඳ, ගැට කිඳ, මීටි කිඳ, දික් කිඳ, අළු කිඳ, සෙවෙල් කිඳ", "category": "plant" },
  { "word": "කිද්‍ර", "meaning": "මිරිස්", "category": "plant" },
  { "word": "කිද්‍ර අන්‍ත", "meaning": "ඉඟු", "category": "plant" },
  { "word": "කිත්කර", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "කිත්කිණි", "meaning": "කවුකිරිය, උග්‍රරස්ස, මුවන්ත", "category": "plant" },
  { "word": "කිත්කිරාත", "meaning": "හෝපලු, අශෝක", "category": "plant" },
  { "word": "කිත්කිරාළ", "meaning": "වකුල, (මුහුණමල්)", "category": "plant" },
  { "word": "කිත්පල්ලක", "meaning": "නාකේසරා, නාමල් රේණු, නෙළුම් රේණු, සුවඳ කොට්ටම්", "category": "plant" },
  { "word": "කිත්තාල", "meaning": "කිතුල්", "category": "plant" },
  { "word": "කිත්තම", "meaning": "කීිරි", "category": "treatment" },
  { "word": "කිත්තම බිජු", "meaning": "යොගා බීජු", "category": "treatment" },
  { "word": "කිත්තුක", "meaning": "කාල, (එරබදු) කිහිරි", "category": "plant" },
  { "word": "කිත්සුක", "meaning": "රන්කාල", "category": "plant" },
  { "word": "කිත්හ", "meaning": "කාලහංසයෝ", "category": "treatment" },
  { "word": "කිභව", "meaning": "කවුකරඹු", "category": "plant" },
  { "word": "කිහිඟු", "meaning": "මුලාස්ස", "category": "plant" },
  { "word": "කිහිගුල්", "meaning": "මුලාස්ස", "category": "plant" },
  { "word": "කිතිහේර", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කිතිහුල්", "meaning": "මිලිකුන් එලය, (මියලි ගෙඩි = පැසුනු ගෙඩි)", "category": "plant" },
  { "word": "කිතිමිස්", "meaning": "කළු මිසූන්", "category": "treatment" },
  { "word": "කිතිලිකාලි", "meaning": "නිල්කැට", "category": "treatment" },
  { "word": "කිතිනි", "meaning": "මින කපු, සැබෝ, ලෝලු, නිල්කටු රොලු, ඇඹුල්වේ, මහ ඉඟිනි, හෙලසැබෝ, තිබ්බටු", "category": "plant" },
  { "word": "කිතිනිහුලස", "meaning": "කවු කරල් සැබෝ", "category": "plant" },
  { "word": "කිතිගිරියා", "meaning": "ගින් තේර, (කඳුරැලි වල හටගන්නා නිල්පාට මල් පොකුරු සහිත කුඩා පඳුරු වර්ගයක්)", "category": "plant" },
  { "word": "කිනි", "meaning": "ගින් වම්බටු", "category": "plant" },
  { "word": "කිඹ", "meaning": "කනට ගස", "category": "plant" },
  {
    "word": "කිඹුක්",
    "meaning": "විෂ සහිත අඹ ගෙඩි වැනි ගෙඩි ඇති ගසක්, (ගොඩ කඳුරු යයි විශ්වාස කළ හැක.)",
    "category": "plant"
  },
  { "word": "කිඹපල", "meaning": "කඳුරු ගස", "category": "plant" },
  { "word": "කිඹපාක", "meaning": "කඳුරු ගස", "category": "plant" },
  { "word": "කිඹගිර", "meaning": "නස්නාරං", "category": "plant" },
  { "word": "කිඹි", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කිඹිල", "meaning": "දේවදාර", "category": "plant" },
  { "word": "කිඹිහර", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කිඹික", "meaning": "කසට ගස", "category": "plant" },
  { "word": "කිඹිලි", "meaning": "ඉස්සා, (නලමිස්සූ)", "category": "treatment" },
  { "word": "කිඹුල්", "meaning": "කිඹුල්ලු", "category": "treatment" },

  // --- පිටුව 111 (image_861a6b.png) ---
  {
    "word": "කිඹුල්වැන්න",
    "scientific": "Polygonum Tomentosum",
    "meaning": "අතීසාර නාශක ඖෂධයකි. කුමිබිලාකාර (කිඹුලෙකුගේ ගැබ්වුරුකම ඇති) මල් හටගන්නා මේ වර්ගය දිය සිරාව ඇති රොගිය ගස්වලත්, ගල් වලත් වෙයි. කිතුල් කෙඳි වැනි කළු පාට කුඩා දඬු වල සෑදෙන මස ගති දිය ගතියෙන් යුත් කොළ ඇති මේ වර්ගය ලංකාවේ පැරණි නාමේ කාසියට සමාන නිසා නම්පෙති යයි ද, කාසිපෙති යයි ද ගැමි වහරෙහි යෙදී ඇත. මිය ඇඹුල් - කසට රසයෙන් යුක්තය. අතීසාර රෝගයට හා අධික පිපාසයට මේවා තම්බා ගත් ජලය උතුම්. දිය සෙවෙල් සහිත ගස්වල පෑලවෙන මේ වර්ගයේ මුල් පසුව පොළොවට ඇදෙයි. තවත් මතයක්: ඇඹුල් ඇඹිලිය වල ගැබ් හුරුකම ඇති පෙති හතරකින් යුක්ත වූ 'පෙති පලා' නමින් දකුණු පළාතේ ප්‍රකට පලා වර්ගය කිඹුල්වැන්න බැව් එක් ප්‍රසිද්ධ වෛද්‍ය පරම්පරා වක පවතින මතයකි.",
    "category": "plant"
  },
  { "word": "කියඹු", "meaning": "කස", "category": "plant" },
  { "word": "කිරිමිර", "meaning": "නාරං ගස", "category": "plant" },
  { "word": "කිරිමිරණව", "meaning": "නාරං ගස", "category": "plant" },
  { "word": "කිිරවා", "meaning": "වනුප් ඇට", "category": "plant" },
  { "word": "කිිරතු", "meaning": "බිංකොහොඹ", "category": "plant" },
  { "word": "කිිරඹ", "meaning": "හිර අඹ", "category": "plant" },
  { "word": "කිිරිමාල", "meaning": "ඇසල ගස", "category": "plant" },
  { "word": "කිිරාත", "meaning": "බිංකොහොඹ", "category": "plant" },
  { "word": "කිිරාතක", "meaning": "බිංකොහොඹ", "category": "plant" },
  { "word": "කිිරාතප", "meaning": "කෝන්, තඹවන් සඳුන්, බිංකොහොඹ", "category": "plant" },
  { "word": "කිිරාත තිකතා", "meaning": "බිංකොහොඹ, නේපාල බිංකොහොඹ", "category": "plant" },
  { "word": "කිිරාතිනි", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "කිිරාමබු", "meaning": "කරාබුනැටි", "category": "plant" },
  { "word": "කිිරි", "meaning": "ළව්රල", "category": "plant" },
  { "word": "කිිරිඅල", "meaning": "කිරි හබරල, කිරිබදු අල, කිරි ඇති ගස් - රක්ත චන්දන ගස", "category": "plant" },
  { "word": "කිිරික", "meaning": "කිරිපලු", "category": "plant" },
  { "word": "කිිරිකවෙළු", "meaning": "සිතියම් කොළ (අෂ්ටක වගියේ සිරැවක්)", "category": "plant" },
  { "word": "කිිරීගු", "meaning": "මුලා", "category": "plant" },
  { "word": "කිරිගොප්ප", "meaning": "උඩවැඩියා වගියට අයත් කිරි සහිත වැලක්", "category": "plant" },

  // --- පිටුව 112 (image_861aa8.png) ---
  {
    "word": "කිරිගොප්ප",
    "meaning": "මෙය දිරා ගිය පොතු සහිත විශාල ගස්වල පැලවී එයින් මුල් බිමට ඇදී වැවෙන උඩවැඩියා වගියට අයත් වැලකි. මෙහි කඳ කොළ හා මල් වලත් සුදු පාට කිරි රාශියක් ම තිබේ. කොළ දිග පළලින් අඟල් 1 1/2 x 1 ක් පමණ ඇත. මේවා අක්කපාන කොළ මෙන් ඝනය. මල්-සැත්ගේ කණිගාරණ විශේෂයක් වූ කරාබු වලට සමානය. ලා රත් පැහැයෙන් යුත් පොකුරු සහිත ඒ මල් පිපීමෙන් පසු පරවන්නේ දොළොස් පැයකට පමණ පසුවය. අඳුරු සහිත ඝන වනාන්තර වල වැවෙන මේ වැල් වගිය උඩවැඩියා බවත් පඬිවරුන් විසින් ප්‍රකට නගරයන්හි පිහිටි ස්වකීය උඩවැඩියා ගායන්හි අලංකාරය පිණිස වවා තිබෙනු දක්නට පුළුවන. මෙය කැඩුම්-බිඳුම් වෙදකමේ අවසන්වී තිබෙන තැන් එකතු කිරීමටත් ඇට පෑස්සීමටත් ගන්නා ප්‍රත්‍යක්ෂ රහස් ඖෂධයකි.",
    "category": "plant"
  },
  { "word": "කිරිදි", "meaning": "ඔලිඳ, ගොයම් අතර වැවෙන තෘණ වගියක් (යව වැනි තෘණ පඳුරු විශේෂයක්)", "category": "plant" },
  { "word": "කිරිදි වැල්", "meaning": "වැටවල් බැඳීමට, වට්ටි පෙට්ටි ආදියේ ගැටි දැමීම වැනි ගොරෝසු වැඩට ගන්නා ලොකු වැල් වගියක්", "category": "plant" },
  {
    "word": "කිරිනුග",
    "scientific": "Ficus Infectoria",
    "meaning": "කඳේ පිට ඉතා රත් පාට පොතු සහ කුඩා අතු වලට ම ඇලී තිබෙන කබල ඇට පමණ ගෙඩි ඇති නුග වගියට අයත් ඖෂධයක් වූ මේ ගස ගැන ප්‍රමාණවත් විස්තරයක් මේ පොතේ 91 වෙනි පිටුවේ ඇත.",
    "category": "plant"
  },

  // --- පිටුව 113 (image_861ae4.png) ---
  { "word": "කිරිපලා", "meaning": "කිරිනැන්ඳ ගස", "category": "plant" },
  { "word": "කිරිපළු", "meaning": "කිරිබත්", "category": "plant" },
  { "word": "කිරිපූරණකාන්ත", "meaning": "දත්කැටියා", "category": "plant" },
  { "word": "කිරිලදූ", "meaning": "එනම් අල හෝ වැල්", "category": "plant" },
  { "word": "කිරිලින්ගී", "meaning": "කරපිංචා ගස", "category": "plant" },
  { "word": "කිරිමි", "meaning": "කුකුළු ගස, ඉඳි ගස", "category": "plant" },
  { "word": "කිරිමිස්", "meaning": "වල් නස්සල්", "category": "plant" },
  { "word": "කිරිල", "meaning": "කිරිල්ල (කිරිල්ලා ගස)", "category": "plant" },
  { "word": "කිරිලක්", "meaning": "පියා ගස", "category": "plant" },
  {
    "word": "කිරිවල්ලා",
    "scientific": "Holarrhena Antidysenterica",
    "meaning": "කෙළිඳ වගියට අයත් (ලංකා) කාම රෝග වලට ගුණැති ගසක්. විස්තර ඉදිරියෙහි ඇත.",
    "category": "plant"
  },
  { "word": "කිරිවැල්", "meaning": "ඉරමුසු", "category": "plant" },
  { "word": "කිරිරුක", "meaning": "කිරිපලු ගස, පියා ගස", "category": "plant" },
  { "word": "කිරයගුළු", "meaning": "(කිරිඳිගුළු) කිරිඳි ගුල", "category": "plant" },
  { "word": "කිරිගෑන්ද", "meaning": "කුඩා පලා ගසක්", "category": "plant" },
  { "word": "කිරිබුළු", "meaning": "කෑඳ-කිරි වක්කර පිසූ හාලේ කැඳ", "category": "treatment" },
  { "word": "කිරිව", "meaning": "වනුක් ගස", "category": "plant" },
  { "word": "කිරිසි", "meaning": "කුඹුක් ගස", "category": "plant" },
  { "word": "කිරෙර", "meaning": "නිල් තඹපලා, කුරක්කම්පලා", "category": "plant" },
  { "word": "කිල්කායනෙල්ලි", "meaning": "පිටවක්කා (බිම් නෙල්ලි)", "category": "plant" },
  { "word": "කිලිනි", "meaning": "අල", "category": "plant" },
  { "word": "කිලොපාදිකා", "meaning": "හීන් නිදිකුම්බා", "category": "plant" },
  { "word": "කිළුම", "meaning": "මෝරු", "category": "treatment" },
  { "word": "කිලබ", "meaning": "හෙලගනික, දේවදාර", "category": "plant" },
  { "word": "කිලා", "meaning": "මඟ කරඹ", "category": "plant" },
  { "word": "කිලාවින්", "meaning": "හුණ ගස, උණ ගස", "category": "plant" },
  { "word": "කිලාල", "meaning": "ගෝ මෘත", "category": "treatment" },
  { "word": "කිලාස", "meaning": "කුෂ්ඨ, පිසුම්පෙත්ත", "category": "symptom" },
  { "word": "කිලිකිලය", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "කිලිකිලි", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "කිලිකිලිප්පෙයි", "meaning": "අබනගිරිය, යක්බේරිය", "category": "plant" },
  { "word": "කිලිකව", "meaning": "දුම්මල", "category": "plant" },
  { "word": "කිලදිලි", "meaning": "කුමුදු මල්", "category": "plant" },
  { "word": "කිලිමන්", "meaning": "දේවදාර", "category": "plant" },
  { "word": "කිලිල්", "meaning": "උණ ගස, දළක් ගස", "category": "plant" },

  // --- පිටුව 114 (image_861b22.png) ---
  {
    "word": "කිරිවල්ලා",
    "meaning": "මෙය කෙළිඳ වෙනුවට ගන්නා අඟල් 1 1/2 ක් පමණ විශාල මල් ඇති අඟල් 4 ක් පමණ දිග හා අඟලක් පමණ පළල කොළ ඇති අඩි 20 ක් පමණ උසට වැඩෙන ගසකි. කොළ හැඩහුරු කමින් වැලි අතෝඩ කොළ වලට බොහෝ සේ සමාන වුව ද ප්‍රමාණයෙන් මඳක් කුඩාය. මේ ගසේ ඇට, පොතු, හා කොළ දේශීය වෛද්‍ය ප්‍රතිකාර සඳහා ගනු ලැබේ. විශේෂයෙන්ම අතීසාර, ජ්වර හා ළමා රෝග වලටත් ප්‍රත්‍යක්ෂ ඖෂධයකි.",
    "category": "plant"
  },
  { "word": "කිවි", "meaning": "රිලවා", "category": "treatment" },
  { "word": "කිසක", "meaning": "උක් ගස, උණ ගස", "category": "plant" },
  { "word": "කිසිකරෝමන්", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "කික්කුපිටින්", "meaning": "උක් ගස, උණ ගස, බට ගස", "category": "plant" },
  { "word": "කිස්මිස්", "meaning": "වියළි මිදි - උද්දප්පලම්", "category": "plant" },
  { "word": "කිසල්", "meaning": "දඹ", "category": "plant" },
  { "word": "කිසල", "meaning": "කිහිරිදිය", "category": "plant" },
  { "word": "කිසල", "meaning": "කිහිරිදිය, ලා දළුව, කොළ පත", "category": "plant" },
  { "word": "කිල්ලය", "meaning": "ලා පත්‍ර (දඹ)", "category": "plant" },
  { "word": "කිසි", "meaning": "කසට ගස", "category": "plant" },
  { "word": "කිසිගිල", "meaning": "ඉස්සෝ", "category": "treatment" },
  { "word": "කිසුම", "meaning": "මල්", "category": "plant" },
  { "word": "කිසුල්ල", "meaning": "මිදෙල්ල", "category": "plant" },
  { "word": "කිහිම", "meaning": "කුසුම", "category": "plant" },
  {
    "word": "කිහිඟිය",
    "meaning": "පිහිඹිය ගස, ඝන වනාන්තරවල විශාල ගල් අසල වැඩී වශයෙන් හටගන්නා මේ ගසේ කොළ ගරුඬාකාරය. නිල් වණි වූ ඒ කොළ පරබැලවී වැටීම ද අඩුය. ගොමුවක් සේ සාර්ථක ව (ඝනසෑරේට) වැඩී තිබෙන නිසා ග්‍රීෂ්ම ප්‍රදේශවල ගෙවල් අසල වැවීමට සුදුසුයි.",
    "category": "plant"
  },
  { "word": "කිහිරී-බදිර (රත්කිහිරිය ගස)", "meaning": "රත් කිහිරිය ගස", "category": "plant" },
  { "word": "කිංගෙදිරිදං", "meaning": "ඉද්ද", "category": "plant" },
  { "word": "කිතික", "meaning": "මැනිඇට", "category": "plant" },
  { "word": "කිිකිරිදිය", "meaning": "එලකිිකිරිදිය, අඳුන් කිිකිරිදිය යයි වගී දෙකකි. අඳුන් කිිකිරිදිය අකලට පැසෙන කෙස් කළු කරණ, ඉස සිහිල් කරණ තෙල් වලට සහ ඇතැම් අරිෂ්ට වලටත් ගණිති. මෙය අලි වෙදකමේ ද ප්‍රධාන ඖෂධයකි.", "category": "plant" },
  { "word": "කිවක", "meaning": "රන් බට", "category": "plant" },
  { "word": "කිවකා", "meaning": "පවනින් හමන හුණ", "category": "plant" },
  { "word": "කිට", "meaning": "සබෝර", "category": "plant" },
  { "word": "කිටක", "meaning": "කොසඹ ගස", "category": "plant" },
  { "word": "කිටගන", "meaning": "ගෙන්දගම් (ගන්ධක)", "category": "treatment" },
  { "word": "කිටජ", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "කිටනාම", "meaning": "රතු නිදිකුම්බා", "category": "plant" },
  { "word": "කිටපමපයා", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "කිටවිජයා", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "කිටපාදිකා", "meaning": "වලා වැන්න, රතු නිදිකුම්බා", "category": "plant" },
  { "word": "කිටමණිබාලි", "meaning": "කසඹිලියා", "category": "plant" },
  { "word": "කිටමාරිකා", "meaning": "වලා වැන්න", "category": "plant" },
  { "word": "කිටමාරි", "meaning": "වලා වැන්න", "category": "plant" },
  { "word": "කිටමාලිකා", "meaning": "වලා වැන්න", "category": "plant" },
  { "word": "කිටවිසාලිනී", "meaning": "සාලිපර්ණී", "category": "plant" },
  { "word": "කිටයතන", "meaning": "ගෙන්දගම් (ගන්ධක)", "category": "treatment" },
  { "word": "කිටයා", "meaning": "වලන්සාල්", "category": "plant" },
  { "word": "කිඛෙර", "meaning": "සුලුකුර ගස", "category": "plant" },

  // --- පිටුව 115 (image_861b4a.png) ---
  {
    "word": "කීණ",
    "meaning": "කීන ගස. මේවායේ අරටු අරිෂ්ට වලට ගණිති.",
    "category": "plant"
  },
  { "word": "කීණු", "meaning": "ගම්මිරිස්", "category": "plant" },
  { "word": "කීතනිකා", "meaning": "වැල්මී", "category": "plant" },
  { "word": "කීනාව මුල්", "meaning": "කංකාවා මුල් (කීන මුල් = කීන නැමැති ගසේ මුල්)", "category": "plant" },
  { "word": "කීනාග", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "කීන්තී", "meaning": "අවිරිය ගස", "category": "plant" },
  { "word": "කීර්ති", "meaning": "බූරාත ගස", "category": "plant" },
  { "word": "කීරා", "meaning": "මී", "category": "treatment" },
  { "word": "කීරකනැඩි අල", "meaning": "කුෂ රෝගයට ගන්නා බෙහෙතක්", "category": "plant" },
  { "word": "කීරප", "meaning": "ජයම", "category": "treatment" },
  { "word": "කීරහනුපල", "meaning": "පුලන් (ඉබිබුල්) ගස", "category": "plant" },
  { "word": "කීරනාගක", "meaning": "නොපිල", "category": "plant" },
  { "word": "කීරනායක", "meaning": "නොපිල", "category": "plant" },
  { "word": "කීරමාතා", "meaning": "වලා වැන්න", "category": "plant" },
  { "word": "කීිරික", "meaning": "කිරිපලු", "category": "plant" },
  { "word": "කීිරෙෂට", "meaning": "කොසඹ, මඟ කොසඹ, අඹ ගස, ගල්මෝර ගස", "category": "plant" },
  { "word": "කීිරෙර", "meaning": "තඹපලා වගී", "category": "plant" },
  { "word": "කීල", "meaning": "ලාටු, දුම්මල හා පොල්තෙල් උණු කිරීමෙන් සාදා ගන්නා බදම", "category": "treatment" },
  { "word": "කීල", "meaning": "කොකුම්, ලියනගලා", "category": "plant" },
  { "word": "කීලක", "meaning": "නාකුල්", "category": "plant" },
  { "word": "කීලකාසිනෙල්ලි", "meaning": "පිටවක්කා, (බිම් නෙල්ලි)", "category": "plant" },
  { "word": "කීලත්", "meaning": "මෝරු", "category": "treatment" },
  { "word": "කීලපාදිකා", "meaning": "වලා වැන්න", "category": "plant" },
  { "word": "කිලම්", "meaning": "දේවදාර", "category": "plant" },
  { "word": "කිලවනෙල්ලි", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "කිලසංසජී", "meaning": "නිගිිරි ගස", "category": "plant" },
  { "word": "කිලාල", "meaning": "ලේ, වතුර, ඉඳුසල්, මැලියම්", "category": "treatment" },
  { "word": "කිඟපන්", "meaning": "කරල්සැබෝ", "category": "plant" },
  { "word": "කිඟුලු", "meaning": "නාකුල්", "category": "plant" },
  { "word": "කිහිරෝමා", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "කිඹිදු", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කු", "meaning": "පෘථිවිය, පෘථිවි ධාතුව", "category": "treatment" },
  { "word": "කුක්කුටපපු", "meaning": "ඉඟුරු මුල්", "category": "plant" },
  { "word": "කුංචි", "meaning": "කාකෝලි (අෂ්ටක වගියේ සිරැවක්)", "category": "plant" },
  { "word": "කුබ්‍රමණි", "meaning": "සින්බිලා", "category": "plant" },
  { "word": "කුක්", "meaning": "මෝරා", "category": "treatment" },
  { "word": "කුක්කිල්", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "කුක්කුට", "meaning": "කුකුළා", "category": "treatment" },
  { "word": "කුක්කුටක", "meaning": "නොපිල, සිහින් සාතාවාරිය, ඉබිබුල්", "category": "plant" },
  { "word": "කුක්කුටපාදප", "meaning": "දෙව අබ", "category": "plant" },
  { "word": "කුක්කුටවල්", "meaning": "නොපිල", "category": "plant" },
  { "word": "කුක්කුටමකීරී", "meaning": "සිවිය", "category": "plant" },
  { "word": "කුක්කුටවම්න්තක", "meaning": "සිවිය", "category": "plant" },
  { "word": "කුක්කුට ශිබ", "meaning": "කුකුල් කරමල් ගස, වනුක් ගස", "category": "plant" },
  { "word": "කුක්කුටශිඛ", "meaning": "වනුක්, සෙන්දිරික්කා", "category": "plant" },
  { "word": "කුක්කුටා", "meaning": "කසාවත් ගිරිනීල්ල", "category": "plant" },
  { "word": "කුක්කුටාණ්ඩ", "meaning": "කිහිරි බිජු", "category": "plant" },
  { "word": "කුක්කුටාණ්ඩභම", "meaning": "කත්හිරක්කා බබු", "category": "plant" },
  { "word": "කුක්කුටි", "meaning": "ඉබිබුල්, වාෂභක (අෂ්ටක වගියේ සිරැවක්) කිඹුල්වැන්න, හින්වම්මුතු", "category": "plant" },
  { "word": "කුක්කුටිකා", "meaning": "ඉබිබුල්, (හිඟුල්)", "category": "plant" },
  { "word": "කුක්කුර", "meaning": "විෂ්ණු ක්‍රාන්ති, පොහොඹරු", "category": "plant" },
  { "word": "කුක්කුල", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "කුක්කුලකෝෂි", "meaning": "පුපුල වැල", "category": "plant" },
  { "word": "කුක්කුෂ", "meaning": "ඉළුක්", "category": "plant" },
  { "word": "කුසසි", "meaning": "තිත්ත ලබු", "category": "plant" },
  { "word": "කුසිරඬු", "meaning": "බට ගස", "category": "plant" },
  { "word": "කුසමුසුල", "meaning": "බබරාජා ච", "category": "plant" },
  { "word": "කුසහ", "meaning": "මී පැණි", "category": "treatment" },
  { "word": "කුකුට", "meaning": "ඉබිබුල් ගස, කිඹුල්වැන්න", "category": "plant" },
  { "word": "කුකුටමසන", "meaning": "සිවිය", "category": "plant" },
  { "word": "කුකුටි", "meaning": "ඉබිබුල් ගස", "category": "plant" },
  { "word": "කුකුන්ඨ", "meaning": "මෑ, ළමා", "category": "plant" }
];