// data_335_344.js - පිටු 335 සිට 344 දක්වා සියලුම වචන
const data_extra_335_344 = [
    // --- පිටුව 335 ---
    { 
        "word": "බුරුල්ල ගස", 
        "meaning": "බුරුල්ල ගස. ඉර-හඳ නොදුටු දළු නමින් රහස් බෙහෙත් වට්ටෝරු වල තිබෙන මේ ගසේ පෙතන් කපු ගෙඩිවැනි කෝෂ තුල තිබෙන දළු තුවාල සුව කිරීමට ත්, තල තෙල් සමග මිශ්‍ර කර ගත් මේ දළු සහ ගසේ බඩය (මද=ලොඳ) පිළිස්සුම් තුවාල වලට හා තෙල් වර්ග සෑදීමට ත් ප්‍රයෝජන වත් ය.", 
        "category": "plant",
        "image": "img_335_burulla.jpg"
    },
    { "word": "බුරුවා", "meaning": "කිකිරිඳිය", "category": "plant" },
    { 
        "word": "බුලත්", 
        "meaning": "(තාම්බුල) නාගවල්ලි, කහ බුලත්, දිය බුලත්, මලයා (ගල්) බුලත්, ගස් බුලත්, කොවු බුලත්, බුලත්පාලා, (බිම දිව බුලත්) යයි රසයෙන් හා ගුණයෙන් වෙනස් වූ බුලත් වර්ග සමූහයකි. හැම බුලත් වැලක ම කඳ (නො පිදුන) කොළ හා කිනිති(පිදුන)බුලත් කොළ හැඩහුරු කමින්, රසයෙන් හා ගුණයෙන් අසමාන ය. බුලත් ඇතැම් ආසියාතික ජාතීහු මංගල සම්මත ද්‍රව්‍යයක් ලෙස සලකති.", 
        "category": "plant" 
    },
    { "word": "බුලන්තිය", "meaning": "දිවුල්", "category": "plant" },
    { 
        "word": "බුලත්ගුහ", 
        "meaning": "බුලතෙහි ගුණ-කැට,තික්ත,මධුර, ක්‍ෂාර, කසට රස, වා, සෙම්, කාමරෝග දුරුවීම, මුව දුගඳ පහවීම හා සැරසිම, මළ පිරිසිදු කිරීම, කාමාග්නි දීපනය හා උෂ්ණ ගුණයෙන් යුක්ත වීම; යන තෙළෙස යි. බුලත් සපීම කරන්නේ මේ කී ගුණ ගැන පාරම්පරික දැනීමක් ඇති නිසා ය.", 
        "category": "plant" 
    },
    { "word": "බුම්බෝ", "meaning": "බෝගස", "category": "plant" },
    { "word": "බුවන", "meaning": "අබ", "category": "plant" },
    { "word": "බුවනක", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "බුත්සැන්ද", "meaning": "මුස්සැන්දවලට ඇතැම් පළාත් වල මෙසේ ව්‍යවහාර කරති.", "category": "plant" },
    { "word": "බුසුන්", "meaning": "ගස්මුල, රුක්මල්", "category": "plant" },
    { "word": "බුකාන්ද", "meaning": "කොළය යට බුවක් තිබෙන කැන්ද විශේෂය, ගන්දි බෙහෙත් වශයෙන් ප්‍රසිද්ධ යි.", "category": "plant" },
    { "word": "බුකිද", "meaning": "බුව සහිත කොළ ඇති කිඳි වර්ගයට මේ නම ව්‍යවහාර වේ.", "category": "plant" },
    { "word": "බුතකේශි", "meaning": "නික", "category": "plant" },
    { "word": "බුතවේධ්‍ය", "meaning": "තලා", "category": "plant" },
    { "word": "බුනිබ", "meaning": "බිංකොසඹ", "category": "plant" },

    // --- පිටුව 336 & 337 (බෙහෙත් අනෝදා විස්තරය පිටු දෙකේම ඇත) ---
    { "word": "බුපදි", "meaning": "බෝලිද්ද", "category": "plant" },
    { "word": "බුමුල්ල", "meaning": "පොල් අතු මුල එකට බැඳී තිබෙන දැල වැනි කවරය. මෙය ඉටි ආදිය ඇතුව බොහො දියර දේවල් පෙරීමට පෙරහනක් ලෙස පාවිච්චි කරති.", "category": "equipment" },
    { "word": "බුමිඅවකාර", "meaning": "එළ බින්තඹුරු", "category": "plant" },
    { "word": "බුමිලතා", "meaning": "බිමිතඹුරු වැල", "category": "plant" },
    { "word": "බුරන්ද", "meaning": "ගුරන්ද = ගරිද (අරිමෙද)", "category": "plant" },
    { "word": "බුවල්ල", "meaning": "පොල්ගෙඩි වැටීමෙන් පසු ඉතිරිවන (හිස්) වල්ල", "category": "plant" },
    { "word": "බුසා", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "බුහනයහ", "meaning": "පොල්මල වැසී තිබෙන සණ කවරය", "category": "plant" },
    { "word": "බෙන්ඩුවාල", "meaning": "කොන්තර", "category": "plant" },
    { "word": "බෙණි", "meaning": "කරපිංචා", "category": "plant" },
    { "word": "බෙයද", "meaning": "පතිතය, කදුරලියා", "category": "plant" },
    { "word": "බෙයලිත්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "බෙරලිය", "meaning": "පලා වර්ගයක්,(දියබෙරලිය, ගොඩ බෙරලිය යයි දෙවගයකි)", "category": "plant" },
    { "word": "බෙරාවි", "meaning": "බෙදුරු", "category": "plant" },
    { "word": "බෙරු", "meaning": "තෘණ වර්ගයක්,අවරියගස", "category": "plant" },
    { "word": "බෙරැමුල්", "meaning": "බේරුමුල්", "category": "plant" },
    { "word": "බෙල්බිජු", "meaning": "බෙලි ඇට", "category": "plant" },
    { "word": "බෙල්මදුව", "meaning": "බෙලි ගෙඩියේ මද", "category": "plant" },
    { "word": "බෙලි", "meaning": "බෙල්ලෝ, මලිගිය වැල, ඉද්දවැල, බෙලි(බිල්ව) ගස", "category": "plant" },
    { "word": "බෙලිදෑවල", "meaning": "බෙලි ගෙඩියේ මද", "category": "plant" },
    { "word": "බෙලිමදුව", "meaning": "බෙලි ගෙඩියේ මද", "category": "plant" },
    { "word": "බෙලිමැලසි", "meaning": "බෙලිගැට (නොපැසුන ගෙඩි)", "category": "plant" },
    { "word": "බෙලියනුග", "meaning": "කාවාටි බෙල්ලන් කැබැලි වතුර උණුකර උකු කොට සාදා ගන්නා ද්‍රව ආහාරයක්. මේ වර්ගය සම්බෝල හා හොදි ව්‍යංජන රසවත් කිරීමට ප්‍රතිවාප වශයෙන් යොදති. මේ බෙල්ලෝ බෙන්තර ගඟේ සුලභ ව සිටිති.", "category": "food" },
    { "word": "බෙලිල", "meaning": "කොබෝලීල ගස", "category": "plant" },
    { "word": "බෙලුවා", "meaning": "බෙලි", "category": "plant" },
    { "word": "බෙහෙරපලා", "meaning": "අවරිය කොළ", "category": "plant" },
    { 
        "word": "බෙහෙත් අනෝදා", 
        "scientific": "Abutilon Indicum",
        "meaning": "කහ පාට මල් සහ කොකිස් අව්වු වැනි කුඩා ගෙඩි සෑදෙන මේ ගසේ කොළ සිංහල කැකුළු හාල් සමග තම්බා එම හාල්පාණු වෙන් ම අඹරා කල්ගිය ඔඩු-වන-තුවාලවල ගෑමෙන්, ඔඩු දුව තිබේ නම් ඒ ඔඩු ඇදී, කෝෂය තිබේ නම් එය ද කැපී තුවාල ශුද්ධවී රතු මස් පෑදී ඉක්මනින් සුවය ලැබේ යි. මේ ගසේ කොළ වලින් හා මුල් වලින් ලබාගන්නා සාරයෙන් උපදංශ (පරංගි) හා සමාජරෝග නිසා ඇතිවන තුවාල ද සුවකර ගත හැකි යි. මේ සිංහල කැකුළුහාල් කුඩු සහිත අනෝදා මිශ්‍රණයෙන් ඔඩු දුව-වණ තුවාල වලට වර්තමාන පෙනිසිලින් වලින් ලැබෙන ගුණයට සමාන ගුණයක් ලැබෙන බව අත්දැකීම් අනුව කිව හැක.", 
        "category": "plant",
        "image": "img_336_anoda.jpg"
    },
    { "word": "බෙහොරු", "meaning": "බටු", "category": "plant" },
    { "word": "බෙදුරු", "meaning": "ගස් උඩ වැවෙන පැළෑටි වර්ගයක් (උඩවැඩියා)", "category": "plant" },
    { "word": "බේරා", "meaning": "අවරිය", "category": "plant" },

    // --- පිටුව 337 ---
    { "word": "බොකල", "meaning": "බොකල වැල්", "category": "plant" },
    { "word": "බොජුන්", "meaning": "බත්", "category": "food" },
    { "word": "බොටු", "meaning": "බටු", "category": "plant" },
    { "word": "බොඩහමු", "meaning": "බඩහමු=කරල් එළියට නොඇදී පිදෙන බණ්ඩිය එලෙස ම පැසෙන අමුවර්ගය", "category": "plant" },
    { "word": "බොඩහමුසාල්", "meaning": "බඩ අමු හාල් (අමු ඇට තුල තිබෙන මද)", "category": "plant" },
    { "word": "බොඩ", "meaning": "බෝදි ගස", "category": "plant" },
    { "word": "බොද", "meaning": "ඉස්ම", "category": "liquid" },
    { "word": "බොධන", "meaning": "අගිල්", "category": "plant" },
    { "word": "බොධනා", "meaning": "දඩකලත්", "category": "plant" },
    { "word": "බොධනී", "meaning": "වදකසා, නිප්පිලි, වම්බටු", "category": "plant" },
    { "word": "බොධනීය", "meaning": "වදකසා, තලාගස", "category": "plant" },
    { "word": "බොරැදමුණු", "meaning": "උගුරැස්ස", "category": "plant" },
    { "word": "බොල්පනාලබන්තා", "meaning": "පුහු පතා මල්", "category": "plant" },
    { "word": "බොලටිය", "meaning": "ඇස්වටය", "category": "anatomy" },
    { "word": "බොලරස", "meaning": "වටවනාචි", "category": "plant" },
    { "word": "බොලුසුණු", "meaning": "බෙල්ලන් දවා පුලුස්සා ගත් සුණු (අළු)", "category": "mineral" },
    { "word": "බොහොඹ", "meaning": "කටුස්සා", "category": "animal" },
    { "word": "බෝදෘ", "meaning": "ගෙද", "category": "plant" },
    { "word": "බෝදනතුෂ්ටි", "meaning": "ගෙදපලා", "category": "plant" },
    { "word": "බෝදිඇට", "meaning": "කළු කොල්ලු ඇට වැනි ඇට වර්ගයක්. බාකුවි, බබුවි, (ඉදිරියෙහි සන්නිනායම් ගණන ලියූ ඡායාරූප සහිත විස්තරය බලන්න)", "category": "plant" },
    { "word": "බෝදිලි", "meaning": "බොහෝ පලදාව ඇති කුඩා පොල් වර්ගයක්", "category": "plant" },
    { "word": "බෝදි", "meaning": "ඇසටු, බෝගස", "category": "plant" },
    { "word": "බෝදුම්", "meaning": "බෝගස, ඇසටු", "category": "plant" },
    { "word": "බෝධි", "meaning": "ඇසටු, බෝගස", "category": "plant" },
    { "word": "බෝධිදෘම", "meaning": "ඇසටු, බෝගස", "category": "plant" },
    { "word": "බෝධිපාදප", "meaning": "ඇසටු, බෝ, පුලිල ගස", "category": "plant" },
    { "word": "බෝනුග", "meaning": "එනම් ගස", "category": "plant" },
    { "word": "බෝපල", "meaning": "මිගස", "category": "plant" },
    { "word": "බෝඹු", "meaning": "ලොඹු වර්ගයේ ගසක්. නියම ලොඹු නැතිවූ විට ගත යුත්තේ ලොත් සුඹුලු නොව මේ ගසේ පොතු ය. (ලොත් සුඹුලු ගණ ඉදිරියෙහි ලියා ඇති ඡායාරූප සහිත විස්තරය බලන්න)", "category": "plant" },
    { "word": "බෝබිජු", "meaning": "දෙඹම් ගස", "category": "plant" },
    { "word": "බෝබෝලු", "meaning": "කුඩා ගෙඩිය (ගැටය)", "category": "plant" },

    // --- පිටුව 338 ---
    { 
        "word": "බෝමී", 
        "scientific": "Litsaea Sebifera",
        "meaning": "Litsaea Sebifera- මේ ගසේ පොතු දේශීය වෙදකමේ බිඳුන ඇට පෑස්සීමට ගන්නා ප්‍රධාන ඖෂධයකි. මේ පොතු අමුකහ සමග අඹරා ගෑමෙන් සිරීම් සහ තුවාල ද සුව වේ. අතිසාර රෝගයට හා ස්නායු දුර්වලකමට දෙන ඖෂධ සංයෝග වලට ද උවල් පොතු ඇතුළත් ව තිබේ.", 
        "category": "plant",
        "image": "img_338_bomi.jpg"
    },
    { "word": "බෝරක්", "meaning": "ඇසතු ගස", "category": "plant" },
    { "word": "බෝල", "meaning": "වච්චනාභි, ගෙන්දගම්", "category": "plant" },
    { "word": "බෝලිද්ද", "meaning": "ඉද්ද වර්ගයක්, මලිගිය වැල", "category": "plant" },
    { "word": "බෘංග", "meaning": "ඉඳි, කිකිරිඳිය, කරාඹු", "category": "plant" },
    { "word": "බෘංගරාජ", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "බෘංගලතා", "meaning": "වැල්තිබ්බටු", "category": "plant" },
    { "word": "බෘහත්ඵලා", "meaning": "තිත්තලබු", "category": "plant" },
    { "word": "බෘහති", "meaning": "වම්බටු, ඇත් බටු, තිබ්බටු, එළ බටු", "category": "plant" },
    { "word": "බෘහාර", "meaning": "කටරොළු", "category": "plant" },
    { "word": "බෘහේසි", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "බෘහ", "meaning": "ඉඳි", "category": "plant" },
    { "word": "බෘහාරාජ", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "බෘහි", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "බෘහලතා", "meaning": "වැල්තිබ්බටු", "category": "plant" },
    { "word": "බෘක්‍ෂන", "meaning": "කරාබුනැටි, කොත්තමල්ලි", "category": "plant" },
    { "word": "බෘජනි", "meaning": "වැල", "category": "plant" },
    { "word": "බෘඩත", "meaning": "වරාගස", "category": "plant" },
    { "word": "බෘන්‍ද", "meaning": "බෙබර", "category": "plant" },
    { "word": "බෘන්‍දක", "meaning": "බාඳුත නම් මුඛරෝගය", "category": "treatment" },
    { "word": "බෘන්‍ම", "meaning": "ලුණුවිල, රත්කෑලිය", "category": "plant" },
    { "word": "බෘන්‍මකණ්ටක", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "බෘන්‍මකණ්ණකා", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "බෘන්‍මකාෂ්ඨ", "meaning": "පුවක්ගස", "category": "plant" },
    { "word": "බෘන්‍මකෙශි", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "බෘන්‍මකොශ", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "බෘන්‍මචාරිණී", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "බෘන්‍මජටා", "meaning": "කුකුරුමුවන්, ජටාමාංශ", "category": "plant" },
    { "word": "බෘන්‍මදාරු", "meaning": "බුන්මදාරාගස", "category": "plant" },
    { "word": "බෘන්‍මදරු", "meaning": "රත්කෑල, පුවක්", "category": "plant" },
    { "word": "බෘන්‍මතිනි", "meaning": "නෙළුම්අල", "category": "plant" },
    { "word": "බෘන්‍මදණ්ඩ", "meaning": "පුවක්", "category": "plant" },
    { "word": "බෘන්‍මදණ්ඩී", "meaning": "යොන්තුඹ", "category": "plant" },
    { "word": "බෘන්‍මදත්තා", "meaning": "කොරාසානි, අසමෝද", "category": "plant" },
    { "word": "බෘන්‍මදුරු", "meaning": "බුන්මදාරා ගස", "category": "plant" },
    { "word": "බෘන්‍මන", "meaning": "බුන්මදාරා, පුවක්ගස", "category": "plant" },
    { "word": "බෘන්‍මපර්ණී", "meaning": "පුස්වැන්න", "category": "plant" },

    // --- පිටුව 339 ---
    { "word": "බෘන්‍මපාදප", "meaning": "කාලගස", "category": "plant" },
    { "word": "බෘන්‍ම මණ්ඩූකි", "meaning": "මකුණුවැන්න, ගොටුකොළ", "category": "plant" },
    { "word": "බෘන්‍මමෙලස", "meaning": "මුකුප් නම් තණකොළ වර්ගය", "category": "plant" },
    { "word": "බෘන්‍මමුලි", "meaning": "බැමිතිරිය, ලුණුවිල", "category": "plant" },
    { "word": "බෘන්‍මය", "meaning": "සූරියකාන්ති", "category": "plant" },
    { "word": "බෘන්‍මයව", "meaning": "යාප්පුර", "category": "plant" },
    { "word": "බෘන්‍මරොෂ්ට", "meaning": "පුවක්ගස", "category": "plant" },
    { "word": "බෘන්‍මලතා", "meaning": "රසකිඳවැල්", "category": "plant" },
    { "word": "බෘන්‍මවර්ධන", "meaning": "තඹ", "category": "mineral" },
    { "word": "බෘන්‍මවෘක්‍ෂ", "meaning": "අහුගස, පලසමිදිවැල", "category": "plant" },
    { "word": "බෘන්‍මවෘක්‍ෂ(2)", "meaning": "කාලගස, රත්කෑල", "category": "plant" },
    { "word": "බෘන්‍මශෘංගී", "meaning": "කෝමාරිකා", "category": "plant" },
    { "word": "බෘන්‍මසාල", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "බෘන්‍මසෘපලා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "බෘන්‍මසූවර්චලා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "බෘන්‍මා", "meaning": "මහඑන්සාල්, මකුණුවැන්න", "category": "plant" },
    { "word": "බෘන්‍මාජ්‍ය", "meaning": "ගෝමුත්‍රා", "category": "animal" },
    { "word": "බෘන්‍මාදනී", "meaning": "වලාවැන්න", "category": "plant" },
    { "word": "බෘන්‍මාදෘශ්‍ය", "meaning": "ගෝමුත්‍රා", "category": "animal" },
    { "word": "බෘන්‍මී", "meaning": "කෝවක්කා, බැමිතිරිය", "category": "plant" },
    { "word": "බෘහප්ඵලා", "meaning": "මහබැවිල, අස්බැවිල", "category": "plant" },
    { "word": "බෘහත්", "meaning": "රක්අත්තන", "category": "plant" },
    { "word": "බෘහත්පත්‍ර", "meaning": "සබරලොත්", "category": "plant" },
    { "word": "බෘහත්පර්ණී", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "බෘහත්පර්ණී(2)", "meaning": "තෙලගස", "category": "plant" },
    { "word": "බෘහත්පුෂ්පී", "meaning": "සනගස", "category": "plant" },
    { "word": "බෘහත්ඵලා", "meaning": "තිත්ත ලබු", "category": "plant" },
    { "word": "බෘහති", "meaning": "කිරිඳි, වම්බටු, තිබ්බටු, මහහෙළබටු, කටුවැල්බටු, රුක්තිබ්බටු", "category": "plant" },
    { "word": "බෘහතිඵල", "meaning": "එළබටුගෙඩි", "category": "plant" },
    { "word": "බෘහත්‍යාදිගණය", "meaning": "හෙළබටු, කටුවැල්බටු, දියමිත්ත, වැල්මී, කෙළිඳසාල්, යන මේ ගණය දොස් පැසවීමට හිතයි. මුත්‍රා කෘච්ඡ්‍රාව හා තුන්දොස් පැසවීම ද කරයි.", "category": "compound" },
    { "word": "බෘහත්‍යෙය", "meaning": "කටුවැල්බටු, හෙළබටු", "category": "plant" },
    { "word": "බෘහදෙලා", "meaning": "මහඑන්සාල්, සිරිවාඩි බැවිල", "category": "plant" },
    { "word": "බෘහස්පර්ණී", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "බ්‍රාහ්මණ", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "බ්‍රාහ්මණකන්‍දා", "meaning": "බිමිතල්අල,ඌරල", "category": "plant" },
    { "word": "බ්‍රාහ්මණයාෂ්ටිකා", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "බ්‍රාහ්මණී", "meaning": "සිරිතේක්කු, මුක්මල්", "category": "plant" },
    { "word": "බ්‍රාහ්මී", "meaning": "බැමිතිරිය, (ලුණුවිල)", "category": "plant" },
    { "word": "බ්‍රාහ්මීකන්‍ද", "meaning": "බිමහල්", "category": "plant" },
    { "word": "බ්‍රාහ්මීනී", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "බ්‍රැන්‍දාබ", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "භාජන", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "භණ්ඩාකි", "meaning": "වම්බටු, තිබ්බටු", "category": "plant" },
    { "word": "භසන්තක", "meaning": "සිනිත්ගොකටු", "category": "plant" },
    { "word": "භසන්‍යපත්‍ර", "meaning": "බුනේත්", "category": "plant" },
    { "word": "භක්ත", "meaning": "බත්", "category": "food" },
    { "word": "භක්තක", "meaning": "ඇඹුලගස", "category": "plant" },
    { "word": "භක්තායතක", "meaning": "ගොකටු", "category": "plant" },
    { "word": "භගන්‍ධලා", "meaning": "කොටදිඹුලාගස", "category": "plant" },
    { "word": "භගංග", "meaning": "ත්‍රස්තාවළු, අරළු, නෙල්ලි, කුරුඳු", "category": "plant" },
    { "word": "භගංගා", "meaning": "කංසා, දුහුදු", "category": "plant" },
    { "word": "භගංනිකා", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "භගංනි", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "භගඬුර", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "භගෙබාදකයා", "meaning": "ඖෂධ හර හා කොළ වගී තැම්බූ වතුර.(මේ බෙහෙත් වතුර ඇතැම් රෝගාබාධ වලදී නෑම පිණිස ගනු ලැබේ.)", "category": "treatment" },
    { "word": "භඬජ්නක", "meaning": "වැල් මුරුංගා", "category": "plant" },
    { "word": "භඬජ්කා", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "භඬජ්", "meaning": "සින්දුමැඬ වැල, සිරිතේක්කු", "category": "plant" },

    // --- පිටුව 340 ---
    { "word": "භණ්ඩාකි", "meaning": "වම්බටු, බටු, කටුවැල් බටු", "category": "plant" },
    { "word": "භණ්ටාර", "meaning": "එළබටු", "category": "plant" },
    { "word": "භණඩාකි", "meaning": "තිබ්බටු, එළබටු; වම්බටු", "category": "plant" },
    { "word": "භණඩිකෝ", "meaning": "බදුවද", "category": "plant" },
    { "word": "භණඩිලෝ", "meaning": "මහරි", "category": "plant" },
    { "word": "භණඩී", "meaning": "වදගස, වැල්මදට, මාරා", "category": "plant" },
    { "word": "භණඩීර", "meaning": "සුප්කූර,මාරා, වැල්මදට", "category": "plant" },
    { "word": "භණඩීරලතිකා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "භණඩීරිකා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "භණඩීරි", "meaning": "මිදෙල්ල, වැල්මදට", "category": "plant" },
    { "word": "භණඩීල", "meaning": "මාරා ගස, මහරි", "category": "plant" },
    { "word": "භණඩූක", "meaning": "තොටිල", "category": "plant" },
    { "word": "භද්‍ර", "meaning": "බුලත්, කච්චිගම්, කලාදුරු, ඉරමුසු, දේවදාර, බක්මී, මහකූර, රත්රන්, දක්, කෙළිඳ, සඳුන්, නිල්මානෙල්, අලකිරියා, ගොකටු", "category": "plant" },
    { "word": "භද්‍රක", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "භද්‍රකණ්ඩක", "meaning": "ගොකටු", "category": "plant" },
    { "word": "භද්‍රකණ්ණ්‍යා", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "භද්‍රකාෂ්ඨ", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "භද්‍රකාශ්මරී", "meaning": "ඇද්දෙමට", "category": "plant" },
    { "word": "භද්‍රකාහී", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "භද්‍රකාෂ්ඨ(2)", "meaning": "දේවදාර", "category": "plant" },
    { "word": "භද්‍රකුම්භ", "meaning": "ඇද්දෙමට", "category": "plant" },
    { "word": "භද්‍රගන්ධ", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "භද්‍රගන්ධිකා", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "භද්‍රජ්", "meaning": "කෙමුන්ද", "category": "plant" },
    { "word": "භද්‍රදාරු", "meaning": "දේවදාර", "category": "plant" },
    { "word": "භද්‍රනාමිකා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "භද්‍රපර්ණිකා", "meaning": "ඇද්දෙමට", "category": "plant" },
    { "word": "භද්‍රපර්ණී", "meaning": "සාරණ, ආපසුමුදු, ඇද්දෙමට", "category": "plant" },
    { "word": "භද්‍රඵල", "meaning": "ඇද්දෙමට, පියාගස", "category": "plant" },
    { "word": "භද්‍රබලා", "meaning": "වැල්බැවිල, ආපසුමුදු", "category": "plant" },
    { "word": "භද්‍රබන්‍ධි", "meaning": "ගසුබු", "category": "plant" },
    { "word": "භද්‍රමල්ලිකා", "meaning": "යොන්තුඹ, බෝලිද්ද", "category": "plant" },
    { "word": "භද්‍රමුස්ත", "meaning": "කලාදුරු, (වම්මුතු)", "category": "plant" },
    { "word": "භද්‍රමුස්තක", "meaning": "කලාදුරු, (වම්මුතු)", "category": "plant" },
    { "word": "භද්‍රයව", "meaning": "කෙළිඳ ඇට, කෙළින්දගස", "category": "plant" },
    { "word": "භද්‍රවතී", "meaning": "ඇද්දෙමට", "category": "plant" },
    { "word": "භද්‍රවමින්", "meaning": "ඉද්දගස", "category": "plant" },
    { "word": "භද්‍රවල්ලි", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "භද්‍රවලා", "meaning": "ආපසුමුදු, වැල්බැවිල", "category": "plant" },
    { "word": "භද්‍රශාල", "meaning": "යහපත් සල්ගස, සුභද්‍රවෘක්‍ෂය", "category": "plant" },
    { "word": "භද්‍රශ්‍රි", "meaning": "සඳුන්", "category": "plant" },
    { "word": "භද්‍රශ්‍රී", "meaning": "එළ සඳුන්, රත්සඳුන්", "category": "plant" },
    { "word": "භද්‍රශ්‍රිය", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "භද්‍රසුභද්‍ර", "meaning": "දේවදාර", "category": "plant" },
    { "word": "භද්‍රසිරි", "meaning": "සඳුන්", "category": "plant" },
    { "word": "භද්‍රා", "meaning": "බුලත්වැල, ඊතණ, සුදු බැවිල, ප්‍රස්සමන්, බැමිතිරිය, හින් ඉරමුසු, ඇත්දෙමට, කුරපලා", "category": "plant" },
    { "word": "භද්‍රාපත්‍රිකා", "meaning": "කන්සා", "category": "plant" },
    { "word": "භද්‍රාලී", "meaning": "මැසිඳු", "category": "plant" },
    { "word": "භද්‍රාශ්‍රය", "meaning": "සඳුන්", "category": "plant" },
    { "word": "භදෝලා", "meaning": "මහ එන්සාල්", "category": "plant" },
    { "word": "භද්‍රෝදනී", "meaning": "සුළු බැවිල", "category": "plant" },
    { "word": "භද්‍රෝකන්තී", "meaning": "සුළුබැවිල", "category": "plant" },
    { "word": "භනස්", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "භමහරාළී", "meaning": "මැසිඳු", "category": "plant" },
    { "word": "භයනාශිනී", "meaning": "ලූණුවිල", "category": "plant" },
    { "word": "භර්පක", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "භර්තෘස්‍යපත්‍රක", "meaning": "මහබෙරු", "category": "plant" },
    { "word": "භර්‍ය්‍යයී", "meaning": "වැල්පෙනෙල", "category": "plant" },
    { "word": "භර්ල", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "භර්ලනක", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "භර්ලතකි", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "භර්ලි", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "භරෝබාහා", "meaning": "දුවගස", "category": "plant" },
    { "word": "භල්ලාතක", "meaning": "සෙන්කොට්ටම්, හල්ලාතක වෙනුවට ප්‍රතිනිධි වශයෙන් බදුල්ල මේ රටේ ගනිති. මේ දෙවර්ගය ම විෂ සහිත ය. විෂ මරා ගත යුතුයි.", "category": "plant" },

    // --- පිටුව 341 ---
    { "word": "භල්ලුක", "meaning": "මහමිදි, තොටිල", "category": "plant" },
    { "word": "භව්‍ය", "meaning": "ගර්භප්පිලි, කාමරංගා, හොඩපර, සිවිය", "category": "plant" },
    { "word": "භව්‍යපතංග", "meaning": "වරාගස", "category": "plant" },
    { "word": "භෂ්ම", "meaning": "අළු, අමුකපුරු", "category": "mineral" },
    { "word": "භෂ්මක", "meaning": "රත්රන්, රිදී, වලඟසාල්, වටරුකැණි", "category": "mineral" },
    { "word": "භෂ්මගන්ධිනී", "meaning": "රහැණිය, (වාල්මොලඟු)", "category": "plant" },
    { "word": "භෂ්මගර්භ", "meaning": "කෝන්ගස", "category": "plant" },
    { "word": "භෂ්මගර්භා", "meaning": "සාමගස, ඇට්ටරගස", "category": "plant" },
    { "word": "භස්තිකෝල්", "meaning": "ගර්භප්පිලි", "category": "plant" },
    { "word": "භාජ්", "meaning": "දුමැඬ", "category": "plant" },
    { "word": "භාණඩී", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "භාණඩිල", "meaning": "මාරා, වැල්මදට, සිරි තේක්කු", "category": "plant" },
    { "word": "භාණඩීර", "meaning": "පිත්ත, ගස් පිත්ත", "category": "plant" },
    { "word": "භානු", "meaning": "වරාගස", "category": "plant" },
    { "word": "භානුඵල", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "භානුඵලා", "meaning": "කෙසෙල්ගෙඩි", "category": "plant" },
    { "word": "භානුහත්ථා", "meaning": "කෝවක්කා, සූරිය කාන්ත", "category": "plant" },
    { "word": "භානුමත්", "meaning": "වරා", "category": "plant" },
    { "word": "භාගීව", "meaning": "රතණ", "category": "mineral" },
    { "word": "භාරගවී", "meaning": "රතණ, හෙළ රතණ", "category": "mineral" },
    { "word": "භාරගිපර්ණී", "meaning": "දම්දෙවිසුදු", "category": "plant" },
    { "word": "භාරගී", "meaning": "සිරිතේක්කු, කටුවැල්බටු", "category": "plant" },
    { "word": "භාරගෂ", "meaning": "පුලිල ගස", "category": "plant" },
    { "word": "භාරග්‍යාමෘත", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "භාරගී(2)", "meaning": "බුළු", "category": "plant" },
    { "word": "භාරකේශර", "meaning": "කටුකෑල", "category": "plant" },
    { "word": "භාරති", "meaning": "තලා, ලුණුවිල", "category": "plant" },
    { "word": "භාරද්වාජ්", "meaning": "වල්කපු", "category": "plant" },
    { "word": "භාරද්වාජ්(2)", "meaning": "කලා, මහ බැවිල, වල් කපු, අනෝද, සිරිවාඩිබැවිල", "category": "plant" },
    { "word": "භාරදාර", "meaning": "සල්ගස", "category": "plant" },
    { "word": "භාරපාදතා", "meaning": "බරවා රෝග ය", "category": "treatment" },
    { "word": "භාරවාහිනී", "meaning": "බෙරු", "category": "plant" },
    { "word": "භාස්කර", "meaning": "කපුරු, වරාගස", "category": "plant" },
    { "word": "භාස්කන්", "meaning": "වරාගස", "category": "plant" },
    { "word": "භාස්වර", "meaning": "වරා, කොට්ටන්", "category": "plant" },
    { "word": "භාසුර පුෂ්පී", "meaning": "ඇත්සේරිය", "category": "plant" },
    { "word": "භිංග", "meaning": "දුදු", "category": "plant" },
    { "word": "භික්‍ෂා", "meaning": "බත්", "category": "food" },
    { "word": "භික්‍ෂු", "meaning": "මුඛමඟන, (වෙල්මුඩ)", "category": "plant" },
    { "word": "භික්‍ෂුකා", "meaning": "මයිලගස", "category": "plant" },
    { "word": "භිඩගටා", "meaning": "දමුකුඹ, (දමිකුඹ=වලඳ පතුලෙහි දැලි=මඳක් පිළිස්සුන) ආහාර කොටස", "category": "food" },
    { "word": "භිඩගරාජ්", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භිඩගා", "meaning": "දුදු", "category": "plant" },
    { "word": "භිඩගාතක", "meaning": "තියන් වැටකොළු", "category": "plant" },
    { "word": "භිඩගිරස", "meaning": "කටුවෙලඟ", "category": "plant" },
    { "word": "භිණ්ඩා", "meaning": "බණ්ඩක්කා", "category": "plant" },
    { "word": "භින්න", "meaning": "ත්‍රස්තාවළු", "category": "plant" },
    { "word": "භිද", "meaning": "කොකුම්", "category": "plant" },
    { "word": "භිදුර", "meaning": "පුමිල,", "category": "plant" },
    { "word": "භින්නහඳුර", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "භින්නහින්නනාත්මන්", "meaning": "වණක, (කබල), අක්කාපාන", "category": "plant" },
    { "word": "භිම", "meaning": "ගොරක", "category": "plant" },
    { "word": "භිමක", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "භිරණ්ඩිකා", "meaning": "වරාමල්", "category": "plant" },
    { "word": "භිරා", "meaning": "ඇත්දෙමට, සාතාවාරිය, කටුවැල්බටු", "category": "plant" },
    { "word": "භිල්ලතරු", "meaning": "ලොත්", "category": "plant" },
    { "word": "භිල්ලා", "meaning": "කලාදුරු වෙසෙසක් (කෙවෙනි මුසක)", "category": "plant" },
    { "word": "භිල්ලී", "meaning": "ලොත්", "category": "plant" },
    { "word": "භිෂක්", "meaning": "වංඇපල, ගල්සෙවෙල්", "category": "plant" },

    // --- පිටුව 342 ---
    { "word": "භිෂක්ජිතා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "භිෂක්ප්‍රියා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "භිෂක්මාතා", "meaning": "වංඇපල", "category": "plant" },
    { "word": "භිෂන්වර", "meaning": "අරළු", "category": "plant" },
    { "word": "භිෂන්ගඬා", "meaning": "දත්ත වෙසෙසක්, (හෘදන්තී)", "category": "plant" },
    { "word": "භිෂද්‍රී", "meaning": "ඉරක්", "category": "plant" },
    { "word": "භිෂපුෂ්ප", "meaning": "රත්නෙළුම්", "category": "plant" },
    { "word": "භිෂවිප්‍රියා", "meaning": "අරළු", "category": "plant" },
    { "word": "භිසසටා", "meaning": "දා ගිය බත් (අමුවත්)", "category": "food" },
    { "word": "භිසකෙකා", "meaning": "වේදා", "category": "person" },
    { "word": "භීම", "meaning": "ඇඹුල්වේ, (ගොරකගස)", "category": "plant" },
    { "word": "භීමකා", "meaning": "මයිලගස", "category": "plant" },
    { "word": "භීරු", "meaning": "ඇද්දෙමට, සාතාවාරිය, සුදු ඊයම්", "category": "plant" },
    { "word": "භීරුක", "meaning": "උක් වෙසෙසක්", "category": "plant" },
    { "word": "භීරුපත්‍රී", "meaning": "සාතාවාරිය කොළ", "category": "plant" },
    { "word": "භීරුපත්‍රී(2)", "meaning": "ශාතාවාරිය", "category": "plant" },
    { "word": "භීෂණ", "meaning": "කිතුල්ගස, තුන්දුරුක්කන්, ගුල්ලකි", "category": "plant" },
    { "word": "භීෂණාහ්වය", "meaning": "දුම්බුටු, කුඹුරු වැල", "category": "plant" },
    { "word": "භීෂණී", "meaning": "තුන්දුරුක්කන්", "category": "plant" },
    { "word": "භීෂවිප්‍රියා(2)", "meaning": "අරළු", "category": "plant" },
    { "word": "භීමසේන", "meaning": "කපුරු විශේෂයක්", "category": "mineral" },
    { "word": "භුකතා", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "භුජ්ජ", "meaning": "රූක්බුරාද, ගදකිහිරි", "category": "plant" },
    { "word": "භුප්", "meaning": "කරගස, අත", "category": "anatomy" },
    { "word": "භුපංග", "meaning": "කළුඊයම්", "category": "mineral" },
    { "word": "භුපංග(2)", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "භුපඬගක", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "භුපඬගම", "meaning": "අරත්ත, කළුවා, ඊයම්", "category": "mineral" },
    { "word": "භුපඬගලතා", "meaning": "බුලත් වැල", "category": "plant" },
    { "word": "භුපඬගා", "meaning": "කරගස", "category": "plant" },
    { "word": "භුපඬගාක්‍ෂී", "meaning": "අරත්ත, කළුවාඅල", "category": "plant" },
    { "word": "භුපවභාගාබ්‍ය", "meaning": "නාමල් රේණු, කළුඊයම්", "category": "mineral" },
    { "word": "භුපවභාගාම්‍ය", "meaning": "නාමල් රේණු, කළුඊයම්", "category": "mineral" },
    { "word": "භුපපත්‍ර", "meaning": "කරගස, රුක්බුරාද, ඇසතු", "category": "plant" },
    { "word": "භුපපර්ණී", "meaning": "සස්සඳ, සර්ප විෂට සහ කාමි රෝගයට ප්‍රත්‍යක්‍ෂ බෙහෙතකි.", "category": "plant" },
    { "word": "භුපසමි", "meaning": "නාගස", "category": "plant" },
    { "word": "භුපෝගද", "meaning": "කරගස", "category": "plant" },
    { "word": "භුබාත්‍රී", "meaning": "පිටවක්කා, දුටුසතුටු", "category": "plant" },
    { "word": "භුරප්", "meaning": "කරගස,රුක්බුරාද, බුජ්ජපත්", "category": "plant" },
    { "word": "භුරප්පත්", "meaning": "බුරාද", "category": "plant" },
    { "word": "භුරප්සාර", "meaning": "කරගස, පුමිල", "category": "plant" },
    { "word": "භුවන", "meaning": "වතුර", "category": "liquid" },
    { "word": "භුවනක", "meaning": "රටකජු", "category": "plant" },
    { "word": "භුස්‍යාණ", "meaning": "බලතණ, අඳුතලා, රතු අක්මැල්ල, සනගස", "category": "plant" },
    { "word": "භුස්පොට", "meaning": "හතු (බිම්මල්)", "category": "plant" },
    { "word": "භුකදම්බක", "meaning": "මුඛමඟන, ක්‍රිමිගස්සා, බිමකොළොම්, බිම් බක්මී, අසමොදගම්", "category": "plant" },
    { "word": "භුකුමීඝාණඩී", "meaning": "මසන්", "category": "plant" },
    { "word": "භුකුෂ්මාණ්ඩී", "meaning": "බෙබර=(මසන්)කොමඩු(පුසුල්)", "category": "plant" },
    { "word": "භුකේශ", "meaning": "නුග ගස, සෙවෙල්", "category": "plant" },
    { "word": "භුබර්ජ්ජුරී", "meaning": "හින්ඉඳි", "category": "plant" },
    { "word": "භුධාත්‍රී", "meaning": "බිමනෙල්ලි", "category": "plant" },
    { "word": "භුපම්බු", "meaning": "තිරිඟු, රිඟුරැස්ස, බලුදම්", "category": "plant" },
    { "word": "භුතක්‍ෂී", "meaning": "නිකගස්", "category": "plant" },
    { "word": "භුතක", "meaning": "තලාගස", "category": "plant" },
    { "word": "භුතකෙශ", "meaning": "සේපාලිකා, නිල්තිකා ගොලොමි, (තෘණ විශේෂයක්)", "category": "plant" },

    // --- පිටුව 343 ---
    { "word": "භූතකේශී", "meaning": "ලැවිය ගස, තලාගස යක්බේරිය, ජටාමාංශ, කළුතිකා, නෙළුම්තිකා, හන, ගොම වරටි", "category": "plant" },
    { "word": "භූතකෙශිකා", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "භූතකෙශ්‍යා", "meaning": "නිකගස", "category": "plant" },
    { "word": "භූතගන්ධිකා", "meaning": "දුම්මල, (තලාගස) සුරා", "category": "plant" },
    { "word": "භූතඝන", "meaning": "තලාගස, භූරපත්‍ර, සුදුදුහුදු", "category": "plant" },
    { "word": "භූතස්නී", "meaning": "තලාගස, වලඟසාල්", "category": "plant" },
    { "word": "භූතපටා", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "භූතපත්‍රී", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "භූතද්‍රාවින්", "meaning": "රත්කණේරු", "category": "plant" },
    { "word": "භූතද්‍රැම", "meaning": "ලෝලුගස", "category": "plant" },
    { "word": "භූතන්ත්‍රී", "meaning": "කළුතලා", "category": "plant" },
    { "word": "භූතනාස", "meaning": "යක්බේරිය, පෙරුංකායම්", "category": "plant" },
    { "word": "භූතනාසන", "meaning": "අබ, බදුල්ල, පිණ්ඩාහිඟු", "category": "plant" },
    { "word": "භූතපාදප", "meaning": "ලෝලුගස", "category": "plant" },
    { "word": "භූතප්‍රිය", "meaning": "තලාගස", "category": "plant" },
    { "word": "භූතපුෂ්ප", "meaning": "තොටිල", "category": "plant" },
    { "word": "භූතවෘක්‍ෂ", "meaning": "බුවගස", "category": "plant" },
    { "word": "භූතවෘක්‍ෂ(2)", "meaning": "බුවගස, තොටිල ගස", "category": "plant" },
    { "word": "භූතවේසායා", "meaning": "කළුතිකා", "category": "plant" },
    { "word": "භූතසාර", "meaning": "තොටිල", "category": "plant" },
    { "word": "භූතහනන්ති", "meaning": "මල්තුඹ, එල්රතණ, වදකහ, කුසතණ", "category": "plant" },
    { "word": "භූතහාර", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "භූතහාරින්", "meaning": "දේවදාර", "category": "plant" },
    { "word": "භූතපහා", "meaning": "කර ගස", "category": "plant" },
    { "word": "භූතාරි", "meaning": "පෙරුංකායම්", "category": "plant" },
    { "word": "භූතාවාස", "meaning": "බුවගස, උක්ගස", "category": "plant" },
    { "word": "භූතාවෙශී", "meaning": "නික, හෙළ සේපාලිකා, ජටාමාංශ, රුකඟුණ", "category": "plant" },
    { "word": "භූතිකා", "meaning": "තොටිල, බිමිකොසඹ, අසමෝද, කපුරු, යක්බේරිය, සුවඳතෘණ", "category": "plant" },
    { "word": "භූතිකදම්බක", "meaning": "මහමුඛමඟන", "category": "plant" },
    { "word": "භූතිකා(2)", "meaning": "සුදු පාසානම්", "category": "mineral" },
    { "word": "භූතිඵල", "meaning": "බෝගස", "category": "plant" },
    { "word": "භූතිවෘක්‍ෂ", "meaning": "මහමුඛමඟන", "category": "plant" },
    { "word": "භූතී", "meaning": "මහඩබකලත්, සෑඇති නම් ඖෂධය", "category": "plant" },
    { "word": "භූතෘණක", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "භූතෙසක්‍ෂු", "meaning": "උක්ගස, වැලුක්", "category": "plant" },
    { "word": "භූධාත්‍රී", "meaning": "පිටවක්කා", "category": "plant" },
    { "word": "භූනිම්බ", "meaning": "බිමිකොසඹ", "category": "plant" },
    { "word": "භූනිප", "meaning": "මුඛමඟන", "category": "plant" },
    { "word": "භූපතී", "meaning": "ඉද්ද වැල", "category": "plant" },
    { "word": "භූපද", "meaning": "ඉද්ද වැල", "category": "plant" },
    { "word": "භූපාදි", "meaning": "ඉද්ද, සිනිද්ද", "category": "plant" },
    { "word": "භූපීලු", "meaning": "බිම්මෝරගස", "category": "plant" },
    { "word": "භූබදරි", "meaning": "හින්බෙබර", "category": "plant" },
    { "word": "භූමණ්ඩලච්ඡද", "meaning": "මහ සාරණ", "category": "plant" },
    { "word": "භූමණ්ඩලී", "meaning": "උණගස", "category": "plant" },
    { "word": "භූමිකදම්බ", "meaning": "මුඛමඟන", "category": "plant" },
    { "word": "භූමිකදම්බක", "meaning": "සතු", "category": "plant" },
    { "word": "භූමික්‍ෂමාණ්ඩ", "meaning": "එළ කිරිබදු", "category": "plant" },
    { "word": "භූමිචුක්කිලංගු", "meaning": "කිරිබදු අල", "category": "plant" },
    { "word": "භූමිබර්ජ්ජුරිකා", "meaning": "ඉඳි", "category": "plant" },
    { "word": "භූමිචම්පක", "meaning": "සවිකෙන්ද, යවකෙන්ද, (බිංසපු)", "category": "plant" },
    { "word": "භූමිප්", "meaning": "උද්භිදලුණු, මුඛමඟන", "category": "plant" },
    { "word": "භූමිපම්බුකා", "meaning": "සින්නාරං, බව්දම්", "category": "plant" },
    { "word": "භූමිදරු", "meaning": "මකුණුවැන්න", "category": "plant" },
    { "word": "භූමිනාරංග", "meaning": "සින්නාරම්", "category": "plant" },
    { "word": "භූමිපිනාව", "meaning": "තල්ගස", "category": "plant" },
    { "word": "භූමිබලා", "meaning": "අස්බැවිල, මහබැවිල, සිම්බැවිල", "category": "plant" },
    { "word": "භූමිමණ්ඩපග්‍රහණ", "meaning": "යොගොගොඹු", "category": "plant" },
    { "word": "භූමිලග්නා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "භූමිලතා", "meaning": "බිමතඹුරුවැල,ගැඩඹුලා, (ගැටඹුලා)", "category": "plant" },
    { "word": "භූමිසහා", "meaning": "සල්ගස", "category": "plant" },
    { "word": "භූම්‍යාමලකී", "meaning": "පිටවක්කා", "category": "plant" },
    { "word": "භූම්‍යාවල්ලී", "meaning": "පිටවක්කා", "category": "plant" },

    // --- පිටුව 344 ---
    { "word": "භූරප්", "meaning": "බුරපත්‍ර", "category": "plant" },
    { "word": "භූරප්සාර", "meaning": "පුමිල", "category": "plant" },
    { "word": "භූරිණ්ඩී", "meaning": "දික්තිබිය, කිරිඳි", "category": "plant" },
    { "word": "භූරිදුග්ගඬා", "meaning": "ඇත්සැටිය", "category": "plant" },
    { "word": "භූරිපුෂ්පා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "භූරිඵලා", "meaning": "සුළුබැවිල", "category": "plant" },
    { "word": "භූරිපේණා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "භූරිමල්ලී", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "භූරිරස", "meaning": "උක්ගස", "category": "plant" },
    { "word": "භූරාණ්ඩී", "meaning": "දික්තිබිය, (ඇත්සොඬ=හස්තිගුණ්ඩී) කිරිඳිවැල", "category": "plant" },
    { "word": "භූරුහා", "meaning": "කටරොළු", "category": "plant" },
    { "word": "භූලග්නා", "meaning": "අබනගිරියා", "category": "plant" },
    { "word": "භූලතා", "meaning": "බුලත්වැල, බිම්ලිය, (බිම්පාලා)", "category": "plant" },
    { "word": "භූෂ්ණි", "meaning": "සිවංගුරු", "category": "plant" },
    { "word": "භූෂණ", "meaning": "හිරියල්, නිප්පිලි මුල්", "category": "mineral" },
    { "word": "භූෂණඵල", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "භූෂිත", "meaning": "රුකඟුණ", "category": "plant" },
    { "word": "භූෂිත්‍ර", "meaning": "බිමමාරා ගස", "category": "plant" },
    { "word": "භූෂණ(2)", "meaning": "තුත්තනාගම්", "category": "mineral" },
    { "word": "භෘංගාර", "meaning": "කරාබුනැටි, රත්රන්", "category": "mineral" },
    { "word": "භෘංග", "meaning": "කරාබුනැටි, කුරුඳු, බුළු, මීපැණි, මීනිරන්", "category": "plant" },
    { "word": "භෘංගජා", "meaning": "අගිල්, සඳුන්, සිරිතේක්කු, කිකිරිඳිය", "category": "plant" },
    { "word": "භෘංගපර්ණී", "meaning": "හින්එන්සාල්", "category": "plant" },
    { "word": "භෘංගප්‍රියංකර", "meaning": "බවදම් ගස, ජම්බු ගස, බක්මී", "category": "plant" },
    { "word": "භෘංගප්‍රියා", "meaning": "යොහොඹු, වැටකේ, බවදම්, ජම්බු", "category": "plant" },
    { "word": "භෘංගබන්ධු", "meaning": "කොඳ", "category": "plant" },
    { "word": "භෘංගරාජ", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භෘංගරාජී", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භෘංගරාජී(2)", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භෘංගරාජී(3)", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භෘංගවල්ලභ", "meaning": "කොළොම්, ජම්බු", "category": "plant" },
    { "word": "භෘංගානා", "meaning": "කරාබුනැටි", "category": "plant" },
    { "word": "භෘංගානා(2)", "meaning": "කරාබුනැටි", "category": "plant" },
    { "word": "භෘංගානාබ්‍ය", "meaning": "කරාබුනැටි, වසාවාසි", "category": "plant" },
    { "word": "භෘංගානාහව", "meaning": "බෝලිද්ද", "category": "plant" },
    { "word": "භෘංගාභිහත", "meaning": "අඹ", "category": "plant" },
    { "word": "භෘංගාරී", "meaning": "කිකිරිඳිය, රත්රන්, කරාබුනැටි", "category": "plant" },
    { "word": "භෘංගාහ්ව", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භෘංගිනී", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "භෘංගිනීවල", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "භෘංගිත්", "meaning": "ඇම්බරල්ල", "category": "plant" },
    { "word": "භෘබේගපටා", "meaning": "කෝමාරිකා, බවදම්, සිරිතේක්කු, හාත-කලාදුරු", "category": "plant" },
    { "word": "භෘත", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "භෘපතෘණ", "meaning": "බඳිනාල්", "category": "plant" },
    { "word": "භෙකපර්ණී", "meaning": "මණ්ඩූකපර්ණී, ගොටුකොළ", "category": "plant" },
    { "word": "භෙකරුප්", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භෙකී", "meaning": "ගොටුකොළ, මකුවැන්න", "category": "plant" },
    { "word": "භෙදන", "meaning": "බදුල්ල ගස, පොල්පලා", "category": "plant" },
    { "word": "භෙරකා", "meaning": "කටුපිල ගස", "category": "plant" },
    { "word": "භෙපප්", "meaning": "වියලි ඉඟුරු, (සිඳිඟුරු) බෙහෙත්", "category": "plant" },
    { "word": "භෙපප්(2)", "meaning": "වියලි ඉඟුරු, (සිඳිඟුරු) බෙහෙත්", "category": "plant" },
    { "word": "භෙරම", "meaning": "කවුපිලගස", "category": "plant" },
    { "word": "භෙෂජ්", "meaning": "සිඳිඟුරු, බෙහෙත්", "category": "plant" },
    { "word": "භෝගිගඬා", "meaning": "අරත්ත", "category": "plant" },
    { "word": "භෝගිවල්ලභ", "meaning": "සඳුන්", "category": "plant" },
    { "word": "භෝජ්න", "meaning": "බත්", "category": "food" },
    { "word": "භෞම", "meaning": "උද්භිදලුණු, පාංශුලුණු", "category": "mineral" }
];

