// data_153_161.js - පිටු 153 සිට 161 දක්වා සියලුම වචන
const data_extra_153_161 = [
  // --- පිටුව 153 ---
  { "word": "බරයෂ්ටිකා", "meaning": "සුලුබැවිල", "category": "plant" },
  { "word": "බරලොහ", "meaning": "පින්තල", "category": "treatment" },
  { "word": "බරලොහක", "meaning": "පින්තල", "category": "treatment" },
  { "word": "බරවල්ලරිකා", "meaning": "සිරිවැඩි බැවිල", "category": "plant" },
  { "word": "බරවල්ලිකා", "meaning": "බුලත්, සිරිවැඩි බැවිල", "category": "plant" },
  { "word": "බරගාබා", "meaning": "සිරිතේක්කු, අසමෝද", "category": "plant" },
  { "word": "බරගුක", "meaning": "පියල් ගස", "category": "plant" },
  { "word": "බරගුාවා", "meaning": "වල්ඉද්ද ගස", "category": "plant" },
  { "word": "බරසකන්ධ", "meaning": "හිඳි ගස්, මාරා, මුද්රිය, යක්බේරිය, දේවදාලිය, මඟල් ගස, කිරිපලු, කොටදිඹුලා", "category": "plant" },
  { "word": "බරසකන්ධ", "meaning": "ඉඳිගස", "category": "plant" },
  { "word": "බරසවරා", "meaning": "වල් ඉද්ද", "category": "plant" },
  { "word": "බරසා", "meaning": "අසමෝද, මහ අසමෝද, සිරිතේක්කු", "category": "plant" },
  { "word": "බරා", "meaning": "කොටදිඹුලා, දේවදාලිය, යක්බේරිය", "category": "plant" },
  { "word": "බරාහූ", "meaning": "වරාගස", "category": "plant" },
  { "word": "බරාබා", "meaning": "මොණරකුඩුම්බිය, අසමෝද", "category": "plant" },
  { "word": "බරාහ්වා", "meaning": "කළුදුරු, අසමෝද, දූටු සතුරැ, මොණර කුඩුම්බිය", "category": "plant" },
  { "word": "බරොළු", "meaning": "ඉළුක් තණ", "category": "plant" },
  { "word": "බල්ල", "meaning": "බෙහෙත් මඩින භාජනය", "category": "treatment" },
  { "word": "බල්ලකී", "meaning": "සකුරු", "category": "treatment" },
  { "word": "බල්ලි", "meaning": "හොරගස", "category": "plant" },
  { "word": "බල්ව", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "බලවට", "meaning": "කාෂ රෝගය", "category": "symptom" },
  { "word": "බල", "meaning": "අත්තන, අසමෝද", "category": "plant" },
  { "word": "බලක", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "බලකුල", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "බලමූර්ති", "meaning": "රසදිය", "category": "treatment" },
  { "word": "බලි", "meaning": "බුළුගස, තලප, බිමිතල්", "category": "plant" },
  { "word": "බලිකා", "meaning": "මිරිස්", "category": "plant" },
  { "word": "බලීදම", "meaning": "හොරගස", "category": "plant" },
  { "word": "බලීනි", "meaning": "බිමිතල්, උවරල", "category": "plant" },
  { "word": "බලීවර්‍ධන", "meaning": "දන්ත රෝගයක්", "category": "symptom" },
  { "word": "බවාෂ්ප", "meaning": "පිණි, වතුර", "category": "treatment" },
  { "word": "බස්බක", "meaning": "අබින්", "category": "treatment" },
  { "word": "බස්බක්ෂීර", "meaning": "අබින්", "category": "treatment" },
  { "word": "බස්බසරස", "meaning": "අබින්", "category": "treatment" },
  { "word": "බස", "meaning": "සුවඳහොට, අබින් ගස", "category": "plant" },
  { "word": "බසකන්ධ", "meaning": "සිරිෂ වාක්‍යය (මඟරි ගස)", "category": "plant" },
  { "word": "බසනිලි", "meaning": "අබින් ගස", "category": "plant" },
  { "word": "බසපිජ්", "meaning": "අබින් ගස", "category": "plant" },
  { "word": "බසබස", "meaning": "අබින් ගස", "category": "plant" },
  { "word": "බසපෙණක්ෂීර", "meaning": "අබින්", "category": "treatment" },
  { "word": "බසමිභවා", "meaning": "සූක්‍ෂම ජටාමාංශ", "category": "plant" },
  { "word": "බාබස(නිල)", "meaning": "අබින් ගස", "category": "plant" },
  { "word": "බාබසනිලෝත්භූත", "meaning": "අබින් ගස", "category": "plant" },
  { "word": "බාණ්ඩව", "meaning": "යොන් ඉඳි", "category": "plant" },
  { "word": "බාදිර", "meaning": "කයිප්පු, ගුරැන්ද", "category": "treatment" },
  { "word": "බාදිරසාර", "meaning": "කිහිරි ගස", "category": "plant" },
  { "word": "බාද්‍රපත්‍රී", "meaning": "කිහිරි ගස", "category": "plant" },
  { "word": "බානක", "meaning": "සාරණ", "category": "plant" },
  { "word": "බානෝදක", "meaning": "පොල්", "category": "plant" },
  { "word": "බාෂිකා", "meaning": "පිළුද", "category": "treatment" },
  { "word": "බාරක", "meaning": "ඉඳුසල්", "category": "plant" },
  { "word": "බාරද්වාජ", "meaning": "මුක්කරා", "category": "plant" },
  { "word": "බාරිකා", "meaning": "මඟ පේර ගස", "category": "plant" },
  { "word": "බාලිත්‍ර්", "meaning": "කපාල රෝගය", "category": "symptom" },
  { "word": "බීර", "meaning": "කිරි", "category": "treatment" },
  { "word": "බිරනිවිට්ටි", "meaning": "මහ බැවිල", "category": "plant" },
  { "word": "බිරිකා", "meaning": "කිරිපලු", "category": "plant" },
  { "word": "බිලාස", "meaning": "කිලාස (කුෂ්ඨ රෝගයක්)", "category": "symptom" },
  { "word": "බුප්පක", "meaning": "දේවදාලිය වැල්", "category": "plant" },
  { "word": "බුබ", "meaning": "වාත රක්ත රෝගය", "category": "symptom" },
  { "word": "බුදු", "meaning": "මීපැණි", "category": "treatment" },
  { "word": "බුර", "meaning": "සක්නබ", "category": "treatment" },
  { "word": "බුරක", "meaning": "මුද්රිය වාක්‍යය, ඉකිරිගස", "category": "plant" },

  // --- පිටුව 154 ---
  { "word": "බුරසාතා", "meaning": "කොරාසානි", "category": "plant" },
  { "word": "බුරා", "meaning": "කටුරොලු", "category": "plant" },
  { "word": "බුරාසනිවා", "meaning": "වදකහ", "category": "plant" },
  { "word": "බුරාහ්වා", "meaning": "අසමෝද", "category": "plant" },
  { "word": "බුරී", "meaning": "එල කටුරොලු", "category": "plant" },
  { "word": "බුරී", "meaning": "සිවිය", "category": "plant" },
  { "word": "බෙවර", "meaning": "කසීස්", "category": "treatment" },
  { "word": "බෙවරාඤ්ජන", "meaning": "කසීස්", "category": "treatment" },
  { "word": "බෙදිනී", "meaning": "අස්වැන්න", "category": "plant" },
  { "word": "බෙල", "meaning": "කෙල", "category": "treatment" },
  { "word": "බෙබක", "meaning": "(ශීර්ෂක) නිඹුල්", "category": "plant" },
  { "word": "ගඟා", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "ගඟාපත්‍රී", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "ගංගා", "meaning": "කංසා (තිලෝක විජ්ජ)", "category": "plant" },
  { "word": "ගංගන", "meaning": "ඉඳුසල්", "category": "plant" },
  { "word": "ගන්ටාද්‍රැ", "meaning": "අබ", "category": "plant" },
  { "word": "ගන්තලා", "meaning": "තලා වර්ගයක්", "category": "plant" },
  { "word": "ගඟද්‍රැ", "meaning": "බා දුම්මල", "category": "treatment" },
  { "word": "ගහන", "meaning": "මිණීරන්", "category": "treatment" },
  { "word": "ගගනසිම්බා", "meaning": "සින්තඹල", "category": "plant" },
  { "word": "ගගරී", "meaning": "කිරි කැලුකන පාත්‍ර (භාජනය)", "category": "treatment" },
  { "word": "ගඩගල", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ගඩ්ගඩ", "meaning": "මිගුටි", "category": "treatment" },
  { "word": "ගඩ්ගද", "meaning": "පුස්කර", "category": "treatment" },
  { "word": "ගබේභය", "meaning": "එම්මුතු", "category": "plant" },
  { "word": "ගවේගරී", "meaning": "ඇඹුල්ඇඹිලිය", "category": "plant" },
  { "word": "ගඩේභරකී", "meaning": "ඇත්බැවිල, මඟබැවිල, ගස්කැලිය", "category": "plant" },
  { "word": "ගඩධාරී", "meaning": "දුරාලභා", "category": "plant" },
  { "word": "ගජ", "meaning": "නාමල්රේණු, ඇත්තෝර, ගජතිප්පිලි", "category": "plant" },
  { "word": "ගජායන", "meaning": "බෝගස්", "category": "plant" },
  { "word": "ගජකණ", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "ගජකන්ධ", "meaning": "හබරල ගස", "category": "plant" },
  { "word": "ගජකන්ධි", "meaning": "හබරල ගස, මීකන්පලා", "category": "plant" },
  { "word": "ගජකර්ණීකා", "meaning": "මහගොත් කැකිරි", "category": "plant" },
  { "word": "ගජකුමුඹූ", "meaning": "දෙහි", "category": "plant" },
  { "word": "ගජකුසුම", "meaning": "නාගස්", "category": "plant" },
  { "word": "ගජකාර්ෂණ", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "ගජකේගර", "meaning": "නාකෙසරා", "category": "plant" },
  { "word": "ගජකේගර සූණු", "meaning": "අතීසාර නාශක චූර්ණයක්", "category": "treatment" },
  { "word": "ගජතිප්පිලි", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "ගජතෙක්කන්", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "ගජදන්තවපාලා", "meaning": "කැකිරි", "category": "plant" },
  { "word": "ගජදම", "meaning": "නන්දි රුක", "category": "plant" },
  { "word": "ගජපර්කා", "meaning": "ඔලිඳ ඇට", "category": "plant" },
  { "word": "ගජපාදප", "meaning": "අත්තික්කා, පලොල්ගස", "category": "plant" },
  { "word": "ගජපිප්පලී", "meaning": "ගජතිප්පිලි, සිවිය", "category": "plant" },
  { "word": "ගජපුෂ්පී", "meaning": "නාගපුෂ්ප නම් ලතා වෙසෙස", "category": "plant" },
  { "word": "ගජප්‍රියා", "meaning": "කුකුරුමුවන්, කිරිබදු, ඉන්සලු", "category": "plant" },
  { "word": "ගජබලා", "meaning": "සිරිවැඩිබැවිල", "category": "plant" },
  { "word": "ගජභක්‍ෂ", "meaning": "ඉන්සලු, ඇසතු ගස", "category": "plant" },
  { "word": "ගජභක්‍ෂිකා", "meaning": "බෝගස, කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "ගජභක්ෂ්‍යා", "meaning": "ඉන්සලු, කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "ගජවල්ලභා", "meaning": "කුකුරුමුවන්, වල් කෙසෙල්, ඉන්සලු ගස", "category": "plant" },
  { "word": "ගජවාර්ප්‍රියා", "meaning": "කිරිබදු", "category": "plant" },
  { "word": "ගජපිබ්බ", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "ගජවිරාමාරී", "meaning": "නියඟරා, මඟගොන් සුතුකැකිරි", "category": "plant" },
  { "word": "ගජාව්හ", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "ගජාදන", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "ගජාදිනාමා", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "ගජාසන", "meaning": "ඇසතු, කුකුරුමුවන්, බෝගස, පුමිල", "category": "plant" },
  { "word": "ගජාහ්ව", "meaning": "නාගස", "category": "plant" },
  { "word": "ගජාන්වයා", "meaning": "බෝලිද්ද, ඇත්වගපුල්", "category": "plant" },

  // --- පිටුව 155 ---
  { "word": "ගජේෂ්ටා", "meaning": "කෝවක්කා, කැකිරි, කිරිබදු", "category": "plant" },
  { "word": "ගජ්ජන්ද ගත්තේ", "meaning": "ගොබල අල (රහස්වට්ටෝරුවක ඔසුවක්)", "category": "plant" },
  { "word": "ගජෝ", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "ගජොසකුලභා", "meaning": "ඇත්වගපුල්, සිවිය", "category": "plant" },
  { "word": "ගජොපම", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "ගජෝවනනක", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "ගජ්ජාසිකා", "meaning": "කන්සා", "category": "plant" },
  { "word": "ගඩ", "meaning": "කපොලය", "category": "treatment" },
  { "word": "ගඩපුරාක්", "meaning": "ලේ, (ගඩ) ගෙඩි පැසවීමට ගාන පුරාක් සහිත සෙවෙල් ගතිය ඇති වැල් වගියක්", "category": "plant" },
  { "word": "ගඩවුලුකොල", "meaning": "හෙලන්දිරිය කොළ, ගවාදෙහි (කුඬලුදෙහි)", "category": "plant" },
  { "word": "ගණවණ්ටි", "meaning": "ප්‍රිවේර, නාමල් රේණු", "category": "plant" },
  { "word": "ගණකභාරී", "meaning": "බිමිතල්, උවරල, නිදිකුම්බා", "category": "plant" },
  { "word": "ගණක්කාලි", "meaning": "නිදිකුම්බා වැල්", "category": "plant" },
  { "word": "ගණඩගාත්‍රා", "meaning": "ආන්තකා (අනෝදා)", "category": "plant" },
  { "word": "ගණඩපිණ්ඩිතක", "meaning": "කවුකරඹු", "category": "plant" },
  { "word": "ගණඩමාලී", "meaning": "නිදිකුම්බා ගස", "category": "plant" },
  { "word": "ගණඩමාලිකා", "meaning": "නිදිකුම්බා වැල්", "category": "plant" },
  { "word": "ගණඩාක්ෂ", "meaning": "රෝමලුණු, රීදීහුන්තම්, හෙලබටු", "category": "treatment" },
  { "word": "ගණඩාබ්‍යා", "meaning": "රෝමලුණු", "category": "treatment" },
  { "word": "ගණඩාරි", "meaning": "කොබෝලිල", "category": "plant" },
  { "word": "ගණඩාලී", "meaning": "කපොල රෝගයක්", "category": "symptom" },
  { "word": "ගණඩාලි", "meaning": "වම්මුතු, කුසතණ, ඊතණ, වැල්මදට", "category": "plant" },
  { "word": "ගණ්ඩීර", "meaning": "සිවිය, පහුක්, පලොල්, කරවිල, මඟ උක්, වැල්පල, (වැල් අල) කිඩාරම්", "category": "plant" },
  { "word": "ගණ්ඩීරකන්‍ද", "meaning": "වල්ලි අල (වැල් අල)", "category": "plant" },
  { "word": "ගණ්ඩිරිකා", "meaning": "සිවිය, වැල්මදට, දළක් ගස", "category": "plant" },
  { "word": "ගණ්ඩූක", "meaning": "සිවිය", "category": "plant" },
  { "word": "ගණ", "meaning": "කලාඳුරු, දියමිදෙල්ල, අසමෝද", "category": "plant" },
  { "word": "ගණපුක්", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ගණපුෂ්පක", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ගණපුෂ්පිකා", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ගණිප්‍රභා", "meaning": "මීගස, බෝලාපලා", "category": "plant" },
  { "word": "ගණස", "meaning": "සැවන්ඳරා, (සුවඳහොට)", "category": "plant" },
  { "word": "ගණරූප", "meaning": "වරා", "category": "plant" },
  { "word": "ගණරුපිකා", "meaning": "හෙලවරා, දළක්, වැල් තිබිබොටු", "category": "plant" },
  { "word": "ගණරූපිත්", "meaning": "එලවරා", "category": "plant" },
  { "word": "ගණනායක", "meaning": "අරණක්කසා, හෙලවරා", "category": "plant" },
  { "word": "ගණී", "meaning": "සපුගස", "category": "plant" },
  { "word": "ගණිකා", "meaning": "මඟකපු, කසාවත් බෝලිද්ද, රන්වන් බෝලිද්ද", "category": "plant" },
  { "word": "ගණිකාරිකා", "meaning": "සිහින් මිදි, කිණිහිරි", "category": "plant" },
  { "word": "ගණේරුකා", "meaning": "මිදි ගස", "category": "plant" },
  { "word": "ගණෝරුකා", "meaning": "කිණිහිරි, එරබදු ගස", "category": "plant" },
  { "word": "ගණෙගකුසුම", "meaning": "රත්කණේරු ගස", "category": "plant" },
  { "word": "ගණෙගප්‍රිය", "meaning": "රත්කණේරු ගස", "category": "plant" },
  { "word": "ගණේරු", "meaning": "කිණිහිරි, එරබදු", "category": "plant" },
  { "word": "ගත", "meaning": "(සත) ගිතෙල්", "category": "treatment" },
  { "word": "ගතගෙවිකා", "meaning": "හෝපලු", "category": "plant" },
  { "word": "ගනිකාරි", "meaning": "කපුගස", "category": "plant" },
  { "word": "ගඥගණබ", "meaning": "හෙලසැබෝ", "category": "plant" },
  { "word": "ගද", "meaning": "සුවඳ කොට්ටම්", "category": "plant" },
  { "word": "ගදසන", "meaning": "නන්දි රුක", "category": "plant" },
  { "word": "ගදඛ", "meaning": "එරබදු", "category": "plant" },
  { "word": "ගදබද්ධත්", "meaning": "එරබදු", "category": "plant" },
  { "word": "ගද", "meaning": "පුලිල, පලොල්", "category": "plant" },
  { "word": "ගදබ්යක", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "ගද්ගුනී", "meaning": "ක්‍ෂය රෝගය", "category": "symptom" },
  { "word": "ගදර්ථිකා", "meaning": "ගොඩිච්චි (ඇත්අබි)", "category": "plant" },
  { "word": "ගදන්වය", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "ගදුභා", "meaning": "වංඇපල", "category": "plant" },
  { "word": "ගදුගිගස", "meaning": "කලාඳුරු", "category": "plant" },

  // --- පිටුව 156 (image_87e0fa.jpg) ---
  { "word": "ගද", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගදසාර", "meaning": "සඳුන්", "category": "plant" },
  { "word": "ගන්‍ධ", "meaning": "තෙලඹු, ගෙන්දගම්", "category": "plant" },
  { "word": "ගන්‍දක", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්‍දූ", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධී", "meaning": "ගෙන්දගම්, අරත්ත, තෙලඹු, රතැණ, අගිල්, මුරංගා ගස", "category": "plant" },
  { "word": "ගන්ධික", "meaning": "ගෙන්දගම්, මුරංගා", "category": "plant" },
  { "word": "ගන්ධකනක", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "ගන්ධකපාෂාණ", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධකස්තුුරිකා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "ගන්ධකාරී", "meaning": "එල නිදිකුම්බා වැල්, ඉඳුසල්", "category": "plant" },
  { "word": "ගන්ධකාලි", "meaning": "නිදිකුම්බා, පුවඟු ගස", "category": "plant" },
  { "word": "ගන්ධකාෂ්ට", "meaning": "සඳුන්, අගිල්", "category": "plant" },
  { "word": "ගන්ධගි", "meaning": "ඉඳුසල් ගස", "category": "plant" },
  { "word": "ගන්ධකුරී", "meaning": "තලිස්පත්තුරු", "category": "plant" },
  { "word": "ගන්ධකුසුමා", "meaning": "කිණිහිරි, සිහින් මිදි", "category": "plant" },
  { "word": "ගන්ධකෙලිකා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "ගන්ධකොපල", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධගර්භ", "meaning": "බෙලි ගස", "category": "plant" },
  { "word": "ගන්ධගාත්‍ර", "meaning": "අනෝදා", "category": "plant" },
  { "word": "ගන්ධචෙලිකා", "meaning": "කස්තුරි, තකුල්, උරලෑසීපීටි", "category": "treatment" },
  { "word": "ගන්ධජටිලා", "meaning": "වදකහ", "category": "plant" },
  { "word": "ගන්ධජාත", "meaning": "කොල්ලන් කොළ", "category": "plant" },
  { "word": "ගන්ධඩව්", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ගන්ධතුලසී", "meaning": "සුවඳ තලා", "category": "plant" },
  { "word": "ගන්ධතෘණ", "meaning": "සැවැන්දරා (සුවඳහොට) සේර", "category": "plant" },
  { "word": "ගන්ධදලා", "meaning": "අසමෝද", "category": "plant" },
  { "word": "ගන්ධදූර්වා", "meaning": "සඳුන්", "category": "plant" },
  { "word": "ගන්ධද්‍රව්‍ය", "meaning": "නා කේසරා", "category": "plant" },
  { "word": "ගන්ධධුම්ජ", "meaning": "කළු අගිල්", "category": "plant" },
  { "word": "ගන්ධධූලි", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "ගන්ධනාකුලී", "meaning": "අරත්ත, සිවිය, ඒකාවේරිය", "category": "plant" },
  { "word": "ගන්ධනාමන්", "meaning": "රතුමල් තලා", "category": "plant" },
  { "word": "ගන්ධනිර්යාස", "meaning": "වවවමාවි, ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධනිලයා", "meaning": "සිනිද්ද", "category": "plant" },
  {
    "word": "ගන්ධිභා",
    "scientific": "Kaempferia Galanga",
    "meaning": "හිඟුරුපියලි (සුවඳ කොළ ඇති හිඟුරුපියලි). කුඩා කහ කොළවලට සමාන කොළ ඇති පොළොවට ම ඇලී වැවෙන කුඩා පඳුරු වගියකි හිඟුරුපියලි. වාලි සහිත ඉඩම්වල මැනවින් වැවෙන මේ වර්‍ගයේ කුඩා අල පොකුරු සෑදී තිබේ. එකට බැඳී තිබෙන මේ පඳුරුවල එක පැලයකට එක අලය බැගින් අල පොකුර ද එකට බැඳී ඇත. අල පමණක් සුවඳ ඇති වර්‍ගයක් සහ අල මෙන් ම කොළ ද සුවඳ ඇති වර්‍ගයකි හිඟුරුපියලි.",
    "category": "plant"
  },

  // --- පිටුව 157 (image_87e0fd.jpg) ---
  { "word": "ගන්ධපත්‍ර", "meaning": "කරපිංචා, බෙලි, ඉන්සලු, අසමෝද, සිහින් මිදි, ලප්නාරං, තලා", "category": "plant" },
  { "word": "ගන්ධපත්‍රා", "meaning": "සිහින් මිදි", "category": "plant" },
  { "word": "ගන්ධපර්ණිකා", "meaning": "අඳුනතලා, අසමෝද", "category": "plant" },
  { "word": "ගන්ධපර්ණී", "meaning": "රක්ත චන්දන, දිය මින්ත", "category": "plant" },
  { "word": "ගන්ධපති", "meaning": "සිරිතේක්කු", "category": "plant" },
  { "word": "ගන්ධපල්ලවා", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධපාලා", "meaning": "පුවඟු, උවන්සාල, ඉඳුසල්", "category": "plant" },
  { "word": "ගන්ධපාලාගජා", "meaning": "උණ්කපුරු වෙසෙසක්", "category": "plant" },
  { "word": "ගන්ධපාලාලු", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධපාලි", "meaning": "රක්කගුණ, පුවඟු, සපුකැකුළු", "category": "plant" },
  { "word": "ගන්ධපාෂාණමි", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධපිණ්ඩිතක", "meaning": "කවුකරඹු", "category": "plant" },
  { "word": "ගන්ධපිබිබිර", "meaning": "කලු කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "ගන්ධපුෂ්ප", "meaning": "පුවඟු, රක්කගුණ, හෝපලු", "category": "plant" },
  { "word": "ගන්ධපුෂ්පා", "meaning": "සිහින් මිදි, අවිරිය, වැටකේ", "category": "plant" },
  { "word": "ගන්ධපුනිකා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ගන්ධප්‍රියභගු", "meaning": "සුවඳ පුවඟු", "category": "plant" },
  { "word": "ගන්ධපණීච්ඡිකා", "meaning": "රතු තලා ගස", "category": "plant" },
  { "word": "ගන්ධපල", "meaning": "කරපිංචා, දිවුල්, සපුකැකුළු, සිහින් නාරං", "category": "plant" },
  { "word": "ගන්ධඵලිකා", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ගන්ධඵලී", "meaning": "පුවඟු, සපුමල් කැකුළු", "category": "plant" },
  { "word": "ගන්ධබටු", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධබන්ධු", "meaning": "අඹ ගස", "category": "plant" },
  { "word": "ගන්ධබහල", "meaning": "තෙල අඳු ගස", "category": "plant" },
  { "word": "ගන්ධබිජා", "meaning": "උවන්සාල", "category": "plant" },
  { "word": "ගන්ධභද්‍රා", "meaning": "ආපස්සුමුදු වැල්", "category": "plant" },
  { "word": "ගන්ධභාණ්ඩ", "meaning": "තෙලසවු ගස, ඇඹරැල්ලා", "category": "plant" },
  { "word": "ගන්ධමාංශී", "meaning": "ජටාංශ", "category": "plant" },
  { "word": "ගන්ධමාදන", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධමාර්ජාරවීර්යී", "meaning": "උරලෑසීපීටි", "category": "treatment" },
  { "word": "ගන්ධමාලා", "meaning": "ලුණුවිල", "category": "plant" },
  { "word": "ගන්ධමුඛණ්ඩ", "meaning": "තුන්පුලිල (තෙලසවු ගස)", "category": "plant" },
  { "word": "ගන්ධමූල", "meaning": "සිහින් මිදි, හිඟුරුපියලි, ඉරිවේරිය", "category": "plant" },
  { "word": "ගන්ධමූලක", "meaning": "සිහින් මිදි, හිඟුරුපියලි, ඉරිවේරිය", "category": "plant" },
  { "word": "ගන්ධමූලා", "meaning": "සිහින් මිදි, ලුණුවිල, පුස්වැන්න, ඉරමුසු, ඉන්සලු, හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධමුලී", "meaning": "ලුණුවිල (බැමිනිරිය), හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධමූලිකා", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධමෘගනී", "meaning": "අරණක්කසා, (හරන්කහ)", "category": "plant" },
  { "word": "ගන්ධමෘගපුෂ්ප", "meaning": "කොලොම් ගස", "category": "plant" },
  { "word": "ගන්ධමොදන", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධය", "meaning": "අහිරුබධයන්", "category": "treatment" },
  { "word": "ගන්ධයි", "meaning": "සඳුන්", "category": "plant" },
  { "word": "ගන්ධම්", "meaning": "හෙල කණේරු, කොබුගල්, රැතැණ, සුවඳ රැතැණ, හෙල එඬරු", "category": "plant" },
  { "word": "ගන්ධමෘග", "meaning": "අස්ගොදු (අමුක්කරා)", "category": "plant" },
  { "word": "ගන්ධර්භභා", "meaning": "සිරිතේක්කු", "category": "plant" },

  // --- පිටුව 158 (image_87e103.jpg) ---
  { "word": "ගන්ධිෂභා", "meaning": "එඬරු, හෙල එඬරු", "category": "plant" },
  { "word": "ගන්ධිගගක", "meaning": "එරබදු, හෙලඑරබදු", "category": "plant" },
  { "word": "ගන්ධරස", "meaning": "වවවමාවි, ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධරසභාගක", "meaning": "සිරිතේක්කු", "category": "plant" },
  { "word": "ගන්ධරාප්", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "ගන්ධරාජ", "meaning": "සුදු හඳුන්, රත් ගුගුල්, උරලෑසීපීටි", "category": "treatment" },
  { "word": "ගන්ධරැහා", "meaning": "වල්ඉද්ද", "category": "plant" },
  { "word": "ගන්ධලතා", "meaning": "පුවඟු", "category": "plant" },
  { "word": "ගන්ධලොග", "meaning": "පිත්තල", "category": "treatment" },
  { "word": "ගන්ධවත් පුෂ්ප", "meaning": "බක්මී", "category": "plant" },
  { "word": "ගන්ධවති", "meaning": "සුරා, තලිස්පත්තුරු, වල් අසමෝදගම්", "category": "treatment" },
  { "word": "ගන්ධවංශ", "meaning": "මහබැවිල", "category": "plant" },
  { "word": "ගන්ධවර", "meaning": "කපුරු", "category": "plant" },
  { "word": "ගන්ධවල්කල", "meaning": "කුරඳු පොතු", "category": "plant" },
  { "word": "ගන්ධවල්ලරී", "meaning": "කුඹුරු වැල, මඟුල්කුඹුරු වැන්න, මහබැවිල", "category": "plant" },
  { "word": "ගන්ධවල්ලී", "meaning": "කහපාට ගොඩ මානෙල්", "category": "plant" },
  { "word": "ගන්ධවල්ලිකා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "ගන්ධවාර", "meaning": "කපුරු, අමුක්කරා", "category": "plant" },
  { "word": "ගන්ධවාහිනි", "meaning": "මුත්‍ර මාංශී", "category": "treatment" },
  { "word": "ගන්ධවිලාසිනී", "meaning": "පබළු", "category": "treatment" },
  { "word": "ගන්ධවිනිලා", "meaning": "කිරිනු", "category": "plant" },
  { "word": "ගන්ධවිප", "meaning": "කුලස්පන වාක්‍යය (ගන්ධමූල)", "category": "treatment" },
  { "word": "ගන්ධවිෂ", "meaning": "උවනාල්", "category": "plant" },
  { "word": "ගන්ධවීර", "meaning": "කෙසෙල් ගස, ඉඳුසල්", "category": "plant" },
  { "word": "ගන්ධවෙදිකා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "ගන්ධවෙලිකා", "meaning": "උරලෑ පීටි", "category": "treatment" },
  { "word": "ගන්ධවෙපට", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "ගන්ධව්‍යාඝ්‍ර", "meaning": "පුවඟු, රැකුණ, (ගස්අගුණ) සිහින් මිදි, සල්, කරපිංචා යන ගස් වගී", "category": "plant" },
  { "word": "ගන්ධව්‍යාකුලී", "meaning": "තකුල්", "category": "plant" },
  { "word": "ගන්ධහටී", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධහේබර", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "ගන්ධසාර", "meaning": "සුදු හඳුන්, ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධසාරක", "meaning": "සඳුන්", "category": "plant" },
  { "word": "ගන්ධසූචී", "meaning": "ඇඹරැල්ලා ගස", "category": "plant" },
  { "word": "ගන්ධසෝම", "meaning": "මානෙල්", "category": "plant" },
  { "word": "ගන්ධසෝමිකා", "meaning": "උපුල්, හෙල්මලි (සුදු බිලු)", "category": "plant" },
  { "word": "ගන්ධහාරිනී", "meaning": "තලා ගස", "category": "plant" },
  { "word": "ගන්‍ධා", "meaning": "ගෙන්දගම්, මදටිය, සපු මල්, හිඟුරුපියලි, අසමෝදගම්", "category": "plant" },
  { "word": "ගන්ධැබ්‍යා", "meaning": "සුරා", "category": "treatment" },
  { "word": "ගන්ධාගරු", "meaning": "සුවඳ අගිල්", "category": "plant" },
  { "word": "ගන්ධිස්ත", "meaning": "සඳුන් ගස, හින්තාරං, උරලෑසීපීටි", "category": "plant" },
  { "word": "ගන්ධාස්‍යා", "meaning": "රන්වන් බෝලිද්ද, කඩුකරෝෂණ", "category": "plant" },
  { "word": "ගන්ධිකා", "meaning": "මහ සාතාවාරිය", "category": "plant" },
  { "word": "ගන්ධිලා", "meaning": "වල් දෙඹ, ලප්නාරං", "category": "plant" },
  { "word": "ගන්ධාරි", "meaning": "අරත්ත, කලුවා ගස", "category": "plant" },
  { "word": "ගන්ධාර", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධාරි", "meaning": "කණේරු, අලරිය, කන්සා, කටුවෙලඟ, වසාවාසි, යවාසා, හිඟුරුපියලි", "category": "plant" },
  { "word": "ගන්ධාරිකා", "meaning": "හිඟුරුපියලි වෙසෙසක්", "category": "plant" },
  { "word": "ගන්ධාල ගර්භ", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ගන්ධාලි", "meaning": "ආපස්සුමුදු, වසාවාසි", "category": "plant" },
  { "word": "ගන්ධාලිගර්භ", "meaning": "මහ එන්සාල්", "category": "plant" },
  { "word": "ගන්ධාව", "meaning": "අස්ගොදු, හෙල පලොල්", "category": "plant" },
  { "word": "ගන්ධාවා", "meaning": "පලොල්, හෙල පලොල්", "category": "plant" },
  { "word": "ගන්ධොර්මින්", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්ධාවා", "meaning": "පුවඟු, රත් තලා", "category": "plant" },
  { "word": "ගන්ී", "meaning": "තාලි, කොකුම්", "category": "plant" },
  { "word": "ගන්තිකා", "meaning": "ඇපල, ගෙන්දගම්", "category": "plant" },
  { "word": "ගන්ත්‍රී", "meaning": "මුංවැන්න, අසමෝදගම්", "category": "plant" },
  { "word": "ගන්ද්ධී", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "ගන්තිත්", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්තිනු", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "ගන්තිති", "meaning": "දියබෙරලිය, කෙසෙල්, තලිස්පත්තුරු, ඉන්සලු", "category": "plant" },
  { "word": "ගන්ධිපත්‍ර", "meaning": "රක්ත චන්දන ගස", "category": "plant" },

  // --- පිටුව 159 (image_87e127.jpg) ---
  { "word": "ගන්ධිපර්ණ", "meaning": "රක්ත චන්දන", "category": "plant" },
  { "word": "ගන්ධිලා", "meaning": "වම්මුතු, (කලාඳුරු)", "category": "plant" },
  { "word": "ගන්ධිපණි", "meaning": "පලොල්", "category": "plant" },
  { "word": "ගන්ධිෂා", "meaning": "පලොල්", "category": "plant" },
  { "word": "ගබ්බුකුලු", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "ගහකො(ලි)", "meaning": "හිඟුරුපියලි, වම්මුතු (කලාඳුරු)", "category": "plant" },
  { "word": "ගහනොඝා", "meaning": "වදකහ", "category": "plant" },
  { "word": "ගහනොත්කට", "meaning": "සඳුන්, කුකුරුමුවන්", "category": "plant" },
  { "word": "ගහනොත්තම", "meaning": "සඳුන්, සුරා", "category": "treatment" },
  { "word": "ගහනොත්පලා", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගන්තසූරා", "meaning": "ගම්සූරිය ගස", "category": "plant" },
  { "word": "ගන්තගිබුප්පය", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "ගන්තහන්", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "ගණ", "meaning": "දියමිදෙල්ල, කලාඳුරු, (වම්මුතු)", "category": "plant" },
  { "word": "ගණපුක්", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ගණයසවද", "meaning": "සැවැන්දරා මුල්", "category": "plant" },
  { "word": "ගණරූපී", "meaning": "හෙල වරා", "category": "plant" },
  { "word": "ගණසවද", "meaning": "සැවැන්දරා", "category": "plant" },
  { "word": "ගණස්යා", "meaning": "කපුරු", "category": "plant" },
  { "word": "ගනී", "meaning": "සපු ගස", "category": "plant" },
  { "word": "ගහනොස", "meaning": "තලපත", "category": "plant" },
  { "word": "ගහස්ති", "meaning": "රත් නිවුල්, බදුල්ල", "category": "plant" },
  { "word": "ගහිකා", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "ගමිහාරි", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "ගමිභීර", "meaning": "ඇත්දෙමට, දෙඹ, ලප්නාරං", "category": "plant" },
  { "word": "ගමිභීරක", "meaning": "මරාවක වාක්‍යය", "category": "treatment" },
  { "word": "ගමිභීර ලවණ", "meaning": "රෝමලුණු, උදභිද ලුණු", "category": "treatment" },
  {
    "word": "ගම්මළු",
    "meaning": "ගම්මාලු (ගම්මළු) මොර හෝ පීතසාල ගස. දකුණු ඉන්දියාව ජන්ම භූමිය කොට ඇති මෙය අඩි 50 ක් 60 ක් පමණ උසට වැඩෙන විශාල ගසකි. වියළි කලාපයෙහි ඉක්මනින් වැවෙන මේ ගස් සෙවන සඳහා යුරෝපීයයන් විසින් ඉන්දියාවෙන් ලංකාවට ගෙනැවිත් වවන ලද්දක් යැයි සිතිය හැක. මේ ගසෙන් රතුපාට කිරි වර්‍ගයක් ලබා ගත හැක. ඒවා බෝතල් වල දමා සුරැකි ව තබා ගතහොත් නරක් නොවී බොහෝ කල් පවතී. තද තිත්ත ගතියකින් යුත් මේ කිරි උණ හා රුධිර පීඩනය ඇතුව මධුමේහාදී රෝගෝපශමණය පිණිසත් ලය විරේක පිණිසත් සුදුසු යයි ඇතැම් අයගේ මතයකි.",
    "category": "plant"
  },
  { "word": "ගමක", "meaning": "කරවිල", "category": "plant" },
  { "word": "ගමන්සුරා", "meaning": "ගම්සූරිය ගස", "category": "plant" },

  // --- පිටුව 160 (image_87e14c.jpg) ---
  { "word": "ගයිරිකා", "meaning": "සිවන්ගුරු", "category": "treatment" },
  { "word": "ගර්ජක", "meaning": "අගිල් ගස, ඇඹල ගස", "category": "plant" },
  { "word": "ගර්ජර", "meaning": "කෑරට්, රතු ලුහුණු", "category": "plant" },
  { "word": "ගර්ජාඵල", "meaning": "කටුකිහිරි ගස", "category": "plant" },
  { "word": "ගර්තකලමිබුකා", "meaning": "මුගුණුවැන්න", "category": "plant" },
  { "word": "ගර්ද", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ගර්දභ", "meaning": "හෙල මානෙල්, වලඟසාල්", "category": "plant" },
  { "word": "ගර්දභගන්‍ධිකා", "meaning": "දම්දෙවිසුදු (සිරිතේක්කු)", "category": "plant" },
  { "word": "ගර්දභසාකා", "meaning": "දම්දෙවිසුදු", "category": "plant" },
  { "word": "ගර්දනශාඛා", "meaning": "දම්දෙවිසුදු", "category": "plant" },
  { "word": "ගර්දහශාඛී", "meaning": "දම්දෙවිසුදු", "category": "plant" },
  { "word": "ගර්දභා", "meaning": "එල කටුවැල්බටු", "category": "plant" },
  { "word": "ගර්දභාජනිකා", "meaning": "බූතූඟ, දේවදාලිය, ගබ්බු, අබනගිරිය, තෙලසැටිස", "category": "plant" },
  { "word": "ගර්දභාණ්ඩ", "meaning": "තෙලසවු ගස, ඇඹරැල්ලා", "category": "plant" },
  { "word": "ගර්දභී", "meaning": "එල කටරොලු, කටුවැල්බටු", "category": "plant" },
  { "word": "ගර්දිපර්ණී", "meaning": "නෝසාල (ගෝන්සල) වැල්", "category": "plant" },
  { "word": "ගර්බ", "meaning": "තෙලසවු ගස", "category": "plant" },
  { "word": "ගර්භ", "meaning": "ඇවට්ඨිය, ලෝලු", "category": "plant" },
  { "word": "ගර්භකණ්ඨක", "meaning": "කොස්ගස", "category": "plant" },
  { "word": "ගර්භකර", "meaning": "බුන්සරණ", "category": "plant" },
  { "word": "ගර්භඝාතනී", "meaning": "ලියනගලා, මසිල", "category": "plant" },
  { "word": "ගර්භද", "meaning": "බුන්සරණ, එල කටුවැල්බටු", "category": "plant" },
  { "word": "ගර්භද්‍රුකා", "meaning": "බුන්සරණ", "category": "plant" },
  { "word": "ගර්භනාසනා", "meaning": "රක්පෙනෙල", "category": "plant" },
  { "word": "ගර්භනුද", "meaning": "ලියනගලා", "category": "plant" },
  { "word": "ගර්භපාතකා", "meaning": "මුරංගා, රත් මුරංගා", "category": "plant" },
  { "word": "ගර්භපාතන", "meaning": "රක්පෙනෙල ගස", "category": "plant" },
  { "word": "ගර්භපාතිනී", "meaning": "කිණිහිරිය, ලියනගලා", "category": "plant" },
  { "word": "ගර්භනාභ", "meaning": "පුමිල, තුත්පුමිල, සූරිය", "category": "plant" },

  // --- පිටුව 161 (image_87e153.jpg) ---
  { "word": "ගර්භවිග්‍රාවිනී", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ගර්භග්‍රාවීන්", "meaning": "කිතුල්", "category": "plant" },
  { "word": "ගර්භස්තී", "meaning": "රත්නිවුල්, බදුල්ල", "category": "plant" },
  { "word": "ගර්භසම්භවා", "meaning": "මහ එන්සාල්", "category": "plant" },
  { "word": "ගර්භාකාර", "meaning": "තලා, සුවතලා", "category": "plant" },
  { "word": "ගර්භාරා", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ගර්භාරි", "meaning": "ඇත් දෙමට, හීන් එන්සාල්", "category": "plant" },
  { "word": "ගර්භිනී", "meaning": "බුන්සරණ ගස", "category": "plant" },
  { "word": "ගර්භාබු", "meaning": "තිත්ත ලබු", "category": "plant" },
  { "word": "ගර", "meaning": "විෂ වගී", "category": "treatment" },
  { "word": "ගර්ජන", "meaning": "කළු අල, වේලා ගස", "category": "plant" },
  { "word": "ගර්බිල්ල වැල්", "meaning": "බොංග පුහුල්, යක් පුහුල්, බිබ්බි පුහුල් යන නම් වලින් හැඳින් වෙන මේ වැල්වල කත් පුහුල් වලට මඳක් කුඩාවූ අලුපාට ගෙඩි හටගනියි. 'මුව් මුව්' නමැති ගෙඩිවල රසයට සමාන රසයක් ඇති මේ ගෙඩි වල සූභ මුත්‍රකාරක ඖෂධයකි.", "category": "plant" },
  { "word": "ගර්දම", "meaning": "කදුරු ගස", "category": "plant" },
  { "word": "ගරල", "meaning": "වවවමාවි", "category": "treatment" },
  { "word": "ගරලය", "meaning": "වවවමාවි", "category": "treatment" },
  { "word": "ගරසන", "meaning": "අබ", "category": "plant" },
  { "word": "ගරහත්", "meaning": "කළු අබ, වේලා ගස", "category": "plant" },
  { "word": "ගරහනූ", "meaning": "ලුණිකර බිම", "category": "treatment" },
  { "word": "ගරා", "meaning": "කරගස", "category": "plant" },
  { "word": "ගරාත්මක", "meaning": "මුරංගා ගස", "category": "plant" },
  { "word": "ගරී", "meaning": "දේවදාලිය වැල්", "category": "plant" },
  { "word": "ගරිබ", "meaning": "අරළු", "category": "plant" },
  { "word": "ගරිද", "meaning": "ගුරැන්ද (ගුප්වන්දන) ආකාශ ගරුඩ, (සමහර පළාත් වල ගර්බිල්ලා (යක් පුහුල්) වැල් වලට ද ගරිද යයි කියති.)", "category": "plant" },
  { "word": "ගරා", "meaning": "අගිල්, ඇවට්ඨිය", "category": "plant" },
  { "word": "ගරඩ", "meaning": "සවණිමාක්‍ෂි (රත් මසිදු)", "category": "treatment" },
  { "word": "ගුරාළු හාල්", "meaning": "ගුරාළු හාල්", "category": "treatment" },
  {
    "word": "ගරුඬපාසාණ",
    "meaning": "නිල් මේ වන් පැහැති ගල් වර්‍ගයකි. මේ ගල් වර්‍ගයේ විෂ නාශක බලයක් ඇතැයි බොහෝ දෙනා අතර පවතින විශ්වාසයක් තිබේ. සබන් කෑල්ලක හැඩ හුරාකමට කැපූ මේ වර්‍ගයේ ගලකින් ස්නානය කරණ වේලාවල දී ඇඟ ඇතිල්ලීම කරන්නේ සමේ හටගන්නා හොරි, දද, කුෂ්ඨ, අවහන් ආදී රෝග සුව කර ගැනීම සඳහා ය. ගරුඬෙකු (ලොකු පත්තෑයෙකු) ගේ හැඩහුරුකමට බොහෝ සෙයින් සමාන දෙ පැත්තට බෙදී ගිය කුඩා කොළ සහිත පැළෑටියකි.",
    "category": "treatment"
  }
];