// data_325_334.js - පිටු 325 සිට 334 දක්වා සියලුම වචන
const data_extra_325_334 = [
    // --- පිටුව 325 ---
    { "word": "ඵේංගු", "meaning": "කොටදිඹුලා", "category": "plant" },
    { "word": "ඵේණ", "meaning": "මුදුපෙණ", "category": "nature" },
    { "word": "ඵේණාහ්ව", "meaning": "මුදුපෙණ", "category": "nature" },
    { "word": "ඵේන්ල", "meaning": "බෙබර, සින්බෙබර ගෙඩි, කොසඹ, රුක්පෙනෙල", "category": "plant" },
    { "word": "බංගය", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "බංජි", "meaning": "ගිරිතෙල්ල වැල(මාබණඩා)", "category": "plant" },
    { 
        "word": "බක්මී", 
        "scientific": "Sarcocephalus Cordatus",
        "meaning": "Sarcocephalus Cordatus- බක්මී පේරනැබල හෝ කුඩා තේක්ක කොළ වැනි කොළ ඇති විශාල ගසකි. මෙහි කඳ ලා කොස් ගසක අරටුව මෙන් ලා කහ පැහැයෙන් යුක්ත ය. මල් මඳක් ඉදුන රඹුටන් ගෙඩි වැනි ය. ගෙඩි සපදිල්ලා ගෙඩි පමණ ඇත. ඇඹුල් රසයෙන් හා පැණි රසයෙන් යුත් මේ වර්ගයේ ඉදුන ගෙඩි ගම්බද පාසැල් කරා යන එන සිසු දරුවන්ගේ අතිරේක ආහාරයකි. බක්මී පොතු වියරු බලු විෂට හා සර්ප විෂට ප්‍රත්‍යක්ෂ ඖෂධයකි. මේ පොතු කලං දොළහක් ගෙන පත අට පත එකට සිඳුවා එළ ගිතෙල් අනුපාන දමා උදේ-සවස කෂාය හතරක් හෝ උදෑසන හතරක් මේ පොතු යුෂ දුමු කඳ ප්‍රතිවාප වශයෙන් ගිතෙල් දමා නොබී දුනහොත් හැම වර්ගයක ම ශරීරගත වූ විෂ පහ වෙයි. කෑ මුඛය ඉදිමී තිබේ නම්: මේ පොතු කහ-ලුණු ලා කොටා මලවා උදේ-සවස බැඳ යුතු යි. මෙය අඟල් දොළහක් පමණ දිග හා අඟල් හතරක් පමණ පළල ඇති වවුල්මුගා කොළ වැනි කොළ වලින් යුත් නෑඹුව් ගස් මෙන් සෘජුව යන වහාවැවෙන ගසකි. මෙහි ලීය සුදු පාට යි. මේ වර්ගය දර පිණිස මිස ඖෂධ පිණිස ගැනීමට නියම කළ තැනක් දකින්ට නැත. බක්මී-බකිනි දෙක එක ම වර්ගයක් වශයෙන් ඇතැම් පළාත්වල සලකති. එහෙත් වචන දෙකේ මිස ගස් දෙකේ කිසිම සමානකමක් නැති මේ ගස් දෙක වෙන් වශයෙන් අඳුනා ගැනීම ප්‍රයෝජනවත් ය. බක්මී පොතු වෙනුවට බකිනි පොතු වරදවා ගතහොත් නැති අසනීප ඇතිවිය හැකි හෙයිනි.", 
        "category": "plant",
        "image": "img_325_bakmee.jpg"
    },
    { 
        "word": "බකිනි", 
        "meaning": "බකිනි ගස", 
        "category": "plant",
        "image": "img_325_bakini.jpg"
    },

    // --- පිටුව 326 ---
    { "word": "බක", "meaning": "වකපුෂ්ප, කොකුම්", "category": "plant" },
    { "word": "බකන", "meaning": "ගර්භප්පිලි", "category": "plant" },
    { "word": "බකුල", "meaning": "මුහුණමල්", "category": "plant" },
    { "word": "බගය", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "බගහර", "meaning": "සුරා", "category": "liquid" },
    { "word": "බජ්ජල", "meaning": "යක්එරබදු (පාරිහද) බෙබර ගස", "category": "plant" },
    { "word": "බටකපුරු", "meaning": "බටගස් තුල සෑදෙන සිනක්කාරම් කෑලි වැනි සුදු පාට ද්‍රව්‍යය", "category": "mineral" },
    { 
        "word": "බඩකිරිල්ල", 
        "scientific": "Erythroxylon Lucidum",
        "meaning": "Erythroxylon Lucidum- බඩකිරිල්ල, බට (කොහු) කිරිල්ල, හුනු කිරිල්ල යයි කිරිල්ල වර්ග තුනකි. කෝරකාකොළ මෙන් උල් වී ගිය සිහින් කොළ හා නයි (සිහින්) මිරිස් කරල් වැනි ඉදුන විට රත් පාට ගෙඩි ඇති වර්ගය බඩකිරිල්ල යි. මේ ගසේ කොළ, මුල්, පොතු ආදී හැම දෙයක් ම ලමා (කෘමි) රෝග පිළිබඳ ප්‍රත්‍යක්ෂ ඖෂධයකි. කොළ වියලා කුඩු කර හාල් පිටි සමග මිශ්‍රකර කිතුල් හකුරු හෝ පැණි දමා සකස් කර ගන්නා අග්ගලා කෘමි රෝග නාශක ආහාරයක් වශයෙන් ලමයින්ට කෑමට දෙති. තද පණු ගායට මේ පොතු කෂාය පොවති. මේ ගසේ කොළත් වෙනත් ඖෂධ යෝග සමග මිශ්‍ර කර සකස් කළ ලමා රෝග පිළිබඳ බෙහෙත් වර්ග ද ඇත.", 
        "category": "plant",
        "image": "img_326_badakirilla.jpg"
    },

    // --- පිටුව 327 ---
    { "word": "බට(කොහු)කිරිල්ල", "meaning": "බෝඹු කොළ පමණ විශාල කොළ ඇති ලොකු කිරිඳි ඇට පමණ විශාල ගෙඩි පොකුරු සෑදෙන වර්ගයකි. මේ ගෙඩි ගම්බද ලමයින්ගේ පාසැල් ජීවිතයෙහි දී බට ලී වලින් සෑදූ (කිරිල්ල තුවක්කු) තුවක්කු වලට දමා වෙඩි තැබීමට පාවිච්චි කරති. ඉදුන විට කළු පාට වූ මේ කිරිල්ල ගෙඩි ඇඹුල් රසින් හා පැණි රසින් යුක්ත ය. ඒවා කෑමට පක්‍ෂින් මෙන් ම ලමයින් ද කැමති ය. මේ වර්ගය බෙහෙත් වලට ගැනීමක් නැත.", "category": "plant" },
    { "word": "හුනුකිරිල්ල", "meaning": "කොළ බටකිරිල්ල කොළ වලටත් මඳක් විශාල ය. ගසත්, කොළත් මද සුදු පැහැයකින් යුක්ත ය. ඒ වර්ගයේ ගෙඩි කොහුකිරිල්ල ගෙඩි වලට වඩා මඳක් කුඩා ය. සතුන්ගේ කණ්‍යාහරණ මෙන් මේ වර්ගයේ ගෙඩි වල ඉදිරි පැත්තේහි වෙන් වෙන් ම මතුපී පෙනෙන ඉබුළු තුනක් ඇත. ගෙඩි ද තද සුදු පාටින් යුක්ත ය. දර පිණිස හැර හුනුකිරිල්ල ගසෙන් ගන්නා වෙන ප්‍රයෝජනයක් නැත.", "category": "plant" },
    { "word": "බටදැල්", "meaning": "බටදැල්ල නම් වූ විශාල ව වැවෙන තෘණ වර්ගය", "category": "plant" },
    { "word": "බටු", "meaning": "බටු ගස", "category": "plant" },
    { "word": "බටුකර", "meaning": "කරබටු, ඉදුන එළබටු හෝ ඉදුනු එළබටු ගෙඩියේ මද ය. (වනාගත ව වැවෙන එළ බටු ගෙඩි වලට සමාන ගෙඩි ඇති රතු පාට වර්ගයක් ඇත. ඒවාට ද කරබටු යයි කියති.)", "category": "plant" },
    { "word": "බඩල්වනස්ස", "meaning": "විල්වනස්ස, ඇදුම (රෝගය)ට ප්‍රත්‍යක්ෂ ඖෂධයකි.", "category": "plant" },
    { "word": "බඩිල", "meaning": "සියඹලා", "category": "plant" },
    { "word": "බණ", "meaning": "ගින්නේරිය ගස", "category": "plant" },
    { "word": "බණිග්බණ්ඩු", "meaning": "බෙරු ගස", "category": "plant" },
    { "word": "බද්දිප", "meaning": "යක්එරබදු ගස", "category": "plant" },
    { "word": "බද්දිප ඇට", "meaning": "එරබදු ඇට", "category": "plant" },
    { "word": "බද්දිය", "meaning": "එරබදු", "category": "plant" },
    { "word": "බදර", "meaning": "මඟකපු, බෙබර, බිමනල්", "category": "plant" },
    { "word": "බදරි", "meaning": "බෙබර, බිමිතල්, මඟකපු, යක්බේරිය, ගණගස, නිදිකුම්බා, හුරල", "category": "plant" },
    { "word": "බදතිකා", "meaning": "කපු", "category": "plant" },
    { "word": "බදරිච්ඡද", "meaning": "ඇත්බෙබර", "category": "plant" },
    { "word": "බදරිතරු", "meaning": "බෙබර ගස, බදුල්ල ගස", "category": "plant" },
    { "word": "බදරිපත්‍ර", "meaning": "බෙබරපත්", "category": "plant" },
    { "word": "බදරිඵල", "meaning": "නිල් සේපාලිකා", "category": "plant" },
    { "word": "බදිර", "meaning": "කාල", "category": "plant" },
    { "word": "බදිරෝ", "meaning": "කිණිහිරි", "category": "plant" },
    { "word": "බදු", "meaning": "සුගල", "category": "plant" },
    { "word": "බදුරට", "meaning": "මසන් ඇට", "category": "plant" },
    { "word": "බදුන", "meaning": "හාපනය", "category": "plant" },
    { "word": "බදුවද", "meaning": "පොකුරු සෑදෙන ලොකු වදමල්", "category": "plant" },
    { "word": "බදුලු", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "බදු", "meaning": "රණහුණ", "category": "plant" },
    { "word": "බදුකා", "meaning": "මඟුල්කරඳ", "category": "plant" },
    { "word": "බදුලතා", "meaning": "ඉරමුසු වැල", "category": "plant" },
    { "word": "බධපාදි", "meaning": "හබනගිරියා", "category": "plant" },
    { "word": "බධපුෂ්පි", "meaning": "බිමකල්", "category": "plant" },

    // --- පිටුව 328 ---
    { "word": "බධඵල", "meaning": "කරඳ", "category": "plant" },
    { "word": "බධිර", "meaning": "සණ, යකබ, යක්බේරිය", "category": "plant" },
    { "word": "බන්ධුක", "meaning": "සින් දුමැඬ, පනුරාපණ", "category": "plant" },
    { "word": "බන්දු", "meaning": "සාෂහක", "category": "plant" },
    { "word": "බන්දුල", "meaning": "බදුවද ගස", "category": "plant" },
    { "word": "බන්ධුපාදි", "meaning": "හබන ගිරියා", "category": "plant" },
    { "word": "බන්ධි", "meaning": "සුළු පෝටා වැල", "category": "plant" },
    { "word": "බන්ධ්‍යා", "meaning": "ගෝරෝචන", "category": "plant" },
    { "word": "බන්ධ්‍යාකෝටි", "meaning": "මල්තුඹ", "category": "plant" },
    { "word": "බන්ධු", "meaning": "බදුවද", "category": "plant" },
    { "word": "බන්ධුක (2)", "meaning": "බදුවද, ගම්මාළු ගස", "category": "plant" },
    { "word": "බන්ධුක පුෂ්ප", "meaning": "පියා ගස", "category": "plant" },
    { "word": "බන්ධීව, බන්ධීවක", "meaning": "බදුවද", "category": "plant" },
    { "word": "බන්ධීවක පුෂ්ප", "meaning": "රන්වන් අත්තන, බදුවද මල්", "category": "plant" },
    { "word": "බන්ධුවර", "meaning": "බදුවද, නලමුරු, වලඟසාල්, සාෂහක", "category": "plant" },
    { "word": "බන්ධුර", "meaning": "කුන්දිරුක්කන්, සාෂහක", "category": "plant" },
    { "word": "බක්නව", "meaning": "කාලනිය ගස", "category": "plant" },
    { "word": "බනව්‍ය", "meaning": "සුදු දුනු", "category": "plant" },
    { "word": "බනත්", "meaning": "බත්", "category": "food" },
    { "word": "බපෙපා", "meaning": "කඩුලු", "category": "plant" },
    { "word": "බබුරු දමුණු", "meaning": "එඬරු රූක (කොලොම් ගස)", "category": "plant" },
    { "word": "බබුස්තාන", "meaning": "බබිබප් නම් තෘණ වර්ගය", "category": "plant" },
    { "word": "බභා", "meaning": "මහ එන්සාල්", "category": "plant" },
    { "word": "බභාබාහු", "meaning": "රන්වන් අත්තන, ගුරා", "category": "plant" },
    { "word": "බභාෂ්ට", "meaning": "තුවරලා", "category": "plant" },
    { "word": "බම්බු", "meaning": "උණගස", "category": "plant" },
    { "word": "බමර", "meaning": "බඹර පැණි", "category": "food" },
    { "word": "බරමුල්", "meaning": "ලුණුවිල, බැමිතිරිය", "category": "plant" },
    { "word": "බබර", "meaning": "මී මැස්සන්", "category": "animal" },
    { "word": "බබුරක්", "meaning": "කාල", "category": "plant" },
    { "word": "බබුරු", "meaning": "කුකුළන්", "category": "animal" },
    { "word": "බරී", "meaning": "ලොලු", "category": "plant" },
    { "word": "බරගිපත්‍ර", "meaning": "ලොලු කොළ", "category": "plant" },
    { "word": "බර්බට", "meaning": "වී", "category": "plant" },
    { "word": "බර්බර", "meaning": "රිදී, වේලා, සිරිතේක්කු, සල් ගස, රම්මානිස්ස, පිල ගස", "category": "plant" },
    { "word": "බර්බර වර්ෂක", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "බර්බරා", "meaning": "වේලා, රම්මානිස්ස", "category": "plant" },
    { "word": "බර්බරාබ්‍ය", "meaning": "රම්මානිස්ස", "category": "plant" },
    { "word": "බර්බරිකා", "meaning": "වේලා, රම්මානිස්ස", "category": "plant" },
    { "word": "බර්බෂ්ට", "meaning": "තුවරලා, ඉරිවේරිය", "category": "plant" },
    { "word": "බර්ව", "meaning": "කන්සා", "category": "plant" },
    { "word": "බර්හ", "meaning": "මෝණර පිල", "category": "plant" },
    { "word": "බර්හි", "meaning": "ගෝසාල වැල", "category": "plant" },
    { "word": "බර්හිනී පුෂ්ප", "meaning": "බඩදම්", "category": "plant" },
    { "word": "බර්හිෂ්ට", "meaning": "තුවරලා, ඉරිවේරිය", "category": "plant" },
    { "word": "බනයී", "meaning": "මෝණරපිල්, මහ පොණඬරු, ඉරක්", "category": "plant" },
    { "word": "බනර්‍හපුෂ්ප", "meaning": "පොණඬරු", "category": "plant" },
    { "word": "බර", "meaning": "රසකිඳ, තිපල්, මේවන්, බැමිතිරිය, පලමු, වලඟසාල්, දියමිත්ත, සාතාවාරිය, කහ", "category": "plant" },
    { "word": "බරනුල්", "meaning": "අඟල් 12 = (අඩිය)", "category": "measurement" },
    { "word": "බරන", "meaning": "නයා", "category": "animal" },
    { "word": "බරනය", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "බරමස්", "meaning": "මෝරා", "category": "animal" },
    { "word": "බරවා", "meaning": "(බරපා) ශ්ලීපද=ශීපද රෝගය", "category": "treatment" },
    { "word": "බරස්", "meaning": "කෙසෙල් =(මස් කෙසෙල් වර්ග)", "category": "plant" },
    { "word": "බලලක", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "බලලකා", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "බල්ලී", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "බලප", "meaning": "මහ බැවිල, අමුක්කරා, සාරණ", "category": "plant" },
    { "word": "බලයඵල", "meaning": "ලා ගෙඩි", "category": "plant" },
    { "word": "බලයා", "meaning": "අමුක්කරා, මේවන්, අරළු", "category": "plant" },
    { "word": "බල", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "බලකොල", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "බලප්", "meaning": "බබුස් තෘණ", "category": "plant" },
    { "word": "බලපා", "meaning": "අමුක්කරා", "category": "plant" },

    // --- පිටුව 329 ---
    { "word": "බලද", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "බලදා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "බලභද්‍ර", "meaning": "සරල, (හොර ගස)", "category": "plant" },
    { "word": "බල භද්‍රක, බල භද්‍රිකා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "බල භෙෂජ්‍ය", "meaning": "වෙනිවැල් කෂායෙහි ලා ශුද්ධ කර ගත් තුතු (පල්මානික්කම්)", "category": "compound" },
    { "word": "බලමුත්තාපනිකා", "meaning": "හෙළ එරබු", "category": "plant" },
    { "word": "බලල් වසුරු", "meaning": "බලල් බෙටි", "category": "animal" },
    { "word": "බලවජ", "meaning": "වැලුක්", "category": "plant" },
    { "word": "බලවන්ත", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "බලසාර", "meaning": "සල් ගස", "category": "plant" },
    { "word": "බලසෞගන්ධිකා", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "බලා", "meaning": "අස්වැන්න, වල් මුං, සුළු බැවිල", "category": "plant" },
    { "word": "බලාකා", "meaning": "මහ බැවිල, සිරිවාඩි බැවිල", "category": "plant" },
    { "word": "බලාග්නි", "meaning": "කලගස", "category": "plant" },
    { "word": "බලාස්‍ය", "meaning": "මුං", "category": "plant" },
    { "word": "බලාහිකතා", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "බලාමෝටා", "meaning": "සස්සඳ, කංසා", "category": "plant" },
    { "word": "බලාය", "meaning": "ලුණුවරණ, කැළිය ගස්", "category": "plant" },
    { "word": "බලාසග්නී", "meaning": "දූදු වැල්", "category": "plant" },
    { "word": "බලාසාග්නි", "meaning": "දූදු වැල්", "category": "plant" },
    { "word": "බලාහක", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "බලි", "meaning": "මහ බැබිල", "category": "plant" },
    { "word": "බලික්ම", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "බලික්මා", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "බලික්කුට", "meaning": "රත්තිටුල්", "category": "plant" },
    { "word": "බලිත", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "බලිපු", "meaning": "කරබෙගිය", "category": "plant" },
    { "word": "බලිප්‍රිය", "meaning": "ලොන් ගස", "category": "plant" },
    { "word": "බල්", "meaning": "කළු ලුණු", "category": "mineral" },
    { "word": "බද්ධිවි", "meaning": "වරාපක්කඩ, පතොක්", "category": "plant" },
    { "word": "බ(ව)ර", "meaning": "රසකිඳ, නිපල්, මේවන්, බැමිතිරිය, වලඟසාල්, කොකුම්, අමු ඉඟුරු, දියමිත්ත, කහ, ලුණුවරණ, ශාතාවාරිය", "category": "plant" },
    { "word": "බස්ත", "meaning": "රන්වන් වේලා", "category": "plant" },
    { "word": "බස්තාගන්ධී", "meaning": "සුළු කුඹුක්", "category": "plant" },
    { "word": "බස්තාගන්ධ", "meaning": "වේලා", "category": "plant" },
    { "word": "බස්තාගන්ධිකා", "meaning": "පෙරුන්කායම්", "category": "plant" },
    { "word": "බස්තානතී", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "බස්තමෝද", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "බස්තුගුහාන්", "meaning": "වැල් මදට", "category": "plant" },
    { "word": "බස්තුගන්ධි", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "බස්තුගන්ධිකා", "meaning": "මැඩහඟු, පෙරුම්කායම්", "category": "plant" },
    { "word": "බස්තුගන්ධා", "meaning": "වේලා", "category": "plant" },
    { "word": "බස්මනං", "meaning": "අමුකපුරු", "category": "plant" },
    { "word": "බස්මාගීය", "meaning": "දේවදාර", "category": "plant" },
    { "word": "බස්ව", "meaning": "ඇට්ටර", "category": "plant" },
    { "word": "බහති", "meaning": "හෙළ බටු", "category": "plant" },
    { "word": "බහ දුරුසිරි", "meaning": "භද්‍රශ්‍රී වෘක්‍ෂය, සඳුන් ගස", "category": "plant" },
    { "word": "බහන්", "meaning": "ලනුව", "category": "plant" },
    { "word": "බහමුදුරි", "meaning": "වැල් මුරුංගා", "category": "plant" },
    { "word": "බහරි", "meaning": "කුසතණ", "category": "plant" },
    { "word": "බහල්", "meaning": "දෙසාලිස (42)", "category": "measurement" },
    { "word": "බහල", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "බහලා", "meaning": "මෝර ගස", "category": "plant" },
    { "word": "බහලබක්", "meaning": "වැල් මුරුංගා, තොටිල", "category": "plant" },
    { "word": "බහලබ්බ", "meaning": "පියා ගස, බෙලි ගස, හෙළ ලොත්, මෝරගස, කිරිපළු", "category": "plant" },
    { "word": "බහල පත්‍ර", "meaning": "කළු කිහිරි", "category": "plant" },
    { "word": "බහල පල්ලව", "meaning": "වැල් මුරුංගා", "category": "plant" },
    { "word": "බහල වල්කල", "meaning": "හෙළ ලොත්", "category": "plant" },
    { "word": "බහලා (2)", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "බහස්ම", "meaning": "භස්ම කිරීම", "category": "treatment" },
    { "word": "බගා", "meaning": "ගිතෙල්", "category": "liquid" },
    { "word": "බහුක්‍ෂීරී", "meaning": "මහ උක්", "category": "plant" },
    { "word": "බහුකණ්ටකි", "meaning": "හින් ගොකටු, කටුවෙලඟ, වැටකේ, සුළු තල ගස", "category": "plant" },
    { "word": "බහු කණ්ටකී", "meaning": "සෑම ගස", "category": "plant" },

    // --- පිටුව 330 ---
    { "word": "බහුකණ්ඩු", "meaning": "කටුවැල් බටු", "category": "plant" },
    { "word": "බහුකණ්ඩුක", "meaning": "කිබාරම්", "category": "plant" },
    { "word": "බහුකණ්ටක", "meaning": "වැටකේ", "category": "plant" },
    { "word": "බහුකර්ණිකා", "meaning": "මකුණුවැන්න", "category": "plant" },
    { "word": "බහුගන්ධ", "meaning": "කුන්දිරුක්කන්, පොත්ත, ඉද්ද, සපු කැකුළු, සුදු දුරු", "category": "plant" },
    { "word": "බහුවච්ඡද", "meaning": "පුලිල, භූරපත්‍ර", "category": "plant" },
    { "word": "බහුවිඡින්න", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "බහුවිඡින්නා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "බහුඡව", "meaning": "බෙලි, කිනිහිරැද", "category": "plant" },
    { "word": "බහුතර්නිකා", "meaning": "කලුකාමිමේරිය", "category": "plant" },
    { "word": "බහුද", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "බහුධාවන", "meaning": "අන්දර", "category": "plant" },
    { "word": "බහුධාවලය", "meaning": "හින් එන්සාල්", "category": "plant" },
    { "word": "බහුපත්‍රි", "meaning": "පුලිල", "category": "plant" },
    { "word": "බහුපත්‍ර", "meaning": "දිය බෙරලිය, මුරුවා", "category": "plant" },
    { "word": "බහුපත්‍රක", "meaning": "රුක් තිබ්බටු", "category": "plant" },
    { "word": "බහුපත්‍රා", "meaning": "මහ ශාතාවාරිය, වම්බටු, නව නැඹිලිය, කටුපිල, දියබෙරලිය", "category": "plant" },
    { "word": "බහු පත්‍රිකා", "meaning": "තිබ්බටු, ශාතාවාරිය, උළුවාහාල්", "category": "plant" },
    { "word": "බහුපත්‍රී", "meaning": "මිටවක්කා", "category": "plant" },
    { "word": "බහු පර්ණිකා", "meaning": "බෝ ගස", "category": "plant" },
    { "word": "බහුපර්ණිනී", "meaning": "පතුක්", "category": "plant" },
    { "word": "බහුපර්ණී", "meaning": "බෝ ගස", "category": "plant" },
    { "word": "බහුපර්විකා", "meaning": "උණගස", "category": "plant" },
    { "word": "බහුපර්ව පුෂ්පක", "meaning": "රන්වන් අත්තන", "category": "plant" },
    { "word": "බහුපල", "meaning": "හිරිණු", "category": "plant" },
    { "word": "බහුපා, බහුපාද", "meaning": "නුග ගස, මහ නුග", "category": "plant" },
    { "word": "බහුපාදි", "meaning": "අබනගිරියා", "category": "plant" },
    { "word": "බහුපුට", "meaning": "සුදු ලූනු, භූරපත්‍ර, පුලිල, මිණිඅත්", "category": "plant" },
    { "word": "බහුපුටී, බහුපුට්‍රා", "meaning": "මිටවක්කා", "category": "plant" },
    { "word": "බහුපුත්‍රිකා", "meaning": "තිබ්බොටු", "category": "plant" },
    { "word": "බහුපුෂ්ප", "meaning": "කටුපිල ගස, මයිල ගස", "category": "plant" },
    { "word": "බහුපුජා", "meaning": "කටුපිල", "category": "plant" },
    { "word": "බහුඵල", "meaning": "වැල් තිබ්බටු", "category": "plant" },
    { "word": "බහුඵලා", "meaning": "මුද්දරප්පලම්, කහකාමීරිය, එල ඔලිඳ, වැල් තිබ්බටු", "category": "plant" },
    { "word": "බහුඵලාගස", "meaning": "එල කිහිරි", "category": "plant" },
    { "word": "බහුඵලී, බහුඵලීව", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "බහුපේණිකා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "බහුබිජ්", "meaning": "මිරිස්", "category": "plant" },
    { "word": "බහුබිජක", "meaning": "තකුල්, ඇට කෙසෙල්, ගොඩ මිරිස්", "category": "plant" },
    { "word": "බහුබිජ්‍ය", "meaning": "කපුකැන", "category": "plant" },
    { "word": "බහු මඤ්ජරී", "meaning": "තලා, කළුතලා", "category": "plant" },
    { "word": "බහුමුර්වී", "meaning": "වල් කපු ගස", "category": "plant" },
    { "word": "බහුමුල", "meaning": "මුරුංගා, සැවැන්න, සාතාවාරිය, කළු කිහිරි", "category": "plant" },
    { "word": "බහුමුලා", "meaning": "සැවැන්න, සාතාවාරිය", "category": "plant" },
    { "word": "බහුමුලිකා", "meaning": "ඇම්බරැල්ල", "category": "plant" },
    { "word": "බහුරස", "meaning": "උක්ගස", "category": "plant" },
    { "word": "බහුරන්දි", "meaning": "නෙළුඹුදැලි", "category": "plant" },
    { "word": "බහුරූප", "meaning": "එඬරු (කොලොම්) වෘක්‍ෂය", "category": "plant" },
    { "word": "බහුරූප (2)", "meaning": "දුම්මල, මයිල, බදුල්ල", "category": "plant" },
    { "word": "බහුරේණුක", "meaning": "කරබෙගිය", "category": "plant" },
    { "word": "බහුල", "meaning": "බෙරු, එන්සාල්, ශතපුෂ්ප, මැඩහඟු", "category": "plant" },
    { "word": "බහුලගන්ධා", "meaning": "එන්සාල්", "category": "plant" },
    { "word": "බහුලච්ඡද", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "බහුලා", "meaning": "මහ එන්සාල්, හින් එන්සාල්, ශතපුෂ්ප, බුලත් වැල්, කටුවැල්බටු, මැඩහඟු", "category": "plant" },
    { "word": "බහුලායීනී", "meaning": "එන්සාල්", "category": "plant" },
    { "word": "බහුවල්ලි", "meaning": "මහ කරවිල", "category": "plant" },
    { "word": "බහුවාතක", "meaning": "ලොලු ගස", "category": "plant" },
    { "word": "බහුවාර", "meaning": "ලොලු ගස", "category": "plant" },
    { "word": "බහුවාරක", "meaning": "ලොලු, අන්දර", "category": "plant" },
    { "word": "බහුවාහක", "meaning": "ලොලු", "category": "plant" },

    // --- පිටුව 331 ---
    { "word": "බහුවින්නා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "බහුවීජ", "meaning": "අසු ගස්", "category": "plant" },
    { "word": "බහුවීය්‍ය", "meaning": "තලා, බුලු, කුරතම්පලා, ඉඹුල්, අහු ගස", "category": "plant" },
    { "word": "බහුශල්‍ය", "meaning": "කළු කිහිරි", "category": "plant" },
    { "word": "බහුශාලා", "meaning": "දදුක්", "category": "plant" },
    { "word": "බහුශාඛිකා", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "බහුසුතා", "meaning": "පිටවක්කා, සාතාවාරිය", "category": "plant" },
    { "word": "බහුසුවා", "meaning": "කිහිරි", "category": "plant" },
    { "word": "බනේදක", "meaning": "බුළු", "category": "plant" },
    { "word": "බලල්", "meaning": "බලල් ලුණු", "category": "mineral" },
    { "word": "බයංසි", "meaning": "කටුවැල් බටු", "category": "plant" },
    { "word": "බාංජ්", "meaning": "ගිරිනිල්ල", "category": "plant" },
    { "word": "බාකුවි", "meaning": "බෝදි ඇට = බබුවි, කලු කොල්ලු ඇට වලට සමාන ඇට වර්ගයකි. ඇතැම් අය බෝදි ඇට - සන්නි නායම් දෙවර්ගය ම එක වර්ගයක් ලෙස සලකතත් සන්නි නායම් වෙන වර්ගයකි. කාකණොලා නමින් බෝදි ඇට ත් ගම්භ්‍රාවී නමින් සන්නිනායමුත් හැඳින්වේ යි. ඡායාරූප සහිත සන්නිනායම් ගැන ලියූ විවේචනය ඉදිරියෙන් ඇත, බලන්න.", "category": "plant" },
    { "word": "බාදර", "meaning": "කපු ගස, කපු පුළුන්, නූල්", "category": "plant" },
    { "word": "බාදරා", "meaning": "කැකුණ ගස", "category": "plant" },
    { "word": "බාධියං", "meaning": "බිහිරි බව", "category": "treatment" },
    { "word": "බාන", "meaning": "නිල් කටුකරඬු, සැවැන්න, පිලිල, කණවේසියා පැණි, ගිරිනිල්ල", "category": "plant" },
    { "word": "බානක", "meaning": "නිල් කටුකරඬු", "category": "plant" },
    { "word": "බාතදැසි", "meaning": "නිල් ගිරිනිල්ල", "category": "plant" },
    { "word": "බානවීරස", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "බානාහ්ව", "meaning": "මුකුප් නම් තණකොළ", "category": "plant" },
    { "word": "බාර්ලි", "meaning": "යව නම් ධාන්‍ය වර්ගය", "category": "plant" },
    { "word": "බාලිගිකා", "meaning": "කොකුම්, රත් නිටුල්, පෙරුම්කායම්", "category": "plant" },
    { "word": "බාල", "meaning": "ඉරිවේරිය, බෝලිද්ද, හින් එන්සාල්, වැටකේ, පොල් ගස, වැටකේ මල, ඉද්ද මල", "category": "plant" },
    { "word": "බාලක", "meaning": "ඉරිවේරිය, කෙහෙල්, කිහිරි", "category": "plant" },
    { "word": "බාලක ප්‍රිය", "meaning": "කෙසෙල්, ගොන් කැකිරි", "category": "plant" },
    { "word": "බාලතනය", "meaning": "කිහිරි", "category": "plant" },
    { "word": "බාලතාණ", "meaning": "ලා තණ", "category": "plant" },
    { "word": "බාලපත්‍ර", "meaning": "කළු කිහිරි, ඇල් කසඹිලියා, රත් කිහිරි, සිරිවාඩි බැවිල", "category": "plant" },
    { "word": "බාලපුෂ්ප", "meaning": "මහ ඇල් කසඹිලියා", "category": "plant" },
    { "word": "බාල පුෂ්පිකා", "meaning": "බෝලිද්ද", "category": "plant" },
    { "word": "බාලප්‍රියා", "meaning": "කැකිරි", "category": "plant" },
    { "word": "බාලඵල", "meaning": "ලා ගෙඩි", "category": "plant" },
    { "word": "බාලවායප්", "meaning": "නිල් වෛරෝඩි", "category": "mineral" },
    { "word": "බාල්‍ය ඵල", "meaning": "ලා ගෙඩි", "category": "plant" },
    { "word": "බාලා", "meaning": "පොල් ගස, සිනිද්ද පුනෙද, ඇඹුලැඹිලිය, නිල් කටුකරඬු, කෝමාරිකා, ඉද්ද", "category": "plant" },
    { "word": "බාලිකා", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "බාලිය", "meaning": "බලිද", "category": "plant" },
    { "word": "බාලී", "meaning": "හින් එන්සාල්", "category": "plant" },
    { "word": "බාලුකා", "meaning": "වැලි", "category": "nature" },
    { "word": "බාලෙය", "meaning": "සිරිතේක්කු, කලාදුරු", "category": "plant" },
    { "word": "බාලෙශාබ", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "බාලෙෂ්ට", "meaning": "බෙබර (මසන්)", "category": "plant" },
    { "word": "බා(වා)ණ", "meaning": "මුද්දරප්පලම්, පිල ගස, සැවැන්න මුල්, නිල් කටුකරඬු", "category": "plant" },
    { "word": "බා(වා)ලක", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "බාෂ්ප", "meaning": "කඳුළු", "category": "liquid" },
    { "word": "බාෂ්පිකා", "meaning": "පත්‍රාහිංගු, පෙරුම්කායම්", "category": "plant" },
    { "word": "බාහිර", "meaning": "රත් නිටුල්", "category": "plant" },
    { "word": "බාහු", "meaning": "අත", "category": "anatomy" },
    { "word": "බාහුලතා", "meaning": "කරවිල", "category": "plant" },

    // --- පිටුව 332 ---
    { "word": "බාහුලා", "meaning": "හින් එන්සාල්", "category": "plant" },
    { "word": "බාහු වල්ලී", "meaning": "කරවිල වැල", "category": "plant" },
    { "word": "බාහු වල්ලිකා", "meaning": "කරවිල, මහ කරිවිල", "category": "plant" },
    { "word": "බැකරපතු", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "බැටඳි තෙල්", "meaning": "තලතෙල්", "category": "liquid" },
    { "word": "බැඳි", "meaning": "ලාක්‍ෂා", "category": "mineral" },
    { "word": "බැඳිවටු කෙනෙල්", "meaning": "අමුවෙන් ඇඹුල් රසත් ඉදුන විට ඇඹුල් රස හා පැණිරසත් ඇති නවරිකෙසෙල් ගෙඩි වැනි ගෙඩි හට ගන්නා වියලි කලාපයේ පෑලවෙන මුතු කාවැටුපාවට ප්‍රත්‍යක්ෂ වැල් වර්ගයකි.", "category": "plant" },
    { "word": "බැබිල", "meaning": "බෑවිල ගස", "category": "plant" },
    { "word": "බැමිතිරිය", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "බැරිනි", "meaning": "ගණිනය", "category": "plant" },
    { "word": "බැලතණ", "meaning": "එනම් තෘණ වර්ගය. තල්මිට කපා, ලුණු ලා කොටා මලවා බඳින ශක්තිමත් තෘණ පඳුරු වර්ගයකි", "category": "plant" },
    { "word": "බෑලිල", "meaning": "බෑවිල ගස", "category": "plant" },
    { "word": "බෑවිල", "meaning": "බෑවිල වර්ග නවය-හින් බෑවිල, මහ බෑවිල, සුළු බූබෑවිල, මහ බූබෑවිල, කොටිකන් බෑවිල, සිරිවාඩි බෑවිල, කේගර බෑවිල, වැල්බෑවිල, පැණි බෑවිල යන නව වර්ගය යි. (බැබිල නැති තැන ප්‍රතිනිධි වශයෙන් අනෝදා ගැනීමට නියම කර තිබේ) පැණි බැබිල අශ්මරි රෝගයට ප්‍රත්‍යක්ෂ ඖෂධයකි.", "category": "plant" },
    { "word": "බෑහැනි", "meaning": "ගලකම් වල දී කරණ බැලුම", "category": "treatment" },
    { "word": "බිංරක්‍ෂා", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "බික්", "meaning": "නික, දෙබම් ගෙඩි ආදියෙහි ගලවා වෙන් කළ හැකි කොටස", "category": "plant" },
    { "word": "බිඟු", "meaning": "කිකිරිඳිය, මීමැස්සන්", "category": "plant" },
    { "word": "බිඟුකොළ", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "බිඟුසන්නා", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "බිජ්පූර", "meaning": "ලප්නාරම්", "category": "plant" },
    { "word": "බිජ්රුපු", "meaning": "ලප්නාරම්", "category": "plant" },
    { "word": "බිජී", "meaning": "කොමඩු", "category": "plant" },
    { "word": "බිබ්", "meaning": "බලල් ලුණු, තුවරලා", "category": "mineral" },
    { "word": "බිබිංග", "meaning": "කාල වර්ගයේ ගස් වල අතු (පීති)", "category": "plant" },
    { "word": "බිබිලු", "meaning": "බිබලි (තාල වර්ගයේ ගස්වල පීති)", "category": "plant" },
    { 
        "word": "බින්නුග", 
        "scientific": "Tylophora Asthmatica",
        "meaning": "Tylophora Asthmatica- නුග කොළ වැනි කොළ හා සාතාවාරිය අල වැනි මුල් ඇති වැල් වර්ගයකි. මේ මුල් මනා සුවඳකින් යුක්ත ය. මේ වර්ගය ප්‍රධාන වශයෙන්ම වමන කාරක (ලඝු විරේක) ඖෂධයකි. අතිසාර ජීවානු නැසීමෙහි ත්, ශලේෂ්මා, ජ්වර හා හෘදයාබාධ නැසීමෙහි ත් මුත්‍ර වර්ධනය කිරීමෙහි ත් පසස්නා ලදී.", 
        "category": "plant",
        "image": "img_332_binnuga.jpg"
    },

    // --- පිටුව 333 ---
    { "word": "බිත්කා", "meaning": "කවුඩු කැකිරි, කෝවක්කා, උඩැත්ත", "category": "plant" },
    { "word": "බිදල", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "බිදරුල", "meaning": "රත් කරව් ගස", "category": "plant" },
    { "word": "බිදාරී", "meaning": "ඌරල, සින් බෙබර ගස, කිරිබදු", "category": "plant" },
    { "word": "බිදාරිකා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "බිදාරී ගන්ධා", "meaning": "අස්වැන්න", "category": "plant" },
    { "word": "බිදාරී ගස්සා", "meaning": "සිනිත් බෙබර", "category": "plant" },
    { "word": "බින් තල්", "meaning": "බිමිතල් අල", "category": "plant" },
    { "word": "බින්තිබ", "meaning": "බින් කොහොඹ", "category": "plant" },
    { "word": "බින් රක්‍ෂ", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "බිනිසා", "meaning": "කන්සා", "category": "plant" },
    { "word": "බිමතුඹුරු", "meaning": "බතලවැල් වලට මඳක් සමාන වූ මෙහි සුදු, රතු භෙදයෙන් වර්ග දෙකක් ඇත.", "category": "plant" },
    { "word": "බිමිතිඹ", "meaning": "නිඹකොසඹ", "category": "plant" },
    { "word": "බිම නෙල්ලි", "meaning": "පිටවක්කා, මෙය හෙළ, රත් වශයෙන් දෙවර්ගයකි. සෝම රෝගාදියෙහි ගන්නේ සුදු වර්ගයයි.", "category": "plant" },
    { "word": "බිම පුහුල්", "meaning": "එළ කිරිබදු", "category": "plant" },
    { "word": "බිමබහුල", "meaning": "රත් කරව් ගස", "category": "plant" },
    { "word": "බිමිබි", "meaning": "කෙම්වැල්, = කෝවක්කා වැල්, (බිමුවැල්)", "category": "plant" },
    { "word": "බිම්බිඵල", "meaning": "(බිමුවගෙඩි) කෝවක්කා වැල් වල ගෙඩි (කෙම් ගෙඩි)", "category": "plant" },
    { "word": "බිම්බිකා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "බිම්බිරි, බිම්බිලිකා", "meaning": "බිලිං ගස", "category": "plant" },
    { "word": "බිම්බෝදක", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "බිම්මද", "meaning": "අබ", "category": "plant" },
    { "word": "බිම්මදු", "meaning": "බිම් දිගේ වැවෙන මදුවැල්", "category": "plant" },
    { "word": "බිම්මාරා", "meaning": "පොල් කරබඩයේ හැඩහුරු කම ඇති පොළවට ඇලී තිබෙන රතු පාට කුඩා පැල වර්ගයක්.", "category": "plant" },
    { "word": "බිම්මුල්", "meaning": "මදටිය ඇටයකට කුඩා වූ ඔතා තිබෙන නූල් බෝලයක් වැනි සුදු පාට දිග පණුවෙනි. මේ සතා හමු වූ විට බට කුඩල් වල දමා ප්‍රවේසම් කර තබති. නැවත දෙහි ඇඹුල් හෝ තන කිරි ගෑවුන විටක ප්‍රාණවත් වෙයි. පෝර පසෙහි සහ ගොම දිරා ගිය සරණ ගෙබිමි වල ද මොවුහු සිටිති.", "category": "animal" },
    { "word": "බිම්ලිය", "meaning": "එළ බිමිනඹුරු, ගැඩවෙල්ලු", "category": "plant" },
    { "word": "බිබු", "meaning": "කෝවක්කා, කොබෝවක්කා, කපුරු", "category": "plant" },
    { "word": "බිබුලු", "meaning": "ගස් වර්ගයක්", "category": "plant" },
    { "word": "බියල්", "meaning": "මී ඇට මදය", "category": "plant" },
    { "word": "බියලි", "meaning": "පියල්ල, පලුව", "category": "plant" },
    { "word": "බිල්ලෝ", "meaning": "බෙලි", "category": "plant" },
    { "word": "බිල්ව", "meaning": "බෙලි ගස, පලම, රත්නිවුල්", "category": "plant" },
    { "word": "බිල්වජ", "meaning": "වැලුක්", "category": "plant" },
    { "word": "බිල්වය", "meaning": "පලම, (කලං දෙළහ)බෙලි", "category": "measurement" },
    { "word": "බිල", "meaning": "බලල්ලුණු", "category": "mineral" },
    { "word": "බිලග", "meaning": "කෝන්", "category": "plant" },
    { "word": "බිලගෝ", "meaning": "කාබි", "category": "plant" },
    { "word": "බිල පත්‍ර", "meaning": "ඇල් කසඹිලියා", "category": "plant" },
    { "word": "බිලමෝහ", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "බිල්ජ්", "meaning": "බලල් ලුණු", "category": "mineral" },

    // --- පිටුව 334 ---
    { "word": "බිලාය", "meaning": "බෑවිල", "category": "plant" },
    { "word": "බිලාලපය", "meaning": "කලං තුණ", "category": "measurement" },
    { "word": "බිලාල ලවණ", "meaning": "බලල් ලුණු", "category": "mineral" },
    { "word": "බිලාලිකා", "meaning": "වලඟසාල්", "category": "plant" },
    { "word": "බිලී", "meaning": "ඉස්සන්", "category": "animal" },
    { "word": "බිලිං", "meaning": "බිලිං ගස", "category": "plant" },
    { "word": "බිලිඳුන්", "meaning": "කොල්ලු", "category": "plant" },
    { "word": "බිලිපුටු", "meaning": "කපුටන්", "category": "animal" },
    { "word": "බිලියද", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "බිෂ", "meaning": "තෙවඩල", "category": "plant" },
    { "word": "බිෂපුෂ්ප", "meaning": "රත් නෙළුම්", "category": "plant" },
    { "word": "බිෂපුගුන", "meaning": "රත් නෙළුම්", "category": "plant" },
    { "word": "බිෂිකා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "බිහිසර", "meaning": "තණරද, උණ ආදි තෘණ රාජ වෘක්‍ෂ", "category": "plant" },
    { "word": "බීජ්", "meaning": "ඇට, ලප්නාරං, අංකුරය, ඇට කෙසෙල්", "category": "plant" },
    { "word": "බීජක", "meaning": "පියා ගස, ලප්නාරං", "category": "plant" },
    { "word": "බීජකදලි", "meaning": "ඇට කෙසෙල්", "category": "plant" },
    { "word": "බීජකෘන්සිත", "meaning": "ලොලු ගස", "category": "plant" },
    { "word": "බීජකෝෂක", "meaning": "බීජකෝෂය, නෙළුම් බට්ට", "category": "plant" },
    { "word": "බීජගහී ප්‍රතාන", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "බීජගහී ප්‍රතානිකා", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "බීජධාන්‍ය", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "බීජපූර", "meaning": "දෙඹම්, ලප්නාරම්", "category": "plant" },
    { "word": "බීජ පූරක", "meaning": "ලප්නාරම්, දෙඹම් ගස", "category": "plant" },
    { "word": "බීජඵල", "meaning": "ඇට කෙසෙල්", "category": "plant" },
    { "word": "බීජඵලා", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "බීජමෝපපල", "meaning": "ඇට කෙසෙල් ගෙඩි", "category": "plant" },
    { "word": "බීජාහ්ව", "meaning": "ලප්නාරං", "category": "plant" },
    { "word": "බීතසන්නී", "meaning": "සන්නි රෝගයක්", "category": "treatment" },
    { "word": "බීනාශ", "meaning": "බුව", "category": "plant" },
    { "word": "බීරණ මූලිකා", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "බීරණී", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "බීරපත්", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "බුක්‍ෂා", "meaning": "රත්එඬරු", "category": "plant" },
    { "word": "බුජ්ජ", "meaning": "බූරුඳ", "category": "plant" },
    { "word": "බුජ්ජන", "meaning": "නයා", "category": "animal" },
    { "word": "බුජ්ජහය", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "බුජ්ජපත්", "meaning": "බුජ්ජරැක", "category": "plant" },
    { "word": "බුජ්ජරැක", "meaning": "දෙඹම් ගස", "category": "plant" },
    { "word": "බුටක", "meaning": "තිත්ත වැටකොළු", "category": "plant" },
    { "word": "බුත්සරණ", "meaning": "(ලංකාකානාස්) පමිත උඩ එකතුවන කුණු පසෙහි හා දෙණි වලත් හටගන්නා මේ වර්ගයේ ඇටි රත් හෙලඹු ඇට පමණ විශාලය. කළු පැහැයෙන් යුක්ත ය. කොළ මල් හා දඬු කැනාස් වලට සමානය.", "category": "plant" },
    { "word": "බුතක", "meaning": "නලා", "category": "plant" },
    { "word": "බුද්දප්පරණ", "meaning": "බුත්සරණ", "category": "plant" },
    { "word": "බුදුරිස්හාමි", "meaning": "මුඛමඟණ", "category": "plant" },
    { "word": "බුද්ධපුෂ්පි", "meaning": "බිමිතල්, ඌරල", "category": "plant" },
    { "word": "බුද්ධා", "meaning": "ඇටකෙහෙල්, ජටාමාංශ", "category": "plant" },
    { "word": "බුන්නෙල්", "meaning": "දුන්නෙල්, මීකිරි වලින් ගන්නා තෙල", "category": "liquid" },
    { "word": "බුන්ද", "meaning": "ගස් වැල්වල මුල", "category": "plant" },
    { "word": "බුනිබ්", "meaning": "බිමකොහොඹ", "category": "plant" },
    { "word": "බුබුස්තාන", "meaning": "සැවැන්දරා", "category": "plant" },
    { "word": "බුබුළුපැන්", "meaning": "පොළව පලාගෙන මතු වන දිය, බුබුළුවල ජලය", "category": "nature" },
    { "word": "බුම්බලා", "meaning": "බිම්බෑවිල", "category": "plant" },
    { "word": "බුරජ්", "meaning": "කිනිබුරැද", "category": "plant" },
    { "word": "බුරෂ්ක", "meaning": "තුරුක්තෙල්", "category": "liquid" },
    { "word": "බුරැට්ට", "meaning": "වැටකොළු", "category": "plant" },
    { "word": "බුරැත", "meaning": "එනම් ගස, මල් බුරැත, ඉටි බුරැත යයි බුරැත දෙවර්ගය කි. මල්බුරැත ලීයේ අරටුව වෛරන් වැටී තිබෙන අතර ඉටි බුරැත අරටුව තනිකර ඇත්දත් පාටින් යුක්ත ව තිබේ.", "category": "plant" },
    { "word": "බුරුජ", "meaning": "නවරෝෂ", "category": "plant" }
];

