// data_270_278.js - පිටු 270 සිට 278 දක්වා සියලුම වචන
const data_extra_270_278 = [
  // --- පිටුව 270 ---
  { "word": "නවදුස්පා", "meaning": "වසතැල්ල", "category": "plant" },
  { "word": "නවනීත", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "නවනීතක", "meaning": "එළඟිතෙල්", "category": "treatment" },
  { "word": "නවතාළිලිය", "meaning": "හෙළ පිටවක්කා, රතු පිටවක්කා", "category": "plant" },
  { "word": "නව මල්ලිකා", "meaning": "සිනිද්ද, සමන්පිච්ච, වැල් ඉද්ද", "category": "plant" },
  { "word": "නවමාලි", "meaning": "දෑසමන්", "category": "plant" },
  { "word": "නවමාලිකා", "meaning": "දොඩම් (සිනිද්ද, බෝලිද්ද)", "category": "plant" },
  { "word": "නවරත්න", "meaning": "මුතු, මැණික්, වෛඩූර්ය, (වෛරෝඩි), විදුර, ගෝමේද, පබලු, පද්මරාග, පච්ච, නිල් යන නව රුවන. (රතු, නිල්, සුදු නිල්, වෛරෝඩි, පද්මරාග, පුෂ්පරාග, ගෝමේද, පච්ච සහ මුතු කැටය යන නව රත්න සෑදීමක යි දැනට භාවිත වන්නේ.)", "category": "treatment" },
  { "word": "නවරත්න කුමාරයා", "meaning": "එඬරු ගස", "category": "plant" },
  { "word": "නවරච්චු කාන්තාවී", "meaning": "නවරිකෙසෙල් කන්තාවී", "category": "plant" },
  { 
    "word": "නවහන්දි", 
    "scientific": "Euphorbia Tirucalli",
    "meaning": "අප්‍රිකාව ජන්ම භූමි කොට ඇති මේ පැලෑටිය සෑම පුරුකකින්ම කුඩා පැන්සල් ප්‍රමාණ නඩු බෙදී යන නිසා නවහන්දි නමින් අප අතර ප්‍රකට වූවකි. කොළ වෙනුවට ත් දඬුම පිහිටීම, කිරි සහිත බව හා වියලි කලාපයේ වැවීම ගැන මේ කරුණු ගණන් සලකන විට දළුක් පවුලට ම අයත් මේ ගස අප්‍රිකාවෙහි සිට මෙහි ගෙන එන ලද්දැයි යන මතය සනාථ වෙයි. කෙසේ නමුත් මේ වගියට අපේ සංස්කෘත හා දේශීය නම් දී බෙහෙත් වට්ටෝරු වලට ද ඇතුළත් කර ඇත. මේ දඬු හන්දි තෙල් සිඳීමටත්, කිරි විරේකයක් වශයෙන් ගැනීමටත් අපේ වෙද පොත් වල නියම කර තිබේ.", 
    "category": "plant" 
  },
  { "word": "නවසී", "meaning": "කහකඩ කසට රස නැති, පොල් කඩුව පිට පැත්ත සුදු පාට පොල් වගියක්", "category": "plant" },
  { "word": "නවි", "meaning": "අබලු වැල", "category": "plant" },
  { "word": "නවි විලාසි", "meaning": "ලෝලු, රේරු", "category": "plant" },
  { "word": "නවෝධා", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "නෂ්ට කාමයා", "meaning": "අප්‍රාණික ලිංග ඇතිබව", "category": "symptom" },
  { "word": "නෂ්ට පුෂ්පය", "meaning": "ඔසප් නොවීම", "category": "symptom" },
  { "word": "නස්නාරං", "meaning": "නත්නාරං = ලප්නාරං (තද ඇඹුල් ගතියකින් යුත් කුඩා නාරං වගියක්)", "category": "plant" },
  { "word": "නහරි", "meaning": "හිඟුරු පියලි අල", "category": "plant" },
  { "word": "නහුස", "meaning": "තුවරලා", "category": "plant" },
  { "word": "නළ", "meaning": "කුලල් බට", "category": "plant" },

  // --- පිටුව 271 ---
  { "word": "නා", "meaning": "රියම්", "category": "plant" },
  { "word": "නාක්කතීනා", "meaning": "අනෝදා", "category": "plant" },
  { "word": "නාකවිටිනා", "meaning": "සමදරා ගස", "category": "plant" },
  { "word": "නාකවටුවාලේ", "meaning": "ඇට කෙසෙල්", "category": "plant" },
  { "word": "නාකනම්", "meaning": "සක්නැබ", "category": "plant" },
  { "word": "නාකප්පුතාප", "meaning": "නා කෙසරු", "category": "plant" },
  { "word": "නා කෙසර", "meaning": "නාමල් රේණු", "category": "plant" },
  { "word": "නාකුලි", "meaning": "අරත්ත, අස්වැන්න, හෙළ කටුවැල්බටු, රණවරා", "category": "plant" },
  { "word": "නාකුලී", "meaning": "අරත්ත, දන්තකැටියා, ඒකාවේරිය", "category": "plant" },
  { "word": "නාග", "meaning": "නාරාක, රියම්, දෙඹ, නාමල් රේණු, සිහින් නාරං, ගස්කැලිය, ඇත්දත්", "category": "plant" },
  { "word": "නාගකන්‍යා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "නාගකිංජල්කා", "meaning": "නාමල් රේණු", "category": "plant" },
  { "word": "නාග කුමාරි", "meaning": "වැල්මදට, රසකිඳ", "category": "plant" },
  { "word": "නාග කෙසර", "meaning": "නාමල් රේණු, දෙඹකිණ, නාගස්", "category": "plant" },
  { "word": "නාගගන්ධ", "meaning": "සිදුවරම්", "category": "plant" },
  { "word": "නාග ගන්ධ", "meaning": "මනෝසිල, පුස්වැන්න", "category": "plant" },
  { "word": "නාග ග්‍රන්ථි", "meaning": "සිදුවරම්", "category": "plant" },
  { "word": "නාගප්", "meaning": "සිදුවරම්", "category": "plant" },
  { "word": "නාගජීවනා", "meaning": "පොල්පලා", "category": "plant" },
  { "word": "නාගජිහ්වකා", "meaning": "මනෝසිල, පොල්පලා", "category": "plant" },
  { "word": "නාගජිහ්වා", "meaning": "ලක්, වැළුක්, රඹුක්, රත්ගිරියල්, පුස්වැන්න", "category": "plant" },
  { "word": "නාගතාලි", "meaning": "නාගදරණ", "category": "plant" },
  { "word": "නාගදත්", "meaning": "සිදුවරම්", "category": "plant" },
  { "word": "නාගදන්ත", "meaning": "බුලත්, කැකිරි, දත්ත", "category": "plant" },
  { "word": "නාගදන්තී", "meaning": "කැකිරි, දත්ත, රඹුක්, වැළුක්", "category": "plant" },
  { "word": "නාගදමනී", "meaning": "වැල්තුඹ, සප්සඳ", "category": "plant" },
  { "word": "නාගදිව", "meaning": "රත්ගිරියල්", "category": "plant" },
  { "word": "නාගද්‍රැ", "meaning": "දළක්", "category": "plant" },
  { "word": "නාගපතු", "meaning": "බුලත්", "category": "plant" },
  { "word": "නාග පාෂාණම්", "meaning": "පාෂාණම් වගියක් (වස)", "category": "treatment" },
  { "word": "නාගපුෂ්පක", "meaning": "මහදත්ත", "category": "plant" },
  { "word": "නාගපුෂ්ප", "meaning": "නාමල්, නාකෙසරු", "category": "plant" },
  { "word": "නාගපුෂ්ප ඵල", "meaning": "කොමඩු", "category": "plant" },
  { "word": "නාගපුෂ්පී", "meaning": "රසතැල්ල", "category": "plant" },
  { "word": "නාගපු", "meaning": "නාමල්", "category": "plant" },
  { "word": "නාගඵල", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "නාගබලා", "meaning": "සිරිවැඩි බැබිල, ගස්කැලිය", "category": "plant" },
  { "word": "නාගබාහු", "meaning": "සිදුවරම්", "category": "plant" },
  { "word": "නාගභින්න", "meaning": "පුස්වැන්න, මැණික්වැන්න, පොල්පලා", "category": "plant" },
  { "word": "නාගමරම්", "meaning": "නාගස", "category": "plant" },
  { "word": "නාගමල්ලී", "meaning": "අනිත්ත මල්", "category": "plant" },
  { "word": "නාගමිලි", "meaning": "නාගස", "category": "plant" },
  { "word": "නාගමාතා", "meaning": "රත්ගිරියල්, කළුතලා", "category": "plant" },
  { "word": "නාගමාරා", "meaning": "කිකිරිදිය", "category": "plant" },
  { "word": "නාගමාලිකා", "meaning": "මනෝසිල, නාගස්", "category": "plant" },
  { "word": "නාගමාලි", "meaning": "හෝලක", "category": "plant" },
  { "word": "නාගමුෂ්ටි", "meaning": "අනිත්ත මල්", "category": "plant" },
  { "word": "නාගර", "meaning": "සිද්ධිඟුරු, කලාඳුරු, කෙකටිය, දෙබම්, සිහින් නාරං, මය (ජම) නාරං", "category": "plant" },
  { "word": "නාගර", "meaning": "කලාඳුරු අල", "category": "plant" },
  { "word": "නාගරංග", "meaning": "සිහින් නාරං", "category": "plant" },
  { "word": "නාගලතා", "meaning": "බුලත් වැල", "category": "plant" },
  { "word": "නාගවතී", "meaning": "රසතැල්ල", "category": "plant" },
  { "word": "නාගවල්ලී", "meaning": "බුලත්", "category": "plant" },
  { "word": "නාගවල්ලිකා", "meaning": "බුලත්", "category": "plant" },
  { "word": "නාගවාරිනී", "meaning": "නාපිරිත්ත වැල්, තුත්තනාගම්", "category": "plant" },
  { "word": "නාගස්‍යෝනා", "meaning": "දත්ත", "category": "plant" },
  { "word": "නාගසම්භව", "meaning": "සින්දුරම්", "category": "treatment" },

  // --- පිටුව 272 ---
  { "word": "නාගසාර", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "නාගහන්තෘ", "meaning": "වැටකොළු, වදකසා", "category": "plant" },
  { "word": "නාගහනු", "meaning": "දිවිපසුරු, පසුවු තලා", "category": "plant" },
  { "word": "නාගා", "meaning": "කුන්දරුක්කන්", "category": "plant" },
  { "word": "නාගාන්තක", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "නාගාහ්වා", "meaning": "සුළු බැබිල, කළු රියම්, දිවි පසුරු", "category": "plant" },
  { "word": "නාගිනී", "meaning": "දිවිපසුරු, බුලත්, රසතැල්ල", "category": "plant" },
  { "word": "නාගෙලා", "meaning": "වටමිරිස් (වල් මොලඟු)", "category": "plant" },
  { "word": "නාගෝ", "meaning": "නාගස්", "category": "plant" },
  { "word": "නාට", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "නාටන", "meaning": "බදුල්ල", "category": "plant" },
  { "word": "නාටමිල", "meaning": "වැල්කොස්", "category": "plant" },
  { "word": "නාටුපරිපානි", "meaning": "ගස් බැබිල", "category": "plant" },
  { "word": "නාඩි", "meaning": "මීලපලා, බනි පෙරෙමිකායම්, ජයපාල, මගදියබෙරලිය", "category": "plant" },
  { "word": "නාඩිකා", "meaning": "වතුක්", "category": "plant" },
  { "word": "නාඩි කරඟ", "meaning": "හකුල්, කපුකිනිස්ස", "category": "plant" },
  { "word": "නාඩිනාරංගක", "meaning": "තකුල්, කපු කිනිස්ස", "category": "plant" },
  { "word": "නාඩින්ත්තා", "meaning": "බිම් කොසඹ", "category": "plant" },
  { "word": "නාඩිනිඹු", "meaning": "බගි පෙරෙමිකායම්", "category": "treatment" },
  { "word": "නාතුමාතුලේ", "meaning": "ලප්නාරම්", "category": "plant" },
  { "word": "නාතපාදුක්තා පුෂ්ප", "meaning": "කතුරු මුරුංගා", "category": "plant" },
  { "word": "නාද", "meaning": "අඹනගිරියා හෝ කූරතම්පලා", "category": "plant" },
  { "word": "නාදෙයු", "meaning": "පොල්පලා, හාතාවාරිය, රත්ගිරියල්", "category": "plant" },
  { "word": "නාදෙය", "meaning": "නීතිග", "category": "plant" },
  { "word": "නාදෙයි", "meaning": "බල්දම්, මදි, පිටවක්කා, (බිම්නෙල්ලි) සිහින්නාරං, ඇත්වග පුල්, (ඇත් කලාඳුරු)", "category": "plant" },
  { "word": "නාදෙය", "meaning": "සමිදලුහු, ඇඹුල්වේ, මිදි, කලාඳුරු, ඊතණ, කුසතණ, සිහින් නාරං, කොටදිඹුලා", "category": "plant" },
  { "word": "නානල්", "meaning": "බට", "category": "plant" },
  { "word": "නානා වර්ණ", "meaning": "දෙඹගස", "category": "plant" },
  { "word": "නාපිරිත්ත", "meaning": "වැල්, කොළ, මල් හා ගෙඩි ත් බොහෝ දුරට කපු කිනිස්ස වලට සමාන මේ වැලේ දළු ගෙඩි පැසවීම සඳහා ආලේපය පිණිස ගනිති.", "category": "plant" },
  { "word": "නාපුෂ්ප", "meaning": "නාමල් රේණු", "category": "plant" },
  { "word": "නාභී", "meaning": "කස්තුරි, (මුවනැබ) සක්නැබ, මලබටු", "category": "treatment" },
  { "word": "නාභිසිතා", "meaning": "රසාංජන", "category": "treatment" },
  { "word": "නාමවර මාබෝපත්", "meaning": "මෝරු මහ බෝකොළ", "category": "plant" },
  { "word": "නාමප්‍රිය", "meaning": "උක්සකුරු", "category": "treatment" },
  { "word": "නාමරක්කු", "meaning": "රතුළූනු", "category": "plant" },
  { "word": "නාමල්රේණු", "meaning": "නා කෙසරු", "category": "plant" },
  { "word": "නාමාලිකා", "meaning": "මිරිස්", "category": "plant" },
  { "word": "නායතිකෘතා", "meaning": "බිම් කොසඹ", "category": "plant" },
  { "word": "නායි කඩුඟු", "meaning": "රම්මානිස්ස, රත්පත් වේලා", "category": "plant" },
  { "word": "නායිපාකල්", "meaning": "තුඹ, වැල්තුඹ", "category": "plant" },
  { "word": "නායි වේලෙයි", "meaning": "රම්මානිස්ස", "category": "plant" },
  { "word": "නායුරුමි", "meaning": "කරල් සැබෝ", "category": "plant" },
  { "word": "නායුරිවි", "meaning": "කරල් සැබෝ", "category": "plant" },
  { "word": "නායීනිකෘතා", "meaning": "බිම් කොසඹ", "category": "plant" },
  { "word": "නාරං", "meaning": "හින් නාරං, ජමනාරං, නස්නාරං (නත්නාරං) ලප්නාරං යයි නාරං වගී කීපයකි. මේ හැම වගියක් ම ඖෂධ වශයෙන් ත් හා ආහාර වශයෙන් ත් ගනිති.", "category": "plant" },
  { "word": "නාරංග", "meaning": "සිහින් නාරං", "category": "plant" },
  { "word": "නාරත්තන්කායි", "meaning": "ලප්නාරම්", "category": "plant" },
  { "word": "නාරමට", "meaning": "වෙලිප්පරිත්ති", "category": "plant" },
  { "word": "නාරමිකම්", "meaning": "දෙබම්", "category": "plant" },
  { "word": "නාරෂ්ටා", "meaning": "පුවඟු", "category": "plant" },
  { "word": "නාරාවි", "meaning": "තරාදිය", "category": "treatment" },

  // --- පිටුව 273 & 274 ---
  { "word": "නාරායන අල", "meaning": "හාතාවාරිය අල", "category": "plant" },
  { "word": "නාරායනප්‍රිය", "meaning": "රත්පත් සඳුන්, වනු වැල්", "category": "plant" },
  { "word": "නාරායනී", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "නාරායනය", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "නාරිකේලි", "meaning": "පොල්", "category": "plant" },
  { "word": "නාරිකේලි ඵල", "meaning": "පොල් ගෙඩි", "category": "plant" },
  { "word": "නාරිස්න", "meaning": "රක්අඟුණ (ගස්අඟුණ)", "category": "plant" },
  { "word": "නාල", "meaning": "හඬු", "category": "plant" },
  { "word": "නාලක", "meaning": "වච්චනාවි, තම්පලා දඬු", "category": "plant" },
  { "word": "නාලානි", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නාලාරංජී", "meaning": "මිදිගස", "category": "plant" },
  { "word": "නාලි", "meaning": "සුළු පෝටාවැල, නාලිය", "category": "plant" },
  { "word": "නාලිකා", "meaning": "තල්, පොල්", "category": "plant" },
  { "word": "නාලිකා", "meaning": "ලුණුවිල", "category": "plant" },
  { "word": "නාලිකාපිණ්ඩි", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "නාලිකේර", "meaning": "පොල්", "category": "plant" },
  { "word": "නාලින්දා", "meaning": "සැවැන්දරා", "category": "plant" },
  { "word": "නාලිය", "meaning": "බුලත්", "category": "plant" },
  { "word": "නාලිමනිපු", "meaning": "සෙන්දිරික්කා", "category": "plant" },
  { "word": "නාවිහය", "meaning": "නාගස", "category": "plant" },
  { "word": "නාවි", "meaning": "වච්චනාවි, කරල්සැබෝ", "category": "plant" },
  { "word": "නාස", "meaning": "වක්නිය = පසුරුතලා = දිවි පසුරු", "category": "plant" },
  { "word": "නාසිකා රෝගය", "meaning": "පීනස", "category": "symptom" },
  { "word": "නාසිරාවොලෙලෙ", "meaning": "වේලා ගස්", "category": "plant" },
  { "word": "නාහිකී", "meaning": "තැල්ල", "category": "plant" },
  { "word": "නාළිකේර", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "නාලිබගන්දුර", "meaning": "රෝග විශේෂයක්", "category": "symptom" },
  { "word": "නාළිරූප", "meaning": "නහර කැක්කුම", "category": "symptom" },
  { "word": "නාළිරෝග", "meaning": "විෂ ගඩු රෝග", "category": "symptom" },
  { 
    "word": "නැටව", 
    "meaning": "නැටවි ගස. සුදු පාට කඳකින් යුත් අඩි සියයක් පමණ උසට වැවෙන මේ ගසේ කොළ හැඩහුරු කමින් මකුල්ල කොළ වලට සමානය. ප්‍රමාණයෙන් ඊට වඩා විශාලය. මේ කොළ දිග-පළල අඟල් 7 x 2 1/2 ක් පමණ ඇත. කරමක පුවක් ගෙඩි පමණ වූ මේ ගසේ ගෙඩි පැසුන විට නාවාගෙඩි මෙන් හතරට පැලී වැටෙයි. පුපුරා වැටෙන මේ ගෙඩි කට හාරමක රසයකිනුත්, කරාබුනැටි සුවඳට සමාන සුවඳකිනුත්, මත් වන ගතියකිනුත් යුක්ත යි. ගැමියෝ මේ ලෙලි සහ ගසේ පොතු බුලත් විට සුගන්ධවත් කිරීමට හා දුම් කොළ වෙනුවට ත් කති. පරික්ෂණයකට භාජන කළහොත් මේ ගස් වර්ගයෙන් සුවඳ ද්‍රව්‍ය හා නිද්‍රාජනක ඖෂධ වගී පෙරා ගත හැකි බැව් පෙනේ. ගස් අතරින් මේ ගස මතු වී පෙනෙ යි. අනිත් ගස් වලට වඩා උසින් කරටිය සිටීම මේ ගසේ ස්වභාවය නිසයි. එසේම මිනී යුත් අතරින් වඩා උස් ව පෙනෙන මිනිසුන්ට නැටව දිග යයි ගැමියන් අතර පවත්නා ප්‍රවාදය නැටව ගස ක් කැලය න් අතර පවත්නා ස්වභාවය අනුව පවතින්නකි.", 
    "category": "plant" 
  },
  { "word": "නැටි", "meaning": "නටු", "category": "plant" },
  { "word": "නැටුව / නැටුඹ / නැටුම", "meaning": "නාලිය=පත හතර=කාල හතර", "category": "treatment" },
  { "word": "නැටුඹ හතර", "meaning": "ලාස", "category": "treatment" },
  { "word": "නැබ", "meaning": "නාභිය", "category": "treatment" },
  { "word": "නැඹුසු", "meaning": "ලුණුවරණ", "category": "plant" },
  { "word": "නැරල්", "meaning": "පොල්", "category": "plant" },
  { "word": "නැලිහෙල්", "meaning": "පොල්තෙල්", "category": "treatment" },
  { "word": "නැලිය", "meaning": "පලම් 16", "category": "treatment" },
  { "word": "නැවුරුක", "meaning": "කොළොම්, කෝන්", "category": "plant" },
  { "word": "නැහ", "meaning": "නාසය", "category": "treatment" },
  { "word": "නිඃසාර", "meaning": "කිනිහිරියා ගස", "category": "plant" },
  { "word": "නිඃශ්‍රීව", "meaning": "බතින් පෙරාගත් කාඩි", "category": "treatment" },
  { "word": "නිඃස්නේහා", "meaning": "අගස්ත, බතින් පෙරා කාඩි", "category": "treatment" },
  { "word": "නිඃසා", "meaning": "කෙසෙල්, ගැට නිවුල්", "category": "plant" },
  { "word": "නිඃස්‍රැති", "meaning": "යොන්හිඳි, ගැටනිවුල්, කෙසෙල්", "category": "plant" },
  { "word": "නික්කුවි", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "නික්ඛ", "meaning": "රත්රන්", "category": "treatment" },
  { "word": "නිකුහාතක", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "නික", "meaning": "පසළොස් කලඳ, නික ගස", "category": "plant" },
  { "word": "නිකඅඹු", "meaning": "නිකහඹු, (නිකකැඳ)", "category": "treatment" },
  { "word": "නිකපත්‍ර", "meaning": "නික කොළ, පතොක්", "category": "plant" },
  { "word": "නිකා", "meaning": "සමූහය", "category": "plant" },
  { "word": "නිකිඟුරා", "meaning": "නික, ඉඟුරු දෙවර්ගය", "category": "plant" },
  { "word": "නිකුඤ්ජක", "meaning": "හොමුවඟු", "category": "plant" },
  { "word": "නිකුම්භ", "meaning": "දත්ත, මහදත්ත, ත්‍රස්තාවාලු, වතුක්, සෙන්දිරික්කා", "category": "plant" },
  { "word": "නිකේටක", "meaning": "ගල්පියල්", "category": "plant" },
  { "word": "නිග්ගුණ්ඩි", "meaning": "නික", "category": "plant" },
  { "word": "නිඝණ්ඩු", "meaning": "නුගගස", "category": "plant" },
  { "word": "නිගණ්ඩක", "meaning": "මිදෙල්ල", "category": "plant" },
  { "word": "නිවුල", "meaning": "මිදෙල්ල, දියකොළොම්, ඇඹුල්වේ", "category": "plant" },
  { "word": "නිප්පිරි", "meaning": "උබැත්ත", "category": "plant" },
  { "word": "නිප්පලවාක්‍ෂ", "meaning": "මිදෙල්ල ගස", "category": "plant" },
  { "word": "නිපරදල", "meaning": "දේවදාර ගස", "category": "plant" },
  { "word": "නිපරලොහ", "meaning": "ලෝකඩ", "category": "treatment" },
  { "word": "නිච්චා", "meaning": "ඇටිවේරිය", "category": "plant" },
  { "word": "නිටොල්", "meaning": "නිවුල් ගස", "category": "plant" },
  { "word": "නිත්‍යපුෂ්ප", "meaning": "ගල්පියල්", "category": "plant" },
  { "word": "නිතම්බ", "meaning": "රත්කිහිරිය", "category": "plant" },
  { "word": "නිතනි", "meaning": "පණිරස", "category": "treatment" },
  { "word": "නිදින්ධා", "meaning": "කටුවැල්බටු, එත්සාල්", "category": "plant" },
  { "word": "නිදින්ධි", "meaning": "කටුවැල්බටු, තිබ්බටු", "category": "plant" },
  { "word": "නිදින්ධිකා", "meaning": "කටුවැල්බටු, තිබ්බටු", "category": "plant" },
  { "word": "නිදිදාරු මුදියන්සේ", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "නිද්‍රා", "meaning": "පියපල", "category": "plant" },
  { "word": "නිද්‍රායි", "meaning": "බිම්කොසඹ", "category": "plant" },
  { "word": "නිද්‍රානාගක", "meaning": "කෝපි", "category": "plant" },
  { "word": "නිද්‍රාඵල", "meaning": "බටුගෙඩි", "category": "plant" },

  // --- පිටුව 275 & 276 (නියගලා සම්පූර්ණ විස්තරය) ---
  { "word": "නිද්‍රාරි", "meaning": "බිම්කොසඹ", "category": "plant" },
  { "word": "නිද්‍රාව", "meaning": "හෙළ බටු", "category": "plant" },
  { "word": "නිවුලා", "meaning": "දුදු", "category": "plant" },
  { "word": "නිබන්ධ", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නිම්නජාත", "meaning": "කටුවෙළඟ", "category": "plant" },
  { "word": "නිම්", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නිඹ / නිම්බක", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නිම්බතරු", "meaning": "කොසඹ, එරබදු", "category": "plant" },
  { "word": "නිම්බපිනා", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නිම්බවිප්", "meaning": "කිරිපළුගස, කොසඹගස", "category": "plant" },
  { "word": "නිම්බුකා", "meaning": "දෙසි", "category": "plant" },
  { "word": "නිමල", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "නිමලා", "meaning": "සවින්දව", "category": "treatment" },
  { "word": "නිම්පිනා", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නිමුල", "meaning": "මුවකිරිය", "category": "plant" },
  { "word": "නිමේග", "meaning": "එළ කරල්සැබෝ", "category": "plant" },
  { "word": "නිමේනජාත", "meaning": "කටුවෙළඟ", "category": "plant" },
  { "word": "නිමොක්", "meaning": "සර්ප හැවය", "category": "treatment" },
  { "word": "නිබ", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නිබරු", "meaning": "සල්ගස", "category": "plant" },
  { "word": "නිය", "meaning": "දිවි පහුරු නෝ නිය ගස් = (නිය, කැමුණිය ය යි වගී දෙකකි.) නිය ග්ලේෂම නාශක ඖෂධයකි. නියමල් හා ගස් පතුරු ගලවා ලබා ගන්නා නියබඩ බුලත්විට රසවත් කිරීමට අමතර ද්‍රව්‍යයක් වශයෙන් ගනිති. ඒ වගියේ වන ගත (කැළෑ) වගියට කාල (වල්) නිය යයි කියති.", "category": "plant" },
  { 
    "word": "නියගලා", 
    "scientific": "Gloriosa Superba",
    "meaning": "නියඟලා - ලියනඟලා වැල්. නියඟලා යන නාමයෙන් ගම්වාසීන් අතර ප්‍රසිද්ධ ලියනඟලා ඉතා ශෝභාමත් වැලකි. උල් වූ අග ඇති තද නිල් පැහැයෙන් යුත් කොළ ත්, ගෝනුසු මල් වලට මඳක් සමාන තද ගිනි පැහැයෙන් යුත් ඊට සරිලන මල් පොකුරු ත්, නිසා මෙහි ශෝභාව වැඩි වෙ යි. ගස් මුදුන් වල පිපී තිබෙන මේ වගියේ රත්පාට මල් බොහෝ දුරට මුවද පැහැ දිලව පෙනෙ යි. එ හෙ ත් මෙය වස වර්ගයකි. මේවායේ අල ලාදුරු, උපදංශ (පරංගි) ඇතුළු කල් ගිය තුවාල (වණ) වලට හා හිස උඳු ගොව්වා කෑමට ත්, සර්ප විෂටත් ගන්නා ඖෂධ යෝග වලට එකතු කරති. දරුවන් බිහි වීම හෝ වැදූමස් වැටීම පමා වී වේදනා ගෙන දෙන අවස්ථාවන්හි මේ නියඟලා අල අඹරා දෙපතුලෙහි හෝ යටිබඩෙහි ගෑමට වහා ප්‍රසූතිය හා වැදූමස් වැටීම ත් සිදු වෙ යි.\n\n**වැරදී නියඟලා අල කැවෙන හැටි**\nකෑමට ගන්නා කිරිතල නමැති අල වර්ගය ත් මේ නියඟලා අල ත් ප්‍රමාණයෙන් හා පෙනුමෙන් සමාන ය. දෙවර්ගයේ ම අල හට ගන්නේ වැලේ මුලින් අඩි හයක් පමණ විහිදි ගිය තටු වල ය. පාවාල අල ගට ගැන්ම මෙනි. එම නිසා කිරිතල වැල් අසල නියඟලා වැල් තිබුනොත් කිරිතල ඉදිරීමේ ප්‍රවේසමෙන් කළ යුතු ය. වැල්වල සිට දුරින් තිබෙන නවුල අල ඉදිරීමේ දී මාරු විය හැකි හෙයිනි. ගිනිකලය යි වරදවා නියඟලා අල උදුරා ගෙනැවිත් තම්බා කෑම නිසා අනුරාධපුරය පළාතේ රජ වී ඝන මරණ සංඛ්‍යාව ද ස්වල්ප නො වේ.", 
    "category": "plant" 
  },
  { "word": "නියමින", "meaning": "කොසඹ", "category": "plant" },
  { "word": "නියබලාව", "meaning": "(නොපිසු අඹුල් හෝද්ද=ගොහිහෝද්ද හෝ පෑගිය)", "category": "treatment" },
  { "word": "නියඳ", "meaning": "අන්නාසි කොළ සමාන කටු නැති කුඩා ගසක්. (කොළ උල් වූ ද, නුවූ ද නියඳ වගී දෙකකි)", "category": "plant" },
  { "word": "නියසාක", "meaning": "සක්නැබ", "category": "plant" },
  { "word": "නිගීත පුෂ්පී", "meaning": "හිඹුල් මල්, කැල මල්", "category": "plant" },
  { "word": "නිර්ගුණ්ඩ", "meaning": "නික, සේපාලිකා, කළු තලා", "category": "plant" },
  { "word": "නිර්ජරා", "meaning": "කවුඩු උඩැත්ත, කවුඩු කැකිරි, රසකිඳ, බිම්නෙල්, ඌරල", "category": "plant" },
  { "word": "නිර්ජල", "meaning": "වියලි දේ, මෝරු", "category": "treatment" },
  { "word": "නිර්දගන", "meaning": "මුරුවා වැල්", "category": "plant" },
  { "word": "නිර්දව", "meaning": "වියලිදේ", "category": "treatment" },
  { "word": "නිර්භන්සර", "meaning": "ලාක්‍ෂා, ලාකඩ", "category": "treatment" },
  { "word": "නිර්මල", "meaning": "කතේරු, (අලරිය) ගුගුල්, මිනිරන්, සවින්දව, පුද්ඝලමල්", "category": "treatment" },
  { "word": "නිමලි", "meaning": "පික්මැලි, ඉඟිනි, කඩල", "category": "plant" },
  { "word": "නිමාල්‍ය", "meaning": "පුද්ඝලමල්", "category": "plant" },
  { "word": "නිර්මුල", "meaning": "මුවකිරිය", "category": "plant" },
  { "word": "නිමෝක", "meaning": "නයිසැවය", "category": "treatment" },
  { "word": "නිමෝවන", "meaning": "නයිසැවය", "category": "treatment" },
  { "word": "නියන්‍යාග", "meaning": "නිඹුල්මැලියම්, හිඹුල්ලාටු, කොසඹ", "category": "plant" },
  { "word": "නියන්‍යාසගත", "meaning": "විලිකුම් ගෙඩි", "category": "plant" },
  { "word": "නියන්‍යාගමාලක", "meaning": "කොසඹ රුක", "category": "plant" },
  { "word": "නිරයසූල", "meaning": "ලාබු, කසාය වගී", "category": "treatment" },
  { "word": "නිර්ලොහා", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "නිර්වාහ", "meaning": "හෙළ කරල් සැබෝ", "category": "plant" },
  { "word": "නිර්වෙස", "meaning": "කොකුම්", "category": "plant" },
  { "word": "නිරවකංචි", "meaning": "ඇඹුල්", "category": "plant" },
  { "word": "නිරස", "meaning": "වියලි දේ", "category": "treatment" },
  { "word": "නිරසානුර", "meaning": "ලුණුවිල", "category": "plant" },
  { "word": "නිරාම", "meaning": "කෝන්, කොබු", "category": "plant" },
  { "word": "නිරාමය", "meaning": "ලෙඩින් මිදුනේ", "category": "symptom" },
  { "word": "නිරාමාව", "meaning": "දිවුල්", "category": "plant" },
  { "word": "නිරාමිස", "meaning": "දිවුල්", "category": "plant" },
  { "word": "නිරාහි", "meaning": "උබැත්ත", "category": "plant" },

  // --- පිටුව 277 & 278 (නිටුල් සහ නිල් ඇවරිය) ---
  { "word": "නිරික්ෂි", "meaning": "තෙලඹු", "category": "plant" },
  { "word": "නිර්කර්ණිකා", "meaning": "මහමිදි", "category": "plant" },
  { "word": "නිරික්‍ෂුවි", "meaning": "ඇඹුල්වේ", "category": "plant" },
  { "word": "නිරිලපලා", "meaning": "තිරිපලා", "category": "plant" },
  { "word": "නිරිවංක්‍ෂවි", "meaning": "ඇඹුල්වේ", "category": "plant" },
  { "word": "නිරෝචක", "meaning": "රුකඟුණ", "category": "plant" },
  { "word": "නිරෝදන", "meaning": "කාඩි", "category": "treatment" },
  { "word": "නිල්", "meaning": "බෙලිගස, සෙවෙල්", "category": "plant" },
  { "word": "නිල්කටා", "meaning": "මෝණරු", "category": "plant" },
  { "word": "නිල්ගිරිනිල්ල", "meaning": "නිල්වැල්ලා වැල්, ගල්වල හෝ ලොකු ගස්වල පතුරු අල්ලා ගෙන වැවෙන නිල් පාට කඳ හා නිල් පාට රවුත් කොළ ඇති බීජ සහිත වැල් වර්ගයක්. මෙය මුඛ රෝග(පිළිකා) වලට ගෑමට ගනිති.", "category": "plant" },
  { "word": "නිල්මැලි", "meaning": "බෙලිගස", "category": "plant" },
  { "word": "නිල්ලකොක්කෝ", "meaning": "ගස්අඟුණ", "category": "plant" },
  { "word": "නිල්වැල්ලා වැල්", "meaning": "නිල්ගිරිනිල්ල", "category": "plant" },
  { "word": "නිලපානෙ", "meaning": "ඌරල", "category": "plant" },
  { "word": "නිලයා", "meaning": "සුළුබැබිල", "category": "plant" },
  { "word": "නිලවරි", "meaning": "කටරොලු", "category": "plant" },
  { "word": "නිලවෙම්පු", "meaning": "බිම් කොසඹ", "category": "plant" },
  { "word": "නිලිපුල් / නිලිබ / නිලුපුල්", "meaning": "නිල්මානෙල්", "category": "plant" },
  { "word": "නිවුචු", "meaning": "වී කුඩු", "category": "treatment" },
  { "word": "නිවෙස්කල්", "meaning": "ඇසිලිය හෙලන කාලය", "category": "plant" },
  { "word": "නිශ්වලා", "meaning": "ශාලිපර්ණී", "category": "plant" },
  { "word": "නිශා", "meaning": "කසා, කහ", "category": "plant" },
  { "word": "නිශාඛ්‍ය", "meaning": "එන්සාල්, මහ එන්සාල්", "category": "plant" },
  { "word": "නිශාවර", "meaning": "හිඟුරුපියලි, හණගස, හරංකහ", "category": "plant" },
  { "word": "නිශාවරි", "meaning": "අරණකසා (හරන්කහ)", "category": "plant" },
  { "word": "නිශාද", "meaning": "අඹරන් ගල", "category": "treatment" },
  { "word": "නිශාදුර", "meaning": "වතුවැල්, (බාත්වැල්) දරා ගල (උඩ ඇඹරුම් ගල)", "category": "treatment" },
  { "word": "නිශාපනි", "meaning": "කපුරු, හිඟුරුපියලි", "category": "plant" },
  { "word": "නිශාපුෂ්ප", "meaning": "සේපාලිකා මල්", "category": "plant" },
  { "word": "නිශායාසි", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "නිශාවර", "meaning": "ජටාමකුට", "category": "plant" },
  { "word": "නිශාහ්ව", "meaning": "කසා, කසාඅල", "category": "plant" },
  { "word": "නිශ්‍රේණි", "meaning": "යොන්හිඳි", "category": "plant" },
  { "word": "නිෂ්ක", "meaning": "රත්රන්, තුන් කලඳ", "category": "treatment" },
  { 
    "word": "නිල් නිටුල්", 
    "scientific": "Plumbago Capensis",
    "meaning": "රත් නිටුල්, එළ නිටුල්, නිල් නිටුල් යයි නිටුල් වර්ග තුනකි. මල් රත් වර්ගයට රත් නිටුල් කියා ද, මල් සුදු වර්ගයට එළ නිටුල් කියා ද, මල් නිල් වර්ගයට නිල් නිටුල් කියා ද ව්‍යවහාර කරති. ඖෂධ වශයෙන් වැඩිපුර ගන්නේ මේවායේ මුල් ය.", 
    "category": "plant" 
  },
  { 
    "word": "රත් නිටුල්", 
    "meaning": "කාස-උණ-අතිසාර-අගස්-මන්දග්නිය ආදි රෝග සඳහා අවශ්‍ය කෂාය-අරිෂ්ට-ආසව-ගුලි-කල්ක-ලේහ ආදි ශරීරගත කරන ඖෂධ වර්ග පිළියෙළ කිරීමට ලංකාවේ වැඩි වශයෙන් ගන්නේ රත් නිටුල්ය. එහෙත් මේ සඳහා ඉන්දියාවේ වැඩිපුර ගන්නේ ගිනිකාර ගතියෙන් අඩු එළ නිටුල් ය.", 
    "category": "plant" 
  },
  { 
    "word": "එළ නිටුල්", 
    "meaning": "කුෂ්ඨ - ඉදිමුම් ආදිය සඳහා පිටත ගෑමට ඉන්දියාවේ පාවිච්චි කරන්නේ අධික ගිනිකාර කමින් යුත් රත් නිටුල් ය. එහෙත් මේ සඳහා ලංකාවේ ගන්නේ එළ නිටුල් ය. එළ නිටුල් ගව රෝග(හරක් ලෙඩ) පිළිබඳ බෙහෙත් වට්ටෝරු වල හා වෙනත් අපේ වට්ටෝරු වෙද පොත්වලද ඇතුළත්ව තිබේ. මේ නිටුල් දෙවර්ගයම ගුණයෙන් බොහෝ දුරට සමාන ය. වෙනසකට ඇත්තේ එළ නිටුල් වලට වඩා රත් නිටුල් වල අධික ගිනිකාර බව පමණකි.", 
    "category": "plant" 
  },
  { 
    "word": "නිල් නිටුල් දියවැඩියාවට", 
    "meaning": "නිල් නිටුල් සාරය බහු මූත්‍ර දෝෂය (දියවැඩියාව) ට ප්‍රත්‍යක්‍ෂ ඖෂධයකි. අනුපාත වශයෙන් ගිතෙල් දමා නිල් නිටුල්මුල් කෂාය හෝ මේ මුල් මිශ්‍ර අරිෂ්ට වර්ග හෝ සකස් කොට දින පතා පාවිච්චි කිරීමෙන් දියවැඩියාව සුව වෙයි.", 
    "category": "treatment" 
  },
  { 
    "word": "නිල් ඇවරිය", 
    "scientific": "Indigofera Tinctoria",
    "meaning": "නිලිනි. අඩි දෙකහමාරකට වඩා උසට නොවැවෙන මේ පැලෑටියේ කොළ තද නිල් පාටකින් යුක්තය. හැඩහුරුකමින් සෙනෙහ කොළ වලට සමානය මේ...", 
    "category": "plant" 
  }
];





