// data_241_250.js - පිටු 241 සිට 250 දක්වා සියලුම වචන
const data_extra_241_250 = [
  // --- පිටුව 241 ---
  { "word": "දක්ඛායණී", "meaning": "දත්ත, මහදත්ත", "category": "plant" },
  { "word": "දක්ඛිණාවර්ත", "meaning": "වතුසුද්ද", "category": "plant" },
  { "word": "දක්ඛිණාත්‍ය", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "දගියවැල්", "meaning": "පුසුල් වැල්", "category": "plant" },
  { "word": "දඟපු", "meaning": "සුළු කරඹ", "category": "plant" },
  { "word": "දායා", "meaning": "ගොකටු, (නෙරෙවි)", "category": "plant" },
  { "word": "දයිම", "meaning": "දෙළුම්", "category": "plant" },
  { "word": "දයිම්සාර", "meaning": "දෙළුම්", "category": "plant" },
  { "word": "දයිම", "meaning": "දෙළුම්, එන්සාල්", "category": "plant" },
  { "word": "දයිමදක්ඛිණ", "meaning": "භාජනය", "category": "treatment" },
  { "word": "දයිමපුෂ්පිකා", "meaning": "වල් එරබදු ගස, දෙළුම් ගස", "category": "plant" },
  { "word": "දයිමපුෂ්ප", "meaning": "දෙළුම් මල්, එරබදු, රත්නිවුල්", "category": "plant" },
  { "word": "දයිමපුෂ්පක", "meaning": "වල් එරබදු", "category": "plant" },
  { "word": "දයිමි", "meaning": "දෙළුම්", "category": "plant" },
  { "word": "දයිම්පුෂ්ප", "meaning": "එරබදු ගස", "category": "plant" },
  { "word": "දයිම්සාර", "meaning": "දෙළුම් ගස", "category": "plant" },
  { "word": "දයිවාහස", "meaning": "බක්මී, බකිනි, කොළොම්", "category": "plant" },
  { "word": "දාරි", "meaning": "දෙළුම්", "category": "plant" },
  { "word": "දතනී", "meaning": "මසිල", "category": "plant" },
  { "word": "දතකුසුම්", "meaning": "මසිල මල්", "category": "plant" },
  { "word": "දත්‍රී", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "දත්‍රිමණ්ඩ", "meaning": "තිපල් (අරළු, බුළු, නෙල්ලි)", "category": "plant" },
  { "word": "දපපු", "meaning": "රොටී", "category": "treatment" },
  { "word": "දනන", "meaning": "දමනක වෘක්ෂය", "category": "plant" },
  { "word": "දනති", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "දනහිය", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "දනගන්ධී", "meaning": "රක්අත්තන ගස", "category": "plant" },
  { "word": "දන විභූත", "meaning": "තුවරලා", "category": "plant" },
  { "word": "දනවප්‍රිය", "meaning": "නාගවල්ලී බුලත්", "category": "plant" },
  { "word": "දනිය වැල්", "meaning": "පුහුල් වැල්", "category": "plant" },
  { "word": "දනායක", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "දම්බි", "meaning": "වළුවැල්", "category": "plant" },
  { "word": "දම", "meaning": "සීන්මිදි", "category": "plant" },
  { "word": "දමන", "meaning": "දමනක රුක", "category": "plant" },
  { "word": "දමිලි", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "දධත්පුෂ්ප", "meaning": "වක්නිය (දිවිපහුරු)", "category": "plant" },
  { "word": "දද්දුර", "meaning": "ලාකඩ", "category": "treatment" },
  { "word": "දර්ව", "meaning": "නිඹුල්, ගැටනිඹුල්, රසඳුන්, දේවදාර, කසා, දාරුහරිදා", "category": "plant" },
  { "word": "දර්විකා", "meaning": "සමුද්‍රභව - රසාංජන", "category": "treatment" },
  { "word": "දර්විකා", "meaning": "නිඹුල්, ගැටනිඹුල්, ගොකටු", "category": "plant" },
  { "word": "දර්විරසෝත්භව", "meaning": "රසාංජන - (රසඳුන්)", "category": "treatment" },
  { "word": "දර්විපත්‍රිකා", "meaning": "ගොකටු", "category": "plant" },
  { "word": "දර්විභේද", "meaning": "කපුරුකහ", "category": "plant" },
  { "word": "දර්වි", "meaning": "දාරුහරිදා", "category": "plant" },
  { "word": "දර්විකාභදෝද්භව", "meaning": "රසඳුන්", "category": "treatment" },
  { "word": "දශී", "meaning": "බුව", "category": "plant" },
  { "word": "දශනි", "meaning": "ගුරුවැට", "category": "treatment" },
  { "word": "දර", "meaning": "කෛවර්තමුස්තක, වම්මුතු", "category": "plant" },
  { "word": "ද්රකා", "meaning": "සිරිතේ මසන්", "category": "plant" },
  { "word": "ද්රගන්තා", "meaning": "නියඳ අල, සුවඳැති අල", "category": "plant" },
  { "word": "ද්රණ", "meaning": "ඉඟිනි ගස", "category": "plant" },
  { "word": "දර්ද", "meaning": "රසදිය, වච්චනාවි, සාදිලිංගම්", "category": "treatment" },
  { "word": "දර්පලා", "meaning": "බිම්නෙල්ලි (පිටවක්කා)", "category": "plant" },
  { "word": "දරා", "meaning": "දේවදාර, වෙනිවැල් (බාත්වැල්) උගුරැස්ස, දාරුහරිදා", "category": "plant" },
  { "word": "දරාකා", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දරාකදලි", "meaning": "ඇටකෙසෙල්", "category": "plant" },
  { "word": "දරාමිණී / දරාවිවර්ණිකා", "meaning": "කුරුඳු", "category": "plant" },
  { "word": "දරාණී", "meaning": "රත්නිවුල්, ඉඟිනි ඇට", "category": "plant" },
  { "word": "දරානීර", "meaning": "මහනුග", "category": "plant" },
  { "word": "දරානිසා", "meaning": "දාරුහරිදා", "category": "plant" },
  { "word": "දරාපුත්‍රිකා", "meaning": "පෙරුම්කායම්", "category": "treatment" },
  { "word": "දරාපත්‍රී", "meaning": "සත්තාහිබ්බු", "category": "plant" },
  { "word": "දරාපීතා", "meaning": "දාරුහරිදා", "category": "plant" },

  // --- පිටුව 242 ---
  { "word": "දරාහෘදා", "meaning": "දේවදාර", "category": "plant" },
  { "word": "දරාර්ජිත", "meaning": "වගපුල්, බාත්වැල්", "category": "plant" },
  { "word": "දරාසාර", "meaning": "සඳුන්", "category": "plant" },
  { "word": "දරාසිතා", "meaning": "කුරුඳුපොතු", "category": "plant" },
  {
    "word": "දාරුහරිදා (දුරුහිරිදා)",
    "meaning": "මේ වෙනුවට අපේ රටේ ගන්නේ වෙනිවැල් (වෙනිවැල) ය. දාරුහරිදා ලතාව විශේෂයක් නොව වෘක්‍ෂ විශේෂයකි. එය තික්ත, කටුක, උෂණ ගුණයෙන් යුක්ත වණ, ප්‍රමේහ, දද, විසර්ප, එහි ගත දෝෂ, විෂ, කන් රෝග හා ඇස් රෝග නසන ද්‍රව්‍යයකි. මේ බෙහෙත වෙනුවට ප්‍රතීනිධි වශයෙන් ගන්ට නියම කර තිබෙන කහ අල වලට වඩා වැල් වගියක් වුවත් වෙනිවැල් සමාන බැවින් වැස් පරික්‍ෂාවෙන් හැරුව විකා බැලීමෙන් වුවද ප්‍රකට වන්නකි. දාරුහරිදා මෙන්ම වෙනි වැල්ද පිහිටස්ම හා ග්‍රන්ථි රෝග සමනයෙහි සමාන ක්‍රියාකාරීත්වයක් ඇති බව පරික්‍ෂාවෙන් ම දනිමු. මේ රටේ අවුරුදු එක් දහස් පන්සියයකට නොඅඩු කාලයක සිට දාරුහරිදා වලට වෙනි වැල් ම නියම කර තිබෙන්නේ විධිමත් පර්යේෂණයකින් පසුව බවට කිසිම සැකයක් නැත. දාරුහරිදා හා වෙනිවැල්වල ඇත්තේ සමාන ගුණයකි. ප්‍රතිනිධි වශයෙන් නියම කළ කහ අල වංශයේ එ වැනි සමානකමක් නැත.",
    "category": "plant"
  },
  { "word": "දලඟකිරා", "meaning": "කන්මිසකුරු (කතෛසියා හතුරු)", "category": "treatment" },
  { "word": "දලිම", "meaning": "දෙළුම්, දේවදාලි ලතාව", "category": "plant" },
  { "word": "දලි", "meaning": "දෙළුම්, දේවදාලි ලතාව", "category": "plant" },
  { "word": "දුව", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "දවන", "meaning": "කිහිරි", "category": "plant" },
  { "word": "දවනී", "meaning": "අස්වැන්න", "category": "plant" },
  { "word": "දවිබක", "meaning": "හිඟුරුපියලි", "category": "plant" },
  { "word": "දගපුර", "meaning": "මහ කලාඳුරු, කොට්ටවියා මුරු", "category": "plant" },
  { "word": "දස", "meaning": "ශාරද අරටු (සිරිවට්ටු)", "category": "plant" },
  { "word": "දසකුටජ්", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "දශි", "meaning": "කටුකරඬු, නීල්කටුකරඬු, නිල් ගිරිනිල්ල, මුවැන්න, කොළුම්, බූරැල්ල ගස", "category": "plant" },
  { "word": "දශිකා", "meaning": "නිල් ගිරිනිල්ල, නිල් කටුකරඬු", "category": "plant" },
  { "word": "දශිකුරුණ්ඩක", "meaning": "නිල් කටුකරඬු", "category": "plant" },
  { "word": "දශක", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "දශකාතාව", "meaning": "දේවදාර වෙසෙසක්", "category": "plant" },
  { "word": "දසන්නි", "meaning": "කෙළවදම", "category": "plant" },
  { "word": "දසධාරා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "දසනාසිනී", "meaning": "කෙළදම", "category": "plant" },
  { "word": "දසනීගෝවා", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "දසසොස්නී", "meaning": "නිඹුල්", "category": "plant" },
  { "word": "දසහන", "meaning": "සිළු, හෙළ පඹුරු", "category": "plant" },
  { "word": "දසහනී", "meaning": "හෙළ දඹ", "category": "plant" },
  { "word": "දසහරණ", "meaning": "සැවැන්දරා", "category": "plant" },
  { "word": "දසහරා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "දශිනී", "meaning": "හෙළ පඹුරු", "category": "plant" },

  // --- පිටුව 243 ---
  { "word": "දසිනරා", "meaning": "(දඹුදින්තරා) නිදිකුම්බා, වැල්මදට", "category": "plant" },
  {
    "word": "දන්තී (දන්ති)",
    "scientific": "Baliospermum Montanum",
    "meaning": "දන්තී වගී දෙකකි. එයින් එක වගියක කොළ වල ගිරිමිනා තලයක මෙන් වටේට දත් තිබේ. කොළ ප්‍රමාණයෙන් හා හැඩහුරු කමින් ඉල්ල කොළ වලට සමානය. කඳේ කොළ බෙදී යන තැන් වලින් අඟල් හතරක් පමණ දිගට ඇදී යන පොල් ඉරටු පමණ නඩුවල කඩුවල මල් වැනි කුඩා මල් හට ගනී. මේ පාලා විශේෂය කඩල නැතහොත් කුඩා මෑ ඇටයක සා ආල වැනි අල තිබේ. මේ අල වාතාබාධ-ආමගුල-අතීසාර ආදී මඟත් රෝග සමූහයකට ම දෙන ඖෂධ යෝග සමග මිශ්‍ර කරති. ඉන්දියාවෙන් මෙහි ගෙනෙන්නේ චූර්ණ කරණ ලද මේ දන්තී වර්ගයේ පාරභපයකි. අනිත් වගිය ලංකාවේ පෙර සිට පැවත එන වර්ගයයි. ඒවායේ කොළ කපු කොළ වලට සමානය. මල් ප්‍රමාණයෙන් හා හැඩයෙන් නාපිරිත්ත මල් වැනිය. කරල් හා ඇට ද නාපිරිත්ත හෝ කපුකිනිස්ස කරල්වල ඇට වලට සමානය. රට (ඉන්දියාවේ) දන්තවල අල මිස ඇට නැත. එසේම ලංකාවේ වර්ගයේ ඇට මිස අල නැත. අල වෙනුවට ඇත්තේ කුඩා මුල් පමණකි. එම නිසා අල උවමනා වූ විට රට දන්තත් ඇට උවමනා වූ විට මෙරට දන්තත් පාවිච්චි කරන්ට සිදුවී තිබේ.",
    "category": "plant"
  },
  { "word": "දශුරා", "meaning": "අත්තන ගස", "category": "plant" },
  { "word": "දශිනිරිය", "meaning": "ලුණුවිල (බැමිනිරිය)", "category": "plant" },
  { "word": "දරගන්ධි", "meaning": "පලිඟු ගල", "category": "treatment" },
  { "word": "දර්ථානී", "meaning": "ගර්භණීය", "category": "treatment" },
  { "word": "දලි", "meaning": "අංකුරය, සමූහය, අලුත් නෙළුම්දලු", "category": "plant" },
  { "word": "දලිදිය", "meaning": "දලි වතුර", "category": "treatment" },
  { "word": "දලිපොතු", "meaning": "දල්ලන්ගේ පොතු", "category": "plant" },
  { "word": "දවාන", "meaning": "පලිඟු ගල", "category": "treatment" },
  { "word": "දගාලියගෙද", "meaning": "ගෙදපලා, පැලෑටි වර්ගයක්", "category": "plant" },
  { "word": "දක්ගුල්", "meaning": "සාදිලිංගම්", "category": "treatment" },

  // --- පිටුව 244 ---
  { "word": "දෑ", "meaning": "නිකිටි ගස, චීවවමාල", "category": "plant" },
  { "word": "දක්", "meaning": "අක දෙකක්", "category": "treatment" },
  { "word": "දනුරා", "meaning": "අත්තන ගස", "category": "plant" },
  { "word": "දා ඵල", "meaning": "සාදික්කා ගෙඩි", "category": "plant" },
  { "word": "දාපුප්", "meaning": "දෑසමන්, පීවව", "category": "plant" },
  { "word": "දාමාන", "meaning": "සමිඳු", "category": "plant" },
  { "word": "දාසප්", "meaning": "දෑසමන්, චීවවමාල", "category": "plant" },
  { "word": "දෑසමන්", "meaning": "දාසප්", "category": "plant" },
  { "word": "දික්නිබිය", "meaning": "නිරස්ස පල", "category": "plant" },
  { "word": "දික්තිටිය", "meaning": "හින් අක්මැල්ල", "category": "plant" },
  { "word": "දික්පල", "meaning": "ඇසල", "category": "plant" },
  { "word": "දිගුදල", "meaning": "වැටකේ", "category": "plant" },
  { "word": "දිගුනෙත්", "meaning": "බුළු", "category": "plant" },
  { "word": "දිඹර", "meaning": "මුදුපෙණ", "category": "treatment" },
  { "word": "දිදි", "meaning": "මදිව කිරි", "category": "treatment" },
  { "word": "දින්", "meaning": "ඉකිරිය (නිරමුල්ලිය)", "category": "plant" },
  { "word": "දින්ද", "meaning": "රණහුණ ගස", "category": "plant" },
  { "word": "දින්දය", "meaning": "රණහුණ", "category": "plant" },
  { "word": "දින", "meaning": "හුරල", "category": "plant" },
  { "word": "දිනකර", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිනකණී", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිනකාන්ට්", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිනප", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිනමණි", "meaning": "වරාගස", "category": "plant" },
  { "word": "දිනමනී", "meaning": "වරාගස", "category": "plant" },
  { "word": "දින රත්න", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිනිඳු", "meaning": "වරාගස", "category": "plant" },
  { "word": "දිනිසුරු", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිම්බ", "meaning": "දිම් බීජ", "category": "plant" },
  { "word": "දඹිඳු (දිම්බිජු)", "meaning": "දඹයන්ගේ බිත්තර හෝ මිරිස් ගස වැනි කුඩා ගසක සෑදෙන ගම්මිරිස් ඇට ප්‍රමාණ රත්පැහැති කුඩා ගෙඩි. (ඇට වර්‍ගයක්.) මෙයින් දිරියන්ගේ බිජු (බිත්තර) සංඥා ප්‍රබෝධනය සඳහා තලයට වාරු මැසි වශයෙන් ගති.", "category": "plant" },
  { "word": "දිඹුල්", "meaning": "උදුම්බර හෝ දිවුල්", "category": "plant" },
  { "word": "දිඹුල්මාලසි", "meaning": "දිවුල් ගැට හෝ අත්තික්කා ගැට (නොඉදුණ ගෙඩි)", "category": "plant" },
  { "word": "දිය", "meaning": "ප්‍රසුල්, ඉරිවේරිය", "category": "plant" },
  { "word": "දියගුරැල්ල", "meaning": "ගුරැල්ල (බුරැල්ල) ගස් වලට සමානකම ඇති කොළ-මල් හා ගෙඩි හට ගන්නා පුවක් සහිත සෙවෙල් වැල් වර්ගයක්.", "category": "plant" },
  { "word": "දියනිප්පිලි", "meaning": "(දියබුලත්) වර්ෂාව අධික හෝ නිතර දිය සිරාව ඇති ප්‍රදේශවල හටගන්නා පිළිස්සුණ තුවාල වලට ප්‍රත්‍යක්‍ෂ පාසැල් සිසුන් ගල්ලෑලි මැකීමට ද ගන්නා ඇඹුල් කර රස යන්තමින් යුත් දිය ගලන පලාවකි.", "category": "plant" },
  { "word": "දියදඹ", "meaning": "දඹ වර්‍ගයක්, බලුදම් ගස", "category": "plant" },
  { "word": "දියදෙළුම්", "meaning": "කිරල ගස", "category": "plant" },
  { "word": "දියනෙත්", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දියනිල්ල", "meaning": "එනම් කුඩා ගස", "category": "plant" },
  { "word": "දිය නොපාල හුණු", "meaning": "අළුහුණු (නොකැවුම් හුණු)", "category": "treatment" },
  { "word": "දියපරබල් (කුමනිකා)", "meaning": "මේ වර්ගයේ බර්වා රෝගය බෝ කරන්නේ කමින් සිටිතැයි යනු වෛද්‍ය මතයයි. මේවා බහුල වශයෙන් වැවී තිබෙන ප්‍රදේශ වල සර්වා රෝගය අධිකබව ද ප්‍රකටය.", "category": "plant" },
  { "word": "දියමිල", "meaning": "දිකිරි දිය", "category": "treatment" },
  { "word": "දියමැලි", "meaning": "දියපරබලා, දියසෙවෙල්, (මිසපුරා)", "category": "plant" },
  { "word": "දියමිදෙල්ල", "meaning": "මිදෙල්ල ගස", "category": "plant" },
  { "word": "දියයතුරා", "meaning": "ජල යන්ත්‍රය", "category": "treatment" },
  { "word": "දියවර්මිතර", "meaning": "දියමින්ත වැල", "category": "plant" },
  { "word": "දියවැඩියා", "meaning": "මධුමේහ රෝගය", "category": "symptom" },

  // --- පිටුව 245 ---
  { "word": "දියහබරල", "meaning": "මැල්ලුම සඳහා ඉතා රසැති ශීත ගුණයෙන් යුත් පලා වර්ගයකි. මේවායේ යුෂ රත්පිත් අධික අයගේ ප්‍රයෝජනය සඳහා හිඳින තෙල් වලට ද බෙහෙවින්ම ප්‍රයෝජනවත් ය.", "category": "plant" },
  { "word": "දිය හෙවිරිය", "meaning": "සෙවෙල් = දිය සෙවෙල්", "category": "plant" },
  { "word": "දිරානෝ", "meaning": "දිය හබරලිය", "category": "plant" },
  { "word": "දිලීපපු", "meaning": "උඳුපියලි", "category": "plant" },
  { "word": "දිව ශක්‍රිය", "meaning": "ජීවක, වෘෂභක, දෙවර්ගය", "category": "plant" },
  { "word": "දිව සුරු", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිවස කර", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිවාකණී", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "දිවාකර", "meaning": "වරා ගස", "category": "plant" },
  {
    "word": "දිවිපහුරු (දිවි අඩිය වැල්)",
    "scientific": "Ipomaea Pes-tigridis",
    "meaning": "වන් නිය. මේ වැල් වගියේ කොළ ඇඟිලි පහකින් යුක්තය. අඟල් තුන හමාරක් පමණ වට ප්‍රමාණයක් ඇති කොළ වල සිහින් බුවක් තිබේ. මේ කොළ හැඩහුරු කමින් දිවි අඩි වලට සමාන හෙයින් දිවි අඩි = (දිවි පහුරු = වතායුක්ත = වක් නිය) යන නාමයන් ව්‍යවහාර වන බව පෙනේ. මේ වැල්වල මදු මල් සමාන සුදු පාට මල් හටගනියි. මේ වැල් සහමුලයෙන් ගෙන කොටා මිරිකාගත් යුෂ විෂර බිබි විෂ ශරීර ගත වූ අයට පොවා නහස කර කැඳෙහි යෙදීමෙන් සම්පූර්ණ සුවය ලබාගත හැක. පිළිස්සීමෙන් හටගන්නා දිය බුබුළු වලට මේ කොළ යුෂ ගෑමෙනුත්, පිළිස්සීමෙන් හටගත් තුවාල වලට මේ කොළ අමුකහ සමග අඹරා ගෑමෙනුත් සුවය ලැබේ.",
    "category": "plant"
  },
  { "word": "දිවාතිසම", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "දිවාමණී", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිවාවසු", "meaning": "වරා ගස", "category": "plant" },
  { "word": "දිමිනක", "meaning": "දිවිපහුරු", "category": "plant" },
  { "word": "දිවි පියුරු", "meaning": "වතායුක්ත - පතුරු කලා (දිවිපහුරු)", "category": "plant" },
  { "word": "දිවබු", "meaning": "කලුවැල්ල, (කලවැල්)", "category": "plant" },
  { "word": "දිවුල්", "meaning": "දිවුල් ගස", "category": "plant" },
  { "word": "දිවුල්ලාබු", "meaning": "දිවුල් මැලියම්", "category": "treatment" },
  { "word": "දිව්‍ය", "meaning": "ලක්කෑල්ල, ගුගුල්, කරාබුනැටි, කුරුඳු, කොට්ටම්, සඳුන්, තලා ගස්, රසකිඳ", "category": "plant" },
  { "word": "දිව්‍යගන්ධ", "meaning": "ගෙන්දගම්, කුරුඳු, කරාබු නැටි, එන්සාල්", "category": "plant" },
  { "word": "දිව්‍යගන්ධා", "meaning": "මහ එන්සාල්", "category": "plant" },
  { "word": "දිව්‍ය මඤ්ජු", "meaning": "රන්වන් සඳුන්, කරාබු", "category": "plant" },

  // --- පිටුව 246 ---
  { "word": "දිව්‍ය වන්දන පුෂ්ප", "meaning": "කරාබු නැටි, වසාවාසි", "category": "plant" },
  { "word": "දිව්‍ය වන්දිත පුෂ්ප", "meaning": "කරාබු නැටි, වසාවාසි", "category": "plant" },
  { "word": "දිව්‍ය තුම්බි", "meaning": "ලබු වෙසෙසක්", "category": "plant" },
  { "word": "දිව්‍ය තෛපස", "meaning": "මුගුණවැන්න, බැමිනිරිය, (ලුණුවිල)", "category": "plant" },
  { "word": "දිව්‍ය තෛපා", "meaning": "ලුණුවිල", "category": "plant" },
  { "word": "දිව්‍ය පංචාමෘත", "meaning": "ගිතෙල්, එළකිරි, එළ දිකිරි, මීපැණි, හකුරු යන පස", "category": "treatment" },
  { "word": "දිව්‍යපුෂ්ප", "meaning": "කණේරු ගස", "category": "plant" },
  { "word": "දිව්‍යපුෂ්පක", "meaning": "අලරිය, ගැටතුඹ", "category": "plant" },
  { "word": "දිව්‍යපුෂ්පිකා", "meaning": "කණේරු, රතු මල් ඇති වරා", "category": "plant" },
  { "word": "දිව්‍යලතා", "meaning": "මුරුවා වැල", "category": "plant" },
  { "word": "දිව්‍යවාක්‍ෂ", "meaning": "මඳුර ගස", "category": "plant" },
  { "word": "දිව්‍යසාර", "meaning": "සල්", "category": "plant" },
  { "word": "දිව්‍යා", "meaning": "හාතාවාරිය, ලුණුවිල, රසකිඳ, තලා, හෙළ වැටකොළු, තිත්ත තැල්ල, අරළු", "category": "plant" },
  { "word": "දිව්‍යෞෂධී", "meaning": "රන්තන්තිරියල්, මනෝගිලා", "category": "plant" },
  { "word": "දිහි-දයි", "meaning": "දිකිරි", "category": "treatment" },
  { "word": "දී-දිකිරි", "meaning": "දී", "category": "treatment" },
  { "word": "දීඝ වණ්ට", "meaning": "තොවිල", "category": "plant" },
  { "word": "දීප", "meaning": "ඉරිවේරිය", "category": "plant" },
  { "word": "දීප්තිමත්", "meaning": "වරාගස", "category": "plant" },
  { "word": "දීන", "meaning": "කුවරලා මල", "category": "plant" },
  { "word": "දීපන-ලියනහලා, බක්මී, කොකුම්, දුදු, පෙරුම්කායම්", "meaning": "දීපන", "category": "treatment" },
  { "word": "දීපනා-කොලොම්, ලුණුවිල, බක්මී, ලියනහලා, මනෝසිල, ලාකඩ", "meaning": "දීපනා", "category": "treatment" },
  { "word": "දීපනාංශු-වරාගස", "meaning": "දීපනාංශු", "category": "plant" },
  { "word": "දීපාව්ව-ලාකිරි, ලාකඩ", "meaning": "දීපාව්ව", "category": "treatment" },
  { "word": "දීප්ති-ලාකිරි, ලාකඩ", "meaning": "දීප්ති", "category": "treatment" },
  { "word": "දීප්තිකාන්සස-කස්ටෝ (කාංචන ලෝහ)", "meaning": "දීප්තිකාන්සස", "category": "treatment" },
  { "word": "දීපස", "meaning": "කළුදුරු, අසමෝද, දුටුසතුටු (මොනර කුඩුම්බිය), සුදුදුරු, උළුවා, කොකුම්, රත්නිවුල්, ක්‍රිමිහන්තෘ", "category": "plant" },
  { "word": "දීපක", "meaning": "අසමෝද, දෙදුරු, මොනර කුඩුම්බිය", "category": "plant" },
  { "word": "දීපවල්ලී", "meaning": "අසමෝදගම්", "category": "plant" },
  { "word": "දීපසා", "meaning": "පිත්තිරි", "category": "plant" },
  { "word": "දීපකා", "meaning": "ඇත්තෝර ගස, නිඹුල්", "category": "plant" },
  { "word": "දීප කර්පූරප්", "meaning": "කපුරු", "category": "treatment" },
  { "word": "දීපනර", "meaning": "ගොරක ගස, පහන් ගස", "category": "plant" },
  { "word": "දීපන", "meaning": "කාද, රතු ලිපුනු, පෙරුම්කායම්, නෝර්, උටුසතුටු, රත්නිවුල්", "category": "treatment" },
  { "word": "දීපනී", "meaning": "අසමෝද, අරළු, දිය මින්ත", "category": "plant" },
  { "word": "දීපනීකාරකාරිකා", "meaning": "අරළු", "category": "plant" },
  { "word": "දීපනියා", "meaning": "ක්‍රිමිහන්තෘ, අසමෝද, සිහින් අසමෝද", "category": "plant" },
  { "word": "දීපන්‍යා", "meaning": "අසමෝදගම්, නිප්පිලි, සිවිය, නිඹුල්, සිද්ධිගුරු", "category": "plant" },
  { "word": "දීප පාදප", "meaning": "පහන් ගස", "category": "plant" },
  { "word": "දීපපුෂ්ප", "meaning": "සපු", "category": "plant" },
  { "word": "දීප මූලා", "meaning": "කවුපිල", "category": "plant" },
  { "word": "දීප වාක්‍ෂ", "meaning": "තලාර ගස", "category": "plant" },
  { "word": "දීපගබඩෘ", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "දීප සංඥක", "meaning": "නිඹුල් ගස", "category": "plant" },
  { "word": "දීපිකා", "meaning": "හාතාවාරිය, වදකහ", "category": "plant" },
  { "word": "දීප්ත", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "දීප්ති", "meaning": "නල්වැල්, රත්හැල්", "category": "plant" },
  { "word": "දීප්තිකා", "meaning": "සිහින් දුරු, (සුදුදුරු) බටගස, තේක්ක ගස", "category": "plant" },
  { "word": "දීප්තිගන්ධ", "meaning": "සිනියා ගස", "category": "plant" },
  { "word": "දීප්තිගණා", "meaning": "සිහින් දුරු, (සුදු දුරු)", "category": "plant" },
  { "word": "දීප්තිසංඥා", "meaning": "බිම්නල්", "category": "plant" },

  // --- පිටුව 247 ---
  { "word": "දීර්ඝකන්‍ධ", "meaning": "තියඹරා, මහ කැකිරි, ඌරල, බිමිතල්", "category": "plant" },
  { "word": "දීර්ඝකා", "meaning": "සකෘ ශාඛා", "category": "plant" },
  { "word": "දීර්ඝකිල", "meaning": "ගල්පිලල් රක්, රුකුගුණ", "category": "plant" },
  { "word": "දීර්ඝ කිලක", "meaning": "පුවඟු, ගසේ අංකුර, ගල් පියල්", "category": "plant" },
  { "word": "දීර්ඝකුලතා", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "දීර්ඝකැම්මේරියා", "meaning": "ඇල් වෙසෙසක්", "category": "plant" },
  { "word": "දීර්ඝගන්ධී", "meaning": "කස්තුරි, උරාලා සැටවිටි", "category": "treatment" },
  { "word": "දීර්ඝගන්ධා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "දීර්ඝ ග්‍රන්ථී", "meaning": "ගප්නිප්පිලි, සිවිය", "category": "plant" },
  { "word": "දීර්ඝගොමුළු", "meaning": "මහ තිරිඟු", "category": "plant" },
  { "word": "දීර්ඝජ්ජිද", "meaning": "උක්ගස, තේක්ක ගස", "category": "plant" },
  { "word": "දීර්ඝතීරක", "meaning": "ගෙදපලා", "category": "plant" },
  { "word": "දීර්ඝකරැ", "meaning": "තල්", "category": "plant" },
  { "word": "දීර්ඝනීසෝ", "meaning": "කැකිරි", "category": "plant" },
  { "word": "දීර්ඝදණ්ඩ", "meaning": "නවගිලි එරබදු", "category": "plant" },
  { "word": "දීර්ඝදණ්ඩක", "meaning": "එරබදු, තල්ගස", "category": "plant" },
  { "word": "දීර්ඝදන්ති", "meaning": "ගොමස නැම රුක, එබුරු ගස", "category": "plant" },
  { "word": "දීර්ඝදන්තක", "meaning": "එරබදු", "category": "plant" },
  { "word": "දීර්ඝදල", "meaning": "අමු නම් ධාන්‍ය වගිය", "category": "plant" },
  { "word": "දීර්ඝද්‍රැ", "meaning": "තල ගස", "category": "plant" },
  { "word": "දීර්ඝදුම", "meaning": "ඉඹුල් ගස", "category": "plant" },
  { "word": "දීර්ඝනාද", "meaning": "සක්", "category": "treatment" },
  { "word": "දීර්ඝනාල", "meaning": "හබරල", "category": "plant" },
  { "word": "දීර්ඝනීවහන", "meaning": "ශක්ගෙඩිය (සමග)", "category": "treatment" },
  { "word": "දීර්ඝ පටොලිකා", "meaning": "පතෝල වැල", "category": "plant" },
  { "word": "දීර්ඝපත්‍ර", "meaning": "කෙසෙල්, දඹ, ඉරවක්, මුරත, කඳුරු, තල්, මට සුදු සාරණ", "category": "plant" },
  { "word": "දීර්ඝපත්‍රක", "meaning": "කෙසෙල්, රුකුගුණ, මුරත, ඉරවක්, අරත්ත, එරබු", "category": "plant" },
  { "word": "දීර්ඝපත්‍රා", "meaning": "දිය මෙනේරිය, දිය බේරලිය, දමිගස, ප්‍රශ්නිපර්ණී", "category": "plant" },
  { "word": "දීර්ඝපත්‍රී", "meaning": "පුවඟු, සුදු සාරණ", "category": "plant" },
  { "word": "දීර්ඝපත්‍රිකා", "meaning": "රුකුගුණ, රුකුගුණ මුල්", "category": "plant" },
  { "word": "දීර්ඝ පත්‍රිකා", "meaning": "සාරණ, මුව සාරණ, කෙසෙල්, අරත්ත, පුවඟු, වද කසා, රතු ලුහුණු, ශාලිපර්ණී, රුකුගුණ", "category": "plant" },
  { "word": "දීර්ඝපත්‍රි", "meaning": "ශාලිපර්ණී, ප්‍රශ්නිපර්ණී", "category": "plant" },
  { "word": "දීර්ඝපර්ණ", "meaning": "අස්වැන්න, පඹුක්, මුරත ගස", "category": "plant" },
  { "word": "දීර්ඝපර්වික", "meaning": "උක්", "category": "plant" },
  { "word": "දීර්ඝපල්ලව", "meaning": "ගිණි", "category": "plant" },
  { "word": "දීර්ඝපලාඤ්ජු", "meaning": "තල්ගස, කඳුරු ගස", "category": "plant" },
  { "word": "දීර්ඝපාදප", "meaning": "තල්ගස, පුවක්, උක්ගස", "category": "plant" },
  { "word": "දීර්ඝපානි", "meaning": "පඹුක්", "category": "plant" },
  { "word": "දීර්ඝමුලිකා", "meaning": "ගල්පියල් ගස", "category": "plant" },
  { "word": "දීර්ඝපුෂ්ප", "meaning": "මසිල, මිරිකුළු (මුරුංගා) ඇසල, පත්පාඩගම්, වරා වෙසෙසක්", "category": "plant" },
  { "word": "දීර්ඝපුෂ්පී", "meaning": "කඩුවැල් බටු", "category": "plant" },
  { "word": "දීර්ඝපුෂ්පිකා", "meaning": "මසිල", "category": "plant" },
  { "word": "දීර්ඝඵල", "meaning": "ඇසල, කතුරු මුරුංගා", "category": "plant" },
  { "word": "දීර්ඝඵලා", "meaning": "වැටකොළු, මැඩහඟු, තිත්ත ලබු", "category": "plant" },
  { "word": "දීර්ඝඵලිකා", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "දීර්ඝමුඛගබක", "meaning": "හෙල එරබු", "category": "plant" },
  { "word": "දීර්ඝමූල", "meaning": "අන්දර ගස, අස්වැන්න, සැවැන්දරා, කොහිල, මුරුවා, පුසුල්, කලු හුස්නවාලු, නොවිල, පත්තක්කා, කසඹිලියා, හෙල වරා, ඉරබු, බෙලි, ශාලිපර්ණී", "category": "plant" },
  { "word": "දීර්ඝමූලක", "meaning": "මොණබා, මුලපලා", "category": "plant" },
  { "word": "දීර්ඝමූලා", "meaning": "අස්වැන්න, අන්දර, ඉරමුසු, ඇසල, මහ හිරමුසු, පොල් පලා, යවාස, ශාලිපර්ණී", "category": "plant" },
  { "word": "දීර්ඝමුලි", "meaning": "කාම්මේරිය, බුරල්ල ගස", "category": "plant" },
  { "word": "දීර්ඝවංශා", "meaning": "කසා", "category": "plant" },
  { "word": "දීර්ඝරාගා", "meaning": "කසා (කහ)", "category": "plant" },

  // --- පිටුව 248 ---
  { "word": "දීර්ඝරෝමන්", "meaning": "නොවිල, වලස් ලොම්", "category": "plant" },
  { "word": "දීර්ඝරෝමා", "meaning": "නොවිල", "category": "plant" },
  { "word": "දීර්ඝලතාද්‍රැම", "meaning": "සූරිය ගස", "category": "plant" },
  { "word": "දීර්ඝලෝචන", "meaning": "රම්මානිස්ස, වෙලා", "category": "plant" },
  { "word": "දීර්ඝලෝචන යෂ්ටිකා", "meaning": "වැළුක්, උක් ගස", "category": "plant" },
  { "word": "දීර්ඝවමිකා", "meaning": "මනසාරණ", "category": "plant" },
  { "word": "දීර්ඝවල්ලි", "meaning": "ගැඹිල්ල වැල්, වැල්මදට, පානාල ගරුඬ", "category": "plant" },
  { "word": "දීර්ඝවාස", "meaning": "සල්, බූරැක, කුඹුක්, සුළු කුඹුක්, කොළොම්, තල් ගස", "category": "plant" },
  { "word": "දීර්ඝවාහන", "meaning": "කොවිල, මුරුවා දළු, මුරුවා", "category": "plant" },
  { "word": "දීර්ඝවාහන ඵල", "meaning": "කොවිල", "category": "plant" },
  { "word": "දීර්ඝවෘන්තක", "meaning": "තොවිල", "category": "plant" },
  { "word": "දීර්ඝවාගි", "meaning": "මකලඳ", "category": "plant" },
  { "word": "දීර්ඝවෘන්ත", "meaning": "අරත්ත", "category": "plant" },
  { "word": "දීර්ඝාබ", "meaning": "සල් ගස, හුණ ගස, තේක්ක ගස", "category": "plant" },
  { "word": "දීර්ඝිකාභක", "meaning": "මෑ", "category": "plant" },
  { "word": "දීර්ඝසකභ", "meaning": "හල්", "category": "plant" },
  { "word": "දීර්ඝසංඥක", "meaning": "බට ගස", "category": "plant" },
  { "word": "දීර්ඝසාව", "meaning": "හණ", "category": "plant" },
  { "word": "දීර්ඝාංශු", "meaning": "ප්‍රශ්නිපර්ණී", "category": "plant" },
  { "word": "දීර්ඝාඬ", "meaning": "ඇසල", "category": "plant" },
  { "word": "දීර්ඝාශ්‍රි", "meaning": "ශාලිපර්ණී", "category": "plant" },
  { "word": "දීර්ඝායු", "meaning": "මෝර ගස, හෙළ මිදුරා", "category": "plant" },
  { "word": "දීර්ඝායුෂ්", "meaning": "බෝ ගස, ඉඹුල්, එරබදු", "category": "plant" },
  { "word": "දීර්ඝායුස", "meaning": "එරබදු", "category": "plant" },
  { "word": "දීර්ඝාලගී", "meaning": "එරබදු ගස", "category": "plant" },
  { "word": "දීර්ඝිකා", "meaning": "සියුපත් තණ, ගොඩිය", "category": "plant" },
  { "word": "දීර්ඝශු", "meaning": "වැළුක්, rඹුක්, උක්", "category": "plant" },
  { "word": "දීරාන", "meaning": "දිය මෙනේරිය", "category": "plant" },
  { "word": "දුංදය", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "දුංබන්‍ධ", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "දුංබදිර", "meaning": "ගුරුවැට ගස", "category": "plant" },
  { "word": "දුඃසහ", "meaning": "කටුවැල් බටු, හෑල්කසඹිලියා, ගිඩි ගස්, අගස්තර බැබිල, වැල්කැරඳ, ජටාමාංශ", "category": "plant" },
  { "word": "දුක්ඛ සහ", "meaning": "කසඹිලියා වැල", "category": "plant" },
  { "word": "දුග්ධ", "meaning": "කිරි", "category": "treatment" },
  { "word": "දුග්ධකාලිය", "meaning": "කිරේන් පිසූ අබ, වෙඬරු, කිරිපෙණ", "category": "treatment" },
  { "word": "දුග්ධතුම්බි", "meaning": "(සුදු) ලබු", "category": "plant" },
  { "word": "දුග්ධතය", "meaning": "එළකිරි, එළුකිරි, මීකිරි යන තෙවගය", "category": "treatment" },
  { "word": "දුග්ධය", "meaning": "අත්තික්කා කිරි (වතුර)", "category": "treatment" },
  { "word": "දුග්ධවෘක්‍ෂ", "meaning": "හල ගස, කිරි ගස", "category": "plant" },
  { "word": "දුග්ධ", "meaning": "බක්මී, ඉරමුසු, කිරිපළු, කවෙළු", "category": "plant" },
  { "word": "දුග්ධශාඛා", "meaning": "හිරි", "category": "plant" },
  { "word": "දුග්ධිකා", "meaning": "උප්පල ලෑ, තිත්ත නැල්ල, වරා, තිත්ත ලබු, කිරි කවෙළු, නිකගහන්දි", "category": "plant" },
  { "word": "දුග්ධා", "meaning": "වරා", "category": "plant" },
  { "word": "දුග්ධිනිකා", "meaning": "රතු සැබෝ, වරා ගස", "category": "plant" },
  { "word": "දුග්ධී", "meaning": "කිරි, දළුක්, කිරිඅඟුණ, කිරිගරුඬ ගල්", "category": "treatment" },
  { "word": "දුච්චිකා", "meaning": "සුරා නම් ගන්ධ ද්‍රව්‍යය, තලිස් පතුරු", "category": "plant" },
  { "word": "දුටුසතුටු", "meaning": "මොණරකුඩුම්බිය, = කෝබේසිපොල = (කුබේසි කොළ) ගොඩ මානෙල්, ඇස්වැද්ද", "category": "plant" },
  { "word": "දුන්බුභා", "meaning": "අබ ගස", "category": "plant" },
  { "word": "දුනිය", "meaning": "සින්ක්කාරම්", "category": "treatment" },
  { "word": "දුද්දුර", "meaning": "අත්තන ඇට, කන්සා ඇට", "category": "plant" },

  // --- පිටුව 249 ---
  { "word": "දුදුම්", "meaning": "නිල්කොළ ඇති හුණ", "category": "plant" },
  { "word": "දුදු", "meaning": "වල් උළුවා, කිරි", "category": "plant" },
  { "word": "දුදුග", "meaning": "අඹ, හෙළ අඹ", "category": "plant" },
  { "word": "දුදුල", "meaning": "දියලබු", "category": "plant" },
  { "word": "දුන්ගි", "meaning": "අත්තන", "category": "plant" },
  { "word": "දුනුග", "meaning": "හෙළ අඹ", "category": "plant" },
  { "word": "දුන්තාවකන්‍", "meaning": "අර්සස් රෝගය", "category": "symptom" },
  { "word": "දුනු", "meaning": "සිරියල්", "category": "treatment" },
  { "word": "දුනුදන්", "meaning": "වැරහලි", "category": "treatment" },
  { "word": "දුනුකේ", "meaning": "දුනුකේයිය", "category": "plant" },
  {
    "word": "දුනුමඩලා",
    "meaning": "මෙය සුදුපාට කඳකින් යුත් අඩි හැටක් පමණ උසට වැවෙන විශාල ගසකි. ලුණුවරණ කොළ වලට සමාන මේ ගසේ කොළ එක නැට්ටේ තුනක් හෝ හතරක් බැගින් පිහිටා තිබේ. මේ ගසේ පොතු සුභ පොවා ඒ පොතු ම වක්කඩුවේ තම්බා යටි බඩ තැවීමෙන් දුෂ්කර ප්‍රසූත (මුක් ගර්භ) ය ඇති ගර්භිණී සත්‍රීන්ට වහා ප්‍රසූත ය සිදු වී වැදමස් වැටීම ත් එකෙණෙහි ම සිදු වන බව වක්කෝරු වෙද පොත් වල කියා තිබේ. මේ පොතු කාඩුම් - සිදුම් වෙදකම පිළිබඳව ද ප්‍රත්‍යක්ෂ ඖෂධයකි.",
    "category": "plant"
  },
  { "word": "දුනුකේ", "meaning": "දුම්මල ගස", "category": "plant" },
  { "word": "දුප්සස", "meaning": "කසඹිලියා", "category": "plant" },
  { "word": "දුබ්බා", "meaning": "හිතණ", "category": "plant" },
  { "word": "දුගිණි", "meaning": "වරා", "category": "plant" },
  { "word": "දුම්", "meaning": "ගස", "category": "plant" },
  { "word": "දුම්බිල්ල", "meaning": "අගිල්", "category": "plant" },
  { "word": "දුම්මල", "meaning": "ලාබුව, දුම්මල", "category": "treatment" },
  { "word": "දුම්බ", "meaning": "දුම්බලා, කල්වැල්", "category": "plant" },
  { "word": "දුම්පල", "meaning": "කහිටිරි", "category": "plant" },
  { "word": "දුම්රද", "meaning": "බෝ ගස", "category": "plant" },
  { "word": "දුමිබ", "meaning": "නාල්වැල්", "category": "plant" },
  { "word": "දුමිඳු", "meaning": "බෝ ගස", "category": "plant" },
  { "word": "දුගි", "meaning": "ගුගුල්, නිල්කටරොළු", "category": "plant" },
  { "word": "දුගිනික", "meaning": "ලුණුහුණු, අබ ගස, බෝදි ඇට ගස", "category": "plant" },
  { "word": "දුගීක්‍ෂු", "meaning": "ගුරුවැදගස (ගරිදගස) මේ වායේ රෝග ප්‍රතිෂේධක ශක්තියක් තිබේ. 171 පිට බලන්න.", "category": "plant" },
  { "word": "දුගීපුෂ්පික", "meaning": "වනස්පති වෘක්‍ෂය (නුග)", "category": "plant" },
  { "word": "දුගීගාන්ලදා", "meaning": "හෙළ අඹ, ගුගුල්", "category": "plant" },
  { "word": "දුගීශ්චය", "meaning": "හෙළ සැබෝ", "category": "plant" },
  { "word": "දුර්භා", "meaning": "සැබෝ, වම්මුතු", "category": "plant" },
  { "word": "දුර්ජර", "meaning": "දූදු, ගිහින්", "category": "plant" },
  { "word": "දුර්ජර්ජටිල", "meaning": "කැකිරි", "category": "plant" },

  // --- පිටුව 250 ---
  { "word": "දුර්බර", "meaning": "බදුල්ල, වාහනක, කොමෝරීක", "category": "plant" },
  { "word": "දුර්දර්මී", "meaning": "බදුල්ල ගස", "category": "plant" },
  { "word": "දුද්‍රැ", "meaning": "කිරිපළු ගස", "category": "plant" },
  { "word": "දුරීර්", "meaning": "බදුල්ල, රසදිය", "category": "plant" },
  { "word": "දුධිර", "meaning": "ඊතණ, කුසතණ", "category": "plant" },
  { "word": "දුදෘමී", "meaning": "සන් ප් රාරි රුක, නාගදමනී රුක", "category": "plant" },
  { "word": "දුර්නාම", "meaning": "අර්සස් රෝගය", "category": "symptom" },
  { "word": "දුර්නාමාරි", "meaning": "කිඩාරම්", "category": "plant" },
  { "word": "දුධීරා", "meaning": "දුදුවැල", "category": "plant" },
  { "word": "දුර්මිත", "meaning": "දුහඳු", "category": "plant" },
  { "word": "දුර්මිතාරාරයා", "meaning": "හෙළ ඊතණ, කුසතණ", "category": "plant" },
  { "word": "දුර්මනී", "meaning": "සැබෝ", "category": "plant" },
  { "word": "දුර්භාසා", "meaning": "හෙළ හුනිද", "category": "plant" },
  { "word": "දුර්මුඛා", "meaning": "හුනිද, හෙළ හුනිද, කටු වැල්බටු", "category": "plant" },
  { "word": "දුමකා", "meaning": "හෙළ හුනිද", "category": "plant" },
  { "word": "දුර්මොසා", "meaning": "හුනිද", "category": "plant" },
  { "word": "දුලභ", "meaning": "එලකබු වැල්බටු, හිඟුරුපියලි", "category": "plant" },
  { "word": "දුලීනා", "meaning": "හැල් කසඹිලියා", "category": "plant" },
  { "word": "දුර්ලාභා", "meaning": "(ධන්වයවාස) යවාස, වැල් කසඹිලියා, (වාග්විකාලී) ගස් කසඹිලියා, (වල්කසඹිලියා) යි වෙන් වෙන් වූ වගී හතරකි. ධන් (අරාබි) දේශයෙහි වැවෙන යවාස (ධන්වයවාස) නම් පැළෑටි වගිය දුරාලභා බව ත්, දුරාලභා හා යවාස යන දෙවගිය ම සමාන ගුණ ඇති ඖෂධ බව ත්, දුරාලභා වෙනුවට යවාස ගැන්ම සුදුසු බව ත්, ඉන්දියානු ද්‍රව්‍ය ගුණ නියඝණ්ඩුවල කියා තිබේ. එහෙත් දුරාලභා (ධන්වයවාස) යවාස දෙවගිය වෙනුවට වැල් කසඹිලියා හෝ ගස් කසඹිලියා ගැනීමට ඉන්දියානු පොත් වල නියම කර ඇති තැනක් දැනගන්නට නැත.", "category": "plant" },
  { "word": "ධන්වයවාස (දුරාලභා)", "meaning": "මෙය ධන් (අරාබි) දේශය ප්‍රභව කොට ඇති අබියක් පමණ උසට වැවෙන පැලෑටියකි. මෙහි කොළ දිග-පළල අඟල් 1/2 x 1/8 ක් පමණ ඇත. මල් රතු පාට ය. අතුවල සහ කඳේ කටු තිබේ. දුරාලභා (ධන්වයවාස) වලට ව්‍යවහාර කරන්නේ ලෂ්මන්කන්‍යා (සිටුවහන් විසින් කනු ලබන පැලෑටි)", "category": "plant" },
  { "word": "දුමී", "meaning": "හිඹුල්", "category": "plant" },
  { "word": "දුමීන", "meaning": "ගොකටු, නෙරෙවි, රිදී", "category": "plant" },
  { "word": "දුර්ම", "meaning": "වාහනක, ඊතණ, කුසතණ, සිහින් සාතාවාරිය", "category": "plant" },
  { "word": "දුර්ලා", "meaning": "සිනිඹලා", "category": "plant" },
  { "word": "දුම", "meaning": "වනුවැල්, (බාත්වැල්) හෙළ ඊතණ, කුසතණ", "category": "plant" },
  { "word": "දුර්විධඝා", "meaning": "හිඟුරුපියලි විශේෂයක්", "category": "plant" },
  { "word": "දුර", "meaning": "හොරගස", "category": "plant" },
  { "word": "දුත්තීහුස", "meaning": "කරල් සැබෝ, වඳුරු මෑ, හැල් කසඹිලියා", "category": "plant" },
  { "word": "දුරාසර්පස", "meaning": "හෙළ අබ", "category": "plant" },
  { "word": "දුරාශිකාව", "meaning": "බෙලි", "category": "plant" },
  { "word": "දුරාධි", "meaning": "හෙළ අබ", "category": "plant" },
  { "word": "දුරාරහ", "meaning": "බෙලි, පුවක්, ඉන්සල, කිඳි, පොල්", "category": "plant" },
  { "word": "දුරාරෝහා", "meaning": "හිඹුල්, බෙලි, කිඳි ගස, කල්ගස", "category": "plant" },
  { "word": "දුරාරොහා", "meaning": "හිඹුල්, කිඳි, තල්, ශ්‍රී වල්ලි රුක", "category": "plant" }
];