// data_306_314.js - පිටු 306 සිට 314 දක්වා සියලුම වචන
const data_extra_306_314 = [
    // --- පිටුව 306 ---
    { 
        "word": "පිල", 
        "meaning": "ප්‍රසිද්ධ=(ගස්පිල) කතුරු පිල, කටුපිල යයි වර්ග දෙකකි. කතුරු පිල උපදංශ ඇතුළු වාත රෝග වලට ත්, දන්ත රෝග කර්ණ රෝග සහිත සෙම් රෝග වලට ත් ප්‍රත්‍යක්ෂ විෂ නාශක ඖෂධයකි. කටු පිල ගැන විස්තරයක් 68 පිටේ ඇත.", 
        "category": "plant" 
    },
    { "word": "පිලකා", "meaning": "පුලිල, පලොල්", "category": "plant" },
    { "word": "පිලාමරම්", "meaning": "කොස් ගස", "category": "plant" },
    { "word": "පිලි", "meaning": "ගෙඩිය", "category": "plant" },
    { "word": "පිලිමිනන", "meaning": "තෘණ වර්ගයක්", "category": "plant" },
    { "word": "පිලිමිනි", "meaning": "පුලිඟු", "category": "plant" },
    { "word": "පිලිල", "meaning": "ඉටි කෙහෙල්=(උඩවැඩියා) දියසෙවෙල් හා ගස්වල ඕපපාතිකව හට ගනිමින් වැඩෙන පැලෑටි", "category": "plant" },
    { "word": "පිලිවිලි", "meaning": "බෝගස්", "category": "plant" },
    { "word": "පිලිහුඩු", "meaning": "මස්-මාළු වර්ග හෝ තම්පලා වර්ගයක්", "category": "food" },
    { "word": "පිලිවරි", "meaning": "ලත්ගස්", "category": "plant" },
    { "word": "පිලුපර්ණී", "meaning": "මුරුවා වැල", "category": "plant" },
    { "word": "පිලුකා", "meaning": "පියාගස්", "category": "plant" },
    { "word": "පිශාච", "meaning": "කොට දිඹුලා, ශාකොට වෘක්‍ෂය (ගැට නෙටුල් ගස)", "category": "plant" },
    { "word": "පිශාචිකා", "meaning": "තෝර ගස", "category": "plant" },
    { "word": "පිශාවදා", "meaning": "ගැටනෙටුල්", "category": "plant" },
    { "word": "පිශාවී", "meaning": "මස්වැන්න, ජටාමාංශ", "category": "plant" },
    { "word": "පිශාවිකා", "meaning": "මස්වැන්න, ජටාමාංශ", "category": "plant" },
    { "word": "පිශිත", "meaning": "පියා ගස, උණ කපුරු, පික්මැලි", "category": "plant" },
    { "word": "පිශුන", "meaning": "කොකුම්, පික්මැලි (පික්මැලි=හිඟි - පිච්ච)", "category": "plant" },
    { "word": "පිෂණපර්ණී", "meaning": "පාෂාණ පර්ණී (පුස්වැන්න)", "category": "plant" },
    { "word": "පිෂ්ට", "meaning": "ඊයම්, සුණුකිරිම (කුඩුකිරීම) පිටි", "category": "mineral" },
    { "word": "පිෂ්ට පාෂාණනායක", "meaning": "බෙබර ගෙඩි", "category": "plant" },
    { "word": "පිෂ්ටි", "meaning": "හිඟුල්", "category": "mineral" },
    { "word": "පිෂ්ටික", "meaning": "හාල් පිටි වලින් උපන් කිරි වැනි ද්‍රව්‍යය", "category": "food" },
    { "word": "පිෂ", "meaning": "සුණුකිරිම", "category": "treatment" },
    { "word": "පිසඟ පද්ම", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "පිසඟුරා", "meaning": "දියසෙවෙල්(දියපරඬැල්=පෙද)", "category": "plant" },
    { "word": "පිසිත", "meaning": "මාංශය", "category": "anatomy" },
    { "word": "පිසිනි", "meaning": "ලාටු වර්ග", "category": "plant" },
    { "word": "පිසිබ", "meaning": "කොසඹ", "category": "plant" },
    { "word": "පිසුනා", "meaning": "සෙව්වන්දි, කොකුම්", "category": "plant" },
    { "word": "පිහිටිය", "meaning": "(කිහිරිය) තද නිල්පාටින් යුත් අඟල් එක හමාරක් පමණ පළල හා අඟල් හතරක් පමණ දිග ඇති කොළ වලින් යුත් සෙවන සඳහා ප්‍රයෝජනයට ගන්නා වටුලු සහිත ගසක්", "category": "plant" },
    { "word": "පිළුල්ලිය", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "පික්කෙයි", "meaning": "තියන් වැටකොළු", "category": "plant" },
    { "word": "පික්තු", "meaning": "වැටකොළු", "category": "plant" },
    { "word": "පික්නකායි", "meaning": "වැටකොළු", "category": "plant" },
    { "word": "පීත", "meaning": "හිරියල්, කොකුම්, වනුවැල්, (බාන් වැල්) මුං, කසා, රන්වන් සඳුන්, මහ වැටකොළු, කහ, දොඹ", "category": "mineral" },
    { "word": "පීතක", "meaning": "කටුකරඬු, මැහිඟු, පද්මකාෂ්ඨ, වනු වැල්, තොටිල, බිම් කොසඹ, කොකුම්, රත්හාල්, මුහුණමල්, හෙළ වලාවැන්න, හිරියල්", "category": "plant" },
    { "word": "පීතකදලි", "meaning": "කෙසෙල් (රන්වන් කෙසෙල්)", "category": "plant" },

    // --- පිටුව 307 ---
    { "word": "පීතකන්දුල", "meaning": "වම්බටු", "category": "plant" },
    { "word": "පීතකන්‍ද", "meaning": "කැරට්", "category": "plant" },
    { "word": "පීත කරෝහිණී", "meaning": "කටුකරඬු, පීතකරෝෂණ", "category": "plant" },
    { "word": "පීතකා", "meaning": "පීතකරෝෂණ", "category": "plant" },
    { "word": "පීතකාවේර", "meaning": "කොකුම්, පිත්තල", "category": "mineral" },
    { "word": "පීතකාෂ්ඨ", "meaning": "රන්වන් අගිල්, රන්වන් සඳුන්", "category": "plant" },
    { "word": "පීතකේශ", "meaning": "නාමල් රේණු", "category": "plant" },
    { "word": "පීතචන්දන", "meaning": "රන්වන් සඳුන්, වනු වැල්", "category": "plant" },
    { "word": "පීතජ්න්", "meaning": "දාරුහරිද්‍රා", "category": "plant" },
    { "word": "පීත තණ්ඩුල", "meaning": "කිරිපලු, මෙනේරි", "category": "plant" },
    { "word": "පීතතෛලා", "meaning": "දුහුදු, කටුවෙලඟ", "category": "plant" },
    { "word": "පීතද්විපාතින", "meaning": "බාන්වැල්", "category": "plant" },
    { "word": "පීතදාරු", "meaning": "හොර අරටු, දේවදාර, කහ ගස", "category": "plant" },
    { "word": "පීතදාම", "meaning": "වනුවැල්, හොර අරටු, දේවදාර, පිච්ච, යොහොඹු", "category": "plant" },
    { "word": "පීතන", "meaning": "ඇම්බරැල්ල, කසා, හිරියල්, පලොල්, කොකුම්, වනු වැල්", "category": "plant" },
    { "word": "පීතනක", "meaning": "ඇම්බරැල්ල", "category": "plant" },
    { "word": "පීතනා", "meaning": "කඩල", "category": "plant" },
    { "word": "පීතනී", "meaning": "අස්වැන්න", "category": "plant" },
    { "word": "පීතපුෂ්ප", "meaning": "වල්අබ, අස්බැවිල, රන්කිරි ගොකටු, අඬනගිරියා, මඟුල්කරඳ, කිහිරි, මහ බැවිල, වැටකොළු, කුඹුරුවැල්, කැකිරි, මස්බැද්ද", "category": "plant" },
    { "word": "පීතපුෂ්පක", "meaning": "මුහුණමල්, තුවර, මහ බැවිල, රටතෝර", "category": "plant" },
    { "word": "පීතපුෂ්පා", "meaning": "රම්මානිස්ස, වැල් තුඹ, කැකිරි, රන්කිරි ගොකටු", "category": "plant" },
    { "word": "පීතපුෂ්පී", "meaning": "අස්බැවිල, යක්බේරිය, වේලිප්පරිත්ති", "category": "plant" },
    { "word": "පීතපුෂ්පිකා", "meaning": "පුපුල්, මහ බැවිල, කොමඩු", "category": "plant" },
    { "word": "පීත ඵල", "meaning": "ගැට නෙටුල්, කාමරංගා", "category": "plant" },
    { "word": "පීතඵලා", "meaning": "බෙලි, හෙළබටු, ඇද්දෙමට, කාමරංගා", "category": "plant" },
    { "word": "පීතඵෙණ", "meaning": "කොසඹ", "category": "plant" },
    { "word": "පීතබාන", "meaning": "දසමන්, රන්වන් සමන්පිච්ච", "category": "plant" },
    { "word": "පීතද්‍රැ", "meaning": "බාන්වැල්", "category": "plant" },
    { "word": "පීතබධන", "meaning": "දාරුහරිද්‍රා", "category": "plant" },
    { "word": "පීත බර්බරිකා", "meaning": "වේලා", "category": "plant" },
    { "word": "පීතමධ්‍ය", "meaning": "සිහින් දුරු, (සුදු දුරු)", "category": "plant" },
    { "word": "පීත මාක්‍ෂික", "meaning": "කිකිරිඳිය, රන්වන් කිකිරිඳිය", "category": "plant" },
    { "word": "පීත මූලා", "meaning": "එරැලෑ සැපිවි, මැණික්වැන්න, පොල්පලා", "category": "plant" },
    { "word": "පීතයුතී", "meaning": "රන්වන් ඉද්ද, බෝලිද්ද", "category": "plant" },
    { "word": "පීත රත්න", "meaning": "ගෝමේද", "category": "mineral" },
    { "word": "පීතරාග", "meaning": "මී ඉටි, නෙළුම් රේණු, (නා කේසර)", "category": "plant" },
    { "word": "පීතකරෝෂණ", "meaning": "හොර ගස, ඇද්දෙමට", "category": "plant" },
    { "word": "පීතරොචනෛ", "meaning": "පීතරෝහිණී, රන්වන් කටුකරෝෂණ", "category": "plant" },
    { "word": "පීතරෝහිණී", "meaning": "කහ කටුකරඬු", "category": "plant" },
    { "word": "පීතලා", "meaning": "පිත්තල", "category": "mineral" },
    { "word": "පීතලෝහ", "meaning": "පිත්තල", "category": "mineral" },
    { "word": "පීතවර්ණී", "meaning": "කසා (කහ)", "category": "plant" },
    { "word": "පීතවීජ", "meaning": "එළබටු", "category": "plant" },
    { "word": "පීතවෘක්‍ෂ", "meaning": "තොටිල, තෝර", "category": "plant" },
    { "word": "පීතශාර", "meaning": "රත්හඳුන්, අහුගස, වනු වැල්, වැල්මදට, රුකඟුණ, ගල් පියල්, ගෝමේද", "category": "plant" },
    { "word": "පීතශාල", "meaning": "පියල් ගස, පියා ගස, ගම්මුලු ගස", "category": "plant" },
    { "word": "පීතසාරක", "meaning": "අහුගස, පියා ගස, කොසඹ", "category": "plant" },
    { "word": "පීතා", "meaning": "කසා, දුහුදු, දාරුහරිද්‍රා, පීතකරෝෂණ", "category": "plant" },
    { "word": "පීතාඞග", "meaning": "තොටිල භෙදයක්", "category": "plant" },

    // --- පිටුව 308 ---
    { "word": "පීතාජාත", "meaning": "දසමන්, රන්වන් සමන්පිච්ච", "category": "plant" },
    { "word": "පීතාද්‍රැ", "meaning": "බාන්වැල්", "category": "plant" },
    { "word": "පීතාබධන", "meaning": "දාරුහරිද්‍රා", "category": "plant" },
    { "word": "පීතිකා", "meaning": "රන්වන් බෝලිද්ද, කසා, දාරුහරිද්‍රා", "category": "plant" },
    { "word": "පීතිනී", "meaning": "ශාලිපර්ණී", "category": "plant" },
    { "word": "පීතේරි", "meaning": "මිදිවච කිරි", "category": "plant" },
    { "word": "පීත්ඵල", "meaning": "සිහින් මිදි", "category": "plant" },
    { "word": "පීතක", "meaning": "තොටිල", "category": "plant" },
    { "word": "පීතතෛල", "meaning": "කලුකාමිමේරිය", "category": "plant" },
    { "word": "පීනපාදප", "meaning": "තොටිල", "category": "plant" },
    { "word": "පීතස", "meaning": "එනම් රෝගය, බෙබර", "category": "treatment" },
    { "word": "පීනාසො", "meaning": "නාසිකා රෝගය", "category": "treatment" },
    { "word": "පීයූෂ", "meaning": "අමෘත, කිරි", "category": "liquid" },
    { "word": "පීරණෙඬ", "meaning": "සිරස්ස", "category": "plant" },
    { "word": "පීලි", "meaning": "කටුපිල", "category": "plant" },
    { "word": "පීලිනී", "meaning": "මැඩහඟු (වේලිප්පරිත්ති) මස්බැද්ද", "category": "plant" },
    { "word": "පීලු", "meaning": "කොරාසානි, ඉඟිනි, වැලතුණ, වනෙතිබු මොර, පියා ගස", "category": "plant" },
    { "word": "පීලුක", "meaning": "මොර", "category": "plant" },
    { "word": "පීලුකි", "meaning": "මුරුවා, මස්බැද්ද, නියඳ, කෝවක්කා", "category": "plant" },
    { "word": "පීලුර්ණී", "meaning": "මුරුවා වැල්", "category": "plant" },
    { "word": "පීලුපත්‍ර", "meaning": "මුරුවා වැල්, කටුපිල", "category": "plant" },
    { "word": "පීලුපර්ණී", "meaning": "කෝවක්කා, කටුඬු කෝවක්කා, වැඩහඟු, මස්බැද්ද, නියඳ, මුරුවා කොළ, කැකිරි, උඩැත්ත", "category": "plant" },
    { "word": "පීලුපුෂ්පී", "meaning": "මුරුවා වැල්", "category": "plant" },
    { "word": "පීලුවර්ණී", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "පීවර", "meaning": "මේවන්, සාතාවාරිය, අමුක්කරා, ශාලිපර්ණී", "category": "plant" },
    { 
        "word": "පීවරී", 
        "scientific": "Abroma Augusta",
        "meaning": "යක් කපු.-Abroma Augusta-මෙය ඉන්දියාව ජන්මභූමි කොට ඇති රත්කෑන්ද කොළ වලට සමාන කොළ වලින් යුත්, මුල් සහ ඇට සැලකීමෙන් විශාල ලෙස බෝවී යන, අඩි පහළොහක් පමණ උසට වැඩෙන පඳුරු වර්ගයකි. අපේ රටේ බුලත් වැල් වල කඳ (නොපිදුන) බුලත් වැල හා කිනිති (පිදුන) බුලත් වැල ඇති වෙනස මෙන් ම මේ වර්ගයේ ද නො පිදුන අතු වල සහ පිදුන අතු වල කොළ අතරෙහි විශාල වෙනසක් දක්නට තිබේ. නො පිදුන අතු වල කොළ රත්කෑන්ද කොළ මෙන් විශාල ය. හැඩහුරුකමින් ද එ සේම ය. පිදුන කොළ කුඩා ය. පෙනුමෙන් හා ප්‍රමාණයෙන් පිදුන බුලත් කොළ වලට සමාන ය. මේ ගසේ මල් කපු මල් වැනි ය. කුඩා රිකිලි දිගේ පහළට සෑදෙන මේ මල් වලින් හට ගන්නා ඇට කොපු (ගෙඩි) පැසුනවිට විවෘත වී කපු නිසි ඇට ප්‍රමාණ කළු පාට ඇට වලින් පිරී තිබෙයි. මේ ගසේ මුල් වල සාරය අතිශය මාස් ශුද්ධියෙහි දී ඇති වන වේදනාව මගහරවා මසකට වරක් බැගින් ස්වාභාවික මාස් ශුද්ධිය ඇති කිරීමට ත්, මාස් ශුද්ධියට පෙර අධික ලෙස ලේ රැස්වී මෙන් සහ ලේ නහර ගත වීමෙන් හිසෙහි සහ මධ්‍ය ප්‍රදේශයෙහි ත්, ඇති වන වේදනාවන් දුරු කිරීමට ත් ප්‍රත්‍යක්ෂ ඖෂධයකි. මේ ගස් වර්ගය ලක්දිව හැම ප්‍රදේශයක ම හොඳින් වැවිය හැකි බව පෙනේ. එම නිසා බෝ කර ගැනීමට උවමනා අයට අප වවා තිබෙන ගස් වලින් ඇට ලබා ගත හැක.", 
        "category": "plant",
        "image": "img_308_peewari.jpg"
    },

    // --- පිටුව 309 ---
    { "word": "පීවරා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "පීවරෝසළසස්බඬා", "meaning": "කවෙලු, කිරිකවෙලු", "category": "plant" },
    { "word": "පුංකු", "meaning": "කරඳ", "category": "plant" },
    { "word": "පුංග", "meaning": "කරඳ", "category": "plant" },
    { "word": "පුංගල", "meaning": "වට්ටක්කා වැල", "category": "plant" },
    { "word": "පුංසවන", "meaning": "කිරි", "category": "liquid" },
    { "word": "පුඟ", "meaning": "දෙඹ ගස", "category": "plant" },
    { "word": "පුඬකුමරම්", "meaning": "කරඳගස", "category": "plant" },
    { "word": "පුඬිකා", "meaning": "පිල, හෙළපිල", "category": "plant" },
    { "word": "පුඬග", "meaning": "මඟුල්කරඳ", "category": "plant" },
    { "word": "පුඬගව", "meaning": "සාෂහක, වංඇපල", "category": "plant" },
    { "word": "පුවුෂ්කා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "පුවුජාලි", "meaning": "ඇත්අඩි", "category": "plant" },
    { "word": "පුවුජී", "meaning": "එරඬු", "category": "plant" },
    { "word": "පුවුජීකා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "පුවුජීන්", "meaning": "එළවරා", "category": "plant" },
    { "word": "පුවිමන්‍ද", "meaning": "කොසඹ", "category": "plant" },
    { "word": "පුට", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "පුටකෝෂ", "meaning": "සුදුලූනු", "category": "plant" },
    { "word": "පුටපෝෂණ", "meaning": "පොල්", "category": "plant" },
    { "word": "පුටපාක", "meaning": "ලොකු භාජනයක හෝ වළඳකා දහයියා පුරවා මැදට ගොම වරටි දමා ගිනි දල්වා ඒ තුළ තබන ලද කට වසා මැටි බැඳි බෙහෙත් බඳුන.", "category": "equipment" },
    { "word": "පුටයක්(ක)", "meaning": "(ගොටුවක්) බෙහෙත් ඔතා උණු අළු පල්ලේ දමා තැම්බීම.", "category": "treatment" },
    { "word": "පුටස්", "meaning": "කිතුල්ගුද", "category": "plant" },
    { "word": "පුටී", "meaning": "එන්සාල්", "category": "plant" },

    // --- පිටුව 310 ---
    { "word": "පුටෝදක", "meaning": "පොල්", "category": "plant" },
    { "word": "පුබල්", "meaning": "මී මත්තන් වැල", "category": "plant" },
    { "word": "පුණ්ඩර", "meaning": "හෙළ උක් දඬු", "category": "plant" },
    { "word": "පුණ්ඩරී", "meaning": "මහ සාරණ, සුදු උක්", "category": "plant" },
    { "word": "පුණ්ඩරීක", "meaning": "හෙළ පියුම්, ඇටඹ", "category": "plant" },
    { "word": "පුණ්ඩරීකා", "meaning": "හෙළ නෙළුම් මල්, කුකුරුමුවන්, අඹ, ඇටඹ, පොණඬරු", "category": "plant" },
    { "word": "පුණ්ඩරීය", "meaning": "පොණඬරු", "category": "plant" },
    { "word": "පුණ්ඩයසී", "meaning": "පොණඬරු", "category": "plant" },
    { "word": "පුණ්ඩාහ්ව", "meaning": "පොණඬරු", "category": "plant" },
    { "word": "පුණ්ඩුක", "meaning": "යොහොඹු, ගැටපිච්ච, පොණඬරු, බෝලිද්ද, මදටිය, මාරා, කොසඹ, සුදු නෙළුම්", "category": "plant" },
    { "word": "පුණ්ඩ්‍ය", "meaning": "මසන්", "category": "plant" },
    { "word": "පුණණකති", "meaning": "ගල්කූර", "category": "plant" },
    { "word": "පුණණා", "meaning": "ඇත්තෝර", "category": "plant" },
    { "word": "පුණණාග", "meaning": "දෙඹ, සාදික්කා, හෙළ උපුල්", "category": "plant" },
    { "word": "පුණේණාමරම්", "meaning": "දෙඹ ගස", "category": "plant" },
    { "word": "පුණ්මුරුන්කෙ", "meaning": "වැල් මුරුංගා", "category": "plant" },
    { "word": "පුණකාවිචෝරි", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "පුණ්‍යගන්ධ", "meaning": "සපු", "category": "plant" },
    { "word": "පුණේන්තව", "meaning": "සාරණ", "category": "plant" },
    { "word": "පුණමරම්", "meaning": "අහු ගස", "category": "plant" },
    { "word": "පුණරන්", "meaning": "දෙඹ", "category": "plant" },
    { "word": "පුණේක්කාලි", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "පුන්නම්පලම්", "meaning": "අස්මි අල", "category": "plant" },
    { "word": "පුතන", "meaning": "අරළු", "category": "plant" },
    { "word": "පුතිකා", "meaning": "රත් නිවිති", "category": "plant" },
    { "word": "පුත්‍ර", "meaning": "ලැවිය, බුත්සරණ", "category": "plant" },
    { "word": "පුත්‍රජීව", "meaning": "ගණ", "category": "plant" },
    { "word": "පුත්‍රජානී", "meaning": "වටුලැටිය", "category": "plant" },
    { "word": "පුත්‍රජාහනී", "meaning": "රසතැල්ල, ලප්තැල්ල", "category": "plant" },
    { "word": "පුත්‍රජාරී", "meaning": "යක්බේරිය, භූමිනාද", "category": "plant" },
    { "word": "පුත්‍රජීව (2)", "meaning": "බුත්සරණ, රත්කතුරා, ලකවැටිය", "category": "plant" },
    { "word": "පුත්‍රජීව ඇට", "meaning": "ලකවැටිය ඇට", "category": "plant" },
    { "word": "පුත්‍රදාරා", "meaning": "රසතැල්ල", "category": "plant" },
    { "word": "පුත්‍රජනනී", "meaning": "තුන්දර වැල්", "category": "plant" },
    { "word": "පුත්‍රී", "meaning": "බිම්නෙල්ලි", "category": "plant" },
    { "word": "පුත්‍රොඝා", "meaning": "පිල, හෙළ පිල", "category": "plant" },
    { "word": "පුදතම්පලා කොළ", "meaning": "තම්පලා වර්ගයක්", "category": "plant" },
    { "word": "පුදනමල්", "meaning": "පූජා කිරීමෙන් පසු අස්කළ මල්", "category": "plant" },
    { "word": "පුන්නාට", "meaning": "තෝර", "category": "plant" },
    { "word": "පුන්නාග", "meaning": "සාදික්කා, දෙඹ, හෙළ උපුල්", "category": "plant" },
    { "word": "පුන්නාටයනාම", "meaning": "දෙඹ කින", "category": "plant" },
    { "word": "පුණ්‍යගන්ධ (2)", "meaning": "සපු", "category": "plant" },
    { "word": "පුණ්‍යතෘණ", "meaning": "ඊතණ, කුසතණ, හෙළ ඊතණ", "category": "plant" },
    { "word": "පුණ්‍යලතා", "meaning": "රටලබු, වට්ටක්කා", "category": "plant" },
    { "word": "පුනග", "meaning": "දෙඹ ගස", "category": "plant" },
    { "word": "පුනත්‍ය", "meaning": "මසන්", "category": "plant" },
    { "word": "පුනදෙඹ", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "පුනනග", "meaning": "දිඹුල්", "category": "plant" },
    { "word": "පුනබෝ", "meaning": "දෙළුම් ගස", "category": "plant" },
    { "word": "පුනර්භව", "meaning": "රත්ගෙඳ, රත්සාරණ", "category": "plant" },
    { "word": "පුනර්භවා", "meaning": "සාරණ, මහ සාරණ, සුළු සාරණ, පිටසුදුපලා", "category": "plant" },
    { "word": "පුනාගකිරෙයි", "meaning": "සුළුනයි", "category": "plant" },
    { "word": "පුනාබු", "meaning": "හකුරු", "category": "food" },
    { "word": "පුනි", "meaning": "සිහින් අරත්ත, කුඩාකච්චා", "category": "plant" },
    { "word": "පුනුගු", "meaning": "උරුලෑසැපිටි", "category": "animal" },
    { "word": "පුනුගුසට්ටන්", "meaning": "උරුලෑසට්ටන්", "category": "animal" },
    { "word": "පුප්", "meaning": "මල", "category": "plant" },
    { "word": "පුප්පි", "meaning": "මිහිල", "category": "plant" },
    { "word": "පුප්මි", "meaning": "මීපැණි", "category": "food" },

    // --- පිටුව 311 ---
    { 
        "word": "පුපුල", 
        "meaning": "පුපුල ගස් සම දේශගුණය ඇති ප්‍රදේශවල වැවෙන පඳුරු වර්ගයකි. මේ ගස් වල මල් හා කොළ වාරණීය මල් සහ කොළ වලට සමාන ය. එහෙත් මේ කොළ වාරණීය කොළ පමණ ඝන නැත. ප්‍රාණවත් බව ද අඩු ය. පුපුල කොළ සහ පොතු ගන්දි වෙදකමේ ප්‍රධාන ඖෂධයකි. දේශීය වෙදකමේ නොයෙක් තෙල් වර්ග වලට මේ පොතු සහ කොළ වල යුෂ අවශ්‍ය වේ.", 
        "category": "plant",
        "image": "img_311_pupula.jpg"
    },
    { "word": "පුබෙබා", "meaning": "සාරව", "category": "plant" },
    { "word": "පුමන්කම්", "meaning": "අත්තන ගස", "category": "plant" },
    { "word": "පුමන්නේ", "meaning": "අත්තන", "category": "plant" },
    { "word": "පුරනබිජු", "meaning": "වලඟසාල්, බෝදිඇට", "category": "plant" },
    { "word": "පුර", "meaning": "හෙළඑරබු, අරත්ත, (රත්ත), ගුගුල්, කුන්දිරුක්කන්, ලප්නාරම්", "category": "plant" },
    { "word": "පුරතම්පය", "meaning": "සුදු දුරු", "category": "plant" },
    { "word": "පුරතකෝ", "meaning": "අබ", "category": "plant" },
    { "word": "පුරසල්", "meaning": "ලප්නාරම්", "category": "plant" },
    { "word": "පුරා", "meaning": "ඉන්සළු", "category": "plant" },
    { "word": "පුරාලකන්", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "පුරිසම්", "meaning": "රත්කෑල, කෑල", "category": "plant" },
    { "word": "පුරු", "meaning": "එළ එරබු, (නවගිලිය)", "category": "plant" },
    { "word": "පුරුෂ", "meaning": "දෙඹ, ගුගුල්", "category": "plant" },
    { "word": "පුරුෂදන්තීකා", "meaning": "මහමෙවන්", "category": "plant" },
    { "word": "පුරූෂපුකාශිෂ", "meaning": "කසිස්, (කාසිස)", "category": "mineral" },
    { "word": "පුරූෂම්", "meaning": "ගස්කෑලිය", "category": "plant" },
    { "word": "පුරූෂාන්වය", "meaning": "දෙඹ, මහ දෙඹ", "category": "plant" },
    { "word": "පුරූහත", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "පුරෙකකඤ්චිවෝඩි", "meaning": "වැල්‍කසඹිලියා", "category": "plant" },
    { "word": "පුරෛසං", "meaning": "එරමිණියා", "category": "plant" },
    { "word": "පුරෝවාස", "meaning": "මුවකිරිය", "category": "plant" },
    { "word": "පුල්", "meaning": "පුබුදු වීම", "category": "general" },
    { "word": "පුල්කිරෙයි", "meaning": "දියබෙරලිය", "category": "plant" },
    { "word": "පුල්කොළ", "meaning": "සෙන්කොට්ටම්, උපුල් කොළ", "category": "plant" },
    { "word": "පුල්ලෙකනතලෙයි", "meaning": "කොමාරිකා", "category": "plant" },
    { "word": "පුලනතී", "meaning": "කලිල්", "category": "plant" },
    { "word": "පුලන්දිය", "meaning": "කටුපිල", "category": "plant" },
    { "word": "පුලයාර්", "meaning": "පොල්කුඩුපලා", "category": "plant" },
    { "word": "පුලෂ්ටි", "meaning": "ගෙඳ", "category": "plant" },
    { "word": "පුලි", "meaning": "සියඹලා", "category": "plant" },
    { "word": "පුලිනුවක්කි", "meaning": "එළ එඬරු", "category": "plant" },
    { "word": "පුලියම්", "meaning": "සිනිබලා, සියඹලා", "category": "plant" },
    { "word": "පුලියමරම්", "meaning": "සිනිබලා, (සියඹලා) ගස", "category": "plant" },
    { "word": "පුලියාරෛ", "meaning": "ඇඹුල් ඇඹිලිය", "category": "plant" },

    // --- පිටුව 312 & 313 ---
    { "word": "පුලිල", "meaning": "පලොල්", "category": "plant" },
    { "word": "පුළු", "meaning": "හබලපෙති", "category": "food" },
    { "word": "පුවප්පරු", "meaning": "පොල්රු", "category": "plant" },
    { "word": "පුවප්පු", "meaning": "පොල්", "category": "plant" },
    { "word": "පුවක්", "meaning": "පුවක් ගස, (පූග)", "category": "plant" },
    { "word": "පුවක්ඇටියා", "meaning": "තුවාල වලට සහ බුලත්විට කෑමට පුවක් වෙනුවට පොතු ගන්නා කසට ගතියෙන් යුත් අඩි දහයක් පමණ උසට වැවෙන පඳුරු වර්ගයක්", "category": "plant" },
    { "word": "පුවකු", "meaning": "පුවක් ගස", "category": "plant" },
    { "word": "පුවගය", "meaning": "පුවක් ගස", "category": "plant" },
    { "word": "පුවටා", "meaning": "පුවටන්, පෝටාවැල්", "category": "plant" },
    { "word": "පුවතු", "meaning": "පුවක් ගස", "category": "plant" },
    { "word": "පුවාලු", "meaning": "ප්‍රවාලෙ වර්ණය පිණිස ගන්නා ලොකු කෙසෙල් ගෙඩි වර්ගයක්, ඇතැම් පළාත්වල කෝලිකුට්ටු කෙසෙල් වලට ද පුවාලු යයි කියති.", "category": "plant" },
    { 
        "word": "පුවඟු", 
        "scientific": "Aglaia Roxburghiana",
        "meaning": "Aglaia Roxburghiana- පුවඟු සහ සුවඳ පුවඟු යයි වර්ග දෙකකි. දිග-පළල අඟල් 4 x 1 1/2 කට වැඩි නොවූ එක ඉත්තේ කොළ හතර-පහ බැගින් ඇති, කහ පාට කුඩා මල් පොකුරු හා ඒවායින් සපදිල්ලා මල් කැකුළු පමණ ගෙඩි පොකුරු සෑදෙන ගස් වර්ගයකි පුවඟු. සුවඳ පුවඟු දිග-පළල අඟල් 1 1/4 x 3/4 කට වඩා විශාල නොවූ කොළ ඇති මිහිරි සුවඳකින් යුත් කහ පාටින් යුත් පුවඟු වලට වඩා කුඩා මල් පොකුරු හටගන්නා වර්ගයකි. පුවඟු ඉන්දියාවේ හා ලංකාවේ වනාන්තර වල වැවෙන වර්ගයකි. සුවඳ පුවඟු ඉන්දියාවෙන් ගෙනැවිත් මෑතකදී බෝ කරණ ලද්දකි. \n\nපුවඟු - රුක්\nපුවඟු ගෙඩි වෙනුවට ලංකාවේ පාවිච්චි කරන්නේ රුක් මල් (ගෙඩි) ය. රුක් ගස වනාහී දිග-පළල අඟල් 10 x 3 1/2 කට වැඩි නොවූ කොළ ඇති, වැලි අනෝදා ගෙඩියක පිටපැත්ත මෙන් ගැට සහිත, ලොකු කඩල ඇට ප්‍රමාණ මල් සෑදෙන ගසකි. අතුවල හා කඳෙහිත් තට්ටුවල සෑදෙන මේ මල් පොකුරු අමුවෙන් (පිපෙන්ට පළමුව) නිල්පාට ය. පැසුන (මේරූ) විට රන්වන් පාට ය. පිපුනාම මේ මල් වලින් ද සුවඳ පුවඟු මල් වලට සමාන සුවඳක් නික්මෙයි. රුක් ගස් වල ගෙඩි හටගන්නේ මේ මල් පොකුරු වලින් නොවේ. අතු දිගට වෙන වෙන ම ය. \n\nපුවඟු-රුක් දෙවර්ගය ම මෙම දිවයිනෙහි තිබියදී පුවඟු ගෙඩි වෙනුවට රුක් මල් ගැනීම අනාදිමත් කාලයක සිට අපේ දේශීය වෛද්‍යවරයන් විසින් කරගෙන එන ක්‍රියාවකි. මෙය නො දැනුමක්-නුගත් කමක් හෝ වැරදීමක් නිසා සිදුවූවකැයි ඉවත දැමීමට පෙර මඳක් විමසා බැලිය යුතුව තිබේ. රාවණ සමයේ සිට සිංහල රාජ්‍යයේ අවසානය දක්වා උගත්කමින් හා කෘතහස්ත භාවයෙන් ද අනූන වූ වෛද්‍ය පරම්පරාවලින් මේ ලක්දිව හිස් නොවූ බව ඓතිහාසික සිදුවීම් අනුව නිගමනයකට බැසීමට ඉඩ ඇති හෙයිනි. \n\nපුවඟු-සුවඳ පුවඟු දෙවර්ගයෙන් සුවඳ පුවඟු ගුණයෙන් අධික බව ප්‍රකට කරුණකි. සුවඳ පුවඟු මල් (ගෙඩි) හා රුක්මල් (ගෙඩි වැනි මල්) ද වර්ණයෙනුත් සුවඳිනුත් එක සමාන ය. එකල සුවඳ පුවඟු ඉන්දියාවේ මිස ලංකාවේ තිබුණේ නැත. එය මෑතකදී මෙහි බෝකරණ ලද්දකි. එම නිසා සුවඳ පුවඟු සපයා ගන්නට නො හැකිවූ විට ඊට ප්‍රතිනිධි වශයෙන් පුවඟු ගෙඩි වලට වඩා රුක්මල් ගැනීම සුදුසු යයි කරණ ලද පරීක්‍ෂණ අනුව සම්මත කරගන්ට ඇතැයි සිතුවොත් වැරදිද? \n\nදුරාලභා - දාරුහරිද්‍රා - රක්ත චන්දන ආදී විදේශික ඖෂධ වෙනුවට ප්‍රතිනිධි වශයෙන් ගැනීමට ඉන්දියානු වෛද්‍යවරයන් විසින් කරණ ලද නියමයන්ට වෙනස් ඖෂධ වර්ග මේ රටේ පාවිච්චි කිරීම ද මෙයට සාක්‍ෂියකි. \n\nපුවඟු වෙනුවට රුක්මල් ගැනීම හරි හෝ වැරදි යයි ස්ථිරලෙස ම සම්මත කළ හැක්කේ පුවඟු - සුවඳ පුවඟු හා රුක්මල් පිළිබඳ විද්‍යානුකූල පරීක්‍ෂණයක් කිරීමෙන් පසුව මිස එක එක්කෙනා ලියා තිබෙන අතක් මනක් වලින් නොවේ.", 
        "category": "plant",
        "image": "img_312_puwangu.jpg"
    },

    // --- පිටුව 314 ---
    { "word": "පුවොදනී", "meaning": "කටුවැල් බටු", "category": "plant" },
    { "word": "පුෂ්කර", "meaning": "පුස්කර, නෙළුම්, කොට්ටම්", "category": "plant" },
    { "word": "පුෂ්කල", "meaning": "මිටට ගන්නා ප්‍රමාණ හැට හතරක්, උරැලෑවා", "category": "measurement" },
    { "word": "පුෂ්ටිවරා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "පුෂ්ටිදා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "පුෂ්පචුෂරි", "meaning": "සුදු උක් ගස", "category": "plant" },
    { "word": "පුෂ්ප බැවිල", "meaning": "හීවේර", "category": "plant" },
    { "word": "පුෂ්පකප්පූරි", "meaning": "කොට්ටම්, අබ, මෑලිගම්", "category": "plant" },
    { "word": "පුෂ්පරාන්වය", "meaning": "අමුකපුරු", "category": "plant" },
    { "word": "පුෂ්පරොචක", "meaning": "නාමල් රේණු", "category": "plant" },
    { "word": "පුෂ්පරෝග", "meaning": "ලියනගලා", "category": "plant" },
    { "word": "පුෂ්පලතා", "meaning": "කොමඩු වැල, පත්තක්කා වැල, පුහුල් වැල", "category": "plant" },
    { "word": "පුෂ්පලා", "meaning": "දුරියන් (ජූලියන් ගස).", "category": "plant" },
    { "word": "පුෂ්පවාන්", "meaning": "මුරුවා ගස", "category": "plant" },
    { "word": "පුෂ්පවාස", "meaning": "පියල්", "category": "plant" },
    { "word": "පුෂ්පශාධනරා", "meaning": "ලියනගලා, මේ මායේ අල ද්‍රැව ප්‍රසවයේදී පතුල් වල ගෑමට භාවිත කෙරෙයි.", "category": "plant" },
    { "word": "පුෂ්පසනු", "meaning": "මී පැණි", "category": "food" },
    { "word": "පුෂ්පසාර", "meaning": "මී පැණි", "category": "food" },
    { "word": "පුෂ්පසූත්‍ය", "meaning": "දිඹුල්", "category": "plant" },
    { "word": "පුෂ්පාඤ්ජන", "meaning": "මල් අඳුන්", "category": "mineral" },
    { "word": "පුෂ්පාම්ල", "meaning": "සියඹලා", "category": "plant" },
    { "word": "පුෂ්පාහ්වා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "පුෂ්පිකා", "meaning": "මස්වැන්න, යක්බේරිය", "category": "plant" },
    { "word": "පුෂ්බට්ට", "meaning": "පුස්වැලේ ඇටයට ඇතැමෙක් මෙසේ කියති. මේ ඇට මද ග්‍රන්ථි ශෝථවලට ගනු ලැබේ", "category": "plant" },
    { "word": "පුෂ්පරේචන", "meaning": "නාමල් රේණු", "category": "plant" },
    { "word": "පුෂ්‍යලතා", "meaning": "පුහුල්වැල", "category": "plant" },
    { "word": "පුස්විල", "meaning": "වසතැල්ල, දියමිත්ත කොළවලට සමාන කොළ ඇති මේ වැල් වර්ගය කටු ඇනුනාම කහ-ලූණු ලා කොටා මලවා බඳිනු. සුව වේ.", "category": "plant" },
    { "word": "පුස්තා", "meaning": "පුස්ඇට, නා ඇට", "category": "plant" },
    { "word": "පුස්පකාමල:", "meaning": "කොසඹ", "category": "plant" },
    { "word": "පුස්පන්", "meaning": "මහ සාරණ", "category": "plant" },
    { "word": "පුස්පන්වය", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "පුස්පරා", "meaning": "අත්තන", "category": "plant" },
    { "word": "පුස්පසේකර", "meaning": "මී පැණි", "category": "food" },
    { "word": "පුස්පා", "meaning": "රුක්මල", "category": "plant" },
    { "word": "පුස්පි", "meaning": "එරබදු", "category": "plant" },
    { "word": "පුස්මකණ්ටකාලි", "meaning": "ඉඹුල් මැලියම්", "category": "plant" },
    { 
        "word": "පුස්වැන්න", 
        "meaning": "පෘෂ්ණිපර්ණී = ත්‍රිපර්ණී = ක්‍රොෂ්ටුවින්නා, නරි වලිගයක් වැනි මලක් සෑදෙන එක නැටුවේ දිගටි හැඩයෙන් යුත් කොළ තුනක් බැගින් ඇති පැලෑටියකි. පෘෂ්ණිපර්ණී වල හැඩහුරුකම මෙසේ සවිස්තරව දක්වා තිබියදීත් සරස්වතී නිඝණ්ඩුව ඇතුළු බොහෝ පොත් වල වර්ග දෙකක් වශයෙන් වෙන් වෙන්ව විස්තරකර තිබිය දීත් මේ වර්ගයට සමාන කිසිම ලක්‍ෂණයක් නැති පොල්පලා, පුස්වැන්න (පෘෂ්ණිපර්ණී) වෙනුවට ගැනීම තේරුම් ගත නො හැකි ප්‍රකට කරුණකි. එසේම පුස්වැන්න පැලෑටි මේ රටේ සුලභව තිබේ. පෘෂ්ණිපර්ණී උෂ්ණ-අතිසාර රෝග නාශක ඖෂධයකි.", 
        "category": "plant" 
    }
];

