// data_135_143.js - පිටු 135 සිට 143 දක්වා සියලුම වචන
const data_extra_135_143 = [
  // --- පිටුව 135 (image_87ddc0.jpg) ---
  { "word": "කෛරවිනීඵල", "meaning": "උපුල් ඇට", "category": "plant" },
  { "word": "කෛරවී", "meaning": "උවනාල්", "category": "plant" },
  { "word": "කෛරාතක", "meaning": "කණේරු ගස", "category": "plant" },
  { "word": "කෛරාත", "meaning": "බිංකොහොඹ", "category": "plant" },
  { "word": "කෛරාතක", "meaning": "බිංකොහොඹ", "category": "plant" },
  { "word": "කෛරාල", "meaning": "වලඟසාල්, බිංකොසඹ", "category": "plant" },
  { "word": "කෛරාලී", "meaning": "වලඟසාල්, බිංකොසඹ", "category": "plant" },
  { "word": "කෛවර්ත", "meaning": "වල්කොසඹ", "category": "plant" },
  { "word": "කෛවර්තී", "meaning": "කලාඳුරු, දියෙහි සෑදෙන කලාඳුරු විශේෂයක්", "category": "plant" },
  { "word": "කෛවර්තමුස්තකා", "meaning": "මූරු, දියකලාඳුරු, (දියෙහි සෑදෙන කලාඳුරු විශේෂයක්)", "category": "plant" },
  { "word": "කෛවර්තීමුස්තා", "meaning": "මූරු, දියකලාඳුරු, (දියෙහි සෑදෙන කලාඳුරු විශේෂයක්)", "category": "plant" },
  { "word": "කෛවර්තිකා", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "කෛවර්ය", "meaning": "කපු ගස", "category": "plant" },
  { "word": "කෛවල", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "කෛයසිකා", "meaning": "ඇම්බරැල්ල ගස", "category": "plant" },
  { "word": "කොක්කටිමරම්", "meaning": "උග්‍රකපුරුගස්", "category": "plant" },
  { "word": "කොක්කාලි", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "කොක්කුමඤ්ජරේසි", "meaning": "කොබෝලිල", "category": "plant" },
  { "word": "කොක්මොට", "meaning": "දියමුසු භූමවල (කුඹුරුවල) බොහෝ සේ ගොයම් සමග වැවෙන වගියක්", "category": "plant" },
  { "word": "කොක්සි", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "කොක", "meaning": "කිණිහිරි, කිඳි, බින්තල්, ඉදිකුළු", "category": "plant" },
  { "word": "කොකකාලි", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "කොකටී", "meaning": "රන්කිරිගොකටු", "category": "plant" },
  { "word": "කොකටිය", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "කොකනද", "meaning": "රත් නෙළුම්, රත් මානෙල්, (රත්පුල්) හෙල පියුම්", "category": "plant" },
  { "word": "කොකවිසල්", "meaning": "රක්ත චන්දන", "category": "plant" },
  { "word": "කොකාක්‍ෂි", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "කොකාග්‍ර", "meaning": "කිබරම් වෙසෙසක්", "category": "plant" },
  { "word": "කොකිල", "meaning": "බැබරගෙඩිය", "category": "plant" },
  { "word": "කොකිලච්ඡි", "meaning": "පලොල්, හෙල පලොල්", "category": "plant" },
  { "word": "කොකිලනයන", "meaning": "ඉකිරි ගස", "category": "plant" },
  { "word": "කොකිලා", "meaning": "මසන්, රත් පලොල්", "category": "plant" },
  { "word": "කොකිලාක්‍ෂ", "meaning": "නිරමුල්ලිය, වැලුක්, රඹුක්", "category": "plant" },
  { "word": "කොකිලාවාස", "meaning": "අඹ", "category": "plant" },
  { "word": "කොකිලෙක්ෂු", "meaning": "කළු උක් ගස, ඉඟිරිගස", "category": "plant" },
  { "word": "කොකිලෙෂ්ට", "meaning": "මාදම් ගස", "category": "plant" },
  { "word": "කොකිලෝත්සව", "meaning": "අඹ ගස", "category": "plant" },
  { "word": "කොකුන්ද ගත්තේ", "meaning": "පුස් ඇට", "category": "plant" },
  { "word": "කොකුපණු", "meaning": "පාණ්ඩු රෝගයට හේතුවන ක්ෂුද්‍ර ප්‍රාණී විශේෂය.", "category": "symptom" },

  // --- පිටුව 136 (image_87dddb.jpg) ---
  {
    "word": "කොකුම්",
    "scientific": "Kokuna Zeylanicum",
    "meaning": "මෙය ලංකාවේ අඩි 150 ක් දක්වා උසට වැවෙන විශාල වෘක්ෂයකි. ගසට වැදෙන සුව පහරකින් ඇතිවන කම්පනයකින් පවා මේ ගසේ පොත්ත ගැලවී වැටෙයි. ඇතුළු පැත්ත තද කසා වර්ණයකින් යුත් මේ පොතු සිහින් වෙන්ට අඹරා වතුරත් සමග මිශ්‍ර කර පෑතැලි සබන් කෑලි මෙන් සකස් කොට අලෙවි කරනු ලබති. ඇතැම් පළාත්වල ස්ත්‍රී පුරුෂ දෙ පක්ෂය ම ජලස්නානය කරන විට මේ කෑලි සබන් වෙනුවට පාවිච්චි කරති. මේ කොකුම් පොතු කල්කය අංග රාගය ඇති කරන, රූප ලාවන්‍යය ගෙන දෙන සමේ විෂ බීජ නසන ඖෂධයකි. සබන් ගැන දැන ගැනීමට කලින් ලාංකිකයන් විසින් මේ කොකුම් පොතු කල්කය ඒ වෙනුවට පාවිච්චි කරන ලද බව පැරණි පොත පතින් පෙනේ. මොරටු වැඩි වශයෙන් වාසය කරන්නේත්, බිත්තර දමා පැටවුන් ඇති කර ගන්නේත් මේ ගස් මුදුන්හි සාදා ගන්නා කූඩුවල ය. වහා පොත්ත ගැලවෙන මේ ගස්වලට ඒ පක්ෂීන්ගේ සතුරන් වන උනහපුළුවන් ආදී සතුන්ට නිශ්ශබ්දව යාම දුෂ්කර හෙයින් ඔවුන්ගෙන් ආරක්ෂාවීම සඳහා මේ වර්ගයේ ගස් ම තෝරා ගන්නවා විය හැක.",
    "category": "plant"
  },
  { "word": "කොකුමිපිපි", "meaning": "යොන්තුඹ", "category": "plant" },
  { "word": "කොකුමරම්", "meaning": "කිණිහිරි", "category": "plant" },
  { "word": "කොකුනා", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "කොඩිකුමරම්", "meaning": "කිණිහිරි ගස", "category": "plant" },
  { "word": "කොච්චි", "meaning": "කුඩා මිරිස් (නයි මිරිස්)", "category": "plant" },
  { "word": "කොව", "meaning": "කුරඳු පොතු", "category": "plant" },
  { "word": "කොවකා", "meaning": "උන්සස, සිවිය, ගජතිප්පිලි", "category": "plant" },
  { "word": "කොවිපර්ණිකා", "meaning": "ගජතිප්පිලි, සිවිය", "category": "plant" },
  { "word": "කොට්ටංකානෙයි", "meaning": "වෙලඹුබ (මුඛ මඟණ)", "category": "plant" },
  { "word": "කොට්ටකුන්තිපුල්", "meaning": "තුත්තිරි", "category": "plant" },
  { "word": "කොට්ටම්", "meaning": "උපුල් කොළ, සෙන් කොට්ටම්", "category": "plant" },
  { "word": "කොට්ටාකරන්තෙකෙ", "meaning": "මුඛමඟණ", "category": "plant" },
  { "word": "කොට්ටික්කසිර", "meaning": "ලේ හා වාතය ද නිසා දණහිස්ව ඉදිමෙන රෝගයක්", "category": "symptom" },
  { "word": "කොට", "meaning": "කෝවක්කා, පුවක්ගස", "category": "plant" },
  { "word": "කොටජ්", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කොටද", "meaning": "කෙළිඳ, කෙළිඳ ඇට", "category": "plant" },
  { "word": "කොටපර්ණිකා", "meaning": "තිප්පිලි මුල්", "category": "plant" },
  { "word": "කොටර්", "meaning": "කිණිහිරි, ගැටනිවුල්", "category": "plant" },
  { "word": "කොටපුෂ්පි", "meaning": "ගිරිනීල්ල (මාබණ්ඩා)", "category": "plant" },
  { "word": "කොටර්වාහිනී", "meaning": "සුදු හුන්සවාලු", "category": "plant" },
  { "word": "කොටරි", "meaning": "ගැටනිවුල් ගස", "category": "plant" },
  { "word": "කොටසිබිලි", "meaning": "කොවඩුඹුල", "category": "plant" },
  { "word": "කොටි", "meaning": "කබල, පික්මල්, ගැටපිච්ච, කෙළිඳ", "category": "plant" },
  { "word": "කොටිකා", "meaning": "ගොලපුවක්, කරංකාගෙඩි, කලන්තුන, කඩල", "category": "plant" },
  { "word": "කොටිකාවක්", "meaning": "කලන් තුනක බර", "category": "treatment" },
  { "word": "කොටිල්ලු", "meaning": "ගැටපිච්ච", "category": "plant" },
  { "word": "කොටිවල්ලා", "meaning": "පික්මල්", "category": "plant" },
  { "word": "කොටිවැක්ෂක", "meaning": "කෙළිඳ ඇට (කෙළිඳ ගස)", "category": "plant" },
  { "word": "කොටිසූණු", "meaning": "කටුවැල්බටු කුඩු", "category": "treatment" },
  { "word": "කොටොදුම්බර", "meaning": "දිවුල් ගස", "category": "plant" },

  // --- පිටුව 137 (image_87dde1.jpg) ---
  { "word": "කොටොල් අල", "meaning": "කොබෝල් අල", "category": "plant" },
  { "word": "කොඩ", "meaning": "වක්‍රාකාර කුෂ්ඨ විශේෂ (දද) යක්", "category": "symptom" },
  { "word": "කොඩර්", "meaning": "රැකහුහණ", "category": "plant" },
  { "word": "කොඩිමූඳුරි", "meaning": "මිදිවැල", "category": "plant" },
  { "word": "කොඩි", "meaning": "මල්", "category": "plant" },
  { "word": "කොඩිඅඩම්බෙයි", "meaning": "බිමිතබුරා", "category": "plant" },
  { "word": "කොඩිකල්ලී", "meaning": "රටදළක්", "category": "plant" },
  { "word": "කොඩිකාරෙයි", "meaning": "කුඹුරු වැල්", "category": "plant" },
  { "word": "කොඩිකල්ලි", "meaning": "මුවකිරිය", "category": "plant" },
  { "word": "කොඩිතූම්බෙයි", "meaning": "වැල්තුඹ", "category": "plant" },
  { "word": "කොඩිමුරුක්කෙයි", "meaning": "වැල්මුරංගා", "category": "plant" },
  { "word": "කොඩියාකුන්තල්", "meaning": "බිමිතලු", "category": "plant" },
  { "word": "කොඩිවේලි", "meaning": "රක්නිටුල්", "category": "plant" },
  { "word": "කොඩස්", "meaning": "දසපුර", "category": "plant" },
  { "word": "කොඩොල්", "meaning": "නායක", "category": "treatment" },
  { "word": "කොත්තමල්ලි", "meaning": "කොත්තඹුරු", "category": "plant" },
  {
    "word": "කොතලහිඹුටු",
    "scientific": "Salacia Reticulata",
    "meaning": "හිඹුටු, කොතල හිඹුටු යයි හිඹුටු වර්ග දෙකකි. දිය සිරාව සහිත තැන්වල පඳුරු වශයෙන් වැවෙන මේ දෙවර්ගයේ ම කොළ සහ මල් එක සමාන ය. එහෙත් කොතල හිඹුටු වැලේ මුල පෙති තට කැපූ විට ලා රත් පාටින් යුත් රවුම් හැඩයේ රේඛා බෙදී ඇත. හිඹුටු වැල එසේ කැපූවිට ඇතුළත එක ම සුදු වර්ණයෙන් යුක්ත ය. දෙවර්ගයේ ම වැල්වල පොත්ත කහපාට ය. බෙහෙත් කටු වල කොතල හිඹුටු, හිඹුටු දෙවර්ගයේ ම මුල් එක ම කොතලා හිඹුටු මුල් වශයෙන් විකිණීමට තබා ඇත. කොතල හිඹුටු වැල් තේරීමේදී ඒ වැල් ගිරයෙන් පෙත්තට කපා බලා ඇතුළු පැත්ත ලා රත් පැහැයෙන් යුත් වර්ගය පමණක් කොතල හිඹුටු වශයෙන් තෝරා ගත යුතුය. මේ වර්ගයේ මුලේ සාරය පිපාසය සංසිඳුවීම පිණිසත් මුත්‍ර අධිකත්වය (දියවැඩියා රෝගය) සංසිඳුවීම පිණිසත් ලාංකික වෛද්‍ය පරම්පරා වල භාවිතා කරගෙන එයි. දියවැඩියා රෝගය සඳහා ගතයුතු ඖෂධය කොතල හිඹුටු නොව කොතලා කෙමිය යයි ද ඇතැම් අය අතර පවත්නා තවත් මතයකි.",
    "category": "plant"
  },

  // --- පිටුව 138 (image_87e087.jpg) ---
  { "word": "කොත්තා", "meaning": "වැල්පෙනෙල", "category": "plant" },
  { "word": "කොත්තාලෙයි", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "කොත්තඹුරු", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "කොතලා", "meaning": "කොතලාවැල්", "category": "plant" },
  { "word": "කොතලාකෙමිය", "meaning": "මුත්‍ර රෝගයට කොතලා හිඹුටු වලට වඩා මේ වැලේ සාරය උසස් යයි ඇතැම් වෛද්‍යවරයෝ කියති.", "category": "plant" },
  { "word": "කොතුරැබැද්ද", "meaning": "මීකන්පලා (මූෂික පර්ණී)", "category": "plant" },
  {
    "word": "කොද",
    "meaning": "කොද, වැකොද යයි කොද වගී දෙකකි. එකක් (කොද) අඩියක් පමණ ජලය ඇති මඩ සහිත කුඹුරු වලත් වඩා ගැඹුරු නැති වැව් වලත් හටගන්නා උත්පලාදී ගණයට අයත් සුදු පැහැති කුඩා මල් හටගන්නා වගියකි. අනික (වැකොද) දිරා ගිය මහ ගස් වල හෝ පොළොවෙහි හට ගන්නා ගැටපිච්ච වලට සමාන වැල් සහ දෑසමන් මල් වලට සමාන මල් ඇති වගියකි. මේ දෙවර්ගය ම පිපෙන්නේ සවසටයි. මිය ලය ප්‍රබෝධවන සුවඳින් යුක්තයි. කවි සමයේ කොද කැකුළු වලට ලලනාවන්ගේ දත් උපමා කර තිබෙන්නේ දෑකැති ව කිව්වීයේ (වැකොද) මල් කැකුළු වලට ය. මේවාට පිවිසර වැසියෝ වල්පිච්ච කියා ද කියති.",
    "category": "plant"
  },
  { "word": "කොදුප්පු", "meaning": "අමු (ධාන්‍ය වගියක්)", "category": "plant" },
  { "word": "කොඩුව", "meaning": "අමු", "category": "plant" },
  { "word": "කොඩුවික", "meaning": "සුවස ලුණු", "category": "treatment" },
  { "word": "කොද්‍රාණි", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "කොන්නෙ", "meaning": "ඇසල", "category": "plant" },
  { "word": "කොණ්ඩකාරත්තෙයි", "meaning": "කමිලා (ජමනාරන්)", "category": "plant" },
  { "word": "කොනවළු", "meaning": "බකල", "category": "symptom" },
  { "word": "කොනල", "meaning": "මිදි", "category": "plant" },
  { "word": "කොනලරික", "meaning": "කවන්තස්ස", "category": "treatment" },
  { "word": "කොපනක", "meaning": "හිඟුරුපියලි, සුවඳකසා", "category": "plant" },
  { "word": "කොපනය", "meaning": "හොරගුටි, කවිටකුමන්ජල්", "category": "plant" },
  { "word": "කොපනා", "meaning": "රතු කණේරු", "category": "plant" },
  { "word": "කොපපුෂ්ප", "meaning": "කටුපිල", "category": "plant" },
  { "word": "කොපු", "meaning": "ළිඳ", "category": "treatment" },
  {
    "word": "කොබ්බෑ",
    "meaning": "පෙනුමෙන් හා හැඩහුරුකමින් ලුණුවරණ ගසේ දළු වලට හා කොළ වලට මඳක් සමාන මේ පඳුරු වගිය දේශීය කැඩුම්-බිඳුම් වෙදකමේ උසස් ම ඖෂධයකි. බිඳුණ ඇට පෑස්සීම, තැලුම් හා ඉදිමුමටත් ගන්නා ඖෂධ යෝගවලට මේ ගසේ පොතු ද ඇතුළත් ය.",
    "category": "plant"
  },

  // --- පිටුව 139 (image_87e0a2.jpg) ---
  { "word": "කොබලීල", "meaning": "කොවිලාර (කොබෝලිල)", "category": "plant" },
  { "word": "කොබවක්කා / කොබේවක්කා", "meaning": "නිතිග = කෙම් වැල්, = කොබෝමැල්ල = කෝවක්කා, සූ යයි කාන්ත", "category": "plant" },
  { "word": "කොබිවිකා", "meaning": "කෝවක්කා, රසකිඳ", "category": "plant" },
  { "word": "කොබු", "meaning": "කෝන් (කුබුක්)", "category": "plant" },
  { "word": "කොබුක්", "meaning": "කෝන් ගස", "category": "plant" },
  { "word": "කොම්මෙයි", "meaning": "කෝවක්කා", "category": "plant" },
  { "word": "කොඹුකල්ලි", "meaning": "නවනන්දි", "category": "plant" },
  { "word": "කොම්මඩු", "meaning": "කුෂ්මාණ්ඩ, පුහුල්", "category": "plant" },
  { "word": "කොමලක", "meaning": "පද්මකාෂ්ඨ", "category": "treatment" },
  { "word": "කොමලනාලිකේර", "meaning": "කුරැම්බා", "category": "plant" },
  { "word": "කොමිලපත්‍රකා", "meaning": "මුරංගා ගස", "category": "plant" },
  { "word": "කොමලපුසව", "meaning": "එල ගිරිනීල්ල", "category": "plant" },
  { "word": "කොමලවල්කලි", "meaning": "ලාවුළු, බිලිංගස", "category": "plant" },
  { "word": "කොමිලා", "meaning": "කිරිපලු ගස, ඉඳිගස", "category": "plant" },
  { "word": "කොමිවෙදකම", "meaning": "ගෝමේද", "category": "treatment" },
  { "word": "කොමුල්", "meaning": "දෙමට", "category": "plant" },
  { "word": "කොමුක", "meaning": "මසන්", "category": "plant" },
  { "word": "කොර", "meaning": "තකුල්, තෙවබල, තෙවම අල (තෙවමුදුල = මාංකාල)", "category": "plant" },
  { "word": "කොරකා", "meaning": "කැකුළු, තෙවම අල, තකුල්", "category": "plant" },
  { "word": "කොරකාමාංස", "meaning": "අගුණ(කර) ගස", "category": "plant" },
  { "word": "කොරකාසරා", "meaning": "වම්මුතු, මගවම්මුතු", "category": "plant" },
  { "word": "කොරගා", "meaning": "නෙල්ලි, ඇඹුල්වැල", "category": "plant" },
  { "word": "කොරබිනි", "meaning": "තිප්පිලි (වගපුල්) සිත් එන්සාල්", "category": "plant" },
  { "word": "කොරණ්ටි", "meaning": "බැබර ගස", "category": "plant" },
  { "word": "කොරණ්ඩ", "meaning": "කටුකරඬු", "category": "plant" },
  { "word": "කොරද්‍රැක", "meaning": "අමු (ධාන්‍ය වගියක්)", "category": "plant" },
  { "word": "කොරඹි", "meaning": "මසන් (බැබර)", "category": "plant" },
  { "word": "කොරල", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "කොරස", "meaning": "මසන් (බැබර)", "category": "plant" },
  { "word": "කොරසවැල්", "meaning": "තද රළු ගතියකින් යුත් මේ වැලේ කොළ ඇඟ ගෑවුනොත් සීරෙන පමණ ගොරෝසු ගතියකින් යුක්ත ය. මේ වැල් වලින් මිරිකා ගන්නා යුෂ කොළසන්නි රෝගයට නස්‍ය සඳහා ප්‍රත්‍යක්ෂ ඖෂධයකි.", "category": "plant" },
  { "word": "කොරැඇසියා", "meaning": "ගස් වගියක්", "category": "plant" },
  { "word": "කොරාසානි", "meaning": "අබ වගියක්", "category": "plant" },
  { "word": "කොරිම්ද", "meaning": "ඇත්දෙමට ගස", "category": "plant" },
  { "word": "කොල්ලන්තකොලෙයි", "meaning": "කොල්ලන් කොළ, උපුල් කොළ", "category": "plant" },
  { "word": "කොල්ලම්", "meaning": "නමලු", "category": "treatment" },
  { "word": "කොල්ලගස", "meaning": "පතොක් ගස්, ගලිස ගස්", "category": "plant" },
  { "word": "කොල්ලු", "meaning": "කලත්", "category": "plant" },
  { "word": "කොල", "meaning": "තිවුල් ගස, තකුල්, රක්කාගුණ, ගජතිප්පිලි, කොල්ලු, ලෝලු, සිවිය, ගම්මිරිස්, සිද්ධිගුරු", "category": "plant" },
  { "word": "කොලං", "meaning": "කපුකින", "category": "plant" },
  { "word": "කොලකා", "meaning": "අඟුණ, ලෝලු, මිරිස්, කපුකිනිස්ස", "category": "plant" },
  { "word": "කොලකිට්ටිකා", "meaning": "යොන්තුඹ", "category": "plant" },
  { "word": "කොලකගෙරැකා", "meaning": "කලාඳුරු", "category": "plant" },
  { "word": "කොලකා", "meaning": "වඳුරුමෑ", "category": "plant" },
  { "word": "කොලකි", "meaning": "සින්බෙබර", "category": "plant" },
  { "word": "කොලගනි", "meaning": "ඇත්වගපුල්", "category": "plant" },
  { "word": "කොලසොබා", "meaning": "බැබර විශේෂයක්", "category": "plant" },
  { "word": "කොලබික", "meaning": "නෙල්ලි ගස", "category": "plant" },
  { "word": "කොළබි", "meaning": "එන්සාල්", "category": "plant" },

  // --- පිටුව 140 (image_87e0a8.jpg) ---
  { "word": "කොලට", "meaning": "කොට්ටන්", "category": "plant" },
  { "word": "කොලතු", "meaning": "අත්ත, ශාඛාව", "category": "treatment" },
  { "word": "කොලදල", "meaning": "නබි නම් සුවඳ ද්‍රව්‍යය", "category": "treatment" },
  { "word": "කොලනාගිකා", "meaning": "වධකිනි නම් වාක්‍යය", "category": "treatment" },
  { "word": "කොලපුෂ්ප", "meaning": "කටුපිල", "category": "plant" },
  { "word": "කොලඵල", "meaning": "බැබර", "category": "plant" },
  { "word": "කොලබිම්බිකා", "meaning": "කෝවක්කා", "category": "plant" },
  { "word": "කොලබු", "meaning": "දම්ගෙඩිය", "category": "plant" },
  { "word": "කොලමාරි", "meaning": "තකුල්", "category": "plant" },
  { "word": "කොලමුල", "meaning": "තිප්පිලි මුල්", "category": "plant" },
  { "word": "කොලඹ", "meaning": "කොලොම්", "category": "plant" },
  { "word": "කොලරික", "meaning": "පුවඟු", "category": "plant" },
  { "word": "කොලවල්ලි", "meaning": "සිවිය, ගජතිප්පිලි", "category": "plant" },
  { "word": "කොලවල්ලිකා", "meaning": "සිවිය, ගජතිප්පිලි", "category": "plant" },
  { "word": "කොලමුලි", "meaning": "තිප්පිලි මුල්", "category": "plant" },
  { "word": "කොලා", "meaning": "තිප්පිලි, සිවිය, මහ මුඛ මඟණ", "category": "plant" },
  { "word": "කොලාහල", "meaning": "මුඛ මඟණ", "category": "treatment" },
  { "word": "කොලි", "meaning": "බැබර", "category": "plant" },
  { "word": "කොලිකරමල්", "meaning": "කුකුල් කරමල් නම් තඹපලා වගිය", "category": "plant" },
  { "word": "කොලු", "meaning": "කුඩා බටු ගස", "category": "plant" },
  { "word": "කොලුන්තු", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කොලොග", "meaning": "අරළු", "category": "plant" },
  { "word": "කොලොගි", "meaning": "කඳය", "category": "treatment" },
  { "word": "කොලොස්", "meaning": "කැකුණ මල", "category": "plant" },
  { "word": "කොලොෂා", "meaning": "තිප්පිලි", "category": "plant" },
  { "word": "කොට්ටිවේ", "meaning": "කෝවක්කා වැල්", "category": "plant" },
  { "word": "කොවාරි", "meaning": "ඉරමුසු", "category": "plant" },
  { "word": "කොවිද්‍ර", "meaning": "(කොවිලාර) කොබෝලිල (එරබදු)", "category": "plant" },
  { "word": "කොගා", "meaning": "නැවැත්ත මුල්", "category": "plant" },
  { "word": "කොගිත්", "meaning": "අඹ ගස", "category": "plant" },
  { "word": "කොගිරපුෂ්ප", "meaning": "තිරිමුරැවා වැල්", "category": "plant" },
  { "word": "කොෂ්ඨෙක්ෂු", "meaning": "සුදු උක් ගස", "category": "plant" },
  { "word": "කොෂ්ඨ", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "කොෂ", "meaning": "සාදික්කා, කොට්ටන්", "category": "plant" },
  { "word": "කොෂඵල", "meaning": "කළු ත්‍රස්තවාලු, තකුල්, වැල්පෙනෙල, සාදික්කා, වැටකොළු", "category": "plant" },
  { "word": "කොෂලත්කිරෙහි", "meaning": "කොහිල", "category": "plant" },
  { "word": "කොෂවති", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "කොෂාතකි", "meaning": "වැටකොළු, තිත්ත වැටකොළු, දේවදාලිය වැල්", "category": "plant" },
  { "word": "කොෂාධිපත්‍රිනි", "meaning": "පලොල්, දුම්මැල්ල, පුලිල", "category": "plant" },
  { "word": "කොෂාඵල", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "කොෂක", "meaning": "තිප්පිලි", "category": "plant" },
  { "word": "කොෂඵල", "meaning": "කපුකිනිස්ස, පණිස, (කොස්)", "category": "plant" },
  { "word": "කොසමඟ", "meaning": "කොසඹ", "category": "plant" },
  { "word": "කොසයප්ල", "meaning": "කපුකිනිස්ස ගෙඩි", "category": "plant" },
  { "word": "කොසීන්", "meaning": "අබ (අබ ගස)", "category": "plant" },
  { "word": "කොක්ලිය", "meaning": "ඉකිරි ගස", "category": "plant" },
  { "word": "කොවොධාන", "meaning": "නෙළුම් ඇට, නෙළුම් මල, වගපුල්", "category": "plant" },
  { "word": "කොට", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කොටජ්", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කොටජි", "meaning": "කෙළිඳ (කෙළිඳසාල්)", "category": "plant" },
  { "word": "කොටි", "meaning": "කෙළිඳ ගස", "category": "plant" },
  { "word": "කොටලිය", "meaning": "කෑරට්, බීට් රූට් අල", "category": "plant" },
  { "word": "කොණඬ", "meaning": "යකඩ", "category": "treatment" },
  { "word": "කොබිනායක", "meaning": "තුඹ, ගැටතුඹ, මඟතුඹ", "category": "plant" },
  {
    "word": "කොහිල",
    "meaning": "කොහිලනස් (කොස විල-කොකොවිල පලා) කිරි කොහිල, ගුරු කොහිල, වැල් කොහිල, කටු කොහිල යයි කොහිල වගී කීපයකි. තැම්බූවිට හොඳින් පිපෙන රසවත් වගිය ප්‍රමාණයෙන් සිහින් වූ කිරි කොහිල යි. ප්‍රමාණයෙන් ඉතා විශාල වූ ගුරු කොහිල රසයෙන් අඩු ය. අල තැම්බූ විට හොඳින් පිපීමක් ද නැත. දිය කඩවල හා සණි පොතු සහිත ගස්වලත්, ගල් වලත් පසුරු අල්ලා දුවන වැල්...",
    "category": "plant"
  },

  // --- පිටුව 141 (image_87e0c3.jpg) ---
  { "word": "කොහිල (ඉතිරි විස්තරය)", "meaning": "කොහිල රසයෙන් හා ගුණයෙන් උසස් නැත. කළු කොහිලවල අල හා කොළ ඉතා විශාල ය. දඬු, අල හා කොළවල උඩ පැත්තත් තද කළු පාටින් යුක්ත ය. කොළවල යට පැත්ත පමණක් ගුරු පාට ය. රස, ගුණ, අතින් ඉතා උසස් වූ කළු කොහිල රටේ සුලභ නැත. වස, විෂ, ශරීරගත වීමෙහි දීත් මූල රෝගයෙහි දීත්, ප්‍රත්‍යක්ෂ ඖෂධයක් වූ කොහිල අල, දඬු හා කරටි ලාංකිකයෝ උසස් ආහාරයක් ලෙස සලකති.", "category": "plant" },
  { "word": "කොහො", "meaning": "කොස් ගස", "category": "plant" },
  { "word": "කොහොත්", "meaning": "කෝන්, කොබු", "category": "plant" },
  { "word": "කොහොම්", "meaning": "කොසඹ ගස", "category": "plant" },
  { "word": "කොහොමිබි", "meaning": "කොසඹ ගස", "category": "plant" },
  { "word": "කොහොවිල", "meaning": "කොහිල", "category": "plant" },
  { "word": "කොහොවිලාසට", "meaning": "කොහිල", "category": "plant" },
  { "word": "කොල්-හොගයම ගස", "meaning": "හොගයම ගස", "category": "plant" },
  { "word": "කොලඩුබු", "meaning": "කෙබුක්", "category": "plant" },
  { "word": "කොලුනිබුල්", "meaning": "කටු නිඹුල් ගස", "category": "plant" },
  { "word": "කොප්‍රාභ", "meaning": "ද්‍රෝණස", "category": "treatment" },
  { "word": "කොලොම්", "meaning": "කදම්භ වාක්‍යය (කොලොම් ගස)", "category": "plant" },
  { "word": "කොලොස්", "meaning": "කැකුණ මැලියම්", "category": "treatment" },
  { "word": "කෝකනද", "meaning": "රත්පුල්", "category": "plant" },
  { "word": "කෝණාල", "meaning": "මිදි", "category": "plant" },
  { "word": "කෝත්-කෝන් ගස (එනස වර්‍ගය)", "meaning": "එනස වර්‍ගය", "category": "plant" },
  { "word": "කෝන්ගු", "meaning": "හිණිහිරිය", "category": "plant" },
  { "word": "කෝනපුලි", "meaning": "අන්ඳර ගස", "category": "plant" },
  { "word": "කෝතල", "meaning": "මිදි, සිහින් මිදි", "category": "plant" },
  { "word": "කෝපි", "meaning": "මෙලක්මාල, කාවා, (බාබා)", "category": "plant" },
  { "word": "කෝපි ඇට", "meaning": "බාබා සාල්", "category": "plant" },
  { "word": "කෝම", "meaning": "මිරිස් වැල", "category": "plant" },
  { "word": "කෝමරසි", "meaning": "ගස් කැප්පිටියා", "category": "plant" },
  { "word": "කෝමාරිකා", "meaning": "කෝමාරිකා (කුමාරි) පාලය", "category": "plant" },
  { "word": "කෝබිකසායොලෙයි", "meaning": "ගොඩමානෙල්", "category": "plant" },
  { "word": "කෝයන", "meaning": "කොත්තමල්ලි", "category": "plant" },
  { "word": "කෝරාර්කමුලි", "meaning": "කන්සා පාලය", "category": "plant" },
  { "word": "කෝරක", "meaning": "මල්කැකුළු", "category": "plant" },
  { "word": "කෝරණ්ඩ", "meaning": "කටුකරඬු", "category": "plant" },
  { "word": "කෝරදුලු", "meaning": "අමු, කොල්ලු", "category": "plant" },
  { "word": "කෝරායි", "meaning": "කෙලෙන්ගු, කලාඳුරු අල", "category": "plant" },
  { "word": "කෝරල", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "කෝරෝවනෙයි", "meaning": "ගෝරෝචන", "category": "treatment" },
  { "word": "කෝල", "meaning": "පුවඟු, රැකුණ, මසන්, (බැබර) තිප්පිලි, සිද්ධිගුරු, සිවිය, ගජතිප්පිලි, කලාඳුරු, රත්නිවුල්, කුරැඳු, කෝවක්කා", "category": "plant" },
  { "word": "කෝලං", "meaning": "රක්කාගුණ", "category": "treatment" },
  { "word": "කෝලක", "meaning": "යක්බේරිය, මිරිස්, තිප්පිලි, ඉඟුරු", "category": "plant" },
  { "word": "කෝලකනිප", "meaning": "තකුල්", "category": "plant" },
  { "word": "කෝලකසේරැක", "meaning": "කලාඳුරු, (වම්මුතු)", "category": "plant" },
  { "word": "කෝලකි", "meaning": "සිහින් මසන්, (සිහින් බැබර)", "category": "plant" },
  { "word": "කෝලබි", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "කෝලදල", "meaning": "නබි නම් ගන්ධ ද්‍රව්‍යය", "category": "treatment" },
  { "word": "කෝලපුෂ්ප / කෝලපුෂ්පී", "meaning": "කටුපිල", "category": "plant" },
  { "word": "කෝලඵල", "meaning": "මසන් (බැබර)", "category": "plant" },
  { "word": "කෝලමාරි", "meaning": "තකුල්", "category": "plant" },
  { "word": "കൊളമുല്ലി", "meaning": "තිප්පිලි මුල් (දධවමුල්)", "category": "plant" },
  { "word": "කෝලය", "meaning": "උල්ලාහාල්", "category": "plant" },
  { "word": "කෝලරික", "meaning": "රැකුණ, (ගස්අගුණ) පුවඟු", "category": "plant" },

  // --- පිටුව 142 (image_87e0df.jpg) ---
  { "word": "කෝලවල්ලී", "meaning": "ගජතිප්පිලි, (ඇත් වගපුල්) සිවිය වැල්", "category": "plant" },
  { "word": "කෝලවල්ලිකා", "meaning": "ඇත් වගපුල්, සිවිය", "category": "plant" },
  { "word": "කෝලි", "meaning": "මසන් (බැබර) ඉලන්ද", "category": "plant" },
  { "word": "කෝලිකාරම්", "meaning": "සැවුල් පගර (කුකුල් වසුරු)", "category": "treatment" },
  { "word": "කෝලිකුට්ටු", "meaning": "පිටි සහිත රසවත් කෙසෙල් වගියක් (ඇතැම් අය මේ වගියට 'පුවාලු' යයි කියන නමුත් එය හරි නැත. පුවාලු සහ හම්බන් පුවාලු යයි කියන්නේ වෑංජන පිණිස ගන්නා කෙසෙල් වගී දෙකකට ය.)", "category": "plant" },
  {
    "word": "කෝවක්කා",
    "scientific": "Cephalanda Indica",
    "meaning": "කෝවක්කා = කෙම්වැල් = බිම් බිබුල = (බිබුලපල) කොබෝවක්කා = තෙලන් කැකිරි, යන මේ නම් වලින් ලංකාවේ නොයෙක් පළාත් වල හඳුන්වන මෙම වගිය දියවැඩියාවට ඉතාම ප්‍රත්‍යක්ෂ ඖෂධයකි. දුම්මැල්ල කොළ වලට සහ ගෙඩි වලටත් මඳක් සමාන වූ සිරිත කොළ ඇති මේ වගිය ලංකාවේ වියළි කලාපයට අයත් ප්‍රදේශ වල පිලියස්සු හේන්වල කටු සර බෝගත් සමග පැලවී හේන් ලුල් වනවිට මැරී යයි. මේ වගියේ කොළ මැල්ලුමටත් ගෙඩි වෑංජන පිණිසත් ගනිති. නොපෑ යුතු (අමු) ගෙඩි නිල් පාට ය. ගුණවත් රේඛාවලින් යුක්ත ය. ප්‍රමාණයෙන් දුම්මැල්ල ගෙඩි පමණ ඇත. ඉදුණු විට ලා රත් පැහැයෙන් යුක්ත ය. කාන්තාවන්ගේ තොල්, මේ වගියේ ඉදුණු ගෙඩි වලට සමාන කර ඇති බැව් පැරණි පොත පතින් පෙනේ. බුද්ධදාස රජතුමා ලියූ සාරාර්ථ සංග්‍රහයෙහි බහු මූත්‍ර වර්ණය සීමා කිරීම සඳහා මෙය ප්‍රත්‍යක්ෂ ඖෂධයක් බව විස්තර කර ඇත. මේ වැල්වල සාරය සම්පූර්ණයෙන් ගෙන ඒ රෝගය සඳහා යෙදීමෙන් ප්‍රත්‍යක්ෂ ඵල ලැබෙන බැව් පලපුරුද්ද අනුව කිව හැක.",
    "category": "plant"
  },
  { "word": "කෝවන්දනී", "meaning": "පුවඟු", "category": "plant" },
  { "word": "කෝවිද්‍ර", "meaning": "කොබෝලිල, රත් කොබෝලිල", "category": "plant" },
  { "word": "කෝඩියස", "meaning": "චන්දන වාක්‍යය (කෝන් ගස)", "category": "plant" },
  { "word": "කෝෂ්ට", "meaning": "කොට්ටම්, සුවඳ කොට්ටම්", "category": "plant" },
  { "word": "කෝෂ්ටකා", "meaning": "සාතාවාරිය", "category": "plant" },
  { "word": "කෝෂ්ටබිදාරිකා", "meaning": "කිරිබදු (හඳුලතා)", "category": "plant" },
  { "word": "කෝෂ්ටුබිදාරිකා", "meaning": "කිරිබදු (හඳුලතා)", "category": "plant" },

  // --- පිටුව 143 (image_87e0e5.jpg) ---
  { "word": "කෝෂ්ට්‍රිබ්‍රිදාරිකා", "meaning": "කිරිබදු (හඳුලතා)", "category": "plant" },
  { "word": "කෝෂ්ට්‍රැකමෙබලා", "meaning": "පලොල්", "category": "plant" },
  { "word": "කෝෂ", "meaning": "කොට්ටන්, සාදික්කා, (ජාතිඵල)", "category": "plant" },
  { "word": "කෝෂක", "meaning": "සාදික්කා, තිප්පිලි", "category": "plant" },
  { "word": "කෝෂපල", "meaning": "වැටකොළු, වල් පෙනෙල, තකුල්, (කපුකිනිස්ස), ත්‍රස්තවාලු, සාදික්කා", "category": "plant" },
  { "word": "කෝෂයපල", "meaning": "තකුල්", "category": "plant" },
  { "word": "කෝෂවති", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "කොෂාතකි", "meaning": "වැටකොළු, තිත්ත වැටකොළු, දේවදාලිය වැල්", "category": "plant" },
  { "word": "කෝෂාධිපත්‍රිනි", "meaning": "පලොල්, දුම්මැල්ල, පුලිල", "category": "plant" },
  { "word": "කෝෂාප්ල", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "කොෂක", "meaning": "තිප්පිලි", "category": "plant" },
  { "word": "කෝෂඵල", "meaning": "කපුකිනිස්ස, පණිස, (කොස්)", "category": "plant" },
  { "word": "කොසමඟ", "meaning": "කොසඹ", "category": "plant" },
  { "word": "කොෂයප්ල", "meaning": "කපුකිනිස්ස ගෙඩි", "category": "plant" },
  { "word": "කෝසීන්", "meaning": "අබ (අබ ගස)", "category": "plant" },
  { "word": "කෞතිකිල", "meaning": "ඉකිරි ගස", "category": "plant" },
  { "word": "කෞමාධපන", "meaning": "නෙළුම් ඇට, නෙළුම් මල, වගපුල්", "category": "plant" },
  { "word": "කෞට", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කෞටජ", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කෞටජි", "meaning": "කෙළිඳ (කෙළිඳසාල්)", "category": "plant" },
  { "word": "කෞටී", "meaning": "කෙළිඳ ගස", "category": "plant" },
  { "word": "කෞටීල්‍ය", "meaning": "කෑරට්, බීට්රූට් අල", "category": "plant" },
  { "word": "කෞණ්ඩ", "meaning": "යකඩ", "category": "treatment" },
  { "word": "කෞබිනායක", "meaning": "තුඹ, ගැටතුඹ, මඟතුඹ", "category": "plant" },
  { "word": "කෞබිනාය", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කෞඩූවික", "meaning": "සුවස ලුණු", "category": "treatment" },
  { "word": "කෞතනී", "meaning": "වටරැගැන්, වල්ගා මිරිස් (වැල් මොලඟු)", "category": "plant" },
  { "word": "කෞන්තෙය", "meaning": "කුඹුක් ගස", "category": "plant" },
  { "word": "කෞමුද", "meaning": "කුමුදු", "category": "plant" },
  { "word": "කෞමුදී", "meaning": "මානෙල් අල, හෙලපුල්", "category": "plant" },
  { "word": "කෞමුදු", "meaning": "රන් බිලු, රතැඹුල", "category": "plant" },
  { "word": "කෞරිය", "meaning": "කරවිල", "category": "plant" },
  { "word": "කෞලක", "meaning": "හොයඳුන්", "category": "treatment" },
  { "word": "කෞලිර", "meaning": "කකුළුසුනු (කහිටක ශාලි)", "category": "plant" },
  { "word": "කෞවල", "meaning": "පිටවක්කා, බැබර ගෙඩි", "category": "plant" },
  { "word": "කෞවීර", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "කෞවේර", "meaning": "කොට්ටම්, සුවඳ කොට්ටම්", "category": "plant" },
  { "word": "කෞශිකය / කෞශිකෝත්සව", "meaning": "ගැටනිවුල්", "category": "plant" },
  { "word": "කෞශික", "meaning": "ගුගුල්, මූරුත ගස", "category": "plant" },
  { "word": "කෞශිකා", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "කෞශිකා", "meaning": "ග්‍රන්ථපර්ණී වාක්‍යය, පුරා", "category": "plant" },
  { "word": "කෞෂටපර්ණි", "meaning": "පලොල්, ප්‍රස්වැන්න", "category": "plant" },
  { "word": "කෞෂටපර්ණිකා", "meaning": "පලොල්", "category": "plant" },
  { "word": "කෞෂ්‍ය", "meaning": "දවසක් ඉකුත් වූ ගිතෙල්", "category": "treatment" },
  { "word": "කෞෂම්භක", "meaning": "දුම්මැල්ල, (වත පවෝල)", "category": "plant" },
  { "word": "කෞෂි", "meaning": "ගුගුල්", "category": "plant" },
  { "word": "කෞසිකඵල", "meaning": "පොල්, පොල් ගස", "category": "plant" },
  { "word": "කෞසුම්භ", "meaning": "වනුක්, සෙන්දිරික්කා, කොකුම්මල්", "category": "plant" },
  { "word": "ක්‍යාම්බු", "meaning": "රන්වන් වෙසෙසක්", "category": "plant" }
];