// data_345_354.js - පිටු 345 සිට 354 දක්වා සියලුම වචන
const data_extra_345_354 = [
    // --- පිටුව 345 ---
    { "word": "භෘගුභවා", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "භෘගුරාජි", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "භෘංගාර", "meaning": "කිකිරිඳිය, කරාබුනැටි", "category": "plant" },
    { "word": "භෘංගුරා", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "භෘමක", "meaning": "අසෝකාන්ත", "category": "plant" },
    { "word": "භ්‍රමර", "meaning": "මීපැණි, බඹරපැණි, මීමැස්සා", "category": "plant" },
    { "word": "භ්‍රමරප්‍රිය", "meaning": "කරාබුනැටි, වසාවාසි", "category": "plant" },
    { "word": "භ්‍රමරානිසි", "meaning": "සපුගස", "category": "plant" },
    { "word": "භ්‍රමරානන්ද", "meaning": "මූණමල් ගස", "category": "plant" },
    { "word": "භ්‍රමරි", "meaning": "ආපසුමුදු", "category": "plant" },
    { "word": "භ්‍රමරෙෂ්ට", "meaning": "රත් මහනෙල්, තොටිල සිරිතේක්කු, සින්නාරං", "category": "plant" },
    { "word": "භ්‍රමරෝත්සව", "meaning": "යොහොඹු", "category": "plant" },
    { "word": "භ්‍රමරෝෂ්ට", "meaning": "තොටිල", "category": "plant" },
    { "word": "භ්‍රෂ්ට", "meaning": "දාගිය බත් (දාගිය බත්)", "category": "food" },
    { "word": "භ්‍රෂ්ටතණ්ඩුල", "meaning": "බැඳිසාල්", "category": "food" },
    { "word": "භ්‍රෂ්ටයව", "meaning": "බැඳිසාල්", "category": "food" },
    { "word": "භ්‍රාන්ත", "meaning": "තුන්බෝ අත්තන", "category": "plant" },
    { "word": "භ්‍රාමක", "meaning": "යකඩකාන්දම්", "category": "mineral" },
    { "word": "භ්‍රීෂ්ට", "meaning": "දාගිය බත්", "category": "food" },
    { "word": "මංජවර්ණා", "meaning": "අහු ගස් හෝ කහ පාට අරටුවක් සහිත දේවතා වෘක්‍ෂයක්", "category": "plant" },
    { "word": "මංච", "meaning": "එඬරු", "category": "plant" },
    { "word": "මංජුලා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "මක්කට", "meaning": "වඳුරුමෑ", "category": "plant" },
    { "word": "මක්‍ෂටිකා", "meaning": "ගල් සෙවෙල්, (ශිලා ජතු)", "category": "mineral" },
    { "word": "මක්‍ෂවිකා", "meaning": "කිරිපලු ගස", "category": "plant" },
    { "word": "මක්‍ෂිකා", "meaning": "මී පැණි", "category": "food" },
    { "word": "මක්ෂිකාලය", "meaning": "මී පැණි, මල්පැණි", "category": "food" },
    { "word": "මක්‍ෂිකුට්", "meaning": "තුන්තම් (මැසිඳු)", "category": "plant" },
    { "word": "මකතා", "meaning": "කංසා", "category": "plant" },
    { "word": "මකන්ද", "meaning": "අඹ", "category": "plant" },
    { "word": "මකරන්ද", "meaning": "කණේරු, නුග, නෙළුම් රේණු, කොඳ, මීපැණි, මල්පැණි", "category": "plant" },
    { "word": "මකරන්දවතී", "meaning": "පලොල් ගස", "category": "plant" },
    { "word": "මකරාකාර", "meaning": "කරඳ ප්‍රභෙදයක්", "category": "plant" },
    { "word": "මකරින්ද", "meaning": "මකුල්ගස, අඹ, කුකුරුමුවන්", "category": "plant" },
    { "word": "මකුට", "meaning": "අසමෝදගම් - ජටාමාකුට", "category": "plant" },
    { "word": "මකුර", "meaning": "වකුල (මුණමල්)", "category": "plant" },
    { 
        "word": "මුගුණුවැන්න", 
        "scientific": "Geophila Reniformis",
        "meaning": "Geophila Reniformis- මණ්ඩූකපර්ණී. මුගුණුවැන්න, මකුවැන්න, මීකන් පලා, කොතුරුබැද්ද, යන සිංහල නම් වලින් හැඳින් වෙන මේ වැල් වර්ගය දියසීරාව හා අඳුර ඇති තැන් වල හොඳින් වැවෙයි. කොළ මඳක් කළු පැහැයෙන් යුක්ත ය. මී කන් මෙන් ගොටු ගැසී තිබේ. පලය මුදුනෙහි සෑදෙන ගෙඩි වැල් තිබ්බටු ගෙඩි පමණ ඇත. ඉදුන විට රතු පාට ය. මේ වර්ගය ලමා (කාමි) රෝග වල (පණුගාය)ට ප්‍රත්‍යක්‍ෂ ඖෂධයකි. ඇතැම් පළාත් වල මීකන් පලා වෙනුවට ගොටුකොළ ගනිති. එය සුදුසු නැත.", 
        "category": "plant",
        "image": "img_345_mugunuwanna.jpg"
    },

    // --- පිටුව 346 ---
    { "word": "මකුල්ගස", "meaning": "මකුලු (මකුල්ල) ගස, කුකුරුමාන්ගස", "category": "plant" },
    { "word": "මකුල", "meaning": "මූණමල්, කැකුල", "category": "plant" },
    { "word": "මකුලක", "meaning": "මහදත්ත, මූණමල් ගස", "category": "plant" },
    { "word": "මකුලමුපු", "meaning": "මූහුණමල්", "category": "plant" },
    { "word": "මකුළු", "meaning": "මකුල්ල ගස = (මකුළු ගස) (ඉන්දියාවේ තිබෙන චවුල් මුග්‍රා (තුවරකා) ගස වෙනුවට ලංකාවේ ඖෂධ වශයෙන් ගතා යුත්තේ මේ ගස යි. මෙහි සාරය ලාදුරු, උපදංශ, (පරංගි) ඇතුළු චර්මරෝගෝප සමනයෙහි ලා ප්‍රයෝජන වත් ය.) මෙය අරටු සහිත විශාල ගස කි.", "category": "plant" },
    { "word": "මකුළු ඇට", "meaning": "මකුළු ගෙඩි වල ඇට", "category": "plant" },
    { "word": "මකුෂ්ට", "meaning": "වල් මුං", "category": "plant" },
    { "word": "මකුෂ්ටක", "meaning": "හින් මුං (ධාන්‍ය ප්‍රභේදයක්)", "category": "plant" },
    { "word": "මග්නී පුෂ්ප", "meaning": "අස්බැවිල, මුවකිරිය", "category": "plant" },
    { "word": "මගද", "meaning": "නිප්පිලි, දුරු", "category": "plant" },
    { "word": "මගධ", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "මගධජ", "meaning": "නිප්පිලි මුල්", "category": "plant" },
    { "word": "මගධා", "meaning": "නිප්පිලි, කවකලා", "category": "plant" },
    { "word": "මගදොත්භවා", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "මගනා", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "මගල්‍යා", "meaning": "ජීවක", "category": "plant" },
    { "word": "මගුල්", "meaning": "බෙලි", "category": "plant" },
    { "word": "මගුල් කරඳ", "meaning": "කරඳ වර්ගයක්, මෙය සෙම් රෝග හා විෂබීජ නාශක ඖෂධයකි.", "category": "plant" },
    { "word": "මගුලේ යන්නෝ නියමා", "meaning": "මගුල් කරඳ ගස", "category": "plant" },
    { "word": "මගලා", "meaning": "බෙලි ගස", "category": "plant" },
    { "word": "මඟාසහං", "meaning": "කෝමාරිකා", "category": "plant" },
    { "word": "මඟුල්කුඹුරුවැන්න", "meaning": "ගොඩමානෙල්", "category": "plant" },
    { "word": "මඟවාසිති", "meaning": "මලිත", "category": "plant" },
    { "word": "මඟුකා", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "මඟගනා", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "මඟගසි", "meaning": "වගපුල්", "category": "plant" },
    { "word": "මඟගල", "meaning": "එළ රතණ, එළ නෙළුම්, තිඹිරි, බෙලි", "category": "plant" },
    { "word": "මඟගලච්ඡායා", "meaning": "නුග ගස", "category": "plant" },
    { "word": "මඟගලපුද", "meaning": "කහ", "category": "plant" },
    { "word": "මඟගලී", "meaning": "ගොඩමානෙල්", "category": "plant" },
    { "word": "මඟගල්‍යා", "meaning": "රතණ, කුකුරුමාන්, සඳුන්, සුවඳ අගිල්, රත් සින්දූරම්, බෙලි, එළ නෙළුම්, නුග, ගෝරෝචන, දීකිරි, සුදු දුරු, සැබෝ, පලොල් ගස, කරඳ, බැමිතිරිය, බෝ ගස, මී ගස, දිඹුල් (ජූල්) පොතු", "category": "plant" },
    { "word": "මඟගල්‍යක", "meaning": "මසූර්, (මැසිරි) පරිප්පු", "category": "plant" },
    { "word": "මඟගල්‍ය කුසුමා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "මඟගල්‍ය ජනනෙතිකා", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "මඟගල්‍ය නාම", "meaning": "මීගස, ජීවක", "category": "plant" },
    { "word": "මඟගල්‍යාති ප්‍රසාධනී", "meaning": "මඟුල්කුඹුරුවැන්න", "category": "plant" },
    { "word": "මඟගල්‍යා", "meaning": "බුලත්, ගෝරෝචන, යොන් තුඹ, රතණ, එළවද, වදකසා, ජීවක, සුවඳ අගිල්, පුවඟු, මස්වැන්න, ශතපුෂ්ප, කහ, විෂ්ණුක්‍රාන්ති, සින් මුං, කිරිපලා, බෝගස, සාමගස්", "category": "plant" },

    // --- පිටුව 347 ---
    { "word": "මච්ඡසි", "meaning": "සිනි", "category": "plant" },
    { "word": "මච්ඡකා", "meaning": "අමු ඉඟුරු", "category": "plant" },
    { "word": "මජ්ජතාල", "meaning": "තල්පැලමද=(තල්පිලි - තල්පි)", "category": "plant" },
    { "word": "මජ්ජසාර", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "මජ්ජා", "meaning": "ඇටමිදුලු, අරටු", "category": "plant" },
    { "word": "මඤ්ජා", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "මඤ්ජාති", "meaning": "ගල්මද", "category": "mineral" },
    { "word": "මඤ්ජාර පුෂ්පක", "meaning": "මඟුල්කරඳ, මයිල", "category": "plant" },
    { "word": "මඤ්ජාරමොහනී", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "මඤ්ජාරා", "meaning": "ප්‍රපාදියෙන් කළු සුරා", "category": "liquid" },
    { "word": "මඤ්ජාරි", "meaning": "බැවිල, කස්තුරි", "category": "plant" },
    { "word": "මඤ්ජ", "meaning": "මඤ්ජත්", "category": "plant" },
    { "word": "මඤ්ජටා", "meaning": "මදටිය", "category": "plant" },
    { "word": "මඤ්ජර", "meaning": "මාරා, මුතු", "category": "plant" },
    { "word": "මඤ්ජරි", "meaning": "කරඳ, අක්මැල්ල, තිලකලතා, තලා", "category": "plant" },
    { "word": "මඤ්ජරිකා", "meaning": "කස්තුරි, කරව් තලා", "category": "plant" },
    { "word": "මඤ්ජරි පත්", "meaning": "විලඳවැන්න හෝ කරඳ", "category": "plant" },
    { "word": "මක්‍ෂිරි", "meaning": "තලා, මල්කැන, සාතාවාරිය", "category": "plant" },
    { "word": "මක්‍ෂිරි නමු", "meaning": "වේවැල් (වෙනසි)", "category": "plant" },
    { "word": "මක්‍ෂිරි පුෂ්ප", "meaning": "මඟුල්කරඳ", "category": "plant" },
    { "word": "මක්‍ෂිරි පුෂ්පක", "meaning": "මඟුල්කරඳ", "category": "plant" },
    { "word": "මක්‍ෂුල්", "meaning": "වෙනි වැල්, කහපුව, (කහ)", "category": "plant" },
    { "word": "මක්‍ෂුෂ්ටා", "meaning": "වැල්මදට (මදටිය වැල)", "category": "plant" },
    { "word": "මක්‍ෂුෂ්පතිකා", "meaning": "කරඳ", "category": "plant" },
    { "word": "මඤ්ජුලා", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "මක්‍ෂුෂ්ටක", "meaning": "හිමාලයෙහි ගංඟාමාදිත පර්වතය අසල තිබෙන බැව් කියන දිය-ගොඩ හැම වගියේම මල් පිපෙන වෘක්‍ෂයක් හෝ කරඳ ඇට මද", "category": "plant" },
    { "word": "මක්‍ෂුෂ්ඨා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "මඤ්ජෙෂ්ටි", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "මට්ටි", "meaning": "බැවිල, බින්තඹුරු", "category": "plant" },
    { "word": "මඩ", "meaning": "මයසාරණ", "category": "plant" },
    { "word": "මඩලපත්", "meaning": "බෝගස", "category": "plant" },
    { "word": "මඩලා", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "මඩලු", "meaning": "කපුරු", "category": "plant" },
    { "word": "මඩාදු", "meaning": "කෑද", "category": "plant" },
    { "word": "මඩිත්‍රී", "meaning": "වදකහ", "category": "plant" },
    { "word": "මඩු", "meaning": "මඩුගස, සමුගය", "category": "plant" },
    { "word": "මඩුපර්ණී", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "මණ්ඩ", "meaning": "තෙල්ලි, දී පෙරලි දිය එරඬු, හුළු කෑද", "category": "liquid" },
    { "word": "මණ්ඩකූපට", "meaning": "සින්මුං", "category": "plant" },
    { "word": "මණ්ඩල", "meaning": "දුම්, බිම්බිඵල, කුෂ්ට ප්‍රභේදයක්", "category": "plant" },
    { "word": "මණ්ඩල පත්‍ර", "meaning": "බෝ ගස", "category": "plant" },
    { "word": "මණ්ඩල පත්‍රක", "meaning": "සුළු සාරණ, මහ සාරණ", "category": "plant" },
    { "word": "මණ්ඩල පත්‍රිකා", "meaning": "රතු සාරණ", "category": "plant" },
    { "word": "මණ්ඩලයක්", "meaning": "දවස් 44 ක්", "category": "measurement" },
    { "word": "මණ්ඩලා", "meaning": "කුකුරුමාන්, කෝමාරිකා", "category": "plant" },
    { "word": "මණ්ඩලි", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "මණ්ඩාපිටදිසටා", "meaning": "මණ්ඩල (ලොහ භාජන) යක් උඩදී ගෑම (උරච්චි කිරීම) කර", "category": "treatment" },
    { "word": "මණ්ඩින්", "meaning": "නුග ගස", "category": "plant" },
    { "word": "මණ්ඩූක", "meaning": "සල්ගස", "category": "plant" },
    { "word": "මණ්ඩූක පත්‍රී", "meaning": "මකුණුවැන්න", "category": "plant" },
    { "word": "මණ්ඩූකපර්ණී", "meaning": "බැමිතිරිය, කෝවක්කා, තොටිල, මකුණුවැන්න වැල්මදට", "category": "plant" },
    { "word": "මණ්ඩූක පර්ණිකා", "meaning": "ගොටුකොළ", "category": "plant" },

    // --- පිටුව 348 ---
    { "word": "මණ්ඩූක මාතා", "meaning": "ගොටුකොළ, ලූණු විල", "category": "plant" },
    { "word": "මණ්ඩූකි", "meaning": "වැල්මදට, මුද්දරප්පලම්, ගොටුකොළ, කෝවක්කා", "category": "plant" },
    { "word": "මණ්ඩූ මරම්", "meaning": "මඩු ගස", "category": "plant" },
    { "word": "මණ්ඩූර්", "meaning": "සබෝර", "category": "mineral" },
    { "word": "මණ්ඩූරි", "meaning": "යබෝර", "category": "mineral" },
    { "word": "මණ්ඩූල", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "මණොදක", "meaning": "කෑද", "category": "plant" },
    { "word": "මණිතා", "meaning": "කළුතලා", "category": "plant" },
    { "word": "මණකොට්ටම්", "meaning": "සුවඳ කොට්ටම්", "category": "plant" },
    { "word": "මණියසිලා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මණිච්ඡිද්‍රා", "meaning": "මේවත් (මේදෘ)", "category": "plant" },
    { "word": "මණිතක්කාලි", "meaning": "කළුකාමිමේරිය", "category": "plant" },
    { "word": "මණිපුෂ්පිකා", "meaning": "පිලගස", "category": "plant" },
    { "word": "මණිමන්ජ", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "මණිරාග", "meaning": "හිඟුල්", "category": "mineral" },
    { "word": "මණිවිජ", "meaning": "දෙඹම්", "category": "plant" },
    { "word": "මණොගුප්තා", "meaning": "රත්හිරියල්", "category": "mineral" },
    { "word": "මණොඥ", "meaning": "වැල්තුඹ", "category": "plant" },
    { "word": "මණොප්", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "මණොපා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මණොහනත්", "meaning": "බක්මී", "category": "plant" },
    { "word": "මණොමවිකා", "meaning": "රත්හිරියල්", "category": "mineral" },
    { "word": "මණොරමා", "meaning": "බව්දම්, පුවඟු, කොඳ, කළුතිකා", "category": "plant" },
    { "word": "මණොහ්වා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මණොහර", "meaning": "රත් නෙළුම්, රත් මහනෙල්, මල්තුඹ වැල, නිප්පිලි", "category": "plant" },
    { "word": "මණොශිලා", "meaning": "රත්හිරියල්", "category": "mineral" },
    { "word": "මණොහාරි", "meaning": "හිප්පිලි", "category": "plant" },
    { "word": "මත්කුණාරි", "meaning": "ත්‍රස්තාවළු, කන්සා", "category": "plant" },
    { "word": "මත්හක්කා", "meaning": "කළු කාමිමේරිය", "category": "plant" },
    { "word": "මත්තන්", "meaning": "අත්තන", "category": "plant" },
    { "word": "මත්නා", "meaning": "ශතපුෂ්ප, වැටහිර", "category": "plant" },
    { "word": "මත්තාල", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මත්තිය", "meaning": "දුටු", "category": "plant" },
    { "word": "මත්කො", "meaning": "කිඹුල්", "category": "animal" },
    { "word": "මතු", "meaning": "දී පෙරලි දිය", "category": "liquid" },
    { "word": "මතුනාරි", "meaning": "කන්සා", "category": "plant" },
    { "word": "මත්යාර", "meaning": "මැසිඳු", "category": "plant" },
    { "word": "මත්සාඛි", "meaning": "සිනි", "category": "plant" },
    { "word": "මත්ස‍්‍ය", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "මත්ස‍්‍යක", "meaning": "මුගුණුවැන්න", "category": "plant" },
    { "word": "මත්ස‍්‍යගන්ධා", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "මත්ස‍්‍යගන්ධිකා", "meaning": "සිනි", "category": "plant" },
    { "word": "මත්ස‍්‍යපිත්තා", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "මත්ස‍්‍යමාස", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "මත්ස‍්‍යමින්තා", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "මත්ස‍්‍යසාක්‍ෂක", "meaning": "මුගුණුවැන්න, ලූණු විල", "category": "plant" },
    { "word": "මත්ස‍්‍යසාක්‍ෂි", "meaning": "මුගුණුවැන්න, බෝදි ඇට", "category": "plant" },
    { "word": "මත්ස‍්‍යහුණ්ඩිකා", "meaning": "උක් සකුරු", "category": "food" },
    { "word": "මත්ස‍්‍යහුණ්ඩි", "meaning": "කඩසකුරු, උක් සකුරු", "category": "food" },
    { "word": "මත්ස්‍යාදනී", "meaning": "මුගුණුවැන්න, කටු කරෝහිණී", "category": "plant" },
    { "word": "මත්ස්‍යාරී", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "මත්ස්‍යා සකුලා", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "මත්හමුසාල්", "meaning": "මක්වන (කරල්) අමු සාල්", "category": "food" },
    { "word": "මනි", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "මනික", "meaning": "තල, බෙලි", "category": "plant" },
    { "word": "මනිකා", "meaning": "තල ගස, බෙලි ගස, තලා ගස", "category": "plant" },
    { "word": "මතුමත්තා", "meaning": "අත්තන, තුන්බෝ අත්තන", "category": "plant" },
    { "word": "මතුවහා", "meaning": "දෙඹම්", "category": "plant" },
    { "word": "මටන", "meaning": "කිණිහිරි ගස, මහමිදි", "category": "plant" },
    { "word": "මටනප්", "meaning": "දී ආදිය", "category": "liquid" },
    { "word": "මපිත", "meaning": "කිරි මෝරු", "category": "liquid" },
    { "word": "මද්‍ය", "meaning": "සුරා", "category": "liquid" },
    { "word": "මද්‍යගන්ධ", "meaning": "මූණමල් ගස, කඩසකුරු, නියඳ, යොන් හිඳි, මී ඉටි, මෑබ ගඟු, අඹ, වැල් මුරුංගා, උක්දඬු", "category": "plant" },

    // --- පිටුව 349 ---
    { "word": "මද්‍යගන්ධිකා", "meaning": "මලිත ගස", "category": "plant" },
    { "word": "මද්‍යාපාවනි", "meaning": "මලිත ගස", "category": "plant" },
    { "word": "මද්‍යාපාසිකා", "meaning": "මලිත ගස", "category": "plant" },
    { "word": "මද්‍යපුෂ්ප", "meaning": "හොමුවානු, මලිත මල්", "category": "plant" },
    { "word": "මද්‍යපුෂ්පා", "meaning": "මලිත මල්", "category": "plant" },
    { "word": "මද්‍යමොද", "meaning": "මූණමල් ගස", "category": "plant" },
    { "word": "මද", "meaning": "මිදි ගස, කස්තුරි, මලිත ගස, බෝදි ගස", "category": "plant" },
    { "word": "මදකාර", "meaning": "කංසා", "category": "plant" },
    { "word": "මදකාරි", "meaning": "කංසා", "category": "plant" },
    { "word": "මදකලි", "meaning": "නීති වැල", "category": "plant" },
    { "word": "මදගන්ධ", "meaning": "සුරා, රුක් අත්තන", "category": "plant" },
    { "word": "මදගොහඬ", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "මදස්න", "meaning": "නීති පලා", "category": "plant" },
    { "word": "මදට", "meaning": "මදටිය", "category": "plant" },
    { "word": "මදද", "meaning": "මලිත ගස", "category": "plant" },
    { "word": "මදන්තිකා", "meaning": "හෙළ ඉද්ද", "category": "plant" },
    { "word": "මදන", "meaning": "සුරා, අත්තන ගස, අත්තන ගෙඩි, කුකුරුමාන්, තෝර ගස", "category": "plant" },
    { "word": "මදනක", "meaning": "කළු අත්තන, තිකුළු, කුකුරුමාන්, දමනක වෘක්‍ෂය, මී ඉටි", "category": "plant" },
    { 
        "word": "මදනකාමපූ", 
        "meaning": "මදනකාමපූ නමින් වර්ග තුනක් ඇත. එකක් තිබ්බටු වැල් වලට සමාන පඳුරු වර්ගය කි. මේ වර්ගයේ මල් ලා නිලට හුරු කහ පාටින් යුක්ත ය. මල් පෙති වැලි අනෝදා මල් පෙති මෙන් ඝන ය. අතු අතර සහ අග ත් තැනින් තැන මේ මල් පොකුරු වලින් ගෙඩි පොකුරු සෑදෙයි. එක පොකුරක ගෙඩි පහළොහක් විස්සක් පමණ තිබේ. මේ ගෙඩි සහ ඇතුලේ තිබෙන ඇට ත් මීගෙඩි වලට සහ මී ඇට වලට සමාන ය. මුලින් තිබෙන්නේ මේ වර්ගයේ රිකිල්ලක චිත්‍රයකි. දෙවැනි වර්ගයේ කොළ හා මල් සාදික්කා කොළ වලට හා මල් වලට සමාන ය. එය අඩි දොළහක් පමණ උසට වැවෙන ගසකි. ඖෂධ වශයෙන් ඇට මද සහ මල් ගන්නා මේ දෙවර්ගය ම ලිංගික ආශා වර්ධනය කරණ, මදු කාරක, වාජීකරණ ඖෂධ වෙනි. තුන් වැනි වර්ගය ලංකාවේ මුදු බිම් සහිත පෘථිවියේ දී සුරෝපිය පාලකයන්ට “මඩු ගසක් හෝ පොල් ගසක් නැති හැම ඉඩමක් ම රාජ සන්තක ය” යි උපදෙස් දුන් කළු සුද්දන් නිසා ප්‍රසිද්ධියට පත්ව තිබෙන මඩු ගස යි. සමූහ වශයෙන් අවුරුද්දකට දෙවරක් බැගින් අතු සෑදෙන - මෝරන අතු සැරසිලි සඳහා ත්, ලපටි අතු (දළු) ව්‍යංජන සඳහා ත් ප්‍රයෝජනයට ගන්නා මඩු ගස බොහෝ ප්‍රකට නිසා, චිත්‍රයක් අවශ්‍ය යයි නො සිතුවෙමි. මේ ගසේ මල් අන්නාසි ගෙඩි වැනි ය. පිපෙන විට තද දුගඳක් නික්මෙයි. මල් කෑමට ගන්නේ නැත. මේ මල් වලින් දෙඹ ගෙඩි පමණ ගෙඩි වල්ලු සෑදෙයි. මේ ඇට (ගෙඩි) වල පිටතින් තිබෙන සණ කටුව අස් කර මදය ගෙන අව්වෙන් වියලා කුඩු කර සාදා ගන්නා පිටි සහල් පිටි සමග මිශ්‍ර කර පිට්ටු, කෑද, කිරිබත් ආදිය පිළියෙල කර ගනිති. මඩු දළු හා ඇට මද්‍ය කාරක ගුණයෙන් යුත් වාජීකරණ ඖෂධයකි. මූල රෝගයෙහි පසස්නා ලද මඩු දළු රසවත් ආහාරයක් ද වෙයි.", 
        "category": "plant",
        "image": "img_349_madanakamapu.jpg"
    },

    // --- පිටුව 350 ---
    { "word": "මදනපාල", "meaning": "අත්තන ගෙඩි", "category": "plant" },
    { "word": "මදනමාන", "meaning": "සත්‍රීන්ගේ යෝනිමාර්ගය", "category": "anatomy" },
    { "word": "මදනා", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "මදනාර්ජනී", "meaning": "ශාතාවාරිය", "category": "plant" },
    { "word": "මදක", "meaning": "තල ගස, බෙලි ගස", "category": "plant" },
    { "word": "මදනී", "meaning": "කස්තුරි, යොහොඹු", "category": "plant" },
    { "word": "මදනියක", "meaning": "මලිත ගස", "category": "plant" },
    { "word": "මදහප්පනී", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "මදයන්තිකා", "meaning": "වල් ඉද්ද", "category": "plant" },
    { "word": "මදයන්ති", "meaning": "බෝලිද්ද", "category": "plant" },
    { "word": "මදර", "meaning": "එරබදු", "category": "plant" },
    { "word": "මදරා", "meaning": "එරබදු", "category": "plant" },
    { "word": "මදරාක", "meaning": "එරබදු ගස", "category": "plant" },
    { "word": "මදගස", "meaning": "ලඹු", "category": "plant" },
    { "word": "මදහෙතු", "meaning": "මලිත ගස", "category": "plant" },
    { "word": "මදෘ", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "මදෘස", "meaning": "හල්ගස", "category": "plant" },
    { "word": "මදෘන්‍ය", "meaning": "අක්මැල්ල", "category": "plant" },

    // --- පිටුව 351 ---
    { 
        "word": "මදාර", 
        "meaning": "මදාරා ගස", 
        "category": "plant" 
    },
    { 
        "word": "මදාරා - මඤ්ජර", 
        "scientific": "Cleistanthus collinues",
        "meaning": "Cleistanthus collinues- සුදු පාට කේඳි වැටී ගිය සණ පොත්තක් සහ රත් හඳුන් කොළ වලට හැඩහුරු කමින් බොහෝ සේ සමාන, තේජාන්විත වෘක්‍ෂය කි. මෙහි අරටුව පතඟි වැනි (පද්මරාග) වර්ණයෙන් යුක්ත ය. රත් පාට ලොකු මල් පමණක් සෑදෙන වර්ගයක් සහ, කුඩා මල් සහිත නෙල්ලි ගෙඩි ප්‍රමාණ ගෙඩි සෑදෙන වර්ගයකුත් තිබේ. කඳේ පාට - පොත්ත - හරය (අරටුව) හා කොළ ත් පෙනුමෙන් මේ ගස් සමාන වන්නෙ රත් හඳුන් ගසට පමණකි. වෙනස කට තිබෙන්නේ ලී දෙවර්ගයෙහි සුවඳ හා රත් හඳුන් කොළ වල ඇති මස අධික ගතිය ත් පමණකි. මේ ගස් වලට කිසිම සතෙකුගෙන් අනතුරක් නැත. එහි කොළ දඬු ආදිය අනුභව කරණවා තබා ස්පර්ශ කරණ සතෙකුත් නැත. සර්ප වර්ග හා අලි ඇතුන් මේ ගස් අසලට පවා නොයති. මේ ගස් තිබෙන භූමි වලට තේජස, භාග්‍යය, හා දියුණුව ලැබෙන බව කරණ ලද පරීක්‍ෂණ අනුව කිව හැකි ය. ලංකාවේ ගස් තුන හතරකට වඩා නැති මේ වර්ගයේ ගසක් අප විහාරස්ථානයේ ද තිබේ.", 
        "category": "plant",
        "image": "img_351_madara.jpg"
    },
    { "word": "මදිකා", "meaning": "මදටිය", "category": "plant" },
    { "word": "මදිත", "meaning": "එරබදු", "category": "plant" },
    { "word": "මදිත ඵල", "meaning": "එරබදු", "category": "plant" },
    { "word": "මදිරා", "meaning": "සුරා, රත් කිහිරි", "category": "liquid" },
    { "word": "මදී", "meaning": "එන්සාල්", "category": "plant" },
    { "word": "මදු", "meaning": "මලිත, මදු වැල්, සිහින් මදු", "category": "plant" },
    { "word": "මදුක", "meaning": "වැල්මී, උක් පැණි, මී පුප්", "category": "plant" },
    { "word": "මදුකද්වය", "meaning": "වැල්මී, මී පුප් (මී මල්)", "category": "plant" },
    { "word": "මදුකත", "meaning": "කිණිහිරි ගස", "category": "plant" },
    { "word": "මදුප්පිලා", "meaning": "මී ගස", "category": "plant" },
    { "word": "මදුපක්", "meaning": "මිදු කොළ", "category": "plant" },
    { "word": "මදුපතති", "meaning": "කිණිහිරි", "category": "plant" },
    { "word": "මදුපතහී", "meaning": "මී පැණි", "category": "food" },
    { "word": "මදුපවුරා", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "මදුපාහි", "meaning": "ගස්කෑලිය", "category": "plant" },
    { "word": "මදුපුෂ්ප", "meaning": "මීගස, මීමල්, (මීපුප්)", "category": "plant" },
    { "word": "මදුපුෂ්ප", "meaning": "මීමල්, (මීපුප්)", "category": "plant" },
    { "word": "මදුබුල", "meaning": "මීවදය", "category": "nature" },
    { "word": "මදුමඬු", "meaning": "වැල්මී, මීපැණි, දෙවගය", "category": "plant" },
    { "word": "මදුර", "meaning": "දෙළුම්පල, මීපැණි, දෙල්මයුෂ", "category": "plant" },
    { "word": "මදුරවචා", "meaning": "දූවගස", "category": "plant" },

    // --- පිටුව 352 ---
    { "word": "මදුරමරම්", "meaning": "සුඹුක්ගස", "category": "plant" },
    { "word": "මදුරස", "meaning": "මෝරගස, මිදි, වැල්මී, මීපැණි", "category": "plant" },
    { "word": "මදුරසා", "meaning": "මූරුවා", "category": "plant" },
    { "word": "මදුරා", "meaning": "මිදිපල, මීපැණි", "category": "plant" },
    { "word": "මදුරාමිල", "meaning": "තිත්තනිමල, සියඹලා ගස", "category": "plant" },
    { "word": "මදුරාමිලය", "meaning": "ගොරක", "category": "plant" },
    { "word": "මදුරැ", "meaning": "මදුරුතලා, එරබදුගස", "category": "plant" },
    { "word": "මදුරැට", "meaning": "මදුරුතලා ඇට", "category": "plant" },
    { "word": "මදුලිත", "meaning": "මූරුවා", "category": "plant" },
    { "word": "මදුලුවා", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මදුශෙඛණ්ඩ", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "මදුෂ්ටි", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මදුෂ්ටිල", "meaning": "ගැටපිච්ච, යොහොඹු, මීගස්", "category": "plant" },
    { "word": "මදුසර්ප්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "මදුසර්පික", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "මදුසාර", "meaning": "මීගස", "category": "plant" },
    { "word": "මදුසාර", "meaning": "මීගස", "category": "plant" },
    { "word": "මදෙන්කට", "meaning": "සුරා", "category": "liquid" },
    { "word": "මදෙන්කතා", "meaning": "වම්බටු, සුරා", "category": "plant" },
    { "word": "මදෙස්", "meaning": "පෙට්ටිය", "category": "general" },
    { "word": "මඩවාශ්ව", "meaning": "මීමල් වලින් සෑදූ සුරා", "category": "liquid" },
    { "word": "මඩවාශ්‍රව", "meaning": "මූරුවා", "category": "plant" },
    { "word": "මඩවාසව", "meaning": "මී පැණියෙන් හෝ මල් රස දමා සෑදූ ආසව, (පල්කර පෙරා ගත් ජලය)", "category": "liquid" },
    { "word": "මඩශ්‍රී", "meaning": "මීපැණි", "category": "food" },
    { "word": "මඩ", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "මධු", "meaning": "වැල්මී, ජීවානතිකා වැල් හෝ පලු ගස, මීපැණි, ඊයම්, මාරා ගස, මල්, මිදිරස", "category": "plant" },
    { "word": "මධුක", "meaning": "වැල්මී, උක්පැණි, ගල්මී ගස, උක්සකුරු, රත්හඳුන්, සුදු ඊයම්, මීමල්", "category": "plant" },
    { "word": "මධුක්‍ෂිකා", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මධුක්‍ෂීර", "meaning": "ඉඳි", "category": "plant" },
    { "word": "මධුකක්කුටි", "meaning": "පැණිදෙබම්", "category": "plant" },
    { "word": "මධුකපත්‍රක", "meaning": "සාරණ", "category": "plant" },
    { "word": "මධුකප්‍රිය", "meaning": "අඹ ගස", "category": "plant" },
    { "word": "මධුකකීලී", "meaning": "දෙබම් ප්‍රභේදයක්, ලප් නාරන්, රටඉඳි", "category": "plant" },
    { "word": "මධුකර", "meaning": "කිරිපලා, කිකිරිඳිය", "category": "plant" },
    { "word": "මධුකල්ප", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "මධුකා", "meaning": "මීපැණි, වැල්මී, ඇත්දෙමට", "category": "plant" },
    { "word": "මධුකො", "meaning": "මීගස්", "category": "plant" },
    { "word": "මධුකොෂ", "meaning": "මීවද, මීඉටි", "category": "nature" },
    { "word": "මධුගන්ධික පුෂ්ප", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "මධුච්ඡිහ", "meaning": "මීපැණි", "category": "food" },
    { "word": "මධුජ", "meaning": "මීඉටි", "category": "nature" },
    { "word": "මධුජම්බීර", "meaning": "පැණිදෙබම්", "category": "plant" },
    { "word": "මධුත්‍රය", "meaning": "සිනි, මීපැණි, ගිතෙල්", "category": "food" },
    { "word": "මධුතෘණ", "meaning": "උක්ගස", "category": "plant" },
    { "word": "මධුදිකා", "meaning": "මූරුවා", "category": "plant" },
    { "word": "මධුද්‍රැම", "meaning": "පලොල්ගස, අඹගස, (මී අඹ ගස)", "category": "plant" },
    { "word": "මධුදූතී", "meaning": "රත්පලොල් ගස", "category": "plant" },
    { "word": "මධුදෘබ", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "මධුදෘම", "meaning": "මීගස", "category": "plant" },
    { "word": "මධුධාතු", "meaning": "මැසිඳු", "category": "plant" },
    { "word": "මධුබුලි", "meaning": "උක්සකුරු ප්‍රභේදයක්", "category": "food" },
    { "word": "මධුපලට", "meaning": "මීවදය", "category": "nature" },
    { "word": "මධුපත්ති", "meaning": "කිණිහිරි", "category": "plant" },
    { "word": "මධුපනති", "meaning": "මීපැණි", "category": "food" },
    { "word": "මධුපර්ක", "meaning": "දීකිරි, ගිතෙල්, වතුර, සිනි, මීපැණි මේ පස මධු පර්ක නම් වේ.", "category": "compound" },
    { "word": "මධුපර්ණිකා", "meaning": "බෙරු, ඇද්දෙමට, එළ ජම්බු, කන්සා", "category": "plant" },

    // --- පිටුව 353 ---
    { "word": "මධුපර්ණී", "meaning": "රසකිඳ, ඇද්දෙමට, බෙරු, දෙබම්, විෂ්ණුක්‍රාන්ති, වරා, මූරුවා, මේවත්, නිදිකුම්බා, එළ ජම්බු", "category": "plant" },
    { "word": "මධුපත්‍රක", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මධුපත්‍රී", "meaning": "ඇද්දෙමට", "category": "plant" },
    { "word": "මධුපාලිකා", "meaning": "මූරුවා = ගම්භාරි", "category": "plant" },
    { "word": "මධුපිලු", "meaning": "මිනිරිමෝර (පැණිමෝර)", "category": "plant" },
    { "word": "මධුපුෂ්ප", "meaning": "මීපැණි, හෝපලු, මීගස, මාරා, මූණමල්, දත්ත, බඹර පැණි, වරාගස, ශතපුෂ්ප", "category": "plant" },
    { "word": "මධුපුෂ්පිකා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "මධුපුෂ්පී", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "මධුපුරී", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "මධුපුරඃ", "meaning": "මීගස", "category": "plant" },
    { "word": "මධුඵල", "meaning": "දීකිරි, පොල්, ඉඳිගස, මුද්දරප්පලම්", "category": "plant" },
    { "word": "මධුබහුලා", "meaning": "යොහොඹුවැල", "category": "plant" },
    { "word": "මධුභද්‍රා", "meaning": "ඇද්දෙමට", "category": "plant" },
    { "word": "මධුමක්‍ෂිකමුඛ", "meaning": "මඟුල්කරඳ", "category": "plant" },
    { "word": "මධුමජ්ජත්", "meaning": "අගුණවැල", "category": "plant" },
    { "word": "මධුමති", "meaning": "මූරුවාවැල", "category": "plant" },
    { "word": "මධුමක්‍ෂිකී", "meaning": "මීහකුරු, දසමන්", "category": "food" },
    { "word": "මධුමලකි", "meaning": "කිරිඅගුණ", "category": "plant" },
    { "word": "මධුමාක්‍ෂිකා", "meaning": "මැසිඳු, (මාක්‍ෂිකා)", "category": "plant" },
    { "word": "මධුමාර්ජක", "meaning": "ඉඳිගස", "category": "plant" },
    { "word": "මධුමාසප්‍රකාගක", "meaning": "කරඳ ගස", "category": "plant" },
    { "word": "මධුමාසප්‍රිය", "meaning": "කරඳගස", "category": "plant" },
    { "word": "මධුමූල", "meaning": "අල ප්‍රභේදයක්", "category": "plant" },
    { "word": "මධුමෙහ", "meaning": "මූත්‍රයෙහි මධු(සිනි) ඇති කරණ ප්‍රමේහ රෝගය", "category": "treatment" },
    { "word": "මධුයෂ්ටි", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මධුයෂ්ටිකා", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මධුයොනි", "meaning": "මුද්දරප්පලම්, මිදිවැල්", "category": "plant" },
    { "word": "මධුර", "meaning": "රත්මුරුංගා, මීලඹ, ර තු උක්, සිනි, ඇල්වී, සුදුදුරු, කළුඊයම්, සුදුඊයම්, මහරතණ, මීකැකිරි, මේවත්, උළුවා, කිරි පළු, වැල්මී, ශතපුෂ්ප, කවේළු, සාතාවාරිය, මහදුම්මැල්ල", "category": "plant" },
    { "word": "මධුරක", "meaning": "උක්පැණි, ජීවක, වැල්මී, පොණඬරු, ශතපුෂ්ප", "category": "plant" },
    { "word": "මධුරච්ඡද", "meaning": "මී", "category": "food" },
    { "word": "මධුරත්ව", "meaning": "දූවගස", "category": "plant" },
    { "word": "මධුරත්‍රය", "meaning": "ගිතෙල්, සිනි, මීපැණි යන තුන් වගය", "category": "food" },
    { "word": "මධුරතික්තක", "meaning": "වැල්මුරුංගා", "category": "plant" },
    { "word": "මධුරපර්ණික", "meaning": "අවරිය", "category": "plant" },
    { "word": "මධුරඵල", "meaning": "බෙබරගස, (මහමසන්)", "category": "plant" },
    { "word": "මධුරමර්ජකා", "meaning": "යොන්ඉඳිගස", "category": "plant" },
    { "word": "මධුරමණ්ඩරිකා", "meaning": "ඉඳිගස", "category": "plant" },
    { "word": "මධුරමර්ක", "meaning": "රටඉඳි", "category": "plant" },
    { "word": "මධුරමලක", "meaning": "ගොරකගෙඩි, ඇම්බරල්ල", "category": "plant" },
    { "word": "මධුරමාර්ජකා", "meaning": "ඉඳිගස", "category": "plant" },
    { "word": "මධුරවල්ලි", "meaning": "වැල්මී, දෙළුම්, පැණි දෙබම්", "category": "plant" },
    { "word": "මධුරශ්‍රවා", "meaning": "මිණඬා ඉඳි, වැල්මී", "category": "plant" },
    { "word": "මධුරස", "meaning": "ජීවක, මුද්දරප්පලම්, වතුර, උක්, කිරිකවේළු, ඇද්දෙමට", "category": "plant" },
    { "word": "මධුරසා", "meaning": "මුද්දරප්පලම්, කිරිපලා, කඩසකුරු, නියඳ, යොන්ඉඳි, මී ඉටි, මෑබගඟු, වැල්මුරුංගා, උක් දඬු", "category": "plant" },
    { "word": "මධුරා", "meaning": "සින්සාතාවාරිය, මේවත්, කවේළු, කිරිපලා, වේලා, තෙල්ලි, මෑබගඟු, ශතපුෂ්ප, ත්‍රස්තාවළු", "category": "plant" },
    { "word": "මධුරාම්ලක", "meaning": "ඇම්බරල්ලගස", "category": "plant" },
    { "word": "මධුරාම්ලඵල", "meaning": "පියල්ගස, කිරිපළු ගස", "category": "plant" },
    { "word": "මධුරාහ්වය", "meaning": "ඇම්බරල්ල, පැපිලිය", "category": "plant" },

    // --- පිටුව 354 ---
    { "word": "මධුරිකා", "meaning": "ශතපුෂ්ප, මහදුරු", "category": "plant" },
    { "word": "මධුරි", "meaning": "වැල්මී, වැල්මුරුංගා", "category": "plant" },
    { "word": "මධුරේණුකා", "meaning": "කපුගස, ඇඹුල්වේ", "category": "plant" },
    { "word": "මධුලක", "meaning": "ගල්මීගස, නියඳ, මීගස", "category": "plant" },
    { "word": "මධුලග්න", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "මධුලටිටිකා", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මධුලිකා", "meaning": "බක්මී, අඹ, මූරුවා", "category": "plant" },
    { "word": "මධුවල්ලී", "meaning": "වැල්මී, සිනිද්ද", "category": "plant" },
    { "word": "මධුවාග", "meaning": "මීඉටි", "category": "nature" },
    { "word": "මධුවිජ්", "meaning": "දෙළුම්ගස", "category": "plant" },
    { "word": "මධුවිජ්පුර", "meaning": "මීකැකිරි", "category": "plant" },
    { "word": "මධුශ්ශිල", "meaning": "මීගස", "category": "plant" },
    { "word": "මධුශ්වසා", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "මධුශ්‍රිත", "meaning": "මූරුවා, මීගස, මීඉටි", "category": "plant" },
    { "word": "මධුශ්‍රිග්‍රැ", "meaning": "රත්මුරුංගා, වැල්මුරුංගා", "category": "plant" },
    { "word": "මධුශිග්‍රැක", "meaning": "වැල්මුරුංගා", "category": "plant" },
    { "word": "මධුශෙෂ", "meaning": "මීඉටි", "category": "nature" },
    { "word": "මධුශොණික", "meaning": "මීපැණි", "category": "food" },
    { "word": "මධුශ්‍රාව", "meaning": "මීගස", "category": "plant" },
    { "word": "මධුශ්‍රවා", "meaning": "වලාවැන්න. වැල්මී, මූරුවා, කිරිපලා, මීගස, ජීවාන්තිකා වැල, මැඩ ගඟු", "category": "plant" },
    { "word": "මධුශ්‍රාවා", "meaning": "මීගස", "category": "plant" },
    { "word": "මධුශ්‍රෙණී", "meaning": "මූරුවා, මෑබගඟු", "category": "plant" },
    { "word": "මධුශ්‍රෙනිකා", "meaning": "නියඳ", "category": "plant" },
    { "word": "මධුන්‍ශිල", "meaning": "(මධුප්ශිල) = මීගස", "category": "plant" },
    { "word": "මධුපුෂ්ප", "meaning": "අශෝකා", "category": "plant" },
    { "word": "මධුයෝනි", "meaning": "මුද්‍රිකා", "category": "plant" },
    { "word": "මධුසුයා", "meaning": "මූරුවා", "category": "plant" },
    { "word": "මධුක", "meaning": "වැල්මී, මීගස", "category": "plant" },
    { "word": "මධුකසාර", "meaning": "(මගරි) මීඅරටු", "category": "plant" },
    { "word": "මධුවුජ්ජට", "meaning": "මීඉටි", "category": "nature" },
    { "word": "මධූතී", "meaning": "එළ ජම්බු", "category": "plant" },
    { "word": "මධුල", "meaning": "මීකැකිරි, අඹ, මූරුවා, ගල් මීගස, දියමීගස", "category": "plant" },
    { "word": "මධුලක", "meaning": "ගල්මීගස", "category": "plant" },
    { "word": "මධුලිකා", "meaning": "වැල්මී", "category": "plant" },
    { "word": "මධුලිකා", "meaning": "මූරුවා", "category": "plant" },
    { "word": "මධුබ්‍යාකූක", "meaning": "අලප්‍රභෙදයක්", "category": "plant" },
    { "word": "මන්ත්‍රප්ශිල්ම", "meaning": "ගින්දර", "category": "nature" },
    { "word": "මන්වාඩි", "meaning": "මදටිය", "category": "plant" },
    { "word": "මන්ජරි", "meaning": "කැන", "category": "plant" },
    { "word": "මන්ජල්", "meaning": "කසා", "category": "plant" },
    { "word": "මන්ජිෂ්ටා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "මන්ඩල්", "meaning": "ඇට්ටර", "category": "plant" },
    { "word": "මන්ථ", "meaning": "අත්සුණු හා ගිතෙල් මිශ්‍ර කොට ඇල් දියෙන් වඩා දිය නොකොට, වඩා දැඩි නොකොට ගනා සකස් කර ගන්නා ලද ආහාරය “මන්ථ” නමි.", "category": "food" },
    { "word": "මන්ථජ", "meaning": "වෙඬරු", "category": "food" },
    { "word": "මන්ථන", "meaning": "කළඹන දණ්ඩ, වෙඬරු", "category": "equipment" },
    { "word": "මන්ථර", "meaning": "කළඹන දණ්ඩ, මල්කොපුව, ගෙඩිය", "category": "plant" },
    { "word": "මන්ථාන", "meaning": "ඇසළ ගස, කළඹන දණ්ඩ", "category": "plant" },
    { "word": "මන්ද", "meaning": "මාරා ගස, එරබදු ගස", "category": "plant" },
    { "word": "මන්දපතික්කිල", "meaning": "සෙන්දිරික්කා", "category": "plant" },
    { "word": "මන්දස්", "meaning": "මහකරඹ", "category": "plant" },
    { "word": "මන්දාහේතුක", "meaning": "මයිලගස", "category": "plant" },
    { "word": "මඤ්", "meaning": "කිරිඳි", "category": "plant" },
    { "word": "මඤ්ජර", "meaning": "කටුවැල්බටු, කටුකෑල, එරබදු, වරා, වැල්තිබ්බටු, යක්බේරිය, එළවරා, නල්සෙවෙල්", "category": "plant" },
    { "word": "මඤ්ජරක", "meaning": "හෙළසැබෝ", "category": "plant" },
    { "word": "මඤ්ජරමරම්", "meaning": "මදුරා", "category": "plant" },
    { "word": "මඤ්ජරි", "meaning": "කුප්පමේනිය", "category": "plant" },
    { "word": "මඤ්ජරා", "meaning": "හෙළවරා", "category": "plant" },
    { "word": "මඤ්ජරෝපා", "meaning": "ගල්සෙවෙල්", "category": "plant" },
    { "word": "මඤ්ජකි", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "මඤ්ජේෂණ", "meaning": "මදටියසුඹු", "category": "plant" },
    { "word": "මන්මල", "meaning": "අඹගස, ජූල්ගස, (දිවුල්ගස)", "category": "plant" },
    { "word": "මන්මථාලය", "meaning": "අඹගස", "category": "plant" }
];

