// data_507_513.js - පිටු 507 සිට 513 දක්වා සියලුම වචන සහ විස්තර
const data_extra_507_513 = [

    // --- පිටුව 507 ---
    { "word": "සොහස්බන්ධ", "meaning": "හෙළ හිඹුරු", "category": "plant" },
    { "word": "සොහාඤ්ජන", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සොම්‍යා", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "සොම", "meaning": "මාරා, යාපුර, බෝදි ඇට, මුවකිරිය, රත්හඳුන්, බැමිතිරිය", "category": "plant" },
    { "word": "සොමක්‍ෂීර", "meaning": "මුවකිරිය", "category": "plant" },
    { "word": "සොමනස", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "සොමපාදප", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "සොමරාජිකා / සොමරාජී", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "සොමිලතා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "සොමවෘක්‍ෂ", "meaning": "මදට ගස, මුවකිරිය", "category": "plant" },
    { "word": "සොමවෘක්‍ෂො", "meaning": "හෙළ කිහිරි", "category": "plant" },
    { "word": "සොමවල්ක", "meaning": "කරඳ, හෙළ කිහිරි, ඇත්දෙමට, මදටිය", "category": "plant" },
    { "word": "සොමවල්ලරී", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "සොමවල්ලිකා", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "සොමවල්ලී", "meaning": "මුවකිරිය, බෝදි ඇට, කංසා, රසකිඳ, මුඟුණුවැන්න, ලුණුවිල", "category": "plant" },
    { "word": "සොමවෘක්‍ෂ", "meaning": "එළ කිහිරි, ඇත්දෙමට", "category": "plant" },
    { "word": "සොමසති", "meaning": "දුම්මල", "category": "plant" },
    { "word": "සොමසෘති", "meaning": "දුම්මල", "category": "plant" },
    { "word": "සොම සමභවා", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "සොමසාර", "meaning": "එළ කිහිරි", "category": "plant" },
    { "word": "සොම හරිතකී", "meaning": "බෙලි", "category": "plant" },
    { "word": "සොමා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "සොමි", "meaning": "කපුරු", "category": "plant" },
    { "word": "සොමිදු", "meaning": "ශුක්‍රධාතුව", "category": "anatomy" },
    { "word": "සොමොවරහ", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "සොර", "meaning": "හොර ගස, (සරල) හිඟුරු පියලි", "category": "plant" },
    { "word": "සොරස", "meaning": "යුෂ, (ඉස්ම)", "category": "liquid" },
    { "word": "සොරහර", "meaning": "හොර අරටුව", "category": "plant" },
    { "word": "සෞවීරං", "meaning": "කාඩි", "category": "liquid" },
    { "word": "සොස", "meaning": "වියලීම = ක්‍ෂය රෝගය", "category": "treatment" },
    { "word": "සොසන", "meaning": "මිරිස්", "category": "plant" },
    { "word": "සොසා", "meaning": "කකීටක ශෘංගි", "category": "plant" },
    { "word": "සොසො", "meaning": "ක්‍ෂය රෝගය", "category": "treatment" },
    { "word": "සොළොසභා", "meaning": "සොලොසහුල් (අඟල් 16)", "category": "general" },
    { "word": "සෝ", "meaning": "කහ", "category": "plant" },
    { "word": "සෝද", "meaning": "තෙරිවිස", "category": "plant" },
    { "word": "සෝදක", "meaning": "උණුදිය", "category": "liquid" },
    { "word": "සෝදිය", "meaning": "ඔහදිය", "category": "plant" },
    { "word": "සෝනක", "meaning": "සුදු ලූනු, තොටිල ගස", "category": "plant" },
    { "word": "සෝනා", "meaning": "තොටිල, එරබදු ගස", "category": "plant" },
    { "word": "සෝනික්කන්", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "සෝමී", "meaning": "කළු කිහිරි, මුවකිරිය, ප්‍රමේහ රෝගයක්", "category": "plant" },
    { "word": "සෝමිකණ්ඨක", "meaning": "බෙබර ගස", "category": "plant" },
    { "word": "සෝමිරාජි", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "සෝමිවල්ලිකා", "meaning": "මදටිය, මුවකිරිය, සන්නිනායන්", "category": "plant" },
    { "word": "සෝමිවැල්", "meaning": "මුවකිරිය", "category": "plant" },
    { "word": "සෝමෝවරයා", "meaning": "කෙළිඳ සාල්", "category": "plant" },
    { "word": "සෝවල්ඝය", "meaning": "මිදටිය", "category": "plant" },
    { "word": "සෝස", "meaning": "සවාස නම් රෝගය", "category": "treatment" },
    { "word": "සෝසා", "meaning": "කකුළු සුනු", "category": "animal" },
    { "word": "ස්‍යන්දන", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "ස්‍යාමාකා", "meaning": "ඇසළ", "category": "plant" },
    { "word": "සෞගන්ධමාරක", "meaning": "පික්මල", "category": "plant" },
    { "word": "සෞගන්ධ", "meaning": "මූණමල්, ගෙන්දගම්, රටකපුරු", "category": "plant" },
    { "word": "සෞගන්ධිකා", "meaning": "ගෙන්දගම්, හෙල්මැලි", "category": "mineral" },
    { "word": "සෞගන්ධිකපත්‍රක", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "සෞගන්ධික", "meaning": "හෙල්මැලි, සුවඳතණ, රතණ", "category": "plant" },
    { "word": "සෞණ්ඩී", "meaning": "ගජතිප්පිලි", "category": "plant" },

    // --- පිටුව 508 ---
    { "word": "සෞධභූෂණ", "meaning": "හුණු", "category": "mineral" },
    { "word": "සෞභාග්‍ය", "meaning": "සින්දූරම්, පුස්කර", "category": "mineral" },
    { "word": "සෞභාඤ්ජන", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "සෞම්‍ය", "meaning": "දිවුල් ගස, අත්තන, සිවංගුරු, අස්වැන්න", "category": "plant" },
    { "word": "සෞම්‍යගන්ධි", "meaning": "නෙළුම් මල", "category": "plant" },
    { "word": "සෞම්‍යනසයාන්ති", "meaning": "දාසමන්, සමන් කැකුළු", "category": "plant" },
    { "word": "සෞම්‍යලතා", "meaning": "සෝමලතා, සෝම වල්ලී, ලුණුවිල", "category": "plant" },
    { "word": "සෞම්‍යා", "meaning": "අස්වැන්න, සුවංගුරු, ඔලිඳ", "category": "plant" },
    { "word": "සෞර", "meaning": "දිවුල් ගස", "category": "plant" },
    { "word": "සෞර ගන්ධිකා", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "සෞරජ", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "සෞරභ", "meaning": "කොකුම්", "category": "plant" },
    { "word": "සෞරාෂ්ට්‍රක", "meaning": "ලෝකඩ", "category": "mineral" },
    { "word": "සෞරාෂ්ට්‍රව සමභව", "meaning": "සුදු පාසානම්", "category": "mineral" },
    { "word": "සෞරෙය", "meaning": "සුදු කටු කරඬු", "category": "plant" },
    { "word": "සෞවචිල", "meaning": "කළු ලුණු, සුවස ලුණු", "category": "mineral" },
    { "word": "සෞවර්ණ", "meaning": "සිද්ධිගුරු", "category": "plant" },
    { "word": "සෞවර්ණ භෙදනී", "meaning": "පුවඟු", "category": "plant" },
    { "word": "සෞවීර", "meaning": "බෙබර, නුදු ගස, කාඩි, (යව සාලින් පිළියෙලකර ගත් කාඩි ජලය)", "category": "plant" },
    { "word": "සෞවීරක", "meaning": "කාඩි ආදි අම්ල වර්ග", "category": "liquid" },
    { "word": "සෞවීරසාර", "meaning": "නොයඳුන්", "category": "plant" },
    { "word": "සෞතානාක", "meaning": "තොටිල", "category": "plant" },
    { "word": "ස්බන්ධජ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "ස්බන්ධතරු", "meaning": "පොල්ගස", "category": "plant" },
    { "word": "ස්බන්ධඵල", "meaning": "දිවුල්ගස, පොල්ගස", "category": "plant" },
    { "word": "ස්ඛන්ධබන්ධනා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "ස්බන්ධමූල", "meaning": "තුන්පුවිල", "category": "plant" },
    { "word": "ස්බන්ධරුහ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "ස්තන්‍ය", "meaning": "කිරි", "category": "liquid" },
    { "word": "ස්තොක", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "ස්ත්‍රියොරාජ", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ස්ත්‍රීවිනතහාරී", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "ස්ත්‍රීනිරීක්‍ෂණදොහද", "meaning": "හෝපළු", "category": "plant" },
    { "word": "ස්තන්‍යක්‍ෂීරාවත", "meaning": "හුණුගල්", "category": "mineral" },
    { "word": "ස්තලකමල", "meaning": "ගොඩපියුම (මිතඹර = එක්පෙති පියුම)", "category": "plant" },
    { "word": "ස්තලකුමුද", "meaning": "කණේරු", "category": "plant" },
    { "word": "ස්තලමඤ්ජරී", "meaning": "සැබෝ", "category": "plant" },
    { "word": "ස්තලශෘංගාට", "meaning": "ගොකටු", "category": "plant" },
    { "word": "ස්තලේරුහ", "meaning": "කෝමාරිකා", "category": "plant" },
    { "word": "ස්ථවිර", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ස්ථානකර්ණී", "meaning": "කටරොලු", "category": "plant" },
    { "word": "ස්ථානවකුලා", "meaning": "වේලාගස", "category": "plant" },
    { "word": "ස්ථාපනක", "meaning": "මහරී", "category": "plant" },
    { "word": "ස්ථාපනී", "meaning": "දියමින්ත", "category": "plant" },
    { "word": "ස්ථාලී", "meaning": "පලොල්, රත්පලොල්", "category": "plant" },
    { "word": "ස්ථාවරා", "meaning": "හෙළනික", "category": "plant" },
    { "word": "ස්ථිර", "meaning": "යකඩ, සල්ගස", "category": "mineral" },
    { "word": "ස්ථිරක", "meaning": "කරබෙහිය", "category": "plant" },
    { "word": "ස්ථිරගන්ධ", "meaning": "සපු, පලොල්, වැටකේ", "category": "plant" },
    { "word": "ස්ථිරච්ඡද", "meaning": "කරගස, භූරපත්‍ර, බූරුද, (සාරණ)", "category": "plant" },
    { "word": "ස්ථිරජීවිතා", "meaning": "ඉඹුල් ගස", "category": "plant" },
    { "word": "ස්ථිරද්‍රැම", "meaning": "මීගස", "category": "plant" },
    { "word": "ස්ථිරපත්‍ර", "meaning": "කිතුල් ගස", "category": "plant" },
    { "word": "ස්ථිරපුෂ්ප", "meaning": "සපුගස, මූණමල් ගස", "category": "plant" },
    { "word": "ස්ථිරපුෂ්පින්", "meaning": "මාරාගස", "category": "plant" },
    { "word": "ස්ථිරඵලා", "meaning": "කොමඩු පුහුල්", "category": "plant" },
    { "word": "ස්ථිරරබගා", "meaning": "බෙරු", "category": "plant" },

    // --- පිටුව 509 ---
    { "word": "ස්ථිරරාගා", "meaning": "වනුවැල්, (වෙනිවැල්)", "category": "plant" },
    { "word": "ස්ථිරරාගයා", "meaning": "දාරුහරිද්‍රා", "category": "plant" },
    { "word": "ස්ථිරසාදනක", "meaning": "නික", "category": "plant" },
    { "word": "ස්ථිරසාර", "meaning": "මාරාගස", "category": "plant" },
    { "word": "ස්ථිරා", "meaning": "අස්වැන්න, කිරිකවෙලු, ඉඹුල්", "category": "plant" },
    { "word": "ස්ථිරාදිගණය", "meaning": "අස්වැන්න, සුළුබූරුද (සාරණ), එඬරු, ගස්කැලිය, (නාගබලා), ඔසබිය, ජීවක අල, ගොකටු, (නෙරෙංචි) සාතාවාරිය, පුස්වැන්න, කිරිබදු අල, වළාවැන්න, (හංසපාදි) එළබටු, කටුවැල්බටු, ඇත්සැටිය, සුළු ගෙලඩිය, (සුළු මුංවැන්න) මහ ගෙලඩිය, (මහමුංවැන්න) වඳුරු මෑ, මඟුල්කුඹුරුවැන්න යන මේ ස්ථිරාදිගණය. විෂම - ගුල්ම - වාත - කාස - මුත්‍ර - පිත්ත යන මේ දේ නසන්නේ යි.", "category": "compound" },
    { "word": "ස්ථිරාබද්ධිය", "meaning": "කිතුල්ගස", "category": "plant" },
    { "word": "ස්ථිරායුස්", "meaning": "ඉඹුල් ගස", "category": "plant" },
    { "word": "ස්ථිරායු", "meaning": "ඉඹුල්ගස", "category": "plant" },
    { "word": "ස්ථුල", "meaning": "කොස්, ගජතිප්පිලි, කැකිරි, මහඑන්සාල්", "category": "plant" },
    { "word": "ස්ථුලකචචු", "meaning": "කූරනත් (කුරක්කන්)", "category": "plant" },
    { "word": "ස්ථුලකණා", "meaning": "මාදුරු (මහදුරු)", "category": "plant" },
    { "word": "ස්ථුලකණටක", "meaning": "තලා, ඉඹුල්", "category": "plant" },
    { "word": "ස්ථුලකණ්ඨ", "meaning": "බටුගස", "category": "plant" },
    { "word": "ස්ථුලකන්ද", "meaning": "රතුළූනු, කිඩාරම්", "category": "plant" },
    { "word": "ස්ථුලකණ්ඩි", "meaning": "වම්බටු", "category": "plant" },
    { "word": "ස්ථුලචඤ්චු", "meaning": "මහඑරබු", "category": "plant" },
    { "word": "ස්ථුලජීරක", "meaning": "සුදු දුරු, කළුදුරු", "category": "plant" },
    { "word": "ස්ථුලදන්තී", "meaning": "මුක්ප නාණ (මුදුතණ)", "category": "plant" },
    { "word": "ස්ථුලදලා", "meaning": "කෝමාරිකා", "category": "plant" },
    { "word": "ස්ථුලපට්ට", "meaning": "කපුගස", "category": "plant" },
    { "word": "ස්ථුලපුෂ්ප", "meaning": "ගලේ උපන් කටරොලු", "category": "plant" },
    { "word": "ස්ථුලඵල", "meaning": "ඉඹුල්ගස, පනසගස", "category": "plant" },
    { "word": "ස්ථුලබ්‍රහතී / ස්ථුලභණ්ඩාකී", "meaning": "වම්බොටු", "category": "plant" },
    { "word": "ස්ථුලමරිච", "meaning": "තකුල්", "category": "plant" },
    { "word": "ස්ථුලවල්කල", "meaning": "රත්ලොත්", "category": "plant" },
    { "word": "ස්ථුලවෛදෙහී", "meaning": "ගජතිප්පිලි", "category": "plant" },
    { "word": "ස්ථුලශාඛාට", "meaning": "ගොකටු", "category": "plant" },
    { "word": "ස්ථුලා", "meaning": "මහඑන්සාල්", "category": "plant" },
    { "word": "ස්ථුලාජාජී", "meaning": "මාදුරු", "category": "plant" },
    { "word": "ස්ථුලෙලා", "meaning": "මහ එන්සාල්", "category": "plant" },
    { "word": "ස්නෞතෙයක", "meaning": "හරංකසා", "category": "plant" },
    { "word": "ස්නෞකද්‍රව", "meaning": "තලප", "category": "plant" },
    { "word": "ස්නෞවක", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "ස්නෞහනෙය", "meaning": "සත්වන්ති (ග්‍රන්ථි පර්ණී)", "category": "plant" },
    { "word": "ස්නෞහනෙයක", "meaning": "පොණඩරු", "category": "plant" },
    { "word": "ස්නිග්ධ", "meaning": "බෙබර, ගොරද, හීන් බෙබර, රත්එඬරු, හොරගස, ගෝරෝචන", "category": "plant" },
    { "word": "ස්නිග්ධ කරඤ්ජක", "meaning": "කරඳ", "category": "plant" },
    { "word": "ස්නිග්ධතණ්ඩුල", "meaning": "සැට දා හාල්", "category": "plant" },
    { "word": "ස්නිග්ධදාරු", "meaning": "දේවදාර, හොරගස", "category": "plant" },
    { "word": "ස්නිග්ධනන්දජ", "meaning": "දේවදාර", "category": "plant" },
    { "word": "ස්නිග්ධපර්ණී", "meaning": "මුරුවා, ඇත්දෙමට", "category": "plant" },
    { "word": "ස්නිග්ධපත්‍ර", "meaning": "බෙබර, සිරිල, දිඹුල්", "category": "plant" },
    { "word": "ස්නිග්ධ පත්‍රක", "meaning": "දේවදාර, බෙබර, පාලඬා, කොකුම්", "category": "plant" },
    { "word": "ස්නිග්ධඵලා", "meaning": "අරත්ත, ඒකාවේරිය", "category": "plant" },
    { "word": "ස්නිග්ධා", "meaning": "ගෝරෝචන, තලප, බෙබර ගෙඩි, රත්එඬරු", "category": "plant" },
    { "word": "ස්නිග්ධාච්ඡද", "meaning": "මුරුවා", "category": "plant" },
    { "word": "ස්නිග්ධාජච්වි", "meaning": "බෙබර", "category": "plant" },

    // --- පිටුව 510 ---
    { "word": "ස්නුක් / ස්නුෂා / ස්නුහ්(හා)", "meaning": "දළුක්", "category": "plant" },
    { "word": "ස්නුගච්ඡද", "meaning": "සීනුක්, ක්‍ෂීරකංචුකී වෘක්‍ෂය", "category": "plant" },
    { "word": "ස්නුහී", "meaning": "පතුක්, දළුක්", "category": "plant" },
    { "word": "ස්නෙහ", "meaning": "තලතෙල්, ගිතෙල්", "category": "liquid" },
    { "word": "ස්නෙහ පිණ්ඩිතක", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "ස්නෙහඵල", "meaning": "දේවදාර", "category": "plant" },
    { "word": "ස්නෙහබිජ", "meaning": "රුකගුණ", "category": "plant" },
    { "word": "ස්නෙහබීජ", "meaning": "රුකගුණ, බදුල්ල", "category": "plant" },
    { "word": "ස්නෙහහරඬ", "meaning": "තල", "category": "plant" },
    { "word": "ස්නොහවිඩ", "meaning": "දේවදාරගස", "category": "plant" },
    { "word": "ස්නෙහවිද්", "meaning": "පියල්ගස", "category": "plant" },
    { "word": "ස්නෙහවෘක්‍ෂ", "meaning": "දේවදාර ගස", "category": "plant" },
    { "word": "ස්පක්", "meaning": "පික්මල්", "category": "plant" },
    { "word": "ස්පෘක්කා", "meaning": "පික්මල්, උණකපුරු, නිදිකුම්බා", "category": "plant" },
    { "word": "ස්පෘශා / ස්පෘශී / ස්පෘතී", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "ස්ඵට", "meaning": "නයිපෙණ", "category": "plant" },
    { "word": "ස්ඵටික", "meaning": "පලිඟු, කපුරු, සුදුපාසානම්", "category": "mineral" },
    { "word": "ස්ඵටිකාභ්‍ය", "meaning": "සුදුපාසානම්", "category": "mineral" },
    { "word": "ස්ඵටිකාර", "meaning": "සිනක්කාරම්", "category": "mineral" },
    { "word": "ස්ඵටිකාහුව", "meaning": "කපුරු", "category": "plant" },
    { "word": "ස්ඵටිකොපල", "meaning": "පලිඟු", "category": "mineral" },
    { "word": "ස්ඵඤ්ජන", "meaning": "කෝන්ගස, තිඹිරි", "category": "plant" },
    { "word": "ස්ඵගීලජ්ජා", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ස්ඵගීශුභ්‍රා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "ස්ඵලා", "meaning": "ලාපල, (ගැට=මැලසි)", "category": "plant" },
    { "word": "ස්ඵුට", "meaning": "මහදත්ත", "category": "plant" },
    { "word": "ස්ඵුරී", "meaning": "කැකිරි", "category": "plant" },
    { "word": "ස්ඵුජීය / ස්ඵුජීක", "meaning": "තිඹිරි", "category": "plant" },
    { "word": "ස්ඵොටක / ස්ඵොටද", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "ස්ඵොටවිජ්ජක", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "ස්ඵොටිකා", "meaning": "තිඹිරි, ඉඹුල්", "category": "plant" },
    { "word": "ස්ඵොතා", "meaning": "වරාගස, වැලිද්ද (වල්ඉද්ද)", "category": "plant" },
    { "word": "ස්මරදූතී", "meaning": "තලගස, පලොල් ගස", "category": "plant" },
    { "word": "ස්මරාධිපාස", "meaning": "අශොක (හෝපළු)", "category": "plant" },
    { "word": "ස්ලක්‍ෂණ", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "ස්ලක්‍ෂණත්‍වක්", "meaning": "කරගස", "category": "plant" },
    { "word": "ස්ලෙෂ්ම", "meaning": "සෙම", "category": "anatomy" },
    { "word": "ස්ලෙෂ්මක", "meaning": "කිරිපලු, කිරිකවෙලු", "category": "plant" },
    { "word": "ස්ලෙෂ්මාතක", "meaning": "ලෝලුගස", "category": "plant" },
    { "word": "ස්‍යාමා", "meaning": "මකුණුවැන්න, නාගස, එළ රතණ, කළු තුස්තවාලු, වැල් පෙනෙල, ඉරමුසු, පෝටා වැල", "category": "plant" },
    { "word": "ස්‍යයිත්", "meaning": "පියාගස", "category": "plant" },
    { "word": "ස්‍යංසි", "meaning": "මොරගස", "category": "plant" },
    { "word": "ස්‍යුසොට", "meaning": "කොකැටිය, (දියඉකිරිය)", "category": "plant" },
    { "word": "ස්‍යුතජල", "meaning": "උණු දිය", "category": "liquid" },
    { "word": "ස්‍යුත්", "meaning": "උළුකැඳ", "category": "food" },
    { "word": "ස්‍රුව", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "ස්‍රුවා", "meaning": "මුරුවා", "category": "plant" },
    { "word": "ස්‍රාවක", "meaning": "මිරිස්", "category": "plant" },
    { "word": "ස්‍රිබංගි", "meaning": "නුග ගස, කකීටකශෘංගි", "category": "plant" },
    { "word": "ස්‍රෙෂ්ඨා", "meaning": "ඔලිඳ", "category": "plant" },

    // --- පිටුව 511 ---
    { "word": "ස්‍රොතස්නී", "meaning": "සුවසලුණු", "category": "mineral" },
    { "word": "ස්‍රොතප් / ස්‍රොතොඤ්ජන", "meaning": "නොයඳුන්", "category": "mineral" },
    { "word": "ස්වාඞ්ගරු", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "ස්වාස්න", "meaning": "සර්ජිකක්‍ෂාර", "category": "mineral" },
    { "word": "ස්වාත", "meaning": "පත්‍රාහිංගු", "category": "plant" },
    { "word": "ස්වාච", "meaning": "මුරුවා", "category": "plant" },
    { "word": "ස්වගුප්තා", "meaning": "නිදිකුම්බා, වඳුරු මෑ", "category": "plant" },
    { "word": "ස්වච්ඡ", "meaning": "එළ රතණ, මිණිරන්", "category": "plant" },
    { "word": "ස්වච්ඡපත්‍ර", "meaning": "මිණිරන්", "category": "mineral" },
    { "word": "ස්වතිතරො", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "ස්වදංෂ්ට්‍රා", "meaning": "ගොකටු", "category": "plant" },
    { "word": "ස්වදිසී", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "ස්වධාප්‍රිය", "meaning": "කළුතලා", "category": "plant" },
    { "word": "ස්වතනාතක", "meaning": "දෙඹගස", "category": "plant" },
    { "word": "ස්වපද", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "ස්වපිණ්ඩා", "meaning": "පිණ්ඩබරජ්ජර, (රටඉඳි)", "category": "plant" },
    { "word": "ස්වයංබහුජනා", "meaning": "වඳුරුමෑ", "category": "plant" },
    { "word": "ස්වයංභූ", "meaning": "කළුතලා", "category": "plant" },
    { "word": "ස්වර්චල", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "ස්වර්ජිකා / ස්වර්ජිකාපාක්‍ය", "meaning": "යවකාරලුණු", "category": "mineral" },
    { "word": "ස්වර්ණ", "meaning": "ඇසළ, රත්රන්, හරන් කසා, අත්තන, නාමල්රේණු", "category": "plant" },
    { "word": "ස්වර්ණක්‍ෂීරී", "meaning": "රත්කිරිගොකටු", "category": "plant" },
    { "word": "ස්වර්ණකෙතකී", "meaning": "රන්වන් වැටකේ", "category": "plant" },
    { "word": "ස්වර්ණගන්ධා", "meaning": "පික්මලි", "category": "plant" },
    { "word": "ස්වර්ණඥපංචා", "meaning": "ඇසළගස", "category": "plant" },
    { "word": "ස්වර්ණජ", "meaning": "ඊයම්", "category": "mineral" },
    { "word": "ස්වර්ණද්වා", "meaning": "රන්කිරි ගොකටු", "category": "plant" },
    { "word": "ස්වර්ණදී", "meaning": "ඇත්සැටිය", "category": "plant" },
    { "word": "ස්වර්ණදිමිතී", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "ස්වර්ණද්‍රැ / ස්වර්ණද්‍රැම", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ස්වර්ණපත්‍රී", "meaning": "සෙනෙහ කොළ", "category": "plant" },
    { "word": "ස්වර්ණපාටක", "meaning": "පුෂ්කර", "category": "plant" },
    { "word": "ස්වර්ණපුෂ්ප", "meaning": "සපු, ඇසළ, රන් වැටකේ, බැමිතිරිය, කින්හිරි", "category": "plant" },
    { "word": "ස්වර්ණපුෂ්පිකා", "meaning": "රන්වන් බෝලිද්ද, ඇසළ", "category": "plant" },
    { "word": "ස්වර්ණපුෂ්පී", "meaning": "වල් අබ", "category": "plant" },
    { "word": "ස්වර්ණඵලා", "meaning": "රත්කෙසෙල්", "category": "plant" },
    { "word": "ස්වර්ණවල්කල", "meaning": "තොවිල", "category": "plant" },
    { "word": "ස්වර්ණවිජ", "meaning": "නෙළු තෙලුම්", "category": "plant" },
    { "word": "ස්වර්ණභූෂිතා", "meaning": "කොල්ලම් කොළ", "category": "plant" },
    { "word": "ස්වර්ණනාබගාර", "meaning": "රන්වන් කිකිරි දිය", "category": "plant" },
    { "word": "ස්වර්ණමාක්‍ෂික", "meaning": "රන්මැසිද", "category": "mineral" },
    { "word": "ස්වර්ණලතා", "meaning": "දූදු", "category": "plant" },
    { "word": "ස්වර්ණවර්ණා", "meaning": "කහ, වනුවැල්", "category": "plant" },
    { "word": "ස්වර්ණවල්කල", "meaning": "තොපිල", "category": "plant" },
    { "word": "ස්වර්ණසෙපාලිකා", "meaning": "ඇසළ, රන්වන් සේපාලිකා", "category": "plant" },
    { "word": "ස්වර්ණස්පාල්‍යා", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ස්වර්ණාඛ්‍ය", "meaning": "නාමල් රේණු, ඇසළ", "category": "plant" },
    { "word": "ස්වර්ණාට", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ස්වර්ණාරි", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ස්වතී", "meaning": "හරංකසා", "category": "plant" },
    { "word": "ස්වරකත", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "ස්වරත", "meaning": "රුකගුණ", "category": "plant" },
    { "word": "ස්වරධාතක", "meaning": "නාමල්රේණු, නාකේසුරු", "category": "plant" },
    { "word": "ස්වරල", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "ස්වරස", "meaning": "යුෂ, තලාගස, රුකගුණ", "category": "general" },
    { "word": "ස්වරාහද්‍රා", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "ස්වල්පකෙශරින්", "meaning": "කොබෝලීල", "category": "plant" },

    // --- පිටුව 512 ---
    { "word": "ස්වල්පපත්‍රක", "meaning": "වැල්මී", "category": "plant" },
    { "word": "ස්වල්පමෙධා", "meaning": "පලොල්", "category": "plant" },
    { "word": "ස්වල්පවර්ණා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "ස්වශක්තු", "meaning": "අත්සුණු", "category": "food" },
    { "word": "ස්වසතිකා", "meaning": "හීන්සාතාවාරිය, කිඹුල්වැන්න", "category": "plant" },
    { "word": "ස්වසද", "meaning": "පුෂ්කර", "category": "plant" },
    { "word": "ස්වසන", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "ස්වසමිභූමි", "meaning": "ලුණුවිල", "category": "plant" },
    { "word": "ස්වසාන", "meaning": "සන්, (සඞ්ඛ) සෝභොන", "category": "general" },
    { "word": "ස්වාදුම්ල", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "ස්වාද්වී", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "ස්වාදු", "meaning": "ජීවක, කිරිකවෙලු, මුද්දරප් පලම්", "category": "plant" },
    { "word": "ස්වාදුකණ්ටක", "meaning": "උගුරුස්ස, ගොකටු", "category": "plant" },
    { "word": "ස්වාදුකන්‍ද", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "ස්වාදුකා", "meaning": "දත්ත (නාගදන්ති)", "category": "plant" },
    { "word": "ස්වාදුඛණ්ඩ", "meaning": "උක්සකුරු", "category": "food" },
    { "word": "ස්වාදුගන්ධා", "meaning": "කෝවක්කා, රන්මුරුංගා", "category": "plant" },
    { "word": "ස්වාදුගරා", "meaning": "කලුඅගිල්", "category": "plant" },
    { "word": "ස්වාදුතික්තක", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "ස්වාදුතික්තඵල", "meaning": "කටුවෙලඟ", "category": "plant" },
    { "word": "ස්වාදුත්‍රිඵල", "meaning": "යොන්ඉඳි, (රටඉඳි) මුද්දරප්පලම්, ඇත්දෙමට ගෙඩි (මේවා මිහිරි ඵලයෝයි)", "category": "compound" },
    { "word": "ස්වාදුපත්‍ර", "meaning": "ජුල් (දිවුල්)", "category": "plant" },
    { "word": "ස්වාදුපර්ණී", "meaning": "වරාගස", "category": "plant" },
    { "word": "ස්වාදුපාකා", "meaning": "කලුකැම්මේරිය", "category": "plant" },
    { "word": "ස්වාදුපිණ්ඩා", "meaning": "යොන්ඉඳි", "category": "plant" },
    { "word": "ස්වාදුපුෂ්ප", "meaning": "මීගස", "category": "plant" },
    { "word": "ස්වාදුපුෂ්පිකා", "meaning": "වරාගස", "category": "plant" },
    { "word": "ස්වාදුපුෂ්පී", "meaning": "මයිලගස", "category": "plant" },
    { "word": "ස්වාදුපොදකී", "meaning": "වැල්නිවිති (නිවිති වැල්)", "category": "plant" },
    { "word": "ස්වාදුඵල", "meaning": "වාලුගුන්, කැකිරි, කොබෝලීල, මුද්‍රික", "category": "plant" },
    { "word": "ස්වාදුඵලා", "meaning": "රසකිඳ, නෙල්ලි, මිදි වැල්", "category": "plant" },
    { "word": "ස්වාදුබ්‍රහතී", "meaning": "වම්බටු", "category": "plant" },
    { "word": "ස්වාදුමර්ජක", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "ස්වාදුමුර්ජත්", "meaning": "ගල්පියල්ගස", "category": "plant" },
    { "word": "ස්වාදුමුඬුරා", "meaning": "කිරිකවෙලු", "category": "plant" },
    { "word": "ස්වාදුමාසා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "ස්වාදුමාංසි", "meaning": "කවෙලු", "category": "plant" },
    { "word": "ස්වාදුර", "meaning": "කැකිරි", "category": "plant" },
    { "word": "ස්වාදුරස", "meaning": "කවෙලු", "category": "plant" },
    { "word": "ස්වාදුරසා", "meaning": "සුරා, සාතාවාරිය, කවෙලු, මුද්දරප්පලම්, ඇඹරැල්ල, මුරුවා", "category": "plant" },
    { "word": "ස්වාදුරෝමසා", "meaning": "කැකිරි", "category": "plant" },
    { "word": "ස්වාදුලතා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "ස්වාදූ", "meaning": "කිරිකවෙලු", "category": "plant" },
    { "word": "ස්වානජීහ්වා", "meaning": "පතුක්, බලුදලුවං වැල්, (බහ්දිවි වැල්)", "category": "plant" },
    { "word": "ස්වානජ්හ්වාදල", "meaning": "පතුක් ගස්", "category": "plant" },
    { "word": "ස්වාමි", "meaning": "රසදිය", "category": "mineral" },
    { "word": "ස්වාස්‍යානිබොධනී", "meaning": "සුළුදඹකලත්", "category": "plant" },
    { "word": "ස්වෙත", "meaning": "මුවකිරිය, සුදු පාසානම්, රිදී, වරාගස, සුදුහඳුන්, සුළුදඹකලත්, සුදුඔලු", "category": "plant" },
    { "word": "ස්වෙතඅම්බොජ", "meaning": "හෙළ නෙළුම්", "category": "plant" },
    { "word": "ස්වෙතක", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "ස්වෙතකා", "meaning": "කපු, සුදු ඉඹුල්", "category": "plant" },
    { "word": "ස්වෙතකාම්බොජ", "meaning": "කටුපිල", "category": "plant" },
    { "word": "ස්වෙතකුසුම", "meaning": "වැල්තිබ්බොටු", "category": "plant" },
    { "word": "ස්වෙතඛදිර", "meaning": "හෙළ කිහිරි", "category": "plant" },
    { "word": "ස්වෙතගුඤ්ජා", "meaning": "එළ ඔලිඳ", "category": "plant" },
    { "word": "ස්වෙතචන්දන", "meaning": "සුදු හඳුන්", "category": "plant" },
    { "word": "ස්වෙතචාමර පුෂ්ප", "meaning": "වෑක්", "category": "plant" },

    // --- පිටුව 513 ---
    { "word": "ස්වෙත ජම්බු", "meaning": "එළ ජම්බු", "category": "plant" },
    { "word": "ස්වෙත ජීරක", "meaning": "සුදු දුරු", "category": "plant" },
    { "word": "ස්වෙතදූර්", "meaning": "ඉළුක්", "category": "plant" },
    { "word": "ස්වෙතද්‍රැම", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "ස්වෙතනාමා", "meaning": "සුළුදඹකලත්", "category": "plant" },
    { "word": "ස්වෙතනීය", "meaning": "ඉඟිනි", "category": "plant" },
    { "word": "ස්වෙතපත්‍ර / ස්වෙත පත්‍රා", "meaning": "මහ සාරණ", "category": "plant" },
    { "word": "ස්වෙතපාකි", "meaning": "කටුපිල", "category": "plant" },
    { "word": "ස්වෙතපාටලි", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "ස්වෙත පාෂාණ", "meaning": "එලිමරිඤ්ජු, සුදු පාසානම්", "category": "mineral" },
    { "word": "ස්වෙත පිණ්ඩිතක", "meaning": "සුදු කටුකරඬු, මදන අල", "category": "plant" },
    { "word": "ස්වෙතපුබ්බ", "meaning": "හෙළ පිල ගස", "category": "plant" },
    { "word": "ස්වෙතපුෂ්ප", "meaning": "හෙළනික, මසේනිය, අලරිය, ලුණුවරණ, මැඩහඟු", "category": "plant" },
    { "word": "ස්වෙතපුෂ්පී", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "ස්වෙතමඬුරා", "meaning": "වැල් මුරුංගා", "category": "plant" },
    { "word": "ස්වෙතමරිච", "meaning": "වල් මුරුංගා", "category": "plant" },
    { "word": "ස්වෙතමුෂ්ටි", "meaning": "රේරු ගස", "category": "plant" },
    { "word": "ස්වෙතමූල", "meaning": "සුවසාරණ, මහසාරණ", "category": "plant" },
    { "word": "ස්වෙත මූලිකා", "meaning": "උඳු", "category": "plant" },
    { "word": "ස්වෙතයොති", "meaning": "සුදුහඳුන්", "category": "plant" },
    { "word": "ස්වෙතලොද්‍ර", "meaning": "හෙළ ලොත්", "category": "plant" },
    { "word": "ස්වෙතලොහ", "meaning": "ලෝකඩ", "category": "mineral" },
    { "word": "ස්වෙතවචා", "meaning": "(හෙළ වද) සුදුවදකහ", "category": "plant" },
    { "word": "ස්වෙතවාහ / ස්වෙතවාහන", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "ස්වෙතවිෂා", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "ස්වෙතශිග්‍රැක්", "meaning": "හෙළ නික", "category": "plant" },
    { "word": "ස්වෙතශ්‍රිග", "meaning": "සුදු ඊයම්", "category": "mineral" },
    { "word": "ස්වෙතස්බන්ධා", "meaning": "දත්ත", "category": "plant" },
    { "word": "ස්වෙතසර්ෂප", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "ස්වෙතසුරසා", "meaning": "කපු, සුදු තලා", "category": "plant" },
    { "word": "ස්වෙතා", "meaning": "මහ සාරණ, රේරු", "category": "plant" },
    { "word": "ස්වෙතාකී", "meaning": "හෙළ වරා", "category": "plant" },
    { "word": "ස්වෙතාර්ජක", "meaning": "අඳුතලා", "category": "plant" },
    { "word": "හංස කකුල්", "meaning": "වළාවැන්න, සාදිලිංගම්", "category": "plant" },
    { "word": "හංසපාදි / හංසපාදී", "meaning": "වළාවැන්න, (හංසපාදී)", "category": "plant" },
    { "word": "හංසපාද", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "හංසප්‍රච්ඡ", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "හංසපේත", "meaning": "අබින්", "category": "plant" },
    { "word": "හංසමාංසා", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "හංසමාලා", "meaning": "බක්මී", "category": "plant" },
    { "word": "හංසලොමශ", "meaning": "කසීස්", "category": "mineral" },
    { "word": "හංසවන්", "meaning": "දිලාවැන්න", "category": "plant" },
    { "word": "හංසාධක්‍ෂී", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "හකුරු", "meaning": "ශක්කරා (පැණි උකු කොට සාදන ද්‍රව්‍යයක්)", "category": "food" },
    { "word": "හගාරත්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "හඟුදු", "meaning": "කහ", "category": "plant" },
    { "word": "හඟුළු", "meaning": "අඟුණ වැල්, තැල් වැල්, සිරිල", "category": "plant" },
    { "word": "හජ්නද", "meaning": "වනුවැල්, (වෙනිවැල්)", "category": "plant" },
    { "word": "හටවිලාසිනී", "meaning": "කහ", "category": "plant" },
    { "word": "හටපර්ණී", "meaning": "පෙද, දියපරඬලා", "category": "plant" },
    { "word": "හටාලු", "meaning": "දිය පරඬලා", "category": "plant" },
    { "word": "හටි", "meaning": "දියපරඬලා", "category": "plant" },
    { "word": "හණ්ඩා", "meaning": "බටු ගස", "category": "plant" },
    { "word": "හත්පත්", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "හත්වන්", "meaning": "අත්තන ගස", "category": "plant" },
    { "word": "හත්වැන්න", "meaning": "පුස්වැන්න, කිඹුල්වැන්න, අස්වැන්න, මීලදැන්න, මකුණුවැන්න, වළාවැන්න, මුඟුණුවැන්න", "category": "plant" },
    { "word": "හදවත්", "meaning": "හෘදය මාංශය", "category": "anatomy" }

];