// data_162_171.js - පිටු 162 සිට 171 දක්වා සියලුම වචන
const data_extra_162_171 = [
  // --- පිටුව 162 ---
  {
    "word": "ගරුඬශාලි",
    "meaning": "පතොක් වගියට අයත් පැළෑටියකි. මෙය ගරුඬ (පත්තෑ) විෂ ඇතුළු සර්ප විෂට ප්‍රත්‍යක්ෂ ඖෂධයකි. ගරුඬෙකු (පත්තෑයෙකු) ගේ රූප සටහනට මඳක් සමාන පතුරු වැනි තුනී කොළ ඇති අඩි තුනක් පමණ උසට වැවෙන තවත් පැළෑටි වගියකටත් ගරුඬරාජ යයි කියති. එය ද සර්ප විෂ නාශක ඖෂධයකි.",
    "category": "plant"
  },
  { "word": "ගරුඬශාලි", "meaning": "ගුරාළු හාල්", "category": "treatment" },
  { "word": "ගරුඬා", "meaning": "ද්‍රක්ෂා, මුද්දරප්පලම්", "category": "plant" },
  { "word": "ගරුඬාහත", "meaning": "සෝමලතා භේදයක්", "category": "plant" },
  { "word": "ගරුඬී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ගරුණික්තා", "meaning": "කඩුකරෝෂණ", "category": "plant" },
  { "word": "ගරුසාර", "meaning": "කිහිරි", "category": "plant" },
  { "word": "ගල්නහර", "meaning": "එනම් බෙහෙත් වගිය", "category": "treatment" },
  { "word": "ගල්සෙවෙල්", "meaning": "එනම් වගිය", "category": "plant" },
  { "word": "ගලයා", "meaning": "මහවාළුක්", "category": "plant" },
  { "word": "ගල", "meaning": "කිහිරි", "category": "plant" },
  { "word": "ගලං", "meaning": "ඉඟුරු අල", "category": "plant" },
  { "word": "ගලගණ්ඩ", "meaning": "ගල රෝගයක්", "category": "symptom" },
  { "word": "ගලග්‍රහ", "meaning": "උගුරෙහි සෑදෙන රෝගයක්", "category": "symptom" },
  { "word": "ගලෂිණි", "meaning": "පද්මකාෂ්ඨ", "category": "treatment" },
  { "word": "ගලා", "meaning": "මුඩමහණ, නිදිකුම්බා, වලාවැන්න, කිහිරි", "category": "plant" },
  { "word": "ගලෝතා", "meaning": "හෙල පෝටා වැල්", "category": "plant" },
  { "word": "ගලාම", "meaning": "සබර (ලොත්)", "category": "plant" },
  {
    "word": "ගලිස්",
    "scientific": "Gardenia Latifolia",
    "meaning": "සපු කොළ වලට සමාන කොළ ඇති, වැරණියා ගසේ කොළ බෙදෙන්නාක් මෙන් දඬුවලින් කොළ දෙපැත්තට හෝ තුන් පැත්තකට බෙදී යන, ඝන වනාන්තරවල වැවෙන ගසකි. අඟල් 6 x 3 ක් පමණ දිග-පළල ඇති මේ කොළ තද ගොරෝසු ගතියකින් යුක්ත ය. කරටිවල සෑදෙන දළු එක් රැස් වී ඇත. මේ ගසේ දළු සහිත කරටිය පොඩි කළ විට ලාකඩ වැනි දෙයක් සෑදේ. කොල්ලුලෑකඩ (කොල්ලලාකඩ) යයි අපර නාමයක් මේ ගසට ව්‍යවහාර කරන්නේ ඒ නිසා ය. මේ කරටි පොඩි කර ගිතෙලෙහි බහා තැබූ පසු සෑදෙන ලාකඩ වර්ගය වඩ කෑම සඳහා තුවාල වලට ලන ප්ලාස්ටර් සෑදීමට ගනිති. ඉතා තද ගතියකින් යුත් මේ ගසේ දඬු මෝල්ගස්, උදළු මිටි, පොරෝ මිටි ආදිය සකස් කර ගැනීමට ප්‍රයෝජනවත් ය.",
    "category": "plant"
  },
  { "word": "ගලී", "meaning": "නියඟලා", "category": "plant" },
  { "word": "ගලුවී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ගලො", "meaning": "වැල්ප්", "category": "plant" },
  { "word": "ගව්‍යා", "meaning": "ගොරද (ගෝරෝචන)", "category": "treatment" },
  { "word": "ගවක්ෂීර", "meaning": "කිරි (මීකිරි)", "category": "treatment" },

  // --- පිටුව 163 ---
  { "word": "ගවර්‍ජ්ජ", "meaning": "මහගොත්කැකිරි", "category": "plant" },
  { "word": "ගවදත්", "meaning": "හිරියල්", "category": "treatment" },
  { "word": "ගවපුස්සල්", "meaning": "ගොන්කැකිරිවැල්", "category": "plant" },
  { "word": "ගවයෝද්භව", "meaning": "හුලන්කිරිය", "category": "plant" },
  { "word": "ගවර", "meaning": "වලඟසාල්, හිරියල්", "category": "plant" },
  { "word": "ගවරිපු තෛල", "meaning": "ගිනිතෙල්, කොසඹ තෙල්", "category": "treatment" },
  { "word": "ගවල", "meaning": "මිණරක් අඟ", "category": "treatment" },
  { "word": "ගවාක්‍ෂි", "meaning": "විෂ්ණුක්‍රාන්ති, කටරොලු, කැකිරි, කෝවක්කා, ගැටනිවුල්", "category": "plant" },
  { "word": "ගවාදක", "meaning": "කෝවක්කා, කැකිරි, කටරොලු", "category": "plant" },
  { "word": "ගවාදනී", "meaning": "නිල් කටරොලු, ගොන් කැකිරි, ගල්මොර", "category": "plant" },
  { "word": "ගවාමෘත", "meaning": "එලකිරි", "category": "treatment" },
  { "word": "ගවි", "meaning": "ගිනිතෙල්, ගෝරෝචන", "category": "treatment" },
  { "word": "ගවින", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "ගවෙඩුකා", "meaning": "ගස්කැලිය, සිවංගුරු, මනබවිල", "category": "plant" },
  { "word": "ගවෙරැක", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගවෙශකා", "meaning": "සිරිවැඩිබැවිල", "category": "plant" },
  { "word": "ගව්‍යද්‍රැ", "meaning": "එනම් ගස", "category": "plant" },
  { "word": "ගස්කාලිය", "meaning": "ගස්කාල, (රත් කාල (පත්කාල) කාටකාල යයි කාල (කාලිය) වගී දෙකකි.) නාගබලා නම් ගස", "category": "plant" },
  { "word": "ගස්පින්න", "meaning": "තිත්ත පින්න, භාණ්ඩිර් (දත් කැක්කුමට ප්‍රත්‍යක්ෂ බෙහෙතකි)", "category": "plant" },
  {
    "word": "ගස් පෙනෙල",
    "scientific": "Sapindus Trifoliatus",
    "meaning": "වැල් පෙනෙල, ගස් පෙනෙල යයි වගී දෙකකි. වැල් පෙනෙල කොළ කරවිල කොළ වලට මඳක් සමාන ය. එක කොපුවක බුත් සරණ ඇට පමණ ඇති කළු පාටින් යුත් ඇට 2 ක් හෝ 3 ක් බැගින් සෑදේ. මේවායේ දළු රතු ලූනුත් එක පමණ ගෙන එලගිතෙලින් මලවා අනුභව කිරීමෙන් සෞම්‍ය ධාතු වර්ධනය කෙරේ. සම්පූර්ණ වැල ම වාත නාශක ඖෂධයකි. 'අත්ථුවාර්ඩ්' රෝගය සඳහා අවශ්‍ය අරිෂ්ට, කෂාය, මැල්ලුම් ආදිය පිණිස මෙය ප්‍රත්‍යක්ෂ ඖෂධයකි. ගස් පෙනෙල කොබ්බෑ කොළ වලට මඳක් සමාන නැදුන් ගස් සේ උසට වැඩෙන ගස් වඟියකි. මේ ගසේ ගිරිනීල්ල ගෙඩි වැනි ගෙඩි පොකුරු හටගනී. මේවා රෙදි පිරිසිදු කිරීමට හා රිදී-රත්රන් බඩු ඔප දැමීමටත් ගනිති. මේ ගසේ මුල්වල සාරය ගර්භනී ස්ත්‍රීන්ට අහිතකර ය.",
    "category": "plant"
  },

  // --- පිටුව 164 ---
  { "word": "ගස්බිල", "meaning": "බෙලි ගස", "category": "plant" },
  { "word": "ගස්සමන්", "meaning": "පිච්ච ගස", "category": "plant" },
  { "word": "ගස්සභානාචාරිය", "meaning": "ශාතාවාරිය වැනි කොළ ඇති අඩි දෙකක් පමණ උසට වැවෙන වගියකි. මේ වගියේ එක් ගසක සෑදෙන්නේ අඟල් පහකට වඩා දික් නොවූ අල හතක් පමණකි.", "category": "plant" },
  { "word": "ගභීරි", "meaning": "මඟුල්කරඳ", "category": "plant" },
  { "word": "ගහණී", "meaning": "ග්‍රහණී රෝගය", "category": "symptom" },
  { "word": "ගහන", "meaning": "නාසිකාව, නාසය", "category": "treatment" },
  { "word": "ගහරා", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "ගහල", "meaning": "ගස් අල (කිරි අල වැනි අල මොරැල්ලන් සෑදෙන අලකොළ ගස් වලට සමාන අල ගස් වගියකි)", "category": "plant" },
  { "word": "ගප්‍රෙවී", "meaning": "කිඳි", "category": "plant" },
  { "word": "ගාංග", "meaning": "වම්මුතු, කෙකටිය, අත්තන", "category": "plant" },
  { "word": "ගාබෙය", "meaning": "කලාඳුරු, අත්තන, ගොකටු, කළුදුරු", "category": "plant" },
  { "word": "ගාබෙරී", "meaning": "ඇඹුල්ඇඹිලිය", "category": "plant" },
  { "word": "ගාබෙරිකා", "meaning": "කාමරංගා, සිරිවැඩි බැවිල", "category": "plant" },
  { "word": "ගාබෙරැක", "meaning": "සිරිවැඩිබැවිල", "category": "plant" },
  { "word": "ගාබෙරැකි", "meaning": "ගස්කැලිය, මඟබැවිල", "category": "plant" },
  { "word": "ගාබෙරැහා", "meaning": "සිරිවැඩිබැවිල", "category": "plant" },
  { "word": "ගාප්ප්‍ර", "meaning": "මිරිකුළු, (මුරංගා,) රතු ඉඟුරු, කෑරට්", "category": "plant" },
  { "word": "ගාස", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "ගාසමණ්ඩල", "meaning": "කුකුරමාන", "category": "plant" },
  { "word": "ගාසමොහිනී", "meaning": "දේවදාලියවැල්, දෙවදාර", "category": "plant" },
  { "word": "ගාණ්ඩිර්", "meaning": "දක්", "category": "treatment" },
  { "word": "ගාණ්ඩිර්කා", "meaning": "තිප්පිලිමුල්, වැල්මදට", "category": "plant" },
  { "word": "ගාණ්ඩිව", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "ගාණ්ඩිවී", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "ගාණ්ඩිවින්", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "ගාත්‍රබල", "meaning": "වඳුරු මෑ, හිඟුරුපියලි", "category": "plant" },
  { "word": "ගාඩ්‍යභා", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "ගාකම්", "meaning": "නවතාලිලි එඬරු", "category": "plant" },
  { "word": "ගාකම්හස්ත", "meaning": "එඬරු", "category": "plant" },
  { "word": "ගාකවන්තපුෂ්ප", "meaning": "බක්මී", "category": "plant" },
  { "word": "ගාකාරිකා", "meaning": "කටුවැල්බටු", "category": "plant" },
  { "word": "ගාතිනී", "meaning": "වදකහ", "category": "plant" },
  { "word": "ගාන්ධාරි", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "ගාමක", "meaning": "කරවිල", "category": "plant" },
  { "word": "ගාමිනා", "meaning": "තෙල්බේරු, බේරු", "category": "plant" },
  { "word": "ගායත්‍රා", "meaning": "සෝමලතා භේදයක්", "category": "plant" },
  { "word": "ගායත්‍රී", "meaning": "කිහිරි, කළු කිහිරි", "category": "plant" },
  { "word": "ගාර්ජර", "meaning": "කෑරට් ගස", "category": "plant" },
  { "word": "ගාරවල්ලිනී", "meaning": "කැල්වැල්", "category": "plant" },
  { "word": "ගාරැඩි", "meaning": "මදුවැල්", "category": "plant" },
  { "word": "ගාරැත්මනපත්‍රිකා", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "ගාල", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "ගාලව", "meaning": "ලොත්, තිඹිරි", "category": "plant" },
  { "word": "ගාලාම", "meaning": "ලොත්", "category": "plant" },
  { "word": "ගාවේසියා", "meaning": "රත්රන්", "category": "treatment" },
  { "word": "ගාෂබහරි", "meaning": "ඇඹුලඇඹිලිය, කාම රත්තා", "category": "plant" },

  // --- පිටුව 165 ---
  { "word": "ගෑගුල", "meaning": "ගව මූත්‍ර", "category": "treatment" },
  { "word": "ගැටකසා", "meaning": "ගාටකෂ", "category": "treatment" },
  { "word": "ගැටනිඹිරි", "meaning": "නිඹිරි වගියක්", "category": "plant" },
  { "word": "ගැටතුඹ", "meaning": "වෙල්වල හටගන්නා සුදු පාට මල් ඇති තිත්ත රසයෙන් යුක්ත කාම රෝගයට ප්‍රත්‍යක්ෂ ඖෂධයක්", "category": "plant" },
  { "word": "ගැටනෝඩු", "meaning": "බුලත් වගියක්", "category": "plant" },
  { "word": "ගැටනෙවුල්", "meaning": "ගාබොට (සිද්ධියම් සහිත විස්තරයක් ඉදිරියෙහි ඇත)", "category": "plant" },
  { "word": "ගැටවුල්නහර", "meaning": "ගැබ්බිල් පස්පාර", "category": "treatment" },
  { "word": "ගෑබිබ", "meaning": "ගාඩුව් ගස්, වේගයෙන් ගිනි ගන්නා තද රත් වීමකින් යුත් මේවායේ අඟුරු පැරණි ලාංකිකයෝ වෙඩි බෙහෙත් සෑදීමේ ප්‍රධාන ද්‍රව්‍යයක් ලෙස පාවිච්චි කළහ.", "category": "plant" },
  {
    "word": "ගැබනෙමුල් (ගැබනිඹුල්)",
    "scientific": "Streblus Asper",
    "meaning": "නිඹුල් වගියට අයත් වූ මේ ගස අඩි 50 ක් පමණ උසට වැවෙයි. වෙනත් බොහෝ ගස් වල මෙන් මේ ගසේ කඳෙහි පිටත දිරා ගිය පොත්තක් නැත. ඒ වෙනුවට ඇත්තේ නිල් පැහැයෙන් යුත් ඔබ වැටුන පොත්තකි. මේ කඳේ තැනින් තැන ලොකු දෙහි ගෙඩි පමණ ඉදිරියට නෙරා ගිය ගැට සෑදී තිබෙන නිසා මේ ගසට ගැබ නිඹුල් යන නාමය ව්‍යවහාර වන බැව් සිතිය හැක. මේ ගසේ කොළ හින්තඹල කොළ වලට සමාන ය. ප්‍රමාණයෙන් ඊට මඳක් විශාල ය. කර කොළ මෙන් මස සහිත ය. ඇත් ආදී සිවුපා සතුන්ගේ සහ මිනිසුන්ගේ කැඩුම්-බිඳුම්-ගෙඩි-වණ සඳහා පිළියෙළ කරන ඖෂධ යෝග වලට මේ ගසේ පොතු බෙහෙවින් ප්‍රයෝජනවත් ය.",
    "category": "plant"
  },
  { "word": "ගාඩබු", "meaning": "ගාඩවැල්ලු, (ගැටවැල්ලු, = ගොඩවැල්ලු)", "category": "plant" },
  { "word": "ගාඩවිල්", "meaning": "ගාඩවැල්ලු", "category": "plant" },
  { "word": "ගාඩියු", "meaning": "ගාඩුව් ගස, ගාඩවිලා", "category": "plant" },
  { "word": "ගාවුබු", "meaning": "කොට්ටම්බා, ගාඩුව් ගස්", "category": "plant" },
  { "word": "ගාබසරැ", "meaning": "කකුල රූපය", "category": "treatment" },
  { "word": "ගාහැමි සමන්", "meaning": "වල් ඉද්ද", "category": "plant" },

  // --- පිටුව 166 ---
  { "word": "ගීක", "meaning": "ලියනහල අල", "category": "plant" },
  { "word": "ගීස්කභල", "meaning": "කටුවෙලඟ, කඩුවැල්බටු", "category": "plant" },
  { "word": "ගින්තේරි", "meaning": "ගිනිහිරිය", "category": "plant" },
  { "word": "ගිනි", "meaning": "රත්නිවුල්, සිවිය", "category": "plant" },
  { "word": "ගිනිදිව", "meaning": "ලියනඟලා, මසිල", "category": "plant" },
  { "word": "ගිනිපස", "meaning": "මුරුවා, ඇඹුල්ඇඹිලිය, රත්නිවුල්, කිබාරත්, හිරස්ස", "category": "plant" },
  { "word": "ගිනිමුම", "meaning": "තියනඟලා", "category": "plant" },
  { "word": "ගිනිරැස්", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ගිනිසිල", "meaning": "ලියනඟලා, මසිල", "category": "plant" },
  { "word": "ගිනිසුව", "meaning": "නියඟලා", "category": "plant" },
  { "word": "ගිම්", "meaning": "පොල්පලා වැනි ගස් වගියක්", "category": "plant" },
  { "word": "ගිම්පලා", "meaning": "කිඳි", "category": "plant" },
  { "word": "ගිම්හන්", "meaning": "පොසොන්, ඇසලූ දෙමස", "category": "treatment" },
  { "word": "ගීංයකසුම්", "meaning": "කරාබුනැටි", "category": "plant" },
  { "word": "ගිරහ", "meaning": "බුලත් කරටිය", "category": "plant" },
  { "word": "ගිරා කෙම්වැල්", "meaning": "කෝවක්කා වැල් (බිබුලවැල්)", "category": "plant" },
  { "word": "ගිරාපලා", "meaning": "දියසිරාව ඇති තන්හි පෑලවෙන සිසිල් ගුණය ඇති පලා වගියක්", "category": "plant" },
  { "word": "ගිරිකණිකා", "meaning": "කටරොලු", "category": "plant" },
  { "word": "ගිරිකදම්බ", "meaning": "බක්මී ගස", "category": "plant" },
  { "word": "ගිරිකදලි", "meaning": "ඇටකෙසෙල්, (මතකෙසෙල්)", "category": "plant" },
  { "word": "ගිරිකණී", "meaning": "කටරොලු", "category": "plant" },
  { "word": "ගිරිකර්ණී", "meaning": "කටරොලු දෙක, ගිරිනීල්ල", "category": "plant" },
  { "word": "ගිරිකර්ණිකා", "meaning": "කටරොලු, ඇසලූ", "category": "plant" },
  { "word": "ගිරිකා", "meaning": "කොහොඹ, තොවිල, රැක ගුණ, ගිරිනීල්ල", "category": "plant" },
  { "word": "ගිරිකණ්භලා", "meaning": "කඩුවෙලඟ, උග්‍රරස්ස", "category": "plant" },
  { "word": "ගිරිජ", "meaning": "ගල්සෙවෙල්, මිණීරන්, ලප්නාරත්, ගල්මද, ගල්තහර, සිවංගුරු, ලෝකඩ", "category": "treatment" },
  { "word": "ගිරිපතු", "meaning": "ගල්සෙවෙල්", "category": "plant" },
  { "word": "ගිරිපධාතු", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගිරිජන්මන්", "meaning": "ගල්සෙවෙල්", "category": "plant" },
  { "word": "ගිරිජශෛල", "meaning": "ගල්සෙවෙල්, ගල්මද", "category": "treatment" },
  { "word": "ගිරිජා", "meaning": "ගන්ධක, ගල්පියල්, ගල්මද, මොර, මිණීරන්, ලප්නාරත්", "category": "treatment" },
  { "word": "ගිරිජාමල", "meaning": "මිණීරන්", "category": "treatment" },
  { "word": "ගිරිජාවිට්", "meaning": "ගෙන්දගම්, මිණීරන්", "category": "treatment" },
  { "word": "ගිරිජාහ්වය", "meaning": "ගල්සෙවෙල්", "category": "plant" },
  { "word": "ගිරිජින්වා", "meaning": "අබනගිරිය", "category": "plant" },
  { "word": "ගිරිනීල්ලවැල්", "meaning": "මාබණ්ඩා වැල් (වැඬදුරු)", "category": "plant" },
  { "word": "ගිරිද්‍ර", "meaning": "බුලත් දළු", "category": "plant" },
  { "word": "ගිරිධාතු", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගිරිනන්ද", "meaning": "තිප්පිලි", "category": "plant" },
  { "word": "ගිරිනීඹ", "meaning": "තොවිල, ලුණූමිදෙල්ල", "category": "plant" },
  { "word": "ගිරිනිල්", "meaning": "කටරොලුවැල්, ගින්තේරිය", "category": "plant" },
  { "word": "ගිරිනිල්බාණු", "meaning": "මහරිගස", "category": "plant" },
  { "word": "ගිරිනීල්ල", "meaning": "ගින්තේරිය (ගින්තේර=ගිනිහිරිය) දියසිරාව සහිත දෙනිවල වැවෙන නිල්පාට මල් පොකුරු ඇති කුඩා පඳුරු වගියක්", "category": "plant" },
  { "word": "ගිරිනීල්ල", "meaning": "වැඬදුරු", "category": "plant" },
  { "word": "ගිරිපතු", "meaning": "ලුණූමිදෙල්ල", "category": "plant" },
  { "word": "ගිරිපාදිකා", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "ගිරිපීලු", "meaning": "වතමොර, උග්‍රරස්ස", "category": "plant" },
  { "word": "ගිරිපුෂ්ප", "meaning": "ගල්මද, ගල්සෙවෙල්", "category": "plant" },
  { "word": "ගිරිපුෂ්පක", "meaning": "ගල්මද, ගල්සෙවෙල්", "category": "plant" },
  { "word": "ගිරිනිද", "meaning": "පොල්පලා", "category": "plant" },
  { "word": "ගිරිහේද", "meaning": "පොල්පලා, (ප්‍රහණ්ඩෙය)", "category": "plant" },
  { "word": "ගිරිමනෝහර", "meaning": "ඇසලූ ගස", "category": "plant" },
  { "word": "ගිරිමල්ලිකා", "meaning": "කෙළිඳසාල්, ඇසල", "category": "plant" },
  { "word": "ගිරිමල", "meaning": "මිණීරන්", "category": "treatment" },
  { "word": "ගිරිමාංසධාතු", "meaning": "සිවංගුරු", "category": "treatment" },

  // --- පිටුව 167 ---
  { "word": "ගිරිමාලක", "meaning": "ඇසලූ, (එරහඳි)", "category": "plant" },
  { "word": "ගිරිමේද", "meaning": "ගුරැන්ද", "category": "plant" },
  { "word": "ගිරිමන්", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගිරිමදව", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගිරිමද්", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගිරිමීමා", "meaning": "ඇටකෙසෙල්", "category": "plant" },
  { "word": "ගිරිවාෂින්", "meaning": "හබරල ගස", "category": "plant" },
  { "word": "ගිරිශාබ්ධි", "meaning": "කලුනික", "category": "plant" },
  { "word": "ගිරිශෙබර", "meaning": "මහ මුහුණමල් ගස", "category": "plant" },
  { "word": "ගිරිසෙවද", "meaning": "ගල්සෙවෙල්", "category": "plant" },
  { "word": "ගිරිසමිභව", "meaning": "ගල්මොර, ගල්මිගස", "category": "plant" },
  { "word": "ගිරිසාර", "meaning": "යකඩ", "category": "treatment" },
  { "word": "ගිරිසාලිනී", "meaning": "ගිරිනීල්ල වැල් (මාබණ්ඩා) එලකටරොලු, නිල්කට රොලු", "category": "plant" },
  { "word": "ගිරිසිංහ", "meaning": "නික", "category": "plant" },
  { "word": "ගිරිසින්ධුක", "meaning": "කලුමල් ඇති නික ගස", "category": "plant" },
  { "word": "ගිරිහ්වා", "meaning": "කටරොලු", "category": "plant" },
  { "word": "ගිල්මැලී", "meaning": "බෙලිගස", "category": "plant" },
  { "word": "ගිල", "meaning": "දෙළුම්, පැණිදෙළුම්", "category": "plant" },
  { "word": "ගිවුලුගස්", "meaning": "දිවුල් (දිවුල්, ජිවුලුගස්)", "category": "plant" },
  { "word": "ගිවාණකුසුම", "meaning": "කරාබු නැටි", "category": "plant" },
  { "word": "ගිර්ලතා", "meaning": "මඟදුරු වැල", "category": "plant" },
  { "word": "ගුංජා", "meaning": "ඔලිඳ", "category": "plant" },
  { "word": "ගුගුලක", "meaning": "ගොන්සල වැල්", "category": "plant" },
  { "word": "ගුගුලු", "meaning": "රත්මුරංගා, අබ", "category": "plant" },
  {
    "word": "ගුගුල්",
    "meaning": "පර්සියාව හා අනිකුත් අසල්වැසි රටවල වැවෙන ගස් වඟියකින් ලබාගන්නා ලාටුවකි ගුගුල්. ප්‍රධාන විෂබීජ නාශක ඖෂධයක් වූ මෙය වණ රෝග අතීසාර-පීනස් ආදී ආබාධයන්හි පසස්නා ලදී. පසු කාලයක බ්‍රිතාන්‍යයේ ප්‍රයෝජනය සඳහා Tincture Mukul නමැති මෙයින් බෙහෙත් වඟියක් සාදා ගෙන අපරදිග වෛද්‍යවරයෝ ද ප්‍රයෝජන ගනිති.",
    "category": "treatment"
  },
  { "word": "ගුෂ්කවන්ධ", "meaning": "ග්‍රන්ථිපර්ණී වාක්‍යය, වඳුරු මෑ වැල", "category": "plant" },
  { "word": "ගුෂ්කකරඤ්ජ", "meaning": "කරඳ වගියක්", "category": "plant" },
  { "word": "ගුජ්ජපර්ණිකා", "meaning": "කෙසෙල්", "category": "plant" },
  { "word": "ගුජ්ජපත්‍ර", "meaning": "තල්", "category": "plant" },
  { "word": "ගුජ්ජඵලා", "meaning": "මුද්රිකාඵල, කෙසෙල්ගස", "category": "plant" },
  { "word": "ගුජ්ජපුෂ්ප", "meaning": "කළුකම්මේරිය, රක් අත්තන, ඉඟිනි, කිරිපලු, මලිත, කරඳ, කෙසෙල්, සිහින් මිදි, මුද්දරප්පලම්", "category": "plant" },
  { "word": "ගුජ්ජපුෂ්පි", "meaning": "මලිත", "category": "plant" },
  { "word": "ගුජ්ජවල්ල", "meaning": "කිරිපලු, කරඳ, ඉඟිනි, දියහොමබුවහ", "category": "plant" },
  { "word": "ගුජ්ජ", "meaning": "විෂ්ණුක්‍රාන්ති, කරඳ, දෙළුම්, වැල්ක්, දෙළුම්, කෙසෙල්, රඹුක්", "category": "plant" },
  { "word": "ගුජ්ජකා", "meaning": "ඔලිඳ", "category": "plant" },
  { "word": "ගුඤ්ජ", "meaning": "ඔලිඳ", "category": "plant" },
  { "word": "ගුඤ්ජකා", "meaning": "බලිද", "category": "plant" },
  { "word": "ගුඤ්ජා", "meaning": "රතුලූනු", "category": "plant" },
  { "word": "ගුජ්ජා", "meaning": "සිනි, උක්සකුරු", "category": "treatment" },
  { "word": "ගුටිකා", "meaning": "සූකිරි", "category": "treatment" },
  { "word": "ගුටිකා", "meaning": "ගුලිය, වටකය, මෝදකය, පිඬ, හුනිද", "category": "treatment" },
  { "word": "ගුටිබටු", "meaning": "තලා, (රහස් වට්ටෝරුවක එන ඔසුවක්)", "category": "plant" },
  { "word": "ගුජ්ජිකා", "meaning": "ගුරැළු වැල්", "category": "plant" },
  { "word": "ගුද්ධ", "meaning": "තල්ගස, රත්කණේරු, මඟ දවක්, උක්සකුරු", "category": "treatment" },
  { "word": "ගුඩිකාණ්ඩ", "meaning": "උක්ගස", "category": "plant" },
  { "word": "ගුඩ්ඩකන්‍ධ", "meaning": "ගල්කහඬු", "category": "treatment" },
  { "word": "ගුඩ්ඩකාලිකා", "meaning": "පෙරුම්කායම්", "category": "treatment" },

  // --- පිටුව 168 ---
  { "word": "ගුඩ්ඩක්", "meaning": "කුරඳු පොතු", "category": "plant" },
  { "word": "ගුඩ්බව", "meaning": "කුරඳු පොතු, වසාවාසි", "category": "plant" },
  { "word": "ගුඩ්තෘණ", "meaning": "උක්ගස", "category": "plant" },
  { "word": "ගුඩ්ද්‍රැ", "meaning": "උක්ගස", "category": "plant" },
  { "word": "ගුඩ්පාතුක", "meaning": "උක්ගස", "category": "plant" },
  { "word": "ගුඩ්පුෂ්ප", "meaning": "මීගස, මූණමල් ගස", "category": "plant" },
  { "word": "ගුඩ්පුෂ්පඵල", "meaning": "පුවක්ගෙඩි", "category": "plant" },
  { "word": "ගුඩ්ඵල", "meaning": "මොර, ලෝලු, තල්, නිවුල්, කළුකැම්මේරිය", "category": "plant" },
  { "word": "ගුඩ්බිජ", "meaning": "වටමුං", "category": "plant" },
  { "word": "ගුඩ්මක්ෂරී", "meaning": "ධිබිනි නම් වාක්‍යය", "category": "treatment" },
  { "word": "ගුඩ්මූල", "meaning": "උක්ගස, සුලුකුර", "category": "plant" },
  { "word": "ගුඩය", "meaning": "කිතුල් හකුරු", "category": "treatment" },
  { "word": "ගුඩයෝගපලා", "meaning": "පුහුල් වැල්, ගුණ කුෂ්මාණ්ඩ (පැණි කොමඩු)", "category": "plant" },
  { "word": "ගුඩයෝපඵලා", "meaning": "පුහුල්, (කොමඩු, පත්තක්කා, පත්කොමඩු)", "category": "plant" },
  { "word": "ගුඩරොහිනී", "meaning": "කටුවෙලඟ", "category": "plant" },
  { "word": "ගුඩ්වජ", "meaning": "මඟුක්", "category": "plant" },
  { "word": "ගුඩවල්ලිකා", "meaning": "පුවඟු, රැකුණ", "category": "plant" },
  { "word": "ගුඩ්වීජ", "meaning": "ත්‍රස්තවාලු", "category": "plant" },
  { "word": "ගුඩ්වාක්‍ෂ", "meaning": "ලෝලු, ලාවුලු = (ලාවුටු)", "category": "plant" },
  { "word": "ගුඩශකීරා", "meaning": "උක්සකුරු", "category": "treatment" },
  { "word": "ගුඩ්ශිග්‍රැ", "meaning": "රත්මුරංගා", "category": "plant" },
  { "word": "ගුඩ්සං", "meaning": "කිතුල් හකුරු", "category": "treatment" },
  { "word": "ගුඩ්සාර", "meaning": "සීනි", "category": "treatment" },
  { "word": "ගුඩා", "meaning": "දක්, මුද්රප්පලම්, මිදි, සීනි, රසකිඳ", "category": "treatment" },
  { "word": "ගුඩාක / ගුඩාකා", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "ගුඩාඛ්‍ය", "meaning": "දළුක්ගස", "category": "plant" },
  { "word": "ගුඩාගස්", "meaning": "ගල්මොර ගස", "category": "plant" },
  { "word": "ගුඩු", "meaning": "වියළිමද", "category": "treatment" },
  { "word": "ගුඩිවී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ගුඩ්ඪ්වාද්‍යගණය", "meaning": "රසකිඳ, කොසඹ, කොත්තමල්ලි, පද්මක, සුදුහඳුන් යන මේ ගණය, පිපාස, දූමිලී, අරුචි, වමණය හා සියලු හුන් නසන්නේය", "category": "treatment" },
  { "word": "ගුණ", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "ගුණකන්‍ද", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "ගුණකන්‍ධ", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "ගුණාධි", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "ගුණිධි", "meaning": "හණ", "category": "plant" },
  { "word": "ගුණ්ඩු", "meaning": "අස්දෙමට, ඊතණ", "category": "plant" },
  { "word": "ගුණ", "meaning": "රක්කාගුණ", "category": "treatment" },
  { "word": "ගුණසක", "meaning": "නිතිග", "category": "plant" },
  { "word": "ගුණවන්තරා", "meaning": "කපුගස", "category": "plant" },
  { "word": "ගුණස්ස", "meaning": "මාංශ රෝහිණී, රතැණ", "category": "plant" },
  { "word": "ගුණා", "meaning": "කුඩා සුදු බෝලිද්ද", "category": "plant" },
  { "word": "ගුණොත්පලා", "meaning": "උවනා ලී, කිඳි", "category": "plant" },
  { "word": "ගුප්", "meaning": "ග්‍රන්ථි පර්ණී වාක්‍යය", "category": "treatment" },
  { "word": "ගුප්තක", "meaning": "කල්ගස", "category": "plant" },
  { "word": "ගුප්සපතු", "meaning": "රක්ත චන්දන, ඉඟිනි, කෙසෙල්, කිරිපලු, කරඳ, මසිල, සිහින් මිදි, කලු කැම්මේරිය, මුද්දරප්පලම්", "category": "plant" },
  { "word": "ගුප්සපුෂ්ප", "meaning": "අක්ෂි රෝගය", "category": "symptom" },
  { "word": "ගුදකිල", "meaning": "උදාවර්ත රෝගය", "category": "symptom" },
  { "word": "ගුදග්‍රහ", "meaning": "කිඩාරම්", "category": "plant" },
  { "word": "ගුදජර්සන", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "ගුදන්තාරි", "meaning": "කිඩාරම්", "category": "plant" },
  { "word": "ගුදමියහර", "meaning": "රක්කාගුණ, පුවඟු", "category": "plant" },
  { "word": "ගුදස්ස", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "ගුන්ජල", "meaning": "හණ, වම්මුතු, ඇසලූ", "category": "plant" },
  { "word": "ගුන්ජ", "meaning": "හණ, බටගස, වම්මුතු, කාලියගස්", "category": "plant" },
  { "word": "ගුනු", "meaning": "එරතැණ, වම්මුතු", "category": "plant" },
  { "word": "ගුනුමුලා", "meaning": "පුවඟු, රක්කාගුණ, හණ, කලාඳුරු", "category": "plant" },
  { "word": "ගුන්ජා", "meaning": "මනෝසිල, දිවුල්, කරඳ, අත්තන", "category": "treatment" },
  { "word": "ගුප්තක", "meaning": "එන්සාල්", "category": "plant" },

  // --- පිටුව 169 ---
  { "word": "ගුප්තගන්ධි", "meaning": "රක්ත අත්තන", "category": "plant" },
  { "word": "ගුප්තවජ්ජ", "meaning": "රක්ත අත්තන", "category": "plant" },
  { "word": "ගුප්තපුෂ්ප / ගුප්තපුෂ්පි", "meaning": "කාකජංඝා, (කළුකැම්මේරිය)", "category": "plant" },
  { "word": "ගුප්තඵලා", "meaning": "පුවඟු, රැකාගුණ", "category": "plant" },
  { "word": "ගුප්තස්නේහ", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "ගුප්තා", "meaning": "ලෑහැබ", "category": "treatment" },
  { "word": "ගුමි", "meaning": "ගුල්මය, (ගොමුව=පඳුර)", "category": "symptom" },
  { "word": "ගුමු", "meaning": "පුවක්ගස", "category": "plant" },
  { "word": "ගුමී", "meaning": "බබරාජයන්ත්‍රි", "category": "treatment" },
  { "word": "ගුමීණී", "meaning": "වසතැල්ල, කිරිපලා, බබදරා සන්නි", "category": "plant" },
  { "word": "ගුරීවී", "meaning": "ගුරැල්ලගස, බුරැල්ල ගස", "category": "plant" },
  { "word": "ගුරිලගස්", "meaning": "වඳුරු මෑ", "category": "plant" },
  { "word": "ගුරා", "meaning": "කිරිඳි", "category": "plant" },
  { "word": "ගුරාකා", "meaning": "කිරිඳි", "category": "plant" },
  { "word": "ගුරාකාභුනි", "meaning": "අගිල්", "category": "plant" },
  { "word": "ගුරාගන්ධිකා", "meaning": "හෙලඅබ", "category": "plant" },
  { "word": "ගුරාසක", "meaning": "කුරඳුපොතු", "category": "plant" },
  { "word": "ගුරාෂක", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගුරාද", "meaning": "හෙල හිඟුරු", "category": "plant" },
  { "word": "ගුරාන්දරිකකරක්කාලි", "meaning": "මහපස්මුල්", "category": "treatment" },
  { "word": "ගුරාපංචමූලී", "meaning": "රියම්", "category": "treatment" },
  { "word": "ගුරාපත්‍ර", "meaning": "සියඹලා", "category": "plant" },
  { "word": "ගුරාපත්‍රා", "meaning": "පුවක්ගස", "category": "plant" },
  { "word": "ගුරාපුෂ්ප", "meaning": "කලාඳුරු", "category": "plant" },
  { "word": "ගුරාබාණ්ඩක", "meaning": "ලුණු වරණ", "category": "plant" },
  { "word": "ගුරාමාල", "meaning": "ලුණුවරණ", "category": "plant" },
  { "word": "ගුරාමාලී", "meaning": "බුරැල්ල ගස", "category": "plant" },
  { "word": "ගුරැල්", "meaning": "වට්ටක්කා", "category": "plant" },
  { "word": "ගුරැවිජ", "meaning": "ලෝලු, කිරිපලු", "category": "plant" },
  { "word": "ගුරැසකන්ධ", "meaning": "වලඟසාල්, ඇටිවේරිය", "category": "plant" },
  { "word": "ගුරැසාර", "meaning": "වලඟසාල්, ඇටිවේරිය, කිහිරි", "category": "plant" },
  {
    "word": "ගුරුප්‍රභ",
    "meaning": "රූප පහ (ගුරුප්‍රභ - සඳුප්‍රභ - ගුරුප්‍රභ - චන්ප්‍රභ - ගරුඩප්‍රභ) ට අයත් එක් වගියක් වූ මේ පැළෑටිය හැඩහුරු කමෙන් චන්ප්‍රභ පාලයට බෙහෙවින් සමාන ය. කඳ රත් පැහැයෙන් යුක්ත ය. කොළ දිග-පළලින් අඟල් 2 1/2 x 1 1/4 ක් පමණ ඇත. මඳක් නිල් වර්ණයෙන් යුත් මේ පැළෑටියේ කොළ වල ඇතුළත හා පිටත රත් පැහැති රේඛාවන්ගෙන් යුක්ත ය. සම්පූර්ණ පැළෑටිය ම අඟල් 7 කට වඩා උසට නොවෑඩෙයි. දේශීය වෙදකමේ ඇතැම් තෙල් වගී සම්පාදනයෙහි ලා ඖෂධයක් වශයෙන් මේ පැළෑටිය නියම කර තිබේ. රසකිඳ කොළ වලට මඳක් සමාන අළු සහිත නොපැහැදිලි සුදු ගතියකින් යුත් නාරිවේකුගේ හැඩහුරුකම ඇති මල් හටගන්නා ඇතැම් වැල් වගියකට ද ගුරුප්‍රභ යයි කියන නමුත් ඒවා මෑතක සිට ලංකාවේ බෝ වී යන කාර්මල් නමින් ලාංකිකයන් අතර ව්‍යවහාර වන වැල් වගිය මිස ගුරුප්‍රභ නොවේ.",
    "category": "plant"
  },

  // --- පිටුව 170 ---
  { "word": "ගුරුසී / ගුරුසිංසපා", "meaning": "ඇටිවේරිය", "category": "plant" },
  { "word": "ගුරුගන්", "meaning": "හෙල අබ", "category": "plant" },
  { "word": "ගුරෝ", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "ගුල්ප", "meaning": "පඳුරැ, ගොප්ඇටය", "category": "plant" },
  { "word": "ගුල්පස්ථාන", "meaning": "පුවක්ගස", "category": "plant" },
  { "word": "ගුල්ම", "meaning": "ගුල්ම රෝගය", "category": "symptom" },
  { "word": "ගුල්මක", "meaning": "රතු කණේරු ගස", "category": "plant" },
  { "word": "ගුල්මකේතු", "meaning": "ඇඹුල්වේ", "category": "plant" },
  { "word": "ගුල්මඝන", "meaning": "අලරිය, කණේරැ, පියල් ගස, හිඟුල්", "category": "plant" },
  { "word": "ගුල්මඝනී", "meaning": "මුවකිරිය, පියාගස", "category": "plant" },
  { "word": "ගුල්මමූල", "meaning": "අමු ඉඟුරැ, කිරිබදු, උක් ගස", "category": "plant" },
  { "word": "ගුල්මවල්ලී", "meaning": "බෝදි ඇට, සෝමලතා", "category": "plant" },
  { "word": "ගුල්මගුල", "meaning": "සූත්‍ර රෝග භේදයක්", "category": "symptom" },
  { "word": "ගුල්මහර", "meaning": "අලරිය, රත් කණේරැ", "category": "plant" },
  { "word": "ගුල්මි", "meaning": "එන්සාල්, නෙල්ලි", "category": "plant" },
  { "word": "ගුල්මිකා", "meaning": "රත් කණේරැ", "category": "plant" },
  { "word": "ගුල්මින්", "meaning": "කණ්ඩකපාලි වාක්‍යය", "category": "treatment" },
  { "word": "ගුල්මිනී", "meaning": "රැහැනිය (වටරැහැනිය) බුලත්", "category": "plant" },
  { "word": "ගුල්මිනීරේණු", "meaning": "වටරැහැන, (වල්ගා මිරිස්)", "category": "plant" },
  { "word": "ගුල්මී", "meaning": "එන්සාල්, නෙල්ලි, කණ්ඩක පාලි, බිලින් ගස", "category": "plant" },
  { "word": "ගුල", "meaning": "මාරා, මදටිය, උක්සකුරැ, අවටිකිකා", "category": "treatment" },
  { "word": "ගුලල්ල", "meaning": "පලු", "category": "plant" },
  { "word": "ගුලපුෂ්ප", "meaning": "පුවක්, මීගස, ලොත් රත්ලොත්", "category": "plant" },
  { "word": "ගුලමඤ්ජරී", "meaning": "ඉඟිනි", "category": "plant" },
  { "word": "ගුලමුල", "meaning": "උක්ගස", "category": "plant" },
  { "word": "ගුලසඤ්ජාපන", "meaning": "මදටිය, මහරි, මී ගස", "category": "plant" },
  { "word": "ගුලා", "meaning": "මුහලක්, කොටදිඹුලා, දඹ ගස", "category": "plant" },
  { "word": "ගුළු", "meaning": "උක්හකුරු", "category": "treatment" },
  { "word": "ගුවාකා", "meaning": "පුවක්", "category": "plant" },
  { "word": "ගුවිෂ්දන්තීකා", "meaning": "කෙසෙල්ගස", "category": "plant" },
  { "word": "ගුමිප්ඵල", "meaning": "මුද්දරප්පලම්, කැම්මේරි කරඳ, සිහින්මිදි, කෙසෙල්", "category": "plant" },
  { "word": "ගුප්පී", "meaning": "ඇත්දෙමට ගස", "category": "plant" },
  { "word": "ගුහ්‍යනිස්‍යන්ද", "meaning": "මුත්‍ර", "category": "treatment" },
  { "word": "ගුහ්‍යපත්‍ර / ගුහ්‍යපුෂ්ප", "meaning": "ඇසතු ගස", "category": "plant" },
  { "word": "ගුන්ජබිබ", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ගුන්ජබිජකා", "meaning": "ගුණ", "category": "treatment" },
  { "word": "ගුහා", "meaning": "අස්වැන්න", "category": "plant" },
  { "word": "ගුහාවාකා", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "ගුභා", "meaning": "පුස්වැන්න හෝ සල්වන්ති (ගාලිපර්ණී)", "category": "plant" },
  { "word": "ගුහාවදරි", "meaning": "ශාලිපර්ණී - (සවැන්න)", "category": "plant" },
  { "word": "ගුභාසය", "meaning": "හෘදය, ගුහාවල වසන", "category": "treatment" },
  { "word": "ගුසපත්‍ර", "meaning": "පුවඟු, කංසා, දවක්", "category": "plant" },
  { "word": "ගුසවල", "meaning": "මසන් (බැබර)", "category": "plant" },
  { "word": "ගුසපුෂ්ප", "meaning": "ඇසතු, මුණමල්", "category": "plant" },
  { "word": "ගුසවලා", "meaning": "ගාඩුව්බී (වක්නි) මසන්", "category": "plant" },
  { "word": "ගුසමල්ලිකා", "meaning": "රැකාගුණ", "category": "plant" },

  // --- පිටුව 171 ---
  { "word": "ගුසවල්ලිකා", "meaning": "පියාගස, රැකාගුණ, වමලු (මිනිස් අසූචි) මෙය විනය පිටකයේ (මහාවගග පාලි-හෙස ජජ්කන්ධක-202 පිට) තිබෙන වස කැවුන අයට බුදුරජාණන් වහන්සේ විසින් ම නියම කර වදාරණ ලද පහසු බෙහෙතකි. තමාගේ ම හෝ අන්‍යයෙකුගේ මිනිස් අසූචි ගෙන ඇල්දියෙන් දියකර එකෙණෙහි පානය කිරීමෙන් කවර වර්ගයක දාරැණු වසක් කැවුනත් සුවය ලබා ගත හැක.", "category": "treatment" },
  {
    "word": "ගුරැන්ද",
    "scientific": "Gmelina Arborea",
    "meaning": "ගුරැන්ද - ගිරිමෙද (ගුප්ත චන්දන). (Celtis timorensis)මේ ගසේ කොළ හැඩ හුරු කමින් කුරැදු කොළ වලටත් කඳ කැන්ඳ ගසටත් සමාන ය. කඳ ද සුදු පැහැයෙන් යුක්ත ය. ලියේ අරටුවෙන් ඉතා තද මිනිස් අසූචි ගඳක් නික්මෙයි. මේ අරටුව හොඳින් වියලුන විට පමණක් දුගඳ බොහෝ දුරට අඩු වෙයි. මේ අරටුව රෝග බීජ නාශක ඖෂධයක් ලෙස ලංකාවේ රහස් බෙහෙත් වට්ටෝරුවල සඳහන්ව ඇත. ප්‍රතිශ්යා උණ, උන්සසහි සාත, සර්ප, පාපොල, වසුරිය ආදී වසංගත රෝග පැතිර යන අවස්ථාවන්හි මේ අරටු කෑල්ලක් ඉඟ බැඳ තබා ගැනීමෙන් ඒ අසනීප නො වැලඳෙන බව ඒ වට්ටෝරුවල කියා තිබේ. මෙය අද්දුටු ප්‍රතිකාරයක් බැව් පලපුරුද්ද අනුව කිව හැක. මේ අරටුවෙන් නික්මෙන තද ගන්ධයෙහි රෝග බීජ නාශක ශක්තියක් තිබීම මෙයට හේතුවයි. මෙය විද්‍යානුකූල පරීක්ෂණයකට භාජනය කොට ශාස්ත්‍රානුකූලව විෂබීජ නාශක ඖෂධයක් සකස් කර ගත යුතු ද්‍රව්‍යයකි. එසේ කළහොත් ඇතැම් අපරදිග වෛද්‍යවරයත් අපේ වෙදකමේ පෙන්වන අඩුපාඩු කීපයෙන් එකක් ද මග හැරී යයි.",
    "category": "plant"
  },
  { "word": "ප්‍රේත දෝෂ", "meaning": "මේ ගසේ බොහෝ ශක්තිමත් වූ අරටුවෙන් ඉරාගන්නා රිප්ප - පරාල ආදී ගෘහොපකරණ ඇතැම් අය නොදැනීමෙන් හෝ නොසැලකීමෙන් වහලවල් සෑදීමට ගනිති. හොඳින් වියලුන විට දුගඳ අඩුවී යන, තෙත්වන විට තද අසූචි ගඳ නික්මෙන මේ ලී වර්ගය දමා සෑදූ...", "category": "treatment" }
];