// data_89_98.js
const data_extra_89_98 = [
  // --- පිටුව 89 (image_aa0126.png) ---
  { "word": "කරුණිකාළි", "meaning": "කිහිිරි", "category": "plant" },
  { "word": "කරුණිතූලසී", "meaning": "කලුතල", "category": "plant" },
  { "word": "කරුණිමල්ල", "meaning": "දුස්සින්", "category": "plant" },
  { "word": "කරුණා", "meaning": "වදකහ", "category": "plant" },
  { "word": "කරුණාම්", "meaning": "කලු වම්මොනාවි", "category": "plant" },
  { "word": "කරුණහ උප්පු", "meaning": "කලු ලුණු", "category": "treatment" },
  { "word": "කරුන්විරකම්", "meaning": "කලුදුරු", "category": "plant" },
  { "word": "කරුන්ජේරත්නෙයි", "meaning": "කලුවා අල, අරත්ත (රාජණා-රැත්ත)", "category": "plant" },
  { "word": "කරතොච්චි", "meaning": "කලුනික", "category": "plant" },
  { "word": "කරප්පුකකනකයි", "meaning": "කලු කසකසා", "category": "plant" },
  { "word": "කරම්ප්‍රපානී", "meaning": "උක් පැණි", "category": "treatment" },
  { "word": "කරඹුල්ලාපානී", "meaning": "උක් පැණි", "category": "treatment" },
  { "word": "කරම්නලෙයි", "meaning": "කලු තලා", "category": "plant" },
  { "word": "කරමුක්කය", "meaning": "දුස්සින්", "category": "plant" },
  { "word": "කරාලු", "meaning": "උක්", "category": "plant" },
  { "word": "කරාවල", "meaning": "කලවර් (කළුපාට තද අලුවක් ඇති ගස් වගිය)", "category": "plant" },
  { "word": "කරෑවා", "meaning": "කුරුඳු", "category": "plant" },
  { "word": "කරෑවා අරිසි", "meaning": "කලු කඩල, බාදියාන්", "category": "plant" },
  { "word": "කරාවාපට්ටෙයි", "meaning": "කුරුඳු පොතු", "category": "plant" },
  { "word": "කරේවන්කේ", "meaning": "නිල් මියා ගස්", "category": "plant" },
  { "word": "කරේවේම්පු", "meaning": "කරබෙයියා (කරපිංචා ගස)", "category": "plant" },
  { "word": "කරාවේල්", "meaning": "බබිබුල", "category": "plant" },
  { "word": "කරේපි", "meaning": "හීන, ඇට", "category": "treatment" },
  { "word": "කරේණු", "meaning": "කිණිහිරිගස", "category": "plant" },
  { "word": "කරේනුක", "meaning": "වැල්කහඹි", "category": "plant" },
  { "word": "කරේපත්ත", "meaning": "කළු අබ", "category": "plant" },
  { "word": "කරේරි", "meaning": "ලුණු වරණ", "category": "plant" },
  { "word": "කරේවිකා", "meaning": "හිස්කබල", "category": "symptom" },
  { "word": "කරෝ", "meaning": "වංඇපල", "category": "plant" },
  { "word": "කරෝකී", "meaning": "රොම්බලුහු", "category": "plant" },
  { "word": "කරෝපගා", "meaning": "මඟ හෝන් සුදු කැකිරි, නියඟරා", "category": "plant" },
  { "word": "කල්බිදිය", "meaning": "හුලංගිත්, ශින් ගස", "category": "plant" },
  { "word": "කල්ක", "meaning": "සුරක්නෙල්, බුලු", "category": "plant" },
  { "word": "කල්කවාප්‍රිය", "meaning": "වනු වැල්, (බාන් වැල්=වෙනිවැල්)", "category": "plant" },
  { "word": "කල්කඛණ්ඩ", "meaning": "ගල්කහඬු, (සූකිරි)", "category": "treatment" },
  { "word": "කල්කඵල", "meaning": "දෙළුම් ගස", "category": "plant" },
  { "word": "කල්කරොඩ", "meaning": "ලොත් ගස", "category": "plant" },
  { "word": "කල්කී", "meaning": "තූරක්නෙල්", "category": "plant" },
  { "word": "කල්කී වාක්‍යය", "meaning": "බූලුගස", "category": "plant" },
  { "word": "කල්සණිකා", "meaning": "කළු ඉරමුසු", "category": "plant" },
  { "word": "කල්නෝ", "meaning": "බුලු ගස", "category": "plant" },
  { "word": "කල්නාර්", "meaning": "ගල් නාර", "category": "treatment" },
  { "word": "කලයක", "meaning": "හිඟුරුමියැලි", "category": "plant" },
  { "word": "කලපදම", "meaning": "හීත් ඇසල ගස", "category": "plant" },
  { "word": "කලපාදප", "meaning": "දේවදාර, බුලු රුක", "category": "plant" },
  { "word": "කලාවාප්‍රිය", "meaning": "බාන්වැල්", "category": "plant" },
  { "word": "කලාධික", "meaning": "පැපිලිය, (පන්පාඩගම්)", "category": "plant" },
  { "word": "කලාසි", "meaning": "ගල් සේද, (ගල්සෙවල)", "category": "plant" },
  { "word": "කල්මදම", "meaning": "ගල්මද", "category": "treatment" },
  { "word": "කල්මුරසී", "meaning": "ගල්මෝර", "category": "plant" },
  { "word": "කල්‍ය", "meaning": "මී පැණි", "category": "treatment" },
  { "word": "කල්පනමුරුක්කූ", "meaning": "එරබදු", "category": "plant" },
  { "word": "කල්‍ය", "meaning": "කොත්තමල්ලි, මානෙල්, ඉඟුරු, ගරංකහ", "category": "plant" },
  { "word": "කල්ලහර", "meaning": "ගෙල්මලි (කල්හාර)", "category": "plant" },
  { "word": "කල්ලිපාකානූ", "meaning": "පෙනිපුවක්", "category": "plant" },
  { "word": "කල්ලිප්පාල්", "meaning": "දළක් කිරි", "category": "treatment" },
  { "word": "කල්ලි", "meaning": "දළක්, මඟ උක්", "category": "plant" },
  { "word": "කල්ලු පපු", "meaning": "ගල්පුවක්", "category": "plant" },
  { "word": "කල්ලුවාකි", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කල්ගම", "meaning": "ගල්මද", "category": "treatment" },
  { "word": "කල්නර", "meaning": "කල්නාරය", "category": "treatment" },
  { "word": "කල්නාර්", "meaning": "ගෙල්මලි", "category": "plant" },
  { "word": "කලසක", "meaning": "සුවඳ කසා, හිඟුරුමියැලි", "category": "plant" },
  { "word": "කලසදම", "meaning": "බුලු ගස", "category": "plant" },
  { "word": "කලසපත්‍රිකා", "meaning": "රතු සැබෝ ගස", "category": "plant" },
  { "word": "කලසපත්‍රී", "meaning": "රතු සැබෝ ගස", "category": "plant" },
  { "word": "කලවන්ත", "meaning": "නිරෝගී", "category": "treatment" },
  { "word": "කල්‍ය", "meaning": "අරණක්කසා, (ගරංකහ), කොත්තමල්ලි, නිල්පුල්", "category": "plant" },
  { "word": "කළ්‍යාණී", "meaning": "රත්රන්", "category": "treatment" },

  // --- පිටුව 90 (image_a9fd84.png) ---
  { "word": "කලකණික", "meaning": "පැපිලිය", "category": "plant" },
  { "word": "කලකණිවිට", "meaning": "මලපුවා හෝ කබල", "category": "treatment" },
  { "word": "කල්‍යාණී", "meaning": "මූරුවා, දියබෙරලිය, පල්, සුදු පාවිල", "category": "plant" },
  { "word": "කල්‍යාණිකා", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "කල්‍යාණිනී", "meaning": "පැපිල ගස", "category": "plant" },
  { "word": "කල්‍යාණ්", "meaning": "මස්වන්න, කල්ගස", "category": "plant" },
  { "word": "කල්‍යාණශිඟු", "meaning": "මූරුවා", "category": "plant" },
  { "word": "කලොච්චීවන", "meaning": "මෙහි, කලුකම්මේරිය, තල් ගස, කෙළිඳ", "category": "plant" },
  { "word": "කලාප", "meaning": "කලඳ (මදටිය විස්සක බර)", "category": "treatment" },
  { "word": "කලාමොක්කූ", "meaning": "(කලාමොක්කු) අඟිල්", "category": "plant" },
  { "word": "කලස", "meaning": "කකුල්, (කපුකිනිස්ස), ගිවුල්, කලුදුරු", "category": "plant" },
  { "word": "කලකල", "meaning": "කල් මැලියම්", "category": "treatment" },
  { "word": "කලකණ්ණිකා", "meaning": "කළු ඉරමුසු", "category": "plant" },
  { "word": "කලවක්කොට්ටෙහි", "meaning": "කුඹුරු ඇට", "category": "plant" },
  { "word": "කලවිට්", "meaning": "කුඹුරු වැල්", "category": "plant" },
  { "word": "කලප්", "meaning": "කලඳ", "category": "treatment" },
  { "word": "කලවි", "meaning": "කිසි සාවට නොඹුරු සෙම්", "category": "symptom" },
  { "word": "කලන්", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කලභ", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කලද", "meaning": "කලින්ත (මදටිය විස්සක බර)", "category": "treatment" },
  { "word": "කලදුරු", "meaning": "කලාඳුරු", "category": "plant" },
  { "word": "කලබො", "meaning": "රීදි", "category": "treatment" },
  { "word": "කලබොග", "meaning": "රීදි, රත්රන්", "category": "treatment" },
  { "word": "කලන්ගල්කාච්චි", "meaning": "නොගොල්ලු අල", "category": "plant" },
  { "word": "කලන්දු", "meaning": "කටුකරෝස වැල් (කටුකෝෂිකා වැල්)", "category": "plant" },
  { "word": "කලන්දොක්කූ", "meaning": "අඟිල්", "category": "plant" },
  { "word": "කලක", "meaning": "එක් මසක් වූ ගැබ, හොල් ගස", "category": "treatment" },
  { "word": "කලකප්‍රිය", "meaning": "බෙලි", "category": "plant" },
  { "word": "කලග්ගන්තීර", "meaning": "ගාල් දෙවුළු දිය", "category": "treatment" },
  { "word": "කලගිරි", "meaning": "දෙවුළු දිය", "category": "treatment" },
  { "word": "කලම්", "meaning": "මොණරා", "category": "treatment" },
  { "word": "කලම්", "meaning": "පැපිලිය, මොණරවිල් පාටිය", "category": "plant" },
  { "word": "කලම්", "meaning": "විලසලා", "category": "plant" },
  { "word": "කලහ", "meaning": "අත්තන, මංගහ්", "category": "plant" },
  { "word": "කලහ පොත", "meaning": "අත්තන පොතු", "category": "plant" },
  { "word": "කලභවල්ලභ", "meaning": "පියගස්", "category": "plant" },
  { "word": "කලම්බ", "meaning": "කපුකිනිස්ස, (කකුල්), කොකුම් ගස", "category": "plant" },
  { "word": "කලම්බක", "meaning": "මකී, දුරහරිටා", "category": "plant" },
  { "word": "කලක්ඛ", "meaning": "නිළිගුමල් (නිවිති වැල්)", "category": "plant" },
  { "word": "කලඹිකා", "meaning": "නිවිති", "category": "plant" },
  { "word": "කලම්", "meaning": "නිවිති", "category": "plant" },
  { "word": "කලම්බු", "meaning": "නිවිති", "category": "plant" },
  { "word": "කලඹුක", "meaning": "නිවිති", "category": "plant" },
  { "word": "කලවෙල්", "meaning": "නිවිති", "category": "plant" },
  { "word": "කලවෙට්ටු", "meaning": "වේලා", "category": "plant" },
  { "word": "කලමෙයාක්කු", "meaning": "අඟිල්", "category": "plant" },
  { "word": "කලම්", "meaning": "සිල සලබ", "category": "plant" },
  { "word": "කලම්", "meaning": "නිවිති", "category": "plant" },
  { "word": "කලන්", "meaning": "අත්තන", "category": "plant" },
  { "word": "කලවේට්ටු", "meaning": "කලව තම ඇල් වී වගිය", "category": "plant" },
  { "word": "කලසෙක්", "meaning": "කල් මැලියම්", "category": "treatment" },
  { "word": "කලෑවි", "meaning": "තොත්තෙරි (යොනොමු)", "category": "plant" },
  { "word": "කලෑරේත්නම්", "meaning": "ගල් රක්ත", "category": "treatment" },
  { "word": "කලසක", "meaning": "කෙළිඳ ගස", "category": "plant" },
  { "word": "කලවක්ක", "meaning": "කෙළිඳ ගස", "category": "plant" },
  { "word": "කලගුනික", "meaning": "පැපිලිය (පන්පාඩගම්)", "category": "plant" },
  { "word": "කලසී", "meaning": "වැල්පැපොල, අශ්වකණ්ණ, පලොල්, කිරිදිවැල්", "category": "plant" },

  // --- පිටුව 91 (image_a9fa3f.png) ---
  { "word": "කලසිකා", "meaning": "පුස්වෙන්න", "category": "plant" },
  { "word": "කලහ ගස්", "meaning": "තුවාල සේමීමට කහට වතුර සාදා ගන්නා තද රතු පාටකින් යුත් පොතු තිබෙන ගසක්. මේ කහට සායම් වශයෙන් ද පාවිච්චි කරයි. උග්‍ර ගතියෙන් යුත් කහින් කහට ගතිය ඇති මේවායේ පොතු අතිසාර රෝගයට දෙන කසාය වලට ද ගනී.", "category": "plant" },
  { "word": "කලහ කානක", "meaning": "කුකුරුකඳු, කෙළිඳ ගස", "category": "plant" },
  { "word": "කලහලක", "meaning": "සියඹලා", "category": "plant" },
  { "word": "කලී", "meaning": "මනෝසිල, කරඹ, කාමරේගා, ඉඟුරු, මීපැණි", "category": "treatment" },
  { "word": "කලාකොඩිකාරෙහි", "meaning": "කරබ, සිහින් කරඹ", "category": "plant" },
  { "word": "කලාප්", "meaning": "කළුදුරු, මහදුරු", "category": "plant" },
  { "word": "කලාසක", "meaning": "ගුරප්නල් වී", "category": "plant" },
  { "word": "කලාදුරු", "meaning": "වංස (වළුනු)", "category": "plant" },
  { "word": "කලාස", "meaning": "මොණර පිල", "category": "treatment" },
  { "word": "කලාපි", "meaning": "හුඟ", "category": "plant" },
  { "word": "කලාමිනී", "meaning": "නොපොලු (නොපොලු), කාමරංගා, හීත් කලාඳුරු", "category": "plant" },
  { "word": "කලෑස", "meaning": "කලඹ, කබල", "category": "treatment" },
  { "word": "කලාසක", "meaning": "කලව තම ඇල් වී වගිය", "category": "plant" },
  { "word": "කලාවක", "meaning": "මකුණුවැන්න (මකුළු වැන්න) ගලබුද=දිය මතුපිට උපදනා පන් වෙසෙසක්", "category": "plant" },
  { "word": "කලාරු", "meaning": "රත්වන් වැටකේ", "category": "plant" },
  { "word": "කලාව", "meaning": "කලවෙ නිහත", "category": "plant" },
  { "word": "කලී", "meaning": "සිහින්, කරඹ, බුලු, කලප, බුලු පල්ල", "category": "plant" },
  { "word": "කලිකාර", "meaning": "සිවිල, දියතිප්පිලි", "category": "plant" },
  { "word": "කලිකාටි", "meaning": "ලියනගලා", "category": "plant" },
  { "word": "කලිකානිකා", "meaning": "සිවිල, කුණුකරඳ, ලියනගලා", "category": "plant" },
  { "word": "කලිකාශිත්", "meaning": "නොපොලු", "category": "plant" },
  { "word": "කලිකා", "meaning": "කරාබුනැටි, බොර, මල් කැකුළු, සුවඳ කොට, අලවිය, කඹුපිල", "category": "plant" },
  { "word": "කලිකිලා", "meaning": "බෙලි", "category": "plant" },
  { "word": "කලිමොහාතම", "meaning": "කරාබුනැටි", "category": "plant" },
  { "word": "කලිමුඛික", "meaning": "බුලු", "category": "plant" },
  { "word": "කලිගණත", "meaning": "කුඹුරු වැල", "category": "plant" },
  { "word": "කලිගා", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කලිඞ්ග", "meaning": "කෙළිඳ, මොර, කලිල, කුකුරුකඳු", "category": "plant" },
  { "word": "කලිඞ්ගක", "meaning": "කෙළිඳ, බුල්ල, මහරි, කුකුරුකඳු, බුළු", "category": "plant" },
  { "word": "කලිඟුපෙප්", "meaning": "කෙළිඳ ඇට", "category": "plant" },
  { "word": "කලිඟුසෙඩා", "meaning": "කෙළිඳ ගස", "category": "plant" },
  { "word": "කලිඟු බීජ", "meaning": "කෙළිඳ ඇට", "category": "plant" },
  { "word": "කලිමාහා", "meaning": "සුදු හිරැස්ස පාල, කකුළු සූනු, (කහිටකශාලි)", "category": "plant" },
  { "word": "කලිමාලී", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කලිසකසිකා", "meaning": "වල්මෑ, අවරිය ගස", "category": "plant" },
  { "word": "කලිසභන", "meaning": "වැල්බී", "category": "plant" },
  { "word": "කලී නගර", "meaning": "බුළු", "category": "plant" },
  { "word": "කලී ද්‍රව", "meaning": "බුළු, මොරගස, මදපල්ල", "category": "plant" },
  { "word": "කලී මඳ", "meaning": "කෑසිරි, පාණී කොමඩු", "category": "plant" },
  { "word": "කලිසන", "meaning": "බුළු, මොරගස", "category": "plant" },
  { "word": "කලිකාස", "meaning": "බෙලි", "category": "plant" },
  { "word": "කලීජී", "meaning": "බුළු", "category": "plant" },
  { "word": "කලී ඵල", "meaning": "බුළු ගෙඩිය", "category": "plant" },
  { "word": "කලිමාල", "meaning": "තලස්ගාරය", "category": "plant" },
  { "word": "කලිම", "meaning": "මහරි ගස", "category": "plant" },
  { "word": "කලිමාරිසා", "meaning": "සිවිල, කුණුකරඳ", "category": "plant" },
  { "word": "කලිමාල(ක)", "meaning": "කුරක්කන්", "category": "plant" },
  { "word": "කලිමාල්‍ය", "meaning": "සබුසඳුන්", "category": "plant" },

  // --- පිටුව 92 (image_a9f6e1.png) ---
  { "word": "කලියක", "meaning": "ගොන්වැල්, (මතුවැල්)", "category": "plant" },
  { "word": "කලියුශාලස", "meaning": "බුළු", "category": "plant" },
  { "word": "කලියුගාවාස", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කලිරෝ", "meaning": "කිඹුල්", "category": "treatment" },
  { "word": "කලීලයා", "meaning": "කම්බිල", "category": "plant" },
  { "word": "කලීවංස", "meaning": "බුළු", "category": "plant" },
  { "word": "කලිසෝදරා", "meaning": "නවකන්දි", "category": "plant" },
  { "word": "කලිහාරි", "meaning": "නියඟලා", "category": "plant" },
  { "word": "කලී", "meaning": "බුළු, කුකුරු මුවන්, කලා", "category": "plant" },
  { "word": "කලීගතක", "meaning": "වැල්මී", "category": "plant" },
  { "word": "කලීද්‍ර", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කලීර", "meaning": "ගස්වල බඩය", "category": "plant" },
  { "word": "කලීල", "meaning": "නුවර ගස", "category": "plant" },
  { "word": "කලූ", "meaning": "තිප්පිලි, සභි විෂ, ගුළු ව්‍යාල", "category": "plant" },
  { "word": "කළුකද", "meaning": "කිහිිරි", "category": "plant" },
  { "word": "කළු කැම්මේරිය", "meaning": "මනික්කන්නා, (අජ්කැම්මේරිය=කාකජංඝා)", "category": "plant" },
  { "word": "කලු කොහිල", "meaning": "මෙය දම් බටු ගසට හෝ කටු මිරිස් ගසට සමාන අඩි තුනක් පමණ උසට වැඩෙන පැළෑටියකි. මේ වගිය තෙල් බෙහෙත් සඳහා කෘම අඩයක් වශයෙන් ගණිති. රෝග බාධ හෝ වෙන යම් කිසි හේතූන් නිසා නින්ද නොයන අයට නිද්‍රා ජනක ඖෂධයක් වශයෙන් මෙය බොහෝ ප්‍රයෝජනවත්ය. නින්ද නොයන අයගේ කොට්ටයට යටින් මේ ගසේ අමු අතු කැබැල්ලක් දමා තැබුවිට හොඳින් නින්ද යයි.", "category": "plant" },
  { "word": "කළු කිහිරි", "meaning": "කච්චර ගස", "category": "plant" },
  { "word": "කළු කුමාර මූඩියන්සේ", "meaning": "කළු ගව රල (රහස් බේත් වට්ටෝරුවක එන වචනයක්)", "category": "treatment" },

  // --- පිටුව 93 (image_a9f6e1.png - කලු කොහිල විස්තරය ඉහත ඇතුළත් කර ඇත) ---
  // --- පිටුව 94 (image_a9a354.png) ---
  { "word": "කලුවා ගස්", "meaning": "කටින් වඩා මඳක් ලොකු වූ එකම අලයකි. ගරහට වැඩියන මේ අලයේ කෙළවර ගස වැවී ඇත. ගසේ කොළ ඉඟුරු කොළ වලට මඳක් සමානය. එය අඩි තුනක් පමණ උසට වැවේ ය. අජීර්ණ, පණු හොරි, දද, කුෂ්ඨ ආදී හමේ හටගන්නා රෝග සඳහා මෙය ප්‍රත්‍යක්ෂ ඖෂධයකි.", "category": "plant" },
  { "word": "කලුවාගස්", "meaning": "කළුපාට කොළ හා කඳ ඇති පිටින් පෙනෙන පෙනුමෙන් කළුවර ගසට බොහෝ දුරට සමාන සීතාධික ප්‍රදේශවල වැඩෙන ගස් වගියකි. මේවායේ ලෑ සමිපූර්ණ සුදු පාටින් යුක්තය.", "category": "plant" },
  { "word": "කළුවැල්කලා", "meaning": "කලා වගියක්, කළු වැල්", "category": "plant" },
  { "word": "කළුවැල්", "meaning": "කාලාගරු, අගිල්", "category": "plant" },
  { "word": "කළුසම්බෙිරි", "meaning": "වැල්මීදුව", "category": "plant" },
  { "word": "කළුසු", "meaning": "කන්පක නම් ගස් වගිය (තළි රුක)", "category": "plant" },
  { "word": "කළුගහ", "meaning": "කළුවර අරළු", "category": "plant" },
  { "word": "කලොඟින", "meaning": "එරමිණියා වැල", "category": "plant" },
  { "word": "කවක", "meaning": "බිම්මල් (හතු)", "category": "plant" },
  { "word": "කවව", "meaning": "පැපිලිය, නැවී රැක, හෙලෑනුඹු ගස", "category": "plant" },
  { "word": "කවවනාලක", "meaning": "පැපිලිය, නැවී රැක, හෙලෑනුඹු ගස", "category": "plant" },
  { "word": "කවවපත්‍ර", "meaning": "බූරාද ගස", "category": "plant" },
  { "word": "කවඩ්", "meaning": "බෙල්ලන්", "category": "treatment" },
  { "word": "කවද", "meaning": "හිස නාති තිලකද", "category": "treatment" },
  { "word": "කවරා", "meaning": "වෙලා ගස", "category": "plant" },
  { "word": "කවරි", "meaning": "වෙලා, රත්කණේරා, මනෝසිල", "category": "plant" },
  { "word": "කවරි කලා", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "කවරි කටුක", "meaning": "වෙලා ගස", "category": "plant" },
  { "word": "කවලග්‍රහ", "meaning": "තුන් කලඳ", "category": "treatment" },
  { "word": "කවාකා", "meaning": "කැකිරි", "category": "plant" },
  { "word": "කවි", "meaning": "තූරක්නෙල්, ගජතිප්පිලි", "category": "plant" },
  { "word": "කවිකේශ", "meaning": "ගිවුලු", "category": "plant" },
  { "word": "කවිතාභාභූ", "meaning": "තුඹ", "category": "plant" },
  { "word": "කවිර්", "meaning": "ගිවුලු ගස", "category": "plant" },
  { "word": "කවි තුප්පේය", "meaning": "යොන් තුඹ", "category": "plant" },
  { "word": "කවි තුඹෙයි", "meaning": "කව්තුඹ (යොන්තඹ=මරි තොන්ඩි)", "category": "plant" },
  { "word": "කවිලා", "meaning": "දිය මින්ත", "category": "plant" },
  { "word": "කවුඩිරී", "meaning": "කරපිංචා", "category": "plant" },
  { "word": "කවුඩු උලබත්ත", "meaning": "කවුඩු කැකිරි", "category": "plant" },
  { "word": "කවුඩු ගියගරා", "meaning": "කවුඩු කැකිරි", "category": "plant" },
  { "word": "කවුඩු තුඹෙහි", "meaning": "යොන්තඹ, ඇත් තුඹ, (මී ගු තුඹ)", "category": "plant" },
  { "word": "කවුන්නීය", "meaning": "රුතැණිය (වැල් මොලඟු=වැල්ගාමිරිස්)", "category": "plant" },
  { "word": "කෂේරා", "meaning": "ගස් වෙසෙසක්", "category": "plant" },
  { "word": "කෂෙල්ලූ", "meaning": "කාකෝලි (අෂ්ටක වගියේ ඖෂධයක්)", "category": "plant" },
  { "word": "කෂෝපනී", "meaning": "මඳක් උණු පැන්", "category": "treatment" },
  { "word": "කෂාවරිකා", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කෂ්මල", "meaning": "මුර්ඡාව", "category": "symptom" },
  { "word": "කෂ්මර", "meaning": "කුංකුමප්පු (සඳුන් මල්) කොකුම්", "category": "plant" },
  { "word": "කෂා", "meaning": "මස්වන්න", "category": "plant" },
  { "word": "කෂාය", "meaning": "පුවක් ගස, උදු, කොවිල, රත් ලොත්, ලේ, ඇල්කහඹිලියා", "category": "treatment" },
  { "word": "කෂේරා", "meaning": "උවරල, බිමිතල්, කෙක පිය, තූන්හිරියා පත්", "category": "plant" },
  { "word": "කෂේරුකා", "meaning": "කෙකපිය, කලාඳුරු", "category": "plant" },
  { "word": "කෂ්විල", "meaning": "සුලුපාරණ", "category": "treatment" },
  { "word": "කෂාය", "meaning": "කොවිල, දඹ, දුව ගස, කෂට පුවක් ගස, කෂට රස", "category": "treatment" },
  { "word": "කෂායකා", "meaning": "දුරා ලභා (යවාසා)", "category": "plant" },
  { "word": "කෂායකාන්ත", "meaning": "රතු ලොත් ගස", "category": "plant" },
  { "word": "කෂාය ජල", "meaning": "පුලලී, ඇසලූ, දිවුල්, මඟරි, තුඟ, යන මෙයින් පෙරා ගත් ජලය", "category": "treatment" },

  // --- පිටුව 95 (image_a9a029.png) ---
  { "word": "කෂාය වගී", "meaning": "නීපල, ඉන්සලු, අඹ, දඹ, මූණමල්, කිහිිරි, යන මේවා යේ කෂට ජලය.", "category": "treatment" },
  { "word": "කෂායා", "meaning": "දුරා ලභා, ඇම්බරැල්ල, ඉඳි ගස", "category": "plant" },
  { "word": "කෂායිත්", "meaning": "ඉඳි ගස, සල් ගස, අරත්ත", "category": "plant" },
  { "word": "කෂේරුකා", "meaning": "කෙකපිය", "category": "plant" },
  { "word": "කස්කිලික", "meaning": "කක්කිලාස", "category": "treatment" },
  { "word": "කස්තුරි", "meaning": "මෘග මද, උරලැෑ පීටි, සායාමා", "category": "treatment" },
  { "word": "කස්තුරිකා", "meaning": "කණේරා", "category": "plant" },
  { "word": "කස්තුරිකා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කස්තුරි මක්කල්", "meaning": "අරණක්කසා (හරංකහ)", "category": "plant" },
  { "word": "කස්තුරි මල්ලිකා", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කස්තුරි මල්ලිකා", "meaning": "ඉඳිගස", "category": "plant" },
  { "word": "කස්තුරිමාංගා බේර්", "meaning": "කස්තුරි", "category": "treatment" },
  { "word": "කස්තුල", "meaning": "හරංකහ අල", "category": "plant" },
  { "word": "කස්තන", "meaning": "ගක්බේරිය, කිරාත, (බිම කොහොඹ,) ගණ", "category": "plant" },
  { "word": "කසප්‍ර", "meaning": "මිරි ඇට", "category": "plant" },
  { "word": "කස්මී රප", "meaning": "කොකුම්", "category": "plant" },
  { "word": "කස", "meaning": "පොල් ගස, කහ අල, කණ්ණා", "category": "plant" },
  { "word": "කසකස", "meaning": "තෝර ගස", "category": "plant" },
  { "word": "කසකාල", "meaning": "කසපිය ගස", "category": "plant" },
  { "word": "කසව", "meaning": "කසව, කසාය", "category": "treatment" },
  { "word": "කසව", "meaning": "කසට රස", "category": "treatment" },
  { "word": "කසවගඟ", "meaning": "කසට ගස", "category": "plant" },
  { "word": "කසවතුර", "meaning": "කසමල් ගස", "category": "plant" },
  { "word": "කසඳුන්", "meaning": "රත්සඳුන්", "category": "plant" },
  { "word": "කසන මර්දන", "meaning": "තෝර ගස", "category": "plant" },
  { "word": "කසනෝත්පාට", "meaning": "වංඇපල", "category": "plant" },
  { "word": "කසනෝත්පාපන", "meaning": "වංඇපල, (ආඩතෝඩා)", "category": "plant" },
  { "word": "කසපල", "meaning": "පොල් ගෙඩිය", "category": "plant" },
  { "word": "කසමල්", "meaning": "වැලිකහමල්", "category": "plant" },
  { "word": "කසා", "meaning": "මස්වන්න, වනු වැල්, අමු හෝ වියළි කසා", "category": "plant" },
  { "word": "කසාකම්ම", "meaning": "මිරිස්", "category": "plant" },
  { "word": "කසාකා", "meaning": "තෝර ගස", "category": "plant" },
  { "word": "කසාබිලිය", "meaning": "කසඹිලියා වැල", "category": "plant" },
  { "word": "කසාස", "meaning": "සිරස, කල්ක, කාව (සිදි කසාය) සීත, පාණ්ඩ යයි කෂාය වගී පසකි.", "category": "treatment" },
  { "word": "කසාය කාන්", "meaning": "කබර (ලොත්) ගස", "category": "plant" },
  { "word": "කෂායළුලිකා", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "කසාය මධුර වර්ධ", "meaning": "දඹ ගස", "category": "plant" },
  { "word": "කසාය දුර්වනා", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "කසාය වාත්", "meaning": "සුලුකුමුක්", "category": "treatment" },
  { "word": "කසාය", "meaning": "කසඹිලියා", "category": "plant" },
  { "word": "කසායාස", "meaning": "ඇඹුල් ඇඹිලිය", "category": "plant" },
  { "word": "කසායින්", "meaning": "සල්, දෙහි ගස", "category": "plant" },
  { "word": "කසිනි", "meaning": "අරණක්කසා (ගරංකසා)", "category": "plant" },
  { "word": "කසිය", "meaning": "ජීරක්කාසි (කාසිය නම ද්‍රව්‍යය)", "category": "treatment" },
  { "word": "කසු", "meaning": "රත්රන්", "category": "treatment" },
  { "word": "කසුන්", "meaning": "රන්", "category": "treatment" },
  { "word": "කසුලාර", "meaning": "නෙලුමා නෙල් (සුදු නෙළුම්)", "category": "plant" },
  { "word": "කහගි", "meaning": "කාසි", "category": "treatment" },
  { "word": "කහමුන්", "meaning": "රණවරා ඇට", "category": "plant" },
  { "word": "කහර්", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "කහර්මිනා", "meaning": "වී වගියක්", "category": "plant" },
  { "word": "කහලී", "meaning": "ගප්බේරිය, වැල්මී", "category": "plant" },
  { "word": "කළන්", "meaning": "මදටිය විස්සක බර (කලඳ)", "category": "treatment" },
  { "word": "කළඳ", "meaning": "මදටිය විස්සක බර (කලඳ)", "category": "treatment" },
  { "word": "කළන්ද", "meaning": "මදටිය විස්සක බර (කලඳ)", "category": "treatment" },
  { "word": "කළල්", "meaning": "කකුල රූපය", "category": "symptom" },
  { "word": "කළානුසාරී", "meaning": "කළුවැල්", "category": "plant" },
  { "word": "කළාය", "meaning": "කඹිල", "category": "plant" },
  { "word": "කළීර", "meaning": "උණ කිඟිල්, වේබිබ ආදිය", "category": "plant" },

  // --- පිටුව 96 (image_a99fd1.png) ---
  { "word": "කා", "meaning": "කුරටිය, ගස, ඉරිවේරිය", "category": "plant" },
  { "word": "කාංචන", "meaning": "සිවංගුරු, නාගස්, රත් රන්, කාමල් රේණු", "category": "plant" },
  { "word": "කාංචිකොසිවල්", "meaning": "වැල්කසඹිලියා", "category": "plant" },
  { "word": "කාංස පත්‍ර", "meaning": "කුරුණිය, නෑලි හතර (සේරු 4 = රාත්තල් 8)", "category": "treatment" },
  { "word": "කාංසිකා", "meaning": "මුංවැන්න", "category": "plant" },
  { "word": "කාංස්‍ය", "meaning": "යකඩ, ලෝකඩ", "category": "treatment" },
  { "word": "කාංස්‍ය නීල", "meaning": "තුත්තම්, ලෝකඩ", "category": "treatment" },
  { "word": "කාකනම", "meaning": "කවරොලු", "category": "plant" },
  { "word": "කාකීර", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කාකී", "meaning": "තුබරී, (තුවරලා)", "category": "plant" },
  { "word": "කාකිර", "meaning": "කවෙළු", "category": "plant" },
  { "word": "කාකීව", "meaning": "මිරික්කලු, (මූරංගා)", "category": "plant" },
  { "word": "කාක", "meaning": "කැකිරි, කලුකම්මේරිය, කිණිහිරි, දන්ත, කොවඩිබුලා, කලුඅගිල්", "category": "plant" },
  { "word": "කාකකබූ", "meaning": "මෛත්තී, ගල්දුම්මල", "category": "plant" },
  { "word": "කාකකාර්", "meaning": "ඉඳි, (ඉඳිගස)", "category": "plant" },
  { "word": "කාකකලා", "meaning": "කොවඩිබුලා, කැම්මේරිය", "category": "plant" },
  { "word": "කාකකවාකා", "meaning": "කවුඩු කැකිරි", "category": "plant" },
  { "word": "කාකකුඩිබ්බ", "meaning": "ඇඹුල්, නිල්පුල්", "category": "plant" },
  { "word": "කාකකුම්භිකා", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කාකගුක්ස්", "meaning": "මුංඇට, (බලීද)", "category": "plant" },
  { "word": "කාකජන්ති", "meaning": "මහකරඳ, මගුල්කරඳ, ගොබකදුරු", "category": "plant" },
  { "word": "කාකඩහි", "meaning": "උග්‍රරස්ස, කටුවෙලඟ, ලියනගලා", "category": "plant" },
  { "word": "කාකතප්වල්ලා", "meaning": "සිහින් කිණිහිරි, (සුළු කිණිහිරි)", "category": "plant" },
  { "word": "කාකතප්වර්දි", "meaning": "හෙලකිණිහිරි", "category": "plant" },
  { "word": "කාකතිකුම්", "meaning": "මුංඇට, බලීද", "category": "plant" },
  { "word": "කාකජ්වල", "meaning": "කොවඩිබුලා, කළු කැම්මේරිය, අලවිය, අක්මැල්ල", "category": "plant" },
  { "word": "කාකජම්මු", "meaning": "බලූදම, දියදඹ", "category": "plant" },
  { "word": "කාකජානු (ක)", "meaning": "ගුරැල්ල ගස", "category": "plant" },
  { "word": "කාකදීකප්", "meaning": "මුංඇට, (බලීද)", "category": "plant" },
  { "word": "කාකඩුම්බර", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "කාකණී", "meaning": "කවුඩුකැකිරි, කෝවක්කා, තොවිල, ගුරැල්ල", "category": "plant" },
  { "word": "කාකනඬු", "meaning": "ගුරැල්ල ගස", "category": "plant" },
  { "word": "කාකනඩ්ඩි", "meaning": "කඩුවෙලඟ, උග්‍රරස්ස, මදදුරු, තොවිල", "category": "plant" },
  { "word": "කාකණී නාතක", "meaning": "සියඹලා", "category": "plant" },
  { "word": "කාකනිකා", "meaning": "කැල්වැල්, අක්මැල්ල, මගුල්කරඳ, කලුකම්මේරිය, ගජලු, මුංඇට", "category": "plant" },
  { "word": "කාකතින්ත", "meaning": "කැල්වැල්", "category": "plant" },
  { "word": "කාකතිලක", "meaning": "සිහින් කිණිහිරි, සුළු කිණිහිරි", "category": "plant" },
  { "word": "කාකතුණ්බාලා", "meaning": "මීගුරුදුකෑම්මේරිය", "category": "plant" },
  { "word": "කාකතුණ්ඩා", "meaning": "අගිල්, කළු අඟිල්", "category": "plant" },
  { "word": "කාකතුණ්ඩ්කා", "meaning": "කිරියගුළු", "category": "plant" },
  { "word": "කාකතුණ්ඩි", "meaning": "මුංඇට, කැල්වැල්", "category": "plant" },
  { "word": "කාකතෙරා", "meaning": "කවුඩුකිරිය", "category": "plant" },
  { "word": "කාකදනතිකා", "meaning": "මුංඇට, දන්තගස, රතුකැම්මේරිය", "category": "plant" },
  { "word": "කාකධනී", "meaning": "බලීද", "category": "plant" },
  { "word": "කාකනදිකා", "meaning": "බලීද, (මුංඇට)", "category": "plant" },
  { "word": "කාකනමකොවෙච්චි", "meaning": "කවුඩුකිරි, කෝවක්කා, කවුඩුකෝවක්කා", "category": "plant" },
  { "word": "කාකනාම", "meaning": "වලා වැන්න", "category": "plant" },
  { "word": "කාකනාමය", "meaning": "කපුරු මුරංගා", "category": "plant" },
  { "word": "කාකනාස", "meaning": "උග්‍රරස්ස", "category": "plant" },
  { "word": "කාකනාසනී", "meaning": "උග්‍රරස්ස, කවුවෙලඟ", "category": "plant" },
  { "word": "කාකනාසා", "meaning": "කොවඩිබුලා, ගොබකදුරු, මීගුරුදුකැම්මේරිය", "category": "plant" },
  { "word": "කාකනාසිකා", "meaning": "කළුකැම්මේරිය, ගුරැල්ල, ලියනගලා", "category": "plant" },

  // --- පිටුව 97 (image_a99ca3.png) ---
  { "word": "කාකනාසිනී", "meaning": "උග්‍රරස්ස, කටුවෙලඟ", "category": "plant" },
  { "word": "කාකනී", "meaning": "ඇඹුල්වේ", "category": "plant" },
  { "word": "කාකනී", "meaning": "සින්බිලා", "category": "plant" },
  { "word": "කාකනීලා", "meaning": "බලුදම ගස", "category": "plant" },
  { "word": "කාකනෙරා", "meaning": "කවුඩුකිරිය, කවුඩුකිණිරි", "category": "plant" },
  { "word": "කාකපර්ණී", "meaning": "මුං වැන්න", "category": "plant" },
  { "word": "කාකපිල", "meaning": "සිහින් කිණිහිරි, (සුවර්ණගිරි)", "category": "plant" },
  { "word": "කාකපිලුකා", "meaning": "මුංඇට, (බලීද)", "category": "plant" },
  { "word": "කාකපුෂ්ප", "meaning": "විෂ්ණු ක්‍රාන්ත", "category": "plant" },
  { "word": "කාකප්‍රාණා", "meaning": "මීගුරුදුකැම්මේරිය", "category": "plant" },
  { "word": "කාකළු", "meaning": "කොසඹ, මහකොසඹ, බලුදම ගස", "category": "plant" },
  { "word": "කාකව්ලා", "meaning": "බලුදම ගස", "category": "plant" },
  { "word": "කාකබෝධි-කඹුබෝ ගස", "meaning": "මේ වගියේ කොළ බෝපත්‍ර වලට බොහෝ සෙයින් සමානය. එහෙත් ඒ කොළ බෝපත්‍ර වලට වඩා තද නිල් පැහැයෙන් යුක්තය. කොළවල නැටි සහ කඳ ද බෝධි වෘක්ෂ වල නැටි හා කඳ මෙන් සුදු පාට නැත. ගුරු පාටින් (කිලිටි රත් පැහැයෙන්) යුක්තය. අතු ද වැල්මෙන් පහතට එල්ලී වැටී තිබේ. මෙහි පොතු කැල්ම, ඉදිමුම හා ඇට පෑස්සීම යන මේ ආබාධ සඳහා අවශ්‍ය තෙල්, බෙහෙත්, මැල්ලුම්, ලේහ (පත්තූ) සෑදීමට අතිශයින් ප්‍රයෝජනවත්ය.", "category": "plant" },
  { "word": "වසංගත රෝගවලින් ආරක්ෂාවීම සඳහා පුරාණ කෙමක්", "meaning": "පාන්දර (ඉතා අළුයම) කපු වතක් ශරීරයට මත්තෙන් මේ ගසක් ලඟට මොට්ටා ආයුධය (මුවහත් ඇති කළු ගල් පතුරක්) ද රැගෙන පැමිණ ගසට පිටුපෑවෙන සේ නැගෙනහිර දෙසට යාරී ගසේ නැගෙනහිර දෙසට ගිය මුලකින් පොත්තක් කපුවත් ගැබ්ගබ ද අසුවන සේ පිටි අතින් (තමා පිටුපස වූ ගස පැත්තෙන්) ගලවා ගත යුතුය. මේ පොතු කෑලි ඉන බැඳ ගැනීමෙන් කිසිම වසංගත රෝගයක් බෝ නොවන බැව් පැරණි රහස් වට්ටෝරු වෙද පොත් වල කියා තිබේ. මෙය අත්දුටු සත්‍ය ක්‍රියාව (කෙමකි).", "category": "treatment" },
  { "word": "කාකභාණඬි", "meaning": "එලප්‍රනිද", "category": "plant" },
  { "word": "කාකභාණඬී", "meaning": "මනකරඳ, හිඟුරු කැම්මේරිය", "category": "plant" },

  // --- පිටුව 98 (image_a99bb0.png) ---
  { "word": "කාකාමර්දී", "meaning": "තෝර, තුවරලා", "category": "plant" },
  { "word": "කාකමාචී", "meaning": "කළුකම්මේරිය", "category": "plant" },
  { "word": "කාකමාතා", "meaning": "කළුකම්මේරිය", "category": "plant" },
  { "word": "කාකමුග්ග", "meaning": "මුංවැන්න", "category": "plant" },
  { "word": "කාකමුද්ගා", "meaning": "මුංවැන්න", "category": "plant" },
  { "word": "කාක රුක්", "meaning": "කොසඹ ගස", "category": "plant" },
  { "word": "කාකරූපා", "meaning": "අඟිල්, කළු අඟිල්", "category": "plant" },
  { "word": "කාකරුහා", "meaning": "පිළිල", "category": "plant" },
  { "word": "කාක ලම්බි", "meaning": "තලා, කළුකම්මේරිය, නිවිති වැල්", "category": "plant" },
  { "word": "කාකලී ද්‍රක්ෂා", "meaning": "මිදි වෙසෙසක් (කළු මිදි)", "category": "plant" },
  { "word": "කාකලෝධ්භ", "meaning": "ඇඹුල, අඟිල්, ඔළු", "category": "plant" },
  { "word": "කාකවල්ලභා", "meaning": "බලුදම", "category": "plant" },
  { "word": "කාකවල්ලරී", "meaning": "කවෙළු, කැල්වැල්, ගොහන් ගස", "category": "plant" },
  { "word": "කාකවල්ලී", "meaning": "හඟුලු, කැල්වැල්, කිරියගුළු", "category": "plant" },
  { "word": "කාකවලී", "meaning": "තැල්ල", "category": "plant" },
  { "word": "කාකවිප්කා", "meaning": "කවුඩු කිණිහිරිය", "category": "plant" },
  { "word": "කාකවෘන්තා", "meaning": "රතු කොල්ලු", "category": "plant" },
  { "word": "කාකශාන්තිකා", "meaning": "මුංඇට", "category": "plant" },
  { "word": "කාකශාලී", "meaning": "කළුගහල්", "category": "plant" },
  { "word": "කාකශිඛී", "meaning": "වලා වැන්න, කතුරුමුරුංගා", "category": "plant" },
  { "word": "කාකශිම්බී", "meaning": "රතු මුංඇට, කැල්වැල්", "category": "plant" },
  { "word": "කාකස්ත්‍රී", "meaning": "කතුරුමුරුංගා", "category": "plant" },
  { "word": "කාකස්පෘෂ්", "meaning": "කවුඩු කිණිහිරි", "category": "plant" },
  { "word": "කාකස්‍යී", "meaning": "ගප්බේරිය, වැල්මී", "category": "plant" },
  { "word": "කාකසම්මතා", "meaning": "බලීද", "category": "plant" },
  { "word": "කාකසාහ්වා", "meaning": "කැම්මේරිය", "category": "plant" },
  { "word": "කාකසෙවකා", "meaning": "උක් දණ්ඩ", "category": "plant" },
  { "word": "කාකසිංහා", "meaning": "කළුකම්මේරිය", "category": "plant" },
  { "word": "කාකා", "meaning": "අක්මැල්ල, කවෙළු, ගොබකදුරු, කොවඩිබුලා", "category": "plant" },
  { "word": "කාකාධනී", "meaning": "ලියනගලා, කවු වෙලඟ", "category": "plant" },
  { "word": "කාකාණ්ඩ", "meaning": "තොවිල, කවුඩුකිණිහිරි", "category": "plant" },
  { "word": "කාකාණ්ඩී", "meaning": "කවු වෙලඟ, තොවිල, මීමැස්සු", "category": "plant" },
  { "word": "කාකාදනී", "meaning": "බලීද, කටුවෙලඟ, සිහිට වැල්", "category": "plant" },
  { "word": "කාකාස්‍ය", "meaning": "කැල්වැල්", "category": "plant" },
  { "word": "කාකාල", "meaning": "වචවන්චාවි", "category": "plant" },
  { "word": "කාකාලී", "meaning": "ඇත්සාවිය", "category": "plant" },
  { "word": "කාකාහ්වා", "meaning": "කළුකම්මේරිය", "category": "plant" },
  { "word": "කාකාහ්වනා", "meaning": "කළුකම්මේරිය", "category": "plant" },
  { "word": "කාකාසතියා", "meaning": "මහසුදු කැම්මේරිය", "category": "plant" },
  { "word": "කාකි", "meaning": "නාපිරින්ත්ත, තෝර, කොවඩිබුලා, කිරියගුළු", "category": "plant" },
  { "word": "කාකිණී", "meaning": "බලීද", "category": "plant" },
  { "word": "කාකිමුඛ", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "කාකොසන්ධුකා", "meaning": "වැල්තුඹ", "category": "plant" },
  { "word": "කාකොදු", "meaning": "කටුකිණිහිරි", "category": "plant" },
  { "word": "කාකෙස්ට", "meaning": "කොසඹගස", "category": "plant" },
  { "word": "කාකෝ", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "කාකෝදුම්බරිකා", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "කාකෝන්තුව", "meaning": "සුදුබිළලු", "category": "plant" },
  { "word": "කාකෝත්පල", "meaning": "ඇඹුල, රක්තාශ්‍රය, (රත්නිල්පුල්)", "category": "plant" },
  { "word": "කාකෝදර", "meaning": "නාගස, නා", "category": "plant" },
  { "word": "කාකෝදුම්බරිකා", "meaning": "කොවඩිබුලා", "category": "plant" },
  { "word": "කාකෝල", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "කාකෝලී", "meaning": "කඩුවෙලඟ, කවෙළු, වැල්තීබිබටු, ඇත්සාවිය, රත්නම්සලා", "category": "plant" },
  { "word": "කාකොල්‍යාදීගණය", "meaning": "කිරිකවැල් දෙක, මීගකවැල් දෙක, වැල්මී, කකුළුසුනු, සුළුමෙවන්, මහමෙවන් දෙක, දිව, සභිය දෙක, පොත් බර, මිදි, සුලුකලන් (මුංවැන්න) දබකලන්, (මස්වන්න) තුක්පිරිස, (හුණමකුළු) සුළු හෙලබිය නොහොත් මහහෙලබිය කීිරීනය ගුළු, පිස්සුම්, රසකැද යන මේ ගණය ශරීර පිනවයි. තන කීිරි ඇති කරයි. ජීවනදාතු හා රේතස් වඩයි. පිත් ලේ හා වාතය නසයි.", "category": "treatment" }
];