// data_211_220.js - පිටු 211 සිට 220 දක්වා සියලුම වචන
const data_extra_211_220 = [
  // --- පිටුව 211 ---
  { "word": "තමුකා", "meaning": "උගුරස්ස", "category": "plant" },
  { "word": "තමුතලතා / තමුලතා", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "තමෝදර්ශන", "meaning": "පිතතප රෝගයක් (අඳුර දැක්ම)", "category": "symptom" },
  { "word": "තබකුෂ්ඨ", "meaning": "කුෂ්ඨ රෝග භේදයක් (තාමු කුෂ්ඨය)", "category": "symptom" },
  { "word": "තබකො", "meaning": "තම්පලා", "category": "plant" },
  { "word": "තබපිල්", "meaning": "පොල්ගස", "category": "plant" },
  { "word": "තබරස", "meaning": "රත්නෙළුම්, හෙළ පියුම්", "category": "plant" },
  { "word": "තබල", "meaning": "හින්තඹල, මහතඹල, රත් තඹල, එළ තඹල, සහතඹල යයි තඹල ගස්වගී කීපයකි.", "category": "plant" },
  { "word": "තබසිළු", "meaning": "කුකුළන්", "category": "plant" },
  { "word": "තඹු", "meaning": "සිවලුන්", "category": "plant" },
  { "word": "තඹුතිල් (තඹුතෙල්)", "meaning": "පිට නිල්පාට සහ ඇතුළ තඹපාට පොල් වර්ගය. දැනට බොහෝදෙනා රන් තැඹිලි ලෙස වරදවා ගන්නේ මේ පොල් වගිය යි.", "category": "plant" },
  { "word": "තඹුරු", "meaning": "රත්නෙළුම්, හෙළ පියුම්", "category": "plant" },
  { "word": "තයිර්", "meaning": "දීකිරි", "category": "treatment" },
  { "word": "තයිර්වුලා", "meaning": "වේලා, මල් සුදු වේලා", "category": "plant" },
  { "word": "තයිරවධනන්තීර්", "meaning": "දීපෙරලි දිය", "category": "treatment" },
  { "word": "තයිරා", "meaning": "දී", "category": "treatment" },
  { "word": "තර්ක්‍ෂ්‍ය", "meaning": "රසඳුන්", "category": "treatment" },
  { "word": "තකින්ධක", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "තකීනා", "meaning": "කාන්දම්", "category": "treatment" },
  { "word": "තකිරි", "meaning": "සිහින්මිදි, මහමිදි, ඇටවෙරිය, ඇත්තෝර, වල්කැකිරි, නීතිග ගස", "category": "plant" },
  { "word": "තරණි(ල)", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "තකෝපි", "meaning": "රේරු", "category": "plant" },
  { "word": "තකෝලක", "meaning": "තකුල් (කපුකිනිස්ස)", "category": "plant" },
  { "word": "තකෝලන්", "meaning": "තකුල් (කපුකිනිස්ස)", "category": "plant" },
  { "word": "තපී", "meaning": "පියාගස", "category": "plant" },
  { "word": "තපික", "meaning": "අත්සුණු", "category": "treatment" },
  { "word": "තපීන", "meaning": "අත්සුණු", "category": "treatment" },
  { "word": "තපිනී", "meaning": "ලුණුවිල, ලෝලුගස, යව වලින් කළ ආහාරය", "category": "plant" },
  { "word": "තර්බට=තජ්බට", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "තර", "meaning": "ඇසිකිනිගෙල, අසකිගෝල(ය) වෘක්‍ෂය", "category": "plant" },
  { "word": "තරක", "meaning": "අත්තන, උන්මත්ත", "category": "plant" },
  { "word": "තරග", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "තරට", "meaning": "ඇත්තෝරගස", "category": "plant" },
  {
    "word": "තරණ",
    "meaning": "පාවට්ටා පැළයට සමාන මේ ගසේ කොළ රත්මල් කොළ වැනි ය. එහෙත් ලා කොළපාටයෙන් යුත් මේවා රත්මල් කොළ වලට වඩා මඳක් උල් ය. ශරීරයේ හටගන්නා ලේ ගෙඩි, විෂර ගෙඩි ආදිය පැසවීම සඳහා මේ ගසේ ගෙඩි අඹරා ගෑමට යෝග්‍ය ය.",
    "category": "plant"
  },

  // --- පිටුව 212 ---
  { "word": "තරණ දළු", "meaning": "ඉලක් දෙවගියට ද මේ නම ව්‍යවහාර වේ.", "category": "plant" },
  { "word": "තරණි", "meaning": "කෝමාරිකා, වරාගස, කටුරෝස", "category": "plant" },
  { "word": "තරණිවල්ලි", "meaning": "වරා, කෝමාරිකා, කටුරෝස", "category": "plant" },
  { "word": "තරණිමිත්‍ර", "meaning": "වරා ගස", "category": "plant" },
  { "word": "තරමිප්‍රප්", "meaning": "කොමඩු, පත්තක්කා", "category": "plant" },
  { "word": "තරල", "meaning": "කාඩි, තළප", "category": "treatment" },
  { "word": "තරලි", "meaning": "සස්සඳවැළ, කපුරු", "category": "plant" },
  { "word": "තරැ", "meaning": "වෘක්‍ෂය, මහ පෝටා වැල, ඇසිකිනිගෙල, අක්‍ෂය ය, රත්කාල, දව ගස", "category": "plant" },
  { "word": "තරාජ", "meaning": "එළකිරි ගස", "category": "plant" },
  { "word": "තරාජීවන", "meaning": "රක්මුල", "category": "plant" },
  { "word": "තරාණි", "meaning": "නවැගිලි එරබු, දත්ත, දඩක්, මහදුරු, දේවදාර, සෙව්වන්දි මල", "category": "plant" },
  { "word": "තරාණිද", "meaning": "ලා ඉඟුරු", "category": "plant" },
  { "word": "තරාණිද්‍ර", "meaning": "කොළොම් ගස", "category": "plant" },
  { "word": "තරාණිමීතා", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "තරුණී", "meaning": "කෝමාරිකා, රම්මානිස්ස රසකිඳ, මිදි, කටුකරඬු, මහ කටුදුරු", "category": "plant" },
  { "word": "තරුණිය", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "තරුණීකර්‍ෂමල", "meaning": "මදටගස", "category": "plant" },
  { "word": "තරුණීමූල", "meaning": "දත්ත මුල්", "category": "plant" },
  { "word": "තරුපිෂ්පා", "meaning": "ලාබු, (මාලියම්)", "category": "plant" },
  { "word": "තරාහුප්", "meaning": "රක් පිළිල", "category": "plant" },
  { "word": "තරාමෘක්‍ෂක", "meaning": "ලාබු, (මාලියම්)", "category": "plant" },
  { "word": "තරාමාලිනී", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "තරාප්‍රැප්", "meaning": "මහ නුග, තල්ගස", "category": "plant" },
  { "word": "තරාප්‍රහා", "meaning": "පිළිල", "category": "plant" },
  { "word": "තරාප්‍රරෝහිණී", "meaning": "පිළිල", "category": "plant" },
  { "word": "තරාප්‍රවල්ලි", "meaning": "පිළිල, (ඉටිකෙසෙල්) පතුකා නම් ලතාව", "category": "plant" },
  { "word": "තරාප්‍රවිලාසිනී", "meaning": "සිනිද්ද", "category": "plant" },
  { "word": "තරාසාර", "meaning": "කපුරු, රක්මාලියම්", "category": "plant" },
  { "word": "තරාට", "meaning": "රිපුල් අල", "category": "plant" },
  { "word": "තරාප්‍රරෝදන", "meaning": "කාඩි", "category": "treatment" },
  { "word": "තල්", "meaning": "හල් ගස", "category": "plant" },
  { "word": "තල්කිලන්", "meaning": "තල්කෝඹි = තල්කිරන්, (තල්ගෙඩි පැළ වූ විට මතුවන මොටෙයියන් = අංකුර)", "category": "plant" },
  { "word": "තල්වක්", "meaning": "ඔලිඳ", "category": "plant" },
  { "word": "තල්වාකර", "meaning": "දෙවරක් පෙරා අරක්කු", "category": "treatment" },
  { "word": "තල්වාට", "meaning": "තල්පතින් කළ අවාන (තාලවෘන්තය)", "category": "plant" },
  { "word": "තල", "meaning": "තල්ගස, තෙල", "category": "plant" },
  { "word": "තලගන", "meaning": "තල්ගස", "category": "plant" },
  { "word": "තලගර්දිය සත්‍රීන්ගේ යටිබඩ රෝගයට බෙහෙත්", "meaning": "(තල සාර ජලය)", "category": "treatment" },
  { "word": "තලතාලේ", "meaning": "නීතිග", "category": "plant" },
  { "word": "තලපක්කඩ", "meaning": "තල්ගෙඩිවලට,බෙලි", "category": "plant" },
  { "word": "තලපෝට", "meaning": "දියබෙරලිය, රණවරා", "category": "plant" },
  { "word": "තලමුරුවට තලපුනක්කු", "meaning": "(කලමුරු)", "category": "plant" },
  { "word": "තලග", "meaning": "කලං තුන", "category": "treatment" },
  { "word": "තලවප්පු", "meaning": "ලියනඟලා වැල", "category": "plant" },
  { "word": "තලප්පාලො", "meaning": "පුවක්", "category": "plant" },
  { "word": "තලසුණු", "meaning": "තලමුරුවට හෝ තල වලින් සෑදූ අංගලා", "category": "treatment" },
  { "word": "තලඟ", "meaning": "තලාගස", "category": "plant" },
  { "word": "තලා", "meaning": "ඇසල ගස, සුදු රියන්, තෙල, තලා වගී", "category": "plant" },
  { "word": "තලාටු මිනිරන් වගියක්", "meaning": "(මයිකා)", "category": "treatment" },
  { "word": "තලාවගි එකොළොසකි", "meaning": "සුවඳතලා, කවකලා, කෙහෙතලා, කාටු පැනතලා, අඬුතලා, හෝතලා, එළමල් තලා, තල් මල් තලා, යකින්න තලා, මදුරු තලා, බුලත්තලා", "category": "plant" },
  { "word": "තලාෂ්ට", "meaning": "තලිස්පතුරු", "category": "plant" },
  { "word": "තලිස්පතුරු", "meaning": "එනම් ඔසුව (තාලිශ)", "category": "plant" },
  { "word": "තලුලැසි", "meaning": "මිදි", "category": "plant" },
  { "word": "තවක්‍ෂීර", "meaning": "හුලන්කිරිය ගස, පුවඟු (ප්‍රියඟු)", "category": "plant" },

  // --- පිටුව 213 ---
  { "word": "නවාබිහාල්", "meaning": "හබලපෙති", "category": "treatment" },
  { "word": "නවුඩු", "meaning": "කුඩු", "category": "treatment" },
  { "word": "තස්කර", "meaning": "හිඟුරුපියලි, කුකුරු මුවන්", "category": "plant" },
  { "word": "තස්කරි", "meaning": "හරංකහ, එළ නිදිකුම්බා", "category": "plant" },
  { "word": "තස්තිකා", "meaning": "පැපිලිය, පත්පාඩගම්", "category": "plant" },
  { "word": "තසින", "meaning": "පිපාසය", "category": "symptom" },
  { "word": "තාක්‍ෂ්‍යප්‍රසව", "meaning": "මුරුත ගස", "category": "plant" },
  { "word": "තාක්‍ෂ්‍යශෛල", "meaning": "රසඳුන්, (රසාංජන)", "category": "treatment" },
  { "word": "තාකතනහි", "meaning": "කටරොළු වැල", "category": "plant" },
  { "word": "තාබග", "meaning": "කළු තලා", "category": "plant" },
  { "word": "තාබ", "meaning": "කිතුල් ගස", "category": "plant" },
  { "word": "තාබක", "meaning": "මාබණ්ඩා ඇට (මේ වෙනුවට ලංකාවේ ගන්නේ මාබණ්ඩා ඇට)", "category": "plant" },
  { "word": "තාබකාවල", "meaning": "මහ එන්සාල්", "category": "plant" },
  { "word": "තාබකිව්ල", "meaning": "මහ එන්සාල්", "category": "plant" },
  { "word": "තායි", "meaning": "තල්රු, වෘක්‍ෂවිශේෂයක්", "category": "plant" },
  { "word": "තානකිපු", "meaning": "බාහතී", "category": "plant" },
  { "word": "තාදෙසි", "meaning": "බුළුදම්", "category": "plant" },
  { "word": "තාන්සි", "meaning": "බුළු", "category": "plant" },
  { "word": "තාන්සික්කායි", "meaning": "බුළු ගෙඩි", "category": "plant" },
  { "word": "තාන්තිකා", "meaning": "ගොසඳුන්", "category": "plant" },
  { "word": "තාන්දා", "meaning": "හුනිද වැල", "category": "plant" },
  { "word": "තාන්දුක", "meaning": "හුනිද", "category": "plant" },
  { "word": "තානක", "meaning": "ඔලිඳ", "category": "plant" },
  { "word": "තානුර", "meaning": "ලෝලු ගස", "category": "plant" },
  { "word": "තාපන", "meaning": "වරා ගස", "category": "plant" },
  { "word": "තාපස", "meaning": "කොල්ලම්කොළ, කුකුරු මුවන්, දමනකාරක, මිදි වැල", "category": "plant" },
  { "word": "තාපසජ", "meaning": "කොල්ලම්කොළ", "category": "plant" },
  { "word": "තාපසතරු", "meaning": "අඟුණ කර ගස, බුත් සරණ ගස", "category": "plant" },
  { "word": "තාපසද්‍රැම", "meaning": "වැලහුණ, කතුරැ මුරුංගා", "category": "plant" },
  { "word": "තාපසද්‍රැමසහතිහා", "meaning": "බුත්සරණ ගස", "category": "plant" },
  { "word": "තාපසපත්‍ර", "meaning": "දමනක වෘක්‍ෂය", "category": "plant" },
  { "word": "තාපසප්‍රියා", "meaning": "පියාගස, කිරිපළු, උක් ගස", "category": "plant" },
  { "word": "තාපසප්‍රියා", "meaning": "මුද්‍රිකඵල, මාදුරු, (මහදුරු)", "category": "plant" },
  { "word": "තාපසවෘක්‍ෂ", "meaning": "අඟුණ කර ගස", "category": "plant" },
  { "word": "තාපසා", "meaning": "මිදිවැල්", "category": "plant" },
  { "word": "තාපසි", "meaning": "ජටාමාංශ, මුඛමහණ, වැලහුණ", "category": "plant" },
  { "word": "තාපසෙසක්‍ෂු", "meaning": "උක් වෙසෙසක්", "category": "plant" },
  { "word": "තාපසේෂට", "meaning": "පියල් ගස, මිදිවැල්", "category": "plant" },
  { "word": "තාපිච්ඡ", "meaning": "මසිඳ", "category": "plant" },
  { "word": "තාපිච්ඡ", "meaning": "කොල්ලම්කොළ, (තමල ගස)", "category": "plant" },
  { "word": "තාපිසමුද්භව", "meaning": "මසිඳ", "category": "plant" },
  { "word": "තාප්‍ය", "meaning": "මසිඳ, (මාක්‍ෂික), රසඳුන්", "category": "treatment" },
  { "word": "තාම්බ්‍ර", "meaning": "තඹ", "category": "treatment" },
  { "word": "තාම්බුල්", "meaning": "බුලත්", "category": "plant" },
  { "word": "තාම්බුලපර්ණිකා", "meaning": "බුලත් වැල", "category": "plant" },
  { "word": "තාම්බුලවල්ලි", "meaning": "බුලත් වැල", "category": "plant" },
  { "word": "තාම්බුලි", "meaning": "ආපසුමුදු, බුලත්", "category": "plant" },
  { "word": "තාම්බුලිකා", "meaning": "බුලත් වැල", "category": "plant" },
  { "word": "තාම්බ්‍ර", "meaning": "තඹ, වැල්මදට, කොළවැල්", "category": "plant" },
  { "word": "තාම්ම්‍ර", "meaning": "තඹ, රත්සඳුන්, කුෂ්ට රෝගයක්, සේපාලිකා", "category": "plant" },
  { "word": "තාම්ම්‍රක", "meaning": "රෝගයක්, සේපාලිකා", "category": "symptom" },
  { "word": "තාම්ම්‍රකණ්ටකා", "meaning": "රත්කිහිරිය", "category": "plant" },
  { "word": "තාම්ම්‍රකිට්ට", "meaning": "තඹ සුණු", "category": "treatment" },
  { "word": "තාම්ම්‍රකුට", "meaning": "දුම්කොළ", "category": "plant" },
  { "word": "තාම්ම්‍රගර්භ", "meaning": "තුත්තම්", "category": "treatment" },
  { "word": "තාම්ම්‍රචූඩක", "meaning": "කුකුරුමුවන් වෘක්‍ෂය", "category": "plant" },
  { "word": "තාම්ම්‍රදාම", "meaning": "රත්සඳුන්", "category": "plant" },
  { "word": "තාම්ම්‍රධාතු", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "තාම්ම්‍රපත්‍රී", "meaning": "වලාවැන්න", "category": "plant" },

  // --- පිටුව 214 ---
  { "word": "තාම්ම්‍රපර්ණ", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "තාම්ම්‍රපර්ණී", "meaning": "කොල්ලු, (කලන්) මෑ, කසඹිලියා, වැල්මදට", "category": "plant" },
  { "word": "තාම්ම්‍රපල්ලව", "meaning": "හෝපලු", "category": "plant" },
  { "word": "තාම්ම්‍රපාකින්", "meaning": "තෙලෙඹු ගස", "category": "plant" },
  { "word": "තාම්ම්‍රපාදී", "meaning": "වලාවැන්න, රතු නිදි කුම්බා", "category": "plant" },
  { "word": "තාම්ම්‍රපුෂ්ප", "meaning": "පලොල්, කොබෝ ලීල, මසිල", "category": "plant" },
  { "word": "තාම්ම්‍රපුෂ්පී", "meaning": "රක්තසැවාව, මසිල, නාරන්", "category": "plant" },
  { "word": "තාම්ම්‍රපුෂ්පිකා", "meaning": "වැල් පෙනෙල, ත්‍රස්තාවාලු, මසිල", "category": "plant" },
  { "word": "තාම්ම්‍රමූල", "meaning": "පලොල්, මෝර, ඇම්බරැල්ලා, රුකුගුණ", "category": "plant" },
  { "word": "තාම්ම්‍රහෂ්ම", "meaning": "තඹ දැවූ අළු", "category": "treatment" },
  { "word": "තාම්ම්‍රමුෂ්ටික", "meaning": "දුම්කොළ", "category": "plant" },
  { "word": "තාම්ම්‍රමුලා", "meaning": "වැල්මදට, දුරලනා, කිරිපළු", "category": "plant" },
  { "word": "තාම්ම්‍රලෝහ", "meaning": "තඹ", "category": "treatment" },
  { "word": "තාම්ම්‍රවර්ණ", "meaning": "සිවංගුරු, වද ගස", "category": "plant" },
  { "word": "තාම්ම්‍රවල්ලී", "meaning": "වැල්මදට, බුලත්", "category": "plant" },
  { "word": "තාම්ම්‍රවල්‍යඵල", "meaning": "තොවිල්ල", "category": "plant" },
  { "word": "තාම්ම්‍රවිප්", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "තාම්ම්‍රවෘක්‍ෂ", "meaning": "කොබු, සුළු කුඹුක්, උගුරස්ස, රත්වන් සලන්", "category": "plant" },
  { "word": "තාම්ම්‍රවෘන්තා", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "තාම්ම්‍රවෘන්තිකා", "meaning": "සේපාලිකා", "category": "plant" },
  { "word": "තාම්ම්‍රශාලී", "meaning": "රත්හැල්", "category": "plant" },
  { "word": "තාම්ම්‍රසාර", "meaning": "රත්සඳුන්", "category": "plant" },
  { "word": "තාම්ම්‍රසාරක", "meaning": "කෝන්, කොබු, රත් සඳුන්", "category": "plant" },
  { "word": "තාම්ම්‍රසාරිකා", "meaning": "රත්කිහිරි, රත් සඳුන්", "category": "plant" },
  { "word": "තාම්මු්‍රා", "meaning": "ඔලිඳ, වැල්මදට", "category": "plant" },
  { "word": "තාම්ම්‍රාහ", "meaning": "රත්සඳුන්", "category": "plant" },
  { "word": "තාම්ම්‍රිකා", "meaning": "හුනිද, රත් හුනිද, වැල් මදට", "category": "plant" },
  { "word": "තාම්ම්‍රොපධාතු", "meaning": "තුත්තම්", "category": "treatment" },
  { "word": "තාම්‍රා", "meaning": "දෙල්ම් ගිතෙල්", "category": "treatment" },
  { "word": "තාමරංග", "meaning": "බිලිං", "category": "plant" },
  { "word": "තාමරඅල්ලි", "meaning": "නෙළුම් රේණු", "category": "plant" },
  { "word": "තාමර අල", "meaning": "නෙළුම් අල", "category": "plant" },
  { "word": "තාමරක්ක", "meaning": "රතු ලූණු", "category": "plant" },
  { "word": "තාමරකුෂ්ට", "meaning": "තාම්ම්‍රකුෂ්ටය (රෝගයක්)", "category": "symptom" },
  { "word": "තාමරවිවින්නෛ", "meaning": "නෙළුම් බටවා", "category": "plant" },
  { "word": "තාමරස", "meaning": "නෙළුම්, අත්තන, තඹ, රත්රන්", "category": "plant" },
  { "word": "තාමරිකොට්යෙයි", "meaning": "නෙළුම් ඇට", "category": "plant" },
  { "word": "තාමරෙසි", "meaning": "නෙළුම්", "category": "plant" },
  { "word": "තාමලකී", "meaning": "පිටවක්කා, එළ නෙළුම්", "category": "plant" },
  { "word": "තාමස", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "තාමසී", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "තාළුම", "meaning": "කොල්ලම්කොළ", "category": "plant" },
  { "word": "තාරක්‍ෂ්‍ය", "meaning": "තුත්තම්, සදුන්, මුරුංගා, රසාංජන, සල්", "category": "plant" },
  { "word": "තාරක්‍ෂ්‍යජ", "meaning": "රසඳුන්", "category": "treatment" },
  { "word": "තාරක්‍ෂ්‍යශෛල", "meaning": "රසාංජන", "category": "treatment" },
  { "word": "තාරක්‍ෂ්‍යප්‍රසව", "meaning": "මුරුත ගස", "category": "plant" },
  { "word": "තාරක්‍ෂි", "meaning": "මදුවැල්", "category": "plant" },
  { "word": "තාර", "meaning": "රිදී, ගල් අඟුරු වලින් ගන්නා තෙල්", "category": "treatment" },
  { "word": "තාරක", "meaning": "මීගස, බෝලාපල", "category": "plant" },
  { "word": "තාරකා", "meaning": "දේවතාඩ වෘක්‍ෂය, කැකිරි", "category": "plant" },
  { "word": "තාරකාවෙනී", "meaning": "දේවදාර", "category": "plant" },
  { "word": "තාරාවි", "meaning": "තරවි වෘක්‍ෂය", "category": "plant" },
  { "word": "තාරදී", "meaning": "තරවි වෘක්‍ෂය", "category": "plant" },
  { "word": "තාරපුෂ්ප", "meaning": "කොඳ", "category": "plant" },
  { "word": "තාරිකා", "meaning": "කළුවා", "category": "plant" },
  { "word": "තාරැහී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තාරැවී", "meaning": "සැබෝ", "category": "plant" },

  // --- පිටුව 215 ---
  { "word": "තාලපර්ණී", "meaning": "සතකුප්ප (ශත පුෂ්ප)", "category": "plant" },
  { "word": "තාල", "meaning": "තල්ගස, හිරියල්, රටතෝර, තලිස්පතුරු", "category": "plant" },
  { "word": "තාලක්‍ෂීරක", "meaning": "තල් හකුරු", "category": "treatment" },
  { "word": "තාලක", "meaning": "හිරියල්, රටතෝර", "category": "plant" },
  { "word": "තාලකන්ද", "meaning": "බිමිතල්", "category": "plant" },
  { "word": "තාලකරිර්", "meaning": "තල්බඩය", "category": "plant" },
  { "word": "තාලකා", "meaning": "දේවදාලිය, උඩහල්ලා හෝ උඩහල් නම් වැල් වර්ගය (පබාවල් යයි ද කියති)", "category": "plant" },
  { "word": "තාලකාපලු", "meaning": "මහ එන්සාල්", "category": "plant" },
  { "word": "තාලකි", "meaning": "කලරැ", "category": "plant" },
  { "word": "තාලගභී", "meaning": "තල් මද", "category": "plant" },
  { "word": "තාලතරැ", "meaning": "තල් ගස", "category": "plant" },
  { "word": "තාලපත්‍ර", "meaning": "උළුවාහාල්", "category": "plant" },
  { "word": "තාලපත්‍රා", "meaning": "බිමිතල්, වල්සාතාවාරිය", "category": "plant" },
  { "word": "තාලපත්‍රී", "meaning": "මකුවැන්න, ගොඩු කොළ", "category": "plant" },
  { "word": "තාලපත්‍රිකා", "meaning": "බිමිතල්, ඌරල, වල් සාතාවාරිය", "category": "plant" },
  { "word": "තාලපර්ණී", "meaning": "බිමිතල්, සතකුප්ප, මහ සාතාවාරිය", "category": "plant" },
  { "word": "තාලප්ඵල", "meaning": "තල්ගෙඩි", "category": "plant" },
  { "word": "තාලමස්සු", "meaning": "වැටකේ මල්", "category": "plant" },
  { "word": "තාලමූලි", "meaning": "නවතාළිලිය, (පිටවක්කා) බිමිතල්, තල", "category": "plant" },
  { "word": "තාලමූලිකා", "meaning": "බිමිතල් අල, ඌරල", "category": "plant" },
  { "word": "තාලාංකුර", "meaning": "මනෝසිල, තල්පැලය", "category": "plant" },
  { "word": "තාලි", "meaning": "පිටවක්කා, තැල්ල", "category": "plant" },
  { "word": "තාලිකා", "meaning": "තලිස්පතුරු", "category": "plant" },
  { "word": "තාලිස", "meaning": "තලිස්පතුරු, බිමිතල්", "category": "plant" },
  { "word": "තාලිසපත්‍රී", "meaning": "තලිස්පතුරු", "category": "plant" },
  { "word": "තාලිසපත්‍ර", "meaning": "පිටවක්කා, තලිස් පතුරු", "category": "plant" },
  { "word": "තාලිසපත්‍රක", "meaning": "තලිස්පතුරු", "category": "plant" },
  { "word": "තාලිතල", "meaning": "බිමිතල්", "category": "plant" },
  { "word": "තාලිපත්‍ර", "meaning": "තලිස්පතුරු", "category": "plant" },
  { "word": "තාලිශ(ක)", "meaning": "තලිස්පතුරු, පිටවක්කා", "category": "plant" },
  { "word": "තාලුපුපුට", "meaning": "මුඛ රෝගයක්", "category": "symptom" },
  { "word": "තාලෛ", "meaning": "වැටකේ", "category": "plant" },
  { "word": "තාවරී", "meaning": "කරල්සැබ", "category": "plant" },
  { "word": "තාසුන", "meaning": "සල්ගස", "category": "plant" },
  { "word": "තැක්", "meaning": "කිරිමෝරු", "category": "treatment" },
  { "word": "තැම්බේරිය", "meaning": "කාම්මේරිය ගස", "category": "plant" },
  {
    "word": "තැඹිලි",
    "meaning": "ලෙල්ල ඇතුළ සහ පිට රන්වන් පාට පොල් වගිය රන් තැඹිලි නමි. මෙය දුර්ලභයි. මේ වෙනුවට ලෙල්ල ඇතුළ පැත්ත තඹපාට සහ පිට පැත්ත නිල්පාට තඹුතෙල් හෝ තඹුතිල් නමැති පොල් වගිය ගනිති. එය වැරදියි. රත් තැඹිලි සහ ගොන් (ලා කහ) තැඹිලි දෙවර්ගය රටේ සුලභයි.",
    "category": "plant"
  },
  { "word": "තැල්කොල්", "meaning": "තැල් වගියේ කොළ", "category": "plant" },
  { "word": "තැල්වැල්", "meaning": "තික්තහල්, රසතැල්, වසතැල්, ලප්තැල් යයි තැල් වගී සතරකි. හඟුලු යනු ද තැල් වලට යෙදෙන අපර නාම යකි.", "category": "plant" },
  { "word": "තැලි තෙල්", "meaning": "තැඟිලි තෙල්", "category": "treatment" },
  { "word": "තෑස්", "meaning": "ධාන්‍ය කුඩු", "category": "treatment" },
  { "word": "තික්තරි", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "තික්ත", "meaning": "බිංකොහොඹ, පැපිලිය, කෙළිඳ, හොර (සරල) දුම්මැල්ල, ලුණුවරණ, අඟුණ කර ගස", "category": "plant" },
  { "word": "තික්තක", "meaning": "බිංකොහොඹ, දුම්මැල්ල, රුකුගුණ, කටුකරෝෂණ, යක්බේරිය, කළුකිහිරි, තික්ත ලබු", "category": "plant" },

  // --- පිටුව 216 ---
  { "word": "තික්තකකෝශාතකී", "meaning": "තික්ත කැකිරි", "category": "plant" },
  { "word": "තික්තකරෝහිණී", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "තික්තකා", "meaning": "බූරැල්ල ගස, කුඹුරුවැල", "category": "plant" },
  { "word": "තික්තකාණ්ඩ", "meaning": "බිංකොහොඹ", "category": "plant" },
  { "word": "තික්තකුමිනි", "meaning": "තික්තලබු", "category": "plant" },
  { "word": "තික්තගන්ධ", "meaning": "මස්බැද්ද, මැඩහඟු, හෙළ අබ, නිදිකුම්බා", "category": "plant" },
  { "word": "තික්තගන්ධිකා", "meaning": "හෙළ අබ, නිදිකුම්බා", "category": "plant" },
  { "word": "තික්තගුස්පා", "meaning": "මස්බැද්ද, කරඳ", "category": "plant" },
  { "word": "තික්තතණ්ඩූලා", "meaning": "නිප්පිලි", "category": "plant" },
  { "word": "තික්තදුග්ධා", "meaning": "ගොකටු, වරා, රත් කිරි ගොකටු, කිරිපළු", "category": "plant" },
  { "word": "තික්තපත්‍ර", "meaning": "වැලහුණ, කවුඩුතැන්න (කවුඩුකැකිරි)", "category": "plant" },
  { "word": "තික්තපත්‍රිකා", "meaning": "ලබුතන්න, කවුඩු උඩැත්තා", "category": "plant" },
  { "word": "තික්තපර්ණී", "meaning": "රසකිඳ, වැල්මී", "category": "plant" },
  { "word": "තික්තපුෂ්පා", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "තික්තඵල", "meaning": "යක්බේරිය, ඉඟිනි, නෙල්ලි", "category": "plant" },
  { "word": "තික්තඵලා", "meaning": "හණ, උලබඩැ, කොමඩු", "category": "plant" },
  { "word": "තික්තබීජ", "meaning": "තික්ත ලබු", "category": "plant" },
  { "word": "තික්තානදුක", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "තික්තමර්පං", "meaning": "වැල්අඟුණ, කිරිඅඟුණ", "category": "plant" },
  { "word": "තික්තමරීච", "meaning": "ඉඟිනි ගස", "category": "plant" },
  { "word": "තික්තරසා", "meaning": "බැමිනිරිය", "category": "plant" },
  { "word": "තික්තරෝහිණී", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "තික්තලෝහිනිකා", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "තික්තලා", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "තික්තවර", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "තික්තවල්ලක", "meaning": "මස්බැද්ද, (වෙලිප්පරිත්ති)", "category": "plant" },
  { "word": "තික්තවල්ලි", "meaning": "මුරුවා, (මුරුවා දුල්)", "category": "plant" },
  { "word": "තික්තවාර්තාකු", "meaning": "තිත්තතිබිබොටු", "category": "plant" },
  { "word": "තික්තවීජා", "meaning": "තිත්ත ලබු", "category": "plant" },
  { "word": "තික්තශාඛ", "meaning": "ලුණුවරණ, කිහිරි", "category": "plant" },
  { "word": "තික්තශාලූක", "meaning": "ලුණුවරණ", "category": "plant" },
  { "word": "තික්තශිඛි", "meaning": "වච්චනාවි, නෙරි විෂ", "category": "plant" },
  { "word": "තික්තසාර", "meaning": "කිහිරි, කිහිරි අරටු, (තික්තසාර)", "category": "plant" },
  { "word": "තික්තා", "meaning": "මැඩහඟු, තියඹරා, මහගොන්සුතුකැකිරි, මුරුවා, වෙල්මුබ, (මුඩමහණ) කිඳි, රසකිඳ, බේරු, තෙල්බේරු, පික්මැලි, දියමින්ත, තිත්තලබු, කටුකරෝෂණ, උඩැත්ත", "category": "plant" },
  { "word": "තික්තාඛ්‍යා", "meaning": "තික්තලබු", "category": "plant" },
  { "word": "තික්තාඬා", "meaning": "මුදුරුබාල", "category": "plant" },
  { "word": "තික්තාමෘතා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "තික්තාලාබු", "meaning": "තික්තලබු", "category": "plant" },
  { "word": "තික්තාහ්වයා", "meaning": "තික්ත ලබු", "category": "plant" },
  { "word": "තික්ති", "meaning": "වැලහුණ, තික්ත අඟුණ", "category": "plant" },
  { "word": "තික්තිකා", "meaning": "තිත්තලබු", "category": "plant" },
  { "word": "තික්තිරිප්ල", "meaning": "ජයපාල", "category": "plant" },
  { "word": "තික්තෝත්තමා", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "තික්මෛරද", "meaning": "වරාගස", "category": "plant" },
  { "word": "තික්ෂීරී", "meaning": "ඉකිරි, (තිරමුල්ලිය)", "category": "plant" },
  { "word": "තිකට", "meaning": "ගොකටු", "category": "plant" },
  { "word": "තිකටු", "meaning": "ගොකටු", "category": "plant" },
  { "word": "තිකණ්ටක", "meaning": "ගොකටු, (නෙරෙවි)", "category": "plant" },
  { "word": "තිකිච්ඡා", "meaning": "පිළියම, ප්‍රතිකෘරය", "category": "treatment" },
  { "word": "තිකුළු", "meaning": "ඉඟුරු, මිරිස්, තිප්පිලි", "category": "plant" },
  { "word": "තිගද", "meaning": "සඳුන්, කපුරු, සුවඳ අගිල්", "category": "plant" },
  { "word": "තිගන්ධ", "meaning": "වදමල්", "category": "plant" },
  { "word": "තිංඟුද", "meaning": "තොවිල ගස, ත්‍රස්තාවාලු", "category": "plant" },
  { "word": "තිච්ඡා", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "තිජනයා", "meaning": "මුරුවා, (මුරුවා දුල්)", "category": "plant" },
  { "word": "තිජප්‍රමෝදනී", "meaning": "හෙළ බටු", "category": "plant" },
  { "word": "තිතිග", "meaning": "කෙමි-(කොමක්කා)බලුදම්ගස", "category": "plant" },

  // --- පිටුව 217 ---
  { "word": "තින්තිඩී", "meaning": "ලොත්ගස, තිරස්සවාලු, තොවිල", "category": "plant" },
  { "word": "තින්තිඩීක", "meaning": "ලොත්ගස", "category": "plant" },
  { "word": "තිත්තකොෂාතකී", "meaning": "තිත්ත වැටකොළු", "category": "plant" },
  {
    "word": "තිත්තවැල්",
    "meaning": "මේ ගෙඩි කෑමට කවුඩෝ ඉතා ප්‍රිය බවක් දක්වති. ඒ නිසා හෝ නැතහොත් කාල වර්ණයෙන් යුක්ත නිසා හෝ මේ වගියට කාකඵලා යන සංස්කෘත නාමය යෙදුනා විය හැක. මේ වැල් වැට-කඩුලු බැඳීම සඳහා ගනිති. මත්වන සුළු ගතියකින් යුත් මේ වැල් විෂ බීජ නාශක ඖෂධයකි. සමේ හටගන්නා හොරි, දද, කුෂ්ට, කඩුවෙගන් ආදී චර්ම රෝග වලට මේ වැල් සහ තිත්ත සමදරා පොතුත් අමු කහ සමග ගෙන එකට තම්බා සේදීමෙන් සුවය ලබා ගත හැක.",
    "category": "plant"
  },
  { "word": "තිත්තා", "meaning": "කෝවක්කා", "category": "plant" },
  { "word": "තිත්තක", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "තිත්තනාක", "meaning": "ලුණුවරණ", "category": "plant" },
  { "word": "තිත්තිණිකා", "meaning": "ඇඹුල්වේ (ගොරක හෝ ඇඹුලඇඹිලිය) සියඹලා", "category": "plant" },
  { "word": "තිත්තිප්පු", "meaning": "කුමීරිදේයි- පත්තක්කා, කොමඩු", "category": "plant" },
  { "word": "තිත්තිපෙනේසි", "meaning": "කිතුල්", "category": "plant" },
  { "word": "තිත්තිරිප්ල", "meaning": "ජයපාල", "category": "plant" },
  { "word": "තිත්තුක", "meaning": "ඉඟුරු, මිරිස්, තිප්පිලි-අරළු, බුළු, නෙල්ලි- එන්සාල්, කුරුඳු පොතු, කොල්ලම් කොළ", "category": "plant" },
  { "word": "තිප්පිලි", "meaning": "කඩුමිරිස් (මෙහි අග කොටස සහ සම්පූර්ණ විස්තරය ඊළඟ පිටු වල ඇත.)", "category": "plant" },
  { "word": "තිප්පවටු", "meaning": "තිත්තවටු පිනාටු", "category": "plant" },
  { "word": "තිපත්‍ර", "meaning": "වලාවැන්න", "category": "plant" },
  { "word": "තිපද", "meaning": "කොලොම් ගස", "category": "plant" },
  { "word": "තිපදිකා", "meaning": "වලාවැන්න", "category": "plant" },
  { "word": "තිපල්", "meaning": "අරළු, බුළු, නෙල්ලි යන ත්‍රිවර්ගය", "category": "plant" },
  { "word": "තිපු", "meaning": "සුදු රියම්", "category": "plant" },
  { "word": "තිපුට", "meaning": "ගොකටු, ත්‍රස්තාවාලු, කපු කිනිස්ස", "category": "plant" },
  { "word": "තිපුටී", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "තිපුටීඵල", "meaning": "එරබු", "category": "plant" },

  // --- පිටුව 218 & 219 (තිප්පිලි විස්තරය සම්පූර්ණ කිරීම) ---
  { "word": "තින්දුක", "meaning": "තිඹිරි, කවුඩුතිඹිරි", "category": "plant" },
  { "word": "තින්දුකයා", "meaning": "කලන් තුණ", "category": "treatment" },
  { "word": "තින්දුකාකාන්ත", "meaning": "ඵල- යොන් ඉඳි ගස", "category": "plant" },
  { "word": "තින්දුකාහප්ල", "meaning": "යොන් ඉඳි ගස (රට ඉඳි ගස)", "category": "plant" },
  { "word": "තින්දුකි", "meaning": "තිඹිරි ගස", "category": "plant" },
  { "word": "තින්දුප්", "meaning": "ලොත් ගස", "category": "plant" },
  { "word": "තින්දුල", "meaning": "තිඹිරි ගස", "category": "plant" },
  { "word": "තින්තිච්චිපච්ච", "meaning": "(තින්තිච්චිපච්ච) මදුරැතලා වැනි තලා විශේෂයක්", "category": "plant" },
  { "word": "තිනසි", "meaning": "තණකොළ", "category": "plant" },
  { "word": "තිනරද", "meaning": "තල්ගස", "category": "plant" },
  { "word": "තිනසුලස", "meaning": "බෝලිද්ද වැල", "category": "plant" },
  { "word": "තිනාසක", "meaning": "කොටු ගස", "category": "plant" },
  { "word": "තිනිස", "meaning": "කෝන්, කොබු", "category": "plant" },
  { "word": "තිනෙහිරිසි", "meaning": "තණහාල්", "category": "plant" },
  {
    "word": "තිප්පිලි",
    "meaning": "වගපුල්. පෙර-අපර දෙදිග ම මානව සමාජයට ඇතිවන රෝගා බාධ සඳහා දෛනික ඖෂධයක් වශයෙන් ප්‍රයෝජනවත් පැළෑටියකි තිප්පිලි. දේශීය වෙදකමේ ප්‍රතිශ්‍යා උණ-කාස-පීනස-ඇදුම-ක්‍ෂය ආම-අතිසාර ආදී හැම ආබාධයකට ම ගන්නා ඖෂධ යෝගවලට තිප්පිලි ද එකතු වේ යි. තිප්පිලි (වගපුල්) ගප්තිප්පිලි (ඇත්වගපුල්) යයි තිප්පිලි වගී දෙකකි. කුඩා වගීයට තිප්පිලි කියා ද, ලොකු වගීයට ගප්තිප්පිලි කියා ද කියති. මෙයින් ඖෂධ සඳහා වැඩිපුර ගන්නේ ප්‍රමාණයෙන් කුඩාවුව ද ගුණයෙන් අධික (සිහින්) තිප්පිලි ය. අපට තිප්පිලි කරල් වැඩිපුර ලැබෙන්නේ ඉන්දියාවේ දකුණු බිහාර් (බිහාර) ජනපදයෙන් ය. වර්තමාන බිහාරය පැරණි මගධ දේශයට අයත් ය. පුරාකාලයෙහිත් මගධ දේශයෙහි තිප්පිලි සුලභව වැවුන බැවී තිප්පිලි වලට පාලි-සංස්කෘතභාෂා දෙකින් ම මාගධී යන නාමය ව්‍යවහාර වීමෙන් හැඟේ. තිප්පිලි වැවීම: මගධ දේශයෙහි පමණක් නොව නිතර වතුරට යටවන ගංගා දෙපස පිහිටි ඕකඳ වල ත්, දිය සිරාව ඇති වැලි සහිත හැම ඉඩමක ත් තිප්පිලි මනාව වැවේ. අතිත් අල-බතල ඇතුළු භෝගජාති මෙන් තිප්පිලි වැල් නිතර වතුරෙන් යටවුනාට දකුණුවීමක් නැත. එම නිසා වෙන කිසිවක් වවන්ට බැරි කමෙන් අපතේ යන වතුරුවන්වල ත් ඕකඳ වල ත් තිප්පිලි වැවීම කළ හැක. ගංගා දෙපස රබර් වවා තිබෙන ඕවිටි වල ත් රබර් මුල් වෙලීම අඩු කිරීම සඳහා වවන කිසිම පලක් නැති වැල් ජාති වෙනුවට තිප්පිලි වැවීමෙන් අමතර ආදායමකු ත් ගත හැක. තිප්පිලි කරල් මෙන් ම මුල් සහ තිප්පිලි වැල් සහමුලයෙන් ම ත් අපේ වෙදකමට නිතර ම පාහේ වුවමනා වෙයි. පිටරටින් එන තිප්පිලි රාත්තලකට රුපියල් හතරේ සිට දහය දක්වා අපට ගෙවන්නට සිදුවී තිබේ. එම නිසා රබර්වතුවල කිරි වැඩිවී ම සඳහා අමතර වැවීමක් වශයෙන් ත් වෙන කිසිවක් වවන්ට බැරි නිසා අපතේ ගොස් තිබෙන ඕකඳ-වතුරුවන් වැනි ඉඩම් වල ත් තිප්පිලි වැවීම කළහොත් අවුරුදු පතා පිටරට ඇදී යන විශාල ධනයක් මෙහි රඳවා ගත හැක.",
    "category": "plant"
  },

  // --- පිටුව 219 ---
  { "word": "නිපුසා", "meaning": "තියඹරා", "category": "plant" },
  { "word": "තිඹැඬිස", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "තිඹුකස්", "meaning": "තිඹිරි", "category": "plant" },
  { "word": "තිඹුගස්", "meaning": "තිඹිරි", "category": "plant" },
  { "word": "තිඹුරා", "meaning": "තිඹිරි", "category": "plant" },
  { "word": "තිම්බරි", "meaning": "තිඹිරි, තිත්දුක", "category": "plant" },
  { "word": "තිම්බුති", "meaning": "ගඟුව, කිරිහඟුව", "category": "plant" },
  { "word": "තිමුර", "meaning": "මරිතොණ්ඩු, නෙත්‍රරෝගයක්", "category": "symptom" },
  { "word": "තිම්රා", "meaning": "කහ", "category": "plant" },
  { "word": "තිමිස", "meaning": "කෝන්, පුසුල්, පත්තක්කා, කැකිරි", "category": "plant" },
  { "word": "තිමීරක", "meaning": "මරිතොණ්ඩු ගස", "category": "plant" },
  { "word": "තිමුව", "meaning": "ප්‍රබාවෝ (කුඹල්ලෝ)", "category": "plant" },
  { "word": "තිඹ-පලම්", "meaning": "256, ලාස් 4", "category": "treatment" },
  { "word": "තිඹිරි", "meaning": "තිඹිරි ගස", "category": "plant" },
  { "word": "තිඹිරිගෙය", "meaning": "ගර්භිණී චිකිත්සාගාරය", "category": "treatment" },
  { "word": "තිබොල්", "meaning": "වැල් වගියක්", "category": "plant" },
  { "word": "තියඹු", "meaning": "කහ", "category": "plant" },
  { "word": "තියඹුපුෂ්ප", "meaning": "පියාගස", "category": "plant" },
  { "word": "තිරකා", "meaning": "නික, හෙළ නික", "category": "plant" },
  { "word": "තිරජ්ජීවිකා", "meaning": "එරබදු ගස", "category": "plant" },
  { "word": "තිරස්ක", "meaning": "කොකුම්", "category": "plant" },
  { "word": "තිරිඟ", "meaning": "ගස් වර්ගයක්", "category": "plant" },
  { "word": "තිරිම(අ)", "meaning": "ඇල්වෙසෙසක්", "category": "plant" },
  { "word": "තිරිමරාඩු", "meaning": "මුරුත", "category": "plant" },
  { "word": "තිරිල", "meaning": "තෝවැල්ල", "category": "plant" },
  { "word": "තිරිව", "meaning": "ලොත්, හෙළ ලොත්", "category": "plant" },
  { "word": "තිරිවක", "meaning": "තෙලගස", "category": "plant" },
  { "word": "තිරිඟිකණ්ට", "meaning": "එරබදු ගස", "category": "plant" },
  { "word": "තිරුකෝණෙයි", "meaning": "ඇසල, එරහැඳි", "category": "plant" },
  { "word": "තිරුවාන්නි", "meaning": "පෙතන්", "category": "plant" },
  { "word": "තිල්ල", "meaning": "තෙලකිරිය, තෙලගස, දිය මිදෙල්ල", "category": "plant" },
  { "word": "තිල්ලක", "meaning": "හෙළ ලොත්, වැලිමාන්න", "category": "plant" },
  { "word": "තිල්ල(ල්ව)ක", "meaning": "ලොත්, අඟුණකර ගස, මරාවක ගස", "category": "plant" },

  // --- පිටුව 220 ---
  { "word": "තිල්ලමරම්", "meaning": "තෙලකිරිය ගස්", "category": "plant" },
  { "word": "තිල්ව", "meaning": "ලොත්, තෙලකිරිය, තෙල ගස", "category": "plant" },
  { "word": "තිල්වක", "meaning": "හෙළ ලොත්, තෙලකිරිය, තෙලගස", "category": "plant" },
  { "word": "තිල්වකතරැ", "meaning": "ලොත් ගස", "category": "plant" },
  { "word": "තිල", "meaning": "තල, මදටිය", "category": "plant" },
  { "word": "තිලක්කඩම්බු", "meaning": "බිම්බක්මී", "category": "plant" },
  { "word": "තිලක", "meaning": "තල, තලගස, තෙලකිරිය, කටු දුණු, බෝලිද්ද, මාරා, මද ටිය, හෙළ ලොත්", "category": "plant" },
  { "word": "තිලකට", "meaning": "තලචුණ්ණීය, තලමල්රේණු", "category": "plant" },
  { "word": "තිලකණී", "meaning": "(එළ තල) එළ කරණ ලද තල", "category": "plant" },
  { "word": "තිලකබ", "meaning": "බෝලිද්ද", "category": "plant" },
  { "word": "තිලකල්ක", "meaning": "තලමුරුවට (තලපුන්නක්කු)", "category": "plant" },
  { "word": "තිලකා", "meaning": "සාතාවාරිය, තලතෙල්", "category": "plant" },
  { "word": "තිලකායනෙල්ලි", "meaning": "පිටවක්කා", "category": "plant" },
  { "word": "තිලකිච්ච", "meaning": "හලමුරුවට", "category": "plant" },
  { "word": "තිලබලි", "meaning": "හලමුරුවට", "category": "plant" },
  { "word": "තිලවර්ණ", "meaning": "සුදු සඳුන්", "category": "plant" },
  { "word": "තිලවුණී", "meaning": "හලපිජි, තලමුරුවට", "category": "plant" },
  { "word": "තිලප්", "meaning": "තලතෙල්", "category": "plant" },
  { "word": "තිලපර්ණා", "meaning": "තල මුල්", "category": "plant" },
  { "word": "තිලපා", "meaning": "තල් වෙසෙසක්", "category": "plant" },
  { "word": "තිලපණ්ඩුක", "meaning": "තලසහල් (එළ කළ තල)", "category": "plant" },
  { "word": "තිලතෙල", "meaning": "තල තෙල්", "category": "treatment" },
  { "word": "තිලපත්‍ර", "meaning": "කවනලා", "category": "plant" },
  { "word": "තිලපනො", "meaning": "ඌරල", "category": "plant" },
  { "word": "තිලපර්ණී", "meaning": "සඳුන්, සුදු සඳුන්, රත් සඳුන්, සිරිවඩු", "category": "plant" },
  { "word": "තිලපර්ණිකා", "meaning": "රත් සඳුන්, අයමෝදගම්", "category": "plant" },
  { "word": "තිලපිඤ්ජ", "meaning": "වඳ, තලා, තලමුරුවට", "category": "plant" },
  { "word": "තිලපුෂ්ප", "meaning": "තල මල්", "category": "plant" },
  { "word": "තිලපුෂ්පක", "meaning": "බූව ගස", "category": "plant" },
  { "word": "තිලපෙප්", "meaning": "තිලපිඤ්ජ", "category": "plant" },
  { "word": "තිලබිප්", "meaning": "බෝල්තලා", "category": "plant" },
  { "word": "තිලභව", "meaning": "කටුකරෝෂණ", "category": "plant" },
  { "word": "තිලභාවිනී", "meaning": "දෑසමන් ගස", "category": "plant" },
  { "word": "තිලභේද", "meaning": "අබින් ගස", "category": "plant" },
  { "word": "තිලභේදක", "meaning": "කටුකරෝෂිණී", "category": "plant" },
  { "word": "තිලමී", "meaning": "තල්මල්, තල්මද", "category": "plant" },
  { "word": "තිලමියා", "meaning": "කළුනික", "category": "plant" },
  { "word": "තිලමිල", "meaning": "හලමුරුවට", "category": "plant" },
  { "word": "තිලශිෂ්‍ය", "meaning": "මිරිඟුව, මුරුංගා", "category": "plant" },
  { "word": "තිලස්නේහ", "meaning": "තලතෙල්", "category": "treatment" },
  { "word": "තිලසම්භව", "meaning": "තලතෙල්", "category": "treatment" },
  { "word": "තිලාපත්‍ය", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "තිලෝකා", "meaning": "තිප්පිලි", "category": "plant" },
  { "word": "තිලෝගුරු", "meaning": "බෝ ගස (රහස් බෙත් වට්ටෝරුවක එන වචනයක්)", "category": "plant" },
  { "word": "තිලෝදක", "meaning": "හලමුසු දිය", "category": "treatment" },
  { "word": "තිලෛ", "meaning": "තෙල් ගස", "category": "plant" },
  { "word": "තිවග කුළුරඟ", "meaning": "කරාබු = වසාවාසි, සාදික්කා යන තුන් වගය", "category": "plant" },
  { "word": "තිවිද්‍රැඩි", "meaning": "වාත රෝග 80, පිත් රෝග 40, සෙම්රෝග 20", "category": "symptom" },
  { "word": "තිවිස", "meaning": "අතිවිඩයන්", "category": "plant" },
  { "word": "තිවුත්", "meaning": "ත්‍රස්තාවාලු", "category": "plant" },
  { "word": "තිවුතා", "meaning": "ත්‍රස්තාවාලු", "category": "plant" },
  { "word": "තිශය", "meaning": "නෙල්ලි, පියාගස", "category": "plant" },
  { "word": "තිශයළු", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "තිශාබපත්‍ර", "meaning": "ලී", "category": "plant" },
  { "word": "තිෂ්‍යපුෂ්පා / තිෂ්‍යඵලා / තිෂ්‍යා", "meaning": "නෙල්ලි", "category": "plant" },
  { "word": "තිසර පෙරළිය", "meaning": "වලාවැන්න යයි ගනිමි (විමසත්වා)", "category": "plant" },
  { "word": "තිසුගන්ධි", "meaning": "එන්සාල්, කොල්ලම් කොළ, කුරුඳු යන සුවඳ වර්ග තුන", "category": "plant" },
  { "word": "තිහන්", "meaning": "සහල්, වී, වසාදිය", "category": "plant" }
];