// data_450_458.js - පිටු 450 සිට 460 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 262
const data_extra_450_458 = [
    // --- පිටුව 450 ---
    { "word": "වෛරී", "meaning": "ඵල", "category": "plant" },
    { "word": "වෛරා", "meaning": "මුල්", "category": "plant" },
    { "word": "වෛලාවගීතුන", "meaning": "සුදුමල් වේලා, ලා රත්මල් වේලා, රන්වන් පාට මල් (රන්මානිස්ස) වේලා ය යි වගී තුනකි. මෙයින් මල් සුදු සහ රන්වන් මල් ඇති දෙවගය පමණක් ඖෂධ සඳහා ගනිති.", "category": "plant" },
    { "word": "වෛලිප්පරිත්ති", "meaning": "මැඩහඟු, සුදුරියම්", "category": "plant" },
    { "word": "වෛව", "meaning": "උණගස", "category": "plant" },
    { "word": "වෛවැල්", "meaning": "වේත්‍ර ලතා = (මාවේවැල්, කම්බටුවැල්, (තුඬරුණ) ඇල වේවැල්, කුකුළු (කුඩා) වේවැල් ය යි වේවැල් සතර වගියකි)", "category": "plant" },
    { "word": "වෛක්‍රබකත", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "වෛකුණ්ඨ", "meaning": "අදුතලා, ගැටතුඹ", "category": "plant" },
    { "word": "වෛගන්ධ", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "වෛජයන්ත", "meaning": "මිදි ගස", "category": "plant" },
    { "word": "වෛජයන්ති", "meaning": "ඇටිකෙසෙල්", "category": "plant" },
    { "word": "වෛජයන්තිකා", "meaning": "සින් මිදි ගස, නිතිග", "category": "plant" },
    { "word": "වෛඩූර්‍ය්‍ය", "meaning": "වෙරළුමිණි", "category": "mineral" },
    { "word": "වෛතස", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "වෛද්‍ය", "meaning": "වංඇපල, කවෙළු", "category": "plant" },
    { "word": "වෛද්‍යබන්‍ධු", "meaning": "ඇසළ ගස", "category": "plant" },
    { "word": "වෛද්‍යමාතා", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වෛද්‍යසිංහි", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වෛද්‍යු", "meaning": "කවෙළු", "category": "plant" },
    { "word": "වෛදර්භකෙශිකා", "meaning": "සුදු", "category": "general" },
    { "word": "වෛදල", "meaning": "මුං ආදි පියලි", "category": "plant" },
    { "word": "වෛද්‍රැසති", "meaning": "වෛරෝඩි", "category": "mineral" },
    { "word": "වෛදෙනික", "meaning": "බාවදම්", "category": "plant" },
    { "word": "වෛදෙනි", "meaning": "නිප්පිලි, ඇල්කසඹිලියා, කහ", "category": "plant" },
    { "word": "වෛනවී", "meaning": "උණකපුරු", "category": "plant" },
    { "word": "වෛරමී", "meaning": "විදුරු", "category": "plant" },
    { "word": "වෛරාවෘක්‍ෂ", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "වෛරෝපි", "meaning": "මහ ජම්බු", "category": "plant" },
    { "word": "වෛරාන්තක", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "වෛල්ව", "meaning": "බෙලි ගෙඩිය", "category": "plant" },
    { "word": "වෛශ්වානර", "meaning": "ගින්දර, බදුල්ල, රත් නිටුල්, කටුකරෝහිණී,", "category": "plant" },
    { "word": "වෛශ්‍රවනවාස", "meaning": "නුගගස", "category": "plant" },
    { "word": "වෛශාඛ", "meaning": "සුළු සාරණ", "category": "plant" },
    { "word": "වොත්කාරං", "meaning": "පුස්කර", "category": "plant" },
    { "word": "වොන්නෙ", "meaning": "වෙබරු", "category": "plant" },
    { "word": "වොට", "meaning": "ඔටුවන්", "category": "animal" },
    { "word": "වොර", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "වොල", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "වොෂ", "meaning": "ගෙන්දගම්, ගොඩ මිරිස්", "category": "plant" },
    { "word": "වොස", "meaning": "ආබාතෝඩා", "category": "plant" },
    { "word": "ව්‍යොක්ත ගන්‍ධා", "meaning": "නිල් කටුකරඬු, හෝපළු", "category": "plant" },
    { "word": "ව්‍යඞග", "meaning": "වඳුරුමෑ", "category": "plant" },
    { "word": "ව්‍යඞම්බක", "meaning": "එරබු ගස", "category": "plant" },
    { "word": "ව්‍යඞම්බර", "meaning": "එළ එරබු ගස", "category": "plant" },
    { "word": "ව්‍යතිවාර", "meaning": "මැණික්වැන්න", "category": "plant" },
    { "word": "ව්‍යථා", "meaning": "බැමිතිරිය, අරළු", "category": "plant" },
    { "word": "ව්‍යථාන්තක", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ව්‍යදිඝාත", "meaning": "වරණගස", "category": "plant" },
    { "word": "ව්‍යභිචාරිකසත්‍යා", "meaning": "වාලුඟුන්", "category": "plant" },
    { "word": "ව්‍යවාසි", "meaning": "සකල ශරීරයේ වහා පැතිර යන අබ, කංසා වැනි විෂ වගී", "category": "plant" },

    // --- පිටුව 451 ---
    { "word": "ව්‍යාකෝද", "meaning": "වෑකෝද", "category": "plant" },
    { "word": "ව්‍යාඝ්‍ර", "meaning": "එරබු, රත්එරබු, කරඳ", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රකර / ව්‍යාඝ්‍රතර", "meaning": "රත්එරබු", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රතල", "meaning": "දිවිපහුරු, පසුරුතලා, දළුක්", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රදතී", "meaning": "බින්තල්", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රදල", "meaning": "එරබු, රත්නිටුල්", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රනඛ", "meaning": "දිවිපහුරු, වක්නිය", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රපද", "meaning": "කිහිරි", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රපර්ණිකා", "meaning": "හෙළ එරබු", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රපාද", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රපාද සමාවෘක්‍ෂ", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රපුෂ්පී", "meaning": "එරබු", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රබල", "meaning": "රත්එරබු", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රාදතී", "meaning": "ත්‍රස්තාවළු වැල", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රී", "meaning": "බටු, කටුවැල්බටු, වක්නිය", "category": "plant" },
    { "word": "ව්‍යාඝ්‍රොක්", "meaning": "එරබු", "category": "plant" },
    { "word": "ව්‍යාඩම්බක", "meaning": "එරබු", "category": "plant" },
    { "word": "ව්‍යාඩායුධ", "meaning": "දිවිපහුරු, වක්නිය", "category": "plant" },
    { "word": "ව්‍යාඩායුධ (2)", "meaning": "වක්නිය", "category": "plant" },
    { "word": "ව්‍යාධි", "meaning": "කොට්ටම්", "category": "treatment" },
    { "word": "ව්‍යාධිඝෝෂටක", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "ව්‍යාධිඝාත", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ව්‍යාධිනාස", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ව්‍යාධිඝාතු", "meaning": "බින්තල්", "category": "plant" },
    { "word": "ව්‍යාධි (2)", "meaning": "කොට්ටම්, ලෙඩ, උපුල් කොළ", "category": "plant" },
    { "word": "ව්‍යාපාෂ", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "ව්‍යාල", "meaning": "රත්නිටුල්, එළ නිටුල්", "category": "plant" },
    { "word": "ව්‍යාලගන්‍ධා", "meaning": "කවෙළු", "category": "plant" },
    { "word": "ව්‍යාලජිහ්වා", "meaning": "මහ වැල්මදට", "category": "plant" },
    { "word": "ව්‍යාලදංෂ්ට්‍රා", "meaning": "ගොකටු", "category": "plant" },
    { "word": "ව්‍යාලපත්‍රා", "meaning": "කැකිරි", "category": "plant" },
    { "word": "ව්‍යාලපුහරණ", "meaning": "වක්නිය", "category": "plant" },
    { "word": "ව්‍යාලම්බ", "meaning": "රත් එරබු", "category": "plant" },
    { "word": "ව්‍යාලායුධ", "meaning": "වක්නිය", "category": "plant" },
    { "word": "ව්‍යාවායො", "meaning": "මෛථුනය", "category": "general" },
    { "word": "ව්‍යොෂපකුල්‍යා", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "ව්‍යොෂග", "meaning": "ඉඟුරු, මිරිස්, නිප්පිලි, සිද්ධිගුරු, (තිකුළු)", "category": "plant" },
    { "word": "වෘක", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වෘක්‍ෂකා", "meaning": "කළුතලා", "category": "plant" },
    { "word": "වෘක්‍ෂකාරක", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "වෘක්‍ෂාන්ත", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "වෘණස්නි", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "වෘණදවිත්", "meaning": "සිරිත්කේකු", "category": "plant" },
    { "word": "වෘණහ", "meaning": "එරබු, රසකිඳ", "category": "plant" },
    { "word": "වෘණාග", "meaning": "ගෙන්දගම්, නුග ගස", "category": "plant" },
    { "word": "වෘණෙපිතා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වෘබත", "meaning": "මුල", "category": "anatomy" },
    { "word": "වෘතී", "meaning": "රුක් මල", "category": "plant" },
    { "word": "වෘෂණ්‍යා", "meaning": "මීනුග", "category": "plant" },
    { "word": "වෘෂගද", "meaning": "රන්වන් වේලා, (රම්මානිස්ස)", "category": "plant" },
    { "word": "වෘෂබ", "meaning": "ඔසබිය, ගොන් කැකිරි", "category": "plant" },
    { "word": "වෘෂබ (2)", "meaning": "ගොන් කැකිරි", "category": "plant" },
    { "word": "වෘෂබල", "meaning": "විලිකුත් සියඹලා", "category": "plant" },
    { "word": "වෘසාවජී", "meaning": "එඬරු", "category": "plant" },
    { "word": "ව්‍රීඩා", "meaning": "හොර ගස", "category": "plant" },
    { "word": "ව්‍රීහිකාඤ්චන", "meaning": "ත්‍රස්තාවළු", "category": "plant" },
    { "word": "ව්‍රීහී", "meaning": "වී", "category": "plant" },

    // --- පිටුව 452 ---
    { "word": "ශංවර", "meaning": "වතුර, කහ", "category": "liquid" },
    { "word": "ශංවරී", "meaning": "මීනුග, මකුණුවැන්න, සාතාවාරිය", "category": "plant" },
    { "word": "ශකාත්", "meaning": "අසූචි, මල", "category": "anatomy" },
    { "word": "ශකාධාර", "meaning": "මල මාරය, අපානස්ථානය", "category": "anatomy" },
    { "word": "ශක්නව", "meaning": "අන්සුණු", "category": "plant" },
    { "word": "ශක්ත්‍යා", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "ශක්තිබන්", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ශක්තිපත්‍ර", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ශක්තිපර්ණී", "meaning": "රුක් අත්තන", "category": "plant" },
    { "word": "ශක්නි පර්ණීව", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ශක්තු", "meaning": "බැඳි හාල් ආදී සුණු, අන් සුණු", "category": "food" },
    { "word": "ශක්තු ඵල", "meaning": "ලෝලු, සැම ගස", "category": "plant" },
    { "word": "ශක්තු ඵල (ලී)", "meaning": "සැම ගස", "category": "plant" },
    { "word": "ශක්‍ර", "meaning": "කෙළින්ද ගස", "category": "plant" },
    { "word": "ශක්‍රදාරු", "meaning": "දේවදාර", "category": "plant" },
    { "word": "ශක්‍රද්‍රැම", "meaning": "දේවදාර", "category": "plant" },
    { "word": "ශක්‍රපර්‍ය්‍යාය", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "ශක්‍රපාදක", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "ශක්‍රපාදප", "meaning": "කෙළින්ද ගස, දේවදාර", "category": "plant" },
    { "word": "ශක්‍රපුෂ්ප", "meaning": "මලිත ගස", "category": "plant" },
    { "word": "ශක්‍ර පුෂ්පී", "meaning": "නිටුල් ගස, ලියනඟලා", "category": "plant" },
    { "word": "ශක්‍රනු භවා", "meaning": "කැකිරි", "category": "plant" },
    { "word": "ශක්‍රනු රාග", "meaning": "කෙළින්ද", "category": "plant" },
    { "word": "ශක්‍ර ලොබු", "meaning": "සබර ලොත්", "category": "plant" },
    { "word": "ශක්‍රවර්ණී", "meaning": "කළුතලා", "category": "plant" },
    { "word": "ශක්‍රවල්ලි", "meaning": "කැකිරි වැල", "category": "plant" },
    { "word": "ශක්‍ර විප්", "meaning": "කෙළින්ද ඇට", "category": "plant" },
    { "word": "ශක්‍ර වෘක්‍ෂ", "meaning": "කෙළින්ද ගස", "category": "plant" },
    { "word": "ශක්‍ර ශාඛින්", "meaning": "කෙළින්ද ගස", "category": "plant" },
    { "word": "ශක්‍රසුධා", "meaning": "පාලංගා", "category": "plant" },
    { "word": "ශක්‍රසෘෂ්ටා", "meaning": "අරළු", "category": "plant" },
    { "word": "ශක්‍රාශන", "meaning": "කන්සා, කෙළින්ද ගස", "category": "plant" },
    { "word": "ශක්‍රාහ්වය", "meaning": "කෙළින්ද", "category": "plant" },
    { "word": "ශක්‍රාහ්වා", "meaning": "කෙළින්ද", "category": "plant" },
    { "word": "ශකල", "meaning": "පොතු, කුරුළු පොතු", "category": "plant" },
    { "word": "ශකලින්", "meaning": "මත්ස්‍යයා", "category": "animal" },
    { "word": "ශකාක්‍ෂ", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "ශකුලාක්‍ෂී", "meaning": "එළ රතණ, ගබරතණ", "category": "plant" },
    { "word": "ශකුලාදනී", "meaning": "පටාමාංශ, දියතිප්පිලි, කටිප්ල", "category": "plant" },
    { "word": "ශඛත", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "ශඛරාවාස", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශඛරාහ්වය", "meaning": "සැමගස", "category": "plant" },
    { "word": "ශඛකර්ණිකා", "meaning": "හරංකසා", "category": "plant" },
    { "word": "ශඛ්‍ය", "meaning": "ලිඟුව, වක්නිය, අඬුව", "category": "anatomy" },
    { "word": "ශඛකුතරා", "meaning": "සල් ගස", "category": "plant" },
    { "word": "ශඛකුළු", "meaning": "සැමගස", "category": "plant" },
    { "word": "ශඛකුලා", "meaning": "පුවක් කපන ගිරේ, මහ නෙල් කොළ", "category": "plant" },
    { "word": "ශඛ", "meaning": "සක, වැල්දෙහි, ඇත්සාටිය, සුදු පාෂාණම්", "category": "mineral" },
    { "word": "ශඛ කුසුම", "meaning": "අඩතහිරියා", "category": "plant" },
    { "word": "ශඛද්‍රාවින්", "meaning": "ඇඹුල් වේ", "category": "plant" },
    { "word": "ශඛනඛ", "meaning": "කුඩා සක, සක්නැබ", "category": "animal" },
    { "word": "ශඛනාභි", "meaning": "සක් නැබ = සක් බෙලි කටුවෙහි නැබ (මැද පෙදෙස=මැද පුරුක) මේ වෙනුවට සමීපුෂ්පී සක් බෙලි කටුව ම ගන්නා නමුත් එය හරි නැත)", "category": "animal" },
    { "word": "ශඛනාමිණී", "meaning": "හඬන හිරියා", "category": "plant" },
    { "word": "ශඛපුෂ්පී", "meaning": "සක් මල්", "category": "plant" },
    { "word": "ශඛවාත", "meaning": "ශිඛි රෝගයක්", "category": "treatment" },
    { "word": "ශඛාහ්වා", "meaning": "අඩතහිරියා, වැල්දෙහි, ඇත්සාටිය", "category": "plant" },
    { "word": "ශඛිනී", "meaning": "කටුකරෝහිණී, යක්බේරිය, අඩතහිරියා, සක්මල්, වැල්දෙහි, සුදු ඇඹුලාගිලිය", "category": "plant" },

    // --- පිටුව 453 ---
    { "word": "ශඛිනී ඵල", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ශඛිනී වාස", "meaning": "ගැට නෙටුල්", "category": "plant" },
    { "word": "ශඛී", "meaning": "වක්නිය", "category": "anatomy" },
    { "word": "ශට", "meaning": "කාසි, මූණමල් ගස, අත්තන", "category": "plant" },
    { "word": "ශටී", "meaning": "ඇඹුලාගිලිය, හිඟුරු පියලි", "category": "plant" },
    { "word": "ශඨ", "meaning": "අත්තන", "category": "plant" },
    { "word": "ශඨද්‍රැම", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "ශඩ", "meaning": "සමූහය, ලෙඩ", "category": "treatment" },
    { "word": "ශණකණටකා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "ශණපත්‍ර", "meaning": "සුදු නෙළුම්", "category": "plant" },
    { "word": "ශණපුෂ්පී", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "ශණවර්ණිකා", "meaning": "යක් බේරිය", "category": "plant" },
    { "word": "ශණා", "meaning": "හණ", "category": "plant" },
    { "word": "ශණාලූකා", "meaning": "ඇසළ ගස", "category": "plant" },
    { "word": "ශණිකා", "meaning": "හණ මල්", "category": "plant" },
    { "word": "ශතග්‍රන්ථි", "meaning": "රතණ", "category": "plant" },
    { "word": "ශතඝනී", "meaning": "ඇත්සාටිය, කරඳ", "category": "plant" },
    { "word": "ශතදන්තීකා", "meaning": "මහගොන් කැකිරි", "category": "plant" },
    { "word": "ශතපත්‍ර", "meaning": "සුදු නෙළුම්", "category": "plant" },
    { "word": "ශතපත්‍රිකා", "meaning": "ශතපුෂ්ප, සාතාවාරිය, මාදුරු, (මහ දුරු)", "category": "plant" },
    { "word": "ශතපත්‍රී", "meaning": "ශතපුෂ්ප, සාතාවාරිය", "category": "plant" },
    { "word": "ශතපදීම", "meaning": "හෙළ නෙළුම්", "category": "plant" },
    { "word": "ශතපදී", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "ශතපර්වී", "meaning": "උණ ගස", "category": "plant" },
    { "word": "ශතපස්", "meaning": "වදකහ, රතණ, කටු කරෝහිණී, උණගස", "category": "plant" },
    { "word": "ශතපාමා", "meaning": "හෙළ වද", "category": "plant" },
    { "word": "ශතපර්විකා", "meaning": "රතණ, වදකසා", "category": "plant" },
    { "word": "ශතපා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "ශතපාදිකා", "meaning": "කවෙළු", "category": "plant" },
    { "word": "ශතපුෂ්පක", "meaning": "රත් කණේරු", "category": "plant" },
    { 
        "word": "ශතපුෂ්ප", 
        "scientific": "Peucedanum Graveolens",
        "meaning": "Peucedanum Graveolens-ශත කුප්ප. ගස පුරාම සිය ගණන් පුබුදු වූ මල් වලින් පිරී වැසි යන මහ දුරු ගස වැනි මේ පැලෑටියට දෙමළෙන් කියන සතකුප්ප යන නාමය ම සිංහලයන් අතර ද ව්‍යවහාර වේ. මෙය වායු කෝප නසවත් කිරීමට කුළු බඩු වශයෙන් හා ඖෂධ වශයෙනුත් ඉන්දියාවේ යොදන නමුත් ලංකාවේ වැඩි වශයෙන් යොදන්නේ ඖෂධයක් වශයෙන් පමණකි.\n\nමේ වගිය සූතිකා රුධිරය හා සූතිකා වේදනාව පහ කිරීමට ත්, දරුවන් ලැබීමෙන් පසු මහත් වන ගර්භ කෝෂය පිඬු කිරීම (හැකිලීම) ට ත් ඖෂධයක් වශයෙන් පාවිච්චි කරති.", 
        "category": "plant",
        "image": "img_9dbaab_shatapushpa.jpg"
    },
    { "word": "ශතපුස්‍යා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "ශතප්‍රාස", "meaning": "අලරිය (කණේරු)", "category": "plant" },
    { "word": "ශතභීරු", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "ශතමූල", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "ශතමූලී", "meaning": "රතණ, සාතාවාරිය", "category": "plant" },

    // --- පිටුව 454 ---
    { "word": "ශතවීර‍්‍යා", "meaning": "එළ රතණ", "category": "plant" },
    { "word": "ශතවෙධින්", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "ශතවෙධී", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "ශතවේ‍යාෂ", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "ශතඝ්‍යඝ්‍රාංසි", "meaning": "මොර ගස", "category": "plant" },
    { "word": "ශතසුතා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "ශතා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "ශතාක්‍ෂී", "meaning": "රතණ, ශතපුෂ්ප", "category": "plant" },
    { "word": "ශතාඞග", "meaning": "කොන් ගස", "category": "plant" },
    { "word": "ශතාවරී", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "ශතාහ්වා", "meaning": "ශතපුෂ්ප, සාතාවාරිය", "category": "plant" },
    { "word": "ශතෙකා", "meaning": "ඇම්බරැල්ල", "category": "plant" },
    { "word": "ශතකාවලි", "meaning": "ගප් නිප්පිලි, සිවිය කරල්", "category": "plant" },
    { "word": "ශතපර්ණී", "meaning": "බෙරු", "category": "plant" },
    { "word": "ශපර්විකා", "meaning": "හෙළ රතණ", "category": "plant" },
    { "word": "ශළු", "meaning": "ගවයින්ගේ කුරය, සක්නැබ, ගස මුල", "category": "general" },
    { "word": "ශබිදබොධන", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "ශබිදිකා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "ශමපාක", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ශමබර", "meaning": "රත් නිටුල්, ලොත්, කුඹුක්", "category": "plant" },
    { "word": "ශමබරකඳ", "meaning": "බින්තල් අල", "category": "plant" },
    { "word": "ශමබරි", "meaning": "මකුණුවැන්න, මීනුග, සාතාවාරිය", "category": "plant" },
    { "word": "ශම්බා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "ශම්බුකා", "meaning": "බෙල්ලෝ", "category": "animal" },
    { "word": "ශමනු", "meaning": "කොබලිල", "category": "plant" },
    { "word": "ශමනුප්‍රියා", "meaning": "නෙල්ලි, රතණ", "category": "plant" },
    { "word": "ශමනුවල්ලභ", "meaning": "නෙළුම් මල", "category": "plant" },
    { "word": "ශම්වර", "meaning": "වතුර", "category": "liquid" },
    { "word": "ශම්වරී", "meaning": "මීනුග", "category": "plant" },
    { "word": "ශම්‍යා", "meaning": "රතණ", "category": "plant" },
    { "word": "ශම්‍යාක", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ශමී", "meaning": "සැමගස, ලෝලු", "category": "plant" },
    { "word": "ශමීගහී", "meaning": "ගිතණ", "category": "plant" },
    { "word": "ශම්බදානය", "meaning": "තෝර, මෑ, මුං ආදි ධාන්‍ය", "category": "plant" },
    { "word": "ශම්පත්‍රී", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "ශමීර", "meaning": "වාතය, කටුවැල්බටු", "category": "plant" },
    { "word": "ශම්යිකා", "meaning": "සියඹලා", "category": "plant" },
    { "word": "ශර්කරක", "meaning": "මිහිරි පැණිදෙබොම්", "category": "plant" },
    { "word": "ශර්කර පා", "meaning": "ගල් කණ්ඩු", "category": "food" },
    { "word": "ශර්කරා", "meaning": "සීනි", "category": "food" },
    { "word": "ශර්වරී", "meaning": "රාත්‍රිය, කහ", "category": "plant" },
    { "word": "ශර්ප", "meaning": "සල් ගස, හල් දුම්මල", "category": "plant" },
    { "word": "ශර්පාක්‍ෂී", "meaning": "දත්කැටියා ගස", "category": "plant" },
    { "word": "ශර", "meaning": "බට ගස, යකඩ", "category": "plant" },
    { "word": "ශරට", "meaning": "වනුක්", "category": "plant" },
    { "word": "ශරණී", "meaning": "සපුමුදු", "category": "plant" },
    { "word": "ශරත්පද්මී", "meaning": "හෙළ නෙළුම්", "category": "plant" },
    { "word": "ශරත්පුෂ්පී", "meaning": "බදුවද", "category": "plant" },
    { "word": "ශරද", "meaning": "මහ ඉරමුසු", "category": "plant" },
    { "word": "ශරපුඛා", "meaning": "පිල ගස", "category": "plant" },
    { "word": "ශරල", "meaning": "හොර ගස", "category": "plant" },
    { "word": "ශරාව", "meaning": "නැඹිලිය, පෑස, බඳුන", "category": "general" },
    { "word": "ශල්ක", "meaning": "ගස, පොතු", "category": "plant" },
    { "word": "ශල්මලි", "meaning": "ඉඹුල්, කටුඉඹුල් ගස", "category": "plant" },
    { "word": "ශල්‍යක", "meaning": "තොටිල", "category": "plant" },
    { "word": "ශල්‍යකඳව", "meaning": "තුරුක් තෙල්", "category": "mineral" },
    { "word": "ශල්‍යකී", "meaning": "ඉන්සළු ගස", "category": "plant" },
    { "word": "ශල්‍යප", "meaning": "කිහිරි, කුකුරුමාන්, බෙලි", "category": "plant" },
    { "word": "ශල්‍යයක", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "ශල්‍යපර්ණී", "meaning": "මේවන්", "category": "plant" },
    { "word": "ශල්‍යාක", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "ශල්‍යාකා", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "ශලාවු", "meaning": "බෙලි ගස, අමු ගෙඩි", "category": "plant" },
    { "word": "ශලිල", "meaning": "වතුර", "category": "liquid" },
    { "word": "ශශබර", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශශභෘද්", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශශල්‍ය", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "ශශගිම්බිකා", "meaning": "බුලත්", "category": "plant" },
    { "word": "ශශාඞ්ක", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශශාඞ්ක ලෙඛා", "meaning": "බෝදි ඇට", "category": "plant" },


// සම්පූර්ණ වචන සංඛ්‍යාව: 238
    // --- පිටුව 455 ---
    { "word": "ශශී", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශශිකාන්තා", "meaning": "වඩුකාන්තා", "category": "plant" },
    { "word": "ශශින්", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශශිපර්ණී", "meaning": "පුවඟු", "category": "plant" },
    { "word": "ශශිප්‍රභා", "meaning": "රත්මහනෙල්, සුදුනෙළුම්", "category": "plant" },
    { "word": "ශශිප්‍රිය", "meaning": "රත් මහනෙල්, නිල් මහ නෙල්, ඇඹුල", "category": "plant" },
    { "word": "ශශිලෙඛා", "meaning": "රසකිඳ, බෝදි ඇට", "category": "plant" },
    { "word": "ශශිවාටිකා", "meaning": "සාරණ", "category": "plant" },
    { "word": "ශශිවාලුකා", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශස්‍ය සංවරණ", "meaning": "මුරුත ගස", "category": "plant" },
    { "word": "ශස්‍ය සම්බර", "meaning": "ලෝලු, සල් ගස", "category": "plant" },
    { "word": "ශස්‍යාරා", "meaning": "සුළු සැමගස", "category": "plant" },
    { "word": "ශෂ්ටිකා", "meaning": "වී, (ධාන්‍ය)", "category": "plant" },
    { "word": "ශස්‍යනු", "meaning": "වාතේ", "category": "treatment" },
    { "word": "ශස්‍යත්‍රක", "meaning": "යකඩ", "category": "mineral" },
    { "word": "ශස්‍යනකොෂතර", "meaning": "මහකුකුරුමුවන්", "category": "plant" },
    { "word": "ශස්‍යනවාක්‍ෂ", "meaning": "වෑලුහුණ", "category": "plant" },
    { "word": "ශස්‍යනහසන", "meaning": "සල්ගස", "category": "plant" },
    { "word": "ශස්‍ය", "meaning": "ලාක්‍ෂණකොළ", "category": "plant" },
    { "word": "ශස්‍යවෙල්ලී", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "ශස්‍යවෙධින්", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "ශාක්‍ය", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "ශාක", "meaning": "කොළ මල් ආදි වෘක්‍ෂප්‍රභේද, අතු, අරළුගස, මාරාගස", "category": "plant" },
    { "word": "ශාකචුල්ලිකා", "meaning": "සියඹලා", "category": "plant" },
    { "word": "ශාකජ", "meaning": "මහරි", "category": "plant" },
    { "word": "ශාකප්ඵල", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "ශාකට", "meaning": "ලෝලුගස, දෑවගස", "category": "plant" },
    { "word": "ශාකපත්‍ර", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "ශාකබාලෙය", "meaning": "රසකිඳවැල", "category": "plant" },
    { "word": "ශාකයොග්‍ය", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "ශාකරාජ", "meaning": "කූරතම්පලා", "category": "plant" },
    { "word": "ශාකවාස්තුක", "meaning": "නිල්තම්පලා", "category": "plant" },
    { "word": "ශාකවිල්ව", "meaning": "බටුගස", "category": "plant" },
    { "word": "ශාකවීර", "meaning": "කූරතම්පලා", "category": "plant" },
    { "word": "ශාකශ්‍රෙෂ්ඨ", "meaning": "කූරතම්පලා, කිරි පලා, බටු", "category": "plant" },
    { "word": "ශාකා", "meaning": "අරළු", "category": "plant" },
    { "word": "ශාකාඞග", "meaning": "මිරිස්", "category": "plant" },
    { "word": "ශාකාම්ල", "meaning": "සියඹලා", "category": "plant" },
    { "word": "ශාකාම්ලභෙදන", "meaning": "සියඹලා", "category": "plant" },
    { "word": "ශාකාලාබු", "meaning": "ලබු ප්‍රභේද", "category": "plant" },
    { "word": "ශාකිනී", "meaning": "කූරතම්පලා", "category": "plant" },
    { "word": "ශාඛ", "meaning": "වැල, අතු", "category": "plant" },
    { "word": "ශාඛමාරා", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "ශාඛවරා", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "ශාඛවාක්‍ෂ", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "ශාඛවාක්‍ෂක", "meaning": "සල්ගස", "category": "plant" },
    { "word": "ශාඛශ්‍රෙෂ්ඨ", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "ශාඛාකණිස", "meaning": "දළුක්, සිනුක්", "category": "plant" },
    { "word": "ශාඛාඞගපුෂ්ප", "meaning": "මාරාගස", "category": "plant" },
    { "word": "ශාඛාම්ලා", "meaning": "සියඹලා", "category": "plant" },
    { "word": "ශාබාල", "meaning": "වේවැල්", "category": "plant" },
    { "word": "ශාබාශිතා", "meaning": "අතුවල මුල්", "category": "plant" },
    { "word": "ශාබිණී", "meaning": "කූරතම්පලා, අලකිරිය", "category": "plant" },
    { "word": "ශාබින්", "meaning": "ගස", "category": "plant" },
    { "word": "ශාඛි", "meaning": "ගස, කුඩාගස", "category": "plant" },
    { "word": "ශාබොට", "meaning": "ගැටනිටුල්", "category": "plant" },
    { "word": "ශාඛාශ්‍රිතා", "meaning": "එනිද, (ඔලිඳ)", "category": "plant" },
    { "word": "ශාතක", "meaning": "වස්තුක", "category": "plant" },
    { "word": "ශාණඩවපර්ණී", "meaning": "පොණඩරු", "category": "plant" },
    { "word": "ශාණඩිල්‍ය", "meaning": "බෙලිගස, අත්තන", "category": "plant" },
    { "word": "ශාතකුම්භ", "meaning": "රත්රන්, අත්තන", "category": "plant" },
    { "word": "ශාතකොම්භ", "meaning": "කණේරු, රත්රන්, අත්තන", "category": "plant" },
    { "word": "ශාතන", "meaning": "තුනිකිරීම, විනාසය", "category": "general" },
    { "word": "ශාතහිරු", "meaning": "ඉද්ද විශේෂයක්", "category": "plant" },
    { "word": "ශාතලා", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "ශාද්වලා", "meaning": "රතණ, එළ රතණ", "category": "plant" },
    { "word": "ශාද", "meaning": "මඩ, බැලතණ", "category": "plant" },

    // --- පිටුව 456 ---
    { "word": "ශානි", "meaning": "කැකිරි", "category": "plant" },
    { "word": "ශාමබුක", "meaning": "සක්", "category": "animal" },
    { "word": "ශාමවලිපත්‍රක", "meaning": "රක්අත්තන", "category": "plant" },
    { "word": "ශාමර", "meaning": "ලොත්, වඳුරු මෑ", "category": "plant" },
    { "word": "ශාමල", "meaning": "බෝගස, බෙලි", "category": "plant" },
    { "word": "ශාමවාස්තුක", "meaning": "නිල්තම්පලා", "category": "plant" },
    { "word": "ශාර්කර", "meaning": "සීනි,කිරෙන් නැගි පෙණ", "category": "food" },
    { "word": "ශාර්බග", "meaning": "අමුඉඟුරු", "category": "plant" },
    { "word": "ශාර්බගෂ්ටා", "meaning": "හඟුළු, තැල්වැල්", "category": "plant" },
    { "word": "ශාර", "meaning": "කපුරු පාහාය", "category": "plant" },
    { "word": "ශාරබග", "meaning": "කැදැත්තා මුවා, ඇතා, මීමැස්සා, මොණරා", "category": "animal" },
    { "word": "ශාරද", "meaning": "සුදු පියුම්, උක්ගස, මුනමල් ගස, රන්වන් මුං", "category": "plant" },
    { "word": "ශාරදි", "meaning": "ඉරමුසු, මුණුවිල", "category": "plant" },
    { "word": "ශාරදික", "meaning": "සරත් කාලයෙහි හටගන්නා රෝගය", "category": "treatment" },
    { "word": "ශාරදින්", "meaning": "රක්අත්තන, මුණුවිල", "category": "plant" },
    { "word": "ශාරදී", "meaning": "ලියනඟලා, රක්අත්තන", "category": "plant" },
    { "word": "ශාරිබා", "meaning": "හිරමුසු", "category": "plant" },
    { 
        "word": "ශාරිබාදිගණය", 
        "meaning": "හිරමුසු, පද්මක, සුවඳහොට, මීපුප්, හෙළ-රත් හඳුන් දෙවර්ගය, ඇත්දෙමට, වැල්මී යන මේ ශාරිබාදි ගණය රත් පිත්, පිපාස, තියුණු පිත් උණ, වමනය හා මහත් දාවිල්ල ද නසන්නේ ය.", 
        "category": "compound" 
    },
    { "word": "ශාරිවා", "meaning": "ඉරමුසු", "category": "plant" },
    { "word": "ශාල්මලි", "meaning": "ඉඹුල් ගස", "category": "plant" },
    { "word": "ශාල්මලිකා", "meaning": "ඉඹුල්", "category": "plant" },
    { "word": "ශාල්මලිරස", "meaning": "ඉඹුල්ලාටු", "category": "plant" },
    { "word": "ශාල්මලිවෙෂ්ට", "meaning": "ඉඹුල්ලාටු", "category": "plant" },
    { "word": "ශාල", "meaning": "සල්ගස, ගස, මීඅඹ ගස", "category": "plant" },
    { "word": "ශාලප්", "meaning": "දුම්මල, (හල්දුම්මල)", "category": "mineral" },
    { "word": "ශාලඤ්ච", "meaning": "මුගුණුවැන්න", "category": "plant" },
    { "word": "ශාලද්‍රැම", "meaning": "සල්ගස", "category": "plant" },
    { "word": "ශාලනිර‍්‍යාස", "meaning": "දුම්මල (හල්දුම්මල)", "category": "mineral" },
    { "word": "ශාලපර්ණී", "meaning": "සල්වැන්න, (සල්වැන්න ගැන ඉදිරියෙහි ලියා ඇති ඡායාරූප සහිත විස්තරය බලන්න)", "category": "plant" },
    { "word": "ශාලවෙෂ්ට", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "ශාලසාර", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "ශාලාබු", "meaning": "බෙලි", "category": "plant" },
    { "word": "ශාලානි", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "ශාලාව", "meaning": "ලොත්", "category": "plant" },
    { "word": "ශාලාවෘක", "meaning": "බල්ලා, සිවලා, බළලා මුවා, වඳුරා", "category": "animal" },
    { "word": "ශාලි", "meaning": "සැට දෑ හැල් ආදි ධාන්‍ය", "category": "plant" },
    { "word": "ශාලිකා", "meaning": "කිරිබදු, ශාලිපර්ණී", "category": "plant" },
    { "word": "ශාලිනි", "meaning": "ශාලිපර්ණී", "category": "plant" },
    { "word": "ශාලි", "meaning": "ඇල්වී, උළුවා, කළුදුරු", "category": "plant" },
    { "word": "ශාලිත", "meaning": "නෙළුඹුල, උළුවා", "category": "plant" },
    { "word": "ශාලූ", "meaning": "නෙළුඹුල, කසට ද්‍රව්‍යය, හිඟුරුපියලි", "category": "plant" },
    { "word": "ශාලූක", "meaning": "නෙළුඹුල, රතැබුල මුල්, සාදික්කා", "category": "plant" },
    { "word": "ශාලෙය", "meaning": "ශතපුෂ්ප, පැපිලිය", "category": "plant" },
    { "word": "ශාවර", "meaning": "ලොත්, හෙළ ලොත්", "category": "plant" },
    { "word": "ශාවරී", "meaning": "වඳුරු මෑ, ලොත් සුඹුළු", "category": "plant" },
    { "word": "ශිංගපා", "meaning": "ඇටිවේරිය ගස", "category": "plant" },
    { "word": "ශික්තක", "meaning": "මී ඉටි", "category": "animal" },
    { "word": "ශික්ථ", "meaning": "මී ඉටි, මී වද", "category": "animal" },
    { "word": "ශිඛ(ඛා)ණ්ඩ", "meaning": "මොණර පිල්, මිණිරත්", "category": "mineral" },
    { "word": "ශිඛණ්ඩිකා", "meaning": "ඔලිඳ, බෝලිද්ද", "category": "plant" },
    { "word": "ශිඛණ්ඩින්", "meaning": "හුනිද, බෝලිද්ද", "category": "plant" },
    { "word": "ශිඛර", "meaning": "මුදුන, කරාබුනැටි, කුන්දුරුක්කන්", "category": "plant" },
    { "word": "ශිඛරිකා", "meaning": "පිප්පිලි", "category": "plant" },

    // --- පිටුව 457 ---
    { "word": "ශිඛරින්", "meaning": "පිප්පිලි, සැබෝ, කුන්දුරුක්කන්, යව, තල, ගෙන්දගම්, සිනිද්ද", "category": "plant" },
    { "word": "ශිඛරී", "meaning": "මීනුග, දේවදාලි, සැබෝ", "category": "plant" },
    { "word": "ශිඛාග්‍ර", "meaning": "හිස් මුදුන", "category": "anatomy" },
    { "word": "ශිඛානන්ද", "meaning": "රතුළූනු", "category": "plant" },
    { "word": "ශිඛාමූල", "meaning": "රතුළූනු", "category": "plant" },
    { "word": "ශිඛාලු", "meaning": "මොණරකුඩුම්බිය, (දුටු සතුටු)", "category": "plant" },
    { "word": "ශිඛාවත්", "meaning": "රත්නිටුල් ගස", "category": "plant" },
    { "word": "ශිඛාවර", "meaning": "කොස් ගස", "category": "plant" },
    { "word": "ශිඛාවල", "meaning": "මොණරකුඩුම්බිය", "category": "plant" },
    { "word": "ශිඛාවාන්", "meaning": "හෙළ නිටුල්", "category": "plant" },
    { "word": "ශිඛී", "meaning": "හෙළ නිටුල්", "category": "plant" },
    { "word": "ශිඛීන්", "meaning": "උළුවා, රත්නිටුල්, මොණර කුඩුම්බිය, එල්ලොම්", "category": "plant" },
    { "word": "ශිඛිකණ්ඨ", "meaning": "මයුරතුතු, පල්මාණික්කම්", "category": "plant" },
    { "word": "ශිඛිග්‍රීව", "meaning": "මයුරතුතු", "category": "plant" },
    { "word": "ශිඛිප්‍රිය", "meaning": "සින්බෙබර", "category": "plant" },
    { "word": "ශිඛිමණ්ඩල", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "ශිඛිමන්ජ", "meaning": "කින්හිරි", "category": "plant" },
    { "word": "ශිඛිමොද", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "ශිඛිවර්ධක", "meaning": "කොමඩු පුහුල්", "category": "plant" },
    { "word": "ශිග්‍රැ", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "ශිග්‍රැක", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "ශිග්‍රැකා", "meaning": "රතු මුරුංගා", "category": "plant" },
    { "word": "ශිඝ්‍රාණ", "meaning": "ලෝකඩ පාත්‍රය, ශ්ලේෂ්මාව, යකඩමල, හොටු", "category": "mineral" },
    { "word": "ශිතක", "meaning": "සීනි", "category": "food" },
    { "word": "ශිත", "meaning": "රත්මහනෙල්, හල්මද, තකුල්", "category": "plant" },
    { "word": "ශිතල", "meaning": "කැකිරි", "category": "plant" },
    { "word": "ශිතශූක", "meaning": "යව", "category": "plant" },
    { "word": "ශිතා", "meaning": "කටුවැල්බටු, අතිවුඩයන්, උණකපුරු", "category": "plant" },
    { "word": "ශිතාක", "meaning": "සීනි", "category": "food" },
    { "word": "ශිතානත", "meaning": "බෙලි", "category": "plant" },
    { "word": "ශිතාභ්‍ර", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශිතාෂිකා", "meaning": "අදුතලා", "category": "plant" },
    { "word": "ශිතිසාරකා", "meaning": "නිඹිරි", "category": "plant" },
    { "word": "ශිතොපල", "meaning": "සීනි", "category": "food" },
    { "word": "ශිනි", "meaning": "කරගස, බූර්පත්", "category": "plant" },
    { "word": "ශිඵ", "meaning": "ගස්වල ජටා වැනි මුල්", "category": "plant" },
    { "word": "ශිඵාක", "meaning": "නෙළුම් මුල්", "category": "plant" },
    { "word": "ශිඵාකන්ද", "meaning": "නෙළුම් මුල්", "category": "plant" },
    { "word": "ශිඵාරුහ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "ශිම්‍යා", "meaning": "මුවාන්ත", "category": "plant" },
    { "word": "ශිම්බිපර්ණී", "meaning": "මුවාන්ත", "category": "plant" },
    { "word": "ශිම්බිජ", "meaning": "කොල්ලු", "category": "plant" },
    { "word": "ශිර", "meaning": "නිප්පිලි මුල්, ඉස්මුදුන, හෙළ බටු", "category": "plant" },
    { "word": "ශිරඃකපාල", "meaning": "ඉස්කබල", "category": "anatomy" },
    { "word": "ශිරඃකම්ප", "meaning": "ඉස වෙව්ලීම", "category": "treatment" },
    { "word": "ශිරඃඵල", "meaning": "පොල්ගස", "category": "plant" },
    { "word": "ශිරඃශුල", "meaning": "ඉස රදය", "category": "treatment" },
    { "word": "ශිරා", "meaning": "නහර", "category": "anatomy" },
    { "word": "ශිරාපතු", "meaning": "කිතුල් ගස", "category": "plant" },
    { "word": "ශිරාල", "meaning": "කාමරංගා", "category": "plant" },
    { "word": "ශිරාවෘත්තා", "meaning": "ජයම්", "category": "plant" },
    { "word": "ශිරීෂ", "meaning": "මාරාගස, මහරිගස", "category": "plant" },
    { "word": "ශිරීෂකා", "meaning": "සියඹලා", "category": "plant" },
    { "word": "ශිරොධරා", "meaning": "ග්‍රීවය, බෙල්ල", "category": "anatomy" },
    { "word": "ශිරොර්ති", "meaning": "ඉසේ වේදනාව", "category": "treatment" },
    { "word": "ශිරොවෘත්තා", "meaning": "මිරිස්", "category": "plant" },
    { "word": "ශිරොවෘත්තඵල", "meaning": "රතුසැබෝ", "category": "plant" },
    { "word": "ශිරොසජී", "meaning": "ඉසේ ඇටය", "category": "anatomy" },
    { "word": "ශිලා", "meaning": "ගල්සෙවෙල්, රක්හිරියල්, ගල්මද, මනෝසිල", "category": "mineral" },
    { "word": "ශිලාකර්ණී", "meaning": "වැලුහුන්, ශලලකි, එන්සලු", "category": "plant" },
    { "word": "ශිලාජ්", "meaning": "ගල්මද", "category": "mineral" },
    { "word": "ශිලාජතු", "meaning": "ගල්සෙවෙල්, උපධාතු වෙසෙසක් වූ මේවා ගල්වල හට ගනී", "category": "mineral" },
    { "word": "ශිලාන්තජ", "meaning": "යකඩ", "category": "mineral" },

    // --- පිටුව 458 ---
    { "word": "ශිලාදද්‍රැ", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශිලාධාතු", "meaning": "සුදුගල් (නිරිවානා), කසාවන් සිවංගුරු", "category": "mineral" },
    { "word": "ශිලාපනා", "meaning": "කොල්ලු", "category": "plant" },
    { "word": "ශිලාපුෂ්ප", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශිලාභිද්", "meaning": "පොල්පලා", "category": "plant" },
    { "word": "ශිලානිර්‍ය්‍යාස", "meaning": "ගල්මද, ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශිලාහෙද", "meaning": "පොල්පලා, අක්කාපාන", "category": "plant" },
    { "word": "ශිලාව්‍යාධි", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශිලාසන", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශිලාසාර", "meaning": "යකඩ, (ලෝහ)", "category": "mineral" },
    { "word": "ශිලාස්‍රව", "meaning": "ගල්මද, ගල්සෙවෙල් හෝ ගල්නහර", "category": "mineral" },
    { "word": "ශිලින්ධ්‍ර", "meaning": "කෙසෙල් මල", "category": "plant" },
    { "word": "ශිලීපද", "meaning": "බරපා (බරවා) රෝගය (ශ්ලීපද)", "category": "treatment" },
    { "word": "ශිලොද්භව", "meaning": "ගල්මද, ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශිව", "meaning": "නෙල්ලි, බෙලි, ගුගුල්, රසදිය, මිහිරන්, අගිල්, වතුර, සවින්දව, මුහුදු ලුණු, සුදුපුස්කර, කළුඅත්තන, පිටවක්කා", "category": "plant" },
    { "word": "ශිවද්විෂ්ටා", "meaning": "වැටකේ", "category": "plant" },
    { "word": "ශිවදූරු", "meaning": "දේවදාර, රසකිඳ", "category": "plant" },
    { "word": "ශිවද්‍රැම", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "ශිවධාතු", "meaning": "රසදිය", "category": "mineral" },
    { "word": "ශිවපුෂ්ප", "meaning": "බදුවද, වද", "category": "plant" },
    { "word": "ශිවප්‍රිය", "meaning": "ගුගුල්, අත්තන", "category": "plant" },
    { "word": "ශිවමල්ලක", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "ශිවමල්ලිකා", "meaning": "මුනමල් : 379 පිටේ ඡායාරූප සහිත විස්තරය බලන්න", "category": "plant" },
    { "word": "ශිවමල්ලි", "meaning": "වකපුෂ්ප, කෝවක්කා", "category": "plant" },
    { "word": "ශිව වල්ලභ", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "ශිවබීජ", "meaning": "රසදිය", "category": "mineral" },
    { "word": "ශිවවෙෂ්ට", "meaning": "බෙලි", "category": "plant" },
    { "word": "ශිවශෙඛර", "meaning": "අත්තන, කෝවක්කා", "category": "plant" },
    { "word": "ශිවා", "meaning": "අරළු, නෙල්ලි, සැමගස, රතණ, ගෝරෝචන, පිටවක්කා, ඇත්දෙමට, මකුණුවැන්න, උළුවා, දියමිත්ත, මිහිරන්", "category": "plant" },
    { "word": "ශිවාටිකා", "meaning": "පිණ්ඩාහිඟු", "category": "plant" },
    { "word": "ශිවානාලි", "meaning": "පිටවක්කා", "category": "plant" },
    { "word": "ශිවානී", "meaning": "මිදිගස", "category": "plant" },
    { "word": "ශිවාඵලා", "meaning": "සැමගස", "category": "plant" },
    { "word": "ශිවාලස", "meaning": "රතු තලා", "category": "plant" },
    { "word": "ශිවාස්මානි", "meaning": "මිදිගස", "category": "plant" },
    { "word": "ශිවී", "meaning": "කරගස", "category": "plant" },
    { "word": "ශිශිර", "meaning": "සඳුන්, සැවැන්දරා, තමන්-මාදින් දෙමස", "category": "plant" },
    { "word": "ශිශිරා", "meaning": "ඉරමුසු, රුහාණිය", "category": "plant" },
    { "word": "ශිග්‍රැ", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "ශිසුපර්ණමන්", "meaning": "කරඳ ගස", "category": "plant" },
    { "word": "ශිඝ්‍රාණුකූලක", "meaning": "දත්ත", "category": "plant" },
    { "word": "ශීත", "meaning": "පියාගස, උළුවා, ලෝලු, කපුරු, හොමුවානු", "category": "plant" },
    { "word": "ශීතක්‍ෂාර", "meaning": "සුදුපුෂ්කර", "category": "plant" },
    { "word": "ශීතකර", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතකරි", "meaning": "රතණ", "category": "plant" },
    { "word": "ශීතකා", "meaning": "සීනි", "category": "food" },
    { "word": "ශීතකුම්භ", "meaning": "කණේරු", "category": "plant" },
    { "word": "ශීතගන්ධ", "meaning": "සුදු හඳුන්", "category": "plant" },
    { "word": "ශීතග්‍ර", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතපර්ණී", "meaning": "වරාමල්", "category": "plant" },
    { "word": "ශීතපාකිනී", "meaning": "කවෙළු", "category": "plant" },
    { "word": "ශීතපාකි", "meaning": "සුළුබැබිල, කවෙළු", "category": "plant" },
    { "word": "ශීතපුෂ්ප", "meaning": "මාරා, වරා, ගල්සෙවෙල්", "category": "plant" },
    { "word": "ශීතපුෂ්පී", "meaning": "කරඹ", "category": "plant" },
    { "word": "ශීතපුෂ්පා", "meaning": "කොටික්කම්බැවිල", "category": "plant" },
    { "word": "ශීතප්‍රභ", "meaning": "කපුරු", "category": "plant" }
];


