// data_178_185.js - පිටු 178-183 සහ 185 දක්වා සියලුම වචන (184 පිටුව හැර)
const data_extra_178_185 = [
  // --- පිටුව 178 ---
  { "word": "ගෝපුට", "meaning": "එන්සාල්, මහ එන්සාල්, මහ වම්මුතු (මහ කලාඳුරු)", "category": "plant" },
  { "word": "ගෝපුධා", "meaning": "මහ එන්සාල්", "category": "plant" },
  { "word": "ගෝපුර", "meaning": "කලාඳුරු, කුන්දිරුක්කන්, තුන්පත් කුරුඳු", "category": "plant" },
  { "word": "ගෝපුෂප", "meaning": "දියවම්මුතු", "category": "plant" },
  { "word": "ගෝභව", "meaning": "ගෝරෝචන", "category": "treatment" },
  { "word": "ගෝමඤ්ජර", "meaning": "ඉරමුසු වෙසෙසක්", "category": "plant" },
  { "word": "ගෝමාලී", "meaning": "තලගොයි මස්", "category": "treatment" },
  { "word": "ගෝමුරම", "meaning": "ගෝමුත්‍ර", "category": "treatment" },
  { "word": "ගෝමුත්‍ර", "meaning": "ගොමුත්‍රිය", "category": "treatment" },
  { "word": "ගෝමුත්‍රවිකාර", "meaning": "රතු ඇට ඇති පියා ගස්", "category": "plant" },
  { "word": "ගෝමුත්‍රී", "meaning": "රන්වන් කොල්ලු", "category": "plant" },
  { "word": "ගෝමුල්‍යා", "meaning": "ගම්මුළු", "category": "plant" },
  { "word": "ගෝමේද", "meaning": "ගෝමේදක, (තොපාෂාදිලී රත් පාටින් යුත් බාල මැණික් වගියක්) කොල්ලම් කොළ", "category": "treatment" },
  { "word": "ගෝරක්‍ෂ", "meaning": "සිහින්නාරං, හිරියල්", "category": "plant" },
  { "word": "ගෝරක්‍ෂකර්කටි", "meaning": "කුඩා කැකිරි", "category": "plant" },
  { "word": "ගෝරක්‍ෂපලම්බු", "meaning": "තිරිඟු, පුවක්, සිරිවැඩි බැවිල", "category": "plant" },
  { "word": "ගෝරක්‍ෂතණ්ඩුලා", "meaning": "ගස්කැලිය, සිරිවැඩි බැවිල", "category": "plant" },
  { "word": "ගෝරක්‍ෂතුම්බි", "meaning": "දිය ලබු", "category": "plant" },
  { "word": "ගෝරණ්ඩි", "meaning": "වලාවැන්න", "category": "plant" },
  { "word": "ගෝරාංගි", "meaning": "වලාවැන්න", "category": "plant" },
  { "word": "ගෝරුටි", "meaning": "ගෝරෝචන", "category": "treatment" },
  { "word": "ගෝරූපී", "meaning": "රක්අඟුණ ගස", "category": "plant" },
  { "word": "ගෝරෝචම", "meaning": "රාබුඟුණ, හිරියල්", "category": "plant" },
  { "word": "ගෝරෝචි", "meaning": "රක්අඟුණ ගස", "category": "plant" },
  { "word": "ගෝරෝචනා", "meaning": "ගෝරද", "category": "treatment" },
  { "word": "ගෝල", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "ගෝලක", "meaning": "හෙලබු ගස", "category": "plant" },
  { "word": "ගෝලගන්ධිකා", "meaning": "කාල, කුකුරුමුවන්, මනෝසිල, හිරියල්", "category": "plant" },
  { "word": "ගෝලපුෂ්ප", "meaning": "මීමල්, මීගස", "category": "plant" },
  { "word": "ගෝලඵල", "meaning": "කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "ගෝලමීගා", "meaning": "ගොන්කැකිරි", "category": "plant" },
  { "word": "ගෝලවන්", "meaning": "මල් පුවඟු", "category": "plant" },
  { "word": "ගෝලමී", "meaning": "වදකහ", "category": "plant" },
  { "word": "ගෝලා", "meaning": "මනෝසිල, රත් ගිරියල්", "category": "treatment" },
  { "word": "ගෝලාකාල", "meaning": "මනෝසිල", "category": "treatment" },
  { "word": "ගෝලිකා", "meaning": "බෙබර", "category": "plant" },
  { "word": "ගෝලිය", "meaning": "ගොකටු, තෙලඹු, පලොල්", "category": "plant" },
  { "word": "ගෝලියා", "meaning": "කළු නෙළුඹු", "category": "plant" },
  { "word": "ගෝලෝමී", "meaning": "හෙල රතණ, වදකහ, ජටාමාංශ, තලා, අක්‍ෂපටවා", "category": "plant" },
  { "word": "ගෝවන්දිනී", "meaning": "පුවඟු, කසාවන් මානෙල්", "category": "plant" },
  { "word": "ගෝවල්ලී", "meaning": "පුවඟු", "category": "plant" },
  { "word": "ගෝවල්ලිනී", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "ගෝශීර්ෂ", "meaning": "ගෝශී සඳුන්, සුදුහඳුන්", "category": "plant" },
  { "word": "ගෝශීර්ෂකා", "meaning": "ගැටතුඹ", "category": "plant" },
  { "word": "ගෝශෘංග", "meaning": "කුකුරුමුවන්, බද්ද (වෙලිප්පරිත්ති)", "category": "plant" },
  { "word": "ගෝශකෘත්", "meaning": "ගොම", "category": "treatment" },
  { "word": "ගෝශකෘත්භවා", "meaning": "හෙල රතණ", "category": "plant" },
  { "word": "ගෝස්තනාකාර", "meaning": "රටඉඳි ගස", "category": "plant" },
  { "word": "ගෝස්තනී", "meaning": "මිදි (මිදි වැල්)", "category": "plant" },
  { "word": "ගෝස්තනිකා", "meaning": "හිරමුසු, ඉඳි, ඉඳි දරප්පලම්", "category": "plant" },
  { "word": "ගෝස්තන", "meaning": "හිඹුරා", "category": "plant" },
  { "word": "ගෝස්තන්", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "ගෝසම්භවා", "meaning": "එල රතණ", "category": "plant" },
  { "word": "ගෝසාල", "meaning": "වැල්-වැල් ජාතියක්", "category": "plant" },
  { "word": "ගෝසියසුන්", "meaning": "රත් සඳුන්", "category": "plant" },
  { "word": "ගෝහරිතකී", "meaning": "බෙලි", "category": "plant" },
  { "word": "ගෝහලා / ගෝහාලියා", "meaning": "වලාවැන්න", "category": "plant" },
  { "word": "ගෝහිත", "meaning": "මහ වැටකොළු, බෙලිගස", "category": "plant" },

  // --- පිටුව 179 (ප්‍රත්‍යය "ගෞ" ලෙස සකසා ඇත) ---
  { "word": "ගෞම", "meaning": "ගෝරෝචන, දවගස, වතුර, ඇස, බඩ, අග", "category": "treatment" },
  { "word": "ගෞගන්ධි", "meaning": "උක්හකුරෙන් කළ ආසවය", "category": "treatment" },
  { "word": "ගෞෂිකා", "meaning": "උක් ගස", "category": "plant" },
  { "word": "ගෞෂධ", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "ගෞෂධී", "meaning": "ගෙදපලා, මනෝසිල", "category": "plant" },
  { "word": "ගෞපීර", "meaning": "මඩඟඟු", "category": "plant" },
  { "word": "ගෞගන්ධි", "meaning": "කොල්ලම් කොළ", "category": "plant" },
  { "word": "ගෞගර", "meaning": "සිරිසල්, හෙල අබ, නෙළුම්, වෙලන් ගස, රත්රන්", "category": "plant" },
  { "word": "ගෞගාරක", "meaning": "සිවංගුරු", "category": "treatment" },
  { "word": "ගෞගාරභපී", "meaning": "සුදුසැවැන්න", "category": "plant" },
  { "word": "ගෞගාරබදිර", "meaning": "රත් කිහිරිය", "category": "plant" },
  { "word": "ගෞගාරවනක", "meaning": "සුදු කබල ගස", "category": "plant" },
  { "word": "ගෞගාරපීරක", "meaning": "සිහින්දුරු, (සුදුදුරු)", "category": "plant" },
  { "word": "ගෞගාරවෘක්ෂ", "meaning": "කිරිඅඟුණ (වැල්අඟුණ)", "category": "plant" },
  { "word": "ගෞගාරද්ද්‍රැම", "meaning": "කහ, (කසා)", "category": "plant" },
  { "word": "ගෞගාරද්‍රැම", "meaning": "කහ", "category": "plant" },
  { "word": "ගෞගාරපාෂාණ", "meaning": "රත්හුණු", "category": "treatment" },
  { "word": "ගෞගාරපුෂ්ප", "meaning": "පුවඟු", "category": "plant" },
  { "word": "ගෞගාරප්‍රිය", "meaning": "රුකුගුණ, (ගස්අඟුණ)", "category": "plant" },
  { "word": "ගෞගාරමහා", "meaning": "රන්වන් කෙසෙල් ගෙවියසක්", "category": "plant" },
  { "word": "ගෞගාරමාලා", "meaning": "පසිපයෙහි වූ මීගස", "category": "plant" },
  { "word": "ගෞගාරවර්ණවන්", "meaning": "කහගස්", "category": "plant" },
  { "word": "ගෞගාරවල්ලී", "meaning": "පුවඟු", "category": "plant" },
  { "word": "ගෞගාරවිසි", "meaning": "සුදු හාල් වෙසෙසක්", "category": "plant" },
  { "word": "ගෞගාරසම්භ", "meaning": "හෙල අබ, ගෝරෝචන", "category": "plant" },
  { "word": "ගෞගාරශාක", "meaning": "මීගස් වෙසෙසක්", "category": "plant" },
  { "word": "ගෞගාරශාලි", "meaning": "සුදු හාල් වෙසෙසක්", "category": "plant" },
  { "word": "ගෞගාරසිදුගන්", "meaning": "හෙල අබ (සුදු අබ)", "category": "plant" },
  { "word": "ගෞගාරසවර්ණ", "meaning": "විනුකටු දේශයේ ප්‍රසිද්ධ වූ පලා වෙසෙසක්", "category": "plant" },
  { "word": "ගෞරා", "meaning": "රන්වන් කෙසෙල්, ගෝරෝචන, හෙල අබ", "category": "plant" },
  { "word": "ගෞරාක්‍ෂි", "meaning": "සිහින් එන්සාල්", "category": "plant" },
  { "word": "ගෞරාපාපී", "meaning": "සුදු දුරු", "category": "plant" },
  { "word": "ගෞරාවට", "meaning": "හෙල කිහිරි", "category": "plant" },
  { "word": "ගෞරාහා", "meaning": "කහ ගස", "category": "plant" },
  { "word": "ගෞරාමිලක", "meaning": "ඉදුණු නෙල්ලි ගෙඩිය", "category": "plant" },
  { "word": "ගෞරි", "meaning": "රුකුගුණ, ගෝරෝචන, තලා, ඉද්ද, පියාගස්, කලුනලා, හිරියල්, රත්කෙහෙල්, කසා, වැල්මදට", "category": "plant" },
  { "word": "ගෞරිකා", "meaning": "තලගස, හෙලඅබ", "category": "plant" },
  { "word": "ගෞරිපාෂාණ", "meaning": "මගරෙ වර්ණයෙන් යුත් පාෂාණම වගියක", "category": "treatment" },
  { "word": "ගෞරිප්‍රිය", "meaning": "පුවඟු", "category": "plant" },
  { "word": "ගෞරිය", "meaning": "ඉරමුසු", "category": "plant" },
  { "word": "ගෞරිල", "meaning": "හෙල අබ", "category": "plant" },
  { "word": "ගෞරිලොහ", "meaning": "මිණීරන්", "category": "treatment" },
  { "word": "ගෞරිප", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගෞරිපුෂ්ප", "meaning": "රුකුගුණ (ගස් අඟුණ) පුවඟු", "category": "plant" },
  { "word": "ගෞරිපස්", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගෞරිලලිහා", "meaning": "හිරියල්", "category": "treatment" },
  { "word": "ගෞරිවිප්", "meaning": "ගෙන්දගම්", "category": "treatment" },
  { "word": "ගෞලි", "meaning": "සුවඳසාරණ, ගෙදපලා", "category": "plant" },
  { "word": "ගෞලිකා", "meaning": "නෙළුඹු ගස", "category": "plant" },
  { "word": "ගෞව්‍ය", "meaning": "ගිතෙල්", "category": "treatment" },

  // --- පිටුව 180 ---
  { "word": "ග්‍රඤ්ජන", "meaning": "හෙල ලුහුණු, රතු ලුහුණු, මුරුංගා", "category": "plant" },
  { "word": "ග්‍රඤ්ජනක", "meaning": "මුරුංගා, වල්මුරුංගා", "category": "plant" },
  { "word": "ග්‍රන්ථම", "meaning": "මුරුංගා", "category": "plant" },
  { "word": "ග්‍රන්ථින", "meaning": "උගුරස්ස, වක්නිය", "category": "plant" },
  { "word": "ග්‍රන්ථිනබි", "meaning": "උගුරස්ස, වක්නිය", "category": "plant" },
  { "word": "ග්‍රන්ථිගලා", "meaning": "විෂ්ණුක්‍රාන්ති, තිප්පිලි, නිගුරැපියලි", "category": "plant" },
  { "word": "ග්‍රන්ථි", "meaning": "විෂ්ණුක්‍රාන්ති, ගුගුල්, තිප්පිලි මුල්", "category": "plant" },
  { "word": "ග්‍රන්ථික", "meaning": "තිප්පිලි මුල්, වලාවැන්න", "category": "plant" },
  { "word": "ග්‍රන්ථිකමූල", "meaning": "තිප්පිලි මුල්, වලාවැන්න", "category": "plant" },
  { "word": "ග්‍රන්ථිපා", "meaning": "නලිස් පතුරු", "category": "plant" },
  { "word": "ග්‍රන්ථිපාදාපතු", "meaning": "නලිස් පතුරු", "category": "plant" },
  { "word": "ග්‍රන්ථිපර්ණිකා", "meaning": "මහ මුඩමහණ", "category": "plant" },
  { "word": "ග්‍රන්ථිපර්ණී", "meaning": "උගුරස්ස, කෙසෙල්", "category": "plant" },
  { "word": "ග්‍රන්ථිඵල", "meaning": "හිඟුරුපියලි, විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "ග්‍රන්ථිබර්ජිනී", "meaning": "ගණකටුම", "category": "plant" },
  { "word": "ග්‍රන්ථිපර්ණි", "meaning": "වටාස්ස හෝ නිල් මල් ඇති සුගන්ධ වෙසෙසක්", "category": "plant" },
  { "word": "ග්‍රන්ථිහා", "meaning": "නවනන්දි ගස", "category": "plant" },
  { "word": "ග්‍රන්ථිමන්ඵල", "meaning": "දෙල්ගස, මදුරාගස", "category": "plant" },
  { "word": "ග්‍රන්ථිමා", "meaning": "හිරස්ස", "category": "plant" },
  { "word": "ග්‍රන්ථිමාන්", "meaning": "හිරස්ස", "category": "plant" },
  { "word": "ග්‍රන්ථිමුල", "meaning": "රතුලුහුණු", "category": "plant" },
  { "word": "ග්‍රන්ථිමුලා", "meaning": "රතුලුහුණු, මල්රතණ, කුසතණ", "category": "plant" },
  { "word": "ග්‍රන්ථිල", "meaning": "උගුරස්ස, තිප්පිලි මුල්, අමු ඉඟුරු, සුළුකුර, කංසා, කලාඳුරු, හිඟුරුපියලි", "category": "plant" },
  { "word": "ග්‍රන්ථිලා", "meaning": "උගුරස්ස, මහවම්මුතු", "category": "plant" },
  { "word": "ග්‍රන්ථිවර්ජින්", "meaning": "ග්‍රන්ථිපර්ණින් = නිල්පාටමල් ඇති මේවා සුගන්ධගෙත් යුක්ත යි.", "category": "plant" },
  { "word": "ග්‍රන්ථිමුල", "meaning": "ඉරමුසු, කුරුඳු", "category": "plant" },
  { "word": "ග්‍රන්ථිමුලා", "meaning": "ඉරමුසු, කුරුඳු", "category": "plant" },
  { "word": "ග්‍රන්ථිකා", "meaning": "විෂ්ණුක්‍රාන්ති, හරංකහ, ගුගුල්, කටුකිරිය, තිප්පිලි මුල්", "category": "plant" },
  { "word": "ග්‍රන්ථිකාසාර", "meaning": "ඇපල", "category": "plant" },
  { "word": "ග්‍රන්ථිකර", "meaning": "ඇපල", "category": "plant" },
  { "word": "ග්‍රන්ථිකා", "meaning": "මුඩමහණ, හරංකහ, රෑස්ගුණ, ඇපල, තිප්පිලි මුල්", "category": "plant" },
  { "word": "ග්‍රන්ථිපර්ණී", "meaning": "හිඟුරුපියලි, මහ පොහොඹරු", "category": "plant" },
  { "word": "ග්‍රන්ථිල", "meaning": "උගුරස්ස, කටුකිරිය", "category": "plant" },
  { "word": "ග්‍රන්ථිලෝමක", "meaning": "වදකසා, හෙල රතණ", "category": "plant" },
  { "word": "ග්‍රෂ්ටි", "meaning": "උවරල, බිමිතල්, හිරස්ස", "category": "plant" },
  { "word": "ග්‍රෂ්ටිකා", "meaning": "උවරල, බිමිතල්, හිරස්ස", "category": "plant" },
  { "word": "ග්‍රහසන", "meaning": "හෙල අබ", "category": "plant" },
  { "word": "ග්‍රහණි", "meaning": "එනම් රෝගය (මාන්‍දම)", "category": "symptom" },
  { "word": "ග්‍රහණිහර", "meaning": "කරාබුනැටි", "category": "plant" },
  { "word": "ග්‍රහදාප", "meaning": "වියන් දුඹුලු", "category": "plant" },
  { "word": "ග්‍රහාද්‍රැම", "meaning": "තේක්ක ගස", "category": "plant" },
  { "word": "ග්‍රහද්‍රැමි", "meaning": "ලෝලු", "category": "plant" },
  { "word": "ග්‍රහනායක", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ග්‍රහනාශක", "meaning": "රක්අත්තන, වරාගස", "category": "plant" },
  { "word": "ග්‍රහණීරැප්", "meaning": "ග්‍රහණී රෝගය", "category": "symptom" },
  { "word": "ග්‍රහපති", "meaning": "වරා ගස", "category": "plant" },
  { "word": "ග්‍රහපුෂ්ප", "meaning": "හෝපලු ගස", "category": "plant" },
  { "word": "ග්‍රහසින්", "meaning": "රක්අත්තන ගස", "category": "plant" },
  { "word": "ග්‍රහාපානා", "meaning": "ගෝරෝචන", "category": "treatment" },
  { "word": "ග්‍රාම්‍ය", "meaning": "සිනි", "category": "treatment" },
  { "word": "ග්‍රාම්‍යකරක්කටී", "meaning": "කොමඩු", "category": "plant" },
  { "word": "ග්‍රාම්‍යකුංකුම", "meaning": "වනුක්, සෙන්දිරික්කා", "category": "plant" },
  { "word": "ග්‍රාම්‍යකොෂා", "meaning": "මහ වැටකොළු", "category": "plant" },
  { "word": "ග්‍රාම්‍යා", "meaning": "බේරු, තෙල්බේරු, කදතලා", "category": "plant" },
  { "word": "ග්‍රාම්‍යජ", "meaning": "ඉඳිගස", "category": "plant" },

  // --- පිටුව 181 ---
  { "word": "ග්‍රාමිනා", "meaning": "තෙල් බේරු, අවිරිය", "category": "plant" },
  { "word": "ග්‍රාමිනි", "meaning": "බේරු, තෙල්බේරු, අවිරිය", "category": "plant" },
  { "word": "ග්‍රාම්‍යධර්ම", "meaning": "අස්ගොදු, (අමුක්කරා)", "category": "plant" },
  { "word": "ග්‍රාම්‍යලෝම", "meaning": "ගෙය වදනා, සුවඳ කසා", "category": "plant" },
  { "word": "ග්‍රාම්‍යලෝමියා", "meaning": "වදකසා", "category": "plant" },
  { "word": "ග්‍රාමීන්", "meaning": "බිල්ල, ඉඟුල් මාලියම්", "category": "plant" },
  { "word": "ග්‍රාමිනී", "meaning": "ඇල් කසඹිලියා, කොවිල, දිවුල, නිදිකුම්බා", "category": "plant" },
  { "word": "ග්‍රාමී", "meaning": "ඉඳි ලබු, දිවුල් ගස", "category": "plant" },
  { "word": "ග්‍රාමීඵල", "meaning": "දිවුල් ගෙඩි", "category": "plant" },
  { "word": "ග්‍රෛයෂි", "meaning": "ඇත්වගපුල්, (ගප්තිප්පිලි)", "category": "plant" },
  { "word": "ග්‍රී", "meaning": "ගිතෙල්", "category": "treatment" },
  { "word": "ග්‍රීෂ්මකා", "meaning": "බෝ ගස", "category": "plant" },
  { "word": "ග්‍රීෂ්මකෝ", "meaning": "ඉඳි ගස", "category": "plant" },
  { "word": "ග්‍රීෂ්මජ", "meaning": "ලබු, සිනිද්ද, සිලිංගස", "category": "plant" },
  { "word": "ග්‍රීෂ්මපුෂ්ප", "meaning": "සුවඳහොට", "category": "plant" },
  { "word": "ග්‍රීෂ්මපුෂ්ප", "meaning": "සුවඳහොට", "category": "plant" },
  { "word": "ග්‍රීෂ්මභවා", "meaning": "සිහින් ඉඳි", "category": "plant" },
  { "word": "ග්‍රීෂ්මා", "meaning": "ලොත් ගස, සිනිද්ද ගස", "category": "plant" },
  { "word": "ග්‍රීෂ්මා", "meaning": "බේරු", "category": "plant" },
  { "word": "ග්‍රීෂ්මොද්භවා", "meaning": "සිනිද්ද ගස", "category": "plant" },
  { "word": "ග්‍රෛෂ්මී", "meaning": "සිනිද්ද ගස", "category": "plant" },
  { "word": "ග්‍රෛෂ්මිකා", "meaning": "සිනිද්ද ගස", "category": "plant" },
  { "word": "ග්ලානි", "meaning": "ලෙඩ ඇත්තා", "category": "symptom" },
  { "word": "ග්ලාස්නු", "meaning": "ලෙඩා", "category": "symptom" },
  { "word": "ග්ලෞලි", "meaning": "කෙඩෙන්තු ගතිය", "category": "symptom" },
  { "word": "ග්ලෞවි", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ග්ලෞ", "meaning": "කපුරු", "category": "plant" },
  { "word": "ඝට", "meaning": "ද්‍රෝණිය, පණ ගස", "category": "treatment" },
  { "word": "ඝටිකා", "meaning": "ලවණ, වදල් ලුණු", "category": "treatment" },
  { "word": "ඝණ්ටවණී", "meaning": "පහන්, කොල්ලමගස", "category": "plant" },
  { "word": "ඝණ්ටා", "meaning": "රටබෝදික්කා, තෙලඹු, සිරිවාඩිබැවිල, ඇත් බැවිල", "category": "plant" },
  { "word": "ඝණ්ටාකා", "meaning": "තෙලෙඹුගස", "category": "plant" },
  { "word": "ඝණ්ටාපාටලි", "meaning": "හෙල පලොල්, තෙලෙඹු", "category": "plant" },
  { "word": "ඝණ්ටාපුෂ්ප", "meaning": "අත්තන", "category": "plant" },
  { "word": "ඝණ්ටාරවා", "meaning": "යක්බේරිය, අඬනහිරිය", "category": "plant" },
  { "word": "ඝණ්ටාල", "meaning": "කුකුරුමුවන්ගස", "category": "plant" },
  { "word": "ඝණ්ටාල", "meaning": "තෙලඹු, වැටකොළු", "category": "plant" },
  { "word": "ඝණ්ටාලිකා", "meaning": "මිහිරිමු ගින්නාරං", "category": "plant" },
  { "word": "ඝණ්ටාවිප්", "meaning": "ජයපාල ඇට", "category": "plant" },
  { "word": "ඝණ්ටාවිලා", "meaning": "මහ හණ, අඬනහිරිය", "category": "plant" },
  { "word": "ඝණ්ටිකා", "meaning": "අඬනහිරියා ගස, රටමිරිස්ගස, රසදිය", "category": "plant" },
  { "word": "ඝණ්ටිවිප්", "meaning": "ජයපාල ගස", "category": "plant" },
  { "word": "ඝන", "meaning": "ගිතෙල්", "category": "treatment" },
  { "word": "ඝනක", "meaning": "අත්තන", "category": "plant" },
  { "word": "ඝනකප්", "meaning": "කලාඳුරු, යම්, කුරුඳුපොතු, සාවැන්න, උක්, දියබෙරලිය, තියඹරා, යකඩ, මහ ගොන්සුතුකැකිරි, සිරිල්", "category": "plant" },
  { "word": "ඝනකප්පතු", "meaning": "ගල්වැස්ස, පානව්‍යස්ස", "category": "plant" },
  { "word": "ඝනකල", "meaning": "දියබෙරලිය, දෙළුම්", "category": "plant" },
  { "word": "ඝනකුම්භ", "meaning": "දන්ත", "category": "plant" },
  { "word": "ඝනවජ්ද", "meaning": "මුරංගා, තලිස්පත්තුරු", "category": "plant" },

  // --- පිටුව 182 ---
  { "word": "ඝනවජ්යා", "meaning": "සියඹලා", "category": "plant" },
  { "word": "ඝනඩක්", "meaning": "ලොත්සුඹුලු", "category": "plant" },
  { "word": "ඝනඩව", "meaning": "හෙලලොත්, සබර, (පියාගස්)", "category": "plant" },
  { "word": "ඝනද්‍රැම", "meaning": "සිහින්බෙබර, උගුරස්ස", "category": "plant" },
  { "word": "ඝනධ්වනි", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "ඝනපත්‍ර", "meaning": "සාරණ", "category": "plant" },
  { "word": "ඝනපල්ලව", "meaning": "මුරුංගා", "category": "plant" },
  { "word": "ඝනපුෂ්පිකා", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ඝනප්‍රියා", "meaning": "අතිවිඩයන්, දුන්ත, වලුදම්", "category": "plant" },
  { "word": "ඝනඵල", "meaning": "කටුකිහිරි", "category": "plant" },
  { "word": "ඝනරේණුකා", "meaning": "කළුකැම්මේරිය", "category": "plant" },
  { "word": "ඝනමල්ලිකා", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ඝනමාදිනී", "meaning": "සැවැන්න", "category": "plant" },
  { "word": "ඝනමාලිනී", "meaning": "සුවඳහොට", "category": "plant" },
  { "word": "ඝනමුලා", "meaning": "කළුකැම්මේරිය", "category": "plant" },
  { "word": "ඝනමූලිකා", "meaning": "කටුවිල", "category": "plant" },
  { "word": "ඝනරව", "meaning": "යක්බේරිය", "category": "plant" },
  { "word": "ඝනරස", "meaning": "මුරුවා, කපුරු", "category": "plant" },
  { "word": "ඝනරූප", "meaning": "වරාගස", "category": "plant" },
  { "word": "ඝනරූපක", "meaning": "වරාගස", "category": "plant" },
  { "word": "ඝනවල්ලභ", "meaning": "අතිවිඩයන්", "category": "plant" },
  { "word": "ඝනවල්ලභා", "meaning": "අතිවිඩයන්", "category": "plant" },
  { "word": "ඝනවල්ලී", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "ඝනවිතිගිද", "meaning": "තියඹරා, මහගොන්සුතුකැකිරි", "category": "plant" },
  { "word": "ඝනවාස", "meaning": "කොටදිඹුලා", "category": "plant" },
  { "word": "ඝනශාඛි", "meaning": "මඩඟඟු", "category": "plant" },
  { "word": "ඝනශෘඛ", "meaning": "ඇටවඹස", "category": "plant" },
  { "word": "ඝනස්වන", "meaning": "සුලුඅරණගස", "category": "plant" },
  { "word": "ඝනසාර", "meaning": "රසදිය, අමුකපුරු, මුරුවාවැල්", "category": "plant" },
  { "word": "ඝනා", "meaning": "කලප", "category": "treatment" },
  { "word": "ඝනාග්‍රා", "meaning": "ගුරැල්ලගස", "category": "plant" },
  { "word": "ඝනාඝන", "meaning": "කළුකැම්මේරිය", "category": "plant" },
  { "word": "ඝනාපඝා", "meaning": "කළුකැම්මේරිය", "category": "plant" },
  { "word": "ඝනාමල", "meaning": "සුකුර, පිටවක්කාසාරණ", "category": "plant" },
  { "word": "ඝනාමය", "meaning": "හිඳිගස", "category": "plant" },
  { "word": "ඝනෝදනඃ", "meaning": "පිටහලප", "category": "plant" },
  { "word": "ඝනෝට්ඵල", "meaning": "දෙල්ම්, පානව්‍යස්ස", "category": "plant" },
  { "word": "ඝනෝරද", "meaning": "චීන කපුරු", "category": "plant" },
  { "word": "ඝර්ජිරිගා", "meaning": "බැඳි සහල්", "category": "plant" },
  { "word": "ඝර්මඝන්තී", "meaning": "කහ", "category": "plant" },
  { "word": "ඝර්ම", "meaning": "වතුර, අව්ව", "category": "treatment" },
  { "word": "ඝර්මජ", "meaning": "ජවාදිනම් කස්තුරි වෙසෙස", "category": "treatment" },
  { "word": "ඝරා", "meaning": "මෙවන් (අෂ්ටක වර්ගයේ ඔසුවක්)", "category": "plant" },
  { "word": "ඝර්ෂණාල", "meaning": "අඹරණගල", "category": "treatment" },
  { "word": "ඝසිනී", "meaning": "කහ", "category": "plant" },
  { "word": "ඝරදිඝානකාබාධය", "meaning": "වටීකරණී (ග්‍රාහා) බෙහෙත් ශරීරගත වීමෙන් ඇතිවන රෝගයකි. මේ සඳහා බුදුරජාණන් වහන්සේ නියම කරණ ලද්දේ සිවාලේගි ඇලුණු පස් (සීකාලෝලි) ය.", "category": "treatment" },
  { "word": "ඝල", "meaning": "මෝරු", "category": "treatment" },
  { "word": "ඝෂ්ටිලා", "meaning": "පාෂාණ පර්ණී", "category": "plant" },
  { "word": "ඝාටා", "meaning": "ගස්කැලිය", "category": "plant" },
  { "word": "ඝාණ්ටික", "meaning": "අත්තනගස", "category": "plant" },
  { "word": "ඝාෂව", "meaning": "රත්රන්", "category": "treatment" },
  { "word": "ඝුක", "meaning": "ප්‍රඬාවා, (කුඩාලැල්ල)", "category": "plant" },
  { "word": "ඝුකාචාස", "meaning": "නිවුල්, ගැටනිවුල්", "category": "plant" },
  { "word": "ඝුටිකා", "meaning": "බෝලාපටවා, ගොප්ඇටය", "category": "plant" },
  { "word": "ඝුණිතා", "meaning": "මසන්", "category": "plant" },
  { "word": "ඝුණ්විකා", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ඝුණදර්ශිතා", "meaning": "ඉවද (අතිවිඩයන්)", "category": "plant" },
  { "word": "ඝුණා", "meaning": "කළුදුව", "category": "plant" },
  { "word": "ඝුණ්වී", "meaning": "දේවදාලිය", "category": "plant" },
  { "word": "ඝුන්ත්‍රික", "meaning": "ගොමිව්‍යරුපි", "category": "plant" },
  { "word": "ඝුනපුෂ්පඵල", "meaning": "ලොත්, රතුලොත්", "category": "plant" },
  { "word": "ඝුනප්‍රියා", "meaning": "දුන්ත, හොබල, අතිවිඩයන්", "category": "plant" },
  { "word": "ඝුනවල්ලභා", "meaning": "ඉවද", "category": "plant" },

  // --- පිටුව 183 ---
  { "word": "ඝුනොෂ්ඨා", "meaning": "අතිවිඩයන්", "category": "plant" },
  { "word": "ඝුසුණී", "meaning": "කොකුම්", "category": "plant" },
  { "word": "ඝෘණ්ඩිවාස", "meaning": "පුසුල්", "category": "plant" },
  { "word": "ඝෘත", "meaning": "ගිතෙල්, උයා කකාරණ ලද බෙහෙත", "category": "treatment" },
  { "word": "ඝෘතකරඤ්ජ", "meaning": "කරඳ වෙසෙසක්", "category": "plant" },
  { "word": "ඝෘතකා / ඝෘතකුමාරිකා", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "ඝෘතපක්විකා / ඝෘතමණ්ඩ", "meaning": "කවෙළු", "category": "plant" },
  { "word": "ඝෘතමණ්ඩලිකා", "meaning": "වලාවැන්න, රතු නිදිකුම්බ", "category": "plant" },
  { "word": "ඝෘතමණ්ඩා", "meaning": "කිරිපලා, වලාවැන්න, නිදිකුම්බා", "category": "plant" },
  { "word": "ඝෘතවර්ණිකා", "meaning": "කරඳ, මඟුල්කරඳ", "category": "plant" },
  { "word": "ඝෘතහේතු", "meaning": "වෙඬරු", "category": "treatment" },
  { "word": "ඝෘතාචිකා", "meaning": "නෝරමාලියම", "category": "plant" },
  { "word": "ඝෘනාවී", "meaning": "එන්සාල්", "category": "plant" },
  { "word": "ඝෘතාහ්ව", "meaning": "හොරගස", "category": "plant" },
  { "word": "ඝෘතිලා", "meaning": "පුස්වැන්න", "category": "plant" },
  { "word": "ඝෘෂ්ටි", "meaning": "විෂ්ණුක්‍රාන්ති, සිරස්ස, බිමිතල්, උවරල", "category": "plant" },
  { "word": "ඝෘෂ්ටිකා", "meaning": "පුවඟු", "category": "plant" },
  { "word": "ඝෘෂ්ටිලා", "meaning": "පොල්පලා, මැණික් වැන්න", "category": "plant" },
  { "word": "ඝෙල්කුලිකා", "meaning": "නෙළුඹල", "category": "plant" },
  { "word": "ඝෝටකාරි", "meaning": "කණේරු ගස", "category": "plant" },
  { "word": "ඝෝටගල", "meaning": "වැල්ක්", "category": "plant" },
  { "word": "ඝෝටිකා", "meaning": "මහගෙද", "category": "plant" },
  { "word": "ඝෝටිකාමලා", "meaning": "ගොදපලා", "category": "plant" },
  { "word": "ඝෝපී", "meaning": "මහබෙබර, හින්බෙබර", "category": "plant" },
  { "word": "ඝෝණ්ටා", "meaning": "හණ, යක්බේරිය, කංසුණ, පුවක්, උක්මුල්, මහබැවිල, ඇත්බැවිල", "category": "plant" },
  { "word": "ඝෝණ්ටාවාස", "meaning": "කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "ඝෝණ්ටාඵල", "meaning": "පුවක්ගෙඩිය, බෙබර ගෙඩිය", "category": "plant" },
  { "word": "ඝෝරණ්ටී", "meaning": "පුවක්ගස", "category": "plant" },
  { "word": "ඝෝරා", "meaning": "වැලුක්, රඹුක්, දේවදාලිය", "category": "plant" },
  { "word": "ඝෝල", "meaning": "මෝරු", "category": "treatment" },
  { "word": "ඝෝලි", "meaning": "ගෙද", "category": "plant" },
  { "word": "ඝෝෂ", "meaning": "දේවදාලිය, කරල්සැබෝ, කලාඳුරු, දුම්මල්ල", "category": "plant" },
  { "word": "ඝෝෂක", "meaning": "තිත්ත වැටකොළු, මහ වැටකොළු", "category": "plant" },
  { "word": "ඝෝෂකාකානී", "meaning": "මහවැටකොළු", "category": "plant" },
  { "word": "ඝෝෂවතී", "meaning": "හාතාවාරිය", "category": "plant" },
  { "word": "ඝෝෂා", "meaning": "ගතපුෂ්ප, වැටකේ, කටු දුරු, කකුළුසුනු, වලඟසාල්", "category": "plant" },
  { "word": "ඝෝෂාතකී", "meaning": "සුදු වැටකොළු", "category": "plant" },
  { "word": "චංචුනාභි", "meaning": "සක්නාබ", "category": "plant" },
  { "word": "චක්‍ර", "meaning": "ඉරිවේරිය-සබර (ලොත්), තුවරලා, කහිටකලිංබි", "category": "plant" },
  { "word": "චක්‍රසෙනිකා", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "චක්‍රකා", "meaning": "තුවරලා, සිවිය", "category": "plant" },
  { "word": "චක්‍රානනක", "meaning": "යකඩ, කඩම්", "category": "treatment" },
  { "word": "චක්‍රාකාරක", "meaning": "තෝර, වක්නිය, දිවිපහුරු", "category": "plant" },
  { "word": "චක්‍රකුල්‍යා", "meaning": "පුස්වැන්න, කහතලා, තෝර, විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "චක්‍රගල්", "meaning": "තෝර, ඇත්තෝර", "category": "plant" },
  { "word": "චක්‍රගුල්ඵ", "meaning": "අසෝකා, ගෝපලු ගස", "category": "plant" },
  { "word": "චක්‍රතුලකා", "meaning": "පොල්පලා, පුස්වැන්න, ගතපුෂ්ප, තෝර", "category": "plant" },
  { "word": "චක්‍රතෛල", "meaning": "ඇත්තෝර ඇටතෙල්", "category": "treatment" },
  { "word": "චක්‍රදන්තී", "meaning": "ජයපාල ගස, දුන්ත ගස", "category": "plant" },
  { "word": "චක්‍රදව", "meaning": "ඇත්තෝර", "category": "plant" },
  { "word": "චක්‍රනඛ", "meaning": "වක්නිය, දිවිපහුරු", "category": "plant" },
  { "word": "චක්‍රපද්මාට", "meaning": "ඇත්තෝර", "category": "plant" },

// 184 පිටුවේ සියලුම වචන

  { "word": "චක්‍රපර්ණී", "meaning": "පොල්පලා, පුස්වැන්න, මෑණික්වැන්න, ගතපුෂ්ප", "category": "plant" },
  { "word": "චක්‍රපරිව්‍යාධ", "meaning": "ඇසල ගස", "category": "plant" },
  { "word": "චක්‍රපාණි", "meaning": "කලා", "category": "plant" },
  { "word": "චක්‍රපුෂ්පනාට", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "චක්‍රපුෂ්ප", "meaning": "කෝබු", "category": "plant" },
  { "word": "චක්‍රපුෂ්ම", "meaning": "කෝන්", "category": "plant" },
  { "word": "චක්‍රපුෂ්මී", "meaning": "කෝබු, කෝන්", "category": "plant" },
  { "word": "චක්‍රඵල", "meaning": "කොටදිඹුලා, තොවිල", "category": "plant" },
  { "word": "චක්‍රබණ්ධිනා", "meaning": "තොවිල", "category": "plant" },
  { "word": "චක්‍රබාලා", "meaning": "ඇම්බරැල්ලා", "category": "plant" },
  { "word": "චක්‍රබීජ", "meaning": "තකුල්, කපුකිනිස්ස", "category": "plant" },
  { "word": "චක්‍රමර්‍ද", "meaning": "තෝර, තෝර ඇට, පෙති තෝර", "category": "plant" },
  { "word": "චක්‍රමර්‍දක", "meaning": "පෙති තෝර", "category": "plant" },
  { "word": "චක්‍රමානා", "meaning": "කහිටකලිංගී", "category": "plant" },
  { "word": "චක්‍රමාරක", "meaning": "වරා, හෙල වරා", "category": "plant" },
  { "word": "චක්‍රරාග", "meaning": "සුළඹවන්, මඟවෙවන්, (අෂ්ටක වර්ගයේ ඔසු දෙවගයක්)", "category": "plant" },
  { "word": "චක්‍රරේණුකා", "meaning": "රතු කණේරු", "category": "plant" },
  { "word": "චක්‍රල", "meaning": "රතු කොල්ලු", "category": "plant" },
  { "word": "චක්‍රලක්ෂණ", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "චක්‍රලා", "meaning": "ඇත්කලාඳුරු", "category": "plant" },
  { "word": "චක්‍රලිංග", "meaning": "කෙළිඳ ඇට", "category": "plant" },
  { "word": "චක්‍රලොඹු", "meaning": "ලොත්සුඹුලු", "category": "plant" },
  { "word": "චක්‍රවර්තින්", "meaning": "ශතපුෂ්ප, ජටාමාංශ", "category": "plant" },
  { "word": "චක්‍රවර්තිනී", "meaning": "වටස්ස", "category": "plant" },
  { "word": "චක්‍රවල්ලිකා", "meaning": "පෙනෙල වැල්", "category": "plant" },
  { "word": "චක්‍රවල්ලරී", "meaning": "දළක් වෙසෙසක්", "category": "plant" },
  { "word": "චක්‍රවාතාකි", "meaning": "වම්බටු", "category": "plant" },
  { "word": "චක්‍රවිප්", "meaning": "කපුකිනිස්ස, තකුල්, ජයපාල ඇට", "category": "plant" },
  { "word": "චක්‍රශල්‍යා", "meaning": "එලහුනිද", "category": "plant" },
  { "word": "චක්‍රසංවරණ", "meaning": "කෝන්, කෝබු", "category": "plant" },
  { "word": "චක්‍රසේනා", "meaning": "වෙලිප්පරිත්ති (මස්බැද්ද) මෑඩඟු", "category": "plant" },
  { "word": "චක්‍රා", "meaning": "තිප්පිලි, කකුළුසුනු, ඉඟුරා, දිවිපහුරු", "category": "plant" },
  { "word": "චක්‍රාකාර", "meaning": "වක්නිය", "category": "plant" },
  { "word": "චක්‍රාංග", "meaning": "වැල්මදට", "category": "plant" },
  { "word": "චක්‍රාංගා", "meaning": "කඩුකරෝෂණ, කංසා", "category": "plant" },
  { "word": "චක්‍රාංඝි", "meaning": "කඩුකරෝෂණ, කංසා සුනු", "category": "treatment" },
  { "word": "චක්‍රාධිෂ්ඨා", "meaning": "දියමින්ත, තල් වැල්", "category": "plant" },
  { "word": "චක්‍රායවාසින්", "meaning": "නාරං ගස", "category": "plant" },
  { "word": "චක්‍රාරවක", "meaning": "දිවිපහුරු", "category": "plant" },
  { "word": "චක්‍රාලු", "meaning": "මී අඹ වෙසෙසක්", "category": "plant" },
  { "word": "චක්‍රාව්හය", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "චක්‍රි", "meaning": "තෝර, තුවරලා, ලොත්", "category": "plant" },
  { "word": "චක්‍රිකා", "meaning": "රතුකොල්ලු", "category": "plant" },
  { "word": "චක්‍රිකා", "meaning": "හෙල ඔලිඳ, සිවිය, ඇත්වගපුල්", "category": "plant" },
  { "word": "චක්‍රිනී", "meaning": "වක්නිය, දිවිපහුරු, තෝර", "category": "plant" },
  { "word": "චක්‍රෝත්‍රක", "meaning": "දෙව් අබ", "category": "plant" },
  { "word": "චක්‍රොට", "meaning": "දියමිදෙල්ල", "category": "plant" },
  { "word": "චක්‍රොටි", "meaning": "දෙව් අබ", "category": "plant" },
  { "word": "චක්ෂු", "meaning": "පොල්, මලබටු", "category": "plant" },
  { "word": "චක්ෂුඃ පුෂ්ප", "meaning": "දියමින්ත", "category": "plant" },
  { "word": "චක්ෂුෂ්‍යනී", "meaning": "වෙල්මුබ (මුඩමහණ)", "category": "plant" },
  { "word": "චක්ෂුස්‍යකුලා", "meaning": "දේවදාලිය වැල්", "category": "plant" },
  { "word": "චක්ෂුපිබා", "meaning": "අබනගිරිය", "category": "plant" },
  { "word": "චක්ෂුඵල", "meaning": "ඉඟිනිඇට", "category": "plant" },
  { "word": "චක්ෂුබහුල", "meaning": "මෑඩඟු", "category": "plant" },
  { "word": "චක්ෂුෂියාන්", "meaning": "මෑඩඟු", "category": "plant" },
  { "word": "චක්ෂුර", "meaning": "අටවිටක්කා", "category": "plant" },
  { "word": "චක්ෂුස්", "meaning": "මෑඩඟු", "category": "plant" },
  { "word": "චක්ෂුස", "meaning": "වලාවැන්න, මස්බැද්ද, ඉඟිනි, කොල්ලු, කෝමාරිකා, රසඳුන්, ඇත්දෙමට, වැටකේ", "category": "plant" },
  { "word": "චක්ෂුසා", "meaning": "වටරුහෑණ, (වාල්මොලඟු) කෝමාරිකා", "category": "plant" },

  // --- පිටුව 185 (අනුමාන කළ 'ච' අක්ෂරය සහිතව) ---
  { "word": "චක්ෂුස්‍ය", "meaning": "වලාවැන්න, වැටකේ, කෝමාරිකා, ඉඟිනි, මුරුංගා", "category": "plant" },
  { "word": "චක්ෂුෂ්‍යා", "meaning": "ඉරිවේරිය", "category": "plant" },
  { "word": "චක්ෂුෂ්‍ය", "meaning": "සක්නාබ", "category": "plant" },
  { "word": "චක්ෂුෂ්‍ය", "meaning": "ගස", "category": "plant" },
  { "word": "චක්ෂුරා", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "චටු", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "චටුඃ", "meaning": "පලොල්", "category": "plant" },
  { "word": "චටකාවලා", "meaning": "පලොල්", "category": "plant" },
  { "word": "චටකා", "meaning": "සියඹලා", "category": "plant" },
  { "word": "චටවරී", "meaning": "රසදිය, තිප්පිලි", "category": "treatment" },
  { "word": "චටවල", "meaning": "බෝ ගස", "category": "plant" },
  { "word": "චටවලපත්‍ර", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "චටවලාබහුල", "meaning": "එරබු, හෙල එරබු, (නවාගිලිය)", "category": "plant" },
  { "word": "චටවු", "meaning": "නිප්මිලිමුල්, රත් හුනිද", "category": "plant" },
  { "word": "චටකා", "meaning": "නිස්පිලිමුල්", "category": "plant" },
  { "word": "චටකාසිරි", "meaning": "රත්කණේරු, අලරිය, හිඟුරුපියලි, තොරගස, රත් කරවිගස", "category": "plant" },
  { "word": "චණ්ඩ", "meaning": "රත් කණේරු, සිරිතේක්කු", "category": "plant" },
  { "word": "චණ්ඩා", "meaning": "වදකහ", "category": "plant" },
  { "word": "චණ්ඩක", "meaning": "සියඹලා", "category": "plant" },
  { "word": "චණ්ඩද්‍රැමා", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "චණ්ඩන", "meaning": "බල්ලුණු", "category": "treatment" },
  { "word": "චණ්ඩලවන", "meaning": "රසකිඳ", "category": "plant" },
  { "word": "චණ්ඩභාසා", "meaning": "අඩනගිරිය, ගොඩුකොළ, ඊතණ, හෙලරතණ, කුසතණ, හිඟුරුපියලි, හඟුල්වැල්, දිවුල්", "category": "plant" },
  { "word": "චණ්ඩා", "meaning": "අලරිය, රත් අලරිය (කණේරු, රත් කණේරු)", "category": "plant" },
  { "word": "චණ්ඩාකුසුම", "meaning": "අලරිය, හෙල කණේරු", "category": "plant" },
  { "word": "චණ්ඩාක", "meaning": "රත් අලරිය", "category": "plant" },
  { "word": "චණ්ඩාලක", "meaning": "කණේරු ගස", "category": "plant" },
  { "word": "චණ්ඩාලිකා", "meaning": "මුං, සිහින් මුං", "category": "plant" },
  { "word": "චණ්ඩිකා", "meaning": "රත් අලරිය, (රත්කණේරු)", "category": "plant" },
  { "word": "චණ්ඩිකුසුම", "meaning": "ග්‍රන්ථිපර්ණී වෙසෙසක්", "category": "plant" },
  { "word": "චණ්ඩාලතා", "meaning": "නිප්පිලිමුල්", "category": "plant" },
  { "word": "චණ්ඩාමල", "meaning": "සිහින්ගොකටු", "category": "plant" },
  { "word": "චණ්ඩ්‍රැම", "meaning": "ගස්කැලිය", "category": "plant" },
  { "word": "චතල", "meaning": "පොල්පලා, පුස්වැන්න, මෑණික්වැන්න", "category": "plant" },
  { "word": "චතුඃපත්‍රී", "meaning": "කුරුඳු, සුදුදුරු, අරළු, අසමෝද යන සතරට ද, කස්තුරිදෙහාගයහි, සඳුන් සතර භාගයයි යන මීට ද, කොකුම් මල්තුනයි, කපුරු සතරයි යන මීට ද, චතුඃසම යයි කියති.", "category": "treatment" },
  { "word": "චතුඃසම", "meaning": "පාද හතර", "category": "treatment" },
  { "word": "චතුප්පාද", "meaning": "සඳුන්, කපුරු, කොකුම්, තුවරලා හෝ කොකුම්, යොන්පුප්, (අරාබි සමන්) තුවරලා, තුරුක්තෙල්, (අරාබි සුවඳතෙලක්)", "category": "plant" },
  { "word": "චතුර්ගුණ්ඩී", "meaning": "එන්සාල්, කුරුඳු පොතු, කොල්ලම්කොළ, නාමල්රේණු", "category": "plant" },
  { "word": "චතුර්ජාත", "meaning": "ගොකටු", "category": "plant" },
  { "word": "චතුර්බුජ", "meaning": "චතුසුද්ද, කිඹුල්වැන්න", "category": "plant" },
  { "word": "චතුර්බුජපත්‍රිකා", "meaning": "වම්මුතු, ඉවද, රසකිඳ, සිද්ධිගුරු", "category": "plant" },
  { "word": "චතුර්ධාරා", "meaning": "අහුගස", "category": "plant" },
  { "word": "චතුර්බහිනි", "meaning": "සල්වැන්න, පුස්වැන්න, මස්වැන්න, මුවවැන්න", "category": "plant" },
  { "word": "චතුර්බාහුල", "meaning": "මහගෙද", "category": "plant" },
  { "word": "චතුරබුහුලා", "meaning": "සාතාවාරිය, කෝමාරිකා", "category": "plant" },
  { "word": "චතුරමිල", "meaning": "ඇසල", "category": "plant" },
  { "word": "චතුරගිනි", "meaning": "ඇසල", "category": "plant" },
  { "word": "චතුරශ්‍රා", "meaning": "ගොරකා, සියඹලා, ඇඹුල්දෙඹම්, දෙහි", "category": "plant" }
];