// data_125_134.js - පිටු 125 සිට 134 දක්වා සියලුම වචන
const data_extra_125_134 = [
  // --- පිටුව 125 ---
  { "word": "කුවල", "meaning": "බෙබර, ඇඹුල, නිළුපුල්", "category": "plant" },
  { "word": "කුවලකණී", "meaning": "නිල් මානෙල්", "category": "plant" },
  { "word": "කුවලකී", "meaning": "සුදු සල් ගස", "category": "plant" },
  { "word": "කුවලයා", "meaning": "නිල්පුල්, ඇඹිල ගස", "category": "plant" },
  { "word": "කුවලී", "meaning": "මසන් (බැබර) ඉඳුසල්", "category": "plant" },
  { "word": "කුවලෙල", "meaning": "බෙලි ගස", "category": "plant" },
  { "word": "කුහ්ව", "meaning": "බලල් ලුණු", "category": "treatment" },
  { "word": "කුමිබිලන්තගන්", "meaning": "හින්තඹල", "category": "plant" },
  { "word": "කුබිලින්තගන්", "meaning": "හින්තඹල", "category": "plant" },
  { "word": "කුවෙර", "meaning": "නන්දි රුක", "category": "plant" },
  { "word": "කුවෙරක", "meaning": "වතු සුද්ද, කිරිබෝ ගස, නන්දි රුක", "category": "plant" },
  { "word": "කුවෙරාක්‍ෂි", "meaning": "කුඹුරු ඇට, හෙල පලොල්", "category": "plant" },
  { "word": "කුවෙරාග", "meaning": "නුග, මහ නුග", "category": "plant" },
  { "word": "කුවෙරස", "meaning": "පලොල්, කුඹුරු", "category": "plant" },
  { "word": "කුෂාන්තකාන්ත", "meaning": "කුණුකරඳ ගස", "category": "plant" },
  { "word": "කුෂෙගෙය", "meaning": "නෙළුම්", "category": "plant" },
  { "word": "කුස", "meaning": "දළක්, වැල්ක්, වතුර, කුස තණ", "category": "plant" },
  { "word": "කුසකාශ", "meaning": "ඊතණ, කුසතණ", "category": "plant" },
  { "word": "කුසපුෂ්ප", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
  { "word": "කුසරීර", "meaning": "මහාගාල වාක්‍යය", "category": "treatment" },
  { "word": "කුශලී", "meaning": "කෝමාරිකා, අස්මින්තක වාක්‍යය", "category": "plant" },
  { "word": "කුශලොදර", "meaning": "ලෝලු", "category": "plant" },
  { "word": "කුශස්තව", "meaning": "කුසතණ පඳුර", "category": "plant" },
  { "word": "කුශා", "meaning": "ඉදිකුළු රතු පාට මිහිරි රස ඇති ලප්තාරු (කස්තාරාත්) වගිය", "category": "plant" },
  { "word": "කුශල්මලී", "meaning": "එරබදු", "category": "plant" },
  { "word": "කුශිංෂපා", "meaning": "ඇවට්ඨිය වෙසෙසක්", "category": "plant" },
  { "word": "කුශික", "meaning": "සල් ගස, ඉළු, බුරාත, අමු, ඇසල, දුම්මල", "category": "plant" },
  { "word": "කුශිඳ", "meaning": "රත් හඳුන්", "category": "plant" },
  { "word": "කුශෙරිකා", "meaning": "කෙළිඳ", "category": "plant" },
  { "word": "කුශෙශය", "meaning": "කිණිහිරි ගස", "category": "plant" },
  { "word": "කුෂ්ට", "meaning": "කොට්ටම්, යකඩ, කුෂ්ඨ රෝගය, කුලස්පන වාක්ය", "category": "treatment" },
  { "word": "කුෂටක", "meaning": "කොට්ටම්", "category": "plant" },
  { "word": "කුෂටකණ්ටක", "meaning": "කිණිහිරි ගස", "category": "plant" },
  { "word": "කුෂටකාන්තන", "meaning": "තෝර", "category": "plant" },
  { "word": "කුෂටගන්‍ධා", "meaning": "අස්ගොදු", "category": "plant" },
  { "word": "කුෂටගන්‍ධිකා", "meaning": "එන්සාල්, ගොකටු, (නෙරෙවි)", "category": "plant" },
  { "word": "කුෂටගන්‍ධිනී", "meaning": "අමුක්කරා", "category": "plant" },
  { "word": "කුෂටවහ", "meaning": "බෝදි ඇට, ඇසල, කිහිරි, කළු කිහිරිය, කොවඩිබුලා, කලුකම්මේරිය", "category": "plant" },
  { "word": "කුෂ්ටාසනී", "meaning": "බින්තල් අල, උවරල, මාරා, මුද්රිය, මහරි, හෙල අබ, කොවඩිබුලා, බෝදි ඇට, කලු කැම්මේරිය, කලු කිහිරි", "category": "plant" },
  { "word": "කුෂ්ටතොදන", "meaning": "රත් කිහිරි ගස", "category": "plant" },
  { "word": "කුෂ්ටනාශනී", "meaning": "බෝදි ඇට, හෙල අබ, ඇසල ගස", "category": "plant" },
  { "word": "කුෂ්ටහා", "meaning": "කොසඹ, දුම්මැල්ල", "category": "plant" },
  { "word": "කුෂ්ටිහුන්", "meaning": "හිඹුරා, කිහිරි", "category": "plant" },
  { "word": "කුෂ්ටහාස", "meaning": "හිඹුරා, කිහිරි", "category": "plant" },
  { "word": "කුෂ්ටමර්දනී", "meaning": "ගෙන්දගම් (ගන්ධක)", "category": "treatment" },
  { "word": "කුෂ්ටවෙරිත්", "meaning": "සන්තීනායත (බෝදි ඇට ගස)", "category": "plant" },
  { "word": "කුෂ්ටවාක්ය", "meaning": "හිඟුරා ගස, ගුරැන්ද", "category": "plant" },
  { "word": "කුෂ්ටසූදන", "meaning": "ඇසල, එරහඬි, කිහිරිිය, කලු කිහිරිය (කලුහර)", "category": "plant" },
  { "word": "කුෂ්ටහන්", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "කුෂ්ටාරි", "meaning": "දුම්මැල්ල, හිඹුරැ, ගෙන්දගම්", "category": "treatment" },
  { "word": "කුෂ්යගන්ත්‍රි", "meaning": "බෝදි ඇට", "category": "plant" },
  { "word": "කුෂ්යගන්ත්‍රා", "meaning": "හබරල", "category": "plant" },
  { "word": "කුෂක", "meaning": "බූ ගස", "category": "plant" },
  { "word": "කුෂ්යාල", "meaning": "කුබේර", "category": "treatment" },
  { "word": "කුස්තුම්බරී", "meaning": "කොත්තඹුරු (කොත්තමල්ලි)", "category": "plant" },
  { "word": "කුස්තුම්බරැ", "meaning": "කොත්තඹුරු (කොත්තමල්ලි)", "category": "plant" },
  { "word": "කුස", "meaning": "වැලක්, රඹුක්, කුසතණ, ඊතණ", "category": "plant" },

  // --- පිටුව 126 ---
  { "word": "කුසකන්", "meaning": "වියළි කහ", "category": "plant" },
  { "word": "කුසභ", "meaning": "මූරුත", "category": "plant" },
  { "word": "කුසපත්‍ර", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "කුසලි", "meaning": "රක්ත චන්දන, ගස් රක් හඳුන්", "category": "plant" },
  { "word": "කුසල්මලී", "meaning": "එරබදු ගස, ඉබුල් ගස", "category": "plant" },
  { "word": "කුසුමකෙමි", "meaning": "මල් බට්ට (පුෂ්පකර්ණිකා)", "category": "plant" },
  { "word": "කුසුමහ", "meaning": "වනුක්, සෙන්දිරික්කා, කුණුකරඳ", "category": "plant" },
  { "word": "කුසුමිහාපෙයි", "meaning": "වනුක්, සෙන්දිරික්කා", "category": "plant" },
  { "word": "කුසුමරද", "meaning": "මල් රේණු, (පුෂ්ප පරාග)", "category": "plant" },
  { "word": "කුසුමරස", "meaning": "මල් පැණි, (පුෂ්ප මකරන්ද) මී පැණි", "category": "treatment" },
  { "word": "කුසුම", "meaning": "මල, කරාබු නැටි, ගෙඩිය, තෝර, කෙසෙල්, මසිලල", "category": "plant" },
  { "word": "කුසුමඵල", "meaning": "සාදික්කා", "category": "plant" },
  { "word": "කුසුමහන්ති", "meaning": "සෙන්දිරික්කා", "category": "plant" },
  { "word": "කුසුමා", "meaning": "වැකොඳ, දෑසමන්, රත් පලොල්", "category": "plant" },
  { "word": "කුසුමාඤ්ජන", "meaning": "පින්තලෙහි මලක් වැනිව උපන් අඳුන් (පින්තලවල නිල් පාට මලකඩ)", "category": "treatment" },
  { "word": "කුසුමාත්මක", "meaning": "කොකුම්", "category": "plant" },
  { "word": "කුසුමාණ්ඩ", "meaning": "සපු ගස", "category": "plant" },
  { "word": "කුසුමාරිකා", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "කුසුමාසව", "meaning": "මල්වලින් හෝ මී පැණි වලින් උපදින සුරා වගී", "category": "treatment" },
  { "word": "කුසුමෝද්භව", "meaning": "කොකුම්", "category": "plant" },
  { "word": "කුසො", "meaning": "කුසතණ", "category": "plant" },
  { "word": "කෘහක", "meaning": "ග්‍රන්ථි පර්ණීරක (ගණවන්ටි ගස)", "category": "plant" },
  { "word": "කෘතලි", "meaning": "බුලත්", "category": "plant" },
  { "word": "කෘනා", "meaning": "කටුකරෝෂණී", "category": "plant" },
  { "word": "කෘතින", "meaning": "කපුරු", "category": "plant" },
  { "word": "කෘමිරි", "meaning": "ගස්බඩ", "category": "plant" },
  { "word": "කෘමිරොග", "meaning": "කුෂ්ඨ රෝගය", "category": "symptom" },
  { "word": "කෘතකභෙදි", "meaning": "කටුකරෝෂණී", "category": "plant" },
  { "word": "කෘතජීව", "meaning": "බුන්සාරණ", "category": "plant" },
  { "word": "කෘතරවාහිනි", "meaning": "හුන්සවාලු", "category": "plant" },
  { "word": "කෘතලමස්තක", "meaning": "සිවිය", "category": "plant" },
  { "word": "කෘතස්නාන", "meaning": "පිටවක්කා (නවතාලිලිය)", "category": "plant" },
  { "word": "කෘතගල්මලී", "meaning": "එරබදු, කැල, කටුඉබුල්", "category": "plant" },
  { "word": "කෘතාන්ධසිද්ධිකාන්ත", "meaning": "බුන්සාරණ ගස", "category": "plant" },
  { "word": "කෘතායුස්", "meaning": "ගුගුල් ගස", "category": "plant" },
  { "word": "කෘප", "meaning": "වෙනිවැල් ගැට", "category": "plant" },
  { "word": "කූර්පපර්ණී", "meaning": "මැඩගු", "category": "plant" },
  { "word": "කූර්වභාප", "meaning": "බූප්පන්", "category": "treatment" },
  { "word": "කූර්වභෙබර", "meaning": "පොල් ගස", "category": "plant" },
  { "word": "කූර්ව ශීර්ෂ", "meaning": "ගොප්ඇටය", "category": "treatment" },
  { "word": "කූර්වශීර්ෂික", "meaning": "ජීවක වාක්‍යය, පොල් ගස", "category": "plant" },
  { "word": "කූරූ", "meaning": "කුරක්කම්පලා ගස", "category": "plant" },
  { "word": "කූලප්‍රක්‍ෂ", "meaning": "කොල්ලු", "category": "plant" },
  { "word": "කූලක", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "කූලා", "meaning": "හින්දැත්ත ගස", "category": "plant" },
  { "word": "කෘකර", "meaning": "සිවිය, කණේරු", "category": "plant" },
  { "word": "කෘකරා", "meaning": "තිප්පිලි", "category": "plant" },
  { "word": "කෘකලා", "meaning": "වගපුල් (තිප්පිලි)", "category": "plant" },
  { "word": "කෘච්ඡු", "meaning": "මුත්‍ර කෘච්ඡු රෝගය", "category": "symptom" },
  { "word": "කෘතප්‍රාරි", "meaning": "අන්ඳර ගස", "category": "plant" },
  { "word": "කෘණකප", "meaning": "වල්තඹපලා", "category": "plant" },
  { "word": "කෘතනි", "meaning": "කරගස", "category": "plant" },
  { "word": "කෘතනිම", "meaning": "රසඳුන්, පාංශු ලුණු, රෝම ලුණු, වනු වැල් කසායේ ලූ තුත්තම්", "category": "treatment" },
  { "word": "කෘත්තිමක", "meaning": "බලල්ලුණු", "category": "treatment" },

  // --- පිටුව 127 ---
  { "word": "කෘත්තිමදූප", "meaning": "දුම්මල", "category": "treatment" },
  { "word": "කෘත්තිමරත්න", "meaning": "කාච මැටි (පිදුරු වන්කරණ මැටි වගිය)", "category": "treatment" },
  { "word": "කෘත", "meaning": "බලල්ලුණු, ඉනිතියැට, රෝමලුණු, සඳුන්", "category": "treatment" },
  { "word": "කෘතක", "meaning": "බලල්ලුණු, රෝමලුණු", "category": "treatment" },
  { "word": "කෘතඤ්ඤි", "meaning": "ලෝකඩ", "category": "treatment" },
  { "word": "කෘතවිනි", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "කෘතප්‍රාභා", "meaning": "බැමිනිරිය (බුනුවිල)", "category": "plant" },
  { "word": "කෘතපර්ණිකා", "meaning": "කඩුවෙලග, උග්‍රරස්ස", "category": "plant" },
  { "word": "කෘතපිණ්ඩිති", "meaning": "ගල්සෙවෙල්", "category": "plant" },
  { "word": "කෘතඵල", "meaning": "කිණිහිරි, ඇසල, නාකුල්", "category": "plant" },
  { "word": "කෘතමාල", "meaning": "ඇසල", "category": "plant" },
  { "word": "කෘතමාලක", "meaning": "ඇසලූ", "category": "plant" },
  { "word": "කෘතමාලා", "meaning": "ඇසලූ", "category": "plant" },
  { "word": "කෘතමාලී", "meaning": "පිටවක්කා (නවතාලිලිය)", "category": "plant" },
  { "word": "කෘතමෙදක", "meaning": "තියන්වැටකොළු", "category": "plant" },
  { "word": "කෘතර", "meaning": "රෝමලුණු", "category": "treatment" },
  { "word": "කෘතරොහිණී", "meaning": "කිඳි, (රසකිඳ)", "category": "plant" },
  { "word": "කෘතව", "meaning": "අත්තන, දන්ත", "category": "plant" },
  { "word": "කෘතවාච", "meaning": "කෝමාරිකා", "category": "plant" },
  { "word": "කෘතවෙදක", "meaning": "වැටකොළු", "category": "plant" },
  { "word": "කෘතවෙදන", "meaning": "තියන්වැටකොළු, ඇසල, මුන්ඳි", "category": "plant" },
  { "word": "කෘතාජ්ජලී", "meaning": "නිදිකුම්බා", "category": "plant" },
  { "word": "කෘතාන්ත", "meaning": "ශරීරයේ සප්තධාතු", "category": "treatment" },
  { "word": "කෘති", "meaning": "රෝමලුණු", "category": "treatment" },
  { "word": "කෘත්‍රිම", "meaning": "පාංශුලුණු, වෙනිවැල් කසායේ ලූ තුත්තම්", "category": "treatment" },
  { "word": "කෘත්‍රිමක", "meaning": "බලල්ලුණු", "category": "treatment" },
  { "word": "කෘමිකණ්ටක", "meaning": "වලගසල්, දිවුල් ගස, (අත්තික්කා) නිවුල් ගස", "category": "plant" },
  { "word": "කෘමිකා", "meaning": "ග්‍රන්ථපර්ණී වාක්‍යය", "category": "plant" },
  { "word": "කෘමිගුහා", "meaning": "නියඟරා, කැකිරි, මහ ගොත්සුතු කැකිරි", "category": "plant" },
  { "word": "කෘමිජන", "meaning": "දිවුල්, අත්තික්කා, වලගසල්, කුකුරුමුවන්, ගබ්කෑ, කසා, කැල, එරබදු", "category": "plant" },
  { "word": "කෘමිජාතින්", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කෘමිජිත්", "meaning": "දුම්බලා වාක්‍යය", "category": "plant" },
  { "word": "කෘමිජ්ඤා", "meaning": "අඟිල්, ලෝකඩ, සඳුන්", "category": "treatment" },
  { "word": "කෘමිධ", "meaning": "අගිල්", "category": "plant" },
  { "word": "කෘමිදන්න", "meaning": "දන්ත රෝගයක්", "category": "symptom" },
  { "word": "කෘමිද්විෂා", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කෘමිනාශිනී", "meaning": "අසමෝදගම්", "category": "plant" },
  { "word": "කෘමිඵල", "meaning": "අත්තික්කා (දිවුල්)", "category": "plant" },
  { "word": "කෘමිමුල", "meaning": "පුවක් ගස", "category": "plant" },
  { "word": "කෘමිමුලී", "meaning": "මුහුණමල් ගස", "category": "plant" },
  { "word": "කෘමිරිපු", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කෘමිලක", "meaning": "වල්ළුමු, මුං", "category": "plant" },
  { "word": "කෘමිලා", "meaning": "දේවදාර", "category": "plant" },
  { "word": "කෘමිවක්ය", "meaning": "වල් අබ වෙසෙසක්", "category": "plant" },
  { "word": "කෘමිශත්‍රැ", "meaning": "එරබදු ගස, වලගසල්", "category": "plant" },
  { "word": "කෘමිශාත්‍රව", "meaning": "ඉඟුරා, ගුරැන්ද", "category": "plant" },
  { "word": "කෘමිහ", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කෘමිහර", "meaning": "වලගසල්", "category": "plant" },
  { "word": "කෘශගාබා", "meaning": "පැපිලිය", "category": "plant" },
  { "word": "කෘශාංගි", "meaning": "පුවඟු", "category": "plant" },
  { "word": "කෘශාසන", "meaning": "තිප්පිලි, කරඹ, කලු අගිල්, බෙරා, කළුදුරු, සාරණ, මුද්රප්පලම්, පැපිලිය, කවෙළු, පත්පාඩගම්, මහ අබ, කඩුකරෝෂණ, මිරිස්, බෝදි ඇට, නීලාංජන, කිරිබදු, මුරංගා, කාන්තම්, යබොර, යකඩ, කලුතලා, සුවඳකොට්ටම්", "category": "treatment" },
  { "word": "කෘශාත්", "meaning": "රත්නිවුල්", "category": "plant" },
  { "word": "කෘශිකා", "meaning": "මීකන්පලා (මූෂිකපර්ණී)", "category": "plant" },

  // --- පිටුව 128 ---
  { "word": "කෘෂීවල", "meaning": "ගුරැල්ල ගස", "category": "plant" },
  { "word": "කෘශොදරි", "meaning": "ඉරමුසු", "category": "plant" },
  { "word": "කෘෂණ", "meaning": "මුරංගා, මිරිස්, කාන්තම්, යකඩ, තිප්පිලි, කරඹ, උදින්දු මුණු, අගිල්", "category": "treatment" },
  { "word": "කෘෂණක", "meaning": "අබ, කලු අබ, වලඟසාල්, කලුමුං", "category": "plant" },
  { "word": "කෘෂණකඤ්චුක", "meaning": "කලුසන්නි", "category": "symptom" },
  { "word": "කෘෂණකඤ්ජු", "meaning": "රත්පුල්", "category": "plant" },
  { "word": "කෘෂණකවීර", "meaning": "නිල් කණේරු", "category": "plant" },
  { "word": "කෘෂණකාතරා", "meaning": "රත්හුනිද", "category": "plant" },
  { "word": "කෘෂණකාන්තා", "meaning": "යකඩ, කාන්තම්", "category": "treatment" },
  { "word": "කෘෂණකාෂ්ට", "meaning": "කලාඳුරු, කලු අගිල්", "category": "plant" },
  { "word": "කෘෂණකාස", "meaning": "හල්ගස", "category": "plant" },
  { "word": "කෘෂණකුබේරක", "meaning": "කළුවන් තලා", "category": "plant" },
  { "word": "කෘෂණකුලත්ථිකා", "meaning": "වල්කොල්ලු", "category": "plant" },
  { "word": "කෘෂණකුසුම", "meaning": "නිල් මල් ඇති කණේරු ගස", "category": "plant" },
  { "word": "කෘෂණකෙලි", "meaning": "වනුක්, සෙන්දිරික්කා", "category": "plant" },
  { "word": "කෘෂණකබ", "meaning": "තල් ගස", "category": "plant" },
  { "word": "කෘෂණබල්ව", "meaning": "කලුකොල්ලු", "category": "plant" },
  { "word": "කෘෂණගත රෝග", "meaning": "ඇසේ රෝග", "category": "symptom" },
  { "word": "කෘෂණගබ්", "meaning": "කරබෙයියා, වැල්මුරංගා", "category": "plant" },
  { "word": "කෘෂණගෘහී", "meaning": "ඇත්දෙමට, කරබෙයියා", "category": "plant" },
  { "word": "කෘෂණගොකර්ණී", "meaning": "නිල් මල් ඇති මුරුවා වැල්", "category": "plant" },
  { "word": "කෘෂණගොවරා", "meaning": "බටු, හෙලබටු", "category": "plant" },
  { "word": "කෘෂණචක්‍ෂුක", "meaning": "කබල", "category": "treatment" },
  { "word": "කෘෂණචන්දන", "meaning": "රන්වන් සඳුන්, සුදු හඳුන්", "category": "plant" },
  { "word": "කෘෂණචිත්‍රක", "meaning": "නිල් නෙබුල්", "category": "plant" },
  { "word": "කෘෂණචූඩිකා", "meaning": "හුනිද", "category": "plant" },
  { "word": "කෘෂණචූර්ණී", "meaning": "යහුණු (යකඩ සුණු) යකඩමල", "category": "treatment" },
  { "word": "කෘෂණචූර්ණක", "meaning": "කබල ගස", "category": "plant" },
  { "word": "කෘෂණජිහ්ව", "meaning": "කලුඅගිල්", "category": "plant" },
  { "word": "කෘෂණජපටා", "meaning": "ජටාමාංශ, ජටාමකුට", "category": "plant" },
  { "word": "කෘෂණජයනි", "meaning": "කළුවන් නිතිග ගස", "category": "plant" },
  { "word": "කෘෂණජීර", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කෘෂණජීරක", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කෘෂණජව", "meaning": "මුහුණමල් ගස", "category": "plant" },
  { "word": "කෘෂණතණ්ඩූලා", "meaning": "වලඟසාල්, තිප්පිලි", "category": "plant" },
  { "word": "කෘෂණතරු", "meaning": "කරබෙයියා (කරපිංචා)", "category": "plant" },
  { "word": "කෘෂණතාම", "meaning": "ගෝශීර්ෂ චන්දන = (ගෝ ශී සඳුන්)", "category": "plant" },
  { "word": "කෘෂණනිල", "meaning": "කලුතල", "category": "plant" },
  { "word": "කෘෂණතික්‍ෂණා", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කෘෂණතුලසී", "meaning": "කලුතලා, තලාගස", "category": "plant" },
  { "word": "කෘෂණත්‍රිවෘතා", "meaning": "කලු ත්‍රස්තවාලු", "category": "plant" },
  { "word": "කෘෂණදන්තා", "meaning": "ඇත්දෙමට ගස", "category": "plant" },
  { "word": "කෘෂණදන්තූරක", "meaning": "කලුඅත්තන ගස", "category": "plant" },
  { "word": "කෘෂණධුස්තූර", "meaning": "කලු අත්තන", "category": "plant" },
  { "word": "කෘෂණධූතූර", "meaning": "කලු තුත්බෝ අත්තන", "category": "plant" },
  { "word": "කෘෂණනිම්බක", "meaning": "කරපිංචා ගස", "category": "plant" },
  { "word": "කෘෂණනිම්බ", "meaning": "වල්පෙනෙල", "category": "plant" },
  { "word": "කෘෂණනිර්වගුණ්ඩී", "meaning": "කලුනික", "category": "plant" },
  { "word": "කෘෂණපර්ණී", "meaning": "කලුතලා", "category": "plant" },
  { "word": "කෘෂණපල්ලවා", "meaning": "කලු නිමිතිවල", "category": "plant" },
  { "word": "කෘෂණපාක", "meaning": "සිහින්තඹර, කරඹ ගස", "category": "plant" },
  { "word": "කෘෂණපාකඵල", "meaning": "කරඹගෙඩි", "category": "plant" },
  { "word": "කෘෂණපාටලා", "meaning": "පලොල්, එල පලොල්", "category": "plant" },
  { "word": "කෘෂණපාද", "meaning": "කළුකැම්මේරිය", "category": "plant" },
  { "word": "කෘෂ්ණඵල", "meaning": "ඇත්දෙමටගෙඩි, බෝදි ඇට", "category": "plant" },

  // --- පිටුව 129 ---
  { "word": "කෘෂ්ණපිණ්ඩිත්ක", "meaning": "කුකුරුමුවන්", "category": "plant" },
  { "word": "කෘෂ්ණපුෂ්පී", "meaning": "පුවඟු ගස", "category": "plant" },
  { "word": "කෘෂ්ණපුෂ්ප", "meaning": "කලු අත්තන", "category": "plant" },
  { "word": "කෘෂ්ණපුනීලා", "meaning": "පුවඟු ගස", "category": "plant" },
  { "word": "කෘෂ්ණපූජී", "meaning": "කලුඉඟුරු", "category": "plant" },
  { "word": "කෘෂ්ණප්‍රිය", "meaning": "කොලොම් ගස", "category": "plant" },
  { "word": "කෘෂ්ණඵලපාක", "meaning": "සිහින් කරඹ", "category": "plant" },
  { "word": "කෘෂ්ණඵලා", "meaning": "කරඹ, බෝදි ඇට, මාගස", "category": "plant" },
  { "word": "කෘෂ්ණබර්බර", "meaning": "කළුවන් වේලාගස", "category": "plant" },
  { "word": "කෘෂ්ණබලා", "meaning": "හුනිද (ඔලිඳ)", "category": "plant" },
  { "word": "කෘෂ්ණබීජ", "meaning": "රක්තමුරංගා, මුරංගා ඇට", "category": "plant" },
  { "word": "කෘෂ්ණභූහෘහවා", "meaning": "කරිවිලවැල්", "category": "plant" },
  { "word": "කෘෂ්ණභූකුෂ්මාණ්ඩ", "meaning": "කළුවත් නැටි හා කොළ ඇති කිරි බදු (කලු කිරිබදු)", "category": "plant" },
  { "word": "කෘෂ්ණභූෂණ", "meaning": "ගම්මිරිස්", "category": "plant" },
  { "word": "කෘෂ්ණභේද", "meaning": "කුමරන්, කඩුකරෝෂණ", "category": "plant" },
  { "word": "කෘෂ්ණභේදකා", "meaning": "කුමරන්, (කඩුකරෝෂණ) කලු ඊයම්", "category": "treatment" },
  { "word": "කෘෂ්ණමඤ්ජරිකා", "meaning": "කලුතලා, අක්මැල්ල, කලුකැම්මේරිය", "category": "plant" },
  { "word": "කෘෂ්ණමඤ්ජරී", "meaning": "කලුතලා", "category": "plant" },
  { "word": "කෘෂ්ණමනස්ස", "meaning": "ලෝලු, කළුමඟ", "category": "plant" },
  { "word": "කෘෂ්ණමදන", "meaning": "කලු කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "කෘෂ්ණමල්ලිකා", "meaning": "අක්මැල්ල, කලුතලා", "category": "plant" },
  { "word": "කෘෂ්ණමාෂ", "meaning": "කළු මෑ", "category": "plant" },
  { "word": "කෘෂ්ණමාලකා", "meaning": "අක්මැල්ල, කලුතලා", "category": "plant" },
  { "word": "කෘෂ්ණමාස", "meaning": "කලු මෑ", "category": "plant" },
  { "word": "කෘෂ්ණමුඛා", "meaning": "කලු ඉරමුසු වැල්", "category": "plant" },
  { "word": "කෘෂ්ණමුද්ග", "meaning": "කලුමුං", "category": "plant" },
  { "word": "කෘෂ්ණමූලා", "meaning": "නික්මුසු", "category": "plant" },
  { "word": "කෘෂ්ණමූලී", "meaning": "ඉරමුසු, කලුඉරමුසු", "category": "plant" },
  { "word": "කෘෂ්ණමුෂ්ක", "meaning": "තෙලඹු ගස", "category": "plant" },
  { "word": "කෘෂ්ණමෙචක", "meaning": "කලු ලුණු", "category": "treatment" },
  { "word": "කෘෂ්ණමෙද", "meaning": "කලු හිඹුරා", "category": "plant" },
  { "word": "කෘෂ්ණමෙදි", "meaning": "කඩුකරෝභණ (කුල රුණ)", "category": "plant" },
  { "word": "කෘෂ්ණමෙඝ", "meaning": "ප්‍රමේහ රෝගයක්", "category": "symptom" },
  { "word": "කෘෂ්ණයෂ්ටිකා", "meaning": "කලු සැට දූ හාල්", "category": "plant" },
  { "word": "කෘෂ්ණරත්නිකා", "meaning": "හුනිද, (ඔලිඳ)", "category": "plant" },
  { "word": "කෘෂ්ණරාජ", "meaning": "කළුවන් මුරංගා ගස", "category": "plant" },
  { "word": "කෘෂ්ණරාජිකා", "meaning": "අබ", "category": "plant" },
  { "word": "කෘෂ්ණරාහ", "meaning": "ආපස්සුමුදු", "category": "plant" },
  { "word": "කෘෂ්ණලවණ", "meaning": "කලු ලුණු, සුවස ලුණු", "category": "treatment" },
  { "word": "කෘෂ්ණලා", "meaning": "හුනිද (ඔලිඳ)", "category": "plant" },
  { "word": "කෘෂ්ණලෝචක", "meaning": "හුනිද (ඔලිඳ)", "category": "plant" },
  { "word": "කෘෂ්ණලෝහ", "meaning": "යකඩ, කාන්තම්", "category": "treatment" },
  { "word": "කෘෂ්ණවර්ණ", "meaning": "කස්තුරි, කරාබුනැටි, කලු අගිල්", "category": "treatment" },
  { "word": "කෘෂ්ණවල්ලී", "meaning": "කවතලා, අක්මැල්ල, ඉරමුසු", "category": "plant" },
  { "word": "කෘෂ්ණවල්ලිකා", "meaning": "ආපස්සුමුදු", "category": "plant" },
  { "word": "කෘෂ්ණවාක්", "meaning": "මස්වන්න", "category": "plant" },
  { "word": "කෘෂ්ණවායස", "meaning": "අගිල්", "category": "plant" },
  { "word": "කෘෂ්ණවාලුකා", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "කෘෂ්ණවාසා", "meaning": "ඇසතු (ඇසතු = ආහප්‍ර)", "category": "plant" },
  { "word": "කෘෂ්ණවිජ", "meaning": "කොසඹ, රත්මුරංගා", "category": "plant" },
  { "word": "කෘෂ්ණවෘක්‍ෂ", "meaning": "පියාගස, කලු අගිල්, කළුහිර", "category": "plant" },
  { "word": "කෘෂ්ණවෘන්තා", "meaning": "මස්වන්න, කුඹුරු වැල්, පලොල්, රත් පලොල්", "category": "plant" },
  { "word": "කෘෂ්ණවෘන්තා", "meaning": "පලොල්, කුඹුරු වැල්, උඳුපියලි", "category": "plant" },
  { "word": "කෘෂ්ණවෘන්තිකිකා", "meaning": "ඇත්දෙමට", "category": "plant" },
  { "word": "කෘෂ්ණව්‍රීහි", "meaning": "කලු වෙල්හාල්", "category": "plant" },

  // --- පිටුව 130 ---
  {
    "word": "කෘෂ්ණවෘන්තිකා",
    "meaning": "දෙමට - ඇත්දෙමට යයි දෙමට වගී දෙකකි. ඇත්දෙමට ගස රත් කෑන්ද ගසක් වැනි විශාල ගසකි. මේ වගියේ කඳ සුදු පාටය. මල් හැඩහුරුකමින් හා වර්ණයෙන් එක සමාන ය. ඇත්දෙමට මහා පස් මූලෙන් එකකි. මේ වගියේ මුල් වල පොතු දඟ මුල් කෂාය ඇතුළු වාතාබාධ, අජීර්ණ හා උණ නැසීම පිණිස සාදා ගන්නා කෂාය වලට යොදති. ඇත්දෙමට පොතුවල සාරය ආමාශය ශක්තිමත් කරණ මුත්‍රකාරක ඖෂධයකි.",
    "category": "plant"
  },
  { "word": "කෘෂ්ණවේතනා", "meaning": "පලොල් ගස", "category": "plant" },
  { "word": "කෘෂ්ණශාඛා", "meaning": "කලු අගිල්", "category": "plant" },
  { "word": "කෘෂ්ණශිග්‍රැ", "meaning": "මුරංගා ගස", "category": "plant" },
  { "word": "කෘෂ්ණශිඛා", "meaning": "කලු ඊයම්, අගිල්", "category": "treatment" },
  { "word": "කෘෂ්ණශෛරියක", "meaning": "කළුවන් මල් ඇති ගිරිනීල්ල", "category": "plant" },
  { "word": "කෘෂ්ණසක", "meaning": "කොලොම් ගස", "category": "plant" },
  { "word": "කෘෂ්ණසංඥක", "meaning": "සුවස ලුණු", "category": "treatment" },
  { "word": "කෘෂ්ණසය", "meaning": "කුඹුක් ගස", "category": "plant" },
  { "word": "කෘෂ්ණසබ", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කෘෂ්ණසර්පන", "meaning": "මුරංගා ගස", "category": "plant" },
  { "word": "කෘෂ්ණසම්භ", "meaning": "කලු අබ, මහ අබ", "category": "plant" },
  { "word": "කෘෂ්ණසාක", "meaning": "පැපිලිය, (පත්පාඩගම්)", "category": "plant" },
  { "word": "කෘෂ්ණසාර", "meaning": "දැක් ගස, ඇටිපේරිය, කිහිරි", "category": "plant" },
  { "word": "කෘෂ්ණසාරංග", "meaning": "ඇටිපේරිය", "category": "plant" },
  { "word": "කෘෂ්ණසාරධී", "meaning": "ඇවට්ඨිය, (ගිරිසපා)", "category": "plant" },
  { "word": "කෘෂ්ණසාරිවා", "meaning": "කලුහිරමුසු", "category": "plant" },
  { "word": "කෘෂ්ණසින්ධුවාර", "meaning": "කලුනික", "category": "plant" },

  // --- පිටුව 131 ---
  { "word": "කෘෂ්ණසීසක", "meaning": "කලු ඊයම්", "category": "treatment" },
  { "word": "කෘෂ්ණසූක්‍ෂමඵලා", "meaning": "ඉරමුසු වෙසෙසක්", "category": "plant" },
  { "word": "කෘෂ්ණසූක්‍ෂිපීඵලා", "meaning": "වෙලිප්පරිත්ති (මස්බැද්ද) සිහින් මැඩගු", "category": "plant" },
  { "word": "කෘෂ්ණසූරිය", "meaning": "හලා", "category": "plant" },
  { "word": "කෘෂ්ණස්‍රොත", "meaning": "රසඳුන්", "category": "treatment" },
  { "word": "කෘෂ්ණහෙමක", "meaning": "මිණීරන්", "category": "treatment" },
  { "word": "කෘෂ්ණා", "meaning": "කලු ලුණු, සිහින් මස්බැද්ද, යකඩ, තිප්පිලි, කරඹ, උඳුපියලි, අගිල්, සාරණ", "category": "treatment" },
  { "word": "කෘෂ්ණාබ්‍යා", "meaning": "නිල් සාරණ", "category": "plant" },
  { "word": "කෘෂ්ණාගුරු", "meaning": "කලුඅගිල්", "category": "plant" },
  { "word": "කෘෂ්ණාජටා", "meaning": "තිප්පිලිමුල්", "category": "plant" },
  { "word": "කෘෂ්ණාජ්ජී", "meaning": "කළුදුරු", "category": "plant" },
  { "word": "කෘෂ්ණාඩ්කි", "meaning": "කලු මල් ඇති රට තෝර ගස", "category": "plant" },
  { "word": "කෘෂ්ණාභා", "meaning": "කලුකපු ගස", "category": "plant" },
  { "word": "කෘෂ්ණාමල", "meaning": "කාන්තම්", "category": "treatment" },
  { "word": "කෘෂ්ණාමුල", "meaning": "තිප්පිලි මුල්", "category": "plant" },
  { "word": "කෘෂ්ණායස", "meaning": "යකඩ, කාන්තම්", "category": "treatment" },
  { "word": "කෘෂ්ණාර්ජිත", "meaning": "නිටෝල් ගස", "category": "plant" },
  { "word": "කෘෂ්ණාර්ක", "meaning": "අක්මැල්ල", "category": "plant" },
  { "word": "කෘෂ්ණාරි", "meaning": "පැපිලිය (පත්පාඩගම්)", "category": "plant" },
  { "word": "කෘෂ්ණාලක", "meaning": "හුනිද (ඔලිඳ)", "category": "plant" },
  { "word": "කෘෂ්ණාලා", "meaning": "හුනිද (ඔලිඳ)", "category": "plant" },
  { "word": "කෘෂ්ණාවාස", "meaning": "ඇසතු, බෝගස", "category": "plant" },
  { "word": "කෘෂ්ණිකා", "meaning": "හීඟ අබ, කළුවැල්, තලා", "category": "plant" },
  { "word": "කෘෂ්ණේක්ෂු", "meaning": "කලු උක් ගස", "category": "plant" },
  { "word": "කෘෂ්ණෝදුම්බරිකා", "meaning": "කොවඩිබුලා ගස", "category": "plant" },
  { "word": "කෘසගෝ", "meaning": "බුළු ගස", "category": "plant" },
  { "word": "කේ", "meaning": "දුනුවැක්ේ, වැටකේ (කේතකි)", "category": "plant" },
  { "word": "කේපාලි", "meaning": "පුවඟු ගස", "category": "plant" },
  { "word": "කේපානුගා", "meaning": "සිහින් මිදි", "category": "plant" },
  { "word": "කේපාතක", "meaning": "රෝමලුණු", "category": "treatment" },
  { "word": "කෙම", "meaning": "එලවරා, මහ සාරණ, අස්බැවිල, මුරංගා, සුලුකුමුක්, කලුරන්, බදුල්ල", "category": "treatment" },
  { "word": "කෙමරබක", "meaning": "වරාමල්", "category": "plant" },
  { "word": "කේරොහිණී", "meaning": "කිඳි, රසකිඳ", "category": "plant" },
  { "word": "කෛපතඹුරු", "meaning": "තූරක්නෙල් (තූරක්ෂක නම් සුගන්ධ ද්‍රව්‍යය - ඉඳුසල් ලාටු)", "category": "treatment" },
  { "word": "කේ", "meaning": "වැටකේ, දුනුවැටකේ", "category": "plant" },
  { "word": "කේකිශිඛා", "meaning": "මොණර කුඩුම්බිය", "category": "plant" },
  { "word": "කෙකේඅරලු", "meaning": "වැටකේමුල් (වැටකේ ගස්වල ඉහළ සිට පහතට ඇදෙන අටුවන්)", "category": "plant" },
  { "word": "කේමුල්", "meaning": "වැටකේමුල්", "category": "plant" },
  { "word": "කෙහෙමුල්", "meaning": "කෙහෙඇටුවන්", "category": "plant" },
  { "word": "කේවුක", "meaning": "ගෝවාගස", "category": "plant" },
  { "word": "කෙවට්ට", "meaning": "වාකබො - වල් සුවඳැල් (ඉඳුන විට ගෙඩි කඩා හැලෙන තද ගතියකින් යුත් සුවඳැල් වලට සමාන කෙසෙල් වගිය)", "category": "plant" },
  { "word": "කේතන් බෑවිල", "meaning": "කොටිකන් බෑවිල", "category": "plant" },
  { "word": "කේවේරි", "meaning": "කෙටේරිය, පොරව", "category": "treatment" },
  { "word": "කේත", "meaning": "තූරක්නෙල්", "category": "plant" },
  { "word": "කේතක", "meaning": "වැටකේගස, වැටකේමල", "category": "plant" },
  { "word": "කේතකි", "meaning": "වැටකේ, මුහුදු වැටකේ", "category": "plant" },
  { "word": "කේතු", "meaning": "සිහින්මිදි", "category": "plant" },
  { "word": "කේදාරජ", "meaning": "පද්මකාෂ්ඨ", "category": "treatment" },
  { "word": "කෙඳකම", "meaning": "ගන්ධක (ගෙන්දගම්)", "category": "treatment" },
  { "word": "කෙළක", "meaning": "කිහිරි ගස, කුකුරුමුවන් ගස", "category": "plant" },
  { "word": "කෙඳුඵල", "meaning": "නිඹිරිගෙඩි", "category": "plant" },
  { "word": "කෙඳු", "meaning": "කොමඩු", "category": "plant" },
  { "word": "කෙනෙරසම්", "meaning": "ඇත්සම්", "category": "treatment" },

  // --- පිටුව 132 ---
  { "word": "කෙප්ප", "meaning": "වාතරෝගයක්", "category": "symptom" },
  { "word": "කෙප්පානෙක", "meaning": "කුප්පමේනිය", "category": "plant" },
  { "word": "කෙප්පෙ", "meaning": "කුරහන් (සිහින් ධාන්‍ය වගියක්)", "category": "plant" },
  { "word": "කෙමී", "meaning": "කෝවක්කා", "category": "plant" },
  { "word": "කෙමිකොළ", "meaning": "නිවිතිකොළ (කෝවක්කා කොළ)", "category": "plant" },
  { "word": "කෙමිටෙඩි", "meaning": "ඉදුනු කෝවක්කාගෙඩි", "category": "plant" },
  { "word": "කෙමිපා", "meaning": "කුප්පමේනිය", "category": "plant" },
  { "word": "කෙමිපන්", "meaning": "ගල්කුනර (කෙමි) වල එකතු වන ජලය", "category": "treatment" },
  { "word": "කෙම්බිජු", "meaning": "කෝවක්කා ඇට", "category": "plant" },
  { "word": "කෙම්බු", "meaning": "ගෝවා", "category": "plant" },
  { "word": "කෙම්වැල්", "meaning": "කෝවක්කා වැල්", "category": "plant" },
  { "word": "කෙම්බ්‍ර", "meaning": "දෙමට", "category": "plant" },
  { "word": "කෙමිලි", "meaning": "මුද්දරප්පලම්", "category": "plant" },
  { "word": "කෙම්", "meaning": "පිස්සුකෙම්", "category": "treatment" },
  { "word": "කෙමුක", "meaning": "කිහිරි, තෙබු, ගෝවා", "category": "plant" },
  { "word": "කෙයරකපුකා", "meaning": "කඩුකරෝෂණී (කුලරුණ)", "category": "plant" },
  { "word": "කෙයරමප්", "meaning": "පෝලිපි (පාලමද)", "category": "plant" },
  { "word": "කෙයරල", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "කෙයරව", "meaning": "ඇඹුල", "category": "plant" },
  { "word": "කෙයූර්පත්‍රා", "meaning": "වැටකේ", "category": "plant" },
  { "word": "කෙර්", "meaning": "පොල්, මිණීරන්", "category": "treatment" },
  { "word": "කෙල්", "meaning": "කෙසෙල්", "category": "plant" },
  { "word": "කෙල්නාර", "meaning": "ගල්සෙවෙල්", "category": "plant" },
  { "word": "කෙලට", "meaning": "වනුප් ඇට", "category": "plant" },
  { "word": "කෙලටක", "meaning": "ගෝවා අල", "category": "plant" },
  { "word": "කෙලික", "meaning": "හෝපලු, අශෝක, දියරක්තබලා", "category": "plant" },
  { "word": "කෙලිකදම්බ", "meaning": "බක්මී ගස", "category": "plant" },
  { "word": "කෙලිගන්ත", "meaning": "කුඹුක්", "category": "plant" },
  { "word": "කෙලින්චි", "meaning": "පීල", "category": "treatment" },
  { "word": "කෙලිපත්‍රා", "meaning": "වැටකේ", "category": "plant" },
  { "word": "කෙලි", "meaning": "පොල්", "category": "plant" },
  { "word": "කෙවිලි", "meaning": "තැඹිලි", "category": "plant" },
  { "word": "කෙවලද්‍රව්‍ය", "meaning": "ගම්මිරිස්", "category": "plant" },
  { "word": "කෙවල වෙල්ල", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "කෙග", "meaning": "නෙල්ලි, ඇඹුලගුල, හිඹේර, ලුණු වරණ", "category": "plant" },
  { "word": "කෙගකාර", "meaning": "උක්වෙසෙසක්", "category": "plant" },
  { "word": "කෙගට", "meaning": "තොවිල ගස", "category": "plant" },
  { "word": "කෙගනාමිත්", "meaning": "ප්‍රිවේර", "category": "treatment" },
  { "word": "කෙගනාමා", "meaning": "ප්‍රිවේර", "category": "treatment" },
  { "word": "කෙගනාමිකා", "meaning": "ප්‍රිවේර", "category": "treatment" },
  { "word": "කෙගපර්ණී", "meaning": "කරල්සැබෝ", "category": "plant" },
  { "word": "කෙගපර්ණිකා", "meaning": "කරල්සැබ", "category": "plant" },
  { "word": "කෙගපර්ණිකා", "meaning": "හෙල කරල්සැබ", "category": "plant" },
  { "word": "කෙගමුන්නි", "meaning": "සැම ගස්", "category": "plant" },
  { "word": "කෙගමුංජක", "meaning": "දුම්මැල්ල", "category": "plant" },
  { "word": "කෙගමුෂ්ටි", "meaning": "රේරාගස්, වල්කොසඹ", "category": "plant" },
  { "word": "කෙගමුෂ්ටිකා", "meaning": "කොසඹ, මහකොසඹ", "category": "plant" },
  { "word": "කෙගර", "meaning": "පෙරුම්කායම්, මල්කාසිස, පොල්, දඹ, නාගස, නාමල් රේණු, පිටවක්කා, මුහුණමල්, සාදිලිංගම්, රත්රන්", "category": "treatment" },
  { "word": "කෙගරබ්බ", "meaning": "එන්සාල්, එල්වල්ලු, කිරිදිිය", "category": "plant" },
  { "word": "කෙගරබිගිනි", "meaning": "ගොඩමානෙල්", "category": "plant" },
  { "word": "කෙගරංජනක", "meaning": "නිල්කටුකරඹු, වේලා, ගිරිනීල්ල, කිිකිරිදිය", "category": "plant" },
  { "word": "කෙගරා", "meaning": "මහ කලාඳුරු", "category": "plant" },
  { "word": "කෙගරාජ", "meaning": "කිිකිරිදිය, රත් වන් කිිකිරිදිය", "category": "plant" },
  { "word": "කෙගරාමිල", "meaning": "ලප්තාරන් ගස", "category": "plant" },
  { "word": "කෙගරාහ්ව", "meaning": "ප්‍රිවේර", "category": "treatment" },
  { "word": "කෙගරි", "meaning": "වැල්මුරංගා, මුරංගා, නාකෙසුරු", "category": "plant" },
  { "word": "කෙගරිකා", "meaning": "මහබැවිල", "category": "plant" },
  { "word": "කෙගරින්", "meaning": "නාගස, දඹ, නෙළුම්", "category": "plant" },
  { "word": "කෙගරී", "meaning": "රත් මුරංගා", "category": "plant" },
  { "word": "කෙගරෑපා", "meaning": "පිළිල (ඉටිකෙසෙල්)", "category": "plant" },

  // --- පිටුව 133 ---
  { "word": "කෙගරෑහා", "meaning": "දන්ත, මහදන්ත, මගුල්කුඹුරුගෙත්ත, මහබැවිල, කිිකිරිදිය", "category": "plant" },
  { "word": "කෙගරැස්ක", "meaning": "ඇත්තෝර ගස", "category": "plant" },
  { "word": "කෙගව", "meaning": "කින දෙඹ ගස, නාගස", "category": "plant" },
  { "word": "කෙගවප්‍රියා", "meaning": "ඝෝරෝචන", "category": "treatment" },
  { "word": "කෙගවර්ධිනි", "meaning": "මිගුල්කුඹුරුවැන්න, මහ බැවිල, ගොඩමානෙල්", "category": "plant" },
  { "word": "කෙගවායුධ", "meaning": "අඹගස", "category": "plant" },
  { "word": "කෙගවාලාය", "meaning": "බෝගස", "category": "plant" },
  { "word": "කෙගවාවාස", "meaning": "බෝගස", "category": "plant" },
  { "word": "කෙගවන්තඵලා", "meaning": "සැමගස", "category": "plant" },
  { "word": "කෙශා", "meaning": "ජටාමාංශ", "category": "plant" },
  { "word": "කෙශාබ්ය", "meaning": "ප්‍රිවේර", "category": "treatment" },
  { "word": "කෙශාපාස", "meaning": "සැමරැක", "category": "plant" },
  { "word": "කෙශාරි", "meaning": "නාකෙසුරු ගස (නාගස)", "category": "plant" },
  { "word": "කෙශරාහ", "meaning": "ගොඩමානෙල්", "category": "plant" },
  { "word": "කෙශාලි", "meaning": "කිිකිරිදිය", "category": "plant" },
  { "word": "කෙශාහ්ව", "meaning": "ප්‍රිවේර", "category": "treatment" },
  { "word": "කෙගි", "meaning": "වැල්මී, යක්බේරිය, සාතාවාරිය, ජටාමාංශ, වරා, සක්නබ, සැමරැක", "category": "plant" },
  { "word": "කෙගිකා", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "කෙගිකා", "meaning": "යක්බේරිය, සාතාවාරිය", "category": "plant" },
  { "word": "කෙගිනී", "meaning": "හිඟුරුපියලි. වල්දෙහි, යක්බේරිය, ජටාමාංශ", "category": "plant" },
  { "word": "කෙග්‍ය", "meaning": "පියාගස, කලුඅගිල්, කිිකිරිදිය, රත්නිවුල්, ප්‍රිවේර", "category": "plant" },
  { "word": "කෙග්‍යඵල", "meaning": "මිණග, නික", "category": "plant" },
  { "word": "කෙෂ්ත්‍රකමෙබලා", "meaning": "පලොල්", "category": "plant" },
  { "word": "කෙෂක", "meaning": "ගුගුල්, කංසා ඇට", "category": "plant" },
  { "word": "කෙසරවර", "meaning": "කොකුම්", "category": "plant" },
  { "word": "කෙසරසතු", "meaning": "එබරතෙල්", "category": "treatment" },
  { "word": "කෙසර", "meaning": "මුණමල්, මල් රේණු, එරබදුතෙල්", "category": "plant" },
  { "word": "කෙසරොච්චටා", "meaning": "වම්මුතු", "category": "plant" },
  { "word": "කේසුර", "meaning": "කෙකටිය", "category": "plant" },
  { "word": "කෙසෙල්", "meaning": "කෙසෙල් = කදලි (මෝව)", "category": "plant" },
  { "word": "කෙනෙ අරව", "meaning": "වැටකේ ගසෙහි කඳෙන් ඇදෙන මුල්", "category": "plant" },
  { "word": "කෙතෙතලා", "meaning": "තලා වගියක්", "category": "plant" },
  { "word": "කෙහෙදිහෙව", "meaning": "කෙඳි හැර", "category": "treatment" },
  { "word": "කෙහෙලූම්", "meaning": "ඉසකෙස්", "category": "treatment" },
  { "word": "කෙලිද", "meaning": "කිරිවල්ලා වගියට ම අයත් ගසක්", "category": "plant" },

  // --- පිටුව 134 ---
  {
    "word": "කෙළිඳ",
    "meaning": "කිරිවල්ලා වගියට ම අයත් කෙළිඳ ගස ලංකාවේ ද මැනවින් වැවෙන බව පෙනේ. කෙළිඳ සුලභ නොවූ අවස්ථාවන්හි පැරණි ලාංකික වෛද්‍යවරයෝ ඒ වෙනුවට කිරිවල්ලා ගසෙන් ප්‍රයෝජන ගත්හ. කෙළිඳ කොළ දිග පළලින් අඟල් 6 x 2 1/2 ක් පමණ ඇත. මල් රතු සහ සුදු වශයෙන් කෙළිඳ දෙවගියක් තිබෙන නමුත් ඖෂධ පිණිස පාවිච්චි කරන්නේ මල් සුදු වගිය පමණකි. කෙළිඳ ඇට සහ පොතු අතීසාරය, පිත්, සෙම්, පිපාස, ආම, හා කුෂ්ඨ රෝග නැති කිරීමට හිත යි.",
    "category": "plant"
  },
  { "word": "කේ", "meaning": "දුනුවැක්ේ, වැටකේ (කේතකි)", "category": "plant" },
  { "word": "කේතකී", "meaning": "වැටකේ", "category": "plant" },
  { "word": "කේතු", "meaning": "වැටකේ", "category": "plant" },
  { "word": "කේන්ද්‍ර", "meaning": "කොමඩු", "category": "plant" },
  { "word": "කේප්පේ", "meaning": "කුරක්කන් (කුරහන්)", "category": "plant" },
  { "word": "කේබුක", "meaning": "කෙබු", "category": "plant" },
  { "word": "කේර", "meaning": "මිණීරන්", "category": "treatment" },
  { "word": "කේරමජ", "meaning": "පෝලිපිනි", "category": "plant" },
  { "word": "කේගමුෂ්ටී", "meaning": "රේරා", "category": "plant" },
  { "word": "කේගකය", "meaning": "කන්සා", "category": "plant" },
  { "word": "කේශර ඉද්ද මූඩියන්සේ", "meaning": "කේශර බැවිල (රහස් බෙහෙත් වට්ටෝරුවක ඔසුවක්)", "category": "plant" },
  { "word": "කේශර", "meaning": "නාමල් රේණු, නාගස", "category": "plant" },
  { "word": "කෛ", "meaning": "කයිප්පු", "category": "treatment" },
  { "word": "කෛකෝඟුක", "meaning": "කැලමල", "category": "plant" },
  { "word": "කෛකක්ක", "meaning": "වැටකේ", "category": "plant" },
  { "word": "කෛකේගිකුලෙයි", "meaning": "කිිකිරිදිය", "category": "plant" },
  { "word": "කෛකඩව්‍ය", "meaning": "කපු ගස", "category": "plant" },
  { "word": "කෛකවප", "meaning": "කෙළිඳ ගස", "category": "plant" },
  { "word": "කෛකටයි", "meaning": "කොසඹ, බිංකොසඹ, ඇත්දෙමට, කුණුකරඳ, කුකුරුමුවන්", "category": "plant" },
  { "word": "කෛකණ්ඩය", "meaning": "කරපිංචා, ඇඹුල්වේ, සිරිල, කපු ගස", "category": "plant" },
  { "word": "කෛතන්ය", "meaning": "කිිකිරිදිය", "category": "plant" },
  { "word": "කෛතක", "meaning": "වැටකේ", "category": "plant" },
  { "word": "කෛතව", "meaning": "හෙල කුමුදු, අත්තන මල්", "category": "plant" },
  { "word": "කෛදාර", "meaning": "පද්මකාෂ්ඨ", "category": "treatment" },
  { "word": "කෛපිතා", "meaning": "කලුත්‍රස්තවාලු", "category": "plant" },
  { "word": "කෛයාන්ත කර", "meaning": "කිිකිරිදිය", "category": "plant" },
  { "word": "කෛයාන්තගය", "meaning": "කිිකිරිදිය", "category": "plant" },
  { "word": "කෛරලි", "meaning": "වලඟසාල්", "category": "plant" },
  { "word": "කෛරව", "meaning": "සුදු මානෙල්, විලඟසාල්", "category": "plant" }
];