// data_355_364.js - පිටු 355 සිට 364 දක්වා සියලුම වචන
const data_extra_355_364 = [
    // --- පිටුව 355 ---
    { "word": "මන්හෙල", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මනාශිලා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මන", "meaning": "ජටාමාංශ, මැණික්", "category": "plant" },
    { "word": "මනඅකිල්", "meaning": "සුවඳ අගිල්", "category": "plant" },
    { "word": "මනකප්", "meaning": "රිලවා", "category": "animal" },
    { "word": "මනකොට්ටම්", "meaning": "සුවඳ කොට්ටම්", "category": "plant" },
    { "word": "මනභගක", "meaning": "තුවරලා", "category": "plant" },
    { "word": "මනලෙ", "meaning": "දෙඩම්", "category": "plant" },
    { "word": "මනස්ශිල", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මනස්ශිලා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මනසෙලං", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මනසිල්", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මනාදෙක", "meaning": "පලම් 16", "category": "measurement" },
    { "word": "මතින්තක්කාලි", "meaning": "කළුකාම්මේරිය", "category": "plant" },
    { "word": "මනිබක", "meaning": "මැණික්කට්ටුව", "category": "anatomy" },
    { "word": "මනිපුෂ්පිකා", "meaning": "හෙළපිල ගස", "category": "plant" },
    { "word": "මනිරාගකර", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "මනිලත්", "meaning": "මුහුණගස්, (මුහුණ මල් ගස්)", "category": "plant" },
    { "word": "මනෝශිල", "meaning": "රත්හිරියල්", "category": "mineral" },
    { "word": "මනෝගුප්තා", "meaning": "රත්හිරියල්, මනෝසිල", "category": "mineral" },
    { "word": "මනෝප්", "meaning": "සුදුදුරු, මනෝසිල, ගෝලෝක", "category": "plant" },
    { "word": "මනෝප්ව", "meaning": "ලියනගලා", "category": "plant" },
    { "word": "මනෝපාන්තමනෝ", "meaning": "සල්ගස", "category": "plant" },
    { "word": "මනෝරමා", "meaning": "බටදම්, පුවඟු, කළුතිකා", "category": "plant" },
    { "word": "මනෝශෙල", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "මනෝහ්වා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "මනෝගමී", "meaning": "සින්නාරං", "category": "plant" },
    { "word": "මනෝහාර", "meaning": "නිල්බුලු", "category": "plant" },
    { "word": "මධුෂ්ටිලා", "meaning": "මිගස", "category": "plant" },
    { "word": "මබර", "meaning": "මීමැස්මොර (අපස්මාර = වස්මර)", "category": "treatment" },
    { "word": "මඹ", "meaning": "බක්මී", "category": "plant" },
    { "word": "මම්බ", "meaning": "බක්මීගස", "category": "plant" },
    { "word": "මමර", "meaning": "අපස්මාර", "category": "treatment" },
    { "word": "මමරාපා", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "මය", "meaning": "යකඩ", "category": "mineral" },
    { "word": "මයල", "meaning": "සුදු, රතු නෙළුම් දෙවගය", "category": "plant" },
    { "word": "මයසාර", "meaning": "වානේ", "category": "mineral" },
    { "word": "මසිරිය", "meaning": "සැබෝ", "category": "plant" },
    { "word": "මසිල්තුතු", "meaning": "පල්මාණික්කන්", "category": "mineral" },
    { "word": "මසිල්රෝවන", "meaning": "ගෝරෝචන", "category": "mineral" },
    { "word": "මයිල", "meaning": "මෙය මලිත (ධාතකී) නොවේ රත් කොබෝ ලීල ගසකට සමාන කොළ හා කරල් ඇති ගසකි. ඉදිරියෙහි මලිත ගැන ලියා ඇති විස්තරය බලන්න.", "category": "plant" },
    { "word": "මයිලබි කුරුඤ්ඤ", "meaning": "තුන්පත්කුරුඳු", "category": "plant" },
    { "word": "මයුර", "meaning": "හෙළසැබෝ, මොණරකුඩුම්බිය, පල්මාණික්කම්", "category": "plant" },
    { "word": "මයුරක", "meaning": "මොණරනල්, හෙළසැබෝ", "category": "plant" },
    { "word": "මයුරකහ", "meaning": "වේලාගස", "category": "plant" },
    { "word": "මයුරතර", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "මයුරකරක්", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "මයුරනල", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "මයුරගලකොසඹ", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "මයුරගිරි", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "මයුරග්‍රීවක", "meaning": "පල්මාණික්කම්", "category": "mineral" },
    { "word": "මයුරපක්‍ෂ", "meaning": "තොටිල", "category": "plant" },
    { "word": "මයුරතුත්තම්", "meaning": "මයුරතුතු", "category": "mineral" },
    { "word": "මයුරපක්‍ෂ(2)", "meaning": "මොණරපිල්", "category": "plant" },
    { "word": "මයුරපත්‍ර", "meaning": "මොණරකුඩුම්බිය", "category": "plant" },
    { "word": "මයුරශිඛා", "meaning": "මොණරකුඩුම්බිය", "category": "plant" },
    { "word": "මයුරිකා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "මකී", "meaning": "වසතැල්ල", "category": "plant" },
    { "word": "මකීට", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "මකීටනිෂ්ක", "meaning": "පියාගස", "category": "plant" },
    { "word": "මකීටපිප්පලී", "meaning": "කරල්සැබෝ", "category": "plant" },
    { "word": "මකීටප්‍රිය", "meaning": "ඇටමුගස්", "category": "plant" },
    { "word": "මකීටබිජ්", "meaning": "මදුරුමෑ කරල්", "category": "plant" },
    { "word": "මකිඩගිමි", "meaning": "සාදිලිංගම්", "category": "mineral" },

    // --- පිටුව 356 ---
    { "word": "මකීට(සෘප)", "meaning": "තඹ", "category": "mineral" },
    { "word": "මකීටා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "මකීටාක්‍ෂ", "meaning": "තඹ", "category": "mineral" },
    { "word": "මකීටාන්තකණ්ටක", "meaning": "සණගස", "category": "plant" },
    { "word": "මකීටී", "meaning": "සැබෝ, අසමෝද, වදෑරූම, මුගුල්කරඳ, බෙබරගස, ජූල්ගස (දිවුල්ගස) යක්බේරිය", "category": "plant" },
    { "word": "මකීර්", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "මකිලකණ්ටක", "meaning": "මහ උක්", "category": "plant" },
    { "word": "මකිලගුල", "meaning": "වාටු ඇටට සාදෙන රූපාව", "category": "plant" },
    { "word": "මනිවාල්", "meaning": "මර්තමාත් (පැසුන විට කරමක් සුදුපාට ඇති වැඩි වශයෙන් ව්‍යාඤ්ජනයට ගන්නා කෙසෙල් වගියක්)", "category": "plant" },
    { "word": "මණ්ඩංගි", "meaning": "කැසිපිත්තන් වැල", "category": "plant" },
    { "word": "මදීක", "meaning": "තෝරගස", "category": "plant" },
    { "word": "මමී", "meaning": "ප්‍රාණඝාතනය, මිරිස්වැල", "category": "plant" },
    { "word": "මමිතුමා", "meaning": "රසතැල්ල", "category": "plant" },
    { "word": "මම්නායක", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "මමීර", "meaning": "යක්බේරිය, බාන්වැල්, කහ", "category": "plant" },
    { "word": "මම්රි", "meaning": "දාරුහරිද්‍රා", "category": "plant" },
    { "word": "මඟිනාම්බු", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "මරකත", "meaning": "මරාමණී (පද්මරාග මැණික්)", "category": "mineral" },
    { "word": "මරකතපත්‍රී", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "මරද", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "මරාද", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "මරහව", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "මරම්", "meaning": "ගස්", "category": "plant" },
    { "word": "මරම්මල්", "meaning": "වෙනිවැල්", "category": "plant" },
    { "word": "මරම්පල්", "meaning": "වෙනිවැල්", "category": "plant" },
    { "word": "මරයුරි", "meaning": "හුප්පතු", "category": "plant" },
    { "word": "මරාකාලි", "meaning": "ඇත්සැටිය", "category": "plant" },
    { "word": "මරාමරම්", "meaning": "සල්ගස", "category": "plant" },
    { "word": "මරායව", "meaning": "මුරුවා", "category": "plant" },
    { "word": "මරිකොළන්දු", "meaning": "තුවරලා", "category": "plant" },
    { "word": "මරිච", "meaning": "මිරිස්, ගම්මිරිස්", "category": "plant" },
    { "word": "මරිවපත්‍රක", "meaning": "හොරගස", "category": "plant" },
    { "word": "මරින්දු", "meaning": "එලිමරින්දු", "category": "plant" },
    { "word": "මරිතොන්ඩි", "meaning": "හෙනගස්", "category": "plant" },
    { 
        "word": "මරිතොන්ඩි", 
        "scientific": "Lawsonia Alba",
        "meaning": "Lawsonia Alba- රක්තගහී - (මෙන්ඩිකා). දෙළුම් කොළ වලට මඳක් සමාන අඩි දහයක් පමණ උසට වැවෙන ගසකි. මේ වගිය ඉස රූපාව, ලාදුරු හා පිලාව මහත් වීම වැනි අසනීප වලට ත්, පිළිස්සුන තුවාල වලට හා වණ වලටත් ඖෂධයක් වශයෙන් ගනිති. මහමදිකයන්ගේ (මුස්ලිම්/මුසල්මානු) ශුභ වාක්‍යයක් වූ මේ ගසේ ගෙඩිවල යුෂ ඔවුන්ගේ භාර්‍යාවන්ගේ නියපොතු පාටකිරීමට ගනිති.", 
        "category": "plant",
        "image": "img_356_marithondi.jpg"
    },

    // --- පිටුව 357 ---
    { "word": "මරිමාංෂෙබි", "meaning": "ඇම්බරල්ල", "category": "plant" },
    { "word": "මරිෂට", "meaning": "මෝරා", "category": "animal" },
    { "word": "මරිෂටා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "මරිස", "meaning": "ගම්මිරිස්", "category": "plant" },
    { "word": "මරිවක", "meaning": "ගොඩ මිරිස්, මාතුඟ ගස", "category": "plant" },
    { "word": "මරිවි", "meaning": "රෂ්මිය, ඉද්ද, සිනිද්ද", "category": "plant" },
    { "word": "මරු", "meaning": "නියඳ, වැලි, සස්සඳවැල", "category": "plant" },
    { "word": "මරුක්කාරශී", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "මරුක", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "මරු(ක)ත", "meaning": "පික්මැලි, කරවුතලා", "category": "plant" },
    { "word": "මරූකගබ", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "මරූකු", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "මරූප්තමා", "meaning": "දුරාලභා", "category": "plant" },
    { "word": "මරූප්", "meaning": "ගුගුල්, නියඳ", "category": "plant" },
    { "word": "මරූපා", "meaning": "නියඳ", "category": "plant" },
    { "word": "මරූත්තුරාසි", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "මරූත්හව", "meaning": "කිමිල", "category": "plant" },
    { "word": "මරූත්හවා", "meaning": "කපුගස, කුඩාකිණිරි, කහඹිලියා, නියඳ, මහගොත් සුතුකැකිරි, ගුගුල්, හැල්කසඹිලියා, බින්තල්", "category": "plant" },
    { "word": "මරූතා", "meaning": "රණකපුරු", "category": "plant" },
    { "word": "මරූතු", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "මරූදීපට", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "මරූද්‍රම", "meaning": "කිණිහිරි", "category": "plant" },
    { "word": "මරූන්මාලා", "meaning": "පික්මැලි, (පික්මල්)", "category": "plant" },
    { "word": "මරූබක", "meaning": "කුකුරුමුවන්", "category": "plant" },
    { "word": "මරූහුරාග", "meaning": "කණේරු", "category": "plant" },
    { "word": "මරූවක", "meaning": "හින්තලා, නියඳ, කුකුරුමාන්, කරවුතලා", "category": "plant" },
    { "word": "මරූවගස්", "meaning": "කරවුතලා", "category": "plant" },
    { "word": "මරූසමිහවා", "meaning": "ගුගුල්, කුඩාඇල්කසඹිලියා", "category": "plant" },
    { "word": "මල්", "meaning": "මල්, මලාව, අප්පල්ලය", "category": "plant" },
    { "word": "මල්කොණ්ඩූ", "meaning": "මල්රේණු", "category": "plant" },
    { "word": "මල්කොද", "meaning": "මල්වල තිබෙන දික් කෙන්දි", "category": "plant" },
    { "word": "මල්දඹු", "meaning": "නයා", "category": "animal" },
    { "word": "මල්මුවරද", "meaning": "මල්පැණි", "category": "plant" },
    { "word": "මල්රද", "meaning": "රේණු", "category": "plant" },
    { "word": "මල්ල", "meaning": "කම්මුල", "category": "anatomy" },
    { "word": "මල්ලක", "meaning": "පොල් ගෙඩියෙන් සෑදූ පාත්‍රය, පොල්මල", "category": "general" },
    { "word": "මල්ලප්", "meaning": "මිරිස්", "category": "plant" },
    { "word": "මල්ලරි", "meaning": "කැන", "category": "plant" },
    { "word": "මල්ලී", "meaning": "ඉද්දගස", "category": "plant" },
    { "word": "මල්ලිකා", "meaning": "උළුවා, වලාවැන්න, සිනිද්ද, කොත්තමල්ලි, ඉද්ද, දසමන්", "category": "plant" },
    { "word": "මල්ලිකාපුෂ්ප", "meaning": "කෙළිඳගස, මූණුවරණ", "category": "plant" },
    { "word": "මල්ලිකෙ", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "මල්ලිගන්ධි", "meaning": "(කළුවැල්) කළුඅගිල්", "category": "plant" },
    { "word": "මල්ලිගන්ධිකා", "meaning": "පිච්ච, ඉද්ද, සුවඳ අගිල්", "category": "plant" },
    { "word": "මල්ලිපත්‍ර", "meaning": "අරත්ත, ගැටතුඹ", "category": "plant" },
    { "word": "මල", "meaning": "වර්චස්, කපුරු, යකඩදියෙහි මල", "category": "mineral" },
    { "word": "මල(2)", "meaning": "ශුක්‍රය, වා, පිත්, සෙම්, හිරියල්, තුරුක්තෙල්, සුදු හඳුන්", "category": "anatomy" },
    { "word": "මලගුක්ත", "meaning": "මලිත=ධාතකී (ගිනි දළු වැනි රත්පාට මල් ඇති ගසක්)", "category": "plant" },
    { "word": "මලගුලුප්පෙ", "meaning": "මෑ, ලීමෑ", "category": "plant" },
    { "word": "මලරක්කායි", "meaning": "ගල්පියාගස්", "category": "plant" },
    { "word": "මලක්‍ෂාර", "meaning": "රිදීතුත්පත්", "category": "mineral" },
    { "word": "මලගය", "meaning": "කසට ගස", "category": "plant" },
    { "word": "මලගියවැල", "meaning": "ඉද්දවැල", "category": "plant" },
    { "word": "මලච්", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "මලතිප්පල", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "මලද", "meaning": "හඳුන්ගස", "category": "plant" },
    { "word": "මලපු", "meaning": "කොටදිඹුලා ගස", "category": "plant" },
    { "word": "මලපුෂ්ප", "meaning": "කොටදිඹුලා ගස", "category": "plant" },
    { "word": "මලපුතිකා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "මලබවු", "meaning": "මලබොටුගස්", "category": "plant" },

    // --- පිටුව 358 ---
    { "word": "මලහෙදිනි", "meaning": "කටුකරෝහණ", "category": "plant" },
    { "word": "මලඹු", "meaning": "අසූවි, මුතු", "category": "mineral" },
    { "word": "මලය", "meaning": "සඳුන්", "category": "plant" },
    { "word": "මලයප්", "meaning": "සඳුන්", "category": "plant" },
    { "word": "මලයානගමව", "meaning": "සඳුන්", "category": "plant" },
    { "word": "මලයානන්තී", "meaning": "කොබෝලීල", "category": "plant" },
    { "word": "මලයාමනක්කු", "meaning": "දුන්ත", "category": "plant" },
    { "word": "මලයු", "meaning": "බෝදිඇට, පුමිල", "category": "plant" },
    { "word": "මලයුර", "meaning": "බෝදිඇට", "category": "plant" },
    { "word": "මලයෝද්ගහවා", "meaning": "ගොඩ මිරිස්", "category": "plant" },
    { "word": "මලබු", "meaning": "ඉර අව්ව නොවැටෙන අඳුරු සහිත නිතර දිය සීරාව ඇති තැන්වල හටගන්නා ලොකු නෙළුම් කොළ ප්‍රමාණ කොළ ඇති පැලෑටියකි. එක පාලයක කොළ හතකට වඩා එකවර දකින්ට නැත. මේ කොළ හටගන්නේ පාත්සල් ප්‍රමාණ නටුව වල ය. මේ වගියේ යුෂ හොරි, දද, කුෂ්ඨ, කඩුවෙගන් ආදී චර්ම රෝග වලට ප්‍රත්‍යක්‍ෂ ඖෂධයකි.", "category": "plant" },
    { "word": "මලවෙම්බු", "meaning": "මනකොසඹ", "category": "plant" },
    { "word": "මලසා", "meaning": "හින් එන්සාල්", "category": "plant" },
    { "word": "මලසාධන", "meaning": "පොණඬරු", "category": "plant" },
    { "word": "මලසාර", "meaning": "සල්ගස", "category": "plant" },
    { "word": "මලහර්ණී", "meaning": "කත්තාන්ද", "category": "plant" },
    { "word": "මලගා", "meaning": "ගොකටු", "category": "plant" },
    { "word": "මලා", "meaning": "මල්ල, මලාව", "category": "plant" },
    { "word": "මලාක්‍ෂු", "meaning": "මයිල", "category": "plant" },
    { "word": "මලානි", "meaning": "අබ", "category": "plant" },
    { "word": "මලාස්‍ය", "meaning": "කොටදිඹුලා", "category": "plant" },
    { "word": "මලාව", "meaning": "මණඩය, පෙට්ටිය, පාස", "category": "general" },
    { "word": "මලිගිය", "meaning": "වැලිද්ද, මලිගියවැල", "category": "plant" },
    { "word": "මලිගිය වැල්", "meaning": "මාලතී, ගැටපිච්ච, යොහොඹු වැල්, (ඇතැම් අය ඉද්ද වලට ද මේ නම කියන බව පෙනේ)", "category": "plant" },
    { "word": "මලිත", "meaning": "මලිත්ත", "category": "plant" },
    { 
        "word": "මලිත", 
        "scientific": "Woodfordia Floribunda",
        "meaning": "Woodfordia Floribunda-ධාතකී. මලිත - මයිල යයි වගී දෙකකි. ගැඩුඹ කොළ වැනි උල්වූ කොළ හා රතු පාට මල් ඇති වගිය මලිත නමි. මෙහි කුඩා රිකිලි වල දෙ පැත්තට බෙදී යන සේ එක තැන කොළ දෙක බැගින් හට ගනී යි. රත් පාට ගිනි දළු වැනි මල් පොකුරු සෑදෙන්නේ ද ඒ තාන්වල ය. මයිල වෙන ම වගියකි. එහි කොළ රත් කොබෝලීල කොළ මෙන් දෙකට බෙදී ඇත. මුදුනෙහි පමණක් පොකුරු වශයෙන් සෑදෙන මේ වගියේ මල් කහ මිශ්‍ර නිල් පාටින් යුක්තය.", 
        "category": "plant",
        "image": "img_358_malitha.jpg"
    },

    // --- පිටුව 359 ---
    { "word": "මලිත (අතිරේක)", "meaning": "මලිත-මයිල වගී දෙක ම එක වගියක් හැටියට අපේ ඇතැම් පැරණි නිඝණ්ඩුවල හා අකාරාදි වල සඳහන් ව තිබේ. එසේ ම ධාතකී වෙනුවට මයිල මල් ද පාවිච්චි කර තිබේ. සරස්වතී නිඝණ්ඩුවෙහි ධාතකී වලට මයිල කියාද, අමර කෝෂයෙහි හා පාලි නිඝණ්ඩුවෙහි ධාතකී වලට මලකින්න - මලඉත්ත කියා ද අර්ථ දී ඇත. පැරණි කෝෂකාර වියත් පඬිවරයන් දී තිබෙන ලක්‍ෂණ අනුව නම් ධාතකී වෙනුවට ගත යුත්තේ මයිල නොව මලිත ම ය. මයිල - මලිත දෙවගිය ම රස-ගුණ විපාකයෙන් සමාන යයි ද, අසමාන යයි ද නවීන රසායන විද්‍යාඥයෝත් දෙ පිළකට බෙදී දෙකක් කියති. මේ පිළිවෙලට ම ලංකාවේ පැරණි වෛද්‍යවරයෝ ද දෙපිලකට බෙදී සිටින්ට ඇති බැව් ධාතකී වෙනුවට මයිල මල් ගෑණීමෙන් පෙනේ. මලිත මල් අතිසාර ආදි රෝගාබාධ සඳහා සාදන කෂාය-චූර්ණ-ආසව වලට හා අරිෂ්ට-ආසව වගී නරක් නො වී කල් තබා ගෑණීමට අවශ්‍ය මද්‍යසාර නිපදවීම පිණිස ත් පාවිච්චි කරති. අතික් ගුණ කෙසේ වෙත ත් මයිල මල් වලට වඩා මලිත මල් වල මද්‍යසාර නිපදවීමේ ශක්තිය අධික බැව් මේ දෙවගිය එක පමණට ගෙන එක ප්‍රමාණ අරිෂ්ට බරණි දෙකකට දමා නියම කාලය අවසන් වීමෙන් පසු පෙරා බැලුවොත් වැටහී යනවා ඇත. පැරණි මහ පඬිවරයන් දී තිබෙන ලක්‍ෂණ අනුව ධාතකී, මලිත ම බවත්, ධාතකී වෙනුවට මලිත මල් ම ගැණීම වඩා සුදුසු බව ත් පෙනේ.", "category": "plant" },
    { "word": "මලින්දු", "meaning": "මයිල", "category": "plant" },
    { "word": "මලින", "meaning": "මිරිස්, හංසයිත්", "category": "plant" },
    { "word": "මලිමස", "meaning": "මල්කසිස්", "category": "mineral" },
    { "word": "මලපු", "meaning": "වැලිද්ද, මල්කැන, ඉද්ද වැල", "category": "plant" },
    { "word": "මල්ෂා", "meaning": "රත්මුරුංගා", "category": "plant" },
    { "word": "මලෙසිමන්ගල්", "meaning": "කේගරබැවිල", "category": "plant" },
    { "word": "මලෙසිවාලෙයි", "meaning": "වනකෙසෙල්, (ඇට කෙසෙල්)", "category": "plant" },
    { "word": "මලෙලෙ කුන්දුරුක්කන්", "meaning": "කට්ට කුමන්ජල්", "category": "plant" },
    { "word": "මලෙලෙම්වල්", "meaning": "වෙනිවැල් ගැට", "category": "plant" },
    { "word": "මලෙයි වෙම්බු", "meaning": "මහ කොහොඹ", "category": "plant" },
    { "word": "මලොමසා", "meaning": "මල්කසිස්", "category": "mineral" },
    { "word": "මවතිමුල", "meaning": "තුවරලා", "category": "plant" },
    { "word": "මවුන්තිකා", "meaning": "මුතු", "category": "mineral" },
    { "word": "මශක", "meaning": "රත්තමසලා", "category": "plant" },
    { "word": "මශකින්", "meaning": "අන්ගික්කා", "category": "plant" },
    { "word": "මශා", "meaning": "වදකසා", "category": "plant" },
    { "word": "මශි", "meaning": "නිල් සේපාලිකා නටු, ලිවීමට ගන්නා දැලි (තීන්ත)", "category": "plant" },
    { "word": "මශුයක", "meaning": "කොසඹ", "category": "plant" },
    { "word": "මශුයකා", "meaning": "කොසඹ", "category": "plant" },
    { "word": "මශූර", "meaning": "හෙළ කරල් සැබෝ, කළු දුරු, ත්‍රස්තාවළු", "category": "plant" },
    { "word": "මශූරි", "meaning": "ත්‍රිවත්, රක්ත ත්‍රිවත්", "category": "plant" },
    { "word": "මෂ්කාර", "meaning": "රන් ගස", "category": "plant" },
    { "word": "මෂ්කරී", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "මෂ්", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "මස් ඇස්", "meaning": "මුගුණුවැන්න", "category": "plant" },
    { "word": "මස්ක", "meaning": "වදෑරූ මෑ", "category": "plant" },
    { "word": "මස්කර", "meaning": "උණ ගස", "category": "plant" },
    { "word": "මස්හකමස්පූරි", "meaning": "කිරිඳි", "category": "plant" },
    { "word": "මස්තදුරු", "meaning": "දේවදාර", "category": "plant" },

    // --- පිටුව 360 ---
    { "word": "මස්තරල", "meaning": "මහ කලාදුරු", "category": "plant" },
    { "word": "මස්තු", "meaning": "දීපෙරලි දිය, මිදුන කිරෙන් උනන (එකතු වන) ජලය හෝ කිරි එක කොටසකට වතුර තුන් කොටසක් ලා මඬගත් ජලය.", "category": "liquid" },
    { 
        "word": "මස්බැද්ද", 
        "scientific": "Gymnema Sylvestre",
        "meaning": "Gymnema Sylvestre-මෙෂශෘංගි. මෙය මුරුවා-දූල් වල මෙන් සිහින් බුවක් ඇති ඇත් අඟුණ වැලට සමාන වැලකි. කොළ වල දිග පළල අඟල් 2 1/2 x 1 1/2ක් පමණ ඇත. තික්ත-කසට රසයෙන් යුක්ත ආමාශය ශක්තිමත් කරණ ඖෂධයකි. කාස-ඇස් රෝග හා සමේ හටගන්නා බිබිලි වලට ත් මේ කොළ යුෂ ප්‍රයෝජනවත් ය. මෙහි තිබෙන විශේෂ ලක්‍ෂණය නම්: මේ කොළ සැපීමෙන් පසු දිවට වෙන කිසිම දෙයක රස නො දැනීම යි. වැරදී හෝ හුනු කෑවුනොත් මේ කොළ ටිකක් විකා යුෂ ගිලීමෙන් ඒ විෂ සම්පූර්ණයෙන් ම පහ වී යයි. මේ වගිය වෙනුවට ඇතැම් අය බින් නුග (මුලින්) ගන්නා නමුත් එය වෙන ඖෂධයකි. මස්බැද්ද නොවේ. (බින්නුග ගුණ 332 පිටේ විස්තරය බලන්න.)", 
        "category": "plant",
        "image": "img_360_masbadda.jpg"
    },
    { "word": "මස්රඬු", "meaning": "ආඳන්, (මත්ස්‍යරාජයන්)", "category": "animal" },
    { "word": "මස්වත්", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "මස්වැන්න", "meaning": "කිඹුල් වැන්න (මාංශ පර්ණී)", "category": "plant" },
    { "word": "මස්වා", "meaning": "කිඹුල්ලු", "category": "animal" },
    { "word": "මසක", "meaning": "රත් තම්පලා", "category": "plant" },
    { "word": "මසකානි", "meaning": "මුඛ රෝගය", "category": "treatment" },
    { "word": "මසක්කර", "meaning": "පින්තල", "category": "plant" },
    { "word": "මසත්", "meaning": "බෙබර ගස", "category": "plant" },
    { "word": "මසන", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "මසරා", "meaning": "ත්‍රස්තාවළු", "category": "plant" },
    { "word": "මසාරගල්ල", "meaning": "මාසිරි ගල්", "category": "mineral" },
    { "word": "මසිකා", "meaning": "නිල් සේපාලිකා නටු", "category": "plant" },
    { "word": "මසිපල", "meaning": "ලියන තීන්ත", "category": "general" },
    { "word": "මසිනා", "meaning": "එළ රතණ", "category": "plant" },
    { "word": "මසිර", "meaning": "සුළු කූරතම්පලා", "category": "plant" },
    { "word": "මසේනියා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "මසු", "meaning": "ත්‍රස්තාවළු", "category": "plant" },
    { "word": "මසුරදිදල ප්‍රහා", "meaning": "වැල් පෙනෙල", "category": "plant" },
    { "word": "මසුරදල", "meaning": "කළු ත්‍රස්තාවළු, ඇඹරැල්ල", "category": "plant" },
    { "word": "මසුරිය", "meaning": "කරල් සැබෝ", "category": "plant" },
    { "word": "මසුරිකා", "meaning": "වසන්ත රෝගය හෙවත් මසුරිකාව (වසූරිය)", "category": "treatment" },
    { "word": "මසූරි", "meaning": "කළු ත්‍රස්තාවළු, රතු ත්‍රස්තාවළු", "category": "plant" },
    { "word": "මහා", "meaning": "කොබෝලීල ගස", "category": "plant" },

    // --- පිටුව 361 ---
    { "word": "මහ අදිකාරම්", "meaning": "බුව ගස", "category": "plant" },
    { "word": "මහ අගද", "meaning": "තිප්පිලි", "category": "plant" },
    { "word": "මහලුක්", "meaning": "දඹක් ගස", "category": "plant" },
    { "word": "මහ ඉඟිනි", "meaning": "ගොඩ කදුරු", "category": "plant" },
    { "word": "මහ ඔසු", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "මහ එන්සාල්", "meaning": "හිංගු පත්‍රිකා", "category": "plant" },
    { "word": "මහ කන්දෙ", "meaning": "හෙළ ලුහුනු", "category": "plant" },
    { "word": "මහකළුවා", "meaning": "මහ කළුවා ගස", "category": "plant" },
    { "word": "මහකවෙල්ලු", "meaning": "මහා කාකොලි", "category": "plant" },
    { "word": "මහකාල", "meaning": "නිත්ත නොඬල", "category": "plant" },
    { "word": "මහ කැනැස්ස", "meaning": "මහති", "category": "plant" },
    { "word": "මහ කර්ණිකාර", "meaning": "ඇසළ", "category": "plant" },
    { "word": "මහ කෙළිඳ", "meaning": "ලොකු කෙළිඳ වගිය මේවායේ කොළ, මල් හා කරල් විශාල ය.", "category": "plant" },
    { "word": "මහ ගෙලබිය", "meaning": "මහ මුවාවැන්න, මහ කලන්, (මහ කොල්ලු)", "category": "plant" },
    { "word": "මහගුල්ම", "meaning": "මුවකිරිය", "category": "plant" },
    { "word": "මහ ගොන් සුතු කැකිරි", "meaning": "මහ ගොන් කැකිරි", "category": "plant" },
    { "word": "මහච්ඡද", "meaning": "සල් ගස, දේවදාර", "category": "plant" },
    { "word": "මහ චෝරක", "meaning": "හරංකහ", "category": "plant" },
    { "word": "මහති", "meaning": "මහ කැනැස්ස, වම්බටු, තිබ්බටු", "category": "plant" },
    { "word": "මහදෘම", "meaning": "තොටිල", "category": "plant" },
    { "word": "මහනාලා", "meaning": "කෙහෙල්", "category": "plant" },
    { "word": "මහනතිකා", "meaning": "තොටිල ගස", "category": "plant" },
    { "word": "මහතස්", "meaning": "කුඩා පැලෑටියක් = (මගතසි-සුව නයි දෙවගිය ගැන ඡායාරූප සහිත විස්තරයක් සුළුනයි යන මේදය යටතේ ඉදිරියෙහි ඇත)", "category": "plant" },
    { "word": "මහනාබ", "meaning": "මහ නඹිල", "category": "plant" },
    { "word": "මහනිඹ", "meaning": "තොටිල, ඇසළ", "category": "plant" },
    { "word": "මහනෙල්", "meaning": "මානෙල් (ජලජ පුෂ්ප වගියකි) නිල්-හෙළ (සුදු) වගයෙන් දෙවගය කි.", "category": "plant" },
    { "word": "මහපතු", "meaning": "රත් එරබු", "category": "plant" },
    { "word": "මහපතික්කිල", "meaning": "අමුකහ", "category": "plant" },
    { "word": "මහපල", "meaning": "පොල්ගස", "category": "plant" },
    { "word": "මහපස්මුල් ගණය", "meaning": "බෙලි, සිහින් මිදි, තොටිල, ඇත් දෙමට, පලොල් යන මේ මහ පස් මුල් ගණය බඩගිනි ඇති කිරීම හා සෙම්, වාත, නසන්නේයි.", "category": "compound" },
    { "word": "මහ පැණි වාක්‍ෂය", "meaning": "බක්මී ගස", "category": "plant" },
    { "word": "මහඵල", "meaning": "මාදම් ගෙඩි", "category": "plant" },
    { "word": "මහ බල", "meaning": "රසදිය හෝ කාන්දම්", "category": "mineral" },
    { "word": "මහ බුරාද", "meaning": "මහසාරණ ගස", "category": "plant" },
    { "word": "මහමි", "meaning": "බඹර පැණි", "category": "food" },
    { "word": "මහමෙවන්", "meaning": "මහාමේදා", "category": "plant" },
    { "word": "මහරස", "meaning": "උක් ගස", "category": "plant" },
    { 
        "word": "මහ හැඩයා", 
        "scientific": "Lycopodium Phlegmaria",
        "meaning": "Lycopodium Phlegmaria- මහා හැඩයා, කුඩා හැඩයා යයි වගී දෙකකි. උඩ වැඩියා වගියට අයත් වූ මේ පැලෑටි දෙපලවල් අසල දිය සීරාව සහිත අඳුරු පෙදෙස් වල පිහිටි ගස් වල දිය සෙවෙල් හා දිරාන පොතු ද ආහාර කොට ගනිමින් වැඩෙයි. නාරටිය දෙපසට බෙදී ගිය පොල් මල් ඇට වැනි කුඩා කොළ සහිත වගිය මහ හැඩයා නමින් හැඳින් වේ. ඊටත් කුඩා කෙන්දි වැනි කොළ සහිත වගිය කුඩා හැඩයා නමි. අඩි එකහමාරක් පමණ දික් වීමෙන් පසු වෑම් මල් (බුලත් මල්) වැනි කරල් කීපයක් පැලෑටියේ අග සාදෙයි. මේ දෙවගියම දේශීය වෙදකමේ තෙල් - බෙහෙත් වට්ටෝරු වලට ඇතුළත් කර තිබේ.", 
        "category": "plant",
        "image": "img_361_maha_hadaya.jpg"
    },

    // --- පිටුව 362 ---
    { "word": "මහරා", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "මහරි", "meaning": "මාරා", "category": "plant" },
    { "word": "මහරුක්", "meaning": "පොල්", "category": "plant" },
    { "word": "මන රතු සාල් / මහ රොතු හාල්", "meaning": "ධාන්‍ය වගියක්", "category": "plant" },
    { "word": "මහලෙඬ", "meaning": "මසුරිකා (වසූරි) රෝගය", "category": "treatment" },
    { "word": "මහසපි", "meaning": "හරංකහ", "category": "plant" },
    { "word": "මහසාර", "meaning": "කළු කිහිරි", "category": "plant" },
    { "word": "මහසිරා", "meaning": "වහනහර", "category": "anatomy" },
    { "word": "මහසුදනා", "meaning": "කුඩා සුදන හැඩහුරුකම ඇති ලොකු වගිය", "category": "plant" },
    { "word": "මහ සෝරකම", "meaning": "හරංකහ", "category": "plant" },
    { "word": "මහහිගිණිය", "meaning": "මහ ඉඟිනි", "category": "plant" },
    { "word": "මහා", "meaning": "මුරුවා වැල, කකීටකශෘංගි, මුහුණු ගස", "category": "plant" },
    { "word": "මහාක", "meaning": "මුතු, මහ මුතු", "category": "mineral" },
    { "word": "මහාකටිවෙපද", "meaning": "සිඳිඟුරු", "category": "plant" },
    { "word": "මහා කදම්බක", "meaning": "කොළොම් ගස", "category": "plant" },
    { "word": "මහාකන්‍ද", "meaning": "රතු ලූනු, සුදු ලූනු", "category": "plant" },
    { "word": "මහාකපිත්ථක", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "මහා කකීට පිප්පලී", "meaning": "රත් ගොකටු", "category": "plant" },
    { "word": "මහා කර්ණිකාර", "meaning": "ඇසළ ගස", "category": "plant" },
    { "word": "මහා කාස", "meaning": "තල් ගස", "category": "plant" },
    { "word": "මහා කුමිහි", "meaning": "ඇත්දෙමට ගස, (කළු එල)", "category": "plant" },
    { "word": "මහා කුමුදු", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "මහා කුමුදිකා", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "මහා කොෂ ඵලා", "meaning": "දේවදාලිය වැල", "category": "plant" },
    { "word": "මහාගඛණ", "meaning": "මාදම්", "category": "plant" },
    { "word": "මහා ඛර්ජුරිකා", "meaning": "යොන් ඉඳි", "category": "plant" },
    { "word": "මහා ගණ", "meaning": "දිය හොමුවානු, කෙළිඳ, මහ බැවිල", "category": "plant" },
    { "word": "මහා ගක්මුලී", "meaning": "ගොඩමානෙල්", "category": "plant" },
    { "word": "මහා ගන්‍ධා", "meaning": "මඟුල් කුඹුරු, වාත්ත, හරිවන්දන, ජලවේතස", "category": "plant" },
    { "word": "මහාගුප්තා", "meaning": "වදෑරු මෑ", "category": "plant" },
    { "word": "මහා ගුල්පා", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "මහා ගුල්ම", "meaning": "මුවකිරිය", "category": "plant" },
    { "word": "මහා ගුල්මා", "meaning": "මුවකිරියා", "category": "plant" },
    { "word": "මහා ගුහා", "meaning": "අස්වැන්න", "category": "plant" },
    { "word": "මහා ගොණ්ඨා", "meaning": "කකීටක ශෘංගි", "category": "plant" },
    { "word": "මහා ගෝෂා", "meaning": "කකීටකශෘංගි, කුන්දු රක්කන්", "category": "plant" },
    { "word": "මහාඝොෂා", "meaning": "ගොකටු, රත් නිටුල්", "category": "plant" },
    { "word": "මහාච්ඡද", "meaning": "දේවදාර ගස", "category": "plant" },
    { "word": "මහාච්ඡායා", "meaning": "නුග ගස", "category": "plant" },
    { "word": "මහාච්ඡිදා", "meaning": "මිහමෙවන්", "category": "plant" },
    { "word": "මහාවලක", "meaning": "මදට ගස", "category": "plant" },
    { "word": "මහාජටා", "meaning": "බටු ගස, රුදු ජටා", "category": "plant" },
    { "word": "මහාජම්බු", "meaning": "මාදම් ගස", "category": "plant" },
    { "word": "මහාජාලි", "meaning": "රන්වන් වැටකොළු, දුම්මැල්ල", "category": "plant" },
    { "word": "මහා ජාලිනී", "meaning": "වැල් තුඹ", "category": "plant" },
    { "word": "මහා තරු", "meaning": "දඹක් ගස", "category": "plant" },

    // --- පිටුව 363 ---
    { "word": "මහාතාලි", "meaning": "තල් ගස", "category": "plant" },
    { "word": "මහාතිකතා", "meaning": "කොසඹ ගස", "category": "plant" },
    { "word": "මහා තිකතා", "meaning": "පික්මැලි", "category": "plant" },
    { "word": "මහා තීක්‍ෂණ", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "මහා තෙජස්", "meaning": "රසදිය", "category": "mineral" },
    { "word": "මහා දක්‍ෂ", "meaning": "අස්බැවිල", "category": "plant" },
    { "word": "මහාදාරු", "meaning": "දේවදාර", "category": "plant" },
    { "word": "මහාදිසිකලද්‍රම", "meaning": "හොරගස", "category": "plant" },
    { "word": "මහාද්‍රෝණි", "meaning": "මහතුඹ", "category": "plant" },
    { "word": "මහාද්‍රම", "meaning": "ඇසතු ගස", "category": "plant" },
    { "word": "මහා ධාතු", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "මහානාමෝ", "meaning": "උක්", "category": "plant" },
    { "word": "මහානාබ", "meaning": "මහතඹිල", "category": "plant" },
    { "word": "මහා නිම්බ", "meaning": "තොටිල ගස", "category": "plant" },
    { "word": "මහානිල", "meaning": "මහ ජම්බු, කිකිරිඳිය", "category": "plant" },
    { "word": "මහා පඤ්චාංගුල", "meaning": "මහ එරබු ගස", "category": "plant" },
    { "word": "මහාපත්‍ර", "meaning": "හෙළ ලොත්, තෙල ගස, සල් ගස, අස්බැවිල, රත් එරබු", "category": "plant" },
    { "word": "මහාපත්‍රා", "meaning": "මහ ජම්බු ගස", "category": "plant" },
    { "word": "මහා පත්‍රාලුක", "meaning": "හබරල", "category": "plant" },
    { "word": "මහාපත්‍රී", "meaning": "එළ එරබු ගස", "category": "plant" },
    { "word": "මහා පාංශුල්ල", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "මහාපිණ්ඩිතක", "meaning": "කළුපාට මහමදන රූක", "category": "plant" },
    { "word": "මහා පුරාඥදනා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "මහා පුරඥදනතිකා", "meaning": "මහා සාතාවාරිය, මහමෙවන්", "category": "plant" },
    { "word": "මහාපුෂ්පා", "meaning": "ගිරිනිල්ල, කටරොළු", "category": "plant" },
    { "word": "මහාපුෂ්පී", "meaning": "වරා ගස", "category": "plant" },
    { "word": "මහා ඵල", "meaning": "දිඹුල්, බෙලි, වැලුගුන්, සාදික්කා, මාදම්, පොල්, වම්බොටු", "category": "plant" },
    { "word": "මහාඵලා", "meaning": "මාදම් ගස්, පොල් ගස්, බෙලි, සියඹලා, වම්බටු, කොමඩු පුසුල්, නික්ත ලබු, අස්බැවිල", "category": "plant" },
    { "word": "මහා බර්බරිකා", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "මහා බල", "meaning": "රන්වන් බැවිල, යකඩ, කාන්දම්, ඊයම්", "category": "mineral" },
    { "word": "මහාබල එල", "meaning": "සිරිතේක්කු", "category": "plant" },
    { "word": "මහාබලා", "meaning": "සිරිවාඩි බැවිල, මහ බැවිල - අස් බැවිල, කාන්දම්, ඊයම්, ගල් සෙවෙල්", "category": "mineral" },
    { "word": "මහාබිප්", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "මහාභද්‍ර", "meaning": "සුළු බැවිල", "category": "plant" },
    { "word": "මහාමල", "meaning": "මහ ඇඹුල, සියඹලා", "category": "plant" },
    { "word": "මහාමණ්ඩී", "meaning": "මුඛමඟන", "category": "plant" },
    { "word": "මහාමතී", "meaning": "කඳුරුගෙඩිය වැල", "category": "plant" },
    { "word": "මහාමා", "meaning": "උඳු", "category": "plant" },
    { "word": "මහාමාස", "meaning": "ලීමෑ, උඳු", "category": "plant" },
    { "word": "මහාමුල", "meaning": "මහලුහුනු, (රාජපලාණ්ඩු)", "category": "plant" },
    { "word": "මහාමෙද", "meaning": "මහ මෙවන්", "category": "plant" },
    { "word": "මහාමෙඩ", "meaning": "හෙළ හිඹුරු", "category": "plant" },
    { "word": "මහාමොහි", "meaning": "අත්තන", "category": "plant" },
    { "word": "මහායශා", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "මගාරක්‍ෂා", "meaning": "කිකිරිඳිය", "category": "plant" },
    { "word": "මහාරජත", "meaning": "(වනුක්) සෙන්දිරික්කා, රත්රන්", "category": "mineral" },
    { "word": "මහාරඤ්ජන", "meaning": "වනුක් මල්, රත්රන්", "category": "mineral" },
    { "word": "මහාරස", "meaning": "ඉඳි, කොකැටිය, උක්දඬු, රසදිය, කාඩි දිය, වැල් මුරුංගා", "category": "liquid" },
    { "word": "මහාරාජ", "meaning": "හෝපළු ගස", "category": "plant" },
    { "word": "මහාරාජ ද්‍රම", "meaning": "ඇසල ගස", "category": "plant" },
    { "word": "මහාරිෂ්ට", "meaning": "වල් කොසඹ", "category": "plant" },
    { "word": "මහාරුහ", "meaning": "කෙහෙල් ගස", "category": "plant" },
    { "word": "මහාල", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "මහාලයා", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "මහාලොධ්‍ර", "meaning": "හෙළ ලොත්", "category": "plant" },
    { "word": "මහාවක්‍ෂිභා", "meaning": "මහසාරණ", "category": "plant" },
    { "word": "මහාවරෝහ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "මහාවල්ලී", "meaning": "මහ කරවිල, ත්‍රස්තාවළු, යොහොඹු", "category": "plant" },
    { "word": "මහා වාතිකිණී", "meaning": "වම්බටු, කිකිරිඳිය", "category": "plant" },
    { "word": "මහාවියසී", "meaning": "වල්කපු, රසකිඳ, රසදිය", "category": "mineral" },
    { "word": "මහාවෘක්‍ෂ", "meaning": "දඹක්, බින්තල්, පොල්", "category": "plant" },

    // --- පිටුව 364 ---
    { "word": "මහාවෘහති", "meaning": "එළබටු, මහලක්, කළු කිහිරි", "category": "plant" },
    { "word": "මහා වෘණ", "meaning": "මහත් වන", "category": "plant" },
    { "word": "මහාව්‍යාධි", "meaning": "අටමහ රෝගාදි මහා රෝග", "category": "treatment" },
    { "word": "මහාශය", "meaning": "මහ අත්තන", "category": "plant" },
    { "word": "මහාශණ", "meaning": "හණ ගස", "category": "plant" },
    { "word": "මහාශණ පුෂ්පී", "meaning": "මහ හණ මල්", "category": "plant" },
    { "word": "මහාශතා", "meaning": "මහ සාතාවාරිය", "category": "plant" },
    { "word": "මහාශව", "meaning": "තුන්බෝ අත්තන", "category": "plant" },
    { "word": "මහා ශාඛා", "meaning": "කොටිකන් බැවිල", "category": "plant" },
    { "word": "මහාශාර", "meaning": "එළ කිහිරි", "category": "plant" },
    { "word": "මහාශාලි", "meaning": "මහ ඇල් වී", "category": "plant" },
    { "word": "මහාශිකා", "meaning": "අස්බැවිල", "category": "plant" },
    { "word": "මහාශිනා", "meaning": "මහ සාතාවාරිය", "category": "plant" },
    { "word": "මහාස්‍රාව", "meaning": "දුදු, සිඳිඟුරු, රතු ලූනු, මාරා, ජම්බු, සිරිවාඩි බැවිල", "category": "plant" },
    { "word": "මහාස්‍රාවා", "meaning": "මාදම්", "category": "plant" },
    { "word": "මහාස්වේතා", "meaning": "කපු, කළු කිරිබදු, එළ කිරිබදු, ඇඹුල් වේ, කලගස", "category": "plant" },
    { "word": "මහාස්‍රතා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "මහාසෙදය", "meaning": "මහාස්වේදය. අඩග වාතයට බුදු රජානන් වහන්සේ විසින් නියම කරණ ලද වේද පෑමකි. (දෙරියන (අඩි තුන) ක් පළල හා ශරීරයන (අඩි නමය) ක් දිග ද අඩියක් ගැඹුර ද සිටින සේ වලක් සාරා ඒ වල තුලට තදින් රත් වන අඟුරු බහින දර වගී දමා පුළුස්සා අඟුරු බැස්සාට පසු වියලන වැලි හා පස් වලින් වලේ මට්ටමට පුරවා සමතලා කර, ඊට උඩින් වාතහර නික, වන්ඇපල, කටුකරඬු ආදී කොළ වගී අතුරා වාතාබාධයෙන් පෙළෙන රෝගියා ඒ අඹු ගස්වා, වාත නාසක, මහා නාරායන, සිද්ධාර්ථ, බලා කෝරණ්ඩ, ලසුනෙරණ්ඩ ආදි තෙල් එකට මිශ්‍ර කර ගත් තෙල් මිශ්‍රණය ඔහුගේ ඇඟේ ගා හොඳින් නහර ක්‍රියා කරණ සේ අතුල්ලා ඒ ගිනි වල උඩ අතුරා තිබෙන කොළ ඇතිරිල්ලෙහි නිදා ගන්ට සලස්වා ඒ මේ අත පෙරලවමින් ඩහ ගැන්වීම යි, මෙය කර බලන්න. ඉතා ප්‍රත්‍යක්‍ෂ ප්‍රතිකාර ක්‍රමයක් ය)", "category": "treatment" },
    { "word": "මහා සහා", "meaning": "උඳුපියලි, කටුකරඬු", "category": "plant" },
    { "word": "මහාසර්ජ්", "meaning": "පියා ගස, කොස් ගස", "category": "plant" },
    { "word": "මහාසුනේත්‍රා", "meaning": "අරත්ත", "category": "plant" },
    { "word": "මහා සුගන්ධ", "meaning": "අරත්ත", "category": "plant" },
    { "word": "මහාසුගුණි", "meaning": "මුඛමඟණ", "category": "plant" },
    { "word": "මහාසුක්‍ෂමා", "meaning": "ගිරිනිල්ල, කිරිඳි, මහ පෝටා, වැල් පෙනෙල", "category": "plant" },
    { "word": "මහාහිගන්‍ධා", "meaning": "මහ අරත්ත", "category": "plant" },
    { "word": "මහා හ්‍රස්වා", "meaning": "වදෑරූ මෑ", "category": "plant" },
    { "word": "මහාහසී", "meaning": "හෙළ සඳුන්", "category": "plant" },
    { "word": "මහිකා", "meaning": "පිනි", "category": "nature" },
    { "word": "මහිරත", "meaning": "මිහිරන්", "category": "mineral" },
    { "word": "මහිලා", "meaning": "පුවඟු, ගස් අඟුණ, හරේණුක, එන්සාල්", "category": "plant" },
    { "word": "මහිෂ්පත්‍ර", "meaning": "සිඳිඟුරු", "category": "plant" },
    { "word": "මහිපක්‍ෂි", "meaning": "හිඟුල්", "category": "mineral" },
    { "word": "මහිඵලතා", "meaning": "ගිරිනිල්ල", "category": "plant" },
    { "word": "මහිෂවර්ඩනිනී", "meaning": "රතණ ප්‍රභේද", "category": "plant" },
    { "word": "මහිෂාක්‍ෂ", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "මහිසාරිත", "meaning": "හිරිහු", "category": "plant" },
    { "word": "මහි", "meaning": "කඳුරුගෙඩිය වැල්", "category": "plant" },
    { "word": "මහිජ", "meaning": "අමුඉඟුරු", "category": "plant" },
    { "word": "මහිලතා", "meaning": "ගැටමුලා", "category": "plant" },
    { "word": "මහිර්‍රහ", "meaning": "ගස", "category": "plant" },
    { "word": "මහීස", "meaning": "ඉඟුරු, හිරිහු", "category": "plant" },
    { "word": "මහෙතුකා", "meaning": "මයිල", "category": "plant" }
];

