// data_439_449.js - පිටු 439 සිට 448 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 204
const data_extra_439_449 = [
    // --- පිටුව 439 ---
    { "word": "විහාකර", "meaning": "වරාගස, හෙළ නිටුල්", "category": "plant" },
    { "word": "විභාවරී", "meaning": "කහ", "category": "plant" },
    { "word": "විභාවසු", "meaning": "වරා ගස, රත් නිටුල්", "category": "plant" },
    { "word": "විහීනක / විහීතකී", "meaning": "මුව ගස", "category": "plant" },
    { "word": "විහිස", "meaning": "මුල", "category": "plant" },
    { "word": "විහිසා", "meaning": "මිදි", "category": "plant" },
    { "word": "විම්බ", "meaning": "කෙම් ගෙඩිය, (කෝවක්කා ගෙඩිය)", "category": "plant" },
    { "word": "විම්බට", "meaning": "අබ", "category": "plant" },
    { "word": "විම්බිකා", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "විමල", "meaning": "දසමන්, යමිනුව ලුණු", "category": "plant" },
    { "word": "විමලා", "meaning": "නෙල්ලි, බැමිතිරිය", "category": "plant" },
    { "word": "විමගන්ධිකා", "meaning": "වැල් පෙනෙල", "category": "plant" },
    { "word": "වියඳුන්", "meaning": "කැවිලි", "category": "food" },
    { "word": "විරයා", "meaning": "උන්මාදය, (පිස්සුව) මීමස් මොරය (වස්මර)", "category": "treatment" },
    { "word": "වියළි ගැට වෙයන්", "meaning": "වේලිච්ච ගැට වෙලුන්", "category": "plant" },
    { "word": "විරංග", "meaning": "පික් මල්", "category": "plant" },
    { "word": "විරණ", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "විරණාමූල", "meaning": "සැවැන්දරා", "category": "plant" },
    { "word": "විරෂ", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "විරහ", "meaning": "රති කෙළිය", "category": "general" },
    { "word": "විරාල", "meaning": "කිහිරි,", "category": "plant" },
    { "word": "විරාලිකා", "meaning": "කිරිකවෙලු", "category": "plant" },
    { "word": "විරිකතා", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "විරුස්", "meaning": "ලබත්ත", "category": "plant" },
    { "word": "විරූප", "meaning": "නිප්පිලි මුල්, අතිවිඩයන්, ඇල් කසඹිලියා, කළුදුරු", "category": "plant" },
    { "word": "විරූපා", "meaning": "නිල්මානෙල්, උඩැත්ත", "category": "plant" },
    { "word": "විරේක", "meaning": "මලාශය පහතට යාම (මල පහවීම)", "category": "treatment" },
    { "word": "විරේකී", "meaning": "රුකඟුණ, යක්බේරිය", "category": "plant" },
    { "word": "විරෙචන", "meaning": "මොර ගස, මල පහවීම", "category": "plant" },
    { "word": "විරෙචනී", "meaning": "පික්මැලි", "category": "plant" },
    { "word": "විරොචක", "meaning": "එරබදු, තොටිල, වරා ගස", "category": "plant" },
    { "word": "විල්කොත්", "meaning": "කොත්ත", "category": "plant" },
    { "word": "විල්තලා", "meaning": "තලා වගියක්, විලකොළ", "category": "plant" },
    { "word": "විල්දුම්මල", "meaning": "විල්වලින් හාරාගන්නා දුම්මල", "category": "mineral" },
    { "word": "විල්ලම්", "meaning": "බෙලි ගස", "category": "plant" },
    { "word": "විල්ලමුලා", "meaning": "බින්තල්", "category": "plant" },
    { "word": "විල්ව", "meaning": "බෙලි", "category": "plant" },
    { "word": "විල්විකා", "meaning": "පත්පාඬගු", "category": "plant" },
    { "word": "විලංගන්", "meaning": "මිහිරන්", "category": "plant" },
    { "word": "විලබාදන", "meaning": "වළඟසාල්", "category": "plant" },
    { "word": "විලග", "meaning": "වළඟසාල්", "category": "plant" },
    { "word": "විලද", "meaning": "වී පොරි (ධාන්‍ය බැඳි ලද මල් = ලාජා)", "category": "plant" },
    { "word": "විලද පැන්", "meaning": "මල් රස, මල් වතුර", "category": "liquid" },
    { "word": "විලඳවැන්න", "meaning": "විලද වැනි මල් හට ගන්නා මුඩුවැන්න වලට මදක් සමාන වමන කාරක පැලෑටියක්, (ඇතැම් අය සක්ම පුෂ්පි = (සක් මල්) වලට ද විලඳ වැන්න යයි කියති)", "category": "plant" },
    { "word": "විලපලා", "meaning": "තනකිරි වඩවන කෑමක් (පලා වගියක්)", "category": "plant" },
    { "word": "විලුලා", "meaning": "සුදු බැබිල", "category": "plant" },
    { "word": "විලාප්", "meaning": "දෙබොම්", "category": "plant" },
    { "word": "විලාප පගිරි", "meaning": "දෙබොම් පැගිරි", "category": "plant" },
    { "word": "විලාමරම", "meaning": "හිඹුලු ගස", "category": "plant" },
    { "word": "විලාවරිසි", "meaning": "විලා අරිසි =(වළගසාල්)", "category": "plant" },
    { "word": "විලාසිනී", "meaning": "කසා, සංකකුප්පි", "category": "plant" },
    { "word": "විලි", "meaning": "ගෙඩිය, ඵල", "category": "plant" },
    { "word": "විලිකුම්", "meaning": "පැසුණු", "category": "plant" },
    { "word": "විලිකුම්කදලි", "meaning": "ඉදුන කෙසෙල්ගෙඩි", "category": "plant" },
    { "word": "විලිකුම් පත්", "meaning": "පැසුන කොළ", "category": "plant" },
    { "word": "විලිකුම්මිරිදිය", "meaning": "උණුවතුර", "category": "liquid" },
    { "word": "විලිමුවන්", "meaning": "රිලවුන්", "category": "animal" },
    { "word": "විලෙපනය", "meaning": "සඳුන්, කසා, ගොරද, කොකුම්, මෙකි දේ", "category": "plant" },
    { "word": "විලෙපි", "meaning": "තලප", "category": "food" },
    { "word": "විලොවක", "meaning": "සන ගස, පැපිලිය", "category": "plant" },
    { "word": "විලොඩි", "meaning": "මෝරු", "category": "liquid" },

    // --- පිටුව 440 ---
    { "word": "විවස්වන්", "meaning": "වරා, රත්නිටුල්", "category": "plant" },
    { "word": "විවිටප", "meaning": "හැමගස්", "category": "plant" },
    { "word": "විවාසි", "meaning": "කින්හදෙඹ", "category": "plant" },
    { "word": "විශ්‍රගන්ධක", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "විශ්‍රගන්‍ධා", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "විශ්‍රා", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "විශ්තාණ", "meaning": "වෑක්", "category": "plant" },
    { "word": "විශ්ව", "meaning": "සින්දුරා, අතිවිඩයන්, නිප්පිලි", "category": "plant" },
    { "word": "විශ්වක", "meaning": "වාලුඟුන්", "category": "plant" },
    { "word": "විශ්වභෙසජ", "meaning": "අතිවිඩයන්, බින් තල්, පුවඟු", "category": "plant" },
    { "word": "විශ්වභෙසජා", "meaning": "රුකඟුණ", "category": "plant" },
    { "word": "විශ්වගන්‍ධ", "meaning": "ගෙන්දගම්, මූණු, අදු තලා", "category": "plant" },
    { "word": "විශ්වගන්‍ධා", "meaning": "තලා, අදු තලා", "category": "plant" },
    { "word": "විශ්වග්‍රන්ථි", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "විශ්වදෙවා", "meaning": "ගස්කැලිය, මහ බැබිල, ගොඩමානෙල්", "category": "plant" },
    { "word": "විශ්වදේවී", "meaning": "සිරිවාඩි බැබිල", "category": "plant" },
    { "word": "විශ්වභෙපජ", "meaning": "සින්දුරා", "category": "plant" },
    { "word": "විශ්වරූපක", "meaning": "කළු අගිල්", "category": "plant" },
    { "word": "විශ්වරූපී", "meaning": "කලුගල්, අගිල්", "category": "mineral" },
    { "word": "විශ්වසා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "විශ්වා", "meaning": "අතිවිඩයන්, වියලි ඉඟුරු", "category": "plant" },
    { "word": "විශ්වාමිත්‍ර ප්‍රිය", "meaning": "පොල්", "category": "plant" },
    { "word": "විශ්වෞෂධ", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "විශමච්ඡද", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "විශල්‍යකා", "meaning": "කුඹුරු වැල", "category": "plant" },
    { "word": "විශල්‍යා", "meaning": "හෙළ නෙළුම්, මහ ගොන් සුදු කැකිරි, අසමෝදගම්, තිය ගලා, නිටුල් ගස, රසකිඳ, නියඹරා, කටුවැල් බටු", "category": "plant" },
    { "word": "විශා", "meaning": "අතිවිඩයන්, කේසර බැබිල, වච්චනාවි, වෙල් මුඩ (මුඩමහණ)", "category": "plant" },
    { "word": "විශාඛජ", "meaning": "නාරන් ගස", "category": "plant" },
    { "word": "විශාඛා", "meaning": "කරවිල, සාරණ මුල්", "category": "plant" },
    { "word": "විශානි", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "විශාල", "meaning": "රත් මහනෙල්, නියඹරා, ඇත්බටු, (වම්බටු)", "category": "plant" },
    { "word": "විශාලත්ව", "meaning": "රුක් අත්තන", "category": "plant" },
    { "word": "විශාල තලගහ", "meaning": "පියා ගස", "category": "plant" },
    { "word": "විශාල පත්‍ර", "meaning": "තල් ගස", "category": "plant" },
    { "word": "විශාලා", "meaning": "මහ ගොන් සුදු කැකිරි, නියඹරා", "category": "plant" },
    { "word": "විශාලි", "meaning": "අසමෝද", "category": "plant" },
    { "word": "විශිෂ්පර්ණී", "meaning": "කොසඹ", "category": "plant" },
    { "word": "විශුද්ධලවණ", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "විශුද්ධි", "meaning": "කසා", "category": "plant" },
    { "word": "විශෝදරි", "meaning": "කටුවෙලඟ", "category": "plant" },
    { "word": "විශොධනී", "meaning": "දත්ත", "category": "plant" },
    { "word": "විශොධිත්", "meaning": "දත්ත", "category": "plant" },
    { "word": "විශ්‍රගන්‍ධා", "meaning": "වෙල්මුඩ (මුඩමහණ)", "category": "plant" },
    { "word": "විෂටර", "meaning": "නය", "category": "animal" },
    { "word": "විෂටරුහා", "meaning": "රන්වන් වැටකේ", "category": "plant" },
    { "word": "විෂටා", "meaning": "මල, (අසූචි)", "category": "anatomy" },
    { "word": "විෂ්ණුක්‍රාන්තා", "meaning": "කටරොළු", "category": "plant" },
    { "word": "විෂ්ණුක්‍රාන්තා", "meaning": "විෂ්ණුක්‍රාන්තී", "category": "plant" },
    { "word": "විෂ්ණුගන්‍ධ", "meaning": "විෂ්ණුක්‍රාන්තී", "category": "plant" },
    { "word": "විෂ්ණුප්‍රියා", "meaning": "තලා, කළුතලා", "category": "plant" },
    { "word": "විෂ්ණුරූපවන්", "meaning": "කරඳ ගස", "category": "plant" },
    { "word": "විෂ්ණුවල්ලභා", "meaning": "මලිත, තලා", "category": "plant" },
    { "word": "විෂ්ණුවල්ලභා", "meaning": "විෂ්ණුක්‍රාන්තී, ගිනිසිළු, (මලිත) ගස", "category": "plant" },
    { "word": "විෂ්ණුසයන", "meaning": "නුග ගස", "category": "plant" },
    { "word": "විෂ්ණුහිතා", "meaning": "කළුතලා", "category": "plant" },
    { "word": "විෂ්පර්ණී", "meaning": "නිඹිරි ගස", "category": "plant" },
    { "word": "විෂ්පුරණී", "meaning": "නිඹිරි ගස", "category": "plant" },
    { "word": "විෂ්ඵොට", "meaning": "පිළිකාව, පැපොල් හෝ මසූරිකා (වසූරි) රෝග", "category": "treatment" },
    { "word": "විෂ්වක්‍ෂෙණ", "meaning": "පුවඟු, රුකඟුණ", "category": "plant" },
    { "word": "විෂ්වරිත්මස්ප්‍රියා", "meaning": "බිමිතල්", "category": "plant" },
    { "word": "විෂ", "meaning": "නෙළුම් රේණු, නෙළුම් අල, ගෙන්දගම්, වච්චනාවි, ජේරු", "category": "plant" },
    { "word": "විෂකණ්ටකිනි", "meaning": "මල්තුඹ", "category": "plant" },

    // --- පිටුව 441 ---
    { 
        "word": "විෂ කුම්බ", 
        "meaning": "මඤ්ඤොක්කා කොළ වැනි කොළ හා රත් පාට මල් පොකුරු ත් රට එඬරු ගෙඩි වැනි ගෙඩි ත් ඇති මේ ගසට විෂ කුම්බ යයි කියති. මෙය සර්ප විෂ නාසක විෂකුම්භ නැමැති ඖෂධය ලෙස බොහෝ දෙනා කියත ත් හැඩ හුරු කමින් මෙය ලංකාවට මෑතකදී බෝ වූ ත ගසක් බැව් පෙනේ.\n\nඅපේ පැරණි සිංහල වෙද පොත් වල විෂකුම්භා නමින් හැඳින් වෙන්නේ කඳේ ත් මුල් වල ත් අත්තික්කා වැනි ගෙඩි හා බූව සහිත දිග කොළ ඇති ගසේ පට්ටාව දිගට ම ගැලවෙන කොටදිඹුලා = (කබුඩු අත්තික්කා = වායසෝදුම්බර) යන අපර නාමයන්ගෙන් හැඳින්වෙන (Ficus Hispida) නමැති කොට දිඹුලා ගස යි. ජයපාල වලට ද විෂකුම්භා යයි කියති. විෂ සහිත වගියක් නිසා එයට විෂ කුම්බ ය යි කියනවා විය හැක.", 
        "category": "plant",
        "image": "img_9346b9_vishakumba.jpg"
    },
    { "word": "විෂ ගන්ධකා", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "විෂගන්ධි", "meaning": "රම්මානිස්ස", "category": "plant" },
    { "word": "විෂගන්ධිනී", "meaning": "අතිවිඩයම්", "category": "plant" },
    { "word": "විෂඝන", "meaning": "සියඹලා, පෙරුම්කායම්, මුල", "category": "plant" },
    { "word": "විෂඝනබීජ", "meaning": "මූණමල්", "category": "plant" },
    { "word": "විෂඝනී", "meaning": "සියඹලා, මහ ලුක්, සස්සඳ, පෙරුම්කායම්, ගොඩ මේරිය, මුඩමහණ, රතණ, දේවදාලි, සුදු (හෙළ) කටරොළු", "category": "plant" },
    { "word": "විෂජිත්", "meaning": "මහරි", "category": "plant" },
    { "word": "විෂජ්හව", "meaning": "දේවදාලි", "category": "plant" },
    { "word": "විෂණ්ඩ", "meaning": "නෙළුම් අල", "category": "plant" },
    { "word": "විෂනිහංසුකා", "meaning": "කුපිලු, (ගොඩකදුරු)", "category": "plant" },
    { "word": "විෂද", "meaning": "මල් කසිස්", "category": "mineral" },
    { "word": "විෂදා", "meaning": "වම්බොටු", "category": "plant" },
    { "word": "විෂද්‍රැ", "meaning": "සියඹලා", "category": "plant" },
    { "word": "විෂද්‍රැමාණී", "meaning": "මුඩමහණ (ව්‍යාධි රෝගයට හා ග්‍රහණියට ගුණ දෙන ඖෂධයකි. 373 පිට බලන්න)", "category": "plant" },
    { "word": "විෂද්‍රැම", "meaning": "වල් මුරුංගා", "category": "plant" },
    { "word": "විෂධවංසි", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "විෂධ", "meaning": "මහ කසිස්", "category": "mineral" },
    { "word": "විෂධා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "විෂඝාතින්", "meaning": "මාරා, කසඹිලියා, මුල, සපු, කැකිරි, අදුතලා, පිටවක්කා, රතු සාරණ, කහ, ඇත්සැටිය, මහ කරඳ, වදකසා, පිංබාහිඟු, සියඹලා, ලෝලු", "category": "plant" },

    // --- පිටුව 442 ---
    { "word": "විෂනාසන", "meaning": "මාරා ගස (මෙය විෂ නාසක ඖෂධයකි)", "category": "plant" },
    { "word": "විෂනාසනී", "meaning": "රසකිඳ, තියද", "category": "plant" },
    { "word": "විෂනුද්", "meaning": "තොටිල", "category": "plant" },
    { "word": "විෂපහ", "meaning": "කටරොළු වැල්, නිත්තලබු", "category": "plant" },
    { "word": "විෂපු", "meaning": "විසප්පු", "category": "treatment" },
    { "word": "විෂපුෂ්ප", "meaning": "නිල් නෙළුම්, කුකුරුමාන්", "category": "plant" },
    { "word": "විෂපුෂ්පක", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "විෂමච්ඡද", "meaning": "රුක් අත්තන", "category": "plant" },
    { "word": "විෂමමණ්ඩල", "meaning": "තොලබෝ(තොලබෝ ග්‍රන්ථි ශොථයට ප්‍රත්‍යක්‍ෂ බෙහෙතකි. 231 පිට බලන්න)", "category": "plant" },
    { "word": "විෂමදල", "meaning": "රුක් අත්තන", "category": "plant" },
    { "word": "විෂමදෙහක", "meaning": "ලෙඩ ඇත්තෙක්", "category": "person" },
    { "word": "විෂමර්දනී", "meaning": "අරත්ත, ඒකාවේරිය", "category": "plant" },
    { "word": "විෂමුෂ්ටික", "meaning": "ගොඩකදුරු", "category": "plant" },
    { "word": "විෂමුෂ්ටී", "meaning": "ජේරු, ගොඩකදුරු", "category": "plant" },
    { "word": "විෂරූ", "meaning": "නිඹිරි", "category": "plant" },
    { "word": "විෂරූප", "meaning": "අතිවිඩයන්", "category": "plant" },
    { "word": "විෂරූපක", "meaning": "කළු අගිල්", "category": "plant" },
    { "word": "විෂරූපා", "meaning": "අතිවිඩයන්", "category": "plant" },
    { "word": "විෂලතා", "meaning": "කැකිරි වැල", "category": "plant" },
    { "word": "විෂල්‍යා", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "විෂවෘක්‍ෂ", "meaning": "රේරු ගස", "category": "plant" },
    { "word": "විෂවාලක", "meaning": "නෙළුම් අල", "category": "plant" },
    { "word": "විෂවිනාසනී", "meaning": "තියද", "category": "plant" },
    { "word": "විෂස්න", "meaning": "මාරා, සපු, මුලු, වේලා, ගොන් කැකිරි, යවාස, මහ කරඳ", "category": "plant" },
    { "word": "විෂහනනී", "meaning": "කටරොළු", "category": "plant" },
    { "word": "විෂහා", "meaning": "දේවදාලිය වැල", "category": "plant" },
    { "word": "විෂා", "meaning": "අතිවිඩයන්, කේසර බැබිල, ලියනඟලා, ජේරු", "category": "plant" },
    { "word": "විෂාඛ", "meaning": "සුළු සාරණ", "category": "plant" },
    { "word": "විෂාඛතුල", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "විෂාණී", "meaning": "මුවන් ආදීන් ගේ අඟ, ඇත් දත, ඌරුදත, කොට්ටන්, කිරිකවෙළු", "category": "animal" },
    { "word": "විෂාණික", "meaning": "තෝර ගස", "category": "plant" },
    { "word": "විෂාණිකා", "meaning": "කකීටකශෘංගි, නෙල්ලි, පින්මැලි, අඟ, මැඩහඟු", "category": "plant" },
    { "word": "විෂාණිකා කුසුම", "meaning": "කෙනෙල් ගස", "category": "plant" },
    { "word": "විෂාණී (2)", "meaning": "යහපනක, මැඩහඟු, ඇත්සාටිය", "category": "plant" },
    { "word": "විෂාද", "meaning": "මහ සාරණ", "category": "plant" },
    { "word": "විෂාපහ", "meaning": "නික්ත ලබු", "category": "plant" },
    { "word": "විෂාපහා", "meaning": "කටුවෙලඟ, ඇපල, කළුනික, දේවදාලිය, කටරොළු, නික්ත ලබු", "category": "plant" },
    { "word": "විෂායනා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "විෂාරද", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "විෂාරාති", "meaning": "කළු අත්තන, මහ එරබු", "category": "plant" },
    { "word": "විෂාරී", "meaning": "දිය බෙරලිය, ප්‍රතිකර්ඤ්ඤ", "category": "plant" },
    { "word": "විෂාවහ", "meaning": "සස්සඳ, වරාමුල, ගොන්කැකිරි, නාගදමනී", "category": "plant" },
    { "word": "විෂාස්‍ය", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "විෂෞෂධි", "meaning": "දත්ත, (මහාදන්තී)", "category": "plant" },
    { "word": "විස්ව", "meaning": "නිප්පිලි, ඉඟුරු", "category": "plant" },
    { "word": "විස්වරූපක", "meaning": "කළු වැල්", "category": "plant" },
    { "word": "විසංලක", "meaning": "වාලුඟුන්", "category": "plant" },
    { "word": "විසඤ්ඤා", "meaning": "වෙනිවැල්කෂායෙන් යුත් තුත්තම්", "category": "treatment" },
    { "word": "විසණ්ණී", "meaning": "තලිය පතුරා", "category": "plant" },
    { "word": "විසුගන්‍ධා", "meaning": "නියඹරා", "category": "plant" },
    { "word": "විසුගන්ධි", "meaning": "හිරියල්", "category": "mineral" },
    { "word": "විස", "meaning": "නෙළුඹුදැලි, නෙරිවිස, සර්පවිස, වච්චනාවි", "category": "plant" },
    { "word": "විසකුසුම", "meaning": "නෙළුම් මල", "category": "plant" },
    { "word": "විසගඳ", "meaning": "ඉවද, අතිවිඩයම්", "category": "plant" },
    { "word": "විසගන්ධි", "meaning": "රන්වන් වේලා", "category": "plant" },
    { "word": "විසඝාත", "meaning": "වාලුඟුන්", "category": "plant" },
    { "word": "විසද", "meaning": "සාරණ", "category": "plant" },

//  පිටු 443 සිට 446 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 210
 // --- පිටුව 443 ---
    { 
        "word": "විස දූවිලි", 
        "meaning": "වඳුරු මෑ හෝ උඩවැඩියා වගියට අයත් පැල වගියක් මේ වගියේ ගෙඩි වේලී පිපිරුණ විට නික්මෙන දූලි (දූවිලි) වැනි ඇට ඇඟේ ගෑවුනහොත් කසීම, දූවිල්ල, හා වේදනාව ගණියි.", 
        "category": "plant" 
    },
    { "word": "විසනිරි", "meaning": "නෙරිවිස", "category": "plant" },
    { "word": "විසබිජු", "meaning": "ජයපාල ඇට", "category": "plant" },
    { "word": "විසමදල", "meaning": "රක් අත්තන", "category": "plant" },
    { "word": "විසල්", "meaning": "රක්තත්තන ගස", "category": "plant" },
    { "word": "විසල්‍යා", "meaning": "රසකිඳ, නියඹරා, අසමෝද, මලිත, දත්ත", "category": "plant" },
    { "word": "විසලදල", "meaning": "රක්අත්තන", "category": "plant" },
    { "word": "විසවිහා", "meaning": "රේරු", "category": "plant" },
    { "word": "විසවා", "meaning": "ඉවද", "category": "plant" },
    { "word": "විසස්න", "meaning": "ගමිසූරිය", "category": "plant" },
    { "word": "විසා", "meaning": "ඉවද", "category": "plant" },
    { "word": "විසාරින්", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "විසාල", "meaning": "කුඹුරු වැල", "category": "plant" },
    { "word": "විසාලා", "meaning": "පෙනෙල ගස, ගොන් කැකිරි", "category": "plant" },
    { "word": "විසාලාක්‍ෂි", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "විසාහ්වය", "meaning": "රේරු", "category": "plant" },
    { "word": "විසි", "meaning": "මාරා ගස, මදට ගස", "category": "plant" },
    { "word": "විසිනී", "meaning": "නෙළුම්, කෙරව", "category": "plant" },
    { "word": "විසිවන", "meaning": "මාරා", "category": "plant" },
    { "word": "විසිවනසු", "meaning": "මදට", "category": "plant" },
    { "word": "විසුවිකා", "meaning": "අතීසාරය", "category": "treatment" },
    { "word": "විහිද", "meaning": "තණරද", "category": "plant" },
    { "word": "විහිදි / විහිදුම්", "meaning": "පුබුදුවීම", "category": "general" },
    { "word": "විළඟං", "meaning": "වළඟ සාල්", "category": "plant" },
    { "word": "වීජ", "meaning": "අංකුරය, ඇට, ගෙඩි ආදිය", "category": "plant" },
    { "word": "වීජක", "meaning": "නස්නාරන්", "category": "plant" },
    { "word": "වීජකොෂ", "meaning": "නෙළුම් බඩිටා", "category": "plant" },
    { "word": "වීජග්‍රහී", "meaning": "පතෝල", "category": "plant" },
    { "word": "වීජග්‍රහණී", "meaning": "මුවාන්ත", "category": "plant" },
    { "word": "වීජපාදප", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "වීජ පුෂ්ප", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "වීජපූර", "meaning": "දෙබොම් ප්‍රභේදයක්, ලප් නාරන්", "category": "plant" },
    { "word": "වීජඵලකා", "meaning": "දෙල්ම, කුකුරුමාන්, දෙබොම්", "category": "plant" },
    { "word": "වීජමාතෘකා", "meaning": "නෙළුම් ඇට", "category": "plant" },
    { "word": "වීජරසන", "meaning": "මෑ, උඳු", "category": "plant" },
    { "word": "වීජරෙවන", "meaning": "ජයපාල ඇට", "category": "plant" },
    { "word": "වීජවෘක්‍ෂ", "meaning": "පියා ගස", "category": "plant" },
    { "word": "වීජාලි", "meaning": "සියඹලා", "category": "plant" },
    { "word": "වීජිකා", "meaning": "බුලත් වැල", "category": "plant" },
    { "word": "වීඩාල", "meaning": "තුන්පත් කුරුඳු", "category": "plant" },
    { "word": "වීත්තු", "meaning": "අන්දර", "category": "plant" },
    { "word": "වීජ්‍යා", "meaning": "තුරු පෙලු", "category": "plant" },
    { "word": "වීර්‍ය්‍ය", "meaning": "ශුක්‍රධාතුව", "category": "anatomy" },
    { "word": "වීර", "meaning": "කුඹුක්, නිඹිරි, සාමහක, උණකපුරු, මිරිස්, කාඩි, බදුල්ල ගස, නෙළුම් අල, සැවැන්න", "category": "plant" },
    { "word": "වීරක", "meaning": "කණේරු", "category": "plant" },
    { "word": "වීරකණ්ඨා", "meaning": "නරිඅල", "category": "plant" },
    { "word": "වීරණ", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "වීරණ කෂායක", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "වීරණ මූලිකා", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "වීරණී", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "වීරතර", "meaning": "සැවැන්න, අන්දර, කුඹුක්, බදුල්ල", "category": "plant" },
    { "word": "වීරතරු", "meaning": "අන්දර, කුඹුක්, ඉකිරි, බදුල්ල", "category": "plant" },
    { "word": "වීරතුර", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "වීරද", "meaning": "අන්දර", "category": "plant" },
    { "word": "වීරපත්‍ර", "meaning": "කංසා", "category": "plant" },
    { "word": "වීරපත්‍රා", "meaning": "ඉද්ද, බඹදමි", "category": "plant" },
    { "word": "වීරභද්‍ර", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "වීර වෘක්‍ෂ", "meaning": "අන්දර, බදුල්ල", "category": "plant" },

    // --- පිටුව 444 ---
    { 
        "word": "වීරතරාදි ගණය", 
        "meaning": "අන්දර, සිහින් මිදි, වෑක්, පෝටා, ගිතණ, බොරළු දමුණු, සාතාවාරිය, කොබෝවක්කා, තොටිල, ගොකටු, යාපුර, (තිරිල) රත් මල් ගස්, ඉළුප්, කටුකරඬු දෙවගය, පගණිඛෙය (පොල් පලා) යන මේ වීරතරාදි ගණය අශ්මරි - මූත්‍ර කෘච්ඡ්‍ර - මූත්‍ර අඝාත හා වාතරෝග නසන්නේ යි.", 
        "category": "compound" 
    },
    { "word": "වීර හනස්", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "වීරා", "meaning": "කිරි කවෙලු, නෙල්ලි, එන්සාල්, කෙසෙල්, වරා, කිරිබදු, මහ සාතාවාරිය, කෝමාරිකා, අතිවුඩයන්, මුද්දරප්පලම්, ඉන්සළු, කිරිඳි, කිරිකවෙළු", "category": "plant" },
    { "word": "වීරාමිල", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "වීරාසිරා", "meaning": "කිරි අඟුණ ගස", "category": "plant" },
    { "word": "වීරිකතා", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "වීරු", "meaning": "කළුදුරු, පණු බොහො ඇති වැල", "category": "plant" },
    { "word": "වීරුඬ", "meaning": "ඉඟුරු, උබෑත්ත, වරා", "category": "plant" },
    { "word": "වීරුප", "meaning": "කසා, අතිවුඩයන්, පුණ්ඩි, වගපුල්", "category": "plant" },
    { "word": "වීරුපා", "meaning": "උබෑත්ත, දුරාලභා", "category": "plant" },
    { "word": "වීලි", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "වීස", "meaning": "ඉලු සල් ගස", "category": "plant" },
    { "word": "වීසන", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "වෘද්ධිරෝග", "meaning": "වෘද්ධි රෝගය", "category": "treatment" },
    { "word": "වෘන්තෙ", "meaning": "නිබ්බටු", "category": "plant" },
    { "word": "වෘච්ච", "meaning": "උළුවා", "category": "plant" },
    { "word": "වෘෂණ", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වෘසභිල", "meaning": "සියඹලා ගස", "category": "plant" },
    { "word": "වෘකා", "meaning": "වගුබුව", "category": "plant" },
    { "word": "වෘකා පුෂ්පකා", "meaning": "මහරි", "category": "plant" },
    { "word": "වෘක්‍ෂ", "meaning": "කෙළින්ද ගස", "category": "plant" },
    { "word": "වෘක්‍ෂක", "meaning": "පියා ගස, ගස, කෙළින්ද", "category": "plant" },
    { "word": "වෘක්‍ෂකඳ", "meaning": "බින්තල්", "category": "plant" },
    { "word": "වෘක්‍ෂකද", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "වෘක්‍ෂගන්ධ", "meaning": "සින් දුමැඬ", "category": "plant" },
    { "word": "වෘක්‍ෂගන්ධිනී", "meaning": "ගැටතුඹ", "category": "plant" },
    { "word": "වෘක්‍ෂධූප", "meaning": "හොර ගස", "category": "plant" },
    { "word": "වෘක්‍ෂනාථ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "වෘක්‍ෂපර්ණී", "meaning": "රුක් කොළ", "category": "plant" },
    { "word": "වෘක්‍ෂපාක", "meaning": "නුග ගස", "category": "plant" },
    { "word": "වෘක්‍ෂභක්‍ෂ", "meaning": "පිළිල", "category": "plant" },
    { "word": "වෘක්‍ෂභයාශ්‍රිතා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "වෘක්‍ෂමැන්‍දිනී", "meaning": "දිය හොමුවානු", "category": "plant" },
    { "word": "වෘක්‍ෂයාශි", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "වෘක්‍ෂරුහා", "meaning": "පිළිල, සින්දුමැඬ", "category": "plant" },
    { "word": "වෘක්‍ෂසාරක", "meaning": "ගැටතුඹ", "category": "plant" },
    { "word": "වෘක්‍ෂාදන", "meaning": "ඇසටු, පියාගස, පිළිල", "category": "plant" },
    { "word": "වෘක්‍ෂාදනී", "meaning": "පුවටා, සින්දුමැඬ, පිළිල", "category": "plant" },
    { "word": "වෘක්‍ෂාමල", "meaning": "සියඹලා, රටගොරක", "category": "plant" },
    { "word": "වෘක්‍ෂොත්පල", "meaning": "මිදිගස, කින්හිරි ගස", "category": "plant" },
    { "word": "වෘක", "meaning": "කෝවක්කා, දියමිත්ත", "category": "plant" },
    { "word": "වෘකධූප", "meaning": "සිරිවඩු, දඬුබාඬි ධූප (දඬුබාඩි ධූප)", "category": "plant" },
    { "word": "වෘකධුම", "meaning": "තුරුක් තෙල්, ඇපල, ගුගුල්", "category": "mineral" },
    { "word": "වෘක ධූම", "meaning": "තුරුක් තෙල්, ඇපල, ගුගුල්", "category": "mineral" },
    { "word": "වෘකමුලක", "meaning": "ඇපල", "category": "plant" },
    { "word": "වෘකවන්තකා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වෘණ", "meaning": "වණය, තුවාලය", "category": "treatment" },
    { "word": "වෘණිකා", "meaning": "කටුතලා", "category": "plant" },
    { "word": "වෘණකාරක", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "වෘණිස්න", "meaning": "මසේනිය (මස්වැන්න)", "category": "plant" },
    { "word": "වෘණිස්නී", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "වෘණිරිපු", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "වෘණසොධන", "meaning": "කඩුවෙලඟ", "category": "plant" },

    // --- පිටුව 445 ---
    { "word": "වෘෂණහා", "meaning": "එරබු", "category": "plant" },
    { "word": "වෘෂාලිකා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "වෘෂෙණිනා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වෘෂෙනිතා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වෘන්ත", "meaning": "බින්තල්, ඇඹුල, වතුසුද්ද මල", "category": "plant" },
    { "word": "වෘන්තකෝෂ", "meaning": "දේවදාලි", "category": "plant" },
    { "word": "වෘන්තපත්‍රා", "meaning": "දියමිත්ත, දියබෙරලිය", "category": "plant" },
    { "word": "වෘන්තපර්ණී", "meaning": "මහ නාමල්, දියමිත්ත", "category": "plant" },
    { "word": "වෘන්තපුෂ්ප", "meaning": "කොළොම්, මාරා", "category": "plant" },
    { "word": "වෘන්තපුෂ්පක", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "වෘන්තපුෂ්පා", "meaning": "කෙසෙල් ගස, බක්මී", "category": "plant" },
    { "word": "වෘන්තඵල", "meaning": "දෙහි, මිරිස්, දෙළුම්, බෙබර, ජූල්, (දිවුල්) බටු, නෙල්ලි", "category": "plant" },
    { "word": "වෘන්තමල්ලිකා", "meaning": "හෙළවරා", "category": "plant" },
    { "word": "වෘන්තලොහ", "meaning": "පිත්තල", "category": "mineral" },
    { "word": "වෘන්තවිප්‍ර", "meaning": "නාපිරිත්ත, ආසකි", "category": "plant" },
    { "word": "වෘන්තා", "meaning": "මස්වැන්න, පුවඟු", "category": "plant" },
    { "word": "වෘන්තාබිණි", "meaning": "පතුක්", "category": "plant" },
    { "word": "වෘන්තාස්‍ර", "meaning": "මස්වැන්න", "category": "plant" },
    { "word": "වෘන්තිකා", "meaning": "නෙළුදම්", "category": "plant" },
    { "word": "වෘත්තිකා", "meaning": "හෙළුදම්, සේපාලිකා", "category": "plant" },
    { "word": "වෘතෙතන්‍දිවර", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "වෘන්තා", "meaning": "අරළු", "category": "plant" },
    { "word": "වෘශ්චිකා", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "වෘද්ධ", "meaning": "ගල්මද, ගල්සෙවෙල්, කප්පරවල්ලිය, නවහැකිලිය, බදුල්ලගස", "category": "plant" },
    { "word": "වෘද්ධපාත", "meaning": "බුළු ගස", "category": "plant" },
    { "word": "වෘද්ධදාරිකා", "meaning": "මුහුණුවැන්න", "category": "plant" },
    { "word": "වෘද්ධඵල", "meaning": "දේවදාලිය, අන්දරගස, විලිකුම් ගෙඩි", "category": "plant" },
    { "word": "වෘද්ධරුප්", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "වෘද්ධිහිතක", "meaning": "ඇම්බරල්ල", "category": "plant" },
    { "word": "වෘශ්චි", "meaning": "ගල්වල හටගන්නා ද්‍රව්‍යයක්. අකෝෂ, ඇත්බැබිල", "category": "plant" },
    { "word": "වෘශ්චිකා", "meaning": "අපතක වගියේ ඔසුවක්", "category": "plant" },
    { 
        "word": "වෘඬදාරු වැල්", 
        "scientific": "Argyreia Speciosa",
        "meaning": "Argyreia Speciosa-ලංකාවේ ගිරිතිල්ල වෙනුවට ඉන්දියාවේ ගන්නේ මේ වැල් ය. මෙහි කොළ රසකිඳ කොළ වලට මදක් සමාන ය. කොළ වල විල්ලුද වැනි දිලිසෙන සුදු බූවක් තිබේ. වැල් ද මූරුවා වැල් මෙන් සුදු පාට ය.", 
        "category": "plant",
        "image": "img_93b75b_vruddhadaru.jpg"
    },
    { "word": "වෘෂන", "meaning": "නටු", "category": "plant" },
    { "word": "වෘන්තාඵල", "meaning": "රත්සැබෝ", "category": "plant" },
    { "word": "වෘන්තා", "meaning": "රත් පලොල්", "category": "plant" },
    { "word": "වෘන්තාකි", "meaning": "වම්බටු", "category": "plant" },
    { "word": "වෘන්තිකා", "meaning": "කටුකරෝහිණී", "category": "plant" },
    { "word": "වෘක්‍ෂ", "meaning": "තලා, අබ", "category": "plant" },
    { "word": "වෘශා", "meaning": "රක්මල්", "category": "plant" },

    // --- පිටුව 446 ---
    { "word": "වෘශ්චවාක", "meaning": "කෝවක්කා, මදනගස", "category": "plant" },
    { "word": "වෘශ්චික", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "වෘශ්චික කර්ණී", "meaning": "මිකන්පලා", "category": "plant" },
    { "word": "වෘශ්විකාදංෂ්ට්‍රා", "meaning": "ඇත්සැටිය", "category": "plant" },
    { "word": "වෘශ්චිකාලි", "meaning": "වැල්කසඹිලියා (එළු අං මෙන් උඩට නැගී කරල් ඇති මදක් බූවසහිත දියමිත්ත වැනි පත්‍ර වලින් යුත් කටු සහිත දකුණට කරකැවෙන වැල් වගියක් ය යි සුශ්‍රැත ටීකාවේ කියා තිබේ). වේලිපරිත්ති මේ ලකුණු වලින් යුක්ත යි.", "category": "plant" },
    { "word": "වෘශ්චිපත්‍රී", "meaning": "ඇත්සැටිය, වැල්කසඹිලියා", "category": "plant" },
    { "word": "වෘශ්විපර්ණී", "meaning": "ඇත්සැටිය, වෘශ්විකාලි", "category": "plant" },
    { "word": "වෘශ්වී", "meaning": "ඇත්සාටිය", "category": "plant" },
    { "word": "වෘශ්වීර", "meaning": "සුදු සාරණ", "category": "plant" },
    { "word": "වෘෂ්ටිඝනී", "meaning": "හින් එන්සාල්", "category": "plant" },
    { "word": "වෘෂභ", "meaning": "ශුක්ල වැඩිකරණ, නෙල්ලි, සාතාවාරිය. ඔසබිය, මුද්‍රික ඵල", "category": "plant" },
    { "word": "වෘෂභක", "meaning": "කිරිබදු අල", "category": "plant" },
    { "word": "වෘෂභගන්ධ", "meaning": "කිරිබදු, කොටිකන් බැබිල", "category": "plant" },
    { "word": "වෘෂභගන්ධිකා", "meaning": "මහබැබිල", "category": "plant" },
    { "word": "වෘෂභවල්ලී", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "වෘෂභා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "වෘෂ", "meaning": "පාංශු ලුණු, ඔසබිය, ආඩතෝඩා, මොණරපිල්", "category": "plant" },
    { "word": "වෘෂක", "meaning": "පාංශු ලුණු, ආඩතෝඩා", "category": "plant" },
    { "word": "වෘෂකණ්පා", "meaning": "මුගුණුවැන්න", "category": "plant" },
    { "word": "වෘෂකපාසී", "meaning": "බුලත්", "category": "plant" },
    { "word": "වෘෂගද", "meaning": "රම්මානිස්ස", "category": "plant" },
    { "word": "වෘෂගන්ධිකා", "meaning": "ගිරිනිල්ල", "category": "plant" },
    { "word": "වෘෂද", "meaning": "රිදී", "category": "mineral" },
    { "word": "වෘෂදංශක", "meaning": "බළලා", "category": "animal" },
    { "word": "වෘෂදංශවිඩ්", "meaning": "බලල් වසුරු", "category": "animal" },
    { "word": "වෘෂ දවාග්නි", "meaning": "ඉඟුරු, කලාදුරු", "category": "plant" },
    { "word": "වෘෂනාශක", "meaning": "වළඟසාල්", "category": "plant" },
    { "word": "වෘෂපර්ණී", "meaning": "කොතුරබාඑද්ද = (මිකන්පලා)", "category": "plant" },
    { "word": "වෘෂපුෂ්පිකා", "meaning": "ගොඩමානෙල්", "category": "plant" },
    { "word": "වෘෂභ (2)", "meaning": "ඔසබිය, ගොන්කැකිරි", "category": "plant" },
    { "word": "වෘෂභාක්‍ෂි", "meaning": "නියඹරා, කටරොළු, කැකිරි", "category": "plant" },
    { "word": "වෘෂභී", "meaning": "මහ එන්සාල්", "category": "plant" },
    { "word": "වෘෂවර්ජ", "meaning": "එඬරු", "category": "plant" },
    { "word": "වෘෂා", "meaning": "වංඇපල, අමුක්කරා, හාතාවාරිය, දුදු, මුගුණුවැන්න", "category": "plant" },
    { "word": "වෘෂාකා", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "වෘෂාඞ්ගි", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "වෘෂාදනී", "meaning": "කැකිරි", "category": "plant" },
    { "word": "වෘෂාලි", "meaning": "ගිරිනිල්ල", "category": "plant" },
    { "word": "වෘහච්චඤ්චු", "meaning": "මහඑරබු", "category": "plant" },
    { "word": "වෘහච්ඡදා", "meaning": "නස්නාරම්", "category": "plant" },
    { "word": "වෘහත්ගලා", "meaning": "මහබැබිල", "category": "plant" },
    { "word": "වෘහත්නාල", "meaning": "කිතුල්", "category": "plant" },
    { "word": "වෘහත්නිම්බා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වෘහත්පාණී", "meaning": "උණ ගස", "category": "plant" },
    { "word": "වෘහත්පාටලි", "meaning": "අත්තන ගස", "category": "plant" },
    { "word": "වෘහත්පාදප", "meaning": "නුග ගස", "category": "plant" },
    { "word": "වෘහත්පාලින්", "meaning": "වල්දුරු", "category": "plant" },
    { "word": "වෘහත්ඵල", "meaning": "මහමොර", "category": "plant" },
    { "word": "වෘහත්පුෂ්පී", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "වෘහත්ඵලා", "meaning": "මාදම්, නික්ත ලබු", "category": "plant" },
    { "word": "වෘහත්බලා", "meaning": "මහබැබිල", "category": "plant" },
    { "word": "වෘහත්බානු", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "වෘහතිකා", "meaning": "බටු", "category": "plant" },
    { "word": "වෘහතී", "meaning": "කටුවැල්බටු, වම්බටු, කුඩාබටු", "category": "plant" },
    { "word": "වෘහද්දල", "meaning": "කිතුල්, පට්ටිකා ලොත්", "category": "plant" },
    { "word": "වෘහද්දාල", "meaning": "මහලියනඟලා වැල", "category": "plant" },
    { "word": "වෘහද්වල්ක", "meaning": "පට්ටිකා ලොත්", "category": "plant" },
    { "word": "වෘහද්වාරැණී", "meaning": "මහනියඹරා", "category": "plant" },
    { "word": "වෘහද්විප්", "meaning": "ඇම්බරල්ල", "category": "plant" },




// සම්පූර්ණ වචන සංඛ්‍යාව: 109

    // --- පිටුව 447 ---
    { "word": "වෘහදම්ලා", "meaning": "කාමරංගා", "category": "plant" },
    { "word": "වෘහදලා", "meaning": "මහ එන්සාල්", "category": "plant" },
    { "word": "වෘහනතල", "meaning": "මහ උක්", "category": "plant" },
    { "word": "වෘහන්තලා", "meaning": "කුඹුක්", "category": "plant" },
    { "word": "වෙගා", "meaning": "කටුවෙලඟ", "category": "plant" },
    { "word": "වෙජයන්තිකා", "meaning": "නිතිග", "category": "plant" },
    { "word": "වෙජානා", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "වෙඩිඋප්පු", "meaning": "වෙඩිලුණු", "category": "mineral" },
    { "word": "වෙඩිසන්ති", "meaning": "සන්නි රෝගයක්", "category": "treatment" },
    { "word": "වෙණි", "meaning": "දේවදාර", "category": "plant" },
    { 
        "word": "වෙණිවැල්", 
        "meaning": "වතුවැල් = මුරුවා කොළ වලට මදක් සමාන කහ පාටින් යුත් වැල් වගියක්. තද තික්ත ගතියක් ඇති මේ වැල් ජ්වර - වාතාබාධ හා ග්‍රන්ථි රෝගයට ගන්නා බෙහෙත් වගී වලට එකතු කරති. ඖෂධ සඳහා ගන්නේ මේ වැල් වගියේ මහත් වී තිබෙන පුරුක් (ගැට) ය. තැල්මට හා පිටගැස්මට ද වෙනි වැල් ගැට ප්‍රත්‍යක්‍ෂ ඖෂධයකි. මහරක් දිගිරි කිරීමට හා ඇඳි මට ගන්නා නිසා බාන් වැල් නමින් ද, කහ පාට නිසා කහ වැල් නමින් ද, ගම්වාසීන් අතර ප්‍රසිද්ධ මේ වැල් වගිය ඖෂධ වශයෙන් ගන්නේ දාරුහරිද්‍රා නමැති ඉන්දියානු ගස් වගිය වෙනුවට ය.", 
        "category": "plant" 
    },
    { "word": "වෙණීර", "meaning": "කොහොඹ", "category": "plant" },
    { "word": "වෙණු", "meaning": "උණගස", "category": "plant" },
    { "word": "වෙණුකකීර", "meaning": "කණේරු", "category": "plant" },
    { "word": "වෙණුජ", "meaning": "මිරිස්", "category": "plant" },
    { "word": "වෙණුපත්‍රී", "meaning": "පිණ්ඩාහිංගු, දියබෙරලිය", "category": "plant" },
    { "word": "වෙණයව", "meaning": "උණහාල්", "category": "plant" },
    { "word": "වෙත්නිලේ", "meaning": "බුලත්", "category": "plant" },
    { "word": "වෙතු", "meaning": "වේවැල", "category": "plant" },
    { "word": "වෙතන", "meaning": "ඇල්වේවැල", "category": "plant" },
    { "word": "වෙතසාම්ල", "meaning": "ඇඹුල්වේ", "category": "plant" },
    { "word": "වෙතුම්පෙ", "meaning": "අනෝදා ගස", "category": "plant" },
    { "word": "වෙද", "meaning": "පෙරුම්කායම්, රසදිය, දිය පුබාවා", "category": "plant" },
    { "word": "වෙදමඬු", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වෙදමුක්ඛ්‍ය", "meaning": "කස්තුරි, හිඟුරුපියලි", "category": "plant" },
    { "word": "වෙදමුක්ඛ්‍යක", "meaning": "හිඟුරුපියලි", "category": "plant" },
    { "word": "වෙදමුල්", "meaning": "වංඇපල මුල්", "category": "plant" },
    { "word": "වෙදරාළගෙ මෝ", "meaning": "(වෛද්‍ය මාතා) වංඇපල (සර්ප වෙදකමේ රහස් වචනයක්)", "category": "plant" },
    { "word": "වෙදවේ", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වෙදි", "meaning": "දියමිත්ත, ඇඹුලාගිලිය, බැමි තිරිය", "category": "plant" },
    { "word": "වෙධක", "meaning": "ඇඹුල්වේ, කොත්තමල්ලි, යකඩ, රසදිය", "category": "plant" },
    { "word": "වෙධනී", "meaning": "කස්තුරි, උළුවා", "category": "plant" },
    { "word": "වෙධස්", "meaning": "එළවරා", "category": "plant" },
    { "word": "වෙධිනී", "meaning": "පුබාවා", "category": "plant" },
    { "word": "වෙන්කඩුගු", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "වෙන්කනලි", "meaning": "එළ ඔලිඳ වැල", "category": "plant" },
    { "word": "වෙන්කරන්කාලි", "meaning": "හෙළ කිහිරි", "category": "plant" },
    { "word": "වෙන්කල්", "meaning": "ලෝකඩ", "category": "mineral" },
    { "word": "වෙන්කාලල්ලි", "meaning": "සුදුමුතු අල", "category": "plant" },
    { "word": "වෙන්කොලි", "meaning": "පිලගස, හෙළ පිල", "category": "plant" },
    { "word": "වෙන්තාමරසි", "meaning": "හෙළ නෙළුම්", "category": "plant" },
    { "word": "වෙන්තුලෙ", "meaning": "අදුතලා", "category": "plant" },
    { "word": "වෙන්තොඹි", "meaning": "නියඟලා", "category": "plant" },
    { "word": "වෙන්තාවල්", "meaning": "හාලිදඹ", "category": "plant" },
    { "word": "වෙන්තීර", "meaning": "උණුවතුර", "category": "liquid" },
    { "word": "වෙන්නේ", "meaning": "එළ එඬරු", "category": "plant" },
    { "word": "වෙනි", "meaning": "දේවදාලි", "category": "plant" },

    // --- පිටුව 448 ---
    { "word": "වෙනු", "meaning": "උණගස, නිල්උණ", "category": "plant" },
    { "word": "වෙනුරස්", "meaning": "විෂ්ණුක්‍රාන්තී", "category": "plant" },
    { "word": "වෙප්පමරම්", "meaning": "කොසඹ ගස", "category": "plant" },
    { "word": "වෙප්පාල් අරිසි", "meaning": "කෙළිඳසාල්", "category": "plant" },
    { "word": "වෙප්පාලෙයි", "meaning": "කෙළිඳ ගස", "category": "plant" },
    { "word": "වෙපටී", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වෙපථු", "meaning": "කම්පාවීම, වෙව්ලීම", "category": "treatment" },
    { "word": "වෙම්බු", "meaning": "කොසඹ", "category": "plant" },
    { "word": "වෙම්බුමරම්", "meaning": "කොසඹ ගස", "category": "plant" },
    { "word": "වෙම්බාවම්", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "වෙයග බඩ", "meaning": "වේවැලෙහි අග බඩය හෙවත් මොලොක් කොටස", "category": "plant" },
    { "word": "වෙයග", "meaning": "කුෂ්ට රෝගයක්", "category": "treatment" },
    { "word": "වෙයගතිලිකා", "meaning": "කුෂ්ට රෝගයක්", "category": "treatment" },
    { "word": "වෙර්කොඹු", "meaning": "සින්දුරා", "category": "plant" },
    { "word": "වෙර", "meaning": "හරිගය, බටු, කටුවැල්බටු, කොකුම්, කපුරු", "category": "plant" },
    { "word": "වෙරළු", "meaning": "වෙරළු ගස", "category": "plant" },
    { "word": "වෙරළුමිණි", "meaning": "වෛරෝඩි මැණික", "category": "mineral" },
    { "word": "වෙරා", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "වෙල්එරක්කු", "meaning": "හෙළවරා", "category": "plant" },
    { "word": "වෙල්නාවල්", "meaning": "හෙළදම්", "category": "plant" },
    { "word": "වෙල්බිජු", "meaning": "කුඹුරුඇට", "category": "plant" },
    { "word": "වෙල්මුඩ", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "වෙල්ල", "meaning": "මිරිස්, මිහිරන්, වළඟසාල්", "category": "plant" },
    { "word": "වෙල්ලකානන්‍දි", "meaning": "මුස්සාන්ද", "category": "plant" },
    { "word": "වෙල්ලකුණඩුමණි", "meaning": "හෙළ ඔලිඳ", "category": "plant" },
    { "word": "වෙල්ලජ", "meaning": "මිරිස්, වළඟසාල්", "category": "plant" },

    // --- පිටුව 449 (සහ 448 රූපය) ---
    { 
        "word": "වෙල්ලන්ගිරිය", 
        "scientific": "Paramignya Monophylla",
        "meaning": "Paramignya Monophylla- වෙල්ලන්ගිරිය මැඩිය කොළ වලට මදක් සමාන කටු සහිත පඳුරු වගියකි. මෙහි සුදු පාට කොළ ඇති වගියක් සහ තද නිල් (කළු) පාට කොළ ඇති වගියක් දැයි දෙවගියක් තිබේ. මෙයින් ඖෂධ වශයෙන් ගන්නේ මුලින් කී වගිය යි. ඒ වගිය සොයා ගන්ට බැරි වූ විට දෙවැනි ව කී කළු වෙල්ලන්ගිරිය ද ඖෂධ වශයෙන් ගණිති.\n\nවෙල්ලන්ගිරිය කොළ-පොතු හා මුල් තෙල් වගී සෑදීමට කැඩුම්-බිඳුම් වෙදකමේ බෙහෙත් වලට හා සර්ප විෂට ත්, අවශ්‍ය වේ. අල්ප මුත්‍ර වහනය සිදු වූ විට එය වැඩි කොට මුත්‍ර පිරිසිදු කිරීම සඳහා ත්, ගවයින්ගේ ලේ සහිත මුත්‍ර යාම සඳහා ත් මේ වගියේ සාරය යොදති.\n\nමේ පඳුරුවල සෑදෙන වල්දෙහි පමණ ලොකු ගෙඩි ඉදුන විට තද දුගඳක් නික්මෙයි. මේ ගෙඩි ඉදී කුණුවූ විට ඒ ගෙඩි තුළින් ඇහැ මුල්ලන් උපදින බව වෘද්ධයෝ කියති.", 
        "category": "plant",
        "image": "img_93d0c7_vellanigiriya.jpg"
    },
    { "word": "වෙල්ලනඟර", "meaning": "අන්දර", "category": "plant" },
    { "word": "වෙල්ලන", "meaning": "මල්රතණ", "category": "plant" },
    { "word": "වෙල්ලප්පරිත්ති", "meaning": "මස්බැද්ද", "category": "plant" },
    { "word": "වෙල්ලප්පාගිරි", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "වෙල්ලප්පාසානම්", "meaning": "සුදු පාසානම්", "category": "mineral" },
    { "word": "වෙල්ලප්පුවන්පල", "meaning": "කෙළිඳසාල්", "category": "plant" },
    { "word": "වෙල්ලරි", "meaning": "කැකිරි", "category": "plant" },
    { "word": "වෙල්ලරුක්කු", "meaning": "හෙළ වරා", "category": "plant" },
    { "word": "වෙල්ලාපාමාගි", "meaning": "සුදු කරල්සැබෝ", "category": "plant" },
    { "word": "වෙල්ලි", "meaning": "රිදී", "category": "mineral" },
    { "word": "වෙල්ලිකා", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වෙල්ලිප්පරිත්නි", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "වෙල්ලියම්", "meaning": "සුදු තුඹ", "category": "plant" },
    { "word": "වෙල්ලෙයිවසම්බු", "meaning": "එළ වදකසාඅල", "category": "plant" },
    { "word": "වෙල්ලොන්තිරං", "meaning": "හෙළ ලොත්, ලුණුවරණ, පළිඟු", "category": "plant" },
    { "word": "වෙල්නල්පිටි", "meaning": "වෙල්හල්සාල් පිටි", "category": "food" },
    { "word": "වෙලං", "meaning": "වෙලඟ ගස", "category": "plant" },
    { "word": "වෙල", "meaning": "ලප්නාරං", "category": "plant" },
    { 
        "word": "වෙලඟ", 
        "meaning": "වෙලඟ ගස, (ලේවැරැල්ල කොළ වැනි කොළ ඇති සෘජුව වැවෙන විශාල ගසකි. මේ කොළවල යටි පැත්ත සහ ගෙඩි ත් කුඩු පාටින් (ලා රත් පාහයෙන්) යුක්ත ය. කුඩු වෙලුඟ ගැන 119 පිටේ ලියා ඇති විස්තරය බලන්න", 
        "category": "plant" 
    },
    { "word": "වෙලවාක", "meaning": "හෙළහිඹුරු", "category": "plant" },
    { "word": "වෙලුප්පු", "meaning": "සුදු ලූණු (සුවස ලුණු)", "category": "plant" },
    { "word": "වෙලුරියම්", "meaning": "වෙරළුමිණි", "category": "mineral" },
    { "word": "වෙලෙප්", "meaning": "නාමගස්", "category": "plant" },
    { "word": "වෙෂ්ටක", "meaning": "සිරිවඩු, ඉඹුල්ලාටු", "category": "plant" },
    { "word": "වෙෂ්ටසාර", "meaning": "සිරිවඩු", "category": "plant" },
    { "word": "වෙෂණ", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "වේගා", "meaning": "කූරටිය", "category": "plant" },
    { "word": "වේණු", "meaning": "උණගස", "category": "plant" },
    { "word": "වේපථු", "meaning": "තිතිග", "category": "plant" },
    { "word": "වේතුම්පේ", "meaning": "අනෝදා ගස", "category": "plant" },
    { "word": "වේද", "meaning": "රසදිය", "category": "mineral" },
    { "word": "වේදනී", "meaning": "වම් රෝගයක්", "category": "treatment" },
    { "word": "වේපටී", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වේපතු", "meaning": "වාත රෝගයක් (වෙව්ලීම)", "category": "treatment" },
    { "word": "වේබිජු", "meaning": "වේවැල් ඇටය", "category": "plant" },
    { "word": "වේර්කොඹු", "meaning": "සින්දුරා", "category": "mineral" }

];

