// data_428_438.js - පිටු 428 සිට 430 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 120
const data_extra_428_438 = [
    // --- පිටුව 428 ---
    { "word": "වල්ලිදුර්වා", "meaning": "වල්රතණ", "category": "plant" },
    { "word": "වල්ලිබදරි", "meaning": "හිඹුටුබෙර", "category": "plant" },
    { "word": "වල්ලිමධුක(ර)", "meaning": "වැල්මී", "category": "plant" },
    { "word": "වල්ලිමුද්ඝ", "meaning": "වල්මුං", "category": "plant" },
    { "word": "වල්ලි වෘක්‍ෂ", "meaning": "සල්ගස", "category": "plant" },
    { "word": "වල්ලූර", "meaning": "වියලි මස්, (වැලිලාඬු=වැලිලිරා)", "category": "food" },
    { "word": "වල්ලයා", "meaning": "නෙල්ලි ගස", "category": "plant" },
    { "word": "වල්වදුරු කොළ", "meaning": "වල්වන්රද්‍ර (වල් මන්රද්‍ර) කොළ", "category": "plant" },
    { "word": "වළකිඳු", "meaning": "පිටිකර, ගලවළුව", "category": "anatomy" },
    { "word": "වළඟ", "meaning": "මිහිරන්, වළඟසාල්, ඉඟටිය", "category": "plant" },
    { "word": "වළඟුලුවා", "meaning": "වළඟඑළුවා (වල්ලුළුවා)", "category": "plant" },
    { "word": "වළපත්‍රී", "meaning": "කොසඹ", "category": "plant" },
    { "word": "වළපුරක්", "meaning": "ලප්නාරන්", "category": "plant" },
    { "word": "වළඹ", "meaning": "වල් අඹ", "category": "plant" },
    { "word": "වළයන්කඩුප්පු", "meaning": "පුරාණ වස්තු විශේෂයක්", "category": "general" },
    { "word": "වළල්ලප්පු", "meaning": "බළල්ලුණු", "category": "mineral" },
    { "word": "වළාකා", "meaning": "නිල්ගස්", "category": "plant" },
    { "word": "වළා", "meaning": "කළු තුස්තවාලු, වම්මුතු (කලාදුරු)", "category": "plant" },
    { "word": "වළාක", "meaning": "මුං", "category": "plant" },
    { "word": "වළාන", "meaning": "ආරණ්‍යය", "category": "general" },
    { 
        "word": "වළාවැන්න", 
        "meaning": "හාසපාදි=කිතුල් පාළයේ හැඩහුරුකම ඇති මීවන වගියට අයත් පැලෑටියක්. මේ වර්ගයට අයත් පැලෑටි 100 ක් පමණ තිබේ එයින් ඖෂධ සඳහා ගන්නේ ලොකු කොළ තිබෙන වර්ගය පමණකි. හංස පාද වැනි හැඩහුරුකමින් යුත් කොළ ඇති මේ වර්ගය වෙනුවට ඇතැම් වෛද්‍ය පරම්පරා වල උඩුවියලි ද ගණිති. මුඛ රෝග මෙන් ම මෙයට දිවි මකුළු විෂට ප්‍රත්‍යක්‍ෂ ඖෂධයකි.", 
        "category": "plant" 
    },
    { "word": "වලි", "meaning": "ගෙන්දගම්, කසට ගස", "category": "plant" },
    { "word": "වලිද්ද", "meaning": "වල්සුද්ද ගස", "category": "plant" },
    { "word": "වලිදුලෙයි", "meaning": "ඇත්බටු (වම්බටු)", "category": "plant" },
    { "word": "වලිප්පාලසි", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "වලුහිතෙ", "meaning": "වම්බටු", "category": "plant" },
    { "word": "වළුපස", "meaning": "පොල්, තල්, කෙසෙල්, පුවක්, ඉඳි", "category": "plant" },
    { "word": "වවුලපියා", "meaning": "වවුලන්ගේ පියාපතු", "category": "animal" },
    { 
        "word": "වවුලැටිය", 
        "scientific": "Caesalpinia Digyna",
        "meaning": "Caesalpinia Digyna- කටු සහිත වැලක්. වවුලාවිය ද කුඹුරු පවුලට අයත් කටු සහිත වැලකි. මෙහි කොළ කුඹුරු කොළ වලට වඩා කුඩා ය. හින්තඹලකොළ මෙන් ඕවාල හැඩයෙන් යුක්ත ය. දඬුව රන් පාට ය. කුඹුරු වැලේ කටු වලට වඩා කටු තියුණු ය. ඇට ද කුඹුරු ඇට වලට වඩා කුඩා ය. කුඹුරු වැලේ කොළ මීට වඩා ලොකු ය. දික් ය. අග උල් වී ඇත. දඬුව ද රත් පාට නැත. ඇට ද ලොකු ය. කටු ද මේ පමණ ගණසාරයට නැත. මේ දෙවගිය වෙන් වශයෙන් අඳුනා ගත හැක්කේ මේ ලක්‍ෂණ අනුව ය.\n\nදේශීය වෙදකමේ වෙනසක් නැති ව මේ දෙවර්ගය ම එකම ඖෂධයක් වශයෙන් ගණිති.\n\nපියාඹා යන වවුලෝ මේ වැල් වල ගැටෙනි එයින් ඔවුන්ගේ පියා පත් (සිවි) සිදුරුවී ඉගිලී යා නොහැකි ව මේ පඳුරු වල ම රැඳෙන නිසා මෙයට වවුලාවි (වවුල්+ගැටිය) යන නම සිංහලයෙන් ව්‍යවහාර වන බව පෙනේ.\n\n\"වවුලන් එල්ලී සිටින විලාශයක් දක්වන කොළ ඇති ඔවුන් ලැටි ගැමට (උලා කෑමට) කැමති එක්තරා පඳුරු වගියකට වවුලාවි ය යි කියති\" යන අළුත් මතය පිළිගත නොහැක. වවුලාවිය කුඹුරු වර්ගයට ම අයත් වැලක් බැව් පෙර-අපර දෙදිග ම උද්භිද විද්‍යාඥයින් විසින් පිළිගෙන තිබෙන හෙයිනි.", 
        "category": "plant",
        "image": "img_428_wawulawiya.jpg"
    },

    // --- පිටුව 429 ---
    { "word": "වංශි", "meaning": "උණකපුරු", "category": "plant" },
    { "word": "වශිකා", "meaning": "කිරිඳි", "category": "plant" },
    { "word": "වශි", "meaning": "ගප්පිප්පිලි, සිවිය", "category": "plant" },
    { "word": "වශික", "meaning": "අගිල්, සඳුන්", "category": "plant" },
    { "word": "වශිර", "meaning": "මුදුලුණු, ගප්පිප්පිලි, රත් සැබෝ, සිවිය, රත්ගොකටු", "category": "plant" },
    { "word": "වශිරි", "meaning": "ගප්පිප්පිලි", "category": "plant" },
    { "word": "වස්", "meaning": "උණගස, නිල් උණ", "category": "plant" },
    { "word": "වස්කරි", "meaning": "හෙළ හිඹුරු", "category": "plant" },
    { "word": "වස්තක", "meaning": "පියඟුමුණු", "category": "plant" },
    { "word": "වස්තකණ්", "meaning": "සල් ගස", "category": "plant" },
    { "word": "වස්තගන්‍ධා", "meaning": "වේලා", "category": "plant" },
    { "word": "වස්තමොද", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "වස්තිකමංසය", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "වස්තිකා", "meaning": "වල්ලවවා", "category": "plant" },
    { "word": "වස්තී", "meaning": "මූත්‍ර තිබෙන මිත", "category": "anatomy" },
    { "word": "වස්තුක", "meaning": "සුදුවැල්පලා, නිල්තම්පලා", "category": "plant" },
    { "word": "වස්තුවීජා", "meaning": "මහමේවන්", "category": "plant" },
    { "word": "වස්තු", "meaning": "කොල්ලන් කොළ", "category": "plant" },
    { "word": "වස්තු තමාලක", "meaning": "කොල්ලන් කොළ", "category": "plant" },
    { "word": "වස්තුභූෂණ", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "වස්තුරඤ්ජන", "meaning": "වනුක්", "category": "plant" },
    { "word": "වස්තුරාගධාත්", "meaning": "මීල්කසිස්", "category": "mineral" },
    { "word": "වස්මර", "meaning": "අපස්මාරය (මිම්ස්මොර)", "category": "treatment" },
    { "word": "වස්සිකා", "meaning": "දසමන්", "category": "plant" },
    { "word": "වස්සිකි", "meaning": "දසමන්", "category": "plant" },
    { "word": "වසයා", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "වස", "meaning": "වච්චනාභි, ඊතණ", "category": "plant" },
    { "word": "වසක", "meaning": "පාංශුලුණු", "category": "mineral" },
    { "word": "වසත", "meaning": "අරළු", "category": "plant" },
    { 
        "word": "වසකැල් / වසකැල්ල", 
        "meaning": "නිතඹ කැල්, රස තැල්, වසතැල්, ලප් කැල්, ය යි තැල් වගී හතරකි. හතුලු යනු ද මෙයට ම නමකි. මෙය දියමිත්ත කොළ වලට සමාන කොළ ඇති වැල් වගියකි.", 
        "category": "plant" 
    },
    { "word": "වසන්ත", "meaning": "බුළු ගස, බක් - වෙසක් දෙමස, තොටිල", "category": "plant" },
    { "word": "වසන්තක", "meaning": "තොටිල ගස", "category": "plant" },

    // --- පිටුව 430 ---
    { "word": "වසන්තදූත", "meaning": "යොහොඹුවැල, අඹ, පලොල්, කින්හිරි", "category": "plant" },
    { "word": "වසන්තදූතී", "meaning": "පලොල්, රත්පලොල්", "category": "plant" },
    { "word": "වසන්තද්‍රැ", "meaning": "අඹ ගස, බුළු ගස", "category": "plant" },
    { "word": "වසනොද්භව", "meaning": "සින්දූරම්", "category": "mineral" },
    { "word": "වසත්දල", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "වසනා", "meaning": "වච්චනාභි", "category": "plant" },
    { "word": "වසනාමාල", "meaning": "කොල්ලම් කොළ", "category": "plant" },
    { "word": "වසමුත්‍ර", "meaning": "වදකහ", "category": "plant" },
    { "word": "වසය", "meaning": "වැල් කසඹිලියා වැල, වච්චනාභි", "category": "plant" },
    { "word": "වසලුමු", "meaning": "නයා", "category": "animal" },
    { "word": "වස වෙද", "meaning": "විෂ වෙද්‍ය වරයා", "category": "person" },
    { "word": "වසා", "meaning": "මේද තෙල, මස්වැන්න, ලුණුමිල", "category": "plant" },
    { "word": "වසාදනී", "meaning": "අටිටර", "category": "plant" },
    { "word": "වසාලි", "meaning": "හෙළ පෝටා", "category": "plant" },
    { "word": "වසිකා", "meaning": "සුළු පෝටා වැල", "category": "plant" },
    { "word": "වසිර", "meaning": "ගප් නිප්පිලි, සිවිය", "category": "plant" },
    { "word": "වසි", "meaning": "රත් ගොකටු, ඇඹුල්වේ", "category": "plant" },
    { "word": "වසු", "meaning": "බකපුෂ්ප, පාංශු ලුණු, කෝවක්කා, ගෙන්දගම්, වාඩි නම් ඖෂධය, දිඹුල්", "category": "plant" },
    { "word": "වසුක", "meaning": "වරා, මූණමල්, සාම්හාරී නම් ලුණු, වලාවැන්න, බකපුෂ්ප, සිරිල, යාපුර, නුග ගස", "category": "plant" },
    { "word": "වසුවීජා", "meaning": "මහමේවන්, උණ ගස", "category": "plant" },
    { "word": "වසුතනාම", "meaning": "රිදී", "category": "mineral" },
    { "word": "වසුහරිබ", "meaning": "කෝවක්කා, මූණමල්ගස", "category": "plant" },
    { "word": "වසුරක්", "meaning": "දිඹුල් ගස", "category": "plant" },
    { "word": "වසුස්සව", "meaning": "ඉන්සළු ගස", "category": "plant" },
    { "word": "වහ්නි", "meaning": "ගිනි, රත් නිටුල්, බදුල්ල, කොසඹ", "category": "plant" },
    { "word": "වහ්නිකාරී", "meaning": "නෙල්ලි ගස", "category": "plant" },
    { "word": "වහ්නිගර්භ", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "වහ්නිගහ්නී", "meaning": "උණ ගස, සැම ගස", "category": "plant" },
    { "word": "වහ්නිජ්වාලා", "meaning": "ලියනඟලා, මලිතගස", "category": "plant" },
    { "word": "වහ්නිදීපක", "meaning": "අසමෝදගම්, වනුක්", "category": "plant" },
    { "word": "වහ්නිමාමා", "meaning": "එළ නිටුල්", "category": "plant" },
    { "word": "වහ්නිත්‍රී", "meaning": "ජටාමාංශ", "category": "plant" },
    { "word": "වහ්නිපුෂ්ප", "meaning": "මලිත මල්, ලියනඟලා මල්", "category": "plant" },
    { "word": "වහ්නිභෝග්‍ය", "meaning": "ගිතෙල්", "category": "liquid" },
    { "word": "වහ්නිමන්ථ", "meaning": "මිදි ගස, කින්හිරි ගස", "category": "plant" },
    { "word": "වහ්නිමුඛී", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "වහ්නිමුල", "meaning": "මහ මිදි", "category": "plant" },
    { "word": "වහ්නිරුචි", "meaning": "දුදු", "category": "plant" },
    { "word": "වහ්නිලොහක", "meaning": "ලෝකඩ", "category": "mineral" },
    { "word": "වහ්නිවර්ණ", "meaning": "රත් මහනෙල්", "category": "plant" },
    { "word": "වහ්නිවල්ලභ", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "වහ්නිවිජ", "meaning": "දුරා, මලිත ගස", "category": "plant" },
    { "word": "වහ්නිශිඛ", "meaning": "වනුක්, පුවඟු, මලිත ගස", "category": "plant" },
    { "word": "වහ්නිශිඛා", "meaning": "බැබිල, ලියනඟලා", "category": "plant" },
    { "word": "වහ්නිසඛ", "meaning": "වාතය, දුරා", "category": "plant" },
    { "word": "වහ්නි (2)", "meaning": "පැපිලිය, ගිනි, කෝශර බැබිල", "category": "plant" },
    { "word": "වහලගර්භ", "meaning": "සමර සඳුන්", "category": "plant" },
    { "word": "වහල වක්‍ෂුස්", "meaning": "මැඩහඟු", "category": "anatomy" },
    { "word": "වහලක්‍ෂම", "meaning": "හෙළ ලොත්", "category": "plant" },
    { "word": "වහලා", "meaning": "මහ එන්සාල්, ගතපුෂ්ප", "category": "plant" },
    { "word": "වහිශ්චුඩා", "meaning": "හරංකසා", "category": "plant" },
    { "word": "වහෛධුක", "meaning": "බුළු ගස", "category": "plant" },
    { "word": "වාක", "meaning": "සුඹුළු, (පට්ටා)", "category": "plant" },
    { "word": "වාකපුෂ්ප", "meaning": "කරාබුනැටි, කුරුඳු", "category": "plant" },
    { "word": "වාකු", "meaning": "අමුනාල", "category": "plant" },
    { "word": "වාකුවිකා", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "වාකුවී", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "වාකොළ", "meaning": "වා ගසේ කොළ", "category": "plant" },

// පිටු 431 සිට 436 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 226
    // --- පිටුව 431 ---
    { "word": "වාකේ", "meaning": "මහරි", "category": "plant" },
    { "word": "වාගස්", "meaning": "මාරා වගියට අයත් තද අරටුවකින් යුත් ගසක්", "category": "plant" },
    { "word": "වාගුජ", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "වාචං", "meaning": "වරකා ගෙඩිය", "category": "plant" },
    { "word": "වාචක", "meaning": "පිච්ච මල", "category": "plant" },
    { "word": "වාජා", "meaning": "අමුක්කරා අල", "category": "plant" },
    { "word": "වාජි", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වාජිකර්ණී", "meaning": "රත් මුරුංගා", "category": "plant" },
    { "word": "වාජිකරී", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වාජිගන්‍ධා", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වාජිදන්ත", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වාජිදන්තී", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වාජිපත්", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වාජිප්‍රසූ", "meaning": "උඳුපියලි", "category": "plant" },
    { "word": "වාජිහාස", "meaning": "හණ", "category": "plant" },
    { "word": "වාජිභෝජ්‍ය", "meaning": "මුං", "category": "plant" },
    { "word": "වාජීකරණ", "meaning": "ධාතු වර්ධනය කරණ බෙහෙත්", "category": "treatment" },
    { "word": "වාටිකා", "meaning": "පත්පාඬගු", "category": "plant" },
    { "word": "වාට්‍යපුෂ්පිකා", "meaning": "කොටිපහන් බැබිල", "category": "plant" },
    { "word": "වාට්‍යාටවී", "meaning": "සුළු බු බැබිල", "category": "plant" },
    { "word": "වාට්‍යා", "meaning": "සුළු බැබිල", "category": "plant" },
    { "word": "වාට්‍යාපුෂ්පී", "meaning": "අස්බැබිල, මහ බැබිල, අනෝදා", "category": "plant" },
    { "word": "වාට්‍යාල", "meaning": "මල්සුදු බැබිල, අස්බැබිල, වාට්‍යාලක සුළු බැබිල", "category": "plant" },
    { "word": "වාට්‍යාලී / වාට්‍යාලිකා", "meaning": "සුළු බු බැබිල", "category": "plant" },
    { "word": "වාණඩව", "meaning": "නිල් කටුකරඬු", "category": "plant" },
    { "word": "වාණීර", "meaning": "වේවැල්, තුන් පුලිල, ඇඹුල්වේ", "category": "plant" },
    { "word": "වාතනි", "meaning": "වේලිප්පරිත්ති, නාරං ගස", "category": "plant" },
    { "word": "වාත අතිසාර", "meaning": "වාතය කිපීමෙන් උපදනා අතීසාර රෝගය", "category": "treatment" },
    { "word": "වාත උදර", "meaning": "වාතෝදරය", "category": "treatment" },
    { "word": "වාතක", "meaning": "අසනපර්ණ", "category": "plant" },
    { "word": "වාතකි", "meaning": "හෙළබටු", "category": "plant" },
    { "word": "වාත කුණ්ඩලිකා", "meaning": "මූත්‍ර කෘච්ඡ්‍රා රෝගය", "category": "treatment" },
    { "word": "වාතකුෂ්මාණ්ඩ", "meaning": "පැපොල්", "category": "plant" },
    { "word": "වාතඝන", "meaning": "ලී මෑ, මෑ", "category": "plant" },
    { "word": "වාතඝනී", "meaning": "උඳු, වල් බැබිල, ආපසු මුදු, අරත්ත, අස්වැන්න, අමුක්කරා", "category": "plant" },
    { "word": "වාතඝාතකො", "meaning": "ඇසළ", "category": "plant" },
    { "word": "වාතඝප්", "meaning": "වම්මුතු (කලාදුරු)", "category": "plant" },
    { "word": "වාතජ්වර", "meaning": "වාතජ්වරය", "category": "treatment" },
    { "word": "වාතද්ධප්", "meaning": "කලාදුරු අල", "category": "plant" },
    { "word": "වාතපොත", "meaning": "කෑල ගස", "category": "plant" },
    { "word": "වාත මැඩක්කිය", "meaning": "වාතභංග = (වායිපායි)", "category": "plant" },
    { "word": "වාත රක්තාස්‍ර", "meaning": "පොණ්ඩරු", "category": "plant" },
    { "word": "වාතරක්තාමී", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "වාතරෝග", "meaning": "ඇසටු ගස", "category": "plant" },
    { "word": "වාතරායණ", "meaning": "හොර ගස", "category": "plant" },
    { "word": "වාතවෛරි", "meaning": "රත් එරබු", "category": "plant" },
    { "word": "වාතසඛි", "meaning": "වල් මුරුංගා", "category": "plant" },
    { "word": "වාතහර", "meaning": "තොටිල", "category": "plant" },
    { "word": "වාතහා", "meaning": "ඇත් දෙමට", "category": "plant" },
    { "word": "වාතාද", "meaning": "කොස් ගස, කොට්ටම්බා ගස", "category": "plant" },
    { "word": "වාතාමොද", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "වාතාරි", "meaning": "එරඬු, සාතාවාරිය, සේපාලිකා, අසමෝදගම්, සිරිත්කේකු, දළුක්, ආපසු මුදු, කිබාරම්, වලඟසාල්, කොටදිඹුලා, බදුල්ල", "category": "plant" },
    { "word": "වාතිකන්", "meaning": "වල් නිබ්බටු", "category": "plant" },
    { "word": "වාතිග", "meaning": "වම්බටු", "category": "plant" },
    { "word": "වාතිබඝන", "meaning": "හෙළ බටු, බටු", "category": "plant" },
    { "word": "වාතිනි", "meaning": "සූර්‍යකාන්තී", "category": "plant" },
    { "word": "වාතිය", "meaning": "කාඩි", "category": "liquid" },
    { "word": "වාතෝනා", "meaning": "ගැට නිටුල්", "category": "plant" },
    { "word": "වාදන", "meaning": "ගෙන්දගම්", "category": "mineral" },

    // --- පිටුව 432 ---
    { "word": "වාදමී", "meaning": "වාතරක්ත රෝගය", "category": "treatment" },
    { "word": "වාදරඞග", "meaning": "ඇසතු බෝ ගස", "category": "plant" },
    { "word": "වාදල", "meaning": "වැල්මී", "category": "plant" },
    { "word": "වාදළු", "meaning": "වා ගස් වල දළු", "category": "plant" },
    { "word": "වාදි", "meaning": "සුළු බැබිල", "category": "plant" },
    { "word": "වාද්‍රකී", "meaning": "කැකිරි", "category": "plant" },
    { "word": "වාන්තොක", "meaning": "කරාබු නැටි", "category": "plant" },
    { "word": "වානෙතාක", "meaning": "කරාබු නැටි", "category": "plant" },
    { "word": "වානුක", "meaning": "වල් ඉඟුරු, පිප්පිලි", "category": "plant" },
    { "word": "වාන", "meaning": "වියලි ගෙඩි", "category": "plant" },
    { "word": "වාත ප්‍රසප්", "meaning": "මීගස, කෑල ගස", "category": "plant" },
    { "word": "වානමෙපිකා", "meaning": "වල් උළුහාල්", "category": "plant" },
    { "word": "වානර ප්‍රසප්", "meaning": "මීගස", "category": "plant" },
    { "word": "වානරප්‍රියා", "meaning": "කිරිපළු ගස", "category": "plant" },
    { "word": "වානරාසාක", "meaning": "ලොත් ගස", "category": "plant" },
    { "word": "වානරී", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "වානීර", "meaning": "වේවැල්", "category": "plant" },
    { "word": "වානෙය", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වානෙයං", "meaning": "දසපුර", "category": "plant" },
    { "word": "වාප්‍ය", "meaning": "කොට්ටම්", "category": "plant" },
    { "word": "වාමක", "meaning": "රිදී තුත්තම්", "category": "mineral" },
    { "word": "වාමඝනී", "meaning": "කටුකරෝහණි", "category": "plant" },
    { "word": "වාමනී", "meaning": "අගුන, කොට්ටම්, සුදුහඳුන්", "category": "plant" },
    { "word": "වාමලෝච", "meaning": "කසිල වැල", "category": "plant" },
    { "word": "වාමලෝචා", "meaning": "කසිල වැල", "category": "plant" },
    { "word": "වාමහාරී", "meaning": "කටුකරෝහණි", "category": "plant" },
    { "word": "වාමාකා", "meaning": "රිදී තුත්තම්", "category": "mineral" },
    { "word": "වාමාඞ්ගනා", "meaning": "අසෝකා", "category": "plant" },
    { "word": "වාමාඞ්ගිඝාත", "meaning": "අසෝකා", "category": "plant" },
    { "word": "වායස", "meaning": "අගිල්, හොර අරටු, කළු කාම්මේරිය", "category": "plant" },
    { "word": "වායසක", "meaning": "හඟුළු", "category": "plant" },
    { "word": "වායස ජඞ්ගා", "meaning": "ගුරැල්ල", "category": "plant" },
    { "word": "වායසා", "meaning": "හඟුළු", "category": "plant" },
    { "word": "වායසාදනී", "meaning": "අගිල්", "category": "plant" },
    { "word": "වායසාරාතී", "meaning": "මහ දුදු", "category": "plant" },
    { "word": "වායසී", "meaning": "කොටදිඹුලා, කිරිකවෙල්ල, කළුකාම්මේරිය, තල් වැල්", "category": "plant" },
    { "word": "වායසේක්‍ෂු", "meaning": "කුසතණ", "category": "plant" },
    { "word": "වායසෝලී", "meaning": "කවෙල්ල, කළු කාම්මේරිය", "category": "plant" },
    { "word": "වායීන", "meaning": "මිරිස්", "category": "plant" },
    { "word": "වාසි විලඞගන්", "meaning": "වලඟසාල්", "category": "plant" },
    { "word": "වාසුදේව ප්‍රියඞ්කරී", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "වායු මුලන්ගු", "meaning": "වල්මුකූ (වල් මොලඟු)", "category": "plant" },
    { "word": "වායුවාහිනී", "meaning": "ශරීරයේ නහර", "category": "anatomy" },
    { "word": "වාර්", "meaning": "වතුර", "category": "liquid" },
    { "word": "වාර්‍තාකූ", "meaning": "ඇත්බටු (වම්බටු)", "category": "plant" },
    { "word": "වාර්‍තාකන්", "meaning": "වල් නිබ්බටු ගෙඩි", "category": "plant" },
    { "word": "වාර්‍තාකී / වාර්‍තාකූ", "meaning": "එළබටු", "category": "plant" },
    { "word": "වාර්‍තාකී එළ", "meaning": "කටුවැල්බටු, වම්බටු, කෝවක්කා", "category": "plant" },
    { "word": "වාර්‍ද්‍රද", "meaning": "ඔකිද (ඔකිද ඇට), අඹ", "category": "plant" },
    { "word": "වාර්‍දර", "meaning": "ඔලිඳ, ලාකඩ, අඹ", "category": "plant" },
    { "word": "වාර්‍ද්ධිනව", "meaning": "මුදු ලුණු", "category": "mineral" },
    { "word": "වාර්‍ෂිකා", "meaning": "යොන්තුඹ, බැමිතිරිය, (මුණුවිල) ගැටපිච්ච", "category": "plant" },
    { "word": "වාර්‍හත", "meaning": "බටු ගෙඩිය", "category": "plant" },
    { "word": "වාර", "meaning": "සුවඳ හොට", "category": "plant" },
    { "word": "වාරගා", "meaning": "සුළු බු බැබිල", "category": "plant" },
    { "word": "වාරණකර්ණිකා", "meaning": "සබරල", "category": "plant" },
    { "word": "වාරණබුසා", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "වාරණ වල්ලභා", "meaning": "කෙසෙල්", "category": "plant" },
    { "word": "වාරණා", "meaning": "කෙහෙල්", "category": "plant" },
    { "word": "වාරාහ", "meaning": "මහ කුකුරුමාන්", "category": "plant" },
    { "word": "වාරාහකර්ණී", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වාරාහ පත්‍රී", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "වාරාහාඞ්ගී", "meaning": "දත්ත", "category": "plant" },
    { "word": "වාරාහි", "meaning": "යොන්තුඹ, බින් තල්, ඌරල", "category": "plant" },
    { "word": "වාරි", "meaning": "වතුර, ඉරිවේරිය, තකුල්, සාතාවාරිය, සන්නාඹ", "category": "plant" },
    { "word": "වාරිකණ්ටකා", "meaning": "දිය ඉකිරි", "category": "plant" },
    { "word": "වාරිකර්ණී", "meaning": "පලොල්", "category": "plant" },

    // --- පිටුව 433 ---
    { "word": "වාරිකාකී", "meaning": "ඇත්බටු, වම්බටු, බටු", "category": "plant" },
    { "word": "වාරිකුඹ", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "වාරිචඞ්ගර", "meaning": "රත් පලොල්", "category": "plant" },
    { "word": "වාරිචාමර", "meaning": "පෙද", "category": "plant" },
    { "word": "වාරිජ", "meaning": "සක් බෙල්ලා, නෙළුම් මල, කුරුදු, ලුණු ප්‍රභේද, කරාබු, දිය රත්රන්", "category": "plant" },
    { "word": "වාරිජලද", "meaning": "සන්නාඹ", "category": "plant" },
    { "word": "වාරිතස්කර", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වාරිද", "meaning": "කලාදුරු, හ්‍රීබේර", "category": "plant" },
    { "word": "වාරිධර", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වාරිනාම", "meaning": "කිරිඳි", "category": "plant" },
    { "word": "වාරිනාමිකා", "meaning": "හ්‍රීබේර", "category": "plant" },
    { "word": "වාරිපර්ණී", "meaning": "පලොල්, දිය පරඩලා", "category": "plant" },
    { "word": "වාරිප්‍රසාදන", "meaning": "ඉඟිනි ඇට", "category": "plant" },
    { "word": "වාරිපාලිකා", "meaning": "පලොල්", "category": "plant" },
    { "word": "වාරිපාෂාණ", "meaning": "පොල්පලා", "category": "plant" },
    { "word": "වාරිපුෂ්ප", "meaning": "කරාබු නැටි", "category": "plant" },
    { "word": "වාරිප්‍රසාදන", "meaning": "පලොල්", "category": "plant" },
    { "word": "වාරිප්‍රසාදන ඵල", "meaning": "ඉඟිනි ඇට", "category": "plant" },
    { "word": "වාරිපාර්ණී", "meaning": "පලොල්, කුම්භිකා", "category": "plant" },
    { "word": "වාරිඵල", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වාරිබදර", "meaning": "ප්‍රාවීනාමලක (උගුරුස්ස)", "category": "plant" },
    { "word": "වාරිබාලකා", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වාරිභව", "meaning": "හොයදුන්, සක්", "category": "plant" },
    { "word": "වාරිමසි", "meaning": "කලාදුරු අල", "category": "plant" },
    { "word": "වාරිමුල්", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "වාරිමුලී", "meaning": "පලොල්", "category": "plant" },
    { "word": "වාරිරුහ", "meaning": "නෙළුම්", "category": "plant" },
    { "word": "වාරිවදන", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "වාරිවර", "meaning": "මහ කරඹ", "category": "plant" },
    { "word": "වාරිවල්ලභා", "meaning": "බෙබර (මසන්)", "category": "plant" },
    { "word": "වාරිවාහ", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "වාරිසම්භව", "meaning": "ලුණෝකාපන = (හොයදුන්)", "category": "plant" },
    { "word": "වාරිසම්භූත", "meaning": "මුහුදු ලුණු", "category": "mineral" },
    { "word": "වාරිසාලිකා", "meaning": "දිය පරඩලා හෝ පාසි", "category": "plant" },
    { "word": "වාරුණ", "meaning": "වතුර", "category": "liquid" },
    { "word": "වාරුණා", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "වාරුණී", "meaning": "මහ ගොන්සුදුකැකිරි, සුරා, රතණ", "category": "plant" },
    { "word": "වාරුණීග්‍රහ", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "වාරුණී", "meaning": "පුෂාදියෙන් කළ සුරා", "category": "liquid" },
    { "word": "වාල්මොලඟු", "meaning": "වල්ගාමිරිස්", "category": "plant" },
    { "word": "වාල", "meaning": "ඉරිවේරිය, වතුර, මීනුග, ඒලවාලුක (අළු ඇට)", "category": "plant" },
    { "word": "වාලක", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "වාලභෛෂජ්‍ය", "meaning": "බාන්වැල්, (වෙනිවැල්) කෂායෙහි ලූ තුටු (දුටු)", "category": "plant" },
    { "word": "වාලයප්", "meaning": "වෛරෝඩි මැණික්", "category": "mineral" },
    { "word": "වාලවායප්", "meaning": "වෛරෝඩි", "category": "mineral" },
    { "word": "වාලිකා", "meaning": "ඇඹුලැඹිලිය", "category": "plant" },
    { "word": "වාලූකා", "meaning": "මුගුණුවැන්න, වැලි", "category": "plant" },
    { "word": "වාලෙසිමරමි", "meaning": "කෙසෙල් ගස", "category": "plant" },
    { "word": "වාලුකා", "meaning": "කපුරු, වැලි, සාතාවාරිය, ඒලවාලුක", "category": "plant" },
    { "word": "වාලුකා යන්ත්‍රය", "meaning": "භාජනයක වැලි පුරවා මැද ඖෂධ දැමූ වෙනත් භාජනයක් තබා පුටදීමට සාදාගන්නා උපකරණය", "category": "treatment" },
    { "word": "වාලු(බ)කී", "meaning": "කැකිරි", "category": "plant" },
    { "word": "වාලුලවාසි", "meaning": "දුදු", "category": "plant" },
    { "word": "වාශ", "meaning": "රෙදි", "category": "general" },
    { "word": "වාශක", "meaning": "කළුතලා, වංඇපල", "category": "plant" },
    { "word": "වාශා", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වාෂ්ප", "meaning": "කුරතම්පලා, පත්පාඬගු, කඳුළු", "category": "plant" },
    { "word": "වාස්තුක", "meaning": "විල්පලා, නිල් තම්පලා", "category": "plant" },
    { "word": "වාස්පිකා", "meaning": "කළුදුරු, පත්පාඬගු", "category": "plant" },
    { "word": "වාස්පෙය", "meaning": "නාමල්රේණු", "category": "plant" },
    { "word": "වාසක", "meaning": "වංඇපල", "category": "plant" },

    // --- පිටුව 434 ---
    { "word": "වාසුදේව ප්‍රියංකරී", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "වාසන්තා", "meaning": "මුං, කළුමුං, කුකුරුමාන්", "category": "plant" },
    { "word": "වාසන්ති", "meaning": "යොහොඹු", "category": "plant" },
    { "word": "වාසන්තිද", "meaning": "බුළුගස", "category": "plant" },
    { "word": "වාසමිලකා", "meaning": "පිච්ච", "category": "plant" },
    { "word": "වාසා", "meaning": "වංඇපල, ගල්කසඹිලියා", "category": "plant" },
    { "word": "වාසි", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වාසිතා", "meaning": "වංඇපල", "category": "plant" },
    { "word": "වාසිනී", "meaning": "වියලි කටුකරඬු", "category": "plant" },
    { "word": "වාසිමිරිස්", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "වාසුක", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "වාසුදේවප්‍රියඞ්කර", "meaning": "සාතාවාරිය වැල", "category": "plant" },
    { "word": "වාසොව", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "වාසොවා", "meaning": "වසාවාසි", "category": "plant" },
    { "word": "වාහ්ලි", "meaning": "වහල දේශයෙහි කොකුම්, පෙරුම්කායම්", "category": "plant" },
    { "word": "වාහ්ලීකා", "meaning": "පිණ්ඩාහිංගු, කොකුම්මල්, තුරුක්තෙල්", "category": "plant" },
    { "word": "වාහ්ලීක", "meaning": "පිණ්ඩාහිංගු", "category": "plant" },
    { "word": "වාහන", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "වාහස(ලාස්)", "meaning": "ලාස් දහස (16) ය", "category": "measurement" },
    { "word": "වාහස(කිබුල්)", "meaning": "කිබුල්වැන්න, මල්තුඹ", "category": "plant" },
    { "word": "වාහිරත", "meaning": "ඉඟුරු, ගම්මිරිස්, නිප්පිලි, (තිකටු)", "category": "plant" },
    { "word": "වාහුවාර", "meaning": "ලෝළුගස", "category": "plant" },
    { "word": "වැක්කී", "meaning": "කාරං", "category": "mineral" },
    { "word": "වැග්ගී", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "වැග්‍ර", "meaning": "අරක්කු", "category": "liquid" },
    { "word": "වැටකේරළු", "meaning": "වැටකේ අරළු(වැටකේ ගස්වල පාතට ඇදෙන අරටුවන් මුල්)", "category": "plant" },
    { "word": "වැටතිර්", "meaning": "ආඬකෝබා", "category": "plant" },
    { "word": "වැටතිරියා", "meaning": "වංඇපල (ආඩතෝඩා)", "category": "plant" },
    { "word": "වැටෙන", "meaning": "තණරද", "category": "plant" },
    { 
        "word": "වාත්ත-", 
        "meaning": "අස්වැන්න = සල්වැන්න (ශාලපර්ණී), මස්වැන්න (මාෂපර්ණී), මුංවැන්න (මුද්ගපර්ණී), පුස්වැන්න (පෘෂ්ණිපර්ණී), වළාවැන්න = වැලිවැන්න (හංසපාදී), මකුවැන්න (මණ්ඩුකපර්ණී), කිබුල්වැන්න (සමසතිකා, විලඳ), වැන්න (ශබිබ පුෂ්පි), සක්වැන්න (චක්‍රපර්ණී)", 
        "category": "plant" 
    },
    { 
        "word": "වැරනියා", 
        "meaning": "නික කොළ වලට මදක් සමාන තික්ත රසයෙන් යුත් කොළ ඇති පඳුරු වගියකි. මී වස්සන්ගේ පණු ගාය මේ කොළ වලට ලුණු වතුර ඉස දීමෙන් සුව වේ.", 
        "category": "plant" 
    },
    { "word": "වැරල්", "meaning": "කරාබු", "category": "plant" },
    { "word": "වැරල්ල", "meaning": "වැරැල්ලගස (කුෂ්ටරෝගයට ගන්නා බෙහෙතක්)", "category": "plant" },
    { 
        "word": "වැල්අඟුන", 
        "meaning": "අඟුණ වැල් (කිරිඅඟුණ=තික්ත අඟුණ යයි අඟුණ වැල් දෙවගියකි. මෙයින් කිරි අඟුණ කිරි පණු ගායට ත්, තික්ත අඟුණ ශ්ලීපද=(බරවා=බරවා) රෝගයට ත් ප්‍රත්‍යක්‍ෂ යි.)", 
        "category": "plant" 
    },
    { "word": "වැල්අල", "meaning": "අල වැල් (අල බසින වැල් වගී)", "category": "plant" },
    { "word": "වැල් ඇගිනිය", "meaning": "වැල් අඟුණ, මුලි", "category": "plant" },
    { "word": "වැල්ගුරිල", "meaning": "ගුරැල්වැල (ගෝසාල වැල්=ගෝයාලියා ලතා=ගොඩා පලි=වල් බූරැල්ල)", "category": "plant" },
    { "word": "වැල්නික", "meaning": "නිකවැල්", "category": "plant" },
    { "word": "වැල්නීති", "meaning": "නිවිතිවැල්", "category": "plant" },
    { 
        "word": "වැල්පස් මුල් ගණය", 
        "meaning": "කිරිබදු, හීරස්සු, මැඩහඟු, රසකිඳ, වැල්කසඹිලියා හෝ පුවටා යන මේ වැල් පස් මුල මුත්‍රකෘච්ඡ්‍රා හා වාත රෝග කසන්කේ ය.", 
        "category": "compound" 
    },


//පිටු 435 සිට 438 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 144
// --- පිටුව 435 සහ 436 හි දිගු විස්තර ---
    { 
        "word": "වල්කැප්පෙටියා", 
        "scientific": "Croton Officinalis",
        "meaning": "Croton Officinalis-ගස් කැප්පෙටියා, වැල් කැප්පෙටියා යයි වගී දෙකකි. මෙයින් ගස් කැප්පෙටියා මුල් සහ පොතු තුවාල තෙල් සහ ගව බෙහෙත් සෑදීමට ත්, කොළ වම්බටු, අමුමිරිස් සහ බුලත් පාත්ති පොහොර කිරීමට ත්, ගණිති. මේ ගසේ කිරි කැපුන් තුවාල වලට ලේ පිට ම දැමීමෙන් ඒවා නොපැසවා සම්පූර්ණයෙන් ම වියලී යයි. (සුව වෙයි)\n\nවැල් කැප්පෙටියා, ගස් කැප්පෙටියා කොළ වලට වඩා මඳක් දිගටි හැඩයෙන් යුත් රුළු (රළු) මැඩියා කොළ වැනි, ඒ පමණ ලොකු නො වූ කොළ ඇති වැල් මෙන් දිගට යන පඳුරු වගියකි. මේ ගසේ පංචාංගය ම සර්ප විෂට හා කැපුන් තුවාල වලට ත් ප්‍රත්‍යක්‍ෂ යි.\n\nඇතැම් අය මේ පැලෑටිය Croton Officinalis (පොඩි අරිසි) නමින් හඳුන්වති. (320 පිට බලන්න.)", 
        "category": "plant",
        "image": "img_435_wal_kappetiya.jpg"
    },
    { 
        "word": "වැල්පෙනෙල", 
        "scientific": "Cardiospermum Halicacabum",
        "meaning": "Cardiospermum Halicacabum- කාලමේෂිකා. අයි වඤ්ජා යන අපර නාමය කින් ද හැඳින්වෙන පෙනෙල වැලේ කොළ-රන් සහ ඇට කොපු ත් ඉතා ගොහාමත් ය තුඹ කරවිල වැලකට මඳක් සමාන වූ මේ වැලේ කොප තුළ ගෝන මුනිස්සන් හෝ බුත්සරණ ඇට පමණ විශාල කාල වර්ණයෙන් යුත් ඇට තුන බැගින් ඇත.\n\nමේ වගිය දේශීය වෙදකමේ ඉතා උසස් ඖෂධයකි. අණ්ඩ වාත-අන්ත්‍රවෘද්ධි ඇතුළු වාතා බාධ සඳහා මේ වගියේ පංචාංග ය ම අරිෂ්ට-කෂාය-මල්ලිම-සහ කැඳ පිණිස ත් අවශ්‍ය වේ. පෙනෙල දළු රතු ලූනු-උම්බලකඩ සමග එක පමණට ගෙණ එළගි තෙලින් මලවා කෑමෙන් සෞම්‍ය ධාතු වර්ධනය වෙයි.\n\nපෙනෙල වැල් සර්ප විෂට හා ආමශූල-උදරශූල ආදී වෙනත් ආබාධ සඳහා ද ගණිති.\n\nහින්දු ජාතිකයෝ මේ වගිය මල පහත කරණ ද්‍රව්‍යක් වශයෙන් පාවිච්චි කරති. කහ-සුදු දෙ පාටින් යුත් පෙනෙල වැල් වගී දෙකක් තිබේ. මේ දෙවර්ගය ම වෙනසක් නැතිව ඖෂධ සඳහා යොදති. ගස් පෙනෙල වෙන වගියකි. ඒ ගැන මේ පොතේ 163 පිටේ ඡායාරූප සහිත විස්තරයක් ඇත.", 
        "category": "plant",
        "image": "img_435_wal_penela.jpg"
    },

    // --- පිටුව 436 (ඉතිරි වචන) ---
    { "word": "වල්මදට", "meaning": "සෙව්කන්, දඬුදුන්තරා, සෙව්වේල්ලී", "category": "plant" },
    { "word": "වැල්මල්", "meaning": "බුලන් වැල්වල තෝ රට වැල්වල කරල්", "category": "plant" },
    { "word": "වැල්මී", "meaning": "පැණිවැල (මධුයෂ්ටිකා)", "category": "plant" },
    { "word": "වැල්රිමාන්", "meaning": "වැලිරාඬු, (වේලුන දඩමස්)", "category": "food" },
    { "word": "වල්වරකා", "meaning": "වියලි කලාපයේ වැවෙන මදනකාමපු වලට සමාන කුඩා ඇඹුල් කෙසෙල් ගෙඩි පමණ ගෙඩි පොකුරු සෑදෙන අජීර්ණරෝගනාශක වැල්වගියක්", "category": "plant" },
    { "word": "වැල්සමන්", "meaning": "පිච්ච වැල", "category": "plant" },
    { "word": "වැල්", "meaning": "විලිකුම් ඵල, ඉදුනමට බෙරි වන ගෙඩි සෑදෙන කොස් ගස් වගිය. (වැලගස්)", "category": "plant" },
    { "word": "වැලගෙඩිය", "meaning": "ඉදුන විට මුදු තද නැති කොස් ගෙඩිය.", "category": "plant" },
    { "word": "වෑලිකසා", "meaning": "වැලිකහ", "category": "plant" },
    { "word": "වෑලිගර ලුණු", "meaning": "වැලිකාර ලුණු", "category": "mineral" },
    { "word": "වෑලිවැන්න", "meaning": "වළාවැන්න, (හංසපාදි) (පිලා, බරවා රෝග වලට ගන්නා බෙහෙතක්)", "category": "plant" },
    { "word": "වෑලිනකුරු", "meaning": "උකුකළ පැණි කොළ පත (පුවක් කොළය) කට වන් කර සාදා ගන්නා පැණි පට්ටය මාස කීපයක් දුම් යට එල්ලා තැබීමෙන් පසු සුකිරි (ගල් කණ්ඩු) මෙන් මිදෙන වැලි හකුරු සෑදෙයි.", "category": "food" },
    { "word": "වෑලුක්", "meaning": "උක් (ඉක්‍ෂු) විශේෂයක්", "category": "plant" },
    { "word": "වෑලුක්මල්", "meaning": "වෑලුක් ගසෙහි මල්", "category": "plant" },
    { "word": "වෑලුගු", "meaning": "වෑලුක්", "category": "plant" },
    { "word": "වෑකොට", "meaning": "වල්පිච්ච (පිච්ච මල් වලට සමාන සුදු පාහයෙන් යුක්ත සවසට පිපෙන සුගන්ධවත් මල් ඇති ගැටපිච්ච වලට සමාන වැල් වගියකි. මේ වැල් ලපල්ලව හා දිරා කල්, කොස් ආදි ගස්වල ද පෑලී වැවෙයි.)", "category": "plant" },
    { "word": "වෑග්‍ර", "meaning": "අරක්කු", "category": "liquid" },

    // --- පිටුව 437 ---
    { "word": "විංගම්", "meaning": "නිප්පිලි", "category": "plant" },
    { "word": "වික්‍රාන්තා", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "වික්නිත", "meaning": "වරා", "category": "plant" },
    { "word": "වික්‍ෂිර", "meaning": "වරා ගස", "category": "plant" },
    { "word": "විකංකට", "meaning": "ගොකටු", "category": "plant" },
    { "word": "විකංකත", "meaning": "උගුරුස්ස, මහබැබිල", "category": "plant" },
    { "word": "විකංකතා", "meaning": "ඇස් බැබිල, මහබැබිල, කටුකිරිය", "category": "plant" },
    { "word": "විකට", "meaning": "සුදු හඳුන්, කටුකරඬු වෙසෙසක්", "category": "plant" },
    { "word": "විකණටක", "meaning": "හින්බෙබර, යවාස", "category": "plant" },
    { "word": "විකන්", "meaning": "කිහිරි", "category": "plant" },
    { "word": "විකන්ත", "meaning": "වරා ගස", "category": "plant" },
    { "word": "විකරණ", "meaning": "වරා", "category": "plant" },
    { "word": "විකලම්බක", "meaning": "ගොකටු", "category": "plant" },
    { "word": "විකශවර", "meaning": "රතු සාරණ", "category": "plant" },
    { "word": "විකෂා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "විකසිත", "meaning": "පුබුදුවීම", "category": "general" },
    { "word": "විකා", "meaning": "ගප්නිප්පිලි, සිවිය", "category": "plant" },
    { "word": "විකාර", "meaning": "ලෙඩ", "category": "treatment" },
    { "word": "විකාගි", "meaning": "දෙපයත් වියලා ශරීර බල බිඳ සන්ධිපත් අප්‍රාණික කරණ පුවක් වැනි විෂ ඵල වගියක්", "category": "plant" },
    { "word": "විකිරණ", "meaning": "වරාගස", "category": "plant" },
    { "word": "විකිරණඵලා", "meaning": "වල්නිබ්බටු, එළවරා", "category": "plant" },
    { "word": "විකෘන්තක", "meaning": "මුසුරතුතු, (පල්මාණික්කම්) කොත්තමල්ලි", "category": "plant" },
    { "word": "විඥෙය", "meaning": "අමු ඉඟුරු", "category": "plant" },
    { "word": "විඥෙයා", "meaning": "සේරු", "category": "plant" },
    { "word": "විගන්ධක", "meaning": "නියඹරා", "category": "plant" },
    { "word": "විගන්ධිකා", "meaning": "අතිවුඩයන්, මුඩමහණ", "category": "plant" },
    { "word": "විගන්ධිනී", "meaning": "අතිවුඩයන්", "category": "plant" },
    { "word": "විඝන", "meaning": "කරඹ", "category": "plant" },
    { "word": "විඝනෙශානකාන්තා", "meaning": "සුදු රතණ", "category": "plant" },
    { "word": "විචගම්", "meaning": "නිප්පිලි, (වගපුල්)", "category": "plant" },
    { "word": "විචචව", "meaning": "සුළුසාරණ", "category": "plant" },
    { "word": "විචක්‍ෂණ", "meaning": "දත්ත, කවෙළු", "category": "plant" },
    { "word": "විචකිල", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "විචච්චන", "meaning": "උණගස", "category": "plant" },
    { "word": "විචර්චිකා", "meaning": "කුෂ්ට රෝගය", "category": "treatment" },
    { "word": "විචිත්‍රා", "meaning": "අසෝකා", "category": "plant" },
    { "word": "විචිත්‍රා (2)", "meaning": "මදට ගස", "category": "plant" },
    { "word": "විචිත්‍රාබිණි", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "විජ්ජුල", "meaning": "පොත්ත, කුරුඳුපොතු", "category": "plant" },
    { "word": "විජුනි", "meaning": "මාරාගස", "category": "plant" },
    { "word": "විජා", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "විජාමහනී", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "විජය", "meaning": "ඉද්දගස, මදට ගස, කඹුක්, අරළු", "category": "plant" },
    { "word": "විජයා", "meaning": "ඉද්ද, සිනිද්ද, අරළු, රතණ, කන්සා, සේපාලිකා, වැල්මදට, හිඟුරුපියලි, මහමිදි, වදකහ තලා", "category": "plant" },
    { "word": "විජයාර්ධා", "meaning": "මහ එන්සාල්, වඳුරුමෑ", "category": "plant" },
    { "word": "විජුල", "meaning": "ඉඹුල් කඳ", "category": "plant" },
    { "word": "විට්", "meaning": "මල (අසූවි)", "category": "anatomy" },
    { "word": "විටිබදිර", "meaning": "ඇපල, හිඹුරු", "category": "plant" },
    { "word": "විටිනිද", "meaning": "කැකිරි", "category": "plant" },
    { "word": "විටිලවණ / විඩ", "meaning": "බලල් ලුණු", "category": "mineral" },
    { "word": "විට", "meaning": "නාරම්ගස, කිහිරි ප්‍රභේදයක් - ලවණ", "category": "plant" },
    { "word": "විටප", "meaning": "අත්ත, කොළ, ගස", "category": "plant" },
    { "word": "විටපත්‍රී", "meaning": "හින් බෙබර", "category": "plant" },
    { "word": "විටපින්", "meaning": "නුග ගස", "category": "plant" },
    { "word": "විටපි", "meaning": "ගස", "category": "plant" },
    { "word": "විටපො / විටහි", "meaning": "වෙලෙප්", "category": "plant" },
    { "word": "විටි", "meaning": "රන්වන් සඳුන්", "category": "plant" },
    { "word": "විඩිගක", "meaning": "බලල් ලුණු", "category": "mineral" },
    { "word": "විඩහිද", "meaning": "කැකිරි", "category": "plant" },

    // --- පිටුව 438 ---
    { "word": "විඩලවණ", "meaning": "බලල් ලුණු", "category": "mineral" },
    { "word": "විඩංග", "meaning": "වළඟසාල්", "category": "plant" },
    { "word": "විඩන්ගල්", "meaning": "අන්දර", "category": "plant" },
    { "word": "විඩාල", "meaning": "ඇස්පිඩ, හිරියල්, කිරිබදු", "category": "mineral" },
    { "word": "විඩාල ලවණ", "meaning": "බලල් ලුණු", "category": "mineral" },
    { "word": "විඩාලා", "meaning": "තුන්පත් කුරුඳු", "category": "plant" },
    { "word": "විඩුල", "meaning": "වේවැල්", "category": "plant" },
    { "word": "විතණ්ඩා", "meaning": "නිහිරිවැල, කොමඬු", "category": "plant" },
    { "word": "විතන්නක", "meaning": "වෑක්, සාතාවාරිය", "category": "plant" },
    { "word": "විතශොක", "meaning": "අසෝකා", "category": "plant" },
    { "word": "විතාන මූලක", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "විතාන", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "විතුන්නක", "meaning": "නවහැකිලිය", "category": "plant" },
    { "word": "විතුන්නා", "meaning": "කොත්තමල්ලි, කිබුල්වැන්න", "category": "plant" },
    { "word": "විතුන්නාක", "meaning": "පල් මාණික්කම්, නවහැකිලිය, කොත්තමල්ලි", "category": "plant" },
    { "word": "විතුන්නය", "meaning": "කිබුල්වැන්න (පනමපෙති)", "category": "plant" },
    { "word": "විතුන්න්‍ය", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "විතුන", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "විතෛ", "meaning": "ඇට", "category": "plant" },
    { "word": "විද්‍රැමො", "meaning": "පබළු", "category": "mineral" },
    { "word": "විද්දෝදර", "meaning": "උදර රෝග විශේෂයක්", "category": "treatment" },
    { "word": "විධකණී", "meaning": "දියමිත්ත", "category": "plant" },
    { "word": "විධුද්‍රො", "meaning": "වී", "category": "plant" },
    { "word": "විද්‍යාමාතෘකා", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "විද්‍යා", "meaning": "ගුගුල්, හින් මිදි", "category": "plant" },
    { "word": "විද්‍රදල", "meaning": "කරගස", "category": "plant" },
    { "word": "විද්‍රැල්ලතා", "meaning": "නියඟලා", "category": "plant" },
    { "word": "විද්‍රක", "meaning": "ගුරැකැට", "category": "mineral" },
    { "word": "විද්‍රධී", "meaning": "එනම් රෝගය", "category": "treatment" },
    { "word": "විද්‍රධිතාගක", "meaning": "ඇසළ", "category": "plant" },
    { "word": "විද්‍රධිනාසන", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "විද්‍රාවන", "meaning": "රිදී තුත්තන්", "category": "mineral" },
    { "word": "විද්‍රැම", "meaning": "පබළු", "category": "mineral" },
    { "word": "විද්‍රැම ලතා", "meaning": "පබළු වැල, ලියනඟලා වැල", "category": "plant" },
    { "word": "විදග්ධ", "meaning": "විශේෂයෙන් දහිය", "category": "treatment" },
    { "word": "විදපා", "meaning": "ගුගුල්, සින් මිදි", "category": "plant" },
    { "word": "විදල", "meaning": "රත්රන්, ත්‍රස්තාවළු, කළු ත්‍රස්තාවළු", "category": "mineral" },
    { "word": "විදක", "meaning": "ගුරුකැට", "category": "mineral" },
    { "word": "විදාරණ", "meaning": "කින්හිරි ගස", "category": "plant" },
    { "word": "විදාරි", "meaning": "බිම් පුහුල්, අස්වැන්න", "category": "plant" },
    { "word": "විදාරිගන්ධා", "meaning": "අස්වැන්න", "category": "plant" },
    { "word": "විදාරිණී", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "විදාලිකා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "විදු", "meaning": "බුලත්", "category": "plant" },
    { "word": "විදිලක්තුව", "meaning": "බුලත් වැල", "category": "plant" },
    { "word": "විදුම / විදුමල", "meaning": "පබළු", "category": "mineral" },
    { "word": "විදුර", "meaning": "වපු = (දියමන්ති), විදුරු", "category": "mineral" },
    { "word": "විදුරඹ", "meaning": "නරමුතු", "category": "mineral" },
    { "word": "විදුරා", "meaning": "දෙව්මී, කිබාරම්, දියමන්ති,", "category": "mineral" },
    { "word": "විදුරාතෙල වැල", "meaning": "සිරස්ස වැල", "category": "plant" },
    { "word": "විදුරු මුව", "meaning": "ප්‍රවාල්ලා", "category": "mineral" },
    { "word": "විදුල", "meaning": "ඇඹුල්වේ, සුවඳ තණ", "category": "plant" },
    { "word": "විදුලා", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "විධාතා", "meaning": "සුරා, නිප්පිලි", "category": "plant" },
    { "word": "විධු", "meaning": "කපුරු", "category": "mineral" },
    { "word": "විනෘපත්‍ර", "meaning": "කරගස", "category": "plant" },
    { "word": "විනධ්‍ය", "meaning": "එන්සාල්, ලාවලු, (ලාහලු) ගස", "category": "plant" },
    { "word": "විනධ්‍යාහ්ව", "meaning": "අමුක්කරා", "category": "plant" },
    { "word": "විනමුක", "meaning": "තුවරලා මල", "category": "plant" },
    { "word": "විනිතාකුල ප්‍රත්‍රක", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "විපක්‍ෂිකා", "meaning": "කාල ගස", "category": "plant" },
    { "word": "විපාතිකා", "meaning": "පතුල් පැලියාව, (පතුල් පැලෙන (පාද) රෝගය)", "category": "treatment" },
    { "word": "විපින", "meaning": "ආරණ්‍යය", "category": "general" },
    { "word": "විපුල", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "විපුලා / විපුෂා", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "විප්ල", "meaning": "වැටකේ", "category": "plant" },
    { "word": "විබන්‍ධ", "meaning": "මලබද්ධය, කොසඹ", "category": "treatment" }


];

