// data_385_394.js - පිටු 385 සිට 394 දක්වා සියලුම වචන සහ විස්තර
const data_extra_385_394 = [
    // --- පිටුව 385 ---
    { "word": "යක්‍ෂි", "meaning": "කටුපිල ගස", "category": "plant" },
    { "word": "යක්‍ෂ්මස්නි", "meaning": "මුද්දරප්පලම්", "category": "plant" },
    { "word": "යක්‍ෂ්මා", "meaning": "ක්‍ෂයරෝගය", "category": "treatment" },
    { "word": "යකා බැඳි වැල්", "meaning": "ඉසඟු හෝ වැල් දෙහි වැල්. ඉසඟු = ඉය හෝ වැල් දෙහි", "category": "plant" },
    { "word": "යකා වනසු", "meaning": "යකවනස්ස (යකු වනස්ස)", "category": "plant" },
    { "word": "යකාස්", "meaning": "කුඹුරු ඇට, කුඹුරු වැල", "category": "plant" },
    { "word": "යකිනතලා", "meaning": "තලා වර්ගයක්", "category": "plant" },
    { 
        "word": "යකිනාරන්", 
        "scientific": "Atlantia Zeylanica",
        "meaning": "Atlantia Zeylanica- තද පැඟිරි ගතියෙන් යුත් ගස් වර්ගයක්. යකිනාරන් පමණ තද පැඟිරි සුවඳින් යුත් වෙන පැඟිරි ගස් වර්ගයක් නැත. මෙහි කොළ මාසිය කොළ වලට නැතහොත් දෙඩම්පනා කොළ වලට සමාන ය. කඳෙහි සහ අතු වල ත් අඟල් එක හමාර දක්වා දික් වූ තියුණු කටු ඇත. මෙහි මල් කරඹ මල් වලට සමාන ය. නටුව ලා රත් පැහැයෙන් සහ මල් පෙති සුදු පැහැයෙන් යුක්ත ය. මේ ගසේ අතු අග ප්‍රමාණයෙන් තිබ්බටු ගෙඩි පමණ හා හැඩහුරු කමින් මදනකාමපූ ගෙඩි වැනි ගෙඩි පොකුරු සෑදෙයි.\n\nමේ ගසේ කොළ කොටා මිරිකා ගත් යුෂ සෙම් පැසවීම සඳහා කැඳ පිසීමට ත්, ප්‍රතිශ්‍යාව නරක් වී සෙම වියළන විට එම සෙම බුරුල් වීම සඳහා තම්බා වෙදු පෑම (දුම් ඇල්ලීම) ට ත්, ඇතැම් සන්නි රෝග සඳහා කොළ යුෂ නශ්‍ය කිරීමට හා යකුවනස්ස, නික, කුඹුරු කොළ සමග ගිනි කබල් වලට දමා දුම්පා සෙවද ගැන්වීමට ත් පාවිච්චි කරති.\n\nයකිනාරන් මුල් කෂාය-තෙල්-බෙහෙත් වගී සඳහා අවශ්‍ය ඖෂධ යෝග වලට ගණිති.", 
        "category": "plant",
        "image": "img_385_yakinaran.jpg"
    },
    { "word": "යකිවනසු (ස්ස)", "meaning": "යකුවනස්ස ගස", "category": "plant" },
    { "word": "යකු", "meaning": "කුඹුරු ඇට, යකවනස්ස, යක්බේරිය", "category": "plant" },
    { "word": "යකුත් එබුව", "meaning": "යක්‍ෂාවේශ වූව (තනිකම නිසා රෝගී වූ අය)", "category": "treatment" },
    { "word": "යකුනෙත්", "meaning": "කුඹුරු ඇට", "category": "plant" },
    { "word": "යකුවනසු", "meaning": "යක්වනස්ස", "category": "plant" },
    { "word": "යකාන්ච්ඡාල", "meaning": "උදර රෝගයක්", "category": "treatment" },

    // --- පිටුව 386 ---
    { "word": "යකෘත්", "meaning": "අක්මාව, එය වැඩීමෙන් ඇති වන රෝගය.", "category": "treatment" },
    { "word": "යඥ අංග", "meaning": "දිවුල් ගස", "category": "plant" },
    { "word": "යකෘත් වෛරින්", "meaning": "එරබදු ගස", "category": "plant" },
    { "word": "යඥක", "meaning": "කෑල ගස", "category": "plant" },
    { "word": "යඥධූප", "meaning": "දුම්මල", "category": "mineral" },
    { "word": "යඥනේතා", "meaning": "මුවකිරිය, මූණමල් ගස", "category": "plant" },
    { "word": "යඥභූෂණ", "meaning": "සුදු කුසතණ, ඉළුක්", "category": "plant" },
    { "word": "යඥයෝග්‍ය", "meaning": "අත්තික්කා", "category": "plant" },
    { "word": "යඥවල්ලි", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "යඥවෘක්‍ෂ", "meaning": "නුග ගස", "category": "plant" },
    { "word": "යඥශ්‍රෙෂ්ඨ", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "යඥසංස්තරණ", "meaning": "ඉළුක්", "category": "plant" },
    { "word": "යඥසාර", "meaning": "දිවුල්", "category": "plant" },
    { "word": "යඥාංග", "meaning": "ඉළුක්, කිහිරි, අත්තික්කා", "category": "plant" },
    { "word": "යඥාංගික", "meaning": "කළු කිහිරි", "category": "plant" },
    { "word": "යඥායෝග", "meaning": "අත්තික්කා, තුන්පුලිල", "category": "plant" },
    { "word": "යඥිකා", "meaning": "කළුකිහිරි", "category": "plant" },
    { "word": "යඥිකා", "meaning": "ඉළුක්", "category": "plant" },
    { "word": "යඥි වෘක්‍ෂ", "meaning": "මුවකිරිය", "category": "plant" },
    { "word": "යඥෙය", "meaning": "ඉළුක්", "category": "plant" },
    { "word": "යඥෝඩූම්බර", "meaning": "දිවුල් ගස", "category": "plant" },
    { "word": "යඥ්‍යා", "meaning": "දුම්මල්ල", "category": "plant" },
    { "word": "යඥ්‍යාහ්වෝ", "meaning": "දිවුල්", "category": "plant" },
    { "word": "යට්පි", "meaning": "වැල්මී", "category": "plant" },
    { "word": "යටි", "meaning": "ලතාව, වැල්මී, වැල්මදට", "category": "plant" },
    { "word": "යතිඳු", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "යදල්", "meaning": "යබොර, යකඩ මළ", "category": "mineral" },
    { "word": "ය දල් සුන්නෙත්", "meaning": "යකඩ කුඩු වලින්", "category": "mineral" },
    { "word": "ය තුග", "meaning": "පතොක්", "category": "plant" },
    { "word": "ය පත", "meaning": "යකඩ තහඩුව", "category": "mineral" },
    { "word": "යම දූතිකා", "meaning": "සියඹලා", "category": "plant" },
    { "word": "යමනාතකා", "meaning": "අසමෝද", "category": "plant" },
    { "word": "යමප්‍රිය", "meaning": "නුග ගස", "category": "plant" },
    { "word": "යමල", "meaning": "හිඹුල්, යකඩ මළ", "category": "mineral" },
    { "word": "යමලකණ්ටක", "meaning": "දඹක් ගස", "category": "plant" },
    { "word": "යමලපත්‍ර", "meaning": "පොල්පලා", "category": "plant" },
    { "word": "යමලපත්‍රිකා", "meaning": "කොබෝලීල ගස", "category": "plant" },
    { "word": "යමලපුෂ්පක", "meaning": "කොබෝලීල ගස", "category": "plant" },
    { "word": "යමල ඵල", "meaning": "මහ වැල් පෙනෙල, උණ ගස", "category": "plant" },
    { "word": "යමලාලා", "meaning": "කිරිඳි", "category": "plant" },
    { "word": "යමානිකා", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "යමානී", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "යමුඛා", "meaning": "හොයදුන්", "category": "plant" },
    { "word": "යමෝ", "meaning": "අසමෝදගන්", "category": "plant" },
    { "word": "යරල්", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "යල හැනි", "meaning": "මල්කැන", "category": "plant" },
    { "word": "යල්ව", "meaning": "සාලියා අරිසි", "category": "plant" },
    { "word": "යව", "meaning": "හුන වී, අස මෝදගම්, යව හාල්, කොල්ලු", "category": "plant" },
    { "word": "යවංගු", "meaning": "සිනි", "category": "food" },
    { "word": "යවඃ", "meaning": "අරළු ගස", "category": "plant" },
    { "word": "යවක්‍ෂාර", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවක", "meaning": "කළුතලා, යවධාන්‍ය, කෙත පිය", "category": "plant" },
    { "word": "යවකණ්ටක", "meaning": "හින් සාතාවාරිය", "category": "plant" },
    { "word": "යවකර", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවප්", "meaning": "අසමෝද, යවකර ලුණු", "category": "plant" },
    { "word": "යවතාෂ්ට්‍ර", "meaning": "කොසඹ", "category": "plant" },
    { "word": "යවතික්තා", "meaning": "ඇල් වී, අරත්ත, යක්බේරිය, චිරතා", "category": "plant" },
    { "word": "යවද්‍යායා", "meaning": "බැඳි සාල්", "category": "food" },
    { "word": "යවදනී", "meaning": "අසමෝදගම්, ශතපුෂ්ප", "category": "plant" },
    { "word": "යවධාතිකා", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "යවධාන්‍ය", "meaning": "බැඳිසාල්", "category": "food" },
    { "word": "යවධාන්‍යක", "meaning": "යව වී, අසමෝදගම්", "category": "plant" },
    { "word": "යවන", "meaning": "නිරිහු", "category": "plant" },
    { "word": "යවකද්වීෂ්ට", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "යවනප්‍රිය", "meaning": "මිරිස්", "category": "plant" },
    { "word": "යවන සමන්", "meaning": "ගැටපිච්ච", "category": "plant" },
    { "word": "යවනාමකා", "meaning": "හින් අසමෝදගම්", "category": "plant" },

    // --- පිටුව 387 ---
    { "word": "යවනාලජ", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවනෙෂ්ට", "meaning": "කොසඹ, මහ ලුහුනු, මිරිස්, ඉඳි, ඊයම්, ලූනු, මෑබ ගඟු, වච්චනාභි", "category": "plant" },
    { "word": "යවපත්‍ර (යවන පත්‍රිකා)", "meaning": "උඩැත්ත", "category": "plant" },
    { "word": "යව පත්‍රිකා", "meaning": "උඩැත්ත", "category": "plant" },
    { "word": "යවපුෂ්පී", "meaning": "සබර ලොත්", "category": "plant" },
    { "word": "යවප්‍රබත්‍යා", "meaning": "යව ඇට වැනි කුෂ්ටය", "category": "treatment" },
    { "word": "යවඵල", "meaning": "උණ ගස, කෙළින්ද, ජටා මාංශ", "category": "plant" },
    { "word": "යවරෝද", "meaning": "අරළු", "category": "plant" },
    { "word": "යවලාස", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවිලූඃ", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවිශුක", "meaning": "යවබුළු, යවකර ලුණු", "category": "plant" },
    { "word": "යවුශුකප්", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවශාර", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවසෝ", "meaning": "ධාන්‍ය වගියක්", "category": "plant" },
    { "word": "යවා", "meaning": "යව නම් වූ ධාන්‍ය වගිය", "category": "plant" },
    { "word": "යවාගූ", "meaning": "නුළු කැඳ (ලුණු කැඳ), බත් ඇට මෙන් සය ගුණයක් වතුර යොදා ඇති කැඳ වෙසෙස", "category": "food" },
    { "word": "යවාග්‍රප්", "meaning": "කාඩි දිය, යවකර ලුණු", "category": "liquid" },
    { "word": "යවානිකා", "meaning": "මහ අසමෝදගම්", "category": "plant" },
    { "word": "යවානී", "meaning": "කළුදුරු, හින් අසමෝද, මහ අසමෝද", "category": "plant" },
    { "word": "යවාපක්‍ෂය", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවාමිහ", "meaning": "යව කැම්බු දිය", "category": "liquid" },
    { "word": "යවාමිලප්", "meaning": "කාඩි, බෙබර ගස", "category": "plant" },
    { "word": "යවාස", "meaning": "බක්මීගස (දුරාලභා) වෙනුවට ප්‍රතිනිධි වශයෙන් ගෑණීමට ඉන්දියානු පඬුවන් විසින් නියම කරණ ලද ඉන් දියානු පැලෑටියකි. මේ දෙවගි ය වෙනුවට ම ලංකාවේ ගන්නේ වැල් කහඹිලියා ය. 250 පිටේ දුරාලභා ගැන ලියූ විස්තරය බලන්න.", "category": "plant" },
    { "word": "යවාහ්ව", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යවාහ්වා", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "යවොප්", "meaning": "කාඩි, හොයදුන්", "category": "liquid" },
    { "word": "යශෂ්කරී", "meaning": "කිරි පලා", "category": "plant" },
    { "word": "යෂ්ට්‍යාහ්ව", "meaning": "වැල්මී", "category": "plant" },
    { "word": "යෂ්ටී", "meaning": "හින් මිදි, නිප්පිලි, වැල්මී, රත්හඳුන්, වැල්මදට", "category": "plant" },
    { "word": "යෂ්ටික", "meaning": "වැල්මී", "category": "plant" },
    { "word": "යෂ්ටිපුෂ්ප", "meaning": "බුත්සරණ", "category": "plant" },
    { "word": "යෂ්ටී පුෂ්ප", "meaning": "ජීවක ගස", "category": "plant" },
    { "word": "යෂ්ටීමධු", "meaning": "වැල්මී", "category": "plant" },
    { "word": "යෂ්ටීමධුක", "meaning": "රත් හඳුන්, වැල්මී", "category": "plant" },
    { "word": "යසසි", "meaning": "කුඹුරු ඇට", "category": "plant" },
    { "word": "යහපුහුරු", "meaning": "යහ වපු (ශතපුෂ්ප)", "category": "plant" },
    { "word": "යහවපු", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "යහුණු", "meaning": "යකඩ කුඩු", "category": "mineral" },
    { "word": "යාගු", "meaning": "කැඳ", "category": "food" },
    { "word": "යාගු (කැඳ) ගුණදසය", "meaning": "ආයු, වර්ණ, සැප, බල, ප්‍රතිහාන ඇනිවීම, සා, පිපාස ය දුරුවීම, වාතය අනුලෝම් වීම, වස්ති ශෝධනය හා ආමාශයශය පහ වීම යන මේ ගුණ දසය බුදු රජාණන් වහන්සේ විසින් විනය පිටක දේශනාවෙහි දී වදාරණ ලද්දකි.", "category": "food" },
    { "word": "යාගේෂක", "meaning": "වැලුක්", "category": "plant" },
    { "word": "යාවන", "meaning": "තුරුක් තෙල්", "category": "liquid" },
    { "word": "යාල්කදික", "meaning": "කෑල, එරබදු, කිහිරි, ඇසටු", "category": "plant" },
    { "word": "යාතුස්න", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "යානේයිකමිල්", "meaning": "ඇද්දෙමට", "category": "plant" },
    { "word": "යානෙයිතකර", "meaning": "ඇත්තෝර", "category": "plant" },
    { "word": "යානෙයිවනන්ගි", "meaning": "ඇත්සැටිය", "category": "plant" },
    { "word": "යාපුර", "meaning": "නිරිල =(බුන්ම යව) (තෝ වැල්ල = රට බුලත්)", "category": "plant" },
    { "word": "වැල්ල", "meaning": "රට බුලත්", "category": "plant" },

    // --- පිටුව 388 ---
    { "word": "යාප්‍ය", "meaning": "සන්සිඳවන්ට පුළුවන් ලෙඩ", "category": "treatment" },
    { "word": "යාබ", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "යාමුන", "meaning": "හොයදුන්", "category": "plant" },
    { "word": "යාමුනෙෂ්ටක", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "යාම්‍ය", "meaning": "හිඟුල්", "category": "mineral" },
    { "word": "යාම්‍යක", "meaning": "කතුරු මුරුංගා ගස, හඳුන් ගස", "category": "plant" },
    { "word": "යාම්‍යාදෘ", "meaning": "ඉඹුල් ගස", "category": "plant" },
    { "word": "යාමෙසාද්භූත", "meaning": "දකුණු දෙසෙහි හට ගන්නා ශ්‍රීමත් තල් ගස", "category": "plant" },
    { "word": "යාවකෝ", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "යාවන", "meaning": "අසමෝදගම්", "category": "plant" },
    { "word": "යාවනාල", "meaning": "ධාන්‍ය ප්‍රභේද", "category": "plant" },
    { "word": "යාවපු", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "යාවශුක", "meaning": "යවකර ලුණු", "category": "mineral" },
    { "word": "යාස", "meaning": "යවාස (ඒ වෙනුවට මේ රටේ වැල් කසඹිලියා ගණිති)", "category": "plant" },
    { "word": "යාසක", "meaning": "යවාස", "category": "plant" },
    { "word": "යුක්තරස", "meaning": "අරත්ත", "category": "plant" },
    { "word": "යුග්මකණ්ටක", "meaning": "බෙබර ගස", "category": "plant" },
    { "word": "යුග්ම පත්‍ර", "meaning": "රක් අත්තන, රතු කොබෝලීල, ඉන්සළු", "category": "plant" },
    { "word": "යුග්මපත්‍රක", "meaning": "කොබෝලීල", "category": "plant" },
    { "word": "යුග්මඵලා", "meaning": "මහ බෙබර, ඇත් සැටිය, කිරිඳි", "category": "plant" },
    { "word": "යුග්‍ය", "meaning": "මහදඹ කලත්", "category": "plant" },
    { "word": "යුග", "meaning": "යුග්ම, (දෙක)", "category": "measurement" },
    { "word": "යුගදල", "meaning": "කොබලීල (කොබෝලීල)", "category": "plant" },
    { "word": "යුගපත්", "meaning": "කොබෝලීල ගස, ඉන්සළු ගස", "category": "plant" },
    { "word": "යුගපත්නිරු", "meaning": "අත්තන, තුන්බෝ අත්තන", "category": "plant" },
    { "word": "යුගපත්‍ර", "meaning": "කොබෝලීල ගස, ඉන්සළු ගස", "category": "plant" },
    { "word": "යුගපත්‍රක", "meaning": "කොබලීල (කොබෝලීල)", "category": "plant" },
    { "word": "යුගලාබ්‍ය", "meaning": "රම්මානිස්ස", "category": "plant" },
    { "word": "යුෂ්පාමානක", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "යුති / යුතිකා", "meaning": "බෝලිද්ද", "category": "plant" },
    { "word": "යුවනි", "meaning": "කෝමාරිකා", "category": "plant" },
    { "word": "යුවනිෂ්ටා", "meaning": "පිච්ච", "category": "plant" },
    { "word": "යුවලපත්", "meaning": "කොබෝලීල", "category": "plant" },
    { "word": "යුස", "meaning": "ඉස්ම, මුංඇට ආදිය තම්බා ගත් රසය", "category": "liquid" },
    { "word": "යූථිකපර්ණී", "meaning": "අනිත්ත", "category": "plant" },
    { "word": "යූථිකා", "meaning": "බෝලිද්ද", "category": "plant" },
    { "word": "යූථී", "meaning": "දියමිත්ත, බෝලිද්ද", "category": "plant" },
    { "word": "යූෂ", "meaning": "තුන් පුලිල", "category": "plant" },
    { "word": "යූෂදෘ", "meaning": "කිහිරි ගස, යුෂ, මුං ආදියෙහි යුෂ", "category": "plant" },
    { "word": "යෙල කලඳ", "meaning": "කලන් බාගය", "category": "measurement" },
    { "word": "යෙෂ්කත්", "meaning": "වැල් මදට", "category": "plant" },
    { "word": "යෝගක", "meaning": "පතඟි", "category": "plant" },
    { "word": "යෝගවහා", "meaning": "මූරුවා", "category": "plant" },
    { "word": "යෝගවාහී", "meaning": "පිත්තල, ගල් සෙවෙල්", "category": "mineral" },
    { "word": "යෝගී", "meaning": "මූරුවා", "category": "plant" },
    { "word": "යෝගේෂ්ට", "meaning": "කළු ඊයම්", "category": "mineral" },
    { "word": "යෝග", "meaning": "සාදිවි නම් ඖෂධය, සුළු දඹ කලත්", "category": "plant" },
    { "word": "යෝපන ගඬා", "meaning": "කස්තුරි", "category": "animal" },
    { "word": "යෝජිත පර්ණී", "meaning": "වැල් මදට", "category": "plant" },
    { "word": "යෝජන වල්ලී", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "යෝජනා", "meaning": "කකීටක ශෘංගි", "category": "plant" },
    { "word": "යෝන් ඉඳි", "meaning": "රට ඉඳි", "category": "plant" },
    { "word": "යෝනි", "meaning": "වතුර", "category": "liquid" },
    { "word": "යොමු", "meaning": "පිච්ච මල්", "category": "plant" },

    // --- පිටුව 389 ---
    { "word": "යොය", "meaning": "නෙරී විෂ", "category": "plant" },
    { "word": "යොෂික් ප්‍රියා", "meaning": "කහ", "category": "plant" },
    { "word": "යොහොඹු", "meaning": "ගැට පිච්ච, මාලතී (මලගිය මල්)", "category": "plant" },
    { "word": "යොහොඹු වැල්", "meaning": "ගැටපිච්ච වැල්", "category": "plant" },
    { "word": "යෝග", "meaning": "යෙදීම", "category": "general" },
    { "word": "යෝගා බිජ්", "meaning": "කණ්ටක මුල, කින්නරා ඇට", "category": "plant" },
    { "word": "යෝනී", "meaning": "යකුවනස්ස", "category": "plant" },
    { "word": "යෝනියා", "meaning": "යකුවනසු, උතු මග", "category": "anatomy" },
    { "word": "යෝනි ව්‍යාපත්", "meaning": "ස්ත්‍රී රෝගයක්", "category": "treatment" },
    { "word": "යෝනී(2)", "meaning": "වතුර", "category": "liquid" },
    { "word": "යෝය", "meaning": "නෙරිවිස, වච්චනාභි", "category": "plant" },
    { "word": "යෙෂවනී", "meaning": "යකුවනසු, කෝමාරිකා", "category": "plant" },
    { "word": "රාව", "meaning": "රත්කෑල", "category": "plant" },
    { "word": "රංජනී", "meaning": "අවරිය", "category": "plant" },
    { "word": "රංස", "meaning": "මනෝසිල, සවිඳවලුණු", "category": "mineral" },
    { "word": "රංතොලිවී", "meaning": "පිලගස", "category": "plant" },
    { "word": "රක්", "meaning": "මනෝසිල, රත්හිරියල්", "category": "mineral" },
    { "word": "රක්කලල්", "meaning": "මනඃ ශිලා කල්කය (මනෝශිල කල්කය)", "category": "mineral" },
    { "word": "රක්සුණු", "meaning": "මනඃ ශිලාචූර්ණය", "category": "mineral" },
    { "word": "රක්ගොයවු", "meaning": "රත්ගොකටුගස්, රත්මල්ගස්", "category": "plant" },
    { "word": "රක්ත", "meaning": "ඇඹුල්වේ, කිහිරි, ලේ, සින්දූරම්, මුතු, වැලඟුන, නුග, කොකුම්, තඹ, සාදිලිංගම්, සෙන්දිරින්කා, දිය මිදෙල්ල, වැල් මදට, ලාකඩ, ඔලිඳ, රත්හඳුන්", "category": "mineral" },
    { "word": "රක්ත උමෝදිකා", "meaning": "රත්තිවිනි", "category": "plant" },
    { "word": "රක්තක", "meaning": "බදුවද, රත්මුරුංගා, රත් එරබු, ලේ, කටුකරඬු, කොල්ලු", "category": "plant" },
    { "word": "රක්තක වීරවෘක්‍ෂ", "meaning": "රත්එරබු", "category": "plant" },
    { "word": "රක්තකඤ්", "meaning": "පබළු", "category": "mineral" },
    { "word": "රක්තකමලා", "meaning": "රත්උපුල්", "category": "plant" },
    { "word": "රක්තකරවීර", "meaning": "රතුකණේරු", "category": "plant" },
    { "word": "රක්තකා", "meaning": "කටුවැල්බටු", "category": "plant" },
    { "word": "රක්තකාඤ්චන", "meaning": "රතුසපුගස", "category": "plant" },
    { "word": "රක්තකාණ්ඩ", "meaning": "රතුසාරණ", "category": "plant" },
    { "word": "රක්තකාහ්ව", "meaning": "පතඟි", "category": "plant" },
    { "word": "රක්තකුමුද", "meaning": "රත්මහනෙල්", "category": "plant" },
    { "word": "රක්තකුරවක", "meaning": "රත්කරව්ගස", "category": "plant" },
    { "word": "රක්තකුසුම", "meaning": "දෙළුම්ගස, එරබදු", "category": "plant" },
    { "word": "රක්තකේශර", "meaning": "දෙඹ ගස, එරබදු ගස, නාමල්රේණු", "category": "plant" },
    { "word": "රක්තකෙසරු", "meaning": "නාමල්", "category": "plant" },
    { "word": "රක්තඛදිර", "meaning": "රත්කිහිරි", "category": "plant" },
    { "word": "රක්තඛල්ව", "meaning": "කොල්ලු", "category": "plant" },
    { "word": "රක්තගන්ධක", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "රක්තගර්භ", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "රක්තගොක්‍ෂුරක", "meaning": "රත්ගොකටු", "category": "plant" },
    { "word": "රක්තගෝමේද", "meaning": "ගෝමේදගල", "category": "mineral" },
    { "word": "රක්තඝන", "meaning": "එරබදු, ඊ තණ", "category": "plant" },
    { "word": "රක්තචන්දන", "meaning": "රත් හඳුන්, වැල්මදට", "category": "plant" },
    { "word": "රක්තචන්දනා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "රක්තචිත්‍රක", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "රක්තචූර්ණී", "meaning": "සින්දූරම්", "category": "mineral" },
    { "word": "රක්තජ", "meaning": "තඹ", "category": "mineral" },
    { "word": "රක්තජරස", "meaning": "ලේරස", "category": "anatomy" },
    { "word": "රක්තතණ්ඩුලා", "meaning": "සුළුබූබැවිල", "category": "plant" },
    { "word": "රක්තදලා", "meaning": "මුහුණුවිල", "category": "plant" },
    { "word": "රක්තධාතුක", "meaning": "තඹ, සිවංගුරු", "category": "mineral" },
    { "word": "රක්තනායක", "meaning": "කෙළිඳගස්", "category": "plant" },
    { "word": "රක්තනාල", "meaning": "රත්තම්පලා", "category": "plant" },
    { "word": "රක්තනාලී", "meaning": "රත්මහනෙල්", "category": "plant" },
    { "word": "රක්තනීල", "meaning": "නුගගස", "category": "plant" },
    { "word": "රක්තපත්‍රිකා", "meaning": "බදුවද ගස, අරත්ත", "category": "plant" },
    { "word": "රක්තපර්ණී", "meaning": "වල්මදට", "category": "plant" },

    // --- පිටුව 390 ---
    { "word": "රක්තපල්ලව", "meaning": "හෝපළු ගස", "category": "plant" },
    { "word": "රක්තපා", "meaning": "කූඩාවා (කුඩැල්ලා)", "category": "animal" },
    { "word": "රක්තපාකී", "meaning": "කටුවැල්බටු, බටු", "category": "plant" },
    { "word": "රක්තපාද", "meaning": "වලාවැන්න, නිදිකුම්බා", "category": "plant" },
    { "word": "රක්තපාදී", "meaning": "වලාවැන්න", "category": "plant" },
    { "word": "රක්තපායිනී", "meaning": "කූඩාවා", "category": "animal" },
    { "word": "රක්තපාරද", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "රක්තපාෂාණක", "meaning": "සුවංගුරු, (සිවංගුරු)", "category": "mineral" },
    { "word": "රක්තපිත්ත", "meaning": "රත්පිත", "category": "treatment" },
    { "word": "රක්තපුෂ්ප", "meaning": "එරබදු, කණේරු, රත් කිහිරි, දෙළුම්, මූණ මල්, බදුවද, දෙඹ, කෑල, පැපිලිය, ඉඹුල්, සෙන්දිරික්කා", "category": "plant" },
    { "word": "රක්තපුෂ්පී", "meaning": "දියමිදෙල්ල, නිදිකුම්බා, මලිත", "category": "plant" },
    { "word": "රක්තපුෂ්පිකා", "meaning": "ඉඹුල්, නිදිකුම්බා, රතුසාරණ", "category": "plant" },
    { "word": "රක්තපුෂ්පී(2)", "meaning": "එරබදු, ලුණුවරණ, පලොල්, වදගස, සස්සඳ, දේවදාලිය", "category": "plant" },
    { "word": "රක්තපූරක", "meaning": "සියඹලා", "category": "plant" },
    { "word": "රක්තපූණව", "meaning": "රත් කටුකරඬු, කණේරු", "category": "plant" },
    { "word": "රක්තඵල", "meaning": "නුග ගස, කෙම්වැල්", "category": "plant" },
    { "word": "රක්තඵලා", "meaning": "කෝවක්කා,කෙම්වැල්", "category": "plant" },
    { "word": "රක්තඵලිකා", "meaning": "ඔලිඳ", "category": "plant" },
    { "word": "රක්තබිඳුච්ඡද", "meaning": "රසතැල්ල", "category": "plant" },
    { "word": "රක්තබිඳුපත්‍ර", "meaning": "රසතැල්ල", "category": "plant" },
    { "word": "රක්තබිඳුසමපත්‍ර", "meaning": "රසතැල්ල", "category": "plant" },
    { "word": "රක්තබීජ", "meaning": "මදට ගස", "category": "plant" },
    { "word": "රක්තබීජා", "meaning": "එරබදු ගස", "category": "plant" },
    { "word": "රක්තමන්දාර", "meaning": "මිදෙල්ල ගස", "category": "plant" },
    { "word": "රක්තමන්දාරී", "meaning": "අක්මැල්ල", "category": "plant" },
    { "word": "රක්තමණි", "meaning": "රතු මැණික", "category": "mineral" },
    { "word": "රක්තමාලි", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "රක්තමූලා", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "රක්තමේඝ", "meaning": "ප්‍රමේහ රෝග භෙදයක්", "category": "treatment" },
    { "word": "රක්තයෂ්ටි", "meaning": "ඔලිඳවැල්, වැල්මදට", "category": "plant" },
    { "word": "රක්තරජ", "meaning": "සින්දූරම්", "category": "mineral" },
    { "word": "රක්තරේණු", "meaning": "කෑලමල්, කෑකුල, සින්දූරම්", "category": "plant" },
    { "word": "රක්තලතාතක", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "රක්තලතා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "රක්තලසුන", "meaning": "රතුලූනු", "category": "plant" },
    { "word": "රක්තලා", "meaning": "අගිල්", "category": "plant" },
    { "word": "රක්තලොහ", "meaning": "තඹ", "category": "mineral" },
    { "word": "රක්තවටී", "meaning": "මැසිරි", "category": "plant" },
    { "word": "රක්තවර්ණිකා", "meaning": "එරබදු", "category": "plant" },
    { "word": "රක්තවර්ණමාලා", "meaning": "කොකුම්", "category": "plant" },
    { "word": "රක්තවර්ධන", "meaning": "බටුගස", "category": "plant" },
    { "word": "රක්තවර්ෂු", "meaning": "රතුසාරණ", "category": "plant" },
    { "word": "රක්තවාස්තුක", "meaning": "රත්තම්පලා", "category": "plant" },
    { "word": "රක්තවිඳුච්ඡද", "meaning": "රසතැල්ල", "category": "plant" },
    { "word": "රක්තවීජ", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "රක්තවෘන්තා", "meaning": "සුළු සාරණ, සේපාලිකා", "category": "plant" },
    { "word": "රක්තවෛදුර්‍ය", "meaning": "රතු වයිරෝඩි", "category": "mineral" },
    { "word": "රක්තශිඛික", "meaning": "හොරගස, ගුගුල්", "category": "plant" },
    { "word": "රක්තසංකෝච", "meaning": "කොකුම්", "category": "plant" },
    { "word": "රක්තසන්ධික", "meaning": "රත්මහනෙල්", "category": "plant" },
    { "word": "රක්තසන්ධ්‍යක", "meaning": "රතු නෙල්මැලි, නෙළුම්", "category": "plant" },
    { "word": "රක්තසර්ෂප", "meaning": "රතු අබ", "category": "plant" },
    { "word": "රක්තසහා", "meaning": "රතු උඳුපියලි", "category": "plant" },
    { "word": "රක්තසාර", "meaning": "ඇඹුල්වේ, රත්හඳුන්", "category": "plant" },
    { "word": "රක්තසෞගන්ධික", "meaning": "රතු නෙල්මැලි", "category": "plant" },
    { "word": "රක්තා", "meaning": "ලාකඩ, ලියනගලා", "category": "plant" },
    { "word": "රක්තාකාර", "meaning": "පබළු", "category": "mineral" },
    { "word": "රක්තාංග", "meaning": "කටුවෙලඟ, කොකුම්, පබළු, කිරිපලා, වැල්මදට", "category": "plant" },
    { "word": "රක්තාණ්ඩිනී", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "රක්තාතිරක්ත", "meaning": "රත්ගොකටු", "category": "plant" },
    { "word": "රක්තාධාර", "meaning": "ශරීරය වසා සිටි සම", "category": "anatomy" },
    { "word": "රක්තාපර්ණිකා", "meaning": "කුඹුරුමිරිස්", "category": "plant" },
    { "word": "රක්තාපහා", "meaning": "ගෙත්දගම්", "category": "mineral" },

    // --- පිටුව 391 ---
    { "word": "රක්තාපාමාර්ග", "meaning": "රත්සැබෝ", "category": "plant" },
    { "word": "රක්තාම්ලාන", "meaning": "රතු උඳුපියලි", "category": "plant" },
    { "word": "රක්තාලු", "meaning": "බතල", "category": "plant" },
    { "word": "රක්තශාලි", "meaning": "රත්හැල්", "category": "plant" },
    { "word": "රක්තශිඛික", "meaning": "හොර", "category": "plant" },
    { "word": "රක්තීකා", "meaning": "ඔලිඳ, අබ", "category": "plant" },
    { "word": "රක්තෙක්‍ෂු", "meaning": "රතු උක්", "category": "plant" },
    { "word": "රක්තෙරණ්ඩ", "meaning": "රතු එරබු", "category": "plant" },
    { "word": "රක්තොත්පල", "meaning": "රතුඋපුල්, රක් මහනෙල්, රත් නෙළුම්", "category": "plant" },
    { "word": "රක්‍ෂණී", "meaning": "බැමිතිරිය", "category": "plant" },
    { "word": "රක්‍ෂසි", "meaning": "හරන්කසා", "category": "plant" },
    { "word": "රක්‍ෂා", "meaning": "ලසු දිග, අළු", "category": "plant" },
    { "word": "රක්‍ෂාපත්‍ර", "meaning": "කරගස", "category": "plant" },
    { "word": "රක්‍ෂෝඝන", "meaning": "කාඩි, පෙරැම්කායම්, බදුල්ල, සුදු අබ, වදකහ, හරන්කහ", "category": "plant" },
    { "word": "රක්‍ෂෝහත්", "meaning": "ගුගුල්, සුදු අබ", "category": "plant" },
    { "word": "රක්සය", "meaning": "කොපවැල", "category": "plant" },
    { "word": "රඛග", "meaning": "පුෂ්කර, සුදු ඊයම්, කිහිරි අරටුව", "category": "plant" },
    { "word": "රඛගක", "meaning": "සුදු ඊයම්", "category": "mineral" },
    { "word": "රඛගකාෂ්ඨ", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "රඛගජ", "meaning": "සින්දූරම්", "category": "mineral" },
    { "word": "රඛගද", "meaning": "කිහිරි අරටුව, පුෂ්කර, කයිප්පු", "category": "plant" },
    { "word": "රඛගදයක", "meaning": "පික්මල්", "category": "plant" },
    { "word": "රඛගපත්‍රී", "meaning": "බෙරු", "category": "plant" },
    { "word": "රඛගපුෂ්පී", "meaning": "බෙරු", "category": "plant" },
    { "word": "රඛගභෝග්‍ය", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "රඛගමාතා", "meaning": "ලාකඩ", "category": "mineral" },
    { "word": "රඛගලාසිනී", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "රඛගවිප්", "meaning": "රිදී", "category": "mineral" },
    { "word": "රඛගා", "meaning": "කෙහෙල් ගස", "category": "plant" },
    { "word": "රඛගාරි", "meaning": "කණේරු", "category": "plant" },
    { "word": "රඛගිණී", "meaning": "දිවුල්, සාතාවාරිය, කොටවියාමුරු", "category": "plant" },
    { "word": "රජ", "meaning": "වෙනිවැල්, ඔසප් ලේ, පැපිලිය, මල්රේණු, තල්ගස", "category": "plant" },
    { "word": "රජග", "meaning": "තොටිල ගස", "category": "plant" },
    { "word": "රජත", "meaning": "රිදී, ඇත්දළ, ලේ, ගල, රත්රන්, සුදුපාට තල්ගස", "category": "plant" },
    { "word": "රජතී", "meaning": "රිදී, ඇත්දෙමට", "category": "plant" },
    { "word": "රජදත්", "meaning": "ඇත්දත්, (රාජදත්ත)", "category": "animal" },
    { "word": "රජනං", "meaning": "තල්ගස", "category": "plant" },
    { "word": "රජන", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "රජනදෘම", "meaning": "මදට ගස", "category": "plant" },
    { "word": "රජතී(2)", "meaning": "කහ, පැපිලිය, රාත්‍රිය, කුඩුමිරිස්", "category": "plant" },
    { "word": "රජනිපිල්ල", "meaning": "කුඩුමිරිස්වැල", "category": "plant" },
    { "word": "රජනිඵල", "meaning": "පිනි", "category": "nature" },
    { "word": "රජනිද්වය", "meaning": "කහ, වෙනිවැල්, (බාන්වැල්) දෙවර්ගය", "category": "plant" },
    { "word": "රජනිවල්ලී", "meaning": "තෝවල්ල, යාපුර", "category": "plant" },
    { "word": "රජනියාසා", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "රජමුල්", "meaning": "ඇසළ මුල්, ඇසළ ගස", "category": "plant" },
    { "word": "රජවරක්", "meaning": "ඇසළ ගස,", "category": "plant" },
    { "word": "රජවරකසුඹුල්", "meaning": "ඇහැලමුලේ පොතු", "category": "plant" },
    { "word": "රජස්", "meaning": "කිල්ල, මල්රේණු", "category": "plant" },
    { "word": "රජස්වලා", "meaning": "කිල්ල, ඔසප් සත්‍රිය", "category": "person" },
    { "word": "රඤ්ච", "meaning": "රත්කෑල ගස", "category": "plant" },
    { "word": "රඤ්ජක", "meaning": "සාදිලිංගම්, කටුවෙලඟ", "category": "mineral" },
    { "word": "රඤ්ජන", "meaning": "රත්හඳුන්, වැල්මදට, සේපාලිකා - කටුකරඬු, බෙරු, කහ, පැපිලිය, ඇත්දෙමට", "category": "plant" },
    { "word": "රඤ්ජනක", "meaning": "කටුවෙලඟ", "category": "plant" },
    { "word": "රඤ්ජනා", "meaning": "ලාකඩ, කහ", "category": "plant" },
    { "word": "රඤ්ජනී", "meaning": "බෙරුගස, අවරිය", "category": "plant" },
    { "word": "රඤ්ජීකා", "meaning": "වැල්මදට", "category": "plant" },
    { "word": "රටංකන", "meaning": "ලාකඩ", "category": "mineral" },

    // --- පිටුව 392 ---
    { 
        "word": "රට අරළු", 
        "scientific": "Terminalia Chebula",
        "meaning": "Terminalia Chebula-විශාල කොළ හා ගෙඩි ඇති අරළු වර්ගයක්.\n\nවිජයා, රෝහිනී, පූතනා, අමෘතා, අභයා, ජීවන්ති, චේතකී යයි අරළු වගී සතකි. වාජීකරණයෙහි විජයා නම් අරළු ද, ක්‍ෂය රෝගයෙහි රෝහිණී නම් අරළු ද, ආලේපයෙහි (ඇඟ ගෑමෙහි) පූතනා නම් අරළු ද, විරේචනයෙහි අමෘතා නම් අරළු ද, අක්‍ෂි රෝගයෙහි අභයා නම් අරළු ද, සියළු රෝග නැසීමෙහි තැතහොත් අරළු අවශ්‍ය හැම ඖෂධ යෝගයන්හි ජීවන්ති නම් අරළු ද, චූර්ණ සාදි මෙනි චේතකී නම් අරළු ද ගත යුතු යි.\n\nමේ හැම වගියක ම ලපටි (නොපැසුන) ගෙඩි වියලා ගත්තා ලද කළු අරළු නැතහොත් කොළු අරළු යයි තව වගියක් ද තිබේ. දෙමලු - කොච්චි - මුස්ලිම් වෙද මහත්වරු අරළු වෙනුවට ඖෂධ වශයෙන් ගන්නේ මේ වගිය (වියලා ගත් අරළු ගැට)යි, (කකීටකශෘංගි වලට ද කොළු අරළු යයි ව්‍යවහාර කරති).\n\nසාමාන්‍යයෙන් අරළු කොළ දිග පළලින් අඟල් 6 x 3 කට වඩා විශාල නැත. මේ සත් වර්ගයට ම අයත් ඉතා විශාල අරළු ගෙඩිය වුව ද ලොකු ලුණුවිදෙල්ල ගෙඩියකට වඩා විශාල නැත.\n\nඑහෙ ත්, මේ රටේ ඇතැම් ප්‍රදේශවල සාමාන්‍ය කොළ හා ගෙඩි මෙන් දෙගුණයක් විශාල අරළු වගියක් තිබේ. මේ වගියේ කොළ දිග-පළල අඟල් 10 x 6 ක් පමණ ඇත. ගෙඩි ද තරමක රබිඩබ (ඉඳුන) පුවක් ගෙඩි පමණ ඇත.\n\nපිට රට වලින් මෙහි ගෙනැවිත් බෝ කරණ ලද ප්‍රමාණියෙන් විශාල ඇතැම් ගෙඩි වගී රට පුවක් - රට දෙල් - රට අඹ - රට අන්නාසි වශයෙන් හැඳින්වෙන්නාක් මෙන් ම මේ රටේ අරළු වලට වඩා ප්‍රමාණයෙන් විශාල මේ වගිය රට අරළු නමින් හැඳින්වීමි. පරික්‍ෂාකර බලා මේ වගිය වැවීමෙන් වැඩි ප්‍රයෝජනයක් ලබා ගත හැකි බැව් පාඨකයන් ඉදිරියේ තබමි.", 
        "category": "plant",
        "image": "img_392_rata_aralu.jpg"
    },

    // --- පිටුව 393 ---
    { "word": "රටතෝර", "meaning": "පරිප්පු, (තෝරවර්ගයක්)", "category": "plant" },
    { "word": "රටල", "meaning": "ඉන්නල, =(හිනිඅල=ඉතිඅල=ඉන්නල) මඤ්ඤොක්කා, රාජ අල, ගහල", "category": "plant" },
    { "word": "රටසිටඑන සුද්දා", "meaning": "සුදුළුණු අල", "category": "plant" },
    { "word": "රටහිවිල්ල කොළ", "meaning": "ඉවිල්ල =(ඉල්ල) කොළ (මෙය බුලත් වෙනුවට බුලත් විටට ත්, කැපුන් තුවාල වලට ත් ගන්නා අඳුරු සුදු පාටින් යුත් වාතහරබ හෝ රදලිය කොළ වැනි කොළ ඇති ගස් වගියකි. මේ වර්ගයේ ගස් අඩි පහළොහක් පමණ උසට වැවේ යි.", "category": "plant" },
    { "word": "රණ්ඩා", "meaning": "මීනුග, මුකුණුවැන්න", "category": "plant" },
    { "word": "රණ", "meaning": "උණ ගස", "category": "plant" },
    { "word": "රණඋණ", "meaning": "රණ උණ ගස, රන්වන් පාට ඇති උණ ගස් වගිය", "category": "plant" },
    { "word": "රණබට", "meaning": "බටගස් ජාතියක්", "category": "plant" },
    { "word": "රණබිජු", "meaning": "රණවරා ඇට", "category": "plant" },
    { "word": "රණප්‍රිය", "meaning": "සාතාවන්දරා", "category": "plant" },
    { "word": "රණහුණ", "meaning": "රන්වන් පාට හුණ ගස්", "category": "plant" },
    { "word": "රණ්ල", "meaning": "තිසර පෙරලිය", "category": "plant" },
    { "word": "රත්", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "රත්ඉඟුවැල්", "meaning": "රතු පාට හිඹුරු වැල්", "category": "plant" },
    { "word": "රත්එඬරු", "meaning": "රතු පැහැති එඬරු", "category": "plant" },
    { "word": "රත්කණේරු", "meaning": "ඔලියන්දර (රතු අලරිය)", "category": "plant" },
    { "word": "රත්කදුලැස්ස", "meaning": "රතුපාට කදුලැස්ස", "category": "plant" },
    { "word": "රත්කදුරු", "meaning": "රතුපාට කදුරු ගස්", "category": "plant" },
    { "word": "රත්කරව්", "meaning": "කණවේරිය ගස, (රක්ත කුරවක ගස=බිම්බජාල ගස)", "category": "plant" },
    { 
        "word": "රත්කිහිරිය", 
        "scientific": "Acacia Sundra",
        "meaning": "Acacia Sundra- රත් කිහිරිය - එළ කිහිරිය යයි කිහිරි වර්ග දෙකකි. මෙය ඉන්දියාව - බුරුමය - මලයාව ආදි රටවල වනගතව වැවෙන ගසකි. යකිනාරම් කටු වැනි උල්වගිය තියුණු කටු ඇති මේ ගසේ කොළ සිහින් ය, කිනිතිවල දෙපසට බෙදී ගිය නිදිකුම්බා කොළ වැනි සිහින් කොළ ඇති මේ ගස සාමාන්‍ය පෙනුමෙන් පතඟි ගසකට සමාන ය. මෙහි අරටුව ද පතඟි ලීයෙහි අරටුව මෙන් තද රත් පාහයෙන් යුක්ත ය. එළ කිහිරි හර (අරටුව) සුදු පාහයෙන් යුක්ත ය.", 
        "category": "plant",
        "image": "img_393_rathkihiriya.jpg"
    },

    // --- පිටුව 394 ---
    { 
        "word": "රත්කිහිරිය (ඉකිරිය)", 
        "meaning": "ඉස්තරම් වර්ගයේ කයිප්පු මේ වර්ගයේ අරටු කකාරා ගත් ජලය උකු කිරීමෙන් සෑදේ. රත් කිහිරිය වලින් සාදා ගන්නා කයිප්පු තද රත් (කළු)පාහයෙන් ත්, එළ කිහිරිය වලින් සාදා ගන්නා කයිප්පු කිලිටි සුදු පාහයෙනු ත් යුක්ත ය. වෙනත් ගොලා(පෙති) පුවක් ආදියෙන් සාදන බාල වගී වල කයිප්පු ද තිබේ.\n\nකිහිරි කයිප්පු හොඳ වගිය යි. එය උගුරේ බැරැන්ඩිය, විදුරුමස් වලින් ලේ සාරේ යාම, විදුරුමස් දියවීම යන මේ මුඛ රෝග වලට ප්‍රත්‍යක්‍ෂ ඖෂධයකි. මේ කිහිරි කයිප්පු වර්ගයෙන් කෑල්ලක් කටට දමා ගත් විට එය කපුරු වැනි සැර ගතියකින් යුක්ත ව වහා දියවී යයි. බාල කයිප්පුවල එවැනි ගතියක් නැත.\n\nකිහිරි අර වමීරෝග, කාමිරෝග, ලේ විෂවීම, කැල්ම, හා අතිසාර ආදි රෝග සුව කිරීමෙහි ශක්තියක් ඇති ඖෂධයකි. අපේ රටේ රත්හඳුන් වෙනුවට ගන්නේ මේ රත් කිහිරිය යි. (395 පිටේ රත්හඳුන් ගැන ලියා ඇති විස්තරය බලන්න.)", 
        "category": "plant" 
    },
    { "word": "රත්කොනොඹ", "meaning": "එරබදු", "category": "plant" },
    { "word": "රත්තිනි", "meaning": "කහපළු", "category": "plant" },
    { "word": "රත්ත", "meaning": "අත්තන", "category": "plant" },
    { "word": "රත්තා", "meaning": "සාදිලිංගම්, ලේ", "category": "mineral" },
    { "word": "රත්කක්කි", "meaning": "බලතණ", "category": "plant" },
    { "word": "රත්නකම්බිලිය", "meaning": "රත්මල් ගස", "category": "plant" },
    { "word": "රත්තගුල්ම", "meaning": "ගුල්මරෝග භෙදයක්", "category": "treatment" },
    { "word": "රත්නපල", "meaning": "කෝවක්කා", "category": "plant" },
    { "word": "රත්නඵල", "meaning": "කෙම්වැල් (කෝවක්කා)", "category": "plant" },
    { "word": "රත්නමනි", "meaning": "පියුම්රාමිණි", "category": "mineral" },
    { "word": "රත්තමෙහ", "meaning": "රක්තප්‍රමේහ", "category": "treatment" },
    { "word": "රත්තාතිසාර", "meaning": "රක්තඅතීසාරය", "category": "treatment" },
    { "word": "රත්කාරිසස්", "meaning": "ලේ වැගිරීම ඇති අගිස් රෝගය", "category": "treatment" },
    { "word": "රත්න", "meaning": "රුවන්", "category": "mineral" },
    { "word": "රත්නකැකුළ", "meaning": "පබළු", "category": "mineral" },
    { "word": "රත්නපාලම්", "meaning": "රටදුම්මල", "category": "mineral" },
    { "word": "රත්නික", "meaning": "රත්පාහැති නික", "category": "plant" },
    { "word": "රත්නිටුල්", "meaning": "රතුපාට මල් ඇති නිටුල් වගිය (277 පිටේ විස්තරය බලන්න.)", "category": "plant" },
    { "word": "රත් ගිමිනි", "meaning": "රක්ත උපෝදිකා", "category": "plant" },
    { "word": "රත්නිටුල්(2)", "meaning": "රක්ත චිත්‍රක", "category": "plant" },
    { "word": "රත්පති", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "රත්පල", "meaning": "නුගගස", "category": "plant" },
    { "word": "රත්පා", "meaning": "කූඩාවෝ", "category": "animal" },
    { "word": "රත්පොඩි", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "රක්බඳිනාවැල්", "meaning": "උගුරේ ලෙඩට ගන්නා බෙහෙතක් (වැල්මදට)", "category": "plant" },
    { "word": "රත්බියු", "meaning": "මදටිය", "category": "plant" },
    { "word": "රත්මල", "meaning": "රත් මල් ගස", "category": "plant" },
    { "word": "රත්මහනෙල්", "meaning": "රතු පාට ජලජ පුෂ්ප", "category": "plant" },
    { "word": "රක්මිණී", "meaning": "පද්මරාග", "category": "mineral" },
    { "word": "රත්ලොත්", "meaning": "කොකුම්", "category": "plant" },
    { "word": "රත්සැ ලුහුණු", "meaning": "රතුලූනු", "category": "plant" },
    { "word": "රත්හර", "meaning": "රත් හඳුන් ගස", "category": "plant" },
    { "word": "රත්හැල්", "meaning": "අග්‍ර ධාන්‍ය වූ රක්ත වර්ණ ඇල් වී ජාතිය", "category": "plant" },
    { "word": "රත්හිරියල්", "meaning": "මනෝසිල", "category": "mineral" },
    { "word": "රතඹලා", "meaning": "රත්මල් ගස", "category": "plant" },
    { "word": "රතාඹුල", "meaning": "රතු ඕලු, රත් මහනෙල්", "category": "plant" },
    { "word": "රති", "meaning": "මෛථුනය", "category": "general" }
];

