// data_459_470.js - පිටු 459 සිට 470 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 336
const data_extra_459_470 = [
   
    // --- පිටුව 459 ---
    { "word": "ශීතප්‍රිය", "meaning": "පැපිලිය", "category": "plant" },
    { "word": "ශීතඵල", "meaning": "දිවුල්", "category": "plant" },
    { "word": "ශීතබලා", "meaning": "මහවැල්මදට", "category": "plant" },
    { "word": "ශීතභානු", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතහිරු", "meaning": "නික, ඉද්ද, සිනිද්ද, වැල් ඉද්ද", "category": "plant" },
    { "word": "ශීතමංජරි", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "ශීතමුලින", "meaning": "අගිල්", "category": "plant" },
    { "word": "ශීතමුලිකා", "meaning": "සැවැන්න", "category": "plant" },
    { "word": "ශීතරජ", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතරශ්මි", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතල", "meaning": "මිලයටර සඳුන්, පැපිලිය, කොසඹ", "category": "plant" },
    { "word": "ශීතලක", "meaning": "සුදු උපුල්, තියද", "category": "plant" },
    { "word": "ශීතලච්ඡද", "meaning": "සපුගස", "category": "plant" },
    { "word": "ශීතල ඵල", "meaning": "මහනෙල්", "category": "plant" },
    { "word": "ශීතලා", "meaning": "සුදුබැබිල, කැකිරි, සඳුන්, සැවැන්න, අස්වැන්න, අන්දර, සපු, කපුරු, ගල්සෙවෙල්", "category": "plant" },
    { "word": "ශීතලාරභ", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතලාලය", "meaning": "එළ ජම්බු", "category": "plant" },
    { "word": "ශීතවල්කල", "meaning": "දිවුල්", "category": "plant" },
    { "word": "ශීත වල්ලභා", "meaning": "දිවුල්, බලුදම්, පාසි ලිය", "category": "plant" },
    { "word": "ශීතවිෂානි", "meaning": "පද්මිකාෂ්ඨ", "category": "plant" },
    { "word": "ශීතවිෂානිකා", "meaning": "ප්‍රමිල", "category": "plant" },
    { "word": "ශීතශිව", "meaning": "සවිඳව, උළුවා, කප්පර වල්ලිය, ලෝලු ගස, ශතපුෂ්ප", "category": "plant" },
    { "word": "ශීතසහා", "meaning": "කෝමාරිකා, පියා ගස, නිල් නික, යොහොඹු", "category": "plant" },
    { "word": "ශීතා", "meaning": "රතණ, මුරුවා, මහ බැබිල", "category": "plant" },
    { "word": "ශීතාභ්‍ර", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතාම්බි", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "ශීතානත", "meaning": "බෙලි", "category": "plant" },
    { "word": "ශීතානු", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශීතාර්ප", "meaning": "අළුතලා", "category": "plant" },
    { "word": "ශීතාර්පක", "meaning": "අළුතලා", "category": "plant" },
    { "word": "ශීනාවලා", "meaning": "මහ වැල්මදට", "category": "plant" },
    { "word": "ශීතිසාරක", "meaning": "නිඹිරි", "category": "plant" },
    { "word": "ශීනිපත්‍ර", "meaning": "කොසඹ, පට්ටිකා ලොත්, කින්හිරි ගස", "category": "plant" },
    { "word": "ශීනිපර්ණී", "meaning": "කොසඹ", "category": "plant" },
    { "word": "ශීනිපර්ණී", "meaning": "ඇත්දෙමට, කොසඹ, යොන් තුඹ", "category": "plant" },
    { "word": "ශීනිපුෂ්පී", "meaning": "ශතපුෂ්ප, තුඹ මල්", "category": "plant" },
    { "word": "ශීනිමාලා", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "ශීව", "meaning": "ගල්මද", "category": "mineral" },
    { "word": "ශීවශිව", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "ශිෂ", "meaning": "ජයම්", "category": "general" },
    { "word": "ශිෂක", "meaning": "ජයම්", "category": "general" },
    { "word": "ශුක්ල", "meaning": "රත්තිවුල්, ගිනි", "category": "plant" },
    { "word": "ශුක්ත", "meaning": "බෙල්ලා, කාඩි", "category": "mineral" },
    { "word": "ශුක්ති", "meaning": "සක්නැබ, මුතු බෙලි කටු, අභිෂ රෝගය, වක්නිය, තුරුක් තෙල්, අඩ පලම (කලං හය)", "category": "animal" },
    { "word": "ශුක්තිකා", "meaning": "මුතු බෙල්ලා, ඇඹුලැඹි ලිය", "category": "animal" },
    { "word": "ශුක්නිජ", "meaning": "ලූහුනු, මාරා, මුතු", "category": "plant" },
    { "word": "ශුක්නිශිලා", "meaning": "තුරුක් තෙල්", "category": "mineral" },
    { "word": "ශුක්ති භනු", "meaning": "වක්නිය", "category": "anatomy" },
    { "word": "ශුක්ති-සක්නැබ", "meaning": "තුරුක් තෙල්, වක්නිය, මුතු, මුතුබෙලි කටු", "category": "animal" },
    { "word": "ශුක්‍ර", "meaning": "ශුක්ල ධාතුව, රත් තිවුල්, ගින්න", "category": "anatomy" },
    { "word": "ශුක්‍රප්‍රමාතා", "meaning": "සිරිත්කේකු", "category": "plant" },
    { "word": "ශුක්‍රමේහ", "meaning": "ප්‍රමේහ රෝග විශේෂයක්", "category": "treatment" },
    { "word": "ශුක්‍රලා", "meaning": "මීනුගස, මාරා ගස, ඔලිඳ", "category": "plant" },
    { "word": "ශුක්‍රශුම්භා", "meaning": "අරළු ගස", "category": "plant" },
    { "word": "ශුක්‍යල", "meaning": "වරා, එරඬු, කොඳ, වසාවාසි, රිදී, වෙබරු, ශුක්ල ධාතුව", "category": "plant" },
    { "word": "ශුක්ලක", "meaning": "ත්‍රස්තාවළු, හෙළ ලූනු", "category": "plant" },

    // --- පිටුව 460 ---
    { "word": "ශුක්ලකන්‍ද", "meaning": "අතිවිඩයන්, හෙළ ලූනු", "category": "plant" },
    { "word": "ශුක්ලකන්‍ධ", "meaning": "අතිවිඩයන්, හෙළ ලූනු", "category": "plant" },
    { "word": "ශුක්ලගන්‍ධා", "meaning": "අතිවිඩයන්, හෙළ ලූනු", "category": "plant" },
    { "word": "ශුක්ලගන්‍ධිකා", "meaning": "ත්‍රස්තාවළු", "category": "plant" },
    { "word": "ශුක්ලදන්‍ධ", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "ශුක්ලධාතු", "meaning": "ශුක්ල (ධාතු), එලබටු", "category": "anatomy" },
    { "word": "ශුක්ලපුෂ්ප", "meaning": "කුකුරුමාන්, මහ ගොන් සුදු කැකිරි, කොඳගස, අරත්ත", "category": "plant" },
    { "word": "ශුක්ලපුෂ්පා", "meaning": "අඩතහිරියා", "category": "plant" },
    { "word": "ශුක්ලපුෂ්පිකා", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "ශුක්ලපාදක", "meaning": "නික ගස", "category": "plant" },
    { "word": "ශුක්ලඵලා", "meaning": "වරා ගස", "category": "plant" },
    { "word": "ශුක්ලමර්ෂි", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "ශුක්ලා", "meaning": "ඔලිඳ", "category": "plant" },
    { "word": "ශුක්ලවචා", "meaning": "හෙළ වද, සුවඳ කස්සා", "category": "plant" },
    { "word": "ශුක්ලවාක්‍ෂ", "meaning": "දුව ගස", "category": "plant" },
    { "word": "ශුක්ලශාල", "meaning": "කොසඹ ගස, තල් ගස", "category": "plant" },
    { "word": "ශුක්ලා", "meaning": "සිනි, කවෙළු, කිරිබදු, දක්, වැල් පෙනෙල", "category": "plant" },
    { "word": "ශුසලාධිනි", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "ශුක්ලාශා", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "ශුක්ලාභා", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "ශුක්ලොපලා", "meaning": "සීනි", "category": "food" },
    { "word": "ශුක", "meaning": "තොටිල", "category": "plant" },
    { "word": "ශුකච්ඡද", "meaning": "විෂ්ණුක්‍රාන්තී", "category": "plant" },
    { "word": "ශුකතරු", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ශුකතුණ්ඩ", "meaning": "ඉඟුල්, (හිඟුල් = සාදිලිංගම්)", "category": "mineral" },
    { "word": "ශුකනාස", "meaning": "දද, තොටිල", "category": "plant" },
    { "word": "ශුකභිණ්ඩි", "meaning": "වඳුරු මෑ, (ප්‍රධාන වාජී කරණ ඖෂධයකි)", "category": "plant" },
    { "word": "ශුකපුෂ්ප", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ශුකප්‍රිය", "meaning": "මාරා ගස, ජම්බු, කොසඹ", "category": "plant" },
    { "word": "ශුකඵල", "meaning": "වරා ගස", "category": "plant" },
    { "word": "ශුකරකාන්තා", "meaning": "බිමිතල්, ඌරල", "category": "plant" },
    { "word": "ශුකරෙෂ්ටා", "meaning": "කෙකටිය අල", "category": "plant" },
    { "word": "ශුකල", "meaning": "වරා ගස", "category": "plant" },
    { "word": "ශුකවල්ලභ", "meaning": "දෙළුම් ගස", "category": "plant" },
    { "word": "ශුකශිම්බා", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "ශුකසිම්බි", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "ශුකාක්‍රිඩා", "meaning": "මහරි, මදටිය", "category": "plant" },
    { "word": "ශුකාදන", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "ශුකාශ", "meaning": "වැල්තුඹ", "category": "plant" },
    { "word": "ශුකෝදර", "meaning": "තලිස් පතුරු", "category": "plant" },
    { "word": "ශුචි", "meaning": "රත් තිවුල්, කකීටක ශෘංගි", "category": "plant" },
    { "word": "ශුචිද්‍රැම", "meaning": "ඇසටු ගස", "category": "plant" },
    { "word": "ශුචිපර්ණී", "meaning": "හෙළ නෙළුම්", "category": "plant" },
    { "word": "ශුචිපර්ණිකා", "meaning": "සුදු නෙළුම්", "category": "plant" },
    { "word": "ශුචි මල්ලිකා", "meaning": "සිනිද්ද", "category": "plant" },
    { "word": "ශුණ්ඨි", "meaning": "සිද්ධිගුරු", "category": "plant" },
    { "word": "ශුණ්ඨ්‍යා", "meaning": "සිද්ධිගුරු", "category": "plant" },
    { "word": "ශුණ්ඩා", "meaning": "සුරා", "category": "liquid" },
    { "word": "ශුදරාවර්ධන", "meaning": "කොබොලීල ගස", "category": "plant" },
    { "word": "ශුද්ධ", "meaning": "සවිඳව ලුණු, මිරිස්", "category": "plant" },
    { "word": "ශුද්ධවල්ලී", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "ශුධා", "meaning": "අමුක්කරා, සිනුක්", "category": "plant" },
    { "word": "ශුති", "meaning": "කොම්බු පුහුල්", "category": "plant" },
    { "word": "ශුභ", "meaning": "පද්මකාෂ්ඨ", "category": "plant" },
    { "word": "ශුනද", "meaning": "ඇසටු ගස", "category": "plant" },
    { "word": "ශුභපත්‍රිකා", "meaning": "ශාලිපර්ණී", "category": "plant" },
    { "word": "ශුභා", "meaning": "ගෝරෝචන, පුවඟු, උණකපුරු, සුදු රතණ", "category": "plant" },
    { "word": "ශුභාඤ්ජන", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "ශුභ්‍ර", "meaning": "රසදිය, මිණිරන්, රිදී, කසිස්, සඳුන්", "category": "mineral" },
    { "word": "ශුභ්‍රකර", "meaning": "කපුරු", "category": "plant" },
    { "word": "ශුම්භි", "meaning": "කටරොළු", "category": "plant" },
    { "word": "ශුරණ", "meaning": "කිඩාරම්", "category": "plant" },
    { "word": "ශුල්බ", "meaning": "තඹ", "category": "mineral" },
    { "word": "ශුල්ල", "meaning": "තඹ", "category": "mineral" },
    { "word": "ශුල්ව", "meaning": "තඹ", "category": "mineral" },
    { "word": "ශුල්වාරි", "meaning": "ගෙන්දගම්", "category": "mineral" },


    // --- පිටුව 461 ---
    { "word": "ශූලහත්", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "ශූලිනී", "meaning": "රසතැල්", "category": "plant" },
    { "word": "ශුෂ්කගොමය", "meaning": "ගොම වැරටි", "category": "plant" },
    { "word": "ශුෂ්කයොබාදිප්", "meaning": "මුදුපෙණ", "category": "plant" },
    { "word": "ශුෂ්ක ඵල", "meaning": "වියලි ගෙඩි", "category": "plant" },
    { "word": "ශුෂ්කල", "meaning": "මස්", "category": "animal" },
    { "word": "ශුෂ්ක වෘක්‍ෂ", "meaning": "යවගස", "category": "plant" },
    { "word": "ශුෂ්කා", "meaning": "මුදු පෙණ", "category": "plant" },
    { "word": "ශුෂ්කාංග", "meaning": "යව ගස, ගුරු", "category": "plant" },
    { "word": "ශුෂ්කාද්‍ර", "meaning": "ඉඟුරු", "category": "plant" },
    { "word": "ශුෂ්කාද්‍ර (2)", "meaning": "වියලි ඉඟුරු", "category": "plant" },
    { "word": "ශුෂ්මන්", "meaning": "රත්නිටුල්", "category": "plant" },
    { "word": "ශුශිරා", "meaning": "පබළු", "category": "mineral" },
    { "word": "ශූක ශිඛා", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ශූකච්ඡද", "meaning": "ගරුකත, විෂ්ණුක්‍රාන්තී", "category": "plant" },
    { "word": "ශූකතරු", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ශූකතුණ්ඩ", "meaning": "සාදිලිංගම්", "category": "mineral" },
    { "word": "ශූකධාන්‍ය", "meaning": "යවාදි ධාන්‍ය", "category": "plant" },
    { "word": "ශූකනාසිකා", "meaning": "තොටිල", "category": "plant" },
    { "word": "ශූකපිණ්ඩි", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "ශූකපුෂ්ප", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ශූකපුෂ්ප (2)", "meaning": "විෂ්ණුක්‍රාන්තී, මාරාගස", "category": "plant" },
    { "word": "ශූකප්‍රිය", "meaning": "ජම්බු", "category": "plant" },
    { "word": "ශූකප්‍රියා", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "ශූකර කන්‍ද", "meaning": "බිමිතල්", "category": "plant" },
    { "word": "ශූකර මදාව", "meaning": "සූකර මද්දව (ඌරු හතු)", "category": "plant" },
    { "word": "ශූකරකාන්තා", "meaning": "බිමිතල්", "category": "plant" },
    { "word": "ශූකරී", "meaning": "බිමිතල්", "category": "plant" },
    { "word": "ශූකරෙෂ්ට", "meaning": "කෙකටිය අල", "category": "plant" },
    { "word": "ශූකවන්තී", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "ශූකවල්ලභා", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "ශූකවෘක්‍ෂ", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ශූකශිම්බා", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "ශූකශිම්බි", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "ශූකස්ථාන", "meaning": "වරා ගස", "category": "plant" },
    { "word": "ශූකා", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "ශූකාදන", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "ශූකාස", "meaning": "වැල්තුඹ", "category": "plant" },
    { "word": "ශූකාහ්වය", "meaning": "වැල් තුඹ", "category": "plant" },
    { "word": "ශූකෝදර", "meaning": "තලිස්පතුරු", "category": "plant" },
    { "word": "ශූද්‍රප්‍රිය", "meaning": "ලූහුනු", "category": "plant" },
    { "word": "ශූද්‍රානී", "meaning": "පුවඟු", "category": "plant" },
    { "word": "ශූන්‍යා", "meaning": "මහ කටුවැල් බටු", "category": "plant" },
    { "word": "ශූර", "meaning": "රක්නෙළුල්, සල්, සල්ගස, මිදෙල්ල ගස", "category": "plant" },
    { "word": "ශූරණ", "meaning": "තොටිල, කිඩාරම්", "category": "plant" },
    { "word": "ශූලගහනී", "meaning": "මල් රතණ", "category": "plant" },
    { "word": "ශූලඝන", "meaning": "කොත්තමල්ලි", "category": "plant" },
    { "word": "ශූලසාතන", "meaning": "යකඩ බොර", "category": "mineral" },
    { "word": "ශූලදිප්", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "ශූලනාශන", "meaning": "සුවස ලුණු", "category": "mineral" },
    { "word": "ශූලනෘතා", "meaning": "එරබු", "category": "plant" },
    { "word": "ශූලනන්තිය", "meaning": "අසමෝද", "category": "plant" },
    { "word": "ශූලහත් (2)", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "ශූලිකා", "meaning": "මාරා ගස", "category": "plant" },
    { "word": "ශූලිනී (2)", "meaning": "රසතැල්", "category": "plant" },
    { "word": "ශූලොත්බා", "meaning": "බෝදි ඇට", "category": "plant" },
    { "word": "ශෘගාලඝණ්ටී", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "ශෘගාල ජම්බු", "meaning": "මහ ගොන් කැකිරි", "category": "plant" },
    { "word": "ශෘගාලවින්නා", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "ශෘගාලවානනා", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "ශෘගාලිකා", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "ශෘංග", "meaning": "අඟ, ජීවක, කදුරු ගස", "category": "plant" },
    { "word": "ශෘංගක", "meaning": "දුරු ගස", "category": "plant" },
    { "word": "ශෘංගකන්‍ද", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "ශෘංගප්", "meaning": "හොර ගස, අගිල්, සඳුන්", "category": "plant" },
    { "word": "ශෘංගනාමිණී", "meaning": "කකීටකශෘංගි", "category": "plant" },
    { "word": "ශෘංගබෙර", "meaning": "අමු ඉඟුරු", "category": "plant" },
    { "word": "ශෘංගමූල", "meaning": "ඉකිරි", "category": "plant" },

    // --- පිටුව 462 ---
    { "word": "ශෘංගමොහිනි", "meaning": "සපු ගස", "category": "plant" },
    { "word": "ශෘංගලා", "meaning": "මැඩහඟු", "category": "plant" },
    { "word": "ශෘංගලි", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "ශෘංගවේර", "meaning": "අමු ඉඟුරු", "category": "plant" },
    { "word": "ශෘංගාට", "meaning": "කිරිබදු", "category": "plant" },
    { "word": "ශෘංගාටක", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "ශෘංගාර", "meaning": "කුරුදු, කච්චාල්, සින්දුරම්", "category": "plant" },
    { "word": "ශෘංගාරභූෂණ", "meaning": "සින්දූරම්", "category": "mineral" },
    { "word": "ශෘංගාරින්", "meaning": "පුවක්", "category": "plant" },
    { "word": "ශෘංගාලවින්නා", "meaning": "පුස්වැන්න", "category": "plant" },
    { "word": "ශෘංගිකා", "meaning": "ජීවක", "category": "plant" },
    { "word": "ශෘංගි", "meaning": "වාෂහක, කකීටකශෘංගි, අතිවුඩයන්, ගප්පිප්පිලි", "category": "plant" },
    { "word": "ශෘංගාවාක්‍ෂ", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "ශෙබර", "meaning": "කරාබුනැටි", "category": "plant" },
    { "word": "ශෙබරිකා", "meaning": "ගෝරෝචන, කරල්සැබෝ", "category": "plant" },
    { "word": "ශෙපාලිකා", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "ශෙවාලිකා", "meaning": "නික ගස, සේපාලිකා ගස", "category": "plant" },
    { "word": "ශෙවාලි", "meaning": "සේපාලිකා", "category": "plant" },
    { "word": "ශෙලු", "meaning": "ලෝලු ගස", "category": "plant" },
    { "word": "ශෙවල", "meaning": "පෙද (දියසෙවෙල්)", "category": "plant" },
    { "word": "ශෙවාල", "meaning": "පෙද (දියසෙවෙල්)", "category": "plant" },
    { "word": "ශෙෂණ", "meaning": "තොටිල", "category": "plant" },
    { "word": "ශෙෂසම්භව", "meaning": "නිප්පිලි මුල්", "category": "plant" },
    { "word": "ශෛබරිකා", "meaning": "සැබෝ", "category": "plant" },
    { "word": "ශෛබරය", "meaning": "සැබෝ", "category": "plant" },
    { "word": "ශෛහාක්‍ෂන", "meaning": "රතුමුරුංගා", "category": "plant" },
    { "word": "ශෛයසීක", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "ශෛයසී", "meaning": "සාදික්කා", "category": "plant" },
    { "word": "ශෛරීයන", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "ශෛරී", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "ශෛල", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශෛලක", "meaning": "පෙද", "category": "plant" },
    { "word": "ශෛලගන්ධ", "meaning": "සබර, සඳුන්", "category": "plant" },
    { "word": "ශෛලප්", "meaning": "ගල්සෙවෙල්, රසඳුන්, ගප්පිප්පිලි", "category": "mineral" },
    { "word": "ශෛලනිය‍්‍යාස", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශෛලපත්‍ර", "meaning": "බෙලිගස, කප්පරවල්ලිය", "category": "plant" },
    { "word": "ශෛලපර්ණිකා", "meaning": "සින්අරත්ත", "category": "plant" },
    { "word": "ශෛලවිප්", "meaning": "බදුල්ල", "category": "plant" },
    { "word": "ශෛලසාර", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශෛලාප්", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "ශෛලාට", "meaning": "බිම්කොසඹ, සුදුපාට ලෝකඩ", "category": "mineral" },
    { "word": "ශෛලිකා", "meaning": "ලෝලු ගස", "category": "plant" },
    { "word": "ශෛලූ", "meaning": "ලෝලු ගස", "category": "plant" },
    { "word": "ශෛලූක", "meaning": "ලෝලු ගස", "category": "plant" },
    { "word": "ශෛලූෂ", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "ශෛලෙයප්", "meaning": "කරගස", "category": "plant" },
    { "word": "ශෛලෙය", "meaning": "කප්පරවල්ලිය, ගල්සෙවෙල්, ගල්නහර", "category": "plant" },
    { "word": "ශෛලොත්භවා", "meaning": "හින්පොල්පලා", "category": "plant" },
    { "word": "ශෛව", "meaning": "පෙද, අත්තන", "category": "plant" },
    { "word": "ශෛවල", "meaning": "පෙද, පොණඩරු", "category": "plant" },
    { "word": "ශෛවාල", "meaning": "පෙද, (දියසෙවෙල්)", "category": "plant" },
    { "word": "ශොකනාග", "meaning": "හෝපළු, අශෝක", "category": "plant" },
    { "word": "ශොකහර්තා", "meaning": "හෝපළු, අශෝක", "category": "plant" },
    { "word": "ශොකහාරී", "meaning": "වල් අදුතලා", "category": "plant" },
    { "word": "ශොකා", "meaning": "කටුකරඬු", "category": "plant" },
    { "word": "ශොකාරී", "meaning": "බක්මී, කොළොම්", "category": "plant" },
    { "word": "ශොණිෂ්කෙශ", "meaning": "ගිත්ත, රත්නිටුල්", "category": "plant" },
    { "word": "ශොණ", "meaning": "වරා, සින්දූරම්, ලේ, රත්උක්, රත්නිටුල්, තොටිල", "category": "plant" },
    { "word": "ශොණක", "meaning": "තොටිල", "category": "plant" },
    { "word": "ශොණකිණිටිකා", "meaning": "රත් කටුකරඬු", "category": "plant" },
    { "word": "ශොණකිණිටි", "meaning": "කටුවැල්බටු", "category": "plant" },

    // --- පිටුව 463 ---
    { "word": "ශොණනාඩිෂ", "meaning": "ජයපාල ගස", "category": "plant" },
    { "word": "ශොණපත්‍ර", "meaning": "රතුසාරණ", "category": "plant" },
    { "word": "ශොණ පුෂ්පක", "meaning": "කොබෝලීල", "category": "plant" },
    { "word": "ශොණ පුෂ්පී", "meaning": "එරබදු ගස", "category": "plant" },
    { "word": "ශොණඵලිනී", "meaning": "තැල්වැල්", "category": "plant" },
    { "word": "ශොණාක", "meaning": "තොටිල", "category": "plant" },
    { "word": "ශොණාලු", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ශොණිත", "meaning": "ලේ, හුරිර", "category": "anatomy" },
    { "word": "ශොණිත චන්දන", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "ශොණීඵල", "meaning": "මාණික්‍ය", "category": "mineral" },
    { "word": "ශොප්ස්නී", "meaning": "ශාලිපර්ණී", "category": "plant" },
    { "word": "ශොධන", "meaning": "බුලත්, බෙරු, කොසඹ, කුරුඳු", "category": "plant" },
    { "word": "ශොධනායිස", "meaning": "ජයපාල", "category": "plant" },
    { "word": "ශොඵ", "meaning": "ඉදිමුම", "category": "treatment" },
    { "word": "ශොඵකාරක", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "ශොඵඝන", "meaning": "යක්බේරිය", "category": "plant" },
    { "word": "ශොඵඝනී", "meaning": "සාරණ, මේවන්, අස්වැන්න", "category": "plant" },
    { "word": "ශොඵජිත්", "meaning": "සාරණ", "category": "plant" },
    { "word": "ශොඵජිත්ව", "meaning": "සාරණ", "category": "plant" },
    { "word": "ශොඵනාශන", "meaning": "බෙරු, යක්බේරිය", "category": "plant" },
    { "word": "ශොඵහත්", "meaning": "බදුල්ල ගස", "category": "plant" },
    { "word": "ශොහන", "meaning": "නෙල්ලි", "category": "plant" },
    { "word": "ශොහනක", "meaning": "මුරුංගා", "category": "plant" },
    { "word": "ශොහනා", "meaning": "කහ, ගෝරෝචන", "category": "plant" },
    { "word": "ශොහාඤ්ජන", "meaning": "මුරුංගා, රත්මුරුංගා", "category": "plant" },
    { "word": "ශොමරාප්", "meaning": "බෝදිඇට, කපුරුවිල", "category": "plant" },
    { "word": "ශොමරාප් (2)", "meaning": "බෝදිඇට, (සන්නිනායත්)", "category": "plant" },
    { "word": "ශොමලතා", "meaning": "බෝදි ඇට, මුවකිරිය", "category": "plant" },
    { "word": "ශොමවල්කල", "meaning": "එළකිරි, බෝදිඇට", "category": "plant" },
    { "word": "ශොමවල්ලි", "meaning": "මුවකිරිය", "category": "plant" },
    { "word": "ශොමවාක්‍ෂ", "meaning": "මාරාගස, මදටගස", "category": "plant" },
    { "word": "ශොෂණ", "meaning": "රස අනුභව කිරීම", "category": "general" },
    { "word": "ශොෂසම්භව", "meaning": "නිප්පිලි මුල්", "category": "plant" },
    { "word": "ශෞක්තිකෙය", "meaning": "මුතු", "category": "mineral" },
    { "word": "ශෞකරී", "meaning": "බින්තල්", "category": "plant" },
    { "word": "ශෞබපා", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "ශෞගන්ධික", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "ශෞණඩී", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "ශෞණඩී (2)", "meaning": "ගප්පිප්පිලි", "category": "plant" },
    { "word": "ශ්මශාන", "meaning": "සොහොන", "category": "general" },
    { "word": "ශ්මශ්‍රැ", "meaning": "රැවුල", "category": "anatomy" },
    { "word": "ශ්‍යාද්‍රන", "meaning": "කෝන්ගස", "category": "plant" },
    { "word": "ශ්‍යාද්‍රනී", "meaning": "කෙල", "category": "plant" },
    { "word": "ශ්‍යාම", "meaning": "අත්තන, නුග, මිරිස්, ගිරිතිල්ල, කුඹුක්, ඉඟිනිඇට, බොඩ අමු, තණ, සවිඳව ලුණු", "category": "plant" },
    { "word": "ශ්‍යාමකඤ්ජ", "meaning": "අතිවුඩයන්", "category": "plant" },
    { "word": "ශ්‍යාමකණ්ඨා", "meaning": "ගබරතණ", "category": "plant" },
    { "word": "ශ්‍යාමකාරක", "meaning": "කිහිරි", "category": "plant" },
    { "word": "ශ්‍යාමගන්ධිකා", "meaning": "අතිවුඩයන්", "category": "plant" },
    { "word": "ශ්‍යාමග්‍රන්ථි", "meaning": "ගබරතණ", "category": "plant" },
    { "word": "ශ්‍යාමදර්ශන", "meaning": "ඉළුක්", "category": "plant" },
    { "word": "ශ්‍යාමපත්‍ර", "meaning": "කොල්ලම් කොළ", "category": "plant" },
    { "word": "ශ්‍යාමභව", "meaning": "දේවදාර", "category": "plant" },
    { "word": "ශ්‍යාමභූෂණ", "meaning": "මිරිස්", "category": "plant" },
    { "word": "ශ්‍යාමල", "meaning": "කළුනිප්පිලි, පුලිල, මහ කපු, ජම්බු, කස්තුරි, අමුක්කරා", "category": "plant" },
    { "word": "ශ්‍යාමලවෘඬා", "meaning": "ඔලිඳ", "category": "plant" },
    { "word": "ශ්‍යාමලතු", "meaning": "කළු හිරමුසු", "category": "plant" },
    { "word": "ශ්‍යාමලිකා", "meaning": "බෙරු (තණ විශේෂයකි)", "category": "plant" },
    { "word": "ශ්‍යාමවර්ණ", "meaning": "මාරාගස", "category": "plant" },


//පිටු 464 සිට 466 දක්වා සියලුම වචන සහ විස්තර
// සම්පූර්ණ වචන සංඛ්‍යාව: 131
 // --- පිටුව 464 ---
    { "word": "ශ්‍යාමා", "meaning": "මෙමින්, රසකිඳ, කස්තුරි, බෙරු, ඉන්සළු, ඉරමුසු, ගුගුල්, බෝදිඇට, පිළිල, කළුත්‍රස්තාවාලු, වැල්පෙනෙල, නිල්සාරණ, නිප්පිලි, කහ, නිල්තලා, නෙළුම් ඇට, ඇට්ටර, කිරිඳි, ත්‍රස්තාවාලු, පුවඟු, නිල්රතණ, නුග කොළ, මකුණුවැන්න", "category": "plant" },
    { "word": "ශ්‍යාමාදිගණය", "meaning": "පෝටා, දත්ත, මී නුග, සිනුක්, තිරස්තවාළු, රසකිඳ, දසමන් හෝ දුමිතීරිය, වැල්දෙහි, එළකටරොළු, ඇසළ, හෙළකිරිය, කුඩුවෙලඟ, කරඳ, රත්කිරිගොකටු යන මේ ශ්‍යාමාදි ගණය කෙම උදාවතී-උදර-බඩපිපිම-විෂ-ගුල්ම යන මේ රෝග නසන්නේය.", "category": "compound" },
    { "word": "ශ්‍යාමාක", "meaning": "බොධහමු", "category": "plant" },
    { "word": "ශ්‍යාමව", "meaning": "ඇසළ", "category": "plant" },
    { "word": "ශෙයනසණිතා", "meaning": "දත්ත", "category": "plant" },
    { "word": "ශෙයාණක", "meaning": "තොටිල ගස", "category": "plant" },
    { "word": "ශ්‍රංසන", "meaning": "පියාගස", "category": "plant" },
    { "word": "ශ්‍රංහන", "meaning": "පියාගස", "category": "plant" },
    { "word": "ශ්‍රද්ධා", "meaning": "රත්කණේරු", "category": "plant" },
    { "word": "ශ්‍රබස්කා", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "ශ්‍රමණාහ්වය / ශ්‍රමණී", "meaning": "මුඩමහණ, ජටාමාංශ", "category": "plant" },
    { "word": "ශ්‍රව", "meaning": "කණ", "category": "anatomy" },
    { "word": "ශ්‍රවණ", "meaning": "කණ, දත්ත ගස", "category": "general" },
    { "word": "ශ්‍රවතී", "meaning": "නියද, ගෙද", "category": "plant" },
    { "word": "ශ්‍රවන්දු", "meaning": "සුදුදඹකලත්", "category": "plant" },
    { "word": "ශ්‍රවනා", "meaning": "සියඹලා ගස, දත්ත ගස", "category": "plant" },
    { "word": "ශ්‍රවන්තී", "meaning": "මුකුණුවැන්න, ගෙද", "category": "plant" },
    { "word": "ශ්‍රවා", "meaning": "මුරුවා", "category": "plant" },
    { "word": "ශ්‍රාණා", "meaning": "යවකාද්‍ර", "category": "plant" },
    { "word": "ශ්‍රාර්‍දව නිය‍්‍යාස", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "ශ්‍රාර්‍දවශාක", "meaning": "කරපිංචා ගස", "category": "plant" },
    { "word": "ශ්‍රාවණො", "meaning": "තුන්පත්කුරුඳු", "category": "plant" },
    { "word": "ශ්‍රාවනශීර්ෂක", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "ශ්‍රාවන්තී", "meaning": "මිදි ගස, මීනුග, සුලුදඹ කලත්", "category": "plant" },
    { "word": "ශ්‍රිංසි", "meaning": "පියාගස", "category": "plant" },
    { "word": "ශ්‍රීකාර", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "ශ්‍රීගාලඝණ්ට", "meaning": "ඉකිරි", "category": "plant" },
    { "word": "ශ්‍රීසාදවච", "meaning": "අඹ", "category": "plant" },
    { "word": "ශ්‍රීවගක", "meaning": "ජීවක", "category": "plant" },
    { "word": "ශ්‍රීවගිකා", "meaning": "අගිල්, අතිවුඩයන්, කකීටකශෘංගි", "category": "plant" },
    { "word": "ශ්‍රීවගිනී", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "ශ්‍රීවහිබෙර", "meaning": "අමුඉඟුරු, යක්බේරිය", "category": "plant" },
    { "word": "ශ්‍රීවහිබෙරකමූල", "meaning": "හණගස", "category": "plant" },
    { "word": "ශ්‍රීබිනී", "meaning": "ජීවක, වෘෂහක, අතිවුඩයන්, කකීටකශ්‍රීගි, ඇසටු, (නුග)", "category": "plant" },
    { "word": "ශ්‍රීවගිරිකා", "meaning": "කිරිපලා", "category": "plant" },
    { "word": "ශ්‍රී", "meaning": "හඳුන්, බෙලි ගස, කරාබු නැටි, කොකුම්", "category": "plant" },
    { "word": "ශ්‍රීකණ්ඨ", "meaning": "සඳුන්", "category": "plant" },
    { "word": "ශ්‍රීකණ්ඩිය", "meaning": "සඳුන්", "category": "plant" },
    { "word": "ශ්‍රීකන්දු", "meaning": "විල් බෙබර", "category": "plant" },
    { "word": "ශ්‍රීකර", "meaning": "රත් මහනෙල්, නෙළුම් මුරාත, නිල් මහනෙල්, බුලත්, රතුපුල්", "category": "plant" },
    { "word": "ශ්‍රීකරී", "meaning": "හෙළ සැබෝ, බුලත්, ඉරිවේරිය", "category": "plant" },
    { "word": "ශ්‍රීකාන්ත", "meaning": "සල් ගස", "category": "plant" },
    { "word": "ශ්‍රීඛණ්ඩ", "meaning": "සුදු හඳුන්", "category": "plant" },

    // --- පිටුව 465 ---
    { "word": "ශ්‍රීගෙහ", "meaning": "සුදු නෙළුම්", "category": "plant" },
    { "word": "ශ්‍රීතලා", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "ශ්‍රීද්‍රහ්වය / ශ්‍රීද්‍රම", "meaning": "බෙලි ගස", "category": "plant" },
    { "word": "ශ්‍රීධර", "meaning": "තලා ගස", "category": "plant" },
    { "word": "ශ්‍රීනිකෙත", "meaning": "රත් මහනෙල්", "category": "plant" },
    { "word": "ශ්‍රීනිර්ගුණ්ඨි", "meaning": "කළුතලා", "category": "plant" },
    { "word": "ශ්‍රීනිවාස", "meaning": "සිරිවඩු", "category": "plant" },
    { "word": "ශ්‍රීපර්ණී", "meaning": "නෙළුම්, මිදි, තොටිල", "category": "plant" },
    { "word": "ශ්‍රීපර්ණිභ", "meaning": "නවසාරන්", "category": "mineral" },
    { "word": "ශ්‍රීපර්ණිකා", "meaning": "කරබෙහිය ගස, පුස්වැන්න, ඇත්දෙමට", "category": "plant" },
    { "word": "ශ්‍රීපර්ණී (2)", "meaning": "ඇත්දෙමට, අස්වැන්න, ඉඹුල්, සින් මිදි, තොටිල", "category": "plant" },
    { "word": "ශ්‍රීපල්ලව", "meaning": "කරාබු", "category": "plant" },
    { "word": "ශ්‍රීපුෂ්ප", "meaning": "කරාබුනැටි, නෙළුම්බඩිටා", "category": "plant" },
    { "word": "ශ්‍රී පුසුනක", "meaning": "කරාබු නැටි", "category": "plant" },
    { "word": "ශ්‍රීප්‍රිය", "meaning": "සුදු හඳුන්", "category": "plant" },
    { "word": "ශ්‍රීඵල", "meaning": "නෙල්ලි, ඇත්දෙමට, බෙලි, කිරිපළු, ඉඳි, බෙරු", "category": "plant" },
    { "word": "ශ්‍රීඵලිකාකීර්ති / ශ්‍රීඵලී", "meaning": "බෙරු, අවරිය", "category": "plant" },
    { "word": "ශ්‍රීභද්‍රා", "meaning": "කලාදුරු", "category": "plant" },
    { "word": "ශ්‍රීමන්", "meaning": "හෝපළු, සින්දූරම්, මදට ගස", "category": "plant" },
    { "word": "ශ්‍රීමනී", "meaning": "මුඩමහණ, යොන්තුඹ", "category": "plant" },
    { "word": "ශ්‍රීමලාපහා", "meaning": "දුම්කොළ", "category": "plant" },
    { "word": "ශ්‍රීමහාඵල", "meaning": "බෙලි ගස", "category": "plant" },
    { "word": "ශ්‍රීමාන්", "meaning": "ගුගුල්, මාරා, වෘෂහක, තෙල ගස, සින්දූරම්, කහ", "category": "plant" },
    { "word": "ශ්‍රීලතා", "meaning": "මය දුදු වැල", "category": "plant" },
    { "word": "ශ්‍රීවාස", "meaning": "දේවදාර, සිරිවඩු, සල් දුම්මල", "category": "plant" },
    { "word": "ශ්‍රීවාසක", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "ශ්‍රීවිහුෂණ", "meaning": "සක්", "category": "animal" },
    { "word": "ශ්‍රීවිරො", "meaning": "සාමහක", "category": "plant" },
    { "word": "ශ්‍රීවෘක්‍ෂ", "meaning": "ඇසටු", "category": "plant" },
    { "word": "ශ්‍රීවෙෂ්ට", "meaning": "සිරිවටු=(සරලදව=වාකාඩ්‍රප)", "category": "plant" },
    { "word": "ශ්‍රීවෙෂ්ටක", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "ශ්‍රීසංඝ", "meaning": "බෙලි ගස", "category": "plant" },
    { "word": "ශ්‍රීසාදවච", "meaning": "අඹ", "category": "plant" },
    { 
        "word": "ශ්‍රීහසතිනී", 
        "scientific": "Heliotropium Indicum",
        "meaning": "ඇත්සොඩ. රවල කොළ වලට සමාන කොළ හා ඇත් සොඬක් වැනි දිග නතුවක සුදු පැහැති මල් හට ගන්නා වැසි වශයෙන් වෙල් වල වැවෙන අඩි එකහමාරක් පමණ උස ඇති පැලෑටියකි. මෙය ඇත්සැටිය නමින් ද ඇතැම් අය හඳුන්වති.", 
        "category": "plant",
        "image": "img_9f2709_shrihasathini.jpg"
    },

    // --- පිටුව 466 ---
    { "word": "ශ්‍රෙණී", "meaning": "මුදි ගස, දත්ත", "category": "plant" },
    { "word": "ශ්‍රෙය", "meaning": "රත්කල", "category": "plant" },
    { "word": "ශ්‍රෙයසී", "meaning": "අරත්ත, දියමිත්ත, අරළු, ගප්පිප්පිලි", "category": "plant" },
    { "word": "ශ්‍රෙෂ්ඨ", "meaning": "ජීවක, අමුකසා", "category": "plant" },
    { "word": "ශ්‍රෙෂ්ඨා", "meaning": "නිපල් (අරළු, බුළු, නෙල්ලි)", "category": "plant" },
    { "word": "ශ්‍රෙෂ්ඨාම්ල", "meaning": "සියඹලා", "category": "plant" },
    { "word": "ශ්‍රෙෂ්ඨ්‍ය", "meaning": "සවිඳව ලුණු", "category": "mineral" },
    { "word": "ශ්‍රෙෂ්ඨගන්ධ", "meaning": "සඳුන්", "category": "plant" },
    { "word": "ශ්‍රෙෂ්ඨමූලිකා", "meaning": "මැණික්වැන්න", "category": "plant" },
    { "word": "ශ්‍රෙෂ්ඨා (2)", "meaning": "අරළු, නිප්පිලි, මැණික්වැන්න, බැමිතිරිය, සින්දුමැඬ", "category": "plant" },
    { "word": "ශ්‍රෙෂ්ඨොදක", "meaning": "හාල් දෙවුන් දිය", "category": "liquid" },
    { "word": "ශ්‍රොණ", "meaning": "පියුම් මිණි", "category": "mineral" },
    { "word": "ශ්‍රොණාරත්නක", "meaning": "පියුම්රාමිණි", "category": "mineral" },
    { "word": "ශ්ලක්‍ෂණත්චච", "meaning": "පොල්පලා", "category": "plant" },
    { "word": "ශ්ලීපද", "meaning": "බරපා (බරවා) රෝගය", "category": "treatment" },
    { "word": "ශ්ලීපදප්‍රභව", "meaning": "අඹ ගස", "category": "plant" },
    { "word": "ශ්ලීපදපහා", "meaning": "බුත්සරණ", "category": "plant" },
    { "word": "ශ්ලෙෂ්ම", "meaning": "සෙම", "category": "anatomy" },
    { "word": "ශ්ලෙෂ්මික", "meaning": "කිරිපළු ගස", "category": "plant" },
    { "word": "ශ්ලෙෂ්මීස්නා", "meaning": "බෝලිද්ද, වැටකේ, ඝුඳ", "category": "plant" },
    { "word": "ශ්ලෙෂ්මඵල", "meaning": "ලෝලු ගස", "category": "plant" },
    { "word": "ශ්ලෙෂ්මඝ", "meaning": "ඇත්දෙමට", "category": "plant" },
    { "word": "ශ්ලෙෂ්මාත / ශ්ලෙෂ්මාතක", "meaning": "ලෝලුගස", "category": "plant" },
    { "word": "ශ්වදංෂ්ට්‍රක / ශ්වදංෂ්ට්‍රා", "meaning": "ගොකටු", "category": "plant" },
    { "word": "ශ්වපුල", "meaning": "දෙළුම් ගස", "category": "plant" },
    { "word": "ශ්වථු", "meaning": "ඉදිමුම", "category": "treatment" },
    { "word": "ශ්වයොති", "meaning": "රක්අත්තන", "category": "plant" },
    { "word": "ශ්වර්හ", "meaning": "කොබලීල", "category": "plant" },
    { "word": "ශ්වසන", "meaning": "කුකුරුමාන්", "category": "plant" },
    { "word": "ශ්වසනෙත්තර", "meaning": "මුදි ගස, කුඹුක්", "category": "plant" },
    { "word": "ශ්වාබුබකා", "meaning": "කිරිපළු", "category": "plant" },
    { "word": "ශ්වාස", "meaning": "කාශ රෝගයක්", "category": "treatment" },
    { "word": "ශ්වාහාරී", "meaning": "තෙලම් අල", "category": "plant" },
    { "word": "ශ්විත්‍ර", "meaning": "සෙවතකුෂ්ට (සුදු කබර)", "category": "treatment" },
    { "word": "ශ්වෙත", "meaning": "ලුණුවරණ, කවඩි, සක්, සුදු මිණිරන්, සුදුදුරු, රිදී", "category": "plant" },
    { "word": "ශ්වෙතකණටකාරී", "meaning": "සුදුකටුවැල්බටු", "category": "plant" },
    { "word": "ශ්වෙතකත්‍ය", "meaning": "අතිවිඩයන්", "category": "plant" },
    { "word": "ශ්වෙතකුබෙරාක්‍ෂි", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "ශ්වෙතකුම්භී", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "ශ්වෙතකුෂ්ඨ", "meaning": "සුදු කබර", "category": "treatment" },
    { "word": "ශ්වෙත කුසුම", "meaning": "නික ගස", "category": "plant" },
    { "word": "ශ්වෙතකෙශ", "meaning": "රත් මුරුංගා", "category": "plant" },
    { "word": "ශ්වෙත ගුඤ්ජා", "meaning": "සුදු ඔලිඳ", "category": "plant" },
    { "word": "ශ්වෙත ජීරක", "meaning": "සුදුදුරු", "category": "plant" },
    { "word": "ශ්වෙතතෙල්", "meaning": "සිනිත් එන්සාල්", "category": "plant" },
    { "word": "ශ්වෙත දණ්ඩා", "meaning": "එළ රතණ", "category": "plant" },
    { "word": "ශ්වෙත දූවා", "meaning": "සුදු රතණ", "category": "plant" },
    { "word": "ශ්වෙතධාමන්", "meaning": "කපුරු, මුදුපෙණ", "category": "mineral" },
    { "word": "ශ්වෙත පණ්ණා", "meaning": "සුදු තලා", "category": "plant" },
    { "word": "ශ්වෙත පාටල", "meaning": "හෙළ පලොල්", "category": "plant" },
    { "word": "ශ්වෙත පිණ්ඩීතක", "meaning": "මහ කුකුරුමාන්", "category": "plant" },
    { "word": "ශ්වෙත පුෂ්ප", "meaning": "හෙළ නික, සුදු කණේරු, දත්ත, වැටකොළු, නියඹරා", "category": "plant" },
    { "word": "ශ්වෙත පුෂ්පා", "meaning": "සුදු කටරොළු, මහ ගොන් සුදු කැකිරි, කණේරු, ශ්වෙතචලෙරොහා-හෙළ පලොල්, ශ්වෙතහණඬා-සුදු රතණ", "category": "plant" },

    // --- පිටුව 467 ---
    { "word": "ශ්වෙතමස්තු", "meaning": "කිරිමෝරු", "category": "liquid" },
    { "word": "ශ්වෙතමන්දාර", "meaning": "යක් එරබදු", "category": "plant" },
    { "word": "ශ්වෙතමාරිච", "meaning": "සුදු මිරිස්, වල් මුරුංගා", "category": "plant" },
    { "word": "ශ්වෙත මූලා", "meaning": "මහ සාරණ", "category": "plant" },
    { "word": "ශ්වෙත වචා", "meaning": "අතිවිඩයන්", "category": "plant" },
    { "word": "ශ්වෙත වල්කල", "meaning": "දිවුල් ගස", "category": "plant" },
    { "word": "ශ්වෙත වාසර", "meaning": "උක් ගස", "category": "plant" },
    { "word": "ශ්වෙත විසා", "meaning": "අතිවිඩයන්", "category": "plant" },
    { "word": "ශ්වෙත වෘක්‍ෂ", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "ශ්වෙතව්‍යාඝ්‍රී", "meaning": "හීන් සුදු කටුවැල් බටු", "category": "plant" },
    { "word": "ශ්වෙතව්‍යාඝ්‍රිකා", "meaning": "හෙළ බටු", "category": "plant" },
    { "word": "ශ්වෙතශංඛපුෂ්පී", "meaning": "සුදු කටරොළු", "category": "plant" },
    { "word": "ශ්වෙත ශුරණ", "meaning": "වල් කිඩාරම්", "category": "plant" },
    { "word": "ශ්වෙතස්ඵන්ද", "meaning": "එළ රතණ", "category": "plant" },
    { "word": "ශ්වෙතසර්ෂප", "meaning": "හෙළ අබ", "category": "plant" },
    { "word": "ශ්වෙතසාර", "meaning": "එළ කිහිරි", "category": "plant" },
    { "word": "ශ්වෙතසිඳුවාර", "meaning": "සුදු ජයම්", "category": "plant" },
    { "word": "ශ්වෙතසුරසා", "meaning": "එළ සේපාලිකා", "category": "plant" },
    { "word": "ශ්වෙතසූරණ", "meaning": "වල් කිඩාරම්", "category": "plant" },
    { "word": "ශ්වෙතා", "meaning": "කවඩි, අඩතහිරියා, අතිවිඩයන්, මුවකිරිය, එළ රතණ, එළ කටුවැල් බටු, පොල්පලා, උණකපුරු, සීනි", "category": "plant" },
    { "word": "ශ්වෙතාකී", "meaning": "එළ වරා", "category": "plant" },
    { "word": "ශ්වෙතෙක්‍ෂු", "meaning": "එළ උක්", "category": "plant" },
    { "word": "ශ්වෙතෙලා", "meaning": "හීන් එන්සාල්, කරඳමුංගු", "category": "plant" },
    { "word": "අෂ්ටකඩුක", "meaning": "සිවිය, රත්නිටුල්, නිප්පිලි මුල්, ඉඟුරු, මිරිස්, තිප්පිලි යන කුළු සය වග", "category": "compound" },
    { "word": "අෂ්ටකෝණ", "meaning": "දියමන්ති", "category": "mineral" },
    { "word": "අෂ්ටග්‍රන්ථි", "meaning": "මඟුල්කරඳ, වද", "category": "plant" },
    { "word": "ෂට්ග්‍රන්ථි", "meaning": "තිප්පිලි මුල්, වදකහ", "category": "plant" },
    { "word": "ෂට්ග්‍රන්ථි (2)", "meaning": "කුණු කරඳ", "category": "plant" },
    { "word": "ෂට්පදි", "meaning": "මීමැස්සෝ, බමරු", "category": "animal" },
    { "word": "ෂට්පදප්‍රිය", "meaning": "යොන්තුඹ, නාකෙසර", "category": "plant" },
    { "word": "ෂට්පදා තිථි", "meaning": "අඹ ගස", "category": "plant" },
    { "word": "ෂට්පදානන්දවර්ධන", "meaning": "හෝපළු ගස", "category": "plant" },
    { "word": "ෂට්පදාලය", "meaning": "දෙඹ ගස", "category": "plant" },
    { "word": "ෂට්පදෙෂ්ට", "meaning": "බක්මී, කොළොම්", "category": "plant" },
    { "word": "ෂට් රස", "meaning": "මිහිරි, ලුණු, තිත්ත, කසට, කටුක, ඇඹුල් යන රස සය වගය", "category": "general" },
    { "word": "ෂෂ්ටක", "meaning": "තුවරලා", "category": "plant" },
    { "word": "ෂඩග්‍රන්ථා", "meaning": "වද කසා, හරංකසා, හිඟුරුපියලි, මහ කරඳ", "category": "plant" },
    { "word": "ෂඩග්‍රන්ථි", "meaning": "හිඟුරු පියලි, වදකහ, තිප්පිලි මුල්", "category": "plant" },
    { "word": "ෂඩංග", "meaning": "හීන් ගොකටු පැළ", "category": "plant" },
    { "word": "ෂඩාෂ්මය", "meaning": "තුන්බෝ අත්තන", "category": "plant" },
    { "word": "ෂඩූෂණ", "meaning": "ඉඟුරු, ගම්මිරිස්, තිප්පිලි, තිප්පිලි මුල්, සිවිය, රත්නිටුල්", "category": "compound" },
    { "word": "ෂණ්ඩාකි", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "ෂල්ලිකීකොඩි", "meaning": "පණම්පෙති, කිඹුල්වැන්න", "category": "plant" },
    { "word": "ෂිල්ලිකාසි", "meaning": "පුස් ඇට", "category": "plant" },
    { "word": "ෂූරතාවරෙසි", "meaning": "සෙනෙහ කොළ", "category": "plant" },
    { "word": "ෂුරෙසි", "meaning": "එරමිණියා", "category": "plant" },
    { "word": "ෂෝන අවරෙසි", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "සංවර්ජිකා", "meaning": "නවසාරම්", "category": "mineral" },
    { "word": "සංවනික", "meaning": "බුලු ගස", "category": "plant" },
    { "word": "සංවරිණී", "meaning": "වළාවැන්න", "category": "plant" },
    { "word": "සංවිධාන", "meaning": "කංසා", "category": "plant" },
    { "word": "සංවිසා", "meaning": "අතිවිඩයන්", "category": "plant" },
    { "word": "සංශිත දුග්ධ", "meaning": "මී හරක්", "category": "animal" },

    // --- පිටුව 468 ---
    { "word": "සංස්ඵර්ශා", "meaning": "වටැස්ස", "category": "plant" },
    { "word": "සංහතපුෂ්පිකා", "meaning": "උළුවා", "category": "plant" },
    { "word": "සක්", "meaning": "සබ්බ (සක්බෙලි කටු)", "category": "animal" },
    { "word": "සක් ඇට", "meaning": "සක් කටු", "category": "animal" },
    { "word": "සක්කැබලි", "meaning": "සක්බෙලි කටු", "category": "animal" },
    { "word": "සකබරා", "meaning": "සකුරු", "category": "food" },
    { "word": "සකබරා උදක", "meaning": "හකුරු මුසු ජලය", "category": "liquid" },
    { "word": "සක්තුරග", "meaning": "වරා ගස", "category": "plant" },
    { "word": "සක්නැබ", "meaning": "සබ්බනාභි, (සක් බෙලි කටුවේ මැද පෙදෙස = මැද පුරුක. මේ වෙනුවට සම්පූර්ණ සක්බෙලි කටුව ම ඖෂධසඳහා ගන්නා නමුත් එය හරි නැත)", "category": "animal" },
    { "word": "සක්පුපල", "meaning": "ඉඟිනි ඇට", "category": "plant" },
    { 
        "word": "සක්මල්", 
        "scientific": "Canscora Decussata",
        "meaning": "ශඞ්ඛපුෂ්පී.<br><br>සක් ගෙඩියකට සමාන සුදු පාට කුඩා මල් හා අඟල් 1 x 1/2 ක් පමණ දිග - පළල කොළ ඇති දිය සිරාව සහිත තෙත් බිම් වල වැවෙන ගිරාපලා වලට මඳක් සමාන පැළෑටියකි.<br><br>සක්මල් අපස්මාර (මීමස්මොර = වස් මර), මානසික රෝග, කුෂ්ට රෝග, සප්ත විධ අණ්ඩවෘද්ධි හා දිවිමකුළු විෂ ඇතුළු විෂ ශරීර ගත වීමෙන් හටගන්නා ආබාධ නසන, ධාරණ ශක්තිය දියුණු කරන ප්‍රධාන පංචාංගයේ විරේක ඖෂධයකි.<br><br>මේ පැළෑටියේ සම්පූර්ණ හැඩහුරු කම් හා ඖෂධ ශක්තියත් සසඳා බලන විට මෙය විලඳවැන්න පවුලට අයත් පැළෑටියක් බැව් පෙනේ. එසේ ම ශඞ්ඛපුෂ්පී (සක්මල්) විලඳවැන්න ම යයි ස්ථිර නිගමනයකට බැස ශඞ්ඛ පුෂ්පී වශයෙන් විලඳවැන්න ම ඖෂධ වලට ගන්නා ප්‍රසිද්ධ වෛද්‍ය පරම්පරා ද ලක් දිව තිබේ.<br><br>අඬනහිරියා - වැල් දොහි - හිඟුරු පියලි යන මේ වර්ග සක්මල් ලෙස ගැනීම හරි නැත.", 
        "category": "plant",
        "image": "img_canscora_decussata_sakmal.jpg"
    },
    { "word": "සක්ලොහ", "meaning": "මහදත්ත", "category": "plant" },
    { "word": "සක්වසන", "meaning": "නුග ගස", "category": "plant" },
    { "word": "සක්‍ෂීර", "meaning": "කිරිකවෙළු", "category": "plant" },
    { "word": "සකුසද / සක්සෝද", "meaning": "සප්සඳ = (සප්සඳ) සර්පවිෂට ප්‍රත්‍යක්‍ෂ බෙහෙතකි. බාලයන්ගේ පණුගායට ද එසේම හොඳ ය. (472 පිට බලන්න)", "category": "plant" },
    { "word": "සකාන්තලා", "meaning": "කෙහෙල් ගස", "category": "plant" },

    // --- පිටුව 469 ---
    { "word": "සකට", "meaning": "දූමැබ", "category": "plant" },
    { "word": "සකටලොචන", "meaning": "ගුගුල්", "category": "plant" },
    { "word": "සකණීටක", "meaning": "පෙද", "category": "plant" },
    { "word": "සකඳ", "meaning": "කිකිරිදිය", "category": "plant" },
    { "word": "සකඳුරු", "meaning": "ඉඳිගස", "category": "plant" },
    { "word": "සකන", "meaning": "මුතුබෙල්ලා", "category": "animal" },
    { "word": "සකර", "meaning": "සීනි", "category": "food" },
    { "word": "සකල", "meaning": "කුරුඳුපොතු", "category": "plant" },
    { "word": "සකලාක්‍ෂ", "meaning": "දාවගස", "category": "plant" },
    { "word": "සකුණ", "meaning": "එළ නික", "category": "plant" },
    { "word": "සකුරු", "meaning": "කිතුල්හකුරු", "category": "food" },
    { "word": "සකුරුපූ", "meaning": "හකුරුආප්ප", "category": "food" },
    { "word": "සකුල", "meaning": "කුවරණ", "category": "plant" },
    { "word": "සකුලාක්‍ෂක", "meaning": "කලාඳුරු", "category": "plant" },
    { "word": "සකුලාදනී", "meaning": "කටුකරෝහිණි", "category": "plant" },
    { "word": "සකුලාදිනී", "meaning": "ලියනඟලා", "category": "plant" },
    { "word": "සකොදන", "meaning": "තලිස්පතුරු", "category": "plant" },
    { "word": "සඛි", "meaning": "අරළු, කටුකරඬු, මුහුණුවැන්න", "category": "plant" },
    { "word": "සගන්ධික", "meaning": "කරපිංචා", "category": "plant" },
    { "word": "සඞ්කටාක්‍ෂ", "meaning": "දාවගස", "category": "plant" },
    { "word": "සඞ්කාරු", "meaning": "පින්තල", "category": "plant" },
    { "word": "සඞ්කි", "meaning": "මස්", "category": "animal" },
    { "word": "සඞ්කොච", "meaning": "කොකුම්මල්", "category": "plant" },
    { "word": "සඞ්කොචනී", "meaning": "නිදිකුම්බා", "category": "plant" },
    { "word": "සඞ්ඛපුෂ්පී", "meaning": "සක්මල්", "category": "plant" },
    { "word": "සඞ්ඛමුක්තා", "meaning": "සක්මුතු, (මුතු බෙල්ලන්ගේ මුතු)", "category": "animal" },
    { "word": "සඞ්ඛිනී", "meaning": "වැල්දෙහි, යක්බේරිය, සක්මල්", "category": "plant" },
    { "word": "සඞ්ඛොණ්ඩී", "meaning": "හෙළ නික", "category": "plant" },
    { "word": "සඞ්ගමුලි", "meaning": "මුඩමහණ", "category": "plant" },
    { "word": "සඞ්ගර", "meaning": "සැමගස", "category": "plant" },
    { "word": "සඞ්ගගෙය්‍ය", "meaning": "ගෙන්දගම්", "category": "mineral" },
    { "word": "සඞ්ග්‍රාහීන්", "meaning": "කෙළිඳ ගස", "category": "plant" },
    { "word": "සඞ්ඝපුෂ්පී", "meaning": "සක්මල්", "category": "plant" },
    { "word": "සඞ්ඝාතපත්‍රිකා", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "සචීන", "meaning": "ලුණුවරණ", "category": "plant" },
    { "word": "සචීව", "meaning": "කම් අත්තන", "category": "plant" },
    { "word": "සජෙන්‍රට", "meaning": "අඹ", "category": "plant" },
    { "word": "සර්ජ්‍ය", "meaning": "සල්", "category": "plant" },
    { "word": "සර්ජ්‍යා", "meaning": "දුම්මැල්ල", "category": "plant" },
    { "word": "සර්ජු", "meaning": "දුම්මල", "category": "plant" },
    { "word": "සර්ඣු", "meaning": "රිදී", "category": "mineral" },
    { "word": "සර්ජරස", "meaning": "දුම්මල, සල්මැළියම්", "category": "plant" },
    { "word": "සර්ජාබා", "meaning": "දුම්මල", "category": "plant" },
    { "word": "සර්ජුරස", "meaning": "සල්දුම්මල", "category": "plant" },
    { "word": "සජොවනතක", "meaning": "ඇන්තෝර", "category": "plant" },
    { "word": "සඤ්චාරා", "meaning": "කහ", "category": "plant" },
    { "word": "සඤ්චාලි", "meaning": "ඕලිඳ", "category": "plant" },
    { "word": "සඤ්ජීකා", "meaning": "කාද්‍ර, කාඩි", "category": "liquid" },
    { "word": "සඤ්ජීව", "meaning": "කිරි", "category": "liquid" },
    { "word": "සටාළු", "meaning": "බෙලිපත, (බෙලි කොළ)", "category": "plant" },
    { "word": "සඩිලෝ", "meaning": "යක්වනසු (යකුටනස්ස)", "category": "plant" },
    { "word": "සණ්ඩිති", "meaning": "ගිරිතිල්ල, කිරිහඬුළු", "category": "plant" },
    { "word": "සණ්ඩාකි", "meaning": "ගිරිතිල්ල", "category": "plant" },
    { "word": "සණස්", "meaning": "ඇසතු", "category": "plant" },
    { "word": "සත්දාකාර විෂ", "meaning": "දෂ්ට, ස්පෘෂ්ට, දෘෂ්ටි, අසිත, පීත, බාසිත, සාසිත යන සප්තවිධ විෂ.", "category": "general" },
    { "word": "සත්කට", "meaning": "උගුරුස්ස", "category": "plant" },
    { "word": "සත්තාස", "meaning": "ඇසතු, බෝගස", "category": "plant" },
    { "word": "සත්තපර්ණී", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "සත්කලා", "meaning": "සත් පෙති දා සමන්", "category": "plant" },
    { "word": "සත්තුරඟ", "meaning": "වරාගස", "category": "plant" },
    { "word": "සත්‍රී", "meaning": "කලුව", "category": "plant" },
    { "word": "සත්‍ථවර්ණා", "meaning": "රත්රන්", "category": "mineral" },
    { "word": "සත්දල", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "සත්පත්", "meaning": "රුක්අත්තන", "category": "plant" },
    { "word": "සත්ඵල", "meaning": "දෙළුම්", "category": "plant" },
    { "word": "සක්මැලී", "meaning": "ඉඹුල් මැලියම්", "category": "plant" },
    { "word": "සත්මූලි", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "සත්සාර", "meaning": "කයිප්පු", "category": "plant" },
    { "word": "සත්‍යනාමා", "meaning": "මකුණුවැන්න", "category": "plant" },
    { "word": "සත්‍යඵල", "meaning": "බෙලි", "category": "plant" },
    { "word": "සත්‍යාහ්ව", "meaning": "බැමිතිරිය", "category": "plant" },

    // --- පිටුව 470 ---
    { "word": "සත", "meaning": "ශතපුෂ්ප", "category": "plant" },
    { "word": "සතකුප්ප", "meaning": "යහවපු(ශතපුෂ්ප)", "category": "plant" },
    { "word": "සතග්නි", "meaning": "මුඛරෝගයක්", "category": "treatment" },
    { "word": "සතච්ඡද", "meaning": "කවණික", "category": "plant" },
    { "word": "සතනය", "meaning": "තනකිරි", "category": "liquid" },
    { "word": "සතපත්‍ර", "meaning": "නෙළුම්, කළුතලා", "category": "plant" },
    { "word": "සතපදී", "meaning": "මඟකපු", "category": "plant" },
    { "word": "සතපත්‍රිකා", "meaning": "රතණ, වදකහ", "category": "plant" },
    { "word": "සතපුෂ්පිකා", "meaning": "රත්හඳුන්", "category": "plant" },
    { "word": "සතප්‍රාසය", "meaning": "අලරිය", "category": "plant" },
    { "word": "සතභෙද", "meaning": "පෙරුම්කායම්", "category": "plant" },
    { "word": "සතමල", "meaning": "ඇඹුල", "category": "plant" },
    { "word": "සතමූලා", "meaning": "බින්තල්, සාතාවාරිය", "category": "plant" },
    { "word": "සතමූලිකා", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "සතමූලි", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "සතරහුල්", "meaning": "ඇසළ", "category": "plant" },
    { "word": "සතරහ", "meaning": "සප්තපර්ණී වෘක්‍ෂය", "category": "plant" },
    { "word": "සතරැඹු", "meaning": "මී, දඬුවැල්(බැ), බමර, කණවෙයියා පැණි", "category": "liquid" },
    { 
        "word": "සතරමහා විකට", 
        "meaning": "මල, මුත්‍ර, අළු, මැටි, (සර්පයන් දෂ්ට කළ විට මේ සතර වර්ගය ගෙන ඇල් දියෙන් දියකර පානය කිරීමෙන් විෂ බැස යනවා ඇත මෙය නාගයකු විසින් දෂ්ට කරන ලද භික්‍ෂූන් වහන්සේ නමකට බුදුරජාණන් වහන්සේ විසින් නියමකරන ලද බෙහෙතකි. (විනය පිටක - මහා වග්ග පාලි - 202. පිටුව)", 
        "category": "treatment" 
    },
    { "word": "සතායු", "meaning": "සාතාවාරිය", "category": "plant" },
    { "word": "සතාවරී", "meaning": "සාතාවාරිය, කටුකරෝහිණී", "category": "plant" },
    { "word": "සතිකතක", "meaning": "කොසඹ", "category": "plant" },
    { "word": "සතිකාක", "meaning": "කොසඹ", "category": "plant" },
    { "word": "සතිතප්තවිකා", "meaning": "විෂ්ණුක්‍රාන්ති", "category": "plant" },
    { "word": "සතිසක්කෝ", "meaning": "කෙළිඳ", "category": "plant" },
    { "word": "සතුරාතෙල්", "meaning": "එරඬුතෙල්", "category": "liquid" },
    { "word": "සතුරාසම්මුට්ට", "meaning": "කරඬ්ඨානෙයි= සිහින් දිග කොළ සහිත සර්ප විෂට ගන්නා පැළෑටියක් (සමැටි=හංමැටි=සම්මුට්ට)", "category": "plant" },
    { "word": "සද්දලො", "meaning": "රතණ", "category": "plant" },
    { "word": "සද්‍යඃශොථා", "meaning": "වඳුරු මෑ", "category": "plant" },
    { "word": "සද්‍යොගයොනි", "meaning": "ගල්සෙවෙල්", "category": "mineral" },
    { "word": "සද", "meaning": "සැවැන්දරා", "category": "plant" },
    { "word": "සදක", "meaning": "හාල්", "category": "plant" },
    { "word": "සදකාම්මිනී", "meaning": "දියතරිප්පු (චන්ද්‍රකාන්ත පාෂාණ)", "category": "mineral" },
    { "word": "සදන", "meaning": "රසකිඳ", "category": "plant" },
    { "word": "සදරාජ", "meaning": "හැඩහුරුකමින් ඉරරාජ වලට සමාන සුදු පාට රේඛා වලින් යුත් පැළෑටියක්. (47 පිටේ ඉරරාජ ගුණ ලියා ඇති විස්තරය බලන්න)", "category": "plant" },
    { "word": "සදවිහග", "meaning": "කොකුම්", "category": "plant" },
    { "word": "සදයා", "meaning": "ගොකටු", "category": "plant" },
    { "word": "සඳහොපා", "meaning": "එන්සාල් කොළ", "category": "plant" },
    { "word": "සඳපුෂ්ප", "meaning": "රතු වරා ගස, කොඳ, පොල්ගස", "category": "plant" },
    { "word": "සඳපුෂ්පඵල", "meaning": "බෙලිගස", "category": "plant" },
    { "word": "සඳපුෂ්පා", "meaning": "පුස්සමින්", "category": "plant" },
    { "word": "සඳපුෂ්පී", "meaning": "රතු වරා ගස, පොල්ගස", "category": "plant" },
    { "word": "සඳප්‍රසූත", "meaning": "එරබදු ගස, වරාගස, කොඳවැල", "category": "plant" },
    { "word": "සඳඵල", "meaning": "පොල්ගස, බෙලිගස, දිවුල් ගස, පිටවක්කා", "category": "plant" },
    { "word": "සඳභද්‍රා", "meaning": "පුස්සමින්, ඇත්දෙමට", "category": "plant" },
    { "word": "සඳවගහ", "meaning": "තිබ්බටු ගෙඩි", "category": "plant" },
    { "word": "සඳසන්", "meaning": "ඉරිවේරිය", "category": "plant" },
    { "word": "සඳිවහීත", "meaning": "බෙලි", "category": "plant" },
    { "word": "සඳුන්", "meaning": "හඳුන්", "category": "plant" },
    { "word": "සඳුන්කල්ක", "meaning": "චන්දන කල්කය", "category": "plant" },
    { "word": "සදුල්", "meaning": "ගිතෙල්, දිවියා", "category": "liquid" }
];



